### PR TITLE
Stabilize inclusive range (`..=`)

### PR DESCRIPTION
**Pull request by kennytm**
Stabilize the followings:

* `inclusive_range` — The `std::ops::RangeInclusive` and `std::ops::RangeInclusiveTo` types, except its fields (tracked by #49022 separately).
* `inclusive_range_syntax` — The `a..=b` and `..=b` expression syntax
* `dotdoteq_in_patterns` — Using `a..=b` in a pattern

cc #28237 
r? @rust-lang/lang

### CODE REVIEW

**Comment by kennytm** [comment]
`dotdoteq_in_patterns` is included because the corresponding documentation PRs already mentioned it... If it turns out to be too early to stabilize I can take it out.

**Comment by leonardo-m** [comment]
See also: https://github.com/rust-lang/rust/issues/45222

**Comment by kennytm** [comment]
@leonardo-m The performance fix can be done independently from the stabilization I believe.

**Comment by bluss** [comment]
Performance might depend on the data fields available, stabilizing public fields in the range inclusive iterator is restricting possibilities (to be factual).

Having them not be iterators (but iterable) is an alternative, but the drawbacks of that are pretty clear from the original https://github.com/rust-lang/rfcs/pull/1192, so it is  not a good idea.

**Comment by nikomatsakis** [comment]
The only way that it might be relevant is if we decided to change so that `..=` doesn't implement `Iterator` but only `IntoIterator`. I've historically been mega-opposed, on the grounds that `..` and `..=` should behave as similarly as possible, but if that's truly needed for perf or something that might be persuasive... (I've no idea if that is part of #45222 or what)

**Comment by nrc** [comment]
I think we need documentation before we can stabilise things nowadays, and according to the tracking issue we don't have any of that.

**Comment by kennytm** [comment]
@nrc:

* Book: https://github.com/rust-lang/book/pull/1134
* Reference: https://github.com/rust-lang-nursery/reference/pull/215
* RBE: https://github.com/rust-lang/rust-by-example/pull/1015

The book and reference say they want to wait until stabilization, so are we entering deadlock 😂.

**Comment by steveklabnik** [comment]
> The book and reference say they want to wait until stabilization, so are we entering deadlock 😂.

Usually, the book and reference need a PR *open*, and then the stuff gets stabilized, and then they get merged.

**Comment by nrc** [comment]
@bors: r+

Thanks for the links!

**Comment by kennytm** [comment]
Fixed merge conflict. 

Should this need any FCP? #28237 didn't go through a stabilization FCP yet.

**Comment by kdy1** [comment]
Inclusive range syntax causes panic when it's passed to attribute proc macro  (actually an ICE, but rustc lies)

 https://github.com/alexcrichton/futures-await/issues/55

**Comment by kennytm** [comment]
@kdy1 This issue has been filed as #47950.

**Comment by nikomatsakis** [comment]
I would be in favor of stabilizing, but I think we *do* need an FCP. 

@kennytm if you want to push this through, do you think you could write up a summary comment on the tracking issue #28237 ? In particular, I would like to see:

- Major features we expect to work, and the tests that we have for those in the code base
- Pointers to the docs (at least pending)
- Anything else that seems relevant

The idea is that people with minimal context should be able to quickly see what is being stabilized. It  is not meant to rehash every argument (in particular, I don't think we have to go into the tortured history of choosing a particular sigil here).

**Comment by kennytm** [comment]
@nikomatsakis Done https://github.com/rust-lang/rust/issues/28237#issuecomment-363374130.

**Comment by shepmaster** [comment]
For clarity, this is blocked on #28237 being approved.

**Comment by durka** [comment]
Are there companion PRs to update docs and books?

**Comment by petrochenkov** [comment]
Operator priority issue: https://github.com/rust-lang/rust/issues/48501

**Comment by kennytm** [comment]
FCP for #28237 has ended with one concern (precedence of `&0..=10` in pattern), and this PR is now blocked by #48500 solving this.

**Comment by kennytm** [comment]
#48500 has been merged, I'll fix the conflict and add a check to disallow the pattern `&0..=10` tonight.

**Comment by kennytm** [comment]
@petrochenkov I've added c11d2ebb4b986a2766c36861821d3cc5e7dad6a5 which will disallow parsing of `&a..=b`, `&mut a..=b` and `box a..=b` in a pattern. It will directly suggest replacing with `(a..=b)`, assuming [`pattern_parentheses` will be stabilized very soon](https://github.com/rust-lang/rust/issues/28237#issuecomment-368968680).

r? @nrc again

**Comment by petrochenkov** [comment]
This PR stabilizes internal representation of `RangeInclusive`, I don't think we should do this.
I'd rather keep the fields private and add public getters, or at least leave stabilization of the fields for later.

**Comment by petrochenkov** [comment]
`ident @ START ..= END` is somewhat questionable too, could you add the "no range" restriction to `parse_pat_ident` as well, at least for now?

To elaborate, if (when!) `|` becomes a part of pattern syntax we'll have to keep backward compatibility and parse `ident @ PAT1 | PAT2` as `(ident @ PAT1) | (PAT2)`, i.e. the binary operator `|` has lower priority than "unary operator" `ident @`, so maybe binary operator `..=` should have lower priority as well.

**Comment by petrochenkov** [comment]
Beside these two concerns everything looks good, r=me after addressing.

**Comment by kennytm** [comment]
> `ident @ START ..= END` is somewhat questionable too ... the binary operator `|` has lower priority than "unary operator" `ident @`, so maybe binary operator `..=` should have lower priority as well.

I disagree, `&a..=b` and `box a..=b` worth the error not because of it being a unary operator, but because it has different precedence than its expression counterpart. Besides, `@` looks pretty binary to me 🙂 

We could add a lint but I don't think it should be an error. cc @rust-lang/lang.

**Comment by kennytm** [comment]
> This PR stabilizes internal representation of `RangeInclusive`, I don't think we should do this.

Keeping the fields unstable has been discussed before.

* For unstable: https://github.com/rust-lang/rust/issues/28237#issuecomment-363393750 (no need to expose fields directly)
* For unstable: https://github.com/rust-lang/rust/pull/47813#issuecomment-361098802 (stabilizing restricts optimization possibilities)
* For stable: https://github.com/rust-lang/rust/issues/28237#issuecomment-363502299 (Range and RangeInclusive should have same capabilities)
* For stable: https://github.com/rust-lang/rust/issues/28237#issuecomment-363682897 ("well, it turns out internal iteration is just faster sometimes")
* For stable (?): https://github.com/rust-lang/rust/issues/45222#issuecomment-363184033 (unfortunate consequence because `Range`'s fields are public)

I don't think we want to keep the fields unstable, the design space has been pretty much explored very thoroughly (rust-lang/rfcs#1192 and rust-lang/rfcs#1980). The only viable options are:

1. Stabilize these fields as public, or

2. Make these fields private, change the internal representation to something allowing high performance, and provide some public, insta-stable access methods.
    * Note that there will be method name conflict with `RangeArguments`
    * If this is chosen, what about `RangeInclusiveTo`?
    * Should setters (`set_start`, `set_end`) be provided?

cc @rust-lang/libs

**Comment by alexcrichton** [comment]
Given that `RangeInclusive` basically exactly matches `Range` in terms of design (which is already stable) I'd be fine stabilizing the structure of the structs here.

**Comment by joshtriplett** [comment]
I think it's critically important that we have a representation that allows just as much performance as an exclusive range. People shouldn't have that as a performance pitfall waiting to happen. If that requires making the fields unstable, that seems fine to me.

**Comment by durka** [comment]
I agree. I don't fully understand the performance issue, but if keeping the
representation as it is now makes it *impossible* to provide the same
performance between a..(b+1) and a..=b, then I think that needs to change.
A big part of the motivation for adding inclusive ranges is we want to tell
people to change 0..(10+1) or (0..256u16).map(|x| x as u8) to a..=b,
because it looks better, but if that makes things *slower* then it's a
trap. That's not a zero-cost abstraction.

**Comment by kennytm** [comment]
@petrochenkov 

The unstable field thing is reasonable, but if the field is unstable but the struct is stable, we ought to provide accessor methods, and these methods need to be insta-stable. Then we have to decide on the names (`.start()` and `.end()` *may* conflict with `RangeArguments`), whether we add these methods to `Range`, whether we keep the field of `RangeIncludeTo` unstable/private. I don't see anyway we could avoid these unless we dictate on all these decisions (yes/yes/yes) 😜.

I don't see any point rejecting `ident @ START..=END`. If the cause is generalizing `|`, it should be a blocker of that feature, not here.

**Comment by alercah** [comment]
Can someone explain what the actual performance issue is? I understand why the range is set to (1,0) after iteration, but my read is that this shouldn't involve an extra comparison compared to `Range`. Where am I wrong?

**Comment by kennytm** [comment]
@alercah You may see #45222, which shows an example where `for i in a..(b+1)` is much faster than `for i in a..=b` because LLVM can't vectorize the latter.

**Comment by alercah** [comment]
Thanks!

My sense then would be that there's no need to stabilize methods to access start and end. Stabilizing the trait impls without giving stable access to the range is still an improvement, and it's rare enough to work with range type fields directly. Such methods would also be an indelible wart on the API.

**Comment by durka** [comment]
Indeed, you can get `start` from `range.next()` and `end` from `range.next_back()`. To "set" them you can just construct a new range using the literal syntax.

**Comment by kennytm** [comment]
@bors retry #43283

```
[01:33:27] test sync::mpsc::tests::stress_recv_timeout_two_threads ... ok
[01:33:31] test collections::hash::map::test_map::test_lots_of_insertions ... ok
[01:33:53] test process::tests::test_process_output_fail_to_start ... test process::tests::test_process_output_fail_to_start has been running for over 60 seconds


No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by jadbox** [comment]
is there docs for this?

**Comment by shepmaster** [comment]
@jadbox do you mean like https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html ? Those have been around for a while now.

**Comment by banister** [comment]
why didn't you guys just use the ruby syntax for this? this syntax looks wacky af.

**Pull request merged**
