### PR TITLE
update ICU4X to 1.1.0

### PR DESCRIPTION
**Pull request by lukas-code**
This patch updates the ICU4X crates to version 1.1.0 and regenerates the static data for `rustc_baked_icu_data`.

This is mostly an internal and bugfix update. It notably includes https://github.com/unicode-org/icu4x/pull/2834 to fix the future compatibility warning for [`BYTE_SLICE_IN_PACKED_STRUCT_WITH_DERIVE`](https://github.com/rust-lang/rust/issues/107457).

[full changelog](https://github.com/unicode-org/icu4x/blob/icu%401.1.0/CHANGELOG.md)

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks for the PR, @lukas-code! Let's find a reviewer who knows about this part of the code.

r? @davidtwco

**Review by davidtwco — APPROVED** [review]

**Comment by Manishearth** [comment]
Ddi you manually patch the `pub` into `struct BakedDataProvider`? The way to do this moving forward is what we've done in https://github.com/rust-lang/rust/pull/108054, fwiw.

**Comment by lukas-code** [comment]
I just ran the command from [the docs](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_baked_icu_data/index.html) and didn't change the generated files.

```sh
cd compiler/rustc_baked_icu_data
rm -r src/data
icu4x-datagen -W --pretty --fingerprint --use-separate-crates --format mod -l en es fr it ja pt ru tr zh zh-Hans zh-Hant -k list/and@1 fallback/likelysubtags@1 fallback/parents@1 fallback/supplement/co@1 --cldr-tag latest --icuexport-tag latest -o src/data
```

`icu4x-datagen -Vv` is entirely unhelpful, but `cargo install --list` says I have v1.1.1 installed.

**Comment by Manishearth** [comment]
Ah, that's v1.1.1, I see. I was running v1.1.0

**Pull request merged**
