### PR TITLE
Include trailing comma in multiline Debug representation

### PR DESCRIPTION
**Pull request by dtolnay**
This PR changes the behavior of [`Formatter::debug_struct`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_struct), [`debug_tuple`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_tuple), [`debug_list`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_list), [`debug_set`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_set), and [`debug_map`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_map) to render trailing commas in `{:#?}` mode, which is the dominant style in modern Rust code.

#### Before:

```console
Language {
    name: "Rust",
    trailing_commas: false
}
```

#### After:

```console
Language {
    name: "Rust",
    trailing_commas: true,
}
```

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Is there any reason to do this, beyond being nicer from a formatting perspective?

@rustbot modify labels to relnotes.

**Comment by dtolnay** [comment]
I would say that's the only reason. I won't try to argue that this makes debugging easier. :wink: 

The current behavior of DebugStruct was designed before the code style for Rust had been as well established. You can see in [RFC 640](https://github.com/rust-lang/rfcs/blob/master/text/0640-debug-improvements.md) which proposed `{:#?}` there is this code fragment under *Motivation* without a trailing comma:

```rust
pub struct BufferedStream<S> {
    inner: BufferedReader<InternalBufferedWriter<S>>
}
```

I believe if the feature were being implemented from scratch today it would certainly be done with a trailing comma. This PR only closes the gap between the way it was built in 2015 and the way we would build it today.

**Comment by petrochenkov** [comment]
>Is there any reason to do this, beyond being nicer from a formatting perspective?

Code in `libcore/fmt` is simpler, for example.
Being friendly to code generators is one of the primary reasons why trailing separators are supported in general.

**Comment by Mark-Simulacrum** [comment]
I will make the note that this is likely to cause somewhat widespread test breakage in the community; I don't think that's a reason to not do this, but worth noting. We can run crater if we want to know ahead of time.

@bors try in case we decide to go ahead with a crater run

I presume we'll want an FCP for libs team? Let's try r? @Amanieu for the review

**Comment by Dylan-DPC** [comment]
ping from triage @Amanieu / @rust-lang/libs any updates?

**Comment by alexcrichton** [comment]
I would personally think that we can land this at any time (and should) but @Mark-Simulacrum do you feel that this definitely needs a crater run? I think I probably expect less breakage than you though

**Comment by Mark-Simulacrum** [comment]
Not at all; I expect breakage but probably just local (i.e., tests) and we're generally pretty free to break those. We'll (someone from the release team) probably just open an issue once next beta is cut with this in it and we get a crater run on that, we can assess breakage then. Seems fine to land for now though!

@bors r=alexcrichton (I also glanced through but tests and nothing seems obviously bad)

**Comment by xfix** [comment]
Well, it is a breaking change, and I saw code (although not in Rust) that parsed formatting output in order to get information that is otherwise unobtainable. However, while I can believe some Rust programmers did that, I would assume most were reasonable enough to use `{:?}` instead of `{:#?}` to avoid unnecessary whitespace.

**Comment by Centril** [comment]
Ping from triage, @dtolnay, you have some rebasing todo.

**Comment by dtolnay** [comment]
Rebased to fix conflict with #57847 in src/test/ui/rfc-2361-dbg-macro/dbg-macro-expected-behavior.rs.
Passed `./x.py test` locally.

@bors r=alexcrichton

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/59670#issuecomment-479633006, @bors r-

**Comment by dtolnay** [comment]
Working on it -- I submitted https://github.com/rust-lang/cargo/pull/6818 to fix the test case in Cargo, currently waiting on the Cargo update in rust-lang/rust: #59681.

**Comment by dtolnay** [comment]
Rebased on #59681 and tested again with `./x.py test`. Is there a more exhaustive test command that I could run locally that would run the test suites of whichever tools are tested in Travis?

@bors r=alexcrichton

**Pull request merged**
