### PR TITLE
Markdown cleanup

### PR DESCRIPTION
**Pull request by iangneal**
Fixed a couple of grammatical issues and tweaked line endings (most of the documents seem to be going for line length <= 80, so I tweaked a few things to match that).

### CODE REVIEW

**Comment by aturon** [comment]
Thanks!

@bors: r+

**Comment by aturon** [comment]
@bors: r-

Just noticed that there's a Travis failure that looks legit.

**Comment by Dahca** [comment]
Goofed on a line of markdown, everything seems to be okay now.

**Comment by Dahca** [comment]
I opted for the version of the configure script in #39770 without any of my own edits.

**Comment by frewsxcv** [comment]
Thanks! @bors r+ rollup

**Pull request closed without merging**
