### PR TITLE
Try building rustc with N codegen units

### PR DESCRIPTION
**Pull request by tmiasko**
r? @ghost

### CODE REVIEW

**Comment by tmiasko** [comment]
PR CI x86_64-gnu-llvm-9 took 77m (usually it takes ~40m).

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
The size of unpacked toolchain was also reduced from 404M to 354M (as installed by rustup-toolchain-install-master with default options).

Now with two codegen units (PR CI x86_64-gnu-llvm-9 took 63m).

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
Huge improvements of up to 15.5%.

**Comment by tmiasko** [comment]
With three codegen units (PR CI x86_64-gnu-llvm-9 took 44m).

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
Up to 13.8% improvements with a single 3.7% regression for rustdoc. There are no other regression.

**Comment by tmiasko** [comment]
With four codegen units (PR CI x86_64-gnu-llvm-9 took 39m).

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
Huge improvements of up to 7.1% with no regressions. Bootstrap takes 4% longer.

**Comment by tmiasko** [comment]
With five codegen units (PR CI x86_64-gnu-llvm-9 took 48m).

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
This was an experiment trying to improve the compiler performance by building rustc with reduced number of code generation units. The number of CGUs was fixed into bootstrap so that it would be picked up by the perf benchmarking. As a result rustc was bootstrapping a new rustc with exactly the same number of CGUs it was build with.

|Number of CGUs|Bootstrap timings|Toolchain size diff|Perf results|
|-:|-:|-:|:-|
|1|+86.7%|-50 MB|[link](https://perf.rust-lang.org/compare.html?start=a4cbb44ae2c80545db957763b502dc7f6ea22085&end=ad1e2edcc154dde638611f902f9e504f5a8d9c6f)
|2|+24.6%|-26 MB|[link](https://perf.rust-lang.org/compare.html?start=4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5&end=4c4da1d578ee027b619ce11c645e6de512d26927)
|3| +9.7%|-16 MB|[link](https://perf.rust-lang.org/compare.html?start=85e355ea9bd86ac6580a5d422a65dbf689845808&end=01e13b863b2b389489961bf7431b7a315264a43e)
|4| +4.1%|-11 MB|[link](https://perf.rust-lang.org/compare.html?start=9a9477fada5baf69d693e717d6df902e411a73d6&end=062903552d75442b4d81885a2e0bea22c40f3085)
|5| +1.5%| -8 MB|[link](https://perf.rust-lang.org/compare.html?start=7907345e58b4f4d2c95e5ea9b8e0b3bff8946523&end=13bf8a83fb1c9fd2bedf86550e521ef6310ab2a4)


r? @Mark-Simulacrum what would you say about reducing CGUs used when building rustc? (If I am understanding correctly, the bootstrap timings intentionally limit concurrency at cargo level, so build time increases might be overestimates still).

**Comment by Mark-Simulacrum** [comment]
I would like to better understand why there is a regression for a single CGU but not for two on a number of benchmarks - what went wrong? Please also provide the expected impact to CI times is for each of the above (at least for the dist-x86_64-linux builder, which should be visible in the try builds; just one build that is already done is sufficient IMO).

I don't think it's a good idea to switch this by default in local builds (there absolute performance is less important than the quick turnaround) but in CI it may make sense depending on the impact to build times.

**Comment by tmiasko** [comment]
I extended the table to include try build times from dist-x86_64-linux.

The configuration with 1 CGU with regressions on instruction counts does indeed stand out from others, although this is not reflected in other metrics (except in the case of match-stress-enum benchmark). I could try looking a bit more to try find out what is going on.

**Comment by Mark-Simulacrum** [comment]
It looks like the try builder is pretty variable (45min to 60 min) so it might be good to rerun try (without perf) at least 1-2 more times on each of these to try and get some sense of where things stand. Would you be up for doing that? I think if this is bumping by half an hour that'll be harder to justify than 10-15 minutes, but it is a 1-2% win on the largest crates, so I think 5-10 minutes would be pretty easy sell, at least on Linux.

It's worth noting that we already compile std with [just one codegen unit on CI](https://github.com/rust-lang/rust/blob/921ec4b3fca17cc777766c240038d7d50ba98e0d/src/ci/run.sh#L54). I think it'd be interesting to see the CI timing if we change the codegen units to only affect rustc itself (i.e., gate the effects of rust-codegen-units on `Mode::Rustc` [here](https://github.com/rust-lang/rust/blob/921ec4b3fca17cc777766c240038d7d50ba98e0d/src/bootstrap/builder.rs#L1425)); that'll help avoid blowing our CI budget on optimizing Cargo, RLS, etc. when they're not likely to be as important to eke out the last bit of performance from.

If you want to rerun the perf experiments again with the setting moved to the CI config (src/ci/run.sh, linked in previous paragraph as well), that would give us some sense of how the performance of the Rust compiler when compiling itself (but without throwing in a slowdown from doing so in a different number of CGUs).

I think it'd be good to look into the regressions from the 1 CGU case as they might point to something that affects all of them, say, we have some suboptimal path in the compiler or perhaps an LLVM bug; I would expect 1 CGU to be faster than two at runtime, if not at compile time.

**Comment by tmiasko** [comment]
The bootstrap code was modified that the number of CGUs for the `Mode::Rustc` is based on
`rust-codegen-units`, the `Mode::Std` is based on `rust-codegen-units-std`, and otherwise remains
unset. The `./src/ci/run.sh` sets `rust.codegen-units=N` in addition to already configured
`rust.codegen-units-std=1`.

With `rust.codegen-units=1` (PR CI x86_64-gnu-llvm-9 took 62 min):

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
With `rust.codegen-units=2` (PR CI x86_64-gnu-llvm-9 took 59 min):

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
With rust.codegen-units=3 (PR CI x86_64-gnu-llvm-9 took 44 min):

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
With rust.codegen-units=4 (PR CI x86_64-gnu-llvm-9 took 44 min):

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
With rust.codegen-units=5 (PR CI x86_64-gnu-llvm-9 took 42 min):

@bors try @rust-timer queue

**Comment by tmiasko** [comment]
The table updated with new measurements is in https://github.com/rust-lang/rust/pull/81214#issuecomment-775450908 

@Mark-Simulacrum what would be next steps? Is that sufficient to make a decision, or would you like me to repeat try builds once again?

**Comment by bjorn3** [comment]
I am curious what the effect of only building libstd with a single codegen unit would be.

**Comment by tmiasko** [comment]
The standard library is already built with a single codegen unit.

**Comment by Mark-Simulacrum** [comment]
I might be misunderstanding the table, but by my reading it looks like switching to bootstrapping with codegen units affecting only rustc has actually introduced some pretty major regressions - maybe something has changed on master in the meantime?

I guess I am not feeling like we have a complete picture of the constraints here and the effects of various switches. Bootstrap columns in the table seem pretty useless to me -- they're not indicative of a difference between variant 1 and 2 in terms of performance of rustc at runtime.

There are several inputs which can be changed:
* number of codegen units used for rustc
* number of codegen units used for std
* number of codegen units used for tooling like cargo etc (in theory this has no effect, but really we should validate that assumption)

From each of these we have several metrics to evaluate the effect:
* time spent on CI producing these artifacts
* size of produced artifacts on disk
* runtime performance of the artifacts, likely ideally represented as "how close we get to optimal, with these toggles"
   * likely this wants to be roughly "average change" and "worst regression", but ultimately just needs to be a link to perf.rlo

I think we don't want to alter the settings when perf.rlo is run, as that skews our data and generally doesn't make for something that's easy to compare. That means any changes in configuration in this PR should be gated on Rust's CI (somehow) rather than just any x.py run.

Right now the table I think I'm struggling to read the table in a conclusive way - I don't know exactly what would help, but it seems like the primary problem with the current table is that it combines data along these axes in a way that at least for me is hard to compare. Maybe splitting apart into multiple tables or putting each metric in its own table would be helpful, I'm not sure.

**Comment by tmiasko** [comment]
> it looks like switching to bootstrapping with codegen units affecting only rustc has actually introduced some pretty major regressions - maybe something has changed on master in the meantime?

As far as I can see that is mostly a reflection to what degree optimizer decision made when building rustc affect the results, and how inaccurate benchmarks are as a consequence. After spending some time profiling I am entirely unsurprised given that: 50% of all instructions in inflate are in just one function, for keccak in 2 functions, for match-stress-enum in 2 functions, for ctfe-stress-4 around 10. Just like in match-stress-enum case it should be easy to isolate and direct optimizer towards making the same decisions it is making now, if one desired to do so.

Given that reducing the number of CGUs for tooling takes around 10 min longer in try build ("Try 1" vs "Try 2"), that building with one or two CGUs takes at least 10 min longer ("Try 1" & "Try 2") than other options, and that builds with one, two, three, and four CGUs have regressions in perf results. What about reducing the number of CGUs for rustc to 5, which reduces the size of toolchain by 8 MB, took 54 min in try builder and gave following [perf results](https://perf.rust-lang.org/compare.html?start=e9920ef7749d11fc71cc32ca4ba055bcfeaab945&end=03192e87b7e4444897b09bec2729882ed234cbdd)?

**Pull request closed without merging**
