### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**
r? @ghost

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
If https://github.com/rust-lang/rust/pull/61988 merges, clippy will be broken again (regardless of this pr).

**Comment by lzutao** [comment]
@Centril Do you want to take a look to rustup clippy?

**Comment by Centril** [comment]
@lzutao Don't have time for it right now. It should be relatively straightforward tho... make a "higher" function for resugaring `while`-loops with the information you need using the desugaring information based on what is done in `lowering.rs` in my PR. Then proceed to use that higher function on HIR expressions and match on `Some((the, information, you need))`.

**Pull request merged**
