### PR TITLE
[beta] travis: Ensure cargo links libcurl statically

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a beta backport of https://github.com/rust-lang/rust/pull/40507

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r=brson p=2

(fixing beta)

**Comment by alexcrichton** [comment]
@bors: retry

* spurious ar.exe error https://github.com/rust-lang/rust/issues/40546

**Comment by alexcrichton** [comment]
@bors: retry

* osx timeout?

**Comment by alexcrichton** [comment]
@bors: retry

* osx timeout https://github.com/rust-lang/rust/issues/40571

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/40571

**Comment by frewsxcv** [comment]
@bors retry

prioritizing the rollup which includes these changes https://github.com/rust-lang/rust/pull/40591

**Comment by frewsxcv** [comment]
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

**Comment by alexcrichton** [comment]
gonna make a new PR with more backports

**Pull request closed without merging**
