### PR TITLE
debuginfo: Fix NatVis for Rc and Arc with unsized pointees.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Currently, the NatVis for `Rc<T>` and `Arc<T>` does not support unsized `T`. For both `Rc<T>` and `Rc<dyn SomeTrait>` the visualizers fail:

```txt
    [Reference count] : -> must be used on pointers and . on structures
    [Weak reference count] : -> must be used on pointers and . on structures
```

This PR fixes the visualizers. For slices we can even give show the elements, so one now gets something like:

```txt
slice_rc         : { len=3 }
    [Length]         : 3
    [Reference count] : 41
    [Weak reference count] : 2
    [0]              : 1
    [1]              : 2
    [2]              : 3
```

r? @wesleywiser

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Nominating this for beta-backport. Normally we wouldn't do this but 1.62 is a relatively important release for @michaelwoerister and I's team as it contains all of the work we've done so far on improving the debugging experience on Windows. As such, we've been telling internal users to use this release as a baseline for future work. It would be great if we could have this issue resolved in it as well!

## Backport considerations

- For:
    - Low risk: This change has no effect on any platform other than `*-windows-msvc` and even then, has no effect on anything except debugger visualizations in WinDbg or VS. As such, there is no risk of changing compiler behavior in any way. 
    - Manually tested: In addition to the automated test checked in with this change, this change has also been validated in both WinDbg and Visual Studio manually.

- Against:
    - We typically wouldn't backport this kind of change and instead allow it to ride the trains.

**Comment by GuillaumeGomez** [comment]
Failed in rollup https://github.com/rust-lang/rust/pull/98139.

@bors r-

**Comment by wesleywiser** [comment]
Fixed the test to account for i686. 

@bors r+ rollup

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-16/near/286363312)

@rustbot label +beta-accepted

**Pull request merged**
