### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by arlosi**
8 commits in 03a849043e25104e8b7ad0d4a96c525787b69379..a5e08c4703f202e30cdaf80ca3e7c00baa59c496
2022-06-20 14:47:36 +0000 to 2022-06-23 20:12:03 +0000
- Fix tests due to change in dead_code diagnostic. (rust-lang/cargo#10785)
- Stabilize config-cli (rust-lang/cargo#10755)
- Restrict duplicate deps warning only to published packages (rust-lang/cargo#10767)
- Use fingerprint_hash when computing fingerprints for custom targets (rust-lang/cargo#10746)
- Add preloading for workspace packages in `resolve_with_previous` (rust-lang/cargo#10761)
- capitalise, for consistency (rust-lang/cargo#10772)
- remove unused dependency from benchsuite (rust-lang/cargo#10774)
- docs(contrib): Add documentation for ui tests (rust-lang/cargo#10758)

### CODE REVIEW

**Comment by jonhoo** [comment]
@arlosi Would you mind bumping this slightly to bring in https://github.com/rust-lang/cargo/pull/10755 as well? It brings in a `relnotes`-worthy change to cargo that'd be nice to get in before 1.63 freeze.

**Comment by ehuss** [comment]
@bors r- 

This is going to fail without https://github.com/rust-lang/cargo/pull/10768

**Comment by ehuss** [comment]
Thanks!

@bors r+ rollup=never p=10

**Pull request merged**
