### PR TITLE
Use InternedString instead of Symbol for type parameter types (2)

### PR DESCRIPTION
**Pull request by michaelwoerister**
Reduced alternative to #49266. Let's see if this causes a performance regression.

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362695010). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:00:54] configure: rust.quiet-tests     := True
---
[00:43:35] error[E0277]: the trait bound `syntax::ast::Symbol: std::ops::Deref` is not satisfied
[00:43:35]     --> librustdoc/clean/mod.rs:1797:24
[00:43:35]      |
[00:43:35] 1797 |             if tp.name == keywords::SelfType.name() {
[00:43:35]      |                        ^^ the trait `std::ops::Deref` is not implemented for `syntax::ast::Symbol`
[00:43:35]      |
[00:43:35]      = note: required because of the requirements on the impl of `std::cmp::PartialEq<syntax::ast::Symbol>` for `syntax::symbol::InternedString`
---
[00:43:50] Makefile:28: recipe for target 'all' failed
[00:43:50] make: *** [all] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:13759634:start=1522946959557974590,finish=1522946959565989017,duration=8014427
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:13da83ca
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:13da83ca:start=1522946959573675738,finish=1522946959582376915,duration=8701177
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:30ddbad8
$ dmesg | grep -i kill
[   11.080535] init: failsafe main process (1091) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362695350). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
$ git clone --depth=2 --branch=try https://github.com/rust-lang/rust.git rust-lang/rust
---
[00:02:06] configure: rust.quiet-tests     := True
---
[00:50:19] error[E0277]: the trait bound `syntax::ast::Symbol: std::ops::Deref` is not satisfied
[00:50:19]     --> librustdoc/clean/mod.rs:1797:24
[00:50:19]      |
[00:50:19] 1797 |             if tp.name == keywords::SelfType.name() {
[00:50:19]      |                        ^^ the trait `std::ops::Deref` is not implemented for `syntax::ast::Symbol`
[00:50:19]      |
[00:50:19]      = note: required because of the requirements on the impl of `std::cmp::PartialEq<syntax::ast::Symbol>` for `syntax::symbol::InternedString`
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1500bdcb:start=1522947430748714534,finish=1522947430758013029,duration=9298495
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:02032a11
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:02032a11:start=1522947430768928875,finish=1522947430777800838,duration=8871963
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:034b1330
$ dmesg | grep -i kill
[   10.629479] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362695350). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
$ git clone --depth=2 --branch=try https://github.com/rust-lang/rust.git rust-lang/rust
---
[00:02:06] configure: rust.quiet-tests     := True
---
[00:50:19] error[E0277]: the trait bound `syntax::ast::Symbol: std::ops::Deref` is not satisfied
[00:50:19]     --> librustdoc/clean/mod.rs:1797:24
[00:50:19]      |
[00:50:19] 1797 |             if tp.name == keywords::SelfType.name() {
[00:50:19]      |                        ^^ the trait `std::ops::Deref` is not implemented for `syntax::ast::Symbol`
[00:50:19]      |
[00:50:19]      = note: required because of the requirements on the impl of `std::cmp::PartialEq<syntax::ast::Symbol>` for `syntax::symbol::InternedString`
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1500bdcb:start=1522947430748714534,finish=1522947430758013029,duration=9298495
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:02032a11
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:02032a11:start=1522947430768928875,finish=1522947430777800838,duration=8871963
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:034b1330
$ dmesg | grep -i kill
[   10.629479] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, would you mind doing a perf run for this?

**Comment by Mark-Simulacrum** [comment]
Perf run started.

**Comment by michaelwoerister** [comment]
http://perf.rust-lang.org/compare.html?start=db4235c4fd20b18fcda7f331913cfe30a13f216c&end=b7383f5bde49f79e3fb401a48464a604ad9e1607&stat=instructions%3Au

No real performance regression, it seems. Let's merge this version and treat the optimizations in #49266 in a separate PR, I'd say.

r? @nikomatsakis

**Review by eddyb — APPROVED** [review]

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout in `dist-x86_64-mingw`. Build was successful, but only 3 minutes left for deployment. 

<details><summary>Timings</summary>

```
591:[00:06:50] [TIMING] StartupObjects { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu" } -- 0.321
592:[00:06:51] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "fabricate", path: "src/tools/rust-installer", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 0.142
593:[00:06:51] [TIMING] Mingw { host: "x86_64-pc-windows-gnu" } -- 0.145
594:[00:06:52] [TIMING] Src -- 0.907
595:[00:06:52] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "cargo", path: "src/tools/cargo", mode: Librustc, is_ext_tool: false, extra_features: [] } -- 0.149
596:[00:06:52] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "rustfmt", path: "src/tools/rustfmt", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 0.103
597:[00:06:52] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "cargo-fmt", path: "src/tools/rustfmt", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 0.106
598:[00:06:52] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "clippy-driver", path: "src/tools/clippy", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 0.164
600:[00:06:53] [TIMING] StartupObjects { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu" } -- 0.199
628:[00:10:04] [TIMING] Std { target: "x86_64-pc-windows-gnu", compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" } } -- 191.096
638:[00:10:22] [TIMING] Test { target: "x86_64-pc-windows-gnu", compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" } } -- 17.897
787:[00:36:45] [TIMING] Rustc { target: "x86_64-pc-windows-gnu", compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" } } -- 1583.251
4627:[00:55:00] [TIMING] Llvm { target: "x86_64-pc-windows-gnu", emscripten: false } -- 1095.358
4639:[00:57:53] [TIMING] CodegenBackend { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", backend: "llvm" } -- 172.926
7489:[01:06:01] [TIMING] Llvm { target: "x86_64-pc-windows-gnu", emscripten: true } -- 487.764
7496:[01:08:20] [TIMING] CodegenBackend { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", backend: "emscripten" } -- 138.957
7704:[01:09:22] [TIMING] Lld { target: "x86_64-pc-windows-gnu" } -- 62.500
7733:[01:11:35] [TIMING] Std { target: "x86_64-pc-windows-gnu", compiler: Compiler { stage: 1, host: "x86_64-pc-windows-gnu" } } -- 132.673
7743:[01:11:56] [TIMING] Test { target: "x86_64-pc-windows-gnu", compiler: Compiler { stage: 1, host: "x86_64-pc-windows-gnu" } } -- 20.767
7892:[01:37:11] [TIMING] Rustc { target: "x86_64-pc-windows-gnu", compiler: Compiler { stage: 1, host: "x86_64-pc-windows-gnu" } } -- 1515.080
7904:[01:39:12] [TIMING] CodegenBackend { compiler: Compiler { stage: 1, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", backend: "llvm" } -- 120.948
7911:[01:40:55] [TIMING] CodegenBackend { compiler: Compiler { stage: 1, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", backend: "emscripten" } -- 103.268
7938:[01:42:32] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "unstable-book-gen", path: "src/tools/unstable-book-gen", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 97.191
7939:[01:42:34] [TIMING] UnstableBookGen { target: "x86_64-pc-windows-gnu" } -- 1.923
8106:[01:48:23] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "rustbook", path: "src/tools/rustbook", mode: Librustc, is_ext_tool: false, extra_features: [] } -- 349.028
8108:[01:48:27] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "unstable-book", src: "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\md-doc" } -- 3.242
8110:[01:48:29] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "book/first-edition", src: "C:\\projects\\rust\\src/doc" } -- 1.994
8112:[01:48:32] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "book/second-edition", src: "C:\\projects\\rust\\src/doc" } -- 2.857
8146:[01:52:20] [TIMING] Rustdoc { host: "x86_64-pc-windows-gnu" } -- 228.543
8147:[01:52:21] [TIMING] Standalone { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu" } -- 1.313
8150:[01:52:24] [TIMING] TheBook { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", name: "book" } -- 2.524
8177:[01:54:29] [TIMING] Std { stage: 2, target: "x86_64-pc-windows-gnu" } -- 125.386
8227:[01:55:43] [TIMING] WhitelistedRustc { stage: 2, target: "x86_64-pc-windows-gnu" } -- 73.282
8235:[01:56:08] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "error_index_generator", path: "src/tools/error_index_generator", mode: Librustc, is_ext_tool: false, extra_features: [] } -- 25.371
8236:[01:56:08] [TIMING] ErrorIndex { target: "x86_64-pc-windows-gnu" } -- 0.225
8238:[01:56:10] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "nomicon", src: "C:\\projects\\rust\\src/doc" } -- 1.466
8240:[01:56:11] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "reference", src: "C:\\projects\\rust\\src/doc" } -- 1.469
8242:[01:56:11] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "rustdoc", src: "C:\\projects\\rust\\src/doc" } -- 0.210
8244:[01:56:14] [TIMING] RustbookSrc { target: "x86_64-pc-windows-gnu", name: "rust-by-example", src: "C:\\projects\\rust\\src/doc" } -- 2.670
8246:[01:56:15] [TIMING] CargoBook { target: "x86_64-pc-windows-gnu", name: "cargo" } -- 0.463
8304:[01:59:32] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "fabricate", path: "src/tools/rust-installer", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 190.611
8305:[02:01:01] [TIMING] Docs { stage: 2, host: "x86_64-pc-windows-gnu" } -- 96.084
8309:[02:01:16] [TIMING] Mingw { host: "x86_64-pc-windows-gnu" } -- 14.611
8311:[02:05:11] [TIMING] Rustc { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" } } -- 234.835
8313:[02:07:13] [TIMING] Std { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu" } -- 122.391
8316:[02:07:17] [TIMING] Analysis { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu" } -- 4.282
8318:[02:07:36] [TIMING] Src -- 19.133
8500:[02:24:33] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "cargo", path: "src/tools/cargo", mode: Librustc, is_ext_tool: false, extra_features: [] } -- 1016.431
8501:[02:24:50] [TIMING] Cargo { stage: 2, target: "x86_64-pc-windows-gnu" } -- 16.725
8581:[02:31:13] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "rustfmt", path: "src/tools/rustfmt", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 382.840
8590:[02:32:45] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "cargo-fmt", path: "src/tools/rustfmt", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 92.627
8591:[02:32:57] [TIMING] Rustfmt { stage: 2, target: "x86_64-pc-windows-gnu" } -- 11.539
8763:[02:34:36] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "clippy-driver", path: "src/tools/clippy", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 99.115
8852:[02:43:53] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-gnu" }, target: "x86_64-pc-windows-gnu", tool: "rls", path: "src/tools/rls", mode: Librustc, is_ext_tool: true, extra_features: [] } -- 556.950
8853:[02:44:17] [TIMING] Rls { stage: 2, target: "x86_64-pc-windows-gnu" } -- 24.551
```

</details>

The time spent on building LLVM is unusually long, at 18 minutes (usually it is about 5 minutes).

**Comment by alexcrichton** [comment]
In backporting this PR e31dae4741bc1eaaceeef0fd96dd0135d36598e0 doesn't apply cleanly but it looks non-critical so I'm going to leave it out.

**Comment by michaelwoerister** [comment]
I'll backport that commit too. It's kind of important because otherwise we get rather hard to interpret ICEs in subsequent compilation sessions (and sometimes silent corruption).

**Pull request merged**
