### PR TITLE
Fix dep graph edges around the fulfillment cache in the tcx

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is a fix for #30741. It simplifies dep-graph tracking for trait matching. I was experimenting with having a greater resolution here, but decided to pare back to just have one dep node for "trait resolutions on trait `Foo`", which means that adding an impl to the trait `Foo` will invalidate all fns that had to do any trait matching at all on `Foo`. This seems like a reasonable starting place.

Independently, I realized I had neglected to record a dependency from trans on typeck -- this is obviously needed, since trans consumes a bunch of data structures that typeck produces (but which are not currently individually tracked) -- and because trans assumes that typeck has been done. Eventually those are going to go away and be replaced with MIR, which will be tracked, so this edge would presumably be derived automatically then, but it's an obvious enough thing to want for now.

r? @arielb1 

cc @michaelwoerister -- this might indirectly fix the problem you observed with the trans cache, though it'd be nice to try and craft an independent test case for that.

### CODE REVIEW

**Comment by arielb1** [comment]
Nice way to introduce me to depgraph!

**Comment by jonas-schievink** [comment]
Could this be used to lint on unused trait impls?

**Comment by nikomatsakis** [comment]
@jonas-schievink 

> Could this be used to lint on unused trait impls?

Not with much precision, at least not right now. We're just tracking what traits you looked at, not which impls.

**Pull request merged**
