### PR TITLE
merge const_ipv4 / const_ipv6 feature gate into 'ip' feature gate

### PR DESCRIPTION
**Pull request by RalfJung**
https://github.com/rust-lang/rust/issues/76205 has been closed a while ago, but there are still some functions that reference it. Those functions are all unstable *and* const-unstable. There's no good reason to use a separate feature gate for their const-stability, so this PR moves their const-stability under the same gate as their regular stability, and therefore removes the remaining references to https://github.com/rust-lang/rust/issues/76205.

### CODE REVIEW

**Comment by tgross35** [comment]
@bors r+ rollup

I have been thinking recently that we should split the `ip` gate up since https://github.com/rust-lang/rust/issues/27709 is huge and old and unlikely to be stabilized as one unit. But merging the const gates in makes sense here.

**Comment by tgross35** [comment]
@RalfJung fyi looks like there's a conflict now (I'm sure bors will say that soon)

**Comment by RalfJung** [comment]
@bors r-

Ah in fact we can simplify this by removing the `rustc_const_unstable` attributes entirely.

**Pull request merged**
