### PR TITLE
new solver: improve instrument annotations

### PR DESCRIPTION
**Pull request by lcnr**

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors treeclosed=100

> error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"

@bors retry :(

**Comment by compiler-errors** [comment]
let's test again

@bors p=101

**Comment by RalfJung** [comment]
Oh damn sorry. I saw the log-analyzer message and thought it meant the run had failed. But that message was heavily delayed, this was an error from the run before...

**Comment by RalfJung** [comment]
Yeah I just canceled and restarted a perfectly good run though. Oh well, too late to do anything about it.

**Comment by compiler-errors** [comment]
Ohhh I get it. Oh well 🤷 😄

**Pull request merged**
