### PR TITLE
rustc_query_system: explicitly register reused dep nodes

### PR DESCRIPTION
**Pull request by tgnottingham**
Register nodes that we've reused from the previous session explicitly
with `OnDiskCache`. Previously, we relied on this happening as a side
effect of accessing the nodes in the `PreviousDepGraph`. For the sake of
performance and avoiding unintended side effects, register explictily.

### CODE REVIEW

**Comment by tgnottingham** [comment]
@rustbot label T-compiler A-incr-comp A-query-system I-compiletime

Pinging @Aaron1011, @michaelwoerister.

r? @Aaron1011

**Comment by bjorn3** [comment]
This doesn't have any effect on full and incr-full. (<0.1%) incr-unchanged and incr-patched got up to 2.4% faster. :tada:

**Comment by Aaron1011** [comment]
LGTM. @michaelwoerister Do you have any concerns about this approach? If not, r=me

**Comment by michaelwoerister** [comment]
I'll take a look now.

**Comment by michaelwoerister** [comment]
The approach looks good to me. It's similar to how we do "cache promotion" where we explicitly move things from the previous cache into the current one so things don't get lost.

In general I'd would be happy if we could simplify this whole system so we don't need so much mutable state (and therefore always run into the risk of not doing things in the right order or just making things too complicated to understand). I envision a `DefPathTable` encoding for crate metadata that allows for random access and basically free decoding (because it everything is uncompressed). For that to really work we'll probably need a hashtable implementation that does not need decoding either -- which isn't rocket science but also isn't trivial. And we would need to switch DefPathHashes to being structured as mentioned in https://github.com/rust-lang/rust/pull/79589#issuecomment-748217829. Putting all of those things together would make for a quite elegant setup, I think.

But all of that can be done at a later point in time (if it actually turns out to be a good idea 😃)

Thanks for the PR, @tgnottingham and thanks for keeping an eye on this, @Aaron1011!

**Comment by lqd** [comment]
CI is green, PR is reviewed, mw approves,🚀 

@bors r=Aaron1011

**Pull request merged**
