### PR TITLE
Remove uses of `uint` that are not pointer-related from the `Int` trait

### PR DESCRIPTION
**Pull request by tbu-**
Use `u32` instead.

### CODE REVIEW

**Comment by aturon** [comment]
@tbu- Thanks for doing this! Assuming that https://github.com/rust-lang/rfcs/pull/544 is accepted, we're going to need to (1) establish formal guidelines for integer usage and (2) do a full sweep of std to roll them out during alpha. (This is part of the more general rollout plan.) Do you mind waiting on this PR until a conventions RFC is accepted? (I expect this to happen quickly after alpha, if not before.)

**Comment by tbu-** [comment]
@aturon I'm totally fine with this, and I'm happy that this is talked about seriously.

**Comment by tbu-** [comment]
@aturon Should I close this PR or just wait?

**Comment by aturon** [comment]
@tbu- Please close for now, it helps speed bors up, and then reopen later on when the convention is clear. Thanks again!

**Pull request closed without merging**
