### PR TITLE
Stabilize control-flow-guard codegen option

### PR DESCRIPTION
**Pull request by ajpaverd**
This is the stabilization PR discussed in #68793. It converts the `-Z control-flow-guard` debugging option into a codegen option (`-C control-flow-guard`), and changes the associated tests.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Dear @rust-lang/compiler -- I move that we stabilize the control-flow-guard codegen option. You can find write-ups with the details in [this comment from the tracking issue](https://github.com/rust-lang/rust/issues/68793#issuecomment-638229073).

**Comment by ollie27** [comment]
I tried compiling a simple hello world binary for none MSVC targets with `-Zcontrol-flow-guard=y` and it doesn't seem to be ignored. On `x86_64-pc-windows-gnu` along with the `warning: Windows Control Flow Guard is not supported by this linker.` message I'm getting an ```undefined reference to `__guard_dispatch_icall_fptr'``` error. On `x86_64-unknown-linux-gnu` rustc just segfaults. I can investigate further if needed but I assume we just need to make sure the `cfguard` module flag is only emitted when actually targeting `windows-msvc`.

**Comment by ajpaverd** [comment]
> I tried compiling a simple hello world binary for none MSVC targets with `-Zcontrol-flow-guard=y` and it doesn't seem to be ignored. On `x86_64-pc-windows-gnu` along with the `warning: Windows Control Flow Guard is not supported by this linker.` message I'm getting an `` undefined reference to `__guard_dispatch_icall_fptr' `` error. On `x86_64-unknown-linux-gnu` rustc just segfaults. I can investigate further if needed but I assume we just need to make sure the `cfguard` module flag is only emitted when actually targeting `windows-msvc`.

Thanks for reporting this bug @ollie27! The `windows-gnu` target was indeed a missed cased. As far as I can see, LLVM should still be ignoring this module flag for any non-Windows target (see e.g. [X86TargetMachine.cpp](https://github.com/llvm/llvm-project/blob/d7ea6ce809a4413afb1edafa17ba291b39129f52/llvm/lib/Target/X86/X86TargetMachine.cpp#L412)), so the segfault on `x86_64-unknown-linux-gnu` is surprising, but there could of course be an LLVM bug as well - I'll investigate further. In any case, I agree that only emitting the module flag in rustc if targeting `windows-msvc` would solve both of these issues, and would also be more robust. I'll submit a separate PR for this.

**Comment by nikomatsakis** [comment]
ping @petrochenkov @estebank and @eddyb

**Comment by nikomatsakis** [comment]
@ajpaverd I believe this is ready to merge -- any final changes you had in mind?

**Comment by ajpaverd** [comment]
Thanks @nikomatsakis and all the reviewers! I think this is ready to merge. I guess the question of enabling this mitigation in `libstd` should be a separate discussion/PR.

**Pull request merged**
