### PR TITLE
Implement <Rc<Any>>::downcast

### PR DESCRIPTION
**Pull request by bluss**
* Implement `<Rc<Any>>::downcast::<T>`
  * New unstable method. Works just like Box\<Any\>, but for Rc.
  * Any has two cases for its methods: Any and Any + Send; Rc is never Send, so that case is skipped for Rc.
  * Motivation for being a method with self is to match Box and there is no user-supplied type; the inner type is Any and downcast does not conflict with any method of Any.
* Arc was skipped because Any itself has no downcast for the case that makes most sense: Any + Send + Sync

### CODE REVIEW

**Comment by bluss** [comment]
I'll probably revise this -- the pointer math in from_raw does not optimize out as it should

**Comment by kennytm** [comment]
> Arc is skipped because Any itself has no downcast for the case that makes most sense: Any + Send + Sync

Why we don't implement downcast for `Any + Send + Sync`? Other than [it isn't terribly necessary](https://github.com/rust-lang/rust/issues/44064#issuecomment-324412204).

**Comment by bluss** [comment]
I pushed a new version with a more direct implementation, because the pointer arithmetic of using into_raw/from_raw did not optimize out. ([playground demo for that](https://play.rust-lang.org/?gist=ffcab6203d27b9fc50c746137b3e10c9&version=nightly))

**Comment by bluss** [comment]
@kennytm I'm not sure, there are only four combinations of Any and Send, Sync, so it's simple to cover them all, but a bit confusing in the API doc.

**Comment by sfackler** [comment]
This seems reasonable to me.

@rfcbot fcp merge

**Comment by alexcrichton** [comment]
@bors: r-

oh actually, @bluss mind filing a tracking issue for this and updating the PR with that number?

**Comment by bluss** [comment]
Sure, updated with tracking issue #44608

**Pull request merged**
