### PR TITLE
Changed std:: to core:: in core library documentation

### PR DESCRIPTION
**Pull request by Gip-Gip**
I noticed while reading the core documentation that many times it instructs the user to `use std::` instead of `use core::`, and this seems wrong to me since, as far as I know, you use core when you are in a nostd environment.

I am currently busy and can't compile it at the moment to make sure I didn't break anything, but I did a simple `grep -rl "std::" src/ | xargs sed -i "s/std::/core::/g"` in the /libraries/core directory and this should do the trick.

I didn't put a massive amount of effort into this I'm willing to admit but I do think this minor change is a decent correction to the documentation.

Feel free to correct me or point out any places where I may have broke the code.

### CODE REVIEW

**Comment by Gip-Gip** [comment]
I just noticed I may have replaced too much, when I get the chance I will fix these issues.

**Comment by jyn514** [comment]
Aren't most of these items re-exported from `core` to `std`? When rustdoc inlines a re-exported item, it keeps all the original documentation, so everywhere in `std` will now start saying `core` instead.

Not necessarily a blocker, but seems important to consider.

**Comment by Gip-Gip** [comment]
> Aren't most of these items re-exported from `core` to `std`? When rustdoc inlines a re-exported item, it keeps all the original documentation, so everywhere in `std` will now start saying `core` instead.
> 
> Not necessarily a blocker, but seems important to consider.

Probably, I wouldn't know I just noticed a typo when working on the docs.
Would it help to have a script that simply regex's the documentation? It is a minor fix for sure but still

**Comment by jyn514** [comment]
I am not sure what you mean by regexes. This is a fundamental limitation of rustdoc, it does not allow you to overwrite docs on re-exports instead of appending.

**Comment by Gip-Gip** [comment]
> I am not sure what you mean by regex's. This is a fundamental limitation of rustdoc, it does not allow you to overwrite docs on re-exports instead of appending.

Hmm. I'm not fluent enough in the rust codebase to know of any workarounds or etc.
Would it be possible to perhaps implement enviroment variables in rustdoc to account for name changes in re-exporting, or would that go against some design philosophy of some kind?

For example replace
`/// std::foo`
with something alike
`/// $[crate_name]::foo`

Sounds like a pain but still wondering if it's an option.

**Comment by jyn514** [comment]
That seems possible, but you should discuss with the rustdoc team whether that's a feature they want to support (given that it sounds like only core and std would be using it). They have [a stream on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc).

**Comment by Gip-Gip** [comment]
> That seems possible, but you should discuss with the rustdoc team whether that's a feature they want to support (given that it sounds like only core and std would be using it). They have [a stream on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc).

Thanks! I'll close this and focus in that instead.

**Pull request closed without merging**
