### PR TITLE
Make `#[derive(A, B, ...)]` cfg-eval its input only for `A, B, ...` and stabilize `feature(macro_attributes_in_derive_output)`

### LINKED ISSUE #81119: Tracking issue for macro attributes in `#[derive]` output
This is a tracking issue for macro attributes that can observe output of the `#[derive]` attribute.
This includes macro attributes on the same item as `#[derive]` but below it, and macro attributes on nested nodes of the item with `#[derive]`.

`#[derive]` *fully configures* its input, eagerly evaluating `cfg`s everywhere in its target, for example on fields.
Attributes expanded after the `#[derive]` will see the item in this fully configured form, but we don't want expose it to them on stable channel for now.

Example:
```rust
#[derive(Trait)]
#[my_attr] // Gated
struct S1 {
    field: [u8; 10],
}

#[derive(Trait)]
struct S2 {
    field: [u8; #[my_attr] 10], // Gated
}
```

The feature name is `macro_attributes_in_derive_output`.
The feature gate was introduced in https://github.com/rust-lang/rust/pull/79078.

### PR DESCRIPTION
**Pull request by petrochenkov**
Stabilization report: https://github.com/rust-lang/rust/pull/87220#issuecomment-881923657

Closes #81119
r? @Aaron1011

### CODE REVIEW

**Comment by petrochenkov** [comment]
# Stabilization Report

Historically `#[derive]` attribute eagerly expands all `cfg` and `cfg_attr` attributes in its item ("fully configures" it) before passing that item to derive macros.

For example, in the next example
```rust
#[derive(Trait)]
struct S {
    #[cfg(FALSE)]
    field: u8,
}
```
`Trait` will see tokens `struct S {}` rather than `struct S { #[cfg(FALSE)] field: u8, }`.

PR #79078 ("Turn `#[derive]` into a regular macro attribute") supported macro attributes written after `#[derive]`:
```rust
#[derive(Trait)]
#[my_macro]
struct S {
    #[cfg(FALSE)]
    field: u8,
}
```

Attributes on the same item are expanded in left to right order, so `my_macro` is expanded immediately after `derive`.
The question is: which tokens `my_macro` receives as an input?
1. It can receive the original, not configured, item. In other words `#[derive]` feeds a configured version of the item to `Trait`, but otherwise emit the item in unmodified form so all the `cfg`s and `cfg_attr`s in it are expanded later in natural order.
2. It can receive the same fully configured item as `Trait`.
3. It can receive the item transformed in some entirely different way (not considering this variant here, no motivation to do that).

Code depending on the answer is currently gated by `feature(macro_attributes_in_derive_output)`.

We propose stabilizing the variant `1.` and feeding the fully configured item only to traits inside `#[derive]` and keeping the original item it for later expansion.
This seems to be the most principled solution - `#[derive]` only affects itself and not attributes written after it.
As a result attributes that want to do custom `cfg` processing (like those found by crater in https://github.com/rust-lang/rust/pull/85073#issuecomment-851064125) can be written after `#[derive]` too.
The variant `1.` also prevents abusing empty `#[derive()]` as a cfg-expanding attribute (this problem is going to be addressed by `#[cfg_eval]` (https://github.com/rust-lang/rust/issues/82679) which I'm planning to stabilize next).
The main concern here is performance because some things may need to be configured twice, but as a perf experiment in https://github.com/rust-lang/rust/pull/86057 shows, it's not an issue in practice.

The more radical alternative is to fully configure items before expanding *any* attributes, not only `derive`.
That alternative was implemented as an experiment in https://github.com/rust-lang/rust/pull/85073.
Crater showed that there are indeed attributes that want to do some custom `cfg` processing (https://github.com/rust-lang/rust/pull/85073#issuecomment-851064125) which are broken by this change, so we need some kind opt-out from eager configuration, but it's not clear how that opt-out should look like.
We suggest considering switching to this alternative for the next edition (~Rust 2024), but leave it alone for now.

## Examples

```rust
#[derive(Trait)] // (1) `Trait` sees `struct S {}` as input
#[my_macro] // (2) `my_macro` sees `struct S { #[cfg(FALSE)] field: u8, }` as input
struct S {
    #[cfg(FALSE)]
    field: u8,
}
```

## Test cases

- `src/test/ui/proc-macro/attribute-after-derive.rs` - (2) in the example above
- `src\test\ui\proc-macro\expand-to-derive.rs` or any other test with `derive` and `cfg` - (1) in the example above

## Documentation

https://github.com/rust-lang/reference/issues/1074

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/lang meeting. We agreed with this proposal, and we think it makes sense to change this for current Rust. We do feel that we should move to eager-evaluation by default for a future edition, with an opt-out for macros/attributes that really *want* to deal with unevaluated `cfg`. But for now, this change seems like the right approach.

@rfcbot merge

**Comment by Aaron1011** [comment]
r=me with the merge conflicts addressed

**Pull request merged**
