### PR TITLE
Use non-local OS error strings (en-US)

### LINKED ISSUE #34318: Unreadable io::Error debug strings
While trying to open a non-existing file (on Windows 10, Chinese):

```rust
use std::fs::File;
fn main() {
    File::open("no-such-file.rs").unwrap();
}
```

It panicked with a message:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "\u{7cfb}\u{7edf}\u{627e}\u{4e0d}\u{5230}\u{6307}\u{5b9a}\u{7684}\u{6587}\u{4ef6}\u{3002}" } }', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The OS native error message here is **unreadable** for human being.

The message (`"\u{7cfb}\u{7edf}\u{627e}\u{4e0d}\u{5230}..."`) is the _escaped_ result of "No such file or directory" in Chinese ("系统找不到指定的文件")。[`impl fmt::Debug for str`](http://doc.rust-lang.org/stable/src/core/up/src/libcore/fmt/mod.rs.html#1350-1368) do this escape.

I can read Chinese, which is my mother tongue, but I can't read `\u{7cfb}...`.

Possible solutions:
- Don't use local language (Chinese here) OS error string, use English instead.
- Change `impl fmt::Debug for str` to not escape most Unicode chars. (breaking-change?)

---

```
fn main() {
    let s = "Hello δεΣ❤ 日月";
    println!("{}", s);   // prints "Hello δεΣ❤ 日月"
    println!("{:?}", s); // prints "Hello \u{3b4}\u{3b5}\u{3a3}\u{2764} \u{65e5}\u{6708}"
}
```

[Run it on play.rust-lang.org](https://is.gd/T7lmqG)

Is `impl fmt::Debug for str` really friendly enough for _debug_ purpose? Is there possibility that we change its implementation as similar as `impl fmt::Display for str`?

### PR DESCRIPTION
**Pull request by liigo**
Closes #34318

### CODE REVIEW

**Comment by tbu-** [comment]
Is there precedence of other programming languages doing this? From the top of my head, I only know that Python doesn't.

I don't think this is a good idea, we shouldn't impose English upon the user. If you have, say, a Windows in German, then it is expected that all strings by the operating system actually are in German.

**Comment by liigo** [comment]
@tbu- Yes, I'm Chinese, I would prefer reading OS error strings in Chinese. But Rust doesn't really print OS error strings in Chinese, it print them as `\u{xxxx}\u{yyyy}...`, which I can't read. English is better than `\u{xxxx}\u{yyyy}...`, at least. See https://github.com/rust-lang/rust/issues/34318.

**Comment by tbu-** [comment]
Maybe we should rather escape less characters in the `Debug` implementation of `&str`.

**Comment by retep998** [comment]
I'd rather disable escaping only for OS error strings specifically, not for all strings.

**Comment by tbu-** [comment]
@retep998 I believe Python has a good strategy here, and they don't escape most Unicode symbols, except for weird ones like zero-width space (U+200B):

```
Python 3.5.1 (default, <timestamp>) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "ä", "\u00e4" , "\u200b"
('ä', 'ä', '\u200b')
```

Equivalent Rust:
```
fn main() {
    println!("{:?} {:?}", "ä", "\u{200b}");
}
```

Outputs:
```
"\u{e4}" "\u{200b}"
```

**Comment by alexcrichton** [comment]
Thanks for the PR @liigo! The libs team got a chance to talk about this today and the conclusion was that we're going to go with a solution like #34485 instead to keep localized error strings but try to escape fewer characters.

**Pull request closed without merging**
