### PR TITLE
Get rid of `ConstValue::ScalarPair`

### PR DESCRIPTION
**Pull request by oli-obk**
based on https://github.com/rust-lang/rust/pull/55293 (only the last commit is part of this PR)

### CODE REVIEW

**Comment by oli-obk** [comment]
This can potentially have adverse effects on performance

@bors try

**Comment by oli-obk** [comment]
@rust-timer build a08ddc905730cc7c3a758585abcdd8f0608cdfff

**Comment by oli-obk** [comment]
Small gains for tuple-stress and ucd, big losses for coercions.

Kinda expected. This is a very naive impl: even though str and slices are now ByRef, if they are used in another constant an "optimization" kicks in and converts it back to Value::ScalarPair only to then write it back into memory.

**Comment by RalfJung** [comment]
Seems this got out of Sync with its base PR? I wanted to look at https://github.com/oli-obk/rust/compare/self_managing_allocations...oli-obk:scalar_single to see what is actually new, but that looks like it still contains #55293. Could you rebase?

**Comment by jkordish** [comment]
Ping from triage. @oli-obk checking for a status update if you have time. thanks!

**Comment by oli-obk** [comment]
This PR is blocked on https://github.com/rust-lang/rust/pull/55293 (which in turn is blocked, too)

**Comment by oli-obk** [comment]
@RalfJung do you think it would be reasonable to not read a `ScalarPair` automatically if the backing memory is `ByRef` and just read it when needed?

Kindof adding a `ByRefReadOnly` optimization for `LocalValue`?

**Comment by RalfJung** [comment]
@oli-obk I still don't get it. Are you suggesting we change something in the miri engine? That seems unnecessary, the issue here is just about how to communicate the results of computation to the rest of the compiler. But if you do, could you spell out which miri engine types/operations you intent to change how?

The way I see it, we have `ty::Const` which is roughly like `MPlaceTy` and great for just representing arbitrary blobs of data of any type.  But in the miri engine we also have `ImmTy` because we sometimes need to *work* on data, like when we do casts or arithmetic, and then it's nice to have your data right there and not behind a memory indirection. So when something wants to work with constants of particular types, it should also turn them into such a representation. Maybe the pattern match desugaring can just create an `EvalContext` and call `read_immediate`, or maybe we have a `ty::ConstImmediate` and some `fn read(tcx, cnst: ty::Const) -> ty::ConstImmediate`, or so. That's what I would expect, anyway.

**Comment by oli-obk** [comment]
> So when something wants to work with constants of particular types, it should also turn them into such a representation.

I agree, but what I'm suggesting is to do this the first time we actually try to read an immediate from that local and not do any work before that.

I have (since writing https://github.com/rust-lang/rust/pull/55392#issuecomment-441448390) implemented a scheme that skips even that step.

Instead of creating a `ConstValue::ScalarPair`, which we only need for strings, I created a special `ConstValue::Slice`, which has an `AllocId` and `&'tcx Allocation`, similar to `ByRef`, but that `Allocation` is not for the `&str` fat pointer, but just for the string. The length is taken from the `Allocation`'s size and any pointers to the allocation need to be created via `Pointer::from(alloc_id)`.

This is basically a step all the way back to `ScalarPair`, except that we only use it for the common cases of `&str`, `&[u8]` and `&[u8; N]`. It simplifies some code around these uses cases imo.

As a next step I am considering doing the same for `ConstValue::Scalar` and change it to `ConstValue::Int`, without a possibility to store pointers in there.
We'd not use the layout to decide whether to do the optimization, but do it purely type-based for the few types that can actually benefit from the optimization

**Comment by oli-obk** [comment]
> Yes that's exactly what I was saying? When you need to do work on something, you convert it to an immediate form. The entire rest of the codebase doesn't even have no know that this form exists.

No, you want to convert it the moment you read from the global to a local. I want to convert it the first time someone wants to read an immediate from that local. So where we currently move from `Allocation` in the global to `Immediate` in the local and then immediately back into an `Allocation`, I want to place the `Allocation` there directly and just copy the relevant bytes when copying to another `Allocation`.

But as I said, I have moved to a different scheme.

> I am increasing confused. The goal, I thought, was to remove variants from ConstValue. There should be only one variant, ByRef. There will probably also have to be a type that allow for Unevaluated, let's call it LazyConstValue -- but crucially, the const_eval query returns a single-variant type.

That's not gonna work out of performance reasons. I tried, and each time the perf results were quite clear that we e.g. don't want to have to read array lengths from `Allocation`s or move fat pointers from immediate representations to `Allocation`-backed representations (https://perf.rust-lang.org/compare.html?start=694cf752988728ba5da85c36c2deaeefeb49c05e&end=a08ddc905730cc7c3a758585abcdd8f0608cdfff).

> But what about subslices...?

Currently a non-issue, so I left it out of the implementation.

**Comment by RalfJung** [comment]
> No, you want to convert it the moment you read from the global to a local.

Wait, why are we talking about locals? Inside miri, everything already works. `ConstValue` is for *outside* miri only. There are no locals or globals, just contants. What is even going on?

> But as I said, I have moved to a different scheme.

Okay. So now we are talking about another scheme I don't understand either. Hooray :D

> That's not gonna work out of performance reasons. I tried, and each time the perf results were quite clear that we e.g. don't want to have to read array lengths from Allocations

There is no reason that `ty::Array` should contain the same type that is returned by `const_eval`. In fact I think there are many reasons it should not. The length in `ty::Array` should be "either `Unevaluated` or `u64`". That's an invariant we already have, we just fail to encode it in the type. Whatever code does the normalization can call `const_eval`, and then immediately read the `u64`. In fact it has to because in this proposal we now have a proper type in `ty::Array` that doesn't let us do anything else. :) (It also is currently a `Const` and not a `ConstValue` and hence redundantly stores the fact that the type of the array length is `usize`, or am I missing something?)

Instead of guessing in `const_eval` what the caller wants, we should have the caller tell us.

> or move fat pointers from immediate representations to Allocation-backed representations

What does this mean?

**Comment by oli-obk** [comment]
> The length in ty::Array should be "either Unevaluated or u64".

that... makes so much more sense than any of the crazyness I have come up with and failed to make nice.

> What does this mean?

Encoding fat pointers in constants by using `ByRef` instead of `ScalarValue` causes any use of said constant in another to read it back to `Immediate`, only to be written back to a `ByRef` later.

**Comment by RalfJung** [comment]
> Encoding fat pointers in constants by using ByRef instead of ScalarValue causes any use of said constant in another to read it back to Immediate, only to be written back to a ByRef later.

Ah I see.  Where does that happen though? And can we do something similar to what I proposed for array lengths there?

**Comment by oli-obk** [comment]
> Ah I see. Where does that happen though? And can we do something similar to what I proposed for array lengths there?

I don't think so, every constant in MIR can possibly be a `str` and thus a fat pointer. And these are the very constants that we would like to not have a `Scalar` and `ScalarPair` variant.

@eddyb suggested once to do some constant folding during `MIR` building instead of punting it to const eval later. But that would mean `[5, 6]` gets turned into a single constant, while `[4 + 1, 6]` does not. Of course, for strings that's kind of fine. We'd just allow `["foo", "bar"]` and not `[&"fooo"[0..3], "bar"]` to get the optimization.

**Comment by RalfJung** [comment]
Those constants are only ever accessed for codegen, right? The only difference between what we do now and what we would do then is we would access the `Allocation` once per monomorphization, instead of once per MIR.  Given the cost of monomorphization, how can that even be noticeable?

**Comment by RalfJung** [comment]
But until we have figured that out, here's how I imagine things could look:
```rust
enum LazyConstValue<'tcx, T> {
    Unevaluated(DefId, &'tcx Substs<'tcx>),
    Evaluated(T),
}
enum ConstValue<'tcx> {
    Scalar(Scalar),
    ScalarPair(Scalar, Scalar),
    Indirect(AllocId, &'tcx Allocation, Size),
}
```
`const_eval` returns `ConstValue`. `ty::Array` uses `LazyConstValue<u64>`. `mir::Constant`/`ty::Const` use `LazyConstValue<ConstValue>`.

Does that make sense?

**Comment by oli-obk** [comment]
> Does that make sense?

Yes, this is a 1:1 copy of what I prototyped on the train this morning :D

**Comment by eddyb** [comment]
@RalfJung While that's nicer to work with, it's a bit sad, because it means `ty::Array` is different from `struct Foo<T, const N: usize>`, and there have been some efforts to "normalize" the typesystem into being a "type constructor" combined with some applied generics (in the form of `Substs`).
Someone from @rust-lang/wg-traits might be able to explain better.

**Comment by oli-obk** [comment]
We have two ways that I can come up with off the top of my head to have our cake and eat it, too:

1. add queries (or some faster cache) for converting `&'tcx Const<'tcx>` into `u64` for array lengths
2. add a "normalized" field to `&'tcx Const<'tcx>` which contains the `Scalar` and `ScalarPair` values of the constant, and change the `val` field to be the id, offset, allocation tuple of the constant.

**Pull request closed without merging**
