### PR TITLE
Allow checking miri and RLS with `x.py check src/tools/{miri,rls}`

### PR DESCRIPTION
**Pull request by jyn514**
Helps with https://github.com/rust-lang/rust/issues/80639.

@Xanewok would you find this useful for RLS too?

### CODE REVIEW

**Comment by jyn514** [comment]
Oh hmm I think checking miri needs to be off by default since it's out-of-tree.

**Comment by Xanewok** [comment]
If this doesn't add extra maintenance and this adds support for `x.py check src/tools/rls` in addition to `x.py test src/tools/rls`, then I think it'd make a great addition I'd say, yeah.

**Comment by jyn514** [comment]
cc @RalfJung btw - hopefully this is helpful :)

**Pull request merged**
