### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Linking failed in a rollup https://github.com/rust-lang/rust/pull/90479#issuecomment-956583093
but I hope that's just spurious.. :s

**Comment by lnicola** [comment]
Caused by https://github.com/rust-lang/libc/pull/2451, we need to pull in `libkvm` in the Rust CI image.

**Pull request merged**
