### PR TITLE
Add long error explanation for E0312

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #61137.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I didn't touch the ui tests so why is it failing? O.o

**Comment by mati865** [comment]
Guess you'll have to bless the tests:
```diff
- For more information about this error, try `rustc --explain E0478`.
+ Some errors have detailed explanations: E0312, E0478.
+ For more information about an error, try `rustc --explain E0312`. 
```

**Comment by JohnCSimon** [comment]
Ping from triage
@eddyb - This PR looks like it's ready for review / approval. 
cc: @GuillaumeGomez 
Thanks.

**Pull request merged**
