### PR TITLE
Remove the grammar from the reference

### PR DESCRIPTION
**Pull request by mdinger**
From https://github.com/rust-lang/rust/issues/24723#issuecomment-95636827 :

> Yes, I've been meaning to just remove it in favor of GRAMMAR.md
> - steveklabnik

### CODE REVIEW

**Comment by mdinger** [comment]
Updated with a few more removals. Searching for `ebnf` didn't find anything else but text may talk about the grammar still. You won't discover that without reading though.

**Comment by mdinger** [comment]
Rebased. Basically deletes the ebnf from the reference and moves some of the recent reference changes to the grammar. Until this is done, the reference is probably have a tendency to be more up to date than the grammar because that's what people look at.

The reference was definitely different at a few places suggesting more recent work.

**Comment by mdinger** [comment]
Let me know when/if you want this. I'm gonna hold off on rebasing until then because I'll just need to keep doing it.

**Comment by steveklabnik** [comment]
I do in the general case, yeah, but with the reference editing, people are changing it.

**Comment by mdinger** [comment]
I can roll up the reference changes into one I think. That might work.

**Comment by mdinger** [comment]
@steveklabnik This rolls all the reference changes into one PR

**Comment by steveklabnik** [comment]
I'd rather let bors handle all those normally rather than doing some kind of manual rollup

**Comment by mdinger** [comment]
Okay. Reverted. I only did it because I was afraid of merge conflicts. I don't know how bors handles them.

**Pull request merged**
