### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #75949 (Try to improve the documentation of `filter()` and `filter_map()`.)
 - #76128 (Use Arc::clone and Rc::clone in documentation)
 - #76157 (Update tracking issue for const_caller_location)
 - #76229 (Add missing link in README)
 - #76273 (Move some Vec UI tests into alloc unit tests)
 - #76274 (Allow try blocks as the argument to return expressions)
 - #76307 (Disable use of `--eh-frame-hdr` on wasm32.)
 - #76326 (Fix rust.use-lld when linker is not set)
 - #76331 (Account for version number in NtIdent hack)
 - #76341 (Update llvm-project to include PR 73)
 - #76370 (Fix dropck issue of SyncOnceCell.)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by jyn514** [comment]
Looks spurious.
```
  Downloaded bitflags v1.2.1
warning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `racer v2.1.38` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `lzma-sys v0.1.16` within 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `lzma-sys v0.1.16` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `racer v2.1.38` within 30s)
error: failed to download from `https://crates.io/api/v1/crates/racer/2.1.38/download`

Caused by:
  [28] Timeout was reached (download of `racer v2.1.38` failed to transfer more than 10 bytes in 30s)
', src/tools/tidy/src/deps.rs:202:20
```

**Comment by Dylan-DPC** [comment]
yep gonna roll a new rollup

**Pull request closed without merging**
