### PR TITLE
4 billion statements per block ought to be enough for anybody

### PR DESCRIPTION
**Pull request by scottmcm**
Unsure whether this will really matter, but it can make a bunch of things somewhat smaller -- this halves the size of `mir::Location`, for example.

r? @ghost

### CODE REVIEW

**Comment by Ezrashaw** [comment]
What?! I needed 18446744073709551616 statements in a single block. In fact I was just about to proposing increasing the limit to `u128` (340282366920938463463374607431768211456) which will future proof me as my (very small amount of) code grows.

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 8e3be4bf0f3fa4014120401e9a38a417f58062f4

**Comment by scottmcm** [comment]
Since I see you reacted here,
r? @cjgillot 

Thoughts on if this is worth bothering?  The perf looks pretty neutral to me, so up to you if you think the clarity is helpful or if it's a whatever and should just be closed.

**Comment by cjgillot** [comment]
I concur, it's probably not worth bothering.

Location does not appear in query results, so should have no notable effect on max-rss either. The perf report concludes to a small regression in incr-count, probably missing inlining somewhere?

**Pull request closed without merging**
