### PR TITLE
Stabilize get_type_id

### LINKED ISSUE #27745: Tracking issue for type_id stabilization
The method `get_type_id` in `Any` is intended to support reflection. It's currently unstable in favor of using an associated constant instead.

### PR DESCRIPTION
**Pull request by tmccombs**
Fixes #27745

### CODE REVIEW

**Comment by est31** [comment]
Only read half of the thread but shouldn't the function be renamed to `type_id`?

**Comment by aidanhs** [comment]
There didn't seem to be consensus in the tracking issue for stabilisation during the fcp and there was a  request for more information on whether there's any important use-case waiting on it landing in stable. @tmccombs, perhaps it would be better to comment in the tracking issue with this if you have feedback? Otherwise, nothing has changed since the last fcp.

Regardless, I'll leave to the libs team.
r? @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the PR @tmccombs! Unfortunately I think there may be a bug in fcp where I registered a [blocking concern](https://github.com/rust-lang/rust/issues/27745#issuecomment-374220769) to block stabilizing this method but it didn't halt the FCP process.

As @aidanhs mentioned though if you've got thoughts they'd be most welcome on the issue!

**Comment by tmccombs** [comment]
Oh, I missed that when I was reading through the tracking issue.

**Pull request closed without merging**
