### PR TITLE
Replace `rustc_data_structures::thin_vec::ThinVec` with `thin_vec::ThinVec`

### PR DESCRIPTION
**Pull request by nnethercote**
`rustc_data_structures::thin_vec::ThinVec` looks like this:
```
pub struct ThinVec<T>(Option<Box<Vec<T>>>);
```
It's just a zero word if the vector is empty, but requires two
allocations if it is non-empty. So it's only usable in cases where the
vector is empty most of the time.

This commit removes it in favour of `thin_vec::ThinVec`, which is also
word-sized, but stores the length and capacity in the same allocation as
the elements. It's good in a wider variety of situation, e.g. in enum
variants where the vector is usually/always non-empty.

The commit also:
- Sorts some `Cargo.toml` dependency lists, to make additions easier.
- Sorts some `use` item lists, to make additions easier.
- Changes `clean_trait_ref_with_bindings` to take a
  `ThinVec<TypeBinding>` rather than a `&[TypeBinding]`, because this
  avoid some unnecessary allocations.

r? @spastorino

### CODE REVIEW

**Comment by spastorino** [comment]
@nnethercote I didn't check the code yet, just read your description but ... I was wondering if the perf results were the results you were expecting :). Can you comment on that?.

**Comment by nnethercote** [comment]
Yes, this is disappointing. I'll have to see if I can optimize `thin-vec`'s code.

**Comment by Kobzol** [comment]
I already tried this once in `rustdoc` with similar results. One annoying thing with these global updates is that it's not easy to see the individual changes. It might very well be that e.g. 80 % of places where `ThinVec` is used were improved, but the rest regressed so bad that it swayed the total results.

**Comment by nnethercote** [comment]
> I already tried this once in `rustdoc` with similar results.

Is there a PR?

**Comment by nnethercote** [comment]
(I already fixed a bug and made some small improvements to `thin-vec`.)

**Comment by Kobzol** [comment]
> Is there a PR?

Hmm, I found https://github.com/rust-lang/rust/pull/92514, but that's about thin slices, not thin vecs. I probably didn't even send a PR and just tested it locally, but I remember using the `thin_vec` crate instead of the `rustc` `ThinVec` and not seeing any improvements. But that could have changed since then of course, and I think that I only tested `rustdoc`.

**Comment by nnethercote** [comment]
Hopefully https://github.com/Gankra/thin-vec/pull/34 will fix most/all of the problems.

**Comment by nnethercote** [comment]
The new perf results are a lot closer to neutral, though still slightly on the regression side. @spastorino: I will try out a few other things, no need to review yet.

**Comment by spastorino** [comment]
@nnethercote :+1:

**Comment by nnethercote** [comment]
@spastorino The improvements now slightly outweigh the regressions. I don't entirely trust the last set of results, because I think there is some noise in these results. But I think it's close enough to performance-neutral to proceed.

**Comment by nnethercote** [comment]
Ugh, the post-merge perf run looked very different to the pre-merge perf run, despite there being no change to the code. Clearly a lot of noise here, and hard to know which results to trust. I'll see if I can get any follow-up improvements.

**Comment by rylev** [comment]
@nnethercote any ideas on follow ups here? The results seem like they're partially noise, but some would appear to be real issues.

**Comment by nnethercote** [comment]
Nothing right now, though I have a couple of experiments still to run. But `thin_vec::ThinVec` is a sufficiently useful tool when it comes to shrinking data structures in general that I'd like to keep it in place regardess. In general, the old `rustc_data_structure` one was good for cases where the vector is nearly almost always empty (e.g. attributes on expressions) but awful in any other case due to the double allocation. `thin_vec` has much wider applicability.

**Pull request merged**
