### PR TITLE
Bump to 1.25.0

### PR DESCRIPTION
**Pull request by alexcrichton**
* Bump the release version to 1.25
* Bump the bootstrap compiler to the recent beta
* Allow using unstable rustdoc features on beta - this fix has been applied to
  the beta branch but needed to go to the master branch as well.

### CODE REVIEW

**Comment by estebank** [comment]
```
[00:06:01]    Compiling rustc_errors v0.0.0 (file:///checkout/src/librustc_errors)
[00:06:14] error: internal compiler error: error writing metadata for triple `x86_64-unknown-linux-gnu` and crate `libsyntax`, error: other os error, cause: None
[00:06:14]    --> libsyntax/lib.rs:154:1
[00:06:14]     |
[00:06:14] 154 | __build_diagnostic_array! { libsyntax, DIAGNOSTICS }
[00:06:14]     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:06:14] 
[00:06:14] note: the compiler unexpectedly panicked. this is a bug.
[00:06:14] 
[00:06:14] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:06:14] 
[00:06:14] note: rustc 1.24.0-beta.1 (5b496b726 2018-01-02) running on x86_64-unknown-linux-gnu
[00:06:14] 
[00:06:14] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:451:9
[00:06:14] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:06:14] 
[00:06:14] error: Could not compile `syntax`.
```

**Comment by kennytm** [comment]
@bors r-

Cannot run error index generator. 

```
[00:38:12] thread 'main' panicked at 'env var `RUSTC_ERROR_METADATA_DST` isn't set', libcore/option.rs:891:5
[00:38:12] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:38:12] 
[00:38:12] 
[00:38:12] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/error_index_generator" "html" "/checkout/obj/build/x86_64-unknown-lin
```

**Comment by kennytm** [comment]
Still the same error.

```
Testing error-index stage2
[01:34:50] thread 'main' panicked at 'env var `RUSTC_ERROR_METADATA_DST` isn't set', libcore/option.rs:891:5
[01:34:50] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:34:50] 
[01:34:50] 
[01:34:50] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/error_index_generator" "markdown" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md"
[01:34:50] expected success, got: exit code: 101
[01:34:50] 
[01:34:50] 
[01:34:50] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
```

**Comment by kennytm** [comment]
`x86_64-gnu-incremental`.

```
[00:01:44]    Compiling build_helper v0.1.0 (file:///checkout/src/build_helper)
[00:01:44] error: conflicting paths for `-Z incremental` and `-C incremental` specified: /tmp/rust-incr-cache versus /checkout/obj/build/bootstrap/debug/incremental
[00:01:44] 
[00:01:44] error: Could not compile `build_helper`.
[00:01:44] 
[00:01:44] To learn more, run the command again with --verbose.
[00:01:44] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:44] Build completed unsuccessfully in 0:00:00
```

**Comment by alexcrichton** [comment]
@bors: r+

You know, one of these days bumping the bootstrap compiler will actually be a pleasant affair.

**Comment by kennytm** [comment]
Could not compile stylo on `x86_64-pc-windows-msvc` due to "The system cannot find the file specified. (os error 2)"

```
  Compiling style_traits v0.0.1 (file:///C:/projects/rust/build/ct/servo/components/style_traits)
warning: the type of this value must be known in this context
    --> components\style\gecko\wrapper.rs:1777:30
     |
1777 |         (self.0 as *const _).hash(state);
     |                              ^^^^
     |
note: lint level defined here
    --> components\style\lib.rs:26:9
     |
26   | #![deny(warnings)]
     |         ^^^^^^^^
     = note: #[warn(tyvar_behind_raw_pointer)] implied by #[warn(warnings)]
     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
     = note: for more information, see issue #46906 <https://github.com/rust-lang/rust/issues/46906>
warning: the type of this value must be known in this context
   --> components\style\gecko_bindings\sugar\ownership.rs:112:42
    |
112 |         debug_assert!(!(ptr as *const _).is_null());
    |                                          ^^^^^^^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #46906 <https://github.com/rust-lang/rust/issues/46906>
error: failed to remove C:\projects\rust\build\ct\servo\target\debug\deps\style-24ff635d097fd20b.style-gecko_bindings-structs-root-js.rcgu.o: The system cannot find the file specified. (os error 2)
error: failed to remove C:\projects\rust\build\ct\servo\target\debug\deps\style-24ff635d097fd20b.style-gecko_bindings-structs-root-js.volatile.rcgu.o: The system cannot find the file specified. (os error 2)
error: failed to remove C:\projects\rust\build\ct\servo\target\debug\deps\style-24ff635d097fd20b.style-gecko_bindings-structs-root-js.rcgu.bytecode.encoded: The system cannot find the file specified. (os error 2)
error: failed to remove C:\projects\rust\build\ct\servo\target\debug\deps\style-24ff635d097fd20b.style-gecko_bindings-structs-root-js.volatile.rcgu.bytecode.encoded: The system cannot find the file specified. (os error 2)
warning: Error finalizing incremental compilation session directory `\\?\C:\projects\rust\build\ct\servo\target\debug\incremental\style-3dw81kydn5x5v\s-ex2oqkzms9-1tey9ap-working`: The system cannot find the file specified. (os error 2)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.25.0-dev running on x86_64-pc-windows-msvc
thread 'rustc' panicked at 'librustc\session\mod.rs:645: Trying to invalidate IncrCompSession `InvalidBecauseOfErrors { session_directory: "\\\\?\\C:\\projects\\rust\\build\\ct\\servo\\target\\debug\\incremental\\style-3dw81kydn5x5v\\s-ex2oqkzms9-1tey9ap-working" }`', librustc\session\mod.rs:1130:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `style`.
```

**Comment by andjo403** [comment]
Is it only me that is surprised that I got no compilation time improvement of rustc when this landed?
tested to see so I had not missed anything with cleaning the repo of all untracked files and then build the commit before and after this commit and there was only 4sec difference between the builds.
Was expecting that the #46910 was going to give some improvements.

**Pull request merged**
