### PR TITLE
Prevent duplicated impl on foreign types

### LINKED ISSUE #53689: rustdoc repeats implementation 13 times
This has probably already been filed... but rustdoc displays an impl 13 times [here](https://doc.rust-lang.org/nightly/std/borrow/trait.ToOwned.html#foreign-impls).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #53689.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Is there a way we can reproduce this so we can test it? The change is small enough that it looks fine (though i wonder if there's a deeper issue causing those duplicates to get added in the first place) but i'm hesitant to take it on its own.

**Comment by QuietMisdreavus** [comment]
(Closed by accident, oops...)

**Comment by GuillaumeGomez** [comment]
The issue is actually "easy": the `T` represents multiple types, therefore, the current path duplicates check doesn't work since they're different `T` everytime.

Also for the test, the better one would be the UI one. I'm waiting for it to be merged before adding test for this fix. Do you want me to open an issue for it?

**Comment by QuietMisdreavus** [comment]
Isn't there a way we can use a `@count` rule in a regular rustdoc test that could track this? It seems like a perfect fit for it.

**Comment by GuillaumeGomez** [comment]
It is, just thought it wasn't a great idea.

**Comment by QuietMisdreavus** [comment]
If you think you can get a better test in later on, then i guess it's fine.

@bors r+ rollup

**Pull request merged**
