### PR TITLE
Prefer not to early return from derived visitables

### PR DESCRIPTION
**Pull request by eggyal**
LLVM is not able to tail-call optimise the final early return, as there instructions that follow it.  Making that call the returned expression resolves this. (As identified in https://github.com/rust-lang/rust/pull/117896#issuecomment-2066221568).

r? wg-compiler-performance

### CODE REVIEW

**Comment by eggyal** [comment]
Hm.  Maybe it's not correct to seek review from the wg.

Not sure who to request instead.  r? types

**Comment by lqd** [comment]
@rust-timer build 4c24faf0a8c709baf83bca3e381b6d1463695e03

**Comment by lcnr** [comment]
the perf results seem slightly negative. Do you still want to merge this?

**Comment by eggyal** [comment]
Let me investigate - had seen quite different results locally, albeit there were other variables at play too.  I'll try to isolate them and figure it out!

@rustbot author

**Pull request closed without merging**
