### PR TITLE
Replace german by english word

### PR DESCRIPTION
**Pull request by ParadoxSpiral**
Credit to finding goes to SusWombat on freenode.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Wo, weird. :open_mouth: 

Thanks!

r=me @steveklabnik

**Comment by rkruppe** [comment]
Isn't "verboten" a normal loan word in English, with slightly stronger meaning than "forbidden"? I mean, I'm German so I can't judge how weird this is for the average English speaker, native or non-native, but I was under the impression that this is perfectly valid English.

**Comment by apasel422** [comment]
See https://github.com/rust-lang/rust/pulls?q=is%3Apr+verboten+is%3Aclosed.

**Comment by ParadoxSpiral** [comment]
Oh, didn't know that.
Is there some way to make a comment that won't be displayed, to prevent iteration 4 of this PR?
Something like: "Note: verboten is a legal english word. See https://www.oxforddictionaries.com/de/definition/englisch/verboten"

**Comment by steveklabnik** [comment]
Yes, @rkruppe is right. Just like how "ballet" is a French word that's English by now.

Anywho, as I'm re-writing the book right now, this will eventually just go away, and I still ultimately like it. So thanks for the PR, but I'm gonna let it live in the book a little while longer :smile:

**Pull request closed without merging**
