### PR TITLE
Try to fix perf regression in rustdoc after hir attributes

### PR DESCRIPTION
**Pull request by jdonszelmann**
Slight performance regression introduced in #131808 

r? @jieyouxu

### CODE REVIEW

**Comment by jieyouxu** [comment]
Looks good. Thanks!

@bors r+ rollup

**Comment by jdonszelmann** [comment]
Does it? I still wanted to revisit this cause it doesn't actually solve the problem completely. It's a small improvement but there's still something wrong

**Comment by Kobzol** [comment]
More improvements are always welcome, but this does in fact seem to fully resolve the original perf. regression. Good job :)

**Pull request merged**
