### PR TITLE
Remove "gender" from code of conduct, keep only "gender identity and expression"

### PR DESCRIPTION
**Pull request by Manishearth**
Mirrors https://github.com/rust-lang/rust-www/pull/954 . See that pull
request for motivation.

### CODE REVIEW

**Comment by zackmdavis** [comment]
I'm not overly concerned about the exact wording, because we trust that the community team will handle any problems with common sense and empathy; we don't need to worry about loopholes or "bugs" in an insufficiently-precisely-worded code of conduct in the way we need to worry about bugs in our code. However, it does seem worth noting that a bad actor who mistreated cis women and trans men on the basis of their assigned sex at birth would not be doing so on the basis of gender identity and expression (which cis women and trans men don't share).

**Comment by Manishearth** [comment]
Your point about gender identity applies equally to "gender", though. The point of this change is that they mean the same thing and attempting to draw a distinction in not good.

**Comment by joshlf** [comment]
@zackmdavis I thought about this problem after your comment and @Manishearth's, and while I originally was going to suggest adding "sex" in addition to "gender," that raises its own concerns. In the end, I think that we can reasonably expect people to understand that the kind of mistreatment you describe is covered under the spirit of this policy, and thus there shouldn't be any problem with the community team enforcing based on that spirit.

**Pull request merged**
