### PR TITLE
optimize Range[Inclusive].count()

### PR DESCRIPTION
**Pull request by llogiq**
This special-cases count() for ranges to reduce them to simple arithmetic.

Open questions:

* How to deal with 128bit types?
* What further tests are needed?

### CODE REVIEW

**Comment by jonas-schievink** [comment]
The [`Iterator::count`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.count) docs say: "The method does no guarding against overflows, so counting elements of an iterator with more than usize::MAX elements either produces the wrong result or panics. **If debug assertions are enabled, a panic is guaranteed.**"

`wrapping_sub` won't produce a panic even in debug mode, so perhaps a regular `-` is better?

**Comment by scottmcm** [comment]
Apparently last time this was tried, it hit type inference weirdness: https://github.com/rust-lang/rust/issues/39975#issuecomment-357024045  Maybe that's what's causing the travis failure?

Also, is this even needed?  There's `len` for when you want the O(1) guarantee, and it seems that LLVM already turns `Range::count` into a `sub` in release: https://godbolt.org/g/FGaWje

**Review by mark-i-m — APPROVED** [review]

**Comment by scottmcm** [comment]
Sorry, I should have said that with https://github.com/rust-lang/rust/pull/48012 (part of the conflicting merge commit above), LLVM will also unloop the `RangeInclusive` version.  Godbolt isn't updated as of writing, but https://play.rust-lang.org/?gist=f0b127c0dd48a1b9971166bd59a6e815&version=nightly&mode=release

(Now, llvm is being a bit dumb here, since it's explicitly branching to return `1` when `x == y` instead of calculating `x-y+1` -- also `1`, of course -- but I don't think that's a big deal.)

**Comment by BatmanAoD** [comment]
@llogiq Ping from triage; is this ready for re-review?

**Comment by llogiq** [comment]
I'm going to close this for now, now that #48012 has landed, the wins are negligible.

**Pull request closed without merging**
