### PR TITLE
Used bold and italic in the markdown to make the stack and heap docum…

### PR DESCRIPTION
**Pull request by Shiney**
…entation clearer

I could not use colors as suggested for #29854 because Github doesn't support these in markdown, however this solution may be better for color-blind readers.

### CODE REVIEW

**Comment by huonw** [comment]
r? @steveklabnik 

(I was thinking the colour could be done via `<span style="color:..."></span>` tags, which the documentation on the website rendered via rustdoc will display, although doing that is clearly much more annoying than bold and italic.)

**Comment by steveklabnik** [comment]
Ah interesting! I like this idea.

@Shiney , if it isn't too much work, would you mind:

1. adding a sentence or two explicitly mentioning that the names are connected to the styling
2. Squashing this down to one commit

Thank you!

And yes, we could do colors inline. Let's see how this works and maybe do that in the future, depending.

**Comment by Shiney** [comment]
Okay, I think I've done all the git voodo required to squash the commits to one commit...

**Comment by steveklabnik** [comment]
You have! Thanks so much.

@bors: r+ rollup

**Pull request merged**
