### PR TITLE
Implement negation for wrapping numerals.

### LINKED ISSUE #33037: Neg for Wrapping<T>
`Neg` seems to be missing for `Wrapping<T>`. This was mentioned, and promptly forgotten about, earlier:

https://github.com/rust-lang/rust/issues/27755#issuecomment-166981405

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #33037

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Impls are insta-stable, stability attributes have no effect on them

**Comment by alexcrichton** [comment]
Thanks for the PR @notriddle! As @jonas-schievink mentioned we unfortunately don't read stability annotations on `impl` blocks, so this'll be instantly stable regardless so we may as well tag it with `#[stable]` with a since of 0.10.0

I'll tag this with T-libs as well to be sure it comes up during triage.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to merge. Thanks again for the PR @notriddle!

@bors: r+ 8a8c432f7471a76bdb9179fe622968f6eb381c85

**Comment by arielb1** [comment]
```
---- test_cargo_freshness::rebuild_tests_if_lib_changes stdout ----
	thread 'test_cargo_freshness::rebuild_tests_if_lib_changes' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "The process cannot access the file because it is being used by another process." } }', C:\bot\slave\auto-win-msvc-64-cargotest\build\src\libcore\result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test_cargo_freshness::rebuild_tests_if_lib_changes
```

cc @alexcrichton 

can has RUST_BACKTRACE plz?

@bors retry

**Comment by alexcrichton** [comment]
@arielb1 

I've opened up https://github.com/rust-lang/cargo/issues/2650, and I've seen this issue quite a few times on Cargo itself unfortunately.

I haven't been able to reproduce locally yet, though, to debug.

**Pull request merged**
