### PR TITLE
Put all cached values into a central struct instead of just the stable hash

### PR DESCRIPTION
**Pull request by oli-obk**
cc @nnethercote 

this allows re-use of the type for Predicate without duplicating all the logic for the non-hash cached fields

### CODE REVIEW

**Comment by nnethercote** [comment]
@oli-obk: there is no explanation for the motivation here. Is it purely a code cleanup?

**Comment by oli-obk** [comment]
Yea, I plan to deduplicate logic between Ty and Predicate (and possibly others in the future). The `Predicate` work in https://github.com/rust-lang/rust/pull/94487 duplicates most of the `Ty` logic

**Review by wesleywiser — APPROVED** [review]
lgtm! Might be worth checking the rustc dev guide to see if `TyS` or `PredicateS` are mentioned there and updating it with the appropriate new type names (for instance: https://rustc-dev-guide.rust-lang.org/memory.html?highlight=predicates#example-tytys).

**Pull request merged**
