### PR TITLE
discard default auto trait impls if explicit ones exist

### LINKED ISSUE #84857: auto trait candidate selection is unsound
```rust
struct Always<T, U>(T, U);
unsafe impl<T, U> Send for Always<T, U> {}
struct Foo<T, U>(Always<T, U>);

trait False {}
unsafe impl<U: False> Send for Foo<u32, U> {}

trait WithAssoc {
    type Output;
}
impl<T: Send> WithAssoc for T {
    type Output = Self;
}
impl WithAssoc for Foo<u32, ()> {
    type Output = Box<i32>;
}

fn generic<T, U>(v: Foo<T, U>, f: fn(<Foo<T, U> as WithAssoc>::Output) -> i32) {
    f(foo(v));
}

fn foo<T: Send>(x: T) -> <T as WithAssoc>::Output {
    x
}

fn main() {
    generic(Foo(Always(0, ())), |b| *b);
}
```
> Segmentation fault (core dumped)

---

There are two impls of `Send` for `Foo`, the explicit `impl<U: False> Send for Foo<u32, U>` and the implicit one if all fields are `Send`. The implicit one always holds in this example.

Candidate selection only acknowledges the existence of the implicit impl if the explicit one is known to not apply even when ignoring where bounds.

For `Foo<T, U>: Send` candidate selection can't use  `impl<U: False> Send for Foo<u32, U>`, because `Foo<T, U>` is more generic than `Foo<u32, U>`. So we use the implicit impl which always applies.

For `Foo<u32, ()>` the explicit impl does apply, ignoring where bounds. This impl gets rejected however, as `(): False` does not hold. As we don't consider the implicit impl in this case we therefore accept `impl WithAssoc for Foo<u32, ()>` during coherence.

We now have two arbitrary overlapping impls which is unsound.

### PR DESCRIPTION
**Pull request by lcnr**
fixes #84857

definitely still far from being UwU

When implementing an auto trait for `&'a SomeType` that auto trait is now not implemented for `&&T` which is unfortunate xx

r? @nikomatsakis

### CODE REVIEW

**Comment by lcnr** [comment]
don't have the capacity to work on this rn

**Comment by lcnr** [comment]
@craterbot check

**Comment by lcnr** [comment]
@craterbot check

**Comment by lcnr** [comment]
woops

@bors try

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

cc rust-lang/crater#590

**Comment by lcnr** [comment]
alright, looking through the regressions:

- https://crates.io/crates/one-of/0.2.3: expected, impl for `(T, T)` disables `(T, U)` impls
- https://crates.io/crates/distinct/0.1.1: impl for `PairOfPhantoms<T, T>` disables all `PairOfPhantoms<T, U>` impls
- https://crates.io/crates/imagequant/4.0.0-beta.2: `Sync` impl for `SeaCow<'_, *const T>` https://github.com/ImageOptim/libimagequant/blob/3d825b5b01f465fa9c9dc44b29b5a7ed35c4fa4f/src/seacow.rs#L13 disables `Sync` for `Seacow<_, T>` with `T: Send`
-  https://crates.io/crates/negative-impl/0.1.1: https://github.com/taiki-e/negative-impl/blob/e048d2de5df290d93f7d2d93a7262110fc45ac2b/tests/test.rs#L43 :(

Then 8 crates with query cycles because of opaque types, have to figure these one out. The above regressions are unfortunate, if expected.

**Comment by lcnr** [comment]
@bors try

going to rerun crater for the regressed crates

**Comment by lcnr** [comment]
@craterbot  name=pr-85048-2 start=stable end=try#a0aab45a34400a5afa9e3246429a7455540b55d2 mode=check crates=https://crater-reports.s3.amazonaws.com/pr-85048/retry-regressed-list.txt

**Comment by lcnr** [comment]
@craterbot name=pr-85048-2 end=try#a0aab45a34400a5afa9e3246429a7455540b55d2 mode=check crates=https://crater-reports.s3.amazonaws.com/pr-85048/retry-regressed-list.txt

**Comment by lcnr** [comment]
@craterbot name=pr-85048-2 start=stable end=try#a0aab45a34400a5afa9e3246429a7455540b55d2 mode=check-only crates=https://crater-reports.s3.amazonaws.com/pr-85048/retry-regressed-list.txt

**Comment by lcnr** [comment]
@craterbot run name=pr-85048-2 start=stable end=try#a0aab45a34400a5afa9e3246429a7455540b55d2 mode=check-only crates=https://crater-reports.s3.amazonaws.com/pr-85048/retry-regressed-list.txt

**Comment by nikomatsakis** [comment]
@lcnr and I discussed this today. Our conclusion was that while we do believe this PR should land, and it fixes a bug in the auto trait implementation that gave it unexpected semantics, we don't feel good about breaking the `Sync` impl in https://crates.io/crates/imagequant/4.0.0-beta.2 ([link](https://github.com/ImageOptim/libimagequant/blob/3d825b5b01f465fa9c9dc44b29b5a7ed35c4fa4f/src/seacow.rs#L13)) without a good workaround.

Two possible ways to resolve this:

* Make auto traits marker traits
* Negative impl coherence integration (https://github.com/rust-lang/negative-impls-initiative)

Either would permit a second impl like `impl<T: Send> Send for Cow<'_, T>`.

@lcnr talked about modifying the PR to land as a future compatibility warning in the meantime.

**Comment by Mark-Simulacrum** [comment]
@craterbot edit p=5

**Comment by lcnr** [comment]
alright, so we're left with only the expected auto trait fallout. Going to write a lint for that in a different pr for now.

**Comment by nikomatsakis** [comment]
Now that #93267 is merged, @lcnr, shall we close this?

**Comment by lcnr** [comment]
we could also just merge the breakage in the same version as the lint :sparkles: would prefer that tbh :(

**Pull request closed without merging**
