### PR TITLE
[experiment] Cargo -Zfeatures=itarget crater run

### PR DESCRIPTION
**Pull request by ehuss**
Experiment for crater run of `cargo -Zfeatures=itarget`.

### CODE REVIEW

**Comment by ehuss** [comment]
@craterbot check

**Comment by jonas-schievink** [comment]
@craterbot check

**Comment by ehuss** [comment]
Thanks @jonas-schievink! 😄

**Comment by bjorn3** [comment]
This is for https://github.com/rust-lang/cargo/pull/7820, right?

**Comment by ehuss** [comment]
Yes.  https://github.com/rust-lang/cargo/issues/7914 to be specific.  It's only a rough smoke test, since this only tests one platform, and does not check all cargo targets (examples, tests, etc.).  But it seems like a good first step to get a sense of the impact.

**Pull request closed without merging**
