### PR TITLE
Stabilize naked_functions

### LINKED ISSUE #32408: Tracking issue for naked fns (RFC #1201)
This is the tracking issue for rust-lang/rfcs#1201.

**Note that this is intended as a (particularly) experimental feature.** 

Feedback on its design is required, as well as comparisons with [global asm](https://github.com/rust-lang/rust/issues/35119).

### LINKED ISSUE #90957: Tracking Issue for RFC #2972: Constrained Naked Functions
This is a tracking issue for the RFC "Constrained Naked Functions" (rust-lang/rfcs#2972).
The feature gate for the issue is `#![feature(naked_functions)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC
- [x] Confirm that all errors and warnings are emitted properly
- [ ] Final review of attributes that are incompatible with `#[naked]`
- [ ] Determine precise inlining gurantees
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])
  - https://github.com/rust-lang/rust/pull/134213

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None.

### PR DESCRIPTION
**Pull request by bstrie**
This stabilizes the feature described in RFC 2972, which supercedes the earlier RFC 1201.

Closes #32408
Closes #90957

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Implementation changes in this pull request looks good to me, it's ready for when the FCP over at https://github.com/rust-lang/rust/issues/90957#issuecomment-1028349868 resolves, assuming no new required changes come out of that process.

**Comment by npmccallum** [comment]
@bstrie The FCP has now completed. Please update this PR.

**Comment by JohnTitor** [comment]
Ping from triage: @bstrie Could you resolve merge conflicts and make this PR ready? Thanks!

**Comment by dancrossnyc** [comment]
Another gentle ping here? It would be really nice to see this merged.

**Comment by pnkfelix** [comment]
Based on a quick skim, I think this is blocked on PR #93809, since we do not to stabilize the `naked_function` feature without first ensuring that we only have limited the set of attributes it can be used with to the subset that we are confident about.

**Comment by est31** [comment]
:wave: Hello, I'm writing this comment in this **stabilization PR** to notify you, the authors of this PR, that https://github.com/rust-lang/rust/pull/100591 has been merged, which implemented a change in how features are stabilized.

Your PR has been filed before the change, so will likely require modifications in order to comply with the new rules. I recommend you to:

1. rebase the PR onto latest master, so that uses of the placeholder are possible.
2. replace the version numbers in the PR with the placeholder `CURRENT_RUSTC_VERSION`. For language changes, this means the version numbers in `accepted.rs` (example: 4caedbae869855a19ca49455e2cd338ae3b8c1ef). For library changes, this means the `since` fields (example e576a9b554f24a26c36c04b41c901636d190605b).

That's it! The `CURRENT_RUSTC_VERSION` placeholder will, as part of the release process, be replaced with the version number that the PR merged for. It can be used anywhere in `rust-lang/rust`, not just accepted.rs and the since fields.

If you have any questions, feel free to drop by the [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/libs.20stabilization.20placeholder), or ping me directly in this PR's thread. Thanks! :wave:

**Comment by hudson-ayers** [comment]
With today's stabilization of `asm_sym`, I suspect this feature is one of the last remaining blockers of a move to stable Rust for lots of Rust firmware / OS development (I can say this is true for Tock). So any movement on this stabilization would be great! 

(`asm_const` may still be a blocker for some, but IME it is much easier to approximate with hacks than `naked_functions`.)

**Comment by luojia65** [comment]
Mergeing this would completely boost firmware development in Rust, I'm strongly agree to stabilize this feature. We may expect some reviews but will finally get there.

**Comment by Dylan-DPC** [comment]
Going to close this pr as it is blocked on another PR which is still a draft PR and hence this will stay blocked for a long time.

**Comment by dancrossnyc** [comment]
Out of curiosity, what's the other PR?

**Comment by Lokathor** [comment]
It was linked a few comments up: https://github.com/rust-lang/rust/pull/93809

Seems to be stalled since May

**Comment by dancrossnyc** [comment]
Ah, thanks.

**Pull request closed without merging**
