### PR TITLE
rustdoc: Optimize IdMap

### PR DESCRIPTION
**Pull request by Kobzol**
Slightly optimizes `IdMap`, which is hot in `markdown_links` (context [here](https://github.com/rust-lang/rust/pull/96135#issuecomment-1103539052)). There are more improvements that can be made near this place, but this seemed like an easy win locally (although I tried it on top of https://github.com/rust-lang/rust/pull/94857, so let's see what happens without that PR).

r? @petrochenkov

### CODE REVIEW

**Comment by Kobzol** [comment]
For comparison, when this was applied after the PR which stops resolver cloning, it improved helloworld doc by almost 5 %.

**Comment by petrochenkov** [comment]
Nice.
@bors r+

**Pull request merged**
