### PR TITLE
Update env_logger to 0.5.4

### PR DESCRIPTION
**Pull request by alexcrichton**
It looks like this cuts down on the number of dependencies in env_logger and
notably cuts out a difference between a shared dependency of rls/cargo. My goal
here is to ensure that when we compile the RLS/Cargo on CI we only compile Cargo
once, and this is one step towards that!

### CODE REVIEW

**Comment by kennytm** [comment]
What about #47501?

**Comment by alexcrichton** [comment]
Oh right yeah! Looks like env_logger has since removed the `chrono` dependency, so seems like this may be able to progress?

**Comment by alexcrichton** [comment]
@bors: r=michaelwoerister

I've thrown in an update to `ena` which updates its own dependency on `log` which should also fix a performance issue related to inlining I saw

**Comment by alexcrichton** [comment]
@bors: r=michaelwoerister p=1

Also threw in an update to `derive-new`. This should stop compiling Cargo twice on CI so I'm going to give it higher priority.

**Comment by alexcrichton** [comment]
@bors: retry

pushed to master, re-kicking

**Comment by kennytm** [comment]
`check-aux` failed to build stage1-std from stage0, could not find `rustc_trans-llvm.dll`. Same error as https://github.com/rust-lang/rust/pull/48694#issuecomment-370166324.

```
error: process didn't exit successfully: `C:\projects\rust\build\bootstrap/debug/rustc -vV` (exit code: 101)
--- stdout
rustc 1.26.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-msvc
release: 1.26.0-dev

--- stderr
error: couldn't load codegen backend "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\codegen-backends\\rustc_trans-llvm.dll": "The specified module could not be found. (os error 126)"
```

**Comment by alexcrichton** [comment]
@bors: p=2

getting this ahead of the cargo submodule update

**Comment by alexcrichton** [comment]
@bors: retry

network error?

**Comment by alexcrichton** [comment]
@bors: retry

host is up for me locally?

**Comment by alexcrichton** [comment]
Although one dist builder failed, I'm merging anyway. If someone on mips breaks please ping me!

* [Travis](https://travis-ci.org/rust-lang/rust/builds/350059084?utm_source=github_status&utm_medium=notification)
* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6578)

**Comment by alexcrichton** [comment]
Gah sorry @nrc, didn't mean to break the rls! I forgot to update `rls-rustc` so I've included that update in #48549

**Comment by bdrewery** [comment]
@alexcrichton Looks like the rls-rustc update to 0.2.2 got lost somewhere to bring in https://github.com/nrc/rls-rustc/commit/c563ac9a8559532a6cf2b7cfab59d619ce760cc0:
```
error[E0599]: no method named `unwrap` found for type `()` in the current scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rls-rustc-0.2.1/src/lib.rs:25:24
   |
25 |     env_logger::init().unwrap();
   |                        ^^^^^^

```

**Comment by alexcrichton** [comment]
@bdrewery indeed!

I intended to include it in https://github.com/rust-lang/rust/pull/48549 but that PR changed so many times it fell out by accident, I'll submit a follow-up

**Pull request merged**
