### PR TITLE
core: move intrinsics.rs into intrinsics folder

### PR DESCRIPTION
**Pull request by RalfJung**
This makes the rustbot notification we have set up for this folder in `triagebot.toml` actually work. Also IMO it makes more sense to have it all in one folder.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
This feels like a limitation of triagebot that should ideally be addressed.

**Comment by lqd** [comment]
Wouldn't a `[mentions."library/core/src/intrinsics.rs"]` work here?

**Comment by RalfJung** [comment]
Yeah, but IMO it makes more sense to have all the intrinsics in one folder.

**Comment by workingjubilee** [comment]
oh boy, is it time for the annual slapfight between "people who navigate Rust modules from the module names first" and "people who navigate Rust modules via the folders first"?

**Comment by ChrisDenton** [comment]
To be clear, I have no preference but I do have a mild dislike for churn. Anyway, I'll leave it up to the reviewer.

**Comment by workingjubilee** [comment]
I mean, I obviously can't say "churn bad" given my history[^1]. :^)

[^1]: https://github.com/rust-lang/rust/pull/132574
[^2]: https://github.com/rust-lang/rust/pull/132385
[^3]: https://github.com/rust-lang/rust/pull/132246

**Comment by RalfJung** [comment]
@rust-lang/libs in the end this is up to you. :)

**Comment by Amanieu** [comment]
While I personally prefer the `mod.rs` style, here I would prefer staying consistent with the code style of the rest of the standard library and instead fixing triagebot.

**Comment by RalfJung** [comment]
The standard library has 193 `mod.rs` files. So in which sense does this PR make things not consistent with the existing code style?

**Comment by Amanieu** [comment]
The standard library also has 457 directories which indicates that the prevailing style is to not use mod.rs. Anyways, I don't feel too strongly about this so r=me unless someone else feels strongly about it.

**Comment by RalfJung** [comment]
FWIW for modules which only contain a "tests" file, the `module_name.rs` style makes a lot of sense IMO. And AFAIK no explicit decision for either style has been made by the team, so we shouldn't read too much into a a 2/3 majority. Clearly both styles are popular.

**Comment by workingjubilee** [comment]
I
1. prefer fixing triagebot with or without this PR, tbh
2. prefer not deciding the matter on a simple "vote" or "exit poll"
3. ...truly, please, do not invite me to discuss the tyranny of the majority for the next while, I will struggle to restrain myself
4. am happy to acknowledge RalfJung's interest (more generally, wg-const-eval's interest) and thus organize this directory in a way that strikes them as convenient

considering the first and last items, I am happy to r+ this if someone first opens an issue on the triagebot repo that it might be nice if the triagebot syntax worked for this case "automatically".

**Comment by RalfJung** [comment]
Triagebot is configured in terms of files and folders, not Rust modules. IMO it'd be strange if it worked any differently. So I've formulated the issue in a more open-ended way: https://github.com/rust-lang/triagebot/issues/1855.

**Comment by workingjubilee** [comment]
> Triagebot is configured in terms of files and folders, not Rust modules. IMO it'd be strange if it worked any differently. So I've formulated the issue in a more open-ended way: https://github.com/rust-lang/triagebot/issues/1855

Yes, I was struggling to phrase the "automatically" there as I was considering it.

**Comment by workingjubilee** [comment]
huzzah

@bors r=workingjubilee,Amanieu

**Pull request merged**
