### PR TITLE
Clean out a box of lint

### PR DESCRIPTION
**Pull request by camsteffen**
Removes a dynamic dispatch when building a lint diagnostic.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

As noted in the comments, this was intentional I think -- is there a reason you think those comments don't make sense anymore? Diagnostics code is generally considered "cold" so we try to reduce code size over making those functions as fast as possible, usually.

**Comment by camsteffen** [comment]
I believe this achieves avoiding codegen bloat *and* avoids dynamic dispatch since the common code is still in a separate function and is not generic.

**Comment by bjorn3** [comment]
This slightly regresses performance by up to 0.4%. It also doesn't improve bootstrap performance.

**Comment by camsteffen** [comment]
Okay, I pushed my first idea. Would be interested in another perf run.

**Comment by camsteffen** [comment]
I didn't think the perf run would work with broken tests...should I wait to fix those?

**Comment by Mark-Simulacrum** [comment]
The perf run will not run in-tree tests, though of course some of the benchmarks may not actually be able to run (if they don't compile).

**Comment by camsteffen** [comment]
Doesn't look good. Neutral at best. Closing. ✌️

**Pull request closed without merging**
