### PR TITLE
conditionally modify darwin targets to macosx targets with versions

### PR DESCRIPTION
**Pull request by froydnj**
We need this behavior so that Rust LLVM IR objects match the target triple for Clang LLVM IR objects.  This matching then convinces the linker that yes, you really can do cross-language LTO with objects from different compilers.

The newly-added tests seem to pass locally on x86_64-unknown-linux-gnu.  I haven't done a full test run or tried the new compiler in an cross-language LTO setup yet.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc me

**Comment by michaelwoerister** [comment]
Ideally we would run the cross-language LTO tests for at least one macOS job. @rust-lang/infra, is there any chance we can enable building Clang (via `--enable-lldb` and `--enable-lldb`) and run `x.py test src/test/run-make-fulldeps --test-args clang` there? That would probably have caught the bug earlier.

**Comment by michaelwoerister** [comment]
(see https://github.com/rust-lang/rust/blob/master/src/ci/docker/x86_64-gnu-debug/Dockerfile for how we run those tests for Linux)

**Comment by alexcrichton** [comment]
I don't think we have enough resources on CI to run more tests on OSX right now (especially building lots more LLVM binaries). If it works with what we have seems reasonable to turn on but otherwise we probably can't budget it at this time.

TBH it seems like this would have been good to discover the original bug but other than that it seems really unlikely to catch regressions. We've already got tests on other platforms to catch architectural problems with LTO, and a *new* OSX-specific bug coming up seems like it'd be pretty rare.

**Comment by michaelwoerister** [comment]
> TBH it seems like this would have been good to discover the original bug but other than that it seems really unlikely to catch regressions. We've already got tests on other platforms to catch architectural problems with LTO, and a new OSX-specific bug coming up seems like it'd be pretty rare.

I know there are resource constraints but in general I don't agree. Ideally I'd like every stable feature to be at least smoke-tested on every tier 1 platform. 

That being said, I don't want to block this bugfix.

@alexcrichton, would you be able to review this PR? Or do you know who'd be a good fit? The changes look good to me and there test cases, but I know virtually nothing about macOS platform conventions.

**Comment by alexcrichton** [comment]
@bors: r+

Looks good to me as well!

**Comment by froydnj** [comment]
Hm, @bors did not seem to notice the r+?

**Comment by eddyb** [comment]
@bors r=alexcrichton

(maybe it doesn't like the `:`?)

**Comment by froydnj** [comment]
> This has broken address-sanitizer support.

My plan here is to change the code that does the target triple checking:

https://github.com/rust-lang/rust/blob/c3b8ab5199af4a3c11d14b0cbdb17a641e8eee71/src/librustc_metadata/creader.rs#L771-L792

to ask `librustc_target` for the `Target` associated with the textual target, and compare the `Target`'s `llvm_target` to the `Session`'s `llvm_target`.  In an ideal world, that means both sides will go through translation to `x86_64-apple-*` and we can keep the magic of target translation in `librustc_target`.

**Comment by alexcrichton** [comment]
Hm actually that's looking up in those tables with `llvm_target`, but I think that the value of `--target` from rustc itself may be more appropriate to look up?

**Comment by froydnj** [comment]
> Hm actually that's looking up in those tables with `llvm_target`, but I think that the value of `--target` from rustc itself may be more appropriate to look up?

Ah, that's a good point!  You could make the tables contain `Target`s from those strings, or you could just propagate `--target` down and compare that instead of `llvm_target`.  I'll see what seems easier.

**Comment by froydnj** [comment]
Ah, I see, `Session` already provides access to `Options`, so accessing `--target` should not be a big deal!

**Comment by froydnj** [comment]
Added the `librustc_metadata` changes with just checking `sess.opts.target.target_triple()` as suggested; an `--enable-sanitizers` Mac build succeeded locally, along with the new testcases and what few sanitizer tests I could find.

r? @alexcrichton

**Comment by michaelwoerister** [comment]
Thanks, @froydnj! 
 
@bors r+

**Comment by ehuss** [comment]
This is causing warnings for me for very basic projects.  For example:

```rust
fn main() {}
```

```
rustc main.rs -Clto
```

```
warning: Linking two modules of different target triples: ' is 'x86_64-apple-macosx10.7.0' whereas 'main.7rcbfp3g-cgu.4' is 'x86_64-apple-darwin'


warning: Linking two modules of different target triples: ' is 'x86_64-apple-darwin' whereas 'main.7rcbfp3g-cgu.4' is 'x86_64-apple-macosx10.7.0'
```

This ends up breaking some of Cargo's testsuite.

**Comment by alexcrichton** [comment]
I suspect this warning is printed by LLVM's own linker, @froydnj are you able to take a look into this and how to suppress/ignore the warnings?

**Comment by froydnj** [comment]
I can reproduce the issue (only with `rustc` nightly, not the `rustc` from a build, for whatever reason).  Dumping `-Csave-temps`, I see a bunch of `*.no-opt.bc` files that all have the `x86_64-apple-darwin` target triple, but then everything else has the `x86_64-apple-macosx10.7.0` target triple.  (I guess the `*.no-opt.bc` files come from compiling `main.rs`, but then when `libstd` enters the picture, the more specific target triple `libstd` files have "takes over"?)

Setting `MACOSX_DEPLOYMENT_TARGET=10.9` in `rustc`'s environment appears to make everything receive the correct target triple; any value of `MACOSX_DEPLOYMENT_TARGET` seems to work just fine.

Since `MACOSX_STD_DEPLOYMENT_TARGET` is set to 10.7 for compiling `libstd`, maybe `rustc` should just use `x86_64-apple-macosx10.7.0` by default?

**Comment by alexcrichton** [comment]
Yeah I think the issue is that rustc from our nightlies is built with MACOSX_STD_DEPLOYMENT_TARGET set to 10.7 which means the bitcode for libstd itself is set to 10.7, while the bitcode for user-generated code via Cargo has no version at all (causing the mismatch).

I'd be wary to switch to 10.7 everywhere because I don't really fully understand the implications of doing so. Even if we defaulted to 10.7 the warning would come up if the user configured to 10.9 for example during LTO.

Perhaps we could patch the listed target triple for a module on OSX when we LTO them? Basically just reset the target on darwin to whatever the current target is during rustc's compilation? That would meant that libstd would get updated to x86_64-apple-darwin (no version) during normal LTO, and otherwise it would be switched to x86_64-apple-macosx10.9.0 if configured

**Comment by froydnj** [comment]
> I'd be wary to switch to 10.7 everywhere because I don't really fully understand the implications of doing so. Even if we defaulted to 10.7 the warning would come up if the user configured to 10.9 for example during LTO.

I think this wouldn't happen, because AFAICT--just by looking at the bitcode files, not by examining the LLVM code--the previously 10.7 bitcode files get munged into 10.9 bitcode files when `MACOSX_DEPLOYMENT_TARGET=10.9` is set.

> Perhaps we could patch the listed target triple for a module on OSX when we LTO them? Basically just reset the target on darwin to whatever the current target is during rustc's compilation? That would meant that libstd would get updated to x86_64-apple-darwin (no version) during normal LTO, and otherwise it would be switched to x86_64-apple-macosx10.9.0 if configured

I think this could work.  What's not clear to me is whether `rustc` can twiddle the target triple for the bitcode in this fashion.  Clearly some target triple twiddling can happen (see the above bit about 10.7 -> 10.9 libstd files), but I think that's happening in the black box of LLVM.

**Comment by alexcrichton** [comment]
Oh so if we defaulted all OSX targets to `x86_64-apple-macosx10.7.0` then that means libstd would continue to have bitcode with those targets. If 10.9 is set as the deployment target that'd mean new LLVM modules would be generated with `x86_64-apple-macosx10.9.0`, right? (that'd cause LTO warnings because libstd is 10.7 and the user-compiled bitcode is 10.7)

The modules are [linked here](https://github.com/rust-lang/rust/blob/ef01f29964df207f181bd5bcf236e41372a17273/src/rustllvm/Linker.cpp#L30-L49), and it's true yeah I'm just assuming that `Module` in LLVM has some way to just change the target on the fly, and that may not be true.

**Comment by froydnj** [comment]
> Oh so if we defaulted all OSX targets to `x86_64-apple-macosx10.7.0` then that means libstd would continue to have bitcode with those targets. If 10.9 is set as the deployment target that'd mean new LLVM modules would be generated with `x86_64-apple-macosx10.9.0`, right? (that'd cause LTO warnings because libstd is 10.7 and the user-compiled bitcode is 10.7)

My understanding is that this is incorrect: we have libstd with bitcode for 10.7 today due to the compilation environment for Rust releases.  Defautling to `x86_64-apple-macosx10.7.0` wouldn't change that state of affairs.

Defaulting to `x86_64-apple-macosx10.7.0` means that for "user" code, bitcode would be generated for that target and be compatible with the libstd bitcode.  For users that have `MACOSX_DEPLOYMENT_TARGET` set in the environment, the user code and the libstd bitcode files will both be tagged with the appropriate, matching `x86_64-apple-macosx$VERSION`.  So we shouldn't have any mismatch problems depending on whether `MACOSX_DEPLOYMENT_TARGET` is set or not.

I will try to verify that understanding today.

**Comment by alexcrichton** [comment]
>  For users that have MACOSX_DEPLOYMENT_TARGET set in the environment, the user code and the libstd bitcode files will both be tagged with the appropriate, matching x86_64-apple-macosx$VERSION.

I believe this is true of user code, but unless we rewrite the target listed in the libstd bytecode I don't think that this is true of libstd code? (in that libstd will mention 10.7 no matter what unless it's changed after-the-fact)

**Comment by froydnj** [comment]
> > For users that have MACOSX_DEPLOYMENT_TARGET set in the environment, the user code and the libstd bitcode files will both be tagged with the appropriate, matching x86_64-apple-macosx$VERSION.
> 
> I believe this is true of user code, but unless we rewrite the target listed in the libstd bytecode I don't think that this is true of libstd code? (in that libstd will mention 10.7 no matter what unless it's changed after-the-fact)

For users that have `MACOSX_DEPLOYMENT_TARGET` set in the environment, the "user" code bitcode files would be generated with the `x86_64-apple-macosx$VERSION` target.  Which, naively, does not match `x86_64-apple-macosx10.7.0` in the general case.  But the warning message comes from:

https://github.com/rust-lang/llvm-project/blob/84abffda0e03b03c62bdfc3cfeda1c2cf1f88c85/llvm/lib/Linker/IRMover.cpp#L1334-L1340

Note that the check for triples is `isCompatible`, which for `apple` vendors ignores versions:

https://github.com/rust-lang/llvm-project/blob/84abffda0e03b03c62bdfc3cfeda1c2cf1f88c85/llvm/lib/Support/Triple.cpp#L1552-L1555

And the `isCompatible` check would be satisfied with a ("user") bitcode module with `x86_64-apple-macosx10.9.0` being merged with a (libstd) bitcode module with `x86_64-apple-macosx10.7.0`.

So it would be OK (and possibly more correct, even) to default to `x86_64-apple-macosx10.7.0`.

**Comment by alexcrichton** [comment]
Fascinating! Thanks for digging and finding that @froydnj!

**Comment by nikomatsakis** [comment]
I'm nominated for beta at the request of FF team -- this is blocking them from adopting cross-language ThinLTO. (This would have to be backported with https://github.com/rust-lang/rust/pull/60788, which hasn't landed yet.)

**Comment by pnkfelix** [comment]
[discussed](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-05-16.20.2354818/near/165817925) at T-compiler meeting. Declining to backport, based on the understanding that this would need to be backported in tandem with #60788, and we declined to backport that PR for the reasons given [here](https://github.com/rust-lang/rust/pull/60788/#issuecomment-493110342)

**Pull request merged**
