### PR TITLE
Whitelist wasm32 simd128 target feature

### PR DESCRIPTION
**Pull request by gnzlbg**
r? @alexcrichton

### CODE REVIEW

**Comment by cramertj** [comment]
It looks like the target_feature gate test failed during a rollup: https://github.com/rust-lang/rust/pull/53197#issuecomment-411537736

**Comment by gnzlbg** [comment]
Damn, sorry about that. I forgot to update the `.stderr` file of the ui test that failed. I added a new line, which shifted the code down by one line, and changed the line of the error message from 28 to 29... just pushed the fix. Sorry!

**Comment by cramertj** [comment]
No worries! Thanks for the quick fix :)

@bors r=alexcrichton

**Comment by Hywan** [comment]
\o/

**Comment by gnzlbg** [comment]
FWIW this just means that rustc accepts the feature in all important places. LLVM cannot properly generate code for most (all?) `simd128` intrinsics yet.

**Pull request merged**
