### PR TITLE
Update book

### PR DESCRIPTION
**Pull request by steveklabnik**
This PR does two things:

1. update the book to include https://github.com/rust-lang/book/pull/1088
2. update to mdbook 0.1

Both of these things are big changes, so I want to land them now, well before the next branch, so we can kick the tires.

------------------------------

Locally, I'm seeing some weirdness around the reference and this: 

image

Putting this PR up so others can try and build and see if it reproduces for them.

### CODE REVIEW

**Comment by alexcrichton** [comment]
in terms of r+, r=me whenever this is good to go! I imagine though @rust-lang/docs may wish to help out with the investigation

**Comment by QuietMisdreavus** [comment]
I can confirm the reference rendering strangely. There's [an open PR](https://github.com/rust-lang-nursery/reference/pull/173) on the reference that might help with this; should we merge that first and update it here?

**Comment by Michael-F-Bryan** [comment]
You'll probably want to make sure each document's `book.toml` is updated too. We changed the [configuration file format][cfg] around a bit, but there's a [legacy shim] which will try to detect when you're using the old format and use that, emitting a warning with instructions on how to update.

Let me know if there's anything we can do from `mdbook`'s end!

[legacy shim]: https://github.com/rust-lang-nursery/mdBook/blob/186e64953062e6c812164b08478d3389947d68e4/src/config.rs#L258-L268
[cfg]: http://rust-lang-nursery.github.io/mdBook/format/config.html

**Comment by steveklabnik** [comment]
this should be good to go now 🎊

**Comment by alexcrichton** [comment]
Looks like Travis may be failing?

**Comment by steveklabnik** [comment]
Hm. very odd.

```
[00:42:55] An error occured:
[00:42:55] Rendering failed
```

not super helpful...

**Comment by Michael-F-Bryan** [comment]
> not super helpful...

Lol. We're using `error-chain` and `chain_err()` to give an error more context. If you print out the causes then it'll tell you what went wrong, we currently have a helper in `mdbook` for exactly this:

```rust
/// Prints a "backtrace" of some `Error`.
pub fn log_backtrace(e: &Error) {
    error!("Error: {}", e);

    for cause in e.iter().skip(1) {
        error!("\tCaused By: {}", cause);
    }
}
```

**Comment by steveklabnik** [comment]
@Michael-F-Bryan yeah, sorry, I typed that in haste; this behavior is reasonable.

I've pushed a commit that uses this, let's see what it says (the build succeeds for me locally)

**Comment by steveklabnik** [comment]
i was able to reproduce locally, and this is what I have:

```
Error: Rendering failed
        Caused By: Unable to copy across additional CSS and JS
        Caused By: Unable to copy theme/reference.css to C:\Users\steve\src\rs\build\x86_64-pc-windows-msvc\doc\reference\theme/reference.css
        Caused By: The system cannot find the path specified. (os error 3)
```

this make sense as to why it's only the reference that fails.

note that `C:\Users\steve\src\rs\build\x86_64-pc-windows-msvc\doc\reference\theme/` does exist, this makes me think it's `theme/reference.css` that doesn't. but that does too: `src\doc\reference\theme\reference.css` is there.

i wonder if this is an mdbook bug, not respecting the path when passed in `-d`? that is, the error is just printing `theme/reference.css`, without the prefix and that makes me suspicious.

**Comment by steveklabnik** [comment]
Yes, this is the answer, I believe. The reference has `theme/reference.css` in its config, which is then un-modified by mdbook, leading to it not respecting `-d`. working on an mdbook patch now

**Comment by steveklabnik** [comment]
https://github.com/rust-lang-nursery/mdBook/pull/598

**Comment by steveklabnik** [comment]
confirmed the fix locally, but pushed a commit up here to check on the builders too

we'll need an mdbook release in order to ship this

**Comment by steveklabnik** [comment]
well, uh looks like that's another bug: https://travis-ci.org/rust-lang/rust/builds/334450214#L2554

**Comment by steveklabnik** [comment]
okay! I'm going to wait until the release ships, and then rebase this to be more reasonable.

**Comment by Michael-F-Bryan** [comment]
> okay! I'm going to wait until the release ships, and then rebase this to be more reasonable.

[Shipped!](https://crates.io/crates/mdbook/0.1.2)

**Comment by kennytm** [comment]
@bors r-

distcheck failed due to licensing.

```
[00:13:51] invalid license MPL-2.0 in /checkout/obj/build/tmp/distcheck/src/vendor/toml-query/Cargo.toml
[00:13:51] invalid license MPL-2.0 in /checkout/obj/build/tmp/distcheck/src/vendor/is-match/Cargo.toml
```

**Comment by steveklabnik** [comment]
Why is it invalid? In that we don't accept MPL based code? I was pretty sure we had some already... and it would be kinda weird to reject Mozilla's license, heh.

**Comment by kennytm** [comment]
@steveklabnik it would be invalid if these packages were used by the standard library since it should be strictly MIT/Apache2. As these are only used for generating the book, you can add exceptions to tidy by editing https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs

**Comment by steveklabnik** [comment]
new commit pushed, that look correct? :)

**Pull request merged**
