### PR TITLE
change comments about implementation to be non-doc

### PR DESCRIPTION
**Pull request by gheoan**
Will remove implementation details from https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/config/struct.Options.html

### CODE REVIEW

**Comment by cjgillot** [comment]
Thanks for the PR @gheoan.  Could you explain a bit further the benefits of removing these comments from the documentation?

**Comment by gheoan** [comment]
@cjgillot My understanding is that the documentation is intended for users of the Options struct. These users are working on the rustc compiler or using it as a library through the rustc_interface/rustc_driver APIs and want to initialize the struct or call it's methods, but are not interested in changing the struct struct. On the other hand, the comments modified by this PR are describing the source code at the definition of the struct and are meant for people wanting to change the struct by adding new fields.

The benefit is that people looking at the docs will not read what is not intended for them, saving time.

**Comment by cjgillot** [comment]
With my incr-comp hat on, I'd do the reverse: modify the macro so docs mention for each option whether it is tracked or not.

**Comment by gheoan** [comment]
Fair enough. However, I'm not interested in making the changes you are suggesting, so I'm closing.

**Pull request closed without merging**
