### PR TITLE
Move libXtest into libX/tests

### PR DESCRIPTION
**Pull request by ghost**
This change moves:

1. `libcoretest` into `libcore/tests`
2. `libcollectionstest` into `libcollections/tests`

This is a follow-up to #39561.

r? @alexcrichton

### CODE REVIEW

**Comment by stjepang** [comment]
Tidy failed with:
```/home/stjepan/work/rust/src/libcore/tests/num/flt2dec/strategy/grisu.rs:81: platform-specific cfg: cfg!(target_env = "msvc")
/home/stjepan/work/rust/src/libcore/tests/num/flt2dec/strategy/dragon.rs:49: platform-specific cfg: cfg!(target_env = "msvc")
/home/stjepan/work/rust/src/libcore/tests/num/flt2dec/estimator.rs:14: platform-specific cfg: cfg(not(target_os = "emscripten"))
thread 'main' panicked at 'some tidy checks failed', src/tools/tidy/src/main.rs:63
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm not sure what's up with that... Any ideas?

**Comment by petrochenkov** [comment]
@stjepang 
Tidy checks that crates do not contain platform specific cfgs unless whitelisted.
I should probably search for libcoretest in tidy whitelists and whitelist it under the new location.

**Comment by alexcrichton** [comment]
@borsd: delegate=stjepang

r=me as soon as tidy is fixed

**Comment by malbarbo** [comment]
@stjepang What do you think about striping the lib prefix in the projects directory names? This looks like an ancient convention...

**Comment by alexcrichton** [comment]
Let's not rename things just yet, that's a much broader discussion. Let's stick to this PR just moving the tests to the appropriate locations.

**Comment by malbarbo** [comment]
@stjepang I would like to see all vestigial conventions vanish. You raised some interesting questions, what about open an specific issue to address these questions?

@alexcrichton You are right, that's a broader discussion. I think @stjepang (like me) was just asking an opinion, the intent was not to change this PR, sorry for being unclear.

**Pull request merged**
