### PR TITLE
Forbid non-derefable types explicitly in unsizing casts

### LINKED ISSUE #75118: ICE when coercing `NonNull<[T; 0]>` to `NonNull<[T]>` in const fn
### Code

```Rust
use core::ptr::NonNull;

pub const fn dangling_slice<T>() -> NonNull<[T]> {
    NonNull::<[T; 0]>::dangling()
}
```

### Meta

`rustc --version --verbose`:
```
1.46.0-beta.2

(2020-07-23 6f959902b3103c49ca98)
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_mir/transform/qualify_min_const_fn.rs:196:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-beta.2 (6f959902b 2020-07-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_mir/transform/qualify_min_const_fn.rs:196:58
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:50
  15: rustc_mir::transform::qualify_min_const_fn::is_min_const_fn
  16: rustc_mir::transform::check_consts::validation::Validator::check_body
  17: rustc_mir::transform::mir_const_qualif
  18: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_const_qualif>::compute
  19: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  20: rustc_data_structures::stack::ensure_sufficient_stack
  21: rustc_query_system::query::plumbing::get_query_impl
  22: rustc_mir::transform::mir_validated
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_validated>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_mir::borrow_check::mir_borrowck
  28: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  29: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  30: rustc_data_structures::stack::ensure_sufficient_stack
  31: rustc_query_system::query::plumbing::get_query_impl
  32: rustc_query_system::query::plumbing::ensure_query_impl
  33: rustc_session::utils::<impl rustc_session::session::Session>::time
  34: rustc_interface::passes::analysis
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  36: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  37: rustc_query_system::query::plumbing::get_query_impl
  38: rustc_middle::ty::context::tls::enter_global
  39: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  40: rustc_span::with_source_map
  41: rustc_interface::interface::create_compiler_and_run
  42: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-beta.2 (6f959902b 2020-07-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_const_qualif] const checking `dangling`
#1 [mir_validated] processing `dangling`
#2 [mir_borrowck] borrow-checking `dangling`
#3 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #75118
r? @oli-obk

### CODE REVIEW

**Comment by JohnTitor** [comment]
Seems spurious:
```
2020-08-04T13:24:52.4138230Z Cloning into '/Users/runner/work/rust/rust/src/tools/rls'...
2020-08-04T13:24:52.5558570Z fatal: unable to access 'https://github.com/rust-lang/rls.git/': transfer closed with outstanding read data remaining
2020-08-04T13:24:52.5600530Z fatal: clone of 'https://github.com/rust-lang/rls.git' into submodule path '/Users/runner/work/rust/rust/src/tools/rls' failed
2020-08-04T13:24:52.5608690Z Failed to clone 'src/tools/rls'. Retry scheduled
2020-08-04T13:24:52.7158790Z Cloning into '/Users/runner/work/rust/rust/src/tools/rls'...
2020-08-04T13:24:52.7179710Z fatal: unable to access 'https://github.com/rust-lang/rls.git/': transfer closed with outstanding read data remaining
2020-08-04T13:24:52.7180500Z The command has failed after 5 attempts.
2020-08-04T13:24:52.7184470Z fatal: clone of 'https://github.com/rust-lang/rls.git' into submodule path '/Users/runner/work/rust/rust/src/tools/rls' failed
2020-08-04T13:24:52.7185190Z Failed to clone 'src/tools/rls' a second time, aborting
2020-08-04T13:24:52.7185720Z + [[ 5 -lt 5 ]]
2020-08-04T13:24:52.7186320Z + echo 'The command has failed after 5 attempts.'
2020-08-04T13:24:52.7186540Z + return 1
2020-08-04T13:24:57.7345840Z ##[error]Process completed with exit code 1.
```

@bors retry

**Comment by JohnTitor** [comment]
@oli-obk Could we beta-nominate this? The failure has reached beta and this is an obvious fix.

**Comment by JohnTitor** [comment]
Beta-nominating with this reason: https://github.com/rust-lang/rust/pull/75136#issuecomment-668774651

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/21643weeklymeeting2020080554818.html#206146557) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Pull request merged**
