### PR TITLE
Migrate `rustc_passes` diagnostics

### PR DESCRIPTION
**Pull request by naritanara**
This PR migrates `rustc_passes` diagnostics to use the new translatable system

@rustbot label +A-translation
r? rust-lang/diagnostics
cc #100717

### CODE REVIEW

**Review by davidtwco — COMMENTED** [review]
This a great start! Looks like there are still some diagnostics to port according to the CI failures :)

**Comment by davidtwco** [comment]
🎉 Thanks for your continued work on this!

**Comment by davidtwco** [comment]
Thanks for keeping going with this, please mark it was "ready for review" when you'd like to merge this - we don't need to wait for the whole crate to be complete, whatever you prefer.

**Comment by rdvdev2** [comment]
> Thanks for keeping going with this, please mark it was "ready for review" when you'd like to merge this - we don't need to wait for the whole crate to be complete, whatever you prefer.

This weekend I plan to advance a good bit with this. I would have done earlier, but I messed up with my local clone and lost the day fixing it. The joys of git.

**Comment by rdvdev2** [comment]
Due to college, I'll have to abandon the PR. Anyone can feel free to retake my work from the point I left it (I'll keep my fork available). Thanks for all the help with this, and I hope I can contribute with something else in the future.

**Comment by CleanCut** [comment]
I have opened #102110 to pick up this work. I would love for some collaborators to come and join me in fixing this one, as it is rather large. I outlined the TODO items in the PR description. Come join in!

**Pull request closed without merging**
