### PR TITLE
Allow configuring the parent GitHub repository

### PR DESCRIPTION
**Pull request by emilyalbini**
The git integration in build_helper hardcoded `rust-lang/rust` as the parent GitHub repository, and `master` as the branch name. This works great for `rust-lang/rust`, but causes problems in downstream forks like Ferrocene whenever those functions are invoked (like `./x fmt`).

In `src/stage0.json` there was already a configuration key for the name of the nightly branch, but it wasn't used by build_helper. This PR adds the `github_repository` key to the file, and requires both values to be passed to build_helper whenever a git function is called. This will allow downstream forks to tweak the values.

### CODE REVIEW

**Comment by albertlarsan68** [comment]
This is a good idea, thanks!
Can you update `config.example.toml` with the default values and explanation about the new config?

**Comment by pietroalbini** [comment]
> Can you update config.example.toml with the default values and explanation about the new config?

Right now the configuration is not in `config.toml`/`config.example.toml`, but in `src/stage0.json`, for two reasons:

* `nightly_branch` was already there, so I added `github_repository` alongside it.
* This is not really a configuration the user should set, but a configuration of the *repository/fork* itself. It should work without users having to set any config value when cloning Ferrocene (or any other fork of the compiler). I agree `src/stage0.json` is suboptimal for this, but there is no other place like that right now.

**Comment by albertlarsan68** [comment]
My bad, I was thinking it was an option in config.toml.
I'll review this when I have the time

**Review by albertlarsan68 — APPROVED** [review]
LGTM, I would prefer if `github_repository` was renamed to `git_repository`.
r=me with the change

**Pull request merged**
