### PR TITLE
[r+] Implement fully qualified UFCS expressions.

### PR DESCRIPTION
**Pull request by eddyb**
Working towards #16293, this adds support for `<T as Trait>::method` in expressions.

### CODE REVIEW

**Comment by eddyb** [comment]
@nikomatsakis I almost want to separate `ast::Path` into a `Vec<ast::PathSegment>` and a terminal `ast::PathSegment` - most of the code out there that touches paths uses `.last().unwrap()` and having to produce `ast::Path` from `ast::QPath` isn't really optimal (but I chose it instead of duplicating lots of `resolve` and `typeck` logic).

**Comment by nikomatsakis** [comment]
r+. This looks great. The one thing I'd like to see is a more diverse array of tests, for example:

1. A run-pass test where the trait has a type parameter (`<Foo as Trait<X>>::item()`).
2. A run-pass test where the trait has a region parameter.
3. A compile-fail test where the self type that is provided doesn't match what the user provides (`<i32 as Trait>::method(3_u32)`).

**Comment by nikomatsakis** [comment]
@eddyb regarding Path, I personally would like to refactor it into something recursive, rather than the current vector of path segments. I don't think the vector is particularly helpful. Having something recursive (a cons list, basically) would also make trivial to extract the last name, as you say.

**Comment by huonw** [comment]
Is it worth having some tests with default type parameters (in traits and types)?

Also, does using `_` work? e.g. `<Option<_> as PartialEq>::eq(&Some(1u8), &None)`.

**Comment by eddyb** [comment]
@huonw [yes it does](https://github.com/rust-lang/rust/pull/21077/files#diff-ac2bf0abda4475571ccbceabc1e67b37R90) - also, the implementation results in `<_ as Foo>::bar` being identical to `Foo::bar`, type-wise.

**Comment by eddyb** [comment]
I don't think I handle `<T as PolyTrait>::foo` correctly, given `trait PolyTrait<T>` - that is, it works, just like `PolyTrait::foo` does, where the type param is optional.
I guess I'll just use `instantiate_trait_ref`, which will require that all type params are present.

**Comment by nikomatsakis** [comment]
as we said on IRC, I actually expected `<T as PolyTrait>::foo` to make fresh type variables and work. But I could probably go either way on this, given that we have `_`,

**Pull request merged**
