### PR TITLE
Const prop should finish propagation into user defined variables

### LINKED ISSUE #66638: Const Prop does not finish propagation into user defined variables
The const prop pass handles propagation into temporaries correctly but doesn't propagate temporaries into user defined variables. 

[example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7986a477ff05c3436704d62a4a151ae5)

```rust
fn main() {
  let x = 2 + 2;
}
```

currently compiles to the following MIR:

```
fn  main() -> () {
    let mut _0: ();
    let _1: i32;
    let mut _2: (i32, bool);
    scope 1 {
    }

    bb0: {
        StorageLive(_1);
        (_2.0: i32) = const 4i32;
        (_2.1: bool) = const false;
        _1 = move (_2.0: i32);
        StorageDead(_1);
        return;
    }
}
```

but should ideally compile to:

```
fn  main() -> () {
    let mut _0: ();
    let _1: i32;
    scope 1 {
    }

    bb0: {
        StorageLive(_1);
        _1 = const 4i32;
        StorageDead(_1);
        return;
    }
}
```

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #66638

~~Temporarily rebased on top of #67015 to get those fixes.~~

r? @oli-obk

### CODE REVIEW

**Comment by wesleywiser** [comment]
@bors try
@rustc-timer queue

**Comment by wesleywiser** [comment]
@rust-timer queue

**Comment by wesleywiser** [comment]
@rust-timer build 556f29a19882b5611b6b72969739532774e61d65

**Comment by kennytm** [comment]
@rust-timer build 556f29a19882b5611b6b72969739532774e61d65

**Comment by wesleywiser** [comment]
Fixed failing unit test and rebased.

**Comment by wesleywiser** [comment]
Rebased & fixed test output.

@bors r+

**Comment by oli-obk** [comment]
oh no :see_no_evil: this PR changes diagnostics in clippy. I guess lets keep it on hold until after the beta cutoff

**Comment by wesleywiser** [comment]
I guess this is ready to go?

**Pull request merged**
