### PR TITLE
[WIP] proc_macro: check non-interned handles for "leaks" between/after invocations.

### PR DESCRIPTION
**Pull request by eddyb**
Inspired by #63804, this PR panics on some forms of `proc_macro` API misuse more eagerly (when a proc macro invocation finishes, as opposed to on the first use of a "leaked" handle).

However, it's unsure whether there are legitimate leaks of `proc_macro` "objects" in the wild, and @Centril suggested we try it out on crater first (check-only mode).

### CODE REVIEW

**Comment by eddyb** [comment]
@craterbot run mode=check-only

**Comment by pietroalbini** [comment]
@craterbot crates=full

**Comment by eddyb** [comment]
I'm not sure we should land this, given that all 3 regressions in https://github.com/rust-lang/rust/pull/64398#issuecomment-533186558 that can be directly attributed to this PR are "forgetful" leaks, *not* stashing `proc_macro` objects in thread-local storage.

**Comment by oli-obk** [comment]
Maybe just make it a lint that ppl can silence?

**Comment by Alexendoo** [comment]
Ping from triage, any updates? @eddyb

**Comment by eddyb** [comment]
@oli-obk I'm not exactly sure how - at least it's on the server side of the proc-macro bridge - maybe I can add a method somewhere to report it and the default is `eprintln!` but `rustc` warns instead?

At least `rustc` would know the invocation and would be able to point to it, hmm.

**Comment by eddyb** [comment]
Blocked on https://github.com/rust-lang/crater/pull/461 to find the exact set of regressions.

**Comment by ecstatic-morse** [comment]
@Mark-Simulacrum this was included in the crater run for #63831, which caused ~700 regressions. We want to be sure that that PR didn't mask any regressions in this one. I commented on the broken PR, but I meant for eddyb to trigger runs on all the others. I don't have crater perms, but could you trigger a run with:

@craterbot check crates=https://gist.githubusercontent.com/ecstatic-morse/ca6fe943de6937db635143472358d90d/raw/177739189815b3c52a7f69b494dbb91ea2d25e1d/gistfile1.txt

**Comment by Mark-Simulacrum** [comment]
@craterbot check crates=https://gist.githubusercontent.com/ecstatic-morse/ca6fe943de6937db635143472358d90d/raw/177739189815b3c52a7f69b494dbb91ea2d25e1d/gistfile1.txt

**Comment by Mark-Simulacrum** [comment]
@craterbot p=1 Bumping priority since this is a short run

**Comment by Mark-Simulacrum** [comment]
@craterbot p=1

Bumping priority since this is a short run

**Comment by eddyb** [comment]
I doubt this is worth doing - these handles can't actually be (mis)used anyway.

**Pull request closed without merging**
