### PR TITLE
Use `TyCtxt::mk_str` instead of interned str

### PR DESCRIPTION
**Pull request by compiler-errors**
Split out of #107939. Hopefully the usages of the interned str type aren't so hot that this is a perf regression. Guess we'll see..

r? @oli-obk

### CODE REVIEW

**Comment by compiler-errors** [comment]
(I guess for now we could keep the interned string around and just go through `mk_str` anyways, but I'll gauge the perf impact regardless)

**Comment by oli-obk** [comment]
The regression looks real

```
4,851,078  ???:<rustc_middle::ty::context::CtxtInterners>::intern_ty
3,407,918  ???:<rustc_const_eval::interpret::memory::AllocRefMut<rustc_middle::mir::interpret::AllocId, ()>>::write_scalar
```

so we could look into the alternative strategy of pre-allocating the def id in https://github.com/rust-lang/rust/pull/107939 and thus having an interned `ty::Adt` at TyCtxt creation time.

**Pull request closed without merging**
