### PR TITLE
Add missing `rustc_promotable` attribute to unsigned `min_value` and `max_value`

### LINKED ISSUE #55806: apint fails to compile on beta
apint fails to compile (https://crater-reports.s3.amazonaws.com/beta-1.31-1/beta-2018-10-30/reg/apint-0.2.0/log.txt) on beta. Note that the crate must be compiled in test mode.
```
Nov 03 02:59:10.198 INFO kablam!    Compiling apint v0.2.0 (/source)
Nov 03 02:59:13.651 INFO kablam! error[E0597]: borrowed value does not live long enough
Nov 03 02:59:13.651 INFO kablam!    --> src/apint/constructors.rs:429:11
Nov 03 02:59:13.651 INFO kablam!     |
Nov 03 02:59:13.651 INFO kablam! 429 |               .chain([
Nov 03 02:59:13.651 INFO kablam!     |  ____________________^
Nov 03 02:59:13.651 INFO kablam! 430 | |                 u8::max_value(),
Nov 03 02:59:13.651 INFO kablam! 431 | |                 10,
Nov 03 02:59:13.651 INFO kablam! 432 | |                 42,
Nov 03 02:59:13.651 INFO kablam! 433 | |                 99,
Nov 03 02:59:13.651 INFO kablam! 434 | |                 123
Nov 03 02:59:13.651 INFO kablam! 435 | |             ].into_iter()
Nov 03 02:59:13.651 INFO kablam!     | |_____________^ temporary value does not live long enough
Nov 03 02:59:13.651 INFO kablam! 436 |                .map(|v| *v))
Nov 03 02:59:13.651 INFO kablam! 437 |       }
Nov 03 02:59:13.651 INFO kablam!     |       - temporary value only lives until here
Nov 03 02:59:13.651 INFO kablam!     |
Nov 03 02:59:13.651 INFO kablam!     = note: borrowed value must be valid for the static lifetime...
Nov 03 02:59:13.651 INFO kablam! 
Nov 03 02:59:13.657 INFO kablam! error[E0597]: borrowed value does not live long enough
Nov 03 02:59:13.657 INFO kablam!    --> src/apint/constructors.rs:480:11
Nov 03 02:59:13.657 INFO kablam!     |
Nov 03 02:59:13.657 INFO kablam! 480 |               .chain([
Nov 03 02:59:13.657 INFO kablam!     |  ____________________^
Nov 03 02:59:13.657 INFO kablam! 481 | |                 u16::max_value(),
Nov 03 02:59:13.657 INFO kablam! 482 | |                 500,
Nov 03 02:59:13.657 INFO kablam! 483 | |                 1000,
Nov 03 02:59:13.657 INFO kablam! ...   |
Nov 03 02:59:13.657 INFO kablam! 486 | |                 42_000
Nov 03 02:59:13.657 INFO kablam! 487 | |             ].into_iter().map(|v| *v))
Nov 03 02:59:13.657 INFO kablam!     | |_____________^ temporary value does not live long enough
Nov 03 02:59:13.657 INFO kablam! 488 |       }
Nov 03 02:59:13.657 INFO kablam!     |       - temporary value only lives until here
Nov 03 02:59:13.657 INFO kablam!     |
Nov 03 02:59:13.657 INFO kablam!     = note: borrowed value must be valid for the static lifetime...
Nov 03 02:59:13.657 INFO kablam! 
Nov 03 02:59:13.658 INFO kablam! error[E0597]: borrowed value does not live long enough
Nov 03 02:59:13.658 INFO kablam!    --> src/apint/constructors.rs:513:11
Nov 03 02:59:13.658 INFO kablam!     |
Nov 03 02:59:13.658 INFO kablam! 513 |               .chain([
Nov 03 02:59:13.658 INFO kablam!     |  ____________________^
Nov 03 02:59:13.658 INFO kablam! 514 | |                 u32::max_value(),
Nov 03 02:59:13.658 INFO kablam! 515 | |                 1_000_000,
Nov 03 02:59:13.658 INFO kablam! 516 | |                 999_999_999,
Nov 03 02:59:13.658 INFO kablam! 517 | |                 1_234_567_890
Nov 03 02:59:13.658 INFO kablam! 518 | |             ].into_iter().map(|v| *v))
Nov 03 02:59:13.658 INFO kablam!     | |_____________^ temporary value does not live long enough
Nov 03 02:59:13.658 INFO kablam! 519 |       }
Nov 03 02:59:13.658 INFO kablam!     |       - temporary value only lives until here
Nov 03 02:59:13.659 INFO kablam!     |
Nov 03 02:59:13.659 INFO kablam!     = note: borrowed value must be valid for the static lifetime...
Nov 03 02:59:13.659 INFO kablam! 
Nov 03 02:59:13.663 INFO kablam! error[E0597]: borrowed value does not live long enough
Nov 03 02:59:13.663 INFO kablam!    --> src/apint/constructors.rs:544:11
Nov 03 02:59:13.663 INFO kablam!     |
Nov 03 02:59:13.663 INFO kablam! 544 |               .chain([
Nov 03 02:59:13.663 INFO kablam!     |  ____________________^
Nov 03 02:59:13.663 INFO kablam! 545 | |                 u64::max_value(),
Nov 03 02:59:13.663 INFO kablam! 546 | |                 1_000_000_000_000,
Nov 03 02:59:13.663 INFO kablam! 547 | |                 999_999_999_999_999_999,
Nov 03 02:59:13.663 INFO kablam! 548 | |                 0x0123_4567_89AB_CDEF
Nov 03 02:59:13.663 INFO kablam! 549 | |             ].into_iter().map(|v| *v))
Nov 03 02:59:13.663 INFO kablam!     | |_____________^ temporary value does not live long enough
Nov 03 02:59:13.663 INFO kablam! 550 |       }
Nov 03 02:59:13.664 INFO kablam!     |       - temporary value only lives until here
Nov 03 02:59:13.664 INFO kablam!     |
Nov 03 02:59:13.664 INFO kablam!     = note: borrowed value must be valid for the static lifetime...
Nov 03 02:59:13.664 INFO kablam! 
Nov 03 02:59:13.671 INFO kablam! error[E0597]: borrowed value does not live long enough
Nov 03 02:59:13.671 INFO kablam!    --> src/apint/constructors.rs:575:11
Nov 03 02:59:13.671 INFO kablam!     |
Nov 03 02:59:13.671 INFO kablam! 575 |               .chain([
Nov 03 02:59:13.671 INFO kablam!     |  ____________________^
Nov 03 02:59:13.671 INFO kablam! 576 | |                 u128::max_value(),
Nov 03 02:59:13.671 INFO kablam! 577 | |                 1_000_000_000_000_000_000_000_000,
Nov 03 02:59:13.671 INFO kablam! 578 | |                 999_999_999_999_999_999_999_999_999,
Nov 03 02:59:13.671 INFO kablam! 579 | |                 0x0123_4567_89AB_CDEF_FEDC_BA98_7654_3210
Nov 03 02:59:13.671 INFO kablam! 580 | |             ].into_iter().map(|v| *v))
Nov 03 02:59:13.671 INFO kablam!     | |_____________^ temporary value does not live long enough
Nov 03 02:59:13.672 INFO kablam! 581 |       }
Nov 03 02:59:13.672 INFO kablam!     |       - temporary value only lives until here
Nov 03 02:59:13.672 INFO kablam!     |
Nov 03 02:59:13.672 INFO kablam!     = note: borrowed value must be valid for the static lifetime...
Nov 03 02:59:13.672 INFO kablam! 
Nov 03 02:59:14.105 INFO kablam! error: aborting due to 5 previous errors
```

### PR DESCRIPTION
**Pull request by oli-obk**
cc @pnkfelix 

fixes #55806

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This seems fine to me from a code standpoint but I'm going to r? @eddyb or someone else from the compiler team as I'm not sure what the general policy for rustc_promotable is. If the policy is fine with this then r=me

**Comment by oli-obk** [comment]
This fixes an oversight in https://github.com/rust-lang/rust/pull/53851 where I only added the attribute to the signed integer types but not the unsigned ones (they are in a different macro)

**Review by eddyb — APPROVED** [review]

**Comment by estebank** [comment]
Accepting for beta backport.

**Comment by pietroalbini** [comment]
FYI, `beta-nominated` should still be present until the actual backport is done. [More information](https://forge.rust-lang.org/beta-backporting.html)

**Pull request merged**
