### PR TITLE
fix str::split_at_mut() example

### PR DESCRIPTION
**Pull request by bungcip**
fix documentation issue #32933

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 2bf000349a06f874f8bb6c67a37d3ff533e36165 rollup

Thanks!

**Comment by GuillaumeGomez** [comment]
Showing what's different with the `split_at` method would have been nice. Here, you just changed the mutability and didn't show what it was used for.

Don't you agree @alexcrichton?

**Comment by alexcrichton** [comment]
Sure!

**Comment by GuillaumeGomez** [comment]
Arf, I guess it's too late to r- the PR...

**Comment by bungcip** [comment]
@GuillaumeGomez, well actually I want to create a different example using asciiExt trait but according to https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html#tymethod.make_ascii_uppercase,
that function is unstable. I don't want to create example that only work on nightly.

```rust
fn main() {
    use std::ascii::AsciiExt;
    let mut s = "Per Martin-Löf".to_string();

    {
        let (first, last) = s.split_at_mut(3);

        first.make_ascii_uppercase();
        last.make_ascii_lowercase();
        
        assert_eq!("PER", first);
        assert_eq!(" martin-löf", last);
    }
    
    assert_eq!("PER martin-löf", s)
}
```

**Comment by GuillaumeGomez** [comment]
Since you're writing examples displayed only on nightly for the moment, it doesn't matter. :p

**Pull request merged**
