### PR TITLE
Necromancing (putting back some removed error codes explanations)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Even if the error code isn't used by the compiler anymore, we should keep the explanations in case people using old versions of the compiler want to read them.

r? @Dylan-DPC

### CODE REVIEW

**Comment by petrochenkov** [comment]
Do you plan to do this for all the removed errors?
It's kind of ok, if the error was simply relaxed.
However, some errors were reported as two different codes based on internal details with entirely non-representative explanations, some errors were related to unstable features. I really wouldn't want to bring all of that to the up-to-date compiler.

**Comment by GuillaumeGomez** [comment]
Not all of them. Some didn't even have an explanation so there is no point into adding those back... Like I said, this is mainly for users using old versions of the compiler. And I also marked all of them as not being used by the compiler anymore (as a title, so no confusion).

**Comment by GuillaumeGomez** [comment]
Fixed tidy.

**Comment by petrochenkov** [comment]
@bors r-
This is a questionable change, so I'm going to nominate it for the next compiler team triage meeting.

**Comment by Dylan-DPC** [comment]
Ah okay. No issues :+1:

**Comment by pnkfelix** [comment]
We [discussed](https://zulip-archive.rust-lang.org/131828tcompiler/76822weeklymeeting2019120554818.html#182670934) this in the T-compiler meeting last week.

The general consensus was that we are not totally sure what our plan is with respect to preservation of error codes and error explanations, but we are pretty sure that whatever the plan is, it does not involve having to build explanations for old+unused error codes into the current compiler.

((We **would** like to figure out what our actual long term plan *is* for error codes (and internationalization, etc. But that is probably a topic at least for a design meeting; not something where one would jump straight to writing code.))

**Pull request closed without merging**
