### PR TITLE
Refactor pretty printing slightly

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This doesn't introduce any functional changes (that I'm aware of). The primary intention here is to clean up the code a little. Each commit is intended to stand alone, reviewing commit-by-commit may be easiest.

### CODE REVIEW

**Comment by carols10cents** [comment]
Aaaand one of the osx builds did that thing where it doesn't start :( Restarting it...

**Comment by aidanhs** [comment]
@Mark-Simulacrum looks like this has conflicts that need resolving

**Comment by Mark-Simulacrum** [comment]
Okay, well, I resolved the conflicts but still need to rebase the branch -- I'll leave it as-is until I get a chance to do that...

**Comment by Mark-Simulacrum** [comment]
Rebased.

**Comment by jseyfried** [comment]
Nice!
@bors r+

**Pull request merged**
