### PR TITLE
Add documentation for hasClass function

### LINKED ISSUE #85450: Ensure that hasClass is correctly used
As discovered in https://github.com/rust-lang/rust/pull/85438, `hasClass` returns `false` when the element doesn't exist (which is normal) but that means we have to check if the element exist beforehand sometimes too.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/85450.

r? @jsha

### CODE REVIEW

**Comment by jsha** [comment]
I'm not sure this makes sense as a warning for `hasClass`. `null` is falsy, which is exactly what we'd expect. If we wanted, we could coerce it to `false`, but of course that wouldn't solve the problem.

The core of the problem in #85438 wasn't that `hasClass` was being used incorrectly. It was that we had a series of `if/else` clauses, where one of the clauses was `.. if (!hasClass(foo, "bar")) {`. That clause led to the next clause, the applicable one, not firing. In other words, I think the problem was not with `hasClass` but with the call site.

https://github.com/rust-lang/rust/blob/f510e412e93958e099334de22de375d26264e767/src/librustdoc/html/static/main.js#L477-L489

**Comment by GuillaumeGomez** [comment]
I tried to say that if the element doesn't exist, it will return something coercing to false too. But maybe it's too much... What do you think?

**Comment by jsha** [comment]
I think this comment isn't needed and winds up being just confusing to the reader. More concretely: when writing #85438, if I had read this comment, I still would have introduced the bug, because the comment matches what my expectations were: I expected `hasClass` to return falsy if the element doesn't exist. The thing I didn't realize was that we needed to proceed to the next `else` clause in case `help` doesn't exist.

**Comment by GuillaumeGomez** [comment]
Makes perfectly sense. Closing then!

**Pull request closed without merging**
