### PR TITLE
Rollup of 15 pull requests

### PR DESCRIPTION
**Pull request by emilyalbini**
Successful merges:

 - #55527 (Implement checked_add_duration for SystemTime)
 - #55564 (test/linkage-visibility: Ignore on musl targets)
 - #55672 (miri: accept extern types in structs if they are the only field)
 - #55827 (A few tweaks to iterations/collecting)
 - #55834 (Forward the ABI of the non-zero sized fields of an union if they have the same ABI)
 - #55867 (do not panic just because cargo failed)
 - #55894 (miri enum discriminant handling: Fix treatment of pointers, better error when it is undef)
 - #55916 (Make miri value visitor usfeful for mutation)
 - #55921 (Add placeholder types)
 - #55936 (save-analysis: be even more aggressive about ignorning macro-generated defs)
 - #55949 (ty: return impl Iterator from Predicate::walk_tys)
 - #55952 (Update to Clang 7 on CI.)
 - #55953 (#53488 Refactoring UpvarId)
 - #55962 (rustdoc: properly calculate spans for intra-doc link resolution errors)
 - #55963 (Stress test for MPSC)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Removed #55857 and #55663.

@bors r+ p=16

**Comment by ljedrz** [comment]
@pietroalbini this could be caused by #55871; while I don't see why, an earlier PR containing a broader version of that commit was hitting LLVM OOM.

**Comment by pietroalbini** [comment]
Removed https://github.com/rust-lang/rust/pull/55871

@bors r+ p=15

**Pull request closed without merging**
