### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
12 commits in fc1d58fd0531a57a6b942a14cdcdbcb82ece16f3..7b7af3077bff8d60b7f124189bc9de227d3063a9
2024-02-09 15:54:29 +0000 to 2024-02-17 14:13:00 +0000
- Remove unnecessary `use` statement in metabuild (rust-lang/cargo#13455)
- chore: Update snapbox (rust-lang/cargo#13441)
- chore(deps): update openssl to 3.2.1 again (rust-lang/cargo#13449)
- fix(test): Suggest `--` for libtest arguments (rust-lang/cargo#13448)
- chore(ci): Drop MSRV:1 patch field (rust-lang/cargo#13442)
- fix(add): Remove inconsistent period (rust-lang/cargo#13446)
- fix(add): Ensure users know a feature is being created (rust-lang/cargo#13434)
- Update tests for changes in latest nightly (rust-lang/cargo#13444)
- docs: Minor clarification of build script metadata. (rust-lang/cargo#13436)
- Fix old_cargos tests (rust-lang/cargo#13435)
- Fix confusing error messages for sparse index replaced source (rust-lang/cargo#13433)
- Enable edition migration for 2024 (rust-lang/cargo#13429)

### CODE REVIEW

**Comment by weihanglo** [comment]
<https://github.com/rust-lang/rust/pull/119007#issuecomment-1859231819>

`yum install perl-core` is added

@bors try

**Comment by weihanglo** [comment]
Randomly ping t-infra. @Kobzol is it appropriate to add `yum install perl-core` in docker for building OpenSSL v3 for Cargo?

**Comment by Mark-Simulacrum** [comment]
That should be fine.

**Pull request merged**
