### PR TITLE
add rustc-demangle assertion on mangled symbol

### PR DESCRIPTION
**Pull request by csmoe**
cc https://github.com/rust-lang/rust/issues/60705#issuecomment-844880365
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks, @csmoe! Let's wait and see what the crater run at https://github.com/rust-lang/rust/pull/85530 yields.

**Comment by michaelwoerister** [comment]
I'm also wondering if this should be a `debug_assert!` instead. @Mark-Simulacrum, do you have any idea how much coverage we would get if this is only a debug assertion? Does anybody use a compiler with debug assertions enabled?

**Comment by Mark-Simulacrum** [comment]
Essentially only rustc developers, I'm not sure we even ship builds with debug asserts on. Do we know what performance impact we're looking at?

**Comment by csmoe** [comment]
@michaelwoerister  Or a `crater_run_assert` which checks if we are doing a crater_run through an env variable.

**Comment by Mark-Simulacrum** [comment]
Please don't try to detect crater inside rustc; if you want to test something on crater but not land it, a try build should be sufficient with it just always on, and we can run that through crater.

**Comment by michaelwoerister** [comment]
I think this is blocked on value mangling support: https://github.com/rust-lang/rust/pull/87194

Once we have that, we should at least make it a debug assertion. That way we cover everything that the compiler itself uses.

**Review by michaelwoerister — APPROVED** [review]
Thank you, @csmoe!

**Pull request merged**
