### PR TITLE
rustc_metadata: simplify the interactions between Lazy and Table.

### PR DESCRIPTION
**Pull request by eddyb**
These are small post-#59953 cleanups (including undoing some contrivances from that PR).

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Oh, it seems that I forgot about this.  Maybe someone from @rust-lang/compiler-contributors wants to review?

**Comment by Mark-Simulacrum** [comment]
r? @Mark-Simulacrum 

I'll try to make a review happen here

**Comment by michaelwoerister** [comment]
:heart:

**Comment by Mark-Simulacrum** [comment]
r=me presuming rebase isn't too big of a change

**Pull request merged**
