### PR TITLE
Check for lldb existences

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This PR name and description however are unfortunately very light on details (e.g. there's no description at all). Can you expand a bit on what this PR is doing, what the change is fixing, and perhaps the motivation as well?

**Comment by lzutao** [comment]
I'm sorry. I must have been more clear. 
The problem is if we do not detect if lldb exists, then when calling rust-lldb,
we could have something like this:
```console
% rust-lldb
/home/lzutao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-lldb: 34: exec: lldb: not found
```
With this PR, the script will check if lldb exists, and error out if lldb not found.
Also, this PR favor `$()` subcommand syntax over `` `command` ``. Which I think is more 
clear to see.

**Comment by alexcrichton** [comment]
Ok thanks for the explanation, looks good to me!

@bors: r+

**Pull request merged**
