### PR TITLE
Borrow builder only once in debug derive

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by tmiasko** [comment]
Before:

```rust
let mut debug_trait_builder = ::core::fmt::Formatter::debug_struct(f, "S");
let _ = ::core::fmt::DebugStruct::field(&mut debug_trait_builder, "a", &&(*__self_0_0));
...
::core::fmt::DebugStruct::finish(&mut debug_trait_builder)
```

After: 

```rust
let debug_trait_builder = &mut ::core::fmt::Formatter::debug_struct(f, "S");
let _ = ::core::fmt::DebugStruct::field(debug_trait_builder, "a", &&(*__self_0_0));
...
::core::fmt::DebugStruct::finish(debug_trait_builder)
```

For each call to a debug builder, this implementation reduces the number of temporaries by one and the number of statements by three at MIR level.

r? @pnkfelix

**Comment by pnkfelix** [comment]
@bors r+ rollup=never

(the results seem acceptable, but I dont want to roll them up so that they don't mask effects of other PRs)

**Comment by tmiasko** [comment]
Updated test output.

**Pull request merged**
