### PR TITLE
dbg macro: align line number to 4 digits

### LINKED ISSUE #58647: Align dbg!() and line!() output
Hello. 

Please, consider this issue as a minor.

Output of dbg!() macro will be better if it will align source code line number. I found that line!() macro does it. I think it would be nice if this macro always emit 4 chars, because most source code files has less than 10k lines. Consider the example:

    [some/main.rs:84] hex::encode(dst.as_ref()) = "686aca464489"
    [some/main.rs:126] hex::encode(src.as_ref()) = "f8c91afe015f"

I guess this will be better:

    [some/main.rs:  84] hex::encode(dst.as_ref()) = "686aca464489"
    [some/main.rs: 126] hex::encode(src.as_ref()) = "f8c91afe015f"

or

    [some/main.rs:0084] hex::encode(dst.as_ref()) = "686aca464489"
    [some/main.rs:0126] hex::encode(src.as_ref()) = "f8c91afe015f"

Thank you.

### PR DESCRIPTION
**Pull request by hellow554**
Fixes #58647 

I think this is worth getting some more people into this discussion. Thankfully according to [the doc](https://doc.rust-lang.org/std/macro.dbg.html)

> The exact output printed by this macro should not be relied upon and is subject to future changes.

So nobody can complain ;)

### CODE REVIEW

**Comment by Centril** [comment]
As I said on [the issue](https://github.com/rust-lang/rust/issues/58647), I am not sure that the common case would benefit from this change so I'm therefore not sure this is an improvement.

**Comment by Dylan-DPC** [comment]
ping from triage @Centril any updates on this? i'm assuming we can close this?

**Comment by Centril** [comment]
@Dylan-DPC I'm not the reviewer; r? @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the PR @hellow554, and sorry for the delay!

You're definitely right that I think we can change the output here at any time, so I think we're safe to do that. Given that this is a macro for debugging I think aligning the output seems reasonable to me in spirit, although for the actual formatting I might recommend something different. 

With a leading `0` numbers (because of the C language) can often be interpreted as octal, and I'm not sure I've ever seen a zero-padded  line number before. I also might recommend against right-aligning the number because a lot of editors special case `file:line` as a clickable link, so `file:   line` may fool them by accident. Perhaps though we could do something like:

```
[some/main.rs:84  ] hex::encode(dst.as_ref()) = "686aca464489"
[some/main.rs:126 ] hex::encode(src.as_ref()) = "f8c91afe015f"
```

which I believe would still solve the issue?

Note though that this could be pretty confusing for programs that are always under a hundred lines or so. You'd always have a few spaces at the end and you may not know what they're used for. Additionally the filenames can change between modules, so this may also make it hard to align output across multiple modules.

All-in-all I'm not entirely sure whether this ends up being worth it after digging into the details. While it's a mild cosmetic improvement it seems like a sort of niche one that brings a number of downsides with it which may not outweigh the benefit.

**Comment by Centril** [comment]
> Perhaps though we could do something like:
> 
> ```
> [some/main.rs:84  ] hex::encode(dst.as_ref()) = "686aca464489"
> [some/main.rs:126 ] hex::encode(src.as_ref()) = "f8c91afe015f"
> ```
> 
> which I believe would still solve the issue?

That feels rather "empty" for lack of a better term.

> Note though that this could be pretty confusing for programs that are always under a hundred lines or so. You'd always have a few spaces at the end and you may not know what they're used for. Additionally the filenames can change between modules, so this may also make it hard to align output across multiple modules.

Yep; I think we should also consider smaller modules. That feels like something to encourage. I think most modules should be sized between 100-999 so that aligns well for those. Aligning for 4 digits feels like encouraging the wrong thing.

**Comment by alexcrichton** [comment]
My point isn't so much the number of lines in a module itself but the difference between the filename length of `src/lib.rs` and `src/main.rs`, and how the `dbg!` macro doesn't attempt (and I don't think it should attempt) to cope with those differences and align everything.

**Comment by Centril** [comment]
@alexcrichton Sure; I think yours is a good point as well ;) -- any thoughts on what to do here (...and ping from triage...)?

**Comment by hellow554** [comment]
Somehow this PR slipped through my notification center... 
Thanks alex for your words and I see what you mean.  So I think I should just close this PR and therefore close the related issue?

**Comment by alexcrichton** [comment]
Sounds good to me!

**Pull request closed without merging**
