### PR TITLE
rustdoc: don't run doctests on private items (by default)

### LINKED ISSUE #30094: rustdoc --test ignores visibility
Consider [the following use case](https://gist.github.com/ilammy/9d39d412bcb9c816596d).

I'd expect rustdoc to compile and run doctests only for the _public::function_ since that's the only thing exported from the _example_ crate and thus accessible to rustdoc.

However, this is what I see (actual for current stable (1.4.0) and nightly (1.6, bac2b13a5) builds):

```
ilammy@ferocity ~/dev/rustdoc-visibility-issues
$ rustc --crate-type lib example.rs

ilammy@ferocity ~/dev/rustdoc-visibility-issues
$ rustdoc --test --library-path . example.rs

running 3 tests
test public::complex_helper_0 ... FAILED
test private::real_job_0 ... FAILED
test public::function_0 ... ok

failures:

---- public::complex_helper_0 stdout ----
        <anon>:2:16: 2:30 error: unresolved name `complex_helper` [E0425]
<anon>:2     assert_eq!(complex_helper(1, 2), 3);
                        ^~~~~~~~~~~~~~
<anon>:2:5: 2:41 note: in this expansion of assert_eq! (defined in <std macros>)

error: aborting due to previous error

---- private::real_job_0 stdout ----
        <anon>:3:9: 3:25 error: module `private` is private
<anon>:3     use example::private;
                 ^~~~~~~~~~~~~~~~
error: aborting due to previous error


failures:
    private::real_job_0
    public::complex_helper_0

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured
```

Rustdoc's intent, as I understand it, is documenting _public_ API. Private items do not show up in docs (unless one explicitly [disables the pass that strips them](https://github.com/rust-lang/rust/issues/15347#issuecomment-47828041)). I believe this should also include doctests.

It's natural to use the items being documented in doctest examples, but such examples for private items would not compile due to obvious reasons. I believe analyzing the code snippets is a bit overkill for rustdoc, but it's pretty reasonable to simply strip any doctests for private items (at least by default), assuming that they contain internal code examples and will not not compile outside of the crate being documented.

Not using documentation comments for private items or marking private code examples with `ignore` avoids the issue, but personally I think that these are poor workarounds. If private doctests are ignored by default then exporting a previously private item (together with its documentation) is simply a matter of adding **pub** to it (or to its module import in the crate). However, if any of these workarounds are used then one must explicitly convert regular comments to documentation comments and/or remove `ignore` from doctests in order to get everything right.

Some links to (somewhat) related issues:
- #15347 Add option to include private definition in the documentation
- #27104 Have rustdoc document private items, except `use` and `extern crate`

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
fixes https://github.com/rust-lang/rust/issues/30094

Currently, rustdoc will scan the whole crate for doctests, regardless of whether the docs it finds are actually being shown in documentation, or actually useful docs. This PR changes the doctest collection scan to account for module visibility. Public re-exports of items will also pull in their doctests, if their original location was private. I added a check to make sure that items are not tested twice, to make sure that re-exporting an item into multiple places (say, if the original location is private, you export it into its "canonical" location, and you also include it in a prelude).

To continue running all tests, you can pass `--document-private-items` to rustdoc, like this:

```sh
RUSTDOCFLAGS="--document-private-items" cargo test --doc
```

While typing this up, i noticed that impls inside non-module scope also get skipped here, though running private tests will catch it. If desired, i can try and add it, though i'm not sure how severe it is to be missing.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Whoops, left a "todo" in there that was already addressed. I folded the change into the proper commit and force-pushed.

**Comment by Mark-Simulacrum** [comment]
I think this will need a relatively long warning period or a edition (not 2018, it's too late) to make this change. Silently not running test cases anymore seems like a bad idea.

**Comment by GuillaumeGomez** [comment]
I thought tests were not run on private items. This way of working seems more logical to me and seems to fit the expected behavior better. However, just like @Mark-Simulacrum said, it'd be nice to wait a bit before merging a behavior change.

Once done, r=me.

**Comment by TimNN** [comment]
I agree with @Mark-Simulacrum, and would go even further and **not** do this change at all:

Given that we are saying:

* Examples in Rust Documentation are tested.
* `#[test]`s run even in private modules (IIRC).

I would assume that doctests would also run for private items (even if the documentations is not visible in the end).

**Comment by QuietMisdreavus** [comment]
I can appreciate that reasoning, and i'm willing to scrap this PR and close the linked issue as "won't fix", but there's one wrinkle that doctests have that unit tests do not: doctests are still always run on the public crate. It's impossible to actually test the item being documented properly, unless you want to include some demo code that doesn't touch it. There's no reason to actually write a doctest for a private item, and to leave such an idea open is a bit of an oversight. I've seen several comments requesting some kind of functionality to allow it because of that same parallel @TimNN mentions.

**Comment by TimNN** [comment]
Ping from triage! What is the status of this PR? I assume this needs some discussion from @rust-lang/rustdoc, so marking as such.

**Comment by liigo** [comment]
Please don't do this.

**Comment by QuietMisdreavus** [comment]
Based on discussion in this thread, i'm going to close this PR, and motion to close the linked issue as well. Such a change is too controversial to introduce, especially after the current behavior has been present for so long.

**Pull request closed without merging**
