### PR TITLE
Update hashbrown to 0.12.0

### PR DESCRIPTION
**Pull request by Amanieu**
[Changelog](https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md#v0120---2022-01-17)

### CODE REVIEW

**Comment by Amanieu** [comment]
This seems like an overall win but with a bit of noise since this code is *extremely* sensitive to inlining.

**Comment by Mark-Simulacrum** [comment]
Agreed.

@bors r+

**Comment by Amanieu** [comment]
One of the apple builders seems very slow, it's 5 hours in and still building. I don't think it's related to this PR since perf showed no negative impact on bootstrap times.

@bors retry

**Pull request merged**
