### PR TITLE
Reword "Required because of the requirements on the impl of ..."

### PR DESCRIPTION
**Pull request by cbeuw**
Rephrases the awkward "Required because of the requirements on the impl of `{trait}` for `{type}`" to "required for `{type}` to implement `{trait}`"

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors r-

i like this but maybe let's tweak this further. give me some time to do some thinking.

**Comment by Dylan-DPC** [comment]
@compiler-errors it wasnt approved, just marked never for rollup :joy:

**Comment by compiler-errors** [comment]
@Dylan-DPC -- ack, this is why I should fully wake up before I start to review emails.

**Comment by compiler-errors** [comment]
Anyways, @cbeuw, maybe let's try some wording that still mentions this is a requirement that results from another:

maybe something along the lines of "required because the impl of X for Y requires that Z"

**Comment by cbeuw** [comment]
> required because of the the impl of `X` for `Y`

I feel like this is ambiguous as to whether an impl of `X` for `Y` currently exists. It could be read as if there is an `impl X for Y` somewhere - which generally isn't the case. When this note is emitted the code is demanding the type `Y` to implement `X`, but for various reasons this isn't the case, such as due to the lack of an explicit `impl` instance or a generic type bound isn't being satisfied

**Comment by compiler-errors** [comment]
@cbeuw, this is an ImplDerivedObligation, so this requirement _should_ always be due to an impl's where-clause requirements (or implied bounds). The old messaging also mentioned impl, and i think it should preserve that.

Can you find me an example where mentioning that this is due to an impl is misleading?

**Comment by cbeuw** [comment]
> Can you find me an example where mentioning that this is due to an impl is misleading?

When the trait is supposed to be derived. For example, this test
https://github.com/rust-lang/rust/blob/0e21a27075a8c508f00d1a4430497f17ce93d5c9/src/test/ui/consts/const-blocks/fn-call-in-non-const.rs#L1-L16

The current message says "required because of the requirements on the impl of `Copy` for `Option<Bar>`", besides the roundabout phrasing, `impl Copy for Option<Bar>` does not exist in the code, and likely will never be written. We want `Option<Bar>` to be `Copy` _somehow_, and in this case an `impl` is not relevent

And in cases where the error could be resolved with an explicit `impl`, it's not always possible to write it due to the orphan rule
https://github.com/rust-lang/rust/blob/0e21a27075a8c508f00d1a4430497f17ce93d5c9/src/test/ui/integral-indexing.stderr#L1-L9

I would be nice if `impl Index<u8> for Vec<isize>` exists, but the user can't do anything about it.

As I pointed out above, this could also be misread in the opposite direction: that an `impl Index<u8> for Vec<isize>` _currently exists somewhere_ which imposed some requirements that we failed to satisfy, whereas in reality it's the other way round, that our code demanded `Vec<isize>: Index<u8>`, which does not stand.

**Comment by compiler-errors** [comment]
> As I pointed out above, this could also be misread in the opposite direction: that an impl Index<u8> for Vec<isize> currently exists somewhere which imposed some requirements that we failed to satisfy, whereas in reality it's the other way round, that our code demanded Vec<isize>: Index<u8>, which does not stand.

So the fact that this is an `ImplDerivedObligation` means that Rust is saying a bit more than just "our code demanded `Vec<isize>: Index<u8>`, which does not stand." It's saying that there _is_ an `impl` which is compatible with this demand, but the `where` clauses of that impl are not satisfied.

> The current message says "required because of the requirements on the impl of Copy for Option<Bar>", besides the roundabout phrasing, impl Copy for Option<Bar> does not exist in the code, and cannot be written. We want Option<Bar> to be Copy somehow, and in this case an impl is not relevent

I guess what we disagree on is the fact that the impl exists. Side-note that I totally agree with "required because of the requirements" is a bit roundabout, but that's a bit unrelated with my concerns about this rewording.

While it's true that `impl Copy for Option<Bar>` doesn't exist written like _that_ in any explicitly written or macro-generated code, the impl that `ObligationCauseCode::ImplDerivedObligation` is [pointing to](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/traits/struct.ImplDerivedObligationCause.html#structfield.impl_def_id) is the one that comes from [the expansion of this `derive(Copy)`](https://doc.rust-lang.org/src/core/option.rs.html#515), which _does_ exist, and is the reason that the resulting trait bound `Bar: Copy` (from the primary error) is being required in the first place.

I guess we could be more explicit, and say something like "required due to the impl of `Copy` for `Option<T>` where `T = Bar`", but that seems a bit verbose.

The problem I have with your proposed wording is that loses the fact that this is a _derived_ bound, and one that results from an `impl` (and not from, for example, the trait itself, or well-formedness, or any other reason why `Ty: Trait` would be required by the code).

**Comment by compiler-errors** [comment]
Given [this sample code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2b48b44486b7bdceb7420d88924d5450):
```rust
struct Foo;

trait Bar {}

trait Qux {}

impl<T> Bar for Option<T> where T: Qux {}

fn needs_bar(t: impl Bar) {}

fn main() {
    needs_bar(Some(Foo));
}
```

We currently say:

```
error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): the trait bound `Foo: Qux` is not satisfied
  --> src/main.rs:12:15
   |
12 |     needs_bar(Some(Foo));
   |     --------- ^^^^^^^^^ the trait `Qux` is not implemented for `Foo`
   |     |
   |     required by a bound introduced by this call
   |
   = help: the trait `Bar` is implemented for `Option<T>`
note: required because of the requirements on the impl of `Bar` for `Option<Foo>`
  --> src/main.rs:7:9
   |
7  | impl<T> Bar for Option<T> where T: Qux {}
   |         ^^^     ^^^^^^^^^
note: required by a bound in `needs_bar`
  --> src/main.rs:9:22
   |
9  | fn needs_bar(t: impl Bar) {}
   |                      ^^^ required by this bound in `needs_bar`
```

I think that the proposed rewording is a bit awkward specifically when we're actually able to point out the `impl` in code:

```
note: required because `Option<Foo>` needs to implement `Bar`
  --> src/main.rs:7:9
   |
7  | impl<T> Bar for Option<T> where T: Qux {}
   |         ^^^     ^^^^^^^^^
```

**Comment by compiler-errors** [comment]
Side-note, we could probably specify two different messages depending on if the `impl` is able to be pointed out or not. If we have a impl that is pointable, we could probably say something like "required for this `impl` to satisfy `{predicate}`" and if we don't, we could probably go with a slightly modified wording of "required for `{type}` to implement `{trait}`".

Thoughts?

**Comment by cbeuw** [comment]
I agree that `impl Copy for Option<T> where T: Copy` exists as a result of derive macro expansion, though I like to think this different from `impl Copy for Option<Bar>`, especially when specialisation comes into play.

I think having a different message when a span is immediately printed below is a good idea, and I like the "required for X to do Y" wording

On another note, in your example, it said
```
the trait `Bar` is implemented for `Option<T>`
```
but _not really_. Maybe it should point out the relevant unsatisfied predicate, i.e. "the trait `Bar` is implemented for `Option<T>` only when `T:  Qux`?

**Comment by JohnCSimon** [comment]
Ping from triage: 
@cbeuw What is the status of this PR? Can you fix the merge conflicts?


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by cbeuw** [comment]
Sorry for leaving this for a while. I've now changed it to "required for `{type}` to implement `{trait}`".

I tried to refine it to "required for this impl to satisfy `{predicate}`" when the impl block is printed below. We already have a code path for this but I don't know how to get the where clause `T: Qux` in `impl<T> Bar for Option<T> where T: Qux {}` from a [`ImplDerivedObligationCause`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/traits/struct.ImplDerivedObligationCause.html) - it seems to only contain the parent obligation, but now the current one?
https://github.com/rust-lang/rust/blob/6fa6e2dc675035b782c292d939f309de2ab734d5/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs#L2556-L2566

@rustbot ready

**Comment by compiler-errors** [comment]
Ugh, this is bitrotty of course.

Please rebase this, then r=me (i.e. write `@bors r=compiler-errors` in a github comment)

@bors delegate+ p=1

**Comment by compiler-errors** [comment]
oops haha @bors r-

**Comment by compiler-errors** [comment]
I am dumb and forgot to delegate.

@bors r+

**Pull request merged**
