### PR TITLE
Raise an error if gcov profiling and incremental compilation are both enabled

### LINKED ISSUE #50203: -Zprofile broken in nightly?
I am using `-Zprofile` to use gcov. However, the results are corrupted.

Here are my info.
```
$ cargo -V
cargo 1.26.0-nightly (008c36908 2018-04-13)
$ rustc -V
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
```

Reproduce the issue:
```
$ cargo new hello_world --bin
$ cargo rustc --bins -- -Zprofile -Copt-level=1 -Clink-dead-code -Ccodegen-units=1 -Zno-landing-pads
$ ./target/debug/hello_world
./target/debug/hello_world
Hello, world!
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x66353136)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous run count: corrupt object tag (0x37633437)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x66353136)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x63626564)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous run count: corrupt object tag (0x00456238)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x38327472)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous run count: corrupt object tag (0xa3000000)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x246e6f69)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous run count: corrupt object tag (0x36245447)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous GCDA file: corrupt arc tag (0x36626331)
profiling: /hello_world/target/debug/deps/hello_world-b633c1f029999720.gcda: cannot merge previous run count: corrupt object tag (0x00004530)

```

It works when using older version:
```
$ rustup override set nightly-2017-06-28
```

I don't know if this issue related with https://github.com/kennytm/cov/issues/18

Also: ping https://github.com/rust-lang/rust/issues/42524

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #50203.

### CODE REVIEW

**Comment by marco-c** [comment]
CC @kennytm

**Comment by eddyb** [comment]
I'm not sure this is the correct approach. Shouldn't LLVM re-generate all the necessary files?

**Comment by marco-c** [comment]
> I'm not sure this is the correct approach. Shouldn't LLVM re-generate all the necessary files?

I'm not exactly sure how incremental compilation works, so I don't know. This is just aknowledging the current situation, where you can't use them both, I think it's better than failing without an explanation. The other option would be to allow it but print a warning, like you're doing for some other features (count_llvm_insns, time_llvm_passes). In those cases the feature is half broken though, here it's completely broken.

**Comment by TimNN** [comment]
IIRC, @michaelwoerister is unavailable for reviews until early July, could someone else from @rust-lang/compiler review this?

**Comment by michaelwoerister** [comment]
Thanks for the PR, @marco-c!
It's definitely better to have an explicit early error instead of the ones reported in #50203.

@bors r+

@marco-c, would you mind opening an issue about this problem so we don't lose track of it?

**Comment by marco-c** [comment]
> @marco-c, would you mind opening an issue about this problem so we don't lose track of it?

Sure! I've opened #51983.

**Comment by michaelwoerister** [comment]
Thanks a lot!

**Pull request merged**
