### PR TITLE
Various minor cleanups to rustbuild

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This is work I did before the migration to the new rustbuild. I'd prefer to land this first, before my other PR, to make the diff a little clearer.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Nice cleanups!

**Comment by Mark-Simulacrum** [comment]
I think I broke something, need to investigate..

@bors r-

```
Build completed successfully in 0:01:46
+ python x.py test --host i686-pc-windows-msvc --target i686-pc-windows-msvc
    Finished dev [unoptimized] target(s) in 0.0 secs
thread 'main' panicked at 'no entry found for key', src\libcore\option.rs:823
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\projects\rust\build\bootstrap/debug/bootstrap test --host i686-pc-windows-msvc --target i686-pc-windows-msvc
Build completed unsuccessfully in 0:00:00
```

**Comment by Mark-Simulacrum** [comment]
Ah, found the problem.. I had changed what targets/hosts we find cc/cxx for to be only the ones passed on the command line, but I guess that's not enough.

@bors r=alexcrichton

**Pull request merged**
