### PR TITLE
Only assign dep node indices in non-incremental mode if self profiling is active

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I'm not convinced that this is worth the additional complexity. An atomic `fetch_add` should be rather cheap.

**Comment by Dylan-DPC** [comment]
Closing this based on https://github.com/rust-lang/rust/pull/68687#issuecomment-581492171 and inactivity. Thanks

**Comment by Zoxc** [comment]
`fetch_add` isn't too expensive (~17 cycles on Zen) if they are uncontended and spaced out (so the cycle cost can be hidden). In this case the `fetch_add` potentially from on all CPU cores to a single location and the code is reasonably hot. I'd rather just avoid any potential issues from this with a branch.

**Comment by nikomatsakis** [comment]
Closing this pull request as Zoxc is stepping back from compiler development; see rust-lang/team#316.

**Pull request closed without merging**
