### PR TITLE
Deny bare trait objects in src/libstd

### PR DESCRIPTION
**Pull request by ljedrz**
Enforce #![deny(bare_trait_objects)] in src/libstd.

### CODE REVIEW

**Comment by ljedrz** [comment]
Fixed with [this PR](https://github.com/rust-lang/rust/pull/52336).

**Comment by ishitatsuyuki** [comment]
Tip: cherry picking my commit doesn't interfere with merging.

**Comment by ljedrz** [comment]
@ishitatsuyuki thanks - I haven't done that yet, but it seems pretty handy; did I do it correctly?

**Comment by ishitatsuyuki** [comment]
I think it's fine.

**Comment by stokhos** [comment]
Ping from triage @ljedrz we haven't heard from you for a while, any progress on this PR?

**Comment by pietroalbini** [comment]
Closing this, rolled up in #52336.

**Comment by kennytm** [comment]
Reopening until #52336 is confirmed mergeable.

**Pull request merged**
