### PR TITLE
Match scrutinee need necessary parentheses for structs

### LINKED ISSUE #113459: `unused_parens` reported on complex enum struct-variant literal in match scrutinee expression is actually necessary
### Code

```Rust
#![allow(dead_code)]

enum State {
    Waiting { start_at: u64 }
}

fn main() {
    match (&mut State::Waiting { start_at: 0u64 }) {
        _ => {}
    }
}
```

### Current output

```Shell
warning: unnecessary parentheses around `match` scrutinee expression
 --> src/main.rs:8:11
  |
8 |     match (&mut State::Waiting { start_at: 0u64 }) {
  |           ^                                      ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
8 -     match (&mut State::Waiting { start_at: 0u64 }) {
8 +     match &mut State::Waiting { start_at: 0u64 } {
  |
```

### Desired output

```Shell
No `unused_parens` warning.
```

### Rationale and extra context

The `unused_parens` lint should not fire in this case because the parentheses are actually necessary. Otherwise, following the help to "remove these parentheses" will cause a compilation error.

```rust
error: struct literals are not allowed here
 --> src/main.rs:8:16
  |
8 |     match &mut State::Waiting { start_at: 0u64 } {
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
help: surround the struct literal with parentheses
  |
8 |     match &mut (State::Waiting { start_at: 0u64 }) {
  |                +                                 +
```

Although, following help from the *error* after applying the suggestion from the `unused_parens` lint does lead to valid code.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #113459

### CODE REVIEW

**Review by lukas-code — COMMENTED** [review]
This fix looks insufficient for chained operators, for example this still triggers the lint:
```rust
struct Foo {}

fn main() {
    match (&&Foo {}) {
        _ => {}
    }
}
```

I think the correct fix is to add a case for `AddrOf` to `contains_exterior_struct_lit` here: https://github.com/rust-lang/rust/blob/fe03b46ee4688a99d7155b4f9dcd875b6903952d/compiler/rustc_ast/src/util/parser.rs#L388-L396

**Comment by chenyukang** [comment]
@matthiaskrgr 
do you know the reason for this failure?
from the log seems it's not caused by code change.

**Comment by matthiaskrgr** [comment]
my first thought was that perhaps since the 2 weeks the PR was opened, some other changes went in or additional tests were added which the first version of the pr did not account for, but I didn't look at it in very detail.

**Comment by cjgillot** [comment]
The error is a SIGSEGV on one of the apple builders. Let's try again, see if it's a legitimate failure.
@bors r+

**Comment by klensy** [comment]
So, it isn't merged?

**Comment by chenyukang** [comment]
yes, seems failed in merging.

**Comment by chenyukang** [comment]
@matthiaskrgr
could you please help me with this PR,
seems it's tested successfully, but it's left un-merged because of the issue of:

```console
 Test was successful, but fast-forwarding failed: 422 Update is not a fast forward
```

**Comment by workingjubilee** [comment]
uhh.

**Comment by workingjubilee** [comment]
According to homu, this isn't actually approved.
I am thus reapproving it.

@bors r=cjgillot rollup=never

**Pull request merged**
