### PR TITLE
rustdoc: Collect "rustdoc-reachable" items during early doc link resolution

### PR DESCRIPTION
**Pull request by petrochenkov**
This pass only needs to know about visibilities, attributes and reexports, so it can be run early, similarly to `compute_effective_visibilities` in rustc.
Results of this pass can be used to prune the list of extern impls early thus improving performance of https://github.com/rust-lang/rust/pull/94857.

### CODE REVIEW

**Comment by petrochenkov** [comment]
This implementation is preliminary and needs perf-tuning and cleanup.
@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/107136.
@rustbot label +S-blocked

**Comment by petrochenkov** [comment]
Nice.
So it's not even blocked on https://github.com/rust-lang/rust/pull/107237.
@rustbot author

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup=never

**Comment by nnethercote** [comment]
Perf wins greatly outweigh the regressions here.

@rustbot label: +perf-regression-triaged

**Pull request merged**
