### PR TITLE
revert #48337 (`--explain` usage note)

### PR DESCRIPTION
**Pull request by zackmdavis**
See discussion on #48550 for justification.

(As the commit messages note, there were some conflicts; this wasn't a sheerly mechanical revert. But this should—pending Travis's verdict—get us back to the old extract-rendered-from-JSON UI testing regime, after which an `--explain` usage note can be reimplemented in a cleaner way at leisure.)

cc @GuillaumeGomez @estebank 

r? @petrochenkov

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm not a big fan of a revert but if we're in a hurry, we don't have a better idea... I have a work in progress to fix this which would allow to just make it work with json output.

**Comment by petrochenkov** [comment]
>I have a work in progress to fix this which would allow to just make it work with json output

Ok, let's wait for "`--explain` usage from json" then.
(I'll probably land this PR instead if "`--explain` usage from json" do not materialize in couple of weeks.)

**Comment by GuillaumeGomez** [comment]
The only remaining issue for the fix is some invalid error emission but otherwise it's almost done.

**Comment by zackmdavis** [comment]
@GuillaumeGomez awesome, let's close this in favor of #48684 :sparkling_heart:

**Pull request closed without merging**
