### PR TITLE
Use sys::unix::locks::futex* on wasm+atomics.

### PR DESCRIPTION
**Pull request by m-ou-se**
This removes the wasm-specific lock implementations and instead re-uses the implementations from sys::unix.

Tracking issue: https://github.com/rust-lang/rust/issues/93740

cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Seems reasonable to me! One question I would have though is that I believe that the wasm standard library in atomics mode is not checked on CI, so are the futex locks expected to be used outside of unix platforms? I might otherwise worry about Unix-specific features creeping into the unix-specific futex files which accidentally break wasm and we'd go awhile without figuring that out. If, however, the futex locks are used on a variety of platforms on CI that would probably reduce the likelihood of platform-specific features creeping in.

**Comment by m-ou-se** [comment]
> I might otherwise worry about Unix-specific features creeping into the unix-specific futex files which accidentally break wasm and we'd go awhile without figuring that out.

There's no standard futex API across the different Unix platforms, so there's not really any unix-specific futex features we could start using.

Breaking things through reorganizing files and modules is an issue though, as proven by how the wasm+atomics build was actually broken before this PR. ^^'

**Comment by m-ou-se** [comment]
We should probably start testing wasm+atomics in CI, as that's the only way to really solve that issue. I don't think this PR is making the situation worse. (If anything, it improves things by bringing wasm+atomics back into a buildable state.)

**Review by alexcrichton — APPROVED** [review]
Ok sounds like this at least isn't making the situation any worse, so seems reasonable to me!

**Pull request merged**
