### PR TITLE
[beta] Revert "Promote missing_fragment_specifier to hard error #75516"

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This reverts "Promote missing_fragment_specifier to hard error #75516" on just beta. I would like us to explore a more principled fix, perhaps along the lines @petrochenkov suggested in #76605, on master when we have more time to test it but I don't want us shipping the breakage in the meantime. I don't personally feel comfortable immediately backporting anything more than a revert here.

cc @matklad

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
> Updates src/tools/cargo.

That looks like a false positive from the update (well, revert) of cargotest, so can be ignored.

**Comment by ehuss** [comment]
Yea, I've been meaning to fix that (https://github.com/rust-lang/highfive/issues/253).

**Pull request merged**
