### PR TITLE
Implement RFC #1245 : `unsafe const fn`

### PR DESCRIPTION
**Pull request by thepowersgang**
This is the original test implementation, which works according to the tests I wrote, but might need a review.

### CODE REVIEW

**Comment by thepowersgang** [comment]
Feel free to hold off on this until the amendment is merged.

**Comment by thepowersgang** [comment]
Just for reference (and linking the issues), this is an implementation of rust-lang/rfcs#1245

**Comment by phil-opp** [comment]
What about the order? In rust-lang/rfcs#1245 the order was set to `const unsafe fn` (see [aturon's comment]). But this PR seems to implement `unsafe const fn`.

[aturon's comment]: https://github.com/rust-lang/rfcs/pull/1245#issuecomment-146999181

**Comment by thepowersgang** [comment]
Huh... implements the RFC as merged, but yes, @aturon's comment did state the other ordering.

**Comment by brson** [comment]
@phil-opp @thepowersgang [Filed an issue on the order](https://github.com/rust-lang/rust/issues/29107).

**Pull request merged**
