### PR TITLE
Don't emit the same compiler diagnostic twice.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR makes the compiler filter out diagnostic messages that have already been emitted during the same compilation session.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
To clarify what motivates this PR: With incremental compilation there are cases where we emit diagnostics that we have cached from the previous compilation session. It then sometimes occurs that we have to recompute a value (because we have not cached it) but cannot decide for sure if we should re-emit diagnostics during this re-computation.

This PR solves the problem by having a global filter that just remembers all diagnostics that have already been emitted.

**Comment by arielb1** [comment]
So this is only needed when anonymous nodes (today trait selection) can emit warnings?

**Comment by michaelwoerister** [comment]
It also solves #34229 and makes the implementation of this deduplication logic cleaner.

**Comment by arielb1** [comment]
That's a hacky but ok way of dealing with the derive problem
@bors r+

**Comment by durka** [comment]
Hmm, after this PR the error *count* is wrong. For example, the code in #34229 stops after three unique errors, but says "aborting due to 9 previous errors".

**Pull request merged**
