### PR TITLE
user annotations in patterns

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes https://github.com/rust-lang/rust/issues/54573

r? @pnkfelix

### CODE REVIEW

**Comment by nikomatsakis** [comment]
oh dear, I didn't see that ICE locally for some reason. Probably `--keep-stage 1` =)

**Comment by pnkfelix** [comment]
(also, I am going to retag this as waiting-on-author so @nikomatsakis knows he needs to respond to my Q and/or fix the ICE...)

**Comment by nikomatsakis** [comment]
OK, I spent all day debugging this ICE (and more of Friday than I care to admit), but I finally found it. In fact, @pnkfelix, the problem is not specific to this PR, and may well be affecting you in other PRs.

**Comment by nikomatsakis** [comment]
If I am correct — and I'm 99% sure — I'll push a fix soon. The debugging was seriously hampered by my seeming inability to reproduce the ICE outside of a `x.py` build run. Now that I know the problem, maybe I can come up with a more local reproduction ...

**Comment by nikomatsakis** [comment]
For those of you following along, the bug was in this code from the region renumberer:

https://github.com/rust-lang/rust/blob/423d8109868c1f926f2cfcc3bff980c3daa515fd/src/librustc_mir/borrow_check/nll/renumber.rs#L115-L126

In particular, we still need to be visiting the `Place`, which may have embedded regions. I'm not sure I've so far failed to reproduce this though.

**Comment by pnkfelix** [comment]
@bors r+ p=1

bumping priority slightly because I believe this ICE is impeding ongoing work in others' development branches

**Pull request merged**
