### PR TITLE
allow const function calls in consts that are used in patterns

### PR DESCRIPTION
**Pull request by oli-obk**
r? @arielb1

### CODE REVIEW

**Comment by oli-obk** [comment]
the reason this PR fixes two bugs, is because #29927 was also breaking the test for #30117

**Comment by arielb1** [comment]
@oli-obk 

Why are you using `PatLit`? Will this work for more complicated const fn return results (that feels like a separate issue to me)?

**Comment by oli-obk** [comment]
it's already done for everything that is not a pattern directly. Like if you have an integral operation in a constant, it'll just defer it to `PatLit` and run the const evaluator later.

**Comment by oli-obk** [comment]
example: this won't work, since the enum is not directly in a const:

```rust
enum Cake {
    BlackForest,
    Marmor,
}
use Cake::*;

const BOO: (Cake, Cake) = (Marmor, BlackForest);
const FOO: Cake = BOO.1;

fn main() {
    match BlackForest {
        FOO => println!("hi"),
        _ => println!("bye"),
    }
}
```

**Comment by oli-obk** [comment]
The only expressions that are handled without the const evaluator are `ExprTup`, `ExprCall`, `ExprStruct`, `ExprVec` and `ExprPath`. Everything else is turned into a `PatLit` (see https://github.com/rust-lang/rust/pull/30141/files#diff-58f4817150d93d34d850a20426c38371L366) and then const evaluated here: https://github.com/rust-lang/rust/blob/master/src/librustc/middle/check_match.rs#L781

**Comment by arielb1** [comment]
@oli-obk 

At least add a test that these kinds of abuse result in an error rather than an ICE.

**Comment by oli-obk** [comment]
added a test and noticed that the error is reported twice for the const fn. So now I'm bailing out in case the error was repeated previously.

do you mean "abuse" in the "you shouldn't do this" way or in the "complex situation" way?

**Comment by arielb1** [comment]
@oli-obk 

According to @nikomatsakis we are going to change constant patterns to eliminate that possibility - but still we should not ICE.

**Comment by oli-obk** [comment]
I removed the commit that bailed early, `check-stage1` passes locally, but travis didn't notice the removed commit.

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
I'm not sure what possibility is going to be eliminated, but the following already works, because it hits something that will be const evaluated:

```rust
#![feature(const_fn)]

const BOO: (i32, i64) = (5, bla());

const fn bla() -> i64 { 6 }

const FOO: i64 = BOO.1;

fn main() {
    match 6 {
        FOO => println!("hi"),
        _ => println!("bye"),
    }
}
```

all this PR does is to make sure the following also works

```rust
#![feature(const_fn)]
const fn bla() -> i64 { 6 }

const FOO: i64 = bla();

fn main() {
    match 6 {
        FOO => println!("hi"),
        _ => println!("bye"),
    }
}
```

**Pull request merged**
