### PR TITLE
llvm: Update LLVM to include fix for pathologic case in its LiveDebugValues pass.

### PR DESCRIPTION
**Pull request by michaelwoerister**
See #36926.
r? @alexcrichton

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Oh, wait, I remembered I need to update something in order not to break the build bots, right? Give me a sec...

**Comment by alexcrichton** [comment]
Ah yeah we'll want to modify `src/rustllvm/llvm-auto-clean-trigger`

**Comment by alexcrichton** [comment]
r=me though

**Comment by arielb1** [comment]
Don't you also want to incorporate the fix to #36924 here?

**Comment by michaelwoerister** [comment]
@arielb1 Yes, that seems like a good idea. I'll take care of it.

**Comment by michaelwoerister** [comment]
I'm currently running `make check` locally on a branch also containing the SimplifyCFG fix. If that passes, I'll make another PR against the LLVM repo and update this one.

Btw, I have no clue what that test failure above is about. It seems unrelated to changes in LLVM debuginfo generation.

**Comment by michaelwoerister** [comment]
@bors r=alexcrichton

@alexcrichton I'm assuming, since you merged @arielb1's PR to the LLVM repo, that you are in favor of including that patch with this update...

**Comment by alexcrichton** [comment]
👍

**Comment by nikomatsakis** [comment]
Accepting for beta because terrible regression. However, this *is* bumping LLVM, incorporating the [following commits](https://github.com/rust-lang/llvm/compare/3e03f7374169cd41547d75e62ac2ab8a103a913c...ac1c94226e9fa17005ce7e2dd52dd6d1875f3137), all of which seem relatively targeted to me.

cc @rust-lang/compiler

**Pull request merged**
