### PR TITLE
refactor: merge error code `E0465` into `E0464`

### PR DESCRIPTION
**Pull request by Ezrashaw**
`E0465` is an undocumented and untested error code that is functionally identical to `E0464`. This PR merges `E0465` into `E0464`, thus documenting and testing another error code (#61137).

r? @GuillaumeGomez (not sure if you want to review this but it's relevant to my other PRs that you have reviewed)

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Since you made changes in the compiler, I'll let someone from the compiler team approve this PR.

r? @compiler-errors

**Comment by jyn514** [comment]
@bors r-

Failed in rollup: https://github.com/rust-lang/rust/pull/106306#issuecomment-1368115369

**Comment by Ezrashaw** [comment]
Should all be fixed now, was just a error with the tests.

**Pull request merged**
