### PR TITLE
std::rand::os: Fix race condition of atomics

### LINKED ISSUE #21538: std::os::rand::imp::is_getrandom_available atomics use is racy
is_getrandom_available relies on the ordering of reads and writes that use Ordering::Relaxed to prevent races, which is incorrect. The failure mode would be reading the initial false value of GETRANDOM_AVAILABLE, and thus not using getrandom(2) when it is actually available. Either GETRANDOM_CHECKED should use an acquire load and a release store, or it could just use Once.

### PR DESCRIPTION
**Pull request by klutzy**
Fixes #21538.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could this use a `Once`? That seems more idiomatic and error-prone as well.

**Comment by klutzy** [comment]
done!

**Pull request merged**
