### PR TITLE
[stable] Prepare the 1.17.0 release

### PR DESCRIPTION
**Pull request by alexcrichton**
* Update channel we're building
* Update the cargo submodule to the tip of the `rust-1.17.0` branch

### CODE REVIEW

**Comment by alexcrichton** [comment]
Still in the final preparations, not ready for r+ just yet. Waiting on

* [ ] https://github.com/rust-lang/cargo/pull/3949
* [ ] Verify rust-central-station won't deploy this

**Comment by alexcrichton** [comment]
@bors: r+ p=10000

(this is the stable release)

**Comment by Mark-Simulacrum** [comment]
Just wanted to note that I love how simple this is now (in theory). Is this the first stable to be released through the Travis/AppVeyor infrastructure?

**Comment by alexcrichton** [comment]
This will indeed!

(fingers crossed it doesn't explode)

**Pull request merged**
