### PR TITLE
normalize env constness for nested obligations

### LINKED ISSUE #92230: `const_trait_impl`: super trait not satisfied for generic impl
I tried this code:

```rust
#![feature(const_fn_trait_bound)]
#![feature(const_trait_impl)]

pub trait Super {}
pub trait Sub: Super {}

impl<A> const Super for &A where A: ~const Super {}

impl<A> const Sub for &A where A: ~const Sub {}
```

I expected to see this happen: the code compiles successfully

Instead, this happened: compiler errors saying that ```error[E0277]: the trait bound `A: Super` is not satisfied```

cc @rust-lang/wg-const-eval 

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d34672299e19128b2760f3813fabcb41)

### PR DESCRIPTION
**Pull request by fee1-dead**
Closes #92230.

### CODE REVIEW

**Comment by oli-obk** [comment]
So... if we're gonna replace the hack soonish, then this lgtm. I'd rather have it working now and then look into fixing it than wait for a clean fix.

I think the clean fix would be a two step thing:

1. Use `ParamEnvAnd` instead of a `ParamEnv` and a predicate field inside the `Obligation` datastructure
2. Make `ParamEnv::and` lose the constness on the `ParamEnv` if there are no `~const` in the value. I think we can get that working by adding a new type flag and setting it in `visit_predicate` in the typeflag visitor.

Thoughts? Opinions?

**Comment by fee1-dead** [comment]
> Thoughts? Opinions?

Agreed, basically this was blocking constifying `PartialEq`/`Eq`/`PartialOrd`/`Ord` implementations, which blocks #92228.

**Pull request merged**
