### PR TITLE
Update cargo, rls, books

### PR DESCRIPTION
**Pull request by ehuss**
## cargo

10 commits in 5c6aa46e6f28661270979696e7b4c2f0dff8628f..95b45eca19ac785263fed98ecefe540bb47337ac
2019-02-22 19:32:35 +0000 to 2019-03-06 19:24:30 +0000
- Relax some rustdoc tests. (rust-lang/cargo#6721)
- Include build script execution in the fingerprint. (rust-lang/cargo#6720)
- part of the infrastructure for public & private dependencies in the resolver (rust-lang/cargo#6653)
- Bump to 0.36.0 (rust-lang/cargo#6718)
- Some test/bench-related tweaks (rust-lang/cargo#6707)
- Fix links to the permanent home of the edition guide. (rust-lang/cargo#6703)
- HTTPS all the things (rust-lang/cargo#6614)
- Cargo test quicker by not building untested examples when filtered (rust-lang/cargo#6683)
- Link from ARCHITECTURE.md to docs.rs and github (rust-lang/cargo#6695)
- Update how to install rustfmt (rust-lang/cargo#6696)

## rls

9 commits in 0d6f53e1a4adbaf7d83cdc0cb54720203fcb522e..6a1b5a9cfda2ae19372e0613e76ebefba36edcf5
2019-02-14 07:52:15 +0000 to 2019-03-04 20:24:45 +0000
- Update cargo and clippy. (rust-lang-nursery/rls#1388)
- catch up rust-lang/rust PR#58321 (rust-lang-nursery/rls#1384)
- Apply Clippy fixes (rust-lang-nursery/rls#1327)
- Various cosmetic improvements (rust-lang-nursery/rls#1326)
- Make test `RlsHandle` transport-agnostic (rust-lang-nursery/rls#1317)
- Translate remaining tests (rust-lang-nursery/rls#1320)
- Remove unnecessary #![feature]s (rust-lang-nursery/rls#1323)
- Update Clippy (rust-lang-nursery/rls#1319)
- Update Clippy (rust-lang-nursery/rls#1315)

cc @xanewok

## Books
See #58936 for details.

### CODE REVIEW

**Comment by Xanewok** [comment]
i686-gnu{,-nopt} timed out at 3hrs

@bors retry

**Comment by alexcrichton** [comment]
@bors: retry 

https://github.com/rust-lang/rust/issues/58160

**Comment by pietroalbini** [comment]
@bors retry

Timed out.

**Comment by Xanewok** [comment]
spurious RLS test failure

@bors retry

**Comment by ehuss** [comment]
@bors r-
I'd like to squeeze in another change to cargo here.

**Comment by ehuss** [comment]
cc @zoxc this includes this fix to unblock #56732

**Comment by ehuss** [comment]
@bors retry
network timeouts

**Pull request merged**
