### PR TITLE
Remove obsolete armv5te vars from the dist-various-1 Dockerfile

### PR DESCRIPTION
**Pull request by ljedrz**
The [related cc issue](https://github.com/alexcrichton/cc-rs/issues/271) is closed and its changes are in force.

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage, @aturon, this PR requires your review.

**Comment by ljedrz** [comment]
`The system is going down for power off NOW!`

Is this spurious or did my change just shut down the test chamber 😆?

**Pull request merged**
