### PR TITLE
Get rid of niche selection's dependence on fields's order

### LINKED ISSUE #125630: Missed enum layout optimization depending on enum variant field reordering
rustc fails to optimize the enum Layout of `V1` and `V2` of the (real world) example type `LazyRwLockGuard` to 24 bytes.

In case of `V1`, this might be be due to https://github.com/rust-lang/rust/issues/101567.

But the case of `V2` seems to be a separate issue, as it is identical to `V3` (which is optimized correctly), except for the ordering of the fields inside the `Read` enum variant.

(For clarity, [`RwLockReadGuard`](https://doc.rust-lang.org/std/sync/struct.RwLockReadGuard.html) and [`RwLockWriteGuard`](https://doc.rust-lang.org/std/sync/struct.RwLockWriteGuard.html)  each use 16 bytes and contain a niche).

```rust
use std::sync::*;

// could use 24 bytes, uses 32 (probably known issue, #101567)
pub enum LazyRwLockGuardV1<'a, T> {
    Unlocked(&'a RwLock<T>),
    Read {
        lock: &'a RwLock<T>,
        guard: RwLockReadGuard<'a, T>,
    },    
    Write(RwLockWriteGuard<'a, T>),
}

// helper subtype (16 Bytes) so the main type figures out it's Niche correctly
pub enum LazyRwLockWriteGuard<'a, T> {
    Unlocked(&'a RwLock<T>),
    Write(RwLockWriteGuard<'a, T>),
}

// this type should now be 24 bytes, but unfortunately still uses 32
pub enum LazyRwLockGuardV2<'a, T> {
    Read {
        lock: &'a RwLock<T>,
        guard: RwLockReadGuard<'a, T>,
    },    
    NonRead(LazyRwLockWriteGuard<'a, T>),
}

// this type correctly uses 24 bytes
pub enum LazyRwLockGuardV3<'a, T> {
    Read {
        guard: RwLockReadGuard<'a, T>,
        lock: &'a RwLock<T>, // fields reordered
    },    
    NonRead(LazyRwLockWriteGuard<'a, T>),
}

```

[godbolt repro](https://godbolt.org/z/37783G91x)
[stackoverflow question](https://stackoverflow.com/questions/78310085/why-does-rust-not-reorder-fields-in-an-enum-for-memory-layout)

### PR DESCRIPTION
**Pull request by adwinwhite**
Fixes #125630.
Use the optimal niche selection decided in `univariant()` rather than picking niche field manually.

r? @the8472

### CODE REVIEW

**Comment by the8472** [comment]
I don't think largest niche in the largest variant is necessarily optimal. There may be multiple largest variants. And niches in a smaller variant can still be useful, e.g. when used by an outer enum when nesting multiple into each other. 

The linked case could be solved by sorting the enum variant fields differently, without changing the niche-picking code.

**Comment by adwinwhite** [comment]
My wording is not precise.
The "optimal" actually means the **better strategy** in your [PR](https://github.com/rust-lang/rust/pull/108106/).

I don't quite understand the relevance of niches in smaller variant. My commit still uses the same largest variant as before.
If my understanding is correct, `niche_filling_layout` picks a different field than the **better strategy** thus it doesn't have enough space to fit other variants.

**Comment by adwinwhite** [comment]
The field sorting is quite naive compared to what's implemented in `univariant_biased`, as it doesn't make use of the knowledge of the variant's layout to allow more space for fitting. I don't think simply sorting differently can change much unless we make it as complicated as `univariant_biased`. Maybe there's something I missed?

**Comment by RalfJung** [comment]
Thanks for adjusting the Miri test!

The intention in that Miri test was that the  add(0) would be changed to add(size-of-ptr) if the padding moves elsewhere. Maybe it would make sense to add a "let pad_offset = ...;" and "add(pad_offset)" to make that more clear.

**Comment by the8472** [comment]
> I don't quite understand the relevance of niches in smaller variant. My commit still uses the same largest variant as before.
If my understanding is correct, niche_filling_layout picks a different field than the better strategy thus it doesn't have enough space to fit other variants.

I was thinking of different logic, not `niche_filling_layout`. Now that I have looked at the context you're correct.

> The field sorting is quite naive compared to what's implemented in univariant_biased, as it doesn't make use of the knowledge of the variant's layout to allow more space for fitting.

For the non-prefixed enum layout it should actually be going through the same logic as univariant structs. It's calling ` self.univariant(v, repr, StructKind::AlwaysSized)` a few lines up and the `AlwaysSized` goes through the elaborate sorting.

So yeah, the sorting was already fine. As you spotted, it wasn't making use of the already-optimized niche choice when multiple of the same size were available.

----

I think there would be ways to make the miri test more robust by inferring the position of the padding by enumerating all fields and the struct size. But that's probably overkill for an easily adjusted test. And the layout logic only changes every now and then.

----

LGTM. @bors r+

**Comment by the8472** [comment]
and niches can affect perf

@bors rollup=never

**Comment by adwinwhite** [comment]
Bors met [race condition](https://github.com/rust-lang/homu/issues/75). It seems that a `retry` is needed.
@the8472

**Comment by pnkfelix** [comment]
* primary regression to typenum doc-full (-0.23%)
* marking as triaged; this is a very small (and probably semi-random) cost for a clear win IMO in terms of overall consistency of behavior.

@rustbot label: +perf-regression-triaged

**Pull request merged**
