### PR TITLE
fix error handling for pthread_sigmask(3)

### PR DESCRIPTION
**Pull request by anonion0**
Errors from `pthread_sigmask(3)` were handled using `cvt()`, which expects a return value of `-1` on error and uses `errno`.
However, `pthread_sigmask(3)` returns `0` on success and an error number otherwise.

Fix it by replacing `cvt()` with `cvt_nz()`.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Good catch, thanks!
r? @JohnTitor @bors r+

**Comment by RalfJung** [comment]
Failed in https://github.com/rust-lang/rust/pull/96075#issuecomment-1100188240
@bors r- rollup=iffy

**Comment by JohnTitor** [comment]
@anonion0 Could you move these imports under cfgs?

**Comment by anonion0** [comment]
Should be fixed now.

**Comment by JohnTitor** [comment]
Thanks!
@bors r+

**Pull request merged**
