### PR TITLE
Resolve `$crate`s for pretty-printing at more appropriate time

### LINKED ISSUE #57089: $crate unexpectedly disintegrates depending on unrelated macro invocations
I have proc macros `mac!` which is function-like and `#[attr]` which is an attribute. Both of them simply emit their input unchanged (`input.into_iter().collect()`).

I have an invocation of both macros from another crate which passes tokens containing `$crate`. In the code below, everything is working as expected and both macros receive `Ident { ident: "$crate" }` in their input.

Now for the broken bit: I observed some spooky action at a distance in which changing the behavior of `mac!` affects the input of the totally unrelated invocation of `#[attr]`. The input of `#[attr]` decomposes into `Punct { ch: '$' }` + `Ident { ident: "crate" }` which rustc refuses to parse down the line.

- Either we need to find out what is causing `$crate` to disintegrate into `$` + `crate` and stop that from happening (preferred),
- Or the parser needs to accept an appropriately spanned `$` + `crate` where it appears in procedural macro output.

#### repro_macros/src/lib.rs

```rust
extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro]
pub fn mac(input: TokenStream) -> TokenStream {
    println!("MAC INPUT: {:#?}", input);

    // Change this to `false` to observe the spooky effect on the input of #[attr].
    if true {
        input.into_iter().collect()
    } else {
        TokenStream::new()
    }
}

#[proc_macro_attribute]
pub fn attr(_args: TokenStream, input: TokenStream) -> TokenStream {
    println!("ATTR INPUT: {:#?}", input);
    input.into_iter().collect()
}
```

#### repro/src/lib.rs

```rust
const UNIT: () = ();

macro_rules! m {
    () => {
        repro_macro::mac! {
            pub fn f() {
                $crate::UNIT
            }
        }

        #[repro_macro::attr]
        pub fn g() {
            $crate::UNIT
        }
    };
}

m!();
```

Mentioning @petrochenkov since you worked on #56647.
Mentioning @alexcrichton.

*rustc 1.33.0-nightly (2d3e909e4 2018-12-22)*

### PR DESCRIPTION
**Pull request by petrochenkov**
Doing it in `BuildReducedGraphVisitor` wasn't a good idea, identifiers wasn't actually visited half of the time.
As a result some `$crate`s weren't resolved and were therefore pretty-printed as `$crate` literally, which turns into two tokens during re-parsing of the pretty-printed text.

Now we are visiting and resolving `$crate` identifiers in an item right before sending that item to a proc macro attribute or derive.

Fixes https://github.com/rust-lang/rust/issues/57089

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by grovesNL** [comment]
@petrochenkov @dtolnay I noticed an issue with macro expansion with `-Z unstable-options --pretty=expanded` including `$crate` in the output for the bitflags crate/macro, which is unexpected.

The issue started somewhere between nightlies `2018-12-27-fb86d604b` and  `2018-12-28-60e825389` which seems to be when this landed, though I haven't bisected further yet. It is possible this change is related?

I have an example here: https://gist.github.com/grovesNL/5d3ddc7b95c1939be26c64ba09f1ac2f

(Original issue is reported in eqrion/cbindgen#272)

**Comment by petrochenkov** [comment]
@grovesNL 
Yes, this PR or https://github.com/rust-lang/rust/pull/56647 is the most likely reason.

Does cbindgen really need to treat output of `--pretty=expanded` as Rust code?
In general it's not guaranteed to be well-formed, and certainly not guaranteed to be correct (due to macro hygiene).

**Comment by grovesNL** [comment]
It's not clear if there is a better alternative at the moment – it's definitely very useful to have the expanded macro source for use cases like cbindgen.

I guess cbindgen could special case certain "known" macros in cbindgen (i.e. bitflags and others) or the downstream crates using cbindgen could manually expand macros. Both of these options are a bit problematic, because it would mean cbindgen is unable to work with most macros in general.

**Comment by petrochenkov** [comment]
Ok, I'll try to fix this specific case since it worked before.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/57915

**Pull request merged**
