### PR TITLE
E0088/E0090 fix

### PR DESCRIPTION
**Pull request by sophiajt**
This fixes an issue reported by @eddyb (https://github.com/rust-lang/rust/pull/36208#issuecomment-2707092230) where the check for "too few lifetime parameters" was removed in one of the error message PRs.

I also removed the span shrinking from E0088, as early bound lifetimes give you a confusing underline in some cases.

r=eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors p=1 

* beta backport

**Comment by nikomatsakis** [comment]
Accepting for beta backport. Small patch. cc @rust-lang/compiler

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfaulted

**Pull request merged**
