### PR TITLE
Updated E0087 to new format

### PR DESCRIPTION
**Pull request by ghost**
Part of #35233. r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

Can you also update the corresponding unit test(s) to test for the new label?  You may need to add a couple tests so that you can test for the variations.

**Comment by poveda-ruiz** [comment]
I added a note to src/test/compile-fail/E0087.rs

**Comment by jonathandturner** [comment]
Great!  One last thing, since it's pretty small, can you [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your 2 commits into 1?

After that, I think it'll be ready.

**Comment by poveda-ruiz** [comment]
Sure Jonathan :)

**Comment by jonathandturner** [comment]
Thanks!

@bors r+ rollup

**Comment by alexcrichton** [comment]
@bors: retry

* not sure why...

**Comment by poveda-ruiz** [comment]
It is my fault? D:

**Comment by jonathandturner** [comment]
@poveda-ruiz - there was an extra space at the end of one of your lines.  I've merged this PR in with a bunch of other PRs, so I'm just going to fix it on my end.

For your next one, you can run: 

```
python src/bootstrap/bootstrap.py --stage 1 --step check-tidy
```

**Comment by poveda-ruiz** [comment]
Damn, sorry :(

**Pull request merged**
