### PR TITLE
Add tests for #17001, #21449, #22992, #23208, #23442

### LINKED ISSUE #17001: ICE:  'No def'n found for syntax::ast::DefId{krate: 0u32, node: 4u32} in tcx.tcache',
I get this output:
```
error: internal compiler error: unexpected failure
note: the compiler hit an unexpected failure path. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' failed at 'No def'n found for syntax::ast::DefId{krate: 0u32, node: 4u32} in tcx.tcache', /home/nate/builds/rust/src/librustc/middle/ty.rs:3991
```
when I try and compile this code: http://pastie.org/9528361

### LINKED ISSUE #21449: Compiler panic when doing something wrong with a module
A compiler panic occurs when trying to compile this snippet of code:

```
mod MyMod{
}

fn main() {
    let myVar = MyMod{T:0u64};
}
```
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'No def'n found for DefId { krate: 0u32, node: 4u32 } in tcx.tcache', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/ty.rs:5008

rustc 1.0.0-nightly (f4f10dba2 2015-01-17 20:31:08 +0000)
binary: rustc
commit-hash: f4f10dba2975b51c2d2c92157018db3ac13d4d4a
commit-date: 2015-01-17 20:31:08 +0000
host: x86_64-unknown-linux-gnu [Linux Mint Debian Edition]
release: 1.0.0-nightly

### LINKED ISSUE #22992: Compile Bug: unexpected dereferenceable type
When I was compiling the code of [What are Rust's exact auto-dereferencing rules?](http://stackoverflow.com/questions/28519997/what-are-rusts-exact-auto-dereferencing-rules), it resulted a bug.

The code:
```rust
struct X { val: i32 }
impl std::ops::Deref for X {
    type Target = i32;
    fn deref(&self) -> &i32 { &self.val }
}


trait            M                   { fn m(self); }
impl             M for i32           { fn m(self) { println!("i32::m()"); } }
impl             M for X             { fn m(self) { println!("X::m()"); } }
impl<'a>         M for &'a X         { fn m(self) { println!("&X::m()"); } }
impl<'a, 'b>     M for &'a &'b X     { fn m(self) { println!("&&X::m()"); } }
impl<'a, 'b, 'c> M for &'a &'b &'c X { fn m(self) { println!("&&&X::m()"); } }

trait            RefM                   { fn refm(&self); }
impl             RefM for i32           { fn refm(&self) { println!("i32::refm()"); } }
impl             RefM for X             { fn refm(&self) { println!("X::refm()"); } }
impl<'a>         RefM for &'a X         { fn refm(&self) { println!("&X::refm()"); } }
impl<'a, 'b>     RefM for &'a &'b X     { fn refm(&self) { println!("&&X::refm()"); } }
impl<'a, 'b, 'c> RefM for &'a &'b &'c X { fn refm(&self) { println!("&&&X::refm()"); } }

struct Y { val: i32 }
impl std::ops::Deref for Y {
    type Target = i32;
    fn deref(&self) -> &i32 { &self.val }
}

struct Z { val: Y }
impl std::ops::Deref for Z {
    type Target = Y;
    fn deref(&self) -> &Y { &self.val }
}

struct A;
impl std::marker::Copy for A {}
impl             M for             A { fn m(self) { println!("A::m()"); } }
impl<'a, 'b, 'c> M for &'a &'b &'c A { fn m(self) { println!("&&&A::m()"); } }
impl             RefM for             A { fn refm(&self) { println!("A::refm()"); } }
impl<'a, 'b, 'c> RefM for &'a &'b &'c A { fn refm(&self) { println!("&&&A::refm()"); } }

fn main() {
    // I'll use @ to denote left side of the dot operator
    (*X{val:42}).m();        // i32::refm() , self == @
    X{val:42}.m();           // X::m()      , self == @
    (&X{val:42}).m();        // &X::m()     , self == @
    (&&X{val:42}).m();       // &&X::m()    , self == @
    (&&&X{val:42}).m();      // &&&X:m()    , self == @
    (&&&&X{val:42}).m();     // &&&X::m()   , self == *@
    (&&&&&X{val:42}).m();    // &&&X::m()   , self == **@

    (*X{val:42}).refm();     // i32::refm() , self == @
    X{val:42}.refm();        // X::refm()   , self == @
    (&X{val:42}).refm();     // X::refm()   , self == *@
    (&&X{val:42}).refm();    // &X::refm()  , self == *@
    (&&&X{val:42}).refm();   // &&X::refm() , self == *@
    (&&&&X{val:42}).refm();  // &&&X::refm(), self == *@
    (&&&&&X{val:42}).refm(); // &&&X::refm(), self == **@

    Y{val:42}.refm();        // i32::refm() , self == *@
    Z{val:Y{val:42}}.refm(); // i32::refm() , self == **@

    A.m();                   // A::m()      , self == @
    // without the Copy trait, (&A).m() would be a compilation error:
    // cannot move out of borrowed content
    (&A).m();                // A::m()      , self == *@
    (&&A).m();               // &&&A::m()   , self == &@
    (&&&A).m();              // &&&A::m()   , self == @
    A.refm();                // A::refm()   , self == @
    (&A).refm();             // A::refm()   , self == *@
    (&&A).refm();            // A::refm()   , self == **@
    (&&&A).refm();           // &&&A::refm(), self == @
}
```

And the rustc resulted:
```
# rustc --version
rustc 1.0.0-dev (b4c965ee8 2015-03-02) (built 2015-03-03)

# RUST_BACKTRACE=1 rustc deref.rs 
error: internal compiler error: unexpected dereferenceable type Y
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/laijs/work/rust-for-install/src/libsyntax/diagnostic.rs:189

stack backtrace:
   1:     0x7fcbf38f28ff - sys::backtrace::write::h577e1c6361768c02QyA
   2:     0x7fcbf391b432 - panicking::on_panic::hef3a5ce737f27c37FDJ
   3:     0x7fcbf385618a - rt::unwind::begin_unwind_inner::h51b5b5b16031b3c28jJ
   4:     0x7fcbf0b6d9ed - rt::unwind::begin_unwind::h2713391746432164638
   5:     0x7fcbf0b6e225 - diagnostic::Handler::bug::hfe31e16b8d71f021BHD
   6:     0x7fcbf168f43b - session::Session::bug::h96f42bebaeb8e73fqup
   7:     0x7fcbf3015677 - trans::consts::const_expr::hb0b128b357663b3c4vn
   8:     0x7fcbf2faa3ae - trans::consts::get_const_expr_as_global::h21a61339d5edfef7ftn
   9:     0x7fcbf2f64130 - trans::expr::trans::h0937a1423c3712b8Tth
  10:     0x7fcbf2f9c817 - trans::callee::trans_args::hc57b3e614890b9dfz1g
  11:     0x7fcbf2fa47e2 - trans::callee::trans_call_inner::h14447778500323265516
  12:     0x7fcbf2fac8fc - trans::expr::trans_rvalue_dps_unadjusted::hb70513e148b158edgAi
  13:     0x7fcbf2f62f5e - trans::expr::trans_into::h1fb70f0657f02021Lnh
  14:     0x7fcbf2f61f74 - trans::controlflow::trans_stmt_semi::h3484c46defdec968n4d
  15:     0x7fcbf2f63970 - trans::controlflow::trans_block::hda388713e3e88977a5d
  16:     0x7fcbf302f26f - trans::base::trans_closure::hd3b6ad6febef58aaVct
  17:     0x7fcbf2f4fff8 - trans::base::trans_fn::h63c86b5ef9723009Ont
  18:     0x7fcbf2f4bb76 - trans::base::trans_item::hac26f7be10d65cfeGLt
  19:     0x7fcbf3035d7c - trans::base::trans_crate::hff2787f0626d8852QHu
  20:     0x7fcbf3f8cba2 - driver::phase_4_translate_to_llvm::hbc0b6a58c8ee4f80rNa
  21:     0x7fcbf3f68198 - driver::compile_input::h9de6f092c5dfb6ebIba
  22:     0x7fcbf4032a0e - run_compiler::hb5e94b85ec6e83edF5b
  23:     0x7fcbf40305bc - thunk::F.Invoke<A, R>::invoke::h17784488277762929069
  24:     0x7fcbf402f310 - rt::unwind::try::try_fn::h12687093362529061390
  25:     0x7fcbf398fd08 - rust_try_inner
  26:     0x7fcbf398fcf5 - rust_try
  27:     0x7fcbf402f9fc - thunk::F.Invoke<A, R>::invoke::h5447655687859444331
  28:     0x7fcbf3906f85 - sys::thread::thread_start::h8973b07a174c8c31j5E
  29:     0x7fcbed77f529 - start_thread
  30:     0x7fcbf34da77c - clone
  31: 0xffffffffffffffff - <unknown>
```

### LINKED ISSUE #23208: supertrait expansion needs normalization
This example doesn't compile:

```rust
trait TheTrait : TheSuperTrait<<Self as TheTrait>::Item> {
    type Item;
}

trait TheSuperTrait<T> {
    fn get(&self) -> T;
}

impl TheTrait for i32 {
    type Item = u32;
}

impl TheSuperTrait<u32> for i32 {
    fn get(&self) -> u32 {
        *self as u32
    }
}

fn foo<T:TheTrait<Item=u32>>(t: &T) -> u32 {
    t.get()
}

fn main() {
    foo::<i32>(&22);
}
```

This is because we fail to normalize during supertrait expansion.

### LINKED ISSUE #23442: associated type does not live long enough
This program fails to compile:

```rust
#![crate_type="rlib"]

use std::marker::PhantomData;

pub struct UnionedKeys<'a,K>
    where K: UnifyKey + 'a
{
    table: &'a mut UnificationTable<K>,
    root_key: K,
    stack: Vec<K>,
}

pub trait UnifyKey {
    type Value;
}

pub struct UnificationTable<K:UnifyKey> {
    values: Delegate<K>,
}

pub struct Delegate<K>(PhantomData<K>);
```

This was *supposed* to be fixed by https://github.com/rust-lang/rust/pull/22436, but apparently that fix is not working. I've been wanting to revisit the strategy there anyway, because it leads to infinite recursion in some cases and I'm not happy about it.

The error I see is:

```
/home/nmatsakis/tmp/bar.rs:5:1: 11:2 error: the associated type `<K as UnifyKey>::Value` may not live long enough [E0309]
/home/nmatsakis/tmp/bar.rs:5 pub struct UnionedKeys<'a,K>
/home/nmatsakis/tmp/bar.rs:6     where K: UnifyKey + 'a
/home/nmatsakis/tmp/bar.rs:7 {
/home/nmatsakis/tmp/bar.rs:8     table: &'a mut UnificationTable<K>,
/home/nmatsakis/tmp/bar.rs:9     root_key: K,
/home/nmatsakis/tmp/bar.rs:10     stack: Vec<K>,
                              ...
/home/nmatsakis/tmp/bar.rs:11:2: 11:2 help: consider adding an explicit lifetime bound `<K as UnifyKey>::Value: 'a`...
/home/nmatsakis/tmp/bar.rs:5:1: 11:2 note: ...so that the reference type `&'a mut UnificationTable<K>` does not outlive the data it points at
/home/nmatsakis/tmp/bar.rs:5 pub struct UnionedKeys<'a,K>
/home/nmatsakis/tmp/bar.rs:6     where K: UnifyKey + 'a
/home/nmatsakis/tmp/bar.rs:7 {
/home/nmatsakis/tmp/bar.rs:8     table: &'a mut UnificationTable<K>,
/home/nmatsakis/tmp/bar.rs:9     root_key: K,
/home/nmatsakis/tmp/bar.rs:10     stack: Vec<K>,
                              ...
```

### PR DESCRIPTION
**Pull request by apasel422**
Closes #17001
Closes #21449
Closes #22992
Closes #23208
Closes #23442

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 6a66749b9573a5dd32b0a1d818ecad9b9e2a31ba

Nice!

**Comment by apasel422** [comment]
@alexcrichton `pretty` failed on `issue-22992.rs`. How should I proceed?

**Comment by alexcrichton** [comment]
Feel free to just throw `// ignore-pretty` in the test

**Comment by apasel422** [comment]
@alexcrichton Done. Tests passed.

**Pull request merged**
