### PR TITLE
impl FromIterator<&char> for String

### PR DESCRIPTION
**Pull request by withoutboats**

### CODE REVIEW

**Comment by withoutboats** [comment]
Was sad to observe that this impl is not backwards compatible:

```rust
impl<T> FromIterator<T> for String where String: Extend<T> {
    fn from_iter<I: Iterator<Item = T>>(iter: I) -> String {
        let mut string = String::new();
        string.extend(iter);
        string
    }
}
```

Nor this even more useful impl:

```rust
impl<T, C> FromIterator<T> for C where C: Default + Extend<T> {
    fn from_iter<I: Iterator<Item = T>>(iter: I) -> String {
        let mut collection = C::default();
        collection.extend(iter);
        collection
    }
}

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Looks good to me!

**Comment by sfackler** [comment]
Do we do this kind of implicit dereference elsewhere? Can I for example collect an `Iterator<Item = &u8>` to a `Vec<u8>`?

**Comment by withoutboats** [comment]
@sfackler we implement `Extend<&char>` for `String`, seems to me that there should be a parity between those two (hence the reference to the non-backwards compatible impls).

But I also would definitely support `<T: Copy> FromIterator<&T> for Vec<T>`.

**Comment by ollie27** [comment]
If `impl FromIterator<&char> for String`is added then `impl FromIterator<&char> for Cow<str>` should also be added to keep consistency between the `FromIterator` impls for `String` and `Cox<str>`.

I also think there should be parity between `Extend` and `FromIterator` but it may be too late to add the `FromIterator<&T>` impls to the collections as it might cause inference errors in existing code. For example `[0u8, 1, 2].iter().collect::<Vec<_>>()` would suddenly be ambiguous. That might also be why those impls don't already exist.

**Comment by withoutboats** [comment]
I can add that impl to this PR.

> I also think there should be parity between Extend and FromIterator but it may be too late to add the FromIterator<&T> impls to the collections as it might cause inference errors in existing code. For example [0u8, 1, 2].iter().collect::<Vec<_>>() would suddenly be ambiguous. That might also be why those impls don't already exist.

(Note there's no extend impl so there's no parity in that case).

That impl would need a crater run, but I have trouble imagining code that would not have enough contextual information to distinguish a `Vec<u8>` from a `Vec<&u8>`. Anyway its a separate concept from this PR.

**Comment by alexcrichton** [comment]
@sfackler [yes](https://github.com/rust-lang/rust/blob/0ed75e1f47d099a17de22eb2c1d2b43ce89ea390/src/libcollections/vec.rs#L1684-L1695)

**Comment by sfackler** [comment]
TIL

**Comment by withoutboats** [comment]
I'll try to remember to put up another PR for the Cow impl

**Comment by cuviper** [comment]
@alexcrichton 
> @sfackler [yes](https://github.com/rust-lang/rust/blob/0ed75e1f47d099a17de22eb2c1d2b43ce89ea390/src/libcollections/vec.rs#L1684-L1695)

AFAICS, that impl is only used for its `spec_extend`.  There's still no `FromIterator<&'a T> for Vec<T>`, nor for any other collection.  `String` is the only one doing this, and the rest only copy for `Extend`.

**Comment by alexcrichton** [comment]
Oh sorry I was thinking of [this impl](https://github.com/rust-lang/rust/blob/94e884b6307a59f1e6e64aa7ebc1996b651a7629/src/libcollections/vec.rs#L1901-L1906), namely:

```rust
impl<'a, T: 'a + Copy> Extend<&'a T> for Vec<T> {
```

I forgot that it was only `Extend`, not `FromIterator`.

**Comment by alexcrichton** [comment]
Unfortunately this was just released though so we don't have much time to rethink the merge...

**Comment by cuviper** [comment]
Yeah, I only got here because of the release notes.

**Pull request merged**
