### PR TITLE
Upgrade llvm-project (rustc + avr = lovelove back again!)

### LINKED ISSUE #400: "LLVM ERROR: Not supported instr" on avr-unknown-gnu-atmega328
I am experiencing a bug when trying to compile my application for Arduino Uno.

Probably, there's a regression somewhere.
Because, it used to work 1 month ago. CI: https://travis-ci.com/github/Rahix/avr-hal/builds/207260821

Original issue: https://github.com/Rahix/avr-hal/issues/124

## Output

```
Step 6/6 : RUN cargo +nightly build --example uno-blink
 ---> Running in fde0189b88d8
    Updating git repository `https://github.com/Rahix/ufmt.git`
    Updating crates.io index
 Downloading crates ...
  Downloaded nb v0.1.3
  Downloaded paste v1.0.4
  Downloaded rustc_version v0.2.3
  Downloaded semver-parser v0.7.0
  Downloaded quote v1.0.8
  Downloaded proc-macro2 v1.0.24
  Downloaded proc-macro-hack v0.5.19
  Downloaded vcell v0.1.3
  Downloaded void v1.0.2
  Downloaded cfg-if v0.1.10
  Downloaded unicode-xid v0.2.1
  Downloaded syn v1.0.58
  Downloaded avr-device-macros v0.2.3
  Downloaded avr-device v0.2.3
  Downloaded semver v0.9.0
  Downloaded panic-halt v0.2.0
  Downloaded nb v1.0.0
  Downloaded embedded-hal v0.2.4
  Downloaded bare-metal v0.2.5
 Downloading crates ...
  Downloaded cc v1.0.60
  Downloaded compiler_builtins v0.1.39
  Downloaded getopts v0.2.21
  Downloaded hashbrown v0.9.0
  Downloaded addr2line v0.14.0
  Downloaded gimli v0.23.0
  Downloaded miniz_oxide v0.4.0
  Downloaded adler v0.2.3
  Downloaded object v0.22.0
  Downloaded unicode-width v0.1.8
  Downloaded rustc-demangle v0.1.18
  Downloaded libc v0.2.79
   Compiling compiler_builtins v0.1.39
   Compiling core v0.0.0 (/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.58
   Compiling semver-parser v0.7.0
   Compiling proc-macro-hack v0.5.19
   Compiling paste v1.0.4
   Compiling semver v0.9.0
   Compiling rustc_version v0.2.3
   Compiling quote v1.0.8
   Compiling bare-metal v0.2.5
   Compiling rustc-std-workspace-core v1.99.0 (/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
LLVM ERROR: Not supported instr: <MCInst 258 <MCOperand Reg:1> <MCOperand Imm:15> <MCOperand Reg:40>>
error: could not compile `compiler_builtins`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c cargo +nightly build --example uno-blink' returned a non-zero code: 101

```

With `--release` and `--verbose`:

```
  Compiling embedded-hal v0.2.4
     Running `rustc --crate-name embedded_hal /Users/sobolev/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-hal-0.2.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 --cfg 'feature="unproven"' -C metadata=503a59343e486e01 -C extra-filename=-503a59343e486e01 --out-dir /Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps --target /Users/sobolev/Desktop/avr-hal/avr-specs/avr-atmega328p.json -L dependency=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps -L dependency=/Users/sobolev/Desktop/avr-hal/target/release/deps --extern 'noprelude:compiler_builtins=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps/libcompiler_builtins-afa03ed941a63b4f.rmeta' --extern 'noprelude:core=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps/libcore-30308749cc1695e3.rmeta' --extern nb=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps/libnb-e03ff2173c96de6e.rmeta --extern void=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps/libvoid-4cf9d65885018701.rmeta -Z unstable-options --cap-lints allow`
LLVM ERROR: Not supported instr: <MCInst 258 <MCOperand Reg:1> <MCOperand Imm:15> <MCOperand Reg:40>>
error: could not compile `compiler_builtins`

Caused by:
  process didn't exit successfully: `rustc --crate-name compiler_builtins /Users/sobolev/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.39/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 --cfg 'feature="compiler-builtins"' --cfg 'feature="core"' --cfg 'feature="default"' --cfg 'feature="rustc-dep-of-std"' -C metadata=afa03ed941a63b4f -C extra-filename=-afa03ed941a63b4f --out-dir /Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps --target /Users/sobolev/Desktop/avr-hal/avr-specs/avr-atmega328p.json -Z force-unstable-if-unmarked -L dependency=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps -L dependency=/Users/sobolev/Desktop/avr-hal/target/release/deps --extern core=/Users/sobolev/Desktop/avr-hal/target/avr-atmega328p/release/deps/librustc_std_workspace_core-2709fdbb3f7a5de3.rmeta --cap-lints allow --cfg 'feature="unstable"'` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Reproduction

1. Clone https://github.com/Rahix/avr-hal
2. Add this `Dockefile`:

```Dockerfile
FROM rustlang/rust:nightly-slim

RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    avr-libc \
    binutils-avr \
    gcc-avr \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && apt-get clean -y && rm -rf /var/lib/apt/lists/*

COPY . /code

WORKDIR /code/boards/arduino-uno

RUN rustup component add rust-src
RUN cargo +nightly build --example uno-blink
```

3. Run `docker build --tag=ard .`

## Versions

```
info: The currently active `rustc` version is `rustc 1.51.0-nightly (c8915eebe 2021-01-07)`
```

```
» avr-gcc --version
avr-gcc  9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### LINKED ISSUE #79889: VTables which end up in the data segment are miscompiled on AVR.
The following code snippet should light the pin 13 LED when compiled for the atmega328 and run on an arduino.  It does not. This is possibly related to #74743, and potentially also avr-rust/rust-legacy-fork#47. I initially found this while trying to implement a `RawWakerVTable`, so it is not restricted to compiler-generated vtables - any function pointers which are stored in the data segment are affected.

Attempting to simplify further (such as using a single function pointer) tends to end up with pointers which are passed entirely in code and never loaded from the data segment. These appear to be compiled correctly.

```rust
#![no_std]
#![no_main]
#![feature(llvm_asm, test)]

#[panic_handler]
fn panic(_panic: &core::panic::PanicInfo) -> ! {
    loop {}
}

trait Foo {
    unsafe fn foo(&self);
}

impl Foo for () {
    unsafe fn foo(&self) {
        llvm_asm!(
            "SBI 0x04, 5
         SBI 0x05, 5"
        );
    }
}

#[inline(never)]
unsafe fn invoke(foo: &dyn Foo) {
    foo.foo()
}

#[no_mangle]
pub unsafe extern "C" fn main() {
    invoke(core::hint::black_box(&()));
    loop {}
}
```

Built + Flashed with:

```
% cargo +nightly build -Z build-std=core --target=avr-unknown-gnu-atmega328 --release
% avrdude -p atmega328p -c arduino -P /dev/tty.usbmodem142401 -Uflash:w:./target/avr-unknown-gnu-atmega328/release/avr-test.elf
```

Stepping through the execution in simavr/gdb makes the failure obvious - the vtable contains the byte-address of the implementation function, but the `icall` instruction (and indeed the instruction pointer of the AVR in general) uses word-addresses.

```
(gdb) disas
Dump of assembler code for function _ZN8avr_test6invoke17h7f830b8dbe21df91E:
   0x000000ae <+0>:	movw	r30, r22
   0x000000b0 <+2>:	ldd	r18, Z+6	; 0x06
   0x000000b2 <+4>:	ldd	r19, Z+7	; 0x07
   0x000000b4 <+6>:	movw	r30, r18
=> 0x000000b6 <+8>:	icall
   0x000000b8 <+10>:	ret
End of assembler dump.
(gdb) info r
<snip>
r30            0xa8                168
r31            0x0                 0
SREG           0x0                 0
SP             0x8f5               0x8008f5
PC2            0xb6                182
pc             0x5b                0xb6 <avr_test::invoke+8>
(gdb) si
0x00000150 in ?? ()
```

As can be seen from the GDB output, after loading the VTable entry the Z register (the combination of r30 and r31) contains "0x00A8", and execution jumps to "0x0150". The vtable should instead include "0x0054", which when treated as a word-address will jump to the expected "0x00A8".

### LINKED ISSUE #82104: AVR: Compilation in --release mode fails with LLVM ERROR: Not supported instr
When compiling the following minimal AVR template in --release mode, the compiler aborts with an LLVM error

https://github.com/avr-rust/template-bin.git

(This is an empty template with an empty main that does nothing.)

```
$ cargo build --target avr-atmega328p.json -Z build-std=core --release                                          
   Compiling compiler_builtins v0.1.39                                                                                                                     
   Compiling core v0.0.0 (.../rust-unstable/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)                     
   Compiling rustc-std-workspace-core v1.99.0 (.../rust-unstable/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc
-std-workspace-core)                                                         
   Compiling avr-std-stub v1.0.2                                             
LLVM ERROR: Not supported instr: <MCInst 258 <MCOperand Reg:1> <MCOperand Imm:15> <MCOperand Reg:47>>                                                      
error: could not compile `compiler_builtins`                                 
                                                                             
To learn more, run the command again with --verbose.                                                                                                       
warning: build failed, waiting for other jobs to finish...                                                                                                 
error: build failed                               
```

In debug mode the build works correctly:

```
$ cargo build --target avr-atmega328p.json -Z build-std=core                                                    
   Compiling core v0.0.0 (.../rust-unstable/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)                     
   Compiling compiler_builtins v0.1.39                                       
   Compiling rustc-std-workspace-core v1.99.0 (.../rust-unstable/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc
-std-workspace-core)                                                                                                                                       
   Compiling avr-std-stub v1.0.2                                             
   Compiling template-bin v0.1.0 (.../avr-rust-template)                                                                                  
    Finished dev [unoptimized + debuginfo] target(s) in 14.61s   
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (8e54a2113 2021-02-13)
binary: rustc
commit-hash: 8e54a21139ae96a2aca3129100b057662e2799b9
commit-date: 2021-02-13
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### LINKED ISSUE #83633: SIGSEGV in rust nightly 2021-01-07 (rustc 1.51.0-nightly)
Code for AVR target. Code compiled on Fedora 33. Code reduced by `comby-reducer`. 

[rapt-reduced.tar.gz](https://github.com/rust-lang/rust/files/6220133/rapt-reduced.tar.gz)

Program requires nightly 2021-01-07. I cannot use newer version of rustc to check, because of _unrelated_ bug in llvm for AVR target(`LLVM ERROR: Not supported instr: <MCInst 296 <MCOperand Reg:1> <MCOperand Imm:15> <MCOperand Reg:39>`).

### Code

```Rust
#![no_std]
#![no_main]
use arduino_uno::prelude::*;
use arduino_uno::Serial;
use atmega328p_hal::port::mode;
use atmega328p_hal::port::Pin;
use avr_hal_generic::usart::{Usart, UsartOps};
use avr_std_stub as _;
mod line_buffer;
use line_buffer::LineBuffer;
mod atoi;
use atoi::atoi_u8;
const MAX_BUF_LEN: usize = 128;
static mut LINE_BUFFER: [u8; MAX_BUF_LEN] = [0; MAX_BUF_LEN];
enum PinState {
    InputFloating(Pin<mode::Input<mode::Floating>>),
    InputAnalog(Pin<mode::Input<mode::PullUp>>),
    Output(Pin<mode::Output>),
    TriState(Pin<mode::TriState>),
}
fn error<USART, PD0, PD1, CLOCK>(serial: &mut Usart<USART, PD0, PD1, CLOCK>, message: &str) where    USART: UsartOps<PD0, PD1>, {}
#[arduino_uno::entry]
fn main() -> ! {
    let peripherals = arduino_uno::Peripherals::take().unwrap();
    let mut pins = arduino_uno::Pins::new(peripherals.PORTB, peripherals.PORTC, peripherals.PORTD);
    let serial_rx = pins.d0;
    let serial_tx = pins.d1.into_output(&mut pins.ddr);
    let mut serial = Serial::new(peripherals.USART0, serial_rx, serial_tx, 115200.into_baudrate());
    let mut line_buffer = unsafe { LineBuffer::new(&mut LINE_BUFFER) };
    let mut pin_state = [
        PinState::TriState(pins.d3.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d4.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d5.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d6.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d7.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d8.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d9.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d10.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d11.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d12.into_tri_state(&pins.ddr).downgrade()),
        PinState::TriState(pins.d13.into_tri_state(&pins.ddr).downgrade()),
    ];
    loop {
        ufmt::uwrite!(&mut serial, "\x1B[1mrapt>\x1B[0m ").void_unwrap();
        if line_buffer.read_line(&mut serial) > 0 {
            for command in line_buffer.words() {
                match command {
                    [b'r', tail @ ..] => {
                        match atoi_u8(tail) {
                            Some(pin_number) if (pin_number as usize) < pin_state.len() => {
                                match &pin_state[pin_number as usize] {
                                    PinState::InputFloating(pin) => {
                                        ufmt::uwrite!(serial, "p{}={}\r\n", pin_number, pin.is_high().unwrap()).void_unwrap();
                                    }
                                    PinState::InputAnalog(pin) => {
                                        ufmt::uwrite!(serial, "p{}={}\r\n", pin_number, pin.is_high().unwrap() ).void_unwrap();
                                    }
                                    PinState::TriState(pin) => {
                                        ufmt::uwrite!(serial, "p{}={}\r\n", pin_number, pin.is_high().unwrap()).void_unwrap();
                                    }
                                    _ => {}
                                }
                            }
                            _ => {}
                        }
                    }
                    [b'w', tail @ .., val] => {
                        match atoi_u8(tail) {
                            Some(pin_number) if (pin_number as usize) < pin_state.len() => {
                                match &mut pin_state[pin_number as usize] {
                                    PinState::Output(ref mut pin) => {
                                        let v = match val {
                                            b'l' | b'L' => false,
                                            b'h' | b'H' =>true,
                                            _ => {
                                                continue;
                                            }
                                        };
                                        ufmt::uwrite!(serial, "p{}={}\r\n", pin_number, v).void_unwrap();
                                    }
                                    PinState::TriState(ref mut pin) => {
                                        let v = match val {
                                            b'l' | b'L' => {
                                                pin.set_low().expect("");
                                                false
                                            }
                                            b'h' | b'H' => {
                                                pin.set_high().expect("");
                                                true
                                            }
                                            _ => {
                                                continue;
                                            }
                                        };
                                        ufmt::uwrite!(serial, "p{}={}\r\n", pin_number, v).void_unwrap();
                                    }
                                    _ => {}
                                }
                            }
                            _ => {}
                        }
                    }
                    _ => error(&mut serial, ""),
                }
            }
        }
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (c2de47a9a 2021-01-06)
binary: rustc
commit-hash: c2de47a9aa4c9812884f341f1852e9c9610f5f7a
commit-date: 2021-01-06
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly

```

### Error output

```
  process didn't exit successfully: `rustc --crate-name rapt --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=s -C panic=abort -C lto -C codegen-units=1 -C debuginfo=2 -C metadata=874b614425088d6c -C extra-filename=-874b614425088d6c --out-dir /home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps --target /home/vlisivka/workspace/rapt/avr-atmega328p.json -L dependency=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps -L dependency=/home/vlisivka/workspace/rapt/target/release/deps --extern arduino_uno=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libarduino_uno-2a2559e92b4f8b94.rlib --extern atmega328p_hal=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libatmega328p_hal-9252c4cc0359dc4c.rlib --extern avr_hal_generic=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libavr_hal_generic-8b1481097f48b6ab.rlib --extern avr_std_stub=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libavr_std_stub-9b4b6bb91705909d.rlib --extern 'noprelude:compiler_builtins=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libcompiler_builtins-6ac0a51c4b9ecfe7.rlib' --extern 'noprelude:core=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libcore-627006de141c21fe.rlib' --extern nb=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libnb-949e9a646194f61f.rlib --extern ufmt=/home/vlisivka/workspace/rapt/target/avr-atmega328p/release/deps/libufmt-e2008be75bc74481.rlib -Z unstable-options` (signal: 11, SIGSEGV: invalid memory reference)

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Patryk27**
See:
https://github.com/rust-lang/llvm-project/pull/139

tl;dr:
- closes https://github.com/rust-lang/rust/issues/83633, 
- closes https://github.com/rust-lang/rust/issues/82104,
- closes https://github.com/rust-lang/rust/issues/79889,
- closes https://github.com/rust-lang/compiler-builtins/issues/400.

🙂

### CODE REVIEW

**Comment by Patryk27** [comment]
> ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

This feels unrelated to the pull request 😅 let's try again:

@bors: retry

**Comment by Patryk27** [comment]
oh 😢 -- @nikic could you restart the pipeline?

**Comment by Patryk27** [comment]
```
2022-05-09T07:12:59.4444743Z FAILED: ELF/CMakeFiles/lldELF.dir/InputSection.cpp.o 
2022-05-09T07:12:59.4451003Z sccache /usr/bin/c++  -DGTEST_HAS_RTTI=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IELF -I/checkout/src/llvm-project/lld/ELF -I/checkout/src/llvm-project/lld/include -Iinclude -I/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/include -I/checkout/src/llvm-project/llvm/include -ffunction-sections -fdata-sections -fPIC -m64 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG    -fno-exceptions -fno-rtti -std=gnu++14 -MD -MT ELF/CMakeFiles/lldELF.dir/InputSection.cpp.o -MF ELF/CMakeFiles/lldELF.dir/InputSection.cpp.o.d -o ELF/CMakeFiles/lldELF.dir/InputSection.cpp.o -c /checkout/src/llvm-project/lld/ELF/InputSection.cpp
2022-05-09T07:12:59.4460408Z /checkout/src/llvm-project/lld/ELF/InputSection.cpp: In member function ‘uint64_t lld::elf::SectionBase::getOffset(uint64_t) const’:
2022-05-09T07:12:59.4461212Z /checkout/src/llvm-project/lld/ELF/InputSection.cpp:176:14: error: ‘llvm::ArrayRef<unsigned char> lld::elf::InputSectionBase::rawData’ is protected within this context
2022-05-09T07:12:59.4461929Z   176 |     if (!es->rawData.empty())
2022-05-09T07:12:59.4462198Z       |              ^~~~~~~
2022-05-09T07:12:59.4462604Z In file included from /checkout/src/llvm-project/lld/ELF/InputSection.cpp:9:
2022-05-09T07:12:59.4463123Z /checkout/src/llvm-project/lld/ELF/InputSection.h:231:29: note: declared protected here
2022-05-09T07:12:59.4463497Z   231 |   mutable ArrayRef<uint8_t> rawData;
2022-05-09T07:12:59.4463769Z       |                             ^~~~~~~
```
🤔 not sure what might be going on - the code compiles fine locally; maybe CI has some stale artifacts?

**Comment by Patryk27** [comment]
Ah! This pull request contains not only my two commits for AVR -- I've done `git submodule update --remote src/llvm-project`, which fetched some additional commits; rough guess: https://github.com/rust-lang/llvm-project/pull/134?

**Comment by nikic** [comment]
Yes, it looks like these patches depend on at least https://github.com/llvm/llvm-project/commit/ae1ba6194f09b7e310fd49cf18a2829dcbeb7f6b. I'll revert them.

**Comment by nikic** [comment]
I've reverted the patches, can you please update the submodule to the latest version?

**Comment by Patryk27** [comment]
Sure, on it

**Comment by Patryk27** [comment]
🚀

**Pull request merged**
