### PR TITLE
[RFC issue 1468] make some common traits object-safe

### PR DESCRIPTION
**Pull request by durka**
This is a very dubious change but @eddyb was curious about the fallout. @brson crater this too?

cc rust-lang/rfcs#1468

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I'm confused -- do you really want to land this, or just want the results from a crater run?

**Comment by durka** [comment]
I think for now just the results of a crater run would inform the discussion on that issue. Certainly it would be nice for more things to be object-safe, but there was fallout even within the tests and compiler so it kinda seems like a non-starter unless we have super compelling reasons.

**Comment by nikomatsakis** [comment]
@durka 

>  Certainly it would be nice for more things to be object-safe

Hmm, can you say more about this? In particular, if the trait can't actually be *used* with an object, then why would it be nice for it to be object safe?

**Comment by durka** [comment]
See https://github.com/rust-lang/rfcs/issues/1468#issuecomment-172861415

**Comment by nikomatsakis** [comment]
OK, well, I've kicked off a crater run (I don't think @brson saw the ping). I'll let you know what it says.

**Comment by nikomatsakis** [comment]
Crater report: https://gist.github.com/nikomatsakis/6478dde577e9affd957d

Summary: 3702 crates tested: 1984 working / 1160 broken / 305 regressed / 1 fixed / 252 unknown.

**Pull request closed without merging**
