### PR TITLE
	mk: Compile C code on MSVC with /MD

### PR DESCRIPTION
**Pull request by alexcrichton**
On MSVC there are two ways that the CRT can be linked, either statically or
dynamically. Each object file produced by the compiler is compiled against
msvcrt (a dll) or libcmt (a static library). When the linker is dealing with
more than one object file, it requires that all object files link to the same
CRT, or else the linker will spit out some errors.

For now, compile code with `-MD` as it seems to appear more often in C libraries
so we'll stick with the same trend.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

cc @retep998, @vadimcn

**Comment by retep998** [comment]
`/LTCG` isn't required. If a module is compiled for support with LTCG then as soon as the linker comes across it it will switch to LTCG mode automatically. Not passing `/LTCG` merely causes the linker to waste a bit of time before it realizes it needs to be using LTCG mode, which only matters if any libraries are compiled in LTCG mode. By default most things do not use LTCG, in which case `/LTCG` will probably just slow things down a bit as the linker spends extra effort being prepared for LTCG data which isn't actually there.

**Comment by alexcrichton** [comment]
Aha! @retep998 is correct, and I have more investigation to do locally. I have removed that commit now.

**Pull request merged**
