### PR TITLE
Rollup of 35 pull requests

### PR DESCRIPTION
**Pull request by alexcrichton**
- Successful merges: #39202, #39648, #39770, #39820, #39918, #39921, #40092, #40146, #40199, #40225, #40239, #40257, #40259, #40277, #40278, #40287, #40297, #40308, #40311, #40315, #40319, #40324, #40336, #40340, #40344, #40345, #40367, #40369, #40372, #40373, #40379, #40386, #40389, #40400, #40404
- Failed merges: #39987, #40220, #40261, #40329

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=100

Green light from OSX/Linux/Windows tests locally

**Comment by alexcrichton** [comment]
[actual error](https://gist.github.com/alexcrichton/5f4ad053ac280792e1f7f4d8f5b3391f) 

investigating...

**Comment by arielb1** [comment]
That's presumably the GDB PR.

**Comment by alexcrichton** [comment]
@arielb1 you think https://github.com/rust-lang/rust/pull/40400?

It doesn't seem to touch this test though?

**Comment by alexcrichton** [comment]
I was thinking https://github.com/rust-lang/rust/pull/40220/files as it touches macros, but I'm not sure. The full test suite passed at one point on Windows/mac/linux so it may also be i686-musl specific, but that seems far fetched.

I'm verifying those latter two claims locally.

**Comment by alexcrichton** [comment]
Closing in favor of a [more conservative](https://github.com/rust-lang/rust/pull/40429) version

**Pull request closed without merging**
