### PR TITLE
Simplify `Vec` using `iter::repeat_n`

### PR DESCRIPTION
**Pull request by scottmcm**
By using `repeat_n` instead of `ExtendElement`, we can delete a bunch more `unsafe` code from `Vec`.

All the codegen tests are passing (and I made one stricter to help be sure), so let's see if perf is also happy with it.

r? @ghost 

Built atop #104435; will leave draft until I can rebase atop that.

### CODE REVIEW

**Comment by the8472** [comment]
I'm not sure if it's a good idea to remove this. There's untapped optimization potential in the current implementation. E.g. it could use the zero-value check that vec initialization already has and then use `Allocator::grow_zeroed`.

**Comment by scottmcm** [comment]
@the8472 I agree that's a good thing to add, but I don't think it needs the `ExtendWith` *trait*, since we can't do that for `ExtendFunc` anyway.  I could leave an private `extend_element` function without the trait and type, though, if you think that'd be helpful.

**Comment by scottmcm** [comment]
Curious -- arguably good on cycles, but clearly bad on instructions.

I guess I should do this in smaller pieces, if at all.

**Pull request closed without merging**
