### PR TITLE
Add Homogenous Aggregates for AArch64 codegen

### LINKED ISSUE #24154: aarch64-apple-ios: Returning structs by value in extern "C" functions uses wrong calling convention
Creating an extern C function like this:

```rust
#[repr(C)]
pub struct Point {
    x: f32,
    y: f32,
}

#[no_mangle]
pub extern "C" fn get_point() -> Point {
    return Point{x: 10.0, y: 20.0}
}
```

and compiling using `cargo build --target aarch64-apple-ios --release`, the assembly produced for `get_point` is:

```
_get_point:
0000000000000000                movz    x0, #16800, lsl #48
0000000000000004                movk    x0, #16672, lsl #16
0000000000000008                ret
```

My ARM assembly is a little rusty, but I believe this is expecting the caller to pass in the address of a `Point` in `x0`, and then the function fills it in.

However, this C code, which should be equivalent:

```C
struct point {
    float x;
    float y;
};

struct point get_point(void) {
    return (struct point){10.0, 20.0};
}
```

compiles to the following assembly in Xcode 6.2 targeting arm64:

```
0x1000fec74:  fmov   s0, #1.000000e+01
0x1000fec78:  fmov   s1, #2.000000e+01
0x1000fec7c:  ret
```

which is returning the two struct fields in the SIMD registers.

Is this an issue of how aarch64 is defined or configured, maybe?

### PR DESCRIPTION
**Pull request by jgallagher**
I doubt this PR is ready to merge as-is, for a couple reasons:
- There are no tests for this change. I'm not sure how to add tests for this change, as it modifies the C ABI for a cross-compilation target. Anecdotally, I have an iOS library I've been working on, and before this change, it crashes running on an arm64 device due to bad calling conventions (a simplified example is in #24154), and after this change, it runs correctly.
- This is my first foray into LLVM. I did my best to reimplement what Clang does for AArch64 codegen (https://github.com/llvm-mirror/clang/blob/master/lib/CodeGen/TargetInfo.cpp), particularly in `ABIInfo::isHomogeneousAggregate`, `AArch64ABIInfo::isHomogeneousAggregateBaseType`, and `AArch64ABIInfo::isHomogeneousAggregateSmallEnough`, but I'm not confident I got a complete translation, particularly because Clang includes a lot of checks that I don't believe are necessary for rustc.

Fixes #24154.

### CODE REVIEW

**Comment by sanxiyn** [comment]
I propose we merge this as-is. 1. This is a localized change. 2. This apparently works. 3. We have no infrastructure to test ARM64 changes, yet.

**Comment by jgallagher** [comment]
(I just squashed a commit to fix some typos in the comments - no code changes.)

**Comment by pnkfelix** [comment]
I agree with @sanxiyn 's analysis; sorry for the delay in review.

**Pull request merged**
