### PR TITLE
submodules: update clippy from 3710ec59 to ad3269c4

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
Rustfmt all the things
Clippy dogfood
Update for compiletest changes
Use symbols instead of strings
Rustup to rustc 1.36.0-nightly (1764b2972 2019-05-12)
Add regression test for identity_conversion FP
UI test cleanup: Extract many_single_char_names tests
Add tests for empty_loop lint
Add in_macro again
Rename in_macro to in_macro_or_desugar
````
r? @oli-obk

### CODE REVIEW

**Comment by ehuss** [comment]
After this PR, rls's tests seem to fail with an ICE in rustc:

<details><summary>backtrace</summary>
<pre>
thread 'rustc' panicked at 'index out of bounds: the len is 2 but the index is 4294954756', /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/slice/mod.rs:2689:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: scoped_tls::ScopedKey<T>::with
  11: syntax_pos::symbol::Symbol::as_str
  12: clippy_lints::utils::match_def_path::{{closure}}
             at /Users/eric/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/ad3269c/clippy_lints/src/utils/mod.rs:1122
  13: <fmt_macros::FormatSpec as core::cmp::PartialEq>::eq
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/iter/adapters/mod.rs:589
  14: clippy_lints::utils::conf::helpers::doc_valid_idents::{{closure}}
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/slice/mod.rs:3153
  15: <fmt_macros::FormatSpec as core::cmp::PartialEq>::eq
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/iter/adapters/mod.rs:589
  16: std::sys_common::poison::Flag::borrow
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/iter/traits/iterator.rs:604
  17: <alloc::vec::SetLenOnDrop as core::ops::drop::Drop>::drop
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/liballoc/vec.rs:1862
  18: <alloc::vec::SetLenOnDrop as core::ops::drop::Drop>::drop
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/liballoc/vec.rs:1845
  19: <alloc::vec::SetLenOnDrop as core::ops::drop::Drop>::drop
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/liballoc/vec.rs:1731
  20: std::sys_common::poison::Flag::borrow
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/iter/traits/iterator.rs:1465
  21: clippy_lints::utils::match_def_path
             at /Users/eric/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/ad3269c/clippy_lints/src/utils/mod.rs:1122
  22: <clippy_lints::regex::Regex as rustc::lint::LateLintPass>::check_block_post::{{closure}}
             at /Users/eric/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/ad3269c/clippy_lints/src/regex.rs:116
  23: <rustc::lint::context::LateLintPassObjects as rustc::lint::LateLintPass>::check_expr
  24: <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr
  25: rustc::hir::intravisit::walk_expr
  26: <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr
  27: rustc::hir::intravisit::walk_fn
  28: rustc::hir::intravisit::walk_item
  29: rustc::hir::intravisit::Visitor::visit_nested_item
  30: rustc::hir::intravisit::walk_crate
  31: rustc::lint::context::late_lint_pass_crate
  32: rustc::lint::context::late_lint_crate
  33: rustc::util::common::time
  34: rustc::util::common::time
  35: __rust_maybe_catch_panic
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: __rust_maybe_catch_panic
  38: rustc_interface::passes::analysis::{{closure}}
  39: rustc::util::common::time
  40: rustc_interface::passes::analysis
  41: rustc::ty::query::__query_compute::analysis
  42: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  43: rustc::dep_graph::graph::DepGraph::with_task_impl
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  45: rustc::ty::context::tls::enter_global
  46: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  47: rustc_interface::passes::create_global_ctxt::{{closure}}
  48: rustc_interface::interface::run_compiler_in_existing_thread_pool
  49: std::thread::local::LocalKey<T>::with
  50: scoped_tls::ScopedKey<T>::set
  51: syntax::with_globals
</pre>
</details>

Is there anyone around who can help me debug it?  For context, I would like to update cargo before beta, which will require updating rls, which will require getting rls working.  cc @Xanewok

**Comment by Manishearth** [comment]
cc @oli-obk , i didn't really do that part of the PR (just the mechanical bits)

**Comment by Manishearth** [comment]
The backtrace doesn't make sense, there are no expressions in `fn main() {}`.

It's possible that the Symbol stuff broke some assumptions in RLS as well, and they need to update that.

**Comment by ehuss** [comment]
(Sorry for the noise on this PR, I'm not sure where to move this discussion.)

Looking closer, I think I see what's wrong.  Clippy is storing Symbol definitions in globals (lazy_static), but those symbol definitions are only valid for a single session/thread.  When rls fires up a second build, clippy reuses those Symbol definitions, but they point to invalid values.

I'm not sure of the best way to fix that.  I'm pretty sure Clippy shouldn't be holding any global references to Symbols.  Maybe `clippy_lints/src/utils/paths.rs` could go back to using strs and create Symbols as needed? I'm not sure how much of a performance issue that would be, or if there's a better way.

I'm going to stop looking for now. Feel free to ping me here or on discord if you have any questions.  It looks pretty straightforward, though.

**Comment by Manishearth** [comment]
That's going to be super inefficient. The long term solution for paths.rs is to move as many of those into "diagnostic items" as possible.

Feels like a bug in libsyntax if this can be done safely, though

**Pull request merged**
