### PR TITLE
rustdoc: Fix gap on section anchor symbol when hovering.

### LINKED ISSUE #49485: rustdoc: section anchor symbol can be difficult to click
Some of the section anchors that appear when you hover over an item can be difficult to click.  It seems to disappear when the mouse transitions over the spacing between the item and the symbol.

demo

Tested on a variety of browsers, all seem to behave similarly.  

Rust 1.25 seems OK (there isn't as much spacing).  I only notice this on nightly (1.26.0-nightly (e5277c145 2018-03-28)).

### PR DESCRIPTION
**Pull request by ehuss**
Fixes #49485 for section headings.

### CODE REVIEW

**Comment by ehuss** [comment]
Pretty much any section:

section-hover

Here you can see there's a gap between the elements:
image


It doesn't seem to happen on Chrome, but Firefox and Safari seem to suffer from it.  Different engines seem to treat the en-space differently.  I'm not sure what the en-space is trying to accomplish, actually.  If it is trying to extend the hover region, I think using padding would be more reliable.

**Comment by GuillaumeGomez** [comment]
Ok tested and with your changes, smaller titles work but `h1` don't work anymore (this is the opposite of the current situation). While we're at it, it seems like titles in methods' doc have this issue as well (tested on firefox).

**Comment by ehuss** [comment]
Hm, that's strange. `h1` seems ok to me.  For example on the front page:

image

The purple region is the padding, which should count for hovering.  I made it a little extra wide so that it is sure to overlap.  

I'm not sure what you mean by "titles".  Is that like headers like "Examples"?  Those also seem ok:

image

**Comment by GuillaumeGomez** [comment]
Now it's good, might have failed to update the CSS... Thanks a lot!

@bors: r+ rollup

**Pull request merged**
