### PR TITLE
[do not merge] Test parallel compiler

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build e1f9d0488d052f77315c033b3b8bf47a4d8fdb11

**Comment by Zoxc** [comment]
@rust-timer build eafa54e32a3ec69221700503f21cb456de859f9e

**Comment by Zoxc** [comment]
I did some local timing running `python x.py build --stage 1 src/libstd`:
```

par on - 8 threads:
	rustc 272.694s
	rustc_mir 209.139s
	total 0:14:41

par on - 1 thread:
	rustc 305.675
	rustc_mir 202.261
	total 0:15:28

par off:
	rustc 306.997
	rustc_mir 200.825
	total 0:15:20
```

**Comment by Zoxc** [comment]
Here's some numbers for `x.py check`:
```
check - par off:
	rustc 47.663s
	rustc_mir 18.725s
	total 0:03:55

check - par on - 1 thread:
	rustc 49.490s
	rustc_mir 19.494s
	total 0:04:00

check - par on - 8 threads:
	rustc 19.847s
	rustc_mir 8.665s
	total 0:02:48
```

**Comment by Zoxc** [comment]
@rust-timer build e09f51168143d6b8a4da083242dbec77ef81ee2c

**Comment by Zoxc** [comment]
@rust-timer build 4a5841a15e0c47e1c5f0c6a67145599db7499a7a

**Comment by Zoxc** [comment]
[Numbers](https://perf.rust-lang.org/compare.html?start=f1dee7b53e8053afc315b500a514d7c013745acd&end=4a5841a15e0c47e1c5f0c6a67145599db7499a7a&stat=wall-time) look a bit better with my latest PRs applied. In particular `packed-simd` no longer regresses.

**Comment by Zoxc** [comment]
@rust-timer build 93d37a9d032967653130ac271c682c130e419ba4

**Comment by Zoxc** [comment]
[Numbers for 2 threads](https://perf.rust-lang.org/compare.html?start=66e88562dca2c2b3b026c639b8e2655e88fe3e49&end=93d37a9d032967653130ac271c682c130e419ba4&stat=wall-time).

**Comment by JohnCSimon** [comment]
Triage ping @Zoxc  - this has sat idle for a month.  Has the test completed?

**Comment by gagan0723** [comment]
Ping from triage, I guess the label should be `S-waiting-on-review` instead, since it hasn't been reviewed yet.

@nikomatsakis can you please review this. Also if you think the label should be changed to 
`S-waiting-on-review` please do so. Thanks

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, we would like to know if you @Zoxc could give us a few more minutes to fix the conflicts.

Thanks.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as reopening it is low effort and it looks like the testing here is done at least for now.

**Pull request closed without merging**
