### PR TITLE
Rollup of 20 pull requests

### LINKED ISSUE #55775: Regression in `Command::exec`'s PATH resolution
Using `env_clear()` + `exec()` currently exhibits different behaviour on nightly and stable.

I believe the first nightly to regress was `2018-11-02`.

A minimal reproduction is the following code:

```rust
use std::process::Command;
use std::os::unix::process::CommandExt;

fn main() {
    let mut cmd = Command::new("true");
    cmd.env_clear();
    let err = cmd.exec();
    println!("error: {}", err);
}
```

On stable, it prints no error. On nightly, it prints `error: No such file or directory (os error 2)`.

Using `strace -e trace=execve`, we can see the difference:

```
# stable
execve("/bin/true", ["true"], 0x7fedf1821010 /* 0 vars */) = 0
# nightly
execve("true", ["true"], 0x561a58edbb80 /* 0 vars */) = -1 ENOENT (No such file or directory)
```

## Meta

```
$ rustc --version --verbose
rustc 1.32.0-nightly (15d770400 2018-11-06)
binary: rustc
commit-hash: 15d770400eed9018f18bddf83dd65cb7789280a5
commit-date: 2018-11-06
host: x86_64-unknown-linux-gnu
release: 1.32.0-nightly
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #55136 (Remove short doc where it starts with a codeblock)
 - #55711 (Format BtreeMap::range_mut example)
 - #55722 (impl_stable_hash_for: support enums and tuple structs with generic parameters)
 - #55754 (Avoid converting bytes to UTF-8 strings to print, just pass bytes to stdout/err)
 - #55804 (rustdoc: don't inline `pub use some_crate` unless directly asked to)
 - #55805 (Move `static_assert!` into librustc_data_structures)
 - #55837 (Make PhantomData #[structural_match])
 - #55840 (Fix TLS errors when downloading stage0)
 - #55843 (add FromIterator<A> to Box<[A]>)
 - #55858 (Small fixes on code blocks in rustdoc)
 - #55863 (Fix a typo in std::panic)
 - #55870 (Fix typos.)
 - #55874 (string: Add documentation for `From` impls)
 - #55879 (save-analysis: Don't panic for macro-generated use globs)
 - #55882 (Reference count `crate_inherent_impls`s return value.)
 - #55888 (miri: for uniformity, also move memory_deallocated to AllocationExtra)
 - #55889 (global allocators: add a few comments)
 - #55896 (Document optimizations enabled by FusedIterator)
 - #55905 (Change `Lit::short_name` to `Lit::literal_name`.)
 - #55908 (Fix their/there grammar nit)

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+

Removed #55562 (causing error above)
Added #55589

**Comment by kennytm** [comment]
9696 I guess.

@bors r+

Removed #55589 (already testing)
Added #55136.

**Comment by nrc** [comment]
I can't see an error in the logs :-s

**Comment by kennytm** [comment]
@nrc You've got a spurious error in the RLS test.

<details>

```
[02:11:56] ---- cmd_changing_workspace_lib_retains_bin_diagnostics stdout ----
[02:11:56] thread 'cmd_changing_workspace_lib_retains_bin_diagnostics' panicked at 'assertion failed: `(left == right)`
[02:11:56]   left: `String("E0425")`,
[02:11:56]  right: `"unused_variables"`', tools\rls\tests\tests.rs:408:5
[02:11:56] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[02:11:56] ---rls-stdout---
[02:11:56] Content-Length: 605
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".",":"]},"definitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"renameProvider":true,"executeCommandProvider":{"commands":["rls.applySuggestion-2560","rls.deglobImports-2560"]}}}}Content-Length: 92
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","title":"Building"}}Content-Length: 112
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"library","title":"Building"}}Content-Length: 122
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"library cfg(test)","title":"Building"}}Content-Length: 111
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"binary","title":"Building"}}Content-Length: 121
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"binary cfg(test)","title":"Building"}}Content-Length: 104
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_1","title":"Building"}}Content-Length: 92
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_0","title":"Indexing"}}Content-Length: 733
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"unused_variables","message":"unused variable: `unused`\n\nnote: #[warn(unused_variables)] on by default\nhelp: consider using `_unused` instead: `_unused`","range":{"end":{"character":30,"line":2},"start":{"character":24,"line":2}},"severity":2,"source":"rustc"},{"code":"unused_variables","message":"unused variable: `test_val`\n\nhelp: consider using `_test_val` instead: `_test_val`","range":{"end":{"character":36,"line":9},"start":{"character":28,"line":9}},"severity":2,"source":"rustc"}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/simple_workspace/library/src/lib.rs"}}Content-Length: 493
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"unused_variables","message":"unused variable: `val`\n\nnote: #[warn(unused_variables)] on by default\nhelp: consider using `_val` instead: `_val`","range":{"end":{"character":27,"line":4},"start":{"character":24,"line":4}},"severity":2,"source":"rustc"}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/simple_workspace/binary/src/main.rs"}}Content-Length: 104
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_0","title":"Indexing"}}Content-Length: 92
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_3","title":"Building"}}Content-Length: 112
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_3","message":"library","title":"Building"}}Content-Length: 121
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_3","message":"binary cfg(test)","title":"Building"}}Content-Length: 111
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_3","message":"binary","title":"Building"}}Content-Length: 122
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_3","message":"library cfg(test)","title":"Building"}}Content-Length: 104
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_3","title":"Building"}}Content-Length: 92
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_2","title":"Indexing"}}Content-Length: 681
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"unused_variables","message":"unused variable: `unused`\n\nnote: #[warn(unused_variables)] on by default\nhelp: consider using `_unused` instead: `_unused`","range":{"end":{"character":30,"line":2},"start":{"character":24,"line":2}},"severity":2,"source":"rustc"},{"code":"E0308","message":"mismatched types\n\nexpected u32, found u64","range":{"end":{"character":62,"line":9},"start":{"character":44,"line":9}},"severity":1,"source":"rustc"}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/simple_workspace/library/src/lib.rs"}}Content-Length: 409
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"E0308","message":"mismatched types\n\nexpected u32, found u64","range":{"end":{"character":55,"line":4},"start":{"character":35,"line":4}},"severity":1,"source":"rustc"}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/simple_workspace/binary/src/main.rs"}}Content-Length: 104
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_2","title":"Indexing"}}Content-Length: 92
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_5","title":"Building"}}Content-Length: 122
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_5","message":"library cfg(test)","title":"Building"}}Content-Length: 112
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_5","message":"library","title":"Building"}}Content-Length: 121
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_5","message":"binary cfg(test)","title":"Building"}}Content-Length: 111
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_5","message":"binary","title":"Building"}}Content-Length: 104
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_5","title":"Building"}}Content-Length: 92
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_4","title":"Indexing"}}Content-Length: 733
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"unused_variables","message":"unused variable: `unused`\n\nnote: #[warn(unused_variables)] on by default\nhelp: consider using `_unused` instead: `_unused`","range":{"end":{"character":30,"line":2},"start":{"character":24,"line":2}},"severity":2,"source":"rustc"},{"code":"unused_variables","message":"unused variable: `test_val`\n\nhelp: consider using `_test_val` instead: `_test_val`","range":{"end":{"character":36,"line":9},"start":{"character":28,"line":9}},"severity":2,"source":"rustc"}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/simple_workspace/library/src/lib.rs"}}Content-Length: 444
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"E0425","message":"cannot find function `fetch_u32` in module `library`\n\nnot found in `library`","range":{"end":{"character":53,"line":4},"start":{"character":44,"line":4}},"severity":1,"source":"rustc"}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/simple_workspace/binary/src/main.rs"}}Content-Length: 104
[02:11:56] 
[02:11:56] {"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_4","title":"Indexing"}}
[02:11:56] ---------------
[02:11:56] 
[02:11:56] 
[02:11:56] failures:
[02:11:56]     cmd_changing_workspace_lib_retains_bin_diagnostics
[02:11:56] 
[02:11:56] test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

</details>

**Pull request merged**
