### PR TITLE
Stabilize doc_alias feature

### LINKED ISSUE #50146: Tracking issue for #[doc(alias = "...")]
Edit: Implemented in #49757. From the docs:

This feature allows you to add alias(es) to an item when using the `rustdoc` search through the `doc(alias)` attribute. Example:

```rust,no_run
#![feature(doc_alias)]
#[doc(alias = "x")]
#[doc(alias = "big")]
pub struct BigX;
```

Then, when looking for it through the `rustdoc` search, if you enter "x" or "big", search will show the `BigX` struct first.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #50146.

This PR intend to stabilize the `doc_alias` feature. The last remaining bits were missing checks on the attribute usage and on its arguments. Both have been added so I think we can now move to the next step.

r? @ollie27 

cc @rust-lang/rustdoc

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I \*think\* it needs to wait for this PR to get merged first iirc. (but maybe I'm wrong here?)

**Comment by GuillaumeGomez** [comment]
We have another blocker in fact. Need to fix it first!

**Comment by ollie27** [comment]
This is blocked on the FCP in #50146 completing.

**Comment by GuillaumeGomez** [comment]
Since the FCP has been approved, we can now move forward! \o/

@bors: r=ollie27

**Comment by jyn514** [comment]
> There is still a weird .replace("\"", "") that needs to be removed or a reason for it needs to be found: 

Maybe that should be done first? But I don't feel strongly, it can be done in a follow-up PR.

**Comment by GuillaumeGomez** [comment]
I'll open an issue so it's not forgotten, but it's cleanup, not an issue feature-wise.

**Comment by pickfire** [comment]
Is multiple `#[doc(alias = "a")]` better `#[doc(alias = ["a", "b"])`?

**Pull request merged**
