### PR TITLE
Sync rustc_codegen_cranelift

### PR DESCRIPTION
**Pull request by bjorn3**
The main highlight this sync is improved support for inline assembly. Thanks @nbdd0121! Inline assembly is still disabled by default for builds in the main rust repo though. Cranelift will now also be built from the crates.io releases rather than the git repo. Git repos are incompatible with vendoring.

r? @ghost

@rustbot label +A-codegen +A-cranelift +T-compiler

### CODE REVIEW

**Comment by est31** [comment]
> Git repos are incompatible with vendoring.

What do you mean? https://doc.rust-lang.org/cargo/commands/cargo-vendor.html#description

> This cargo subcommand will vendor all crates.io and git dependencies for a project into the specified directory at <path>.

**Comment by bjorn3** [comment]
They are incompatible with the current vendoring implementation in rustbuilt at least. See https://github.com/rust-lang/rust/issues/90764.

**Pull request merged**
