### PR TITLE
[DO NOT COMMIT] Use derivative to simplify impls in `rustc_type_ir`

### PR DESCRIPTION
**Pull request by compiler-errors**
Gotta keep things like `Copy` impl around since they've got a ton of bounds.

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
Derivative has MIT/Apache 2.0 license. Not exactly sure if there's anything else to do to add a new crate dep.

**Comment by compiler-errors** [comment]
oh also

@bors try @rust-timer queue

**Review by oli-obk — APPROVED** [review]
r=me with perf clean

This is amazing!

**Comment by jackh726** [comment]
Hmm, wonder why perf regresses?

**Comment by compiler-errors** [comment]
Probably the PartialOrd implementation

**Pull request closed without merging**
