### PR TITLE
Update LLVM submodule

### LINKED ISSUE #52026: next_back for a Vec is optimized incorrectly on i686
```
> rustc --version -v
rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
binary: rustc
commit-hash: e3bf634e060bc2f8665878288bcea02008ca346e
commit-date: 2018-06-28
host: i686-pc-windows-msvc
release: 1.28.0-nightly
LLVM version: 6.0
```

Optimized code of the following program panics if `-C codegen-units` is not 1.

```rust
struct S([u32; 2]);
fn main() {
    let x = vec![S([1, 2])];
    let mut it = x.iter();
    if let Some(_) = it.next_back() {
        assert!(it.next_back().is_none());
    }
}
```

`rustc tmp.rs -O -C codegen-units=2 --emit=llvm-ir` gives the following, incorrect LLVM IR for main:

```llvm
; tmp::main
; Function Attrs: uwtable
define internal void @_ZN3tmp4main17hcd108164c8e55929E() unnamed_addr #4 personality i32 (...)* @__CxxFrameHandler3 {
start:
  %x = alloca %"alloc::vec::Vec<S>", align 4
  %0 = bitcast %"alloc::vec::Vec<S>"* %x to i8*
  call void @llvm.lifetime.start.p0i8(i64 12, i8* nonnull %0)
  %1 = tail call i8* @__rust_alloc(i32 8, i32 4) #5
  %2 = icmp eq i8* %1, null
  br i1 %2, label %bb7.i, label %bb11

bb7.i:                                            ; preds = %start
; call alloc::alloc::handle_alloc_error
  tail call void @_ZN5alloc5alloc18handle_alloc_error17hfcecb1bb439aa45aE(i32 8, i32 4) #5
  unreachable

bb11:                                             ; preds = %start
  %_5.sroa.0.sroa.0.0._5.sroa.0.0..sroa_cast2.sroa_idx = bitcast i8* %1 to i32*
  store i32 1, i32* %_5.sroa.0.sroa.0.0._5.sroa.0.0..sroa_cast2.sroa_idx, align 4
  %_5.sroa.0.sroa.4.0._5.sroa.0.0..sroa_cast2.sroa_idx11 = getelementptr inbounds i8, i8* %1, i32 4
  %3 = bitcast i8* %_5.sroa.0.sroa.4.0._5.sroa.0.0..sroa_cast2.sroa_idx11 to i32*
  store i32 2, i32* %3, align 4
  %4 = bitcast %"alloc::vec::Vec<S>"* %x to i8**
  store i8* %1, i8** %4, align 4, !alias.scope !18, !noalias !21
  %_11.sroa.4.0..sroa_idx9.i = getelementptr inbounds %"alloc::vec::Vec<S>", %"alloc::vec::Vec<S>"* %x, i32 0, i32 1, i32 1
  store i32 1, i32* %_11.sroa.4.0..sroa_idx9.i, align 4, !alias.scope !18, !noalias !21
  %_11.sroa.5.0..sroa_idx11.i = getelementptr inbounds %"alloc::vec::Vec<S>", %"alloc::vec::Vec<S>"* %x, i32 0, i32 3
  store i32 1, i32* %_11.sroa.5.0..sroa_idx11.i, align 4, !alias.scope !18, !noalias !21
; invoke std::panicking::begin_panic
  invoke fastcc void @_ZN3std9panicking11begin_panic17hd01ed48f10d004fbE()
          to label %unreachable unwind label %funclet_bb4

funclet_bb4:                                      ; preds = %bb11
  %cleanuppad = cleanuppad within none []
; call core::ptr::drop_in_place
  call fastcc void @_ZN4core3ptr13drop_in_place17h64d221253ddb72c9E(%"alloc::vec::Vec<S>"* nonnull %x) #9 [ "funclet"(token %cleanuppad) ]
  cleanupret from %cleanuppad unwind to caller

unreachable:                                      ; preds = %bb11
  unreachable
}
```

### LINKED ISSUE #56618: Regression in rust-nightly 2018-12-02
Summary of the issue reported in tiberius at https://github.com/steffengy/tiberius/issues/87.

## Issue

When building [tiberius](https://github.com/steffengy/tiberius) with the latest nightlies,
an UDP send using tokio's UdpSockets mysteriously fails on windows:

MIOW `CompletionPort::get_many` returns an Error (only for release builds)
```
Io(Os { code: 10047, kind: Other, message: "An address incompatible with the requested protocol was used." })
```

## Reproduction
Checkout tiberius (or built against the version on crates.io) with the following file.
This might only reproduce on windows (in release builds!).
I have not yet confirmed on linux, the code and deps are different though so a linux build might not trigger it - the part returning the error is miow.

main.rs
```rust
use tiberius::SqlConnection;

fn main() -> Result<(), Box<std::error::Error>> {
    let future = SqlConnection::connect("server=tcp:127.0.0.1\\MSSQLSERVER;database=tibtest;integratedsecurity=sspi;trustservercertificate=true");
    tokio::executor::current_thread::block_on_all(future).unwrap(); // <- panic here

    println!("Done.");
    Ok(())
}

```

## Bisect
Bisected to commit d3ed34824c31f303b98855fee6fc9213dff1f295
@RalfJung since he might have an idea how this changeset could affect things.

Confirmed it with

- Command `cargo-bisect-rustc --start d09466ceb1374bd0ff1c490bfd50133b8ca67558 --end 4a45578bc58ff262864f72680cc02e83f5d2f5b3 --script=test.bat -v --prompt`

- test.bat
`cargo run --release main.rs`

## Observations

I could not produce a minimal testcase that reproduces this, since removing code or abstractions always led to removing the error no matter how unrelated it seemed. My first guess therefore was it's somehow optimization related - **since the error only seems to occur in release builds** - but for me that doesn't quite align with the bisected commit.

### PR DESCRIPTION
**Pull request by nikic**
Fixes #52026.
Fixes #56618.

r? @alexcrichton

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Heads up, @tromey.

**Comment by nikic** [comment]
@michaelwoerister This is just some cherry-picks, not a full LLVM upgrade, so it shouldn't break lldb.

**Pull request merged**
