### PR TITLE
libunwind_panic: adjust miri panic hack

### LINKED ISSUE #548: Miri is outdated
The Miri on playground is from 2019-11-08, there have been quite a few updates since then.

### PR DESCRIPTION
**Pull request by RalfJung**
We adjust the Miri hack in libpanic_unwind such that even with `cfg(miri)`, we build a version of libpanic_unwind that actually works.

This is needed to resolve https://github.com/integer32llc/rust-playground/issues/548.

r? @oli-obk @alexcrichton

### CODE REVIEW

**Comment by oli-obk** [comment]
Makes sensr

@bors r+

**Comment by Aaron1011** [comment]
@RalfJung: I don't understand why this is needed. Does the playground install Miri in a weird way?

**Comment by RalfJung** [comment]
No, but the playground adds a bunch of dependencies and one of them has a build script that panics. As you announced, our previous approach to handling this turns panics in build scripts into aborts.

**Comment by RalfJung** [comment]
Rebased.

@bors r=oli-obk

**Pull request merged**
