### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #104537 (fix std::thread docs are unclear regarding stack sizes)
 - #104558 (Don't assume `FILE_ID_BOTH_DIR_INFO` will be aligned)
 - #104564 (interpret: use Either over Result when it is not representing an error condition)
 - #104568 (clarify that realloc refreshes pointer provenance even when the allocation remains in-place)
 - #104611 (rustdoc: use real buttons for scrape examples controls)
 - #104640 (Migrate kdb style to CSS variables)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=104537,104558,104564,104568,104611,104640)

### CODE REVIEW

**Comment by lqd** [comment]
The regressions are recent `bitmaps` noise: 
@rustbot label: +perf-regression-triaged

image

However, it'd be nice to showcase the PR bringing the wins in the weekly report, likely #104564: 
@rust-timer build 793d7ee883b660b852a4d0588fb1a323246a51b1

**Comment by lqd** [comment]
(it would be cool if the post-merge perfbot messages wouldn't change the labels while we're investigating PRs within a rollup)

Note for weekly triage: the regressions here were noise, and the cool CTFE wins are coming from @RalfJung's #104564. 

And since it improved `eval_to_allocation_raw`, it's likely going to improve real-word CTFE-heavy crates (that we don't track in rustc-perf) similarly to `ctfe-stress-5`, and the ones in all the issues about big consts & statics being slow to compile.

**Comment by RalfJung** [comment]
Uh, why would using `Either` over `Result` result in a perf win...?^^

**Comment by lqd** [comment]
My theory was that it simplified the previous `Err` codepaths (e.g. removing some `Try`-related error conversions code), similar to making fallible code infallible which usually results in better codegen -- but I haven't checked.

**Comment by RalfJung** [comment]
No, `Err` was always replaced by `Left`/`Right` and no `?` were removed.

**Pull request merged**
