### PR TITLE
Resolve a bunch of fixmes

### PR DESCRIPTION
**Pull request by wesleywiser**
Resolves 56 fixmes in test code related to `box` syntax.

### CODE REVIEW

**Comment by petrochenkov** [comment]
If I remember correctly, "when/if possible" == "`box` is stabilized" in these FIXMEs.

**Comment by alexcrichton** [comment]
Thanks for the PR @wesleywiser I wonder though if we could perhaps avoid adding `#![feature(box_syntax)]` where not already specified and perhaps just delete the FIXME as the bug has already been fixed?

**Comment by wesleywiser** [comment]
@petrochenkov My understanding from reading #22405 was that the issue was not being able to infer the result of `box {expr}` in various cases. This no longer seems to be the case since the tests compile. 

@alexcrichton Sure I can do that. What do you think of @petrochenkov's comment? Does this need to wait for `box` stabilization?

**Comment by alexcrichton** [comment]
Oh well it seems that the motivation/purpose of this PR is to remove these FIXME annotations. I don't think the FIXME annotations need to literally be changed to use `box` as it's not stable, and the relevant bug appears to have been fixed. In that sense the FIXME annotations themselves aren't too useful any more so we can just delete them without changing over to using `box`.

I personally prefer to favor stable features wherever possible, so that's just my own personal preference for deleting outright instead of deleting and switching to `box`

**Comment by wesleywiser** [comment]
Easy enough! I'll push a new commit that simply removes the FIXMEs for this particular issue with no other changes.

**Comment by alexcrichton** [comment]
@wesleywiser looks like there's a pretty test failure on Travis?

**Comment by wesleywiser** [comment]
Thanks! I'll look into that tomorrow.

**Comment by wesleywiser** [comment]
@alexcrichton It should be fixed now. It looks like two of the Mac Travis bots failed trying to clone the repo and the other two have been stuck trying to clone for a few hours now. All of the other bots have passed.

**Comment by GuillaumeGomez** [comment]
Are we burrying the box syntax?! 😨

**Comment by michael-zapata** [comment]
There is a lot of places in the compiler where unstable features are being used, removing only the `FIXME` without using that lang item feels like a step backward, since this won't help pushing that feature out of the unstable zone.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @wesleywiser!

@michael-zapata these comments are all ancient and the bugs have all been fixed anyway, so I don't think we're going backwards here at all.

**Comment by alexcrichton** [comment]
@bors: retry

* there was an osx linker segfault (#38878) on travis but bors may not have gotten the notification, retrying to see if we can kick everything back into action

**Pull request merged**
