### PR TITLE
convert calls to `visit_all_item_likes_in_krate`

### PR DESCRIPTION
**Pull request by nikomatsakis**
We no longer need to track the tasks in these cases since these
particular tasks have no outputs (except, potentially, errors...)  and
they always execute.

cc #40746 

r? @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I left in the method itself because it is still used by the variance computation, which is tricky to address without adopting the red/green algorithm. (Working on it...)

**Review by eddyb — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@eddyb ok, will fix, I also have another commit that removes a bunch of other random tasks we should no longer need

**Pull request merged**
