### PR TITLE
Update backtrace submodule

### LINKED ISSUE #117941: error_with_backtrace_outputs_correctly_with_one_source fails on Windows7
Since https://github.com/rust-lang/rust/pull/117089 was merged, the `error_with_backtrace_outputs_correctly_with_one_source` std test fails with the following error on windows7:

```
---- error::tests::error_with_backtrace_outputs_correctly_with_one_source stdout ----
thread 'error::tests::error_with_backtrace_outputs_correctly_with_one_source' panicked at library/std/src/../../backtrace/src/dbghelp.rs:168:1:
called `Option::unwrap()` on a `None` value
```

After some further instrumentation, I was able to find out the source of the problem: `Failed to find SymAddrIncludeInlineTrace in dbghelp`. This was likely caused by https://github.com/rust-lang/backtrace-rs/commit/c1464fadd7c870c87818b86b6161ee188be6f3a4 , which reworked the backtracing code on windows to be faster through the use of newer APIs. Unfortunately, not all of those APIs are available in Windows 7.

### Version it worked on

72012402e1448348b8adf9423647c18a2f094726

### Version with regression

608e9682f0a6482903de8d3332770104a0ad943c

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by roblabla**
This PR updates the backtrace submodule, avoiding panics when resolving backtraces on Windows 7:

- https://github.com/rust-lang/backtrace-rs/pull/578

Fixes #117941

I ran the std unit tests locally on a Windows7 machine, and can confirm that this indeed fixes #117941.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
I've nominated this for a beta backport as otherwise we'd be breaking Windows 7 on the next stable release. We should avoid doing that until 1.76 at the earliest.

**Comment by wesleywiser** [comment]
Thank you so much @roblabla for fixing this and testing on Win 7! 

Just to ensure this stays near the top of the bors queue if a retry is needed:

@bors p=1 

Fixes stable-to-beta regression

**Comment by roblabla** [comment]
Heyo, is there a way to track the backporting process? It kinda looks like it fell through the cracks (all previously beta-nominated PRs have been accepted/rejected), and I'd be interested in seeing if there's any question I can help with.

(Also, I think this is missing a team label? I assume `t-libs`).

**Pull request merged**
