### PR TITLE
Rollup of 17 pull requests

### PR DESCRIPTION
**Pull request by sophiajt**
- Successful merges: #37255, #37537, #37547, #37556, #37557, #37564, #37565, #37566, #37574, #37577, #37579, #37583, #37585, #37586, #37587, #37589, #37596
- Failed merges:

### CODE REVIEW

**Comment by jonathandturner** [comment]
@bor r+ p=1

**Comment by jonathandturner** [comment]
cc @alexcrichton who tried a rollup earlier

**Comment by GuillaumeGomez** [comment]
A bit of everyone tried actually. :p

**Comment by alexcrichton** [comment]
gonna try again with https://github.com/rust-lang/rust/pull/37597

**Pull request closed without merging**
