### PR TITLE
smoke-test for async fn with mir-opt-level=0

### PR DESCRIPTION
**Pull request by RalfJung**
MIR opt levels heavily influence which MIR transformations run, and we barely test non-default opt levels. I am particularly worried about `async fn` lowering and how it might (not) work when the set of preceding MIR passes changes -- see https://github.com/rust-lang/rust/pull/70073.

This adds some basic smoke testing, where at least a few `async fn` `run-pass` test are ensured to also work with mir-opt-level=0.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
I wouldn't do this for the size tests as those could be affected by other optimizations running. For the smoke tests this seems good though.

**Comment by RalfJung** [comment]
The *size* can be affected by MIR optimizations?

**Comment by RalfJung** [comment]
Okay this does not touch the size tests any more.

**Comment by jonas-schievink** [comment]
> The _size_ can be affected by MIR optimizations?

Potentially yeah, at least in the future when we have some more advanced optimizations.

**Comment by RalfJung** [comment]
@jonas-schievink any chance you could review this?

**Review by jonas-schievink — APPROVED** [review]
Looks good. If you want you can also do this for some of the generator tests for some more diversity. But generally r=me

**Comment by RalfJung** [comment]
@jonas-schievink like so?

**Pull request merged**
