### PR TITLE
Allow overriding the TLS model

### PR DESCRIPTION
**Pull request by Amanieu**
This PR adds the ability to override the default "global-dynamic" TLS model with a more specific one through a target json option or a command-line option. This allows for better code generation in certain situations.

This is similar to the `-ftls-model=` option in GCC and Clang.

### CODE REVIEW

**Comment by Amanieu** [comment]
At the moment `get_tls_model` is called each time a `#[thread_local]` static is encountered. I would like to only call this once at the start, that way the TLS model string is validated even if there are no `#[thread_local]` statics. However I am not sure where I should do this and where I should put the cached value.

**Comment by Amanieu** [comment]
Ok, I'm now caching the parsed TLS model in the crate context. This PR is ready for merging.

**Comment by michaelwoerister** [comment]
r? @alexcrichton 

I think @alexcrichton is more qualified to review this.

**Comment by alexcrichton** [comment]
I don't really know what a TLS model is but it seems fine to expose for now. Can this be placed behind feature gates, however, to require nightly and go through the normal stabilization process?

**Comment by Amanieu** [comment]
I don't think we have a mechanism for putting a target json attribute under a feature gate.

**Comment by Amanieu** [comment]
Also, how do I mark a -C option as unstable?

**Comment by alexcrichton** [comment]
That's ok to leave the target json as-is, those are "pretty unstable" as-is anyway. For the options you can move it to `-Z` to make it unstable.

**Comment by Amanieu** [comment]
Done

**Pull request merged**
