### PR TITLE
Suggest correct syntax when writing type arg instead of assoc type

### LINKED ISSUE #20977: Compiler error could suggest using an associated type for e.g. Iterator<T>
If you accidentally write a bound like:

``` rust
pub struct Foo<T, I: Iterator<T>> { /* ... */ }
```

The error message is:

```
err.rs:3:22: 3:33 error: wrong number of type arguments: expected 0, found 1
err.rs:3 pub struct Foo<T, I: Iterator<T>> { x: I }
                              ^~~~~~~~~~~
```

The compiler could be more helpful in these cases where a trait takes 0 arguments but has an associated type and suggest something like: `Iterator has an associated type. Did you mean: I: Iterator<Item=T>?`.

### PR DESCRIPTION
**Pull request by estebank**
- When confusing an associated type with a type argument, suggest the appropriate syntax. Given `Iterator<isize>`, suggest `Iterator<Item = isize>`.
- When encountering multiple missing associated types, emit only one diagnostic.
- Point at associated type def span for context.
- Point at each extra type argument.

Follow up to #48288, fix #20977.

### CODE REVIEW

**Comment by estebank** [comment]
cc @nikomatsakis

**Comment by estebank** [comment]
The output can still be improved, IMO

```
error[E0107]: wrong number of type arguments: expected 0, found 1
 --> file2.rs:1:34
  |
1 | pub struct Foo { i: Box<Iterator<isize>> }
  |                                  ^^^^^ unexpected type argument

error[E0191]: the value of the associated type `Item` (from the trait `std::iter::Iterator`) must be specified
   --> file2.rs:1:25
    |
1   | pub struct Foo { i: Box<Iterator<isize>> }
    |                         ^^^^^^^^^^^^^^^ missing associated type `Item` value
    |
   ::: /Users/ekuber/personal/rust/src/libcore/iter/iterator.rs:104:5
    |
104 |     type Item;
    |     ---------- `Item` defined here
help: if you meant to assign the missing associated type, use the name
    |
1   | pub struct Foo { i: Box<Iterator<Item = isize>> }
    |                                  ^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

The span pointing at the associated type definition span seems superfluous (at least without the corresponding trait's def span) and the wording could do with some copy editing.

**Comment by durka** [comment]
"type value" is not good IMO. How about

> associated type `std::iter::Iterator::Item` must be specified

and

> to specify `Item`, write

**Pull request merged**
