### PR TITLE
Remove hack for js-sys and time-macros-impl

### PR DESCRIPTION
**Pull request by Aaron1011**
r? @ghost

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Deloper2297** [comment]
?

**Comment by Aaron1011** [comment]
First crater run: 440 regressions (https://crater-reports.s3.amazonaws.com/pr-73084-1/index.html)
Second crater run: 413 regressions (https://crater-reports.s3.amazonaws.com/pr-81863/index.html)

I think that the next step is to add a future-incompat-report lint once https://github.com/rust-lang/cargo/pull/8825 is merged

**Review by Deloper2297 — APPROVED** [review]

**Comment by crlf0710** [comment]
@Aaron1011 Ping from triage! Now that pr has been merged. What's next steps here?

**Comment by Aaron1011** [comment]
We are now emitting lints for both of these cases - there's still too much breakage to remove the hack entirely.

**Pull request closed without merging**
