### PR TITLE
try to reduce bajillion test warnings

### PR DESCRIPTION
**Pull request by Gankra**
- Adds features and allows 
- Removes unused muts, unused imports, dead code
- Migrates some deprecated code to new io/env
- Changes std::num::uint/int to be re-exports of std::num::usize/isize

libcollections, liballoc, and libcoretest no longer warn during testing.

libstd warns much less, though there's some dangly bits that weren't obvious fixes. In particular, how to only supress deprecated warnings in specific submodules of std.

### CODE REVIEW

**Comment by Gankro** [comment]
Ah dang some stuff snuck in while I was doing this. Will handle conflicts in the morning.

**Comment by alexcrichton** [comment]
r=me whenever this is ready

**Comment by Gankro** [comment]
Currently removing all the []'s, because I hate myself, apparently.

**Comment by Gankro** [comment]
Rolled back a bunch of my work to not conflict with other PRs.

@bors r=alexcrichton bee14ae

**Comment by Gankro** [comment]
@bors r-

bah

bugs bugs bugs

**Pull request merged**
