### PR TITLE
Add two functions to check type of SockAddr

### PR DESCRIPTION
**Pull request by achanda**
These can be used to determine the type of the underlying IP
address

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I might prefer to call this `is_ipv4` or `is_ipv6` to be clear what the "v" is as well, but otherwise looks reasonable to me.

cc @rust-lang/libs

**Comment by achanda** [comment]
Updated both!

**Comment by aturon** [comment]
I'm :+1: on these additions.

**Comment by achanda** [comment]
And this one too!

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

We'll want to file a tracking issue for these APIs as well, but that can happen just before merging

**Pull request merged**
