### PR TITLE
yeet `ReErased` from `HAS_FREE_LOCAL_NAMES` since `ParamEnv::and` hack is dead

### PR DESCRIPTION
**Pull request by compiler-errors**
I always thought this was kinda sketchy, but it was only needed due to the hack removed in #116417

r? types

### CODE REVIEW

**Comment by lcnr** [comment]
the only non-incr changed affected is `regex doc` and `regression-31157 debug`. I also prefer to change this, accepting the perf impact.

**Comment by lcnr** [comment]
I wasn't able to come up with any test where the param_env hack removed in this PR impacts behavior, but I am still in favor of avoiding such hacks whenever possible

**Comment by compiler-errors** [comment]
This is probably never gonna get approved.

**Pull request closed without merging**
