### PR TITLE
[experimental] Avoid sorting hashmaps during ICH computation.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR implements a different approach for computing stable hashes of unsorted maps. Instead of copying the map into an array and then sorting it, we compute a stable hash per entry and then combine the hashes in an order-independent way. Sounds great but it is not clear if the hash-per-entry introduces too much overhead for this to be a win. A perf run will show.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Queued perf -- should be enough time before it starts that this will finish.

**Comment by michaelwoerister** [comment]
Simulacrum living on the edge `:)` Thanks, Mark!

**Comment by michaelwoerister** [comment]
Link: http://perf.rust-lang.org/compare.html?start=860d169474acabdc53b9a698f8ce02eba7e0daeb&end=6104c1dff329c8c8fc979bca863e0e42923b601e&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, the results are still not available. Did something go wrong or do we just have a long queue currently?

**Comment by Mark-Simulacrum** [comment]
We have a very long queue currently; this PR is in queue and will be available in ~12.5 hours by my estimates, though I might be off by a couple hours I think. Sorry for the delay!

**Comment by michaelwoerister** [comment]
Wow, 12 hours `:)` Thanks for the info!

**Comment by michaelwoerister** [comment]
Performance results are in and it seems that the optimization is not really worth it. At least not in this particular form. We might want to revisit if we ever switch to a hasher with less overhead.

**Pull request closed without merging**
