### PR TITLE
rustc: Remove def::DefUse

### PR DESCRIPTION
**Pull request by petrochenkov**
A relic of some old resolution algorithm?

### CODE REVIEW

**Comment by petrochenkov** [comment]
>fatal: unable to write new index file
>Stopping at 'src/compiler-rt'; script returned non-zero status.

Needs retry

**Comment by Manishearth** [comment]
@bors retry

Failure caused by me shutting down the broken mac5 builder.

**Comment by petrochenkov** [comment]
Rebased.

**Comment by alexcrichton** [comment]
Everything passed here except the android builder which apparently disappeared, but this seems pretty unlikely to only fail on android, so I'm going to merge manually.

**Pull request merged**
