### PR TITLE
[beta] Backport union stabilization PRs

### PR DESCRIPTION
**Pull request by petrochenkov**
Supersedes https://github.com/rust-lang/rust/pull/42321

- https://github.com/rust-lang/rust/pull/42068
- https://github.com/rust-lang/rust/pull/42083

cc @aturon 
r? @brson

### CODE REVIEW

**Comment by est31** [comment]
I think this should be put into the release notes, no?

**Comment by brson** [comment]
I'm going to update the relnotes and backport as part of this pr.

**Comment by brson** [comment]
This isn't backporting the reference docs.

**Comment by brson** [comment]
There's no beta branch of the reference to backport the reference docs to.

I'm feeling fairly uncomfortable about this.

**Comment by nikomatsakis** [comment]
I'll copy my comment from #42068:

"I don't strongly object, but I'm surprised we would backport this. I feel like we try to keep backports to regressions or important bug fixes, and only rarely backport stabilizations -- the exception would be if some feature is hotly demanded. But otoh this seems pretty darn low risk, so no real objection."

**Comment by brson** [comment]
I'm going to look into backporting the reference directly from reference/master and see if it makes sense on beta.

**Comment by brson** [comment]
Here's the commit diff: https://github.com/rust-lang-nursery/reference/compare/6b0de90d87dda15e323ef24cdf7ed873ac5cf4d3...master

**Comment by brson** [comment]
Let's not do it. Feels risky to me.

**Comment by lilianmoraru** [comment]
So, this did not land?
The release notes say that it landed: https://github.com/rust-lang/rust/pull/42503/files#diff-5cafcf46bfb947f8e58fa5c16d39018cR13

**Pull request closed without merging**
