### PR TITLE
Allow #[inline] on closures

### LINKED ISSUE #49632: #[inline] is no longer accepted on closures
Since #49291 `#[inline]` is no longer accepted on closures, despite the fact that this attribute does have an effect on code generation.

The generated LLVM IR (in debug builds) for this example is different if you remove `#[inline(always)]`:
```rust
#![feature(stmt_expr_attributes)] 
#![crate_type="rlib"]

pub fn main() {
    let x = #[inline(always)] || {};
    x();
}
```

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #49632

### CODE REVIEW

**Comment by pietroalbini** [comment]
Highfive failed to assign a reviewer, @estebank?

**Comment by estebank** [comment]
It looks good to me, but deferring to @alexcrichton for final approval. The code looks correct but want a second pair of eyes to make sure there isn't some subtlety I'm not privy to.

r? @alexcrichton

**Comment by estebank** [comment]
Nevermind, reading the convo in the original issue, I feel more confident merging this as is.

@bors r+ rollup

**Comment by estebank** [comment]
@bors r-
@Amanieu you need to fix some tests https://travis-ci.org/rust-lang/rust/jobs/371877369#L1840

```
[00:41:45]     [ui] ui/error-codes/E0518.rs
[00:41:45]     [ui] ui/feature-gate/issue-43106-gating-of-inline.rs
```

**Comment by Amanieu** [comment]
Fixed.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @Amanieu!

To confirm, does this need a beta backport as well?

**Comment by Amanieu** [comment]
@alexcrichton That shouldn't be necessary since attributes on expressions (`stmt_expr_attributes`) are still unstable.

**Comment by alexcrichton** [comment]
Ok great, thanks!

**Pull request merged**
