### PR TITLE
rustdoc: Remove unnecessary `provided_trait_methods` field from Impl

### PR DESCRIPTION
**Pull request by jyn514**
It can be calculated on-demand.

Helps with https://github.com/rust-lang/rust/issues/76382.

### CODE REVIEW

**Comment by jyn514** [comment]
Around -.3% in instruction counts across the board, except regex which regressed by .3%. Up to -1.8% max rss with no major regressions. I think that tradeoff is worth it.

**Comment by CraftSpider** [comment]
Code looks good to me, I agree with the trade-off analysis. Needs a rebase to fix conflicts, then it should be good. I also appreciate the minor code deduplication :P

@rustbot lable: -S-waiting-on-review +S-waiting-on-author

**Pull request merged**
