### PR TITLE
Package more llvm-* tools in the rust-dev component, for run-make-fulldeps tests

### LINKED ISSUE #78110: "llvm-ar: No such file or directory" in run-make-fulldeps tests with download-ci-llvm
I recently added `profile = "compiler"` to `config.toml` in my local repository. In particular, this enables:

```toml
[llvm]
download-ci-llvm = "if-available"
```

When running the full test suite with `./x.py test` I get three errors similar to this:

```rust
---- [run-make] run-make-fulldeps/cross-lang-lto stdout ----

error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
LD_LIBRARY_PATH="/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/cross-lang-lto/cross-lang-lto:/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib:/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/stage0/lib" '/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc' --out-dir /home/simon/projects/rust/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/cross-lang-lto/cross-lang-lto -L /home/simon/projects/rust/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/cross-lang-lto/cross-lang-lto  lib.rs -Copt-level=2 -Clinker-plugin-lto -Ccodegen-units=1 --crate-type=staticlib -o /home/simon/projects/rust/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/cross-lang-lto/cross-lang-lto/liblib.a
(cd /home/simon/projects/rust/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/cross-lang-lto/cross-lang-lto; rm -f ./*.o; "/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/ci-llvm/bin"/llvm-ar x  liblib.a)

------------------------------------------
stderr:
------------------------------------------
warning: ignoring --out-dir flag due to -o flag

warning: 1 warning emitted

/bin/sh: /home/simon/projects/rust/build/x86_64-unknown-linux-gnu/ci-llvm/bin/llvm-ar: No such file or directory
make: *** [Makefile:23: staticlib] Error 127
```

Maybe the packaging of LLVM downloaded from CI needs to be fixed to include `llvm-ar`?

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes https://github.com/rust-lang/rust/issues/78110

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’ll test this as suggested in https://github.com/rust-lang/rust/issues/78110#issuecomment-712401625

@bors try

**Comment by SimonSapin** [comment]
With some more tools…

@bors try

**Comment by SimonSapin** [comment]
Alright, `./x.py test src/test/run-make-fulldeps` now suceeds with `download-ci-llvm = "if-available"` if I hard-code this try build instead of this:

https://github.com/rust-lang/rust/blob/554633534c550d20715e5e1576702b1f035586ad/src/bootstrap/bootstrap.py#L435-L439

But if we land this PR as-is, that logic will still pick the last bors commit that touched the LLVM submodule which for now is before this PR and so does not have the extra tools.

**Comment by Mark-Simulacrum** [comment]
Hm, I wonder if we should just add a stamp file somewhere and check that as well in the list - I feel like that's the right call here. Would you be up for doing that?

**Comment by SimonSapin** [comment]
Sure, what would be a good location?

**Comment by Mark-Simulacrum** [comment]
Let's put it in src/bootstrap/llvm-submodule-stamp. (But I don't care strongly).

**Comment by SimonSapin** [comment]
I believe this is ready for review and landing

**Pull request merged**
