### PR TITLE
First attempt at fixing nightlies

### PR DESCRIPTION
**Pull request by alexcrichton**
Looks like we've got a whole slew of bugs on our hands, let's try to fix them all at once.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

Let's see if we can get this in for tonight

**Comment by alexcrichton** [comment]
cc @nrc, a save-analysis change here

**Comment by frewsxcv** [comment]
This seems more important than the rollup

@bors p=20

**Pull request merged**
