### PR TITLE
Remove outdated references to librustc_middle

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
The relevant comment is now in https://github.com/rust-lang/rust/blob/791a53f380d5cf800191f25941c94ace5099876e/compiler/rustc_middle/src/tests.rs#L3-L13

### CODE REVIEW

**Comment by compiler-errors** [comment]
Can you fix the other 6 instances of `librustc_middle` in the codebase? Otherwise I don't see much purpose in putting up a PR that fixes just one.

@rustbot author

**Comment by fmease** [comment]
r? compiler

**Pull request merged**
