### PR TITLE
Enable zlib in LLVM on aarch64-apple-darwin

### PR DESCRIPTION
**Pull request by cbeuw**
Works on macOS 13.4, Xcode version 14.3.1.0.1.1683849156

This was disabled in #75500 on Apple Silicon Developer Transition Kit, but Apple appears to have fixed their zlib now

### CODE REVIEW

**Comment by clubby789** [comment]
r? @Mark-Simulacrum

Probably a better reviewer for this change

**Comment by Mark-Simulacrum** [comment]
> This PR changes how LLVM is built. Consider updating src/bootstrap/download-ci-llvm-stamp.

Let's bump the file. r=me with that done.

**Comment by cbeuw** [comment]
It's trying to download the CI LLVM of _this_ commit, chicken and egg...

```console
downloading https://ci-artifacts.rust-lang.org/rustc-builds/2e39d68a758dda553f52679ad332893b6acd9ea1/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
error: failed to download llvm from ci

    help: old builds get deleted after a certain time
    help: if trying to compile an old commit of rustc, disable `download-ci-llvm` in config.toml:
```

**Comment by Kobzol** [comment]
Hopefully it should work now that https://github.com/rust-lang/rust/pull/113323 is merged.

**Pull request merged**
