### PR TITLE
Remove some `Vec` allocations to improve performance

### PR DESCRIPTION
**Pull request by estebank**
This claws back most of the performance lost in https://github.com/rust-lang/rust/pull/69745.
r? @eddyb

### CODE REVIEW

**Comment by estebank** [comment]
If this doesn't have a significant impact the alternative to claw back some of the lost performance will be to make `Elaborator` have a type argument that can be either `Predicate` or `PredicateObligation`.

**Comment by estebank** [comment]
The last two commits have little/no impact so we can avoid them if we want.

**Comment by estebank** [comment]
I think this might have missed the train and we will likely want to backport it to beta.

**Comment by pnkfelix** [comment]
discussed at [T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/05709weeklymeeting2020043054818.html#195845136)

beta-accepted

**Pull request merged**
