### PR TITLE
Add `hi`, a very weird expression.

### PR DESCRIPTION
**Pull request by lylythechosenone**
So I noticed that `weird-exprs.rs` exists. I also noticed that this expression exists.

### CODE REVIEW

**Comment by lylythechosenone** [comment]
It also breaks clippy,
```
warning: unnecessary operation
  --> src/main.rs:10:1
   |
10 | / {{{{{{{{{{
11 | |     println!(
12 | |         "{}",
13 | |         {{{{{{{{{{{{{{{{{{{{
...  |
16 | |     )
17 | | }}}}}}}}}};
   | |___________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_operation
   = note: `#[warn(clippy::unnecessary_operation)]` on by default
help: statement can be reduced to
   |
10 + {{{{{{{{{
11 +     println!(
12 +         "{}",
13 +         {{{{{{{{{{{{{{{{{{{{
14 +             string
15 +         }}}}}}}}}}}}}}}}}}}}
16 +     )
17 + }}}}}}}}};
   |

warning: `playground` (bin "playground") generated 1 warning (run `cargo clippy --fix --bin "playground"` to apply 1 suggestion)
```
And rustfmt too
```rust
let string = "Hello, world!";
let string: String = {
    {
        {
            {
                {
                    {
                        {
                            {
                                {
                                    string
                                }
                            }
                        }
                        .chars()
                    }
                }
            }
            .collect()
        }
    }
};
{
    {
        {
            {
                {
                    {
                        {
                            {
                                {
                                    {
                                        println!("{}", {
                                            {
                                                {
                                                    {
                                                        {
                                                            {
                                                                {
                                                                    {
                                                                        {
                                                                            {
                                                                                {
                                                                                    {
                                                                                    // ...
```

**Comment by cuviper** [comment]
I suppose weirdness is subjective, but this one isn't surprising to me -- it's just deeply-nested block expressions. Maybe you could expect `rustfmt` to reduce them, but it does give the correct indentation for what's written. Is there more about this that I'm not seeing?

**Comment by lylythechosenone** [comment]
I mean the weird part is that it can just keep going. And the clippy part
is cursed.

**Comment by compiler-errors** [comment]
Yeah, I'm not personally inclined to land this since `weird-exprs.rs` is (as far as I can tell) more about *surprising* expressions than just weird formatting, etc. If the clippy suggestion is wrong, then it's probably just a clippy bug.

**Comment by clubby789** [comment]
The `hi` function in the PR doesn't trigger clippy, and the clippy output you show doesn't match the function either.

**Comment by lylythechosenone** [comment]
Hmm...the output above is from the rust bot on the discord server, maybe it's using an outdated version. As for Michael's concern, fair enough. It was surprising at the time ¯\_(ツ)_/¯. Thanks for your consideration at least. Closing here.

**Pull request closed without merging**
