### PR TITLE
Add long error explanation for E0539

### PR DESCRIPTION
**Pull request by unexge**
since this error is similar to [E0551](https://github.com/rust-lang/rust/blob/master/src/librustc_error_codes/error_codes/E0551.md) most of the content was copied from it. part of #61137.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
r? @Dylan-DPC 

Thanks 

Cc @GuillaumeGomez

**Comment by estebank** [comment]
There are some unaccounted errors in the example https://github.com/rust-lang/rust/runs/639210154#step:24:3941

**Comment by unexge** [comment]
i guess i need to add `#![feature(staged_api)]`

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks!

@bors: r+ rollup

**Pull request merged**
