### PR TITLE
Replace usages of `..i + 1` ranges with `..=i`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Before this change we were using old computer code techniques. After this change we use the new and improved computer code techniques.

### CODE REVIEW

**Comment by leonardo-m** [comment]
Before merging this I suggest to take a look at the performance effects. Because closed intervals still are slower (but such lower performance is significant only in some situations).

**Comment by frewsxcv** [comment]
@leonardo-m Is there an issue in this repo for tracking such performance issues?

**Comment by kennytm** [comment]
@leonardo-m #45222 has been closed pretty long time ago.

**Comment by leonardo-m** [comment]
I know, and the problem isn't solved well yet. I'll have to reopen that issue or create a new one...

**Comment by leonardo-m** [comment]
I've added a little example in Issue #45222.

**Comment by kennytm** [comment]
@rust-timer build 941e2d778dd7ee7bb9cc658c054e796d7fb9abcc

**Comment by frewsxcv** [comment]
Doesn't like like there's much of a difference in performance, right?

**Comment by Mark-Simulacrum** [comment]
Largely as expected -- ranges are almost definitively _not_ where the compiler spends its time. I'm okay landing this from a performance perspective.

**Pull request merged**
