### PR TITLE
Adjust documentation links for slice::make_ascii_*case

### PR DESCRIPTION
**Pull request by geeklint**
The documentation for the functions `slice::to_ascii_lowercase` and `slice::to_ascii_uppercase` contain the suggestion

> To lowercase the value in-place, use `make_ascii_lowercase`

however the link to the suggested method takes you to the page for `u8`, rather than the method of that name on the same page.

### CODE REVIEW

**Comment by m-ou-se** [comment]
Thanks!

Can you make the links use `slice::` instead of `#method.`? Then rustdoc will be able to verify them.

**Comment by geeklint** [comment]
> Thanks!
> 
> Can you make the links use `slice::` instead of `#method.`? Then rustdoc will be able to verify them.

Sure! I was just mirroring the inverse docs (e.g. [the docs of `make_ascii_lowercase`](https://doc.rust-lang.org/src/core/slice/ascii.rs.html#50)).  Does it make sense to also change those to `slice::` ?

**Comment by m-ou-se** [comment]
Ah yes. This feature of rustdoc is relatively new, and we haven't applied it everywhere in the standard library yet. So if you see any, feel free to update them. (See also https://github.com/rust-lang/rust/issues/75080, which was tracking the progress on that.)

**Comment by m-ou-se** [comment]
Oh, `slice::to_ascii_uppercase` does not work from the `make_ascii_uppercase` documentation, since the latter is defined in `core` and always available, and the former is only available in `alloc` and `std`. Sorry about that.

**Comment by geeklint** [comment]
Okay, so I should put the ones in core back to `#method.`?

**Comment by m-ou-se** [comment]
> Okay, so I should put the ones in core back to `#method.`?

Yes, let's do that for now.

@jyn514 Do you think rustdoc should handle this? We don't have a lot of types to which we add methods in both `core` and `alloc`/`std`, so it might not be worth it.

**Comment by m-ou-se** [comment]
Thanks! And congrats on your first contribution to the Rust standard library ^^

@bors r+ rollup

**Comment by jyn514** [comment]
> Oh, `slice::to_ascii_uppercase` does not work from the `make_ascii_uppercase` documentation, since the latter is defined in `core` and always available, and the former is only available in `alloc` and `std`. Sorry about that.

> @jyn514 Do you think rustdoc should handle this? We don't have a lot of types to which we add methods in both core and alloc/std, so it might not be worth it.

This is a very large can of worms - I would like it to work, but it's hard. https://github.com/rust-lang/rust/issues/74481

**Pull request merged**
