### PR TITLE
book: Clarify that trait or type must be in same crate as impl

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Or something :p

**Comment by kamalmarhubi** [comment]
Since the chapter on traits comes before the one on crates, would it make sense to either quick-define crates or reference the chapter?

**Comment by steveklabnik** [comment]
Yes, we need a forward reference to the crates chapter.

(and @bors will only listen to people with permission :wink: )

**Comment by kamalmarhubi** [comment]
Of course.

And done.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you so much!

**Pull request merged**
