### PR TITLE
DO NOT MERGE: Enable full backtraces

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by kennytm** [comment]
The last time I tried (#45693), while the CI duration is more or less the same for Linux, macOS slowed down to close to the 3 hour limit. So I don't think this can be unconditionally enabled.

**Comment by alexcrichton** [comment]
What's the rationale for this? (no PR description, no documentation...) Why `full `instead of `1`? Why set unconditionally in `bootstrap.py` with no option to turn it off?

**Comment by Zoxc** [comment]
I saw a heap corruption on Windows with backtraces enabled, so I wanted to see if that happened on CI too, but I guess `try` is Linux only and doesn't run tests now.

**Comment by kennytm** [comment]
@Zoxc Is there a bug for this?

**Comment by Zoxc** [comment]
@kennytm There is one now: https://github.com/rust-lang/rust/issues/46243

**Pull request closed without merging**
