### PR TITLE
Explicitly implement `DynSync` and `DynSend` for `TyCtxt`

### PR DESCRIPTION
**Pull request by Zoxc**
This is an attempt to short circuit trait resolution. It should get a perf run for bootstrap impact.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Did we expect this to be a speed-up? If not, is this still worth landing?

r? compiler-errors @rustbot author

**Comment by Zoxc** [comment]
I was expecting a bootstrap improving, which we did see.

**Comment by compiler-errors** [comment]
Okay then!

@bors r+

**Pull request merged**
