### PR TITLE
Clean up after clone3 removal from pidfd code (docs and tests)

### PR DESCRIPTION
**Pull request by safinaskar**
https://github.com/rust-lang/rust/pull/113939 removed clone3 from pidfd code. This patchset does necessary clean up: fixes docs and tests

### CODE REVIEW

**Comment by safinaskar** [comment]
My commits are self-contained and contain detailed commit messages. So "merge" is recommended as opposed to "squash-and-merge". But, of course, you may do whatever you want

**Comment by petrochenkov** [comment]
Formatting check is failing on CI, `x.py fmt` should help.
@rustbot author

**Comment by safinaskar** [comment]
Oops, I see errors. I will fix them

**Comment by safinaskar** [comment]
I fixed

**Pull request merged**
