### PR TITLE
Make pointers to statics internal

### LINKED ISSUE #67611: not Send due to await retainment
* root: updns-0.0.6: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/updns-0.0.6/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/updns-0.0.6/log.txt)

### PR DESCRIPTION
**Pull request by matthewjasper**
Closes #67611

r? @nikomatsakis

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
If this is to get into beta, then it needs to be approved ASAP; release week is next week. cc @pnkfelix @nikomatsakis

**Comment by nikomatsakis** [comment]
@matthewjasper test failures

**Comment by matthewjasper** [comment]
Tests are passing now.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+p=1

I'm going to go ahead and r+ this because I think it's imporant to fix the regression in a timely fashion. There is room to revisit the mechanism and/or discuss in more depth going forward.

(In particular, I'm not trying to shortcircuit lang or other discussion.)

**Comment by nikomatsakis** [comment]
Dear @rust-lang/compiler -- I'm taking the liberty of marking this regression as "beta-accepted" all on my own, because it's Friday and shortly before release. Please feel free to object.

**Pull request merged**
