### PR TITLE
Use `fold` in `Iterator::last` default implementation

### PR DESCRIPTION
**Pull request by czipperz**
We already use it in all the other methods.  Consistency + potential perf is a pretty nice win!

### CODE REVIEW

**Comment by czipperz** [comment]
cc @scottmcm @cuviper from #61726

**Comment by czipperz** [comment]
So `nth` doesn't work because `Self: Sized` is not necessarily fulfilled.  Why does `try_fold` require `Self: Sized`?  The default implementation doesn't use it and it doesn't take `self` by value.  Strange

**Comment by cuviper** [comment]
Regarding `try_fold` -- methods with generic parameters need `Self: Sized` for trait object safety. 

The `last()` change looks fine to me.

**Comment by czipperz** [comment]
Mmh.  I didn't think about that.  I'll change the title.

**Comment by scottmcm** [comment]
Looks good; thanks for the PR!

@bors r+ rollup

**Comment by scottmcm** [comment]
@bors r-

Actually, @czipperz, can you squash the commits here please?  The history for this PR looks like all it's doing is reverting itself.

**Comment by timvermeulen** [comment]
It shouldn't matter, but you may as well use `fold` here?

**Comment by llogiq** [comment]
I just did a quick benchmark and `self.fold(None, move |_, x| Some(x))` was around 10% faster, besides being shorter and IMHO more readable.

**Comment by czipperz** [comment]
I'm surprised it is that much faster wow!  Could you share your benchmark code / data?

**Comment by llogiq** [comment]
```
#![feature(test)]

extern crate test;
use test::{black_box, Bencher};

#[bench]
fn bench_for_each(b: &mut Bencher) {
    fn last<I: Iterator>(i: I) -> Option<<I as Iterator>::Item> where I: Sized {
        let mut last = None;
        i.for_each(|x| last = Some(x));
        last
    }
    let v = vec![0usize; 1024];
    b.iter(|| { last(black_box(v.iter())) })
}

#[bench]
fn bench_fold(b: &mut Bencher) {
    fn last<I: Iterator>(i: I) -> Option<<I as Iterator>::Item> where I: Sized {
        i.fold(None, move |_, x| Some(x))
    }
    let v = vec![0usize; 1024];
    b.iter(|| { last(black_box(v.iter())) })
}
```

Oops, I forgot running the benchmark with `-C opt_level=3`. The `for_each` version gets zero runtime with that, which kind of invalidates the benchmark, though. More research is needed.

**Comment by czipperz** [comment]
I do think `fold` is clearer though

**Comment by czipperz** [comment]
@scottmcm squashed it up

**Comment by scottmcm** [comment]
Thanks, @czipperz!

@bors r+ rollup

**Pull request merged**
