### PR TITLE
Point at var in short lived borrows instead of drop location

### LINKED ISSUE #39268: Misplaced span for the error "does not live long enough"
[Playground](https://is.gd/SdkR3U)

**Code**:

```rust
fn main() {
    let mut x = &5;
    {
        let y = 5;
        x = &y;
    }
}
```

**Compiler's output**:

```
error: `y` does not live long enough
 --> <anon>:6:5
  |
5 |         x = &y;
  |              - borrow occurs here
6 |     }
  |     ^ `y` dropped here while still borrowed
7 | }
  | - borrowed value needs to live until here

error: aborting due to previous error
```

Look at ` --> <anon>:6:5`.
It points to the `}`,
but I expected it to point to the `y`.

Look at `  |     ^ `y` dropped here while still borrowed`.
It is treated as a primary span,
but I expected `  |              - borrow occurs here` to be treated as a primary span.

It is bad for editors, i.e., VSCode.

### PR DESCRIPTION
**Pull request by estebank**
For RLS' sake, point at the borrow location as primary span for short lived borrows, instead of the borrow drop location.

Fix #39268.

### CODE REVIEW

**Comment by arielb1** [comment]
This looks like a nice unification. I basically just cargo-culted the AST borrowck scheme when moving to MIR borrowck.

**Comment by pnkfelix** [comment]
r=me once @estebank has addressed the travis failure

**Pull request merged**
