### PR TITLE
Remove incorrect docs from mem::transmute

### LINKED ISSUE #22032: Docs on std::mem::transmute incorrectly claim the types must have the same alignment
The [std::mem::transmute docs](http://doc.rust-lang.org/std/mem/fn.transmute.html) says:

> Both types must have the same size and alignment, and this guarantee is enforced at compile-time.

Experimentally, this function does not care about alignment:

```rust
#![feature(core)]
use std::simd::*;
use std::mem;

fn main() {
    let _ = unsafe { mem::transmute::<_,(u64,u64)>(u64x2(1,2)) }; // compiles just fine
}
```

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #22032

### CODE REVIEW

**Comment by reem** [comment]
Is there a reason for this not to be checked at compile time, or just implementation effort?

**Comment by steveklabnik** [comment]
@reem I asked @huonw if this was a bug or not, and he said that he hoped it wasn't checked, so maybe he can elaborate?

**Comment by huonw** [comment]
It doesn't seem to make sense to me for the alignment of the input value to matter for the output (the compiler just has to make sure the memory location storing the output has the right alignment), and it restricts things like transmuting SIMD types to/from arrays/tuples etc, and even say, `(u8, u8)` &harr; `u16`.

**Pull request merged**
