### PR TITLE
Miri subtree update

### PR DESCRIPTION
**Pull request by RalfJung**
r? @ghost

### CODE REVIEW

**Comment by jieyouxu** [comment]
Failed in rollup https://github.com/rust-lang/rust/pull/124204#issuecomment-2067774842

```
FAILED TEST: tests/panic\mir-validation.rs
command: "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\bin\\miri.exe" "--error-format=json" "--sysroot=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zmiri-provenance-gc=1" "-Zui-testing" "--target" "x86_64-pc-windows-msvc" "--extern" "getrandom_01=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-de8a1b4b21badd22.rlib" "--extern" "getrandom_01=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-de8a1b4b21badd22.rmeta" "--extern" "getrandom_02=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-e5f662dadaebb8db.rlib" "--extern" "getrandom_02=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-e5f662dadaebb8db.rmeta" "--extern" "libc=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\liblibc-3e0139bc6eeab6f9.rlib" "--extern" "libc=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\liblibc-3e0139bc6eeab6f9.rmeta" "--extern" "num_cpus=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libnum_cpus-127d4d81b9c33250.rlib" "--extern" "num_cpus=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libnum_cpus-127d4d81b9c33250.rmeta" "--extern" "rand=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\librand-01b5952caee7083c.rlib" "--extern" "rand=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\librand-01b5952caee7083c.rmeta" "--extern" "tempfile=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libtempfile-a86f06dcd7fa18db.rlib" "--extern" "tempfile=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libtempfile-a86f06dcd7fa18db.rmeta" "--extern" "page_size=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libpage_size-0ba767a1728111db.rlib" "--extern" "page_size=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libpage_size-0ba767a1728111db.rmeta" "--extern" "tokio=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libtokio-07db6c3a892515e9.rlib" "--extern" "tokio=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libtokio-07db6c3a892515e9.rmeta" "--extern" "windows_sys=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libwindows_sys-07455d154a735a27.rlib" "--extern" "windows_sys=C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libwindows_sys-07455d154a735a27.rmeta" "-L" "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\x86_64-pc-windows-msvc\\debug\\deps" "-L" "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\miri\\debug\\deps" "--out-dir" "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\ui\\tests\\panic" "tests/panic\\mir-validation.rs" "--edition" "2021"
##[error]no message
##[error]no message
##[error]remove this line and possibly later ones by blessing the test
error: panic test got exit code: 0x80000003, but expected 101
error: actual output differed from expected
error: actual output differed from expected
Execute `./miri test --bless` to update `tests/panic\mir-validation.stderr` to the actual output
--- tests/panic\mir-validation.stderr
 thread 'rustc' panicked at compiler/rustc_const_eval/src/transform/validate.rs:LL:CC:
 thread 'rustc' panicked at compiler/rustc_const_eval/src/transform/validate.rs:LL:CC:
 broken MIR in Item(DefId) (after phase change to runtime-optimized) at bb0[1]:
 #0 [optimized_mir] optimizing MIR for `main`
 end of query stack
-
-
-Miri caused an ICE during evaluation. Here's the interpreter backtrace at the time of the panic:
-   |
-   |
-LL |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
-   |
-
```

@bors r-

**Comment by RalfJung** [comment]
That's very strange... somehow catch_unwind does not seem to detect this ICE-induced unwinding, so our custom message is not printed -- but it works fine on Miri's own Windows CI.

@bjorn3  @nbdd0121 is there some reason that catch_unwind would not behave as expected on x86_64-pc-windows-msvc? Are we building the compiler without unwinding on some platforms, or something like that?

**Comment by RalfJung** [comment]
Oh we're also getting the wrong exit code
> panic test got exit code: 0x80000003, but expected 101

I have no idea what that means... I think I'll just disable the test on Windows.

@bors r+

**Pull request merged**
