### PR TITLE
[experiment] ty: add another pointer-sized field to `ParamEnv`.

### PR DESCRIPTION
**Pull request by eddyb**
The motivation is to be able to eventually avoid the drawbacks of keeping around global bounds (i.e. those that don't mention generic params) in `ParamEnvAnd`, i.e.: https://github.com/rust-lang/rust/blob/cdb50c6f2507319f29104a25765bfb79ad53395c/src/librustc/ty/mod.rs#L1840-L1844

Those drawbacks are primarily much worse caching (as it's keyed on all bounds in scope even if all of them mention parameters, and actual `value` doesn't) during type-checking and borrow-checking.

(Also, we currently ignore global bounds outside of the `UserFacing` mode, but I'm not sure that's entire correct, since it seems like it would cause CTFE and MIR optimization ICE easily)

I'm opening this PR to confirm (or, hopefully, disprove) that we can't just split the list into two lists and not cause regressions due to the larger size, since that's the easiest fix I can think of.

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
@nnethercote I'm surprised this isn't worse, especially with all of the static asserts for the sizes.

**Comment by bjorn3** [comment]
ctfe-stress-4-check clean has less specialize query invocations than before. Another instance of the non-determinism of syn-opt?


Query/Function | Time | % Total Time | Δ | Full Executions | Δ | Loading | Δ
-- | -- | -- | -- | -- | -- | -- | --
specializes | 0.002 | 0.02% | -18.1% (-0.000) | 1589 | -15.3% (-286.000) | 0.000 | 0.0% (0.000)

**Comment by eddyb** [comment]
I've seen that before, and discussed it a bunch with @Mark-Simulacrum.
It does look like another nondeterminism modality.

**Comment by nikomatsakis** [comment]
I'm going to close this to help me manage my queue, feel free to re-open @eddyb if desired.

**Pull request closed without merging**
