### PR TITLE
[stable] Emergency stable backports

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We include these for the compatibility notes:

- [`std::arch::x86::_rdtsc` returns `u64` instead of `i64`][stdsimd/559]
- [`std::arch::x86_64::_mm_shuffle_ps` takes an `i32` instead of `u32` for `mask`][stdsimd/522]

[stdsimd/522]: https://github.com/rust-lang-nursery/stdsimd/issues/522
[stdsimd/559]: https://github.com/rust-lang-nursery/stdsimd/issues/559

as well as the HashMap fix https://github.com/rust-lang/rust/pull/62304

**Comment by Centril** [comment]
Reminder: Please include 126be2c79412e21e37b64b46c0d36e143829a950 in master->beta promotion and when we bump the bootstrap compiler on master.

**Comment by Mark-Simulacrum** [comment]
fyi: we're going to punt this to tomorrow morning most likely due to the current travis outage; https://www.traviscistatus.com/incidents/g9xm3l02dknv

@bors retry to cede this to some other builder

**Comment by Mark-Simulacrum** [comment]
Travis claims backlog has cleared on .com, so let's try this again.

@bors r+

**Pull request merged**
