### PR TITLE
std: Rename io to old_io

### PR DESCRIPTION
**Pull request by alexcrichton**
In preparation for the I/O rejuvination of the standard library, this commit
renames the current `io` module to `old_io` in order to make room for the new
I/O modules. It is expected that the I/O RFCs will land incrementally over time
instead of all at once, and this provides a fresh clean path for new modules to
enter into as well as guaranteeing that all old infrastructure will remain in
place for some time.

As each `old_io` module is replaced it will be deprecated in-place for new
structures in `std::{io, fs, net}` (as appropriate).

This commit does _not_ leave a reexport of `old_io as io` as the deprecation
lint does not currently warn on this form of use. This is quite a large breaking
change for all imports in existing code, but all functionality is retained
precisely as-is and path statements simply need to be renamed from `io` to
`old_io`.

[breaking-change]

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that this hasn't quite finished bootstrapping yet (lots of tests to take care of), but wanted to get this out there as I'll probably finish by the time it hits bors :)

**Comment by aturon** [comment]
@bors: r+ 0e646ce

And so it begins.

**Comment by FlaPer87** [comment]
:tada:

**Comment by sfackler** [comment]
@alexcrichton would this be a good time to rename `write` to `write_all` as well?

**Comment by alexcrichton** [comment]
@sfackler I talked with @aturon on IRC about this and we were basically on the fence about that now. Taking the strategy of `old_io` draws a clear line between the old readers/writers and it's less clear to me that the rename is needed. It is still a bit of a porting hazard either way, but it requires breaking many `Writer` implementations today (and then re-breaking them later).

**Comment by untitaker** [comment]
Could anybody point me to design issues with the current ``io`` module? Which problems are so urgent that they would warrant a rewrite?

**Comment by aturon** [comment]
This is part of [io reform](https://github.com/rust-lang/rfcs/pull/517/).

It's not really a "rewrite", more a reorganization and slimming down of APIs (though there are a few deeper changes.)

**Comment by sfackler** [comment]
@alexcrichton so my concern is that when IO reform lands, people are going to update their trait imports, see it compiles and call it a day. Even if someone's aware of the change to `write`, there's a nonzero chance they'll miss a `write` -> `write_all` change or two, which won't be noticed until it subtly breaks things.

**Comment by aturon** [comment]
@sfackler @alexcrichton OK, I'm basically persuaded by @sfackler's argument. It's another relatively easy breaking change (like the `old_io` change) but could help prevent much more aggravating breakage later.

Want to roll that into this PR before it hits bors?

**Comment by sfackler** [comment]
Needs a rebase

**Pull request merged**
