### PR TITLE
add tests for alias bound preference

### PR DESCRIPTION
**Pull request by lcnr**
cc https://github.com/rust-lang/trait-system-refactor-initiative/issues/45

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
oh wait, this needs to wait for my "reveal opaques" pr to land, i'll approve it when it does

@bors r-

**Comment by lcnr** [comment]
added it as a new separate test, but still feels trivial enough and can revert if you disagree

@bors r=compiler-errors rollup

**Pull request merged**
