### PR TITLE
Update browser-ui-test version to 0.9.6

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This update provides a better error message when chromium crashes.

cc @jsha 
r? @Dylan-DPC

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Lot of network errors lately...

**Comment by Dylan-DPC** [comment]
yep that's why the tree is closed :P

**Comment by GuillaumeGomez** [comment]
And I was hoping that it was for a new release...

**Pull request merged**
