### PR TITLE
submodules: update clippy, rls and cargo, fix toolstate

### LINKED ISSUE #54697: Cargo warning during `x.py build`: "the cargo feature `edition` is now stable"
Plenty of lines like the following are printed during a build:
```
warning: the cargo feature `edition` is now stable and is no longer necessary to be listed in the manifest
```

This is likely caused by these:
```
src/tools/rls/Cargo.toml
1:cargo-features = ["edition"]

src/tools/clippy/Cargo.toml
1:cargo-features = ["edition"]

src/tools/clippy/rustc_tools_util/Cargo.toml
1:cargo-features = ["edition"]

src/tools/clippy/clippy_lints/Cargo.toml
1:cargo-features = ["edition"]

src/tools/clippy/clippy_dev/Cargo.toml
1:cargo-features = ["edition"]
```

### PR DESCRIPTION
**Pull request by matthiaskrgr**
rustfmt update failed because of different rustc-ap-syntax versions.

fix clippy toolstate failure

Fixes #54697

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
rebased

**Comment by matthiaskrgr** [comment]
````
[RUSTC-TIMING] rls test:false 74.396
    Finished release [optimized] target(s) in 4m 19s
[TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-msvc" }, target: "x86_64-pc-windows-msvc", tool: "rls", path: "src/tools/rls", mode: ToolRustc, is_optional_tool: true, source_type: Submodule, extra_features: ["clippy"] } -- 259.688
[TIMING] Rls { stage: 2, target: "x86_64-pc-windows-msvc" } -- 12.375
Dist LlvmTools stage2 (x86_64-pc-windows-msvc)
[TIMING] LlvmTools { stage: 2, target: "x86_64-pc-windows-msvc" } -- 21.311
Dist clippy stage2 (x86_64-pc-windows-msvc)
Building stage2 tool cargo-clippy (x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.74s
[TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-msvc" }, target: "x86_64-pc-windows-msvc", tool: "cargo-clippy", path: "src/tools/clippy", mode: ToolRustc, is_optional_tool: true, source_type: Submodule, extra_features: [] } -- 0.893
thread 'main' panicked at 'fs::File::open(&src) failed with The system cannot find the file specified. (os error 2)', bootstrap\lib.rs:1291:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap dist
Build completed unsuccessfully in 1:13:05
Command exited with code 1
set PATH=%PATH%;"C:\Program Files (x86)\Windows Kits\10\Debuggers\X64"
if exist %LOCALAPPDATA%\CrashDumps for %%f in (%LOCALAPPDATA%\CrashDumps\*) do cdb -c "k;q" -G -z "%%f"
````
Does that mean the binary was not found?Tthat's strange because I didn't see any clippy build failures in the log.

**Comment by oli-obk** [comment]
cc @rust-lang/infra

**Comment by alexcrichton** [comment]
This doesn't really look like a out-of-the-ordinary issue wrt building things, and it seems like it's probably related to the clippy submodule update. I'd recommend running the same steps locally and seeing if it fails, and perhaps using `RUST_BACKTRACE` to debug more (and/or adding debug prints).

**Comment by matthiaskrgr** [comment]
I don't have a windows env available and I but run the tests of all the changed submodules locally on linux and didn't see any regressions. Hmm...

**Comment by alexcrichton** [comment]
The bug here looks to be in packaging probably, so you'll need to be executing `./x.py dist`

**Comment by matthiaskrgr** [comment]
That worked, thanks.
I bisected the `dist` failure to https://github.com/rust-lang-nursery/rust-clippy/commit/ca437e81a730e2b449b50e00f3bb7f3d381f327d

**Comment by matthiaskrgr** [comment]
I probably need to update the dist install step to point to the new license files.

**Comment by matthiaskrgr** [comment]
Should be good to go now.

**Pull request merged**
