### PR TITLE
Allow a trailling comma in assert_eq/ne macro

### PR DESCRIPTION
**Pull request by sugar700**
From Rust beginners IRC:

&lt;???> It sure does annoy me that assert_eq!() does not accept a trailing comma after the last argument.
&lt;???> ???: File an issue against https://github.com/rust-lang/rust and CC @rust-lang/libs

Figured that might as well submit it. Will become insta-stable after merging (danger zone).

cc @rust-lang/libs

### CODE REVIEW

**Comment by kennytm** [comment]
cc @rust-lang/libs @zackmdavis

**Comment by xfix** [comment]
By the way, `assert_eq!(1, 1, "description",);` already works due to `format_args` macro allowing trailing commas.

**Review by dtolnay — APPROVED** [review]
Thanks! Seems good to me.

**Pull request merged**
