### PR TITLE
Update RLS

### PR DESCRIPTION
**Pull request by nrc**
r? @alexcrichton

### CODE REVIEW

**Comment by Manishearth** [comment]
(Something's weird with the homu queue, will reopen)

@bors clean retry

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout

**Comment by kennytm** [comment]
@bors retry

Failed to merge

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout

**Comment by kennytm** [comment]
@bors retry 

Failed to merge due to permission problem.

**Comment by kennytm** [comment]
Bors got tired of all the retries 🤷. Please rebase.

**Comment by nrc** [comment]
GAH!

**Comment by kennytm** [comment]
`test_all_targets` failed.

<details>

```
[01:20:57] failures:
[01:20:57] 
[01:20:57] ---- test::test_all_targets stdout ----
[01:20:57] 	expect_messages:
[01:20:57]   results: [
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":{\"capabilities\":{\"textDocumentSync\":2,\"hoverProvider\":true,\"completionProvider\":{\"resolveProvider\":true,\"triggerCharacters\":[\".\",\":\"]},\"definitionProvider\":true,\"referencesProvider\":true,\"documentHighlightProvider\":true,\"documentSymbolProvider\":true,\"workspaceSymbolProvider\":true,\"codeActionProvider\":true,\"documentFormattingProvider\":true,\"documentRangeFormattingProvider\":false,\"renameProvider\":true,\"executeCommandProvider\":{\"commands\":[\"rls.applySuggestion\",\"rls.deglobImports\"]}}}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_7\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_7\",\"message\":\"bin_lib\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_7\",\"message\":\"bin_lib\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_7\",\"message\":\"tests\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_7\",\"message\":\"bin_lib\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_7\",\"message\":\"bin_lib\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"done\":true,\"id\":\"progress_7\",\"title\":\"Build\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_6\",\"title\":\"Diagnostics\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"diagnostics\":[{\"code\":\"unused_variables\",\"message\":\"unused variable: `unused_var`\\n\\nnote: #[warn(unused_variables)] on by default\\nhelp: consider using `_unused_var` instead: `_unused_var`\",\"range\":{\"end\":{\"character\":18,\"line\":2},\"start\":{\"character\":8,\"line\":2}},\"severity\":2,\"source\":\"rustc\"}],\"uri\":\"file:///checkout/src/tools/rls/test_data/bin_lib/tests/tests.rs\"}}",
[01:20:57]     "{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"done\":true,\"id\":\"progress_6\",\"title\":\"Diagnostics\"}}"
[01:20:57] ],
[01:20:57]   expected: [
[01:20:57]     ExpectedMessage {
[01:20:57]         id: Some(
[01:20:57]             0
[01:20:57]         ),
[01:20:57]         contains: [
[01:20:57]             "capabilities"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "title\":\"Build\""
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "message"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "message"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "message"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "message"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "message"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "\"done\":true"
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "progress",
[01:20:57]             "title\":\"Diagnostics\""
[01:20:57]         ]
[01:20:57]     },
[01:20:57]     ExpectedMessage {
[01:20:57]         id: None,
[01:20:57]         contains: [
[01:20:57]             "bin_lib/tests/tests.rs",
[01:20:57]             "unused variable: `unused_var`"
[01:20:57]         ]
[01:20:57]     }
[01:20:57] ]
[01:20:57] thread 'test::test_all_targets' panicked at 'assertion failed: `(left == right)`
[01:20:57]   left: `11`,
[01:20:57]  right: `10`', tools/rls/src/test/harness.rs:223:5
[01:20:57] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:20:57] 
[01:20:57] 
[01:20:57] failures:
[01:20:57]     test::test_all_targets
[01:20:57] 
[01:20:57] test result: FAILED. 42 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

</details>

**Pull request merged**
