### PR TITLE
str: Implement str::trim_newline

### PR DESCRIPTION
**Pull request by ijackson**
This function was contemplated here https://github.com/rust-lang/rfcs/pull/3196#issuecomment-973567100

It seems like a good idea to me.  I chose to call it `trim_newline` rather than `trim_end_newline` since trimming newlines anywhere else would be weird, so `end` felt redundant.

I have not provided a method on `String` as contemplated in that issue.  We don't have any other mutating versions of `str` trimming methods, so everyone who wants that has to write `s.truncate(s.trim_wombat().len())`.  I think that's OK since it is more idiomatic to work with slices.

### CODE REVIEW

**Comment by ijackson** [comment]
Obviously, if the basic idea seems good I will open the tracking issue and update the MR branch.

**Comment by klensy** [comment]
This test will fail:
```rust
assert_eq!("Text", "Text\n\r".trim_newline());
```

**Comment by ijackson** [comment]
> This test will fail:
> ```rust
> assert_eq!("Text", "Text\n\r".trim_newline());
> ```
> 
> Ahh,
> ```
>     /// 'Newline' is precisely a newline character (`0xA`), perhaps
>     /// preceded by a carriage return (`0xD`).  I.e., `'\r\n'` or
>     /// `'\n'`.  (This is the same definition as used by [`str::lines`]
> ```

Indeed. Your response seems to me to demonstrate that the docs needed improving :-).  I have added the actual handling of this, with a note, to the example.

`lines()` treats `"Text\n\r"` as two lines, `"Text"` and `""`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=648cd55ce2178e7c3228e9f75d9b531b .  Arguably the 2nd line should be `"\r"` since there was no LF but it is surely too late to change that now.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@ijackson Can you post your status on this PR? thanks

**Comment by Dylan-DPC** [comment]
Closing this as inactive

**Pull request closed without merging**
