### PR TITLE
[WIP-test run] switch rustc allocator to mimalloc

### PR DESCRIPTION
**Pull request by gnzlbg**
Follow up to #62340 . Disables secure mode.

r? @mati865

### CODE REVIEW

**Comment by gnzlbg** [comment]
The mimalloc maintainers were finally able to reproduce our segfaults, so i'm closing this again since no progress can happen here until those issues are resolved. 

@Mark-Simulacrum there is currently a big barrier of entry to debug rustc issues. I think it would be worth documenting how to run rustc locally in the exact same way that CI does (e.g. using docker as @mati865 explains https://github.com/microsoft/mimalloc/issues/77 ). Also, when running a test fails, there is no easy way to just launch gdb/lldb/valgrind/etc. on the test. One currently gets the CLI invocation for the command that fails, but this does not includes all the environment variables required to run that command correctly.

**Comment by nico-abram** [comment]
Now that daanx figured out what was happening in https://github.com/microsoft/mimalloc/issues/77#issuecomment-572420277 , is it worth retrying?

**Comment by jq-rs** [comment]
I think it is. A new test run has been opened in #81782

**Pull request closed without merging**
