### PR TITLE
Simplify computation of killed borrows

### PR DESCRIPTION
**Pull request by cjgillot**
Follow-up to https://github.com/rust-lang/rust/pull/111759

Processing the first block manually once makes the pre-order walk simpler.

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
ngl I don't understand anything here :')

r? compiler

**Comment by WaffleLapkin** [comment]
r? compiler

**Comment by petrochenkov** [comment]
r? compiler

**Review by davidtwco — APPROVED** [review]

**Pull request merged**
