### PR TITLE
replace the hand-written binary search with the library one

### PR DESCRIPTION
**Pull request by guanqun**

### CODE REVIEW

**Comment by petrochenkov** [comment]
`lookup_source_file_idx` is a very weird function that conflates successful and unsuccessful lookups.

Looks like the previous version assumed that unsuccessful lookups cannot happen, but turns out they do happen (I've just checked) and the function returns a garbage index in this case.
I need to investigate a bit.

**Comment by petrochenkov** [comment]
Ah, sorry, I misunderstood how this works, we are searching through intervals rather than precise values, of course the search will almost always return `Err`.

**Comment by petrochenkov** [comment]
Could you compress the function a bit, like
```rust
    pub fn lookup_source_file_idx(&self, pos: BytePos) -> usize {
        self.files.borrow().source_files.binary_search_by_key(&pos, |key| key.start_pos)
            .unwrap_or_else(|p| p - 1)
    }
```
The asserts don't make much sense here, we'll get a panic one way or another anyway if the number of files is zero.

**Comment by guanqun** [comment]
Thank you @petrochenkov for the review and the double check. I just pushed a new commit to compress the function as you suggested. Please help review again, thanks!

**Pull request merged**
