### PR TITLE
Make PROC_MACRO_DERIVE_RESOLUTION_FALLBACK a hard error

### PR DESCRIPTION
**Pull request by Aaron1011**
r? @ghost

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
Unfortunately, one of the regressions is in the unmaintained crate https://github.com/MaikKlein/enumflags

**Comment by Aaron1011** [comment]
cc @petrochenkov - I'm not sure how you'd like to move forward with this. We could try to move people off https://github.com/MaikKlein/enumflags before we remove the hack, but that would still result in the crate become unusable (the last update was in 2019, and the repository has been archived).

**Comment by petrochenkov** [comment]
>I'm not sure how you'd like to move forward with this.

Leave it as is for a couple more years?
There's no pressure to remove deprecation lints urgently.
It can also be turned into an error on 2021 edition only in the meantime.

**Comment by crlf0710** [comment]
@Aaron1011 Do you want to turn this into an error on 2021 and later editions only? Or do you prefer this be closed?

**Comment by Aaron1011** [comment]
@crlf0710 I think that would be reasonable. While this could theoretically break some 2018 edition code in the presence of a sufficiently weird proc-macro (e.g. a proc-macro which marks the input tokens with a 2021 edition span), I think it would be good to make progress on this issue.

**Comment by JohnCSimon** [comment]
triage: 
@Aaron1011 - what is the status of this PR? Thanks.

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
cc @rust-lang/compiler 

This PR removes a backwards-compatibility hack that was added four years ago in https://github.com/rust-lang/rust/pull/51952.
Currently, we accept code like this:

```rust
// proc-macro crate
#[proc_macro_derive(AnswerFn)]
pub fn derive_answer_fn(_item: TokenStream) -> TokenStream {
	quote ! { mod generated_mod { struct Generated(TypeFromParent); }
}

// other crate
struct TypeFromParent;

#[derive(MyDeriveMacro)]
struct SomeOtherType;
```

Normally, this code would fail to compile, since `TypeFromParent` has not been imported into `generate_mod.` However, we currently detect this kind of usage in derive-macros *only*, and let it compile with a warning. (Note - this is about path resolution, *not* hygiene).


Now that https://crates.io/crates/enumflags-derive/0.4.2 has been released, all affected crates should have an upgrade path.

This has been part of `cargo report-future-incompat` since feature the future-incompat report feature was stabilized (https://github.com/rust-lang/rust/pull/89523), and has been deny-by-default since https://github.com/rust-lang/rust/pull/88041. There have been zero issues opened on rust-lang/rust mentioning either of these decisions.

This PR removes all of the backwards-compatibility code (along with the lint), simplifying `rustc_resolve` in the process. Any crates broken by this change are almost certainly unmaintained, and have an upgrade path if they use a dependency that's tested by Crater.

**Comment by lcnr** [comment]
@rfcbot fcp merge

**Comment by Aaron1011** [comment]
cc @nagisa @estebank @nikomatsakis @pnkfelix for review and checkboxes

**Comment by pnkfelix** [comment]
this probably should have been marked as rollup=never

**Comment by pnkfelix** [comment]
In particular, I have confirmed that this PR was what injected issue #106337.

I'm planning to open a PR reverting this one and beta-nominate it for the 1.67-beta (due for release as 1.67-stable on 2023-01-26) in order to buy us some time to talk about strategies for the macro implementation pattern described in #106337 and in issue #64079

**Pull request merged**
