### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Successful merges:

 - #50544 (Cleanup some dependencies)
 - #50545 (Made some functions in time module const)
 - #50550 (use fmt::Result where applicable)
 - #50558 (Remove all reference to DepGraph::work_products)
 - #50602 (Update canonicalize docs)
 - #50607 (Allocate Symbol strings from an arena)
 - #50613 (Migrate the toolstate update bot to rust-highfive)
 - #50624 (fs::write: Add example writing a &str)
 - #50634 (Do not silently truncate offsets for `read_at`/`write_at` on emscripten)
 - #50644 (AppVeyor: Read back trace from crash dump on failure.)
 - #50661 (Ignore non .rs files for tidy libcoretest)
 - #50663 (rustc: Allow an edition's feature on that edition)
 - #50667 (rustc: Only suggest deleting `extern crate` if it works)

Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
@Mark-Simulacrum could you take out #50613? There's some permission problem.

**Comment by Mark-Simulacrum** [comment]
@bors retry

Removed #50613

**Comment by kennytm** [comment]
@bors retry 

A homu bug (feature?) has interrupted this PR. @Manishearth is this an intended design on the servo side?

Timeline:

1. [2018-05-12T12:55:47Z](https://github.com/rust-lang/rust/pull/50684#issuecomment-388553440): #50684 is `r+`'ed. It was originally at the 10th place of the queue.
2. [2018-05-12T14:35:31Z](https://github.com/rust-lang/rust/pull/50684#issuecomment-388559319): A `try` build requested for #50684 for a perf run, which starts immediately.
3. [2018-05-12T15:30:03Z](https://github.com/rust-lang/rust/pull/50686#issuecomment-388562779): This PR started to test.
4. [2018-05-12T16:23:12Z](https://github.com/rust-lang/rust/pull/50684#issuecomment-388566231): `try` build of #50684 succeeded.
5. [2018-05-12T16:23:22Z](https://github.com/rust-lang/rust/pull/50684#issuecomment-388566239): **Immediately, #50684's real test begins**. This is the bug.
6. [2018-05-12T16:24:17Z](https://github.com/rust-lang/rust/pull/50686#issuecomment-388566294): As a result, the CI test for this PR got canceled by cancelbot.

Moral of the story: Do not run `@bors try` after it has been `r+`'ed.

**Comment by Manishearth** [comment]
Nah bors just can't track more than one state per PR

**Comment by kennytm** [comment]
@Manishearth  OK I'll see what can we do to prevent this scenario in the future. Perhaps just deny `@bors try` if the PR is already queued.

**Pull request merged**
