### PR TITLE
Skip running all lints if --cap-lints allow is used

### PR DESCRIPTION
**Pull request by bjorn3**
They won't be able to emit any warnings or errors anyway.

cc https://github.com/rust-lang/rust/issues/74704 and https://github.com/rust-lang/rust/issues/106983

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
This will not break something like first setting all lints to allow to then setting one particular lint to warn to only have findings of that particular lint, right?

**Comment by bjorn3** [comment]
No, this only affects `--cap-lints` which is used for non-local dependencies by cargo and overrides all lint level definitions in the source file. It seems that the `--force-warn` CLI arg takes precedent over `--cap-lints`, so I will need to run all lints anyway if `--force-warn` is used, but I figured I did first do a perf run before trying to implement that.

**Comment by lqd** [comment]
I also went down a similar route recently (including only doing the optimization when no `--force-warn` options were passed), and overall it seemed this would not be enough without some restructuring of lints and passes, for the reasons below. Let me know if my analysis was incorrect at the time.

> They won't be able to emit any warnings or errors anyway.

Some lints are required to be emitted even on dependencies, independently of `--force-warn` and of `--cap-lints=allow`, so this is subtly wrong IMO: some future-incompatibility lints could be [`FutureReleaseErrorReportNow`](https://github.com/rust-lang/rust/blob/c026d6a400a342e572bdd0de1abbb51680b28047/compiler/rustc_lint_defs/src/lib.rs#L352-L354) and they'd be ignored if we tok this approach of early-returning on cap-lints allow. And since some lints can be multiplexed with other lints in arbitrary passes, we may need to restructure and statically prevent some lints from being ignored when cargo is allowing lints, while allowing/ignoring the others in general.

In the end, the time save was also very small, in addition to only being applicable when building deps, so I didn't pursue this much further. IIRC only a small number of rustc-perf benchmarks had dependencies with "significant" linting time (I can find that data if you want), and it was at best a few hundred ms save in an otherwise slow multi-second builds.

IIUC this experiment is also changing the default to get something out of a perf run, otherwise no `--cap-lints=allow` would be applied there, but even that is going to be unrealistic as only the crates depending on the profiled ones would see lints being turned off in the real world ? (including our `bin` benchmarks)

**Comment by bjorn3** [comment]
> Some lints are required to be emitted even on dependencies, independently of --force-warn and of --cap-lints=allow, so this is subtly wrong IMO: some future-incompatibility lints could be [FutureReleaseErrorReportNow](https://github.com/rust-lang/rust/blob/c026d6a400a342e572bdd0de1abbb51680b28047/compiler/rustc_lint_defs/src/lib.rs#L352-L354) and they'd be ignored if we took this approach of early-returning on cap-lints allow.

Right, didn't think of that.

> In the end, the time save was also very small, in addition to only being applicable when building deps, so I didn't pursue this much further. IIRC only a small number of rustc-perf benchmarks had dependencies with "significant" linting time (I can find that data if you want), and it was at best a few hundred ms save in an otherwise slow multi-second builds.

Eyeballing `-Zself-profile` for libcore I estimate the save to be ~5%. Given that most changes I make to cg_clif require recompiling the standard library, this could save several seconds out of the ~40s I have to wait when making a change. But let's see what perf will tell us.

> IIUC this experiment is also changing the default to get something out of a perf run, otherwise no --cap-lints=allow would be applied there, but even that is going to be unrealistic as only the crates depending on the profiled ones would see lints being turned off in the real world ? (including our bin benchmarks)

Correct. This change won't help with most incremental rebuilds, but it should help with from scratch builds.

**Comment by Kobzol** [comment]
I actually wonder if e.g. for binary benchmarks, we profile only the final/leaf bin crate, or if we also profile its (local) crate dependencies in the same workspace that it depends on :thinking:

**Comment by lqd** [comment]
I think this may have removed more work than expected: possibly the need to typeck some items via the unused items lints, and CTFE allocation validation which is confusingly triggered by a lint. But maybe you wanted to focus at bootstrap times for crates depending on libcore ?

**Comment by apiraino** [comment]
I think @rustbot author

**Comment by bjorn3** [comment]
I don't intent on working on this again in the near future.

**Pull request closed without merging**
