### PR TITLE
Fix ICE in incremental compilation when rust-src component is changed

### PR DESCRIPTION
**Pull request by Aaron1011**
When importing source files from an external crate, we try to remap 'virtualized' filenames pointing into the standard library. However, we only do this remapping if the `rust-src` component is present on disk. As a result, the values we decode from a foreign crate's metadata depend on untracked global state.

This PR explicitly tracks our dependency on this global state via the `crate_hash` query. Instead of just returning an `Svh`, we return a `CrateHashAndState`, which holds the *current* state of the `rust-src` component. As a result, changes to this will cause all queries that depend on `crate_hash` (e.g. all external queries) to get re-run, avoiding the ICEs that result from an unexpected hash change.

### CODE REVIEW

**Comment by davidtwco** [comment]
@Aaron1011 is this still a work in progress or are you looking for a review?

**Comment by Aaron1011** [comment]
I'm still trying to reproduce the ICE with `src/test/run-make-fulldeps/incr-add-rust-src-component/Makefile ` - it should be happening now, but it isn't for some reason. Once I've done that, I'll add the actual fix (which is making a custom `PartialEq` and `HashStable` impl)

**Comment by Aaron1011** [comment]
We don't build the standard library with remapped debug info on CI, which means that the test `src/test/run-make-fulldeps/incr-add-rust-src-component` doesn't do anything.

**Comment by Aaron1011** [comment]
According to https://github.com/rust-lang/rust/pull/83813#discussion_r608573469, we actually *dont* want remapped paths in crate metadata. So, this PR might actually be redundant.

**Comment by Aaron1011** [comment]
This is now ready for review. The perf results look bad, but all of the large regressions are on extremely short benchmarks (e.g. `helloworld`). All of the larger results show minimal (< 1%) regressions. I suspect that these regressions are caused by the increase in the one-time cost of importing all source files from a foreign crate.

A large number of people are hitting https://github.com/rust-lang/rust/issues/84341 in various forms. I'm not 100% certain that this PR will fix all of those issues - however, it will definitely fix some, and will allow us to narrow down the cause of any ones which *aren't* fixed.

cc @rust-lang/wg-incr-comp

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
These changes look good to me, but someone else from incr-comp should probably take a look.

r? @wesleywiser

**Comment by Aaron1011** [comment]
There's been additional discussion in https://github.com/rust-lang/rust/pull/83813. The PR might end up being unecessary after all, or we might want to do with the simpler approach of wiping the entire incremental cache with `rust-src` changes. In any case, that PR will generate merge conflicts, so let's wait for it to get merged.

**Comment by Aaron1011** [comment]
Superseded by https://github.com/rust-lang/rust/pull/84233, which invalidates the entire incremental cache when `rust-src` changes.

**Pull request closed without merging**
