### PR TITLE
Implemented Default for arrays up to [T; 32]

### PR DESCRIPTION
**Pull request by withoutboats**
Implemented Default for arrays up to length 32 where T: Default using an additional macro.

### CODE REVIEW

**Comment by marcusklaas** [comment]
I'm not sure how exactly `array_impls!` works, but I think it should be possible to create array literals in macros.

**Comment by alexcrichton** [comment]
Could this reduce the verbosity a bit by taking a strategy similar to [this `peel!` macro](https://github.com/rust-lang/rust/blob/master/src/libcore/fmt/mod.rs#L1480-L1510)?

**Comment by withoutboats** [comment]
@alexcrichton I don't think so, because array syntax requires that each successive macro invocation insert a different integer literal.

I have managed to shorten it by removing all the `::default()` calls. Now each macro invocation fits on one line, at least.

**Comment by marcusklaas** [comment]
@withoutboats You're almost there! You can 'dynamically' create the integers by using `peel!`'s strategy. You have to pass along a `$counter:expr` argument to your macro, which you can either increment of decrement by 1 with each recursion!

**Comment by withoutboats** [comment]
Okay, this should be good now. I had no idea that `[T; 2 + 2]` was a valid type.

**Comment by alexcrichton** [comment]
Thanks! Could you also:

* Squash these commits together
* Tag the impl blocks with `#[stable(since = "1.4.0", feature = "array_default")]`

**Comment by withoutboats** [comment]
Done. :smile:

**Comment by andrey-gvrd** [comment]
Can you give an example of usage? My attempt:

    #[feature(array_default)]
    fn main() {
        let mut s: [String; 2] = [Default::default(); 2];
    }
Doesn't seem to work. I'm on `rustc 1.5.0 (3d7cd77e4 2015-12-04)`.

**Comment by jonas-schievink** [comment]
@andrey-gvrd `String` isn't `Copy`. Quoting the [array docs](http://manishearth.github.io/rust-internals-docs/std/primitive.array.html):

> Arrays values are created either with an explicit expression that lists each element: [x, y, z] or a repeat expression: [x; N]. The repeat expression requires that the element type is Copy.

Use `vec![Default::default(); 2]` to create a `Vec<String>` instead.

**Comment by withoutboats** [comment]
@andrey-gvrd The way to use this is actually `let mut s: [String; 2] = Default::default();`. You do not need to use the array declaration syntax.

**Pull request merged**
