### PR TITLE
Use some more `const_eval_select` in pointer methods for compile times

### PR DESCRIPTION
**Pull request by Noratrieb**
Builds on top of #105435

`is_aligned_to` is _huge_ with calling `align_offset`, so this should cut it down a lot.

This shows up in https://github.com/rust-lang/rust/issues/65031#issuecomment-1367574340

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Let's hope that this doesn't confuse Bors too much but try has been running for over 25 min I don't know what it's doing

@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
Oh. Yeah. That's a regression I think. Turns out inlining kind of matters.

@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
Looking very good, just like #105435 but even greener. The `regex` regression in `compute_debuginfo_type_name` is interesting, I'll investigate that. But overall, this looks pretty good.

**Comment by Nilstrieb** [comment]
r? thomcc

**Comment by thomcc** [comment]
Thanks!

@bors r+

**Comment by rylev** [comment]
As was [pointed out here](https://github.com/rust-lang/rust/pull/106275#issuecomment-1367904266), the improvements outweigh the regressions so no need to investigate further. 

@rustbot label +perf-regression-triaged

**Pull request merged**
