### PR TITLE
Fix selected crate search filter

### LINKED ISSUE #62929: Documentation: remember the selected crate in search
Right now it is allowed to select whether we want to search within all crates or in the specific ones (e.g. core, std, etc).

It would be really useful to remember the selected option, because in most cases we want to search in the std crate only.

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #62929.

r? @kinnison

### CODE REVIEW

**Review by kinnison — COMMENTED** [review]
I *think* this looks okay, but I'm not sure how to test it.  Can you remind me how to build the stdlib docs with x.py?

**Comment by GuillaumeGomez** [comment]
Sure, here you go: `./x.py doc src/libstd --stage 1`. Then it's generated inside `build/[your-archi]/stage1/doc/std/index.html`.

**Comment by kinnison** [comment]
So in local testing it doesn't seem to remember the crate selection for the search field when I build from your branch.  Am I meant to run up a local webserver for it to work?

**Review by kinnison — APPROVED** [review]
Okay, with a little help understanding how Firefox's local storage works on files, I have replicated this working.

**Comment by Dylan-DPC** [comment]
Neat! :Tada:

**Pull request merged**
