### PR TITLE
Point to the rustdoc attribute where intralink resolution failed.

### PR DESCRIPTION
**Pull request by kennytm**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Can you add a test for multiple lines please? (I want to be sure it won't give the first line of the doc comment.)

Also, in a second time, it'd be nice to get the span for the link directly instead of its line (but it's just an improvement so not mandatory for this PR).

**Comment by kennytm** [comment]
@GuillaumeGomez Done. It now selects the entire documentation block.

Unfortunately, I don't think it is possible to get the span of the link directly, because such information is not passed into [`pulldown-cmark`](https://docs.rs/pulldown-cmark/0.1.2/pulldown_cmark/struct.Parser.html#method.new_with_broken_link_callback) (the whole interface only deals with `&str`s).

Even we *can* compute the pointer offset of the `&str` relative to the whole markdown snippet, the generated span is still wrong because we removed those `///` and `//!` inside `collapsed_doc_value()`.

**Comment by GuillaumeGomez** [comment]
What I meant was for example:

```rust
/// a [link]
///
/// [blabla]
```

To give:

```
warning: [link] cannot be resolved, ignoring it...
--> $DIR/intra-links-warning.rs:1:1
  |
1 |  /// a [link]

warning: [blabla] cannot be resolved, ignoring it...
--> $DIR/intra-links-warning.rs:3:1
  |
3 |  /// [blabla]
```

**Comment by kennytm** [comment]
@GuillaumeGomez That's not possible either because `collapsed_doc_value()` (which returns a `String`) erased all information which `doc_string` the invalid link was found.

**Comment by GuillaumeGomez** [comment]
Hum :-/

**Comment by shepmaster** [comment]
Ping from triage, @GuillaumeGomez !

**Comment by GuillaumeGomez** [comment]
I wonder what we should do in here... Maybe just print the line where the link is and the line where the doc comment started? As is, it's not really useful (still better than what we have but not complete enough). Do you think you can do this?

**Comment by kennytm** [comment]
@GuillaumeGomez The output now looks like this:

```

warning: [Uniooon::X] cannot be resolved, ignoring it...
  --> $DIR/intra-links-warning.rs:13:1
   |
13 | / //! Test with [Foo::baz], [Bar::foo], ...
14 | | //!
15 | | //! and [Uniooon::X].
   | |_____________________^
   |
   = note: the link appears in this line:
           
            and [Uniooon::X].
                 ^^^^^^^^^^ 
```

**Comment by GuillaumeGomez** [comment]
Let's go for this version then. Thanks a lot!

@bors: r+

**Pull request merged**
