### PR TITLE
Update llvm submodule

### PR DESCRIPTION
**Pull request by Amanieu**
- [DIArgList] Re-unique after changing operands to fix non-determinism 
- [AArch64][GlobalISel] Fix an crash in RBS due to a new regclass being added.

### CODE REVIEW

**Comment by est31** [comment]
This should be beta backported, right?

**Comment by glandium** [comment]
> This should be beta backported, right?

It probably should, along #90301

**Comment by cuviper** [comment]
I've set the backport nomination, but please consider adding details for the compiler team's consideration.

**Comment by est31** [comment]
Backporting details: Due to the upgrade to LLVM 13.0, which is part of the 1.56.0 release, there has been a regression in which rustc create nondeterministic output: #90301 . The two commits that this PR backports fix this regression. Even though this might not warrant a point release 1.56.2, it does make sense to keep 1.57.0 from getting it.

**Comment by spastorino** [comment]
Wouldn't also make sense to add `stable-nominated`?. My understanding is that if it's approved for stable backport, the release team will just consider a point release but won't necessarily do it. Also a point release may happen for other reasons and if this is backported will just be included. cc @Mark-Simulacrum

**Comment by est31** [comment]
@spastorino yeah it would, especially considering that 1.56.0 is likely going to be the MSRV for many projects like 1.31.0 was, due to the edition.

**Comment by Amanieu** [comment]
Just to be clear, only the first commit is related to non-determinism. The second one fixes a crash with inline assembly, so strictly speaking it doesn't need to be backported but it doesn't hurt either.

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-18.20.2354818/near/261942064)

Also stable backport approved as per @spastorino suggestion.
Should this PR be considered for a point release? cc: @rust-lang/release 

@rustbot label +beta-accepted
@rustbot label +stable-accepted

**Comment by est31** [comment]
Good point about the other fix existing too. It's important that this PR does not contain the only determinism fix for llvm, the commit "[[RegAllocFast] Fix nondeterminism in debuginfo generation](https://github.com/rust-lang/llvm-project/commit/e048e97f5280e8a232a43ae134d395aeab67c2e8)" is also important. I've seen that beta does not include that commit either, but it is included as parent of the commits that this pr updated llvm to. So care should be taken that the backports of this PR don't just apply the two commits this PR added, but also the prior ones. Just updating the submodule to the [same commit](https://github.com/rust-lang/llvm-project/commits/f08c12fbedcd43f3ee04b0ebbeace60f8145e9b5) that this PR updated should do it. This also adds a drive by fix "[WebAssembly] Fix fixBrTableIndex removing instruction without checking uses", which is okay I think.

**Pull request merged**
