### PR TITLE
Vxworks / Unix deduplication

### PR DESCRIPTION
**Pull request by m-ou-se**
`sys/vxworks` was almost entirely an (outdated) copy of `sys/unix`. I went through every file to check the differences and tried to figure out if they were simply outdated or intentional differences between `unix` and `vxworks`. Most of them did not have any `vxworks`-specific changes, so are deleted. I've added some minor `cfg(target_os = "vxworks")`-specific things to `sys/unix` to allow for deduplication.

Before this change, the vxworks target didn't compile because its outdated process implementation did not match the expected interface anymore. This also fixes that: `std` compiles again for `x86_64-wrs-vxworks`.

It's probably good to merge `sys/vxworks` entirely into `sys/unix`, but it might be better to to that in a follow-up PR.

@rustbot modify labels: +T-libs +C-cleanup

### CODE REVIEW

**Comment by m-ou-se** [comment]
Cc @BaoshanPang

**Comment by lzutao** [comment]
This is nice, however there is no CI for Vxworks (tier 3).

**Comment by m-ou-se** [comment]
> there is no CI for Vxworks (tier 3)

Yup, I noticed. `std` didn't even build for `vxworks` before this PR. At least it builds now.

Keeping an oudated copy of `sys/unix` around is pretty annoying, as changes to `sys` now need to be applied to two slightly different copies of `sys/unix`. For example, #77674, #76651, etc. (Or not, but then the problem just becomes bigger over time as it becomes more outdated.)

**Review by dtolnay — APPROVED** [review]
Thanks!

Accepting without particular scrutiny beyond confirming that every thing changed in the PR is gated with `target_os = "vxworks"`.

**Pull request merged**
