### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
Sigh, `libc` pulls in another library.

**Comment by lnicola** [comment]
Can someone `r+` https://github.com/rust-lang/rust/pull/91967? Thanks.

**Comment by matthiaskrgr** [comment]
So the PR changed some dependencies..?
I'm a but surprised because I didn't see any Cargo.lock changes in the diff.

**Comment by lnicola** [comment]
This PR updates rust-analyzer, which bumped `libc 0.2.108` to `0.2.109` in https://github.com/rust-analyzer/rust-analyzer/commit/9a624abc84f997c71c2c6000d89efc32237e4ea3#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e, then to `0.2.111` in https://github.com/rust-analyzer/rust-analyzer/commit/8782e8e70412641ffe6d3be855649f90562876af#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eR807.

`libc` started using `libdevstat` in https://github.com/rust-lang/libc/commit/ac6e16b90fd36775341724cf0c6b00b4c8d33d60.

**Pull request merged**
