### PR TITLE
Remap paths from other crates

### LINKED ISSUE #66251: `--remap-path-prefix` does not apply to secondary files in diagnostics
Since #64151 added some new diagnostics, Rocket's UI tests have had mismatches in stderr that I can't seem to fix. In particular these diagnostics include "secondary file" paths that aren't easily normalizable or remappable.

I haven't tried to make a minimal reproduction yet, but this output should illustrate the problem:

```
 error[E0277]: the trait bound `usize: rocket::http::uri::Ignorable<rocket::http::uri::Query>` is not satisfied
-  --> $DIR/typed-uri-bad-type.rs:81:34
-   |
-81 |     uri!(other_q: rest = S, id = _);
-   |                                  ^ the trait `rocket::http::uri::Ignorable<rocket::http::uri::Query>` is not implemented for `usize`
-   |
-   = note: required by `rocket::http::uri::assert_ignorable`
+   --> foo/typed-uri-bad-type.rs:41:16
+    |
+41  | fn other_q(id: usize, rest: S) {  }
+    |                ^^^^^ the trait `rocket::http::uri::Ignorable<rocket::http::uri::Query>` is not implemented for `usize`
+...
+81  |     uri!(other_q: rest = S, id = _);
+    |     -------------------------------- in this macro invocation
+    | 
+   ::: /home/jeb/code/Rocket/core/http/src/uri/uri_display.rs:467:40
+    |
+467 | pub fn assert_ignorable<P: UriPart, T: Ignorable<P>>() {  }
+    |                                        ------------ required by this bound in `rocket::http::uri::assert_ignorable`

(...)

status: exit code: 1
command: "rustc" "tests/ui-fail/typed-uri-bad-type.rs" "-L" "/tmp" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/tmp/typed-uri-bad-type.stage-id" "--remap-path-prefix" "/home/jeb/code/Rocket=/Rocket" "--remap-path-prefix" "tests/ui-fail=foo" "-L" "crate=/home/jeb/code/Rocket/target/debug" "-L" "dependency=/home/jeb/code/Rocket/target/debug/deps" "--extern" "rocket_http=/home/jeb/code/Rocket/target/debug/deps/librocket_http-1faeb9d2934513de.rlib" "--extern" "rocket=/home/jeb/code/Rocket/target/debug/deps/librocket-44cf6b9b35acb885.rlib" "-L" "/tmp/typed-uri-bad-type.stage-id.aux" "-A" "unused"
```

Here I'm remapping `tests/ui-fail` to `foo` to demonstrate that `--remap-path-prefix` works at all. Remapping `/home/jeb/code/Rocket` to `/Rocket` is the real goal, because if I can get that to work we should have errors that are identical across build environments. However, it is not actually remapped in the output. Is `--remap-path-prefix` intended to apply to these?

My first attempt at this was to update compiletest to normalize `$SRC_DIR` (laumann/compiletest-rs#198), but that has some problems that I think the `--remap-path-prefix` approach would neatly avoid.

## Meta

`rustc --version --verbose`:

rustc 1.40.0-nightly (1423bec54 2019-11-05)
binary: rustc
commit-hash: 1423bec54cf2db283b614e527cfd602b481485d1
commit-date: 2019-11-05
host: x86_64-unknown-linux-gnu
release: 1.40.0-nightly
LLVM version: 9.0

### PR DESCRIPTION
**Pull request by jyn514**
Previously, `remap-path-prefix` only applied to files loaded *in the current session*. File names
loaded in a previous invocation were used unchanged. This is unfortunate for UI testing when some of
the crates involved are in the standard library (we don't want to recompile the standard library for
arbitrary tests).

Change it to apply to existing files as well. I believe this will eventually allow removing the
special-casing for `-Z simulate-remapped-rust-src-base`. I'm willing to make that change here if desired.

Fixes https://github.com/rust-lang/rust/issues/66251. This might allow me to unblock https://github.com/rust-lang/rust/pull/117609 without first waiting for https://github.com/rust-lang/rust/pull/113611 to land (need to test).

### CODE REVIEW

**Comment by jyn514** [comment]
@Nemo157 suggested that remapping should be *cumulative*, instead of giving precedence to the first flag. In other words, if a file is at path `/foo/lib.rs`, compiled with `remap-path-prefix=/foo=/bar`, and then used as a library in an invocation with `remap-path-prefix=/bar=/baz`, the final path used should be `/baz/lib.rs`, not `/bar/lib.rs` which the PR does currently. I'm willing to make that change but I'd like to hear from petrochenkov what he prefers.

**Comment by Urgau** [comment]
How do this take into account `-Zremap-path-scope`? Could you also add a test with `-Zremap-path-scope=diagnostics`.

**Comment by jyn514** [comment]
@Urgau it should work fine, remap-path-scope works by taking an existing `RealFileName::Remapped` and choosing whether to use `FileNameDisplayPreference::Remapped` or `FileNameDisplayPreference::Local`, it has to handle it by its nature. I'll add a test.

**Comment by petrochenkov** [comment]
Is there anybody familiar with this topic besides michaelwoerister, who is unavailable?
cc @cbeuw maybe

I only remember that path remapping has seen numerous changes and fixes in rustc and multiple RFCs, and it was never enough.

**Comment by petrochenkov** [comment]
The changes look reasonable to me, but I'm not sure what are the full implications.

I'm going to ping @rust-lang/compiler, then wait for a week, then r+.
@rustbot team

**Comment by cbeuw** [comment]
> @Nemo157 suggested that remapping should be cumulative

This has been brought up before: 

> Currently it does not look to me like we need remapping of imported paths (i.e. "double remapping") to fix https://github.com/rust-lang/rust/issues/73167. The compiler has the stable name of upstream file names available. I would opt for trying to fix the existing bugs without introducing new functionality (which would probably need a [major change proposal](https://forge.rust-lang.org/compiler/mcp.html)).
https://github.com/rust-lang/rust/pull/83813#issuecomment-814829096

I don't have an opinion either way, but if we were to introduce it, it should be a deliberate change through MCP. It shouldn't be introduced in this PR.

**Review by cbeuw — APPROVED** [review]

**Comment by michaelwoerister** [comment]
As far as I can tell, the main reason the remapping is only applied to the current crate is that remapped paths are emitted into compiled artifacts (e.g. panic messages in object files, debuginfo, etc) and subsequent compilation sessions cannot modify those anymore. The effect being that one gets an unpredictable mix of paths in the final output. 

For example, if there's a crate A containing an `#[inline]` function `foo()` that is called inside A, but also in crates B and C, each of which has a different path remapping, then a panicking call to `foo()` would point to different file paths, depending on which of the crates `foo()` was called in. 

From my point of view that is a blocker for recursive remapping. Making Cargo do the heavy lifting as described in the [trim paths RFC](https://github.com/rust-lang/rfcs/blob/master/text/3127-trim-paths.md) seems like the better approach to me.

**Comment by Dylan-DPC** [comment]
@jyn514 any updates on this? thanks

**Comment by jyn514** [comment]
nope

**Pull request closed without merging**
