### PR TITLE
Use Option::filter instead of open-coding it

### PR DESCRIPTION
**Pull request by LingMan**

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Looks good to me. @LingMan This is the way to go if you want to do these style changes, I think keeping it small have a higher chance of being accepted.

**Comment by Mark-Simulacrum** [comment]
I am not a maintainer of this particular code section, but the new version looks significantly less readable to me.

cc @matklad @petrochenkov as well

**Comment by matklad** [comment]
Yeah, I also don't think this is an improvement. Although the high-level semantic here is indeed that of `Option::filter`, closures do make code noisier and harder to understand. I don't see any clear cut ways to improve the code (`?` would make the shape awkward, and replacing unwrap_or_else with simpler unwrap_or would survive only until someone runs clippy again), so I think it makes sense to close the PR.

Thanks for the PR anyway, @LingMan, it's useful to see two versions side by side to better understand which one is better.

**Comment by LingMan** [comment]
Huh, interesting. I find it more readable because there's less brain power spent on deciphering the high-level semantic and more focus on what's relevant.
Your code, your choice. Thanks for considering it!

**Pull request closed without merging**
