### PR TITLE
update rtpSpawn's parameters type(It's prototype has been updated in libc)

### PR DESCRIPTION
**Pull request by BaoshanPang**
r? @alexcrichton

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim

**Comment by BaoshanPang** [comment]
@alexcrichton 

Can this change be merged into beta branch too? We are going to make a rust release for vxWorks, and we want to choose one from nightly and beta depend on which one is more stable for us.

**Comment by alexcrichton** [comment]
Sure thing, I'll tag this as nominated. Anyone from @rust-lang/libs object to backporting this?

**Comment by sfackler** [comment]
SGTM

**Comment by BaoshanPang** [comment]
@alexcrichton 

Thanks a lot.

**Pull request merged**
