### PR TITLE
[MIR] Refactor Drop to be a Terminator

### PR DESCRIPTION
**Pull request by nagisa**
The scope of these refactorings is a little bit bigger than the title implies. See each commit for details.

I’m submitting this for nitpicking now (the first 4 commits), because I feel the basic idea/implementation is sound and should work. I will eventually expand this PR to cover the translator changes necessary for all this to work (+ tests), ~~and perhaps implement a dynamic dropping scheme while I’m at it as well.~~

r? @nikomatsakis

### CODE REVIEW

**Comment by nagisa** [comment]
Note to self: still needs setting dropflags for call destination.

**Comment by nikomatsakis** [comment]
@nagisa ok, so I left various comments -- as I said, I'm still feeling unsure about the dynamic drop part of this patch. I'm pretty keen on the rest of it, though there is one downside to making "free" be a call to a lang-item. In particular, it makes its semantics opaque to borrowck. @pnkfelix (who is working on implementing the "move analysis" from borrowck) and I have been discussing whether we ought to be checking the `BOX` pattern. It'd probably be ok to make `BOX` and `FREE` both just calls to their respective lang-items -- after all, once the boxer/emplace protocol stuff lands, that's how it's going to be anyway. But maybe we want to do both?

Anyway, I wonder if you'd be up for separating out the dynamic drop part of this patch from the rest? I'd rather land the first part and keep discussing the dynamic drop question a bit more.

**Comment by nikomatsakis** [comment]
PS, in case it's not clear, nice work.

**Comment by nagisa** [comment]
Scope reduced and nits addressed (hopefully didn’t miss any)

**Comment by nagisa** [comment]
@bors r=nikomatsakis caf62ef

Argh, had completely forgotten about MSVC SEH.

**Pull request merged**
