### PR TITLE
[beta] Release notes, dist with time crate, and #48092

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Backports of 
 - #48092
 - #48013
 - #47286 
 - #48144

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Note that https://github.com/rust-lang/rust/pull/48092 has *not yet been approved* for beta backport, but it seems like a minimal patch that eddyb has cherry picked cleanly. If we don't make a decision by the time we're going to begin cutting stable this'll probably not go in.

**Comment by pietroalbini** [comment]
no space left on device -- #48144

**Comment by Mark-Simulacrum** [comment]
Added #48144.

@bors r=alexcrichton p=100 retry force

**Comment by Mark-Simulacrum** [comment]
@bors retry

Looks spurious.


```
[00:04:55] fatal: unable to access 'https://github.com/rust-lang/rust.git/': Empty reply from server
[00:04:55] thread 'main' panicked at 'command did not execute successfully: "git" "ls-remote" "origin" "master"
[00:04:55] expected success, got: exit code: 128', /checkout/src/build_helper/lib.rs:116:8
```

**Pull request merged**
