### PR TITLE
Reinitialize the dropflag hint in bindings

### LINKED ISSUE #27401: Drop flags on the stack not reinitialized in loops
It looks like that when a local variable is initialized in a loop and dropped in the same loop, the stack local drop flag for that local isn't reinitialized to "not dropped" when the loop runs after the first time.

Concretely, this test passes on stable and fails on nightly right now:

```rust
struct A<'a>(&'a mut i32);

impl<'a> Drop for A<'a> {
    fn drop(&mut self) {
        *self.0 += 1;
    }
}

fn main() {
    let mut cnt = 0;
    for i in 0..2 {
        let a = A(&mut cnt);
        if i == 1 {
            break
        }
        drop(a);
    }
    assert_eq!(cnt, 2);
}
```

cc @pnkfelix

### PR DESCRIPTION
**Pull request by pnkfelix**
Reinitialize the dropflag hint in occurrences of variable bindings.

Such bindings can occur in loops, and thus the binding can be executed after a previous move cleared the flag, thus necessitating the flag be reset to `DTOR_NEEDED_HINT`.

Fix #27401.

### CODE REVIEW

**Comment by pnkfelix** [comment]
hat-tip to @alexcrichton for narrowing down the crates.io unit test failures that exposed this bug!

**Comment by nikomatsakis** [comment]
r+ --- seems good, the only nit is that there could be a test for the dummy local case

**Comment by pnkfelix** [comment]
(i upp'ed priority because I want to get quicker feedback about problems in landing this PR, since I want to ensure it gets into beta but I may be traveling during the time that beta is cut.)

**Comment by pnkfelix** [comment]
An update: this PR appears to either inject a double-free, or somehow expose a latent one.  My suspicion is that the double-free is being "injected", though the real bug is probably somewhere deeper in the non-zeroing moves implementation.  Still looking.

**Comment by pnkfelix** [comment]
closing for now; I'll revive this later, but for the short-term we're just disabling NZM; see #27582

**Pull request closed without merging**
