### PR TITLE
Update snapshots to 2016-03-18 (235d774).

### PR DESCRIPTION
**Pull request by eddyb**
The new snapshots notably include @nikomatsakis' #32164 fix for the regionck error spew.
Also, `./configure --enable-orbit` _and/or_ `make RUSTFLAGS="-Z orbit"` should work now (#32080).

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like make tidy is failing?

Other than that r=me

cc @dhuseby, @semarie, @mneumann 

New snapshots!

**Comment by eddyb** [comment]
@retep998 says this will have to wait until a nightly which can satisfy rustbuild.

@bors r-

**Comment by nikomatsakis** [comment]
Hold the phone: when this lands, can we use `foo?` syntax?

**Pull request merged**
