### PR TITLE
Fix option link and anchor links.

### PR DESCRIPTION
**Pull request by alexispurslane**
This was pointed out by @filsmick and @swatteau in #28412.

### CODE REVIEW

**Comment by christopherdumas** [comment]
(Squashed the commits.)

**Comment by semmaz** [comment]
@steveklabnik @christopherdumas Shouldn't it be "fixed" the other way round, making `rustdoc` rendered `id` and `href` attributes of section identical to `href` rendered by github?

I'm willing to give it a try and see how many of breakage it will introduce to docs.

**Comment by steveklabnik** [comment]
@semmaz it would be nice if `rustdoc` were fixed to do that, but in the meantime, this is a nice, quick fix. With the release coming out soon, this can be backported, and we can fix the underlying issue For Real later, which will take more time. If you'd like to work on that, please do!

@christopherdumas you still have some LLVM changes in here :)

**Comment by steveklabnik** [comment]
oh, no, you fixed it. but it's still out of date for some reason, can you try to rebase please?

**Comment by christopherdumas** [comment]
Sure

**Comment by christopherdumas** [comment]
I rebased this.

**Pull request merged**
