### PR TITLE
librustc/util: DRY fmt::Display for ty::ProjectionTy

### LINKED ISSUE #43991: ICE: 'assertion failed: is_value_path', src/librustc/util/ppaux.rs:121:12
Applying the following diff on top of 7f397bdb produces the ICE `thread 'rustc' panicked at 'assertion failed: is_value_path', src/librustc/util/ppaux.rs:121:12`.

```diff
diff --git a/src/librustc/util/ppaux.rs b/src/librustc/util/ppaux.rs
index 184fd75135..3408c4b8e2 100644
--- a/src/librustc/util/ppaux.rs
+++ b/src/librustc/util/ppaux.rs
@@ -958,15 +958,7 @@ impl<'tcx> fmt::Display for ty::ProjectionPredicate<'tcx> {
 
 impl<'tcx> fmt::Display for ty::ProjectionTy<'tcx> {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        // FIXME(tschottdorf): use something like
-        //   parameterized(f, self.substs, self.item_def_id, &[])
-        // (which currently ICEs).
-        let (trait_ref, item_name) = ty::tls::with(|tcx|
-            (self.trait_ref(tcx), tcx.associated_item(self.item_def_id).name)
-        );
-        write!(f, "{:?}::{}",
-               trait_ref,
-               item_name)
+        parameterized(f, self.substs, self.item_def_id, &[])
     }
 }
 
```

```
$ RUST_BACKTRACE=1 ./x.py test --stage 1 --incremental ./src/rustc
Updating submodules
    Finished dev [unoptimized] target(s) in 0.0 secs
Building stage0 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling rustc v0.0.0 (file:///Users/tamird/src/rust/src/librustc)
   Compiling rustc_resolve v0.0.0 (file:///Users/tamird/src/rust/src/librustc_resolve)
   Compiling rustc_trans_utils v0.0.0 (file:///Users/tamird/src/rust/src/librustc_trans_utils)
   Compiling rustc_const_eval v0.0.0 (file:///Users/tamird/src/rust/src/librustc_const_eval)
   Compiling rustc_incremental v0.0.0 (file:///Users/tamird/src/rust/src/librustc_incremental)
   Compiling rustc_privacy v0.0.0 (file:///Users/tamird/src/rust/src/librustc_privacy)
   Compiling rustc_metadata v0.0.0 (file:///Users/tamird/src/rust/src/librustc_metadata)
   Compiling rustc_typeck v0.0.0 (file:///Users/tamird/src/rust/src/librustc_typeck)
   Compiling rustc_allocator v0.0.0 (file:///Users/tamird/src/rust/src/librustc_allocator)
   Compiling rustc_passes v0.0.0 (file:///Users/tamird/src/rust/src/librustc_passes)
   Compiling rustc_lint v0.0.0 (file:///Users/tamird/src/rust/src/librustc_lint)
   Compiling rustc_mir v0.0.0 (file:///Users/tamird/src/rust/src/librustc_mir)
   Compiling rustc_trans v0.0.0 (file:///Users/tamird/src/rust/src/librustc_trans)
   Compiling rustc_save_analysis v0.0.0 (file:///Users/tamird/src/rust/src/librustc_save_analysis)
   Compiling rustc_plugin v0.0.0 (file:///Users/tamird/src/rust/src/librustc_plugin)
   Compiling rustc_borrowck v0.0.0 (file:///Users/tamird/src/rust/src/librustc_borrowck)
   Compiling rustc_driver v0.0.0 (file:///Users/tamird/src/rust/src/librustc_driver)
   Compiling rustc-main v0.0.0 (file:///Users/tamird/src/rust/src/rustc)
    Finished release [optimized] target(s) in 203.92 secs
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Assembling stage1 compiler (x86_64-apple-darwin)
Building stage1 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling core v0.0.0 (file:///Users/tamird/src/rust/src/libcore)
   Compiling unwind v0.0.0 (file:///Users/tamird/src/rust/src/libunwind)
   Compiling libc v0.0.0 (file:///Users/tamird/src/rust/src/rustc/libc_shim)
   Compiling compiler_builtins v0.0.0 (file:///Users/tamird/src/rust/src/rustc/compiler_builtins_shim)
   Compiling alloc_jemalloc v0.0.0 (file:///Users/tamird/src/rust/src/liballoc_jemalloc)
   Compiling rustc_asan v0.0.0 (file:///Users/tamird/src/rust/src/librustc_asan)
   Compiling rustc_tsan v0.0.0 (file:///Users/tamird/src/rust/src/librustc_tsan)
   Compiling std v0.0.0 (file:///Users/tamird/src/rust/src/libstd)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-dev (ceeb399ce 2017-08-19) running on x86_64-apple-darwin

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: is_value_path', src/librustc/util/ppaux.rs:121:12
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::sys_common::backtrace::print
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: <std::thread::local::LocalKey<T>>::try_with
   8: <std::thread::local::LocalKey<T>>::with
   9: rustc::ty::context::tls::with
  10: rustc::util::ppaux::parameterized
  11: core::fmt::write
  12: core::fmt::Formatter::write_fmt
  13: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::sty::TypeVariants<'tcx>>::fmt
  14: core::fmt::write
  15: core::fmt::Formatter::write_fmt
  16: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::TyS<'tcx>>::fmt
  17: core::fmt::write
  18: core::fmt::Formatter::write_fmt
  19: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::sty::TypeAndMut<'tcx>>::fmt
  20: core::fmt::write
  21: core::fmt::Formatter::write_fmt
  22: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::sty::TypeVariants<'tcx>>::fmt
  23: core::fmt::write
  24: core::fmt::Formatter::write_fmt
  25: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::TyS<'tcx>>::fmt
  26: core::fmt::write
  27: core::fmt::Formatter::write_fmt
  28: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::sty::TypeVariants<'tcx>>::fmt
  29: core::fmt::write
  30: core::fmt::Formatter::write_fmt
  31: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::TyS<'tcx>>::fmt
  32: core::fmt::write
  33: core::fmt::Formatter::write_fmt
  34: rustc::util::ppaux::parameterized
  35: core::fmt::write
  36: core::fmt::Formatter::write_fmt
  37: rustc::util::ppaux::in_binder
  38: <std::thread::local::LocalKey<T>>::try_with
  39: <std::thread::local::LocalKey<T>>::with
  40: rustc::ty::context::tls::with
  41: rustc::util::ppaux::<impl core::fmt::Display for rustc::ty::sty::Binder<rustc::ty::sty::TraitRef<'tcx>>>::fmt
  42: core::fmt::write
  43: core::fmt::Write::write_fmt
  44: <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_type_binding_to_poly_projection_predicate
  45: <alloc::vec::Vec<T>>::extend_desugared
  46: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
  47: <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::instantiate_poly_trait_ref
  48: rustc_typeck::collect::predicates_of
  49: rustc::ty::maps::<impl rustc::ty::maps::queries::predicates_of<'tcx>>::try_get_with::{{closure}}::run_provider
  50: rustc::dep_graph::graph::DepGraph::with_task
  51: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  52: rustc::ty::maps::<impl rustc::ty::maps::queries::predicates_of<'tcx>>::try_get_with
  53: rustc::ty::maps::<impl rustc::ty::maps::queries::predicates_of<'tcx>>::try_get
  54: rustc::ty::maps::TyCtxtAt::predicates_of
  55: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::predicates_of
  56: rustc_typeck::collect::convert_item
  57: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  58: rustc::hir::Crate::visit_all_item_likes
  59: rustc_typeck::collect::collect_item_types
  60: rustc::util::common::time
  61: rustc::session::Session::track_errors
  62: rustc_typeck::check_crate
  63: <std::thread::local::LocalKey<T>>::try_with
  64: <std::thread::local::LocalKey<T>>::with
  65: rustc::ty::context::tls::enter
  66: <std::thread::local::LocalKey<T>>::try_with
  67: <std::thread::local::LocalKey<T>>::with
  68: rustc::ty::context::tls::enter_global
  69: rustc::ty::context::TyCtxt::create_and_enter
  70: rustc_driver::driver::phase_3_run_analysis_passes
  71: rustc_driver::driver::compile_input
  72: rustc_driver::run_compiler

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `/Users/tamird/src/rust/build/bootstrap/debug/rustc --crate-name core src/libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=27a0b780c8c3f494 -C extra-filename=-27a0b780c8c3f494 --out-dir /Users/tamird/src/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps --target x86_64-apple-darwin -L dependency=/Users/tamird/src/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps -L dependency=/Users/tamird/src/rust/build/x86_64-apple-darwin/stage1-std/release/deps` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/Users/tamird/src/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "-j" "4" "--target" "x86_64-apple-darwin" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/Users/tamird/src/rust/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:869:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_new
   5: std::panicking::begin_panic_fmt
   6: bootstrap::compile::run_cargo
   7: <bootstrap::compile::Std as bootstrap::builder::Step>::run
   8: bootstrap::builder::Builder::ensure
   9: <bootstrap::compile::Test as bootstrap::builder::Step>::run
  10: bootstrap::builder::Builder::ensure
  11: <bootstrap::check::Crate as bootstrap::builder::Step>::run
  12: bootstrap::builder::Builder::ensure
  13: <bootstrap::check::CrateLibrustc as bootstrap::builder::Step>::run
  14: bootstrap::builder::Builder::ensure
  15: <bootstrap::check::CrateLibrustc as bootstrap::builder::Step>::make_run::{{closure}}
  16: <bootstrap::check::CrateLibrustc as bootstrap::builder::Step>::make_run
  17: bootstrap::builder::StepDescription::maybe_run
  18: bootstrap::builder::StepDescription::run
  19: bootstrap::builder::Builder::run
  20: bootstrap::Build::build
  21: bootstrap::main
  22: __rust_maybe_catch_panic
  23: std::rt::lang_start
  24: main
failed to run: /Users/tamird/src/rust/build/bootstrap/debug/bootstrap test --stage 1 --incremental ./src/rustc
Build completed unsuccessfully in 0:03:34
```

cc @eddyb @tschottdorf

### PR DESCRIPTION
**Pull request by tamird**
r? @eddyb 

cc @tschottdorf 

Closes #43991, which seems to have been a mistake on my part.

### CODE REVIEW

**Comment by tamird** [comment]
This doesn't do the right thing. @eddyb can you provide some guidance?

**Comment by eddyb** [comment]
I think the problem is `parameterized` thinks only values can be associated items, but not types. Does `tcx.opt_associated_item` or a similarly named method exist?

**Comment by tamird** [comment]
Removing the assertion almost does the right thing:

```
-              found type `<impl Foo as Leak>::T`
+              found type `<impl Foo as Leak`
```

I don't suppose there's a way to step through this, is there?

**Comment by eddyb** [comment]
Ah the remaining problem is that the printing of the method name at the very end of `parameterized` is, well, specific to methods and does not handle type names, only value names.

**Comment by tamird** [comment]
Turns out `parameterized` doesn't handle the case of associated constants, making this approach a bit too naive.

**Comment by kennytm** [comment]
An ICE is triggered when building libcore at stage1.

```
[00:16:29] error: internal compiler error: unexpected panic
[00:16:29] 
[00:16:29] note: the compiler unexpectedly panicked. this is a bug.
[00:16:29] 
[00:16:29] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:16:29] 
[00:16:29] note: rustc 1.21.0-dev (738494e81 2017-08-20) running on x86_64-unknown-linux-gnu
[00:16:29] 
[00:16:29] thread 'rustc' panicked at 'assertion failed: is_value_path', /checkout/src/librustc/util/ppaux.rs:121:12
[00:16:29] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:16:29] 
[00:16:29] error: Could not compile `core`.
```

**Comment by eddyb** [comment]
@tamird Do you think we can close this PR for now?

**Comment by tamird** [comment]
Yep, meant to do that!

**Pull request closed without merging**
