### PR TITLE
Constify `pointer::is_aligned{,to}`

### PR DESCRIPTION
**Pull request by lukas-code**
In this PR i've made `<*const T>::is_aligned` and `<*const T>::is_aligned_to` unstably const.
The main motivation here is to allow something like `debug_assert!(is_aligned_and_not_null(ptr))` in `const fn`s without any `const_eval_select` hacks.

If we don't know the address of a pointer in const eval, this function only returns `true` if we know for sure that the pointer is aligned. This means that in some cases a pointer can never be aligned, which matches the behavior of [`align_offset`](https://doc.rust-lang.org/nightly/core/primitive.pointer.html#method.align_offset)[^1].

Tracking issue for `is_aligned`: https://github.com/rust-lang/rust/issues/96284

[^1]: Note that currently `align_offset` will always return `usize::MAX` in CTFE, but it could return a useful value for some alignments in the future.

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval 

I am not entirely sure about this... pointers are wonky in const and this function does not behave the way people will expect it to behave.

Also I think we should keep this and `align_offset` consistent, and we don't need a new intrinsic for this if we just do `align_offset == 0`.

**Comment by oli-obk** [comment]
> Also I think we should keep this and `align_offset` consistent, and we don't need a new intrinsic for this if we just do `align_offset == 0`.

yea, it should not add a new intrinsic, but be implemented in terms of the existing one.

**Comment by oli-obk** [comment]
> I am not entirely sure about this... pointers are wonky in const and this function does not behave the way people will expect it to behave.

the same is true for align_offset and `[T]::align_to`... which kind makes me want to just declare them "never gonna be const" and instead push the obligation to the caller who can use const_eval_select to skip the check

**Comment by saethlin** [comment]
I think doing that would make those interfaces more popular, people should be using the standard library instead of re-implementing these. Right now I know of a few people who specifically avoid them because of the vague caveat in the docs. If we remove that, there should be a proper announcement of the change in direction we're taking in designing pointer interfaces.

And I for one would like pressure for `const_eval_select` to be more usable.

**Comment by RalfJung** [comment]
Pressure doesn't help. People doing the work help. :)

**Comment by oli-obk** [comment]
> And I for one would like pressure for `const_eval_select` to be more usable.

I'm on it 😆

**Comment by saethlin** [comment]
I think I meant a different kind of pressure. If I can tell a compelling story, it's easy to motivate community members to pitch in.

**Comment by lukas-code** [comment]
I've put up an alternate PR which doesn't need a new intrinsic and uses `align_offset` instead: https://github.com/rust-lang/rust/pull/102795

**Comment by lukas-code** [comment]
Whoops, sorry for the massive ping. Pushed something here that I shouldn't have. Anyway, closing this in favor of https://github.com/rust-lang/rust/pull/102795.

**Pull request closed without merging**
