### PR TITLE
re-add Layout::for_value_raw

### PR DESCRIPTION
**Pull request by CAD97**
Tracking issue: #69835

This was accidentally removed in #70362 56cbf2f22aeb6448acd7eb49e9b2554c80bdbf79.
Originally added in #69079.

### CODE REVIEW

**Comment by CAD97** [comment]
(forgot to readd the docs, doing so)

**Review by arslan-raza-143 — COMMENTED** [review]
@CAD97

**Review by arslan-raza-143 — COMMENTED** [review]
@CAD97

**Pull request merged**
