### PR TITLE
More accurate error for binop errors after identifying RHS type

### LINKED ISSUE #44695: Ergonomics: &String does not implement PartialEq<str>
Start with this:

```rust
fn cmp_prefix() -> bool {
    let owned = "foo".to_owned();
    let string_ref = &owned;
    let partial = "foobar";
    string_ref == partial[..3]
}
```

It doesn't compile: "the trait bound `&String: PartialEq<str>` is not satisfied".

Let's [Google this](https://www.google.nl/search?q=rust+compare+String+with+str), first hit is [StackOverflow](https://stackoverflow.com/questions/25383488/how-to-match-a-string-against-string-literals-in-rust), first/accepted answer talks about `.as_ref()`, try that. `string_ref.as_ref() == &partial[..3]` results in "the trait bound `&_: PartialEq<str>` is not satisfied" [oh, how I hate these underscores in errors].

At this point I try adding `*` to the LHS or `&` to the RHS. The latter results in "type annotations required: cannot resolve `String: AsRef<_>`" [huh?].

Here's actually everything I tried (from my actual code instead of simple example):

```rust
meta_subj == db_subj[..998]
&meta_subj == &db_subj[..998]
meta_subj.as_ref() == &db_subj[..998] // I think this was before Googling, even
meta_subj.as_ref() == db_subj[..998]
meta_subj.as_ref::<&str>() == &db_subj[..998] // WTF is this thing with not resolving String: AsRef?
&meta_subj.as_ref() == db_subj[..998]
*meta_subj.as_ref() == db_subj[..998]
```

At this point I'm pretty much out of ideas other than brute-forcing with some `to_string()`. I don't really consider myself a beginner at this point, having successfully written a few thousand lines of code over the past 15 months, so here's where I have some empathy for those saying Rust's learning curve is just too steep.

I went and read some more on SO and found this, which actually seems to work `(meta_subj as &str) == &db_subj[..998]`. The reason I would not have come up with this is that generally the compiler seems to be able to coerce `&T where T: String` to `&str`, so I find it hard to come up with a reason it cannot do so in this case.

### PR DESCRIPTION
**Pull request by estebank**
Evaluate binops a second time with the resolved RHS type so we can provide suggestions for errors caused by trait predicates that didn't fail when looking for the binop with a type variable in the RHS.

Provide more casting and borrowing suggestions in binops.

Fix #44695, partially address #40660, partially address #57621 (we provide bad suggestion spans when `assert_eq!` is involved), doesn't account for #52544.

Zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Up.20to.20.255.20regression.20on.20kekkak.20with.20.2390006/near/258044068

### CODE REVIEW

**Comment by estebank** [comment]
@bors try @rust-timer queue

This is doing more work on the happy path (evaluating the binop twice, with a ty var and with a concrete ty). Let's see if I need to rework this for perf's sake.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@estebank can you please post the status of this PR?

**Comment by JohnCSimon** [comment]
Ping for triage: 
@estebank FYI this PR has sat idle for months.

**Comment by Dylan-DPC** [comment]
I am closing this as it is bitrotted.

**Pull request closed without merging**
