### PR TITLE
Update LLVM submodule

### LINKED ISSUE #89609: CI: dist-s390x-linux build went from 40min. to 160min with new LLVM pass manager
CI time quadrupled when the new pass manager was enabled:
* Last CI before  the new pass manager was enabled: https://github.com/rust-lang-ci/rust/runs/3707892000?check_suite_focus=true
* CI with the new pass manager was enabled: https://github.com/rust-lang-ci/rust/runs/3708445190?check_suite_focus=true

Right now that does not really matter much because Github's Apple CI runners use very old hardware and take about the same time, but once that is fixed this will block a faster CI. No idea if that platform has any significant userbase.

Maybe disable the new PM for that platform or report it upstream?

### LINKED ISSUE #93923: LLVM miscompilation/assert in `ui/issues/issue-23036.rs` on wasm32-unknown-unknown target
Context: #93697 - the test had to be disabled there to get a fix in

With [patched library/std/src/path.rs](https://github.com/rust-lang/rust/pull/93697/files#diff-212737b68c4541123dae6916cdde516551e1fafcb343467bfe08a3d7ce72c517) running the UI tests targeting wasm32 causes this failure with LLVM asserts enabled:

```
error: test compilation failed although it shouldn't!
status: signal: 6 (core dumped)
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-23036.rs" "-Zthreads=1" "--target=wasm32-unknown-unknown" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-23036/a.wasm" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/wasm32-unknown-unknown/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-23036/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
rustc: /checkout/src/llvm-project/llvm/lib/MC/WasmObjectWriter.cpp:149: void {anonymous}::writePatchableLEB(llvm::raw_pwrite_stream&, uint64_t, uint64_t) [with int W = 5; uint64_t = long unsigned int]: Assertion `SizeLen == W' failed.
------------------------------------------
```

With LLVM asserts disabled it produces invalid wasm bytecode:

```
/home/the8472/workspace/rust/src/etc/wasm32-shim.js:17
let m = new WebAssembly.Module(buffer);
        ^

CompileError: WebAssembly.Module(): Compiling function #3:"_ZN11issue_230364main17hf6fa4aae1344ccadE" failed: Invalid opcode 0xff @+874
    at Object.<anonymous> (/home/the8472/workspace/rust/src/etc/wasm32-shim.js:17:9)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

Manually executing the rustc command printed by the UI test and adding `--emit=llvm-ir` generates the following IR [repro.ir.txt](https://github.com/rust-lang/rust/files/8051876/repro.ir.txt). Running that through `llc` (built by bootstrap) also produces invalid bytecode (checked with `wasm-dis`).

Tested on base commit 686663a49e5 + PR #93697 (currently 45082b077b4)

@rustbot ping llvm

### LINKED ISSUE #94032: optimized i686 fails primal-sieve tests
Discovered in https://github.com/huonw/primal/pull/37#issuecomment-1040750795

### Code

I don't have reduced code, but the `primal-sieve` testsuite fails on `i686-unknown-linux-gnu` when compiled in `--release` mode, specifically on this line:
https://github.com/huonw/primal/blob/79bafd3400ecf530bea1d26db4f3854407588c2a/primal-sieve/src/sieve.rs#L769

```rust
    #[test]
    fn sum_primes() {
        let primes = Sieve::new(2_000_000);

        let mut manual_sum = 0u64;
        for p in primes.primes_from(0) {
            manual_sum += p as u64;
        }
        dbg!(manual_sum);

        let folded_sum = primes.primes_from(0).fold(0u64, |acc, p| acc + p as u64);
        let trait_sum = primes.primes_from(0).map(|p| p as u64).sum::<u64>();
        assert_eq!(manual_sum, folded_sum); // <-- FAILED
        assert_eq!(manual_sum, trait_sum);
    }
```

It fails when compiled from x86_64 host:
```
$ cd primal-sieve
$ cargo +nightly test --release --target i686-unknown-linux-gnu sum_primes
```
or with a native i686 host toolchain:
```
$cargo +nightly-i686 test --release sum_primes
```

I expected to see this happen: the test should pass

Instead, this happened: FAILED

```
---- sieve::tests::sum_primes stdout ----
[primal-sieve/src/sieve.rs:765] manual_sum = 307525716868
thread 'sieve::tests::sum_primes' panicked at 'assertion failed: `(left == right)`
  left: `307525716868`,
 right: `142913828922`', primal-sieve/src/sieve.rs:769:9
```

The left `manual_sum` is wrong, and the right `folded_sum` is correct. They both come from the same generated `primes` sieve, so that part of the code appears to have worked correctly. That leaves the difference between the `for` loop and the `fold`, and while `SievePrimes` does implement both `next` and `fold`, the differences are small.

The same test passes on i686 in debug mode, as well as x86_64 in debug or release.

### Version it worked on

It most recently worked on: stable Rust 1.58.1

### Version with regression

Both beta and nightly are failing the same way.

```
rustc 1.59.0-beta.8 (1945ce657 2022-02-12)
binary: rustc
commit-hash: 1945ce6579506787e0b18f0a2ea03fdb4dfc81c7
commit-date: 2022-02-12
host: x86_64-unknown-linux-gnu
release: 1.59.0-beta.8
LLVM version: 13.0.0
```

```
rustc 1.60.0-nightly (c5c610aad 2022-02-14)
binary: rustc
commit-hash: c5c610aad0a012a9228ecb83cc19e77111a52140
commit-date: 2022-02-14
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by nikic**
This merges upstream changes from the 14.x release branch.

Fixes #89609.
Fixes #93923.
Fixes #94032.

### CODE REVIEW

**Comment by nagisa** [comment]
Ugh, github has become even worse at showing just how exactly the submodule was updated :/

@bors r+

**Comment by lcnr** [comment]
woops, wrong button :sweat_smile: sry

**Comment by nagisa** [comment]
Is this a… interpreter/loader assert? Now that's a new one.

**Comment by nagisa** [comment]
Looks like it might be https://github.com/rust-lang/rust/pull/94779.

@bors retry (tree is closed, so its okay to retry…)

**Comment by nikic** [comment]
@retry That assertion is one of the spurious failures listed on https://github.com/rust-lang/rust/issues/93784.

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bweekly.5D.202022-03-10.20.2354818.html#274850703)

@rustbot label +beta-accepted

**Pull request merged**
