### PR TITLE
Update RLS and Rustfmt

### LINKED ISSUE #56261: rustfmt and rls are only available on x86, x86_64, aarch64, and arm+neon
Use of `rustfmt` -> `bytecount` -> `simd` only works on x86, x86_64, aarch64, and arm+neon, so all other arches are broken.  See also https://github.com/rust-lang/rustfmt/issues/3216.

I'm marking this as a regression since `rustfmt` and `rls` worked fine on all arches on 1.30 stable.  I'm aware the rest are not Tier-1 targets though.

I believe a simple workaround for distro packagers like myself would be to just patch out the enablement of `bytecount`'s `simd-accel` feature in `rustfmt/Cargo.toml`.

### PR DESCRIPTION
**Pull request by nrc**
Closes #56261

### CODE REVIEW

**Comment by nrc** [comment]
run-make failure - seems unlikely to be this PR, but I can't explain it

**Comment by nikic** [comment]
@nrc This is a spurious failure introduced by #49878, which will (hopefully) be fixed once #56396 lands.

**Comment by dlrobertson** [comment]
#56396 landed... Thanks for you patience, this is probably due for a retry

**Pull request merged**
