### PR TITLE
fixes #27124 for bitrig

### LINKED ISSUE #27124: Rust building is broken for BSD system
Starting with the latest update of LLVM, several BSD system don't be able to build rust anymore.

At least:
- freebsd: http://buildbot.rust-lang.org/builders/auto-freebsd10_64-1/builds/2/steps/compile/logs/stdio
- bitrig: http://buildbot.rust-lang.org/builders/auto-bitrig-64-opt/builds/1186/steps/compile/logs/stdio
- openbsd

The error message is the same of these three platform (here bitrig message):
```
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib" "x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib/std-7e44814b.0.o" "-o" "x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib/libstd-7e44814b.so" "x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib/std-7e44814b.metadata.o" "-Wl,-O1" "-nodefaultlibs" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/libcollections-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/librand-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/liballoc-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/librustc_unicode-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/liblibc-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/libcore-7e44814b.rlib" "-Wl,--no-whole-archive" "-L" "x86_64-unknown-bitrig/rt" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/x86_64-unknown-bitrig/llvm/Release/lib" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/.rust/lib/x86_64-unknown-bitrig" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/lib/x86_64-unknown-bitrig" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "rust_builtin" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-l" "backtrace" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-l" "rustrt_native" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "pthread" "-l" "c++abi" "-l" "c" "-l" "m" "-shared" "-l" "compiler-rt"
note: /tmp/rustc.M1grNw2xGkYD/libcollections-7e44814b.rlib: member /tmp/rustc.M1grNw2xGkYD/libcollections-7e44814b.rlib(__.SYMDEF) in archive is not an object
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

cc: @dhuseby @wg @vhbit @mneumann

### PR DESCRIPTION
**Pull request by dhuseby**
fixes the linking error on bitrig.

### CODE REVIEW

**Comment by alexcrichton** [comment]
You should be actually able to delete `archive_format` entirely I believe? You may also want to investigate and see if `gnu` is the format for these archives (I'm not sure what linkers broadly accept by default...).

This may also just indicate a bug in LLVM's implementation? Unsure :(

**Comment by dhuseby** [comment]
@alexcrichton the goal of Bitrig is to *not* use any GNU software so using the default `ar` is the correct solution.  Let me remove it and double check that it builds.

**Comment by alexcrichton** [comment]
Oh "gnu" in this case is just the format of the archive, not the actual tooling used to produce it.

**Comment by dhuseby** [comment]
@alexcrichton what's wrong with using the built-in ar?

**Comment by alexcrichton** [comment]
It generally works, but there are a number of wins for not depending on it:

* Running our own in-process `ar` is much speedier (no forking, less copying, etc)
* When cross compiling it's one less tool we have to find. For example cross compiling to bitrig is in theory easier if we don't run the system `ar`
* Helps us eventually remove this code path altogether (calling the system ar). We want to move to using LLVM's tooling as much as possible to ensure a consistent experience.

**Comment by dhuseby** [comment]
@alexcrichton alright, I tested "gnu" and it works just fine, let's go with that.  rebased and fixed.

**Pull request merged**
