### PR TITLE
Encode eval_always in the lowest bit of DepNodeKind

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build d980fb0060df0e981c26f6f50c452f3cf45d2b8f

**Comment by Zoxc** [comment]
@rust-timer build b4a209dff794e087e6b6e2105393883fdb1f0fa9

**Comment by oli-obk** [comment]
Didn't this yield any memory benefits?Maybe still leave a comment in the source mentioning that packing doesn't improve anythingOn 24 Apr 2019 17:18, Zoxc <notifications@github.com> wrote:Closed #59988.

**Comment by Zoxc** [comment]
@oli-obk No, it was just a way to quickly identify dep nodes which were `eval_always`. However https://github.com/rust-lang/rust/pull/60035 marks `eval_always` dep nodes as `Invalid` when loading them, so we don't need to know anything about the dep nodes while marking them green.

**Pull request closed without merging**
