### PR TITLE
Fix rustdoc formatting of impls

### PR DESCRIPTION
**Pull request by wthrowe**
This fixes a couple of bugs visible on https://doc.rust-lang.org/nightly/std/marker/trait.Sync.html .  For example:
- `impl<T> Sync for *const T` should read `impl<T> !Sync for *const T`
- `impl<T> !Sync for Weak<T>` should read `impl<T> !Sync for Weak<T> where T: ?Sized`

This does change a struct in librustdoc and it seems that almost everything there is marked public, so if librustdoc has stability guarantees that could be a problem.  If it is, I'll find a way to rework the change to avoid modifying public structures.

### CODE REVIEW

**Comment by steveklabnik** [comment]
librustdoc has no stability guarantees, so that's fine. code looks good to me, but I'd like someone else to sign off on it too.

**Comment by tomjakubowski** [comment]
Could you add tests for this? The rustdoc test suite isn't terribly well-documented, but see https://github.com/rust-lang/rust/tree/master/src/test/rustdoc for some examples. The script that runs the rustdoc tests is called [htmldocck.py](https://github.com/rust-lang/rust/blob/master/src/etc/htmldocck.py). Please ask questions if you have any!

**Comment by wthrowe** [comment]
I've added a test covering two of the three cases where impls are currently printed.  I think the third is only used for cross-crate implementations of traits, so I'm not sure if there's an easy way to test that.  (They all use the same formatting code now, so I don't think it's all that important to test the last case.)

**Comment by tomjakubowski** [comment]
Thanks so much! Yeah, cross-crate rustdoc tests are a pain (and unfortunately, also the kind of docs that break the most often). What you want to do for those is write a crate file in `src/test/auxiliary`, and then import that crate into a crate in `src/test/rustdoc` (and `pub use` whatever you need to to exercise the test).

Here's an example:

rustdoc test crate: https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/default-impl.rs
auxiliary test crate: https://github.com/rust-lang/rust/blob/master/src/test/auxiliary/rustdoc-default-impl.rs

**Comment by alexcrichton** [comment]
Looks great to me as well, thanks @wthrowe! r=me if a test like @tomjakubowski mentioned is added.

**Comment by wthrowe** [comment]
Thanks for the tips!  Here's another test!

**Comment by alexcrichton** [comment]
@bors: r+ dd82df67cb53d48833a9be5b60fbf3837136025f

Thanks!

**Comment by alexcrichton** [comment]
Ah right I believe that all cross-crate rustdoc tests need some special sauce for android, I believe you can fix this by just adding `// ignore-cross-compile` at the top.

**Comment by wthrowe** [comment]
See if that does it.

**Pull request merged**
