### PR TITLE
Pointer printing: do not print 0 offset

### PR DESCRIPTION
**Pull request by RalfJung**
r? @eddyb Cc @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
@oli-obk maybe we should just land this without waiting for @eddyb?

**Comment by oli-obk** [comment]
I thought I reviewed this again, and had a definite deja vu effect going through the changes

r? @oli-obk 
@bors r+

**Comment by Dylan-DPC** [comment]
@bors r-

failed in [rollup](https://github.com/rust-lang/rust/pull/72132#issuecomment-627219329)

**Pull request merged**
