### PR TITLE
fs: Use readdir() instead of readdir_r() on Linux and Android

### LINKED ISSUE #34668: `readdir_r` is deprecated as of glibc-2.24
Per [bug 19056](https://sourceware.org/bugzilla/show_bug.cgi?id=19056), glibc-2.24 has deprecated `readdir_r` and `readdir64_r` in favor of plain `readdir` and `readdir64`.  The reasons are discussed on the updated [manpage](http://man7.org/linux/man-pages/man3/readdir_r.3.html).

It states that `readdir` is already thread-safe in "modern" implementations, including glibc.  We should see if all platforms targeted by `unix/fs.rs` satisfy this.  Note that the Solaris (Illumos) port is already using plain `readdir`.

It requires external synchronization if a particular directory stream may be shared among threads, but I believe we avoid that naturally from the lack of `&mut` aliasing.  `Dir` is `Sync`,  but only `ReadDir` accesses it, and only from its mutable `Iterator` implementation.

### LINKED ISSUE #86649: `fs::read_dir()` fails with error 0 on Linux if directory is on NTFS and contains file with filename > 255 bytes
1. Create a filename on an NTFS partition with a name > 255 bytes, e.g. `一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十`.
2. Run this code with the path to the directory containing the file with the very long filename:

```rust
use std::env;
use std::fs::{self, ReadDir};

fn main() {
    test().unwrap();
}

fn test() -> std::io::Result<ReadDir> {
    let args: Vec<String> = env::args().collect();
    for result in fs::read_dir(&args[1])? {
        result.map(|entry| entry.path()).unwrap();
    }
    todo!()
}
```

I expected to see this happen: the code works until it panics on `todo!()`

Instead, this happened: ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 0, kind: Other, message: "Success" }', test.rs:11:42```. Note that in exa, [it fails with `Bad address (os error 14)`](https://github.com/ogham/exa/issues/893).

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by tavianator**
See #40021 for more details.  Fixes #86649.  Fixes #34668.

### CODE REVIEW

**Comment by tavianator** [comment]
Hang on, there's a bug in metadata()

**Comment by tavianator** [comment]
Okay, should be fixed.

r? @joshtriplett

**Comment by ehuss** [comment]
@bors r-

Failed in rollup: https://github.com/rust-lang/rust/pull/92878#issuecomment-1012711761

**Comment by tavianator** [comment]
I switched Android over too, and split up the commits a bit.  I would test the Android build locally but I have no idea how.  Is there documentation for building Rust for Android or should I just try to follow the CI script?

r? @joshtriplett

**Comment by ehuss** [comment]
To test android, it needs the NDK. There is a script [here](https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/android-ndk.sh) for getting it, but I would just use the docker image.  That can be done with `src/ci/docker/run.sh dist-android`.  There is documentation at https://rustc-dev-guide.rust-lang.org/tests/intro.html#testing-with-docker-images for testing with docker.

**Comment by tavianator** [comment]
Thanks!  I ran the library tests in that Docker image and they passed.

**Comment by tavianator** [comment]
Rebased!  Linux and Android tests still pass

**Pull request merged**
