### PR TITLE
Fix rustc_driver swallowing errors when compilation is stopped

### PR DESCRIPTION
**Pull request by gnzlbg**
r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors r+

for future reference, this is relevant for clippy and semverver, because their exit code currently is 0 even if errors occurred

**Comment by oli-obk** [comment]
@bors r-

a comment in the code explaining this would be great.

r=me with that

**Comment by gnzlbg** [comment]
@oli-obk is it easily possible to add a test for this ? I tried for a bit but failed.

**Comment by gnzlbg** [comment]
@oli-obk comment added, this is such a tiny change that i've rebased and force-pushed. Hope that's ok.

**Comment by oli-obk** [comment]
> is it easily possible to add a test for this ? I tried for a bit but failed.

I don't think so. Well, not here. We can add it to clippy and that will make the toolstate fail

**Comment by gnzlbg** [comment]
^^^ @oli-obk FYI this did fix rust-semverver upstream

**Pull request merged**
