### PR TITLE
rustdoc: add [src] links to methods on a trait's page

### LINKED ISSUE #45150: rustdoc: add [src] links to provided methods on a trait's page
For example, here's a method on Iterator right now:

image

Since this is a provided method, there's a worthwhile implementation to link to, so it would be nice to be able to link to it's implementation, by adding a `[src]` link to the method header here.

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Closes #45150

image

### Caveats

- The way I've implemented it, links are also provided for required methods, that just link to the signature in the code. I'm not sure if this is the desired behaviour.

image

- I'm not sure if the css changes are correct. I inspected them visualy on firefox on desktop, and they seem to be fine.
- I can't tell how `src/librustdoc/html/render/mod.rs` is structured, so I probably

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
This looks great! @GuillaumeGomez do you want to review the CSS changes? Otherwise r=me :)

**Comment by jyn514** [comment]
A small nit: if you can squash the last three commits together that would be nice, there are instructions at https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing. No big deal if it's a hassle, though.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks!

@bors: r=jyn514,GuillaumeGomez

**Comment by m-ou-se** [comment]
This feature is saving me so much time while looking up implementations of things in `std`. I keep switching to the nightly docs specifically so I can use this. :)

Thanks a lot!

**Pull request merged**
