### PR TITLE
rustdoc: don't prefer dynamic linking in doc tests

### PR DESCRIPTION
**Pull request by pnkfelix**
This is an attempt to address the regression in #54478

This may be a case where the cure is worse than the disease, at least in the short term...

cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ok I finally got around to my local machine, and it looks like this passes `./x.py test` with the commit I've added to update some UI test output. Other than that let's see what crater has to say...

**Comment by pnkfelix** [comment]
@craterbot run name=rustdoc-test-static-cling  start=master#0e07c4281c343e9e15a0a8fca79538ad1a8eb513 end=try#40d4795669493f1965de7c44029c69552134fe1f mode=build-and-test

**Comment by alexcrichton** [comment]
Well the good news is that this fixed 10 crates. The bad news is that it regressed 23000 crates.

@pietroalbini [random selections of error logs](https://crater-reports.s3.amazonaws.com/rustdoc-test-static-cling/try%2340d4795669493f1965de7c44029c69552134fe1f/reg/google-admin1_reports-1.0.7%2B20171204/log.txt) look sort of confusing, did this run have errors in the middle perhaps?

**Comment by Mark-Simulacrum** [comment]
Yes, I believe the conclusion was that the run itself errored (rather than this PR causing most of the failures).

@craterbot run name=rustdoc-test-static-cling-1 start=master#0e07c4281c343e9e15a0a8fca79538ad1a8eb513 end=try#40d4795669493f1965de7c44029c69552134fe1f mode=build-and-test

**Comment by Mark-Simulacrum** [comment]
https://crater-reports.s3.amazonaws.com/rustdoc-test-static-cling-1/try%2340d4795669493f1965de7c44029c69552134fe1f/reg/docmatic-0.1.2/log.txt
A few of these: https://crater-reports.s3.amazonaws.com/rustdoc-test-static-cling-1/try%2340d4795669493f1965de7c44029c69552134fe1f/reg/restson-0.4.0/log.txt
https://crater-reports.s3.amazonaws.com/rustdoc-test-static-cling-1/try%2340d4795669493f1965de7c44029c69552134fe1f/reg/structopt-flags-0.1.0/log.txt


Haven't tried to reproduce locally but those are the failures that look possibly non-spurious. The wrong crate/mismatched types is the only one I'm super concerned with -- but since it's one case out of ~80k crates tested it seems unlikely that it's actually a problem. As such, presuming we're not expecting a serious performance regression here, I think this is ready to go

**Comment by QuietMisdreavus** [comment]
Based on @alexcrichton's reasoning in https://github.com/rust-lang/rust/issues/54478#issuecomment-428262608, this gets a +1 from me. It would be nice to know why it was set like that in the first place, but since it was set like that for as long as rustdoc has had doctests, i doubt we'll know for sure.

**Pull request merged**
