### PR TITLE
Split the rustc target libraries into separate rustc-dev component

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This is re-applies a squashed version of #64823 as well as including #65337 to fix bugs noted after merging the first PR. 

The second PR is confirmed as fixing windows-gnu, and presumably also fixes other platforms, such as musl (i.e. #65335 should be fixed); `RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup toolchain install nightly-2019-10-16` can be installed to confirm that this is indeed the case.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I would appreciate confirmation from @jethrogb as to musl being fixed, but I personally think we can likely approve and land this.

**Comment by jethrogb** [comment]
At this point, I can only confirm that [this try build](https://github.com/rust-lang/rust/pull/65337#issuecomment-541358847) had the appropriate fix for SGX.

I'd be happy to look at other artifacts once they are built.

**Comment by jethrogb** [comment]
Oh I see the instructions for using dev-static now. I won't be able to try that until tomorrow.

**Comment by jethrogb** [comment]
I ran the following commands, which completed succesfully:
```
RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup toolchain install nightly-2019-10-16
RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup target add --toolchain nightly-2019-10-16 x86_64-fortanix-unknown-sgx
RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup target add --toolchain nightly-2019-10-16 x86_64-unknown-linux-musl
cargo new hw
cd hw
cargo +nightly-2019-10-16 build --target x86_64-unknown-linux-musl
cargo +nightly-2019-10-16 build --target x86_64-fortanix-unknown-sgx
```

**Comment by Mark-Simulacrum** [comment]
Okay, sounds like we're ready to go ahead.

@pietroalbini, this should be ready for approval (basically confirming that we've tested sufficiently, I think; code changes have already been pre-approved by me, they're not mine).

**Comment by pietroalbini** [comment]
Should we make a post on users/reddit asking people to test non-x86 targets?

**Comment by Mark-Simulacrum** [comment]
We, uh, can. I feel like that's going too far though? I guess I'm not opposed.

**Comment by pietroalbini** [comment]
Well, we already had to revert the change one time due to breakages.

As far as I'm aware all the bugs reported in #65335 were fixed (cc @mati865 for windows-gnu?), but I'd err on the side of caution landing this again.

**Comment by mati865** [comment]
> As far as I'm aware all the bugs reported in #65335 were fixed (cc @mati865 for windows-gnu?)

I tested x86_64 `windows-gnu` and `linux-musl` and they are fixed.
There was report of weird (MSVC bug)[https://github.com/rust-lang/rust/issues/65335#issuecomment-541338745] (cc @RalfJung) but I cannot test it.

**Comment by Mark-Simulacrum** [comment]
https://users.rust-lang.org/t/help-test-rustc-dev-component-splitting/33710

**Comment by RalfJung** [comment]
I ran [Miri CI with this experimental toolchain](https://ci.appveyor.com/project/rust-lang-libs/miri/builds/28188009) and everything is green. Looks like whatever issue there was is fixed now.

**Comment by Mark-Simulacrum** [comment]
I've set the arbitrary landing deadline as Monday -- if by then there are no complaints on the internals thread I will approve this.

**Comment by pietroalbini** [comment]
Ok, it's now Monday, let's land this!

@bors r+

**Comment by Mark-Simulacrum** [comment]
It looks like most builders finished on time, not sure why one timed out, retrying...

@bors retry

**Comment by pietroalbini** [comment]
Huh, `rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com` failed to resolve. Oh well.

@bors retry

**Comment by RalfJung** [comment]
> The remote name could not be resolved: 'rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com' 

@bors retry

**Comment by Mark-Simulacrum** [comment]
@bors retry

windows dist build timed out again...

**Comment by jethrogb** [comment]
Yes finally.

**Comment by RalfJung** [comment]
Hm, now I am again seeing weird [failures for Miri on Windows](https://ci.appveyor.com/project/rust-lang-libs/miri/builds/28348251/job/usxllmdal3ag6m1h):
```
Bad status code exit code: 0xc0000135 when getting sysroot info via "C:\\Users\\appveyor\\.cargo\\bin\\miri" "--print" "sysroot".
stdout:
stderr:
```
Any idea why the Miri binary might exit immediately without printing anything?

**Comment by RalfJung** [comment]
Looks like that exit code is `STATUS_DLL_NOT_FOUND`, so my theory remains that somehow the search paths are wrong or so?

**Comment by Mark-Simulacrum** [comment]
That would be odd since this PR should have produced an identical looking sysroot to before... 

Can you check that `rustc --print sysroot` works? If so then it's probably a miri bug (e.g., you need to build it in a slightly different way, or miri is not linking the same as rustc)

**Comment by RalfJung** [comment]
The oddest thing is that it [worked when I tired it with the experimental toolchain](https://ci.appveyor.com/project/rust-lang-libs/miri/builds/28188009).

Ah wait, I have an idea...

**Comment by RalfJung** [comment]
Yes that was it; the failure had nothing to do with this PR and everything with https://github.com/rust-lang/rustup.rs/issues/1575.

**Pull request merged**
