### PR TITLE
add LinkedList::{retain,retain_mut}

### PR DESCRIPTION
**Pull request by TennyZhuang**
Implement #114135 

The API is consistent with other collections.

### CODE REVIEW

**Comment by thomcc** [comment]
Can you file an ACP for this? https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29

**Comment by TennyZhuang** [comment]
> Can you file an ACP for this? https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29

Thanks! I'll add it tomorrow

**Comment by TennyZhuang** [comment]
https://github.com/rust-lang/libs-team/issues/250

**Comment by thomcc** [comment]
This has ACP+, and the implementation looks fine.

@bors r+

**Comment by jdahlstrom** [comment]
Wasn't this supposed to only have the single `retain` method, as per the ACP?

**Pull request merged**
