### PR TITLE
Remove `GenKillAnalysis`

### PR DESCRIPTION
**Pull request by nnethercote**
There are two kinds of dataflow analysis in the compiler: `Analysis`, which is the basic kind, and `GenKillAnalysis`, which is a more specialized kind for gen/kill analyses that is intended as an optimization. However, it turns out that `GenKillAnalysis` is actually a  pessimization! It's faster (and much simpler) to do all the gen/kill analyses via `Analysis`. This lets us remove `GenKillAnalysis`, and `GenKillSet`, and a few other things, and also merge `AnalysisDomain` into `Analysis`. The PR removes 500 lines of code and improves performance.

r? @tmiasko

### CODE REVIEW

**Comment by nnethercote** [comment]
I was hoping for neutral performance effects, but the perf run is much better than that: icount results are great, cycles results are good, bootstrap drops by 3.4s, and artifact size drops by 228 KiB.

**Comment by nnethercote** [comment]
cc @cjgillot

**Comment by cjgillot** [comment]
IIRC, the `GenKill` version has a different asymptotic complexity: it avoids looping through all statements when looping for fixed-point. Could this change introduce a degenerate worst case? Or is it too unlikely to warrant the maintenance cost?

**Comment by nnethercote** [comment]
> IIRC, the GenKill version has a different asymptotic complexity: it avoids looping through all statements when looping for fixed-point. Could this change introduce a degenerate worst case? Or is it too unlikely to warrant the maintenance cost?

I'm no expert on the analyses, but I do have pretty high confidence in the coverage of our test suite, such that any degenerate cases are likely to be very rare. Also, it's interesting that the largest wins were in the secondary benchmarks such as `await-call-tree` and `deeply-nested-multi`, two artificial stress tests that caused performance problems in the past.

**Comment by cjgillot** [comment]
I don't have the same confidence in the test suite, but I don't have any argument besides "may". 
Let's go, and see if we get a perf report. 
@bors r+

**Pull request merged**
