### PR TITLE
[experiment] Enable link-time thread local support on MinGW

### PR DESCRIPTION
**Pull request by joboet**
I read somewhere that GCC supports link-time TLS on Windows. That would simplify the TLS handling code in `std` by a bit and would also hopefully improve performance.

Uses the CI runners for testing as I don't have a Windows machine.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
cc @mati865, see also #100917

Note that i686 windows-msvc also does not have thread-local enabled because the last attempt failed (see #95429). This might or might not be related to [TLS issues](https://github.com/rust-lang/rust/issues/44391) with the Rust compiler.

**Comment by mati865** [comment]
<please no meme from The Office here>

I've tried togging it in the past but EmuTLS used by GCC is just too messed up and causes problems for all languages that use TLS.
I don't think it's possible to workaround this problem in Rust but FWIW `windows-gnullvm` targets that I added not so long ago are working perfectly fine with it (although they are not tested on CI): https://github.com/rust-lang/rust/pull/94872/files#diff-5b82e76d5e73e79c281214a612797bd5ffadd853cc83f1c4e37eef19a1bba35dR48 This is because LLVM uses native Windows TLS by default which is not implemented in GCC.

**Comment by bjorn3** [comment]
Does MinGW use COFF TLS the same way as MSVC? If not, this will break cg_clif for MinGW.

**Comment by mati865** [comment]
MinGW is only the CRT (a bit like glibc or musl on Linux).
TLS is provided by the compiler, in case of GCC it's emuTLS and for Clang it's native Windows TLS (so COFF TLS I suppose?).

**Comment by bjorn3** [comment]
Is there any documentation on emuTLS for implementing it in Cranelift?

**Comment by mati865** [comment]
I have no idea, I'm not familiar with GCC code.

**Comment by Mark-Simulacrum** [comment]
r? compiler

I don't think I have enough context on this platform right now to properly review this.

**Comment by fee1-dead** [comment]
r? compiler

**Comment by eholk** [comment]
Since this is still a draft I'm going to mark it as waiting on the author.

@rustbot author

**Comment by Dylan-DPC** [comment]
closing this as it was an experiment

**Pull request closed without merging**
