### PR TITLE
update stdsimd and remove now-unused MaybeUninit::into_inner

### PR DESCRIPTION
**Pull request by RalfJung**
That's a huge diff for stdsimd... Cc @gnzlbg @alexcrichton

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm, this fails to build:
```
error: couldn't read src/libcore/core_arch_docs.md: No such file or directory (os error 2)                                                                                                                       
 --> src/libcore/../stdsimd/crates/core_arch/src/mod.rs:8:17
  |
8 | #[doc(include = "core_arch_docs.md")]
  |                 ^^^^^^^^^^^^^^^^^^^ couldn't read file
  |
  = help: external doc paths are relative to the crate root
```

**Comment by gnzlbg** [comment]
cc @QuietMisdreavus it appears that `#[doc(include = "core_arch_docs.md")]` does not respect `#[path]`. 

@RalfJung can you test if creating a symlink from `libcore/core_arch_docs.md` to `stdsimd/crates/core_arch/src/core_arch_docs.md` solves this issue? 

Also, libstd probably needs to be compiled with `--cfg feature="std_detect_file_io" --cfg feature="std_detect_dlsym_getauxval"`, so those two should probably be added here: https://github.com/rust-lang/rust/blob/master/src/libstd/Cargo.toml#L50

**Comment by RalfJung** [comment]
> can you test if creating a symlink from `libcore/core_arch_docs.md` to `stdsimd/crates/core_arch/src/core_arch_docs.md` solves this issue?

That seems to help. But don't ask me what it'll do on Windows...

> libstd probably needs to be compiled with `--cfg feature="std_detect_file_io" --cfg feature="std_detect_dlsym_getauxval"`, so those two should probably be added

Like this? However, they should probably be documented. If you tell me which text to put there I'll do it :P

**Comment by gnzlbg** [comment]
> Like this? However, they should probably be documented. If you tell me which text to put there I'll do it. :P

Yes that's exactly what I meant! 

I think a comment stating:

```toml
# Enable std_detect default features:
# https://github.com/rust-lang-nursery/stdsimd/blob/master/crates/std_detect/Cargo.toml
```

would be enough. 

> That seems to help. But don't ask me what it'll do on Windows...

I don't think that will work... Maybe this PR to stdsimd fixes this here: https://github.com/rust-lang-nursery/stdsimd/pull/680

**Comment by RalfJung** [comment]
Well let us see.

**Comment by RalfJung** [comment]
Seems like travis is happy?

I resolved the conflicts.

**Review by gnzlbg — APPROVED** [review]
r? @gnzlbg LGTM. 

@bors: r+

**Comment by RalfJung** [comment]
Seems like bors didn't see this, maybe because of the ":"?

@bors r=gnzlbg

**Comment by Centril** [comment]
In-between-rollup-filler, @bors p=1

**Comment by RalfJung** [comment]
Seems like I somehow lost the part where `into_inner` gets removed.^^ But that's okay, that part is easy to submit later (and can be rollup'd).

**Comment by RalfJung** [comment]
Log ends in
```
C:\projects\rust\build\tmp\dist\rust.wxs(144) : warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product. (1.34.65535 1.34.0.0)
[TIMING] Extended { stage: 2, host: "i686-pc-windows-gnu", target: "i686-pc-windows-gnu" } -- 1101.683
Build completed successfully in 3:19:57
Command exited with code 259
set PATH=%PATH%;"C:\Program Files (x86)\Windows Kits\10\Debuggers\X64"
if exist %LOCALAPPDATA%\CrashDumps for %%f in (%LOCALAPPDATA%\CrashDumps\*) do cdb -c "k;q" -G -z "%%f"
```
Is that just a timeout?

**Comment by hellow554** [comment]
Alex closed my PR https://github.com/rust-lang/rust/pull/58460 in favor of this, but this means, that you please need to update stdsimd to at least [ee8637b](https://github.com/rust-lang-nursery/stdsimd/tree/ee8637b6f675517c742598ff679f666801dba090) to fix https://github.com/rust-lang-nursery/stdsimd/issues/681

**Comment by RalfJung** [comment]
@hellow554 I updated this to latest stdsimd master. Is that enough?

@bors r=gnzlbg

**Comment by RalfJung** [comment]
Oh no, updating stdsimd broke something again. Let's not waste bors' time more...

@bors r-

@gnzlbg any idea what is going on?
```
[00:34:56] error[E0658]: use of unstable library feature 'stdsimd' (see issue #27731)
[00:34:56]   --> /cargo/registry/src/github.com-1ecc6299db9ec823/crc32fast-1.1.2/src/specialized/pclmulqdq.rs:13:12
[00:34:56]    |
[00:34:56] 13 |         if is_x86_feature_detected!("pclmulqdq")
[00:34:56]    |
[00:34:56]    |
[00:34:56]    = help: add #![feature(stdsimd)] to the crate attributes to enable
```

**Comment by RalfJung** [comment]
Actually, ideally you'd just take over this PR. All I want to do is remove `MaybeUninit::into_inner`, but it clearly take a stdsimd expert to to a stdsimd update.

**Comment by hellow554** [comment]
@RalfJung yes, thanks. Sorry that it causes additional headache. 😟

**Comment by gnzlbg** [comment]
@RalfJung the problem is that a change in rustc to allow_internal_unstable required a change to stdsimd, which was applied, and appeared to work there, but the update of rust to that version hasnt been done yet, and it apparently fails: I've sent https://github.com/rust-lang-nursery/stdsimd/pull/687 . This might fix the error, but I'm not sure, am travelling, and can't really test it properly.

**Comment by RalfJung** [comment]
All right, I updated the submodule to include that commit.

**Comment by RalfJung** [comment]
Uh, what?
```
$ MESSAGE_FILE=$(mktemp -t msg.XXXXXX); . src/ci/docker/x86_64-gnu-tools/repo.sh; commit_toolstate_change "$MESSAGE_FILE" "$TRAVIS_BUILD_DIR/src/tools/publish_toolstate.py" "$(git rev-parse HEAD)" "$(git log --format=%s -n1 HEAD)" "$MESSAGE_FILE" "$TOOLSTATE_REPO_ACCESS_TOKEN";
Cloning into 'rust-toolstate'...
I/O error: HTTP Error 422: Unprocessable Entity
📣 Toolstate changed by <unknown PR>!
Tested on commit rust-lang/rust@d215d9591f27d0663445e65615090621153c31df.
Direct link to PR: <<unknown>>
💔 miri on windows: test-fail → build-fail (cc @oli-obk @RalfJung @eddyb, @rust-lang/infra).
💔 miri on linux: test-fail → build-fail (cc @oli-obk @RalfJung @eddyb, @rust-lang/infra).
Traceback (most recent call last):
  File "/home/travis/build/rust-lang/rust/src/tools/publish_toolstate.py", line 219, in <module>
    'Content-Type': 'application/json',
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
```
@rust-lang/infra @oli-obk

**Comment by oli-obk** [comment]
fix is in https://github.com/rust-lang/rust/pull/58541#issuecomment-464472171

**Pull request merged**
