### PR TITLE
Handle Ctrl+C in the build script

### PR DESCRIPTION
**Pull request by achanda**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! We want to be sure to kill the subprocess as well, though, so can you confirm that the call to the build system is killed?

**Comment by achanda** [comment]
@alexcrichton I just checked, all sub processes are killed on a Ctrl+C. Feel free to cross check though!

**Comment by achanda** [comment]
Not sure why the test failed. I don't see any indications in https://travis-ci.org/rust-lang/rust/jobs/183028434 . Should we just retry?

**Comment by petrochenkov** [comment]
@achanda 
Travis tests status isn't taken into account when merging, it's only informative (all Travis testing is also broken at the moment).
You can see the actual status of this PR in https://buildbot.rust-lang.org/homu/queue/rust - it it's still in the queue and hasn't failed, so there's no need to retry.

**Comment by achanda** [comment]
I see, thanks!

**Comment by petrochenkov** [comment]
@achanda 
What was the goal of this patch?
`KeyboardInterrupt` is caught only to exit successfully (with exit code `0`), this doesn't seem right.

**Pull request merged**
