### PR TITLE
[beta] Cargo does not remove [root] from lockfile with --frozen

### PR DESCRIPTION
**Pull request by matklad**
Okey, this is supposed to be a backport of https://github.com/rust-lang/cargo/pull/4687, but looks like beta cargo at rust-lang and beta cargo at cargo are different at the moment, hence the huge diff (one commit in the diffrence rewrote every single test file in Cargo)

rust-lang: https://github.com/rust-lang/cargo/commits/463e850146e9454b8b953ff73772a35b286b58e7
cargo: https://github.com/rust-lang/cargo/commits/rust-1.22.0

r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors p=1

cc @aidanhs Once this lands, and we get a new beta out, crater should be fixed, I think.

**Comment by matklad** [comment]
@Mark-Simulacrum has this broken crater somehow? I wonder why we haven't caught this earlier then, the change about `[root]` was merged a while back...

**Comment by Mark-Simulacrum** [comment]
@matklad Well, the issue with crater is that we generated lockfiles on stable and then tried to use them with beta cargo, which failed, and means that we can't currently (before next beta) run crater on stable vs. beta.

**Pull request merged**
