### PR TITLE
Update the clippy submodule

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by oli-obk** [comment]
race condition with bors

@bors r-

**Comment by oli-obk** [comment]
So we're back at `duplicate artfacts found when compiling a tool`. But all the features match up this time.

Also only happens on windows

**Comment by kennytm** [comment]
No the features of `winapi` differs. These features are only enabled in cargo:

```
jobapi
jobapi2
lmcons
minschannel
minwinbase
ntsecapi
ntstatus
profileapi
psapi
schannel
securitybaseapi
synchapi
sysinfoapi
timezoneapi
winbase
wincon
wincrypt
```

**Comment by oli-obk** [comment]
@bors r=kennytm

copied imports from cargo's `Cargo.toml` and left a comment to keep it in sync

**Comment by oli-obk** [comment]
Seems unrelated to the clippy update:

```
[01:08:33] 1 command(s) did not execute successfully:
[01:08:33] 
[01:08:33]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/nomicon/src/vec-final.md" "--test-args" ""
[01:08:33] 
[01:08:33] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --no-fail-fast src/doc/book src/doc/nomicon src/doc/reference src/doc/rust-by-example src/tools/rls src/tools/rustfmt src/tools/miri src/tools/clippy
```

Maybe the recent nomicon breakage didn't get registered until now?

**Comment by kennytm** [comment]
The nomicon breakage is legit but should not fail this PR. 🤔

**Comment by oli-obk** [comment]
didn't update the submodule branch correctly. Idk why git didn't tell me I pushed to a nonexistant repository.

@bors r=kennytm p=1

**Comment by oli-obk** [comment]
```
`clippy-driver` enabled features ["consoleapi", "dbghelp", "errhandlingapi", "fileapi", "handleapi", "ioapiset", "jobapi", "jobapi2", "minwindef", "namedpipeapi", "ntdef", "ntstatus", "processenv", "processthreadsapi", "psapi", "std", "synchapi", "winbase", "wincon", "winerror", "winnt", "winsock2", "ws2def", "ws2ipdef", "ws2tcpip"] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi-40d1e0056a1952e2.rlib"
        `cargo` enabled features ["consoleapi", "dbghelp", "errhandlingapi", "fileapi", "handleapi", "ioapiset", "jobapi", "jobapi2", "lmcons", "minschannel", "minwinbase", "minwindef", "namedpipeapi", "ntdef", "ntsecapi", "ntstatus", "processenv", "processthreadsapi", "profileapi", "psapi", "schannel", "securitybaseapi", "std", "synchapi", "sysinfoapi", "timezoneapi", "winbase", "wincon", "wincrypt", "winerror", "winnt", "winsock2", "ws2def", "ws2ipdef", "ws2tcpip"] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi-9ad16dd87cb456ff.rlib"
  backtrace 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)
    `clippy-driver` enabled features ["backtrace-sys", "coresymbolication", "dbghelp", "default", "dladdr", "libbacktrace", "libunwind", "winapi"] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libbacktrace-45cac02f5b922b74.rlib"
            `cargo` enabled features ["backtrace-sys", "coresymbolication", "dbghelp", "default", "dladdr", "libbacktrace", "libunwind", "winapi"] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libbacktrace-077f9cc432fa29ca.rlib"
  error-chain 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)
    `clippy-driver` enabled features ["backtrace", "default", "example_generated"] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\liberror_chain-544a13b19deb0c2e.rlib"
              `rls` enabled features ["backtrace", "default", "example_generated"] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\liberror_chain-c2e71ab2abf62ca9.rlib"
  cargo_metadata 0.5.4 (registry+https://github.com/rust-lang/crates.io-index)
    `clippy-driver` enabled features [] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libcargo_metadata-05e46730787288a8.rlib"
              `rls` enabled features [] at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libcargo_metadata-b84ca0904d7314c8.rlib"
```


still a diff even though I copied the features 1:1 from cargo :/

**Comment by oli-obk** [comment]
@bors r=kennytm p=1

manually transcribed missing features

**Pull request merged**
