### PR TITLE
fix copy-paste typo in docs for wrapping_shr

### PR DESCRIPTION
**Pull request by zachreizner**

### CODE REVIEW

**Comment by apasel422** [comment]
@bors: r+ rollup

Thanks!

**Comment by alexcrichton** [comment]
wut

**Comment by apasel422** [comment]
@alexcrichton All the failures seemed spurious.

**Comment by alexcrichton** [comment]
Certainly! That most recent one is super weird (never seen it before)

```
/usr/bin/find: paths must precede expression: ^
Usage: /usr/bin/find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
```

**Comment by apasel422** [comment]
@alexcrichton Any idea why @bors didn't pick up the retry?

**Pull request merged**
