### PR TITLE
Test for appropriate span on second custom derive

### LINKED ISSUE #36935: Second panicking custom derive has bad span
Inlined from https://github.com/rust-lang/rust/issues/35900#issuecomment-246127402

---

Another issue. If a struct has two different custom derives on it and the second one panics, the error span will point to the first one, not the one which panicked.

Reproduction Script

### PR DESCRIPTION
**Pull request by estebank**
Adds test for and closes #36935.

### CODE REVIEW

**Comment by estebank** [comment]
Has there been a change in how `proc_macro` is used in master?

```
error[E0463]: can't find crate for `proc_macro`
  --> C:\projects\rust\src/test\ui\custom-derive\auxiliary\plugin.rs:16:1
   |
16 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
Currently the ui test suite [is not configured](https://github.com/rust-lang/rust/blob/05f4a75ebaccdf3646fbea4b560a3a0dfc1be9e2/src/bootstrap/step.rs#L319) to have librustc available when it runs, so proc-macro tests in the ui test suite aren't guaranteed to work. Rustbuild is nondeterministic in how it lays out steps, so that may explain why it worked locally.

If we really want to add this test as a ui test then the suite needs to be [moved below](https://github.com/rust-lang/rust/blob/05f4a75ebaccdf3646fbea4b560a3a0dfc1be9e2/src/bootstrap/step.rs#L366-L367) like the other "fulldeps" suites.

**Comment by estebank** [comment]
@alexcrichton I'm trying to figure out why I needed to [remove the ui assertion from the `test_with_a_target` test](https://github.com/rust-lang/rust/pull/38607/commits/78e9093abbdedf2d29bf0b42c0cce2cfc2977894#diff-6af36664c6749c96ecb041458ba4e77fL1400) for the test suite to run successfully, and what are the consequences from me doing so.

**Comment by alexcrichton** [comment]
@estebank no worries that's ok. You can actually change the assertion to testing that it's *not* present instead of testing that it's present.

That basically means that we only run the tests for hosts, not targets (which is correct)

**Comment by alexcrichton** [comment]
r=me with that change

**Comment by estebank** [comment]
@alexcrichton, done. I also removed two duplicated asserts while I was at it.

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Pull request merged**
