### PR TITLE
Warn unused type parameters

### LINKED ISSUE #25871: Should have lint to disallow unused type parameters
The following compiles and runs without warning:

```rust
fn foo<T: Sync> () { }

fn main() {
    foo::<i32>()
}
```

I think that this should at least warn, just like unused imports or unused variables; it would almost always be a result from a mistake in refactoring.

### PR DESCRIPTION
**Pull request by sanxiyn**
Rebase of #26684. Fix #25871.

Following @huonw's suggestion, warning is disabled for intrinsics and lang items. An example of unused but not incorrect type parameters is `core::intrinsics::size_of` for intrinsics and `core::marker::PhantomData` for lang items.

Following @nikomatsakis's suggestion, warning can be silenced by prefixing the underscore as in `_T`. As pointed out, `fn _is_sync_send<_T: Sync+Send>() {}` is analogous to `fn drop<T>(_x: T) {}` for unused variables.

### CODE REVIEW

**Comment by frewsxcv** [comment]
```
error: unused type parameter
   --> /checkout/src/libserialize/serialize.rs:677:18
    |
677 |     fn not_found<S, T: ?Sized>(trait_name: &'static str,
    |                  ^
    |
note: lint level defined here
   --> /checkout/src/libserialize/lib.rs:28:31
    |
28  | #![cfg_attr(not(stage0), deny(warnings))]
    |                               ^^^^^^^^

error: unused type parameter
   --> /checkout/src/libserialize/serialize.rs:677:21
    |
677 |     fn not_found<S, T: ?Sized>(trait_name: &'static str,
    |                     ^

error: aborting due to 2 previous errors
```

**Comment by sanxiyn** [comment]
I guess that's what I get for testing with `make check-stage1-cfail`. Fixed all tests.

**Comment by nikomatsakis** [comment]
I'm not sure what the policy is to decide on a new lint, but I do think that this is a useful one -- or at minimum, the error messages you get when you have unused type parameters are terrible. I'm not sure how much this helps though since (as a lint) it gets reported later. I might rather just improve the "unconstrained type parameter" message. @jonathandturner was doing some work on that, I think?

**Comment by jonathandturner** [comment]
Nothing from me, so please feel free to take it and run with it.

**Comment by sanxiyn** [comment]
I would like to get some (any) opinion on this, unlike my last attempt in 2015 which received no comments for a month and closed for inactivity.

**Comment by petrochenkov** [comment]
@sanxiyn 
>I would like to get some (any) opinion on this, unlike my last attempt in 2015 which received no comments for a month and closed for inactivity.

Everyone seems to be on vacation at the moment.
It would be interesting to test this with crater (probably in forbid-by-default form) to see the statistics of breakage. The potential for breakage seems to be relatively high, maybe it will end up as allow-by-default in the worst case.

**Comment by nikomatsakis** [comment]
The code seems ok. We don't really have a clear policy for how to decide whether to add a new lint, do we? I'm not even 100% sure what team is responsible. I don't generally see the compiler team as making "user-facing" decisions of this kind. It could be a @rust-lang/lang decision or perhaps @rust-lang/tools -- have we settled this question in the past?

cc @rust-lang/core

**Comment by aturon** [comment]
@nikomatsakis I believe that new lints are required to go through an RFC and be approved by the lang team.

**Comment by steveklabnik** [comment]
>  I believe that new lints are required to go through an RFC and be approved by the lang team.

Yes, this is true, [as I mentioned on 25871](https://github.com/rust-lang/rust/issues/25871#issuecomment-183043998). @sanxiyn as this is a new lint, please open an RFC. Thanks!

**Pull request closed without merging**
