### PR TITLE
Add powerpc-unknown-linux-musl target

### LINKED ISSUE #42520: Feature request: aarch64-unknown-linux-musl and powerpc-unknown-linux-musl binaries
Other Linux targets like ARM/x86/MIPS have -musl variants in addition to -gnu variants. It'd be nice to have this for PPC and AARCH64 as well.

### PR DESCRIPTION
**Pull request by ArcaneNibble**
This is 100% untested, but this is essentially a copy-paste of https://github.com/rust-lang/rust/pull/44779 now that there is actually an up-to-date non-bitrotten example of how to add a new target. Should close #42520.

Again, this is super untested because I don't even know how to build rust.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Do you want to test this out before landing perhaps? 

I think you can uncomment the `if: branch = auto` in the Travis config for the `cross` builder and that should run it as part of this PR. We'll back out those changes before landing though.

Also, would you be willing to help fix liblibc after this patch lands? Once this gets into nightlies we can start adding automation to the libc repo to assert that the bindings are all correct there.

**Comment by rqou** [comment]
Hmm, good call. It turns out that this is indeed broken thanks to PPC's silly double-double floating point. AFAICT Rust cannot use f128/f80/long-double at all, so I believe passing `-mlong-double-64` to the musl build should be safe?

**Comment by rqou** [comment]
Er, apparently gcc also doesn't define `__ppc__`, but clang apparently does?

**Comment by rqou** [comment]
Uh oh. It looks like libunwind's assembly isn't compatible with binutils (presumably only with llvm's assembler). How should we proceed from here?

**Comment by alexcrichton** [comment]
Unsure! I don't know much about powerpc

**Comment by shepmaster** [comment]
Heya @rqou — have you had any time to make progress on this PR? Do you have any avenues on where to find information / help?

**Comment by rqou** [comment]
Since you asked, I tried to get libunwind to compile with clang and its integrated assembler, but that still does not work. I don't know how this was ever supposed to work, and I have no idea where to look next since nothing here seems to be documented. If you have any ideas, I will go and try them.

**Comment by rqou** [comment]
Of course, there's a brute force solution of replacing the assembly files with something gcc/binutils does accept, but I want to avoid doing that if possible.

**Comment by carols10cents** [comment]
triage ping for you @QuietMisdreavus! ❤️

**Comment by carols10cents** [comment]
(please disregard the comment I just made on the wrong issue)

@rqou I'm asking around to try and find help for you on this, but I'm not sure who has powerpc knowledge :-/

**Comment by hlandau** [comment]
There are people who would be interested in `powerpc64` and `powerpc64le` support for musl too. If it's just a copy/paste job which would introduce no additional issues (besides the pending ones above), maybe consider adding it to this PR?

**Comment by awilfox** [comment]
* I'm not exactly sure how you're building these thingies, but a musl gcc should never need explicit `-mlong-double-64` and if it does there is a bug in the GCC build.  `--enable-decimal-float=no` passed to GCC's `./configure` should help.
* Why is this being done in a file called `build-arm-musl.sh`?  I would think `build-ppc-musl.sh` would be better, with possibly a common "library" shell file for the common code if you desire.
* GCC and clang both seem to define `__PPC__` here; the uncapital ones typically vary between version and compiler.
* Why is libunwind being built with `-gnu-gcc` instead of `-musl-gcc`?  I don't see how this could ever work.
* The libunwind code at https://github.com/llvm-mirror/libunwind/blob/master/src/UnwindRegistersSave.S makes many assumptions about the layout of the registers.  This probably won't work on ELFv2 at all, which is what musl uses for PowerPC 64-bit big endian (and what all libcs uses for PowerPC 64-bit little endian).  That is probably okay, though, because it seems to assume registers are 4 bytes so it won't work on 64-bit PowerPC CPUs anyway.

If Rust truly requires LLVM libunwind to work, then it will require work upstream in LLVM to ever have working PowerPC musl targets.

**Comment by carols10cents** [comment]
@rqou does @awilfox's comment make sense and help at all with how to move this forward?

**Comment by rqou** [comment]
Sorry, finals week. Feel free to take this over if you really really want it done.

**Comment by shepmaster** [comment]
As @rqou has said they are working on finals, let's let this ignore triage until 2018-01-01.

**Comment by alexcrichton** [comment]
ping @rqou, just wanted to bring this back on radar!

**Comment by shepmaster** [comment]
I hope finals went well, @rqou! Since we haven't heard from you in a few weeks, we are going to go ahead and close this for now to keep things tidy. If you have time to work on this again, we hope you will reopen this PR!

**Comment by halvors** [comment]
@rqou What happened to this, seems this is still not supported, only as a Tier 3 target so practical unusable for development on powerpc. Could we please reopen this PR? #106932

**Pull request closed without merging**
