### PR TITLE
Add comparison functions that return both the min and the max value

### PR DESCRIPTION
**Pull request by timvermeulen**
This adds the following functions to `core::cmp`:

- `min_max`
- `min_max_by`
- `min_max_by_key`

Sometimes I need the minimum or maximum of two values without losing ownership of the other one. These functions make this slightly more ergonomic than doing the comparison yourself, and less error-prone if you want to match the behavior of `cmp::{min, max}` when the two values compare equal.

Suggestions for naming these are very welcome, I don't love these but I couldn't think of anything better.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm. So this seems viable -- but maybe it would be better to add sorted(), sorted_by(), etc functions to arrays which have a `self -> Self` signature? That way we get this for "free" for any constant number of arguments.

Let's also loop in someone on the libs team ... cc @dtolnay 

Usage would then be something like this:

```rust
let [min, max] = [a, b].sorted();
```

**Comment by timvermeulen** [comment]
You raise a good point, this could be generalized further in the number of arguments. I suppose a similar argument could be made for making `min` and `max` available to non-empty arrays 🙂

I don't have very compelling use cases at hand, but iirc I only ever needed this for 2 values, not for more. The appeal of adding this for me is that It's more primitive than sorting an array, and that it's slightly more general/"pure" than `cmp::{min, max}`. But I'll happily defer to someone with a stronger opinion on this!

**Comment by Mark-Simulacrum** [comment]
Let's r? @dtolnay for unstable addition approval

I personally don't care much - I guess there's probably not much use for doing this with more than two elements.

On the other hand, you can actually almost do this today, just not in one line. Adding utility methods to save a couple lines doesn't seem hugely worth it.

```rust
let mut s = [a, b];
s.sort();
let [min, max] = s;
```

**Review by dtolnay — COMMENTED** [review]
I think I would prefer not to take these. I don't think they meet the right bar on how widely they would be applicable vs how easy it is to achieve this behavior without new helpers in the standard library.

Thanks anyway!

**Comment by timvermeulen** [comment]
Thanks for taking a look! Maybe someone else has a more compelling use case later 🙂

**Pull request closed without merging**
