### PR TITLE
Add note for E0117

### LINKED ISSUE #39249: improve error message on attempt to impl on type alias
As seen previously in #9767, messaging when attempting to impl a trait involving a type alias could be improved (using current nightly):

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
   --> manifest/mod.rs:169:1
    |
169 |   impl<'a> FromIterator<io::Result<String>> for Result<Manifest<'a>> {
    |  _^ starting here...
170 | |     fn from_iter<I: IntoIterator<Item = io::Result<String>>>(iter: I) -> Result<Self> {
171 | |         let mut m = Manifest::new();
172 | |         Ok(m)
173 | |     }
174 | | }
    | |_^ ...ending here: impl doesn't use types inside crate
    |
    = note: the impl does not reference any types defined in this crate
```

From line 86 of that file:

```rust
pub type Result<Manifest> = ::std::result::Result<Manifest, ManifestError>;
```

I had expected to see `= note: define and implement a trait or new type instead` as described in #9767, but did not, so perhaps this is a regression or a subtly different case?

As someone relatively new to rust, it seems like I should be able to `impl` in this case since it is specialized such that it's only for a Result using my types, but I guess not.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #39249.

I just applied the suggestion of @durka since I don't see anything else to add.

### CODE REVIEW

**Comment by eddyb** [comment]
Could you add a test? r=me otherwise

@bors rollup

**Comment by GuillaumeGomez** [comment]
Sorry forgot to add them. Updated.

@bors r=eddyb rollup

**Comment by durka** [comment]
Travis failure looks real.

```
error: /checkout/src/test/compile-fail/coherence-impls-copy.rs:48: unexpected "note": '48:1: 48:26: the impl does not reference any types defined in this crate'

error: /checkout/src/test/compile-fail/coherence-impls-copy.rs:48: unexpected "note": '48:1: 48:26: define and implement a trait or new type instead'

error: /checkout/src/test/compile-fail/coherence-impls-copy.rs:42: expected note not found: define and implement a trait or new type instead

error: /checkout/src/test/compile-fail/coherence-impls-copy.rs:42: expected note not found: the impl does not reference any types defined in this crate
```

I guess the order of the notes matters?

**Comment by GuillaumeGomez** [comment]
Ok, fixed (very weird case). Thanks for the notification @durka!

@bors: r=eddyb rollup

**Pull request merged**
