### PR TITLE
Sync portable-simd to 2023 May 10

### PR DESCRIPTION
**Pull request by workingjubilee**
It's been a little while since this has been updated because I've been unfortunately distracted. Let's fix that.

r? @ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
GitHub seems to be having "fun" but might as well tell bors about this.

@bors r+ rollup=never

**Comment by Nilstrieb** [comment]
that looks like a legitimate failure
@bors r-

**Comment by BoxyUwU** [comment]
is the title supposed to be 2023 May 10, its not 2022 anymore somehow

**Comment by workingjubilee** [comment]
Oops.

**Comment by workingjubilee** [comment]
Oh, these are much more exciting failures. I thought I hunted all these down, but guess not.

**Comment by workingjubilee** [comment]
I wonder if the `float_to_int_unchecked` trigger is correct, as that should be truncating.

**Comment by workingjubilee** [comment]
Oh, these are the miri tests, and miri is a subtree now. So I can just fix this. Cool.

**Comment by workingjubilee** [comment]
I believe that's all of them. @bors r+

**Comment by workingjubilee** [comment]
GitHub claims they have resolved the incident.
@bors treeclosed-

**Comment by workingjubilee** [comment]
Re-opened as #111475 because *incoherent reasons*

**Pull request closed without merging**
