### PR TITLE
Use time crate in bootstrap dist instead of date

### PR DESCRIPTION
**Pull request by onur**
`bootstrap dist` command is trying to run *NIX specific `date` command to get current month and year. This command keep failing when it's called on a Windows command prompt. This patch is making it use time crate.

Closes: #47908

### CODE REVIEW

**Comment by pietroalbini** [comment]
Thanks for the PR! We’ll periodically check in on it to make sure that @nikomatsakis or someone else from the team reviews it soon.

**Comment by nikomatsakis** [comment]
r? @Mark-Simulacrum 

Seems fine to me, but I don't feel like I own this code.

**Comment by onur** [comment]
Looks like it's been added in #46514

**Comment by Mark-Simulacrum** [comment]
I won't have time in the near future to look at this and we may want a beta backport (not sure if this same problem is on beta). So.... r? @alexcrichton, if I have time I'll steal it back.

**Comment by zackmdavis** [comment]
@Mark-Simulacrum 

> we may want a beta backport (not sure if this same problem is on beta).

Yes, this should be backported to beta. (#46514—of which the author deeply regrets the oversight leading to the necessity of this PR and thanks @onur for catching it—landed 5 December, and the 1.23-stable-release/1.24-beta-train-departure date was 4 January.)

**Comment by Mark-Simulacrum** [comment]
If anyone wants to take care of the beta backport that would be most welcome!

**Pull request merged**
