### PR TITLE
[BETA] Update cargo

### PR DESCRIPTION
**Pull request by alexcrichton**
2 commits in b6c6f685b38d523580813b0031677c2298f458ea..4b105b6abfb12d6985ffe66670e8b2a85982291a
2019-09-19 21:10:09 +0000 to 2019-09-25 17:26:54 +0000
- [beta] Don't ever capture CPU state if timings are disabled (rust-lang/cargo#7430)
- [beta] Backport two changes to 1.39.0 (rust-lang/cargo#7424)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It'd be good to get a beta rollup going but we can land this in the meanwhile I guess...

**Comment by Mark-Simulacrum** [comment]
Rolled up in https://github.com/rust-lang/rust/pull/64814

**Comment by alexcrichton** [comment]
Landed in https://github.com/rust-lang/rust/pull/64814

**Pull request closed without merging**
