### PR TITLE
Fill in missing parts of Integer overflow API 

### PR DESCRIPTION
**Pull request by pnkfelix**
Fill in missing parts of Integer overflow API 

See todo list at #22020

### CODE REVIEW

**Comment by pnkfelix** [comment]
See also my notes at rust-lang/rfcs#964 ... or rather, skim them, because there is a change to `overflowing_div` that I put in here that is very much worth noting.

**Comment by pnkfelix** [comment]
This is now ready for review, and it would be nice for it to be in the next beta.

**Comment by pnkfelix** [comment]
d'oh; I should have done testing for 32-bit targets as well.  Working to address this now.

**Comment by pnkfelix** [comment]
not accepted for beta.

**Comment by brson** [comment]
(because it only adds unstable API features)

**Pull request merged**
