### PR TITLE
Change `char::eq_ignore_ascii_case` to take a `Borrow<char>` instead of `&char`

### LINKED ISSUE #57227: Rework `char::eq_ignore_ascii_case` parameter type
Right now:

    pub fn eq_ignore_ascii_case(&self, other: &char) -> bool {
        self.to_ascii_lowercase() == other.to_ascii_lowercase()
    }

This means that `'a'.eq_ignore_ascii_case('b')` doesn't compile.  Instead the user must type `'a'.eq_ignore_ascii_case(&'b')`.  I would like to allow for both *without breaking backwards compatibility*.

One option would be to change the signature to the following:

    pub fn eq_ignore_ascii_case<C: AsRef<char>>(&self, other: C) -> bool {
        self.to_ascii_lowercase() == other.as_ref().to_ascii_lowercase()
    }

This would require us to implement `AsRef<char>` for `char` and `&char` to facilitate this.

### PR DESCRIPTION
**Pull request by czipperz**
Resolves #57227

### CODE REVIEW

**Comment by czipperz** [comment]
@clarcharr `x.eq_ignore_ascii_case(&y)` is synonymous with `x.to_ascii_lowercase() == y.to_ascii_lowercase()`, which is much more verbose.

**Comment by clarcharr** [comment]
...right, I don't know how I messed that up.

I'm still not super fond of this method and wonder if there's a more ergonomic way to do this.

**Comment by shepmaster** [comment]
I'm unclear on how we deal with this backwards compatibility aspect. For example, this code will now fail:

```rust
fn before(_: &char, _: &char) -> bool {
    false
}

fn after(_: &char, _: impl std::borrow::Borrow<char>) -> bool {
    false
}

fn example(_: fn(&char, &char) -> bool) {}

fn main() {
    example(before);
    example(after);
}
```

r? @BurntSushi

**Comment by czipperz** [comment]
Nice catch @shepmaster .  I was hoping Rust would automatically deduce the types.  I think for this reason I don't think this PR should be merged.  I'm going to work on making tests for these things.  I need to get a real development environment set up.

**Comment by TimNN** [comment]
Ping from triage @czipperz: What is the status of this PR? Should it be closed for now? Or do you think you'll be able to work on fixing the issue?

**Comment by czipperz** [comment]
Yeah shoot I forget to close this @TimNN

**Pull request closed without merging**
