### PR TITLE
remove a sentence #28701

### PR DESCRIPTION
**Pull request by marti1125**
#28701

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks so much!

**Comment by steveklabnik** [comment]
(Oh, and in the future, if you say "Fixes #28701" in your commit message, rather than just the number, GitHub will automatically close the issue when the PR is merged.

**Comment by marti1125** [comment]
@steveklabnik  ok =D

**Comment by steveklabnik** [comment]
(I'm working with @marti1125 on IRC right now, and so I told them this is okay, and they'll make new PRs in the future)

**Pull request merged**
