### PR TITLE
Bump `elided_lifetimes_in_associated_constant` to deny

### PR DESCRIPTION
**Pull request by compiler-errors**
It's been 5 versions since this was last bumped. Let's bump it up again.

### CODE REVIEW

**Comment by tmandry** [comment]
@rfcbot fcp merge

**Comment by tmandry** [comment]
Actually, I don't believe we should have this lint at all and should just use `'static` everywhere. I'm about ready to file a different issue and FCP to remove the lint, but we wanted to hear from @nikomatsakis if he has any rationale for landing the lint.

@rfcbot concern let's just use 'static

**Comment by compiler-errors** [comment]
relevant:

https://github.com/rust-lang/rfcs/pull/1623#issuecomment-239559757

https://github.com/rust-lang/rust/issues/38831#issuecomment-305864245

**Comment by compiler-errors** [comment]
`'static` is a more meaningful value than what's currently happening (recall from the tracking issue #115010 that elided lifetimes in associated consts turn into *new* generic lifetimes, which is very certainly **not correct**), but i still think we should still first unstabilize this behavior before deciding on what actually to do here.

**Comment by tmandry** [comment]
@compiler-errors Does going straight to `'static` only allow strictly more code to compile than before?

> I still think we should still first unstabilize this behavior before deciding on what actually to do here.

Generally sympathetic, and from the notes we decided to do this before. At the same time, it is churn that feels unnecessary if we are going to turn around and allow all of the code again. Speaking of which: Did we ever look at how much churn there is in crater?

While the decision looks trivial to me, I see references in the tracking issue to it needing an RFC and being more subtle than I expect. Modulo the "level of churn" question, I'm comfortable letting this FCP + stabilization cycle be a forcing function for us to find a better way, rather than block an already-agreed path (undoing the stabilization) on somebody doing more work.

@rfcbot resolve let's just use 'static

**Comment by tmandry** [comment]
Looking at the references to #115010 at the bottom of the issue, this lint has created a lot of churn already. This makes me think we should leave this PR nominated and discuss again at the next lang team meeting: Do we see a feasible alternative to going down this route?

**Comment by nikomatsakis** [comment]
@tmandry I feel like I'm missing context here. I'm not sure, for example, what the current behavior is, etc. 

I'm sympathetic to defaulting to `'static` for consistency with `const` elsewhere and the [reasons that I (apparently) outlined before](https://github.com/rust-lang/rust/issues/38831#issuecomment-305864245).

I can certainly imagine reasons to *not* want `'static`, but they are unusual, e.g., `const Foo<'a> = None`.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the triage meeting today.  We were in agreement that `'static` is in fact the right default at least when there are no lifetimes in scope lexically and syntactically.  @tmandry is going to write that up as a separate issue on which we can propose FCP.

**Comment by tmandry** [comment]
@rfcbot concern wait for FCP to default to 'static

**Comment by tmandry** [comment]
The FCP in question has been proposed here: #125190

**Comment by cjgillot** [comment]
Is this unblocked now that https://github.com/rust-lang/rust/pull/125258 has merged?

**Comment by tmandry** [comment]
@rfcbot resolve wait for FCP to default to 'static

**Comment by BoxyUwU** [comment]
bors-r-plus

**Pull request merged**
