### PR TITLE
give more help in the unaligned_references lint

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/rust-lang/rust/issues/82523#issuecomment-988138440 @kaisq

### CODE REVIEW

**Comment by nagisa** [comment]
Hm, from a wording perspective, just “copy the field contents” doesn't really help that much – copy to where, how, and in what way does this help is left for the reader to figure out. I assume what the meaning is here is “make a local variable with a copy of the field's contents and then take a reference to the variable”.

Acknowledging that, in an effort to produce reasonably looking diagnostics, we want to limit the length of any specific diagnostic string, I wonder if it we could have `--explain` mechanism work for future compatibility lints like these, thus giving more space to the non-parenthesized part of the description.

---

I'd also like some input from @estebank about addressing the reader. In the past they argued that messages of the form “consider…” are  a poor style and “you can…” is probably not much different. 

With both points in mind how about something along these lines:

> = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned`

**Comment by RalfJung** [comment]
I like that wording. However, I am a bit worried people will think 'oh so raw pointers are fine' and not realize that `*p` requires proper alignment. I know this makes the text rather long, but I still think I would prefer

> = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use read_unaligned/write_unaligned (loads and stores via `*p` must be properly aligned even when using raw pointers)

It's not like this is an extremely common warning, and when it arises then the programmer really needs to be aware of a lot of subtle details.

**Comment by estebank** [comment]
I like the final proposed output and agree that given how uncommon this will be in practice, going overboard with detail is better than being too terse.

**Pull request merged**
