### PR TITLE
rewrite `ensure_drop_params_and_item_params_correspond`

### PR DESCRIPTION
**Pull request by lcnr**
actually relating types here seems like it's overkill

### CODE REVIEW

**Comment by lcnr** [comment]
was ignored by highfive

r? rust-lang/compiler

**Comment by nagisa** [comment]
I wonder if try works with conflicts in place...

@bors try @rust-timer queue

**Review by nagisa — APPROVED** [review]
Largely LGTM, though I'm not familiar enough with dropck to tell if there aren't any hidden potholes we need to be looking out for by making such a change.

**Review by nikomatsakis — APPROVED** [review]
Hmm.

So I don't like the syntactic comparison for equality that is throughout this code -- I rather prefer the older code, and I would rather express the correctness conditions logically. Certainly in a-mir-formality that is what I expect us to do. (Something like: for all instances of the struct, the drop impl conditions are met.)

That said, the code is cleaner this way, and the only case I could come up with where using syntactic checks would be a problem seems to [already be rejected](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=227432640a3a031c45fa2304a6889333). I consider that a bug, but it's pre-existing and more of a problem with the other drop code.

```rust
struct Foo<T>
where
    T: Iterator,
    T::Item: Send,
{
    t: T,
}

impl<T, I> Drop for Foo<T>
where
    T: Iterator<Item = I>,
    I: Send,
{
    fn drop(&mut self) { }
}

fn main() { }
```

**Do we have a test like this one? If not, can we add one? Otherwise, r=me.**

**Pull request merged**
