### PR TITLE
Fix macro hygiene regression

### PR DESCRIPTION
**Pull request by jseyfried**
The regression was caused by #32923, which is currently in beta.

The following is an example of regressed code:

``` rust
fn main() {
    let x = 0;
    macro_rules! foo { () => {
        println!("{}", x); // prints `0` on stable and after this PR, prints `1` on beta and nightly
    } }

    let x = 1;
    foo!();
}
```

For code to regress, the following is necessary (but not sufficient):
- There must be a local variable before a macro in a block, and the macro must use the variable.
- There must be a second local variable with the same name after the macro.
- The macro must be invoked in a statement position after the second local variable.

For example, if the `let x = 0;` from the breaking example were commented out, it would (correctly) not compile on beta/nightly. If the semicolon were removed from `foo!();`, it would (correctly) print `0` on beta and nightly.

r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
@nrc 
This is the simplest way I could come up with to fix the regression while keeping #32922, #31856, #10681, and #26223 fixed. While I am very confident that it is correct, we (understandably) might not want to backport this big of a change to beta.

In that case, I think we should consider reverting #32923 on beta to avoid regressing hygiene on stable. That being said, the hygiene bug that #32923 fixes, i.e.:
```rust
fn main() {
    let x = 0;
    macro_rules! foo { () => {
        let x = 1;
        println!("{}", x); // prints `0` on stable, should print `1`
    } }
    m!();
}
```
is arguably worse than the bug from the regression.

**Comment by nrc** [comment]
What is the motivation for removing all the unit tests? r+ other than that.

**Comment by jseyfried** [comment]
@nrc 
Some tests were testing functionality that I removed (`resolve_table_hashing_test`, `test_marksof`, `xorpush_test`) and some tests were using functionality that I removed (e.g. `run_renaming_test` was using `mtwt::marksof`). Also, the signatures and semantics of many of the functions changed (e.g. now, unequal marks [prevent renames](https://github.com/rust-lang/rust/pull/34374/commits/a93455eb5d1e54f4415af9c1f44bdd53e7f23ec2#diff-9eab39bd6e0a91db0e92c3e65a6d051dL354)), so I'd have to almost completely rewrite the tests. Finally, the tests are difficult to read, and I haven't entirely grokked what they are doing.

I believe it would be a better use of time to write more `run-pass` and `compile-fail` tests like the ones I added in the last commit. Perhaps if we had written more of these tests earlier, we would have caught #32922 and this regression sooner. These tests will be far more useful for checking future changes to our hygiene implementation.

That being said, I can try to rewrite the unit tests if you think it's worth it.

**Comment by jseyfried** [comment]
@nrc Also, I'm working on dramatically simplifying the hygiene algorithm (without changing semantics) to make it feasible to expand macros in an arbitrary order (needed for macro modularization). I discovered this regression while testing my implementation. Most of the unit tests are not relevant to the simplified implementation.

**Comment by jseyfried** [comment]
I added some more hygiene tests. r? @nrc

**Comment by alexcrichton** [comment]
cc @rust-lang/compiler 

Thoughts on backporting? We hope to produce a new beta soon and would love to include this.

**Comment by nrc** [comment]
somewhat ambiguous about backporting. I think the patch is right, but it is pretty big for a backport, so I'd want to see it properly motivated, i.e., the regression is causing trouble, it's not just a technicality. If that is the case, then happy to backport.

**Comment by alexcrichton** [comment]
@jseyfried do you know if this was causing trouble in the wild?

**Comment by alexcrichton** [comment]
Note that we plan on building the stable 1.10 release tomorrow, so this is unlikely at this point to make a backport. If it's critical to include, though, we can push schedules back and make it work!

**Comment by jseyfried** [comment]
@alexcrichton No, as far as we know this has no impact in the wild, definitely not critical to include.

I still think it would be better to include it, but it's not a big deal -- not worth pushing back the release.

**Comment by alexcrichton** [comment]
Ok, thanks for the update @jseyfried! In that case I'm going to remove the beta-nominated tag from this, but again if anything comes up we can make it work.

**Pull request merged**
