### PR TITLE
Union const colors

### LINKED ISSUE #43523: rustdoc: unions and consts are not color-coded
All the various kinds of item in rust are given a color in rustdoc's CSS, but consts and unions never got one. Fixing should just be a matter of collecting the class name that these items use, and adding a couple rules to rustdoc.css to apply some color to them. The question of *which* color is another matter entirely. `>_>`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #43523

What do you think of these colors:

screen shot 2017-07-30 at 15 10 57

?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/docs

**Comment by QuietMisdreavus** [comment]
The "Union" could stand to be a bit darker, but it also feels about as light as the primitive color, so i'll let it fly.

@TedDriggs - you wanted to check out the new colors, this is the PR that adds them.

**Comment by carols10cents** [comment]
Red/green colorblindness is the most common kind, so structs and enums might not be distinguishable from each other. I have a friend who has some colorblindness, would you like me to run this by him?

**Comment by GuillaumeGomez** [comment]
@carols10cents: It'd be very helpful! Maybe he can suggests better colors as well? :)

**Comment by carols10cents** [comment]
> Maybe he can suggests better colors as well? :)

It's quite likely! Asking!

**Comment by carols10cents** [comment]
Ok! I sent my friend the screenshot and this is what he has to say:

> Struct & Trait are visually distinct. CONST and Union are hard to discern for me as text colors. Enum is fine compared to Struct and Trait, but gets a little lost to me next to Union or CONST.
> 
> Is this syntax highlighting for the documentation? If so, I'd recommend stronger contrast all around if they're meant to sit on a light background. 
>
> Neither CONST nor Union pass WCAG contrast guidelines for use against a white background (http://leaverou.github.io/contrast-ratio/#rgb%28200%2C153%2C89%29-on-white and http://leaverou.github.io/contrast-ratio/#rgb%28193%2C200%2C59-on-white).
>
> Enum is cutting it close too (http://leaverou.github.io/contrast-ratio/#rgb%28105%2C148%2C94%29-on-white). Upping contrast definitely helps me distinguish colors.
>
> I hope this helps. I'll load the colors into the contrast ratio tool and mess around with them to see if I can come up with something I think looks good and is easily distinguishable for me at small sizes against white. :)

**Comment by jnf** [comment]
Hello! I'm the friend @carols10cents referenced above. I have (relatively mild) colorblindness, primarily in distinguishing warm tones. I put together a [Code Pen with some contrast comparisons and an alternate palette](https://codepen.io/anon/pen/eEzrwW/?editors=1100#0). I don't have any context for how these colors are used (my guess is syntax highlighting for docs), so please forgive any misuse.

Anyway, thank you Carol for asking. Yinz keep being this awesome and considerate and I may just have to learn some Rust. ^_^

**Comment by GuillaumeGomez** [comment]
I'll take a look and try to make it easier for colorblind people to see the difference.

**Comment by kennytm** [comment]
The complete list of colors, as the Code Pen only listed five. CR=4.5-ing done via <http://accessible-colors.com/>. Just raising the contrast should not be enough, if the CR of every color is 4.5 they would all become the same shade of gray when the hue is washed out. 

| Kind | Original color | After CR=4.5'ed |
|------|----------------|-----------------|
| Struct | #df3600 | #df3600
| | | |
| Typedef | #e57300 | #df3600
| | | |
| Const (this PR) | #c7944f | #9a6e31
| | | |
| Function | #8c6067 | #8c6067
| | | |
| Union (this PR) | #c0c74f | #767b27
| | | |
| Enum | #5e9766 | 
| | | |
| Macro |  | 
| | | |
| Primitive | #39a7bf | #2C8093
| | | |
| Module | #4d76ae | #4d76ae
| | | |
| Trait | #7c5af3 | #7c5af3


<details><summary>(Coblis simulation of above)</summary>



</details>

**Comment by GuillaumeGomez** [comment]
Here is the new output:

screen shot 2017-08-02 at 23 00 13

Is it fine or is there something else I can do?

**Comment by steveklabnik** [comment]
As long as the contrast is high enough, I'm 👍

**Comment by QuietMisdreavus** [comment]
Looks good to me! I'd like to hear from the others in this thread first, though.

**Comment by carols10cents** [comment]
I defer entirely to @jnf (who has a non-Rust real job in PST so will likely comment in a few hours at the earliest, thank you again for your time on this Jeremy!!!)

**Comment by kennytm** [comment]
@GuillaumeGomez Could we keep functions brown and assign the blue to constants or unions? Existing colors should better be kept "stable".

**Comment by GuillaumeGomez** [comment]
Ok, switched functions and constants color:

screen shot 2017-08-03 at 12 46 42

**Comment by ollie27** [comment]
What about statics? There are also `structfield`, `variant`, `associatedtype` and `associatedconstant`.

For all of these the background highlight color on the search page will also need to be updated to match: https://github.com/rust-lang/rust/blob/b0424b5ff3fef38cd3a6fc82a9cf8995b39e2b64/src/librustdoc/html/static/styles/main.css#L73-L80.

**Comment by GuillaumeGomez** [comment]
@ollie27: Forgot about them. I update as soon as I can!

**Comment by GuillaumeGomez** [comment]
Updated!

screen shot 2017-08-03 at 22 55 04

**Comment by GuillaumeGomez** [comment]
Anything else to do in here?

**Comment by ollie27** [comment]
Any reason not to add colors for statics? After this they'll be the only item type that gets a full page but no colors.

The background highlight colors for `trait` and `type` are still wrong but I guess that's a pre-existing bug. There are still no background colors for `macro`, `constant`, `primitive`, `externcrate` and `static`.

**Comment by GuillaumeGomez** [comment]
@ollie27: Fixed as well! Anything else?

**Comment by ollie27** [comment]
Looks good to me 👍

**Comment by GuillaumeGomez** [comment]
Since you were the last one having issues, I suppose we can r+?

**Comment by QuietMisdreavus** [comment]
It sounds like any interested party is okay with what's left, or was willing to defer to someone else. Let's get this out the door. If anyone finds any more issues with contrast, open another issue and we can work it out!

@bors r+ rollup

**Pull request merged**
