### PR TITLE
Fix blink when main theme is selected

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
So, i tried this by loading it on my server, and it doesn't have the blink affect i get on the current nightly docs. However, neither does the commit without it. `>_>` So i can't be sure it works until it makes it to doc.rlo. It's a useful change, though, so once you fix the merge conflict i can r+.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by steveklabnik** [comment]
Nominating for a beta backport at the next docs team meeting.

**Comment by steveklabnik** [comment]
docs team says 👍 to backport

**Pull request merged**
