### PR TITLE
Change destructuring assignment lowering to use `match`.

### LINKED ISSUE #96579: Desuraring of destructuring assignment has subtle effects on drop-order / scopes of temporaries
For example
```rs
fn main() {
    struct L;
    impl Drop for L {
        fn drop(&mut self) {
            println!("dropped L")
        }
    }
    struct M;
    impl Drop for M {
        fn drop(&mut self) {
            println!("dropped M")
        }
    }

    let x;
    (x = (drop(&L), ()), M);

    println!("---"); // -------------

    let (x1, x2);
    ((x1, x2) = (drop(&L), ()), M);
}
```
Output:
```
dropped M
dropped L
---
dropped L
dropped M
```

<hr>

I came across this by reading [the reference](https://doc.rust-lang.org/stable/reference/expressions/operator-expr.html#destructuring-assignments):

> Assignee expressions are then desugared to pattern matches followed by sequential assignment.

> The desugaring method is straightforward, and is illustrated best by example.
>
> ```
> (a, b) = (3, 4);
>
> [a, b] = [3, 4];
>
> Struct { x: a, y: b } = Struct { x: 3, y: 4};
>
> // desugars to:
>
> {
>     let (_a, _b) = (3, 4);
>     a = _a;
>     b = _b;
> }
>
> {
>     let [_a, _b] = [3, 4];
>     a = _a;
>     b = _b;
> }
>
> {
>     let Struct { x: _a, y: _b } = Struct { x: 3, y: 4};
>     a = _a;
>     b = _b;
> }
>```

The difference between 
```
STATEMENT CONTAINING … x = EXPR …
```
and
```
STATEMENT CONTAINING … { let _x = EXPR; x = _x } …
```
is that in the former case, temporaries in `EXPR` are dropped _after_ the surrounding statement is evaluated, while the latter case has them dropped right after the `let _x = EXPR`.

<hr>

It seems to me that a better desugaring would have been to use something like
```

#![allow(unused)]
fn main() {
struct Struct { x: u32, y: u32 }
let (mut a, mut b) = (0, 0);
(a, b) = (3, 4);

[a, b] = [3, 4];

Struct { x: a, y: b } = Struct { x: 3, y: 4};

// desugars to:

match (3, 4) {
    (_a, _b) => {
        a = _a;
        b = _b;
    }
}

match [3, 4] {
    [_a, _b] =>
        a = _a;
        b = _b;
    }
}

match Struct { x: 3, y: 4} {
    Struct { x: _a, y: _b } => {
        a = _a;
        b = _b;
    }
}
```

<hr>

Or applied to the example above:
```rs
fn main() {
    ………
    
    let (x1, x2);
    // current desugaring
    (
        {
            let (_x1, _x2) = (drop(&L), ());
            x1 = _x1;
            x2 = _x2;
        },
        M,
    );

    println!("---"); // -------------

    let (x1, x2);
    // better desugaring
    (
        match (drop(&L), ()) {
            (_x1, _x2) => {
                x1 = _x1;
                x2 = _x2;
            }
        },
        M,
    );
}
```
```
dropped L
dropped M
---
dropped M
dropped L
```

[Full example in the playground.](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=666c04b6614b33b686aad9c2b30131e1)

Changing it now might technically be a breaking change, OTOH, the feature of destructuring assignment is still very young, and the change is small. I’m not 100% certain about the "bug" label, but I’ll add it for now, next to "enhancement", to let the reader choose whichever they feel more appropriate: @rustbot label C-bug, C-enhancement, F-destructuring_assignment, T-compiler

### PR DESCRIPTION
**Pull request by steffahn**
Previously, lowering `(a, b) = t` produced code like `{ let (lhs1, lhs2) = t; a = lhs1; b = lhs2; }`,
with this PR, `match t { (lhs1, lhs2) => { a = lhs1; b = lhs2; } }` is produced instead.

The desired effect is to make sure that temporaries in the expression `t` aren't dropped too early,
in order to get better consistency between the behavior of e.g. `x = t` vs. `[x] = [t]` or `(x,) = (t,)`
(where `t` is an arbitrary expression).

Fixes #96579

As also discussed shortly [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Destructuring.20assingment.20desugaring), this is a breaking change (most commonly affecting drop order of temporaries of the RHS vs. old values in the places that are being assigned) and thus this will need a crater run, and probably approval from T-lang.

The PR is still missing tests at this point. And there's a `FIXME` to be addressed/discussed (though the `FIXME` is no blocker for a crater run, as AFAICT – in anything – it could only affect diagnostics).

### CODE REVIEW

**Comment by oli-obk** [comment]
@craterbot test

**Comment by steffahn** [comment]
Trying to address the diagnostics change that causes CI failure, I found that the current logic is flawed leading to code like this ICEing on current nightly
```rs
fn main() {
    let x: usize;
    while (x,) = (0_usize,) {}
}
```

I’ll come back to this (and open another issue, etc…) tomorrow.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@steffahn Can you post your status on this PR?

**Comment by JohnCSimon** [comment]
@steffahn 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
