### PR TITLE
force share-generics on drop-glue locally

### PR DESCRIPTION
**Pull request by csmoe**
r? @bjorn3 
a perf-run is requested, thanks.

### CODE REVIEW

**Comment by workingjubilee** [comment]
I'm guessing fewer things get monomorphized into nothing as a result.

**Comment by csmoe** [comment]
@bjorn3 As the previous share-generics on drop-glue stated that drop-glue should be instantiated if **used** https://github.com/rust-lang/rust/pull/68414/files#diff-28d299e2742f2ca199c4d3dcd9df0d8bae3dd0998db034803da401057501fa56R15
I'm doing the nearly same thing as manually `let _ = Foo;` inside rustc, but this hurts the perf a lot. I cannot think of another way to achieve the goal, do you have any insight on this?
(btw, I tried to build a local huge rust repo with this patch, the binary size was 440k smaller)

**Comment by bjorn3** [comment]
I see. Going to re-assign as this is tricky code and I can't convince myself of the correctness due to lack of experience with this code.

r? compiler

**Comment by davidtwco** [comment]
Is there a rationale to this change written anywhere?

**Comment by csmoe** [comment]
@davidtwco This patch was trying to address https://github.com/rust-lang/rust/issues/84175 , but it regressed a lot, and I can not find a better solution, asking for the team for advice.

as for this patch itself, it should not be accepted obviously.

**Comment by davidtwco** [comment]
I can't think of another way to do this - I think there will just be a performance penalty to always generate drop-glue. It might be beneficial when that drop-glue goes on to be used, but there will be many cases where we now generate drop-glue that will never be used.

**Comment by csmoe** [comment]
After reading the code of share-generics and PGO, I'm wandering if it is possible to generate some profdata for rustc itself like PGO profdata for llvm, which teaches rustc to do share-generics on functions for a local project. We are doing this manually by create a top level crate which instantiates functions inside it, then make the business modules depends on it.

thanks for your reviewing :)

**Pull request closed without merging**
