### PR TITLE
rustdoc: do not emit tuple variant fields if none are documented

### LINKED ISSUE #90824: rustdoc: Tuple Fields of Variant section is superfluous and noisy if all fields are undocumented
I understand that if (at least one of) a tuple variant's fields is documented, we need a place to put that documentation. But if not this just adds superfluous noise. Especially if you have a lot of tuple enum variants with undocumented fields it becomes very noisy very quickly. As a real world example from one of my codebases:

```rust
pub enum RotationPolicy {
    /// Only rotate when [`RotatingFileWriter::rotate`] is called.
    Manual,
    /// Rotate when the active file exceeds this many bytes.
    SizeLimit(usize),
    /// Rotate periodically.
    Periodically(Period),
    /// Rotate both periodically and whenever the size limit is exceeded.
    SizeLimitAndPeriodically(usize, Period),
    /// A custom callback to determine when to rotate. Called after every write
    /// with the current active file size and age.
    Custom(Box<dyn FnMut(usize, Duration) -> bool>),
}
```

How it currently looks:

image

And with the superfluous sections removed:

image

I think we should get rid of any "Tuple Fields of Variant" section if that variants' fields are undocumented. It only adds noise and makes the documentation less readable in my opinion.

### PR DESCRIPTION
**Pull request by euclio**
Fixes #90824.

Before:

2021-12-15T22:26:41

After:

2021-12-15T22:27:01

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm not sure that we reached an agreement yet on the issue. Just in case: cc @Nemo157 @jsha @camelid

**Comment by jsha** [comment]
This looks good to me and is the approach that I was trying to express in the issue thread.

@euclio based on the screenshots, you may be building off an outdated master. We made some changes to the display of tuple fields recently and now they look like this (https://doc.rust-lang.org/nightly/std/path/enum.Prefix.html):

image

Would you mind pulling the latest and updating your branch and screenshots?

**Comment by euclio** [comment]
Rebased and updated screenshots.

**Comment by GuillaumeGomez** [comment]
Can you also provide a case where a `0` field is documented as well please? Otherwise looks good to me.

**Comment by camelid** [comment]
@GuillaumeGomez this is waiting on a review I think.

**Comment by GuillaumeGomez** [comment]
Arf indeed. I'll review it tomorrow morning then. Thanks for the ping!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r6

**Comment by GuillaumeGomez** [comment]
With the correct command this time...

@bors: r+

**Comment by matthiaskrgr** [comment]
@bors r-
failed in a rollup https://github.com/rust-lang/rust/pull/92727#issuecomment-1008981079
maybe needs a rebase or something

**Comment by camelid** [comment]
CI is failing.

**Comment by euclio** [comment]
CI is now green.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Pull request merged**
