### PR TITLE
Optimize `shallow_resolve_changed`

### PR DESCRIPTION
**Pull request by nnethercote**
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Seems like it's not really a win, but I'm not opposed to landing it.

**Comment by Centril** [comment]
Seems like a net loss, so why land it?

**Comment by nnethercote** [comment]
That's weird... it was a clear win of about 3-4% on `inflate-check-clean` and `keccak-check-clean` on my machine. I will investigate on Monday.

**Comment by nnethercote** [comment]
I rebased and double-checked the results. Here's what I get locally:
```
inflate-check
        avg: -4.2%      min: -4.2%      max: -4.2%
keccak-check
        avg: -3.0%      min: -3.0%      max: -3.0%
cranelift-codegen-check
        avg: -0.4%      min: -0.4%      max: -0.4%
clap-rs-check
        avg: -0.3%      min: -0.3%      max: -0.3%
serde-check
        avg: -0.3%      min: -0.3%      max: -0.3%
deeply-nested-check
        avg: -0.2%      min: -0.2%      max: -0.2%
unify-linearly-check
        avg: -0.2%      min: -0.2%      max: -0.2%
wg-grammar-check
        avg: -0.1%      min: -0.1%      max: -0.1%
style-servo-check
        avg: -0.1%      min: -0.1%      max: -0.1%
syn-check
        avg: -0.1%      min: -0.1%      max: -0.1%
deep-vector-check
        avg: -0.1%      min: -0.1%      max: -0.1%
piston-image-check
        avg: -0.1%      min: -0.1%      max: -0.1%
cargo-check
        avg: -0.1%      min: -0.1%      max: -0.1%
```
Let's try again.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
> Finished benchmarking try commit [ec4d9e0](https://github.com/rust-lang/rust/commit/ec4d9e01ff378edf7bc46f5d3d0158988ee8fd82), [comparison URL](https://perf.rust-lang.org/compare.html?start=59947fcae6a40df12e33af8c8c7291014b7603e0&end=ec4d9e01ff378edf7bc46f5d3d0158988ee8fd82).

@Mark-Simulacrum: no data is being shown in the results. (Likewise in #66405.) Any idea what's wrong?

**Comment by nnethercote** [comment]
The new results are finished and they are basically a wash: some slight improvements, some slight regressions. This makes no sense to me.
- It doesn't match [my local results](https://github.com/rust-lang/rust/pull/67079#issuecomment-563029012) at all.
- My local results are consistent with the many `ObligationForest` optimizations I've done before: big wins for `inflate` and `keccak`, and smaller wins for `cranelift-codegen`, `clap-rs`, and `serde`.
- `shallow_resolve_unchanged` is known to be very hot, and these commits clearly improve it; there are no trade-offs involved, the new code is simply better.

I don't know what to do with this.

**Comment by nnethercote** [comment]
I did another local perf run, a full one this time. Results are the same as what I got before, and don't match the CI results:
```
inflate-check
        avg: -3.0%      min: -4.2%      max: 0.0%
keccak-check
        avg: -1.9%      min: -3.0%      max: -0.0%
keccak-debug
        avg: -1.7%      min: -2.6%      max: 0.0%
inflate-debug
        avg: -1.8%      min: -2.6%      max: -0.0%
keccak-opt
        avg: -1.5%      min: -2.3%      max: 0.0%
inflate-opt
        avg: -0.5%?     min: -0.7%?     max: 0.0%?
coercions-debug
        avg: -0.1%?     min: -0.5%?     max: 0.1%?
cranelift-codegen-check
        avg: -0.2%      min: -0.4%      max: 0.0%
clap-rs-check
        avg: -0.1%      min: -0.3%      max: -0.0%
serde-check
        avg: -0.2%      min: -0.3%      max: 0.0%
serde-debug
        avg: -0.2%      min: -0.3%      max: 0.0%
serde-opt
        avg: -0.2%      min: -0.3%      max: 0.0%
```
Argh.

**Comment by nnethercote** [comment]
Let's try one more time.

@bors try @rust-timer queue

**Comment by Mark-Simulacrum** [comment]
@nnethercote Maybe it's worth trying to benchmark locally with the CI build (i.e., using `rustup-toolchain-install-master`)? It seems not entirely unlikely that the difference comes down to incremental state or something like that.

**Comment by nikomatsakis** [comment]
Having trouble with the comparison URL :( Not sure what's going on with those things

**Comment by nikomatsakis** [comment]
Maybe it needs to be rebased so that the comparison is based off a more recent commit?

**Comment by nnethercote** [comment]
The CI run does two sets of benchmarking, one for the commits, and one for the parent (the baseline). rust-timer reports back when the first set is done, but the URL doesn't display results successfully until the parent is also done. It's in the queue right now, should be finished soon.

I also suspect a bug in rustc-perf... I am also getting mismatches between local results and CI results in #66405. I am investigating now.

**Comment by nnethercote** [comment]
The latest perf run has finished and the results are closer to what I'd expect (wins on `inflate` and `keccak`), but still don't fully match my local results. I'm about to investigate with local runs of the builds used for the CI run.

**Comment by nnethercote** [comment]
#67248 suggests that CI is working as expected. The most recent CI perf results are good, even though they're not as good as what I saw locally. And logically, the code is clearly better. I will land this, though I'm still uneasy about the variability of the CI perf results.

r=nikomatsakis

**Comment by mati865** [comment]
@netthercote are you build locally with jemalloc enabled? Also difference of glibc versions could make big difference here.

**Pull request merged**
