### PR TITLE
Add `expr202x` macro pattern

### LINKED ISSUE #84155: inline-const is not an expr in macros, but it should be
While writing a macro thingy that generates match blocks, I had a problem where it was previously using an `expr` type, but that didn't work[1], as it didn't accept the inline `const` as an `expr`, so I tried putting it as a `pat` instead, but *that* didn't work[2] as `pat`s aren't accepted in exprs, even if they would be valid in text form.

[1] The subject of this bug report:

```rust
macro_rules! doggo {
    ($v:expr) => {4};
}

fn main() {
    doggo!(const { 2 });
}
```

Compile failure (the subject of this bug):

```
error: no rules expected the token `const`
 --> src/main.rs:8:12
  |
1 | macro_rules! doggo {
  | ------------------ when calling this macro
...
8 |     doggo!(const { 2 });
  |            ^^^^^ no rules expected this token in macro call

error: aborting due to previous error

error: could not compile `rusttest`
```

[2] The thing I tried, that I think is probably reasonable behaviour, although the error needs improvement:

```rust
#![feature(inline_const)]

macro_rules! doggo {
    ($v:pat) => {
        $v
    };
}

fn main() {
    let v = doggo!(const { 2 });
}
```

Error:

```
error: expected expression, found `const{ 2 }`
  --> src/main.rs:5:9
   |
5  |         $v
   |         ^^ expected expression
...
10 |     let v = doggo!(const { 2 });
   |             ------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (d0695c908 2021-04-12)
binary: rustc
commit-hash: d0695c9081b16077d0aed368bccaf437d77ff497
commit-date: 2021-04-12
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### PR DESCRIPTION
**Pull request by lf-**
This makes it possible to use `inline_const` (#76001) and `let_chains`
(#53667) inside macros' `expr` patterns in a future edition by
bifurcating the `expr` nonterminal in a similar way to `pat2021` to
remove some backwards compatibility exceptions that disallow
`const`/`let` at the beginning of an `expr` match.

Fixes #84155 and relaxes the backward compat restriction from #80135 for
a future edition. This is not necessarily intended to go into 2021 as it I don't
think it's simple to write an automatic fix, and I definitely won't have time very
soon.

Here is a pathological case of #79908 that forces this to be an edition
change:

```rust
macro_rules! evil {
    ($e:expr) => {
        // or something else
        const {$e-1}
    };
    (const $b:block) => {
        const {$b}
    }
}
fn main() {
    let x = 5;
    match x {
        evil!(const { 5 }) => panic!("oh no"),
        _ => (),
    };
}
```

### CODE REVIEW

**Comment by m-ou-se** [comment]
cc @rust-lang/project-edition-2021

**Comment by nikomatsakis** [comment]
Hmm, I'm in favor of the concept overall, but I'd like to have a bit of a "write-up" or something that brings together the required information. I don't quite remember, for example, what changes were required to the `expr` non-terminal and why.

**Comment by lf-** [comment]
> Hmm, I'm in favor of the concept overall, but I'd like to have a bit of a "write-up" or something that brings together the required information. I don't quite remember, for example, what changes were required to the `expr` non-terminal and why.

Alright, that's entirely understandable! So it looks like the back compat thing for let chaining came from this comment discussion: https://github.com/rust-lang/rust/pull/60861#issuecomment-495994995 and [an associated fixme in the feature gate ui test introduced by that pr](https://github.com/rust-lang/rust/pull/60861/files#diff-d88c3f9cb474c5bc86352d49ec59dabf33217d2e3fa1a1d7f61fd2c7d88c7832R133) which passes here because this pr doesn't inflict the new behaviour on any edition yet. In other words, this one is here because of conservatism. But we can probably assume that someone out there has written a macro that depends on the exception in the current expression behaviour based on the next one's experience:

The other exception for inline const was because we got bitten by the issue that was proposed in the above discussion, but in the context of inline const. This exception got in because of #80135: it was needed to keep some macros on beta working, which expected the const keyword then some expression after, as I understand it based on my testing and reading examples. 

The former exception was removed here since I was bifurcating anyway and could reserve it. The latter was because of inline const needing to have parens around it to be valid in macro invocations currently, which is odd and rather confusing (I didn't know about this trick to get it accepted by the parser until it was pointed out to me by a friend so I assumed it simply wasn't allowed. the error here is bad too).  Macros taking `:expr` seem liable to hit an issue shaped like this whenever a syntax extension to expressions happens, as a form of inherent fragility, so it's probable some more exceptions like these might get introduced as extensions get added. 

Does this need to happen now? Not strictly. It could happen later or never, at the expense of macros being a little more confusing: It was written while I was under the invalid impression you couldn't pass a const block to a macro as an expression, which I now know is possible with parens, but that fact was anything but discoverable. It would be good to resolve the syntax ambiguity to favour consistency in being able to put `const { ...}` anywhere an expression could go, including in macros, imo. I'm not super familiar with let chaining or how this applies in its case, although I'd be inclined to believe that a similar argument could be made.

**Comment by nikomatsakis** [comment]
I see. So the `expr` macro nonterminal is starting to diverge from the full set of expressions, is the point, in some specific cases (the ones you identified). Hmm!

**Comment by nikomatsakis** [comment]
Nominated for @rust-lang/lang discussion.

**Comment by lf-** [comment]
force push: Fixed the merge conflict and also the feature gate using the wrong suggestion

**Comment by pnkfelix** [comment]
Opened issue #86730 for lang team to discuss *how* we want to resolve this, as discussed in the 2021-05-11 lang team meeting ([minutes](https://github.com/rust-lang/lang-team/blob/master/minutes/2021-05-11.md#add-expr202x-macro-pattern-rust84364), [youtube](https://youtu.be/5hmVDeNc1t0?t=776)).

**Comment by pnkfelix** [comment]
I believe the conclusion of the lang team is that we are not confident that the approach used in this PR is the exact right one we want to deploy, and so I propose we close this PR while we wait to resolve the questions raised in #86730.

**Comment by pnkfelix** [comment]
@rfcbot close

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by crlf0710** [comment]
Closing according to the fcp decision above.

**Comment by pnkfelix** [comment]
as noted by @traviscross elsewhere: Further action here is now gated on acceptance of https://github.com/rust-lang/rfcs/pull/3531, "Macro matcher fragment specifiers edition policy".

**Pull request closed without merging**
