### PR TITLE
Changed color of struct link from #ff794d to #2dbfb8 for Rust docs

### PR DESCRIPTION
**Pull request by PramodBisht**
This is in reference to https://github.com/rust-lang/rust/issues/47801

here I have changed the default color of struct link for `#ff794d` to `#2dbfb8`

cc: @nagisa  @timClicks

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
All struct are red colored, even in doc examples. I'm not sure this is a very good idea to change it... Also, red doesn't mean that a resource isn't available. At least I don't feel it like this...

**Comment by PramodBisht** [comment]
@GuillaumeGomez, @QuietMisdreavus, 
Please feel free to decline PR, if you both think it's not good idea :)

**Comment by nagisa** [comment]
This is what the currently proposed colours look like:

screenshot from 2018-01-27 20-15-00
screenshot from 2018-01-27 20-14-25

---

@GuillaumeGomez would you be fine with changing the colour to some hue that is less far away from red? e.g. something like 

screenshot from 2018-01-27 20-18-35

or 

screenshot from 2018-01-27 20-18-08

**Comment by nagisa** [comment]
Note, there is precedent for changing the colour already. We quite recently changed the lightness of many link colours recently to make colours darker.

**Comment by GuillaumeGomez** [comment]
The orange seems fine. However, it's more of a personal taste here. Also, it'll be need to be changed in the dark theme as well (which wasn't the case in this PR).

**Comment by nagisa** [comment]
The PR does change the dark theme.

**Comment by GuillaumeGomez** [comment]
It puts the same color than in the main theme. Seems strange that two different themes get one color in common. Maybe it renders just fine, but seems weird.

**Comment by QuietMisdreavus** [comment]
As-is, the proposed color is [too light in the main theme](https://www.joedolson.com/tools/color-contrast.php?type=hex&color=%232dbfb8&color2=%23FFFFFF&alpha=). If you want to keep the teal for it, change the `main.css` color to `#1b7e6e` instead. That will give a much better [color contrast of 4.93:1](https://www.joedolson.com/tools/color-contrast.php?type=hex&color=%231b7e6e&color2=%23FFFFFF&alpha=1).

**Comment by PramodBisht** [comment]
@QuietMisdreavus would not #1b7e6e look much similar to color or `macro`(#068000).

**Comment by QuietMisdreavus** [comment]
I guess so. I think the pink color in @nagisa's comment is good - the orange seems like it might be too light, and might also be too close to the existing orange of type aliases.

**Comment by PramodBisht** [comment]
@QuietMisdreavus @GuillaumeGomez @nagisa Pink look goo on white theme. Pushed code change as well.

**Comment by kennytm** [comment]
@nagisa's pink is `#df00b2`, which gives [4.39:1 ratio](https://jdlsn.com/color/?type=hex&color=df00b2&color2=FFFFFF). `#dc00b0` would be exactly 4.5:1.

Note that foreign type uses a similar pink already `#cd00e2` (4.47:1 😓, 4.5:1 would be `#cc00e1`), although it is more purplish.

**Comment by GuillaumeGomez** [comment]
Not orange then? 😢

**Comment by kennytm** [comment]
Current color of type alias is already orange `#ba5d00`.

**Comment by GuillaumeGomez** [comment]
Damn. I found the red really good enough, that's too bad...

**Comment by pietroalbini** [comment]
@GuillaumeGomez ping! What's the status of this PR?

**Comment by GuillaumeGomez** [comment]
We still need to have a consensus over the color.

**Comment by kennytm** [comment]
Nominating to docs team in this case 😛 

Current choices on table:

* No change = Red (`#df3600`)
* This PR = Purple (`#ad448e`)
* Pink (`#dc00b0`) (may be too close to extern type `#cd00e2`)
* Brown (`#a76900`) (may be too close to type alias `#ba5d00`)
* Orange (`#df8e00`) (fails the 4.5:1 contrast ratio)

Existing colors:

| Kind | main.css | dark.css |
|------|----------|----------|
| Macro | `#068000` | `#09bd00` |
| Enum | `#508157` | `#82b089` |
| Primitive | `#2c8093` | `#43aec7` |
| Module | `#4d76ae` | `#bda000` |
| Static | `#546e8a` | `#82a5c9` |
| Trait | `#7c5af3` | `#b78cf2` |
| Extern type | `#cd00e2` | `#dd7de8` |
| Union | `#767b27` | `#a6ae37` |
| Function | `#9a6e31` | `#2BAB63` |
| Type alias | `#ba5d00` | `#ff7f00` |
| Struct (current) | `#df3600` | `#ff794d` |

**Comment by PramodBisht** [comment]
@QuietMisdreavus @kennytm @GuillaumeGomez @nagisa what next?

**Comment by kennytm** [comment]
@PramodBisht As linked from rust-docs/team#5, it is on doc team's agenda in the coming meeting in 9 hours (Feb 13th, 20:00 UTC). You may join the IRC channel `#rust-docs` on irc.mozilla.org at that time.

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
We talked about it in the docs team meeting today, and the inclination is to merge. In the future, we may want to change structs, enums, and unions to have similar colors, but that's a big change, and fixing the immediate issue is better than bogging down this PR in sorting that out.

@PramodBisht thank you so much!

@bors: r+ rollup

**Pull request merged**
