### PR TITLE
ci: Upgrade non-dist Linux testers from ubuntu:16.04 to 22.04

### PR DESCRIPTION
**Pull request by cuviper**
The main goal of updating to 22.04 is to get away from `llvm.allow-old-toolchain`.
A side benefit is that they can also use the system `cmake` instead of building one.

### CODE REVIEW

**Comment by cuviper** [comment]
I don't know how rustdoc-gui tests work, but this seems confused:

```
⚠️ Installed version of browser-ui-test (`0.9.7:undefined`) is different than the one used in the CI (`0.9.7`)
You can install this version using `npm update browser-ui-test` or by using `npm install browser-ui-test@0.9.7`
```

**Comment by Mark-Simulacrum** [comment]
I think I've seen that locally too. You can probably adjust the code in rustbuild(?) to just be OK with a :undefined suffix.

**Comment by cuviper** [comment]
Ok, that looks like an additional field in the npm output, though always "undefined":

```
# npm list --parseable --long --depth=0 --global
/node-v14.4.0-linux-x64/lib::undefined
/node-v14.4.0-linux-x64/lib/node_modules/browser-ui-test:browser-ui-test@0.9.7:undefined
/node-v14.4.0-linux-x64/lib/node_modules/npm:npm@6.14.5:undefined
```

I've attempted to fix that up by splitting on just `':'` first.

**Comment by cuviper** [comment]
Here's the next failure:

```
Running 68 rustdoc-gui (16 concurrently) ...
FFERROR: puppeteer failed when trying to create a new page. Please try again with `--no-sandbox`

`browser-ui-test` crashed unexpectedly. Please try again with adding `--test-args --no-sandbox` at the end. For example: `x.py test src/test/rustdoc-gui --test-args --no-sandbox`
```

I can certainly add that `--no-sandbox`, if someone will second the suggestion as being reasonable...

**Comment by Urgau** [comment]
> Here's the next failure:
> 
> ```
> Running 68 rustdoc-gui (16 concurrently) ...
> FFERROR: puppeteer failed when trying to create a new page. Please try again with `--no-sandbox`
> 
> `browser-ui-test` crashed unexpectedly. Please try again with adding `--test-args --no-sandbox` at the end. For example: `x.py test src/test/rustdoc-gui --test-args --no-sandbox`
> ```
> 
> I can certainly add that `--no-sandbox`, if someone will second the suggestion as being reasonable in CI...

cc @GuillaumeGomez (as maintainer of `browser-ui-test` in the rust repo)

**Comment by GuillaumeGomez** [comment]
You need to add `--test-args --no-sandbox` where `browser-ui-test` is called (so in `docker/host-x86_64/x86_64-gnu-tools/Dockerfile` where we call `test/rustdoc-gui`).

**Comment by cuviper** [comment]
Alright, thanks, I just wanted to make sure that was okay since we didn't need it before. I've added it now.

**Comment by GuillaumeGomez** [comment]
That is a new error. Sometimes the page crashes apparently O.o

**Comment by cuviper** [comment]
Page crashed again. Would it make sense to try with newer Node.js? Looks like the current LTS is 16.17.0.

**Comment by GuillaumeGomez** [comment]
Updating nodejs is a good idea. Not sure if it will solve the issue though since it seems that chromium is the issue. You can try limiting the number of parallel jobs with `--jobs` (as you can see [here](https://github.com/rust-lang/rust/blob/master/src/tools/rustdoc-gui/tester.js#L22)).

**Comment by cuviper** [comment]
OK, I see puppeteer follows the maintenance LTS, which is still v14, so I only updated that to node 14.20.0 for now. But adding rustdoc-gui `--jobs 1` worked locally for me to avoid the page crashes, and there aren't so many to worry about time IMO.

Longer term: AIUI the chromium version is set by puppeteer -- you might want to update that in `browser-ui-test`?
>     npm WARN deprecated puppeteer@3.3.0: Version no longer supported. Upgrade to @latest

**Comment by GuillaumeGomez** [comment]
The reason why I didn't update the puppeteer version is because for some unknown reason, starting the next version, you can't click on pseudo elements (so `div::after` for example). But I think I'll need to update it at some point because this version is just too old.

**Comment by cuviper** [comment]
@pietroalbini this should be working and ready for review now.

**Pull request merged**
