### PR TITLE
Rustdoc: Only show the interface provided by macros

### LINKED ISSUE #17616: rustdoc: show macro interface but not implementation
e.g. http://doc.rust-lang.org/std/macro.bitflags!.html has 120 lines of macro code before anything useful.

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes #17616

New docs for `panic!`:

``` rust
macro_rules! panic {
    () => { ... };
    ($msg:expr) => { ... };
    ($fmt:expr, $($arg:tt)+) => { ... };
}
```

New docs for `assert!`:

``` rust
macro_rules! assert {
    ( $ cond : expr ) => { ... };
    (
$ cond : expr , $ ( $ arg : tt ) + ) => { ... };
}
```

<sup>not pretty, but at least it's not worse :joy:

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Added a semicolon to all arms, to make the docs more similar to the actual macro syntax

**Comment by sanxiyn** [comment]
Can you add a test? See tests under `src/test/rustdoc`.

**Comment by jonas-schievink** [comment]
Test added

**Pull request merged**
