### PR TITLE
optimize for common case

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by kennytm** [comment]
Is there benchmark or generated assembly diff showing there is really an improvement?

**Comment by ishitatsuyuki** [comment]
Surely no. You need intrinsics to provide such hints.

https://godbolt.org/g/0A28T4

**Comment by alexcrichton** [comment]
r? @sfackler 

(random libs team member)

**Comment by sfackler** [comment]
I would like to see an assembly diff along with some benchmarks that show this is a change with a concrete benefit.

**Comment by ofek** [comment]
Using `cargo rustc --release -- --emit asm`?

**Comment by sfackler** [comment]
Sure, that would work.

I care way more about the performance benchmark numbers though.

**Comment by ishitatsuyuki** [comment]
@sfackler see the link attached above for a short reproduction. It shows that LLVM is turning them into same branch.

**Comment by ofek** [comment]
Interesting results

```rust
#![feature(test)]

extern crate test;

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::VecDeque;
    use test::Bencher;

    #[bench]
    fn bench_pop_front(b: &mut Bencher) {
        let size: usize = 1_000_000;
        let mut zeros: VecDeque<u8> = VecDeque::with_capacity(size);
        for i in 0..size {
            zeros.push_front(0u8);
        }

        b.iter(|| {
            for i in 0..size {
                zeros.pop_front();
            }
        })
    }

    #[bench]
    fn bench_pop_back(b: &mut Bencher) {
        let size: usize = 1_000_000;
        let mut zeros: VecDeque<u8> = VecDeque::with_capacity(size);
        for i in 0..size {
            zeros.push_back(0u8);
        }

        b.iter(|| {
            for i in 0..size {
                zeros.pop_back();
            }
        })
    }
}
```

nightly:
```bash
test tests::bench_pop_back  ... bench:   1,596,800 ns/iter (+/- 56,557)
test tests::bench_pop_front ... bench:   1,595,819 ns/iter (+/- 47,883)
```

pr:
```bash
test tests::bench_pop_back  ... bench:   1,605,018 ns/iter (+/- 159,932)
test tests::bench_pop_front ... bench:   1,605,298 ns/iter (+/- 386,199)
```

**Comment by ishitatsuyuki** [comment]
Stop writing stupid code. Use https://github.com/rust-lang/rust/issues/26179 to alter the branch prediction.

**Comment by ofek** [comment]
@ishitatsuyuki I don't think that was necessary. I indeed should have benchmarked earlier, my apologies in that regard.

If LLVM outputs the same thing, why is new order slightly slower and has much more variance?

**Comment by ishitatsuyuki** [comment]
@ofek the time is 99.4% identical, how can you argue that it's not the environmental difference like thermal?

If you **really** want to do a `likely`, use intrinsics. Otherwise, give up.

**Comment by ofek** [comment]
@ishitatsuyuki The difference is repeatable. Do you know why that might be? I'm just curious.

**Comment by ranma42** [comment]
@ofek what difference? your benchmark seems to show that they have the same performance (keeping the variance into account).

**Comment by ishitatsuyuki** [comment]
I'm voting to close this as "very low quality" :P

**Comment by BurntSushi** [comment]
@ishitatsuyuki I'd like to ask you to please be mindful of the language you're using when interacting with other contributors, as per our [code of conduct](https://www.rust-lang.org/en-US/conduct.html). It's encouraged to be critical by providing *constructive feedback* that helps others improve, but unstructured criticism should be kept to a minimum or ideally non-existent.

If you have any questions, please follow up with the moderators by emailing rust-mods@rust-lang.org.

**Comment by ishitatsuyuki** [comment]
@BurntSushi sorry, I will be careful about it!

**Pull request closed without merging**
