### PR TITLE
bump `thiserror` to use syn 2.0

### PR DESCRIPTION
**Pull request by fee1-dead**
cc #109302

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/pull/110119

**Comment by w-flo** [comment]
Will this work now that `rustc-workspace-hack` is gone?

**Comment by fee1-dead** [comment]
since rustc-workspace-hack is gone, this should work

@bors r=Mark-Simulacrum

**Pull request merged**
