### PR TITLE
Implement #[cfg(accessible(::path::to::thing)]

### LINKED ISSUE #64797: Tracking issue for RFC 2523, `#[cfg(accessible(::path::to:thing))]`
This is a tracking issue for `#[cfg(accessible(::path::to::thing))]` (rust-lang/rfcs#2523).

**Steps:**

- [ ] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

None so far.

### PR DESCRIPTION
**Pull request by pickfire**
Works towards #64797

### CODE REVIEW

**Comment by petrochenkov** [comment]
I'd strongly suggest to implement `cfg(version)` (https://github.com/rust-lang/rust/issues/64796) first because it has an orders of magnitude higher usefulness/complexity ratio (and is also a better task for a first compiler PR).

**Comment by pickfire** [comment]
@petrochenkov I thought `cfg(version)` was harder that's why I was checking out on this first. Thanks for pointing that out, IIRC someone is already working on that.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@pickfire - I see this is a draft PR, but can you post your status?

**Comment by pickfire** [comment]
@JohnCSimon I am current working on `version` which is similar to this but I am kinda stuck on this not knowing how to proceed next.

**Comment by JohnCSimon** [comment]
@pickfire 
Ping from triage - it's after the holidays - can you post your status on this PR, please?  Thanks

**Comment by petrochenkov** [comment]
This is not a beginner-friendly feature to implement and I have some implementation in progress (https://github.com/rust-lang/rust/issues/64797#issuecomment-571992579), so I'll close this PR and let @pickfire focus on `cfg(version)`.

**Comment by pickfire** [comment]
Holidays?

@JohnCSimon I am not currently working on this, been trying out on `cfg(version)` but still kinda stuck (I hope someone can give some guidance) and busy as of now. Sorry, I did not explicitly ping here regarding that.

**Pull request closed without merging**
