### PR TITLE
Mark fields used by debug format as used

### LINKED ISSUE #123068: field "never read" warning for field that is used by derive(Debug)
I tried this code:

```rust
use std::str;

#[derive(Debug)]
enum ProcessError {
    Utf8(str::Utf8Error),
    Other,
}

impl From<str::Utf8Error> for ProcessError {
    fn from(e: str::Utf8Error) -> Self {
        Self::Utf8(e)
    }
}

fn process(data: &[u8]) -> Result<(), ProcessError> {
    let s = str::from_utf8(data)?;

    if s != "ok" {
        return Err(ProcessError::Other);
    }

    Ok(())
}

fn main() {
    println!("{:?}", process(&[0xff]));
}
```

I expected to see this happen: build cleanly

Instead, this happened:

```
warning: field `0` is never read
 --> src/main.rs:5:10
  |
5 |     Utf8(str::Utf8Error),
  |     ---- ^^^^^^^^^^^^^^
  |     |
  |     field in this variant
  |
  = note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
  |
5 |     Utf8(()),
  |          ~~
```

Running the program shows the field is used:

```
Err(Utf8(Utf8Error { valid_up_to: 0, error_len: Some(1) }))
```

### Meta

Rust version 1.77.0 (tested in playground)

</p>
</details>

### PR DESCRIPTION
**Pull request by long-long-float**
Fix #123068

In the following code, a field value `ProcessError::Utf8.0` is used by `"{:?}"`.
However a "never read" warning is shown.

```rs
#[derive(Debug)]
enum ProcessError {
    Utf8(i32),
}

fn main() {
    println!("{:?}", ProcessError::Utf8(42));
}
```

```
warning: field `0` is never read
 --> test.rs:3:10
  |
3 |     Utf8(i32),
  |     ---- ^^^
  |     |
  |     field in this variant
  |
  = note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
  |
3 |     Utf8(()),
  |          ~~

warning: 1 warning emitted
```

In this PR, I fixed to mark all enum (for now) fields used by `"{:?}"`.

### CODE REVIEW

**Comment by asquared31415** [comment]
I was under the impression that this was intentional, and that there was meant to be a note along the lines of "Debug is ignored for dead code analysis"

**Comment by Nilstrieb** [comment]
Yes, if we mark this as used then the lint Iis basically useless.
If you only use a field for its Debug output, apply `#[allow(dead_code)]` (or in the future, `#[expect()]`) with a comment about this.

**Comment by asquared31415** [comment]
There is however a bug here in that there's not a note explaining it

**Comment by long-long-float** [comment]
Oh, I misunderstood. I will make new PR to explain a note about that derived traits by `Debug` are intentionally ignored.

**Comment by Nilstrieb** [comment]
cool, thanks!

**Pull request closed without merging**
