### PR TITLE
Autogenerate the manpages with the current date.

### PR DESCRIPTION
**Pull request by dns2utf8**
Requires `date` and `cat`

Follow-up to #35287

r? @nikomatsakis

### CODE REVIEW

**Comment by dns2utf8** [comment]
This adds the `doc-man` target which is included in the `docs` target.

**Comment by nagisa** [comment]
cc @alexcrichton what should we do with rustbuild for this?

**Comment by alexcrichton** [comment]
Yeah @dns2utf8 could you be sure to update rustbuild as well? I believe the relevant support would [go here](https://github.com/rust-lang/rust/blob/ddf92ffae4b8fc74474241f064f41f09db585ed8/src/bootstrap/dist.rs#L211)

**Comment by dns2utf8** [comment]
So would you like me to generate the complete correctly timestamped manpage with the `/src/bootstrap/dist.rs` or just update it so it copies only the generated man pages?

**Comment by dns2utf8** [comment]
I just noticed: there is no way to realy reliably calculate the month or year with the rust stdlib, because of [TIMEZONES](https://www.youtube.com/watch?v=-5wpm-gesOY).

So I prepared a little vote :wink: :

:tada: So should I implement it with modulo? Pro: Simple; Con: May lead to an inacurate result near the border of a month?
:smile: Or use the `chrono` [crate](https://crates.io/crates/chrono)? Is it even possible that early in the build process? Pro: Accurate; Con: needs a crate;
:heart: Or should I just filter the generated man pages and copy them? Pro: simple; Con: requires more external resources

I prepared the `dist.rs` and plan to finish it tomorrow.

**Comment by nagisa** [comment]
I do not think the accuracy matters much here. It took people a bunch of years to notice the date is out-of-date (…ehem…), and even if month is off-by-one we can always lie a bit and tell build was done early or late.

**Comment by nikomatsakis** [comment]
@dns2utf8 I'm confused, are you talking about specifically for the rustbuild modifications? You could shell out to `date` or whatever (and manually specify a time-zone...), right? Or invoke some libc routine or other?

**Comment by alexcrichton** [comment]
@dns2utf8 yeah the manpages will need to be generated by dist.rs, if that build system is being used the makefiles aren't even touched. I also agree with @nagisa that accuracy isn't too important here, and @nikomatsakis is also right that either shelling out is fine or pulling a dependency on chrono/time should also be fine.

**Comment by dns2utf8** [comment]
Okay, working on it :smile:

**Comment by nikomatsakis** [comment]
@dns2utf8 is this ready for review? If not, can we close it and just re-open when it is?

**Comment by dns2utf8** [comment]
It is still in progress. I will reopen it when it is done.

**Pull request closed without merging**
