### PR TITLE
Refactored code to access TLS only in case of panic

### LINKED ISSUE #34787: Don't hit thread-local-storage when entering `catch_unwind`
Although TLS is fast, it's not that fast on Windows and we shouldn't be hitting it on the fast path for `catch_unwind`. Right now all we do this for is to reset the panic counter back to 0.

The purpose of this is to allow [code like this](https://github.com/rust-lang/rust/issues/34727#issuecomment-231511425) to work, but thinking more about that I believe that's actually undefined behavior on MSVC. Basically once a panic is initiated you can't initiate another panic for... "reasons". (I'm not 100% clear myself). This definitely seems like a sketchy pattern as well!

So if we *don't* want to enable that pattern, I think we can get away with different management of the panic counter:

* When a panic starts, bump the panic counter. If this indicates a double panic, abort.
* When a `catch_unwind` returns from *catching a panic*, decrease the panic counter. (maybe assert it's 0?)

This way the normal usage of `catch_unwind` where nothing panics should never hit TLS, and we should still be able to use panics as we do today.

### PR DESCRIPTION
**Pull request by nikhilshagri**
Fixes  #34787
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks @cynicaldevil! Two things I'm curious about:

* Could the `debug_assert!` be moved to the happen just before the `return`? It shouldn't be perf sensitive and should be a valid assertion for both paths.
* Could you take a look at some benchmark numbers and see how much this affects the perf of a no-panic catch_unwind?

**Comment by cynicaldevil** [comment]
Sure! no problem.

**Comment by cynicaldevil** [comment]
do I need to pass additional flags while compiling or is the `- -bench`
flag enough?

**Comment by alexcrichton** [comment]
Yeah you'll want something like:

```rust
#![feature(test)]
extern crate test;

#[bench]
fn foo(bh: &mut test::Bencher) {
    bh.iter(|| /* thing to benchmark */);
}
```

```
$ rustc --test foo.rs -O
$ ./foo --bench
```

**Comment by cynicaldevil** [comment]
I put the assert statement before the return now, and also ran the benchmarks:
```
#![feature(test)]
#![allow(warnings)]
extern crate test;

use std::panic::catch_unwind;

#[bench]
fn test_panic(bh: &mut test::Bencher) {
    bh.iter(|| {
        catch_unwind(|| {
          println!("Hello World!");
        });
    });
}
```
my-toolchain
```
bench:       5,995 ns/iter (+/- 1,333)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured
```
nightly
```
bench:       6,030 ns/iter (+/- 1,330)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured
```
Tbh, there isn't much of a difference, I ran these a few times and the time difference was always in the range of 100ns. Sometimes, the nightly was faster than my custom build. Tested on Ubuntu btw.

**Comment by alexcrichton** [comment]
Oh actually could this be just a micro-benchmark for `catch_unwind` performance? For example, just:

```
catch_unwind(|| {})
```

It's true yeah that `catch_unwind` should always be dwarfed by I/O

**Comment by cynicaldevil** [comment]
@alexcrichton Here it is:
```
#![feature(test)]
#![allow(warnings)]
extern crate test;

use std::panic::catch_unwind;

#[bench]
fn test_panic(bh: &mut test::Bencher) {
    bh.iter(|| {
        catch_unwind(|| {});
    });
}
```
my-toolchain
```
running 1 test
test test_panic ... bench:          12 ns/iter (+/- 1)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured
```
nightly
```
running 1 test
test test_panic ... bench:          13 ns/iter (+/- 8)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured
```

**Comment by alexcrichton** [comment]
@bors: r+ b28e9dcae8f0f1930bbd11c826dd7357093ea7ae

Ok, so not a huge win perhaps on Linux, (verified locally as well), but I suspect on WIndows this will make it much faster!

**Comment by alexcrichton** [comment]
Oh dear, shouldn't have hit the merge button...

I guess let's see if it passes!

**Comment by eddyb** [comment]
@alexcrichton I don't think it did: https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1774

**Comment by TimNN** [comment]
https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1776 as well

**Comment by alexcrichton** [comment]
Yeah sorry about that! I've merged the revert, @cynicaldevil would you mind reopening and I'll r+ correctly this time around?

**Pull request merged**
