### PR TITLE
compiletest: ignore-endian-big, fixes #74829, fixes #74885

### LINKED ISSUE #74829: since 1.44 some mir-opt tests assume little-endian
e.g. https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=ppc64&ver=1.44.1%2Bdfsg1-1&stamp=1595858223&raw=0

~~~~
---- [mir-opt] mir-opt/const-promotion-extern-static.rs stdout ----


executing "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/stage2/bin/rustc" "/<<PKGBUILDDIR>>/src/test/mir-opt/const-promotion-extern-static.rs" "-Zthreads=1" "--target=powerpc64-unknown-linux-gnu" "-Zdump-mir=all" "-Zmir-opt-level=3" "-Zdump-mir-exclude-pass-number" "-Zdump-mir-dir=/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/mir-opt/const-promotion-extern-static" "-C" "prefer-dynamic" "--out-dir" "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/mir-opt/const-promotion-extern-static" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/native/rust-test-helpers" "-Clinker=powerpc64-linux-gnu-gcc" "-L" "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/mir-opt/const-promotion-extern-static/auxiliary"
------stdout------------------------------

------stderr------------------------------
[ .. some warnings .. ]


------------------------------------------
57	- }
58	- 
59	- alloc0 (static: Y, size: 4, align: 4) {
-	-     2a 00 00 00                                     │ *...
+	-     00 00 00 2a                                     │ ...*
61	  }
62	  
63	

thread '[mir-opt] mir-opt/const-promotion-extern-static.rs' panicked at 'Actual MIR output differs from expected MIR output /<<PKGBUILDDIR>>/src/test/mir-opt/const-promotion-extern-static/rustc.BAR.PromoteTemps.diff', src/tools/compiletest/src/runtest.rs:3165:25
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
   4: std::panicking::default_hook::{{closure}}
   5: std::panicking::default_hook
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: std::panicking::begin_panic_fmt
   9: compiletest::runtest::TestCx::run_revision
  10: compiletest::runtest::run
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~~~~

~~~~
test [mir-opt] mir-opt/const-promotion-extern-static.rs ... FAILED
test [mir-opt] mir-opt/const_allocation.rs ... FAILED
test [mir-opt] mir-opt/const_allocation2.rs ... FAILED
test [mir-opt] mir-opt/const_allocation3.rs ... FAILED
test [mir-opt] mir-opt/inline/inline-into-box-place.rs ... FAILED
~~~~
~~~~

### LINKED ISSUE #74885: ui simd-intrinsic-generic-bitmask test fails on big endian
version 1.44.1 [s390x](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=s390x&ver=1.44.1%2Bdfsg1-1&stamp=1595858692&raw=0) [ppc64](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=ppc64&ver=1.44.1%2Bdfsg1-1&stamp=1595858223&raw=0) [powerpc](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=powerpc&ver=1.44.1%2Bdfsg1-1&stamp=1595859982&raw=0) (but the failures have been around ever since the test was introduced)

I will be adding an `ignore-endian-big` feature as part of #74829, just wanted to confirm the failure is OK to ignore:

~~~~
---- [ui] ui/simd/simd-intrinsic-generic-bitmask.rs stdout ----


executing "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/stage2/bin/rustc" "/<<PKGBUILDDIR>>/src/test/ui/simd/simd-intrinsic-generic-bitmask.rs" "-Zthreads=1" "--target=powerpc64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "-o" "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/ui/simd/simd-intrinsic-generic-bitmask/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/native/rust-test-helpers" "-Clinker=powerpc64-linux-gnu-gcc" "-L" "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/ui/simd/simd-intrinsic-generic-bitmask/auxiliary"
------stdout------------------------------

------stderr------------------------------

------------------------------------------
executing "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/ui/simd/simd-intrinsic-generic-bitmask/a"
------stdout------------------------------

------stderr------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `5`', /<<PKGBUILDDIR>>/src/test/ui/simd/simd-intrinsic-generic-bitmask.rs:52:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: simd_intrinsic_generic_bitmask::main
   9: std::rt::lang_start::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

------------------------------------------

error: test run failed!
status: exit code: 101
command: "/<<PKGBUILDDIR>>/build/powerpc64-unknown-linux-gnu/test/ui/simd/simd-intrinsic-generic-bitmask/a"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `5`', /<<PKGBUILDDIR>>/src/test/ui/simd/simd-intrinsic-generic-bitmask.rs:52:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: simd_intrinsic_generic_bitmask::main
   9: std::rt::lang_start::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

------------------------------------------
~~~~

CC @gnzlbg who wrote the test originally

### PR DESCRIPTION
**Pull request by infinity0**
See discussion on #74829 

I tested it on a Debian s390x machine, works well.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
makes sense.

@bors r+

**Comment by infinity0** [comment]
ping @nikomatsakis :) i suppose the bot can't automatically figure out that i did the merge "correctly"

**Comment by nikomatsakis** [comment]
@infinity0 can you actually rebase instead? we prefer to avoid merge commits. Thanks! ❤️

**Comment by infinity0** [comment]
@nikomatsakis sure, done

**Comment by infinity0** [comment]
ping @nikomatsakis :)

**Comment by infinity0** [comment]
If I'm reading [the failure](https://github.com/rust-lang-ci/rust/runs/953545521) right, it seems like a transient issue? `error: io error when listing tests: Os { code: 107, kind: NotConnected, message: "Socket not connected" }`

**Comment by JohnTitor** [comment]
The failure is spurious and should be fixed by #75228.
@bors retry

**Pull request merged**
