### PR TITLE
rustc: Forbid `-Z` flags on stable/beta channels

### LINKED ISSUE #31847: Tracking issue for accepting unstable flags in stable compilers
This issue is intended to track the process of fixing rustc to not accept unstable flags on stable compilers. It's somewhat of a historical mistake that this was allowed, and we're attempting now to repair the logic to disallow unstable flags on the compiler. Today the compiler has a few unstable flags:
- `-Z` - all debugging options in the compiler are intended to be unstable
- `--pretty` - the pretty printer is quite broken in various ways, and it's output is also generally quite unstable
- `--unpretty` - the flag and formats emitted here were not intended to be stable
- `--error-format` - this support is currently experimental in the compiler and may not be ready for prime-time

For backwards compatibility the compiler will continue to accept these flags on the stable and beta channels of Rust. In #31793, however, the compiler will start to issue a warning on these channels whenever these flags are passed. The warning message points at this issue.

The next steps on this issue are likely:
- Wait for the warning to propagate to the stable channel
- Get feedback about which unstable flags are widely used today
- Resolve how to stabilize widely used unstable flags
- Wait for these flags to be stable
- Turn the warning of unstable flags on the stable channel into a hard error

If you're coming to this issue via the compiler warning, please feel free to comment with your flag and use case! We're eager to learn which unstable flags are most widely used to prioritize what to stabilize.

### PR DESCRIPTION
**Pull request by alexcrichton**
First deprecated in rustc 1.8.0 the intention was to never allow `-Z` flags make
their way to the stable channel (or unstable options). After a year of warnings
we've seen one of the main use cases, `-Z no-trans`, stabilized as `cargo
check`. Otherwise while other use cases remain the sentiment is that now's the
time to start forbidding `-Z` by default on stable/beta.

Closes #31847

### CODE REVIEW

**Comment by kennytm** [comment]
so... what about #41743 ("Firefox requires `-Zdebug-macros`")?

**Comment by alexcrichton** [comment]
That's a feature that should be stabilized in time, not block this.

**Comment by Mark-Simulacrum** [comment]
Travis failed legitimately, I think. I'm somewhat concerned that we'd break Firefox's debugging process by landing this, though, especially with no current clear path forward for debug-macros.

```
[00:05:47] error: unused import: `early_warn`
[00:05:47]     --> /checkout/src/librustc/session/config.rs:1664:32
[00:05:47]      |
[00:05:47] 1664 |     use session::{early_error, early_warn};
[00:05:47]      |                                ^^^^^^^^^^
[00:05:47]      |
[00:05:47]      = note: #[deny(unused_imports)] implied by #[deny(warnings)]
[00:05:47] note: lint level defined here
[00:05:47]     --> /checkout/src/librustc/lib.rs:24:9
[00:05:47]      |
[00:05:47] 24   | #![deny(warnings)]
[00:05:47]      |         ^^^^^^^^
[00:05:47] 
[00:05:48] error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
@Mark-Simulacrum we've been printing for over a year that this will become a warning, debugging with these features will continue to work on nightly, as is intended.

**Comment by jsgf** [comment]
I think this is a mistake: https://internals.rust-lang.org/t/disabling-z-for-stable-builds-is-a-mistake/5221

**Comment by ctz** [comment]
Is there a stable replacement for `-Zno-landing-pads`? I know about `Cpanic=abort`, but unfortunately that isn't supported for unit tests (apparently, because `libtest` requires unwinding support).

**Comment by K4sum1** [comment]
It has been over 7 years can we have this reverted now?

**Pull request merged**
