### PR TITLE
Remove duplicate section

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
For some reason the section was duplicated. There was a very minor variation in phrasing; I believe that no information is lost with this PR.

### CODE REVIEW

**Comment by Amanieu** [comment]
This isn't exactly duplicated: there is technically a difference between "tier 1" and "tier 1 with host tools", it's just that at the moment these both contain the same set of targets.

Perhaps it would be better to remove this distinction and only refer to these as "tier 1" targets. We could re-introduce the distinction if we ever add a tier 1 target without host tools.

**Comment by Arthur-Milchior** [comment]
Thank you for the explanation, I think I now have a better understanding of this page.

I could understand it would be easier to keep both sections than to create a new one later. At least to let readers know that they may eventually exists tier 1 without host tools. If the distinction exists in Rust community, my goal was really not to change the way concept are referenced.

May I suggest, as you did with tier 2, titling the section explicitly "Tier 1 target without host tools".
Or maybe refactor a little bit, and have a section
"Tier 1 target", with two subsections, "with" and "without" host tools. And do the same for "Tier 2". This would in particular help understand what is in common and what differs between the "with" and the "without" host tools.

Should I open a bug report? I doubt this PR can be merged as-is, and I suspect this discussion may be better in a bug than a PR. Also, if the change is less trivial, it may be done in a different PR than this one

**Comment by Amanieu** [comment]
I like the idea of making with/without host tools a sub-section of the tier. 

If you update your PR to do this then we can move forward with it.

**Comment by Arthur-Milchior** [comment]
I hope this change will fit your requirement

**Comment by Amanieu** [comment]
Looks good!

r=me once conflicts are resolved.

**Comment by Amanieu** [comment]
ping @Arthur-Milchior can you resolve conflicts and rebase?

**Comment by Dylan-DPC** [comment]
@Arthur-Milchior any updates on this? thanks

**Comment by oskgo** [comment]
@Arthur-Milchior

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this.
Note: if you are going to continue please open the PR BEFORE you push to it, else you won't be able to reopen - this is a quirk of github.
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
