### PR TITLE
Add Stylo and WebRender to src/tools/cargotest

### PR DESCRIPTION
**Pull request by SimonSapin**
This is a subset of Servo that takes relatively less time to compile and does not use unstable Rust features.

### CODE REVIEW

**Comment by SimonSapin** [comment]
CC @aturon @metajack @jonathandturner

**Comment by aturon** [comment]
Awesome, thanks @SimonSapin!

@alexcrichton, see any issue with this?

**Comment by alexcrichton** [comment]
Thanks yeah! Looking into this to make sure it can work. Right now `cargotest` runs on the `x86_64-gnu-aux` builder where the [last successful run](https://travis-ci.org/rust-lang/rust/builds/275784477) clocked in at 1h51m. Locally it took my computer 208s to compile stylo_tests/selectors in the Servo repository (not accounting for download times) and 140s for the webrender repo. I normally multiply by 3-ish for travis's less parallelism as well as using a debug compiler.

Along those lines I'm a little worried that this is going to push us over the 2 hour "soft limit". I think along those lines to land this PR we should allocate a new builder rather than tack on an existing one. We've got some good headroom with capacity on Travis and seeing how this is indeed directly in Mozilla's interests (the organization footing the Travis bill currently) I think it's fine to just go ahead and do this.

@SimonSapin to do this, can you...

* Copy `src/ci/docker/x86_64-gnu-aux` to `src/ci/docker/x86_64-gnu-cargotest`
* Change [this line](https://github.com/rust-lang/rust/blob/fd4bef54abafe6d93ec3c87498de696da6ef5819/src/ci/docker/x86_64-gnu-aux/Dockerfile#L21) of the `Dockerfile` in `x86_64-gnu-cargotest` to instead look like [this line](https://github.com/rust-lang/rust/blob/fd4bef54abafe6d93ec3c87498de696da6ef5819/src/ci/docker/x86_64-gnu-distcheck/Dockerfile#L22), namely `../x.py test src/tools/cargotest`. That'll make this "the builder for cargotset"
* Copy [this section](https://github.com/rust-lang/rust/blob/fd4bef54abafe6d93ec3c87498de696da6ef5819/appveyor.yml#L22-L25) of appveyor.yml, deleting `RUST_CHECK_TARGET` and adding a `SCRIPT` environment variable [like this](https://github.com/rust-lang/rust/blob/fd4bef54abafe6d93ec3c87498de696da6ef5819/appveyor.yml#L58) which also does `./x.py test src/tools/cargotest`.
* Delete [this line](https://github.com/rust-lang/rust/blob/fd4bef54abafe6d93ec3c87498de696da6ef5819/src/bootstrap/mk/Makefile.in#L55) to ensure the aux builder today doesn't continue to do double-testing of cargotest.

That should give us tons of headroom for expanding cargotest after that!

**Comment by SimonSapin** [comment]
@alexcrichton Done, and added a line in `.travis.yml`. I don’t know how to test that last commit, though.

**Comment by alexcrichton** [comment]
@bors: r+

Oh that's ok, that's what we have bors for!

**Comment by alexcrichton** [comment]
@bors: rollup- r-

one bug is that appveyor.yml doesn't haev `./x.py test`

another is;

```
/cargo/git/checkouts/angle-017278ddf8240375/c598aaf/include/EGL/eglplatform.h:118:22: fatal error: X11/Xlib.h: No such file or directory
```

**Comment by SimonSapin** [comment]
> appveyor.yml doesn't have ./x.py test

I don’t understand what that means

> ```
> EGL/eglplatform.h:118:22: fatal error: X11/Xlib.h: No such file or directory
> ```

I’ve added `libgl1-mesa-dev`, `llvm-dev`, and `libedit-dev` to the list of packages to install in `x86_64-gnu-cargotest/Dockerfile`, based on WebRender’s `.travis.yml`.

@alexcrichton, is there some "try" mode to make a full CI run without landing?

**Comment by alexcrichton** [comment]
The appveyor.yml contains:

```
SCRIPT: python x.py src/tools/cargotest
```

there's a missing `test` there

> is there some "try" mode to make a full CI run without landing?

Yes, you can execute this locally via:

```
./src/ci/docker/run.sh x86_64-gnu-cargotest
```

**Comment by SimonSapin** [comment]
Fixed `appveyor.toml`.

As to running the docker script locally I got to the point where it looks like this:

```
…
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building LLVM for x86_64-unknown-linux-gnu
running: "cmake" "/checkout/src/llvm" "-DLLVM_ENABLE_ASSERTIONS=ON" "-DLLVM_TARGETS_TO_BUILD=X86;ARM;AArch64;Mips;PowerPC;SystemZ;JSBackend;MSP430;Sparc;NVPTX;Hexagon" "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=" "-DLLVM_INCLUDE_EXAMPLES=OFF" "-DLLVM_INCLUDE_TESTS=OFF" "-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_ENABLE_ZLIB=OFF" "-DWITH_POLLY=OFF" "-DLLVM_ENABLE_TERMINFO=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=8" "-DLLVM_TARGET_ARCH=x86_64" "-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu" "-DLLVM_LINK_LLVM_DYLIB=ON" "-DCMAKE_C_COMPILER=sccache" "-DCMAKE_C_COMPILER_ARG1=cc" "-DCMAKE_CXX_COMPILER=sccache" "-DCMAKE_CXX_COMPILER_ARG1=c++" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_INSTALL_PREFIX=/checkout/obj/build/x86_64-unknown-linux-gnu/llvm" "-DCMAKE_BUILD_TYPE=Release"
```

With no further output or error message, and `run.sh` exits without an error code.

**Comment by alexcrichton** [comment]
What version of docker do you have locally? I believe to work we need the `--init` argument which was added relatively recently. 

You can also test on Travis if you'd prefer by editing `.travis.yml` and editing the `if: branch = auto` condition on the relevant builder

**Comment by SimonSapin** [comment]
I installed Docker from Ubuntu packages. It did complain about `unknown flag: --init` so I removed that flag and hoped for the best 😀. I’ll try with Travis.

**Comment by SimonSapin** [comment]
https://travis-ci.org/rust-lang/rust/jobs/276901620

**Comment by alexcrichton** [comment]
```
[00:49:40] --- stderr

[00:49:40] configure: error: 

[00:49:40] *** expat is required. or try to use --enable-libxml2

[00:49:40] make: *** [/checkout/obj/build/ct/webrender/target/debug/build/servo-fontconfig-sys-41d9b2a793d1c36f/out/Makefile] Error 1

[00:49:40] thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f",

[00:49:40]                             "makefile.cargo"]).status().unwrap().success()', /cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.3/build.rs:17:4

[00:49:40] note: Run with `RUST_BACKTRACE=1` for a backtrace.

[00:49:40] 

[00:49:40] warning: build failed, waiting for other jobs to finish...

[00:50:03] error: build failed

[00:50:03] thread 'main' panicked at 'tests failed for https://github.com/servo/webrender', /checkout/src/tools/cargotest/main.rs:100:8
```

**Comment by alexcrichton** [comment]
ping @SimonSapin, just want to make sure this doesn't fall off your radar

**Comment by SimonSapin** [comment]
It hasn’t but I’m working on other things at the moment, I’ll revisit this later.

(The fontconfig crate depends on expand and freetype crates, so it’s surprising that it would also require them installed system-wide. Something weird is going on and need investigating.)

**Comment by SimonSapin** [comment]
(I’m starting to look into this again.)

**Comment by SimonSapin** [comment]
After rebasing on master, linking rustc fails because on undefined references to some LLVM symbols when running `src/ci/docker/run.sh x86_64-gnu-cargotest` on my machine. @alexcrichton, have you seen something like this before?

```rust
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
```
[…]
```
   Compiling rustc-main v0.0.0 (file:///checkout/src/rustc)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc-31e1e2eb3a71e8f7.0.o" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc-31e1e2eb3a71e8f7" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc-31e1e2eb3a71e8f7.crate.allocator.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/miniz-sys-6b9a65a8140d8aac/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-9d4b42f8bfd68568/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_driver-7399a4bf5cc2a128" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_lint-5989bff8feadb233" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_passes-71813d5c349bf63c" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_privacy-e1b8d6337b053271" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_save_analysis-7b9db60fc6a55969" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_typeck-8bd28308a1024d4a" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_resolve-c1d0a33f30b63cca" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_borrowck-1a641e198846d7f9" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_mir-2a9f74f901e1935c" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_const_eval-6591b2a3e7f9c048" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_trans-59de2bcce71bd518" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_trans_utils-3bb86a3a86885b0f" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_llvm-1b5f5219ea59ee1a" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_incremental-77629d19d2d0a2ee" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_allocator-2a7589f5f8e8c830" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_plugin-66c47c6a82c18fe2" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_metadata-c994a02a2d471e17" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "syntax_ext-ffcef533ba0ef0ee" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "proc_macro-67fe591cd225efd9" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc-c16406e28e09d976" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "test-f20b0e766996f216" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_const_math-0ffecb5d3362e259" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_back-0b0a6d2135017d8c" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "graphviz-3f6c9f81fbad88e3" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "fmt_macros-966dbf4a19b78e7f" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "arena-ff61296ad4c6212e" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "syntax-46cff030193f255b" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_errors-3783ad33542e1cc7" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "syntax_pos-c99b8537f54d245b" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_data_structures-b0ff83b193b6c4a6" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "term-e48ed7afe4c02e5a" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "serialize-635f0dcf1328d6ed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_cratesio_shim-b4dd9d3b648414ff" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-l" "rustc_platform_intrinsics-e55d0b1c403215b3" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-738f6cf24d6c4e57" "-Wl,-Bstatic" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-218ced6707441be6.rlib" "-Wl,-Bdynamic" "-l" "rt" "-l" "dl" "-l" "pthread" "-l" "m" "-l" "stdc++" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util" "-Wl,-rpath,$ORIGIN/../lib"
  = note: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::TargetRegistry::lookupTarget(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
          /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::DiagnosticInfoOptimizationBase::getMsg[abi:cxx11]() const'
          /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::GlobalValue::getGlobalIdentifier[abi:cxx11]() const'
          /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::report_fatal_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
          /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::sys::getProcessTriple[abi:cxx11]()'
          /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::ModulePass::createPrinterPass(llvm::raw_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
          /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_llvm-1b5f5219ea59ee1a.so: undefined reference to `llvm::Triple::normalize[abi:cxx11](llvm::StringRef)'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `rustc-main`.

Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name rustc /checkout/src/rustc/rustc.rs --error-format json --crate-type bin --emit=dep-info,link -C opt-level=2 --cfg feature="jemalloc" --cfg feature="llvm" --cfg feature="rustc_back" --cfg feature="rustc_driver" -C metadata=31e1e2eb3a71e8f7 -C extra-filename=-31e1e2eb3a71e8f7 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps --extern rustc_back=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_back-0b0a6d2135017d8c.so --extern rustc_driver=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-7399a4bf5cc2a128.so -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/miniz-sys-6b9a65a8140d8aac/out -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-9d4b42f8bfd68568/out -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/lib` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--locked" "--features" " jemalloc llvm" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', /checkout/src/bootstrap/compile.rs:873:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/cargotest
Build completed unsuccessfully in 0:07:28
```

**Comment by SimonSapin** [comment]
Never mind, removing the `obj` dir seems to have fixed that.

**Comment by SimonSapin** [comment]
I got a green Travis build with the new `x86_64-gnu-cargotest` job enabled: https://travis-ci.org/rust-lang/rust/builds/291551489, then removed the commit that temporarily enabled it for PRs. r? @alexcrichton 

----

I ended up adding enough APT packages to install inside the container to make WebRender build. Some of those *should* be unnecessary if we configure the `servo-fontconfig-sys`’s crate build script to tell it where to find freetype compiled by the `servo-freetype-sys` crate, but I decided not to block this PR on that.)

**Comment by alexcrichton** [comment]
@bors: r+

Looks great!

**Comment by SimonSapin** [comment]
The `stylo_tests` crate (an executable, for the purpose of `cargo test`) fails to link on Windows because of `error LNK2019: unresolved external symbol` for many symbols declared with `extern "C" {…}` FFI and normally defined in Gecko, which is not available here. No code recursively using these symbols is called in that crate, I suspect that on Linux and OS X their declarations are garbage-collected before the linker tries to resolve them.

This problem likely also exists upstream, Servo’s CI doesn’t actually run these tests on Windows (it only compiles the static library they depend on).

**Comment by SimonSapin** [comment]
Err, Servo CI even only runs (and compiles) these tests on Linux.

**Comment by alexcrichton** [comment]
@SimonSapin AFAIK there's no "easy" way to turn off these linker errors unfortunately :(

If you'd like though, the test can be disabled in cargotest on Windows?

**Comment by SimonSapin** [comment]
I’m working on a Servo-side work-around so that we don’t need to pile up more per-test config in `cargotest`.

**Comment by SimonSapin** [comment]
Updated with https://github.com/servo/servo/pull/19003.

**Pull request merged**
