### PR TITLE
Create the Unstable Book

### PR DESCRIPTION
**Pull request by steveklabnik**
Part of https://github.com/rust-lang/rust/issues/39588

This isn't done yet. To do:

- [x] import the nightly book contents here
- [x] possibly write some more chapters

This will _not_ be done before it lands; that's part of the whole unstable thing.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Okay, this is good to go. I think we should merge and then write more chapters; it's a neat way for people to contribute!

I'd like to hear @rust-lang/docs 's thoughts on this.

**Comment by steveklabnik** [comment]
Blocked on https://github.com/rust-lang/rust/pull/39976

**Comment by steveklabnik** [comment]
This and https://github.com/rust-lang/rust/pull/39855 are inter-twined since they reference each other. Let's land https://github.com/rust-lang/rust/pull/39855 first.

**Comment by alexcrichton** [comment]
@steveklabnik r=me on the technicals w/ rustbuild and such, I'll leave it up to you to run by @rust-lang/docs on the content

**Comment by steveklabnik** [comment]
Now that https://github.com/rust-lang/rust/pull/39855 is r+'d I've rebased this on top of it, and fixed things up.

r? @frewsxcv

**Comment by steveklabnik** [comment]
Yay! the preceding one passed. I've rebased those commits out.

There seems to be no opposition to landing this, and I'd like to before it gets out of date, so

@bors: r=alexcrichton p=1

**Comment by alexcrichton** [comment]
@bors: retry

appveyor somehow missed this PR?

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged #39003

**Comment by steveklabnik** [comment]
@bors: p=11

this should have landed by now due to spurious failures but it still hasn't, I am unlikely to be able to monitor it tomorrow

**Pull request merged**
