### PR TITLE
Fix issue #20427

### PR DESCRIPTION
**Pull request by petrochenkov**
Names of structs, enums, traits, type aliases and type parameters (i.e. all identifiers that can be used as full paths in type position) are not allowed to match the names of primitive types.
See #20427 for more information.

This is a minor [breaking-change]

### CODE REVIEW

**Comment by petrochenkov** [comment]
duplicate error code E0316, will fix today

**Comment by petrochenkov** [comment]
Fixed.

**Comment by petrochenkov** [comment]
>error: could not write output to ...: No space left on device

o_O
I guess one more retry won't help?

**Comment by aturon** [comment]
I think one of the bots ran out of space and @brson has since cleaned it up.

@bors: retry

**Pull request merged**
