### PR TITLE
Report all lints, even if other errors already occurred.

### PR DESCRIPTION
**Pull request by oli-obk**
This reduces surprises of the "I fixed all the errors, now I'm getting new ones"-kind

r? @ghost

### CODE REVIEW

**Comment by oli-obk** [comment]
Okay... not sure why I ran perf at all 😃 it's not like perf benchmarks emit errors 🤦

**Comment by matthiaskrgr** [comment]
Well it kind makes sense to have some warning/error related benchmarks (perhaps even clippy lints :paperclip:  ? )
I have seen code where rustc would print a couple of initial errors, and then "freeze" for a couple of seconds (4-10?) just to not print any further errors which always seemed a bit weird :upside_down_face:

**Comment by oli-obk** [comment]
r? compiler

Will bless the test later today

**Comment by lcnr** [comment]
how likely is it that we report lints which are invalid because of a previous error? Currently slightly overwhelmed with my other reviews, so

r? compiler

**Comment by oli-obk** [comment]
> how likely is it that we report lints which are invalid because of a previous error?

We should fix those lints by checking for error types or errored typeck in case that happens. I found no obviously wrong cases in the changed diagnostics

**Comment by cjgillot** [comment]
Type checking errors still early-exit because of the `?` on `rustc_hir_analysis::check_crate` a few lines above.
Removing all the short-circuits in that function open floodgates of a larger magnitude.

**Comment by compiler-errors** [comment]
@oli-obk what's the status on this? do you want me to review it, or is does it need reworking? does it need an FCP? :thinking:

**Comment by oli-obk** [comment]
I guess I could rebase it and then compiler FCP it. Not sure it needs an FCP, i'll bring it up in the T-compiler triage

**Comment by wesleywiser** [comment]
I think either an FCP or MCP would be fine 🙂

**Review by jyn514 — APPROVED** [review]
I think this is a good idea and would second an MCP.

**Comment by apiraino** [comment]
switching review flag to note that an MCP would be fine in this case ([Zulip mention](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-04-20/near/351351241))

@rustbot author

**Comment by JohnCSimon** [comment]
@oli-obk 
ping from triage - can you post your status on this PR? There hasn't been an update in a few months, and I see a few merge conflicts Thanks!

**Comment by WaffleLapkin** [comment]
@JohnCSimon Oli is currently on leave, I think they'll continue working on this once they are back in January =)

**Comment by oli-obk** [comment]
The MCP has not been approved and has concerns that can only be resolved by a larger discussion (RFC?) about whether we want to report all lints and errors upfront, or do it in a phased system like we do now.

**Pull request closed without merging**
