### PR TITLE
Refactor code around LocalCrateReader.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by arielb1** [comment]
Tidy failure:
```

**Comment by Ms2ger** [comment]
Will fix.

**Comment by Ms2ger** [comment]
Fixed

**Comment by frewsxcv** [comment]
From Travis:

```
src/librustdoc/test.rs:108:47: 108:51 error: mismatched types [E0308]
src/librustdoc/test.rs:108     let map = hir_map::map_crate(&mut forest, defs);
                                                                         ^~~~
src/librustdoc/test.rs:108:47: 108:51 help: run `rustc --explain E0308` to see a detailed explanation
src/librustdoc/test.rs:108:47: 108:51 note: expected type `rustc::hir::map::Definitions`
src/librustdoc/test.rs:108:47: 108:51 note:    found type `&std::cell::RefCell<rustc::hir::map::Definitions>`
error: aborting due to previous error
```

**Comment by Ms2ger** [comment]
Fixed

**Pull request merged**
