### PR TITLE
trans: pad const structs to aligned size

### LINKED ISSUE #37222: Beta segfault regression
Running this code in either release or debug mode will yield a segfault:

```rust
#[derive(Debug)]
pub struct Binding {
    action: Action,
    mode: u32,
}

#[derive(Debug)]
pub enum Action {
    Esc(&'static str),
    Paste,
    Char(char)
}

static V_BINDINGS: &'static [Binding] = &[
    Binding { action: Action::Paste, mode: 0 },
    Binding { action: Action::Char('v'), mode: 1 },
];

fn main() {
    println!("{:?}", V_BINDINGS);
}
```

It looks like this also runs successfully on stable, just failing on beta/nightly

cc @jwilm

### PR DESCRIPTION
**Pull request by TimNN**
Fixes #37222.

I'm not sure if that is the _correct_ way to fix this, but it _does_ work.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for digging into that issue and putting a patch together @TimNN!

**Comment by eddyb** [comment]
@bors r-

Don't want to keep the long form in. cc @camlorn who changed that code recently.

**Comment by nikomatsakis** [comment]
Discussed in @rust-lang/compiler meeting, marking as beta-accepted. But it's got to merge first I guess. =)

**Comment by eddyb** [comment]
Relevant commit: https://github.com/rust-lang/rust/commit/f16068e577a916122ff1f24719aad2b80e40c975#diff-3dc76d318c3b3ca3bab97ea19a5dd685L1287 - `st.size` was aligned, but was replaced with the unaligned size, now `min_size` (I failed to see @camlorn's mistake during review).

*However*, this can't be backported to beta directly, because [the file there](https://github.com/rust-lang/rust/blob/85ca935b3f0faf6cc689f42821827a75280589ad/src/librustc_trans/adt.rs#L790-L793) is *just after* that original change, with `build_const_struct` not even having access to the right alignment.

**Comment by TimNN** [comment]
```
rustc: x86_64-pc-windows-gnu/stage2/test/stdtest-x86_64-pc-windows-gnu.exe
run: x86_64-pc-windows-gnu/stage2/test/stdtest-x86_64-pc-windows-gnu.exe

running 756 tests

command timed out: 1200 seconds without output, attempting to kill
program finished with exit code 1
elapsedTime=2063.338000
```

**Comment by arielb1** [comment]
- timeout (cc @alexcrichton)

@bors retry

**Comment by alexcrichton** [comment]
Looks like another instance of https://github.com/rust-lang/rust/issues/33361. Unfortunately no idea what that is.

**Pull request merged**
