### PR TITLE
Rollup of 3 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #112260 (Improve document of `unsafe_code` lint)
 - #112429 ([rustdoc] List matching impls on type aliases)
 - #112442 (Deduplicate identical region constraints in new solver)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=112260,112429,112442)

### CODE REVIEW

**Comment by lqd** [comment]
Regressions are on doc builds, which look expected from https://github.com/rust-lang/rust/pull/112429

**Comment by GuillaumeGomez** [comment]
Confirmed. We forgot to run perf-check beforehand...

**Comment by lqd** [comment]
Great, thank you.

@rustbot label: +perf-regression-triaged

**Pull request merged**
