### PR TITLE
Lambda expressions honor no struct literal restriction

### LINKED ISSUE #43412: "No Struct Literal" restriction should be applied to lambda function body
Currently `if || S {} {}` is parsed as `if (|| S {}) {}`. I think it should be parsed as `if (|| S) {} {}`, to be consistent with handling of other similar "open" binary and prefix expressions (lambdas can be viewed as a form of a prefix expression).

Consider these expressions:

```Rust
fn main() {
    if -S {};
    if 0 == -S {};
    if 0 == S {};
    if || S {} {};
    if 0 == || S {} {};
}
```

They are parsed as

```Rust
fn main() {
    if (-S) {};
    if (0 == -S) {};
    if (0 == S) {};
    if (|| S {}) {};
    if (0 == || S {}) {};
}
```

[ast json](https://gist.github.com/matklad/5d7d7b6412408cfe715f621b0241127e)

The last two cases seem to be different from others and wrong. @eddyb on IRC suggested that this behavior could have been introduced accidentally during transition from lambdas with blocks as bodies to lambdas with arbitrary expressions as bodies. 

If this is a bug, fixing it can render some previously valid programs invalid, but this seems rater unlikely, as bare lambdas rarely end up in conditionals. It is possible though:

```Rust
struct S {}
struct E;
impl<T> PartialEq<T> for E { 
    fn eq(&self, _: &T) -> bool { true }
}

fn main() {
    if E == || S {} {}
}
```

### PR DESCRIPTION
**Pull request by matklad**
This is a fix for #43412 if we decide that it is indeed a bug :) 

closes #43412

### CODE REVIEW

**Comment by eddyb** [comment]
@alexcrichton Sure, but #43412 needs a compiler (or maybe even lang team) decision first.

**Comment by shepmaster** [comment]
@nikomatsakis ping! This has been idle for over two weeks, but is pending a team decision. I've also pinged Niko on IRC.

**Comment by eddyb** [comment]
@bors r+

We decided to just accept this and back it out if any regressions are observed.

**Comment by nikomatsakis** [comment]
We discussed briefly in the @rust-lang/compiler meeting (though these sorts of minor grammar questions are often tasked to @rust-lang/lang). Anyway @eddyb and I at least agree with @matklad that this behavior seems like a bug.

**Pull request merged**
