### PR TITLE
lint/ctypes: fix `()` return type checks

### LINKED ISSUE #113436: nightly/beta regression: fnptrs with types containing `()` is warned to be not FFI-safe, while it is before
### Code

```Rust
#![deny(improper_ctypes_definitions)]

#[repr(C)]
pub struct Wrap<T>(u8, T);

pub extern "C" fn f() -> Wrap<()> { todo!() } // This does not warn.

const _: extern "C" fn() -> Wrap<()> = f; // This warns.
```

### Current output

```Shell
error: `extern` fn uses type `()`, which is not FFI-safe
 --> src/lib.rs:8:10
  |
8 | const _: extern "C" fn() -> Wrap<()> = f; // This warns.
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
  |
  = help: consider using a struct instead
  = note: tuples have unspecified layout
note: the lint level is defined here
 --> src/lib.rs:1:9
  |
1 | #![deny(improper_ctypes_definitions)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Desired output

```Shell
<no errors or warnings>
```

### Rationale and extra context

The function itself `extern "C" fn f() -> Wrap<()>` is considered FFI-safe and does not trigger the warning (https://github.com/rust-lang/rust/pull/72890). Its function pointer should also be allowed, to be consistent. 

### Other cases

Discovered on CI https://github.com/oxalica/async-ffi/actions/runs/5450150255/jobs/9915116819#step:4:37

The original code has several more levels of indirection, but is also considered FFI-safe before.

<details><summary>Extracted original code</summary>

```Rust
#![deny(improper_ctypes_definitions)]
use std::marker::PhantomData;

pub type FfiFuture<T> = BorrowingFfiFuture<'static, T>;

#[repr(transparent)]
pub struct BorrowingFfiFuture<'a, T>(LocalBorrowingFfiFuture<'a, T>);

// Does not matter here, but is repr(C).
#[repr(C)]
struct FfiContext(u8);

#[repr(C)]
pub struct LocalBorrowingFfiFuture<'a, T> {
    fut_ptr: *mut (),
    poll_fn: unsafe extern "C" fn(fut_ptr: *mut (), context_ptr: *mut FfiContext) -> FfiPoll<T>,
    drop_fn: unsafe extern "C" fn(*mut ()),
    _marker: PhantomData<&'a ()>,
}

#[repr(C, u8)]
pub enum FfiPoll<T> {
    Ready(T),
    Pending,
    Panicked,
}

pub extern "C" fn f() -> FfiFuture<()> { todo!() }
const _: extern "C" fn() -> FfiFuture<()> = f;
```

</details>

### Anything else?

According to CI logs, the warning occurs since rust 1.72.0-nightly (0ab38e95b 2023-07-03). Probably caused by #108611. cc @davidtwco

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #113436.

`()` is normally FFI-unsafe, but is FFI-safe when used as a return type. It is also desirable that a transparent newtype for `()` is FFI-safe when used as a return type.

In order to support this, when a type was deemed FFI-unsafe, because of a `()` type, and was used in return type - then the type was considered  FFI-safe. However, this was the wrong approach - it didn't check that the `()` was part of a transparent newtype! The consequence of this is that the presence of a `()` type in a more complex return type would make it the entire type be considered safe (as long as the `()` type was the first that the lint found) - which is obviously incorrect.

Instead, this logic is removed, and after [consultation with t-lang](https://github.com/rust-lang/rust/issues/113436#issuecomment-1640756721), I've fixed the bugs and inconsistencies and  made `()` FFI-safe within types.

I also refactor a function, but that's not too exciting.

### CODE REVIEW

**Comment by davidtwco** [comment]
Probably needs a crater run, quite confident this is correct, but it doubles down on a regression.

**Comment by lukas-code** [comment]
Why is this considered ffi-safe:
```rust
#[repr(C)]
pub struct Foo {
    a: u8,
    b: core::marker::PhantomData<()>,
}
```

... but this is not:
```rust
#[repr(C)]
pub struct Foo {
    a: u8,
    b: (),
}
```

Aren't they both guaranteed to have the same layout as this C struct?
```c
struct Foo {
    uint8_t a;
};
```

**Comment by davidtwco** [comment]
See https://github.com/rust-lang/rust/issues/113436#issuecomment-1626003559 for some thoughts on this - [this patch](https://gist.github.com/davidtwco/9ce3cb7c498d1fbc8a224cdd7f8c472b) will change the behaviour to fix this, if that's what we decide we want.

**Comment by davidtwco** [comment]
I've asked for some feedback [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/improper-types.20lint.20question) about which direction to go here.

**Comment by davidtwco** [comment]
This should now be ready for review.

**Comment by oli-obk** [comment]
@craterbot check

**Comment by davidtwco** [comment]
All of these seem unrelated to the changes in this PR, I think the crater run is okay :)

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-07-27/near/379176855)

@rustbot label +beta-accepted

**Pull request merged**
