### PR TITLE
test(patterns): add patterns feature tests to borrowck test suite

### LINKED ISSUE #67311: Extend bindings_after_at (`b1 @ Some(b2)`) tests with nested `or_patterns`
Once `#![feature(or_patterns)]` (#54883), i.e. `pat_0 | ... | pat_n` in nested positions, e.g. `Some(Ok(a) | Err(b))` have progressed sufficiently in their implementation, e.g. when the MIR building implementation is done, we should extend the test suite for `#![feature(bindings_after_at)]` (#65490), e.g. `b1 @ Some(b2)`, to exercise the combination of these two features. Ideally, we would also account for the combination of those two with `#![feature(slice_patterns)]` (#62254) and `#![feature(box_patterns)]` (#29641) as well to make things really air-tight.

This issue has been assigned to @thekuom via [this comment](https://github.com/rust-lang/rust/issues/67311#issuecomment-594281379).

### PR DESCRIPTION
**Pull request by thekuom**
Addresses request here: https://github.com/rust-lang/rust/pull/69690#issuecomment-595763571

Fixes https://github.com/rust-lang/rust/issues/67311.

r? @Centril

### CODE REVIEW

**Comment by thekuom** [comment]
@Centril it looks like the slice_patterns and or_patterns were already covered in the borrowck test suite

**Comment by Centril** [comment]
@thekuom Ah, sorry; it seems I was unclear. There are already a bunch of borrowck tests in `src/test/ui/pattern/bindings-after-at/` which I introduced in https://github.com/rust-lang/rust/pull/66296 and amended in https://github.com/rust-lang/rust/pull/68376/. What's missing is the combination of these features interacting together in borrowck, e.g. tests that use all 4 of nested or-patterns, bindings_after_at, slice_patterns, box_patterns all at the same time.

**Comment by thekuom** [comment]
@Centril, no worries! I will do those

**Comment by Centril** [comment]
Thanks; can you squash the commits into one? r=me with that done.

**Comment by thekuom** [comment]
Done, r=@Centril

**Pull request merged**
