### PR TITLE
Stabilize `#[cfg_eval]` and `feature(macro_attributes_in_derive_output)`

### LINKED ISSUE #81119: Tracking issue for macro attributes in `#[derive]` output
This is a tracking issue for macro attributes that can observe output of the `#[derive]` attribute.
This includes macro attributes on the same item as `#[derive]` but below it, and macro attributes on nested nodes of the item with `#[derive]`.

`#[derive]` *fully configures* its input, eagerly evaluating `cfg`s everywhere in its target, for example on fields.
Attributes expanded after the `#[derive]` will see the item in this fully configured form, but we don't want expose it to them on stable channel for now.

Example:
```rust
#[derive(Trait)]
#[my_attr] // Gated
struct S1 {
    field: [u8; 10],
}

#[derive(Trait)]
struct S2 {
    field: [u8; #[my_attr] 10], // Gated
}
```

The feature name is `macro_attributes_in_derive_output`.
The feature gate was introduced in https://github.com/rust-lang/rust/pull/79078.

### LINKED ISSUE #82679: Tracking Issue for built-in attribute macro `#[cfg_eval]`
Feature gate: `#![feature(cfg_eval)]`

This is a tracking issue for built-in attribute macro `#[cfg_eval]` that is used for eagerly expanding all `#[cfg]` and `#[cfg_attr]` attributes in its input ("fully configuring" the input).
The effect is identical to effect of `#[derive(Foo, Bar)]` which also fully configures its input before passing it to macros `Foo` and `Bar`.

### Public API

```rust
#[cfg_eval]
#[my_attr] // Receives `struct S {}` as input, the field is configured away by `#[cfg_eval]`
struct S {
    #[cfg(FALSE)]
    field: u8,
}
```

### Steps / History

- [ ] Implementation: #...
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

### PR DESCRIPTION
**Pull request by petrochenkov**
TODO: Stabilization report.

Closes https://github.com/rust-lang/rust/issues/82679
Closes https://github.com/rust-lang/rust/issues/81119
r? @Aaron1011

### CODE REVIEW

**Review by pksunkara — APPROVED** [review]
Looks good. 👍

**Comment by petrochenkov** [comment]
I'm going to delay this stabilization a bit and try two more things first:
- Double down on `cfg` and `cfg_attr` being expanded out of order, and eagerly expand them for *all* attributes implicitly, not only for `derive` and `cfg_eval`. Need to check backward compatibility and performance.
- Produce the original unconfigured item from `#[derive(Trait1, Trait2)]` while still feeding its configured version to `Trait1` and `Trait2`. Need to check for performance.

**Comment by pksunkara** [comment]
> * Double down on `cfg` and `cfg_attr` being expanded out of order, and eagerly expand them for _all_ attributes implicitly, not only for `derive` and `cfg_eval`. Need to check backward compatibility and performance.

I am not completely sure about the code and internals, would love if you could help explain a bit of why this is a blocker for stabilising this feature.

> * Produce the original unconfigured item from `#[derive(Trait1, Trait2)]` while still feeding its configured version to `Trait1` and `Trait2`. Need to check for performance.

Why do we need the original unconfigured item?

**Comment by pksunkara** [comment]
Ah, for others who are thinking the same, here's related links: https://github.com/rust-lang/rust/issues/83331, https://github.com/rust-lang/rust/pull/83354

**Comment by petrochenkov** [comment]
@pksunkara 
>would love if you could help explain a bit of why this is a blocker for stabilising this feature.

If input is eagerly fully configured for all attributes, then `#[cfg_eval]` becomes a no-op and no longer has reasons to exist.

>Why do we need the original unconfigured item?

So you can place attributes requiring the original unconfigured input after `#[derive]`.

**Comment by Aaron1011** [comment]
> Double down on cfg and cfg_attr being expanded out of order, and eagerly expand them for all attributes implicitly, not only for derive and cfg_eval. Need to check backward compatibility and performance.

One potential issue with doing this - a macro might want to do addtional processing of `#[cfg]` attributes. For example, someone could write an attribute `#[auto_doc_cfg]` which creates `#[doc(cfg)]` attributes for every `#[cfg]` attribute in the input (and copies them to any generated items).

**Comment by petrochenkov** [comment]
Yeah, not expanding cfgs eagerly gives proc macro authors a choice, so we'll probably need some kind of opt-out.
I'm considering the variant with eagerly expanding cfgs for everything because in 90+% cases doing that is the preferable choice.

**Comment by davidhewitt** [comment]
As a pyO3 maintainer the evidence downstream (in pyO3 at least) is that having cfg-stripping be opt-out would be slightly more convenient for our users, who are often first-time Rustaceans coming from Python.

That said, once we've got a mechanism in the language (whether opt-in or opt-out) then it's quite plausible with pyO3's current design to conditionally compile python bindings for Rust crates just by slapping `#[cfg_attr]` on the right parts of the original Rust source.

We would write documentation for this regardless of whether it would need to explain `#[cfg_eval]` or not, so it's not a big problem either way.

My thanks to you folks for implementing this! 🚀

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/84995.

**Comment by petrochenkov** [comment]
Blocked on #86057.

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/87220.

**Comment by petrochenkov** [comment]
>Blocked on #87220.

Actually no, looks like `#[cfg_eval]` can be stabilized independently from #87220, I've made a PR - https://github.com/rust-lang/rust/pull/87221.
So this PR can be closed.

**Pull request closed without merging**
