### PR TITLE
Stabilize Iterator::step_by

### LINKED ISSUE #27741: Tracking issue for `step_by` stabilization
Update (@SimonSapin): this is now the tracking issue for an iterator adaptor based on `Iterator::nth`:

```rust
pub trait Iterator {
    fn step_by(self, step: usize) -> StepBy<Self>
}
```

The `Step` trait used for making ranges iterators is now tracked at https://github.com/rust-lang/rust/issues/42168.

Original issue:

----

The `step_by` method makes it possible to step through ranges with arbitrary-sized steps. There are several issues that need to be addressed before we can stabilize it:
- The design/stabiliztion of the `Step` trait, which is currently a bit of a mess
- The behavior on negative steps (see [this thread](https://internals.rust-lang.org/t/step-by-on-negative-numbers/2231))
- Likely the design/stabilization of `Zero`/`One`, tracked [here](https://github.com/rust-lang/rust/issues/27739)

### PR DESCRIPTION
**Pull request by tmccombs**
Fixes #27741

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'd really like to see this feature being stabilized as well.

cc @SimonSapin

**Comment by SimonSapin** [comment]
r=me on the diff

@scottmcm Your comment at https://github.com/rust-lang/rust/issues/27741#issuecomment-385237631 is not clear to me. Are you proposing to change the semantics `Iterator::step_by`? Are you opposed to stabilizing it with the current semantics? (That is, take this PR as-is.)

**Comment by SimonSapin** [comment]
Also CC @rust-lang/libs

**Comment by scottmcm** [comment]
@SimonSapin Thanks for the ping!  I think the design process for the method defined the right semantics  -- `(1..).step_by(2)`giving `1, 3, 5, ...` makes sense to me -- so I'm in favour of stabilizing as-is.

(The comment was about implementation awkwardness -- `nth` isn't a great fit for what StepBy needs -- but I'm confident that's surmountable within the existing semantics.)

**Comment by SimonSapin** [comment]
Thanks for confirming!

@bors r+

**Pull request merged**
