### PR TITLE
Distribute libntdll.a with windows-gnu toolchains

### PR DESCRIPTION
**Pull request by ChrisDenton**
This allows the OS loader to load essential functions (e.g. read/write file) at load time instead of lazily doing so at runtime.

r? libs

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm not sure how to evaluate whether this is a good idea or not -- maybe we can reassign to someone else? It seems like a comment in the dist.rs code where we list the dll list that says something about what we should think about when extending or shrinking the list would be good.

**Comment by ChrisDenton** [comment]
In #68519 a similar change was rejected because libstd didn't use ntdll at the time. That has changed. Issue #47359 aims to audit the list but it doesn't look like it's actively maintained or been followed up on. We should probably try to clean up the list at some point, although it is possible some people are relying on specific libraries being distributed. Judging from past history, it seems we tend to accidentally break windows-gnu builds first then fix them by adding to this list when people report the errors. Which isn't great.

Feel free to reassign this PR if you'd prefer.

**Comment by Mark-Simulacrum** [comment]
OK. That seems like reasonable rationale for me to sign off here, we can figure out how to do auditing/better CI in the future. Seems like a hard problem.

@bors r+ rollup=iffy

**Comment by ehuss** [comment]
@bors retry
wasm SIGSEGV

**Comment by ehuss** [comment]
@bors retry
#108227

**Comment by mati865** [comment]
In tests:
```
foo.lib(foo.foo.91a024fd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_NtWriteFile referenced in function _ZN3std3sys7windows6handle6Handle17synchronous_write17h3ccc3ed9499bda2eE
foo.lib(foo.foo.91a024fd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_RtlNtStatusToDosError referenced in function _ZN3std3sys7windows6handle6Handle17synchronous_write17h3ccc3ed9499bda2eE
foo.lib(foo.foo.91a024fd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_NtReadFile referenced in function _ZN3std3sys7windows6handle6Handle16synchronous_read17ha507c58f21a8d842E
foo.lib(foo.foo.91a024fd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_NtCreateFile referenced in function _ZN3std3sys7windows2fs20open_link_no_reparse17h8f348f918f5e59f8E
C:\a\rust\rust\build\x86_64-pc-windows-msvc\test\run-make-fulldeps\lto-smoke-c\lto-smoke-c\bar.exe : fatal error LNK1120: 4 unresolved externals
```

**Comment by ChrisDenton** [comment]
Oh the run-make-fulldeps require adding the extra libraries...

**Pull request merged**
