### PR TITLE
[Do not merge] Rename mpsc_select feature to break its users on Crater

### PR DESCRIPTION
**Pull request by SimonSapin**
CC https://github.com/rust-lang/rust/issues/27800#issuecomment-421343907

### CODE REVIEW

**Comment by SimonSapin** [comment]
@craterbot run mode=check-only start=master#dfabe4b88509bfff1eca9060ccc9a4d28ee394e8 end=try#a02e3c13d0428e0998376a9a1ecf8055d9f0495c

**Comment by lqd** [comment]
Looks like only 2 crates would be broken by this

**Comment by SimonSapin** [comment]
Crater has found three regressions:

* In `fftw-src`, looks spurious: `process killed after not generating output for  300s`

* In `thread_isolated`, the `select!` macro is used in tests to wait on two channels. I submitted PR https://github.com/jgallagher/thread_isolated/pull/1 to replace it on waiting on a single channel with a custom two-variant enum type for messages, and cloning the sender.

* In `rust-channel-perf`, this is a benchmark measuring specifically the performance of the `select!` macro. It seems fine to let the maintainers remove that specific benchmark when the start seeing deprecation warnings or compilation errors. I’ve filed an issue https://github.com/psFried/rust-channel-perf/issues/1 to let them know.

This PR has served its purpose. Thanks to everyone who built and maintains Crater!

**Pull request closed without merging**
