### PR TITLE
Update stdarch submodule and remove special handling in cranelift codegen for some AVX and SSE2 LLVM intrinsics

### PR DESCRIPTION
**Pull request by eduardosm**
https://github.com/rust-lang/stdarch/pull/1463 reimplemented some x86 intrinsics to avoid using some x86-specific LLVM intrinsics:

* Store unaligned (`_mm*_storeu_*`) use `<*mut _>::write_unaligned` instead of `llvm.x86.*.storeu.*`.
* Shift by immediate (`_mm*_s{ll,rl,ra}i_epi*`) use `if` (srl, sll) or `min` (sra) to simulate the behaviour when the RHS is out of range. RHS is constant, so the `if`/`min` will be optimized away.

This PR updates the stdarch submodule to pull these changes and removes special handling for those LLVM intrinsics from cranelift codegen. I left gcc codegen untouched because there are some autogenerated lists.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM but not too familiar with this so will get a second pair of eyes

**Comment by bjorn3** [comment]
Tested locally. Works fine. Thanks for working on this @eduardosm!

@bors r=davidtwco,bjorn3

**Comment by klensy** [comment]
Other stdarch bump https://github.com/rust-lang/rust/pull/115617

**Comment by bjorn3** [comment]
Didn't see that one. Both update stdarch to the exact same commit and this one also removes some now unused code.

**Comment by coastalwhite** [comment]
Whoops. Didn’t see this one, should all be fine though right?

**Pull request merged**
