### PR TITLE
Make sufficiently old or low-impact compatibility lints deny-by-default

### PR DESCRIPTION
**Pull request by petrochenkov**
Tracking issues are updated/created when necessary.
Needs crater run before proceeding.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Started crater run.

**Comment by nikomatsakis** [comment]
Crater-report: https://gist.github.com/nikomatsakis/fc7c4951bc962b163395b7557e082f91

- 5782 crates tested: 3741 working / 1355 broken / 19 regressed / 5 fixed / 662 unknown.

**Comment by petrochenkov** [comment]
`deny(invalid_type_param_default)`:
rust-freqdist-0.1.4 - defaults in impls
scan-rules-0.1.3 - defaults in impls
tangle-0.4.0 - defaults in impls
hex2d-dpcext-0.0.9 - defaults in fns
rotor-carbon-0.6.0 - defaults in fns

`deny(illegal_struct_or_enum_constant_pattern)`:
elfloader32-0.0.3
elfloader-0.0.3
xhtmlchardet-1.0.0

`deny(lifetime_underscore)`:
sxd-xpath-0.2.0
zoneinfo_parse-0.1.2

`deny(inaccessible_extern_crate)`:
epoxy-0.0.2

`illegal_floating_point_constant_pattern`,
`overlapping_inherent_impls`,
`super_or_self_in_global_path`:
∅

other failures are spurious

---

Seems reasonable to deny by default everything, except for, maybe, `invalid_type_param_default`.
I'll try to send PRs to affected crates today or tomorrow.

**Comment by nikomatsakis** [comment]
@petrochenkov I made checkboxes and checked off the cases where you had sent PRs. The only one I didn't see was `rust-freqdist`, did I miss it?

**Comment by petrochenkov** [comment]
@nikomatsakis 
I didn't send PR to `rust-freqdist` because it was already fixed by the author, just unpublished.

**Comment by nikomatsakis** [comment]
Per my proposed rules in [this thread](https://internals.rust-lang.org/t/moving-forward-on-forward-compatibility-lints/4204), I move that we merge this PR, going from stage 1 to stage 2.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge 

I propose that we move this PR to stage 2: deny-by-default. There were <19 total affected crates, and all have been notified with pending PRs, except for one which was already fixed by the author.

**Comment by michaelwoerister** [comment]
@rfcbot reviewed

So the rfcbot can (and should) be used for regular PRs too, not just RFCs?

**Comment by nikomatsakis** [comment]
@michaelwoerister 

> So the rfcbot can (and should) be used for regular PRs too, not just RFCs? 

indeed -- also issues.

**Comment by nikomatsakis** [comment]
I tagged @Aatch, @bkoropoff, and @dotdash since none of them have been very active of late.

**Pull request merged**
