### PR TITLE
save-analysis: handle type defs in struct patterns

### PR DESCRIPTION
**Pull request by nrc**
r? @huonw

### CODE REVIEW

**Comment by nick29581** [comment]
rebased

ping @huonw for review

**Comment by huonw** [comment]
I'm struggling to understand the background for this case. What's a code example that this change fixes/improves?

**Comment by nick29581** [comment]
`impl Foo for i32 {}` In that case we fall into the first branch of the match, but looking up the type definition gives us `None`, this makes sure we register the fact that there is an impl of `Foo` in this case (as well as the trait reference).

**Comment by huonw** [comment]
That sounds like a case for https://github.com/rust-lang/rust/pull/22691?

**Comment by nick29581** [comment]
oh, right, sorry, got confused between the two.

The use case for this is something like:

```
struct Foo {
    a: i32,
}
type Bar = Foo;
fn baz(Bar { a }: Bar) {
}
```

Previously, this crashed in save-analysis. Now it works.

**Pull request merged**
