### PR TITLE
Move rustup to the combined installer

### PR DESCRIPTION
**Pull request by brson**
This changes rustup to use the combined installer instead of downloading both rust and cargo. Temporarily it loses the ability to not install cargo, but sometime soon I'll upgrade rust-installer to support selecting components.

It also disables verbose tarball extraction because it is very noisy with the volume of docs.

Supersedes https://github.com/rust-lang/rust/pull/19927

I've already uploaded to s3.

### CODE REVIEW

**Comment by brson** [comment]
@erickt The ability to pull from the archives will be temporarily broken during the transition to the combined installer because it has a different name.

**Comment by erickt** [comment]
@brson: no worries! it'll be way better to have this landed :)

**Comment by SiegeLord** [comment]
Just FYI, I tried the combined nightly (gotten from https://static.rust-lang.org/dist/rust-combined-nightly-x86_64-unknown-linux-gnu.tar.gz ) and those installed the HTML documentation in a directory that was not world-readable.

**Comment by nikomatsakis** [comment]
Tidy failure: line exceeds 100 characters.

**Comment by brson** [comment]
@SiegeLord presumably that directory was /usr/local/share/doc/rust? What's the documentation directory on your system, and what system is it?

**Comment by SiegeLord** [comment]
@brson No, it was the `/usr/local/share/doc/rust/html`. This was Linux.

```
$ ls -l /usr/local/share/doc/rust/
-rw-r--r--  1 root root 17426 Jan  3 09:47 COPYRIGHT
drwx------ 29 root root  4096 Jan  3 09:48 html
-rw-r--r--  1 root root 10847 Jan  3 09:47 LICENSE-APACHE
-rw-r--r--  1 root root  1071 Jan  3 09:47 LICENSE-MIT
-rw-r--r--  1 root root  4077 Jan  3 09:47 README.md
```

**Comment by brson** [comment]
@SeigeLord perhaps the problem is that the installer is installing the docs using 'cp' instead of 'install', so the files end up with the wrong permissions.

**Comment by brson** [comment]
@SiegeLord I see the same permissions problem here. I only tested in by listing the directory, not actually reading the files. Thanks for bringing it to my attention.

**Pull request merged**
