### PR TITLE
enforce WF conditions after generalizing

### LINKED ISSUE #41677: Type inference breakage on beta
This code compiles on stable, but fails on beta ([playground link](https://gist.github.com/5bdefaad62cb87e2fd2e0a4e4caf9679)):

```rust
#![allow(unused_variables, dead_code)]

use std::marker::PhantomData;

trait Handle {
    type Inner;
}

struct ResizingHandle<H>(PhantomData<H>);
impl<H> Handle for ResizingHandle<H> {
    type Inner = H;
}

struct Sender<T, H: Handle<Inner=T>>(PhantomData<H>);
struct Receiver<T, H: Handle<Inner=T>>(PhantomData<H>);

type ResizingSender<T> = Sender<T, ResizingHandle<T>>;
type ResizingReceiver<T> = Receiver<T, ResizingHandle<T>>;

impl<T, H: Handle<Inner=T>> Receiver<T, H> {
    fn new() -> Self {
        Receiver(PhantomData)
    }
}

impl<T, H: Handle<Inner=T>> Sender<T, H> {
    fn new(receiver: &Receiver<T, H>) -> Self {
        Sender(PhantomData)
    }
}

fn channel<T>(size: usize) -> (ResizingSender<T>, ResizingReceiver<T>) {
    let rx = ResizingReceiver::new();
    let tx = ResizingSender::new(&rx);
    (tx, rx)
}


fn main() {
}
```

Error message:
```
error[E0282]: type annotations needed
  --> <anon>:33:9
   |
33 |     let rx = ResizingReceiver::new();
   |         ^^
   |         |
   |         consider giving `rx` a type
   |         cannot infer type for `Receiver<_, ResizingHandle<T>>`
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Add a `WF(T')` obligation after generalizing `T` to `T'`, if `T'` contains an unconstrained type variable in a bivariant context.

Fixes #41677. 

Beta nominating -- regression.

r? @arielb1

### CODE REVIEW

**Comment by arielb1** [comment]
Got back from holidays. Had a fun week.

This looks like a rather brutal fix. As for concrete worries, I was worried that we might create wf obligations "inside" an higher-ranked binder, and that would cause trouble, but I don't think we ever do subtyping in a higher-ranked context right now?

**Comment by nikomatsakis** [comment]
> This looks like a rather brutal fix.

Brutal as in "brute force"?

> As for concrete worries, I was worried that we might create wf obligations "inside" an higher-ranked binder, and that would cause trouble, but I don't think we ever do subtyping in a higher-ranked context right now?

I don't think that would be a problem. It's not that we don't do subtyping in a higher-ranked context.  Rather, it's that we protect against skolemized regions "escaping" into instantiated type variables. If we did instantiate some type variable with something that includes skolemized regions --- or with region variables that wind up related to skolemized variables --- that would be detected during the leak-check. Since we only ever create the `WF` relations with the value from an instantiated variable, this implies that these relations cannot reference skolemized regions.

(As an aside, I am, though, actively planning how to overhaul that system right now to make it more robust, roughly in the manner that we talked about.)

**Comment by arielb1** [comment]
This is basically a hack around bivariance not being implemented properly, but let's go for it (r+ modulo conflict fix).

**Comment by brson** [comment]
Doesn't cherry-pick cleanly cc @nikomatsakis

**Pull request merged**
