### PR TITLE
Make FnDef 1-ZST in LLVM debuginfo.

### PR DESCRIPTION
**Pull request by cjgillot**
Discussed in https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/LLVM.20HEAD.20llvm.2Edbg.2Edeclare.2Falloca.20size.20mismatch

r? @nikic

### CODE REVIEW

**Comment by nikic** [comment]
MSVC generates different IR due to the special case in https://github.com/rust-lang/rust/blob/eb0f3ed59c6508a37c6598bc9762987f053993a7/compiler/rustc_codegen_ssa/src/mir/debuginfo.rs#L403, so I think this just needs ignore-msvc?

**Comment by cjgillot** [comment]
Rebased and added `ignore-msvc`.

**Pull request merged**
