### PR TITLE
Add more __future__ imports to increase compatibility with Python 3 in bootstrap

### PR DESCRIPTION
**Pull request by johnthagen**
The functionality of the  `__future__` imports are described [here](https://docs.python.org/3/library/__future__.html).

 These will help ensure the bootstrap code stays compatible with Python 3. If changes are made in the future that use absolute imports, division, or the `print` function, this will be ensure that running it under Python 2 will pass or fail the same way as Python 3.

`Option` is made a [new-style class](https://docs.python.org/2/reference/datamodel.html#new-style-and-classic-classes), so that it behaves the same way in Python 2 and 3.

The `__future__ unicode_literals` import is not used, because that can change the semantics of the code in Python 2 in unwanted ways. For more information see [this article](http://python-future.org/unicode_literals.html).

### CODE REVIEW

**Comment by johnthagen** [comment]
I'll await feedback from @aidanhs. This should not change the lower-bound of compatibility, which is still Python 2.7.

**Comment by nikomatsakis** [comment]
@bors r+

If I'm not mistaken, with the exception of "print function" (which we already depended on), all of these changes are pretty long-standing migrations in Python-land, in the sense that I remember them from my days writing Python like 10 years ago. ;)

**Comment by kennytm** [comment]
@bors retry 

* Android SDK HTTPS issue (fixed in #45193)

**Comment by nikomatsakis** [comment]
@johnthagen needs rebase

**Comment by johnthagen** [comment]
@nikomatsakis Conflicts have been resovled

**Pull request merged**
