### PR TITLE
Optimize Vec::shrink_to_fit()

### PR DESCRIPTION
**Pull request by lilyball**
Don't reallocate when capacity is already equal to length

`Vec::shrink_to_fit()` may be called on vectors that are already the
correct length. Calling out to `reallocate()` in this case is a bad idea
because there is no guarantee that `reallocate()` won't allocate a new
buffer anyway, and based on performance seen in external benchmarks, it
seems likely that it is in fact reallocating a new buffer.

Before:

```
test string::tests::bench_exact_size_shrink_to_fit         ... bench:        45 ns/iter (+/- 2)
```

After:

```
test string::tests::bench_exact_size_shrink_to_fit         ... bench:        26 ns/iter (+/- 1)
```

### CODE REVIEW

**Comment by Gankro** [comment]
How does this impact code that *actually* needs to shrink?

**Comment by Gankro** [comment]
(I imagine the overhead is negligable if not free, but am still curious)

**Comment by kballard** [comment]
@Gankro I would imagine it's negligible too. It's a single comparison, of values that are already being used anyway so no cache faults or anything like that. I would welcome some actual profiling but I doubt I can get any meaningful measurements.

**Pull request merged**
