### PR TITLE
fix NLL ICEs

### LINKED ISSUE #52992: crash: checking hyper with borrowck-migrate
````
git clone https://github.com/hyperium/hyper
cd hyper
git checkout v0.11.27
RUSTFLAGS="-Zborrowck=migrate" cargo check -j1

````

````
       Fresh nodrop v0.1.12
       Fresh cfg-if v0.1.4
       Fresh libc v0.2.42
       Fresh lazy_static v1.0.2
       Fresh scopeguard v0.3.3
       Fresh byteorder v1.2.4
       Fresh memoffset v0.2.1
       Fresh slab v0.4.0
       Fresh futures v0.1.23
       Fresh lazycell v0.6.0
       Fresh version_check v0.1.4
       Fresh scoped-tls v0.1.2
       Fresh smallvec v0.2.1
       Fresh safemem v0.2.0
       Fresh slab v0.3.0
       Fresh try-lock v0.1.0
       Fresh take v0.1.0
       Fresh language-tags v0.2.2
       Fresh percent-encoding v1.0.1
       Fresh arrayvec v0.4.7
       Fresh crossbeam-utils v0.3.2
       Fresh log v0.4.3
       Fresh iovec v0.1.2
       Fresh net2 v0.2.33
       Fresh rand v0.4.2
       Fresh num_cpus v1.8.0
       Fresh time v0.1.40
       Fresh tokio-executor v0.1.2
       Fresh tokio-service v0.1.0
       Fresh relay v0.1.1
       Fresh base64 v0.9.2
       Fresh crossbeam-epoch v0.4.3
       Fresh log v0.3.9
       Fresh want v0.0.4
       Fresh bytes v0.4.9
       Fresh mio v0.6.15
       Fresh rand v0.3.22
       Fresh futures-cpupool v0.1.8
       Fresh tokio-timer v0.2.4
       Fresh httparse v1.3.2
       Fresh crossbeam-deque v0.3.1
       Fresh tokio-io v0.1.7
       Fresh unicase v2.1.0
       Fresh tokio-threadpool v0.1.5
       Fresh tokio-reactor v0.1.2
       Fresh tokio-codec v0.1.0
       Fresh mime v0.3.8
       Fresh tokio-fs v0.1.2
       Fresh tokio-tcp v0.1.0
       Fresh tokio-udp v0.1.1
       Fresh tokio v0.1.7
       Fresh tokio-core v0.1.17
       Fresh tokio-proto v0.1.1
    Checking hyper v0.11.27 (file:///tmp/hyper)
     Running `rustc --crate-name hyper src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="server-proto"' --cfg 'feature="tokio-proto"' -C metadata=465f7886ca4a40ca -C extra-filename=-465f7886ca4a40ca --out-dir /tmp/hyper/target/debug/deps -C incremental=/tmp/hyper/target/debug/incremental -L dependency=/tmp/hyper/target/debug/deps --extern base64=/tmp/hyper/target/debug/deps/libbase64-7f888070408e9584.rmeta --extern bytes=/tmp/hyper/target/debug/deps/libbytes-926f4be38b0ef49a.rmeta --extern futures=/tmp/hyper/target/debug/deps/libfutures-3e034e8c4fadab05.rmeta --extern futures_cpupool=/tmp/hyper/target/debug/deps/libfutures_cpupool-3f3a8918cddf229d.rmeta --extern httparse=/tmp/hyper/target/debug/deps/libhttparse-7fa16ff1de6399dc.rmeta --extern iovec=/tmp/hyper/target/debug/deps/libiovec-10dda303b566010f.rmeta --extern language_tags=/tmp/hyper/target/debug/deps/liblanguage_tags-fedadc717cc3771f.rmeta --extern log=/tmp/hyper/target/debug/deps/liblog-81cb68337885c10e.rmeta --extern mime=/tmp/hyper/target/debug/deps/libmime-e6896d1a95033795.rmeta --extern net2=/tmp/hyper/target/debug/deps/libnet2-ab600f3287d3dca8.rmeta --extern percent_encoding=/tmp/hyper/target/debug/deps/libpercent_encoding-0c7a64ed7c39bd90.rmeta --extern relay=/tmp/hyper/target/debug/deps/librelay-8fa98676479e7181.rmeta --extern time=/tmp/hyper/target/debug/deps/libtime-98f6d9e519834157.rmeta --extern tokio_core=/tmp/hyper/target/debug/deps/libtokio_core-825ab810c0bbc020.rmeta --extern tokio_io=/tmp/hyper/target/debug/deps/libtokio_io-25fbcf6adf05ccf3.rmeta --extern tokio_proto=/tmp/hyper/target/debug/deps/libtokio_proto-22632b982b7a70d1.rmeta --extern tokio_service=/tmp/hyper/target/debug/deps/libtokio_service-bcd12f7a5bd6b195.rmeta --extern unicase=/tmp/hyper/target/debug/deps/libunicase-8cddf57e734c9821.rmeta --extern want=/tmp/hyper/target/debug/deps/libwant-fc7ca82b1f72e647.rmeta -Zborrowck=migrate`
thread 'main' panicked at 'scrape_region_constraints: incoming region obligations = [
    (
        NodeId(
            4242
        ),
        RegionObligation(sub_region=ReStatic, sup_type=B)
    )
]', librustc/traits/query/type_op/custom.rs:85:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   8: <rustc::traits::query::type_op::custom::CustomTypeOp<F, G> as rustc::traits::query::type_op::TypeOp<'gcx, 'tcx>>::fully_perform
   9: rustc_mir::borrow_check::nll::type_check::type_check
  10: rustc_mir::borrow_check::nll::compute_regions
  11: rustc_mir::borrow_check::do_mir_borrowck
  12: rustc::ty::context::tls::with_related_context
  13: rustc::infer::InferCtxtBuilder::enter
  14: rustc_mir::borrow_check::mir_borrowck
  15: rustc::ty::query::__query_compute::mir_borrowck
  16: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_borrowck<'tcx>>::compute
  17: rustc::ty::context::tls::with_context
  18: rustc::dep_graph::graph::DepGraph::with_task_impl
  19: rustc::ty::context::tls::with_related_context
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  22: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  23: rustc_mir::borrow_check::nll::type_check::TypeChecker::check_stmt
  24: rustc_mir::borrow_check::nll::type_check::TypeChecker::typeck_mir
  25: rustc_mir::borrow_check::nll::type_check::type_check
  26: rustc_mir::borrow_check::nll::compute_regions
  27: rustc_mir::borrow_check::do_mir_borrowck
  28: rustc::ty::context::tls::with_related_context
  29: rustc::infer::InferCtxtBuilder::enter
  30: rustc_mir::borrow_check::mir_borrowck
  31: rustc::ty::query::__query_compute::mir_borrowck
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_borrowck<'tcx>>::compute
  33: rustc::ty::context::tls::with_context
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::ty::context::tls::with_related_context
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  38: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  39: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners
  40: rustc::util::common::time
  41: rustc::ty::context::tls::enter_context
  42: <std::thread::local::LocalKey<T>>::with
  43: rustc::ty::context::TyCtxt::create_and_enter
  44: rustc_driver::driver::compile_input
  45: rustc_driver::run_compiler_with_pool
  46: <scoped_tls::ScopedKey<T>>::set
  47: <scoped_tls::ScopedKey<T>>::set
  48: syntax::with_globals
  49: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  50: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  51: rustc_driver::run
  52: rustc_driver::main
  53: std::rt::lang_start::{{closure}}
  54: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  55: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  56: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  57: main
  58: __libc_start_main
  59: <unknown>
query stack during panic:
#0 [mir_borrowck] processing `<client::Client<C, B>>::send_request::{{closure}}`
#1 [mir_borrowck] processing `<client::Client<C, B>>::send_request`
end of query stack
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.29.0-nightly (97085f9fb 2018-08-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -Z borrowck=migrate -C debuginfo=2 -C incremental --crate-type lib
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `hyper`.
Caused by:
  process didn't exit successfully: `rustc --crate-name hyper src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="server-proto"' --cfg 'feature="tokio-proto"' -C metadata=465f7886ca4a40ca -C extra-filename=-465f7886ca4a40ca --out-dir /tmp/hyper/target/debug/deps -C incremental=/tmp/hyper/target/debug/incremental -L dependency=/tmp/hyper/target/debug/deps --extern base64=/tmp/hyper/target/debug/deps/libbase64-7f888070408e9584.rmeta --extern bytes=/tmp/hyper/target/debug/deps/libbytes-926f4be38b0ef49a.rmeta --extern futures=/tmp/hyper/target/debug/deps/libfutures-3e034e8c4fadab05.rmeta --extern futures_cpupool=/tmp/hyper/target/debug/deps/libfutures_cpupool-3f3a8918cddf229d.rmeta --extern httparse=/tmp/hyper/target/debug/deps/libhttparse-7fa16ff1de6399dc.rmeta --extern iovec=/tmp/hyper/target/debug/deps/libiovec-10dda303b566010f.rmeta --extern language_tags=/tmp/hyper/target/debug/deps/liblanguage_tags-fedadc717cc3771f.rmeta --extern log=/tmp/hyper/target/debug/deps/liblog-81cb68337885c10e.rmeta --extern mime=/tmp/hyper/target/debug/deps/libmime-e6896d1a95033795.rmeta --extern net2=/tmp/hyper/target/debug/deps/libnet2-ab600f3287d3dca8.rmeta --extern percent_encoding=/tmp/hyper/target/debug/deps/libpercent_encoding-0c7a64ed7c39bd90.rmeta --extern relay=/tmp/hyper/target/debug/deps/librelay-8fa98676479e7181.rmeta --extern time=/tmp/hyper/target/debug/deps/libtime-98f6d9e519834157.rmeta --extern tokio_core=/tmp/hyper/target/debug/deps/libtokio_core-825ab810c0bbc020.rmeta --extern tokio_io=/tmp/hyper/target/debug/deps/libtokio_io-25fbcf6adf05ccf3.rmeta --extern tokio_proto=/tmp/hyper/target/debug/deps/libtokio_proto-22632b982b7a70d1.rmeta
--extern tokio_service=/tmp/hyper/target/debug/deps/libtokio_service-bcd12f7a5bd6b195.rmeta --extern unicase=/tmp/hyper/target/debug/deps/libunicase-8cddf57e734c9821.rmeta --extern want=/tmp/hyper/target/debug/deps/libwant-fc7ca82b1f72e647.rmeta -Zborrowck=migrate` (exit code: 101)
````
````rustc 1.29.0-nightly (97085f9fb 2018-08-01)````

### LINKED ISSUE #53568: [nll] unresolved inference variable in outlives: _#3t
The latest crater run reported some ICE errors that look very similar to #52057 (but are potentially different).  This crate is small but pretty involved with its wrappers over hyper, tokio, and futures, resulting in a lot of associated types and bounds, and some of those 'static bounds might have a weird interaction with the NLL typeck, `impl Trait`, and maybe `delay_span_bug`. 

@lqd minimized it to only one such error, but note that the real code has 5 or 6 of them, so it would be good to verify any potential fix on the `hyper-stub` crate itself rather than just this minimized repro. [Playground](https://play.rust-lang.org/?gist=7fea72155d73e0220eeccd7b9d1ac357&version=nightly&mode=debug&edition=2015).

<details>
<summary>List of crate failures</summary>

 - [hyper-stub-0.1.0](https://crates.io/crates/hyper-stub/0.1.0): [log](https://crater-reports.s3.amazonaws.com/pr-53426/a5d98b025f62ace80fe9d2a15781f900fc42515e-alt/reg/hyper-stub-0.1.0/log.txt)
 - [dekellum.body-image.11424ec2c7d4363c5f5f1cf6eb1e2d3fec7dc2ec](https://github.com/dekellum/body-image/tree/11424ec2c7d4363c5f5f1cf6eb1e2d3fec7dc2ec): [log](https://crater-reports.s3.amazonaws.com/pr-53426/a5d98b025f62ace80fe9d2a15781f900fc42515e-alt/gh/dekellum.body-image/log.txt)

</details>

### LINKED ISSUE #53680: itertool's chunk iterator causes a compiler panic when mapping with non-lexical lifetimes
This is the minimum example I was able to get it down to:
```
#![feature(nll)]

extern crate itertools;
use itertools::Itertools;

fn main() {
    b"abcdefg".iter().chunks(2).into_iter().map(|a| 1);
}
```
When try to compile this the compiler says
```
thread 'main' panicked at 'scrape_region_constraints: incoming region obligations = [
    (
        NodeId(
            20
        ),
        RegionObligation(sub_region='_#1r, sup_type=&u8)
    )
]', librustc/traits/query/type_op/custom.rs:85:5
```

It is specifically an issue with map and non-lexical lifetimes as removing either of them doesn't cause the bug.

## Meta
My current rust version is 
```
rustc 1.30.0-nightly (63d66494a 2018-08-23)
binary: rustc
commit-hash: 63d66494aff57411bfec1dd2a3a5f1af900feab6
commit-date: 2018-08-23
host: x86_64-unknown-linux-gnu
release: 1.30.0-nightly
LLVM version: 7.0
```
But this happened on every other system I tried it on, including [play.rust-lang.org](https://play.rust-lang.org/?gist=835fb875e77ce433a724bbc6b8890a09&version=nightly&mode=debug&edition=2015)

### PR DESCRIPTION
**Pull request by nikomatsakis**
Custom type-ops reuse some of the query machinery -- but while query results are canonicalized after they are constructed, custom type ops are not, and hence we have to resolve the type variables to avoid an ICE here.

Also, use the type-op machinery for implied outlives bounds.

Fixes #53568 
Fixes #52992 
Fixes #53680

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@TimNN jfyi, the output extracted was less than helpful :)

```
[00:45:38] ....................................................................................................
[00:45:40] ...................................................................................................i
[00:45:43] ...................................................................i................................
[00:45:46] ....................................................................................................
[00:45:49] .....................................F.F............................................................
[00:45:54] ....................................................................................................
[00:45:58] ....................................................................................................
[00:46:00] ....................................................................................................
[00:46:03] ....................................................................................................
```

No clue why...

**Comment by nikomatsakis** [comment]
@TimNN 

> No clue why...

the problem turned out to be that this was a case of UI tests that were supposed to fail...not failing. (Because I was missing a `// compile-pass` annotation.)

**Comment by nikomatsakis** [comment]
OK, I've changed my mind. I think this PR is ready to land. I would still like to do some refactoring -- in particular, I am not happy with the way that the trait queries + type-op setup is so *distinct*, but I think that is best left to a separate PR.

**Comment by illicitonion** [comment]
I was about to file a dupe of https://github.com/rust-lang/rust/issues/53680 and have verified that this PR fixes my ICE - thanks for putting it together!

**Pull request merged**
