### PR TITLE
[beta] Prepare Rust 1.84.0

### PR DESCRIPTION
**Pull request by BoxyUwU**
r? @ghost

### CODE REVIEW

**Comment by ehuss** [comment]
I have a strong suspicion that the error is caused by https://github.com/rust-lang/rust/pull/131365. cc @heiseish

**Comment by Mark-Simulacrum** [comment]
That PR should be safe to revert, though I won't get a chance to push that tonight (but consider a simple revert r=me'd).

**Comment by heiseish** [comment]
Apologies please feel free to revert yeah. I will take a look at it again sometimes later.

**Comment by klensy** [comment]
> The job **`dist-i686-msvc`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/12020593304/job/33509509713) [(plain)](https://github.com/rust-lang-ci/rust/commit/0c28a817158a108cedd9f6e1747dfb72a5d4edcb/checks/33509509713/logs)
> Click to see the possible cause of the failure (guessed by this bot)
> 
> ```
> RustFmtGroup.wxs
> RustAnalyzerGroup.wxs
> AnalysisGroup.wxs
> building `msi` installer with "D:/a/rust/rust/wix\\bin/light.exe"
> D:\a\rust\rust\build\tmp\dist\combined-tarball\rust.wxs(306) : error LGHT0094 : Unresolved reference to symbol 'WixComponentGroup:MiriGroup' in section 'Product:*'.
> Command has failed. Rerun with -v to see more details.
>   local time: Tue, Nov 26, 2024  1:13:44 AM
>   network time: Tue, 26 Nov 2024 01:13:44 GMT
> ##[error]Process completed with exit code 1.
> Post job cleanup.
> ```

There is a probable fix for this in https://github.com/rust-lang/rust/pull/133033/commits/d404da04f1e7a5f59099519bcc379885815025e0

**Comment by BoxyUwU** [comment]
test failing from #132993 cc @jieyouxu

**Comment by jieyouxu** [comment]
> test failing from #132993 cc @jieyouxu

can you use https://github.com/rust-lang/rust/pull/133504 to disable the test during post-opt-dist?

**Comment by BoxyUwU** [comment]
I guess the only way to find out if that helps is to just

@bors r+ rollup=never p=10

**Comment by jieyouxu** [comment]
(Delete the test to not block beta bump if needed and discard the ignore change)

**Pull request merged**
