### PR TITLE
librustdoc: set cap-lints=allow when compiling documentation

### PR DESCRIPTION
**Pull request by Ryman**
This sets the `cap-lints` setting to 'allow' for all doc compilations. There's precedent for this as rustdoc [already whitelists unstable code](https://github.com/rust-lang/rust/blob/master/src/librustdoc/core.rs#L112) when compiling documentation, with the expectation being that a regular compile will complain about any problems. I think the same justification applies here.

Problem case in the wild: https://github.com/laumann/compiletest-rs/pull/28

r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
r? @alexcrichton

Not entirely familiar with the complete reasoning behind capping ar Allow, deferring to Alex.

**Comment by huonw** [comment]
@Manishearth https://github.com/rust-lang/rfcs/blob/master/text/1193-cap-lints.md#motivation

**Comment by Manishearth** [comment]
I meant the unstable features stuff. I'm not sure if we should be capping at allow or warn here, and I'm not sure if this should even be a part of rustdoc (not cargo).

Happy with the code changes, though, r=me if nobody has an issue with allow over warn and it being in rustdoc.

**Comment by steveklabnik** [comment]
So, one thing is that when docs run without lints, we get into situations like https://github.com/rust-lang/rust/pull/29523 . I would have loved to have seen a "hey, this feature isn't needed" warning, so that we wouldn't have had the bug.

**Comment by Manishearth** [comment]
So I guess we want to cap in docs but not doctests?

**Comment by Ryman** [comment]
@steveklabnik This change only applies to running `rustdoc` on rust files without the test flag, there's three more codepaths: testing rust files, compiling markdown files, testing markdown files. :sweat_smile: 

Just confirmed that `make-check-docs` still fires warnings from tests in rust files.

**Comment by steveklabnik** [comment]
@Ryman ah! ignore my objection then, sorry :)

**Comment by alexcrichton** [comment]
@steveklabnik oh we actually [have support for that](https://github.com/rust-lang/rust/blob/c143ae7764a4bedc61c6c9d86803af940f813a58/src/libstd/lib.rs#L214-L215), it's just not turned on by default.

I also think that this is fine, seems kinda odd for a documentation generator to be warning you about various parts of your code! Thanks @Ryman!

@bors: r+ b1ef5302d5456add7b3314cd871d23a2dc45afb5

**Pull request merged**
