### PR TITLE
[stable-1.77] cargo backport

### PR DESCRIPTION
**Pull request by weihanglo**
1 commits in 3fe68eabf93cbf3772bbcad09a9206c783e2de3f..e52e360061cacbbeac79f7f1215a7a90b6f08442
2024-02-29 00:16:03 +0000 to 2024-03-26 17:54:36 +0000
- [stable-1.77] Do not strip debuginfo by default for MSVC (rust-lang/cargo#13654)

r? ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
cc @Kobzol 

https://github.com/rust-lang/rust/issues/122857

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=100

Kicking off stable build, targeting Thursday for the point release. I'll try to throw together a blog post but if someone has time please ping me on Zulip and tell me so I can avoid making the time.

**Comment by ehuss** [comment]
@bors retry

#97669 armhf-gnu issue

**Comment by workingjubilee** [comment]
Was this also backported to beta?

**Comment by workingjubilee** [comment]
Yes it was, as #123117.

**Pull request merged**
