### PR TITLE
Fix performance backlash of #74762

### PR DESCRIPTION
**Pull request by ssomers**
A small mistake had a measurable effect on performance. According to benchmarks, this turns #74762 into a petty speedup.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by lcnr** [comment]
Looks like `rust-timer` didn't pick this up

@rust-timer build 86d42ef9e3d641b4c17c285378d84d332de83d0b

**Comment by JohnTitor** [comment]
Hm, it doesn't seem to recover the regression fully?

**Comment by ssomers** [comment]
I have no idea what is being benchmarked here, and since how long, but here is another commit reverting everything that could have an effect.

**Comment by mati865** [comment]
`rust-timer` measures performance of rustc compiling various crates. It doesn't run any of the benchmarks from the code.
Perf results in this case mean the changes from this PR made some code marginally easier to compile (it takes less work). Performance of Rust itself doesn't seem affected.

**Comment by ssomers** [comment]
All I'm saying is that if #74762 caused this, then #68770 must have been much worse. Or in other words, if #74762 caused this, I can easily supply a 1% performance change for the better, simply stripping down a copy of `remove_kv_tracking` that snubs drain_filter. And I'm not saying that this code duplication is bad, because there is more to be gained if these two are no longer chained together.

**Comment by ssomers** [comment]
The [original regression](https://perf.rust-lang.org/compare.html?start=e8876ae2c11f341565059b900eeae1254a9accf1&end=a99ae95c722d4dc8d1eef09aaa4e72d50d496e75&stat=instructions%3Au) in #75060 was alarmed about **helloworld-check** and neither of the commits here change that back. So can I conclude that #74762 was not the culprit? Then in my shallow view, the only other suspect is #75010.

**Comment by Mark-Simulacrum** [comment]
Looking at the regression, it seems to be down to slightly more queries being run -- all metadata decoding. I'm not sure, but it does seem not implausible that the performance was affected by an extra struct or something odd like that. It's such a minor regression that I'm not too worried about tracking it down precisely -- https://github.com/rust-lang/rust/pull/75010 seems like a plausible cause too.

**Comment by ssomers** [comment]
Meanwhile, my small mistake fixed in the first commit here is superseded by #75257, so I think we're done here.

**Pull request closed without merging**
