### PR TITLE
MIR visitor: Don't treat debuginfo field access as a use of the struct

### LINKED ISSUE #77454: Field accesses in debuginfo are treated as real uses of the base local
MIR may contain debuginfo like this after inlining:

```
    scope 1 {
        debug x => _3;                   // in scope 1 at $DIR/inline-closure-captures.rs:11:9: 11:10
        scope 2 {
            debug _q => _10;             // in scope 2 at $DIR/inline-closure-captures.rs:11:14: 11:16
            debug q => (*((*_6).0: &i32)); // in scope 2 at $DIR/inline-closure-captures.rs:10:23: 10:24
            debug t => (*((*_6).1: &T)); // in scope 2 at $DIR/inline-closure-captures.rs:10:17: 10:18
            let mut _9: T;               // in scope 2 at $DIR/inline-closure-captures.rs:12:5: 12:9
        }
    }
```

Here, the field access `(*_6).0` is treated like a use of the `_6` local in MIR visitors (using `PlaceContext::NonMutatingUse`), even though it is not an actual use of `_6`.

Instead, it should be using `PlaceContext::NonUse(NonUseContext::VarDebugInfo)`.

### PR DESCRIPTION
**Pull request by camelid**
Fixes #77454.

r? @jonas-schievink

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Thanks! Please add a comment, and remove any existing special cases that are made obsolete by this fix.

**Comment by camelid** [comment]
> remove any existing special cases that are made obsolete by this fix

What special cases are you referring to?

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust/blob/603ab5bd6e0ffefafa7411cd8bd23a6ca82bcff0/compiler/rustc_mir/src/transform/validate.rs#L201-L205

etc.

**Comment by camelid** [comment]
I added a comment and removed the special case that you pointed out. I'm not sure what others there are though. If you know of more, I am happy to change them, but I don't have enough experience with MIR to know where they might be. Also it's probably fine to change them later since this change shouldn't mess up the special-casing; it just allows getting rid of the special-casing.

**Pull request merged**
