### PR TITLE
std::alloc fix layout size limit with threadsanitizer.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
oh absolutely, just covering the default behavior "effortlessly" user wise :) let's see what other people say.

**Comment by Nilstrieb** [comment]
what about alloc_zeroed? also do you know why this option isn't the default? that seems like a tsan bug..

**Comment by devnexen** [comment]
well this is a common flag to detect OOMs and let the process crash explicitly.

**Comment by Nilstrieb** [comment]
right, it makes sense to have it, but crashing TSan instead of returning null when the layout is too large sounds like a TSan bug.

**Comment by devnexen** [comment]
> right, it makes sense to have it, but crashing TSan instead of returning null when the layout is too large sounds like a TSan bug.

I think it s intentional though, also it s not just tsan but also asan/msan/... crash too default limit threshold might differ with each other.

**Comment by Nilstrieb** [comment]
yeah, this is definitely intentional behavior on the TSan side, there's a test for it: `src/llvm-project/compiler-rt/test/sanitizer_common/TestCases/max_allocation_size.cpp`
given that TSan sees it as a feature to crash on OOM instead of returning null, I'd prefer to avoid papering over this here in std. I do think this is pretty weird behavior though

**Pull request closed without merging**
