### PR TITLE
Update llvm-project

### LINKED ISSUE #98167: Code generation error on AVR using u16::to_be()
I tried this code on AVR (arduino Uno = atmega328p) with opt-level="z":

```rust
let pixels = [0xf800u16, 0x07e0, 0x001f];
let mut buf = [0u16; 3];
{
    let mut i = 0;
    for pixel in pixels.map(u16::to_be) {
        buf[i] = pixel;
        i += 1;
    }
    let _ = uwriteln!(serial, "debug buf {:?} mapped", buf);
}
```

I expected to see this happen: 
`debug buf [248, 57351, 7936] mapped`

Instead, this happened: 
`debug buf [0, 57568, 7967] mapped`

An alternate code that emits the correct output is

```rust
    {
        for (i, pixel) in pixels.iter().enumerate() {
            buf[i] = pixel.to_be();
        }
        let _ = uwriteln!(serial, "debug buf {:?} enumerate", buf);
    }
```

This compiler error is corrupting the pixel stream transmitted via SPI to an ST7789 display from an Arduino Uno.  What appears to be happening is that instead of the bytes being swapped, the LSB is being copied to the MSB.  I do not have the expertise to decompile and examine the assembly code.

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (88860d547 2022-05-09)
binary: rustc
commit-hash: 88860d5474a32f507dde8fba8df35fd2064f11b9
commit-date: 2022-05-09
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1

```

The malfunction also occurs with `cargo +nightly`.

`rustc +nightly --version --verbose`
```
rustc 1.63.0-nightly (b31f9cc22 2022-06-15)
binary: rustc
commit-hash: b31f9cc22bcd720b37ddf927afe378108a5b9a54
commit-date: 2022-06-15
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

The full code can be cloned from https://github.com/mutantbob/rust-avr-code-generation-bug

### PR DESCRIPTION
**Pull request by Patryk27**
Closes https://github.com/rust-lang/rust/issues/98167 🙂

### CODE REVIEW

**Comment by slanterns** [comment]
duplicate with https://github.com/rust-lang/rust/pull/98285/ ?

**Comment by Patryk27** [comment]
Kinda, that one doesn't contain the recent commit from yesterday that fixes the AVR bug I've linked 😅 (since it uses llvm-project from two days ago)

I guess I'll just rebase my PR after https://github.com/rust-lang/rust/pull/98285 gets merged.

**Comment by Patryk27** [comment]
Ready!

**Comment by nikic** [comment]
As this hasn't been merged yet, would you mind updating this PR to the latest commit? I've pushed two more backports.

**Comment by Patryk27** [comment]
Sure, I’ll take a look in two hours or so 🙂

**Comment by Patryk27** [comment]
kk, done!

**Comment by nikic** [comment]
Thanks!

@bors r+ rollup=never

**Comment by nikic** [comment]
Perf result seems to be noise, it seems to be the opposite of the results on the previous commit: https://perf.rust-lang.org/compare.html?start=f342bea9d19f14616c6559312552e6d0ee529cfd&end=5b8cf49c51833ee5d27ae2e8e179337dbb9f14d7&stat=instructions:u

**Comment by nikic** [comment]
Beta nominating as fix for the P-critical miscompile in https://github.com/rust-lang/rust/issues/98568. The update also includes a fix for an AVR-only miscompile (https://github.com/rust-lang/rust/issues/98167), as well as an assertion failure (https://github.com/rust-lang/rust/issues/98076).

Submodule diff: https://github.com/rust-lang/llvm-project/compare/d1ddc34c4b23468f6d2bf553084834b104e16dde...8b6b5014fdad3a750f7242a6bfdcad83619498d4

**Comment by workingjubilee** [comment]
Thank you, @Patryk27 and @nikic!

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-07-07/near/288815441)

@rustbot label +beta-accepted

**Comment by Mark-Simulacrum** [comment]
@nikic is it a problem if we backport by rolling forward to the latest commit here on beta? (https://github.com/rust-lang/llvm-project/compare/c9e2e89ed3aa5a3be77143aa0c86906b4138374a...8b6b5014fdad3a750f7242a6bfdcad83619498d4)

Otherwise can create a targeted backport with a helper branch, but want to make sure there's no accidental mistakes missing a dependency on a previous commit here.

**Comment by nikic** [comment]
@Mark-Simulacrum I think we need a separate backport branch here, because the LLVM fork has been rebased in the meantime, and I'm not confident that it will build on beta (specifically FreeBSD). And no, I don't think there are any relevant dependency commits.

**Comment by Mark-Simulacrum** [comment]
OK, sounds good. I'll look into doing that.

**Comment by Mark-Simulacrum** [comment]
Included in #99098, branch rustc/14.0-2022-07-09.

**Comment by Mark-Simulacrum** [comment]
Dropping regression label, agree that the results are likely noise. See https://github.com/rust-lang/rust/pull/98925#issuecomment-1181719021 for some graphs.

**Pull request merged**
