### PR TITLE
make `super_relate_consts` use trait objects

### PR DESCRIPTION
**Pull request by lcnr**
`super_relate_consts` generates quite a lot of llvm-ir considering that it is still fairly rarely used, so let's try using trait objects for that.

### CODE REVIEW

**Comment by jackh726** [comment]
Perf is basically neutral and this just increases complexity. I'm not sure the tradeoff is worth it.

**Comment by lcnr** [comment]
It looks like a small improvement to me, but as @jackh726 mentioned it does worsen the experience of working on it in the future so I am going ahead and close this for now

**Pull request closed without merging**
