### PR TITLE
Emit the enum range assumption if the range only contains one element

### LINKED ISSUE #82871: Array bounds check not elided when indexing with ZST enum
I tried this code:

```rust
#[repr(C)]
pub enum E {
    A, 
}

pub fn index(x: &[u32; 3], ind: E) -> u32{
    x[ind as usize]
}
```

I expected to see this happen: no bounds check

Instead, this happened (with `-C opt-level=3`)

```asm
example::index:
        push    rax
        mov     rax, rdi
        mov     edi, esi
        cmp     esi, 2
        ja      .LBB0_2
        mov     eax, dword ptr [rax + 4*rdi]
        pop     rcx
        ret
.LBB0_2:
        lea     rdx, [rip + .L__unnamed_1]
        mov     esi, 3
        call    qword ptr [rip + core::panicking::panic_bounds_check@GOTPCREL]
        ud2
```

However adding more variants to the enum makes the bound check go away:

```rust
#[repr(C)]
pub enum E {
    A,
    B,
}

pub fn index(x: &[u32; 3], ind: E) -> u32{
    x[ind as usize]
}
```

generates:

```asm
example::index:
        mov     eax, esi
        mov     eax, dword ptr [rdi + 4*rax]
        ret
```

Here's a godbolt link to play around further: https://rust.godbolt.org/z/dK9e1z
The MIR of the two cases is identical, but the llvm IR in ZST case is lacking `@llvm.assume`, which I assume (heh!) leads to the bounds check being preserved. (However i don't actually understand LLVM, I'm just reading the diff...)

### Meta
rustc 1.50.0

This sounds *very closely related* to #13926, but I'm not actually sure if it is. Please reroute as appropriate.

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/82871

### CODE REVIEW

**Comment by the8472** [comment]
Naive question, but couldn't it be turned into a constant instead if there can only be a single value?

**Comment by nikic** [comment]
This needs a codegen test to make sure the desired optimization takes place. The `src/test/codegen/enum-bounds-check*.rs` tests can serve as inspiration.

**Comment by hi-rustin** [comment]
Now it's look like:

```asm
	.section	__TEXT,__text,regular,pure_instructions
	.macosx_version_min 10, 7
	.globl	_index
	.p2align	4, 0x90
_index:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	movl	(%rdi), %eax
	popq	%rbp
	retq
	.cfi_endproc

.subsections_via_symbols

```

**Comment by hi-rustin** [comment]
> This needs a codegen test to make sure the desired optimization takes place. The `src/test/codegen/enum-bounds-check*.rs` tests can serve as inspiration.

I don't actually know how to assert that test.

**Comment by hi-rustin** [comment]
I think it's ready for review.

**Comment by lcnr** [comment]
this does seem fine to me, would it be possible to instead emit a constant if `start == end`? it feels a bit weird to me to use range assumptions for this.

**Comment by nikic** [comment]
> this does seem fine to me, would it be possible to instead emit a constant if `start == end`? it feels a bit weird to me to use range assumptions for this.

That would be possible, but maybe not worth the bother to special case it? LLVM will end up replacing the value with a constant based on the assumption, so I don't think it will make much of a difference.

**Comment by lcnr** [comment]
in this case

@bors r+

**Pull request merged**
