### PR TITLE
MIR: change "lvalue" terminology to "place".

### PR DESCRIPTION
**Pull request by eddyb**
As pointed out elsewhere, "lvalue" vs "rvalue" is a misleading/obscure distinction and several other choices have been proposed, the one I prefer being "place" vs "value".

This PR only touches the "lvalue" side, and only in MIR-related code, as it's already a lot and could rot.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Giving high priority because bitrot probability is high.

**Comment by kennytm** [comment]
oops sorry

@bors r=nikomatsakis p=15

**Pull request merged**
