### PR TITLE
doc: Address issue of crates not being explained when introduced.

### PR DESCRIPTION
**Pull request by flukejones**
Ref issue [30825](https://github.com/rust-lang/rust/issues/30825)

This commit should suffice to add a concise introduction to the concept of crates. 
My only worry, is that it is maybe too concise; but, the book seems to be written with the understanding that the new Rust user is coming from another language, and so will understand what a Library or Code Package is.

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you!

**Comment by steveklabnik** [comment]
@bors: r-

actually, there's a weird commit in here that doesn't do anything, would you mind rebasing this first?

**Comment by Luke-Nukem** [comment]
@steveklabnik I also changed "it's" to "it is", which makes that sentence easier to read.

If you do prefer, I'll rebase and remove it. Otherwise it seems to be a good change. I'd just forgotten to comment on it

**Comment by steveklabnik** [comment]
It's a good change! The merge commit is just the issue.

**Comment by Luke-Nukem** [comment]
Errr... Can you point me to some info please? I've pulled latest changes and merged, then rebased, but there doesn't appear to be any change.
I'm not really sure what I'm looking for, or what you're seeing :)

**Comment by steveklabnik** [comment]
It's this one: 

2016-01-14-200621_402x41_scrot


and now there's a new one:

2016-01-14-200641_698x59_scrot

`git rebase` should eliminate these kinds of things....

**Comment by steveklabnik** [comment]
wooot! thanks for struggling with this

@bors: r+ rollup

**Comment by Luke-Nukem** [comment]
Got it! I even learnt a few new tricks :grinning:

**Pull request merged**
