### PR TITLE
Crater: closure size profile build

### PR DESCRIPTION
**Pull request by arora-aman**
PR to do a test crater run on just cargo

- `mode=build-only`
- `list:cargo`
- `rustflags={-Zprofile-closures}`
- `p=1` (as suggest [here](https://rust-lang.zulipchat.com/#narrow/stream/189812-t-compiler.2Fwg-rfc-2229/topic/measure.20closure.20sizes/near/245254453) high priority).

### CODE REVIEW

**Comment by arora-aman** [comment]
Can someone start a crater run with paramters:


- `mode=build-only`
- `list:cargo`
- `rustflags={-Zprofile-closures}`
- `p=1` (as suggest [here](https://rust-lang.zulipchat.com/#narrow/stream/189812-t-compiler.2Fwg-rfc-2229/topic/measure.20closure.20sizes/near/245254453) high priority).

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=build-only crates=list:cargo start=master#e9a387d6cf5961a7f2dcb671da3147bd413355c4 end=try#8a4c071f46be56484e9723bd8f1e5eea08177963+rustflags={-Zprofile-closures} p=1

**Comment by Mark-Simulacrum** [comment]
We passed `{-Zprofile-closures}` as the rustflag argument which is clearly bogus...

@craterbot run mode=build-only crates=list:cargo start=master#e9a387d6cf5961a7f2dcb671da3147bd413355c4 end=try#8a4c071f46be56484e9723bd8f1e5eea08177963+rustflags=-Zprofile-closures p=1

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=build-only crates=list:cargo,serde,libc start=master#e9a387d6cf5961a7f2dcb671da3147bd413355c4 end=try#b37eec28c619960bccdd1d5c1c502ce4dcf83564+rustflags=-Zprofile-closures p=1

**Comment by Mark-Simulacrum** [comment]
So it looks like it worked:

* https://crater-reports.s3.amazonaws.com/pr-87066-2/try%23b37eec28c619960bccdd1d5c1c502ce4dcf83564%2Brustflags=-Zprofile-closures/reg/serde-1.0.126/log.txt
* https://crater-reports.s3.amazonaws.com/pr-87066-2/try%23b37eec28c619960bccdd1d5c1c502ce4dcf83564%2Brustflags=-Zprofile-closures/reg/libc-0.2.98/log.txt

Happy to queue a check run across the full set of crates or take a different course of action, please let me know.

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=build-only crates=top-10000 start=master#d5c88c22807925c189328ef9d923c5d2b11a95b8 end=try#d5c88c22807925c189328ef9d923c5d2b11a95b8+rustflags=-Zprofile-closures

Starting another run to collect some data; we'll likely want to abort and re-start this once some PRs land on master, but I figure this might actually finish before then and doesn't seem bad to get it going just to have some additional preliminary results. It'll also give us an opportunity to write up the necessary scripts to parse out the logs and analyze the data across a couple thousand crates (which we don't yet have the data for anywhere).

**Pull request closed without merging**
