### PR TITLE
Update RLS and Rustfmt

### PR DESCRIPTION
**Pull request by nrc**
Fixes broken RLS tests/build

r? @alexcrichton

### CODE REVIEW

**Comment by nrc** [comment]
cc @Mark-Simulacrum

**Comment by alexcrichton** [comment]
Tests passed and we need a fixed nightly, I'm going to merge this manually

* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6770)
* [Travis](https://travis-ci.org/rust-lang/rust/builds/357244435)

**Pull request merged**
