### PR TITLE
Recover `impl<T ?Sized>` correctly

### LINKED ISSUE #111327: type parameters followed by `?` are recovered incorrectly
### Code

```Rust
trait Trait {}

impl<T ?Sized> Trait for T {}
```

### Current output

```Shell
error: invalid `?` in type
 --> src/lib.rs:3:8
  |
3 | impl<T ?Sized> Trait for T {}
  |        ^ `?` is only allowed on expressions, not types
  |
help: if you meant to express that the type might not contain a value, use the `Option` wrapper type
  |
3 | impl<Option<T >Sized> Trait for T {}
  |      +++++++  ~

error: expected one of `>` or `as`, found `Sized`
 --> src/lib.rs:3:9
  |
3 | impl<T ?Sized> Trait for T {}
  |         ^^^^^ expected one of `>` or `as`
```

### Desired output

```Shell
It should suggest adding a `:` and not emit the two current errors, explaining that you forgot to write `:` before the `?Sized` bound.
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #111327

r? @Nilstrieb but you can re-roll

Alternatively, happy to close this if we're okay with just saying "sorry #111327 is just a poor side-effect of parser ambiguity" 🤷

### CODE REVIEW

**Comment by Nilstrieb** [comment]
In my opinion every time a parser error special case causes a worse error than the generic "expected, found" error that's a bug and should be fixed. I will take a look later.

**Review by Noratrieb — COMMENTED** [review]
I don't exactly love the change but I think it's an improvement that, when added with enough comments clarifying that it's not necessary (ideally also inside the `matches!`), is an okay addition to the parser.

**Review by Noratrieb — APPROVED** [review]
r=me

**Pull request merged**
