### PR TITLE
Update openbsd libc

### PR DESCRIPTION
**Pull request by semarie**
The following PR updates libc version to latest commits for correctly support openbsd.
It corrects several points in rustc to be compatible with libc changes.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 8a631b83dc5ca30389b909a8889bbe8b7e8988fa

Thanks!

**Comment by alexcrichton** [comment]
Ah note that the libc update in #30601 I think is the most recent, so the libc update here is likely no longer necessary

**Comment by semarie** [comment]
I have removed the commit for updating libc, so it should be good now.

**Pull request merged**
