### PR TITLE
Fix overlap detection of `usize`/`isize` range patterns

### PR DESCRIPTION
**Pull request by Nadrieril**
`usize` and `isize` are a bit of a special case in the match usefulness algorithm, because the range of values they contain depends on the platform. Specifically, we don't want `0..usize::MAX` to count as an exhaustive match (see also [`precise_pointer_size_matching`](https://github.com/rust-lang/rust/issues/56354)). The way this was initially implemented is by treating those ranges like float ranges, i.e. with limited cleverness. This means we didn't catch the following as unreachable:
```rust
match 0usize {
    0..10 => {},
    10..20 => {},
    5..15 => {}, // oops, should be detected as unreachable
    _ => {},
}
```
This PRs fixes this oversight. Now the only difference between `usize` and `u64` range patterns is in what ranges count as exhaustive.

r? @varkor
@rustbot label +A-exhaustiveness-checking

### CODE REVIEW

**Comment by Nadrieril** [comment]
I also measured a perf improvement, so I'd like a perf run to confirm it.

**Review by varkor — APPROVED** [review]

**Comment by Nadrieril** [comment]
I'm surprised by the perf gain on `match-stress-enum`, particularly since it was caused by the first commit. My only guess it that `split` got simple enough to be inlined. I'm worried I'll lose that gain if I touch anything ^^

**Comment by varkor** [comment]
Thanks!

@bors r+ rollup=never

**Pull request merged**
