### PR TITLE
[experiment] Use new solver in MIR validator subtyping checks

### PR DESCRIPTION
**Pull request by compiler-errors**
Just to see what breaks in crater...

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
No longer ICEs in stage 1

@bors try

**Comment by compiler-errors** [comment]
Still fails in typenum :broken_heart:

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by lqd** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-112365/retry-regressed-list.txt

**Comment by compiler-errors** [comment]
return to life :skull:

@bors try

**Comment by compiler-errors** [comment]
lol

@craterbot check

**Pull request closed without merging**
