### PR TITLE
Assorted diagnostics improvements

### LINKED ISSUE #27288: User facing messages MUST NOT say "illegal".
`error: illegal width `4` for float literal, valid widths are 32 and 64`

`error: illegal recursive enum type; wrap the inner value in a box to make it representable [E0072]`

You can almost always replace `illegal` with `invalid`. Since we're (probably) not breaking the law writing Rust code, we shouldn't use terms about breaking the law.

It seems like this language mostly comes from early specifications, and it causes problems. If panic reasons are visible to end users - users who don't understand it's not illegal under the penal code - they may think they've done something really bad. It's also probably not a good word to see for people for whom English is not their first language.

So please, let's get all the occurrences of "illegal" in error messages out of the language.

### PR DESCRIPTION
**Pull request by nagisa**
Improves diagnostics in various locations, namely:
- A few error messages that orignally were a mix of an error message and suggestion how to fix it have been split up into two messages: an error and help/hint.
- Never report “illegal”. Fixes https://github.com/rust-lang/rust/issues/27288

### CODE REVIEW

**Comment by Havvy** [comment]
r-

I want the style guide updated too. I'm gonna send a PR against nagisa's branch for that.

**Comment by Havvy** [comment]
Actually, scratch that r-. There's no document to place such guidelines on.

**Comment by nagisa** [comment]
Rebased.

**Comment by pnkfelix** [comment]
okay the other two commits are largely about this terminological shift from using the word "illegal" to using the word "invalid"

I myself do not particularly mind, but I'm going to double check with some other team members to make sure everyone agrees that this is the right direction for us to go in.

**Pull request merged**
