### PR TITLE
make this example more obvious

### LINKED ISSUE #31334: The Rust Programming Language - 4.6 Loops issue
The following code will not build or run.  The issue is that 'lines' is never defined in this section of the book. 

```
for (linenumber, line) in lines.enumerate() {
    println!("{}: {}", linenumber, line);
}
Outputs:

0: Content of line one
1: Content of line two
2: Content of line three
3: Content of line four
```

Rust is my first attempt to contribute to someone else's project so if I am not using these issues correctly please let me know and I will cease adding them as I go through the book.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #31334

This is just a quicker fix for this issue; since I'm working on the next draft of the book, I don't want to put a huuuge amount of work into improving it here.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Should the string in use be updated to match what's output below in the "Outputs" section?

**Comment by steveklabnik** [comment]
gah, good call. updated.

**Pull request merged**
