### PR TITLE
Improve BufRead docs and examples regarding UTF-8 issues 

### PR DESCRIPTION
**Pull request by mqudsi**
The `BufRead` docs were rather unusually quiet about how to detect UTF-8 errors in the methods that convert `&[u8]` to `&str` (primarily `read_line()` and `lines()`) and didn't offer any clarity on what state a UTF-8 parse error leaves the underlying `BufRead` impl with.

I've also reworked some of the pointer chasing in the docs (lines says to look at read_line which says to look at read_until) without eliminating it altogether.

The patch is organized as a series of commits that each target specific shortcomings in case there's a desire to part-and-parcel this patch series.

**The only question I would have for a reviewer is if I'm committing an egregious sin by directly mentioning `InvalidData` as the error returned on UTF-8 parse failure. Is there a way to document it and talk about it without that implying there's a stability guarantee (in case it's not already guaranteed that *this* is the error that is returned)? My concern is that `InvalidData` doesn't let you actually recover the current line (no access to its bytes and no indication of UTF-8 valid until position), unlike `std::str::Utf8Error` - but I feel like we should be able to document *something* on how to deal with UTF-8 errors via the `BufRead` interface even if what we have might some day change.**

@rustbot label +A-docs +T-libs-api

### CODE REVIEW

**Comment by mqudsi** [comment]
r? rust-lang/libs-api

**Comment by mqudsi** [comment]
r?

**Comment by jyn514** [comment]
r? rust-lang/libs-api

**Comment by m-ou-se** [comment]
(I [mentioned this Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Documenting.20BufRead.20UTF-8.20failures.20and.20recovery/near/299800441). Posting here too for completeness.)

The `read_line` function simply reads up to and including the first `\n` byte, making it equivalent to the `read_until` function with a `b'\n'` argument, except for the UTF-8 handling. It seems to me that if you want to do anything with non-UTF-8 data, `read_until` would be the right choice. Then if converting the `Vec<u8>` to a `String` or `&str` fails, you still have the original data, and the utf-8 error offset.

**Comment by m-ou-se** [comment]
I don't think we can promise much about recovering from certain errors. Some I/O errors may be permanent, while other types of I/O errors might be recoverable. I don't think we can guarantee that `InvalidData` always represents an UTF-8 error, as it is possible for the underlying `Read` implementation to return this error from a `read()` call (which might or might not be recoverable).

**Comment by mqudsi** [comment]
So the primary motivation is distinguish between a transient error and a permanent one. A line containing non-UTF-8 shouldn’t be taken as a permanent error (you can always try reading the next line) while an actual IO error is a problem. 

Eg in my case I was parsing .gitignore files where each line stands on its own. It would be incorrect to bail just because one line had invalid UTF-8 and the docs don’t talk about how to distinguish between such a transient error and a permanent one.

**Comment by jyn514** [comment]
@mqudsi it sounds like libs team doesn't want to make this guarantee, but maybe for your use case you could use Mara's suggestion of `read_until(b"\n")`? then instead of making the guarantee you can point people towards `read_until` in the docs for `read_line`.

**Comment by mqudsi** [comment]
I don't have any issues - when I realized the limitations, I switched to reading via a different method.

The problem I'm trying to address is that the UTF8-aware `BufReader` functions don't provide a means for the end user to distinguish between a content decoding error and an actual IO error. Sometimes it doesn't matter and either means the dev should abort. Sometimes it does and the dev may want to only abort on IO errors.

If the libs team prefers, I can close out this PR and open a new one with a simpler change: I can document in all the UTF-8 `BufRead`/`BufReader` functions "if you need to be able to distinguish between an error decoding UTF-8 contents and an IO error that might prevent you from retrying or reading further, consider using one of the `&[u8]`/byte slice methods and separately decoding the contents instead."

**Comment by Dylan-DPC** [comment]
Given that this has been inactive for a while now, I think it's better to create a new pr for this. Closing this.

**Pull request closed without merging**
