### PR TITLE
correct import suggestions for edition 2018

### PR DESCRIPTION
**Pull request by zackmdavis**
For #52202.

### CODE REVIEW

**Comment by oli-obk** [comment]
Isn't the crate prefix also valid 2015 Rust?

**Comment by zackmdavis** [comment]
It's [feature-gated](https://github.com/rust-lang/rust/blob/b3e7d70ce7730a929fd3d5094e8ad2eb71c3a399/src/libsyntax/feature_gate.rs#L1864-L1865).

```
zmd@ReflectiveCoherence:~/Code/Misc$ rustc import_suggestion.rs --edition 2015
error[E0658]: `crate` in paths is experimental (see issue #45477)
 --> import_suggestion.rs:1:5
  |
1 | use crate::inner_mod::MyInnerStruct;
  |     ^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

**Comment by oli-obk** [comment]
Oh. Right

r=me with a FIXME comment that references #45477

**Pull request merged**
