### PR TITLE
Never panic in `thread::park` and `thread::park_timeout`

### LINKED ISSUE #102398: `thread::park` causes undefined behaviour on panic
[A](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/sync/once.rs#L481-L492) [lot](https://github.com/kprotty/usync/blob/44a0eeae99a597baa6b91fae7c1b3227103de2bc/src/rwlock.rs#L478) [of](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/thread/scoped.rs#L148-L151) [code](https://github.com/kprotty/usync/blob/44a0eeae99a597baa6b91fae7c1b3227103de2bc/src/condvar.rs#L258-L259) [dealing](https://github.com/matklad/once_cell/blob/97edd07e0ac05fb8e4b994e9a53ba187d8fa17fc/src/imp_std.rs#L254-L256) with synchronization assumes that `thread::park` does not panic. This assumption is however not correct. For instance, a panic occurs if the TLS key used to store the thread info [cannot be created](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/sys/unix/thread_local_key.rs#L10), [if a new thread id cannot be created](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/thread/mod.rs#L1047), [if the creation of a parking primitive fails](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/sys/itron/wait_flag.rs#L22), [if the current time is not available](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/sys/unix/thread_parker/pthread.rs#L67) and [if the parking operation fails](https://github.com/rust-lang/rust/blob/837bf370de144a682041e68bb67469b9f68a55ce/library/std/src/sys/itron/wait_flag.rs#L38).

The code examples above all use intrusive lists and have to wait on a condition to before destroying the list nodes. If `thread::park` panics, the nodes will be dropped during stack unwinding without checking that condition, leading to undefined behaviour (some of these cases are in `std`, so I'm marking this as a soundness problem with `std`).

Fixing this would either require guarding against panics in each of these cases or ensuring that `thread::park` never panics.

@rustbot label +I-unsound +A-atomic +T-libs +T-libs-api

### PR DESCRIPTION
**Pull request by joboet**
fixes #102398

@rustbot label +T-libs +T-libs-api

### CODE REVIEW

**Comment by the8472** [comment]
Wouldn't *not parking* the thread if some underlying resource can't be acquired be a valid strategy? After all park is allowed to wake up any time, similar to condvars. So instead of panicing it would return immediately.

**Comment by m-ou-se** [comment]
@the8472 Yes, but if the error keeps occuring, that'd effectively turn a park-loop into a spin-loop, which is pretty bad.

**Comment by m-ou-se** [comment]
Changing the implementation to never panic looks good to me. Making it a documented guarantee should go through FCP though.

@rfcbot merge

This FCP is for documenting the guarantee that `thread::park()` will never panic. See https://github.com/rust-lang/rust/issues/102398 for context.

**Comment by joboet** [comment]
> Wouldn't _not parking_ the thread if some underlying resource can't be acquired be a valid strategy? After all park is allowed to wake up any time, similar to condvars. So instead of panicing it would return immediately.

Yes, definitely, and this is still valid behaviour. However, since implementing that would impact so many different areas (TLS for instance), I think just aborting is fine for now. Errors should be extremely rare, anyway.

**Comment by DemiMarie** [comment]
> > Wouldn't _not parking_ the thread if some underlying resource can't be acquired be a valid strategy? After all park is allowed to wake up any time, similar to condvars. So instead of panicing it would return immediately.
> 
> Yes, definitely, and this is still valid behaviour. However, since implementing that would impact so many different areas (TLS for instance), I doubt that it is really worth it, as errors should be extremely rare here.

What about eagerly allocating the resources when creating the thread?

**Comment by m-ou-se** [comment]
> What about eagerly allocating the resources when creating the thread?

That doesn't prevent all possible panics. We can't guarantee that e.g. the underlying libc calls always succeed. See https://github.com/rust-lang/rust/issues/102398#issuecomment-1271642165

**Pull request merged**
