### PR TITLE
Added Default impl to PathBuf

### PR DESCRIPTION
**Pull request by XAMPPRocky**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Comment by brson** [comment]
I feel like we've discussed this before and decided not to have a default for paths because it's not clear what it means to be a 'default' path. This implementation I think creates an empty path, but semantically that does not strike me as a 'default path', it strikes me more like a null path and a source of errors.

**Comment by brson** [comment]
@rfcbot concern there's no obvious default for paths per above

**Comment by aturon** [comment]
@brson Yes, I believe this came up for `Path` previously, with the conclusion you mention. But the story is different for `PathBuf`, as it's common to create an empty `PathBuf` and then push components onto it.

**Comment by sfackler** [comment]
A generally good rule of thumb is that if a type has a no-arg `new` method, it probably makes sense to have a `Default` impl that does the same thing. I think clippy may even have a lint for that?

**Comment by clarcharr** [comment]
@sfackler it does: https://github.com/Manishearth/rust-clippy/wiki#new_without_default

**Comment by sfackler** [comment]
@brson ping?

**Comment by clarcharr** [comment]
Also note that this has precedent in Iterator::unzip which requires Default.

**Comment by brson** [comment]
> @brson Yes, I believe this came up for Path previously, with the conclusion you mention. But the story is different for PathBuf, as it's common to create an empty PathBuf and then push components onto it.

And you would use _default_ for that, not new?

**Comment by brson** [comment]
> Also note that this has precedent in Iterator::unzip which requires Default.

I don't quite follow how that is precedent for Path::default.

**Comment by brson** [comment]
I'm afraid I still don't see any obvious motivation here except for @sfackler's rule of thumb that types that implement `new` should implement `default`. I've stated my concern that empty PathBuf's, which could accidentally slip in to arbitrary deriving-default data structures, are bogus, and prone to error. I don't see a use case for defaulting empty paths.

**Comment by clarcharr** [comment]
@brson: the `unzip` iterator adapter assumes `Default` and `Extend` instead of `FromIterator`, basically stating that the `Default` implementation for a container is its empty version.

Empty strings might not be a reasonable default for a lot of containers too, but that's the way stdlib seems to point.

**Comment by BurntSushi** [comment]
> I've stated my concern that empty PathBuf's, which could accidentally slip in to arbitrary deriving-default data structures, are bogus, and prone to error. 

I feel like this is a pretty good point. Paths have additional semantics in the environment that strings don't have.

I don't feel strongly either way on this given @brson's concerns. It does feel like a possible footgun, but I think adding a `Default` impl so that `PathBuf` works with things like `unzip` is pretty nice. Neither seem like a big deal though.

**Comment by aturon** [comment]
I agree with @brson that there's a potential footgun here, but I think it's relatively minor, and OTOH not being able to work easily with things like `unzip` is a pain. So on balance I'm still 👍.

**Comment by Aaronepower** [comment]
> I've stated my concern that empty PathBuf's, which could accidentally slip in to arbitrary deriving-default data structures, are bogus, and prone to error.

@brson I'm not really sure if I see the footgun. What errors could arise from the PathBuf that wouldn't already have to be handled by the user?

**Comment by tbu-** [comment]
See also #32990.

The empty path makes sense for both `Path` and `PathBuf` -- when you accumulate over (concatenate) many of these, the empty path is the neutral element, much like the `Default` implementation for many other types.

**Comment by aturon** [comment]
Ping @brson, are you satisfied by the recent arguments?

**Comment by brson** [comment]
@aturon No, but I clicked the box anyway.

**Comment by aturon** [comment]
Thanks all, and thanks @Aaronepower for sticking in there!

@bors: r+ rollup

**Pull request merged**
