### PR TITLE
Rust 1.32.0 stable release

### PR DESCRIPTION
**Pull request by emilyalbini**
Also cherry-picked the following beta-accepted PRs:

* #57519: Correct RELEASES.md for 1.32.0

r? @Mark-Simulacrum 
cc @rust-lang/release

### CODE REVIEW

**Comment by pietroalbini** [comment]
Uh?

@bors retry

**Comment by Mark-Simulacrum** [comment]
@alexcrichton Do you by chance know the .iss file syntax? Or maybe @retep998? I don't have the time to investigate tonight and am not quite sure what the problem is -- I suspect it has something to do with https://github.com/rust-lang/rust/blob/master/src/etc/installer/exe/rust.iss#L60 but haven't been able to determine yet if that's actually the problem or just a side effect.

**Comment by Mark-Simulacrum** [comment]
Well, all I've learned from the ~half hour of investigative work I did tonight is that I don't understand where these files are coming from. I also haven't found anything that changed since the last successful build of the parent commit from this PR -- i.e., https://ci.appveyor.com/project/rust-lang/rust/builds/21559614/job/6vmkp5fj047niib5 -- within the logs. We've bumped the toolchain to "stable" but that seems to be unrelated to the current failure. As far as I can tell, std is being built and disted -- even though I'm still not quite sure how the files make it into `work` [here](https://github.com/rust-lang/rust/blob/6ecad338381cc3b8d56e2df22e5971a598eddd6c/src/bootstrap/dist.rs#L1678) because as far as I could tell nothing is copying them there. Maybe I'm missing something though -- the dist code is quite convoluted; and in any case nothing has changed in all of bootstrap since the beta build was successful.

@alexcrichton said he'd do some more investigating tomorrow -- and I hope to spend at least a little time as well, though not sure how much I'll have.

**Comment by alexcrichton** [comment]
@bors: r+

No idea what's happening. Added debug information. Let's see what happens

**Comment by mark-i-m** [comment]
Should https://github.com/rust-lang/rust/pull/57610 be backported before the release?

**Comment by pietroalbini** [comment]
Uh, it's *really* late for that. Not `beta-accepted`, no working build of the PR...

**Comment by mark-i-m** [comment]
Yes, I agree. The issue was only discovered a day ago. The alternatives are
- rollback the feature
- let it be broken for a release cycle
- do a point release

None of these seem particularly nice... I thought I would bring it up now, rather than later.

**Comment by petrochenkov** [comment]
@mark-i-m 
"Let it be broken" is ok, it's just a crash, not a compatibility issue, we have plenty of those.

**Comment by mark-i-m** [comment]
Ok. FWIW, I believe the CI build should be green this time; it's passing locally.

**Pull request merged**
