### PR TITLE
Avoid unnecessary work in `finalize_resolutions_in`.

### PR DESCRIPTION
**Pull request by nnethercote**
If `module.opt_def_id()` returns `None`, we can skip most of the work.

r? @lqd

### CODE REVIEW

**Comment by nnethercote** [comment]
This is a 1% win on the `c2-chacha-0.3.3` crate (`check full` build) and has little effect on anything else.

**Comment by lqd** [comment]
I'm not super familiar with the resolver, and the change seems OK, but I wonder if this could impact resolutions to the modules where it's done lazily, e.g. their possible errors / ambiguities ? 

I would trust tests (esp with `#[macro_export]`) to tell us that if that's the case, but I wonder if we do have tests exercizing this code path, do you happen to know that ?

r=me if that's the case, and if we ever need this PR to be easy to find for bisection:

@bors rollup=never

**Comment by nnethercote** [comment]
The idea here is that functionality shouldn't be changed.

The current code creates `reexports`. It doesn't modify anything else while doing so. Then, if `if let Some(def_id) = module.opt_def_id()` succeeds, it does something with `reexports`. Otherwise, it does nothing.

I just rearranged things so that `reexports` isn't built in the "it does nothing" case.

**Comment by lqd** [comment]
To clarify, I meant that `for_each_child` seemed to be able to mutate resolutions, and was wondering whether we knew of modules "populated on access" and if so, whether `finalize_resolutions_id` could be involved in populating them ?


https://github.com/rust-lang/rust/blob/830880640304ba8699c5f9a0c4665c38a3271963/compiler/rustc_resolve/src/lib.rs#L550-L560 and in turn https://github.com/rust-lang/rust/blob/830880640304ba8699c5f9a0c4665c38a3271963/compiler/rustc_resolve/src/lib.rs#L1658-L1664

**Comment by petrochenkov** [comment]
>whether `finalize_resolutions_id` could be involved in populating them

Nah, only modules from other crates are lazily populated, and the less of them is populated the better.
Modules without a def-id cannot be extern though, so in this PR is shouldn't make any difference.

**Comment by nnethercote** [comment]
Slightly unexpected perf results, but the wins and losses more or less balance out so I don't think we need to worry about it.

@rustbot label: +perf-regression-triaged

**Pull request merged**
