### PR TITLE
Enforce that UNTRACKED options are not accessed by queries

### PR DESCRIPTION
**Pull request by pierwill**
Part of https://github.com/rust-lang/rust/issues/90317.

See https://github.com/rust-lang/rust/issues/90317#issuecomment-975950940.

### CODE REVIEW

**Comment by pierwill** [comment]
r? -@michaelwoerister

**Comment by camelid** [comment]
@pierwill when you remove `S-waiting-on-review`, please add another status label (such as `S-waiting-on-author` in its place). The triage team uses this to determine the status of PRs. You should be able to use the command `@rustbot author` to do this for you.

**Comment by pierwill** [comment]
I'm still thinking about how to go about implementing @bjorn3's suggestion in https://github.com/rust-lang/rust/issues/90317#issuecomment-990042731.

This change seems like the obvious place to start https://github.com/rust-lang/rust/pull/91866/commits/5182cb5b4fbc20418875e59bbc50954f2f52ae5a.

But to create the "getters", would it be best to eventually use a macro?

**Comment by pierwill** [comment]
Here's an example method: https://github.com/rust-lang/rust/pull/91866/files/658e745071fb093b6fe13b034b92ab24ae988df1..6e4071881aa98ec7df1f769be26f0b188102b956

If we were to do this for all options, deduplicating the code should be more or less straightword.

Does this help us with the underlying issue in #90317? 🤔

**Comment by pierwill** [comment]
> The point is to run [depgraph.assert_ignored](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_query_system/dep_graph/graph/struct.DepGraph.html#method.assert_ignored) in the getter functions. 😇

This means that the getter functions for each option will need access to the [`DepGraph`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_query_system/dep_graph/graph/struct.DepGraph.html), and maybe the [`Session`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/session/struct.Session.html) as well?

If we do need access to either or both of those data structures, I'm not sure how best to go about it. Will this require adding a dependency on `rustc_query_system` or similar to `rustc_session`?

**Pull request closed without merging**
