### PR TITLE
Remove `Parser::missing_fragment_specifier`.

### PR DESCRIPTION
**Pull request by nnethercote**
r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
@petrochenkov: this is my attempt to implement what you suggested, but there are problems. Consider the program I mentioned previously:
```
#![allow(unused_macros)]
macro_rules! m_used { ( $id ) => {} }
macro_rules! m_unused { ( $id ) => {} }
fn main() { m_used!(x); 
```
Currently, the first macro results in a hard error, the second in a lint error (which is ignorable).

With this change, both macros result in a lint error (which is ignorable). If they are ignored, I get an ICE somewhere in codegen, getting a Layout:
```
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:956:13: failed to get layout for `[type error]`: the type `[type error]` has an unknown layout
 --> y.rs:6:1
  |
6 | fn main() { m_used!(x); }
  | ^^^^^^^^^

thread 'rustc' panicked at 'Box<dyn Any>', /home/njn/dev/rust2/compiler/rustc_errors/src/lib.rs:1289:9
```
I suspect this is related to the fact that an invalid macro will get an empty `MatcherLoc` vec, though I'm not certain. There are also some test failures, but I'm focused on this ICE first.

I'm not sure if this is possible. The current mix of hard errors and lint errors seems hard to adjust. Or am I overlooking something?

**Comment by nnethercote** [comment]
Thinking this through some more...
- In `quoted::parse()` we detect the missing fragment specifier, and record it in `Parser::missing_fragment_specifier`.
- When we first hit a missing fragment specifier during matching, we remove it from `Parser::missing_fragment_specifier` and issue a hard error. The removal prevents us from issuing duplicate errors on subsequent matching attempts.
- If a match succeeds, we have to look for more missing fragment specifiers before accepting the success, because there might be a missing fragment specifier within a sequence that wasn't looked at during matching (e.g. see `ui/macros/macro-missing-fragment.rs`). If so, we issue a hard error.
- After matching is finished, we look in `Parser::missing_fragment_specifier` for any remaining cases. These are ones that weren't hit during matching. For these we issue a lint error.

In the past, attempts were made to change the lint errors to hard errors, but this broke too much existing code.

This PR is about changing the hard errors to lint errors. But then, if we ignore what were previously hard errors, we can't continue compilation sensibly.

So I can't see how to make this work.

**Comment by petrochenkov** [comment]
I missed the fact that they are reported as hard errors on actual match.
I'll try to experiment with this myself today.

>The removal prevents us from issuing duplicate errors on subsequent matching attempts.

This is the less valuable part of this logic given that the compiler deduplicates identical error messages anyway, and given that it requires a piece of global mutable state.

**Comment by petrochenkov** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/95808.

**Pull request closed without merging**
