### PR TITLE
feat(opt-dist): new flag `--benchmark-cargo-config`

### PR DESCRIPTION
**Pull request by weihanglo**
This should be the last piece toward self-contained `opt-dist` (I believe).

The flag propagates cargo configs to `rustc-perf --cargo-config`,
which is particularly useful when the environment is air-gapped,
and you want to use the default set of training crates vendored
in the rustc-src tarball.

It fixes the issue described in #125465

> * The current pinned rustc-perf uses `tempfile::Tempdir` as the working
  directory when collecting profiles from some of these packages.
  This "tmp" working directory usage make it impossible for Cargo to pick
  up the correct vendor sources setting in `.cargo/config.toml` bundled
  in the rustc-src tarball. [^1]
> [^1]: https://github.com/rust-lang/rustc-perf/blob/4f313add609f43e928e98132358e8426ed3969ae/collector/src/compile/benchmark/mod.rs#L164-L173

See also

* <https://github.com/rust-lang/rustc-perf/pull/1913>
* <https://github.com/rust-lang/rust/pull/125465>
* https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/tempfile.20in.20rustc-perf.20make.20it.20hard.20to.20configure.20vendor

r​? Kobzol

### CODE REVIEW

**Comment by weihanglo** [comment]
block on #125465 btw

**Comment by Kobzol** [comment]
I'm not sure if this should be the default, people can have their own `.cargo/config.toml` files with whatever contents, and ideally `dist` (and `opt-dist`) should probably ignore these by default, and be self-contained and isolated. We could gate it behind a CLI flag, and people using vendoring could just use the flag explicitly. What do you think?

**Comment by weihanglo** [comment]
> I'm not sure if this should be the default, people can have their own `.cargo/config.toml` files with whatever contents, and ideally `dist` (and `opt-dist`) should probably ignore these by default, and be self-contained and isolated. We could gate it behind a CLI flag, and people using vendoring could just use the flag explicitly. What do you think?

Yeah I've considered a new flag, though not sure how it should look like. Just propagate `--cargo-config` flag to `opt-dist`?

**Comment by Kobzol** [comment]
Yeah, that sounds reasonable. We should also document it [here](https://rustc-dev-guide.rust-lang.org/building/optimized-build.html#profile-guided-optimization) (maybe we should add some more recent changes there).

**Comment by weihanglo** [comment]
@Kobzol. A new flag `--benchmark-cargo-config` is added(naming is hard 😅). Let me know if it needs more changes :)

Just note that this PR is not really blocked on #125465. However #125465 might need to be merged before a new beta comes out, as we've already started vendoring rustc-perf in some previous PRs.

I'll prepare a doc update soon once everything's settled.

**Review by Kobzol — APPROVED** [review]
Looks good. Feel free to r=me once you remove the draft status.

**Comment by weihanglo** [comment]
Should be safe to rollup.

@bors r=Kobzol rollup

**Pull request merged**
