### PR TITLE
Linker regression

### PR DESCRIPTION
**Pull request by michaelwoerister**
This should fix the symbol conflicts reported in #36852.
The PR also makes some debug output a bit more informative.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
@bors r+

Also, does this affect beta, i.e. do we need to backport this?
I recall @camlorn trying `-Zincremental` at stage0 and it not working, although I don't know if it's this bug.

**Comment by michaelwoerister** [comment]
@bors r-

The new code fails when the same shim is instantiated twice (can't *define* the same function two times). Will fix.

**Comment by michaelwoerister** [comment]
OK, the updated version passes `make check`. 
Yes, I think backporting the fix for fn once shims would make sense (it's very small and uncontroversial, I think).

**Comment by nikomatsakis** [comment]
Accepting for beta because small patch, regression.

cc @rust-lang/compiler

**Pull request merged**
