### PR TITLE
[DO NOT MERGE] Enable parallel compiler by default

### PR DESCRIPTION
**Pull request by bjorn3**
This is a rebase of #75651.

#78201 may have reduced the overhead of parallel rustc.

### CODE REVIEW

**Comment by bjorn3** [comment]
r? @ghost

(forgot this)

**Comment by bjorn3** [comment]
```
failures:
    [ui] ui/privacy/privacy2.rs
    [ui] ui/privacy/privacy3.rs
    [ui] ui/type_length_limit.rs
```

There are a few cases where the exact error changes.

**Comment by est31** [comment]
In the unit test benchmarks, there are sometimes really heavy regressions, but the wall clock time improvement for bigger crates is just beautiful:

Screenshot_20201204_221545

-----

Screenshot_20201204_221333

**Comment by bjorn3** [comment]
Instruction count difference seems to have gotten a bit worse since the last perf test, however wall time difference seems to have gotten a bit more positive than it already was.

**Comment by bjorn3** [comment]
Going to do another perf run with only a single thread to see if the overhead in this case has been reduced.

@bors try @rust-timer queue

**Comment by Mark-Simulacrum** [comment]
The bootstrap times are actually really interesting, because perf runs that build under -j1 - which should mean that we get zero parallelism opportunity. I guess that means that either our -j1 isn't quite working or something else interesting is going on (e.g., we get better scheduling under parallel mode). Either way I'm not sure I'd trust these numbers given that...

Overall though other than that confusing element these do indeed look pretty good. We can't trust the instruction counts I think pretty much at all for this kind of assessment.

**Comment by est31** [comment]
Now it's way less red in the instruction counts (single digit regressions), but there are regressions for the bootstrap timings.

**Pull request closed without merging**
