### PR TITLE
lint: deny incoherent_fundamental_impls by default

### PR DESCRIPTION
**Pull request by hdhoang**
Warn the ecosystem of the pending intent-to-disallow in #49799.

There are 4 ICEs on my machine, look unrelated (having happened before in https://github.com/rust-lang/rust/issues/49146#issuecomment-384473523)

```rust
thread 'main' panicked at 'assertion failed: position <= slice.len()', libserialize/leb128.rs:97:1
```

```
    [run-pass] run-pass/allocator/xcrate-use2.rs
    [run-pass] run-pass/issue-12133-3.rs
    [run-pass] run-pass/issue-32518.rs
    [run-pass] run-pass/trait-default-method-xc-2.rs
```

r? @nikomatsakis

### CODE REVIEW

**Comment by hdhoang** [comment]
looks like I need to coordinate with the `src/doc` submodule. How should I go about that?

**Comment by nikomatsakis** [comment]
@hdhoang I think you can just edit this file directly:

https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/lints/listing/warn-by-default.md

Presumably just move the relevant entry to 

https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/lints/listing/deny-by-default.md

**Comment by hdhoang** [comment]
Oh, how did I come to think doc was a submodule. I have updated the listings.

I suppose #49799 failed before getting to this stage, so I will update it too.

**Comment by shepmaster** [comment]
Ping from triage, @nikomatsakis — looks like this is back in your court!

**Comment by nikomatsakis** [comment]
Thanks @hdhoang !

**Pull request merged**
