### PR TITLE
Allocate Symbol strings from an arena

### PR DESCRIPTION
**Pull request by Zoxc**
This is an alternative to https://github.com/rust-lang/rust/pull/50549

cc @nnethercote

r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@Mark-Simulacrum I'd like a perf run here

**Comment by nnethercote** [comment]
Nitpick: All the comments in this patch would benefit from a full stop ('.') at the end :)

**Comment by nnethercote** [comment]
I did a local benchmarking run. The results were excellent, and much better than those from #50549.
```
helloworld-check
	avg: -4.9%	min: -5.2%	max: -4.7%
unify-linearly-check
	avg: -3.9%	min: -4.6%	max: -3.1%
issue-46449-check
	avg: -3.8%	min: -4.3%	max: -3.2%
parser-check
	avg: -3.5%	min: -4.2%	max: -2.5%
deeply-nested-check
	avg: -3.0%	min: -3.9%	max: -2.3%
issue-46449
	avg: -1.8%	min: -3.7%	max: -1.4%
deeply-nested-opt
	avg: -1.9%	min: -3.6%	max: -0.9%
issue-46449-opt
	avg: -1.2%	min: -3.5%	max: -0.5%
deeply-nested
	avg: -2.1%	min: -3.5%	max: -1.2%
regression-31157-check
	avg: -2.0%	min: -2.8%	max: -1.2%
futures-check
	avg: -1.7%	min: -2.6%	max: -0.6%
tokio-webpush-simple-check
	avg: -1.7%	min: -2.5%	max: -1.0%
futures-opt
	avg: -1.4%	min: -2.4%	max: -0.4%
futures
	avg: -1.5%	min: -2.4%	max: -0.5%
regex-check
	avg: -1.9%	min: -2.4%	max: -0.9%
coercions-check
	avg: -1.1%	min: -2.0%	max: -0.4%
regex-opt
	avg: -0.9%	min: -2.0%	max: -0.1%
regex
	avg: -1.0%	min: -1.9%	max: -0.2%
regression-31157-opt
	avg: -0.2%	min: -1.8%	max: 1.7%
hyper-check
	avg: -1.2%	min: -1.7%	max: -0.6%
parser-opt
	avg: -1.4%	min: -1.7%	max: -1.2%
encoding-check
	avg: -1.2%	min: -1.7%	max: -0.6%
html5ever-check
	avg: -0.7%	min: -1.6%	max: -0.1%
regression-31157
	avg: -1.0%	min: -1.6%	max: -0.4%
helloworld
	avg: -1.5%	min: -1.6%	max: -1.4%
parser
	avg: -1.4%	min: -1.6%	max: -1.1%
unify-linearly
	avg: -1.4%	min: -1.6%	max: -1.2%
encoding-opt
	avg: -0.8%	min: -1.5%	max: -0.0%
coercions-opt
	avg: -0.8%	min: -1.5%	max: -0.3%
hyper-opt
	avg: -0.8%	min: -1.5%	max: -0.2%
helloworld-opt
	avg: -1.4%	min: -1.5%	max: -1.3%
unify-linearly-opt
	avg: -1.3%	min: -1.5%	max: -1.2%
coercions
	avg: -0.7%	min: -1.5%	max: -0.1%
hyper
	avg: -0.8%	min: -1.5%	max: -0.3%
encoding
	avg: -0.6%	min: -1.4%	max: 0.3%
unused-warnings-check
	avg: -1.1%	min: -1.4%	max: -1.0%
html5ever
	avg: -0.8%	min: -1.4%	max: -0.4%
tuple-stress-opt
	avg: -0.7%	min: -1.3%	max: -0.4%
tuple-stress-check
	avg: -0.6%	min: -1.2%	max: -0.2%
unused-warnings
	avg: -1.0%	min: -1.1%	max: -0.9%
syn-check
	avg: -0.7%	min: -1.1%	max: -0.3%
unused-warnings-opt
	avg: -0.9%	min: -1.0%	max: -0.8%
syn
	avg: -0.5%	min: -1.0%	max: -0.2%
syn-opt
	avg: -0.3%	min: -1.0%	max: 0.2%
```
Nice work, @Zoxc!

**Comment by michaelwoerister** [comment]
Let's do it `:)`

@bors r+

**Pull request merged**
