### PR TITLE
Lower condition of `if` expression before it's "then" block

### LINKED ISSUE #82250: Rustc internal panic with feature(let_chains)
I tried this code:

```rust
#![feature(let_chains)]
<with a lot of code>
```

### Meta
`rustc --version --verbose`:
```
rustc 1.52.0-nightly (e9920ef77 2021-02-11)
binary: rustc
commit-hash: e9920ef7749d11fc71cc32ca4ba055bcfeaab945
commit-date: 2021-02-11
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

```
thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(48000),
)', compiler/rustc_ast_lowering/src/lib.rs:714:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/std/src/panicking.rs:435:5
   2: rustc_ast_lowering::LoweringContext::lower_node_id_generic
   3: rustc_ast_lowering::path::<impl rustc_ast_lowering::LoweringContext>::lower_qpath
   4: rustc_data_structures::stack::ensure_sufficient_stack
   5: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   6: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
   7: rustc_data_structures::stack::ensure_sufficient_stack
   8: rustc_ast_lowering::LoweringContext::lower_stmt
   9: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  10: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  11: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  12: rustc_arena::cold_path
  13: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if
  14: rustc_data_structures::stack::ensure_sufficient_stack
  15: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  16: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  17: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  18: rustc_arena::cold_path
  19: rustc_ast_lowering::LoweringContext::lower_block
  20: rustc_data_structures::stack::ensure_sufficient_stack
  21: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_arm
  22: rustc_ast_lowering::Arena::alloc_from_iter
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  25: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  26: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  27: rustc_arena::cold_path
  28: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if
  29: rustc_data_structures::stack::ensure_sufficient_stack
  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  31: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  32: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  33: rustc_arena::cold_path
  34: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if_let
  35: rustc_data_structures::stack::ensure_sufficient_stack
  36: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  37: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  38: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  39: rustc_arena::cold_path
  40: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_fn_body_block
  41: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_maybe_async_body
  42: rustc_ast_lowering::LoweringContext::with_hir_id_owner
  43: rustc_ast::visit::walk_item
  44: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::with_parent_item_lifetime_defs
  45: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  46: rustc_ast::visit::walk_item
  47: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::with_parent_item_lifetime_defs
  48: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  49: rustc_ast::visit::walk_item
  50: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::with_parent_item_lifetime_defs
  51: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  52: rustc_ast_lowering::lower_crate
  53: rustc_interface::passes::BoxedResolver::access::{{closure}}
  54: rustc_interface::passes::configure_and_expand::{{closure}}
  55: rustc_interface::passes::BoxedResolver::access
  56: rustc_interface::queries::Queries::lower_to_hir
  57: rustc_interface::queries::Queries::global_ctxt
  58: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  59: rustc_span::with_source_map
  60: rustc_interface::interface::create_compiler_and_run
  61: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.52.0-nightly (e9920ef77 2021-02-11) running on x86_64-unknown-linux-gnu
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
error: could not compile `project`
To learn more, run the command again with --verbose.
Process finished with exit code 101

```
Note:
A simpler program does not crash, but does not compile.
https://github.com/rust-lang/rfcs/issues/2411#issuecomment-575346318
```
#![feature(let_chains)]
use std::error::Error;
fn main(){
    let obj = Some(1);
    if let Some(i) = obj && i > 5 {

    }
}
```
```log
error: `let` expressions are not supported here
 --> src/main.rs:5:8
  |
5 |     if let Some(i) = obj && i > 5 {
  |        ^^^^^^^^^^^^^^^^^
  |
  = note: only supported directly in conditions of `if`- and `while`-expressions
  = note: as well as when nested within `&&` and parenthesis in those conditions

```
https://github.com/rust-lang/rust/issues/53667

### LINKED ISSUE #82290: let_chains causes a compiler panic
### Code

```Rust
#![feature(str_split_once)]
#![feature(let_chains)]

fn main() {
    let mut bug = "lalacoollolo".to_string();
    if !bug.contains("🔢") && (let Some((start, end)) = bug.split_once("1234")) {
        bug = format!("{}🔢{}", start, end);
    }

    println!("{}", bug);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (8e54a2113 2021-02-13)
binary: rustc
commit-hash: 8e54a21139ae96a2aca3129100b057662e2799b9
commit-date: 2021-02-13
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### Error output

```
thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(28),
)', compiler/rustc_ast_lowering/src/lib.rs:714:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (8e54a2113 2021-02-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(28),
)', compiler/rustc_ast_lowering/src/lib.rs:714:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:435:5
   2: rustc_ast_lowering::LoweringContext::lower_node_id_generic
   3: rustc_ast_lowering::path::<impl rustc_ast_lowering::LoweringContext>::lower_qpath
   4: rustc_data_structures::stack::ensure_sufficient_stack
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   7: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
   8: rustc_data_structures::stack::ensure_sufficient_stack
   9: rustc_data_structures::stack::ensure_sufficient_stack
  10: rustc_data_structures::stack::ensure_sufficient_stack
  11: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  12: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  15: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_ast_lowering::LoweringContext::lower_stmt
  18: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  19: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  20: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  21: rustc_arena::cold_path
  22: rustc_ast_lowering::LoweringContext::lower_block
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_assign
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_ast_lowering::LoweringContext::lower_stmt
  27: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  28: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  29: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  30: rustc_arena::cold_path
  31: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_ast_lowering::LoweringContext::lower_stmt
  34: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  35: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  36: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  37: rustc_arena::cold_path
  38: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_fn_body_block
  39: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_maybe_async_body
  40: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_item
  41: rustc_ast_lowering::LoweringContext::with_hir_id_owner
  42: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  43: rustc_ast_lowering::lower_crate
  44: rustc_interface::passes::BoxedResolver::access::{{closure}}
  45: rustc_interface::passes::configure_and_expand::{{closure}}
  46: rustc_interface::queries::Queries::lower_to_hir
  47: rustc_interface::queries::Queries::global_ctxt
  48: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  49: rustc_span::with_source_map
  50: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (8e54a2113 2021-02-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `bug`

To learn more, run the command again with --verbose.
```

</p>
</details>

I made a small git repo to reproduce the bug [here](https://github.com/irevoire/bug)

### PR DESCRIPTION
**Pull request by estebank**
Fix #82290, fix #82250.

### CODE REVIEW

**Comment by estebank** [comment]
Low priority backport, low risk. Nightly feature let patterns can cause ICE even without the feature gate set. It seems like a case easy to hit, but there's no risk in letting this follow the process.

**Comment by estebank** [comment]
I was wrong, [it affects beta now](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=fb61caa49134083d3ccad05d95ee5366).

**Comment by apiraino** [comment]
beta backport declined, as per discussion on [Zulip team compiler meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-03-25.20.2354818/near/231806882), it is already in stable.

@rustbot label -beta-nominated

**Pull request merged**
