### PR TITLE
Avoid per-register closure expansions

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Best reviewed with whitespace ignored.

This hopefully reduces overall size of the binary. Probably zero impact in instructions/cycles in rustc-perf since we don't really have any asm benchmarks AFAIK...

### CODE REVIEW

**Comment by spastorino** [comment]
Seems good to me r=me once your happy with perf.

**Comment by Mark-Simulacrum** [comment]
The relevant code went down in size by ~58 kb (74,052 -> 16,284 bytes) in the try build, which I'm happy with.

Rebased, waiting for PR CI to pass and then will approve.

**Pull request merged**
