### PR TITLE
Group trait implementation in doc sidebar by source module 

### LINKED ISSUE #105307: Group navigation items in the docs by source crate/module
> I posted [a thread in IRLO](https://internals.rust-lang.org/t/group-navigation-items-in-the-docs-by-source-crate-module/17903) for this feature request, and it seems nobody is against it. Therefore, I come to post an issue here.

For the documentation generated for a type, it seems great to me if the trait implmentations can be grouped by the name of source crate (even source module) in the left navigation panel. Usually, a type won't have too many methods but it can have numerous trait implmentations (especially for numberic related types such as [BigUint](https://docs.rs/num-bigint/0.4.3/num_bigint/struct.BigUint.html) and [rug::Integer](https://docs.rs/rug/1.17.0/rug/struct.Integer.html)).

People usually don't browse the trait implementations by the alphabetic order, they do directly by searching. But sometimes if I don't know which trait I'm looking for, but just want to know what functionalities the type support, it will be great if I can find the implementations by the crate / module name. For example, the implementation of all the arithmetic traits (Add, Sub, etc) can be grouped by the `core::ops` module name.

# Current behavior

(This documentation comes from [`dashu-int::UBig`](https://docs.rs/dashu-int/latest/dashu_int/struct.UBig.html))

image

# Proposed behavior

The style for the module names is to be defined.

image

### PR DESCRIPTION
**Pull request by cmpute**
This should fix #105307, I'm pretty satisfied with the current rendering result: [page1](http://zyxin.xyz/rustdoc-group-test/dashu_base/sign/enum.Sign.html), [page2](http://zyxin.xyz/rustdoc-group-test/dashu_int/struct.UBig.html). However, it's my first time contributing to rust and please pardon me if there're some non-idiomatic code.

image

### CODE REVIEW

**Comment by cmpute** [comment]
Not sure how to fix the goml error in the CI..

**Comment by GuillaumeGomez** [comment]
So before reviewing this:

1. What is this change fixing exactly? (I assume readability but maybe other things too?)
2. Why is this new visual information helping to fix `1.`?

I have to admit I'm not sure to understand why it's interesting to know where an impl come from. This impl list in the sidebar isn't great because a lot of them look similar.

It's a change that I think is important so let's see what the @rust-lang/rustdoc think about it.

**Comment by GuillaumeGomez** [comment]
> Not sure how to fix the goml error in the CI..

It's GUI tests we use to check rustdoc generated documentation. You can find information about it in `src/test/rustdoc-gui/README.md`.

**Comment by cmpute** [comment]
> 1. What is this change fixing exactly? (I assume readability but maybe other things too?)

So, the motivation to do this change for me is that, I think rustdoc is good at documenting existing items (methods, traits, etc), but it's not that good at helping people finding the functionalities. I recently also went through some of the previous discussions about adding a summary section of rust structs, which is actually another way to help increasing the discoverability of the functionalities.

> 2. Why is this new visual information helping to fix 1.?

The proposed change groups the traits by source module, this could make discovering easier. Say I want to know how many arithmetic operations a struct supports, it will be easier if I can check the traits under the `core::ops` group, rather than scanning through the list and find the `Add`, `Sub`, .. traits scattered all around. (`Add` and `Sub` are pretty far away in current sidebar list).

I'm not sure how this change could improve for other kinds of trait (like traits for iterator, async, io, etc), but I suffer a lot from this because I'm working on a crate for numbers. See also the long trait list in [num-bigint](https://docs.rs/num-bigint/0.4.3/num_bigint/struct.BigInt.html), [rug](https://docs.rs/rug/1.18.0/rug/struct.Integer.html), [malachite](https://docs.rs/malachite-nz/0.3.0/malachite_nz/natural/struct.Natural.html).

Ideally the traits should also be grouped by name and collapsed by default to reduce the list length, but that's another change which is harder for me to implement because I'm not super familiar with HTML + CSS. Group the traits by source module will ease this problem at least.

**Comment by cmpute** [comment]
> > Not sure how to fix the goml error in the CI..
> 
> It's GUI tests we use to check rustdoc generated documentation. You can find information about it in `src/test/rustdoc-gui/README.md`.

Thanks! I will look into it later

**Comment by cmpute** [comment]
A second thought: this change might bring relatively large overhead for types that doesn't implement a lot of traits, a solution to this might be:
1. Only group the traits if the total number of implementations is greater than a threshold
2. Add a configuration flag for rustdoc that allow opt-in of this feature. (either a binary flag, or a threshold)

**Comment by GuillaumeGomez** [comment]
> A second thought: this change might bring relatively large overhead for types that doesn't implement a lot of traits, a solution to this might be:
> 
> 1. Only group the traits if the total number of implementations is greater than a threshold
> 2. Add a configuration flag for rustdoc that allow opt-in of this feature. (either a binary flag, or a threshold)

It's because of such things that UI changes are always more complicated than first thought. :)

I don't really know which one would be better. Maybe it might be worth bringing this conversation to [zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc) because I don't know if many rustdoc team members are actually on IRLO. I personally just learned about this today and although I'm (really!) happy to see someone trying to fix this problem, I'm not sure it's the best way to do it. Well many things to discuss.

**Comment by cmpute** [comment]
Thanks! I will post on zulip later :+1:

**Comment by cmpute** [comment]
It seems that there's no consensus yet on how we should improve the sidebar, so I will close this by now

**Pull request closed without merging**
