### PR TITLE
openbsd: probe CFG_GCC egcc

### PR DESCRIPTION
**Pull request by semarie**
under OpenBSD, it could be have present multiples versions of gcc compiler:
- gcc-4.2 (with patchs) : c/c++ compiler present in `/usr/bin`. It is unusable to build recent LLVM (so rustc too).
- gcc/g++ -4.9 : c/c++ compiler, installed as third-party with "ports" mechanism. The compiler is installed in `/usr/local` as `egcc` (and `eg++`).

this PR adds probing for `egcc` for `CFG_GCC`, if the first probed `gcc` is too old. It will set `CC` and `CXX` too, in order to pass the variables to LLVM configure if builded.

please note this PR is a first step in order to build rustc under OpenBSD with unpatched tree.

r? @alexcrichton

cc @brson @dhuseby

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 9ac36f46650d0f4d92b5111688d2fb84a50d591f

Thanks!

**Comment by semarie** [comment]
I add disabling jemalloc for openbsd: with gcc-4.9 TLS don't seems to be detected correctly, whereas using gcc from base, it is ok. I will investigate it later.

@alexcrichton I would like this PR be tested by buildbot before commit. I don't expect it to work at first time, but as it shouldn't fail for others architectures, @bors may commit it.

@dhuseby what is the OpenBSD version in use on the buildbot ? the latest stable (5.7) ? There were changes on linker recently that may changes some configuration need.

**Comment by alexcrichton** [comment]
Unfortunately we don't have a great way to run tests on non-gated builders before it actually lands, but the OpenBSD bot should run the tests regardless when this is merged I believe.

**Comment by alexcrichton** [comment]
(it's also fine to file a follow-up PR if tweaks are needed!)

**Comment by semarie** [comment]
@dhuseby does g++-4.9 is installed on buildbot ?

LLVM building is failing with `checking tool compatibility... configure: error: g++|clang++|icc required but not found`.

**Pull request merged**
