### PR TITLE
Fix a bug caching ids in the HIR lowering with nested lowered nodes

### PR DESCRIPTION
**Pull request by nrc**
Blocks #30884

r? @nikomatsakis 

cc @durka

### CODE REVIEW

**Comment by durka** [comment]
\o/

**Comment by nrc** [comment]
There were two bugs - we were not setting the gensym_key when entering a nested, cached node and we were not restoring the gensym_key when leaving a node.

**Comment by durka** [comment]
That could explain why I got an ICE compiling libcore after fixing only one of those.

**Pull request merged**
