### PR TITLE
Fewer early errors

### PR DESCRIPTION
**Pull request by nnethercote**
r? @davidtwco

### CODE REVIEW

**Comment by nnethercote** [comment]
@davidtwco: I think this is probably desirable. It does add two `#[allow(rustc::untranslatable_diagnostic)] #[allow(rustc::diagnostic_outside_of_impl)]` pairs which aren't good. I wasn't quite sure how to do the error handling in the face of the `error!` macros within `parse_cfg` and `parse_cfg_check`.

**Comment by nnethercote** [comment]
> The job x86_64-gnu-llvm-16 failed

Ugh, another early warning was added since I last updated my repo. I've fixed the compile error, but it required another `#[allow(rustc::untranslatable_diagnostic)] #[allow(rustc::diagnostic_outside_of_impl)]` pair. I should fix it properly, but I don't have the energy today.

**Review by davidtwco — APPROVED** [review]
This is good, a few more untranslatable diagnostics aren't the worst in the world, we can fix those with time. r=me with CI passing unless you think the changes will need another look.

**Comment by nnethercote** [comment]
I fixed the test failures. The problem was that jobserver warnings are now done via `Handler`, which means they now contribute to the warning count, and that warning count now gets printed at the end of execution.

I'm quite uncertain about whether this PR should be merged, because it causes us to count this compiler invocation warnings the same as warnings about the code being compiled. The same thing now happens with self-profile warnings, e.g. we used to do this:
```
$ rustc +nightly -Zself-profile=/ a.rs
warning: failed to create profiler: Permission denied (os error 13)
```
to this:
```
$ rustc +nightly -Zself-profile=/ a.rs
warning: failed to create profiler: Permission denied (os error 13)

warning: 1 warning emitted
```

Or, for a program with a code warning, we go from this:
```
$ rustc +nightly -Zself-profile=/ a.rs
warning: failed to create profiler: Permission denied (os error 13)

warning: unused variable: `x`
 --> a.rs:2:9
  |
2 |     let x = 1;
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

```
and now we do this:
```
$ rustc +nightly -Zself-profile=/ a.rs
warning: failed to create profiler: Permission denied (os error 13)


warning: unused variable: `x`
 --> a.rs:2:9
  |
2 |     let x = 1;
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 2 warnings emitted
```

**Comment by davidtwco** [comment]
> I fixed the test failures. The problem was that jobserver warnings are now done via `Handler`, which means they now contribute to the warning count, and that warning count now gets printed at the end of execution.
> 
> I'm quite uncertain about whether this PR should be merged, because it causes us to count this compiler invocation warnings the same as warnings about the code being compiled. The same thing now happens with self-profile warnings, e.g. we used to do this:

I'm not sure that this is an issue. I think these are as much warnings as those about the code being compiled, they're there because the user would probably want to know what those warnings are telling them, and so should be included in the overall count. I'd maybe feel differently if these were warnings that, for some invocations, would just appear unconditionally, but I don't think that's the case here.

**Pull request merged**
