### PR TITLE
Fix `dropping_copy_types` lint from linting in match-arm with side-effects

### PR DESCRIPTION
**Pull request by Urgau**
This PR fixes an issue with the `dropping_copy_types` and `dropping_references` lints when not all patterns that can have side-effects were detected and ignored.

Nearly _fixes_ https://github.com/rust-lang/rust/issues/112653 (will need beta-backport to completely fix the issue)
r? @Nilstrieb

### CODE REVIEW

**Review by Noratrieb — APPROVED** [review]
r=me if CI is green

**Comment by Urgau** [comment]
CI is green but I don't have bors rights.

(and since this is now approved it seems fine to beta nominate it since the lint landed in 1.71)
@rustbot label +beta-nominated

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-07-06/near/372910554)

@rustbot label +beta-accepted

**Pull request merged**
