### PR TITLE
[WIP] Expand all attributes in left-to-right order

### LINKED ISSUE #83331: Expand `#[cfg]` and `#[cfg_attr]` left-to-right for consistency with other attributes
Currently, cfg-stripping is performed before we invoke any proc-macro attributes. This means that `#[my_attr] #[cfg(FALSE)] struct Foo {}` does not invoke `#[my_attr]` at all, instead of invoking it with `#[cfg(FALSE)] struct Foo {}`

See https://github.com/rust-lang/rust/pull/82419/files/fc9d578bc5ada5162f49ed02a547cf87f2456a93#r580718089 for a more detailed example and discussion.

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/83331.
r? @Aaron1011

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by Mark-Simulacrum** [comment]
@craterbot retry-report

**Comment by petrochenkov** [comment]
There's a variety of errors (some of them are strange and I need to check why they happen in more detail), but my impression so far is that we won't be able to do this.
There are too many uses like
```rust
#[generate_something]
#[cfg(FALSE)]
ITEM
```
where "something" is unintentionally generated despite the `cfg(FALSE)`, and is producing errors.

We should be able to report warnings for out-of-order expansions though (similarly to https://github.com/rust-lang/rust/issues/79202).

I haven't seen regressions from `#[cfg(TRUE)]`s being removed after expansion (they were previously left in place), but, again, I need to look in more detail. Perhaps we'll be able to land at least this part.

**Comment by petrochenkov** [comment]
Analysis of regressions.

Group 1: Proc macro attribute is written before `#[cfg(FALSE)]` so it either doesn't resolve due to missing imports or items introduced by the same `cfg`, or generates some code referring to the ITEM assuming it exists.
Resolved by simple attribute reordering.
```
#[wasm_bindgen] #[cfg(FALSE)] ITEM ++
#[wasm_bindgen_test] #[cfg(FALSE)] ITEM +
#[bench] #[cfg(FALSE)] ITEM +++++++++++
#[global_allocator] #[cfg(FALSE)] ITEM +++
#[ctor] #[cfg(FALSE)] ITEM +
#[tokio::test] #[cfg(feature = "tokio_support")] ITEM +
#[tokio::test] #[cfg(feature = "test")] ITEM +
#[derive(FromPrimitive)] #[cfg(feature = "serde-serialize")] ITEM +
#[derive(MessageEventContent)] #[cfg(feature = "unstable-pre-spec")] ITEM +
#[pin_project] #[cfg(feature = "discover")] ITEM +
```

Group 2: `#[cfg_attr]` disables the legacy derive helper resolution heuristic (#79202) so `#[serde]` no longer resolves.
Resolved by simple attribute reordering.
```
#[serde] #[cfg_attr(TRUE, derive(Serialize))] ITEM +
```

Group 3: `#[test_case]` (https://crates.io/crates/test-case) processes other `#[test_case]` attributes in its input specially, and `#[cfg_attr]`s hide them from it.
Cannot be resolved by simple attribute reordering, needs `#[cfg_eval]`.
```
#[test_case(args)] #[cfg_attr(TRUE, test_case(args))] ++
```

Group 4: Some lints use `item.attrs.is_empty()` as a heuristic, so they start working differently if `#[cfg(TRUE)]` is removed (#84110).
```
#[cfg(TRUE)] { EXPR } // unnecessary braces +
#[cfg(TRUE)] extern crate foo; // `extern crate` is not idiomatic ++
```

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/83824.

**Comment by petrochenkov** [comment]
Superseded by https://github.com/rust-lang/rust/pull/92473.

**Pull request closed without merging**
