### PR TITLE
`ignore-cross-compile` remaining tests that run binaries

### PR DESCRIPTION
**Pull request by Veykril**
Follow up to https://github.com/rust-lang/rust/pull/114958

### CODE REVIEW

**Comment by Veykril** [comment]
(sorry forgot to)
r? @lqd

**Comment by lqd** [comment]
These should be the last ones in your list of ignored tests, right?

**Comment by Veykril** [comment]
Yes, these are the remaining ones

**Comment by lqd** [comment]
cool

@bors r+ rollup

**Pull request merged**
