### PR TITLE
Make Handler more thread-safe

### PR DESCRIPTION
**Pull request by Zoxc**
The use of `code_emitted` to suppress extended explanations is not thread safe. I'm not sure why we keep the documentation for errors outside `diagnostics.rs` anyway. It would be better to add a `teach` method to `DiagnosticsBuilder`, so instead of:
```
if self.tcx.sess.teach(&err.get_code().unwrap()) {
    err.note("...");
}
```
we'd use `err.teach("...")`

cc @estebank

r? @michaelwoerister

### CODE REVIEW

**Comment by shepmaster** [comment]
Ping from review, @michaelwoerister !

**Comment by Zoxc** [comment]
The `Session.one_time_diagnostics` field should probably also be integrated in the `Handler`.

**Comment by pietroalbini** [comment]
Ping from triage @michaelwoerister! This PR still needs your review.

**Comment by Zoxc** [comment]
Actually the scheme used by `one_time_diagnostics` is thread-safe, so I applied it to `taught_diagnostics` (renamed from `tracked_diagnostic_codes`) too.

Neither is compatible with incremental compilation though. @michaelwoerister Do we have a tracking issue for incremental compilation?

**Comment by michaelwoerister** [comment]
@Zoxc We can just add incr. comp. related tasks to #48685, I'd say.

**Comment by pietroalbini** [comment]
Ping from triage @michaelwoerister! What's the status of this PR?

**Pull request merged**
