### PR TITLE
Migrate `pass-linker-flags-flavor`, `pass-linker-flags-from-dep` and `pass-linker-flags` `run-make` tests to rmake

### PR DESCRIPTION
**Pull request by Oneirical**
Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

Please test on i686-msvc. Expected to fail.

try-job: aarch64-apple

### CODE REVIEW

**Comment by Oneirical** [comment]
@rustbot review
Ignore statement restored and reason added. Previous normal CI was green.

**Review by jieyouxu — APPROVED** [review]
Thanks!

**Comment by Oneirical** [comment]
That does not seem related to this PR at all:

```
[RUSTC-TIMING] cargo test:false 18.221
error: failed to remove file `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe`

Caused by:
  Access is denied. (os error 5)
```

Could it be spurious? Would it be worthwhile to try again without changes? @rustbot review

**Comment by jieyouxu** [comment]
We've been having spurious perm issues on windows, it's not ur changes, u can try again

**Pull request merged**
