### PR TITLE
Use SipHash-1-3 instead of SipHash-2-4 for StableHasher

### PR DESCRIPTION
**Pull request by thomcc**
Noticed this, and it seems easy and likely a perf win. IIUC we don't need DDOS resistance (just collision) so we ideally would have an even faster hash, but it's hard to beat this SipHash impl here, since it's been so highly tuned for the interface.

It wouldn't surprise me if there's some subtle reason changing this sucks, as it's so obvious it seems likely to have been done. Still, SipHash-1-3 seems to still have the guarantees StableHasher should need (and seemingly more), and is clearly less work. So it's worth a shot.

Not fully tested locally.

### CODE REVIEW

**Comment by thomcc** [comment]
(Oof, kicked off perf too soon...)

**Comment by Nilstrieb** [comment]
cc @michaelwoerister @cjgillot

**Comment by WaffleLapkin** [comment]
There is only a single perf regression (which is likely due to noise) and a lot of perf wins, so I guess
@rustbot label +perf-regression-triaged

**Comment by cjgillot** [comment]
I don't know anything about hashing functions, but I agree that we don't need DDOS resistance.
The perf results are pretty convincing.
@bors r+

**Comment by thomcc** [comment]
There are also 0 regressions under the "Cycles" view and similar speedups, which is nice to see (it's noisier but more closely corresponds to what users will experience IIUC).

---

As for whether or not this causes problems for us due to being weaker, my understanding is that it should not. I'm not a cryptographer, so someone is free to correct me, but I've done enough work on software involving cryptography to be fairly confident about this much. (Still, @tarcieri might want to weigh in to make sure I'm not blundering here)

My understanding is that the the only valuable property we want out of this hash is a low collision rate when used with a fixed key. This is required to avoid soundness issues, miscompilations, ICEs, and other problems. This means that key-recovery attacks and distinguishers (some of which do apply to other SipHash round choices, but not `1-3`) do not matter at all here.

According to [these](https://www.researchgate.net/publication/280877000_Differential_Cryptanalysis_of_SipHash) [papers](https://eprint.iacr.org/2019/865.pdf), this change allows certain attacks[^3] to find a collision in the internal state in less time.

Specifically, for `SipHash-1-*` there are attacks which cause a collision with probability `2^-167`, but for `SipHash-2-*` the best known attack is probability `2^-236`. (Note that the internal state is 256 bits, and in `SipHash-c-d` the `c` is the number of ARX rounds used when integrating the input with the internal state, and the `d` is the number of rounds used to produce the final output, so for a collision in the internal state only the first number is relevant).

However, we are using a 128 bits of hash output, so the chance of a collision (due to the birthday problem) is `2^-64`, which is true no matter how good of a hash function we use. This means that the change doesn't materially increase collision likelihood — it's still staggeringly unlikely before and after.

---

This does make me wonder why it wasn't done before, but who knows — that code clearly has been optimized quite a bit already, and this seems like the first thing you'd try.

Also, I suspect we could also reduce the output rounds even more, but I suspect a better hash algorithm is a more useful investigation to do, it just has to be implemented really carefully to be an improvement given the way StableHasher is used (an off-the-shelf implementation is almost certainly not going to be an improvement from something this carefully tuned for it's use case).

[^3]: These attacks require actively searching for collisions, rather than just achieving them randomly, so they should just be taken as a bound on the probability. search algorithm driven by the output of the hasher as well, so they're bounds on the actual probability — real-world use should have even fewer collisions.

**Comment by thomcc** [comment]
Oh it got r+ while i was writing that, lol.

**Comment by scottmcm** [comment]
I think this is the easiest "If you can justify the regressions found in this try perf run" I've ever seen 😆

**Comment by michaelwoerister** [comment]
This was discussed a few years ago (see https://github.com/rust-lang/rust/issues/41215). Back then the measured difference between the 1-3 and the 2-4 was very small -- but a lot has changed since then. We just want collision probability to stay roughly the same.

**Comment by Nilstrieb** [comment]
Interesting failure. Maybe the order of the items (`Item` and `Item-1`) was swapped?

**Comment by cjgillot** [comment]
Probably. There are a few instances in the compiler where we sort stuff according to the stable hash. I recommend simply blessing the output.

**Comment by thomcc** [comment]
How do I bless that test's output?

**Comment by Nilstrieb** [comment]
You probably have to manually adjust the comments by hand and swap around the numeric suffixes

**Comment by thomcc** [comment]
I'll do this over the weekend.

@rustbot author

**Comment by nnethercote** [comment]
@thomcc: what's the status here? Is this just waiting for a final r+ to trigger the merge?

**Comment by lqd** [comment]
> what's the status here?

I've checked with @thomcc, they have been busy so I'll help land this in the meantime, and since Thom has done all the work already, it may just require a few back-and-forth with CI. 

So I've rebased and adapted the remaining codegen tests to the new hashes. I've also blessed 2 rustdoc tests, which seem OK to me: some of the conflicting ids have swapped between elements, some intra doc link errors have a slightly different order. rustdoc may depend on hashmap iteration order somewhere leading to these test changes. I'll ask t-rustdoc about them to make sure, and will post an update then.

In the meantime, since this PR has been reviewed already, let's do a final perf run after the rebase (although it seems that a few benchmarks have been noisy recently).

@bors try @rust-timer queue

**Comment by lqd** [comment]
As hoped, the blessed rustdoc tests look acceptable (but show some interesting behavior indeed -- e.g. the trait impls order in the doc looks different from the source file order, but that didn't change in this PR). 

Nothing of substance has changed since the review, so things should be good to go here.

@bors r=cjgillot

**Comment by WaffleLapkin** [comment]
Looks like debuginfo test for function name includes hash of a constant:
https://github.com/rust-lang/rust/blob/be8e5ba157a4ae494f9b4219b3b848e44ea5e8d3/tests/debuginfo/function-names.rs#L81

**Comment by lqd** [comment]
I managed to build a `i686-pc-windows-gnu` target and this rustdoc test passes there. Let's see if it could be spurious.

@bors retry

**Pull request merged**
