### PR TITLE
Improve Box<T> -> Pin<Box<T>> conversion

### LINKED ISSUE #56256: Add `T: ?Sized` to the From<Box<T>> impl for Pin<Box<T>>
Currently, the implementation for `From<Box<T>> for Pin<Box<T>>` is defined as:
```Rust
impl<T> From<Box<T>> for Pin<Box<T>>
```
https://doc.rust-lang.org/beta/std/pin/struct.Pin.html#impl-From%3CBox%3CT%3E%3E

This does not allow trait objects to be pinned. It is however possible to call `Box::pinned`, and convert that into a trait object.

Is it intentional that T is required to be Sized on the From implementation here?

```Rust
impl<T: ?Sized> From<Box<T>> for Pin<Box<T>>
```
allows to call `Pin::from(trait_object)`

### PR DESCRIPTION
**Pull request by Nemo157**
I found the `From` trait conversion for this very hard to find, having a named function for it is much more discoverable. Also fixes #56256 as I need that in the place I'm using this.

Has a placeholder tracking issue, will file an issue once I get feedback.

### CODE REVIEW

**Comment by cramertj** [comment]
I feel sort of odd about having `Box::pin` create a `Pin<Box<_>>` and using `into_pin` to convert a `Box<_>` into a `Pin<Box<_>>`, but it seems basically fine to me. Assigning to a T-libs member to FCP.

r? @alexcrichton

**Comment by alexcrichton** [comment]
Since this is unstable it doesn't need an FCP, but should this also be added to `Rc` and `Arc`?

**Comment by cramertj** [comment]
@alexcrichton No, this method wouldn't be safe on `Rc` and `Arc` because if you have one `Rc<_>` and one `Pin<Rc<_>>` pointing to the same value (which could be created by cloning an `Rc` and using the method you describe) you can use `Pin<Rc<_>>` to witness that the inner value would never be moved, drop the `Pin<Rc<_>>`, then use `Rc::try_unwrap` to move the value out of the remaining `Rc<_>`, which would be unsound.

**Comment by alexcrichton** [comment]
Sure thing

@bors: r=cramertj

**Comment by hellow554** [comment]
Funny enough, today I found this function and asked myself why the heck does it exist? It clearly states, that `From` already does the same, so why having another function doing the same? @Nemo157 what were your reaons apart from "it can be found easier"? Have you ever used it yet? ^^ I'm just curious, because to me it feels verbose and not necessary.

**Comment by Nemo157** [comment]
@hellow554 it's in use here: https://github.com/rust-lang-nursery/futures-rs/blob/8efde615a80aa23ece05d11edbe40db73f326f41/futures-util/src/future/join_all.rs#L119

**Comment by hellow554** [comment]
I see, but `elems.into()` would have done the same. I see the explicitness though... :/ I'm indecisive.

**Comment by Nemo157** [comment]
Yep, but when implementing that originally I didn’t even think of `elems.into()` and just used an unsafe block around `Pin::new_unchecked`, I think I only noticed that `From` worked when adding this method.

**Comment by czipperz** [comment]
If you want to be explicit, you could just use `Pin::from(x)` rather than `x.into_pin()`.

**Comment by Nemo157** [comment]
@czipperz it's interesting that that works, but it's relying on the currently unique implementation of `From<Box<_>>` so could break if any more implementations are added (unless inference constrains the return type to be `Pin<Box<_>>`), e.g. [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c8a8b62b3d3782f826c3e63d4ce181ec).

**Comment by czipperz** [comment]
I misread the code as a method rather than a function.  IE `Pin::from(box)` is equivalent to `Box::into_pin(box)` (as long as other implementations aren't in scope)

**Comment by czipperz** [comment]
I don't think this is really a useful feature to specialize in this way.  Can't you just use the hyper fish operator to disambiguate?

**Comment by czipperz** [comment]
Like do people really implement this sort of functionality?  It seems like there isn't really a reason for this feature to exist imo.

**Pull request merged**
