### PR TITLE
[DO NOT MERGE] [CRATER] Measure future compat migrations

### PR DESCRIPTION
**Pull request by Centril**
Converts miscellaneous future-compat lints to errors for crater measurement.

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
@craterbot check

**Comment by Dylan-DPC** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close -- I don't think we have time to triage this crater run right this moment. But I'll make a note of it locally and try to find time for triage here or find someone who has it.

**Pull request closed without merging**
