### PR TITLE
bump few deps

### PR DESCRIPTION
**Pull request by klensy**
Bumps cargo_metadata, thorin-dwp, windows.

Should dedupe some crates around.

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Bumps LGTM, I'll let Mark double-check though. I'm surprised if nothing breaks especially for `windows` crate bumps from `0.52.0` -> `0.57.0`.

**Comment by klensy** [comment]
Well, compiler builds locally on my win machine; hopefully no stike back from memchr.

**Review by jieyouxu — APPROVED** [review]
Actually since this doesn't touch libs deps, this seems fine.

**Comment by jieyouxu** [comment]
Thanks!
@bors r+ rollup=iffy (bump deps)

**Comment by tgross35** [comment]
@bors retry

CI can't reach docker right now https://github.com/rust-lang/rust/pull/130946#issuecomment-2380048967

**Comment by Kobzol** [comment]
Noise:
image

**Comment by klensy** [comment]
In windows 0.53 (https://github.com/microsoft/windows-rs/releases/tag/0.53.0) was added https://github.com/microsoft/windows-rs/pull/2786 and now rustc_driver links to propsys.dll, but i can't find why it's linked and where actually used yet.

**Pull request merged**
