### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #102092 (refactor: use grep -E/-F instead of fgrep/egrep)
 - #102781 (Improved documentation for `std::io::Error`)
 - #103003 (Fix `suggest_floating_point_literal` ICE)
 - #103039 (checktools: fix comments)
 - #103045 (Remove leading newlines from integer primitive doc examples)
 - #103047 (Update browser-ui-test version to fix some flaky tests)
 - #103054 (Clean up rust-logo rustdoc GUI test)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=102092,102781,103003,103039,103045,103047,103054)

### CODE REVIEW

**Comment by Urgau** [comment]
https://github.com/rust-lang/rust/pull/103054 is failing CI

**Comment by matthiaskrgr** [comment]
Maybe they should be randomly removed then :|

**Comment by TaKO8Ki** [comment]
This is again because of https://github.com/rust-lang/rust/pull/103003. I cancelled r+ in it.

**Pull request closed without merging**
