### PR TITLE
Add use of bool::then in sys/unix/process

### PR DESCRIPTION
**Pull request by wcampbell0x2a**
Remove `else { None }` in favor of using `bool::then()`

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Nice! Thanks

**Comment by joshtriplett** [comment]
Could you please check how this affects codegen? I expect it to produce effectively the same code, but I would like to make sure.

**Comment by wcampbell0x2a** [comment]
> Could you please check how this affects codegen? I expect it to produce effectively the same code, but I would like to make sure.

Never done that but willing to learn it. What commands do I run for that?

**Comment by dtolnay** [comment]
Identical according to https://rust.godbolt.org/z/TY5Y39fxr.

**Comment by wcampbell0x2a** [comment]
> Identical according to https://rust.godbolt.org/z/TY5Y39fxr.

sweet

**Pull request merged**
