### PR TITLE
Rollup of 18 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #26778, #27084, #27127, #27131, #27140, #27146, #27147, #27151, #27154, #27155, #27156, #27157, #27158, #27164, #27166, #27167, #27170, #27175
- Failed merges:

### CODE REVIEW

**Comment by steveklabnik** [comment]
re-rolling up with @apasel422 's fix

**Comment by apasel422** [comment]
686d326 didn't update the compile-fail test for #21174. I'll submit a PR in a sec.

**Comment by apasel422** [comment]
Done in #27202.

**Comment by steveklabnik** [comment]
whoops, making a new one then

**Pull request closed without merging**
