### PR TITLE
Hexagon libstd: update type defs

### PR DESCRIPTION
**Pull request by androm3da**

### CODE REVIEW

**Comment by androm3da** [comment]
Whoops: I normally use editors with rustfmt-on-save but I was just using a host where that's not setup yet.

**Comment by androm3da** [comment]
Ping?

**Comment by androm3da** [comment]
@withoutboats could you take a look or delegate if you get a chance?

**Review by dtolnay — APPROVED** [review]
Stamping without particular scrutiny on the basis that:

- Change only affects `cfg(target_arch = "hexagon")`
- All this was originally added by you in #62814.
- Hexagon is a Tier 3 platform so whatever happens happens.

**Pull request merged**
