### PR TITLE
[WIP] Never type experiments

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This currently just rebases https://github.com/rust-lang/rust/pull/79470 (hopefully all correctly), but will "soon" follow up with an implementation as per https://github.com/rust-lang/lang-team/issues/60#issuecomment-814509681.

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
As an update - I just pushed the new v2 fallback algorithm we had originally discussed; this currently doesn't quite pass tests in-tree but does address some of the known cases the v1 fallback algorithm failed at. 

Niko and I spent a bit of time discussing possible solutions to the problems v2 brings up but didn't arrive at anything concrete yet.

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

Let's get a perf run kicked off for now and get artifacts for a possible crater run.

**Comment by Mark-Simulacrum** [comment]
@craterbot check

**Comment by Mark-Simulacrum** [comment]
Latest commit refactors the code to avoid depending so strongly on the pending obligations to determine inference - this was deemed a "bad idea" in discussions with Niko due to worry over additional select_obligations_where_possible calls introducing inference changes.

It also adds a new [test](https://github.com/Mark-Simulacrum/rust/blob/never-type-fallback-new/src/test/ui/never_type/fallback-closure-wrap.rs) representing one of the failing test cases on Crater (well, likely more than one crate, but the point stands). The problem seems to be that inference is unable to see/learn from the object cast to determine that the output type *must* be `()`; we still fall back but we shouldn't. It might be the ordering of check_casts *after* type_inference_fallback here -- https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/mod.rs#L614-L623

**Comment by Mark-Simulacrum** [comment]
I'll look at using the deferred cast checks as part of the fallback for never type specifically. That might be easy enough...

**Comment by Mark-Simulacrum** [comment]
@bors try

Let's get a try build going -- the latest commit should fix a few of the regressions observed in the last crater run. I want to add some more tests for the other cases observed of breakage -- I think not all of them are probably fixed -- but this should let us make some progress.

**Comment by Mark-Simulacrum** [comment]
@craterbot check

**Comment by jackh726** [comment]
@Mark-Simulacrum what's the plan here? Are you planning to split out some of this into more PRs? I can definitely try to review some, especially code that was mostly written by Niko :)

**Comment by Mark-Simulacrum** [comment]
Yeah, the next steps are:

* Split some more work out, probably, into smaller PRs -- likely will ask for your review on most of these
* Document the algorithm in this PR (Niko's + some further adjustments since then)
* T-lang discussion + potential stabilization report

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close this -- work is proceeding in https://github.com/rust-lang/rust/pull/88804 and this isn't useful to keep open for now.

**Pull request closed without merging**
