### PR TITLE
Implement excluding a build-step via --exclude

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
First step to fixing https://github.com/rust-lang/rust/issues/47911. This doesn't change any CI configuration, but implements what I believe necessary to make that feasible in rustbuild.

In theory this should be sufficient to allow someone to open a PR against .travis.yml and appveyor.yml which splits the Windows 32-bit tests and maybe the OS X tests into multiple builders (depending on what our cost-concerns are) to reduce runtimes.

r? @alexcrichton 
cc @kennytm

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This will need a refactor of how we make multi-path default steps work. Waiting-on-author...

**Comment by alexcrichton** [comment]
@Mark-Simulacrum was this ready to go or did you want to queue up some more changes? (it looked ready!)

**Comment by Mark-Simulacrum** [comment]
I think with the latest commits this is ready for review. I have another branch with more work but that's separate and not quite ready.

**Comment by aidanhs** [comment]
@bors p=1
We're getting the three hour timeouts on non-windows builds (#48192) and our queue is growing - would be good to get this in soon.

**Comment by aidanhs** [comment]
Many failures, e.g.
```
[00:03:15] + python2.7 ../x.py dist --host armv7-unknown-linux-gnueabihf --target armv7-unknown-linux-gnueabihf
[00:03:16]     Finished dev [unoptimized] target(s) in 0.0 secs
[00:03:17] thread 'main' panicked at '"dist::Mingw" should have at least one pathset', bootstrap/builder.rs:193:13
[00:03:17] note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --host armv7-unknown-linux-gnueabihf --target armv7-unknown-linux-gnueabihf
[00:03:17] Build completed unsuccessfully in 0:00:01
```

**Pull request merged**
