### PR TITLE
Reduce the entry on `src/test/ui` (UI test root)

### PR DESCRIPTION
**Pull request by JohnTitor**
CC #73494, similar to #79776.

r? @petrochenkov

### CODE REVIEW

**Comment by nagisa** [comment]
For what it is worth I always have trouble figuring out whether I should just drop a test at the root or, if not, which directory I should use, when adding a test. Having to deal with a fairly arbitrary limit on number of tests seems like a notable contributor roadblock to me.

**Comment by jyn514** [comment]
@nagisa I think if there's no hard limit this is an improvement. If there are ~100 files to start, then 101 isn't a big deal, it's only an issue because so many have accumulated over time.

**Comment by JohnTitor** [comment]
Note that the current entry is 1571 (vs. the limit is 1580) and this PR's is 1487 (vs. the limit is 1500) so _the limit_ has hardly changed.
The hard limit is useful to reduce the moving work and we could ask the contributor to increase the limit value if needed (e.g., adding a new directory).

**Comment by petrochenkov** [comment]
Two comments:
- "block" in some of the tests moved in https://github.com/rust-lang/rust/pull/80539/commits/c53dd6bd44bff9122d5650971f4f8b28adc62382 is the old (pre-1.0) name for closures, so these tests now test `Fn()` and similar stuff rather than block expressions. Perhaps they can be moved to `src\test\ui\closures` with replacing "block" with e.g. "old-closure" in their names. It's also quite possible that those tests can be safely removed now.
- Looks like `src\test\ui\feature-gates` and `src\test\ui\feature-gate` are merged in this PR. I think the idea of the separation was to have one directory for specific feature gates (whose presence is checked by `src\tools\tidy\src\features.rs`) and another directory for the feature-gating mechanism itself. Merging them can still be better due to reduced confusion though.

**Comment by petrochenkov** [comment]
r=me with or without addressing the comments.

**Comment by JohnTitor** [comment]
> * "block" in some of the tests moved in [c53dd6b](https://github.com/rust-lang/rust/commit/c53dd6bd44bff9122d5650971f4f8b28adc62382) is the old (pre-1.0) name for closures, so these tests now test `Fn()` and similar stuff rather than block expressions. Perhaps they can be moved to `src\test\ui\closures` with replacing "block" with e.g. "old-closure" in their names. It's also quite possible that those tests can be safely removed now.

Makes sense, renamed "block" to "old-closure" and moved to the "closures" dir (didn't remove them just in case).

> * Looks like `src\test\ui\feature-gates` and `src\test\ui\feature-gate` are merged in this PR. I think the idea of the separation was to have one directory for specific feature gates (whose presence is checked by `src\tools\tidy\src\features.rs`) and another directory for the feature-gating mechanism itself. Merging them can still be better due to reduced confusion though.

I think it reduces confusion too, I'm going to merge them but if someone thinks it should be separated, we could revert that commit and rename the dirs to something like `feature-gate-checks` and `feature-gate-itself`.

@bors r=petrochenkov

**Comment by JohnTitor** [comment]
Oops, forgot to bless the tests, @bors r-

**Pull request merged**
