### PR TITLE
Stacked borrows: Support 2 phase borrows

### PR DESCRIPTION
**Pull request by RalfJung**
Some infrastructure needed for Stacked Borrows to be able to handle 2-phase-borros.

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
That's a conflict with https://github.com/rust-lang/rust/pull/56165, rebased and fixed.

@bors retry

**Comment by RalfJung** [comment]
RLS gets broken?
```
---- cmd_changing_workspace_lib_retains_bin_diagnostics stdout ----
thread 'cmd_changing_workspace_lib_retains_bin_diagnostics' panicked at 'assertion failed: `(left == right)`
  left: `String("E0425")`,
 right: `"unused_variables"`', src\tools\rls\tests\tests.rs:402:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---rls-stdout---
Content-Length: 605
```
Can this be spurious?

**Comment by RalfJung** [comment]
@bors r-

Once https://github.com/rust-lang/rust/pull/56305 lands, this will fail because it'll break miri. I'll rebase and add the miri update here.

**Comment by RalfJung** [comment]
Rebased

@bors r=oli-obk

**Comment by jethrogb** [comment]
```
$ git submodule update --init --recursive
fatal: reference is not a tree: 61f20761d3124f5a1b1caee8aa15637cc7f92d8e
Unable to checkout '61f20761d3124f5a1b1caee8aa15637cc7f92d8e' in submodule path 'src/tools/miri'
```

**Comment by jethrogb** [comment]
61f2076 exists in https://github.com/RalfJung/miri/commits/stacked-borrows-2-phase but not in https://github.com/solson/miri/commits/master

**Comment by RalfJung** [comment]
That is strange, because miri was still green after this PR.

But anyway that commit is going to be in master soon.

**Comment by RalfJung** [comment]
Hm actually there was no nightly so it'll take another day at least.

But the commit is in a branch in the main repo now, instead of just a PR.  That should suffice.

**Pull request merged**
