### PR TITLE
liballoc: mark str.to_owned() and String::from(&str) as #[inline].

### LINKED ISSUE #53681: String::from and str::to_owned are not inlined
```rust
#![crate_type="rlib"]

pub fn banana() -> String {
    String::from("")
}

pub fn peach() -> String {
    "".to_owned()
}

pub fn expected() -> String {
    unsafe {
    String::from_utf8_unchecked("".as_bytes().to_owned())
    }
}
```

[Playground](https://play.rust-lang.org/?gist=545f458fc407027ad54f901a40dce418&version=nightly&mode=release&edition=2015) (Use show assembly or llvm-ir, make sure to turn on optimisations)

All these functions should be equivalent.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Fixes #53681

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I didn't notice any benchmarks regressing and it size increase of binaries seem to be below 1% in average but perhaps this should get a perf run anyway, just to be extra sure.

**Comment by nagisa** [comment]
@rust-timer build 02d7f803200278daaa402a166bde6eb304de5d93

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 02d7f803200278daaa402a166bde6eb304de5d93

**Comment by matthiaskrgr** [comment]
Hmm, still no perf results? :thinking:

**Comment by Mark-Simulacrum** [comment]
It looks like something went wrong during collection; @bors try

**Comment by nagisa** [comment]
@rust-timer build 02d7f803200278daaa402a166bde6eb304de5d93

**Comment by nagisa** [comment]
Lets see if we can repeat rust-timer builds with results of previous try builds :)

**Comment by nagisa** [comment]
Seems like not.

@bors try

**Comment by nagisa** [comment]
@rust-timer build 9aac7ca572e8ba96e99249a1a9d026331374f228

**Comment by nagisa** [comment]
Overall a very slight increase in number of executed instructions, but that says very little.

**Comment by TimNN** [comment]
Ping from triage @bluss / @nagisa: What is the status of this PR?

**Comment by nagisa** [comment]
@bors r+

I’ll r+ this for the following reasons: while the slight increase in number of executed instructions exists, I believe it is a incorrect statistic to look at here. Inlining can easily go one way or the other on that, while also enabling other optimisations (like eliding allocations) that are important for naive code to be more efficient. The specific case in the code(`expected`) provided in the issue is a prime example of such enablement – LLVM elides the code for the allocation altogether, because the information necessary to do so is available in that context.

**Pull request merged**
