### PR TITLE
Modify the buffer position directly when reading leb128 values.

### PR DESCRIPTION
**Pull request by nnethercote**
It's a small but clear performance win.

r? @michaelwoerister

### CODE REVIEW

**Comment by nnethercote** [comment]
The CI results show universal instruction count improvements, but they are smaller than what I saw locally, and spread differently across the benchmarks. Here are the top 10 `check` results on CI:

Benchmark & Profile | Scenario | % Change | Significance Factor
-- | -- | -- | --
ucd check | incr-unchanged | -1.03%? | 2.46x
tuple-stress check | incr-unchanged | -1.00% | 14.85x
coercions check | incr-unchanged | -0.64% | 6.49x
coercions check | incr-patched: println | -0.58% | 5.73x
html5ever check | incr-patched: println | -0.52%? | 2.08x
tokio-webpush-simple check | full | -0.35% | 1.99x
webrender-wrench check | incr-unchanged | -0.34% | 1.74x
wg-grammar check | incr-unchanged | -0.33% | 1.93x
tokio-webpush-simple check | incr-full | -0.27% | 1.69x
regex check | incr-patched: Job | -0.27% | 1.51x

And here they from my local measurements (where I only did `check` builds):

Benchmark & Profile | Scenario | % Change | Significance Factor
-- | -- | -- | --
helloworld check | full | -1.91% | 9.56x
issue-46449 check | incr-unchanged | -1.86% | 9.30x
issue-46449 check | incr-patched: u8 3072 | -1.74% | 8.68x
helloworld check | incr-full | -1.72% | 8.62x
helloworld check | incr-unchanged | -1.69% | 8.43x
deeply-nested check | incr-unchanged | -1.60% | 8.02x
deeply-nested-closures check | incr-unchanged | -1.57% | 7.87x
await-call-tree check | incr-unchanged | -1.55% | 7.74x
helloworld check | incr-patched: println | -1.54% | 7.72x
issue-46449 check | full | -1.53% | 7.63x

I feel like the match-ups between my local measurements and CI measurements are much weaker than they used to be. I wonder if that's because I don't do PGO locally.

**Comment by michaelwoerister** [comment]
Thanks, @nnethercote! Looks good to me.

@bors r+

> I wonder if that's because I don't do PGO locally.

Yeah, I suspect that that plays into it.

**Comment by michaelwoerister** [comment]
I just saw that https://github.com/rust-lang/rust/pull/92604 already includes the changes in this PR. Let's take that instead.

@bors r-

**Comment by michaelwoerister** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/92604

**Pull request closed without merging**
