### PR TITLE
Enable RISC-V atomic compare and swap

### LINKED ISSUE #56564: Enable RISC-V atomic compare and swap
Now that [LLVM has support for atomic CAS on RISC-V](https://reviews.llvm.org/rL347914) it would be good to enable it in rustc for that backend. I think this should just be a matter of updating LLVM (or cherry picking the relevant commit? Not entirely sure how that works) and then [flipping the switch](https://github.com/rust-lang/rust/blob/367e783e6f66a4dba32decdc68a262953d2f3f1b/src/librustc_target/spec/riscv32imac_unknown_none_elf.rs#L31).

### PR DESCRIPTION
**Pull request by fintelia**
Fixes #56564

### CODE REVIEW

**Comment by memoryruins** [comment]
cc #52787 @japaric @dvc94ch

**Comment by nagisa** [comment]
From what I can see the LLVM submodule has not been updated in the past 6 weeks. It doesn’t seem like this should be landed before an LLVM update, but I would be fine with merging this if this PR updated the LLVM submodule as well...

**Comment by nikic** [comment]
@nagisa LLVM was updated in #57675. You probably still have the (now no longer used) pre-monorepo submodule lying around.

**Comment by Centril** [comment]
r? @nagisa 

You r+ it, you own it ;)

**Pull request merged**
