### PR TITLE
Remove caching of closure from transitive relation

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
In practice, transitive relation sets are usually quite small, so caching the closure is not terrible beneficial (and/or it is frequently invalidated). Regardless, performance measurements indicate that this is not a serious regression over the previous state, so it seems reasonable to simplify the code.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, okay. So this is a rather bad appearing regression for wg-grammar (25% instruction counts). However, looking into it a bit more, e.g. by look at [wall-time](https://perf.rust-lang.org/compare.html?start=66bf391c3aabfc77f5f7139fc9e6944f995d574e&end=572a74f4ea21f93cea1bd5d1c73c3b713c386146&stat=wall-time) it seems that we're actually not regressing too badly for any particular crate -- ~200-500ms on average I believe. If we think this Lock might be a problem in a threaded scenario removing it seems fine based on that.

r? @nikomatsakis 


> Niko and I discussed this a bit on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/187679-t-compiler.2Fwg-parallel-rustc/topic/transitive.20relation / https://zulip-archive.rust-lang.org/187679tcompilerwgparallelrustc/68808transitiverelation.html#176407856) and largely came to the conclusion that maybe these sets are so small this doesn't matter.

**Comment by Mark-Simulacrum** [comment]
(I want to simplify the code further by getting rid of `with_closure` and just calling `.closure()` directly, but want to wait on agreement that we should do this before doing that).

**Comment by Mark-Simulacrum** [comment]
We might want self-profile results here so let's rerun with a new commit @bors try @rust-timer queue

**Comment by eddyb** [comment]
Is there even a point in having this abstraction if the transitive closure isn't cached?!

**Comment by eddyb** [comment]
Also, what are the users of this and can they use direct mutation instead of a `Lock`?

**Comment by Mark-Simulacrum** [comment]
> Is there even a point in having this abstraction if the transitive closure isn't cached?!

Not sure I follow you -- certainly the struct has other (useful) methods, caching the closure is a performance optimization only, right?

> Also, what are the users of this and can they use direct mutation instead of a Lock?

It looks like essentially no -- it's possible I could work around it or so but it looks like we end up with lots of pain, mostly due to `&mut self -> &U` keeping the `&mut` "alive".

I wasn't able to do too much to avoid that -- the Lock is how we do so today, since we don't need &mut access then.

**Comment by eddyb** [comment]
> Not sure I follow you -- certainly the struct has other (useful) methods, caching the closure is a performance optimization only, right?

Without looking into its current usecases, the way I'd use such an abstraction is to compute the closure once for N elements and query it M times, *without* quadratic (`N*M` specifically) behavior for the queries.

(I'm not sure what you could do with a transitive relation without knowing its closure, because just the "seed" can't tell you much about the relation as a  whole)

**Comment by eddyb** [comment]
> It looks like essentially no -- it's possible I could work around it or so but it looks like we end up with lots of pain, mostly due to &mut self -> &U keeping the &mut "alive".

What about a `closure` method returning a different type that contains an immutable reference to the original, besides the cached closure, and focus most of the usage on that separate type?

**Comment by Mark-Simulacrum** [comment]
That... could definitely work! I'll look into doing that.

**Comment by Mark-Simulacrum** [comment]
I think a lot of the code that this'll touch is going to be removed in the next few weeks hopefully as we clean up AST/HIR borrowck fully, so I'm going to hold off on making further changes here.

However, one thought that I had is that it seems like we're basically going to need a lock here no matter what if we want truly transparent "lazy" computation of the closure. There's just no way to get around that.

**Comment by nikomatsakis** [comment]
That seems reasonable. I haven't gone to look at where the code is used, so I'm not sure how effective caching "locally" (as I think @eddyb was suggesting) would be. I agree it makes sense to let the old borrowck code go away a bit before digging into this again.

**Comment by Mark-Simulacrum** [comment]
I'll close this in the meantime and we can circle back to it.

**Pull request closed without merging**
