### PR TITLE
Add rustc_codegen_ssa to sysroot

### PR DESCRIPTION
**Pull request by bjorn3**
Outside of rustc you are currently unable to use it.

r? @nikomatsakis (because you r+'ed #55627)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It shouldn't be too hard to wire up rustbuild to copy the ssa dylib into the sysroot; I agree that such a change would be preferable here. I can probably get some instructions up if that would be helpful, @bjorn3 - loosely I'd start looking in src/bootstrap/compiler.rs.

**Comment by alexcrichton** [comment]
I don't personally have an opinion on whether or not this should go in the sysroot. If it should then this PR looks best to me.

**Comment by Mark-Simulacrum** [comment]
@eddyb I think the latest changes should essentially resolve your concerns with regards to compile times; as such I'm r=me on this change since I think it does the sort of "minimal" changeset to make this happen.

**Comment by nikomatsakis** [comment]
@bors r+ 

@eddyb gave their assent [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/rustc_codegen_ssa/near/148057010)

**Pull request merged**
