### PR TITLE
Format all source files in `tests/coverage/`

### PR DESCRIPTION
**Pull request by Zalathar**
Currently we can't automatically enforce formatting on tests (see #125637), but we can at least keep things relatively tidy by occasionally running the formatter manually.

This was done by temporarily commenting out the `"/tests/"` exclusion in `rustfmt.toml`, and then running:
- `x fmt tests/coverage`
- `x test coverage --bless`

(This PR also includes a few cosmetic tweaks to some of the affected files, to convince rustfmt to format them in the way we want.)

@rustbot label +A-code-coverage

### CODE REVIEW

**Comment by Zalathar** [comment]
The coverage tests were mostly already formatted by #120015, but a few things slipped through, and there were a few small differences caused by me not using the compiler's `rustfmt.toml` at that time.

**Comment by lqd** [comment]
I don't know how thorough one would need to look at this, but reading it over it looks good to me, if you want to consider that an r+

**Comment by Zalathar** [comment]
Yeah, these are small cosmetic changes to tests I'm already pretty familiar with, so “looks good” seems like the right level of scrutiny.

**Comment by lqd** [comment]
If we don't want to remove this test suite from the ones ignored for formatting, so that it doesn't regress in the near future until we manage to format more tests, then @bors r+ rollup

It can be done soon enough nbd.

**Comment by fmease** [comment]
bors sleepy @bors r-

**Pull request merged**
