### PR TITLE
str: add cut and cutn methods

### PR DESCRIPTION
**Pull request by 0x1F339**
These methods just wrap replace/replacen and provide a more concise way to remove patterns from strs

### CODE REVIEW

**Comment by jfager** [comment]
This isn’t what I’d expect a string op named [cut](https://en.m.wikipedia.org/wiki/Cut_(Unix)) to do.

**Comment by cool-cool-sweat** [comment]
I don't think there's any general expectation for rust methods' names to have the same behaviour as unix commands, and I think the name cut does make sense for this since it effectively cuts content out of the string according to the provided pattern. But I'm down w/ considering other names. I originally was gonna use remove but decided against it when I remembered String's remove method

**Comment by leodasvacas** [comment]
Is there any previous discussion on this? Seems too trivial to be in `std`.

**Comment by jfager** [comment]
There's no general expectation for rust methods to match unix commands, but they usually either have some precedent or near-match in other ecosystems, or, conversely, conform to Rust's naming conventions for the sorts of operations that are unique to the language.  

Afaik 'cut' doesn't show up in many (any?) other languages' standard libraries, while the unix command is used widely in a similar enough context that I think it's reasonable to hold up as the prevailing prior art for the name in this particular case.

**Comment by clarcharr** [comment]
IMO `replace` returning `String` instead of `Cow<str>` is a mistake, and I'd prefer that this method do that.

Also, a`cut_in_place` would be nice, using `&mut str`.

**Comment by cool-cool-sweat** [comment]
@jfager Point taken. Maybe a name like purge, delete, snip, blank?
@clarcharr So somethin like
```Rust
fn cut<'a, P: Pattern<'a>>(&'a self, pattern: P) -> Cow<'a, str> {
    let result = self.replace(pattern, "");

    match result == self {
        false => result.into(),
        true => self.into()
    }
}
```
? cut_in_place could be useful I guess and I could take a crack at it if cut and cutn get merged
@leodasvacas Yea this is pretty trivial but it'd just be nice to have a more concise way to remove things from strings. As far as I'm aware there's no previous discussions about this

**Comment by clarcharr** [comment]
@cool-cool-sweat yes, but please don't actually write that code; it's less efficient because it still allocates unconditionally.

As far as naming goes, I like `remove_all` and `remove_n`

**Comment by pietroalbini** [comment]
Thank you for this PR @cool-cool-sweat! The triage team will periodically check in to make sure the PR is properly reviewed.

Ping from triage @bluss! This PR needs your review.

**Comment by cool-cool-sweat** [comment]
Gonna close this since there ain't much interest

**Pull request closed without merging**
