### PR TITLE
Update `compiler-builtins` to 0.1.134

### PR DESCRIPTION
**Pull request by saethlin**
I'm modeling this PR after https://github.com/rust-lang/rust/pull/131314.

This pulls in https://github.com/rust-lang/compiler-builtins/pull/713 which should mitigate the problem reported and discussed in https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Hello.20World.20on.20sparc-unknown-none-elf.20crashes

### CODE REVIEW

**Comment by saethlin** [comment]
This time I actually pushed the change
@bors retry

**Comment by tgross35** [comment]
Still not in the queue, does retry silently not work after a force push?

@bors r+

**Pull request merged**
