### PR TITLE
Use FxIndexMap instead FxHashMap to stabilize iteration order in EffectiveVisibilities

### PR DESCRIPTION
**Pull request by michaelwoerister**
Part of [MCP 533](https://github.com/rust-lang/compiler-team/issues/533).

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I'm going to run a callgrind diff on the libc-check-full case to if the small regression is real.

**Comment by michaelwoerister** [comment]
`set_bindings_effective_visibilities` (which uses the map in question) does show up with an instruction count increase for the libc and unused-warnings benchmarks. The code seems to do a bit more work with `FxIndexMap` instead of `FxHashMap`. However, I don't see how that can be changed without a bigger refactoring of code that otherwise does not look like it's in need of refactoring. Using `UnordMap` instead of `FxIndexMap` is non-trivial too, since `EffectiveVisibilities` public exposes an `iter` method that gives access to internal map.

I think the small regression is acceptable, since this is a correctness/incr-comp-hardening fix.

**Comment by cjgillot** [comment]
cc @petrochenkov as this touches effective visibilities.

**Comment by michaelwoerister** [comment]
I just noticed that this is now the last instance of a `HashMap` occurring in a query result, so I pushed https://github.com/rust-lang/rust/pull/121851/commits/7e4bc4a373574ca727254cc7051ee42cb1102e06 which removes and disallows the `HashStable` impl for `HashMap` 🎉

**Comment by petrochenkov** [comment]
Effective visibility changes look ok.
`unused-warnings` and `libc` are stress tests for effective visibilities, so they will regress a bit if `FxIndexMap` is any slower than `FxHashMap`.

**Review by petrochenkov — APPROVED** [review]

**Comment by klensy** [comment]
Gh gone crazy? First posts dated 1 mar, but written as "commented [now](https://github.com/rust-lang/rust/pull/121851#issue-2163392597)".

**Comment by Mark-Simulacrum** [comment]
See https://github.com/rust-lang/rust/pull/121851#issuecomment-1976192758 for justification.

**Pull request merged**
