### PR TITLE
Shrink `token::Lit`'s hash count from usize to u16.

### PR DESCRIPTION
**Pull request by nnethercote**
On 64-bit platforms, this reduces the size of `token::Lit` from 16 bytes to 8 bytes, and reduces the size of `token::Token` from 32 bytes to 24 bytes.

There are two places where I could add overflow checks, and I've marked them with "njn" comments. It's unlikely that there would be more than 65535 '#' marks at the start of a raw string, but I can add a check if you think it's worthwhile.

r? @eddyb

### CODE REVIEW

**Comment by KalitaAlexey** [comment]
What is your motivation? What will it give? How much memory it will save?

**Comment by nnethercote** [comment]
It's more about reducing memory traffic. Fewer bytes written, read, copied, etc.

**Comment by nnethercote** [comment]
@eddyb: I think the compiler now auto-sorts fields to minimize struct size. Is that right? If so, this change shouldn't be necessary.

**Comment by sanxiyn** [comment]
We decided to revert field reordering for now, see #38523.

**Comment by nnethercote** [comment]
Field reordering seems very likely to be turned on at some point, so let's close this.

**Pull request closed without merging**
