### PR TITLE
Add `pub fn ptr_eq(this: &Self, other: &Self) -> bool` to Rc and Arc

### PR DESCRIPTION
**Pull request by SimonSapin**
Servo and Kuchiki have had helper functions doing this for some time.

### CODE REVIEW

**Comment by aturon** [comment]
cc @rust-lang/libs 

I feel like there's some history here -- e.g. [it used to exist](https://github.com/rust-lang/rust/pull/10634/files#diff-ecb0cc9881d32f07a65e70f6161fe341R87) -- but I'm not sure when/why this was removed offhand.

In general I think this is a nice convenience to provide.

**Comment by frewsxcv** [comment]
```
failures:

---- arc::Arc<T>::ptr_eq_0 stdout ----
	error: use of unstable library feature 'arc_ptr_eq': newly added (see issue #0)
  --> <anon>:10:9
   |
10 | assert!(Arc::ptr_eq(&five, &same_five));
   |         ^^^^^^^^^^^
   |
   = help: add #![feature(arc_ptr_eq)] to the crate attributes to enable

error: use of unstable library feature 'arc_ptr_eq': newly added (see issue #0)
  --> <anon>:11:10
   |
11 | assert!(!Arc::ptr_eq(&five, &other_five));
   |          ^^^^^^^^^^^
   |
   = help: add #![feature(arc_ptr_eq)] to the crate attributes to enable

error: aborting due to previous error(s)

thread 'arc::Arc<T>::ptr_eq_0' panicked at 'Box<Any>', src/librustc/session/mod.rs:167
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- rc::Rc<T>::ptr_eq_0 stdout ----
	error: use of unstable library feature 'rc_ptr_eq': newly added (see issue #0)
  --> <anon>:10:9
   |
10 | assert!(Rc::ptr_eq(&five, &same_five));
   |         ^^^^^^^^^^
   |
   = help: add #![feature(rc_ptr_eq)] to the crate attributes to enable

error: use of unstable library feature 'rc_ptr_eq': newly added (see issue #0)
  --> <anon>:11:10
   |
11 | assert!(!Rc::ptr_eq(&five, &other_five));
   |          ^^^^^^^^^^
   |
   = help: add #![feature(rc_ptr_eq)] to the crate attributes to enable

error: aborting due to previous error(s)

thread 'rc::Rc<T>::ptr_eq_0' panicked at 'Box<Any>', src/librustc/session/mod.rs:167


failures:
    arc::Arc<T>::ptr_eq_0
    rc::Rc<T>::ptr_eq_0
```

**Comment by alexcrichton** [comment]
I guess I don't see a reason to *not* have these in the standard library, but conversely I don't see a particular reason to have these in the standard library either. I've written them from time to time as well, but I never felt like there was a footgun or anything, the implementation was pretty clear.

**Comment by Stebalien** [comment]
Here's a more general solution to the same problem (might make a useful crate): https://gist.github.com/61d5a030296ad3d5b0c3ea71c088c836

**Comment by SimonSapin** [comment]
(Side question: I’ve pushed what I think fixes the doctests, but `make check-stage1` is still running. Is there a make invocation that runs just the doctests for a given crate, like `check-stage1-alloc` runs just the unit tests?)

Yes, it is possible and not particularly difficult to implement outside the standard library, but it seems to be a pretty basic operation when dealing with reference-counted or garbage-collected things. Both Python and Java have operators (`is` and `==`, respectively) built into the language for this.

And Rust’s `std` already has plenty of precedent for including small convenience methods that could be implemented outside.

The only (small) footgun that I know of is being tempted to make a single generic function that works for both `Rc<T>` and `Arc<T>`. I’ve written that function, and there is such a thing as *too* generic: it becomes easy to accidentally compare the addresses of `Rc<T> references instead of the referenced `RcInner<T>` or `T`. @Stebalien’s code avoids this problem by introducing a trait with a recursive method, but that requires (today still unstable) trait specialization.

**Comment by aturon** [comment]
> Yes, it is possible and not particularly difficult to implement outside the standard library, but it seems to be a pretty basic operation when dealing with reference-counted or garbage-collected things. 

Agreed. I think we should ship it.

**Comment by brson** [comment]
Functionality seems fine to me. Is `ptr_eq` the right name? I don't see that name anywhere in std today (nor `ref_eq`). Is there really no precedent for this

**Comment by SimonSapin** [comment]
The `ptr` abbreviation has precedent in the `std::ptr` module’s name. The point of this functionality is to use (almost) `<*cont T as PartialEq>::eq` (as opposed to `<T as PartialEq>::eq`).

**Comment by alexcrichton** [comment]
Discussed at libs triage the conclusion was that these seem good to add. @Kimundi also pointed out that this is very similar to https://github.com/rust-lang/rfcs/issues/1155 and we were also thinking it'd be good to add:

```rust
fn std::mem::ptr_eq<T: ?Sized>(a: &T, b: &T) -> bool;
```

@SimonSapin would you be interested in adding those methods as well? Also could you update the tracking issue reference here as well with a fresh issue?

**Comment by SimonSapin** [comment]
Sure, I can add this. Although in the RFC the arguments are `*const T`. (They can be used with `&T` thought coercion, the docs would give examples of this.) Do you want to change them to `&T`? I think `*const T` fits better in the `std::ptr` module and is maybe easier to document.

Should these be three "features" and tracking issues, or just one?

**Comment by sfackler** [comment]
I kind of like `std::ptr::eq(a, b)` now that I think about it. Should be fine ergonomically since we coerce.

**Comment by SimonSapin** [comment]
`std::ptr::eq` is useful to compare `&T` references (coerced to `*const T`).

Just to be clear however, I don’t think it works as a *replacement* for `Arc::ptr_eq` or `Rc::ptr_eq`. For example, `let a: Arc<T> = …; let b: Arc<T> = …; std::ptr::eq(&a, &b)` will end up comparing `*cont Arc<T>` pointers to the `Arc` pointers on the stack, not comparing `*const ArcInner<T>` like `Arc::ptr_eq` would.

I’ll update the PR to add all three.

**Comment by sfackler** [comment]
Oh yeah, we absolutely want all three.

**Comment by SimonSapin** [comment]
Filed https://github.com/rust-lang/rust/issues/36497 and updated the PR.

**Comment by JoeyAcc** [comment]
Could this *reliably* be used to perform an equality check for functions using pointers?

For example, when I cast function refs to `*mut ()` and compare them, it appears to work in both the positive and negative cases, so it does work (at least for now).

**Pull request merged**
