### PR TITLE
rustc: Tweak expansion order of custom derive

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit alters the expansion order of custom macros-1.1 style `#[derive]`
modes. Instead of left-to-right the expansion now happens in three categories,
each of which is internally left-to-right:
- Old-style custom derive (`#[derive_Foo]`) is expanded
- New-style custom derive (macros 1.1) is expanded
- Built in derive modes are expanded

This gives built in derive modes maximal knowledge about the struct that's being
expanded and also avoids pesky issues like exposing `#[structural_match]` or
`#[rustc_copy_clone_marker]`.

cc #35900

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @nrc 

the problem: https://github.com/rust-lang/rust/issues/35900#issuecomment-245978831
proposed solution: https://github.com/rust-lang/rust/issues/35900#issuecomment-246840357

**Comment by nrc** [comment]
While reviewing this it occurred to me that we should deprecate the old style custom derive sooner rather than later. It is unstable, so I don't think we should wait for macros 1.1 to stabilise.

**Pull request merged**
