### PR TITLE
Allow overriding default runtime CC and AR commands at compile time

### PR DESCRIPTION
**Pull request by Keruspe**

### CODE REVIEW

**Comment by Aatch** [comment]
Why is this change being made? What problem are you solving here? This needs to go into the commit message/PR description. Right now you appear to making a change to something that has worked fine for quite a while.

**Comment by alexcrichton** [comment]
I agree that I'd like to see some more motivation here. I generally think environment variables for something like this isn't the greatest solution because it doesn't handle cross compilation well. You don't actually want `CC` to be inherited to **all** compiler invocations because they may not all target the same platform (especially when invoked through Cargo)

**Comment by Keruspe** [comment]
I realize thatthis comes indeed a little bit our of nowhere, let me add some background to it.

The rationale is actually very tightly linked to cross compilation.

I'm one of the exherbo (a source-based distribution) developpers, and we recently added support for cross-compilation at the core of uour distribution. As we wanted everything to be homogeneous, even the native host is considered as being cross-compiled.

To achieve that, all of our toolchain binaries are prefixed with the architecture they target.

this means that binaries such as "cc" or "ar" don't exist at all. "x86_64-pc-linux-gnu-cc" and friends exist though.

Making these defaults configurable at build time would really help (and every language we packages so far allowed to do that)

The env var way was just the simplest solution I came with, but I'm all ears if something better could be done. As for the env method, I'm totally ok not to use CC and AR directly but some other env variables which only aim is that.

**Comment by Aatch** [comment]
Using variables from the configuration system seems like a better way to go. Right now it seems more like somebody is using the `option_env!` macro incorrectly. At least, that was my first thought when I saw the change. Seeing `option_env!("CFG_CC")` would be more clear.

**Comment by Keruspe** [comment]
Will make some tests with configuration variables.

**Comment by alexcrichton** [comment]
Note that you probably don't need to configure `ar` at all as LLVM already has a cross-platform-aware implementation which we use, so the only thing which needs configuring here is the linker. This can already be modified via the `-C linker` flag to the compiler or via [Cargo configuration](http://doc.crates.io/config.html).

One of the problems with something like `CC` for Rust code is that it's not always cross compiled that frequently. Most Cargo builds nowadays end up having a build script somewhere in the dependency tree (dealing with a native library or code generation) which needs to be compiled for the host platform, not the target platform, meaning that the value of `CC` would be wrong. This is why in Cargo you specify the linker per platform rather than a global linker.

**Comment by Keruspe** [comment]
Here is another attempt, using CFG_CC and a newly defined CFG_AR

Note that ar is needed otherwise libraries compilation fail with "could not execute ar"

I know that these are runtime configurable, the point here is not to change that. All the cross compilation toolchains specifying them explicitely will obviously still work.

The point here is to get a rustc with working defaults if cc and ar don't exist.

**Comment by alexcrichton** [comment]
The current master branch of the compiler almost never falls down to the system `ar`, that only happens for nonstandard targets where we don't know the archive format. For that it may be best to just expose `archive_format` in the custom target json so the system doesn't need to have an `ar` tool.

This also means that `CFG_CC` is only read when the compiler is built, not when it's run, which seems especially odd? These sorts of defaults sound like they should be in the custom target fields rather than for all targets.

**Comment by Keruspe** [comment]
When you say that the current master branch almost never falls down to the system ar, is it something new in 1.3/1.4 or is it supposed to already be the case for 1.2 too?

The fact that it's read only at compile time and not at runtime is exactly the point of these changes.

At runtime neither "cc" nor "ar" are available and we do not want our users to have to export some env vars or pass specific options to cargo/rustc for it to work. During compilation, the package manager exports stuff like CC and AR to the correct values which is why I want those to be interpreted at compile time.

For now, we have some dirty sed in the package, while we try to stay as vanilla as possible. That's why I'm trying to do something upstream here.

What would you suggest? If this way is not acceptable, maybe specific configure switch would be ok? like --with-default-runtime-cc=foo or such?

When you speak of the custom target json, what are you referring to exactly? (I must admit I'm quite new to rust, and even newer to the rustc source base). I might be missing an obvious solution

**Comment by alexcrichton** [comment]
Do you know what target you're compiling by default? Is it the standard `x86_64-unknown-linux-gnu` or is it more specialized?

> When you say that the current master branch almost never falls down to the system ar, is it something new in 1.3/1.4 or is it supposed to already be the case for 1.2 too?

This landed relatively recently in 1.3 I believe, it's not in 1.2.

> The fact that it's read only at compile time and not at runtime is exactly the point of these changes.

Hm, ok. One of the differences between `rustc` and `gcc` is that the Rust compiler is more likely to be a cross compiler than any old build of `gcc`. For example all Rust compilers can target any platform, whereas (to the best of my knowledge) `gcc` generally targets only one or two platforms at a time. This means that a compile-time decision about the "default linker" isn't actually quite right because the compiler could be used to target any number of platforms.

> For now, we have some dirty sed in the package, while we try to stay as vanilla as possible. That's why I'm trying to do something upstream here.

I totally agree! Just trying to get a handle on what's going on here!

> What would you suggest? If this way is not acceptable, maybe specific configure switch would be ok? like --with-default-runtime-cc=foo or such?
> 
> When you speak of the custom target json, what are you referring to exactly? (I must admit I'm quite new to rust, and even newer to the rustc source base). I might be missing an obvious solution

If you're using your own custom target triple then you each target can indicate its own custom linker (which sounds like what you want). If you're using the standard triples, though, it looks like we're gonna need a solution that looks something along the lines of this.

**Comment by Keruspe** [comment]
Here is what a configure call by our package looks like (some enable/disable might change as they're configurable, for docs for example, the release channel is configurable too)

```
./configure --target=x86_64-unknown-linux-gnu --prefix=/usr/x86_64-pc-linux-gnu --datadir=/usr/share --mandir=/usr/share/man --release-channel=dev --disable-llvm-assertions --disable-docs --llvm-root=/usr/x86_64-pc-linux-gnu
```

I believe that's the correct way for building for `x86_64-unknown-linux-gnu`

As for the ar stuff, I'm currently testing against 1.2, that would explain why I'm hitting this, if that's changed in 1.3, that fine then.

I didn't know that a single rustc binary could handle cross compilation that well, that's really nice to hear! To clarify things, I just want the default linker for a 64-bits ELF to be the x86_64 linker, hope that makes sense, even with cross-compilation considered.

Maybe we should switch to some `x86_64-pc-linux-gnu` target and provide a specific json for that?

If we want to stick with the standard triple, given the travis failure, I guess we should either support the linker to be `command args` and not just `command` or switch to come specific configure switch validating the value.

**Comment by alexcrichton** [comment]
Hm ok, interesting! Using the default Linux triple makes it a little more difficult to solve, but certainly not insurmountable! I feel that for packaging and distribution purposes that it's generally pretty unlikely for the standard compiler to be used in many cross-compilation situations, so it may not be too bad to just blanket set the default...

Out of curiosity, is the `ld` program prefixed as well? Or does it exist as just vanilla `ld`? Also, how often do you cross compile from 32 to 64-bit or vice versa? 

cc @brson, this will probably end up adding another `./configure` option I think

**Comment by brson** [comment]
@alexcrichton Word. I don't see a better alternative, though I am enduring constant deep despair at the state of our configure script.

Thank god they are not trying to change `--libdir`!

**Comment by brson** [comment]
@eddyb pointed out [this patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rustc/patches/head.patch) for NixOS, which needs this same thing.

**Comment by Keruspe** [comment]
@brson seems to have the same problem that the current patch here though.

Anyway, I hope to be able to update this in a couple of hours

**Comment by Keruspe** [comment]
@alexcrichton does something like this sounds ok ?

Should I squash the commits?

**Comment by alexcrichton** [comment]
Ok, this looks good to me, thanks @Keruspe! Could you also squash the commits together?

**Comment by Keruspe** [comment]
@alexcrichton squashed and rebased

Any chance for this to be in 1.3 or will it have to wait 1.4?

**Comment by alexcrichton** [comment]
@bors: r+ c97759699264c6b1fa0e88420cd3c720df25e594

Thanks! We generally don't backport anything to beta unless absolutely necessary, so this should make its way into 1.4

**Comment by eddyb** [comment]
Since when do we get spurious segfaults on linux?!

**Pull request merged**
