### PR TITLE
Batch up breaking libsyntax changes

### PR DESCRIPTION
**Pull request by Manishearth**
Contains:
- #33125 
- #33041
- #33157

cc https://github.com/rust-lang/rust/issues/31645

### CODE REVIEW

**Comment by tamird** [comment]
bunch of failures in parse-fail in travis; seems legit?

**Comment by Manishearth** [comment]
investigating.

**Comment by petrochenkov** [comment]
Looks like interaction between https://github.com/rust-lang/rust/pull/33041 and recently landed https://github.com/rust-lang/rust/pull/33020
I'll rebase my PR now and fix the errors previously unreported by compiletest.

**Comment by Manishearth** [comment]
perfect, thanks!

**Pull request merged**
