### PR TITLE
Revert "mk: fix some undefined variable warnings"

### PR DESCRIPTION
**Pull request by alexcrichton**
This reverts commit d03712977d7c913044f2b863269c4491d7fa7c36.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This reverts https://github.com/rust-lang/rust/pull/30367 which looks like it unfortunately caused a 1hr long regression in testing time on the bots (compare [this short build](http://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/7881) to [this long build](http://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/7882)).

I may try to investigate later, but seems good to at least get the cycle time back down for now.

cc @tamird 

r? @brson

**Comment by tamird** [comment]
:(

**Pull request merged**
