### PR TITLE
remark that tool MAINTAINERS must be members of the rust-lang org

### PR DESCRIPTION
**Pull request by RalfJung**
I did not check if this is actually the case for the people currently listed there.

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @pietroalbini @kennytm

**Comment by pietroalbini** [comment]
It's not technically right. Org membership alone doesn't allow assigning yourself to an issue, but you need to have at least explicit *read* access to the repository you're being assigned to.

**Comment by RalfJung** [comment]
@pietroalbini and this applies not just when assigning yourself but also when being assigned by someone else?

**Comment by pietroalbini** [comment]
@RalfJung yeah, at the moment the requirements for being assigned to an issue is "being listed on the Collaborators page of the settings or having previously commented on the issue". The latter doesn't apply here though.

**Comment by pietroalbini** [comment]
Included the message in https://github.com/rust-lang/rust/pull/64119. Closing this.

**Pull request closed without merging**
