### PR TITLE
Remove unused trait imports

### PR DESCRIPTION
**Pull request by sanxiyn**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 01fb27f64814dbd2fef755af4fd6197b1fe74240

Were these caught by a lint? One that we don't have turned on?

**Comment by sanxiyn** [comment]
Yes, these were found by #30021. I decided to send this first while debugging the rebase. (It doesn't finish bootstrapping yet.)

**Comment by alexcrichton** [comment]
Neat!

**Pull request merged**
