### PR TITLE
Fix some rustdoc warnings

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus 

cc @steveklabnik

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Waited long enough to make sure that there were no warnings when travis rendered the docs.

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
Travis failed. I suppose it's a dead link.

@bors: r-

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by QuietMisdreavus** [comment]
r=me pending travis

**Pull request merged**
