### PR TITLE
[beta] Rollup backports

### PR DESCRIPTION
**Pull request by emilyalbini**
Cherry-picked:

*  #59257  Update CI configuration for building Redox libraries
*  #58021  Fix fallout from #57667

Rolled up:

*  #59623  [beta] Update cargo

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Removed #59640.

@bors r+

**Comment by kennytm** [comment]
@bors r=pietroalbini

Included the fix https://github.com/rust-lang/rust/pull/59257#pullrequestreview-216396478, which was accidentally lost due to OP rebasing, but the PR was nevertheless merged without re-r+ because it was included in another rollup that contained the pre-force-push commit.

**Comment by kennytm** [comment]
We need to include #59704 here.

**Pull request closed without merging**
