### PR TITLE
Replace any existing `build/host` symlink

### PR DESCRIPTION
**Pull request by jyn514**
This has two advantages:
1. If `build.build` changes between runs, the symlink is no longer silently wrong.
2. If the entire build directory is moved, the symlink is no longer broken because it points to the wrong absolute path.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
> If the entire build directory is moved, the symlink is no longer broken because it points to the wrong absolute path.

Is there a reason we need an absolute path, not a relative one? At least on Linux I know that relative symlink seem to work fine...

**Comment by jyn514** [comment]
No strong reason, but I didn't want to spend time on it when this also fixes the problem just as well.

**Comment by jyn514** [comment]
looks spurious?

```
/Users/runner/work/rust/rust/src/llvm-project/llvm/lib/Target/RISCV/RISCVInstrInfoV.td:1710:11: error: Record `VLOXSEG7EI8_V' does not have a field named `isConvergent'!
```

@bors retry

**Pull request merged**
