### PR TITLE
Updated E0394 & E0422 to new format

### LINKED ISSUE #35692: E0394 needs to be updated to new format
From: src/test/compile-fail/E0394.rs

E0394 needs a span_label, updated title, and a note, changing it from:

```
error[E0394]: cannot refer to other statics by value, use the address-of operator or a constant instead
  --> src/test/compile-fail/E0394.rs:12:17
   |
12 | static B: u32 = A; //~ ERROR E0394
   |                 ^
```

To:

```
error[E0394]: cannot refer to other statics by value
  --> src/test/compile-fail/E0394.rs:12:17
   |
12 | static B: u32 = A; //~ ERROR E0394
   |                 ^ referring to another static by value
   |
   = note: use the address-of operator or a constant instead
```

### PR DESCRIPTION
**Pull request by knight42**
Fixes #35692 and #35700, as part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

Looking good so far.  The next step is to update the unit tests.  There's a quirk in the unit tester in that it will only tests a label if you add at least one NOTE to the unit test.  I talk about it in the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html) in the Extra Credit section.

With the unit tests, we should be good to go.

**Comment by knight42** [comment]
@jonathandturner 
but I ran `python src/bootstrap/bootstrap.py --step check-cfail --stage 1` locally and passed all the tests...

**Comment by jonathandturner** [comment]
@knight42 - I know, it's confusing :-/  You'll need to update the test for the labels to be checked.

**Comment by knight42** [comment]
I have tried to `grep -R E0422 src/test` and `grep -R E0394 src/test`, but got nothing except `compile-fail/E0422.rs` and `compile-fail/E0394.rs`. Should I add extra test?

**Comment by jonathandturner** [comment]
You can just update those two tests.  As long as there are tests that test the label, we're good.

**Comment by knight42** [comment]
@jonathandturner Thanks for your patience. I updated my last commit. Does this look good now?

**Comment by jonathandturner** [comment]
That's exactly the right direction.  Once you do the same for E0422, I think we're ready.

**Comment by knight42** [comment]
should be fixed this time...

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Pull request merged**
