### PR TITLE
[WIP] Add size-limited command interface, take 2

### LINKED ISSUE #40384: std::process::Command no way to handle command-line length limits
The arg method doesn't track the total resulting command-line length and has no way of indicating to clients that the resulting command-line length would exceed the OS's underlying maximum length. This is fine for launching subprocesses with dozens of arguments, but renders it impossible to implement xargs or similar functionality.

Can I suggest a new method 

`fn try_add_arg<S: AsRef<OsStr>>(&mut self, arg: S) -> Option<S>`

with documentation saying that it's only preferable to `arg` when you're wanting multi-kilobyte command-lines?

`try_add_arg` would keep track of the number of args already added, and if the number of args or the resulting length would exceed the OS limits, then it ignores the argument and returns it back to the client. Otherwise it acts like the normal `arg` method and returns None.

### PR DESCRIPTION
**Pull request by Artoria2e5**
This is a reboot of #74549, which aims to fix #40384. I've changed the thing to use one shared `Arg` trait, and there is a working-looking xargs impl. The things to do are:

* [ ] Write tests.
  * Write a test that inserts some very short stuff via the new `maybe` interface and check that they succeed.
  * I want a way to mock the size_max to a smaller value so stuff like `xargs` are more testable. Maybe later.
  * The Windows raw facility needs testing too.
* [ ] Fix TODO (current CommandSized impl needs to reach down to `as_inner_mut()`). Should be a quick thing.
* [ ] Fix TODO regarding the weird string-storage behavior on Windows. Should probably just forget about the args vector, but the new `force_quote` thing will make it the new append-while-adding a sneaky behavior change.

### CODE REVIEW

**Comment by tavianator** [comment]
On Linux at least, you should round up to a multiple of the page size, since the arguments are allocated one page at a time: https://stackoverflow.com/a/46946024/502399

POSIX documents that xargs should subtract an additional 2048 bytes for extra headroom: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/xargs.html

**Review by dtolnay — COMMENTED** [review]
Removing assignment. Please `r?` request review when you need a look.

**Comment by Artoria2e5** [comment]
@tavianator Judging from what FreeBSD xargs is doing, it looks like subtracting a whole page size is the sure way to go. Updated the code, will push after check.

**Comment by tavianator** [comment]
I ran into a situation where ARG_MAX was only two pages, on ppc64le with 64k pages: https://github.com/tavianator/bfs/pull/34.  So don't overestimate by too much, but one page is probably okay.

**Comment by Artoria2e5** [comment]
I can really use some help with the doc beast...

**Comment by Dylan-DPC** [comment]
Closing this due to inactivity

**Pull request closed without merging**
