### PR TITLE
Bump nightly version to 1.52.0

### PR DESCRIPTION
**Pull request by emilyalbini**
cc @rust-lang/release

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-lang/clippy -- it looks like this is a new test added to ensure clippy's version matches rustc's -- for now, can someone provide instructions on the right set of steps to take? In the future it would be great to ping me / release team if you're adding tests that are affected by version numbers and might cause problems during our release cycle.

If we don't hear back by Saturday evening I'm probably going to just disable these tests for now since we need this PR to land.

**Comment by matthiaskrgr** [comment]
Sorry about that, this is my fault.
Original clippy ticket: https://github.com/rust-lang/rust-clippy/issues/6499
Impl pr: https://github.com/rust-lang/rust-clippy/pull/6526

Test location: https://github.com/rust-lang/rust-clippy/blob/master/tests/versioncheck.rs

Basically with rust turning `1.52.0`, the clippy version will need to be `0.1.52`.

If you bump the versions at
https://github.com/rust-lang/rust-clippy/blob/a507c27660d05f37307369d30bee9e82ce3a11e1/Cargo.toml#L3
and
https://github.com/rust-lang/rust-clippy/blob/a507c27660d05f37307369d30bee9e82ce3a11e1/clippy_lints/Cargo.toml#L4
to `0.1.52`, the test should pass again.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

Thanks. I've opened https://github.com/rust-lang/rust-clippy/issues/6683 to track discontinuing this requirement upstream.

**Pull request merged**
