### PR TITLE
Unpin references

### PR DESCRIPTION
**Pull request by cramertj**
I also considered adding an impl for raw pointers as well, but that makes it easy to accidentally have unsound owning-collections that might otherwise be able to project pinned-ness (e.g. `Box`).

cc @RalfJung 

r? @withoutboats

### CODE REVIEW

**Comment by withoutboats** [comment]
@bors r+

I agree

**Comment by withoutboats** [comment]
I am fairly dubious of any data structure that would claim to safely project through raw pointers; I suppose you could create an adequate API but it seems suspicious to claim to "pin" something that you only have a pointer to.

**Comment by RalfJung** [comment]
LGTM. I also agree raw pointers shouldn't be `Unpin`, just like they are not `Send`/`Sync` -- to make people think about it.

The relevant property here is that from a `PinMut<&mut T>` we cannot get a `PinMut<T>`, and similar with `Pin` and shared references. This makes the `impl Unpin` safe.

Note that this would be implementable fairly easily using `map_unchecked`. How high do we think the risk is that someone does this?

**Comment by RalfJung** [comment]
Might it be a good idea to have a macro in libstd that generates a `map_unchecked` which is guaranteed to not deref (if that's possible... it would have to avoid auto-deref)? That'd still be unsafe but less so. (I imagine `unsafe_pinned!` is something like that.)

Then we could add big fat warnings in the `map_unchecked` docs to use that macro instead, and if that does not work, triple-check if what one wants to do is safe.

**Comment by cramertj** [comment]
@RalfJung I could also imagine adding a clippy lint against a deref inside of a `map_unchecked` impl.

**Pull request merged**
