### PR TITLE
Consistently refer to a test's `revision` instead of `cfg`

### PR DESCRIPTION
**Pull request by Zalathar**
Compiletest allows a test file to specify multiple “revisions” (`//@ revisions: foo bar`), with each revision running as a separate test, and having the ability to define revision-specific headers (`//@[foo] ignore-blah`) and revision-specific code (`#[cfg(foo)]`).

The code that implements this feature sometimes uses the term “cfg” instead of “revision”. This results in two confusingly-different names for the same concept, one of which is ambiguous with other kinds of configuration (such as compiletest's own config).

This PR replaces those occurrences of `cfg` with `revision`, so that one name is used consistently.

### CODE REVIEW

**Comment by Zalathar** [comment]
This inconsistency dates all the way back to #32007, when revisions were first implemented.

I can't see a good reason for having multiple terms for the same concept. Perhaps `cfg` was left over from an earlier design, and the implementation code wasn't fully updated afterwards (since it still worked just fine).

**Comment by jieyouxu** [comment]
FYI: in #121370 I'm changing *all* the compiletest directives to use `//@` consistently, so it would be `//@ <directive-name>` and `//@[revision-name] <directive-name>` in rest of `tests/` too.

**Comment by Zalathar** [comment]
Tweaked a couple of comments to be more forward-looking in light of #121370.

**Comment by compiler-errors** [comment]
r? oli-obk

**Pull request merged**
