### PR TITLE
Add pub visibility for methods as well

### LINKED ISSUE #44527: "pub" keyword isn't displayed for methods in rustdoc
It should be displayed like for functions.

Working on it.

cc @QuietMisdreavus

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #44527.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
r=me pending travis

**Comment by ollie27** [comment]
The `head_len` part just above this will need to be updated as well. Also this could do with some tests.

**Comment by QuietMisdreavus** [comment]
@bors r-

Good catch, @ollie27. I hesitated asking for some tests, but it is a good idea.

**Comment by GuillaumeGomez** [comment]
@ollie27: Good catch!

**Comment by GuillaumeGomez** [comment]
However I have no idea how to test it...

**Comment by ollie27** [comment]
I'm not sure how to add tests for the indentation but a simple test like the following would be useful:

```rust
#![crate_name = "foo"]

pub struct Foo;

impl Foo {
    // @has 'foo/struct.Foo.html' '//code' 'pub fn f()'
    pub fn f() {}
}
```

**Comment by QuietMisdreavus** [comment]
I rummaged through the flags available to compiler tests and it looks like we can't add flags to rustdoc (to enable rendering private items), so for now that will have to do.

**Comment by ollie27** [comment]
@QuietMisdreavus do you mean like https://github.com/rust-lang/rust/blob/5dfc84cfa72b405c194228b53c4de3f6474204ec/src/test/rustdoc/empty-mod-private.rs#L12?

**Comment by QuietMisdreavus** [comment]
Um, yes, exactly that. I didn't realize that the compile-flags worked like that. So yeah, that's what i had in mind to be able to test rendering `pub fn` and `fn` distinctly.

**Comment by GuillaumeGomez** [comment]
Oh damn, I forgot to add the test file! Now I see what you're talking about...

**Comment by GuillaumeGomez** [comment]
I added the test.

**Comment by QuietMisdreavus** [comment]
Could you add another bit to the test where it renders a non-pub function without "pub"? You can disable the `strip-private` pass using the suggestion from https://github.com/rust-lang/rust/pull/44554#issuecomment-329557937 above.

**Comment by QuietMisdreavus** [comment]
(the test got updated to include a non-pub method, and travis passed, so:)

@bors r+

**Pull request merged**
