### PR TITLE
Step::replace_one should put a one, not a zero (Issue #41492)

### PR DESCRIPTION
**Pull request by scottmcm**
Turns out all six of the replace_* impls were backwards.

### CODE REVIEW

**Comment by sfackler** [comment]
I haven't really been following the Step trait design, but if these impls were this broken, it seems like the level of testing of that trait is pretty lacking.

**Review by Havvy — APPROVED** [review]

**Comment by carols10cents** [comment]
@sfackler there are some tests in this PR, are you asking for more tests? Just trying to understand what the next steps are on this PR :)

**Comment by sfackler** [comment]
I am trying to understand why these methods exist if no one has noticed for so long that they return the wrong value :)

**Comment by scottmcm** [comment]
For context, I encountered this trying to implement this proposal https://github.com/rust-lang/rfcs/pull/1980 after the discussion in https://github.com/rust-lang/rust/issues/28237#issuecomment-296345921.

As for why it wasn't noticed, it looks like `std` only uses it when producing a `RangeInclusive::Empty`, and apparently nobody ever cared about the value inside that.  (Which I suppose is an interesting argument that the field in that variant is also useless.)

I agree that the Step trait is sub-optimal, but that's already tracked by https://github.com/rust-lang/rust/issues/27741.  I'd propose making this fix and having the "do these methods make sense" discussion there.

**Comment by sfackler** [comment]
This is certainly an improvement on the status quo

@bors r+

**Pull request merged**
