### PR TITLE
Add iterator method .rfold(init, function); the reverse of fold

### PR DESCRIPTION
**Pull request by bluss**
rfold is the reverse version of fold.

Fold allows iterators to implement a different (non-resumable) internal
iteration when it is more efficient than the external iteration implemented
through the next method. (Common examples are VecDeque and .chain()).

Introduce rfold() so that the same customization is available for reverse
iteration. This is achieved by both adding the method, and by having the
Rev\<I> adaptor connect Rev::rfold → I::fold and Rev::fold → I::rfold.

On the surface, rfold(..) is just .rev().fold(..), but the special case
implementations allow a data structure specific fold to be used through for
example .iter().rev(); we thus have gains even for users never calling exactly
rfold themselves.

### CODE REVIEW

**Comment by aturon** [comment]
cc @rust-lang/libs

**Comment by cuviper** [comment]
Note that I added `FlatMap::fold` in #44577 -- it probably deserves `rfold` too.

**Comment by dtolnay** [comment]
What determines whether this goes on the DoubleEndedIterator trait like rfind or on the Iterator trait like rposition?

```rust
fn rfold<B, F>(self, accum: B, f: F) -> B
where
    F: FnMut(B, Self::Item) -> B,
    Self: Sized + DoubleEndedIterator;
```

**Comment by dtolnay** [comment]
Ah, we already had that discussion in #39399 and #39480.

I would be on board with this addition.

**Comment by alexcrichton** [comment]
Seems like a fine addition to me!

**Comment by sfackler** [comment]
SGTM

**Review by dtolnay — APPROVED** [review]
@bluss r=me but please file a tracking issue and include the issue number in the #[unstable].

**Comment by bluss** [comment]
great, done.

@bors r=dtolnay

**Comment by alexcrichton** [comment]
@bors: retry

Looks like this was spuriously canceled? not sure why...

**Pull request merged**
