### PR TITLE
fix overflow due to multiline error span

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by mitaa** [comment]
... oops.

Thanks for fixing this. (I guess adding yet another testcase, here for "end-highlighted-multiline-but-less-than-6-lines-span", would be overkill)

**Comment by oli-obk** [comment]
@mitaa: the testcase would not help, we need to enable debug assertions in travis and homu. The test case for this situation was 10% of compile-fail ;)

**Comment by pnkfelix** [comment]
> we need to enable debug assertions in travis and homu

In particular, I believe we have at least one buildbot that has `--enable-debug` turned one; but I also think it does not run the test suite. See in particular #27010 which suggested adding such a configuration, and https://github.com/rust-lang/rust-buildbot/pull/38 which turned on gating on it (but it does not run `make check`)

**Comment by nikomatsakis** [comment]
@oli-obk seems like it's still worth having focused tests, since many of us (e.g., me) run tests with `--enable-debug-assertions`

**Comment by nikomatsakis** [comment]
But then there is a test? (Also, the travis failures look...bogus to me?)

**Comment by mitaa** [comment]
> But then there is a test? (Also, the travis failures look...bogus to me?)

Yes, but since the code path was never used, due to overflow, it is naturally off by one. (`>=`, instead of `>`)

Currently, running tests locally.. :-(

**Comment by nikomatsakis** [comment]
@mitaa 

> Yes, but since the code path was never used, due to overflow, it is naturally off by one.

I don't understand what you mean by this.

**Comment by mitaa** [comment]
@nikomatsakis 
> I don't understand what you mean by this. 

Sorry, what I basically meant to say was that there is a test for this, that the travis failure is genuine, and that the final necessary fix is probably to change `(hi.line - lo.line) > MAX_SP_LINES`, which is off-by-one, to `(hi.line - lo.line) >= MAX_SP_LINES`

(`make check-stage1-syntax` passes locally for me with this fix)
(need to rerun `make check` due to probably bogus debuginfo test failures)

**Comment by oli-obk** [comment]
Travis likes it now

**Comment by nikomatsakis** [comment]
lgtm!

**Pull request merged**
