### PR TITLE
Expr walking structural match (reopened)

### LINKED ISSUE #62614: indirect_structural_match lint misfiring on enum variant unused in const item
(Spawned off of https://github.com/rust-lang/rust/issues/62411#issuecomment-510604193)

Consider this code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=449daf68183e9566fc106b070fdaeb10)):

```rust
struct Sum(u32, u32);

impl PartialEq for Sum {
    fn eq(&self, other: &Self) -> bool { self.0 + self.1 == other.0 + other.1 }
}

impl Eq for Sum { }

#[derive(PartialEq, Eq)]
enum Eek {
    TheConst,
    UnusedByTheConst(Sum)
}

const THE_CONST: Eek = Eek::TheConst;

pub fn main() {
    match Eek::UnusedByTheConst(Sum(1,2)) {
        THE_CONST => { println!("Hello"); }
        _ => { println!("Gbye"); }
    }
}
```

In stable and beta, it compiles without warning.

In nightly, it compiles with the following diagnostic warning (#62411):

```
warning: to use a constant of type `Sum` in a pattern, `Sum` must be annotated with `#[derive(PartialEq, Eq)]`
  --> src/main.rs:19:9
   |
19 |         THE_CONST => { println!("Hello"); }
   |         ^^^^^^^^^
   |
   = note: #[warn(indirect_structural_match)] on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #62411 <https://github.com/rust-lang/rust/issues/62411>
```

This is probably not what we want for this lint: It is entirely reasonable for the user to assume that the structural_match check is based solely on the ADT's that one encounters when traversing *the const expression itself*, and one should ignore any unused enum variants that are only tangentially related to the const.

### LINKED ISSUE #65466: ICE resolving non-existent PartialEq::Eq from match of const
(Spawned off of https://github.com/rust-lang/rust/issues/61188#issuecomment-518034786 )

Sometimes the code-generation for pattern-matching a `const` will generate a invocation of `PartialEq::eq` (rather than unfolding the structure of that constant inline, which is the usual compilation strategy used in rustc currently...)

The difference between unfolding inline and invoking `PartialEq::eq` is not meant to be observable, because of [RFC 1445][] (c.f. #31434): "Restrict constants in patterns"

[RFC 1445]: https://github.com/rust-lang/rfcs/pull/1445

However, there are cases where rustc's static analysis of the pattern itself was not thorough enough, and it would let patterns through that do end up invoking `PartialEq::eq` on constants that *do not even implement* `PartialEq` in the first place.

We had been relying on the structural-match checking to catch such cases, where we would first run the structural match check, and if we found an ADT that was a non-structural-match, then we would *then* check if the `const` in question even implements `PartialEq`.

But that strategy, of a delayed check for `PartialEq`, does not suffice in every case. Here is an example, taken from @matthewjasper 's [comment](https://github.com/rust-lang/rust/issues/61188#issuecomment-518034786) linked above:

```rust
#![deny(indirect_structural_match)]

#[derive(PartialEq, Eq)]
enum O<T> {
    Some(*const T), // Can also use PhantomData<T>
    None,
}

struct B;

const C: &[O<B>] = &[O::None];

pub fn foo() {
    let x = O::None;
    match &[x][..] {
        C => (),
        _ => (),
    }
}
```

I had been tagging the above test case as being part of #61188, but at this point I think it is confusing matters, because the code/comments/commit messages say things like "this does not yet fix #61188" and it is ambgious whether that message refers to the original bug described by #61188, or the subsequent issue pointed out by @matthewjasper linked above.

So I am allocating a fresh issue to track the matter here.

### PR DESCRIPTION
**Pull request by pnkfelix**
Long awaited fix to #62614; reopened version of PR #66120

The structural-match check is meant to ensure that consts used in patterns only have types that `derive(PartialEq)` (see [RFC 1445]).

[RFC 1445]: https://github.com/rust-lang/rfcs/blob/master/text/1445-restrict-constants-in-patterns.md

Unfortunately the initial code to enforce structural-match was not quite correct, which led to the creation of the indirect_structural_match compatibility lint; see #62411

Doubly unfortunately the initial code to enforce the lint was not quite correct, which led to it being downgraded to allow-by-default and the filing of #62614.

This PR implements a scheme I outlined on #62614: Instead of basing the analysis solely on the type of the given const, it first attempts to prove the const adheres to the structural-match rules by analysis of the HIR representing the const's right-hand side (RHS). It only falls back to analyzing the type when it encounters a sub-expression on the RHS that it deems too complicated to analyze, such as `const fn` invocations; in such cases it then resorts to a type-based analysis.

----

Follow-up work is to do this as a MIR const-qualif pass rather than walking the HIR.

Fix #62614

Fix #65466

### CODE REVIEW

**Comment by varkor** [comment]
Assigning r? @eddyb as the reviewer for https://github.com/rust-lang/rust/pull/66120, as they already have the context.

**Comment by pnkfelix** [comment]
(It’s the same PR as before, just rebased and with fixed `//~ WARN` annotations. I interpret @eddyb ‘s prior comments as an r+, though maybe they would prefer I push a little harder on const-qualif based version first .....)

**Comment by Centril** [comment]
I think we should have a language team meeting about this before merging the PR. It feels like the language is being changed here but without an explicit design / goal / ... communicated.

**Comment by pnkfelix** [comment]
@centril I'm happy to discuss it with the lang team.

I've interpreted this work as being part of a long-term linguistic bug fix to structural match; its still part of the `indirect_structural_match` future-incompatiblity lint (#62411), and is just addressing the implementation problems that led to that lint being downgraded to allow-by-default (#62623).

But since this PR *is* changing that lint from allow-by-default back to warn-by-default, it certainly falls under the T-lang team purview.

**Comment by pnkfelix** [comment]
We discussed this at [last night's T-lang meeting](https://github.com/rust-lang/lang-team/blob/master/minutes/2020-01-02.md#nominated-prs).

The basic consensus was that the lang team generally felt like we should invest more effort in trying to get the MIR-based (i.e. const-qualification) PR #67343 up to the point where we could land it, rather than landing this PR and then having to maintain multiple similar systems, even if this PR today has better diagnostic quality than #67343.

Therefore, I am going to close this PR, and focus my attention on trying to help get PR #67343 to the point where it is good enough to land Iwhich we currently believe is largely a matter of improving the diagnostics and getting it to use the lint infrastructure rather than be a hard error).

**Pull request closed without merging**
