### PR TITLE
[WIP] Check more things for well-formedness

### LINKED ISSUE #21748: &[Trait] should probably not be allowed
This compiles:
```rust
trait Reader {}
fn perform(readers: &[Reader]) -> usize { 0 }
```
and this complains that there is no `len()`:
```rust
trait Reader {}
fn perform(readers: &[Reader]) -> usize { readers.len() }
```

It seems to me like both should fail to compile with an error about sticking DSTs in a slice.

### LINKED ISSUE #25388: Check types in method signatures
We don't check that types in method signatures are well-formed, or even when they are Sized. I mean, this compiles:
```Rust
pub struct U<T: Send+Sync+Copy+::std::fmt::Display>(*const T);

pub trait Trait { }

pub trait OtherTrait {
    fn f(self, u: U<Trait>);
    fn g(self, u: [u8]);
}

impl OtherTrait for () {
    fn f(self, u: U<Trait>) { }
    fn g(self, ref u: [u8]) {}
}

fn main () {}
```

### LINKED ISSUE #25692: [[T]] is allowed in structs
The following construct compiles:

```rust
struct Foo {
 foo: [[u8]],
}
```

Even though `let foo: [[u8]]` doesn't. From my [very limited understanding](https://github.com/rust-lang/rust-by-example/issues/576) this type doesn't make sense, so it'd be nice if the compiler rejected it at the point of definition.

### PR DESCRIPTION
**Pull request by arielb1**
Makes wf check more bounds (hopefully all of them).

Fixes #21748
Fixes #25692
Fixes #25388

Because it makes the rules stricter, this is technically a
[breaking-change]

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm, I think this PR deserves a bit of thought. First, I've never been happy with the `wf` code, and this PR makes me less happy. It seems like we should be adding the knowledge that (e.g.) `(A,B)` requires that `A:Sized` and `B:Sized` into `implicator.rs`, not `wf.rs`, but honestly I have to re-read the code to remember how they interact (and I suspect there is overlap and they should be simplified).

Second, I do think we should consider just when/where to enforce WF and trait requirements (and where to infer region relationships). The current policy is that we enforce all WF/trait requirements "everywhere" except that it is haphazardly enforced; but it's not totally clear to me that this is the best policy. Certainly the changes here seem ergonomically costly. I have to mull this a bit to form my opinion. (Note that enforcing WF in struct definitions, for example, was done deliberately in order to allow us to obviate things like `T:'a` from appearing on lots of fns.) 

In any case, certainly this change is breaking enough that we would want to start considering the steps and mitigation measures from (pending) RFC rust-lang/rfcs#1122.

cc @rust-lang/lang

**Comment by nikomatsakis** [comment]
ps @arielb1 just to be clear, thanks very much for the PR! I'm not intending those previous comments as a critique of the PR per se, just pointing out that we want to think about these changes and approach them the right way.

**Comment by jroesch** [comment]
@nikomatsakis I think it would be good to clean or clarify the relationship between `wf.rs` and `implicator.rs`, a couple of the inconsistencies @kyledewey and I found around the checking of trait requirements seemed to be related.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Pull request closed without merging**
