### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Centril**
@pietroalbini  Remember to look at https://github.com/rust-lang/rust/pull/60672#issuecomment-491084152.

-----------------------------

Successful merges:

 - #60601 (Add a `cast` method to raw pointers.)
 - #60638 (pin: make the to-module link more visible)
 - #60647 (cleanup: Remove `DefIndexAddressSpace`)
 - #60656 (Inline some Cursor calls for slices)
 - #60657 (Stabilize and re-export core::array in std)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by jethrogb** [comment]
Due to #60657, looks main CI is going to fail as well.

**Comment by jethrogb** [comment]
Except dist-various-2 just passed...?

**Comment by jethrogb** [comment]
Oh the use is only in `cfg(test)` code

**Comment by Centril** [comment]
Beta accepted specifically 028e78d93aac664325d7ed49703032bc3ed3c185.

**Pull request merged**
