### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
7 commits in 708383d620e183a9ece69b8fe930c411d83dee27..b4d18d4bd3db6d872892f6c87c51a02999b80802
2023-10-27 21:09:26 +0000 to 2023-10-31 18:19:10 +0000
- refactor(toml): Cleanup noticed on the way to rust-lang/cargo#12801 (rust-lang/cargo#12902)
- feat(trim-paths): set env `CARGO_TRIM_PATHS` for build scripts (rust-lang/cargo#12900)
- feat: implement RFC 3127 `-Ztrim-paths` (rust-lang/cargo#12625)
- docs: clarify config to use vendored source is printed to stdout (rust-lang/cargo#12893)
- Improve the margin calculation for the search command's UI (rust-lang/cargo#12890)
- Add new packages to [workspace.members] automatically (rust-lang/cargo#12779)
- refactor(toml): Decouple parsing from interning system (rust-lang/cargo#12881)

r? ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
<https://github.com/rust-lang/cargo/pull/12881> might be related?

cc @epage, though I think it is just marginal and no action needed.

**Comment by pnkfelix** [comment]
* regressions are to unicode-normalization-opt-incr-patched:println (1.06%) and clar-opt-full (0.81%)
* the regressions to instruction counts seem small but they persist; i.e. this is not transient noise. (It is not clear whether the cost is borne from cargo itself, or if something has changed about how cargo is invoking rustc that incurs this cost.)
* on the other hand, cycle counts and wall time are not impacted at all, which implies to me that this is probably not worth investigating.
* marking as triaged.

@rustbot label: +perf-regression-triaged

**Comment by weihanglo** [comment]
will look into it

**Comment by nnethercote** [comment]
> (It is not clear whether the cost is borne from cargo itself, or if something has changed about how cargo is invoking rustc that incurs this cost.)

The benchmarks measure the time `rustc`/`rustdoc` takes to compile a single crate. Cargo's execution time isn't measured. So "cargo itself" should be impossible as an explanation. "How cargo is invoking rustc" is possible.

**Comment by weihanglo** [comment]
The only thing touches rustc invocation is <https://github.com/rust-lang/cargo/pull/12625>, but it is behind a cargo feature flag `-Ztrim-paths` so shouldn't affect anything IMO.

**Pull request merged**
