### PR TITLE
build-std compatible sanitizer support

### PR DESCRIPTION
**Pull request by tmiasko**
### Motivation

When using `-Z sanitizer=*` feature it is essential that both user code and
standard library is instrumented. Otherwise the utility of sanitizer will be
limited, or its use will be impractical like in the case of memory sanitizer.

The recently introduced cargo feature build-std makes it possible to rebuild
standard library with arbitrary rustc flags. Unfortunately, those changes alone
do not make it easy to rebuild standard library with sanitizers, since runtimes
are dependencies of std that have to be build in specific environment,
generally not available outside rustbuild process. Additionally rebuilding them
requires presence of llvm-config and compiler-rt sources.

The goal of changes proposed here is to make it possible to avoid rebuilding
sanitizer runtimes when rebuilding the std, thus making it possible to
instrument standard library for use with sanitizer with simple, although
verbose command:

```
env CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=-Zsanitizer=thread cargo test -Zbuild-std --target x86_64-unknown-linux-gnu
```

### Implementation

* Sanitizer runtimes are no long packed into crates. Instead, libraries build
  from compiler-rt are used as is, after renaming them into `librusc_rt.*`.
* rustc obtains runtimes from target libdir for default sysroot, so that
  they are not required in custom build sysroots created with build-std.
* The runtimes are only linked-in into executables to address issue #64629.
  (in previous design it was hard to avoid linking runtimes into static
  libraries produced by rustc as demonstrated by sanitizer-staticlib-link
  test, which still passes despite changes made in #64780).

cc @kennytm, @japaric, @firstyear, @choller

### CODE REVIEW

**Comment by Firstyear** [comment]
I have OSX but I'm not sure what a suitable test plan or steps would be here? 

Otherwise I think everything reads pretty reasonably, but I'd want other better people to put their input into the matter :)

**Comment by tmiasko** [comment]
1. The `src/test/run-make-fulldeps` contains basic sanitizer tests.
   I would suggest starting with those. Some of them are gated to be run
   on Linux only, so I would check if this is still required.
2. Following that, I would create a small cargo project with tests that include
   issues that should be reported by given sanitizer, and then test it with
   `-Zsanitize=*`, and then again with `-Zsanitize=*` and `-Zbuild-std`.
3. Repeat above for some real world project. For a thread sanitizer, test
   suites & benchmarks from crossbeam or tokio crates would be great.  I would
   expect to get reports from either of those, so it should be clear if things
   are working on not.

Concrete steps for 3 suitable for x86_64-unknown-linux-gnu:

```
~/rust $ ./x.py build --stage 1
~/rust $ mkdir -p build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/src
~/rust $ ln -sT $PWD build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/src/rust
~/rust $ rustup toolchain link stage1 build/x86_64-unknown-linux-gnu/stage1

# Testing on tokio: 
~/tokio $ cargo clean
~/tokio $ env CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=-Zsanitizer=thread cargo +stage1 test --target x86_64-unknown-linux-gnu
~/tokio $ cargo clean
~/tokio $ env CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=-Zsanitizer=thread cargo +stage1 -Zbuild-std test --target x86_64-unknown-linux-gnu
```

**Comment by nikomatsakis** [comment]
Is there any documentation for how sanitizers work today? I think that before we make any major changes to the setup, I'd like to see that rectified, so that the new design can be described as an update to the documentation. The rustc-guide would be a suitable place for such a thing. We could also hold a design meeting, but I don't think that's necessarily required, since sanitizers are still experimental.

**Comment by Firstyear** [comment]
Honestly, because they are a -Z flag, and thus nightly only, I think that documentation has not emerged because people don't know they exist, can't access them when they need stable, or have developed other work arounds. For example, I'm required to setup RUSTC_BOOTSTRAP=1 in my makefiles to use stable compilers + -Z with sanitizers and FFI.

I also think that because their major value is with FFI, and that requires the C components to always work with sanitizers, there are not many projects currently using them broadly. 

So this all led to the sanitizers being a super niche feature, wildly useful for people like me who has a C code base that is sanitized and able to develop the tricks to use them with Rust FFI, but most people don't have that set of overlapping scenarios to bring this into peoples minds. 

I think that if the first line of the documentation was "you need nightly to use sanitizers" that's already a major barrier to getting this used more broadly. So I think we need to seriously discuss how we get features like this out from behind nightly only.

**Comment by tmiasko** [comment]
@nikomatsakis japaric published user oriented documentation at https://github.com/japaric/rust-san.

Substantial part of it is dedicated to answering the question how to rebuild
and instrument the `std`, and how to ignore false positives generated when
previous step wasn't followed. Those parts should now be unnecessary thanks to
`-Zbuild-std` in cargo and changes proposed here.

I don't think there was any documentation for implementation in rustc, apart
from description on the pull requests and as a part of discussions therein.

Related documentation changes in rustc-guide https://github.com/rust-lang/rustc-guide/pull/466.

**Comment by choller** [comment]
Thanks for working on this. After some discussions in Discord it seems that this PR is the right way to move forward. As you have noticed, my fix for #64629 was not comprehensive. I am still facing issues where sanitizer runtimes are linked to libraries and we still cannot build Firefox with TSan for that reason.

**Comment by nikomatsakis** [comment]
@tmiasko first off, thanks a ton for the [rustc-guide PR]! As I wrote in [my review], I suspect that the 'how to use sanitizer' material would be better off in the src/doc/rustc directory, as part of the "rustc book".  Do you think you could leave a few notes in the rustc-guide describing *how* sanitizer integration works? (like, it seems like we have to link some LLVM libraries somewhere, and we are copying some files around, why are we doing that?) 

My motivation here is that, particularly for these "little used, perenially unstable" features, I'd like to have some notes on how things work so that if we have to fix bugs we have some idea where to start. (Although this sparks an idea for me that maybe, for features like these, we should also have people kind of "sign up" as maintainers that can be pinged if problems arise... right now, we don't have any notion of who those people might be. I presume you'd be up for that?)

[rustc-guide PR]: https://github.com/rust-lang/rustc-guide/pull/466
[my review]: https://github.com/rust-lang/rustc-guide/pull/466#pullrequestreview-302091098

**Comment by tmiasko** [comment]
@ehuss thanks for suggestion, the unstable-book seems more appropriate.  The
`-Zsanitizer` feature itself is unstable, moreover I think it is best
combined with `-Zbuild-std` which is also unstable.

I moved the user oriented parts to unstable-book (new commit here).  The
high-level overview of the implementation was left in rustc-guide with
additional details about building runtimes, copying, and linking them.

@nikomatsakis sure, you cc me on issues related to sanitizers.

**Comment by nikomatsakis** [comment]
@ehuss 

> I just wanted to note that adding unstable documentation to the rustc book is a little unusual, as it doesn't contain any unstable docs right now

Hmm, I'm ok with the unstable book too. I tend to think that means nobody will ever find it there, but maybe that's the point.

**Comment by nikomatsakis** [comment]
To elaborate on my previous comment, by "maybe that's the point" I meant:

* we don't want people to come across unstable content *too* easily
* and if they ask questions, we can point them at the right place

That said, maybe it'd be useful to extend the rustc book with a pointer to the unstable guide to say something like "you can find documentation on unstable options here". I do appreciate the idea of making it extra clear when things are unstable. The same could apply to the self-profile options.

**Comment by nikomatsakis** [comment]
I'm quite satisfied. Thanks again @tmiasko for going to the extra mile to document what's going on, it made reading the PR much easier.

@bors r+

**Comment by mati865** [comment]
I'm not certain but this PR likely failed in the rollup: https://github.com/rust-lang/rust/pull/65587#issuecomment-544100511

```
failed to execute command: "/Users/vsts/agent/2.158.0/work/1/s/build/x86_64-apple-darwin/llvm/build/bin/llvm-config" "--version"
error: No such file or directory (os error 2)
```

**Comment by tmiasko** [comment]
Rebased. Removed conflicting changes to sanitizer-staticlib-link testcase.
Updated to respect dry-run when preparing sanitizer runtimes (it was the
reason for failure in previous rollup).

r? @nikomatsakis

**Comment by RalfJung** [comment]
> The remote name could not be resolved: 'rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com' 

@bors retry

**Comment by tmiasko** [comment]
Rebased. Not sure why homu removed it from queue due to conflicts but didn't comment here.

**Comment by JohnTitor** [comment]
It's a network error.
@bors retry

**Comment by kennytm** [comment]
@bors r-

```
2019-10-27T03:32:32.8176660Z thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "target `aarch64-apple-ios` is not configured as a host, only as a target"', src/libcore/result.rs:1165:5
```

**Comment by tmiasko** [comment]
* Rebased
* Fixed issue where LLVM for incorrect target would be used.
* Fixed issue where sanitizer libraries would not be part of distribution tarballs.

**Comment by tmiasko** [comment]
* Disabled libFuzzer and XRay when building compiler-rt. They are not necessary, and libfuzzer fails to build on x86_64-apple.

**Comment by tmiasko** [comment]
@nikomatsakis could you re-review? Thanks.

**Comment by kennytm** [comment]
@bors r-

```
2019-11-06T18:02:13.8219120Z clang-7: error: cannot use 'cpp-output' output with multiple -arch options
2019-11-06T18:02:13.8228830Z make[2]: *** [projects/compiler-rt/lib/profile/CMakeFiles/clang_rt.profile_osx.dir/GCDAProfiling.c.o] Error 1
2019-11-06T18:02:13.8231720Z make[1]: *** [projects/compiler-rt/lib/profile/CMakeFiles/clang_rt.profile_osx.dir/all] Error 2
```

**Comment by tmiasko** [comment]
Changed to build compiler-rt as a separate project, rather than as a
subproject of LLVM (in commit d843dd6), everything else is just rebased.

**Comment by tmiasko** [comment]
Rebased.

**Comment by kennytm** [comment]
@bors r-

C++ this time...

```
2019-11-09T13:46:49.0441670Z clang-9: error: cannot use 'c++-cpp-output' output with multiple -arch options
```

**Comment by tmiasko** [comment]
I will try to get access to a macOS to reproduce and debug this properly, but let's give it one more try. 

At this point the build process is quite close to the previous working one.
I removed the call to `configure_cmake` (when building sanitizers), since 
I suspect the issue is with compiler and / or compiler launcher configured
there.

**Comment by tmiasko** [comment]
Rebased.

**Comment by tmiasko** [comment]
I reproduced the build issue from `x86_64-apple`: sccache introduces an
incorrect preprocessor execution. The current version should be able to
work around the issue by not using sccache when building sanitizers.

**Comment by JohnCSimon** [comment]
Ping from triage:
@tmiasko - this PR has been idle for a few days, can you post your status?
cc: @nikomatsakis 
Thank you!

**Comment by tmiasko** [comment]
It is waiting for re-review from @nikomatsakis.

**Comment by JohnCSimon** [comment]
Ping from triage:
 @nikomatsakis this PR is waiting on review 
cc: @tmiasko - 

Thank you!

**Comment by tmiasko** [comment]
Rebased.

**Comment by nikomatsakis** [comment]
Actually, I am just starting to catch up on assigned PRs now. =) I reviewed the new commits and they look good to me, but I confess it's not my area of expertise so the review was somewhat cursory. Nonetheless, I'm going to r+, but someone who is more familiar with this part of the code (maybe @kennytm, @Mark-Simulacrum, or @alexcrichton) may prefer to take a look as well. 

@bors r+

**Comment by tmiasko** [comment]
* Fixed issue where a filename rather than a library name was used for `-l` argument to linker on apple target. 
* Removed sanitizer-invalid-cratetype, because instrumenting proc-macro crates is no longer a hard error (even though doing that is most likely undesirable as per docs).

**Comment by tmiasko** [comment]
Rebased

**Comment by tmiasko** [comment]
Rebased without commit that attempted to reenable leak sanitizer testcase.

**Comment by kennytm** [comment]
@bors retry

`macOS dist-x86_64-apple` timed out (?) without any logs.

**Pull request merged**
