### PR TITLE
Downgrade glibc to 2.11.1 for ppc, ppc64 and s390x

### PR DESCRIPTION
**Pull request by msirringhaus**
As discussed in #73782 
I've tested these changes on rust 1.43.0 for all the specified archs and used the resulting binaries to bootstrap building rust 1.43.1.
I've also shortly tested these changes on master on ppc64.

### CODE REVIEW

**Comment by cuviper** [comment]
Looks fine, but I'm going to test these builds myself before approving.

This doesn't actually include ppc64le though -- that's a separate builder based on CentOS 7 headers for glibc 2.17 and kernel 3.10. Upstream glibc didn't actually support ppc64le until 2.19, but Red Hat backported it. It looks like SUSE added ppc64le support in SLES 12, glibc 2.19 and kernel 3.12, right? So I think that target is fine anyway.

**Review by cuviper — APPROVED** [review]
`r=me` after we've clarified endianness -- I'd rather not have a misleading commit message in there.

**Comment by msirringhaus** [comment]
Whoops, yes you are correct about `le` being wrong

**Comment by cuviper** [comment]
```
  failed to fetch `https://github.com/rust-lang/crates.io-index`
```

@bors retry

**Comment by cuviper** [comment]
Same -- I'll try again later.

**Comment by ehuss** [comment]
@bors retry
zlib error

**Comment by cuviper** [comment]
@ehuss is this a known/ongoing issue?

**Comment by ehuss** [comment]
Yep, working on a fix now, closed the tree in the meantime.

**Pull request merged**
