### PR TITLE
Extend intra-doc links documentation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/rust/issues/62834 and of #43466.

r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
I think the wording here could use a lot of work: "It's very useful in case you want to..." doesn't sound right for documentation. Furthermore, I feel like the main use case for this feature is to link to doc sections, like https://doc.rust-lang.org/stable/std/fmt/index.html#positional-parameters , as opposed to linking to specific impls.

**Comment by Manishearth** [comment]
Do you mind if I write some documentation on this and include it in https://github.com/rust-lang/rust/pull/74430 ?

**Comment by GuillaumeGomez** [comment]
No I don't mind, go ahead! Please close this PR once done.

Also, I remember that @jyn514 had some ideas of improvement for the documentation. You might want to talk with them as well. :)

**Comment by Manishearth** [comment]
Rolled text for this into https://github.com/rust-lang/rust/pull/74430

**Pull request closed without merging**
