### PR TITLE
rustdoc: use javascript to layout notable traits popups

### LINKED ISSUE #102576: Notable traits tooltip is laid out underneath subsequent methods
This happens because `contain: layout` (#102253) establishes a new stacking context

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/hir/map/struct.Map.html#method.parent_owner_iter
parent_iter's notable trait tooltip underflowing is_lhs

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #102576

Preview: https://notriddle.com/notriddle-rustdoc-demos/102576-js-notable-trait/std/iter/trait.Iterator.html#method.step_by

## Before

image

## After

image

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It's similar to my approach in https://github.com/rust-lang/rust/pull/91431. I personally like it. What do you think @Manishearth ?

**Comment by Manishearth** [comment]
Seems like a clean way to do this. Not elated about having more JS but I think this is as good a place to have it if any.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Seems fine so let's go!

@bors r+ rollup

**Comment by Manishearth** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/104208#issuecomment-1309346169

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Let's go again!

@bors r+ rollup

**Pull request merged**
