### PR TITLE
LLVM < 3.5 is unsupported since bb18a3c

### PR DESCRIPTION
**Pull request by tamird**
r? @alexcrichton

### CODE REVIEW

**Comment by dotdash** [comment]
Iff this is to be merged, the ifdef'd code in the custom C bindings should
also be removed.
Am 20.04.2015 20:36 schrieb "Tamir Duberstein" <notifications@github.com>:

**Comment by tamird** [comment]
@dotdash done

**Comment by alexcrichton** [comment]
@bors: r+ 8ad5ad4ffc085abca11e82be5ff12707716841f0

Thanks!

**Comment by tamird** [comment]
had an errant `#elif` instead of an `#else`. I don't support r=alexcrichton is going to work...

**Comment by tamird** [comment]
had an errant #elif instead of an #else. I don't suppose @bors r=alexcrichton is going to work...

**Comment by alexcrichton** [comment]
@bors: r+ 01dfdbd

Yeah @bors only recognizes a whitelisted group of reviewers, but pings are good at getting attention :)

**Comment by tamird** [comment]
@alexcrichton had a spurious closing brace; would you re-approve please?

**Pull request merged**
