### PR TITLE
rustdoc: change color of trait types

### LINKED ISSUE #24441: rustdoc: Searching traits in Chrome got color confused
It's hard to recognize the text inside the orange color block:
rustdoc-search-traits

### PR DESCRIPTION
**Pull request by liigo**
Fixes #24441 

Preview:
new-trait-color

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @steveklabnik 

(not much of a UI guy)

**Comment by P1start** [comment]
I personally much prefer the old colour. I’d say that #24441 is really more of a bug in Chrome than anything else—Chrome really shouldn’t expect every website to avoid using a text colour that is close to the orange it uses to highlight search results.

**Comment by steveklabnik** [comment]
I am not a UX person either, so I don't know. I do know that I didn't like the old color much. Let's see how we feel about this, it's always easy to fix to another color if it looks too weird.

**Comment by gkoz** [comment]
> I personally much prefer the old colour. I’d say that #24441 is really more of a bug in Chrome than anything else

Ditto. This feels like a regression.

**Pull request merged**
