### PR TITLE
Greatly improve rustdoc xpath checks

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Before that, we were using the XML parser from the python standard library which was... pretty limited and very nice on invalid XPaths while preventing to use nice features like `//*[text()="whatever"]`. This PR switches to `parsel`.

While doing this switch, I uncovered quite a lot of small bugs, one being in the HTML generated by rustdoc.

One question remains now: is it ok to ask for a new package to be installed (`parsel`) to run `src/test/rustdoc` test suite @Mark-Simulacrum ? If so, I can add a check into bootstrap and update the requirements in the CI.

r? @jyn514

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I looked for packages supporting XPath in python. `parsel` is internally using `lxml` (which is a binding over a C library, so might be problematic on windows...). I unfortunately couldn't find any pure-python package supporting XPath, which is why I'm asking here. But maybe we should simply switch to another language (maybe rust has crates supporting XPath?). I'm not sure what's the best course of action here.

The initial problem was that the standard python lib we use is very bad (as the test fixes just showed) and way too limited.

**Comment by klensy** [comment]
> which is a binding over a C library, so might be problematic on windows...)

`lxml` works on Windows

**Comment by klensy** [comment]
`pip install lxml` works for me. It can be prebuilded binaries (or locally builded with C compiler).

**Comment by GuillaumeGomez** [comment]
Oh cool, well then `parsel` will work just as fine then.

**Comment by Mark-Simulacrum** [comment]
> @Mark-Simulacrum it sounds like you were concerned installing things is a pain - but x.py is already installing a lot of things behind the scenes, right? Is it a big deal to have it run pip install parsel as well?

AFAIK, we do not install anything in x.py that is a library for a different language, the only things x.py 'installs' are the rustc bootstrap binaries (and I suppose you could consider the Cargo packages we fetch to be installations too).

To some extent rustdoc has increasingly had a larger footprint in terms of "tools it wants", which is not entirely unexpected as the tests for it's HTML and JS generation are fairly different in kind from e.g. compiletest which largely has a dependency on "can run binaries" and some LLVM tools for codegen checking. I think if we were to depend on parsel, I would want to do the same as we do for the JS tools we depend on today -- suggest how to install them, but not actually install them on the users behalf.

I think the more tools and other stuff users need to install to run a test suite, the less likely they're to do so -- I would personally be quite wary of adding our first Python dependency for example outside of python's standard library.

> The main argument to switch to another xpath handler here is that the current one is too limited like I showed at the top. Which frustrated me at a few occasions where I wanted to select an item based on its text to then be able to select one of its child.

It's worth noting that this seems like there is probably alternatives to switching to a different library here. For example, it seems plausible that we can expand ourselves upon the baseline support offered by Python's standard library and add in other XPath selectors (e.g., for text-based matching). It looks like upstream already somewhat [supports](https://docs.python.org/3/library/xml.etree.elementtree.html#xpath-support.) the particular thing noted since 3.7 with the `[.='text']` selector, though it isn't a partial matcher. Requiring a somewhat recent Python version seems preferable to a library to me.

I think it's worth making sure there's @rust-lang/rustdoc discussion of the addition of new external dependencies, particularly ones not facilitated by Cargo (i.e., trivial for most people in the rust-lang/rust tree to get).

I'll also note that both kuchiki and lol-html look like they support CSS-based selectors, which as far as I can tell are often sufficient, though seem to be a little less powerful. We could support both CSS and XPath selectors, in theory, and/or migrate to CSS selectors. My guess is that developers are more likely to quickly understand a CSS selector, fwiw.

**Comment by camelid** [comment]
> I'll also note that both kuchiki and lol-html look like they support CSS-based selectors, which as far as I can tell are often sufficient, though seem to be a little less powerful. We could support both CSS and XPath selectors, in theory, and/or migrate to CSS selectors. My guess is that developers are more likely to quickly understand a CSS selector, fwiw.

I agree that CSS selectors are easier to understand, but IIUC, they are much more limited in what they can express than XPath.

At some point, I would like to try a system where you use XPath or CSS selectors to select a section of the DOM and then have it automatically written to a file, kind of like with UI test stderr. Then you could write tests like this:

```rs
// @select decl 'foo/fn.bar.html' 'pre.rust'
fn bar() -> i32 { 123 }
```

And then have a `foo.decl.html` that looks like this:

```html
<pre class="rust ...">
  fn bar() -> <a href="...">i32</a>
</pre>
```

This would allow auto-blessing of tests, making it easier to change rustdoc's UI; and it would enable testing the order of DOM nodes, which would be make writing tests for things like https://github.com/rust-lang/rust/pull/89098#issuecomment-926158532 much easier. Also, I think we could do this with the existing Python library, since we'd be less reliant on fancy XPath syntax.

**Comment by GuillaumeGomez** [comment]
> I wonder if we can use a pure rust library for this and integrate this into compiletest?

I suggested it and @jyn514 did as well. Unfortunately I don't know of any and developing such a pure rust library would take a lot of time.

**Comment by Manishearth** [comment]
The sxd-xpath crate exists.

**Comment by camelid** [comment]
@GuillaumeGomez I think something went wrong the last time you rebased — this PR includes a debuginfo commit, which doesn't seem right :)

**Comment by camelid** [comment]
Just noting that `@snapshot` tests have now landed, which should reduce the necessity of this change somewhat.

**Comment by GuillaumeGomez** [comment]
Unfortunately it doesn't. We still can't select items based on their text content. I needed that recently to count items which had a specific text but couldn't. `@snapshot` would fit considering it would cover a lot of HTML.

**Comment by jyn514** [comment]
I would like to not be responsible for this.

r? @camelid

**Comment by GuillaumeGomez** [comment]
We recently encountered a new issue with the current tool with https://github.com/rust-lang/rust/pull/95813 and `@snapshot`: it only checks the attributes, not the content itself. Meaning if you have `<div       data-something="a"></div>`, we won't be able to check the existence of the extra whitespace in the `<div>` tag because we can't get the "raw" content.

We looked into it with @Urgau and the tool I picked in this PR doesn't fix this issue either so I'd need to pick a completely different one. I'll try to come back to this as soon as possible.

**Comment by camelid** [comment]
Can you explain the issue with `@snapshot`? It should give you the exact content of the div.

**Comment by GuillaumeGomez** [comment]
It doesn't keep the HTML as is, it generates it. So if you have `<div                        id=1></div>`, you can match it against `<div id=1></div>`, preventing us to detect the unwanted whitespaces.

**Comment by GuillaumeGomez** [comment]
It doesn't keep the HTML as is, it generates it. So if you have `<div                        id=1></div>`, you can match it against `<div id=1></div>`, preventing us to detect the unwanted whitespaces.

**Comment by Dylan-DPC** [comment]
Closing this after a discussion with @GuillaumeGomez

**Pull request closed without merging**
