### PR TITLE
Remove static HashSet for default IDs list

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of https://github.com/rust-lang/rust/pull/133345.

Let's see how it impacts performance.

r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm very curious about it too! :)

**Comment by notriddle** [comment]
Doesn't seem to matter at all?

**Comment by GuillaumeGomez** [comment]
Oh well. At least the code is simpler now.

**Comment by Kobzol** [comment]
Yeah, this is a nice cleanup.

**Pull request merged**
