### PR TITLE
Don't leak return value after panic in drop

### LINKED ISSUE #47949: Panics in destructors can cause the return value to be leaked
## STR

```Rust
struct NoisyDrop;
impl Drop for NoisyDrop {
    fn drop(&mut self) {
        println!("dropping a NoisyDrop");
    }
}

impl NoisyDrop {
    fn new() -> Self {
        println!("creating a NoisyDrop");
        NoisyDrop
    }
}

struct PanickyDrop;
impl Drop for PanickyDrop {
    fn drop(&mut self) {
        panic!()
    }
}

fn foo() -> NoisyDrop {
    let p = PanickyDrop;
    NoisyDrop::new()
}

fn main() {
    foo();
}
```

## Expected Result

"creating a NoisyDrop" and "dropping a NoisyDrop" should appear the same number of times

## Actual Result

```
creating a NoisyDrop
thread 'main' panicked at 'explicit panic', src/main.rs:18:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The destructor is ignored.

### PR DESCRIPTION
**Pull request by matthewjasper**
Closes #47949

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Since this adds code, I suspect it's always going to be a regression. I would ignore the incremental benchmarks here, which brings us down to roughly 5% regression on real world codebases. I think given this is a soundness fix (at least arguably) and certainly unintuitive behavior, we should land this (modulo review of the diff itself, which I have not done).

**Review by davidtwco — APPROVED** [review]
Unsure if this is still only intended for checking perf, but LGTM; someone else should also take a look though.

**Comment by pnkfelix** [comment]
nominating for discussion at next T-compiler triage meeting.

I am inclined to swallow the compiler performance regression, but I figure we will be better off talking about it as a team. Also, I think it will be best to land this early in the release cycle, i.e. soon after the next beta is cut.
 * I know it is a soundness fix, which we would normally prioritize, but I would rather take a little bit more time landing this, and potentially beta-backporting it, than have to deal with reverting it from beta later.

**Comment by matthewjasper** [comment]
cc @richkadel for the changes to the coverage output.
@bors r=pnkfelix

**Comment by richkadel** [comment]
@matthewjasper - Run:

```shell
./x.py test src/test/run-make-fulldeps/coverage --bless 
```

Since the MIR structure and/or block numbers seem to have changed, the spanview files need to be regenerated.

Thanks!

**Comment by richkadel** [comment]
@matthewjasper 

FYI, #79109 should (hopefully) land today, and there are new tests that might be affected by this change.

If you can wait until tomorrow, assuming that PR landed, fetch the latest changes into your branch before running with `--bless`, so it will regenerate the expected results on the most up-to-date tests.

**Pull request merged**
