### PR TITLE
Track PGO profiles in depinfo

### PR DESCRIPTION
**Pull request by Kobzol**
This PR makes sure that PGO profiles (`-Cprofile-use` and `-Cprofile-sample-use`) are tracked in depinfo, so that when they change, the compilation session will be invalidated.

This approach was discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Tracking.20PGO.20profile.20files.20in.20cargo).

I tried it locally and it seems that the code is recompiled just with this change, and https://github.com/rust-lang/rust/pull/100413 is not even needed. But it's possible that not everything required is recompiled, so we will probably want to land both changes. 

Another approach to implement this could be to store the PGO profiles in `sess.parse_sess.file_depinfo` when the session is being created, but then the paths would have to be converted to a string and then to a symbol, which seemed unnecessarily complicated.

CC @michaelwoerister

r? @Eh2406

### CODE REVIEW

**Comment by Eh2406** [comment]
Looks reasonable, but I am not a reviewer on the rust repo.

**Comment by michaelwoerister** [comment]
Thanks a lot, @Kobzol! Looks good.

@bors r+ rollup=never (I prefer to not rollup PRs that modify run-make tests -- those are too flaky)

**Comment by Kobzol** [comment]
Fixed the MSVC CI failure.

@rustbot ready

**Comment by Kobzol** [comment]
@michaelwoerister Probably the PR will have to be reapproved.

**Comment by Kobzol** [comment]
PGO is not used when compiling the perf. suite benchmarks and keccak has been bimodal lately, so this is just noise.

@rustbot label: +perf-regression-triaged

**Pull request merged**
