### PR TITLE
Migrate the diagnostics of the rustc_typeck crate

### PR DESCRIPTION
**Pull request by superblaubeere27**
Currently WIP, please don't merge yet.

### CODE REVIEW

**Comment by davidtwco** [comment]
We have a [no merge policy](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy), could you remove the merge commits?

**Comment by superblaubeere27** [comment]
> We have a [no merge policy](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy), could you remove the merge commits?

Sure. I am not that experienced with git though... How do I do that?

**Comment by TwoThreeTwo** [comment]
git rebase -i <sha before the branches diverged>

**Comment by superblaubeere27** [comment]
All of this is a bit more complicated than anticipated... Can I just create a new, fresh PR? 😅

**Comment by davidtwco** [comment]
> All of this is a bit more complicated than anticipated... Can I just create a new, fresh PR? 😅

Yeah, that's fine too.

**Comment by superblaubeere27** [comment]
Closed in favor of #101007

**Pull request closed without merging**
