### PR TITLE
Feature gate `&Void`'s uninhabitedness.

### PR DESCRIPTION
**Pull request by canndrew**
Here's a totally crazy PR which should never be merged.

### CODE REVIEW

**Comment by canndrew** [comment]
Ping @nikomatsakis @arielb1

**Comment by arielb1** [comment]
The non-reference parts seem to be *mostly* uncontroversial, except for the issue that you can't have a match expression in a macro without risking unreachable code warnings. Not sure what is the best way to handle that.

**Comment by Ericson2314** [comment]
This will continue to work, right?
```rust
match void_ref_result {
    Err(e) => ... ,
    Ok(&r) => match r { },
}
```

**Comment by Ericson2314** [comment]
> Not sure what is the best way to handle that. Macro reachability hygiene?

allow unreachable annotation on arm?

**Comment by arielb1** [comment]
> This will continue to work, right?

If it worked before the matchck changes, it should continue working.

> allow unreachable annotation on arm?

The problem is that the change is an hygiene hazard - every `match` of a generic-containing enum in a macro has to be careful not to cause spurious unreachable arm errors. Maybe just disabling unreachable arm errors in cross-crate macros or something would work as a basic form of hygiene.

**Comment by Ericson2314** [comment]
@arielb1 yeah, the current "unhygenic" approach is somewhat analogous to doing a post-monomorphization warning with generics. I feel like maybe you don't always want that to be ignored, but then a use-site "no---really----please warn/error" would suffice.

**Comment by brson** [comment]
This patch does not apply to beta - the inhabitedness mod does not exist. Is this really a beta backport?

**Comment by nikomatsakis** [comment]
@canndrew I just wanted to say thanks for turning this around so quickly.

**Comment by arielb1** [comment]
@brson 

No. it's a 1.16 issue only.

**Pull request merged**
