### PR TITLE
fixed broken links to char

### LINKED ISSUE #32129: Broken links in `String` documentation from `Deref` impl
There are a bunch of links in the [`String` documentation](http://doc.rust-lang.org/nightly/std/string/struct.String.html) page which are broken. The reason for this is that most links are drawn from the documentation of the `str` type at `/std/primitive.str.html` but the `String` page is located at `/std/string/struct.String.html`. This mismatch in depth of paths causes a number of broken links, for example on the [`String::split`](http://doc.rust-lang.org/nightly/std/string/struct.String.html#method.split) method.

Not sure of the best way to fix this, but needs a tracking issue.

### PR DESCRIPTION
**Pull request by r3drock**
fixes https://github.com/rust-lang/rust/issues/32129

### CODE REVIEW

**Comment by redroc** [comment]
The only problem with the links was that the wrong folder was referenced.

**Comment by QuietMisdreavus** [comment]
Writing those links like that now breaks them when they appear on the page for `&str`. The reason i said that we may be able to fix them now is that we can use the "intra doc links" to reference `char` instead of linking to the page. Try removing the lines you changed entirely. That should cause rustdoc to link to the primitive by referencing its type, rather than trying to reference its page.

**Comment by kennytm** [comment]
@bors r-

Broken links, see the comment above.

**Comment by killercup** [comment]
Do we have a have a way to assert this works without checking it out locally?

Assuming that it does work, can I r=QuietMisdreavus this?

**Comment by QuietMisdreavus** [comment]
Seeing as linkchecker failed the first time, and passed this time, i'm okay with assuming this works. I tried building it locally, but i got an unrelated build error when it tried to document (no idea what's going on there). Since it worked for travis, let's see if it works for bors.

@bors r+ rollup

**Pull request merged**
