### PR TITLE
Use binary prefix

### PR DESCRIPTION
**Pull request by JohnBSmith**

### CODE REVIEW

**Comment by JohnBSmith** [comment]
There is more to examine. Run:

```
grep -nr DEFAULT_BUF_SIZE ./
grep -nr KB ./
grep -nr [^A-Za-z_]MB ./
grep -nr [^A-Za-z_]GB ./
grep -nr KiB ./
grep -nr MiB ./
grep -nr GiB ./
```

**Comment by JohnTitor** [comment]
We also use `KB` on `BufWriter`, at least we should change there as well for consistency. @JohnBSmith Could you address it?

r? @JohnTitor

**Comment by crlf0710** [comment]
@JohnBSmith Ping from triage, could you address the comments above? Thanks!

**Comment by JohnCSimon** [comment]
@JohnBSmith - Hi I'm closing this PR is inactive. Please feel free to reopen it if you're going to continue. Thanks!

**Pull request closed without merging**
