### PR TITLE
Use `LitKind::Err` for malformed floats

### PR DESCRIPTION
**Pull request by nnethercote**
#121120 changed `StringReader::cook_lexer_literal` to return `LitKind::Err` for malformed integer literals. This commit does the same for float literals, for consistency.

r? @fmease

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at at time.

**Review by fmease — APPROVED** [review]
r=me with failing test blessed

**Comment by nnethercote** [comment]
I fixed the clippy test. I think the change kind of neuters it, because the path to the crash that was happening is no longer possible. But I don't think that matters much.

@bors r=fmease

**Comment by fmease** [comment]
Bors?

@bors r+

**Pull request merged**
