### PR TITLE
Suggest appropriate place for lifetime when declared after type arguments

### PR DESCRIPTION
**Pull request by estebank**

### CODE REVIEW

**Comment by estebank** [comment]
Note that before this change the parse error was fatal, stopping `rustc` from moving on to the following phases. With this change it recovers gracefully and continues, beyond the visible effect of providing an appropriate suggestion.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Nice! Can we make a rustfix test here?

**Comment by nikomatsakis** [comment]
cc @zackmdavis, seems like something that might interest you

**Comment by nikomatsakis** [comment]
r=me with a rustfix test

**Comment by estebank** [comment]
@nikomatsakis sadly, it seems like rustfix doesn't handle multipart suggestions at all at the moment :-/

**Comment by estebank** [comment]
Filed https://github.com/rust-lang-nursery/rustfix/issues/152. In the meantime, @bors r=nikomatsakis with intent to come back and add `run-rustfix` to this test at a later time.

**Pull request merged**
