### PR TITLE
Remove misleading target feature aliases

### LINKED ISSUE #100752: Consider renaming the `avx512gfni` feature to just `gfni`
While GFNI has (optional) AVX-512 instructions, there is at least one microarchitecture (Tremont) that has GFNI without AVX-512.

This is further confirmed by running:
```
rustc +nightly -Ctarget-feature=+avx512gfni --print cfg | grep target_feature
target_feature="avx512gfni"
target_feature="cmpxchg16b"
target_feature="fxsr"
target_feature="llvm14-builtins-abi"
target_feature="sse"
target_feature="sse2"
target_feature="sse3"
target_feature="ssse3"
```

Unlike other AVX-512 features, `avx512f` is not enabled, so I'm not sure this should be considered an AVX-512 feature.

### PR DESCRIPTION
**Pull request by calebzulawski**
Fixes #100752.  This is a follow up to #103750. These aliases could not be completely removed until rust-lang/stdarch#1355 landed.

cc @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
LGTM, but I believe this needs T-lang signoff since it affects target features. However I do believe these features are still unstable so it should be fine.

**Comment by calebzulawski** [comment]
Yep, they are still unstable.
r? @rust-lang/lang

**Comment by workingjubilee** [comment]
For context for T-lang, since it might be a bit cryptic from the remarks elsewhere:

There are in fact "avx512{gfni, vaes, ...}" instructions and so on, but the x86 CPU denotes that these instructions are available by signaling "both the avx512 bit and the feature bit enabled" when CPUID is queried. For each feature, it signals that "only" the "feature" instructions are available via having the feature bit enabled but the avx512 bit disabled. The exact details of how this works out sometimes varies a little from what I just said since x86 is a very... "evolved, not designed" instruction set architecture.

**Comment by anden3** [comment]
Hi @calebzulawski! What's the status on this PR? I saw you got a review on the sixth of February :)

**Comment by Amanieu** [comment]
This is waiting on T-lang sign-off. Otherwise the PR itself looks fine.

**Comment by nikomatsakis** [comment]
If you want lang team signoff, we need to nominate it for lang-team discussion! See instructions here:

https://lang-team.rust-lang.org/how_to/nominate.html

In particular, can you author a relatively standalone paragraph explaining the question to be answered? Thanks!

**Comment by calebzulawski** [comment]
@rustbot label +I-lang-nominated

When AVX512 support was initially added, these three features (GFNI, VAES, and VPCLMULQDQ) were included as AVX512 features and prefixed with the `avx512` name.  These features are not yet stabilized.

These features do provide AVX512 instructions when paired with the `avx512f` feature, but on their own they do not. This is not just theoretical--some Intel CPUs support e.g. GFNI that only operates on SSE and AVX vectors (without any AVX512 support).  Intel (and LLVM) do not include AVX512 in the names of these features, either.  Having the `avx512` prefix may mislead a user into believing the `avx512f` feature is enabled by these features, which is true for all other AVX512 features.

My previous PR added the more accurate `gfni`, `vaes`, and `vpclmulqdq` target feature names.  This PR introduces a nightly/unstable breaking change by removing the `avx512gfni`, `avx512vaes`, and `avx512vpclmulqdq` aliases for these features.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Discussed in @rust-lang/lang meeting. We feel good about this change, particularly since target feature gives you warnings if things are wrong.

**Comment by nikomatsakis** [comment]
@rfcbot fcp cancel

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Discussed in https://github.com/orgs/rust-lang/teams/lang meeting. We feel good about this change, particularly since target feature gives you warnings if things are wrong.

**Pull request merged**
