### PR TITLE
Add accessors for io::Error's inner Error

### PR DESCRIPTION
**Pull request by sfackler**
The first commit simply forwards `io::Error`'s `cause` implementation to the inner error.

The second commit adds accessor methods for the inner error. Method names mirror those used elsewhere like `BufReader`.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
This all looks good to me, with downcasting on `Error` I think that this'll basically be necessary.

Can you add some tests which exercise the downcasting and the various accessors?

**Comment by sfackler** [comment]
Updated

**Comment by alexcrichton** [comment]
Could you add "requires UFCS to downcast" to one of the `reason` blocks of the `#[unstable]` attributes as well? Other than that though r=me, thanks!

**Pull request merged**
