### PR TITLE
:arrow_up: rust-analyzer 2022-11-28

### PR DESCRIPTION
**Pull request by arcnmx**
The [prior update](https://github.com/rust-lang/rust/pull/104778) included [checkOnSave multiple targets](https://github.com/rust-lang/rust-analyzer/pull/13290), but missed the [fix for the regression it caused](https://github.com/rust-lang/rust-analyzer/pull/13661).

I performed a git subtree merge, not sure if the commit diff noise is normal? This also could be updated further, but I wanted to be conservative for now.

r? @lnicola

### CODE REVIEW

**Comment by fasterthanlime** [comment]
> I performed a git subtree merge, not sure if the commit diff noise is normal? This also could be updated further, but I wanted to be conservative for now.

Could you specify exactly the commands you ran? These are easier to review than the result, for me at least x)

(But at first glance, this looks okay to me - I think we have to do another rust->ra sync right after this gets merged, right? cc @bjorn3)

**Comment by bjorn3** [comment]
Yeah, doing a rust->ra sync immediately helps avoid conflicts on future syncs.

**Comment by lnicola** [comment]
So I never quite got this, what does "immediately" mean here?

 - before another RA -> rust sync is done
 - before anything else gets merged to the rust repository
 - something else?

**Comment by arcnmx** [comment]
> Could you specify exactly the commands you ran? These are easier to review than the result, for me at least x)

```bash
git subtree --prefix=src/tools/rust-analyzer pull rust-analyzer 2022-11-28
git subtree --prefix=src/tools/rust-analyzer merge 2022-11-28 # alternatively
# (same result for either)
```

> Auto-merging src/tools/rust-analyzer/crates/hir-def/src/nameres.rs
> Merge made by the 'ort' strategy.
>
>  src/tools/rust-analyzer/crates/flycheck/src/lib.rs        |  13 +-
>  .../hir-def/src/macro_expansion_tests/builtin_fn_macro.rs |   6 +-
>  .../crates/hir-expand/src/builtin_fn_macro.rs             |  13 +-
>  src/tools/rust-analyzer/crates/hir-expand/src/db.rs       |   2 +-
>  src/tools/rust-analyzer/crates/hir-expand/src/hygiene.rs  |   8 +-
>  src/tools/rust-analyzer/crates/hir-expand/src/lib.rs      | 227 ++++++-------
>  .../ide-assists/src/handlers/add_missing_impl_members.rs  |  99 ++++++
>  .../src/handlers/convert_tuple_struct_to_named_struct.rs  |  43 ++-
>  .../crates/ide-assists/src/handlers/extract_function.rs   | 210 ++++++++++--
>  .../crates/ide-assists/src/handlers/generate_impl.rs      | 411 +++++++++++++++++++-----
>  src/tools/rust-analyzer/crates/ide-assists/src/lib.rs     |   1 +
>  .../crates/ide-assists/src/tests/generated.rs             |  25 +-
>  .../rust-analyzer/crates/ide-completion/src/context.rs    |  28 +-
>  src/tools/rust-analyzer/crates/ide-completion/src/lib.rs  |   1 -
>  .../crates/ide-completion/src/tests/attribute.rs          |  24 ++
>  .../crates/ide-completion/src/tests/special.rs            |  90 +++++-
>  .../ide-db/src/test_data/test_symbol_index_collection.txt | 134 ++------
>  .../rust-analyzer/crates/ide/src/goto_declaration.rs      | 123 ++++++-
>  src/tools/rust-analyzer/crates/ide/src/hover.rs           | 101 +++---
>  src/tools/rust-analyzer/crates/ide/src/hover/render.rs    |  48 ++-
>  src/tools/rust-analyzer/crates/ide/src/hover/tests.rs     |  35 ++
>  .../rust-analyzer/crates/project-model/src/workspace.rs   |  58 ++--
>  .../rust-analyzer/crates/rust-analyzer/src/config.rs      |  20 +-
>  .../rust-analyzer/crates/rust-analyzer/src/handlers.rs    |  14 +-
>  .../rust-analyzer/crates/rust-analyzer/src/reload.rs      |   6 +-
>  src/tools/rust-analyzer/docs/user/generated_config.adoc   |   2 +-
>  src/tools/rust-analyzer/editors/code/package.json         |  10 +-
>  27 files changed, 1306 insertions(+), 446 deletions(-)

**Comment by bjorn3** [comment]
> So I never quite got this, what does "immediately" mean here?

Before a change on the rust-analyzer side is done that changes the same code as was synced here I believe. I believe the issue is that if this sync back isn't done that the merge commit created here by git subtree will conflict with the changes you make in some cases. Personally for cg_clif I sync back before making any change to cg_clif just to be safe.

**Comment by fasterthanlime** [comment]
```
> Auto-merging src/tools/rust-analyzer/crates/hir-def/src/nameres.rs
```

I'm not sure why that one's happening.

---

Re:

> This also could be updated further, but I wanted to be conservative for now.

I _think_ updating to the latest RA (rather than one from 3 weeks ago) is preferable here, due to the extra sync required in the other direction to avoid merge conflicts further down the line.

By picking an earlier version we're just doing an extra ra->rust, rust->ra sync round, as far as I can tell 🤷‍♀️

**Comment by arcnmx** [comment]
> I think updating to the latest RA (rather than one from 3 weeks ago) is preferable here, due to the extra sync required in the other direction to avoid merge conflicts further down the line.

Fair enough, this was just closer to what was already in-tree.

> git subtree --prefix=src/tools/rust-analyzer pull rust-analyzer 2022-12-12
>
> Auto-merging src/tools/rust-analyzer/crates/hir-def/src/nameres.rs
> Auto-merging src/tools/rust-analyzer/crates/hir-ty/src/infer.rs
> Auto-merging src/tools/rust-analyzer/crates/hir-ty/src/method_resolution.rs
> CONFLICT (content): Merge conflict in src/tools/rust-analyzer/crates/hir-ty/src/method_resolution.rs
> Auto-merging src/tools/rust-analyzer/crates/proc-macro-srv/src/abis/abi_sysroot/ra_server.rs
> Automatic merge failed; fix conflicts and then commit the result.

Submitted as #105855, feel free to pick whichever works better!

**Comment by lnicola** [comment]
> Before a change on the rust-analyzer side is done that changes the same code as was synced here I believe. I believe the issue is that if this sync back isn't done that the merge commit created here by git subtree will conflict with the changes you make in some cases.

But that means we have to make sure we don't merge such a change in RA before both syncs are done, right? And it can take a couple of days to get something merged to rust-lang/rust.

**Comment by bjorn3** [comment]
Clippy syncs often get p=1. With that bors generally merges it the same day.

**Comment by fasterthanlime** [comment]
> Clippy syncs often get p=1. With that bors generally merges it the same day.

Assuming most of the actual work on RA gets done during the week, saturday could be an okay day for a ra->rust then rust->ra sync?

**Pull request closed without merging**
