### PR TITLE
Refactored code to access TLS only in case of panic (II)

### LINKED ISSUE #34787: Don't hit thread-local-storage when entering `catch_unwind`
Although TLS is fast, it's not that fast on Windows and we shouldn't be hitting it on the fast path for `catch_unwind`. Right now all we do this for is to reset the panic counter back to 0.

The purpose of this is to allow [code like this](https://github.com/rust-lang/rust/issues/34727#issuecomment-231511425) to work, but thinking more about that I believe that's actually undefined behavior on MSVC. Basically once a panic is initiated you can't initiate another panic for... "reasons". (I'm not 100% clear myself). This definitely seems like a sketchy pattern as well!

So if we *don't* want to enable that pattern, I think we can get away with different management of the panic counter:

* When a panic starts, bump the panic counter. If this indicates a double panic, abort.
* When a `catch_unwind` returns from *catching a panic*, decrease the panic counter. (maybe assert it's 0?)

This way the normal usage of `catch_unwind` where nothing panics should never hit TLS, and we should still be able to use panics as we do today.

### PR DESCRIPTION
**Pull request by nikhilshagri**
Fixes #34787
r? @alexcrichton
Do it **very** carefully this time!

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 0ab8e0eccbe81c929e57e66cf40c24096c8d3bfa

Thanks, and sorry about that!

**Comment by cynicaldevil** [comment]
No problem!

**Comment by Manishearth** [comment]
```

failures:

---- [run-pass] run-pass\panic-recover-propagate.rs stdout ----
	
error: test run failed!
status: exit code: 3221225725
command: PATH="C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2\lib\rustlib\i686-pc-windows-gnu\lib;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-tools\i686-pc-windows-gnu\release\deps;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-rustc\i686-pc-windows-gnu\release\deps;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-test\i686-pc-windows-gnu\release\deps;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-std\i686-pc-windows-gnu\release\deps;C:\mingw-w64\i686-4.9.1-win32-dwarf-rt_v3-rev1\mingw32\bin;C:\Python27;C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\msys64\usr\bin;C:\python27;C:\python27\scripts;C:\program files (x86)\inno setup 5;C:\program files (x86)\CMake\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0" C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\test\run-pass\panic-recover-propagate.stage2-i686-pc-windows-gnu.exe 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

thread '<unknown>' has overflowed its stack

------------------------------------------

thread '[run-pass] run-pass\panic-recover-propagate.rs' panicked at 'explicit panic', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\tools\compiletest\src\runtest.rs:2243
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-pass] run-pass\panic-recover-propagate.rs

test result: FAILED. 2459 passed; 1 failed; 14 ignored; 0 measured



command did not execute successfully: "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-tools\\i686-pc-windows-gnu\\release\\compiletest.exe" "--compile-lib-path" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\bin" "--run-lib-path" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "--rustc-path" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\bin\\rustc.exe" "--rustdoc-path" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\bin\\rustdoc.exe" "--src-base" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\src/test\\run-pass" "--build-base" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\test\\run-pass" "--stage-id" "stage2-i686-pc-windows-gnu" "--mode" "run-pass" "--target" "i686-pc-windows-gnu" "--host" "i686-pc-windows-gnu" "--llvm-filecheck" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\llvm\\build\\bin\\FileCheck.exe" "--host-rustcflags" "-Crpath -O" "--target-rustcflags" "-Crpath -O -Lnative=C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\rust-test-helpers" "--docck-python" "python" "--lldb-python" "python" "--gdb-version" "GNU gdb (GDB) 7.8" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp" "--android-cross-path" ""
expected success, got: exit code: 101
```

https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1785/steps/test/logs/stdio

**Comment by cynicaldevil** [comment]
This might be occurring because when this panic is thrown, another panic already exists.

**Comment by alexcrichton** [comment]
Hm although in that case wouldn't `catch_unwind` set the panic count to 0, and then the `resume_unwind` would bump it back up to 1?

**Comment by cynicaldevil** [comment]
Updated PR as per discussion on IRC.

**Comment by alexcrichton** [comment]
@bors: r+ b36ae59a1b5d5ea3e3dd9b3e48c1c40fc6f002e8

Thansk!

**Comment by alexcrichton** [comment]
@bors: retry

sorry for the number of retries...

**Comment by alexcrichton** [comment]
Hm last few bits of the message -- 

```
test fs::tests::recursive_rmdir ... ok


command did not execute successfully: "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage0/bin\\cargo.exe" "test" "-j" "8" "--target" "i686-pc-windows-gnu" "--release" "--manifest-path" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\src/rustc/std_shim\\Cargo.toml" "--features" " jemalloc" "-p" "std_shim" "-p" "alloc" "-p" "alloc_system" "-p" "build_helper" "-p" "collections" "-p" "core" "-p" "libc" "-p" "panic_abort" "-p" "panic_unwind" "-p" "rand" "-p" "rustc_unicode" "-p" "std" "-p" "unwind"
expected success, got: exit code: 3221225477


thread '<unnamed>' panicked at 'explicit panic', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\libstd\io\buffered.rs:1109
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

Looks suspicious, but also perhaps https://github.com/rust-lang/rust/issues/33434, so I'm gonna retry and see what happens. If it passes on Travis it *should* pass on bors for a patch like this I think...

@bors: retry

**Comment by cynicaldevil** [comment]
@alexcrichton I looked at the source code where this error occurred, and I think two panics are thrown there,which was ok before this patch.  but now that we can't throw two panics at once, this runtime error might be occurring.

**Comment by alexcrichton** [comment]
Oh really? [This is the panic](https://github.com/rust-lang/rust/blob/master/src/libstd/io/buffered.rs#L1109), right? I couldn't find a second...

**Comment by cynicaldevil** [comment]
the comment above it says 'if it panics again' so I thought there might be
two panics.

**Comment by alexcrichton** [comment]
Ah yeah that test is just ensuring that there's no double panic, as that would abort the process

**Comment by cynicaldevil** [comment]
oh ok then.

**Comment by alexcrichton** [comment]
Hm ok, it looks like that may be a legitimate test failure. Although this *may* be caused by libstd panicking in itself so there's multiple `PANIC_COUNT` counters because there are multiple libstd binaries. 

This may just be a case that needs to get moved to a run-pass test, or the panicking infrastructure in libstd needs to call the *other* libstd panicking infrastructure when we're testing it.

That is, when we test libstd, there are two libstd crates in play. The one we're testing and then the one that libtest (the test harness) is linked against. The `panic!` macro is running code in the libstd being tested, but we want it to actually go through the libstd libtest is linked against (so these assertions match up).

I think this should be fixable with a few sprinklings of `#[cfg(test)]` around the panic module, but that may also just be wishful thinking. We can also just move the test in question to a run-pass test.

**Comment by cynicaldevil** [comment]
Ok, I think I found why this might be happening. I went through the logs  and found that the thread had explicitly panicked before, [here](https://github.com/rust-lang/rust/blob/master/src/libcollectionstest/slice.rs#L1120). Imo, this error only occurs when the thread panics *explicitly*.

**Comment by alexcrichton** [comment]
Hm are you sure? That's in collectionstest but the failing log above is from the unit tests in std?

**Comment by cynicaldevil** [comment]
Yes I am. Like I said, I got it from the stdio logs [here](https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1905/steps/test/logs/stdio). Search for `thread '<unnamed>' panicked at 'explicit panic'`, and you should get two results, one where the thread panics for the first time in `libcollectionstest` and the second where it *should* have panicked in `io/buffered.rs`, at the very end of the log.

**Comment by alexcrichton** [comment]
This isn't running libcollectionstest though? It's only running stdtest, and the explicit panic is [this one](https://github.com/rust-lang/rust/blob/9316ae515e2f8f3f497fb4f1559910c1eef2433d/src/libstd/io/buffered.rs#L1109).

**Comment by cynicaldevil** [comment]
No, it has panicked explicitly once before too. Its in the logs. Here I took a screenshot:
screenshot from 2016-07-25 22-07-15

**Comment by alexcrichton** [comment]
Ah yeah but that was actually in a previous test suite which was in an entirely separate binary, so the threads in this case are separate from one another (especially in terms of panicking).

**Comment by cynicaldevil** [comment]
Oh ok. Still, I think its really strange that it has panicked only **once** before.

**Comment by alexcrichton** [comment]
@cynicaldevil out of curiosity, are you able to reproduce this locally? In theory it shouldn't be windows-specific, but the unwinder can do some crazy things sometimes.

**Comment by cynicaldevil** [comment]
I ran `make check`, and yes, I am able to reproduce it. The problem isn't specific to Windows then.

**Comment by alexcrichton** [comment]
Hm interesting! I unfortunately can't reproduce locally. I'm on 64-bit Linux, what platform are you on?

**Comment by cynicaldevil** [comment]
Same.

**Comment by cynicaldevil** [comment]
FWIW I added an `#[ignore]` to the test and ran `make check` again. It successfully panics a few times as required and then crashes at a test in `rand/reader.rs` again, failing to initiate a panic.

**Comment by alexcrichton** [comment]
Weird, and you're running the stdtest binary, right? I've run that a bunch of times with this patch and it's all succeeding. I wonder if perhaps you may just need to rebase on master to pick up a fix related to unwinding?

**Comment by cynicaldevil** [comment]
What do you mean by `stdtest` binary?

**Comment by alexcrichton** [comment]
Oh which test are you running (or how are you running tests) to see the crash?

**Comment by cynicaldevil** [comment]
I just run `make check`, which runs all the tests.

**Comment by alexcrichton** [comment]
Hm ok, @cynicaldevil maybe try rebasing this patch and testing again? An error *like* the one we saw on the bots was fixed in https://github.com/rust-lang/rust/pull/35014, so it may be that fix just paved the way for this as well perhaps?

**Comment by cynicaldevil** [comment]
Nope, rebased and ran the tests again, still fails at the exact same spot.

**Comment by alexcrichton** [comment]
Hm... can you gist the full logs of your `make check` locally?

**Comment by cynicaldevil** [comment]
https://gist.github.com/cynicaldevil/b2b94723af91e6bf840f5fd4758159a3
I also included a backtrace.

**Comment by alexcrichton** [comment]
Hm as a last ditch effort, can you retry with `RUST_TEST_NOCAPTURE=1`?

**Comment by cynicaldevil** [comment]
Here: https://gist.github.com/cynicaldevil/3c23c0ae76f1481416c487d18f48a80d
I think we found the reason:
 `attempted to subtract with overflow', src/libstd/panicking.rs:255`
which is this line:
```
                s.set(prev - 1);
```
since PANIC_COUNT contains a cell reference to usize object, this particular test trying to subtract from the lowest allowed value, which would be zero.

**Comment by alexcrichton** [comment]
Interesting! Did you configure your local checkout with `--enable-debug-assertions`? That may be why I wasn't reproducing on my end.

I think that also means that my [hunch from before](https://github.com/rust-lang/rust/pull/34866#issuecomment-234680742) was correct. When this test panics, it panic with the standard library's machinery that's being tested. The actual panic, however, is then caught with *another* standard library. The standard library catching the panic did not have its `PANIC_COUNT` reset.

This somehow means that we need to deduplicate the panicking mechanisms here. I think the easiest thing to do would be:

* Add `#[cfg(not(test))]` to the definition of the panic macro in `src/libstd/macros.rs`
* Add `#[macro_reexport(panic)]` to the `realstd` extern crate declaration in `src/libstd/lib.rs`

That means that panics during testing should panic through the original standard library.

Again though the easiest thing to do is to just move this test out of the standard library, which should allow this PR to land.

**Comment by cynicaldevil** [comment]
> Interesting! Did you configure your local checkout with --enable-debug-assertions?

Yes, @eddyb recommended me to add them. They turned out to be useful after all!

> Again though the easiest thing to do is to just move this test out of the standard library

This would be a bad idea imo, because there might be other tests where this might be happening. The other solution which you suggested (adding attributes) looks cleaner.

**Comment by alexcrichton** [comment]
Ok, wanna give that a spin and see if it works?

Also this reminds me why it was failing on the bots, they all enable debug assertions!

**Comment by cynicaldevil** [comment]
Well, turns out adding those attributes also brings in a ton of new errors while testing :sweat_smile:. Think I will move the test for now and see what happens.

**Comment by cynicaldevil** [comment]
How should I move the code inside `run-pass`? Should I just move the content inside a main function? And what about the panic?

**Comment by alexcrichton** [comment]
Yeah just throwing it into a `src/test/run-pass` test should be fine, and you can wrap the whole thing in a `catch_panic` for now as well. The test is basically just ensuring that we don't abort the process, which a `catch_panic` should be sufficient to prevent.

**Comment by cynicaldevil** [comment]
Like I suspected, other tests are unable to initiate the panic too. Should I move all such tests into `run-pass`?

**Comment by alexcrichton** [comment]
Hm what sort of magnitude of tests is it turning out to be? If it's a good number them it may be good to rethink the strategy here. This does mean that a *failing* test in libstd will perhaps have a very obscure error message, which is kinda unfortunate.

Could you gist the errors you were getting from the `#[macro_reexport]` stage?

**Comment by cynicaldevil** [comment]
The process aborts after the first failed panic, so there's no way to determine the number. I will post the logs tomorrow, gotta sleep now :)

**Comment by cynicaldevil** [comment]
Here: https://gist.github.com/cynicaldevil/73c94e6c6d7fd9f5345c6f653b319bf9

**Comment by alexcrichton** [comment]
grr I had a feeling it was going to amount to something like that. Ok I think that route may be a dead end. I also believe that this works today because the only global state for panics is the `PANIC_COUNT` counter, and the function just resets it to 0 no matter what.

Another though, let's try:

* Add a function, `bump_panic_count`, to `panicking.rs`
* Mark the function both as unstable and public. Reexport it from `src/libstd/rt.rs` next to the `begin_panic` and `begin_panic_fmt` reexports.
* When we bump the panic counter, do this:

```rust
if cfg!(test) {
    ::realstd::rt::bump_panic_counter();
} else {
    bump_panic_counter();
}
```

I think all other modifications of the panic counter in theory also need to go through this kind of shim, but for now we can make just the increments go that route.

Does that make sense?

**Comment by cynicaldevil** [comment]
Should I do this wherever the panic counter is modified?

**Comment by alexcrichton** [comment]
I think we can get away with just *increments*, not reads and decrements, but yeah otherwise wherever the panic counter is incremented we'll need logic like that instead.

**Comment by cynicaldevil** [comment]
I tried to using the function for increments, then for increments *and* decrements, and neither seem to work.:worried:

**Comment by alexcrichton** [comment]
Hm ok, I tested out [this patch](https://gist.github.com/alexcrichton/d675523400de93e9b8a06118bb7e880b) and was able to get `make check-stage2-std` working. Could you try that out and see if it works for you?

**Comment by cynicaldevil** [comment]
It passes!! :scream: :tada:
I don't understand how though. Why did you change this part [here](https://gist.github.com/alexcrichton/d675523400de93e9b8a06118bb7e880b#file-foo-diff-L138-L148)?

**Comment by eddyb** [comment]
@cynicaldevil that's because `update_panic_count` returns the "after" count instead of the "before" one.

**Comment by cynicaldevil** [comment]
@eddyb

**Pull request merged**
