### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #102977 (remove HRTB from `[T]::is_sorted_by{,_key}`)
 - #103378 (Fix mod_inv termination for the last iteration)
 - #103456 (`unchecked_{shl|shr}` should use `u32` as the RHS)
 - #103701 (Simplify some pointer method implementations)
 - #104047 (Diagnostics `icu4x` based list formatting.)
 - #104338 (Enforce that `dyn*` coercions are actually pointer-sized)
 - #104498 (Edit docs for `rustc_errors::Handler::stash_diagnostic`)
 - #104556 (rustdoc: use `code-header` class to format enum variants)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=102977,103378,103456,103701,104047,104338,104498,104556)

### CODE REVIEW

**Comment by lqd** [comment]
Is the impact on bootstrap timings here expected ? Do you know why serde now takes twice as long to build (maybe some different feature flags) ?

image

**Comment by Manishearth** [comment]
I don't know!

**Comment by lqd** [comment]
This is probably fine but I'll cc @rust-lang/wg-compiler-performance to see what they think.

**Pull request merged**
