### PR TITLE
Make EvalContext::step public again

### LINKED ISSUE #55061: Make EvalContext::step public again
This is needed for [priroda](https://github.com/oli-obk/priroda) to work. This was made private in c141ccf158d8c660ef20a51104b701b4eb37822b.

### PR DESCRIPTION
**Pull request by bjorn3**
This is needed for priroda

Fixes #55061

### CODE REVIEW

**Comment by oli-obk** [comment]
You should probably add a comment explaining that it's public for priroda

**Comment by bjorn3** [comment]
Done

**Comment by bjorn3** [comment]
Spurious failure

**Comment by oli-obk** [comment]
@bora retry

**Pull request merged**
