### PR TITLE
Don't manually implement `PartialEq` for some types in `rustc_type_ir`

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
> > As a follow-up, we should look at not manually implementing PartialEq for these types but instead going thru a derive 
>
> I will try to tackle this later in a separate PR

https://github.com/rust-lang/rust/issues/127042#issuecomment-2218838446

### CODE REVIEW

**Comment by compiler-errors** [comment]
Wonderful to see that we don't need these manual impls any longer

@bors r+

**Comment by GrigorenkoPV** [comment]
> The job **`x86_64-msvc-ext`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10118606417/job/27985742930) [(plain)](https://github.com/rust-lang-ci/rust/commit/18854a71dea27357aea8dd3b8950ec3d21037de2/checks/27985742930/logs)

```
error: failed to remove file `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe`

Caused by:
  Access is denied. (os error 5)
```

Seems to be spurious. I think I've seem a similar failure on another PR a few days ago.

@bors retry
or how do you do it

**Pull request merged**
