### PR TITLE
Fix short hand struct doc

### PR DESCRIPTION
**Pull request by phungleson**
Don't want to discredit @hngiang effort on this issue.

I just want to lend a hand to fix this issue #38830, it is a very nice feature and is seemingly completed.

Fixes #39096

r? @steveklabnik

### CODE REVIEW

**Comment by hngiang** [comment]
Thanks @phungleson for help me fix issue #38830

**Comment by steveklabnik** [comment]
I think this looks great, thank you! @z1mvader wanted to lend a hand, so let's see what they think. I'm feeling good about this PR, though!

**Comment by z1mvader** [comment]
I'm no authority here but I think it's all right :)

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Great! Thanks so much @hngiang for getting this going, and to @phungleson for keeping it going! ❤️

**Pull request merged**
