### PR TITLE
Change default panic handler message format.

### PR DESCRIPTION
**Pull request by m-ou-se**
**Note:** See [below](https://github.com/rust-lang/rust/pull/112849#issuecomment-1678731335) for the snippet for the Rust 1.73 release blog post.

---

This changes the default panic hook's message format from:

```
thread '{thread}' panicked at '{message}', {location}
```

to

```
thread '{thread}' panicked at {location}:
{message}
```

This puts the message on its own line without surrounding quotes, making it easiser to read. For example:

Before:
```
thread 'main' panicked at 'env variable `IMPORTANT_PATH` should be set by `wrapper_script.sh`', src/main.rs:4:6
```
After:
```
thread 'main' panicked at src/main.rs:4:6:
env variable `IMPORTANT_PATH` should be set by `wrapper_script.sh`
```

---

See this PR by @nyurik, which does that for only multi-line messages (specifically because of `assert_eq`): https://github.com/rust-lang/rust/pull/111071

This is the change that does that for *all* panic messages.

### CODE REVIEW

**Comment by m-ou-se** [comment]
@craterbot run mode=build-and-test

**Comment by m-ou-se** [comment]
I browsed a bit through the crater regressions, but the 20+ semi-random samples I looked at all seem unrelated failures..

**Comment by m-ou-se** [comment]
Retrying the regressed crates to get rid of some spurious failures..

@craterbot run mode=build-and-test crates=https://crater-reports.s3.amazonaws.com/pr-112849/retry-regressed-list.txt

**Comment by m-ou-se** [comment]
Ah, here's one regression caused by this PR: `cargo-fixeq` has a hardcoded regex for the panic message output, that no longer matches: https://github.com/quark-zju/cargo-fixeq/blob/8a57374628f54827a1f6f9c544d2ffd74c04afda/src/parse_out.rs#L42

**Comment by compiler-errors** [comment]
@craterbot p=1

(bumping the small runs above the two larger queued ones)

**Comment by m-ou-se** [comment]
Ah that's better. 18 crater failures. Of those we have:

- 2 failures caused by this PR. These two are the crates.io and github copies of cargo-fixeq, which has a hardcoded regex for the panic message output that no longer matches: https://github.com/quark-zju/cargo-fixeq/blob/8a57374628f54827a1f6f9c544d2ffd74c04afda/src/parse_out.rs#L42
- 16 unrelated failures (2 build/linker errors, 5 file system issues, 2 segfaults, 3 tests that depend on randomness, 1 socket issue, and 3 tests that depend on timing).

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by Amanieu** [comment]
Slight nit: could we drop the trailing colon on the file/line number to make it easier to copy/paste? Most editors support trailing line/column numbers and will jump to that point in the file directly. However that doesn't work if there is a trailing colon (at least on vscode).

**Comment by thomcc** [comment]
Losing the colon entirely seems like it might make things confusing. Maybe putting quotes around it might help? (E.g. `thread '{thread}' panicked at '{location}':`)

**Comment by conradludgate** [comment]
CC @sunshowers as this change will break the default panic error heuristic
https://github.com/nextest-rs/nextest/blob/c73883894a755208f37c59b419a242898526b490/nextest-runner/src/reporter/aggregator.rs#L257

**Comment by jyn514** [comment]
> Running `code src/main.rs:2` doesn't do anything here. Do you have a plugin for that? (Fwiw, the plugin I use for my editor does [support trailing colons](https://github.com/bogado/file-line/blob/559088afaf10124ea663ee0f4f73b1de48fb1632/plugin/file_line.vim#L16) because they are so common.)

fwiw, `code -g src/main.rs:2` *does* work

**Comment by Amanieu** [comment]
I'm also happy if this is just fixed in vscode! Ticked my box.

**Review by nyurik — APPROVED** [review]

**Comment by connorskees** [comment]
My preference is to have the file and line number at the end of the error, at least in the case of multiline error messages. There are many cases where an error will span many lines, and having the span at the end of the message makes it easier to find.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ab1600e6c8cc4c7c8a928965a83863cc

This is a rather contrived example, but if executed in a terminal, one would have to scroll up 100 lines to find where the panic occurred.

**Comment by nyurik** [comment]
Could you give some examples of a proposed message? It sounds like you propose a 3 line message, which i think is a bit too verbose:

```
something paniced
message detailed
panic location is at foo.rs:10:20
```

**Comment by connorskees** [comment]
My preference would be for the existing format. I'm not sure I see any issues with the existing format, and it doesn't seem like necessary churn to change it, though this could just be familiarity bias.

Otherwise, yes I would propose a 3 line error message.

```
thread '{thread}' panicked at '{message}', {location}
```

```
thread '{thread}' panicked:
{message}
at {location}
```

**Comment by nyurik** [comment]
I am ok with a 3 line message, esp because most of the panic messages tend to be program-terminating (i.e. it is rare to have tons of panics in the output, and even unit tests tend to have just a few panics... hopefully).  The location at the very end might also be helpful in some cases, although I can't say it is super critical.

The original issue #94005 explained the reasoning for the multi-line message - in some cases, e.g. assert_eq, the debug output of the message is far too long and messy to easily read, and makes asserts far less useful, esp in a unit test scenario. The output with a 3 line would look a bit weird though:

```
thread 'main' panicked:
assertion `left == right` failed: this is clearly should be 2!
  left: `2`
 right: `3`
at $DIR/assert-eq-macro-msg.rs:6:5
```

**Comment by connorskees** [comment]
If the issue is that in `assert_eq!` the context is formatted on the same line as the `right: ...,` value, is there any reason to not just add a newline character following the value, rather than changing the global panic message format?

I am personally opposed to this change as I find it disruptive to my current workflows, and I find this churn in the default panic message format unnecessary.

Of course, this is an extremely mild inconvenience. But I do not think the new format as proposed is an improvement over the existing format.

**Comment by nyurik** [comment]
@m-ou-se any updates on this? I do believe this to be an important visual/debugging improvement that has been widely approved by the core team and many contributors. 

One brought up aspect that I may agree with is that it might be better to place the `at ...` on the last line by itself to allow easy-to-find panic location without scrolling up in case of a long message (repeating from above):

```
thread 'main' panicked:
assertion `left == right` failed: clearly this should be 2!
  left: `2`
 right: `3`
at $DIR/assert-eq-macro-msg.rs:6:5
```

**Comment by m-ou-se** [comment]
> My preference is to have the file and line number at the end of the error, at least in the case of multiline error messages. There are many cases where an error will span many lines, and having the span at the end of the message makes it easier to find.

I don't think we should spread a simple `panic!("oh no")` over even more (three) lines. Also, a backtrace is often shown after a panic message, which can span many lines. So I think it's more likely there are a lot of lines afterwards than a lot of lines in the panic message itself.

**Comment by m-ou-se** [comment]
> If the issue is that in `assert_eq!` the context is formatted on the same line as the `right: ...,` value, is there any reason to not just add a newline character following the value, rather than changing the global panic message format?

Discussion on `assert_eq`'s output is what originally led to the idea for this PR, but `assert_eq` is not the motivation for this PR. See the opening comment above: https://github.com/rust-lang/rust/pull/112849#issue-1765844086

**Comment by m-ou-se** [comment]
r? libs

**Comment by thomcc** [comment]
LGTM, r=me with conflicts addressed.

**Comment by nyurik** [comment]
@m-ou-se anything i can do to help move this forward?  Seems like its gets merge conflicts the moment one turns away for a sec :)

**Comment by nyurik** [comment]
Horray, it built!  Thanks Mara!  @thomcc please review before it gets a conflict again (highly likely considering the number of test files changed) :)

**Comment by weihanglo** [comment]
Looks like Cargo is blocking this. I'll check if we can adjust those tests or disable them temporarily.

**Comment by weihanglo** [comment]
Let's see if my fix works...

@bors try

**Comment by weihanglo** [comment]
Oh no. bors try is useless here as it won't run cargo test suite. Sorry for the noise.

I believe the patch is ready, and we are good to go.

**Comment by workingjubilee** [comment]
Once more with feeling!

@bors r=thomcc

**Comment by workingjubilee** [comment]
Wait, try build... sec, may just be paranoid, but
@bors r-

**Comment by workingjubilee** [comment]
( several recent queue-stalling accidents involved bad combinations of try builds and PR approvals that have made me paranoid of too-directly combining those commands in sequence, thus the "deapprove then reapprove" dance. hopefully this does not run afoul of them. )

**Comment by nyurik** [comment]
It seems the failure is due to a test that hasn't been blessed because it is `windows-only`. Does anyone have a windows machine to bless these?

**Comment by nyurik** [comment]
I fixed the above build error - please merge https://github.com/m-ou-se/rust/pull/2

**Comment by nyurik** [comment]
Thx everyone for getting this one through!  Turns out the simplest PRs are the hardest to merge :)

I re-based #111071 on top of the main branch, so now its much simpler.  I think we should release both panic message changes in the same release if possible, as they are closely related.

**Comment by lqd** [comment]
@rust-lang/wg-compiler-performance: We may need to do something about https://github.com/rust-lang/rust/pull/114318 breaking the bootstrap timings. They're still missing for more recent PRs, like this one.

**Comment by m-ou-se** [comment]
Snippet for the release blog post (in Markdown), for both this PR and #111071:

```
## Cleaner panic messages

The output produced by the default panic handler has been changed
to put the panic message on its own line instead of wrapping it in quotes.
This can make panic messages easier to read, as shown in this example:

<div style="margin:1em"><pre><code>fn main() {
    let file = "ferris.txt";
    panic!("oh no! {file:?} not found!");
}</code></pre>
Output before Rust 1.73:
<pre style="margin-top:0"><code style="background:#000;color:#ccc" class="language-text">thread 'main' panicked at 'oh no! "ferris.txt" not found!', src/main.rs:3:5</code></pre>
Output starting in Rust 1.73:
<pre style="margin-top:0"><code style="background:#000;color:#ccc" class="language-text">thread 'main' panicked at src/main.rs:3:5:
oh no! "ferris.txt" not found!</code></pre></div>

This is especially useful when the message is long, contains nested quotes, or spans multiple lines.

Additionally, the panic messages produced by `assert_eq` and `assert_ne` have
been modified, moving the custom message (the third argument)
and removing some unnecessary punctuation, as shown below:

<div style="margin:1em"><pre><code>fn main() {
    assert_eq!("🦀", "🐟", "ferris is not a fish");
}</code></pre>
Output before Rust 1.73:
<pre style="margin-top:0"><code style="background:#000;color:#ccc" class="language-text">thread 'main' panicked at 'assertion failed: `(left == right)`
 left: `"🦀"`,
right: `"🐟"`: ferris is not a fish', src/main.rs:2:5</code></pre>
Output starting Rust 1.73:
<pre style="margin-top:0"><code style="background:#000;color:#ccc" class="language-text">thread 'main' panicked at src/main.rs:2:5:
assertion `left == right` failed: ferris is not a fish
 left: "🦀"
right: "🐟"</code></pre></div>
```

<details><summary>Rendered</summary>
Screenshot 2023-08-15 at 12 30 08
</details>

**Comment by safinaskar** [comment]
Despite all this effort, bug https://github.com/rust-lang/rust/issues/108341 still persists. I. e. I still see ugly `\n` in assert output if line is too long

**Comment by safinaskar** [comment]
Also, backtraces are still completely impossible to understand: https://github.com/rust-lang/rust/issues/99560

**Comment by workingjubilee** [comment]
Naturally. This PR was not intended to fix either of those problems. If you want to help us improve our panic and backtrace diagnostics, a good first step would be to find all the issues that have to deal with panic and labeling them like so:

@rustbot label: +A-panic

That is something anyone can do, and it will significantly help us sort these issues out by making it easier to try to figure out which issues _are_ related to each other.

**Pull request merged**
