### PR TITLE
Don't ICE when getting an input file name's stem fails

### LINKED ISSUE #128681: ICE when using `\\.\NUL` as the input filename on Windows
### Code

On a Windows machine, run:

```Rust
rustc \\.\NUL
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (176e54520 2024-08-04)
binary: rustc
commit-hash: 176e5452095444815207be02c16de0b1487a1b53
commit-date: 2024-08-04
host: x86_64-pc-windows-msvc
release: 1.82.0-nightly
LLVM version: 19.1.0
```

### Error output

```
thread 'rustc' panicked at compiler\rustc_session\src\config.rs:842:57:
called `Option::unwrap()` on a `None` value
```

Which is here: https://github.com/rust-lang/rust/blob/4d48a6be74d46304cacb93cb8eb60d70d733b862/compiler/rustc_session/src/config.rs#L842

Specifically the `file_stem().unwrap()` panics. The `\\.\NUL` device is pretty weird as it's a device in its own right that you can read/write to but also a kind of root directory (you can do `\\.\NUL\path\to\rust.rs`) and calling `parent()` on `\\.\NUL` should return `None`. It doesn't quite fit with std's model of paths.

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler\rustc_session\src\config.rs:842:57:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ffd5681d903 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffd5681d903 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffd5681d903 - std::backtrace::Backtrace::create
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\backtrace.rs:331
   3:     0x7ffd5681d84a - std::backtrace::Backtrace::force_capture
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\backtrace.rs:312
   4:     0x7ffceb7fcef9 - memchr
   5:     0x7ffd5683871b - alloc::boxed::impl$50::call
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/alloc\src\boxed.rs:2164
   6:     0x7ffd5683871b - std::panicking::rust_panic_with_hook
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\panicking.rs:805
   7:     0x7ffd568384ef - std::panicking::begin_panic_handler::closure$0
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\panicking.rs:664
   8:     0x7ffd5683569f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\sys\backtrace.rs:170
   9:     0x7ffd56838136 - std::panicking::begin_panic_handler
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\panicking.rs:662
  10:     0x7ffd56890c94 - core::panicking::panic_fmt
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/core\src\panicking.rs:74
  11:     0x7ffd56890d3d - core::panicking::panic
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/core\src\panicking.rs:148
  12:     0x7ffd56890bfe - core::option::unwrap_failed
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/core\src\option.rs:2017
  13:     0x7ffcecea3774 - <rustc_session[2d2a655f635f0202]::config::Input>::filestem
  14:     0x7ffce7350e81 - rustc_interface[386d7deb044bc41f]::util::build_output_filenames
  15:     0x7ffce73497ea - <rustc_interface[386d7deb044bc41f]::queries::Queries>::global_ctxt
  16:     0x7ffce7303523 - _wpgmptr
  17:     0x7ffce72ff27f - _wpgmptr
  18:     0x7ffce730cf5b - _wpgmptr
  19:     0x7ffd56849acd - alloc::boxed::impl$48::call_once
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/alloc\src\boxed.rs:2150
  20:     0x7ffd56849acd - alloc::boxed::impl$48::call_once
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/alloc\src\boxed.rs:2150
  21:     0x7ffd56849acd - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/176e5452095444815207be02c16de0b1487a1b53\library/std\src\sys\pal\windows\thread.rs:55
  22:     0x7ffda697257d - BaseThreadInitThunk
  23:     0x7ffda7caaf28 - RtlUserThreadStart


rustc version: 1.82.0-nightly (176e54520 2024-08-04)
platform: x86_64-pc-windows-msvc
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #128681

The file stem is only used as a user-friendly prefix on intermediary files. While nice to have, it's not the end of the world if it fails so there's no real reason to emit an error here. We can continue with a fixed name as we do when an anonymous string is used.

### CODE REVIEW

**Comment by jieyouxu** [comment]
Looks reasonable to me from first glance, I'll double check what `Input::file_stem` is used for.

**Comment by ChrisDenton** [comment]
Oh it'll also be used for the final artefact name if it's the only (or first?) input and it's not otherwise named. I think this is fine though as it's the same as piping input.

**Comment by jieyouxu** [comment]
> Oh it'll also be used for the final artefact name if it's the only (or first?) input and it's not otherwise named. I think this is fine though as it's the same as piping input.

I took a look and AFAICT this is fine -- we can't be naming the output file `\\.\NUL` in the first place. Do you think we should add a check for the `rust_out` fallback output artifact name behavior? I'm fine with accepting this falling back to `rust_out` with or without this additional check.

**Comment by ChrisDenton** [comment]
Tbh, I'm not sure. But I guess adding a check can't hurt too much. Worst case someone might have to update the test in the future.

**Comment by jieyouxu** [comment]
> Tbh, I'm not sure. But I guess adding a check can't hurt too much. Worst case someone might have to update the test in the future.

Yeah, I don't think we care about the *exact* behavior of this too much, but it seems better to at least have a test to know this behavior is expected *somewhere*.

**Review by jieyouxu — APPROVED** [review]
Thanks for melting the ICE! 😎

**Comment by jieyouxu** [comment]
Please r=me after PR CI is green

**Comment by ChrisDenton** [comment]
> Thanks for melting the ICE! 😎

🔥And a super important one too! 🔥

@bors r=jieyouxu rollup

**Pull request merged**
