### PR TITLE
[beta] Attempt to fix the component manifest problem for rls-preview

### PR DESCRIPTION
**Pull request by nrc**
cc #44270 

see #44352

### CODE REVIEW

**Comment by alexcrichton** [comment]
@nrc want to include the beta bump as well by [changing this line](https://github.com/rust-lang/rust/blob/133aefc9fe15b04c7d1a7df3a5d7ded47e789c39/src/bootstrap/channel.rs#L32)?

(that way a new beta will be released when this is merged)

**Comment by alexcrichton** [comment]
I wonder if `--component-name` is changing the name of the tarball?

**Comment by nrc** [comment]
The problem seems to be that the save-analysis data for std is missing. I thought we only produced that on nightly, which would explain things, but I couldn't find such a condition in the code.

**Comment by nrc** [comment]
I realise this doesn't explain why we only hit this bug with this patch though

**Comment by alexcrichton** [comment]
@nrc you noted on IRC that you weren't able to reproduce locally, but I wonder if this is related to these lines?

https://github.com/rust-lang/rust/blob/133aefc9fe15b04c7d1a7df3a5d7ded47e789c39/src/bootstrap/dist.rs#L1282-L1284

That may explain the windows-specific-ness?

**Comment by frewsxcv** [comment]
why is bors testing this again? @bors retry r-

**Comment by kennytm** [comment]
`dist-fuchsia` errored, failed to deploy.

```
uploading "9637179c7c345460504fb7bf36636d7fb43d1d1f/rust-analysis-beta-aarch64-unknown-fuchsia.tar.gz" with {:content_type=>"application/gzip", :acl=>"public-read"}
Invalid S3 Access Key Id, Stopping Deploy
failed to deploy
```

@alexcrichton is #44385 (Rotate Travis/AppVeyor S3 keys) needed?

**Comment by alexcrichton** [comment]
Yeah, I've now also hijacked this PR to bump the beta to .3 and backport these PRs:

* https://github.com/rust-lang/rust/pull/44263
* https://github.com/rust-lang/rust/pull/44353
* https://github.com/rust-lang/rust/pull/44385
* https://github.com/rust-lang/rust/pull/44399
* https://github.com/rust-lang/rust/pull/44542
* https://github.com/rust-lang/rust/pull/44552

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry

* s3 is down

**Comment by alexcrichton** [comment]
```
$ rls +beta
<never exits>
```

It works!

**Pull request merged**
