### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by Jarcho**
r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me in theory, needs CI fixes and the removal of merge commits

**Comment by Jarcho** [comment]
Aren't the merge commits normal? They're all bors commits or subtree merges.

**Comment by Manishearth** [comment]
ah hmm maybe. I've not seen that comment before

**Comment by Jarcho** [comment]
Looks like the name of the PR is the problem going by https://forge.rust-lang.org/triagebot/no-merge.html.

**Comment by Manishearth** [comment]
Aha, that works then

@bors r+ p=1 rollup=iffy

**Pull request merged**
