### PR TITLE
check -Z query-dep-graph is enabled if -Z dump-dep-graph (#106736)

### PR DESCRIPTION
**Pull request by gftea**
PR to solve #106736, r? @cjgillot

### CODE REVIEW

**Comment by cjgillot** [comment]
Could you add a test that this message appears?

**Comment by gftea** [comment]
> Could you add a test that this message appears?

Can you point me where to add test of it?

**Comment by Nilstrieb** [comment]
The test looks good. As a final step, could you [squash](https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing) the commits? If you need help doing that, feel free to ask.

**Comment by gftea** [comment]
> The test looks good. As a final step, could you [squash](https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing) the commits? If you need help doing that, feel free to ask.

Done, please check @Nilstrieb

**Pull request merged**
