### PR TITLE
Add regression test to close #53787

### LINKED ISSUE #53787: Compiler Crashes when trying to create a label in inline assembler with macros.
Compiler Crashes when trying to create a label in inline assembler with macros. I am not sure if my could would work, but I am pretty sure it should not crash the compiler.

I tried this code:  https://hastebin.com/uyohacewex.bash
I expected to see this happen:  Generate a code sample with the given id
Instead, this happened: Compiler crashes  

**rustc --version --verbose:**

rustc 1.30.0-nightly (73c78734b 2018-08-05)
binary: rustc
commit-hash: 73c78734bae8f2947a4bfdeabebeeb84ccf0b0e1
commit-date: 2018-08-05
host: x86_64-pc-windows-msvc
release: 1.30.0-nightly
LLVM version: 7.0

**Backtrace:**
https://hastebin.com/xeyokeriqo.rb
(Github keeps messing with the windows formatting)

### PR DESCRIPTION
**Pull request by AB1908**
Fixes #53787

### CODE REVIEW

**Comment by AB1908** [comment]
I think this has to do with the error description. I need assistance as I'm not sure what more is to be done.

**Comment by AB1908** [comment]
I was able to reproduce the test error and have pushed the necessary changes. All fingers crossed! :crossed_fingers:

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@AB1908 thanks!

**Pull request merged**
