### PR TITLE
Don't suffix `RibKind` variants

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This PR
- Removes `use RibKind::*`
- Renames `RibKind::{SomethingRibKind => Something}`

It seems unnecessary to have "RibKind" in the end of all variants, if we can just use it as a normal enum. Additionally previously it was weird that `MacroDefinition` is the only unsuffixed variant.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@bors r- 

failed in [rollup](https://github.com/rust-lang-ci/rust/actions/runs/4872155644/jobs/8689999918)

**Comment by WaffleLapkin** [comment]
@Dylan-DPC why do you think this PR is the cause? The failure is with uploading artifacts to S3:
```
Run src/ci/scripts/upload-artifacts.sh
cp: cannot stat 'build/metrics.json': No such file or directory
Error: Process completed with exit code 1.
```

This pr did not touch `build/metrics.json` and I don't see how it can cause anything like that...

**Pull request merged**
