### PR TITLE
Remove NodeId from some HIR nodes

### PR DESCRIPTION
**Pull request by ljedrz**
The next iteration of https://github.com/rust-lang/rust/pull/57578.

Removes `NodeId` from:

- [x] `Lifetime`
- [x] `Ty`
- [x] `GenericParam`
- [x] `WhereClause`
- [x] `WhereEqPredicate`
- [x] `MacroDef`
- [x] `Block`
- [x] `Expr`

r? @Zoxc

### CODE REVIEW

**Comment by Zoxc** [comment]
These changes look good to me.

@bors delegate+

**Comment by ljedrz** [comment]
Hmm, I should update clippy.

@bors r-

**Comment by ljedrz** [comment]
Blocked by https://github.com/rust-lang/rust-clippy/pull/3814.

**Comment by ljedrz** [comment]
The build stalled; might be spurious. I'm not sure if reopening will retry Travis; lemme see...

**Comment by ljedrz** [comment]
The tooltest error seems legit; I'll look into it.

**Comment by ljedrz** [comment]
Can I get a priority bump to 1 due to submodule update?

**Comment by Centril** [comment]
Rollup fairness (due to submodule update), @bors p=1

**Pull request merged**
