### PR TITLE
Use singular they in the serialize::json docs

### PR DESCRIPTION
**Pull request by fenhl**
See [this document](https://gist.github.com/0xabad1dea/8870b192fd1758743f66) by @0xabad1dea for the rationale.

### CODE REVIEW

**Comment by fenhl** [comment]
I'm not sure why my commit is moving the `use self::JsonEvent::*;` line around, that wasn't intentional.

**Comment by steveklabnik** [comment]
thank you very much! r=me after that change is fixed

**Comment by fenhl** [comment]
Done.

**Comment by fenhl** [comment]
@steveklabnik done

**Comment by steveklabnik** [comment]
Thanks so much!

**Comment by kmcallister** [comment]
:sparkling_heart:

**Pull request merged**
