### PR TITLE
Bump to 1.31.0 and bootstrap from 1.30 beta

### LINKED ISSUE #54594: 1.31 version nightly
I noticed the version of nightly is still 1.30, and I was wondering if updating that is waiting for something?  Just slightly confusing, not critical to me.

### PR DESCRIPTION
**Pull request by cuviper**
Closes #54594.

### CODE REVIEW

**Comment by cuviper** [comment]
The affected UI lines should be fixed now.

**Comment by cuviper** [comment]
Rebased.

**Comment by alexcrichton** [comment]
@bors: retry

Something tells me that this PR was not the one that caused `cc`, the C compiler, to execute an illegal instruction on OSX

**Pull request merged**
