### PR TITLE
interpret: use new OpTy::len for Len rvalue

### PR DESCRIPTION
**Pull request by RalfJung**
This avoids a `force_allocation`.

### CODE REVIEW

**Comment by RalfJung** [comment]
Ouch, this regresses the lints because we are not conceptually 'reading' from the local rather than 'writing' to it (which is what `force_allocation` does).

Uh, how is that sound? If it is okay for `force_allocation` to make a local with unknown content into uninit and then rely on the usual checks for reading from uninit memory, then why does ConstProp even need/have [this check](https://github.com/rust-lang/rust/blob/e6518296dcd9e878ac450afdfee4f4bc3fec72f3/compiler/rustc_mir_transform/src/const_prop.rs#L248)?

**Comment by lcnr** [comment]
i can't completely follow what's going on here

r? @oli-obk

**Comment by RalfJung** [comment]
Blocked on https://github.com/rust-lang/rust/pull/100239.

**Comment by RalfJung** [comment]
Looks good. @oli-obk this is @rustbot ready

**Comment by oli-obk** [comment]
@bors try @rust-timer queue

I don't expect this to affect things, but the stress tests are weird, so let's run perf first. r=me once perf is done (just so we know whether to rollup or never)

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/101218#issuecomment-1232283186

@bors r-

**Comment by RalfJung** [comment]
Still rather strange that it would slow down the `externs` test...

**Pull request merged**
