### PR TITLE
libstd: add std::sync::StaticMutex

### LINKED ISSUE #71521: add StaticMutex as Sync proof helper
As [discussed here](https://internals.rust-lang.org/t/what-shall-sync-mean-across-an-await/12020/29?u=rkuhn) the proposal of a [`SyncWrapper` data structure](https://internals.rust-lang.org/t/what-shall-sync-mean-across-an-await/12020/2?u=rkuhn) seems to be a sound way of proving some [relevant cases](https://github.com/hyperium/hyper/pull/2187#pullrequestreview-399514185) to be Sync that would otherwise either need the `unsafe` keyword or incur the overhead of allocating and accessing a Mutex. Therefore I propose to add such a facility to the standard library.

The reasoning behind the name is that this is a facility that statically guarantees mutual exclusion.

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #71521

### CODE REVIEW

**Comment by RalfJung** [comment]
The name of this is really confusing. `StaticMutex` sounds like it would be like `Mutex` (run-time checks for mutual exclusion), but can be used in a `static` (because it has a `const fn` initializer). That is not at all what this is doing.

`SyncWrapper` or `BlockSharedAccess` or so would be better names, IMO.

**Comment by rkuhn** [comment]
Good points, I’m totally fine renaming it. Another proposed name was `Unshare`, IIRC. @eddyb saw a connection to some Pony capability, perhaps that’s another possibility?

**Comment by KrishnaSannasi** [comment]
This should probably be in libcore, and reexported from libstd.

**Comment by crlf0710** [comment]
@rkuhn Ping from triage, would you mind address the review comments above (e.g. renaming)?

**Comment by rkuhn** [comment]
Sure, no problem: I was waiting for someone to make the call as to what the name should be — I’m not too familiar with the processes around here, so I might have missed some place or forum where this discussion should have been held.

Regarding the move to libcore: sure thing, I’d just like to understand the rules here (since Mutex lives in libstd and seems quite fundamental to me).

**Comment by crlf0710** [comment]
I think you can drop by the official zulip (rust-lang.zulipchat.com), there's a T-libs stream in there.

About where the type should live, the rules are easy: If it relies on the existing of an OS (using os primitives), it should live in `std`, other than that, if it needs to allocate memory, it should live in `alloc`, otherwise, just live in `core`. And finally, if it's not living directly in `std`, reexport it from there.

**Comment by rkuhn** [comment]
Okay, thanks!

**Comment by rkuhn** [comment]
Discussion on zulip came to the conclusion of publishing this as a separate crate for now.

**Pull request closed without merging**
