### PR TITLE
Fix anchors in error docs

### PR DESCRIPTION
**Pull request by davidszotten**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like this might need a rebase? Other than though looks good to me!

**Comment by steveklabnik** [comment]
Same! r=me after it applies cleanly.

**Comment by davidszotten** [comment]
found a bunch more missing references. what are your thoughts on getting a checker for this into the test suite?

**Comment by steveklabnik** [comment]
That'd be great.

**Comment by steveklabnik** [comment]
Oh, by the way: please leave a comment after you rebase, as we don't get notified when new commits are pushed :/

**Pull request merged**
