### PR TITLE
Pass a `TyCtxt` through to `FormatRender`

### PR DESCRIPTION
**Pull request by jyn514**
This is the next step after https://github.com/rust-lang/rust/pull/79957 for https://github.com/rust-lang/rust/issues/76382. Eventually I plan to use this to remove `stability`, `const_stability`, and `deprecation` from `Item`, but that needs more extensive changes (in particular, https://github.com/rust-lang/rust/pull/75355 or something like it).

This has no actual changes to behavior, it's just moving types around.

ccc https://github.com/rust-lang/rust/pull/80014#issuecomment-746810284

### CODE REVIEW

**Comment by jyn514** [comment]
Since both this and https://github.com/rust-lang/rust/pull/80119 add `as_sym()`, I'll wait to rebase it until 80119 is merged.

**Comment by jyn514** [comment]
Err maybe not? I'm starting to lose track of which changes happened in which PRs :laughing: too many open at the same time.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Quite a lot of information was stored in the first pass to not have the `TyCtxt` for historical reasons which forced some not-so-nice implementations afterwards. Thanks to this, we'll be able to have much more on-demand requests instead of just storing everything. I'm expecting big memory and perf improvements thanks to this, so thank you @jyn514 !

r=me if this is ready for you (you seemed to be doing some tests still? :smile: )

**Comment by jyn514** [comment]
>  Thanks to this, we'll be able to have much more on-demand requests instead of just storing everything. I'm expecting big memory and perf improvements thanks to this, so thank you @jyn514 !

I already started on a few :) https://github.com/rust-lang/rust/pull/80095 https://github.com/rust-lang/rust/pull/80099

**Pull request merged**
