### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
Bi-weekly Clippy sync.

r? @Manishearth

### CODE REVIEW

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/83038#issuecomment-797108697
Looks like GHA wasn't triggered on this PR?
@bors r-

**Comment by flip1995** [comment]
```
    Checking clippy_lints v0.1.52 (/checkout/src/tools/clippy/clippy_lints)
error: unnecessary parentheses around pattern
   --> src/tools/clippy/clippy_lints/src/loops/manual_memcpy.rs:206:13
    |
206 |         let (Sugg::NonParen(s) | Sugg::MaybeParen(s) | Sugg::BinOp(_, s)) = &self.0;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
    |
    = note: `-D unused-parens` implied by `-D warnings`
error: aborting due to previous error

error: could not compile `clippy_lints`
```

Uh that looks weird. In the rust->Clippy sync direction, I was told to add them. Seems like something changed here and those parentheses aren't necessary anymore? Just seems like unfortunate timing. I will fix this tomorrow.

**Comment by flip1995** [comment]
@Manishearth This should now be ready. 99d0519 fixed the issue. I could've also fixed it by putting `#[cfg(bootstrap)]` in the code, but I wanted to avoid this in Clippy.

**Comment by Manishearth** [comment]
@bors r+

Good call

**Pull request merged**
