### PR TITLE
Use `Lrc<[_]>` instead of `Vec<_>` in `rustc_ast::...::Comment`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
`Comment` seems to be cloned quite a lot, so making the clone cheaper could be nice.

----

I've tried to remove cloning first, but it turns out to be hard b/c of borrock errors. It might be possible to eliminate cloning with a bigger refactor, but maybe this will have a positive impact of perf too.

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
Not sure this is worth the extra complication. Let me know your thoughts.

**Comment by WaffleLapkin** [comment]
Yeah, this doesn't seem to improve much if anything, so I'll just go ahead and close it.

**Pull request closed without merging**
