### PR TITLE
rustc_metadata: Remove `Span` from `ModChild`

### PR DESCRIPTION
**Pull request by petrochenkov**
It can be decoded on demand from regular `def_span` tables.

Partially mitigates perf regressions from https://github.com/rust-lang/rust/pull/109500.

### CODE REVIEW

**Comment by eholk** [comment]
Since this says [WIP], I'm assuming it's not ready to be merged. I'll mark this was waiting on author in the meantime, but feel free to send it back if/when you're ready to have it reviewed.

@rustbot author

**Comment by petrochenkov** [comment]
Yep, this mostly mitigates perf regressions from https://github.com/rust-lang/rust/pull/109500.

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/110160.

**Comment by nnethercote** [comment]
The perf wins greatly outweigh losses.

@rustbot label: +perf-regression-triaged

**Pull request merged**
