### PR TITLE
Remove giant badge in README

### PR DESCRIPTION
**Pull request by frewsxcv**
Is it meant to be this big? I haven't seen any other open source project with this sort of thing

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@nikomatsakis and @steveklabnik seemed in favor on https://github.com/rust-lang/rust/pull/73649 which added this badge - I'd be fine with shrinking it down or removing it personally, I agree it seems rather odd right now.

**Comment by camelid** [comment]
I would also like to remove this. Ideally we could go back to something like how it was before:

```markdown
# The Rust Programming Language
```

**Comment by Mark-Simulacrum** [comment]
I'm going to wait till after the holidays to approve, in case Steve or Niko want to chime in, but I don't think a header is too helpful. The first paragraph gets right into what this repository is; we don't need a header to signal that too.

**Comment by camelid** [comment]
> I'm going to wait till after the holidays to approve, in case Steve or Niko want to chime in

👍 

> but I don't think a header is too helpful. The first paragraph gets right into what this repository is; we don't need a header to signal that too.

Yes, but practically every open-source project has a header. The page looks kind of “naked” without a title at the top. But we can talk about this after the holidays.

**Comment by frewsxcv** [comment]
Brought back a top-level heading in https://github.com/rust-lang/rust/pull/80144/commits/d2cc79eaa2785358a4d0343485122e06235f00c2

**Comment by steveklabnik** [comment]
I like it either way. Constantly churning on this isn't great though.

**Comment by camelid** [comment]
I think we'll wait to get Niko's feedback and then merge this if he's okay with it, since it seems we're either neutral or prefer the simple heading.

> Constantly churning on this isn't great though.

Yeah, hopefully we won't change this any more. IMO, the badge looks really weird and out-of-place.

**Comment by nikomatsakis** [comment]
Hey all, I'm catching up on my review queue. I don't have a *strong* opinion about this, but doing a quick survey of other languages (Go, Ruby, Python) I agree the badge seems unusual (although I do like having the logo). I'm going to r+ but I wanted to cc @Anirban166 (who added the badge) so they're not surprised by the change.

@bors r+

**Pull request merged**
