### PR TITLE
[beta] Bootstrap from stable

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This is the follow up to master/beta promotion, as well as the first round of backports:

* Revert "Allow specifying alignment for functions #81234"
* Revert #85176 addition of clone_from for ManuallyDrop #85758 
* rustdoc: revert deref recur to resume inclusion of impl ExtTrait<Local> for ExtType #84867 
*  [beta] Update cargo #86563 

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=10

Would like to get this merged so we can do master bootstrap bump today/tomorrow as well.

**Comment by Mark-Simulacrum** [comment]
Hm, something about the build environment is causing trouble... maybe refs/remotes/origin/master doesn't exist? will need to investigate

**Comment by cuviper** [comment]
FWIW, I can run that docker image here and it gets the beta rev just fine. More ideas to look at in CI:

- `pwd` / `std::env::current_dir()`
- `git rev-parse --git-dir`
- `git rev-parse --show-toplevel`
- `git branch --remote`

**Comment by Mark-Simulacrum** [comment]
I can't reproduce this failure locally it seems and there's no cross-compilation stuff on that builder (it's a native aarch64 machine)...

I hope this isn't somehow related to it being ARM vs x86, the FileCheck failure doesn't seem platform specific. Indeed, the log suggests that my understanding that CHECK: need not start with the first line of the file is wrong... but the test passing locally with a similar prefix suggests otherwise. I guess we'll see; I've added hopefully a little more debugging information.

@bors r+

**Comment by Mark-Simulacrum** [comment]
@bors r+ 

Stopped using gold here -- asking on Zulip led me to #67829 which is trying to fix an almost identical failure by *using* gold; maybe that is no longer helpful. Otherwise perhaps we'll add a retry loop or something and try again...

**Comment by Mark-Simulacrum** [comment]
I'm pretty much at a loss as to what could be causing the pgo-branch-weights test to pass on x86_64 (and likely other platforms) but not on the ARM builder, and specifically not on this branch. I've tried running it manually with a downloaded rustc from this CI builds here on an aarch64 machine, but that did not yield any problems - the test passed there. It's possible something about the specific environment created by bootstrap is causing problems, I suppose, but that seems pretty unlikely.

Given that aarch64-unknown-linux-gnu is a tier 1 platform, I am hesitant to simply disable the test, but I think if we don't get a resolution quite quickly that'll be the right step to take, filing a P-critical issue to try and investigate and fix it out of band before 1.54 actually gets released in ~6 weeks. The test *does* seem to pass locally, so it's likely something in CI, and so doesn't feel necessarily like it should block the release regardless.

Doing some more debugging now and discussing on Zulip - https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/File.20check.20erroring.20on.20prefix.20in.20input

**Comment by Mark-Simulacrum** [comment]
Hm, it seems we've definitely lost some profiling information or so, locally I see:

2021-06-20T22:20:12.3548846Z -rw-rw-r-- 1 user user 3656 Jun 20 22:19 default_10357918073240249039_0.profraw
2021-06-20T22:20:12.3549820Z -rw-rw-r-- 1 user user  688 Jun 20 22:19 merged.profdata

be instead 4208 and 5976 bytes. 

And 2021-06-20T22:20:12.3552786Z "/checkout/obj/build/aarch64-unknown-linux-gnu/llvm/build/bin/llvm-profdata" show \
2021-06-20T22:20:12.3554697Z 	"/checkout/obj/build/aarch64-unknown-linux-gnu/test/run-make-fulldeps/pgo-branch-weights/pgo-branch-weights/prof_data_dir/merged.profdata"
2021-06-20T22:20:12.3556108Z Instrumentation level: IR  entry_first = 0
2021-06-20T22:20:12.3556751Z Total functions: 1
2021-06-20T22:20:12.3557299Z Maximum function count: 1
2021-06-20T22:20:12.3557891Z Maximum internal block count: 0

shows:

```
Instrumentation level: IR  entry_first = 0
Total functions: 31
Maximum function count: 42
Maximum internal block count: 44
```

Not sure what could cause this...

**Comment by Mark-Simulacrum** [comment]
#78226 tracks re-enabling the pgo-branch-weights test case; we can discuss on that issue whether it is truly a blocker for the 1.54 release but has been labeled as such for now. If and when we get a fix we can re-enable the test.

@bors r+ rollup=never p=10

**Pull request merged**
