### PR TITLE
Remove some noise in the build system’s output.

### PR DESCRIPTION
**Pull request by SimonSapin**
Remove twelve lines of "Synchronizing submodule […]" and "HEAD is now at […]" every time `x.py` is run.

### CODE REVIEW

**Comment by rkruppe** [comment]
The "HEAD is now at [...]" lines have been invaluable while I was trying to point a submodule at a different fork. It alerted me that the build system checked out the wrong commit again. I would like to preserve it (and for completeness, the other output as well) &mdash; perhaps only if `--verbose` is passed?

**Comment by SimonSapin** [comment]
Alright, I changed the PR so that `--quiet` is only passed to git commands when the build is not verbose.

**Comment by est31** [comment]
For me, it was pretty useful to find out that I didn't need to do `git submodule update` after checking out a certain git revision, because usually build systems ask the user to do it. Without the info I would probably still waste my time typing that command. So it is not redundant. Also, I think a tool should be transparent to the user about when it accesses (or may access) the network.

Maybe, if `--quiet` is passed, you could print "Syncing git submodules..." instead? Then it would still have the teaching effect.

**Comment by alexcrichton** [comment]
I've noticed from time to time that these steps take forever on my Windows machine (which I think has slow disks). @SimonSapin in the default case does this avoid printing any output? If so we may want to print something manually just to give a status update if it hang.

**Comment by SimonSapin** [comment]
> @SimonSapin in the default case does this avoid printing any output?

I believe that non-verbose is the default for rustbuild. In the PR as it is now, `--quiet` is passed to these git commands when the build is not verbose.

> If so we may want to print something manually just to give a status update if it hangs.

I don’t understand, what change would you like to see?

**Comment by est31** [comment]
I think @alexcrichton raises a second good reason for why some kind of output should be kept: a tool shouldn't just do something without printing anything to the user.

The easiest way to achieve this would be my suggestion to add a `println!("Synchronizing submodules...");` before the invocation of the git commands. No idea how to achieve printing only if the command "hangs" for some reason... and even if, it wouldn't have the teaching effect that it actually synchronizes the submodules.

**Comment by SimonSapin** [comment]
I don’t mind seeing these lines when something does happen. What I find annoying is seeing them every time in the edit-compile-test cycle when I’m in the middle of working on something.

So ideally, we should make these git commands silent when they have no effect because submodules are already synchronized/reset. However I haven’t found an easy way to do that, `--quiet` is all that git provides unfortunately.

**Comment by est31** [comment]
Mhh from reading the code it seems that running `git submodule sync` is only required if the previous `git submodule status` run has found any state that is not `State::MaybeDirty` for a submodule. Correct me if I'm wrong.

Also, from reading the manpage it seems that `git submodule status` can also output the letter "D" instead of just "-", "+" and " ".

And running `git reset --hard` is only required if the state is actually dirty. You can run `git status --porcelain` before and check if it has non-empty output for this.

**Comment by Mark-Simulacrum** [comment]
Perhaps we can detect if there are changes to submodules, and if so run the submodule update? Otherwise, we can print "No submodule updates necessary." or perhaps nothing. I know I've seen submodules show up in git status; so I assume we could do this...

**Comment by alexcrichton** [comment]
@SimonSapin to clarify I intended what @est31 [mentioned earlier](https://github.com/rust-lang/rust/pull/38778#issuecomment-270436197). If rustbuild ever hangs (doing anything) then the previously printed message should be an indication of why it's hanging. I'm worried about this submodule sync step hanging without having an informational message preceeding it indicating what. Presumably git takes care of that if it's not quiet.

Locally on my Windows machine at least it hangs for multiple seconds even if there are no updates to perform. I have no idea why it's so slow, but it means I'm probably not the only one where a noop update takes awhile. 

The change I'd specifically like to see is just a println when the section is entered, like other steps in rustbuild.

**Pull request closed without merging**
