### PR TITLE
resolve: Try to fix instability in import suggestions

### PR DESCRIPTION
**Pull request by petrochenkov**
cc https://github.com/rust-lang/rust/pull/42033

`lookup_import_candidates` walks module graph in DFS order and skips modules that were already visited (which is correct because there can be cycles).
However it means that if we visited `std::prelude::v1::Result::Ok` first, we will never visit `std::result::Result::Ok` because `Result` will be skipped as already visited (note: enums are also modules here), and otherwise, if we visited `std::result::Result::Ok` first, we will never get to `std::prelude::v1::Result::Ok`.
What child module of `std` (`prelude` or `result`) we will visit first, depends on randomized hashing, so we have instability in diagnostics.

With this patch modules' children are visited in stable order in `lookup_import_candidates`, this should fix the issue, but let's see what Travis will say.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Even if this becomes deterministic by these changes, I dislike the results:

```
+   = help: there is an enum variant `std::result::Result::Ok`, try using `std::result::Result`?
+   = help: there is an enum variant `std::prelude::v1::Option::Some`, try using `std::prelude::v1::Option`?
```

`Result` shows up in the real path while `Option` shows up in the reexport in the prelude.

I still think that it's impossible to produce nice diagnostics with paths during resolve and that we should be caching them until resolve is finished and report them then

**Comment by petrochenkov** [comment]
I don't see how delaying will help here.
These particular diagnostics are reported during the second stage of resolve when all import resolution is done and all definitions are available. Fully completing resolution will not add any new information useful here.

The problem prelude paths is that reexports are shown in candidates as well as true definitions. The intent of the [original PR](https://github.com/rust-lang/rust/pull/31674) was to filter out the reexports, however the implementation doesn't work correctly and nothing outside of the current crate is considered a reexport and filtered out.
`fn each_child_of_item` and friends should preserve the export/non-export distinction and provide it to resolve so it can filter away reexports properly.
This is a completely orthogonal issue though and it doesn't block migration of compile-fail tests to UI testing.

**Comment by oli-obk** [comment]
Makes sense. Implementation Lgtm.

You'll need a reviewer to sign off the PR though.

**Comment by alexcrichton** [comment]
@bors: retry

* musl segfault https://github.com/rust-lang/rust/issues/38618

**Pull request merged**
