### PR TITLE
Push a `char` instead of a `str` with len one into a String

### PR DESCRIPTION
**Pull request by LingMan**
@rustbot modify labels +C-cleanup +T-compiler

### CODE REVIEW

**Comment by bluss** [comment]
Just curious - the push_str handles string to string data so no encoding needed, in most cases using `push_str` should be simpler and more minimal; maybe there are other upsides to pushing a char?

**Comment by ldm0** [comment]
> Just curious - the push_str handles string to string data so no encoding needed, in most cases using `push_str` should be simpler and more minimal; maybe there are other upsides to pushing a char?

Check: https://github.com/rust-lang/rust-clippy/issues/5875

**Comment by LingMan** [comment]
`push` has a [fast-path for ASCII chars](https://doc.rust-lang.org/src/alloc/string.rs.html#1077-1082) that directly pushes the byte to the String's underlying Vec. The encoding as well as the `extend_from_slice` machinery are skipped entirely. While I didn't run any benchmark, I'd assume that makes `push` faster than `push_str` for ASCII-heavy data. Though, you are probably right for chars with 2+ bytes in their UTF-8 representation.

In this particular case it get's optimized down to basically [the same assembly](https://rust.godbolt.org/z/5MsWTM).

**Pull request merged**
