### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by flip1995** [comment]
Delayed sync, because of https://github.com/rust-lang/rust/pull/121671

"Fixed" by https://github.com/rust-lang/rust/issues/12363

**Comment by flip1995** [comment]
> +error: could not create incremental compilation crate directory `target/debug/test/incr/to_string_in_format_args_incremental-sgyntop819vz`: Read-only file system (os error 30)

Wut?

**Comment by Alexendoo** [comment]
That got deleted on the rust side previously, not sure how it came back - https://github.com/rust-lang/rust-clippy/issues/11126

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/113450

Yup, somehow the files were modified and I had to resolve conflicts, so I added them back. Removed them again.

**Pull request merged**
