### PR TITLE
Stabilize associated type bounds (RFC 2289)

### LINKED ISSUE #52662: Tracking issue for RFC 2289, "Associated type bounds"
This is a tracking issue for the RFC "Associated type bounds of form `MyTrait<AssociatedType: Bounds>`" (rust-lang/rfcs#2289). The feature gate is `#![feature(associated_type_bounds)]`.

**Steps:**

- [x] Implement the RFC - #57428
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [x] Does allowing this for `dyn` trait objects introduce any unforeseen issues? This can be resolved during stabilization.
   - [x] Use for trait objects has been forbidden in #120719

- [x] Resolve exact desugaring in the context of putting bounds on an associated type of a trait. See [discussion in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2289-associated-type-bounds.md#an-alternative-desugaring-of-bounds-on-associated-types).

- [x] Consider nested lifetimes, https://gist.github.com/Centril/b0e62d31d4ae1849535c3e506e1fad64.

**TODO:**

- [x] Extend with tests in https://github.com/rust-lang/rust/pull/57428#issuecomment-489336637.

- [x] https://github.com/rust-lang/rust/issues/61752

### PR DESCRIPTION
**Pull request by compiler-errors**
This PR stabilizes associated type bounds, which were laid out in [RFC 2289]. This gives us a shorthand to express nested type bounds that would otherwise need to be expressed with nested `impl Trait` or broken into several `where` clauses.

### What are we stabilizing?

We're stabilizing the associated item bounds syntax, which allows us to put bounds in associated type position within other bounds, i.e. `T: Trait<Assoc: Bounds...>`. See [RFC 2289] for motivation.

In all position, the associated type bound syntax expands into a set of two (or more) bounds, and never anything else (see "How does this differ[...]" section for more info).

Associated type bounds are stabilized in four positions:
* **`where` clauses (and APIT)** - This is equivalent to breaking up the bound into two (or more) `where` clauses. For example, `where T: Trait<Assoc: Bound>` is equivalent to `where T: Trait, <T as Trait>::Assoc: Bound`.
* **Supertraits** - Similar to above, `trait CopyIterator: Iterator<Item: Copy> {}`. This is almost equivalent to breaking up the bound into two (or more) `where` clauses; however, the bound on the associated item is implied whenever the trait is used. See #112573/#112629.
* **Associated type item bounds** - This allows constraining the *nested* rigid projections that are associated with a trait's associated types. e.g. `trait Trait { type Assoc: Trait2<Assoc2: Copy>; }`.
* **opaque item bounds (RPIT, TAIT)** - This allows constraining associated types that are associated with the opaque without having to *name* the opaque. For example, `impl Iterator<Item: Copy>` defines an iterator whose item is `Copy` without having to actually name that item bound.

The latter three are not expressible in surface Rust (though for associated type item bounds, this will change in #120752, which I don't believe should block this PR), so this does represent a slight expansion of what can be expressed in trait bounds.

### How does this differ from the RFC?

Compared to the RFC, the current implementation *always* desugars associated type bounds to sets of `ty::Clause`s internally. Specifically, it does *not* introduce a position-dependent desugaring as laid out in [RFC 2289], and in particular:
* It does *not* desugar to anonymous associated items in associated type item bounds.
* It does *not* desugar to nested RPITs in RPIT bounds, nor nested TAITs in TAIT bounds.

This position-dependent desugaring laid out in the RFC existed simply to side-step limitations of the trait solver, which have mostly been fixed in #120584. The desugaring laid out in the RFC also added unnecessary complication to the design of the feature, and introduces its own limitations to, for example:
* Conditionally lowering to nested `impl Trait` in certain positions such as RPIT and TAIT means that we inherit the limitations of RPIT/TAIT, namely lack of support for higher-ranked opaque inference. See this code example: https://github.com/rust-lang/rust/pull/120752#issuecomment-1979412531.
* Introducing anonymous associated types makes traits no longer object safe, since anonymous associated types are not nameable, and all associated types must be named in `dyn` types.

This last point motivates why this PR is *not* stabilizing support for associated type bounds in `dyn` types, e.g, `dyn Assoc<Item: Bound>`. Why? Because `dyn` types need to have *concrete* types for all associated items, this would necessitate a distinct lowering for associated type bounds, which seems both complicated and unnecessary compared to just requiring the user to write `impl Trait` themselves. See #120719.

### Implementation history:

Limited to the significant behavioral changes and fixes and relevant PRs, ping me if I left something out--
* #57428
* #108063
* #110512
* #112629
* #120719
* #120584

Closes #52662

[RFC 2289]: https://rust-lang.github.io/rfcs/2289-associated-type-bounds.html

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? types
@rustbot label: I-lang-nominated

**Comment by joshtriplett** [comment]
Thank you to @compiler-errors and everyone else who has worked on this! It's wonderful seeing this brought to the point of stabilization. I know many people's fingers keep expecting that this already works. :)

@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by jackh726** [comment]
For implementation history, its probably worth pointing out the PRs I made around the bound var refactoring. Its important in understanding how those are captured.

All in all though, I'm happy to see this stabilized. I also think its important to point out that other than in where clauses, you can't currently write these bounds, because they are more like the "ensures" clauses than the existing "where" clauses and thus have different effects on implied bounds.

**Comment by compiler-errors** [comment]
@jackh726: 

> For implementation history [...]

Feel free to edit and add more commits to the impl history section, since I don't know which ones you're talking about specifically. If they don't have to do with ATB specifically, maybe also leave a little note beside them that talks about how it impacts the impls?

> I also think its important to point out that other than in where clauses, you can't currently write these bounds [...]

Yep. I pointed this out a bit in the document. See "The latter three are not expressible in surface Rust", "however, the bound on the associated item is implied whenever the trait is used". Perhaps ping me if you'd like to request additions to this stabilization doc to make this more clear.

**Comment by pnkfelix** [comment]
@rfcbot reviewed

**Comment by jdahlstrom** [comment]
>   [Associated type item bounds] are not expressible in surface Rust

I sort of had naively assumed that this would already work:

```rust
trait Foo {
    type Bar: Iterator 
    where 
        <Self::Bar as Iterator>::Item: Display;
}
```

but rather it just causes an overflow when evaluating an impl. Should it work and be equivalent to `type Bar: Iterator<Item: Display>`? It certainly feels a bit inconsistent if not.

**Comment by jdahlstrom** [comment]
> Keep in mind that item bounds on associated types are not equivalent to where clauses in general, i.e.

Ah, I thought it's something like that but wasn't sure. Thanks for clarifying things for me!

**Comment by jackh726** [comment]
> Feel free to edit and add more commits to the impl history section, since I don't know which ones you're talking about specifically. If they don't have to do with ATB specifically, maybe also leave a little note beside them that talks about how it impacts the impls?

Yeah, so the specific test I have in mind is [hrtb.rs](https://github.com/rust-lang/rust/blob/master/tests/ui/associated-type-bounds/hrtb.rs). I had thought that I had added this (with the fixes to get it to work) in its own PR, but looks like it was in [this commit](https://github.com/rust-lang/rust/commit/6d5efa9f040d2638318f9e8b96eab718ef664e3c#diff-d2eca76b2fee669a5473eddaf4dbe3440e5458dcb562272088a1d843cfecb0d0) which has a bunch of unrelated things.

I think the important point to note from this test is that associated type bounds *can introduce new binders* (I think your reference PR actually doesn't include this) and describing how those new bounds desugar is important.

Not really sure the best way to include this though :) Seems to technical for a stabilization report, but obviously the syntax is important.

**Comment by jackh726** [comment]
Should this be blocked on documentation written? The only docs I see is the reference, but we probably want more than that, right?

**Comment by compiler-errors** [comment]
@jackh726: Do you have a recommendation for where those docs would live?

**Comment by jackh726** [comment]
Where do we currently talk about associate type bindings? Likely there. If we don't, then I guess it doesn't make sense to block on it.

**Comment by workingjubilee** [comment]
If this isn't about the core implementation being stabilized here, can you open a new issue for addressing any followups? Thanks!

**Pull request merged**
