### PR TITLE
rustc_mir: follow FalseUnwind's real_target edge in qualify_consts.

### LINKED ISSUE #62272: Unconditionally breaking `loop`s not allowed in constants.
*Technically* a regression from 1.24 to 1.25, but I don't think anyone used this.
Example code which used to be allowed:
```rust
pub const FOO: () = loop { break; };
```

I'm pretty sure this changed with #47802, which added the `FalseUnwind` terminator to MIR, but didn't handle it in const-checking (which otherwise ignores cleanup blocks).

cc @matthewjasper @nikomatsakis

### PR DESCRIPTION
**Pull request by eddyb**
As far as I can tell, this was accidentally omitted from #47802.
Fixes #62272.

r? @matthewjasper or @nikomatsakis

### CODE REVIEW

**Comment by Centril** [comment]
@eddyb Can you follow up with a PR to the reference as well?

**Comment by eddyb** [comment]
The reference? Why? This was an implementation bug, any code that works now used to be allowed, and any assumption that it wasn't supposed to be allowed was incorrect.
Did we document the broken behavior somehow? I kind of doubt it.

**Comment by Centril** [comment]
@eddyb Because the reference says nothing about loops that immediately break being allowed in const contexts, https://doc.rust-lang.org/nightly/reference/const_eval.html; and neither does it say anything about const functions either, https://doc.rust-lang.org/nightly/reference/items/functions.html#const-functions.

Speaking of const functions, can you account for `loop { break; }` in those as well?

> [...], and any assumption that it wasn't supposed to be allowed was incorrect.

(General note: what is "supposed to be" is decided by the language team)

**Comment by eddyb** [comment]
@Centril I'm only fixing a bug and bringing the behavior back to its previous state.
If you want to ban *syntactic* loops in constants, you need to do it on HIR, not MIR.
Feel free to open a separate issue for deciding what to do there.

To be clear: MIR constructs like `FalseUnwind` only exist for certain subtle borrowck analysis reasons, not to indicate any particular syntactic constructs, and there was no deliberate attempt in #47802 to disallow always-breaking loops in constants, making this *a bug that we should fix* regardless of syntactic restrictions.

r? @pnkfelix

**Comment by eddyb** [comment]
Oh, also, cc @oli-obk this might need `qualify_min_consts` support as well.

**Comment by pnkfelix** [comment]
> If you want to ban _syntactic_ loops in constants, you need to do it on HIR, not MIR.
> Feel free to open a separate issue for deciding what to do there.

I agree with this.

**Comment by pnkfelix** [comment]
r=me once merge conflict is resolved.

**Pull request merged**
