### PR TITLE
Rollup of all PRs in queue (temporary integration branch)

### PR DESCRIPTION
**Pull request by Manishearth**
Everything on this branch has passed check-stage2 on linux.

This is a temporary integration branch until [our buildbot problems](https://internals.rust-lang.org/t/buildbot-is-down-for-a-bit/2365/3) get fixed.
As the day progresses I'll merge more PRs into this branch once I get them through make check.

This branch isn't complete, keeping it up here so more people can merge PRs into integration if they want.

r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ p=1000000

(should merge when bors comes back up

**Comment by Manishearth** [comment]
@bors r+

Second set of PRs and fixes

**Comment by steveklabnik** [comment]
So, I am getting failures locally with 

```
    [run-pass] run-pass/issue-26709.rs
    [run-pass] run-pass/lang-item-public.rs
    [run-pass] run-pass/sepcomp-lib-lto.rs
```

but, none of these commits touch these files, and @Manishearth had already tested and gotten a pass, so i will assume that it's just a fluke on my system.

**Comment by steveklabnik** [comment]
Merging in all the other rollup'd PRs

**Comment by Manishearth** [comment]
noo

**Comment by steveklabnik** [comment]
2015-07-17-005944_168x156_scrot

aww yeah 22 seconds

**Comment by Manishearth** [comment]
:laughing:

**Comment by steveklabnik** [comment]
fine @bors, build https://github.com/rust-lang/rust/pull/25993, see if i care.

@Manishearth , i'm going to sleep, you got this?

**Comment by Manishearth** [comment]
Yep!

**Comment by Manishearth** [comment]
Okay, this seems stuck. @edunham @alexcrichton

**Comment by Manishearth** [comment]
Mornin' @bors 

:coffee:

**Comment by Manishearth** [comment]
:cake:

**Pull request merged**
