### PR TITLE
Refactor unsized suggestions

### PR DESCRIPTION
**Pull request by tlyu**
@rustbot label +A-diagnostics +A-traits +A-typesystem +C-cleanup +T-compiler

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
I'm not the right reviewer for this. Maybe r? @estebank

**Comment by camelid** [comment]
triage: r? @davidtwco (feel free to reassign)

**Review by davidtwco — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
