### PR TITLE
[TEST] Compile with 1 CGU

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 9c0483ab5cfc2aa7271db8ff9f5087e06e275172

**Comment by Zoxc** [comment]
Using a single CGU is still quite a bit faster. Can we use that for non-nightly builds? cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
We do not currently have the CI time budget to do so, I believe. Perhaps eventually -- but not currently.

**Comment by Zoxc** [comment]
If you build with 1 CGU, you'll have a larger CI time budget ;)

**Comment by alexcrichton** [comment]
More concretely analysis like this can often help guide where to add `#[inline]` annotation if LLVM needs some further nudging to inline functions we can measure make a difference

**Pull request closed without merging**
