### PR TITLE
Fix debuginfo for generators

### LINKED ISSUE #62572: Pretty-printing support for Rust generators
Support printing Rust generators in a way that looks more like enums. Generators (as of #59897) are represented in Rust as variant layouts with some extra fields on the outer layout. These extra fields (which are upvars, captured from the environment of the generator closure) seem to cause printing to become less pretty.

Today printing a Rust generator from `rust-gdb` looks like this:

`
$2 = generator_objects::main::generator {__0: 0x7fffffffd204, <<variant>>: {__state: 3, 0: generator_objects::main::generator::Unresumed, 1: generator_objects::main::generator::Returned, 2: generator_objects::main::generator::Panicked, 3: generator_objects::main::generator::Suspend0 {c: 6, d: 7}, 4: generator_objects::main::generator::Suspend1 {c: 6, d: 7}}}
`

Note that we print the fields of every single variant, even though the discriminant is marked in the [DWARF output](https://gist.github.com/tmandry/92e1368b51bea06d11da1e45218813db).

[Here's the test](https://github.com/rust-lang/rust/blob/c6a9e766f90a5271c2356fbc7941e38559200ab5/src/test/debuginfo/generator-objects.rs) which produced the above output. The above excerpt is from the second print in the test. `__0` in the output is the upvar for `a` from the environment (it should be called `a` instead of `__0`, but this is a problem in the compiler).

I also opened [this bug on GDB](https://sourceware.org/bugzilla/show_bug.cgi?id=24801); I'm not sure how much we upstream pretty printing support today.

### LINKED ISSUE #79009: 1.48 beta test failures, debuginfo-gdb 9.2 -> 10.1
This is with 1.48.0-beta.8, and previously these all passed in 1.47.0. On Debian I see these failures on all architectures. The main difference is we are using gdb 10 now, gdb 9.2 previously. The other debuginfo tests pass fine.

<details><summary>test [debuginfo-gdb] debuginfo/extern-c-fn.rs ... FAILED</summary>

~~~~
error: line not found in debugger output: $1 = [...]"abcd\000"
status: exit code: 0
command: "/usr/bin/gdb" "-quiet" "-batch" "-nx" "-command=/<<PKGBUILDDIR>>/build/x86_64-unknown-linux-gnu/test/debuginfo/extern-c-fn.gdb/extern-c-fn.debugger.script"
stdout:
------------------------------------------
GNU gdb (Debian 10.1-1) 10.1
[..]
Breakpoint 1 at 0x122e: file /<<PKGBUILDDIR>>/src/test/debuginfo/extern-c-fn.rs, line 52.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, extern_c_fn::fn_with_c_abi (s=0x555555556081, len=20) at /<<PKGBUILDDIR>>/src/test/debuginfo/extern-c-fn.rs:52
52	    zzz(); // #break
$1 = (*mut u8) 0x555555556081
$2 = 20
$3 = 19
$4 = true
$5 = 20.5
[Inferior 1 (process 25039) exited normally]
~~~~
</details>

<details><summary>test [debuginfo-gdb] debuginfo/generator-objects.rs ... FAILED</summary>

~~~~
error: line not found in debugger output: $1 = generator_objects::main::generator-0 {__0: 0x[...], <<variant>>: {__state: 0, 0: generator_objects::main::generator-0::Unresumed, 1: generator_objects::main::generator-0::Returned, 2: generator_objects::main::generator-0::Panicked, 3: generator_objects::main::generator-0::Suspend0 {[...]}, 4: generator_objects::main::generator-0::Suspend1 {[...]}}}
status: exit code: 0
command: "/usr/bin/gdb" "-quiet" "-batch" "-nx" "-command=/<<PKGBUILDDIR>>/build/x86_64-unknown-linux-gnu/test/debuginfo/generator-objects.gdb/generator-objects.debugger.script"
stdout:
------------------------------------------
GNU gdb (Debian 10.1-1) 10.1
[..]
Breakpoint 1 at 0x137e: file /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs, line 58.
Breakpoint 2 at 0x13ab: file /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs, line 60.
Breakpoint 3 at 0x13d8: file /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs, line 62.
Breakpoint 4 at 0x140f: file /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs, line 64.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, generator_objects::main () at /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs:58
58	    _zzz(); // #break
$1 = (null)

Breakpoint 2, generator_objects::main () at /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs:60
60	    _zzz(); // #break
$2 = (null)

Breakpoint 3, generator_objects::main () at /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs:62
62	    _zzz(); // #break
$3 = (null)
6 7 8

Breakpoint 4, generator_objects::main () at /<<PKGBUILDDIR>>/src/test/debuginfo/generator-objects.rs:64
64	    _zzz(); // #break
$4 = (null)
A debugging session is active.

	Inferior 1 [process 25180] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
~~~~
</details>

<details><summary>test [debuginfo-gdb] debuginfo/issue-57822.rs ... FAILED</summary>

~~~~
error: line not found in debugger output: $2 = issue_57822::main::generator-3 {__0: issue_57822::main::generator-2 {__0: 2, <<variant>>: {[...]}}, <<variant>>: {[...]}}
status: exit code: 0
command: "/usr/bin/gdb" "-quiet" "-batch" "-nx" "-command=/<<PKGBUILDDIR>>/build/x86_64-unknown-linux-gnu/test/debuginfo/issue-57822.gdb/issue-57822.debugger.script"
stdout:
------------------------------------------
GNU gdb (Debian 10.1-1) 10.1
[..]
Breakpoint 1 at 0x12ef: file /<<PKGBUILDDIR>>/src/test/debuginfo/issue-57822.rs, line 51.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, issue_57822::main () at /<<PKGBUILDDIR>>/src/test/debuginfo/issue-57822.rs:51
51	    zzz(); // #break
$1 = issue_57822::main::closure-1 (issue_57822::main::closure-0 (1))
$2 = issue_57822::main::generator-2{__0: 2, __state: 0, 0: issue_57822::main::generator-2::Unresumed}
A debugging session is active.

	Inferior 1 [process 25521] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
~~~~
</details>

<details><summary>test [debuginfo-gdb] debuginfo/pretty-huge-vec.rs ... FAILED</summary>

~~~~
error: line not found in debugger output: $2 = &[u8] {data_ptr: [...]"\000", length: 1000000000}
status: exit code: 0
command: "/usr/bin/gdb" "-quiet" "-batch" "-nx" "-command=/<<PKGBUILDDIR>>/build/x86_64-unknown-linux-gnu/test/debuginfo/pretty-huge-vec.gdb/pretty-huge-vec.debugger.script"
stdout:
------------------------------------------
GNU gdb (Debian 10.1-1) 10.1
[..]
Breakpoint 1 at 0x1fef: file /<<PKGBUILDDIR>>/src/test/debuginfo/pretty-huge-vec.rs, line 27.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, pretty_huge_vec::main () at /<<PKGBUILDDIR>>/src/test/debuginfo/pretty-huge-vec.rs:27
27	    zzz(); // #break
$1 = Vec(size=1000000000) = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}
$2 = &[u8] {data_ptr: 0x7fffbc266010, length: 1000000000}
A debugging session is active.

	Inferior 1 [process 26156] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
~~~~
</details>

### PR DESCRIPTION
**Pull request by lrh2000**
First, all fields except the discriminant (including `outer_fields`) should be put into structures inside the variant part, which gives an equivalent layout but offers us much better integration with debuggers.

Second, artificial flags in generator variants should be removed.
 - Literally, variants are not artificial. We have `yield` statements, upvars and inner variables in the source code.
 - Functionally, we don't want debuggers to suppress the variants. It contains the state of the generator, which is useful when debugging. So they shouldn't be marked artificial.
 - Debuggers may use artificial flags to find the active variant. In this case, marking variants artificial will make debuggers not work properly.

Fixes #62572.
Fixes #79009.

And refer https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Debuginfo.20for.20generators.

### CODE REVIEW

**Comment by lrh2000** [comment]
cc @tmandry

**Comment by tmandry** [comment]
> There is actually another commit ([lrh2000@e65c460](https://github.com/lrh2000/rust/commit/e65c460dfa2ff9546b5c58a0cda97927779c6863)) that names the upvars for closures and generators in debuginfo. Finally we'll be able to see something like
> 
> ```
> y::main::closure-0 {_upvar_ref_mut__b: 0x[...], _upvar_ref__a: 0x[...]}
> ```

I'd remove `upvar` since it doesn't have meaning outside the compiler. `mut` also doesn't really matter in this context, imo. `ref` does help explain why you're seeing a pointer value, I like that.

**Comment by tmandry** [comment]
Closes #62572 too I think.

I'd like to eventually do this for GeneratorLayout itself, but that's another change.

Thanks! This is a nice improvement. I think this change is ready so I'm going to approve for now and you can open another PR with the upvar naming change.

@bors r+

**Comment by lrh2000** [comment]
> I'd remove upvar since it doesn't have meaning outside the compiler. mut also doesn't really matter in this context, imo. ref does help explain why you're seeing a pointer value, I like that.

Thanks a lot for your feedback. I'll take your advice. The trickiest problem is that if we simply remove `upvar`, we may encounter collision of names accidentally. For example, see the following code:
```rust
fn main() {
    let a = 3;
    let mut c = move || {
        let a = a;
        yield;
        let b = a;
    };
    Pin::new(&mut c).resume(());
    _zzz();
}
```
We could get something like
```
$1 = generator_objects::main::generator-0::Suspend0{a: 3, _upvar__a: 3}
```
But if we simply remove `_upvar__`, there are two fields named `a` in the same structure. I'll think about how to solve the problem, or if you have any suggestions, I'll appreciate it.

**Comment by lrh2000** [comment]
> I'd remove upvar since it doesn't have meaning outside the compiler.

I think it is reasonable. How about just replacing `upvar` with `captured`. Do you think it is better? `capture` is widely used in Rust official documentation, [here] and [there].

[here]: https://doc.rust-lang.org/rust-by-example/fn/closures/capture.html
[there]: https://doc.rust-lang.org/book/ch13-01-closures.html

> `mut` also doesn't really matter in this context, imo

I agree. I added `mut` because it is consistent with the style of the Rust language. It may be helpful if finally we can add a pretty-printer in debuggers. It demangles  something like `_captured_ref_mut__a` into `&mut a` and show it to the end users. (So in the meantime, it also hides `captured` or `upvar`, thus their name doesn't really matter if we can achieve the final goal.)

**Comment by tmandry** [comment]
> > I'd remove upvar since it doesn't have meaning outside the compiler.
> 
> I think what you said is reasonable. How about just replacing `upvar` with `captured`? Do you think it is better? `capture` is widely used in Rust official documentation, [here](https://doc.rust-lang.org/rust-by-example/fn/closures/capture.html) and [there](https://doc.rust-lang.org/book/ch13-01-closures.html).

I'd be fine with it. This should also affect closures. We should also support printing the original name of the variable while stepping through the closure/generator (I think we already do).

> > `mut` also doesn't really matter in this context, imo.
> 
> I agree. I added `mut` because it is consistent with the style of the Rust language. It may be helpful if finally we can add a pretty-printer in debuggers. It demangles something like `_captured_ref_mut__a` into `&mut a` and show it to the end users. (So in the meantime, it also hides `captured` or `upvar`, thus their name doesn't really matter if we can achieve the final goal.)

My sense is that could be confusing, since the user never writes `&mut a` in their code to get the capture. I don't feel too strongly about this.

**Pull request merged**
