### PR TITLE
Some perf experiments

### PR DESCRIPTION
**Pull request by oli-obk**
r? @ghost

looking at regression from https://github.com/rust-lang/rust/pull/99102#issuecomment-1240323004

### CODE REVIEW

**Comment by lqd** [comment]
the perf bot has probably lost this one ?!

**Comment by oli-obk** [comment]
@perfbot build 10d870608eaa08538f193fe3a636577d0660000b

**Comment by oli-obk** [comment]
That was fast ?!

**Comment by bugadani** [comment]
"No results" on the comparison page.

**Comment by oli-obk** [comment]
I expanded the view, they are all too small to be shown. But if you select "Show non-relevant results" you'll get more data

**Comment by bugadani** [comment]
Oh I thought nothing ran 😅

**Comment by lqd** [comment]
These 3 benchmarks are pretty quick to run and the queue was empty :)

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/101561#issuecomment-1240324440 included only a couple of benchmarks, though we should probably surface that on result completion too.

**Pull request closed without merging**
