### PR TITLE
Remove `collect` in `doctest::run_test`

### PR DESCRIPTION
**Pull request by vacuus**

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

**Comment by camelid** [comment]
This actually causes slight instructions count regressions. It may improve max-rss, but the reported changes are not very significant.

**Comment by camelid** [comment]
As such, since the new code is slightly more complex IMO, I'm going to close this PR.

**Comment by camelid** [comment]
And now I'm having second thoughts... the new code might actually be better. I'll re-open this and let someone else decide. :P

**Comment by CraftSpider** [comment]
Personally I think this makes the code look a bit worse, what I'd really like to see is the currently unstable `intersperse` used here, which would allow a single collect.

**Comment by camelid** [comment]
We can use `intersperse` (rustdoc already has the feature gate enabled), but I'm not certain it'd work in this particular case since we need a trailing newline.

**Comment by CraftSpider** [comment]
I like the way this looks now, going to try a perf run to see how this way of doing it fairs

**Comment by camelid** [comment]
Hmm, I don't think the perf tool runs doctests, so that perf run might not even be testing anything.

**Comment by CraftSpider** [comment]
I'll take a look, but if they don't have doctests, then I imagine any difference is more likely noise than real affect of this PR. I'm leaning towards merge if that's the case.

**Comment by Dylan-DPC** [comment]
@CraftSpider any updates on this?

**Comment by CraftSpider** [comment]
After another look, no noticeable perf impact, but it does look nice and I believe slightly reduces allocations

@bors r+

**Pull request merged**
