### PR TITLE
Overhaul `Diagnostic` and `DiagnosticBuilder`

### PR DESCRIPTION
**Pull request by nnethercote**
Implements the first part of https://github.com/rust-lang/compiler-team/issues/722, which moves functionality and use away from `Diagnostic`, onto `DiagnosticBuilder`.

Likely follow-ups:
- Move things around, because this PR was written to minimize diff size, so some things end up in sub-optimal places. E.g. `DiagnosticBuilder` has impls in both `diagnostic.rs` and `diagnostic_builder.rs`.
- Rename `Diagnostic` as `DiagInner` and `DiagnosticBuilder` as `Diag`.

r? @davidtwco

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
This looks good to me given the planned follow-ups.

**Comment by nnethercote** [comment]
> I believe this has [broken Rocket on nightly](https://github.com/rwf2/Rocket/actions/runs/7985532655/job/21804162579).

Thanks for the report, #121427 should fix it.

**Comment by SergioBenitez** [comment]
Sure did! Thank you!

**Pull request merged**
