### PR TITLE
Add rustc version info (git hash + date) to dist tarball

### PR DESCRIPTION
**Pull request by josephDunne**
a fix for #32444

### CODE REVIEW

**Comment by ranma42** [comment]
I think you meant r? @brson

**Comment by josephDunne** [comment]
Thanks @brson in #32444 you mentioned something needs to change in src/rustbuild but im not sure what (and I cant see a folder with that name). Is that still relevant.

Also I cant see why the Travis build fail. It said all tests passed.

**Comment by brson** [comment]
@bors r-

Oh you are right @josephDunne. Thanks for fixing my review :)

[Here's where rustbuild creates the same source tarball](https://github.com/rust-lang/rust/blob/master/src/bootstrap/dist.rs#L391). That `plain_dst_src` directory needs to contain the `version` file, the value of which is `build.version`.

**Comment by josephDunne** [comment]
Am I correct in saying that the other Tarballs have a version file created by the gen_installer.sh script?
How to I exercise this code to test it? You can just point me at the docs if they exist

**Comment by josephDunne** [comment]
r? @brson

I have updated the rustbuild files. I just don't know how to drive the process to confirm it works :-/

**Comment by brson** [comment]
> Am I correct in saying that the other Tarballs have a version file created by the gen_installer.sh script?
> How to I exercise this code to test it? You can just point me at the docs if they exist

No, the version file is only created for the rustc installer and the source tarball, by the build script, and the one in the rustc tarball is later copied into the rust tarball by [rust-packaging](https://github.com/rust-lang/rust-packaging). The gen_installer.sh script doesn't care about the program version.

You can test with `./configure --enable-rustbuild && make dist`

**Comment by josephDunne** [comment]
ok I am happy with this commit. Both the rustc-1.13.0-dev-src.tar.gz and rustc-1.13.0-dev-x86_64-apple-darwin.tar.gz on my computer have a version file in them with the following content:

```
1.13.0-dev (8bb856cbf 2016-09-03)
```

**Pull request merged**
