### PR TITLE
Allow raw pointers to be undef in Miri mode

### PR DESCRIPTION
**Pull request by Aaron1011**
The doctest at https://doc.rust-lang.org/std/mem/fn.uninitialized.html#examples
creates an uninitialized Vec - which (transitively) contains an
uninitialized raw pointer. Since this code is sound, Miri should allow
raw pointers to be undefined, to allow running this kind of code in
Miri.

I've left this as error in const_mode in order to avoid chaning the
behavior of const functions.

### CODE REVIEW

**Comment by Aaron1011** [comment]
I'm not sure what the best way to write a test for this would be.

**Comment by Aaron1011** [comment]
Oops - I just realized that this change was already made in https://github.com/rust-lang/rust/pull/56094

**Comment by RalfJung** [comment]
> Since this code is sound

Rather -- since we haven't yet decided if this code is sound. ;)  Whether undef is allowed in raw ptrs is not decided yet, and you shouldn't rely on it being allowed.

But yes, I already made the same change in that other PR.

**Pull request closed without merging**
