### PR TITLE
Add loongarch64 abi support

### PR DESCRIPTION
**Pull request by zhaixiaojuan**

### CODE REVIEW

**Comment by oli-obk** [comment]
As far as I can tell this adds a new Tier 3 target.

There are instructions at https://doc.rust-lang.org/rustc/target-tier-policy.html#tier-3-target-policy for the conditions that need to be met in order to add such a target.

Please create an [MCP](https://github.com/rust-lang/compiler-team/issues/new/choose) for adding the new target.

**Comment by apiraino** [comment]
The MCP is https://github.com/rust-lang/compiler-team/issues/518 and is now accepted. Can this PR be reviewed or are there other middle steps?

Also, what's the relationship between this PR and https://github.com/rust-lang/rust/pull/96971? Should they progress together? Should they share the reviewers (i.e. same people having the context)?

thanks

**Comment by oli-obk** [comment]
@bors r+

Seems fine to merge this now and deduplicate later

**Comment by xen0n** [comment]
@zhaixiaojuan: Please kindly cc me for further LoongArch changes.

In this PR you used the RISC-V terminology "XLEN" and "FLEN", while they should be "GRLen" and "FRLen" respectively for LoongArch, even if they're actually analogues (with the LoongArch taking the concept from RISC-V). Fortunately the rest looks correct.

**Comment by zhaixiaojuan** [comment]
> @zhaixiaojuan: Please kindly cc me for further LoongArch changes.
> 
> In this PR you used the RISC-V terminology "XLEN" and "FLEN", while they should be "GRLen" and "FRLen" respectively for LoongArch, even if they're actually analogues (with the LoongArch taking the concept from RISC-V). Fortunately the rest looks correct.

Ok

**Pull request merged**
