### PR TITLE
[beta] Doc search backports

### PR DESCRIPTION
**Pull request by durka**
This is a backport of #46081, #46175, #46433, and #46672. They all merged cleanly but I haven't tried a build; let's see what Travis says.

These PRs fix pretty annoying issues with doc search and so I think it's important they don't slip to stable, but these PRs have *NOT* been `beta-accepted` yet.

cc @steveklabnik @GuillaumeGomez can you tag the docs team to talk about beta-acceptance?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/docs

**Comment by QuietMisdreavus** [comment]
Since we called off next week's meeting, we won't have the chance to get a proper meeting discussion of this before the beta/stable cutoff.

I'm in favor of backporting this, because beta got (effectively) a partial implementation of the search tabs. I would hate to see a complete stable cycle go by with an inferior docs experience.

**Comment by steveklabnik** [comment]
Sounds good to me!

**Comment by GuillaumeGomez** [comment]
Ok then let's move forward.

@bors: r+

**Comment by durka** [comment]
There's no tests for this, but I threw up a quick server here with docs from this PR: https://alexburka.com:8000

Comparing to beta docs, it looks to me like all the bugs listed here are indeed fixed.

**Comment by kennytm** [comment]
@bors p=2

Beta backport.

**Comment by alexcrichton** [comment]
Thanks for the backport @durka (belatedly!).

FWIW in terms of tag management I made this mistake of thinking a bunch of PRs weren't backported when they were here! Feel free to cc me on beta backports to ensure the tags are all done right and otherwise our current method of managing the tags is listed at https://forge.rust-lang.org/beta-backporting.html.

**Pull request merged**
