### PR TITLE
syntax: Move ast_map into it's own crate

### PR DESCRIPTION
**Pull request by erickt**
This lets us remove the arena dependency from libsyntax, which is unstable, and supports making libsyntax compile on beta/1.0 (#24518).

r? @alexcrichton

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I have no objection, but I wonder if this should be a rustc crate? Seems pretty specific to the compiler.

**Comment by erickt** [comment]
@nikomatsakis: I had thought it could be useful for future syntax extensions, but I suppose if we go down that road we can always rename `rustc_ast_map` to `syntax_ast_map`. I'll change the name.

**Comment by richo** [comment]
I haven't touched this codebase in a long time (and even then it was super
experimental, I was just curious to see how feasible this approach was),
but are changes like this going to affect visibility for something like:
https://github.com/richo/commavm/blob/master/src/main.rs#L1-L5

**Comment by erickt** [comment]
@alexcrichton / @nikomatsakis: Updated the PR to rename this new package to `rustc_ast_map`.

@richo: As far as I can tell you're not using ast_map, so this shouldn't impact you. I suggest you check out [syntex](https://github.com/erickt/rust-syntex) though, which hopefully will allow for syntax extensions in 1.0 :)

**Comment by Gankro** [comment]
@erickt ping (needs rebase)

**Pull request closed without merging**
