### PR TITLE
[beta] Revert #117472: Stabilize C string literals

### PR DESCRIPTION
**Pull request by wesleywiser**
Based on discussion in [#t-lang](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/rfc.203349.3A.20mixed.20utf8.20literals), revert the stabilization of C string literals in Rust 1.76. 

I also reverted #118566 as it uses the newly stabilized C string literals in various places.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Why revert https://github.com/rust-lang/rust/pull/118566? Seems like a complex diff for no reason, just use a few `#![cfg_attr(not(bootstrap), feature(c_str_literal))]`

**Comment by wesleywiser** [comment]
> Why revert #118566? Seems like a complex diff for no reason, just use a few `#![cfg_attr(not(bootstrap), feature(c_str_literal))]`

Yeah, that's fair. The reverts were clean/trivial so that seemed slightly preferable to me but it's only a few lines to fix the feature gates.

**Comment by nnethercote** [comment]
> The reverts were clean/trivial so that seemed slightly preferable to me but it's only a few lines to fix the feature gates.

@wesleywiser Will you go forward with that alternative approach? I don't mind which way the revert happens, but this is somewhat time-sensitive so I don't want it to sit without progress for long.

**Comment by nnethercote** [comment]
Thanks for doing this!

@bors r+

**Comment by NeptuneUltra101** [comment]
> https://github.com/rust-lang/rust/pull/119528#issuecomment-188419721- [ ] 8~~__~~

**Comment by ehuss** [comment]
@bors retry

timeout on dist-apple-various

**Comment by ehuss** [comment]
@bors retry

timeout on two apple runners

**Comment by cuviper** [comment]
Since this already merged on beta, and was [approved](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-01-11/near/412362285) afterward, I think the "backport" is done.

@rustbot label -beta-nominated +beta-accepted

**Pull request merged**
