### PR TITLE
Fix note for type alias in trait position

### LINKED ISSUE #31686: `type` aliases cannot be used for traits note is printed wrongly
```
src/librustc/session/mod.rs:63:39: 63:67 error: `mir::transform::Passes` is not a trait [E0404]
src/librustc/session/mod.rs:63     pub mir_passes: RefCell<for<'tcx> mir::transform::Passes<'tcx>>,
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc/session/mod.rs:63:39: 63:67 help: run `rustc --explain E0404` to see a detailed explanation
src/librustc/session/mod.rs:63:39: 63:67 note: `type` aliases cannot be used for traits
src/librustc/session/mod.rs:63     pub mir_passes: RefCell<for<'tcx> mir::transform::Passes<'tcx>>,
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The error here is pretty clear, but the note is completely wrong as the relevant snippet appears in the type of the struct field and not `type` item.

### PR DESCRIPTION
**Pull request by vegai**
Fix note for type alias in trait position

Fixes #31686

### CODE REVIEW

**Comment by Manishearth** [comment]
You'll need to update the tests too. tests/compile-fail/issue-5035.rs will need a `//~^^ NOTE: ` marker with the second note

**Comment by vegai** [comment]
Yep, also 3907 broke. Fixed'em both.

**Comment by Manishearth** [comment]
@bors r+

Thanks!

**Comment by bluss** [comment]
I edited the PR title and the PR message, so that a small description of the change lands in the merge message.

**Pull request merged**
