### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #107592 (Default `repr(C)` enums to `c_int` size)
 - #107956 (Copy `bin/*` and `lib/*.dylib` files to `stage0-sysroot`)
 - #108126 (fix a line, and do a consistency fix)
 - #108144 (Add compiler-errors to a few more triagebot groups)
 - #108149 (typo)
 - #108154 (`BasicBlock::new(0)` -> `START_BLOCK` [no functional changes])

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=107592,107956,108126,108144,108149,108154)

### CODE REVIEW

**Comment by nnethercote** [comment]
The bootstrapping perf test failed, which is weird. The last few lines of output with the error:
```
       [RUSTC-TIMING] getopts test:false 0.481
          Compiling proc_macro v0.0.0 (/home/collector/rustc-perf/rust/library/proc_macro)
       [RUSTC-TIMING] proc_macro test:false 2.640
          Compiling test v0.0.0 (/home/collector/rustc-perf/rust/library/test)
       [RUSTC-TIMING] test test:false 3.324
           Finished release [optimized] target(s) in 33.38s
       thread 'main' panicked at 'failed to copy `/home/collector/rustc-perf/target/release/build` to `/home/collector/rustc-perf/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/bin/build`: the source path is neither a regular file nor a symlink to a regular file', lib.rs:1419:17
       note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Strange. Has anything about the paths changed lately? I guess we can keep watching, see if this is a once-only failure or if it continues.

**Comment by matthiaskrgr** [comment]
Hm, the next merge commit also lacks any kind of benchmark...
I wonder if https://github.com/rust-lang/rust/pull/107956/files messed up things for the benchmark server somehow.

**Comment by lqd** [comment]
Only the bootstrap timings are missing, correct ? Make sure the following is toggled.

image

**Comment by matthiaskrgr** [comment]
Ugh :sweat_smile:  could we make it say "No relevant results" instead of "No results" if there are results but that checkbox is not ticket? :/

**Comment by Kobzol** [comment]
Implemented [here](https://github.com/rust-lang/rustc-perf/pull/1525).

**Pull request merged**
