### PR TITLE
[beta] Fix the `f16` and `f128` feature gate regression

### PR DESCRIPTION
**Pull request by tgross35**
Apply the fix from https://github.com/rust-lang/rust/pull/123307#event-12351348325.

Fixes https://github.com/rust-lang/rust/issues/123282

### CODE REVIEW

**Comment by Nilstrieb** [comment]
The way backports usually work is that we label the original PR, and it then gets reviewed in the weekly compiler triage meeting (today). The backport PRs against beta are then usually made by cuviper or other release team members.
But doing it like this should work too, and be seen and reviewed today.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-04-04/near/431330676). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted

**Comment by cuviper** [comment]
Our usual [backporting](https://forge.rust-lang.org/release/backporting.html) query only looks at closed (merged) PRs, so it doesn't show this one. But now that I've seen it, I'll include this in the aggregate backport PR I'm creating.

**Comment by tgross35** [comment]
Thanks all, think I can close this since it's going in through Josh's tree

**Pull request closed without merging**
