### PR TITLE
[Experiment] Replace jemalloc with mimalloc beta branch

### PR DESCRIPTION
**Pull request by fee1-dead**
Like #92249 but uses the improved branch to test out max-rss regression

r? @ghost

### CODE REVIEW

**Comment by fee1-dead** [comment]
Not sure what has happened but I don't know why the last try build was still using outdated versions.

@bors try

**Comment by bjorn3** [comment]
This is now a regression for inst count but an improvement for max-rss.

**Comment by the8472** [comment]
The wall-time results look worse than the instructions.

**Pull request closed without merging**
