### PR TITLE
Updated E0560 to new error format

### LINKED ISSUE #36199: E0560 needs to be updated to new format
From: src/test/compile-fail/E560.rs

E0560 needs a span_label, updating it from:

```
error[E0560]: structure `Simba` has no field named `father`
  --> src/test/compile-fail/E560.rs:16:32
   |
16 |     let s = Simba { mother: 1, father: 0 }; //~ ERROR E0560
   |                                ^^^^^^
```

To:

```
error[E0560]: structure `Simba` has no field named `father`
  --> src/test/compile-fail/E560.rs:16:32
   |
16 |     let s = Simba { mother: 1, father: 0 }; //~ ERROR E0560
   |                                ^^^^^^ `Simba` does not have this field
```

### PR DESCRIPTION
**Pull request by aclarry**
Added a small bit of code to add a label for E0560.

Also renamed src/test/compile-fail/E560.rs file to E0560.rs (not sure why it was named E560).
Updated all test cases which check this error.

Closes #36199

### CODE REVIEW

**Comment by Cobrand** [comment]
@aclarry As expected, your PR for E0560 and mine for E0559 are in conflict. You have to rebase your PR onto master so there are no conflicts anymore.

By the way, @jonathandturner takes care of the "update to new format" thing, so you have to tell rust-highfive that he is the assignee, by doing like so : 
r? @jonathandturner 
(Of course that won't do anything since only the creator of the PR can do that)

Otherwise your PR will probably unnoticed for awhile :)

**Comment by aclarry** [comment]
@Cobrand thanks for the heads up, I thought I merged in your changes, but apparently not :)

r? @jonathandturner

**Comment by jonathandturner** [comment]
@aclarry - looks good.  After you fix up the conflict, you can ping me and we can give it a go.

**Comment by aclarry** [comment]
@jonathandturner I'm running into a bit of a conflict with E0559.  Specifically, which behaviour do we want when we can also suggest a field name?

1. Don't include E0560 label
```
error[E0559]: variant `Field::Fool` has no field named `joke`
 --> src/test/compile-fail/E0559.rs:16:27
   | 
16 |     let s = Field::Fool { joke: 0 }; 
   |                           ^^^^ did you mean `x`?    
```

2. Include label combining E0559 and E0560
```
error[E0559]: variant `Field::Fool` has no field named `joke`
 --> src/test/compile-fail/E0559.rs:16:27
   | 
16 |     let s = Field::Fool { joke: 0 }; 
   |                           ^^^^ `Field::Fool` does not have this field. Did you mean `x`?    
```

3. Include both labels
```
error[E0559]: variant `Field::Fool` has no field named `joke`
 --> src/test/compile-fail/E0559.rs:16:27
   | 
16 |     let s = Field::Fool { joke: 0 }; 
   |                           ^^^^   
   |                           | `Field::Fool` does not have this field.
   |                           |  did you mean `x`?  
```

I'm going to update my PR to use 2), since it seems the most natural, but let me know what the preferred format is.

**Comment by jonathandturner** [comment]
I lean towards option 1.  We could make it explain a little more as well:

```
error[E0559]: variant `Field::Fool` has no field named `joke`
 --> src/test/compile-fail/E0559.rs:16:27
   | 
16 |     let s = Field::Fool { joke: 0 }; 
   |                           ^^^^ unknown field - did you mean `x`?  
```

**Comment by jonathandturner** [comment]
@aclarry - Looks like it's not currently building:

```
error[E0531]: unresolved variant or struct `TyEnum`
    --> src/librustc_typeck/check/mod.rs:3097:23
     |
3097 |         } else if let ty::TyEnum(..) = ty.sty {
     |                       ^^^^^^^^^^

error: aborting due to previous error
```

**Comment by aclarry** [comment]
@jonathandturner Yep, just working that out at the moment.  I updated the PR to use the message ```field does not exist - did you mean `x`?```

**Comment by aclarry** [comment]
@jonathandturner The CI tests have passed, this should be ready to merge if you're happy with the implementation and the updated label for E0559.

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Pull request merged**
