### PR TITLE
Don't assume `FILE_ID_BOTH_DIR_INFO` will be aligned

### LINKED ISSUE #104530: `std::fs::remove_dir_all` occasionally panics on Windows with `assertion failed: info.is_aligned()`
`remove_dir_all` panics on some Windows version when calling `std::fs::remove_dir_all` due to a newly introduced `assert!`.

This code:

```rust
std::fs::remove_dir_all(&pings_dir)?;
```

I expected to see this happen: It removes everything or reports an error.

Instead, this happened: It panics with `assertion failed: info.is_aligned()`.

### Meta

```
$ rustc --version
rustc 1.65.0 (897e37553 2022-11-02)
```

(Crashes on Windows, but we're just using upstream 1.65.0 there).

Full Firefox crash report: https://crash-stats.mozilla.org/report/index/02651884-5b3a-488e-9a43-994b80221106
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1799442

Last commit that changed that: https://github.com/rust-lang/rust/commit/c41f21b3e4e992d5c5c11dae880dc81192a12653
PR: https://github.com/rust-lang/rust/pull/101171
File: https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/fs.rs#L737-L739

We saw that on 3 Windows 10 versions: 10.0.18362, 10.0.18363 and 10.0.19044.
Though I haven't checked the latest crashes, it might be more now.

cc @thomcc

### PR DESCRIPTION
**Pull request by thomcc**
Fixes #104530. See that issue for info.

r? @ChrisDenton

### CODE REVIEW

**Comment by thomcc** [comment]
Nominating for beta backport since it seems pretty bad. I'm hoping it's just an issue with sketchy drivers, but who knows.

**Comment by thomcc** [comment]
I think we should consider using a different directory iteration method (FindNextFileW, like we use for the other directory iteration), but I'm not sure if there's a reason we're doing it the way we are currently (perhaps stability in the face of deletions?)

That said, I know `remove_dir_all` is a pretty tricky function, and has undergone a few rewrites. I definitely don't feel like rewriting it here is justified (especially since I've requested a backport), and could easily cause more problems than it solves.

**Comment by ChrisDenton** [comment]
`FindFirstFileW`/`FindNextFileW` takes a file path so it's a non-starter for `remove_dir_all` given the security considerations. And in any case `FindFirstFileW`/`FindNextFileW` will ultimately be using something similar to what `remove_dir_all` is using (well the NT equivalent) under the hood.

There are various other things we could do (like doing a memcpy if unaligned) but I do agree we should keep this small for now. So...

@bors r+

**Comment by thomcc** [comment]
Ah, good points!

**Comment by thomcc** [comment]
> like doing a memcpy if unaligned

I decided to do this. It's not much code, but probably warrants re-review.

@bors r-

**Comment by thomcc** [comment]
I'll leave the backport request present, but it's tempting to remove it: it's worth noting that this appears to be due to a bug in a particular sandboxing application (Sandboxie), rather than a bug in the stdlib itself.

These sorts of bugs are somewhat unsurprising on Windows, given how arbitrary things insert themselves in various places, but I'm unconvinced it's actually worth taking *that* seriously as a result. Still, I'll leave the request present so we can discuss in the meeting. It's harmless enough either way.

**Pull request merged**
