### PR TITLE
Rustdoc mutability removal

### LINKED ISSUE #67470: [rustdoc] Remove clean Mutability type if unnecessary
As discussed here: https://github.com/rust-lang/rust/pull/67355#discussion_r360351226

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #67470.

As discussed in another PR, the `clean::Mutability` type in rustdoc is useless. So let's remove it!

r? @Centril

### CODE REVIEW

**Comment by Centril** [comment]
You'll need to rebase this `--onto` https://github.com/rust-lang/rust/pull/67355.
r=me with that done.

**Comment by GuillaumeGomez** [comment]
Keeping a tab open meanwhile. ;)

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/67355 has landed.

**Comment by GuillaumeGomez** [comment]
I badly replaced one of the pattern matching...

**Pull request merged**
