### PR TITLE
Fix wording for `Option<T>.unwrap`

### LINKED ISSUE #23713: Make Option.unwrap documentation more precise
Reading the current documentation about `Option<T>.unwrap()` at

  http://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap

it is not clear to me what the effect of `unwrap()` is. I was supposing calling this function returns the value stored in the Option type and replaces it by an `None` value. However, this seems not to be the case as the second assertion in the following example program passes fine:

```rust
fn main() {
    let 
    let x = Some("air");
    assert_eq!(x.unwrap(), "air");
    assert_eq!(x.is_some(), true);
}
```
(You can run the program online at http://goo.gl/F9OnFk).

In addition, the current documentation says:

> Returns the inner T of a Some(T).

Does this means the value contained in the `Some(T)` is moved out or cloned or is a borrow taken? Also, `T` is a type and I don't think that the function really returns a type, but a value of type `T`. Therefore, should the quoted sentence maybe reworded towards something along the lines of:

> Returns the value of type T as it is contained in the Some(T).

Please let me know what you think about these points. I am more than happy to provide a PR to improve the documentation, but I don't know all the answers to the questions I have raised above and I am also not sure if my claims are correct :/

### PR DESCRIPTION
**Pull request by jviereck**
Fixes #23713.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
thanks!

**Comment by apasel422** [comment]
This seems overly explicit. Can't this just be

```
Moves the value out of the option if it is `Some`, or panics if it is `None`.
```

**Comment by jviereck** [comment]
> This seems overly explicit. Can't this just be

You have a point here. You're version sounds cleaner/simplier and I like it. Maybe your proposed description can be extended to still include the `v` like:

```
Moves the value `v` out of the option if it is `Some(v)`, or panics if it is `None`.
```
How does this sound like?

What is the correct procedure to change this PR? Can I just push a new commit into this branch to adjust the docs or should I open a new PR?

**Comment by steveklabnik** [comment]
So, normally pushing a new commit would adjust, but since @alexcrichton has started a rollup, I'm not sure.

**Comment by alexcrichton** [comment]
Oh oops, sorry about that! If you want to send me a patch I'll put it in the rollup if it bounces, and otherwise you can just make a new PR after this one goes through :)

**Pull request merged**
