### PR TITLE
Stabilize `const_intrinsic_copy`

### LINKED ISSUE #80697: Tracking Issue for const_intrinsic_copy
Feature gate: `#![feature(const_intrinsic_copy)]`

This is a tracking issue for making the functions `ptr::copy` and `ptr::copy_nonoverlapping` as well as some related functions `const fn`.

### Public API

```rust
mod ptr {
    pub const unsafe fn copy_nonoverlapping<T>(src: *const T, dst: *mut T, count: usize);
    pub const unsafe fn copy<T>(src: *const T, dst: *mut T, count: usize);
}

impl *const T {
    pub const unsafe fn copy_to(self, dest: *mut T, count: usize);
    pub const unsafe fn copy_to_nonoverlapping(self, dest: *mut T, count: usize);
}

impl *mut T {
    pub const unsafe fn copy_to(self, dest: *mut T, count: usize);
    pub const unsafe fn copy_to_nonoverlapping(self, dest: *mut T, count: usize);

    pub const unsafe fn copy_from(self, src: *const T, count: usize);
    pub const unsafe fn copy_from_nonoverlapping(self, src: *const T, count: usize);
}
```

### Steps / History

- [x] Implementation of `ptr::copy` and `ptr::copy_nonoverlapping` as `const fn`: #79684 
  - [x] Link to this issue in feature gate: #80699
- [x] Also constify `copy_to`, `copy_from` and friends : #83091 
- [x] Final commenting period (FCP)
- [x] Stabilization PR: #97276
- [x] De-stabilization PR: https://github.com/rust-lang/rust/pull/117905
- [ ] TODO: new stabilization PR, once https://github.com/rust-lang/rust/issues/57349 is stable

### PR DESCRIPTION
**Pull request by JohnTitor**
FCP has been completed: https://github.com/rust-lang/rust/issues/80697#issuecomment-1059825428
Closes #80697

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by Dylan-DPC** [comment]
failed in [rollup ci](https://github.com/rust-lang/rust/runs/6787510855)
need to remove the feature gate from test(s)

@bors r-

**Comment by RalfJung** [comment]
@rust-lang/libs-api this should not have landed the way it did. Const-stabilizing intrinsics requires approval from @rust-lang/lang (similar to how exposing any intrinsic on stable requires t-lang approval) and @rust-lang/wg-const-eval... and in this case we would likely have said "no", since any way of mutating mutable references in `const` was very deliberately kept unstable.

**Comment by RalfJung** [comment]
Oh, sorry for that. There was prior approval in https://github.com/rust-lang/rust/issues/80697#issuecomment-1059825428, just not in this PR. My bad!

**Pull request merged**
