### PR TITLE
Visit statement and expression attributes in the AST visitor

### PR DESCRIPTION
**Pull request by jseyfried**
Currently, these attributes are not visited, so they are not gated feature checked in the post expansion visitor. This only affects crates using `#![feature(stmt_expr_attributes)]`.
r? @nrc

### CODE REVIEW

**Comment by durka** [comment]
Does this move these attributes early enough to support `#[allow(...)]` on stmts/exprs?

**Comment by jseyfried** [comment]
@durka 
> Does this move these attributes early enough to support `#[allow(...)]` on stmts/exprs?

No -- it looks like `#[allow(...)]` has no effect on stmts/exprs. Is there an issue for this?

**Pull request merged**
