### PR TITLE
std: improve io error descriptions

### PR DESCRIPTION
**Pull request by seanmonstar**
cc @pnkfelix @alexcrichton

### CODE REVIEW

**Comment by sfackler** [comment]
:+1:

**Comment by steveklabnik** [comment]
:+1:

**Comment by killercup** [comment]
:+1: Very nice, I've been googling OS error numbers far too often.

**Comment by alexcrichton** [comment]
@bors: r+ 025f97a1def6c5fc2169931c18ee818ba5479f84

Thanks!

**Pull request merged**
