### PR TITLE
Move global vars changing tests into run-pass

### PR DESCRIPTION
**Pull request by stepancheg**
Should fix race #42795

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors retry

os x timed out

**Comment by Mark-Simulacrum** [comment]
@bors retry

Trying to get bors to recognize world state...

**Comment by kennytm** [comment]
[macOS (64-bit dist) stuck when compiling stage0-rustc](https://travis-ci.org/rust-lang/rust/jobs/246936296), spurious.

```
[01:35:28]    Compiling proc_macro v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/libproc_macro)
[01:35:58]    Compiling rustc_const_math v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/librustc_const_math)
[01:36:05]    Compiling syntax_ext v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/libsyntax_ext)
[01:36:39]    Compiling rustc v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/librustc)

No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by carols10cents** [comment]
@bors retry

umm 1 osx builder timed out (red) 4 were terminated (gray)?

**Comment by kennytm** [comment]
@carols10cents If any job in the build completed abnormally, all other running jobs will be canceled by bors so another PR can start immediately.

**Pull request merged**
