### PR TITLE
Replace for...insert-style loops with extend/collect

### PR DESCRIPTION
**Pull request by nhwn**
This PR does some general cleanup around the compiler by replacing repeated insertions into collections like `HashMap` and `HashSet` with calls to `extend()` or `collect()`.

Hopefully, this will help avoid reallocation in places where we can avoid it, so I'd like to do a perf run to see if we get some improvements (or regressions).

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
Apologies for the delay in getting back to this - perf results are fairly mixed, not sure that this is worth landing, unless there are further changes you'd like to experiment with.

**Comment by crlf0710** [comment]
@nhwn Ping from triage. Any updates on this?

**Comment by nhwn** [comment]
@rustbot label -S-waiting-on-author +S-waiting-on-review

Sorry for not getting back to this sooner!

I've changed the `extend()` calls to `for` loops with an initial call to `reserve()`. Looking at `hashbrown`'s [implementation](https://rust-lang.github.io/hashbrown/src/hashbrown/map.rs.html#3392-3407), it seems `extend()` will only reserve _half_ the size hint if the map is nonempty. Maybe explicitly pre-allocating the full number of items is better in this case?

I've left the `collect()` calls intact for the sake of readability + similar code already exists in those files, but they can also be changed if needed.

**Comment by davidtwco** [comment]
Perf results are still fairly mixed, some incremental speedups and some full slowdowns - still not sure if this is worth landing.

**Comment by nhwn** [comment]
I wholeheartedly agree. I'm out of things to try, so I'm going to go ahead and close this PR. It's somewhat unfortunate that the attempted approaches didn't work out, but it's definitely not the end of the world.

Thanks for reviewing!

**Pull request closed without merging**
