### PR TITLE
Avoid uneccessary clone of Annotatable

### PR DESCRIPTION
**Pull request by eggyal**
Addresses FIXME comment created in #82608

r? @Aaron1011

### CODE REVIEW

**Comment by Aaron1011** [comment]
Very clever!

@bors try @rust-timer queue

**Comment by eggyal** [comment]
Well that's... interesting ?!

Spurious failure?  Bug in MIRI?  UB?  Not sure what's going on here, but seems pretty unlikely for this PR to be at fault!

**Comment by eggyal** [comment]
Hooray!  But still... all rather suspicious.  Is this a known issue?

**Pull request merged**
