### PR TITLE
Clarify/fix formatting docs concerning fmt::Result/fmt::Error

### PR DESCRIPTION
**Pull request by Stebalien**
1. `fmt::Result` != `io::Result<()>`
2. Formatters should only propagate errors, not return their own.

Confusion on reddit: https://www.reddit.com/r/rust/comments/4yorxr/is_implt_tostring_for_t_where_t_display_sized_a/

### CODE REVIEW

**Comment by briansmith** [comment]
This kind of documentation is an indication that the API is designed wrongly. In particular, the user of the thing that implements `Debug` or whatever can pass a `fmt: &mut Formatter` that keeps track of whether it failed, and then query `fmt` after the operation to see if it had any failure. Thus, the `fmt` method should just not have a return type.

In some cases, the implementation of `fmt` has to choose between panicking and returning `Err(fmt::Error)`. In general, I don't want my code to cause panics so I'm included to return `Err(fmt::Error)`. The suggested documentation says this is not how it is intended to do, but it still isn't clear why it would be worse than calling `panic!`.

**Comment by Stebalien** [comment]
@briansmith I agree it's not ideal but it's stable...

> In particular, the user of the thing that implements Debug or whatever can pass a fmt: &mut Formatter that keeps track of whether it failed, and then query fmt after the operation to see if it had any failure. Thus, the fmt method should just not have a return type.

That's how it works currently. The point of the result is to tell caller that an error has occurred and that it should stop formatting. The actual error is stashed elsewhere. For example:

```rust
impl Display for Something {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        Display::fmt(&self.message, f)?; // bail early on error
        Display::fmt(&":", f)?; // bail early on error
        Display::fmt(&self.detail, f)?;
    }
}
```

> In some cases, the implementation of fmt has to choose between panicking and returning Err(fmt::Error). In general, I don't want my code to cause panics so I'm included to return Err(fmt::Error). The suggested documentation says this is not how it is intended to do, but it still isn't clear why it would be worse than calling panic!.

If it's a bug (programmer error or variant violation), it *should* panic; that's the point of panic. However, if your `Display` implementation can fail normally, you shouldn't be implementing `Display`; formatting is not a fallible operation (the documentation should probably explicitly mention this).

Also, in this case, the error will just be dropped on the floor in trait implementations like `ToString`.

**Comment by Stebalien** [comment]
@briansmith is the updated documentation clear now?

**Comment by briansmith** [comment]
Yes, it is clearer. You might clarify it further by saying more of what you said in your comment above: "If any other kind of error could occur, that is a sign that `Display` and/or `Debug` shouldn't be implemented for the given type; regardless the function must not return `fmt::Error` in such cases; it may `panic!` instead.

**Comment by Stebalien** [comment]
@briansmith now that I actually pushed the change I was asking about... any better?

**Comment by briansmith** [comment]
Yes, it's clearer.

**Comment by GuillaumeGomez** [comment]
:+1: 

cc @steveklabnik

**Pull request merged**
