### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #73655 (va_args implementation for AAPCS.)
 - #73783 (Detect when `'static` obligation might come from an `impl`)
 - #73893 (Stabilize control-flow-guard codegen option)
 - #74237 (compiletest: Rewrite extract_*_version functions)
 - #74528 (refactor and reword intra-doc link errors)
 - #74538 (Guard against non-monomorphized type_id intrinsic call)
 - #74541 (Add the aarch64-apple-darwin target )
 - #74570 (Use forge links for prioritization procedure)
 - #74589 (Update books)
 - #74635 (Fix tooltip position if the documentation starts with a code block)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors treeclosed=5

I should be around today

**Comment by estebank** [comment]
It was #73783 not having fixed an nll test (which I didn't expect).

**Comment by Manishearth** [comment]
@Aaron1011 This doesn't work on closed PRs, also please don't reopen the tree when rollups are being made.

**Comment by Aaron1011** [comment]
@Manishearth: Sorry, I didn't realize you were still doing rollups.

**Comment by Manishearth** [comment]
Yeah, I close the tree so that we don't waste time on testing PRs that will get canceled halfway through. This will mean some downtime for homu since I don't immediately notice failures (ping me!) but unless the tree is closed without activity for more than an hour I'd leave it closed

**Pull request closed without merging**
