### PR TITLE
Remove `crate` visibility modifier

### PR DESCRIPTION
**Pull request by jhpratt**
FCP to remove this syntax is just about complete in #53120. Once it completes, this should be merged ASAP to avoid merge conflicts.

The first two commits remove usage of the feature in this repository, while the last removes the feature itself.

### CODE REVIEW

**Comment by jhpratt** [comment]
As to how this was done: nearly every change was done via regex replacement in my editor. The only code deliberately left using this syntax is in the feature gate test.

I updated the tests and blessed the output, so they should all be up to date. The only non-trivial change was deleting a test that was self-proclaimed to be a duplicate of another. While I did manually review each part of the diff when committing, I did not do so in depth. It was merely a "yes, this diff is semantically correct" check. I presume whoever reviews this will take a similar approach.

**Comment by jackh726** [comment]
If you make a separate PR just removing the uses without removing the features, I'll approve that immediately. Otherwise, just wait until FCP finishes.

**Comment by jhpratt** [comment]
Thanks @jackh726. I just pushed the diff that only removes the uses. If tests fail, I'll keep trying until it passes. I'm building them locally now to try to find any issues quicker.

**Comment by jhpratt** [comment]
CI is green.

**Pull request merged**
