### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #101339 (enable -Zrandomize-layout in debug CI builds )
 - #120736 (rustdoc: add header map to the table of contents)
 - #127021 (Add target support for RTEMS Arm)
 - #128928 (CI: rfl: add more tools and steps)
 - #129584 (warn the user if the upstream master branch is old)
 - #129664 (Arbitrary self types v2: pointers feature gate.)
 - #129752 (Make supertrait and implied predicates queries defaulted)
 - #129918 (Update docs of `missing_abi` lint)
 - #129919 (Stabilize `waker_getters`)
 - #129925 (remove deprecated option `rust.split-debuginfo`)

Failed merges:

 - #129789 (rustdoc: use strategic boxing to shrink `clean::Item`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=101339,120736,127021,128928,129584,129664,129752,129918,129919,129925)

### CODE REVIEW

**Comment by lqd** [comment]
libstdc++ 7 v 8 again causing bootstrap to fail benchmarking

**Comment by rylev** [comment]
The regressions here are small enough that I don't think it's worth investigating further.

@rustbot label: +perf-regression-triaged

**Pull request merged**
