### PR TITLE
Fix 44056 test with debug on macos.

### PR DESCRIPTION
**Pull request by ehuss**
The test `codegen/issue-44056-macos-tls-align.rs` fails on macos if `debug-assertions` is enabled in `config.toml`.  It has the following error:

```
/Users/eric/Proj/rust/rust/src/test/codegen/issue-44056-macos-tls-align.rs:9:11: error: CHECK: expected string not found in input
// CHECK: @STATIC_VAR_1 = thread_local local_unnamed_addr global <{ [32 x i8] }> zeroinitializer, section "__DATA,__thread_bss", align 4
          ^
/Users/eric/Proj/rust/rust/build/x86_64-apple-darwin/test/codegen/issue-44056-macos-tls-align/issue-44056-macos-tls-align.ll:1:1: note: scanning from here
; ModuleID = 'issue_44056_macos_tls_align.3a1fbbbh-cgu.0'
^
/Users/eric/Proj/rust/rust/build/x86_64-apple-darwin/test/codegen/issue-44056-macos-tls-align/issue-44056-macos-tls-align.ll:9:1: note: possible intended match here
@STATIC_VAR_1 = thread_local global <{ [32 x i8] }> zeroinitializer, section "__DATA,__thread_bss", align 4
^
```

Comparing the output, the actual output is missing the text "`local_unnamed_addr`".

The fix here is to ignore `local_unnamed_addr`, as it doesn't seem relevant to the test.

### CODE REVIEW

**Comment by tmiasko** [comment]
The `local_unnamed_addr` looks irrelevant to the purpose of the test. Relaxing the check and keeping test enabled would be probably better solution.

**Comment by ehuss** [comment]
I pushed an update that ignores the differences.

I don't understand, why would rustc generate such different code when it is built with debug-assertions?  The normal build emits 46 lines of LLVM IR, whereas with debug-assertions enabled, it is 160 lines.  I would not expect building the compiler with debug-assertions to change the *output* of the compiler.

**Comment by tmiasko** [comment]
The debug assertions in `intrinsics::copy_nonoverlapping` look responsible, so not the compiler per se, but rather the standard library.

**Comment by ehuss** [comment]
Oh, that makes sense!  I just built with `debug-assertions=true` and `debug-assertions-std=false`, and got the same output as `debug-assertions=false`.  Thanks!

**Pull request merged**
