### PR TITLE
[DO NOT MERGE] Enable `exhaustive_patterns` by default

### PR DESCRIPTION
**Pull request by camelid**
cc #51085

This doesn't stabilize the feature, it just makes it a no-op. This is to
get a perf run as suggested [here].

cc @varkor

[here]: https://github.com/rust-lang/rust/issues/51085#issuecomment-730549823

### CODE REVIEW

**Comment by camelid** [comment]
It seems like this feature doesn't work right with `PhantomData`? See the error in CI:

```
error: unreachable pattern
   --> compiler/rustc_traits/src/chalk/lowering.rs:490:13
    |
490 |             chalk_ir::LifetimeData::Phantom(_, _) => unimplemented!(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D unreachable-patterns` implied by `-D warnings`

error: aborting due to previous error
```

**Comment by varkor** [comment]
`LifetimeData::Phantom` is defined here: https://github.com/rust-lang/chalk/blob/389a261fa374701441aa64dbdf801d8ff2fcac8f/chalk-ir/src/lib.rs#L1198, and contains a `Void` parameter. Therefore it is unreachable.

**Comment by camelid** [comment]
I see, it literally can't be constructed. I forgot about that :)

I removed the match arm and [asked in #wg-traits](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/why.20does.20.60chalk_ir.3A.3ALifetimeData.3A.3APhantom.60.20exist) what the purpose of that variant is.

**Comment by camelid** [comment]
Bootstrapping compilers are so weird 😄

**Comment by lcnr** [comment]
try doesn't care about tests

@bors try @rust-timer queue

**Comment by varkor** [comment]
It seems `exhaustive_patterns` still has very poor performance implications. cc @Nadrieril

**Comment by Nadrieril** [comment]
Ouch ok. The feature only removes possible branches, so it shouldn't affect performance of the algorithm itself. Thus the blame seems to lie in the inhabitedness check, as noticed [here](https://github.com/rust-lang/rust/issues/51085#issuecomment-433476162).
Given that we have to call it at least for every struct&enum (sub)pattern, and that it itself recursively analyses the type, we get more or less O(number_of_matches * number_of_branches * depth_of_pattern * depth_of_type). Caching would turn that into O(depth_of_type) for every type we ever match on.
So my diagnostic is: I expect that caching the inhabitedness check would massively improve perf. Could that be a query? I know nothing about the query architecture but I'd be happy to try.

**Comment by camelid** [comment]
> I know nothing about the query architecture but I'd be happy to try.

Same here, and I would be interested in following along so I understand it better (or at all) :)

**Comment by varkor** [comment]
I have to admit that whenever I've worked with queries in the past, I've just followed my nose based on how existing queries have been implemented :) It sounds worth a try to me, though!

**Comment by Nadrieril** [comment]
@camelid could you rebase on top of https://github.com/rust-lang/rust/pull/79670 and try a perf run again?

**Comment by camelid** [comment]
Rebased on top of #79670 to get a fresh perf run.

**Comment by Nadrieril** [comment]
Now that I think about it, references being inhabited is very annoying, because none of the options work:
```rust
match x { // x: &LifetimeData
	...
	&Phantom(..) => unreachable!(), // warns as unreachable
}
match x { // x: &LifetimeData
	...
	Phantom(..) => unreachable!(), // warns as unreachable
}
match x { // x: &LifetimeData
	...
	// errors as non-exhaustive
}
match x { // x: &LifetimeData
	...
	&_ => unreachable!(), // warns as unreachable
}
match x { // x: &LifetimeData
	...
	_ => unreachable!(), // only option that works
}
```
The only thing that works is adding a `_` branch, but that's a footgun if we later add variants.

**Comment by camelid** [comment]
@Nadrieril Perhaps #79670 broke the existing behavior somehow? This error didn't come up before...

**Comment by camelid** [comment]
It seems like that the compiler incorrectly thinks `Void` is inhabited?

**Comment by Nadrieril** [comment]
@camelid There are more places in `usefulness.rs` and `deconstruct_pat.rs` where you need to enable the feature

**Comment by camelid** [comment]
Ah, glad to know that it's an easy fix :)

It's weird; I thought I grepped through all the places before, but I guess not recently enough 🤷

**Comment by camelid** [comment]
Okay, the rest of the places should be updated. Still not sure how I missed those other spots, but oh well.

**Comment by Nadrieril** [comment]
@camelid I moved some files around since the first time you made this PR, in particular I split `_match.rs` into two so it's probably that

**Comment by camelid** [comment]
Looks like with @Nadrieril's great work on performance, we may now be able to finally stabilize this feature! 🎉 

Though I think there might have been some other concerns not related to performance? Though I think they also can be resolved in a backwards-compatible way?

**Comment by Nadrieril** [comment]
Well I'm waiting on an answer to the never patterns issue that [I summarized](https://github.com/rust-lang/rust/issues/51085#issuecomment-736905101). This feature is probably introducing unsoundness, which is very not good.

**Comment by Nadrieril** [comment]
My current plan is to wait for a reply to https://github.com/rust-lang/rust/issues/78123 and comment in https://github.com/rust-lang/rust/issues/51085 explaining that the feature probably introduces unsoundness, depending on future plans of what is and isn't UB. I expect we will have to turn never patterns into a proper RFC before we can stabilize `exhaustive_patterns`.
In parallel, https://github.com/rust-lang/rust/pull/79670 should get merged and then we can do a final perf test here to separate the perf impact of `exhaustive_patterns` from the one of my PR.

**Comment by Nadrieril** [comment]
#79670 got merged! Let's measure again.

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Oh, I forgot this PR included #79670 ><

**Comment by Nadrieril** [comment]
I resolved the conflicts myself using the GitHub interface; it's nice!
@bors try @rust-timer queue

**Comment by camelid** [comment]
Overall, perf looks neutral! Perhaps very slight regressions, but I think within the margin of error. Thanks to @Nadrieril for putting in the work to speed it up!

**Comment by jackh726** [comment]
@camelid What's the plan for this going forward? Is there more to do or does this just need a review/decision? (I see that CI failed last run, but logs are exired)

**Comment by camelid** [comment]
> @camelid What's the plan for this going forward? Is there more to do or does this just need a review/decision? (I see that CI failed last run, but logs are expired)

This was just an experiment to see what the perf situation was; I didn't close it because I wasn't sure if people wanted to do more tests with it. I believe what's left is making a decision; @Nadrieril may know more.

**Comment by Nadrieril** [comment]
Performance used to be a blocker for the `exhaustive_patterns` feature. This PR was only there to check perf, and now it's fine so we can close it. Discussion will continue on the tracking issue https://github.com/rust-lang/rust/issues/51085

**Pull request closed without merging**
