### PR TITLE
Capture output from threads spawned in tests

### LINKED ISSUE #42474: `cargo test` doesn't capture print from threads
I've filed this bug in [rust-lang/cargo](https://github.com/rust-lang/cargo/issues/4129) but I'm afraid rust-lang/rust is the correct repo for this.

I ran the tests for one of my crates that uses threads in its example code. I've noticed it printed some lines to stdout, even though `--nocapture` wasn't set, but not all of them. It appears that text printed from new threads are not correctly captured, I think this is not intended.

## Reproduce
```
#[cfg(test)]
mod tests {
    use std::thread;
    use std::time::Duration;

    #[test]
    fn it_works() {
        thread::spawn(move || {
            println!("request: {:?}", 123);
        });

        thread::sleep(Duration::from_secs(1));
        println!("response: {:?}", 456);
    }
```

## Output
```
running 2 tests
request: 123
test tests::it_works ... ok
[...]
```

## Meta

`rustc --version --verbose`:

```
rustc 1.17.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.17.0
LLVM version: 4.0
```

### PR DESCRIPTION
**Pull request by tmandry**
Fixes #42474.

r? @dtolnay since you expressed interest in this, but feel free to redirect if you aren't the right person anymore.

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Looks good!

**Comment by dtolnay** [comment]
Er, CI failed though:

```console
--- [ui] ui/panic-while-printing.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit code: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/panic-while-printing.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/panic-while-printing/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/panic-while-printing/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0277]: the trait bound `std::vec::Vec<_>: std::io::LocalOutput` is not satisfied
  --> /checkout/src/test/ui/panic-while-printing.rs:19:20
   |
LL |     set_panic(Some(Box::new(Vec::new())));
   |                    ^^^^^^^^^^^^^^^^^^^^ the trait `std::io::LocalOutput` is not implemented for `std::vec::Vec<_>`
   |
   = note: required for the cast to the object type `dyn std::io::LocalOutput`



--- [ui] ui/threads-sendsync/task-stderr.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit code: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/threads-sendsync/task-stderr.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/threads-sendsync/task-stderr/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/threads-sendsync/task-stderr/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0277]: the trait bound `Sink: std::io::LocalOutput` is not satisfied
  --> /checkout/src/test/ui/threads-sendsync/task-stderr.rs:24:28
   |
LL |         io::set_panic(Some(Box::new(sink)));
   |                            ^^^^^^^^^^^^^^ the trait `std::io::LocalOutput` is not implemented for `Sink`
   |
   = note: required for the cast to the object type `dyn std::io::LocalOutput`
```

**Comment by tmandry** [comment]
Tests fixed!

**Comment by dtolnay** [comment]
```console
error[E0277]: the trait bound `dyn realstd::io::LocalOutput: io::Write` is not satisfied
   --> library/std/src/panicking.rs:216:15
    |
216 |         write(&mut local);
    |               ^^^^^^^^^^ the trait `io::Write` is not implemented for `dyn realstd::io::LocalOutput`
    |
    = note: required because of the requirements on the impl of `io::Write` for `realstd::boxed::Box<dyn realstd::io::LocalOutput>`
    = note: required for the cast to the object type `dyn io::Write`
```

**Comment by tmandry** [comment]
Yep, working on this now. Sorry for the noise.

**Comment by tmandry** [comment]
CI passed.

**Review by dtolnay — APPROVED** [review]

**Comment by tmandry** [comment]
@bors rollup=iffy

I'm trying to track down the cause of https://github.com/rust-lang/rust/pull/75684#issuecomment-675787980 and while I don't think this can cause it (nor can I reproduce locally), nothing else in that change seems related.

**Comment by tmandry** [comment]
@bors retry
Yielding to rollup

**Comment by tmandry** [comment]
Same failure. Seems to only happen on the `dist-i586-gnu-i586-i686-musl` bot, I'll investigate more tomorrow.

**Comment by crlf0710** [comment]
Triage: There's merge conflicts now.

**Comment by m-ou-se** [comment]
This PR partially breaks the effect of [`std::io::stdio::LOCAL_STREAMS`](https://github.com/rust-lang/rust/blob/981346fc07dd5ef414c5b1b21999f7604cece006/library/std/src/io/stdio.rs#L45):

https://github.com/rust-lang/rust/blob/981346fc07dd5ef414c5b1b21999f7604cece006/library/std/src/io/stdio.rs#L33-L37

`clone_io` should first check `LOCAL_STREAMS.load(Relaxed)`, and return `(None, None)` if it was `false`. Otherwise, spawning a thread in non-test program will needlessly register thread local destructors for LOCAL_STDOUT and LOCAL_STDERR.

**Comment by dtolnay** [comment]
Closing in favor of #78227 which includes a rebase of this commit.

**Pull request closed without merging**
