### PR TITLE
Filter away test annotations from UI test output

### PR DESCRIPTION
**Pull request by petrochenkov**
If you worked with UI tests for some time you could notice one issue affecting their readability and also readability of diffs when the tests change.
Look at the output of this test.
```rust
fn main() {
    let 1 = 2; //~ ERROR refutable pattern in local binding
}
```
```
error[E0005]: refutable pattern in local binding: `-2147483648i32..=0i32` not covered
 --> src/main.rs:2:9
  |
2 |     let 1 = 2; //~ ERROR refutable pattern in local binding
  |         ^ pattern `-2147483648i32..=0i32` not covered

error: aborting due to previous error

For more information about this error, try `rustc --explain E0005`.
```
You can see that the "refutable pattern in local binding" is duplicated.
One instance is the actual error, and the second instance is the expected error annotation.
This annotation is useful in the test input, but in the output it clutters the text and makes it harder to see what text refers to actual errors and what is just comments, especially if there are many errors in a single test file.

@estebank [reported](https://github.com/rust-lang/rust/pull/57379#discussion_r245523361) using the next trick to avoid the clutter
```rust
fn main() {
    let 1 = 2;
    //~^ ERROR refutable pattern in local binding
}
```
```
error[E0005]: refutable pattern in local binding: `-2147483648i32..=0i32` not covered
 --> src/main.rs:2:9
  |
2 |     let 1 = 2;
  |         ^ pattern `-2147483648i32..=0i32` not covered

error: aborting due to previous error

For more information about this error, try `rustc --explain E0005`.
```
, i.e. using `//~^` and placing the annotation one line below will remove the annotation from the output.

However, this doesn't always works (consider errors with multi-line spans), and shouldn't be necessary in general!
`compiletest` could automatically filter away its own annotations from the output instead.
This is exactly what this PR does.

r? @davidtwco

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @rust-lang/compiler

**Comment by davidtwco** [comment]
I'm happy to r+ this PR, assuming nobody has any issues with it, but I suspect it'll be pretty difficult to land w/out a tree-close given how large it is.

**Comment by oli-obk** [comment]
> assuming nobody has any issues with it

I say we do it.

> I suspect it'll be pretty difficult to land w/out a tree-close given how large it is.

It should be doable by a quick rebase + bless run while a PR is being processed which doesn't touch stderr files. But a treeclose will make things easier if @petrochenkov has a few contiguous hours to get this working (like if there are random bors failures).

**Comment by petrochenkov** [comment]
Ok, I'll rebase it this evening and try to r+ with high priority.

**Pull request merged**
