### PR TITLE
don't splice from files into pipes in io::copy

### PR DESCRIPTION
**Pull request by the8472**
This fixes potential data ordering issue where a write performed after a copy operation could become visible in the copy even though it signaled completion.

I assumed that by not setting `SPLICE_F_MOVE` we would be safe and the kernel would do a copy in kernel space and we could avoid the read-write syscall and copy-to/from-userspace costs. But apparently that flag only makes a difference when splicing from a pipe, but not when splicing into it.

Context: https://lkml.org/lkml/2023/2/9/673

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Reading through that thread it makes sense but.. that seems unfortunate? This could be a soundness issue, right?

Does this need a test?

**Comment by the8472** [comment]
I don't think rust code can see bytes in memory change under its nose, so there's no soundness issue with non-deterministic bytes.
But it could be an ordering issue leading to logic bugs where one copies data and then modifies the source and the modified version becomes visible on the other side instead of the expected original.

Thinking about it, this shouldn't affect sockets because their buffers can't be modified, so splicing from a socket to a pipe could still be ok. The linked mail also describes this as case 1.

And yeah, I'll add a test, it's subtle enough.

@rustbot author

**Comment by the8472** [comment]
@rustbot ready

added a test and checked that it fails without the fix.

**Comment by ChrisDenton** [comment]
Thank you for investigating this.

@bors r+

**Comment by ChrisDenton** [comment]
Hm, `STATUS_ILLEGAL_INSTRUCTION` on i686-pc-windows-msvc looks a bit worrying but it should not have anything to do with this PR. 

@bors retry

**Comment by NobodyXu** [comment]
For optimization reverted here, I think we could add it back with an intermediate pipe?

I.e. first `splice` to an intermediate pipe with `F_MOVE`, then `splice` to the destination pipe without `F_MOVE`?

The intermediate pipe can be cached and reused, given that we can make sure there's no panicking within `io::copy`

**Comment by the8472** [comment]
If that works at all it'd still negate some of the advantages of splice. More syscalls, more copying. It still might provide some more throughput because pipes would be a larger buffer than our 8k on-stack buffer. Maybe worth a try.

In theory using sendfile/splice from read-only files might be ok, but then the question is in which state the file or file descriptor must be so that we could consider it sufficiently read-only.
Another theoretical option would be to wait for the socket send buffer to drain. Which would be fine for sending huge files, but not when using io::copy to send some chunk of a smaller file.

**Comment by NobodyXu** [comment]
> Maybe worth a try.

Thanks, I'd try opening a PR for this.

> but then the question is in which state the file or file descriptor must be so that we could consider it sufficiently read-only.

Unless it's `/dev/zero` or on an immutable system, I suppose the file can be changed at anytime.

I thought about if CoW filesystem is immune to this, but then I think that's impossible because the mmap abstraction provides by the kernel guarantees it will see updates.

That reminds me, that on CoW fs, `copy_file_range` can be very cheap as it requires no copy only reflink, we could also create a `O_TMPFILE` and use it to achieve zero-copy.

> Another theoretical option would be to wait for the socket send buffer to drain.

I think the best fix would be for the Linux kernel to fix this, if they would provide a flag to opt-in to CoW behavior.

It'd also be great if `mmap` has such flags, currently it says with `MMAP_PRIVATE` read-only `mmap`, it is unspecified if changes to the original file would affect the mmap.

**Comment by NobodyXu** [comment]
@the8472 I think [sealed files](https://man7.org/linux/man-pages/man2/fcntl.2.html) can be used here, if the file has flag `F_SEAL_WRITE` (prevent modifying of existing contents, shrinking and appending is allowed) and `F_SEAL_SEAL` (not changing of seals).

**Comment by NobodyXu** [comment]
So to sum up, I think we can add back optimization via:
 - if the file is on squashfs/erofs

**Comment by NobodyXu** [comment]
@the8472 opened #128300

**Comment by the8472** [comment]
> then just a splice without F_MOVE would work fine.

We never used F_MOVE and it was still a problem. So I'm skeptical it'll work at all but maybe it depends on the direction (from/to pipe).

> then it's immutable (detectable via [statfs](https://man7.org/linux/man-pages/man2/statfs.2.html)
> detectable via fcntl(fd, F_GET_SEALS)

Those cost extra syscalls, which could be unnecessary overhead for small files. So it probably only makes sense to even try these things for large files.

And many of those cases seem rare that it's not worth it. Like who serves e.g. a webserver from a btrfs snapshot?

**Pull request merged**
