### PR TITLE
Fix mutable references in `static mut`

### LINKED ISSUE #56903: cannot mutate statics in initalizer of another static
https://crater-reports.s3.amazonaws.com/beta-1.32-1/beta-2018-12-05/gh/oxidizers.drdns/log.txt

```
Dec 08 20:04:10.309 INFO [stderr] error: cannot mutate statics in the initializer of another static
Dec 08 20:04:10.309 INFO [stderr]    --> src/buffer.rs:279:17
Dec 08 20:04:10.309 INFO [stderr]     |
Dec 08 20:04:10.309 INFO [stderr] 279 |     x: unsafe { &mut STDOUT_BUFFER_SPACE as *mut [u8] as *mut u8 },
Dec 08 20:04:10.309 INFO [stderr]     |                 ^^^^^^^^^^^^^^^^^^^^^^^^
Dec 08 20:04:10.309 INFO [stderr] 
Dec 08 20:04:10.309 INFO [stderr] error: cannot mutate statics in the initializer of another static
Dec 08 20:04:10.310 INFO [stderr]    --> src/buffer.rs:293:17
Dec 08 20:04:10.310 INFO [stderr]     |
Dec 08 20:04:10.310 INFO [stderr] 293 |     x: unsafe { &mut STDERR_BUFFER_SPACE as *mut [u8] as *mut u8 },
Dec 08 20:04:10.310 INFO [stderr]     |                 ^^^^^^^^^^^^^^^^^^^^^^^^
Dec 08 20:04:10.310 INFO [stderr] 
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #56903

### CODE REVIEW

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. beta-accepting.

**Comment by pietroalbini** [comment]
@bors r-
Failing in the rollup.

```
[01:04:26] ---- [ui] ui/consts/static_mut_containing_mut_ref2.rs stdout ----
[01:04:26] diff of stderr:
[01:04:26] 
[01:04:26] 4 LL | pub static mut STDERR_BUFFER: () = unsafe { *(&mut STDERR_BUFFER_SPACE) = 42; };
[01:04:26] 5    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^ statics require immutable values
[01:04:26] - error: aborting due to previous error
[01:04:26] - error: aborting due to previous error
[01:04:26] + error[E0019]: static contains unimplemented expression type
[01:04:26] +   --> $DIR/static_mut_containing_mut_ref2.rs:5:45
[01:04:26] +    |
[01:04:26] + LL | pub static mut STDERR_BUFFER: () = unsafe { *(&mut STDERR_BUFFER_SPACE) = 42; };
[01:04:26] 8 
[01:04:26] - For more information about this error, try `rustc --explain E0017`.
[01:04:26] + error: aborting due to 2 previous errors
[01:04:26] + 
[01:04:26] + 
[01:04:26] + Some errors occurred: E0017, E0019.
[01:04:26] + For more information about an error, try `rustc --explain E0017`.
```

**Pull request merged**
