### PR TITLE
Unimplement Send/Sync for ::env::{Args,ArgsOs,Vars,VarsOs}

### LINKED ISSUE #48004: Send and Sync impls of `::env` types depend on implementation
`::env::{Args,ArgsOs,Vars,VarsOs}` depend entirely on the platform impls in `::sys` for their negative Send/Sync impls.
Implementations of those types currently opt out of Send and Sync, so the user facing types should probably explicitly opt out of Send/Sync to avoid accidental inconsistencies between platforms.

### PR DESCRIPTION
**Pull request by panicbit**
Fixes #48004

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Are we certain that all current platforms explicitly opt-out / don't implement Send/Sync? If so, then this seems fine to me. Please change the annotations to stable, though, as there's no way to gate trait impls today.

**Comment by panicbit** [comment]
Ok, I marked the impls as stable.

Here's an overview over the Send/Sync impls:

### Types not implementing Send/Sync:
- [unix Args/ArgsOs](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/unix/args.rs#L35)
- [unix Vars](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/unix/os.rs#L387)
- [windows Args/ArgsOs](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/windows/args.rs#L40)
- [redox Args/ArgsOs](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/redox/args.rs#L35)
- [redox Vars](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/redox/os.rs#L137)

### Types implementing Send/Sync:
- [windows Vars](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/windows/os.rs#L89)
- [cloadabi Args/ArgsOs (shim)](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/cloudabi/shims/args.rs#L13)
- [cloudabi Vars (shim)](https://github.com/rust-lang/rust/blob/0c6091fbd0eee290c651f73be899f221eeab3c05/src/libstd/sys/cloudabi/shims/os.rs#L27)

**Comment by Mark-Simulacrum** [comment]
So this is a breaking change for `windows::Vars` and cloudabi in general... seems like we're going to potentially end up breaking some users here. This should be detectable with a crater run though, so let's get the artifacts for that: @bors try. Meanwhile, @rust-lang/libs, what do you think about this change?

**Comment by sfackler** [comment]
Can we not make these types Send and Sync on all platforms?

**Comment by alexcrichton** [comment]
@panicbit are you sure that there's any platform where these types are `Send` or `Sync`? You mentioned in "Types implementing Send/Sync:" that Windows is there but it actually contains a raw pointer which means it's not. Perhaps a test could be added asserting that these types aren't send/sync?

**Comment by panicbit** [comment]
@alexcrichton Right, Windows' Vars impl actually contains pointers.

I'm not sure wether it's fine to have them impl Send + Sync.

**Comment by alexcrichton** [comment]
Yes It's currently intentionally conservative that they aren't send/sync I believe, but I don't believe this is a breaking change as mentioned here?

**Comment by kennytm** [comment]
@bors try

Please don't include any punctuations when commanding bors, they don't like that 😉.

**Comment by alexcrichton** [comment]
@panicbit just to confirm, you still think this is a breaking change, right? (I'm still not so sure myself)

**Comment by panicbit** [comment]
@alexcrichton I never expressed the thought of this being a breaking change. I don't think it's really breaking as the current state of things is already broken / unspecified. Though, I'm unsure wether it's best to force `Send` or `!Send`.

**Comment by alexcrichton** [comment]
Ah ok sorry I think I misunderstood. Perhaps a test could be added to assert these aren't sync/send and then we're good to go? I can confirm the windows types are not send/sync, and we can add in in later if we want.

**Comment by BatmanAoD** [comment]
@alexcrichton @panicbit Looks like this is waiting on further investigation for Windows, and *not* waiting on crater?

**Comment by alexcrichton** [comment]
@BatmanAoD oh nah I was originally thinking we'd want a test for this, but on second thought I think this is good to go

@bors: r+

**Pull request merged**
