### PR TITLE
 rustc_mir: implement an "lvalue reuse" optimization (aka destination propagation aka NRVO).

### PR DESCRIPTION
**Pull request by eddyb**
Replaces a chain of moves, such as `a = ...; ... b = move a; ... f(&mut b) ... c = move b`, with the final destination, i.e. only `c = ...; ... f(&mut c); ...` remains (note that borrowing works).

### CODE REVIEW

**Comment by eddyb** [comment]
r? @nikomatsakis 
cc @Mark-Simulacrum Let's throw some benchmarks at this!

**Comment by est31** [comment]
Is this the same that placement new is doing? Will the only reason to use it then be that you like the syntax?

**Comment by eddyb** [comment]
@est31 No, this doesn't change execution order, placement has to allocate *before* evaluating the value directly into the allocation, while `Box::new(expr)` allocates (in the callee) *after* evaluating `expr` .

OTOH, this optimizations only reuses *stack local* destinations when doing so can preserve behavior.

**Comment by Mark-Simulacrum** [comment]
Try build added to queue. Will be complete soon (probably a couple hours).

**Comment by eddyb** [comment]
Assuming [the perf results](http://perf.rust-lang.org/compare.html?start=b087a991fca51c365ce46ad470d85b99f7c9005a&end=cf73ed6046a07efdf456ed78ecad96200b8617fc&stat=instructions%3Au) are accurate, this regresses compile times. Do we have any runtime benchmarks yet? It'd be a shame if we'd have to disable this, especially the first iteration.

**Comment by Mark-Simulacrum** [comment]
Hold up, those perf results are invalid. If you rerun try with `DEPLOY_ALT` removed from https://github.com/rust-lang/rust/blob/827cb0d61e22eb6d5c9c5e8e8d05b07108a9968b/.travis.yml#L25 then we should be able to rebenchmark and then be successful. The current perf results (I believe) are comparing a build without LLVM asserts with a LLVM-asserts enabled build.

**Comment by eddyb** [comment]
@Mark-Simulacrum I'm not sure my hack worked, I'm probably missing the changes to actually upload the results from #46354.

**Comment by Mark-Simulacrum** [comment]
I think you need to change this condition to `$DEPLOY` https://github.com/rust-lang/rust/blob/9de9a00d5e5a9df0ea47e463dabb95aee06a2dc5/.travis.yml#L325

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/46354 actually just merged so I think you should be able to just rebase.

**Comment by Mark-Simulacrum** [comment]
Perf started.

**Comment by eddyb** [comment]
[Perf results](http://perf.rust-lang.org/compare.html?start=0a2e9ade83ff253bb489c63a95b1f499c5e0916f&end=9afa5ec24b58d6d3f271a9d655e1b98c6b550ea7&stat=instructions%3Au) are better, although most wins are minor and there's a regression on `inflate-opt`.
(The `inflate` crate has the entirety of the static huffman table logic in one function, with a lot of macro-generated code, and presumably, very many variables, so any MIR optimization will be slow)

**Comment by stjepang** [comment]
As a random lurker, I wonder how this PR and [this LLVM patch](https://reviews.llvm.org/D38374) relate. AFAICT, they do very similar things but with different code representations (MIR and LLVM IR).

**Comment by pcwalton** [comment]
@stjepang For one, the patch in this PR can handle borrows across functions, while that LLVM patch cannot.

**Comment by eddyb** [comment]
@stjepang I think @pcwalton abandoned that patch in favor of MIR optimizations, which had a lower priority and very little happened since. @pcwalton's own (forward, unlike this PR) "copy propagation" MIR pass is disabled by default because it was too slow to run (missing some caching).

Also, this PR does more than optimize across basic blocks, allowing borrows without needing to track them. OTOH, LLVM could likely handle field accesses, while this PR doesn't, by itself.

Not sure how we could encode the semantics of `Move` (invalidating borrows) for LLVM to use.

**Comment by arielb1** [comment]
I talked with @eddyb on IRC and this appears this optimization is unjustified, especially with NLL..

**Comment by eddyb** [comment]
On IRC @arielb1 pointed out that with NLL this might become valid:
```rust
let (a, b, x);
x = None;
loop {
    a = init;
    use(x, &mut a);
    endregion('α);
    b = move a;
    x = Some(&'α b);
}
endregion('α);
```
This PR, in its current state, would incorrectly reuse `b`'s memory for `a`.
He also suggested using the existing moveck dataflow analyses which should allow tracking all candidates we might possibly be interested in and the interactions between them, and borrows.

**Review by nikomatsakis — COMMENTED** [review]
OK um so I never really finished this review. I was hoping to write up a kind of description of what the code is doing. At this point I'm not sure of current status so I'll just post these incomplete and not that interesting comments for now.

@eddyb -- what is your latest thinking for how to proceed here?

**Comment by carols10cents** [comment]
> @eddyb -- what is your latest thinking for how to proceed here?

ping @eddyb !

**Comment by eddyb** [comment]
@carols10cents I have discussed a new set of analyses with @nikomatsakis which *should* make the optimization sound, and I hope to wrap up bug hunting and get back to this PR soon.

**Comment by scottmcm** [comment]
Looks like this will fix https://github.com/rust-lang/rust/issues/32966

**Comment by eddyb** [comment]
I'll close this PR as a reimplementation is required anyway, for soundness wrt loops.

**Comment by eddyb** [comment]
Note to self, I've tried this:
```rust
#![feature(nll)]

struct Foo(u8);

fn without_nll() {
    let (mut a, mut b);
    let r;
    let mut first = true;
    loop {
        a = Foo(0);
        if first {
            first = false;
            b = a;
        } else {
            r = &a;
            break;
        }
    }
    // `a`, `b`, and `*r` are the same location.
    // However, I don't see a way to abuse it.
}

fn with_nll() {
    let (mut a, mut b);
    let mut r = None;
    loop {
        a = Foo(0);
        // `*r` and `a` are the same location.
        drop((r, &mut a));
        b = a;
        r = Some(&b);
    }
}

fn main() {
    without_nll();
    with_nll();
}
```

`with_nll` doesn't compile yet, the region still covers too much, and it does conflict with `b = a;`.

`without_nll` is optimized, but I was hoping for an easier way to show how going multiple times around a loop, yet taking different branches inside it, could result in unsound optimizations.

As it stands, all I can do is keep this example for future mir-opt tests, and make sure it's not optimized, *preferably* without loop-specific special cases, just a generalized dataflow algorithm.

**Comment by jrmuizel** [comment]
Any chance we can see something like this resurrected?

**Comment by eddyb** [comment]
@jrmuizel This PR is naive and was superseded by https://github.com/rust-lang/rust/pull/47954.

**Pull request closed without merging**
