### PR TITLE
Mark safe_suggestion and pushpop_unsafe as removed in feature_gate.rs

### PR DESCRIPTION
**Pull request by est31**
This removes two features from feature_gate.rs: `safe_suggestion` and `pushpop_unsafe`. Both had been removed in other places already, but were forgotten to be removed from feature_gate.rs.

* `safe_suggestion` was added in commit 164f0105bb65f31b89e5fb7f368c9e6f5833a3f8 and then removed again in commit c11fe553df269d6f47b4c48f5c47c08efdd373dc both in the same PR #38099. 

* `pushpop_unsafe` was added in commit 1829fa5199bae5a192c771807c532badce14be37 and removed again in commit d399098fd82e0bf3ed61bbbbcdbb0b6adfa4c808

Removes two elements from the whitelist of non gate tested unstable lang features (issue #39059).

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
In this case, I take the liberty to r+ it since one of the two unused features is mine and I forgot to remove it. Feel free to r- if there is a mistake I didn't saw!

Thanks @est31!

@bors: r+

**Comment by durka** [comment]
@est31 as per [the comment](https://github.com/rust-lang/rust/blob/ebe9682a25a4aa35b1c95ff73fb297209a8becd7/src/libsyntax/feature_gate.rs#L95) in `feature_gate.rs`, shouldn't `poshpop_unsafe` be moved to the `removed` list instead of deleted?

**Comment by est31** [comment]
@durka better now?

**Comment by GuillaumeGomez** [comment]
Since safe_suggestion never really existed, I'm not sure it's useful to put in the removed list as well...

**Review by durka — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry

After nearly 5 hours it looks like AppVeyor lost track of those builds? I canceled manually to keep the queue moving.

**Comment by est31** [comment]
@alexcrichton it was likely this issue: http://status.appveyor.com/incidents/k06ydx9hkhbt

**Comment by alexcrichton** [comment]
@est31 thanks for the pointer!

**Pull request merged**
