### PR TITLE
Prevent using the default `cc` when that'd result in a broken build

### LINKED ISSUE #111142: Invalid `aarch64-unknown-none` target produced if the `CC_aarch64_unknown_none` env var is not set
If you try to compile the core library for the `aarch64-unknown-none` target, and the `CC_aarch64_unknown_none` environment variable is not set, you will end up with a broken target that can't link any basic program:

```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="<redacted>" VSLANG="1033" "rust-lld" "-flavor" "gnu" "/tmp/rustcPX9tnr/symbols.o" "binary.binary.ec7d7d9e5618561c-cgu.0.rcgu.o" "--as-needed" "-L" "/home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib" "-Bstatic" "/home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/librustc_std_workspace_core-3304236ec67a17db.rlib" "/home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcore-27e4e5b40a434022.rlib" "/home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib" "-Bdynamic" "--eh-frame-hdr" "-z" "noexecstack" "-L" "/home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib" "-o" "binary" "--gc-sections"
  = note: rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas1_relax.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas1_acq.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas1_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas1_acq_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas2_relax.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas2_acq.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas2_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas2_acq_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas4_relax.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas4_acq.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas4_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas4_acq_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas8_relax.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas8_acq.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas8_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas8_acq_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas16_relax.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas16_acq.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas16_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: /home/pietro/tmp/sysroot/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-5d101b3353699a4d.rlib(lse_cas16_acq_rel.o) is incompatible with /tmp/rustcPX9tnr/symbols.o
          rust-lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
```

Inspecting the `libcompiler_builtins-5d101b3353699a4d.rlib` file, we can see that the codegen units produced by rustc are indeed aarch64, but the object files produced by the compiler_builtins's build script are x86_64:

```
$ file compiler_builtins-5d101b3353699a4d.compiler_builtins.aeeb364441e31d74-cgu.0.rcgu.o 
compiler_builtins-5d101b3353699a4d.compiler_builtins.aeeb364441e31d74-cgu.0.rcgu.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), not stripped
$ file lse_cas1_relax.o
lse_cas1_relax.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), stripped
```

Having a "polyglot" `libcompiler_builtins.rlib` makes the linker sad, and results in the confusing linker error messages above.

CI-built tarballs are not affected by this (as it sets the `CC_aarch64_unknown_none` environment variable), but right now this is a huge footgun for anyone trying to build the target locally. We should add some safeguards to prevent this from happening.

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR adds a check in bootstrap to prevent issues like https://github.com/rust-lang/rust/issues/111142 to happen. What happened there is, no compiler for `aarch64-unknown-none` was detected by bootstrap, and so the `cc` crate defaulted to the system host C compiler. That resulted in a broken target, as `libcompiler_builtins.rlib` (or well anything compiling C code in its build script) contained half the object files compiled for aarch64 and half of them compiled for x86_64.

The check added in the PR ensures that, for cross-compilation, the detected C compiler is not the same one as the host compiler, unless the detected compiler is clang (as it supports all targets from a single binary). This should not cause too many false positives, as for example a `./x build library --target i686-unknown-linux-gnu` still works from a x86_64 host. If a false positive occurs, the error message still explains the workaround.

Example error message:

```
  running: "/home/pietro/r/github/rust-lang/rust/2/build/bootstrap/debug/broken-cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "--broken-cc-target=aarch64-unknown-none" "--broken-cc-detected=cc" "-I" "/home/pietro/r/github/rust-lang/rust/2/src/llvm-project/compiler-rt/lib/builtins" "-fno-builtin" "-fvisibility=hidden" "-ffreestanding" "-DVISIBILITY_HIDDEN" "-o" "/home/pietro/r/github/rust-lang/rust/2/build/x86_64-unknown-linux-gnu/stage0-std/aarch64-unknown-none/release/build/compiler_builtins-13da5a491a5cb882/out/ea072bc2688e9ac2-lse_cas1_relax.o" "-c" "/home/pietro/r/github/rust-lang/rust/2/build/x86_64-unknown-linux-gnu/stage0-std/aarch64-unknown-none/release/build/compiler_builtins-13da5a491a5cb882/out/lse_cas1_relax.S"
  cargo:warning=
  cargo:warning=   Error: the automatic detection of the C compiler for cross-compiled
  cargo:warning=   target aarch64-unknown-none returned the compiler also used for the
  cargo:warning=   current host platform.
  cargo:warning=
  cargo:warning=   This is likely wrong, and will likely result in a broken compilation
  cargo:warning=   artifact. Please specify the correct compiler for that target, either
  cargo:warning=   with environment variables:
  cargo:warning=
  cargo:warning=       CC_aarch64_unknown_none=path/to/cc
  cargo:warning=       CXX_aarch64_unknown_none=path/to/cxx
  cargo:warning=
  cargo:warning=   ...or in config.toml:
  cargo:warning=
  cargo:warning=       [target."aarch64-unknown-none"]
  cargo:warning=       cc = "path/to/cc"
  cargo:warning=       cxx = "path/to/cxx"
  cargo:warning=
  cargo:warning=   The detected C compiler was:
  cargo:warning=
  cargo:warning=       cc
  cargo:warning=
  exit status: 1

  --- stderr


  error occurred: Command "/home/pietro/r/github/rust-lang/rust/2/build/bootstrap/debug/broken-cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "--broken-cc-target=aarch64-unknown-none" "--broken-cc-detected=cc" "-I" "/home/pietro/r/github/rust-lang/rust/2/src/llvm-project/compiler-rt/lib/builtins" "-fno-builtin" "-fvisibility=hidden" "-ffreestanding" "-DVISIBILITY_HIDDEN" "-o" "/home/pietro/r/github/rust-lang/rust/2/build/x86_64-unknown-linux-gnu/stage0-std/aarch64-unknown-none/release/build/compiler_builtins-13da5a491a5cb882/out/ea072bc2688e9ac2-lse_cas1_relax.o" "-c" "/home/pietro/r/github/rust-lang/rust/2/build/x86_64-unknown-linux-gnu/stage0-std/aarch64-unknown-none/release/build/compiler_builtins-13da5a491a5cb882/out/lse_cas1_relax.S" with args "broken-cc" did not execute successfully (status code exit status: 1).


Build completed unsuccessfully in 0:00:02
```

Fixes #111142
r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
FYI I am not planning to review this currently since the CI failure seems to show it's not really workable. Unfortunately I don't have suggestions for improving it ... maybe thomcc has suggestions since he maintains cc, but tbh I think the real problem here is that cc generates broken code instead of giving an error.

**Comment by pietroalbini** [comment]
@jyn514 I think the CI problem above will need to be fixed regardless of whether we implement the error in bootstrap (like this PR does) or in `cc` (like you suggest). If the `cc` crate were to error out when it cannot find a suitable compiler, it would also error out on our CI like it's happening right now.

The error is that we're trying to compile 32bit mingw on that builder without the appropriate compiler. I'll fix it in the coming days, but I still think the PR can be reviewed (apart from the CI changes needed to inject the correct compilers).

**Comment by Mark-Simulacrum** [comment]
I think CI is still failing (not sure if that was intended to be fixed?). My sense is that this will make it harder to do "trivial" cross-testing for cases where you _don't_ actually need a C compiler, because you're not planning on using it. We have an escape hatch (or did?) in the form of an env-variable override ("BOOTSTRAP_SKIP_TARGET_SANITY"), added in https://github.com/rust-lang/rust/pull/103569... but forcing people to use something like that doesn't feel great.

I think at _minimum_ we should move this new check into the same code that's trying to confirm that we have C/C++ compilers in sanity.rs. That would probably fix CI without any other changes needed, and be a good enough starting point that I feel OK merging this. But if we see issues I'd be inclined to back this out or move it to a warning rather than hard error.

**Comment by pietroalbini** [comment]
Rewrote the patch to take in account Mark's feedback and the [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/cc.20detection).

To only show the error message when a C compiler is actually used, there is now a `broken-cc` binary responsible for showing the error message to the user, and when a broken C compiler is detected the path to the C compiler for that target is replaced with `broken-cc`. This means the error message is only shown when the compiler is invoked.

**Before merging:** I tested this on Linux, and it should also work for macOS. We need to test whether this behaves correctly on Windows though, and I don't have a Windows machine at hand. Right now the condition has `!compiler.is_like_clang()`, as clang has a single binary for all targets, but I don't know how the linker behaves on Windows and whether we should change that condition to `compiler.is_like_gnu()`.

**Review by onur-ozkan — APPROVED** [review]
> Before merging: I tested this on Linux, and it should also work for macOS. We need to test whether this behaves correctly on Windows though, and I don't have a Windows machine at hand. Right now the condition has !compiler.is_like_clang(), as clang has a single binary for all targets, but I don't know how the linker behaves on Windows and whether we should change that condition to compiler.is_like_gnu().

I don't have Windows environment to check this.

iirc you do have Windows environment, if so, can you check this ? @albertlarsan68

r=me with the Windows compatibility check

**Comment by miguelraz** [comment]
Checked out this branch locally and can confirm that running
```
./x.py build --stage 1 library --target i686-pc-windows-msvc
```
works on recent Windows on a 64bit 12 x AMD Ryzen 5 PRO 4650 and Visual Studio Developer tools installed.

**Comment by kjetilkjeka** [comment]
Is this also used for some sort of testing ABI compliance between rustc and a C compiler?  

I guess nvcc would be the most authoritative one (official nvidia compiler). clang is also able to compile to ptx.

Note that there is not much support for linking in ptx and libcompiler_builtins is linked in llvm bitcode on the nvptx target. Perhaps this is an argument for using clang?

**Comment by pietroalbini** [comment]
So, it turns out this was a legit error by the detection, as CI was trying to compile a CUDA object file with an x86_64 compiler, *but* it was an irrelevant error as none of the test suites executed by CI ever linked to that object file.

Still, I configured CI to use clang as the C/C++ compiler for `nvptx64-nvidia-cuda` (passing `-flto` to make it work), and `#ifdef`'d out a part of the source being compiled that'd crash clang.

**Comment by pietroalbini** [comment]
Seems spurious?

@bors retry

**Comment by pietroalbini** [comment]
Seems like I gated things to run only on nvptx, rather than everywhere but nvptx :sweat_smile: 

@bors r=onur-ozkan rollup=never

**Comment by fmease** [comment]
(I had to synchronize the queue)
@bors r-

**Comment by Dylan-DPC** [comment]
@pietroalbini any updates on this? thanks

**Comment by JohnCSimon** [comment]
@pietroalbini 
Ping from triage: I'm closing this due to inactivity because it hasn't seen any contributions in over a year.

Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks 

@rustbot label: +S-inactive

**Pull request closed without merging**
