### PR TITLE
mem::swap the obvious way for types smaller than the SIMD optimization's block size

### PR DESCRIPTION
**Pull request by scottmcm**
LLVM isn't able to remove the alloca for the unaligned block in the post-SIMD tail in some cases, so doing this helps SRoA work in cases where it currently doesn't.  Found in the `replace_with` RFC discussion.

Examples of the improvements:
<details>
 <summary>swapping `[u16; 3]` takes 1/3 fewer instructions and no stackalloc</summary>

```rust
type Demo = [u16; 3];
pub fn swap_demo(x: &mut Demo, y: &mut Demo) {
    std::mem::swap(x, y);
}
```

nightly:
```asm
_ZN4blah9swap_demo17ha1732a9b71393a7eE:
.seh_proc _ZN4blah9swap_demo17ha1732a9b71393a7eE
	sub	rsp, 32
	.seh_stackalloc 32
	.seh_endprologue
	movzx	eax, word ptr [rcx + 4]
	mov	word ptr [rsp + 4], ax
	mov	eax, dword ptr [rcx]
	mov	dword ptr [rsp], eax
	movzx	eax, word ptr [rdx + 4]
	mov	word ptr [rcx + 4], ax
	mov	eax, dword ptr [rdx]
	mov	dword ptr [rcx], eax
	movzx	eax, word ptr [rsp + 4]
	mov	word ptr [rdx + 4], ax
	mov	eax, dword ptr [rsp]
	mov	dword ptr [rdx], eax
	add	rsp, 32
	ret
	.seh_handlerdata
	.section	.text,"xr",one_only,_ZN4blah9swap_demo17ha1732a9b71393a7eE
	.seh_endproc
```

this PR:
```asm
_ZN4blah9swap_demo17ha1732a9b71393a7eE:
	mov	r8d, dword ptr [rcx]
	movzx	r9d, word ptr [rcx + 4]
	movzx	eax, word ptr [rdx + 4]
	mov	word ptr [rcx + 4], ax
	mov	eax, dword ptr [rdx]
	mov	dword ptr [rcx], eax
	mov	word ptr [rdx + 4], r9w
	mov	dword ptr [rdx], r8d
	ret
```
</details>

<details>
 <summary>`replace_with` optimizes down much better</summary>

Inspired by https://github.com/rust-lang/rfcs/pull/2490,

```rust
fn replace_with<T, F>(x: &mut Option<T>, f: F)
    where F: FnOnce(Option<T>) -> Option<T>
{
    *x = f(x.take());
}

pub fn inc_opt(mut x: &mut Option<i32>) {
    replace_with(&mut x, |i| i.map(|j| j + 1));
}
```

Rust 1.26.0:
```asm
_ZN4blah7inc_opt17heb0acb64c51777cfE:
	mov	rax, qword ptr [rcx]
	movabs	r8, 4294967296
	add	r8, rax
	shl	rax, 32
	movabs	rdx, -4294967296
	and	rdx, r8
	xor	r8d, r8d
	test	rax, rax
	cmove	rdx, rax
	setne	r8b
	or	rdx, r8
	mov	qword ptr [rcx], rdx
	ret
```

Nightly (better thanks to ScalarPair, maybe?):
```asm
_ZN4blah7inc_opt17h66df690be0b5899dE:
	mov	r8, qword ptr [rcx]
	mov	rdx, r8
	shr	rdx, 32
	xor	eax, eax
	test	r8d, r8d
	setne	al
	add	edx, 1
	mov	dword ptr [rcx], eax
	mov	dword ptr [rcx + 4], edx
	ret
```

This PR:
```asm
_ZN4blah7inc_opt17h1426dc215ecbdb19E:
	xor	eax, eax
	cmp	dword ptr [rcx], 0
	setne	al
	mov	dword ptr [rcx], eax
	add	dword ptr [rcx + 4], 1
	ret
```

Where that add is beautiful -- using an addressing mode to not even need to explicitly go through a register -- and the remaining imperfection is well-known (https://github.com/rust-lang/rust/pull/49420#issuecomment-376805721).
</details>

### CODE REVIEW

**Comment by kennytm** [comment]
I don't think this has anything to do with SIMD, as the longer codegen is still produced when commenting out the `#[repr(simd)]`.

OTOH, changing this line:

https://github.com/rust-lang/rust/blob/a739c51d108b1958a1c3e145588035c580e7973a/src/libcore/ptr.rs#L229

to 

```rust
        let mut t = UnalignedBlock(0,0,0,0);
```

is sufficient to get this ASM on godbolt:

```asm
example::swap_i48:
  mov eax, dword ptr [rdi]
  movzx ecx, word ptr [rdi + 4]
  movzx edx, word ptr [rsi + 4]
  mov word ptr [rdi + 4], dx
  mov edx, dword ptr [rsi]
  mov dword ptr [rdi], edx
  mov word ptr [rsi + 4], cx
  mov dword ptr [rsi], eax
  ret
```

**Comment by scottmcm** [comment]
Interesting, @kennytm.  Also really disturbing, since initializing to `undef` should in all situations allow the optimizer more freedom than initializing to a concrete value.  It makes me wonder if the whole "swapping in u64s" approach actually has `undef` problems, perhaps in padding or similar...

(Agreed that it's not actually about the SIMD, but about the tail-too-small-to-SIMD part of the method.)

**Comment by kennytm** [comment]
I've also checked the `inc_opt` case, and https://github.com/rust-lang/rust/pull/52051#issuecomment-402440459 is *not* sufficient to reproduce the ultimate optimized code.

**Comment by scottmcm** [comment]
@kennytm Can you share your godbolt?  [When I try the change locally](https://github.com/scottmcm/rust/commit/7f5867ecbc645901152e7cf6dbcc3d9c8fe059a1#r29593806), I get worse codegen as it zero-inits the part of the stack that the memcpys don't write.

<details>
 <summary>ASM with zero-init for the unaligned block</summary>

```asm
_ZN4blah9swap_demo17ha1732a9b71393a7eE:
.seh_proc _ZN4blah9swap_demo17ha1732a9b71393a7eE
	sub	rsp, 32
	.seh_stackalloc 32
	.seh_endprologue
	xorps	xmm0, xmm0
	movups	xmmword ptr [rsp + 16], xmm0
	movups	xmmword ptr [rsp + 6], xmm0
	movzx	eax, word ptr [rcx + 4]
	mov	word ptr [rsp + 4], ax
	mov	eax, dword ptr [rcx]
	mov	dword ptr [rsp], eax
	movzx	eax, word ptr [rdx + 4]
	mov	word ptr [rcx + 4], ax
	mov	eax, dword ptr [rdx]
	mov	dword ptr [rcx], eax
	mov	eax, dword ptr [rsp]
	mov	dword ptr [rdx], eax
	movzx	eax, word ptr [rsp + 4]
	mov	word ptr [rdx + 4], ax
	add	rsp, 32
	ret
	.seh_handlerdata
	.section	.text,"xr",one_only,_ZN4blah9swap_demo17ha1732a9b71393a7eE
	.seh_endproc
```

</details>

**Comment by kennytm** [comment]
@scottmcm https://godbolt.org/g/1vgFXw

Including `inc_opt` in the same snippet spoils the optimization though 🤔.

**Comment by scottmcm** [comment]
Using an array of 4 `0_u64`s instead of the struct of them also seems to break the optimization, putting in the explicit stack zeroing like I'm seeing locally: https://godbolt.org/g/smQfre

Given how subtle all these changes seem to be, I'm liking the "just do it the obvious way" code even more.

**Comment by kennytm** [comment]
Could we modify `swap_nonoverlapping` instead of creating a new function `swap_nonoverlapping_one`?

```rust
unsafe fn swap_nonoverlapping<T>(x: *mut T, y: *mut T, count: usize) {
    if count == 1 && mem::size_of::<T>() < 32 {
        let z = read(x);
        copy_nonoverlapping(y, x, 1);
        write(y, z);
    } else {
        let x = x as *mut u8;
        let y = y as *mut u8;
        let len = mem::size_of::<T>() * count;
        swap_nonoverlapping_bytes(x, y, len)
    }
}
```

**Comment by stokhos** [comment]
Ping from triage! @rust-lang/libs anyone got time to review this PR?

**Comment by alexcrichton** [comment]
I agree with @scottmcm that we should keep this as a separate function for now, but if the need arises we can always merge it with the original `swap_nonoverlapping` function!

**Comment by scottmcm** [comment]
Does the appveyor build use a different LLVM from tree?  I just rebased this locally on windows and the test passes fine...

**Comment by kennytm** [comment]
@scottmcm Are you targeting `i686-pc-windows-msvc`?

**Comment by scottmcm** [comment]
Thanks, @kennytm!  That makes sense -- it probably doesn't unify the loads/stores on 32-bit.  I've pushed an update to the test to not try to run it everywhere, since it depends on optimizations.

**Pull request merged**
