### PR TITLE
Stop using derivative in rustc_pattern_analysis

### PR DESCRIPTION
**Pull request by lnicola**
CC #109302, https://github.com/rust-lang/rust-analyzer/pull/16420#discussion_r1464357157

r? @Nadrieril

### CODE REVIEW

**Comment by Nilstrieb** [comment]
not particularly happy with the diff 😞
but I can see the motivation
@bors r+ rollup

**Comment by lnicola** [comment]
> not particularly happy with the diff 😞

I'll change it back after #26925 :grinning:.

> Oh, didn't see the assignment to Nadrieril, but I assume it's fine for me to approve it :)

Yeah, sorry, I added it in later.

**Comment by Nadrieril** [comment]
Oh, thank you for doing that! I had started doing that but I didn't enjoy the manual `Clone` and `PartualEq` impls. I guess they're manageable

**Comment by Nadrieril** [comment]
Oh, thank you for doing that! I had started doing that but I didn't enjoy the manual `Clone` and `PartualEq` impls. I guess they're manageable

**Comment by lnicola** [comment]
We could even get rid of it (there's only one other crate using derivative), but I'm not sure how popular that would be.

**Comment by Nadrieril** [comment]
I don't think it would be too hard to maintain it ourselves if we do want to keep it

**Comment by Nilstrieb** [comment]
I think the cost and benefit are both pretty small. It was added recently to replace the manual handwritten impls which were a bit annoying. I don't think it matters that much to get rid of syn 1, the compiler depends on so many crates and I doubt syn 1 or derivative are a bottleneck.

**Comment by Nadrieril** [comment]
Aren't you the one who opened https://github.com/rust-lang/rust/issues/109302? 😄

**Pull request merged**
