### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by compiler-errors**
Successful merges:

 - #116750 (Add Seek::seek_relative)
 - #117110 (Suggest field typo through derefs)
 - #117813 (deprecate `if-available` value of `download-ci-llvm`)
 - #117868 (Set `CFG_OMIT_GIT_HASH=1` during builds when `omit-git-hash` is enabled)
 - #117895 (Adjust frame IP in backtraces relative to image base for SGX target)
 - #117961 (Add `x suggest` entries for testing `mir-opt` and `coverage`)
 - #117992 (Don't require intercrate mode for negative coherence)
 - #117994 (Ignore but do not assume region obligations from unifying headers in negative coherence)
 - #118020 (Fix links to `From<{OwnedHandle, OwnedFd}> for std::process::Child{Stdin, Stdout, Stderr}` in 1.74 release notes)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=116750,117110,117813,117868,117895,117961,117992,117994,118020)

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors r+ rollup=never p=9

Opening a larger rollup since the one that's currently open is really small for some reason.

**Comment by compiler-errors** [comment]
Nevermind, there are conflicting PRs.

**Comment by matthiaskrgr** [comment]
Guess you will find the reason in around 30 minutes :upside_down_face:    https://github.com/rust-lang/rust/pull/118041#issuecomment-1817581354

**Comment by compiler-errors** [comment]
If that rollup failure had been triaged properly then maybe I would've known >5 minutes ago 😿

**Comment by matthiaskrgr** [comment]
:) it's not always that easy especially when theres weird interaction between prs

**Pull request closed without merging**
