### PR TITLE
Library stabilizations for 1.17

### PR DESCRIPTION
**Pull request by aturon**
Details of the stabilizations are available in the commits. Includes only library stabilizations; there are a couple of compiler stabilizations that should also be done for 1.17.

Will need a beta backport, which I will create after approval.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1 

Looks good to me, I pushed a commit as well to fix some tidy errors and missed one API (`BTreeSet::range`)

**Comment by alexcrichton** [comment]
(btw p=1 for the beta nomination)

**Comment by ollie27** [comment]
Shouldn't the `btree_map::Range`, `btree_map::RangeMut` and `btree_set::Range` structs and the trait impls for them also be stabilised?

**Comment by alexcrichton** [comment]
@ollie27 good catch, I'll update those (thanks for the sharp eye!)

**Comment by arielb1** [comment]
```
failures:

---- range.rs - range::RangeArgument::end (line 52) stdout ----

	error: this feature has been stable since 1.17.0. Attribute no longer needed

 --> <anon>:3:12

  |

3 | #![feature(collections_bound)]

  |            ^^^^^^^^^^^^^^^^^

  |

  = note: #[deny(stable_features)] implied by #[deny(warnings)]

note: lint level defined here

 --> <anon>:6:9

  |

6 | #![deny(warnings)]

  |         ^^^^^^^^

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- range.rs - range::RangeArgument::start (line 29) stdout ----

	error: this feature has been stable since 1.17.0. Attribute no longer needed

 --> <anon>:3:12

  |

3 | #![feature(collections_bound)]

  |            ^^^^^^^^^^^^^^^^^

  |

  = note: #[deny(stable_features)] implied by #[deny(warnings)]

note: lint level defined here

 --> <anon>:6:9

  |

6 | #![deny(warnings)]

  |         ^^^^^^^^

```

@bors r-

**Comment by alexcrichton** [comment]
@bor: r+

**Comment by arielb1** [comment]
Mac builders why aren't you running?

@bors retry

**Pull request merged**
