### PR TITLE
`BasicBlock::new(0)` -> `START_BLOCK` [no functional changes]

### PR DESCRIPTION
**Pull request by scottmcm**

### CODE REVIEW

**Comment by compiler-errors** [comment]
Do you want to also change the usages of `BasicBlock::from_{u32,usize}` similarly?

Also, there's one usage of `Location { block: START_BLOCK, statement_index: 0 }` and `START_BLOCK.start_location()` which can be replaced with `Location::START`, I think?

**Comment by scottmcm** [comment]
Oh, sure, I can do some more of this.  'Twas just only the `new(0)` that I noticed, so I looked for the others 🙃

@rustbot author

**Comment by scottmcm** [comment]
Didn't find any `from_usize(0)`s, but hopefully got the rest of them.

@rustbot ready

**Comment by compiler-errors** [comment]
r=me when green

**Pull request merged**
