### PR TITLE
Remove two redundant .nll.stderr files

### PR DESCRIPTION
**Pull request by pnkfelix**
It turns out that the diagnostics generated from NLL for these cases are now exactly the same as that produced by AST borrowck, and thus we can just fallback on those `.stderr` files that already exist for AST-borrowck.

Bravo!

(it is a good idea to remove these files, because it slightly reduces the amount of time humans will spend reviewing the .nll.stderr fileset...)

((it *might* be worthwhile trying to change the `compiletest` code to even issue a warning when two such files have equivalent contents... but I am not going so far as to try to implement that right now...))

### CODE REVIEW

**Comment by pietroalbini** [comment]
@oli-obk this probably needs to be r+ed again.

**Comment by pietroalbini** [comment]
Ok, nevermind. @pnkfelix this PR needs to be rebased on top of the latest master.

**Comment by oli-obk** [comment]
idk why this would have a merge conflict...

@bors r+

**Comment by pietroalbini** [comment]
Yeah, for some reason bors doesn't like this. This needs to be rebased.

**Pull request merged**
