### PR TITLE
Add dist builder for Armv8-M Baseline and HF

### PR DESCRIPTION
**Pull request by hug-dev**
This commit adds the Armv8-M Baseline and Armv8-M Mainline with
FPU targets in the list of targets that
get their dist components built. It also update the build-manifest
so that this target gets also its dist components uploaded.

Made possible with the recent change merged in `compiler-builtins`:
rust-lang-nursery/compiler-builtins#276

A new `compiler-builtins` might be necessary for successfull compilation of the artefacts of those targets.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@hug-dev want to switch the dist-various-1 builder in .travis.yml to working on the `try` branch, then we can `@bors: try`, see a failure, publish compiler-builtins, then `@bors: try` again to see success?

**Comment by hug-dev** [comment]
@alexcrichton Sure! Just to make sure is that that change:
```diff
diff --git a/.travis.yml b/.travis.yml
index 7985b6c0e1..df1182345b 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -121,7 +121,7 @@ matrix:
     - env: IMAGE=armhf-gnu
       if: branch = auto
     - env: IMAGE=dist-various-1 DEPLOY=1
-      if: branch = auto
+      if: branch = try
     - env: IMAGE=dist-various-2 DEPLOY=1
       if: branch = auto
     - env: IMAGE=dist-aarch64-linux DEPLOY=1
```

**Comment by alexcrichton** [comment]
I believe that should do the trick yeah!

**Comment by alexcrichton** [comment]
Hm it looks like the [job failed](https://travis-ci.com/rust-lang/rust/jobs/184926943) but for a different reason? Feel free to use `[patch]` temporarily as well to pull in a fork of compiler-builtins to test here on CI

**Comment by hug-dev** [comment]
I rebased and added a new commit which replace `compiler-builtins` with a virtual release I have made on my own forked version of it at `hug-dev/compiler-builtins` ([release commit](https://github.com/hug-dev/compiler-builtins/commit/e745aea2c2ba46fef91d3761c9af699e5dc214f5))
I also did `cargo +nightly update -p compiler-builtins` to update `Cargo.lock`.
Finally, I temporary hacked `src/tools/tidy/src/extdeps.rs` to make it work.

@alexcrichton If all of this is correct, a new `try` of bors should give us more interesting results :)

**Comment by alexcrichton** [comment]
Nice! The [job](https://travis-ci.com/rust-lang/rust/jobs/186470876) has a bunch of [verbose logs](https://api.travis-ci.com/v3/job/186470876/log.txt) which point to:

https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/54cce0fe70aa1e1d5ecf93ed305f5ebaee8cd3eb/rust-std-nightly-thumbv8m.base-none-eabi.tar.gz

(and the final component can be tweaked to get the different targets)

Mind poking around those and make sure they look all good? After that looks like this'll be an easy merge! (we can get the compiler-builtins changes in and published before this PR lands)

**Comment by hug-dev** [comment]
I can not say if there are no bugs at all, but I think this is fine.
I had a quick look and `thumbv8m.main-none-eabihf` and `thumbv8m.base-none-eabi` artefacts seems to have the same files, with around the same sizes than the other `thumb*` targets. I disassembled `core` for both of them and they seemed to contain the correct instructions. I can not check all of them of course!

**Comment by alexcrichton** [comment]
Ok great! Want to send a PR to compiler-builtins and I can merge/publish?

**Comment by hug-dev** [comment]
Sure! Do you mean a PR that does the same thing as this below to mark the new release?
https://github.com/hug-dev/compiler-builtins/commit/e745aea2c2ba46fef91d3761c9af699e5dc214f5

**Comment by alexcrichton** [comment]
Oh sorry I thought there were more changes that weren't already in there. In that case I've published 0.1.8 now

**Comment by hug-dev** [comment]
No worries! I am going to update this PR to remove the commits that use the `try` branch and `patch` and add a commit to update `Cargo.lock` for `compiler-builtins`

**Comment by hug-dev** [comment]
Rebased to latest `master` and did the previously written modifications.

**Comment by hug-dev** [comment]
Rebased to fix conflict on `Cargo.lock`

**Comment by hug-dev** [comment]
Rebased and removed the `compiler-builtins` update as it is already updated to 0.1.8 upstream :)

**Pull request merged**
