### PR TITLE
Arbitrary self types v2: simulated stabilization, do not merge

### PR DESCRIPTION
**Pull request by adetaylor**
This PR is essentially the same as #132961, but also flips the feature to being stabilized. We shouldn't merge this yet, but we want to do a crater run on this PR to check for unexpected surprises.

The difference relative to #132961 can be seen in [this comparison](https://github.com/adetaylor/rust/compare/arbitrary-self-types-the-big-bit...adetaylor:rust:receiver_trait_with_target_for_real).

Please *do not* review this - please add review comments on #132961, instead.

r? @wesleywiser

### CODE REVIEW

**Comment by wesleywiser** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@rust-timer build 2277c63fa464d237b17b68d3b87f9fbb89e58a3e

**Comment by adetaylor** [comment]
Crater results triaged here - https://github.com/rust-lang/rust/pull/132961#issuecomment-2525554996 - a clean run. Closing this PR.

**Comment by compiler-errors** [comment]
Since this is in no rush to be stabilized (namely, perf investigation still needs to happen and it naturally needs time to bake), we probably should run another stabilization crater run since the large number of "unknown" results is a bit concerning -- that's being investigated in https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/crater.20returning.20unknown (doesn't have to do w/ this PR)

**Comment by compiler-errors** [comment]
Let's rerun crater just for funsies.

@craterbot check

**Comment by adetaylor** [comment]
Triaging the new crater run from [here](https://github.com/rust-lang/rust/pull/133570#issuecomment-2544535469), and relative to the prior [crater run here](https://github.com/rust-lang/rust/pull/133570#issuecomment-2525277946):

* We no longer have 179819 crates in "unknown" (thanks to [this fix?](https://github.com/rust-lang/crater/pull/756))
* The number of crates in "error" state has risen from 5635 to 149100. These were all in "error" in both the before and after commit so it's unlikely to be due to this PR. Looking at a few of those we have a variety of errors - `failed to parse the version requirement `0.11	` for dependency `parking_lot`` is quite common but there are others too.
* Looking at those which have actually regressed in this PR there are 139:
   * They're almost all `no space left on device`, and a few bus errors from linking with `ld` which may well be due to the same problem
  * `opusic-c` gives a `ninja` error [which doesn't seem to be related](https://crater-reports.s3.amazonaws.com/pr-133570-1/try%232277c63fa464d237b17b68d3b87f9fbb89e58a3e/reg/opusic-c-1.5.2-beta.4/log.txt)
  * We have one real problem: [fmhall.chess-program](https://crater-reports.s3.amazonaws.com/pr-133570-1/try%232277c63fa464d237b17b68d3b87f9fbb89e58a3e/gh/fmhall.chess-program/log.txt) gives an ICE with `Encountered anon const with inference variable args but no error reported` - this looks to be from relevant code so is presumed to be a real problem, I'll look later

**Comment by adetaylor** [comment]
Looking into the above "real problem", it in fact reproduces with which the compiler version (c0e0d8f8746740768c13bdb632d7b7f1fef2f17a) immediately before the main arbitrary self types v2 PR (https://github.com/rust-lang/rust/pull/132961) so I'm confident it's not related. I think the reason crater reported it as a new regression is that in prior runs, this test had been OOMing.

**Pull request closed without merging**
