### PR TITLE
Stabilize the `bundle` native library modifier

### LINKED ISSUE #37403: Tracking issue for #[link(kind)] connecting libraries on Windows
Tracking issue for https://github.com/rust-lang/rfcs/pull/1717

- [x] Implement `-l[kind=][oldname:]libname`.
- [x] Implement lib<->symbol association and emit `dllimport` for dylib symbols.
- [x] Implement `kind="static-nobundle"`.

### PR DESCRIPTION
**Pull request by petrochenkov**
And remove the legacy `static-nobundle` linking kind.

Stabilization report - https://github.com/rust-lang/rust/pull/95818#issuecomment-1120470945.

cc #81490
Closes #37403

### CODE REVIEW

**Comment by petrochenkov** [comment]
# Stabilization Report

This PR stabilizes native library modifier `bundle`, a part of RFC 2951: "Linking modifiers for native libraries" (tracking issue https://github.com/rust-lang/rust/pull/83507).
The RFC was implemented about 1 year ago in https://github.com/rust-lang/rust/pull/83507.

Before that it was implemented as a separate linbrary kind `static-nobundle` in early 2017 in https://github.com/rust-lang/rust/pull/38426.
`static-nobundle` kind was deprecated about 1 year ago and this PR removes it.

## `bundle` modifier

Examples: `#[link(name = "mylib", kind = "static", modifiers = "-bundle")]`, `-l static:-bundle=mylib`. 

This modifier is only compatible with the `static` linking kind.
Using any other kind will result in a compiler error.

When building a rlib or staticlib `+bundle` means that all object files from the native static
library will be added to the rlib or staticlib archive, and then used from it during linking of
the final binary.

When building a rlib `-bundle` means that the native static library is registered as a dependency
of that rlib "by name", and object files from it are included only during linking of the final
binary, the file search by that name is also performed during final linking. \
When building a staticlib `-bundle` means that the native static library is simply not included
into the archive and some higher level build system will need to add it later during linking of
the final binary.

This modifier has no effect when building other targets like executables or dynamic libraries.

The default for this modifier is `+bundle`.

## Test cases

- `src\test\run-make\native-link-modifier-*`
- `src\test\ui\native-library-link-flags\*`

## Documentation

https://github.com/rust-lang/reference/pull/1210

**Comment by petrochenkov** [comment]
@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Did the test actually fail? It looks to me like the symbol is present in the output and we instead ran into some kind of IO error in the test runner so this may just need a rebase/retry?

**Comment by petrochenkov** [comment]
Let's try `nm` instead of `llvm-nm`.
@bors r=wesleywiser

**Comment by wesleywiser** [comment]
@bors r-

Ok, it looks like that IO error is cutting off the part of the test which is failing. On my local computer, the tail of the failing test says this:

```
# Build a cdylib, `native-staticlib` will not appear on the linker line because it was bundled previously
# The cdylib will contain the `native_func` symbol in the end
LD_LIBRARY_PATH="/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle:/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib:/tmp/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/tmp/rust/build/x86_64-unknown-linux-gnu/stage0/lib" '/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc' --out-dir /tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle -L /tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle  cdylib-bundled.rs --crate-type=cdylib --print link-args | "/tmp/rust/src/etc/cat-and-grep.sh" -ve '-l[" ]*native-staticlib'
[[[ begin stdout ]]]
"cc" "-Wl,--version-script=/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/rustcN7l4Es/list" "-m64" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/rustcN7l4Es/symbols.o" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/cdylib-bundled.cdylib_bundled.fec11cde-cgu.0.rcgu.o" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/cdylib-bundled.36zfynnmdkuikfvj.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle" "-L" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/libbundled.rlib" "-Wl,--start-group" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-40d3ab217333ea6f.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-342e0c7e58b758c7.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-fd0cbe7355ea90fe.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-5d909f05bea8a2ec.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-c1f0f7998b5f4f34.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-473b04228aa37014.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-7b1987a043416988.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-fbee7d804fb3998f.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-38718f5bda60de40.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-88996712221b1d70.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-92eab706e4a4b72f.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-07e0250875d0f6c4.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-2f0fbed83b3fc1be.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-3dff4abc544e5a9d.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-fbab093adeb72d7e.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-59934a55b0d5ed1e.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-023ef326799aa915.rlib" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-8808ef886908ca43.rlib" "-Wl,--end-group" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-4ca2eb6a42de4f5d.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/libcdylib_bundled.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-nodefaultlibs"

[[[ end stdout ]]]
nm -g /tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/libcdylib_bundled.so | "/tmp/rust/src/etc/cat-and-grep.sh" -e "T _*native_func"
[[[ begin stdout ]]]
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w __cxa_finalize@@GLIBC_2.2.5
                 w __gmon_start__
0000000000001100 T wrapped_func

[[[ end stdout ]]]
Error: cannot match: T _*native_func
rm /tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/libnative-staticlib.o
------------------------------------------
```

**Comment by petrochenkov** [comment]
>Error: cannot match: T _*native_func

🤦 
I pushed a fix for this several days ago, but overwrote it yesterday from an outdated branch.

**Comment by petrochenkov** [comment]
Hmm, maybe these IO errors happen just because a lot of text is printed (due to some CI-specific limitations) after some other original error is encountered?
In that case they should disappear once all the true errors are fixed.

**Comment by wesleywiser** [comment]
> Hmm, maybe these IO errors happen (due to some CI-specific limitations) just because a lot of text is printed after some other original error is encountered? In that case they should disappear once all the true errors are fixed.

Yeah, I think that's true.

I notice in the `cdylib` case, we're linking the native dependency as needed:

> "-Wl,--as-needed" "-L" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle" "-L" "/tmp/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rust/build/x86_64-unknown-linux-gnu/test/run-make/native-link-modifier-bundle/native-link-modifier-bundle/libbundled.rlib"

but since `cdylib-bundled.rs` doesn't use any symbols from native dependency, I don't think the linker has any reason to include it. Maybe I'm missing something?

**Comment by petrochenkov** [comment]
>but since `cdylib-bundled.rs` doesn't use any symbols from native dependency, I don't think the linker has any reason to include it.

The cdylib should export `wrapped_func` and therefore keep it alive.
`wrapped_func` uses `native_func` so it should also be kept.

Looks like I didn't reapply the fix for 

>I pushed a fix for this several days ago, but overwrote it yesterday from an outdated branch.

correctly, `T` was changed to `[Tt]`, but `-g` wasn't removed from `nm -g`.

**Comment by wesleywiser** [comment]
Thanks for your work on this @petrochenkov!

**Pull request merged**
