### PR TITLE
Remove obsolete support for linking unwinder on Android

### PR DESCRIPTION
**Pull request by pcc**
Linking libgcc is no longer supported (see #103673), so remove the related link attributes and the check in unwind's build.rs. The check was the last remaining significant piece of logic in build.rs, so remove build.rs as well.

### CODE REVIEW

**Comment by pcc** [comment]
cc @chriswailes

**Comment by bjorn3** [comment]
Somewhat related, but I think libunwind can be removed from https://github.com/rust-lang/rust/blob/c5afe0a61e39bdd912803eae8d1887a513bdd172/src/bootstrap/src/core/build_steps/dist.rs#L912 as libunwind isn't built from source anymore by the build script of the unwind crate.

**Comment by pcc** [comment]
Does that mean that we *never* build libunwind from source? This seems to indicate that we do so by default when targeting Fuchsia:

https://github.com/rust-lang/rust/blob/c5afe0a61e39bdd912803eae8d1887a513bdd172/config.example.toml#L760

and the code implementing that is:

https://github.com/rust-lang/rust/blob/c5afe0a61e39bdd912803eae8d1887a513bdd172/src/bootstrap/src/core/config/config.rs#L1995

**Comment by bjorn3** [comment]
My understanding is that any in-tree building is done by bootstrap. As such the source for libunwind only needs to be in the full source tarball and not the tarball for the standard library source which is never used with bootstrap.

**Comment by klensy** [comment]
So, drop this too?
https://github.com/rust-lang/rust/blob/b20f40dba9feabf4b446d9b09d15996f0c046eff/library/unwind/Cargo.toml#L22-L23

**Comment by pcc** [comment]
> So, drop this too?
> 
> https://github.com/rust-lang/rust/blob/b20f40dba9feabf4b446d9b09d15996f0c046eff/library/unwind/Cargo.toml#L22-L23

Done

**Pull request merged**
