### PR TITLE
Mini rollup

### PR DESCRIPTION
**Pull request by steveklabnik**
I had to fix up some PRs:
- https://github.com/rust-lang/rust/pull/22976
- https://github.com/rust-lang/rust/pull/22945
- https://github.com/rust-lang/rust/pull/22845

### CODE REVIEW

**Comment by Manishearth** [comment]
Awesome! When the queue is empty this seems like a great thing to keep it going :+1:

**Comment by steveklabnik** [comment]
@Manishearth :heart:

**Pull request merged**
