### PR TITLE
std::unix::stack_overflow::drop_handler addressing todo through libc …

### PR DESCRIPTION
**Pull request by devnexen**
…update

### CODE REVIEW

**Comment by joboet** [comment]
The constant [does not exist](https://docs.rs/libc/0.2.155/aarch64-linux-android/libc/?search=AT_MINSIGSTKSZ) on Android yet, I believe, so we still need the workaround. But maybe you could gate it to be Android-only?

**Comment by devnexen** [comment]
ah true, I misread one level of the libc crate.

**Comment by joboet** [comment]
Thank you!
@bors r+ rollup
r? joboet

**Review by workingjubilee — CHANGES_REQUESTED** [review]
huh? why is this constant not available on both android and linux?

**Comment by workingjubilee** [comment]
That FIXME was for **removing** a novel definition, not merely using `cfg` for one.

r? @workingjubilee

**Comment by workingjubilee** [comment]
This constant is invariant across all Linux architectures and kernels since its definition, so I don't know how I fucked up adding it to Android, but it should not be different there.

**Comment by workingjubilee** [comment]
Adding 3 lines of `cfg` noise is not what I intended, it is not an improvement, and it should not be accepted.

**Comment by devnexen** [comment]
adding [here](https://github.com/rust-lang/libc/pull/3754)

**Comment by workingjubilee** [comment]
Thank you.

**Comment by Dylan-DPC** [comment]
@devnexen any updates on this? thanks

**Comment by devnexen** [comment]
Well I see it is fixed on libc main branch only but not the stable branch I ll see for a backport.

**Comment by alex-semenyuk** [comment]
@devnexen
From wg-triage. Are we blocking with this PR?

**Comment by devnexen** [comment]
Not the case anymore, will update.

**Comment by joboet** [comment]
Right, let's try this again.
@bors r+

**Pull request merged**
