### PR TITLE
Reland #74069

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Investigation in #74716 has concluded that this PR is indeed not a regression (and in fact the rollup itself is not either).

This reverts the revert in #74611.

r? @nnethercote cc @eddyb

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

Let's double check just in case that this is indeed performance neutral.

**Comment by nnethercote** [comment]
Perf effects are minimal, if anything a tiny improvement.

**Comment by Mark-Simulacrum** [comment]
@nnethercote or @eddyb, I think this is good to go, would someone mind r+ing?

**Pull request merged**
