### PR TITLE
Make all vec! macros use square brackets: Attempt 2

### PR DESCRIPTION
**Pull request by iirelu**
[The last PR](https://github.com/rust-lang/rust/pull/37476) ended with tears after a valiant struggle with git. I managed to clean up the completely broken history of that into a brand spanking new PR! Yay!

Original:

> Everyone hates the old syntax. I hope. Otherwise this PR has some controversy I wasn't expecting.

> This would be the perfect time to write a lint recommending vec![..] when you use another style.

> Disclaimer: I may have broken something. If I have, I'll fix them when the tests come in. Luckily the chance for a non-syntactical error is pretty low in all this.

### CODE REVIEW

**Comment by sanxiyn** [comment]
This still has merge commits...

**Comment by retep998** [comment]
There's a little checkbox on the right you can check to allow the maintainers of this project to be able to update your PR for you, which would let them clean up your commit history for you.

**Comment by iirelu** [comment]
Okay, I think I finally unfricked my commit history-- AW GOD DAMMIT
b

**Comment by iirelu** [comment]
After countless horrible force-pushes, history rewrites, and endless trial and error, I have *finally* tamed the beast known as git. Thanks so much to @steveklabnik for all the help! :purple_heart:

**Comment by steveklabnik** [comment]
@bors: r+ p=1

Let's try to get this in the queue so it doesn't go out of date.

**Comment by steveklabnik** [comment]
(That is, I'll r- if Travis still fails for some reason.)

**Comment by steveklabnik** [comment]
Well looks like @bors got to it before Travis, I'm sure it'll be fine 😄

**Comment by WiSaGaN** [comment]
Has there been a discussion why we prefer `vec![]` to `vec!()`?

**Comment by retep998** [comment]
@WiSaGaN Because it matches array literal syntax which uses `[]`.

**Comment by steveklabnik** [comment]
Not all macros get called with `()`. The usual idiom is, macros that look
like function calls use `()`, macros that deal with things like vectors or
arrays use `[]`, and macros that involve wrapping code are invoked with
`{}`. All syntaxes are supported for any macro, but that tends to be idiom.

**Pull request merged**
