### PR TITLE
Move coverage tests from run-make-fulldeps to run-make

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by jyn514** [comment]
Looks spurious? That error would happen on a corrupted download, and this change doesn't touch the python code at all.

@bors retry

**Comment by tmiasko** [comment]
Updated bootstrap to build rust-demangler for the host instead of a target when executing run-make tests.

**Comment by Mark-Simulacrum** [comment]
@bors r+

This seems OK -- I'd love to see them migrate to compiletest proper, but for now this is already likely an improvement, moving the failure earlier.

**Pull request merged**
