### PR TITLE
Style guidelines: Change name of unit test sub-module to "tests".

### PR DESCRIPTION
**Pull request by jooert**
Changes the style guidelines regarding unit tests to recommend using a sub-module named "tests" instead of "test" for unit tests as "test" might clash with imports of libtest (see #23870, #24030 and http://users.rust-lang.org/t/guidelines-naming-of-unit-test-module/1078 for previous discussions).

r? @alexcrichton

### CODE REVIEW

**Comment by steveklabnik** [comment]
Doc stuff is good, but I'm not sure if we want to actually change the whole standard library over. but maybe? Let's see what others think.

(Oh, and thanks for the PR!)

**Comment by alexcrichton** [comment]
@bors: r+ 07cc7d9960a1bc767dc051b9fae0c7ad2b5cd97f

I'm ok with changing over the stdlib, there's some good support and consensus behind `tests` vs `test` and it's also a relatively small change.

**Comment by liigo** [comment]
Nice!

**Comment by steveklabnik** [comment]
marking for docs backport, but just the `style` chunk. TRPL will get its own backport.

**Pull request merged**
