### PR TITLE
Fix `TyKind::is_simple_path`

### LINKED ISSUE #103157: Illegal Eq derive in an enum with Option<f64>
I tried this code:

```rust
#[derive(PartialEq, Eq)]
pub enum Value {
    Boolean(Option<bool>),
    Float(Option<f64>),
}

fn main() {
    let a = Value::Float(Some(f64::NAN));
    
    // Eq should always have a == a
    // https://doc.rust-lang.org/std/cmp/trait.Eq.html
    assert!(a == a);
}
```

I expected to see this happen: code fails to compile.
Instead, this happened: code compiles, and assertion fails.

Changing order of enum variants to make `Float` go first fixes the issue:
```
// error[E0277] the trait bound `f64: Eq` is not satisfied
#[derive(PartialEq, Eq)]
                    -- in this derive macro expansion
pub enum Value {
    Float(Option<f64>),
    Boolean(Option<bool>),
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```

It's reproducible in [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cdd56f0d98da2afa2a89f076e3ad8ec7) in Stable, Beta and Nightly.

### PR DESCRIPTION
**Pull request by nnethercote**
Fixes #103157.

r? @spastorino

### CODE REVIEW

**Comment by apiraino** [comment]
I'm going to ask T-compiler about a backport (either or both stable/beta)

@rustbot label beta-nominated stable-nominated

**Comment by Nilstrieb** [comment]
I agree that this should go at least back to beta
- it's a small and obvious change
- it can break code that compiled with the previous compiler
Backporting it would minimize churn for users at little maintenance cost

**Comment by apiraino** [comment]
Beta and stable backports accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-10-20/near/305157910)

@rustbot label +beta-accepted +stable-accepted

**Comment by spastorino** [comment]
This one was also `stable-accepted`.

@apiraino did you intend to remove `stable-accepted` for some reason?
I think as with #103205, this one needs `@rustbot label +stable-accepted -stable-nominated` too.

**Comment by cuviper** [comment]
I'm general, backports should keep _both_ the nominated and accepted label until they've actually been backported.

**Pull request merged**
