### PR TITLE
Turn parsing into a query

### PR DESCRIPTION
**Pull request by Zoxc**
Builds on https://github.com/rust-lang/rust/pull/59282.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
ping from triage @eddyb waiting for your review on this

**Comment by Mark-Simulacrum** [comment]
Visiting from triage, I'm closing the series of PRs here other than the first one since they will likely only make progress sequentially and it doesn't help to have all of them open. For reference, this is https://github.com/rust-lang/rust/pull/59338, https://github.com/rust-lang/rust/pull/59282, and https://github.com/rust-lang/rust/pull/59205 which are (in that order) blocked on each other and eventually https://github.com/rust-lang/rust/pull/59064.

Feel free to reopen as those PRs merge and/or make progress.

**Comment by rholderfield** [comment]
ping from triage... @Zoxc, can you please provide a status?

**Comment by JohnCSimon** [comment]
@Zoxc Ping from triage - unfortunately this has sat idle for too long and I'm going to have to close this. 
Feel free to re-open when you get back to this.

**Pull request closed without merging**
