### PR TITLE
Generalize `contains` method on `SliceExt`

### PR DESCRIPTION
**Pull request by cjsut**
These commits modify the `contains` method(s) such that one can determine if a slice `&[T]` contains an element "equal" to some value of type `U` for any `T` and `U` that satisfy `T: PartialEq<U>`.  Specifically, the signature of `contains` is changed from

``` rust
fn contains(&self, &T) -> bool where T: PartialEq<T>
```

to

``` rust
fn contains<U>(&self, &U) -> bool where T: PartialEq<U>
```

A test function has been added to libcollectionstest under "slice.rs";  although the most "extensive" changes were in libcore, the use case described below (where `T` is `String` and `U` is `&str`) requires `std`.
### Motivation

Currently the `contains` method on slices supports only a slice's own item type as an argument;  this leads to confusion when the item type is semantically equivalent to another, as in the case of `String`/`&str`.

I have been asked twice in as many days --- by different people --- how to check for a certain string literal in a `Vec<String>` without allocating; the obvious method (`contains`) doesn't work and instead we resort to the less-than-ergonomic `my_vec.iter().any(|s| s == "my literal value")` instead of `my_vec.contains("my literal value")`.
### Misc

This is my first pull request, so I've probably done something wrong. :sweat_smile:  Let me know if you figure out what that is.
- All stage 1 tests pass, but it's not entirely clear to me whether or not the newly-added test was picked up by the build system; I assume CI will be able to do a properly-cleaned build quicker than I would.
- Intuition says this probably deserves a crater run, since it changes the signature of a highly-used function.

### CODE REVIEW

**Comment by ubsan** [comment]
This would be nice for

```rust
fn find(slice: &[String], s: &str) {
  if slice.contains(s) {
    println!("yay!");
  } else {
    println!("aww...");
  }
}
```

Note that this is a [breaking-change] due to inference.

**Comment by durka** [comment]
Like many breaking changes, this one could be avoided if default type parameter inference is ever approved.

**Comment by alexcrichton** [comment]
Thanks for the PR @insaneinside! The implementation and tests look good to me, and now we just need to decide whether to merge or not! It's true that I believe this is technically a breaking change, so we may not be able to get away with it.

I've scheduled a crater run, and if that comes back with lots of breakage it's almost sure we can't merge as-is. If it comes back clean, though, then we'll discuss at the next libs triage meeting if we feel crater is representative enough to merge.

cc @rust-lang/libs

**Comment by alexcrichton** [comment]
It looks like this unfortunately does [cause a number of regressions](https://gist.github.com/alexcrichton/9ae2cab3f5c4faf59a3fe7bba89f1a0c). Unless we have default type parameter fallback for inference, I'm not sure we can implement this just yet :(

**Comment by insaneinside** [comment]
Would you prefer I leave this PR open for that eventuality?  The changes are fairly trivial, and I have no preference either way.

**Comment by alexcrichton** [comment]
Discussed during triage yesterday the libs team decided to close due to the breakage. It was also pointed out that the language feature enabling this is still away out from happening, so it may be awhile before we get that :(

**Pull request closed without merging**
