### PR TITLE
test for parallel compiler by default

### PR DESCRIPTION
**Pull request by SparrowLii**
test for query cache perf
r? @ghost

### CODE REVIEW

**Comment by SparrowLii** [comment]
test again after #111713
@bors try @rust-timer queue

**Comment by SparrowLii** [comment]
@craterbot run

**Comment by lqd** [comment]
@craterbot run crates=https://crater-reports.s3.amazonaws.com/pr-115235/retry-regressed-list.txt p=1

This is going to be a short run, so p=1 should be acceptable for the short delay for the other PR in the queue.

**Comment by SparrowLii** [comment]
@craterbot run crates=https://crater-reports.s3.amazonaws.com/pr-115235-1/retry-regressed-list.txt

**Comment by petrochenkov** [comment]
@craterbot p=1

**Pull request closed without merging**
