### PR TITLE
syntax: use MetaPath (a simpler version of Path) for Attribute and MetaItem.

### PR DESCRIPTION
**Pull request by eddyb**
This is the simpler alternative to #56480, and has two advantages:
* doesn't introduce so many abstractions
* no more `{ast,hir}::PathSegment` in attribute paths
  * that could've contained generic arguments even if it never did for `use` and attributes

r? @petrochenkov cc @nikomatsakis

### CODE REVIEW

**Comment by petrochenkov** [comment]
Didn't have a chance to look at this in detail today, but I'm pretty skeptical about the idea in general.

With two kinds of paths there's now a chance to visit all paths, but forget attribute paths.
Macro paths have exactly the same properties and restrictions as attribute paths, but they still use `Path` and not `MetaPath`.
What is the ultimate motivation/goal? I suspect it's somehow related to https://github.com/rust-lang/rust/pull/56511?

**Comment by eddyb** [comment]
> What is the ultimate motivation/goal?

The description for #56480 covers that a bit. The problem is we have `ast::Path` in `ast::Attribute` but we use `ast::Attribute` in the HIR (and therefore have the risk of AST fragments in HIR).
For my purposes, a newtype of `ast::Path` that `Deref`s to `ast::Path`, but can only be created from a path with no generic arguments, would probably be enough, I think.

> With two kinds of paths there's now a chance to visit/fold all paths, but forget attribute paths accidentally.

This is already an issue, e.g. `MetaItem`'s path wasn't being folded.

**Comment by petrochenkov** [comment]
r=me for the first two commits, see https://github.com/rust-lang/rust/pull/56480 for the third one.

**Comment by eddyb** [comment]
@petrochenkov What do you think of the newtype of `ast::Path` instead of introducing a new `struct`? It would make most of the changes in the third commit go away and still work for me.

**Comment by petrochenkov** [comment]
@eddyb 
>What do you think of the newtype of ast::Path instead of introducing a new struct? It would make most of the changes in the third commit go away and still work for me.

Seems ok.
I'm still interested why having AST pieces in HIR is a problem (https://github.com/rust-lang/rust/pull/56480#issuecomment-444667705) and why you can't `bug!()` on generic arguments (https://github.com/rust-lang/rust/pull/56480#issuecomment-444666685).

**Comment by eddyb** [comment]
@petrochenkov Just customize `ast::Path`'s non-serde encoding? I guess it's okay, it just needs to come with a caveat to never use it with generic arguments.
And I'd still need to parser change from the third commit of this PR, to strip off generic arguments when emitting an error that they're not supported, to avoid anything falling apart later on in the compilation.

**Comment by Aaronepower** [comment]
Triage; @eddyb Hello, have you been able to get back to this PR?

**Comment by TimNN** [comment]
Ping from triage @eddyb: What is the status of this PR?

**Comment by Dylan-DPC** [comment]
ping from triage @eddyb Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Pull request closed without merging**
