### PR TITLE
Stabilize bench_black_box

### PR DESCRIPTION
**Pull request by Urgau**
This PR stabilize `feature(bench_black_box)`.

```rust
pub fn black_box<T>(dummy: T) -> T;
```

The FCP was completed in https://github.com/rust-lang/rust/issues/64102.

@rustbot label +T-libs-api -T-libs

### CODE REVIEW

**Comment by fee1-dead** [comment]
@bors r-:

Failed in a rollup, per https://github.com/rust-lang/rust/pull/102358#discussion_r981350786.

**Comment by Urgau** [comment]
Fixed by applying the patch from `@cuviper` in https://github.com/rust-lang/rust/pull/102358#discussion_r981350786.

**Pull request merged**
