### PR TITLE
[EXPERIMENT] int to decimal conversion

### PR DESCRIPTION
**Pull request by ChrisDenton**
First, lets try simplifying int to decimal a very tiny bit. I kind of suspect this will have zero effect on perf or binary size, at least on x64. We already specialize 128-bit integers and LLVM can see enough to optimize this for us.

r? @ghost

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Oops. Let's try that again.

@bors try

**Comment by ChrisDenton** [comment]
@rust-timer queue

**Comment by lqd** [comment]
(@ChrisDenton "queue" is "wait for a try build to complete", e.g. when you're requesting the try build and perf run at the same time. Here you already have a try build, there won't be another one to wait for)

@rust-timer build 51995308bc954a83694ca56be1c7cd67af48f440

**Comment by ChrisDenton** [comment]
Ah, thanks!

**Comment by ChrisDenton** [comment]
Hm, ok lets see what happens if we just have a very naive implementation. I would expect this to have a bigger impact on performance but maybe the rest of the format infrastructure being slow will limit that impact. It may also reduce binary size but the difference here may be too small to notice.

**Comment by Nilstrieb** [comment]
i dont think rustc formats a lot of integers

**Comment by ChrisDenton** [comment]
Yes, there ended up being one runtime test that tests printing `u8`s in a loop but otherwise there isn't much to exercise this code.

**Comment by Nilstrieb** [comment]
ah, a runtime benchmark ,very neat

**Pull request closed without merging**
