### PR TITLE
Deprecate #![crate_type] and #![crate_name]

### PR DESCRIPTION
**Pull request by bjorn3**
`#![crate_type]` is implemented using a `OnceCell` in the `Session` to allow for setting it after the main source file has already been parsed. This is rather ugly IMO and makes it easy to attempt to access it before it has been set.

`#![crate_name]` is implemented by threading the determined crate name everywhere after the crate has been parsed up till the moment the `TyCtxt` is created, at which point the `crate_name` stored in `TyCtxt` is used. A local patch which used the same technique as `#![crate_type]` resulted in "17 files changed, 72 insertions(+), 127 deletions(-)".

Both `#![crate_type]` and `#![crate_name]` are useless when using Cargo as they must match the values passed in at the command line. Other build systems are unlikely to use either attribute too.

I propose that `#![crate_type]` and `#![crate_name]` will be deprecated and at a future date removed.

### CODE REVIEW

**Comment by bjorn3** [comment]
This has previously been discussed a bit in https://rust-lang.zulipchat.com/#narrow/stream/268952-edition-2021/topic/remove.20.23!.5Bcrate_type.5D

**Comment by jyn514** [comment]
These are used quite a lot for tests, and I also use them for testing rustdoc issues locally. It would be annoying to have to run with `--crate-name` each time I invoke rustdoc.

```
$ rg crate_type src/test/ | wc -l
986
$ rg crate_name src/test/ | wc -l
332
```

**Comment by nagisa** [comment]
This attribute is very extensively used in tests and similar one-off programs that are compiled with rustc directly. I know I type this attribute out at least once every week.

I would like to see what the impact of this change would be by running crater with this lint denied.

Perhaps MCP too, though I guess we can FCP this PR too.

**Comment by bjorn3** [comment]
As a middle ground could we keep `#![crate_type]` and deprecate `#![crate_name]`? Most of the time the crate name is correctly inferred from the file name if `--crate-name` isn't passed. The accesses of the crate type are more localized than the accesses of the crate name, so it is easier to ensure that the crate type is set before accessing it.

**Comment by jyn514** [comment]
Can you explain why you want to deprecate these? You've mentioned that the thread-locals feel hacky and that this is unhelpful when using cargo, but not everyone uses cargo and I don't think we should remove language features *just* because it cleans up the implementation.

**Comment by bjorn3** [comment]
It is not a thread local, but a field of the `Session` that is set after `Session` is already actively being used in case of the crate type. This means that you have to be very careful to not request either property until they have been set on the `Session`. For example you can't use it from the `config` callback of `rustc_interface` at all. The crate name is currently manually passed around everywhere until `TyCtxt` which is anoying, but with a local patch it would become a field just like the crate type, which requires the same careful handling as for the crate type.

**Comment by jyn514** [comment]
I marked this as needs-fcp because I think the lang team should weigh in on deprecating any language features.

**Comment by joshtriplett** [comment]
Personally, I would love to see these deprecated, in favor of the command-line options. The command-line options don't require Cargo, they just require passing the values into `rustc` from whatever is invoking `rustc`. (Test cases could always store this information in a specially formatted comment, similar to what the Rust testsuite does.)

However, these attributes are part of the language, and while we could consider deprecating them, I don't think we can reasonably *remove* them except as part of an edition boundary.

@bjorn3 Would any of the potential simplifications you're describing be possible if we need to retain compatibility with previous editions that support these attributes indefinitely? (For instance, assume that cosmetic issues such as messages were not a problem, and we only had to produce a compatible compiled crate.)

If there's still substantial improvement available even given that constraint, I think this might be worth considering. If there isn't, then I don't think this would be worth the churn it would introduce.

**Comment by bjorn3** [comment]
> Would any of the potential simplifications you're describing be possible if we need to retain compatibility with previous editions that support these attributes indefinitely?

No, unfortunately not. Keeping the attributes, requiring them to be equal to the default value when no commandline argument is passed instead of only requiring a match when the commandline arguments are passed would allow for these simplifications though. In addition I wonder if gcc-rs could even support these attributes at all or whether the gcc driver requires to know of it needs to link in advance before invoking the language specific frontend. (cc @philberty)

**Comment by Havvy** [comment]
> if they choose to not support older editions

As per the definition and intent of editions, you're not a valid Rust compiler unless you actually do support older editions.

**Comment by philberty** [comment]
> > Would any of the potential simplifications you're describing be possible if we need to retain compatibility with previous editions that support these attributes indefinitely?
> 
> No, unfortunately not. Keeping the attributes, requiring them to be equal to the default value when no commandline argument is passed instead of only requiring a match when the commandline arguments are passed would allow for these simplifications though. In addition I wonder if gcc-rs could even support these attributes at all or whether the gcc driver requires to know of it needs to link in advance before invoking the language specific frontend. (cc @philberty) Removing on an edition boundary would help other backends if they choose to not support older editions.

Thanks, @bjorn3 for the heads up. I think there is a method to implement #![crate_name] (by overriding passed options) but no other FE in GCC does this and would likely just cause more problems than it solves. As for #![crate_type] I am currently unaware of any method to actually implement this in gcc-rs. @tschwinge or @dkm do you have any opinions on this?

**Comment by est31** [comment]
What about deprecating and removing cfg_attr-dependent `#[crate_type]`? Then it would become extremely easy to parse it very early on.

**Comment by philberty** [comment]
I personally think @est31 proposal of deprecating crate_type is a great move forward, this is a difficult thing for GCC Rust to support in a graceful way. Crate name is something that is much more easily implemented.

I would like to see this change moving forward in Rust.

**Comment by est31** [comment]
(To clarify, my proposal also extends to `#[crate_name]`. basically still support them but deprecate&remove `cfg_attr(something, crate_name = ...)` and `cfg_attr(something, crate_type = ...)`. This makes sure they can be parsed very early on, before all the cfg expansion logic is set up)

**Comment by joshtriplett** [comment]
The PR as originally proposed here isn't something we can merge; deprecating these would break existing code. And it sounds like even dropping these in an edition wouldn't help, even if that were something we wanted to do. So, I'm going to close this PR.

Proposals to make some other change in this area should likely be a separate PR, and would almost certainly need both an FCP and a crater run.

**Comment by bjorn3** [comment]
> What about deprecating and removing cfg_attr-dependent `#[crate_type]`? Then it would become extremely easy to parse it very early on.

Done in https://github.com/rust-lang/rust/pull/83744

**Pull request closed without merging**
