### PR TITLE
Fixed #48425 : Various functions taking a `TyCtxt` and a `Span` should be taking a `TyCtxtAt`

### LINKED ISSUE #48425: Various functions taking a `TyCtxt` and a `Span` should be taking a `TyCtxtAt`
One example is the `is_sized` method on `Ty`. Internally it creates a `tcx.at(span)`, when it could simply be taking exactly that `TyCtxtAt` as an argument. In miri I had to write `ty.is_sized(tcx.tcx, param_env, tcx.span)` which just feels a little riddiculous (taking apart the `TyCtxtAt`, just to have the method construct it back).

There's probably many other similar methods and functions that should be taking a `TyCtxtAt`

### PR DESCRIPTION
**Pull request by PramodBisht**
Hi @oli-obk 
I have done some code refactoring to fix #48425, Please let me know if anything else is required on this.

### CODE REVIEW

**Comment by PramodBisht** [comment]
Fixing conflicts.

**Comment by oli-obk** [comment]
r? @oli-obk

@nikomatsakis can you add me to the list of ppl who can give bors commands? I can't do that yet, even though I can be assigned as a reviewer

**Comment by oli-obk** [comment]
@PramodBisht please squash the commits into one. You can do that with `git rebase -i origin/master` and `git push --force-with-lease` afterwards. The code lgtm

r=me with commits squashed

**Comment by PramodBisht** [comment]
@oli-obk I am not able to `rebase` it because of `merge commits`, is there any other way around to deal with that. Let me know if I should `recommit` and raise PR from another branch.

**Comment by oli-obk** [comment]
Huh? Merge commits shouldn't matter. Can you paste the entire error?

**Comment by PramodBisht** [comment]
@oli-obk can you come on IRC, can we discuss there?

**Comment by PramodBisht** [comment]
@oli-obk right after running `git rebase -i origin/master`, I am getting this

```
error: could not apply 4882331... Fixed #48425

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply 4882331b3772958718986e4ecbf70eb34e3a2fb2... Fixed #48425
```
master is in sync with main `rust-lang/rust` master

**Comment by oli-obk** [comment]
Sorry I'm on vacation. This is perfectly normal. Just look through the changes, remove all the things you did not change, `git add` the final document and then run `git rebase --continue` if anything is out of order, change it and run `git commit --amend`

**Comment by nikomatsakis** [comment]
@oli-obk hmm. you ought to have them soon. =)

**Comment by PramodBisht** [comment]
@oli-obk All set, could please check again :)

**Comment by oli-obk** [comment]
Jup looks good now

@bors r+

**Pull request merged**
