### PR TITLE
Add support for targets without unwinding in `mir-opt`, and improve `--bless` for it

### PR DESCRIPTION
**Pull request by emilyalbini**
The main goal of this PR is to add support for targets without unwinding support in the `mir-opt` test suite, by adding the `EMIT_MIR_FOR_EACH_PANIC_STRATEGY` comment. Similarly to 32bit vs 64bit, when that comment is present, blessed output files will have the `.panic-unwind` or `.panic-abort` suffix, and the right one will be chosen depending on the target's panic strategy.

The `EMIT_MIR_FOR_EACH_PANIC_STRATEGY` comment replaced all the `ignore-wasm32` comments in the `mir-opt` test suite, as those comments were added due to `wasm32` being a target without unwinding support. The comment was also added on other tests that were only executed on x86 but were still panic strategy dependent.

The `mir-opt` suite was then blessed, which caused a ton of churn as most of the existing output files had to be renamed and (mostly) duplicated with the abort strategy.

---

After [asking on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/mir-opt.20tests.20and.20panic.3Dabort), the main concern about this change is it'd make blessing the `mir-opt` suite even harder, as you'd need to both bless it with an unwinding target and an aborting target. This exacerbated the current situation, where you'd need to bless it with a 32bit and a 64bit target already.

Because of that, this PR also makes significant enhancements to `--bless` for the `mir-opt` suite, where it will automatically bless the suite four times with different targets, while requiring minimal cross-compilation.

To handle the 32bit vs 64bit blessing, there is now an hardcoded list of target mapping between 32bit and 64bit. The goal of the list is to find a related target that will *probably* work without requiring additional cross-compilation toolchains on the system. If a mapping is found, bootstrap will bless the suite with both targets, otherwise just with the current target.

To handle the panic strategy blessing (abort vs unwind), I had to resort to what I call "synthetic targets". For each of the target we're blessing (so either the current one, or a 32bit and a 64bit depending on the previous paragraph), bootstrap will extract the JSON spec of the target and change it to include `"panic-strategy": "abort"`. It will then build the standard library with this synthetic target, and bless the `mir-opt` suite with it.

As a result of these changes, blessing the `mir-opt` suite will actually bless it two or four times with different targets, ensuring all possible variants are actually blessed.

---

This PR is best reviewed commit-by-commit.

r? @jyn514 
cc @saethlin @oli-obk

### CODE REVIEW

**Comment by pietroalbini** [comment]
Most of the diff here is blessing.

**Comment by saethlin** [comment]
> The `EMIT_MIR_FOR_EACH_PANIC_STRATEGY` comment replaced all the `ignore-wasm32` comments in the `mir-opt` test suite

Is that the right default? Should we always emit MIR for each panic strategy? Or emit MIR for each panic strategy if they are different?

**Comment by pietroalbini** [comment]
> Is that the right default? Should we always emit MIR for each panic strategy? Or emit MIR for each panic strategy if they are different?

Note that I didn't add `EMIT_MIR_FOR_EACH_PANIC_STRATEGY` unconditionally, just in the (large) subset of tests that were ignored on `wasm32` due to being broken due to aborting.

> Should we always emit MIR for each panic strategy?

If that's the direction you all want to go with I'm ok with changing the implementation. Around half of the tests right now have `EMIT_MIR_FOR_EACH_PANIC_STRATEGY`, so it'd still be a pretty large increase in the number of output files.

> Or emit MIR for each panic strategy if they are different?

This is a way more complex change than this PR unfortunately. This PR doesn't make any significant change to compiletest (other than using a suffix if the test is marked correctly), with all the unwind vs abort magic done by bootstrap invoking compiletest multiple times.

**Comment by saethlin** [comment]
It sounds like my suggestion is a great candidate for a follow-up PR, perhaps by me. Thanks!

**Comment by jyn514** [comment]
i don't have time for reviews right now, please don't assign me.

r? @saethlin, but feel free to `r? bootstrap` if you're not comfortable reviewing

**Comment by saethlin** [comment]
I've read over this and it looks mostly fine to me? In terms of improving the mir-opt test suite this is a good step forward, and it looks to me like an improvement in usability.

But the majority of this is changes to bootstrap, which I don't think I can really have an informed opinion on.

r? bootstrap

**Comment by ozkanonur** [comment]
I will do the review within the next couple of days.

**Review by onur-ozkan — APPROVED** [review]
Bootstrap changes looks good to me.

**Comment by pietroalbini** [comment]
Rebased to fix the merge conflict.

@bors r=ozkanonur,saethlin rollup=iffy

**Comment by lqd** [comment]
This PR doesn't change the compiler, and the perf changes are the opposite of https://github.com/rust-lang/rust/pull/112400#issuecomment-1591618283's noise basically returning to steady state.

@rustbot label: +perf-regression-triaged

**Pull request merged**
