### PR TITLE
bootstrap: --verbose now prints env variables

### PR DESCRIPTION
**Pull request by pnkfelix**
In `--verbose` mode, print env variables established by cargo spawned processes.

### CODE REVIEW

**Comment by nagisa** [comment]
You can achieve this with `--on-fail=env` already. You can also launch a shell with environment in place with `--on-fail=bash` or whatever else you prefer.

**Comment by pnkfelix** [comment]
@nagisa I'll admit, I was ignorant of `--on-fail` 

But ... won't that supply the information only if the invocation actually fails?

(Invocation failure is not necessarily the only scenario when one would want to extract the info necessary to recreate the environment that rustbuild is setting up... though it is certainly is the obvious case...)

**Comment by alexcrichton** [comment]
@pnkfelix looks good to me, thanks! There's a whole bunch of calls to `Command::env` scattered throughout I think, would you like to add a function to `Build` to do this and transition all those calls to using the `Build` function? (or maybe a wrapper struct?)

I'm fine either way, just curious what you think.

**Comment by pnkfelix** [comment]
@alexcrichton hmm, you're right. I'll look into that.

**Comment by alexcrichton** [comment]
Ok I'll close this in the meantime, but I certainly don't mind still adding this! Just lemme know what your investigation reveals.

**Pull request closed without merging**
