### PR TITLE
Make the arena fast path smaller

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build b40fd9ad1c114049c0ef02dd1a36e93788ec0482

**Comment by michaelwoerister** [comment]
The perf-results mostly look like noise (except for `ctfe-stress`). I'm not sure this is worth the more complicated implementation.

cc @rust-lang/wg-compiler-performance

**Comment by Zoxc** [comment]
The results doesn't look like noise though. The whole point of the arena is performance. We should just use `malloc` otherwise =P

**Comment by Zoxc** [comment]
This is also a nice size optimization. It brings the fast path for allocating an `usize` from:
```
.text:0000000180001235                 mov     rsi, rcx
.text:0000000180001238                 mov     rax, [rcx]
.text:000000018000123B                 mov     rcx, [rcx+8]
.text:000000018000123F                 add     rax, 7
.text:0000000180001243                 and     rax, 0FFFFFFFFFFFFFFF8h
.text:0000000180001247                 mov     [rsi], rax
.text:000000018000124A                 cmp     rcx, rax
.text:000000018000124D                 jb      short loc_180001281
.text:000000018000124F                 mov     rdx, rax
.text:0000000180001252                 add     rdx, 8
.text:0000000180001256                 cmp     rdx, rcx
.text:0000000180001259                 jnb     short loc_18000126B
.text:000000018000125B
.text:000000018000125B loc_18000125B:                          ; CODE XREF: alloctest+4F↓j
.text:000000018000125B                 mov     [rsi], rdx
...
.text:000000018000126B ; ---------------------------------------------------------------------------
.text:000000018000126B
.text:000000018000126B loc_18000126B:                          ; CODE XREF: alloctest+29↑j
.text:000000018000126B                 mov     edx, 8
.text:0000000180001270                 mov     rcx, rsi
.text:0000000180001273                 call    _ZN5arena13DroplessArena4grow17h2cc6dfe0f3889a5eE ; arena::DroplessArena::grow::h2cc6dfe0f3889a5e
.text:0000000180001278                 mov     rax, [rsi]
.text:000000018000127B                 lea     rdx, [rax+8]
.text:000000018000127F                 jmp     short loc_18000125B
.text:0000000180001281 ; ---------------------------------------------------------------------------
.text:0000000180001281
.text:0000000180001281 loc_180001281:                          ; CODE XREF: alloctest+1D↑j
.text:0000000180001281                 lea     rcx, aAssertionFaile ; "assertion failed: self.ptr <= self.end"
.text:0000000180001288                 lea     r8, off_180003230
.text:000000018000128F                 mov     edx, 26h
.text:0000000180001294                 call    _ZN3std9panicking11begin_panic17hca0ac606c2739ec6E ; std::panicking::begin_panic::hca0ac606c2739ec6
.text:0000000180001299 ; ---------------------------------------------------------------------------
.text:0000000180001299                 ud2
.text:0000000180001299 alloctest       endp
```
to:
```
mov     rax, [rcx]
lea     rdx, [rax+8]
cmp     rdx, [rcx+8]
jnb     short slow_path
continue:
...
slow_path:
mov     edx, 8
call    _ZN5arena13DroplessArena18grow_and_alloc_raw17ha43c166c6d43e92fE
jmp continue
```

**Comment by michaelwoerister** [comment]
I can see the first change making sense but why change from `u8` to `usize` for the drop-less arena?

**Comment by Zoxc** [comment]
@michaelwoerister It avoids the instructions realigning the bump pointer by keeping it always `usize` aligned.

**Comment by Zoxc** [comment]
Might make the `DroplessArena` generic over the backing type, so we could use `u8` in the string interner. I think all other allocations are `usize` aligned.

**Comment by michaelwoerister** [comment]
I'm still not convinced that there are performance gains here. Compare this to a perf.rlo run from a few days ago where I accidentally benchmarked to equivalent versions of the compiler (so we know what we see is noise):
https://perf.rust-lang.org/compare.html?start=10e2c729ea2e85cb1e2a08be40564492f49e45ec&end=5280d23d48ea46ca2469a77cc240fbef6767efbb

Except for `ctfe-stress` it looks the same to me.

**Pull request closed without merging**
