### PR TITLE
Move tests from `test/run-fail` to UI

### LINKED ISSUE #65440: Cleanup: Move src/test/run-fail to src/test/ui
We have a small amount of tests in `src/test/run-fail`; these should be moved over to various directories in `src/test/ui` depending on what the test is about. (See https://github.com/rust-lang/rust/pull/65438#issuecomment-542245950 for one example of moving run-fail/ tests to ui/.) When moving each test in `src/test/run-fail` you have to add `// run-fail` to the top of each file.

cc @varkor 

This issue has been assigned to @nvlbg via [this comment](https://github.com/rust-lang/rust/issues/65440#issuecomment-542319420).

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #65440
cc #65865 #65506
r? @nikomatsakis

### CODE REVIEW

**Comment by petrochenkov** [comment]
If we are doing this, https://github.com/rust-lang/rust/issues/65865 needs to be prioritized and implemented soon, IMO.

**Comment by nikomatsakis** [comment]
I'm in favor of unifying these tests, but I think this qualifies as a "major change".

@JohnTitor could you [file a 'major change proposal'](https://github.com/rust-lang/compiler-team/issues/new?assignees=&labels=major-change&template=major_change.md&title=%28My+major+change+proposal%29)? A short write-up would suffice of what the plans are -- just a paragraph or so should be fine.

Some things to include I think:

* Does this remove all uses of run-fail? 
* How will #65865 get resolved?
* Any other lingering bits of work?

**Comment by JohnTitor** [comment]
Sure thing, opened https://github.com/rust-lang/compiler-team/issues/274.

**Comment by petrochenkov** [comment]
Ok, the RFC says
>To be announced at a triage meeting and go through final comment period (a 1 week wait to give people time).

so apparently I can just r+ this now?
It's not clear whether it was "announced at a triage meeting" or not, and what date the time is counting from.

**Comment by petrochenkov** [comment]
r=me after rebase.

**Comment by JohnTitor** [comment]
Rebased. Also removed two tests since they were removed by #70175.

**Comment by JohnTitor** [comment]
Ouch, needs to skip some env, one sec..

**Comment by JohnTitor** [comment]
Should be fixed.
@bors r=petrochenkov

**Comment by JohnTitor** [comment]
This error occurs on some other PRs so should be spurious.
@bors retry

**Pull request merged**
