### PR TITLE
Update Cargo submodule

### PR DESCRIPTION
**Pull request by alexcrichton**
Contains a fix for rust-lang/cargo#4081

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+

@alexcrichton Should this get a higher priority, or fix isn't urgent?

**Comment by alexcrichton** [comment]
Sort of up in the air, but a rollup is fine

**Comment by Mark-Simulacrum** [comment]
@bors r-

This fails Travis, I think Cargo.lock needs updating.

**Pull request merged**
