### PR TITLE
Removes suggestions for misspelled private fields for structs defined in non-local crates

### LINKED ISSUE #22421: Field spelling correction suggests private fields
```rust
fn main() {
    let x: Vec<()> = vec![];
    x.pttr;
}
```

```
foo.rs:3:5: 3:11 error: attempted access of field `pttr` on type `collections::vec::Vec<()>`, but no field with that name was found  
foo.rs:3     x.pttr;
             ^~~~~~
foo.rs:3:7: 3:11 help: did you mean `ptr`?
foo.rs:3     x.pttr;  
               ^~~~
```

### PR DESCRIPTION
**Pull request by leejunseok**
closes #22421

### CODE REVIEW

**Comment by jakub-** [comment]
@leejunseok Looking good, thank you!

Could you please also add a test for the new behaviour? It's not hard to do! You'll need to create an auxiliary `compile-fail` test:

```rust
// aux-build:struct-field-privacy.rs

extern crate struct-field-privacy;

use struct-field-privacy::A;

fn main () {
    // ...
}
```

[struct-field-privacy.rs](https://github.com/rust-lang/rust/blob/b7930d93d9b57beaeabfeb43cf78fc8161ecd46c/src/test/auxiliary/struct-field-privacy.rs) will then act as your external create. [struct-field-hints.rs](https://github.com/rust-lang/rust/blob/b7930d93d9b57beaeabfeb43cf78fc8161ecd46c/src/test/compile-fail/struct-fields-hints.rs) is an example of how you can assert what field hints the compiler should provide.

**Comment by leejunseok** [comment]
Er, it looks like the dashes in struct-field-privacy trips everything up. Is there another external crate I could use instead?

**Comment by leejunseok** [comment]
Oops, just kidding, doing extern crate `"struct-field-privacy" as xc;` seems to work.

**Comment by jakub-** [comment]
@leejunseok My bad, you'll need a license header for the test as well! With that r=me. :)

**Comment by leejunseok** [comment]
Haha, thank you for your help. I'm relatively new to rust and I appreciate the friendly guidance!

**Comment by jakub-** [comment]
@leejunseok No probs! Thanks again. :)

**Comment by Manishearth** [comment]
The failure above was intentional; this PR is part of the rollup so it's redundant to test it individually (and given the state of the queue, rather wasteful). If the rollup doesn't go through in a couple of tries, ask for a retry on this :smile: 

Sorry for the trouble!

**Pull request merged**
