### PR TITLE
Rustdoc fixes for associated items

### PR DESCRIPTION
**Pull request by bluss**
Rustdoc fixes for associated items

This is related to isssue #22442 and solves it partly.

This solves the search index links of associated types and constants,
so that they link to the trait page.

Also add an Associated Constants section if constants are present.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you add a test for the emission of the associated constants section? Regardless, though, thanks!

**Comment by bluss** [comment]
Do you know how I can run the src/test/rustdoc tests? Without a full `make check`. For other categories I can `make check-rpass`  and so on.

**Comment by bluss** [comment]
I found `make check-stage2-rustdocck`

Updated the tests -- is that sufficient, it just checks for something with the right id= tag?

**Comment by alexcrichton** [comment]
Yeah that looks good to me, thanks!

@bors: r+ c46f3ff12b0a0b9c55df89eeb92603e9e488b2a7

**Pull request merged**
