### PR TITLE
Inline some functions that show up in perf runs

### PR DESCRIPTION
**Pull request by oli-obk**
r? @ghost

trying to address the perf regression from https://github.com/rust-lang/rust/pull/104533#issuecomment-1322936011

### CODE REVIEW

**Comment by Kobzol** [comment]
I would hope that these kinds of `#[inline]` changes won't do anything, now that we use LTO.

**Comment by oli-obk** [comment]
Well... I have really hard time telling where the actual regression is, so I was hoping to change inlining behaviour enough to not have random llvm decisions drown out what I'm looking for

**Comment by oli-obk** [comment]
All of the regressions have been improved above and beyond the regression by unrelated changes. I'm not sure how to continue hunting down these regressions, from the cachegrind traces they mostly look like inlining noise

**Pull request closed without merging**
