### PR TITLE
Optimize `BitIter`

### PR DESCRIPTION
**Pull request by nnethercote**
A minor speed improvement.

### CODE REVIEW

**Comment by nnethercote** [comment]
I added another commit, one that benefits from the faster `BitIter`. But I didn't see the r+ before that happened. I have now removed the additional commit; I will do it in a different PR.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/65430#issuecomment-542164968, @bors r-

**Comment by nnethercote** [comment]
I mistakenly thought it was ok for unsigned integers to wrap with `+`. `wrapping_add` fixes the problem.

@bors r=zackmdavis

**Pull request merged**
