### PR TITLE
Avoid infinite recursion on error case in `get_path_res`.

### LINKED ISSUE #101505: regression: hang with -Zsave-analysis
### Code

I tried this code:

```rust
fn next_letter_position(&self, x_index: f32, y_index: f32, width: f32) -> (f32, f32) {
    let vwidth = &self.viewport.x / 2.0;

    match x_index * width {
        0.0 ... vwidth => {
            (x_index + 1.0, y_index)
        },
        _ => (0.0, y_index - 1.0)
    }
}
```

with rustc `rustc 1.65.0-nightly (c07a8b4e0 2022-08-26)` this runs in a couple ms:
`rustc ./a.rs  --crate-type=lib  -Zsave-analysis  -Ztime=yes -Ztime-passes=yes`

with rustc `rustc 1.65.0-nightly (3c7278846 2022-09-06)` this seems to hang somewhere in `save-analysis`

````
  26,77%  librustc_driver-0f3b2583c1b011ce.so  [.] <rustc_middle::hir::map::Map>::get
  24,00%  librustc_driver-0f3b2583c1b011ce.so  [.] <rustc_middle::hir::map::Map>::get_parent_node
   5,76%  librustc_driver-0f3b2583c1b011ce.so  [.] <rustc_save_analysis::SaveContext>::get_path_res
````
( I killed the process after waiting for 5 minutes :upside_down_face: )

### PR DESCRIPTION
**Pull request by nnethercote**
Fixes #101505.

r? @petrochenkov

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Could we move this forward somehow?
The bug prevents the my rust ice-discovery tooling from running properly :sweat:

**Comment by petrochenkov** [comment]
@nnethercote 
>Is it an underlying bug that `get_parent_node` can return the same node it is given?

Likely yes.
Maybe the fresh HIR IDs created in https://github.com/rust-lang/rust/pull/101228 do not setup their parenting relations correctly.
r? @cjgillot

**Comment by cjgillot** [comment]
Thanks for the ping.  I took the opportunity to add a sanity check to HIR indexing to detect this sort of bug earlier in https://github.com/rust-lang/rust/pull/101688.

**Comment by nnethercote** [comment]
Fixed in a better way by #101688.

**Pull request closed without merging**
