### PR TITLE
[WIP] rustc_metadata: Switch `each_child_of_item` from callback to iterator

### PR DESCRIPTION
**Pull request by petrochenkov**
to avoid allocations.

### CODE REVIEW

**Comment by petrochenkov** [comment]
WTF 😂 
Is rustc+LLVM really that bad at inlining a few layers of iterators? Or is it `chain` to blame?

Anyway, this is waiting on https://github.com/rust-lang/rust/pull/92245, https://github.com/rust-lang/rust/pull/92153, https://github.com/rust-lang/rust/pull/92086, https://github.com/rust-lang/rust/pull/92034, and https://github.com/rust-lang/rust/pull/91795.
I'll re-measure once those PRs are merged or closed.

**Comment by mati865** [comment]
> Is rustc+LLVM really that bad at inlining a few layers of iterators? Or is it `chain` to blame?


I've seen edge cases when `chain(..)` performs terrible but usually it's more about the iterators or their content. One of extreme examples: https://rust.godbolt.org/z/Paf5ofnrq

**Comment by jackh726** [comment]
Let me know when this is ready for review.

**Comment by petrochenkov** [comment]
Looks like it's still not an improvement.

**Pull request closed without merging**
