### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #46938, #47334, #47420, #47508, #47510, #47512, #47535, #47559
- Failed merges:

### CODE REVIEW

**Comment by estebank** [comment]
https://travis-ci.org/rust-lang/rust/jobs/330886192#L7274 👀
```
[01:33:13] test cargo_fail_with_no_stderr has been running for over 60 seconds
```

**Comment by GuillaumeGomez** [comment]
Let's retry I suppose...

@bors: retry

**Comment by estebank** [comment]
same error

@bors retry

**Comment by alexcrichton** [comment]
@bors: r-

this is a legitimate error:

```
$ echo -n foo > foo.rs
$ ./bin/rustc foo.rs
# hangs forever
```

**Comment by GuillaumeGomez** [comment]
Then I close this PR.

**Pull request closed without merging**
