### PR TITLE
rustc: Add the `cmpxchg16b` target feature on x86/x86_64

### PR DESCRIPTION
**Pull request by alexcrichton**
This appears to be called `cx16` in LLVM and a few other locations, but
the Intel Intrinsic Guide doesn't have a name for this and the CPU
manual from Intel only mentions `cmpxchg16b`, so that's the name chosen
here.

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @gnzlbg

**Comment by gnzlbg** [comment]
r? me

**Review by gnzlbg — APPROVED** [review]
LGTM, i couldn't find another name for these.

**Pull request merged**
