### PR TITLE
Attempt to fix appveyor

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This will fix the problem, I think, but I don't know that this is a good idea (potentially leaving ourselves open to attackers, I guess, if a cert was revoked...). Of course, it may not. I don't actually have windows to check on..

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
AFAIK revocation is on by default for Windows but not elsewhere, see https://github.com/rust-lang/cargo/pull/3699

Can you add a comment to this? Otherwise r=me

**Comment by Mark-Simulacrum** [comment]
hm... So I get the following locally (sorry for screenshot, not sure how to hook clipboard to VM). Not sure what to do here...

image

**Pull request merged**
