### PR TITLE
Use quiet tests by default

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb

### CODE REVIEW

**Review by Mark-Simulacrum — CHANGES_REQUESTED** [review]
We'll want to change https://github.com/rust-lang/rust/blob/master/src/ci/run.sh#L31 such that the condition is inverted and it passes disable-quiet-tests. We can probably unconditionally enable step timings if that makes the code easier.

(This is because otherwise diagnosing which test failed or "timed out" is near-impossible).

**Comment by oli-obk** [comment]
I decided that `disable-quiet-tests` was too negative and in the spirit of positivism we now have `enable-verbose-tests`

**Comment by pietroalbini** [comment]
Ping from triage @eddyb! This PR needs your review.

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
