### PR TITLE
Consider return type when giving various method suggestions

### PR DESCRIPTION
**Pull request by compiler-errors**
1. Fix a bug in method probe where we weren't normalizing `xform_ret_ty` for non-`impl` method candidates. This shouldn't affect happy-path code, since we only use `xform_ret_ty` when probing methods for diagnostics (I think).
2. Pass the return type expectation down to `lookup_probe`/`probe_for_name` usages in diagnostics. Added a few UI tests to gate against bad suggestions.
3. Make a `FnCtxt::lookup_probe_for_diagnostic` which properly passes down `IsSuggestion(true)`. Should help suppress other weird notes in some corner cases.

### CODE REVIEW

**Review by estebank — APPROVED** [review]
I'm really surprised by the perf results (although they are quite localized).

**Comment by compiler-errors** [comment]
Tempted to believe that it's 1f92d5cca52572b08556620ba339365f485166bb causing the problem. Gonna try an experiment...

**Comment by compiler-errors** [comment]
Interestingly, due to 1f92d5c, this code also now compiles successfully:

```rust
use std::ops::Deref;

trait Foo {
    fn foo(&self) -> &Self::Target where Self: Deref { &**self }
}

trait Bar {
    fn foo(&self) {}
}

fn test(i: impl Foo + Bar) {
    i.foo();
}
```

... becuase we now unconditionally normalize the `xform_ret_ty`, *not only* for impl candidates, but for trait and param method probe candidates as well.

**Comment by compiler-errors** [comment]
This should revert that behavior, which is a bit disappointing IMO, but should help with the perf regression..?

@bors try @rust-timer queue

**Comment by oli-obk** [comment]
r=me after a rebase.

I recently dug around in this code and am very happy about the new `_for_diagnostics` function.

**Pull request merged**
