### PR TITLE
update stdarch

### PR DESCRIPTION
**Pull request by yanns**
This will allow using miri on simd instructions
https://github.com/rust-lang/stdarch/issues/1347#issuecomment-1353664361

### CODE REVIEW

**Comment by Amanieu** [comment]
cc @calebzulawski Any idea why this is failing? I would have thought your PR #103750 makes this work.

**Comment by calebzulawski** [comment]
It looks like std is built with the beta compiler, which doesn't have those changes yet

**Comment by Amanieu** [comment]
The beta compiler should have been updated just last week though, so I would expect it to include these changes.

**Comment by calebzulawski** [comment]
The log shows downloading the beta compiler from Nov 1, that sounds like 1.66 rather than 1.67

**Comment by Amanieu** [comment]
Blocked on #105741.

**Comment by Amanieu** [comment]
#105741 is now merged, can you rebase?

**Comment by yanns** [comment]
@Amanieu Do you have an idea why it is failing? Can I help somehow?

**Comment by calebzulawski** [comment]
Those errors are due to changes from #100752.  Some feature names have been deprecated in the `is_x86_feature_detected` macro.  I added `allow(deprecated)` to the tests that use the old names, though...

**Comment by calebzulawski** [comment]
Ah actually, as part of this update, this file needs to change too: https://github.com/rust-lang/rust/blame/master/library/std/tests/run-time-detect.rs#L123.  `avx512gfni`, `avx512vaes`, and `avx512vpclmulqdq` should all have the `avx512` prefix removed.

**Comment by yanns** [comment]
@calebzulawski thanks for the help. The CI checks are now passing.

**Pull request merged**
