### PR TITLE
Make `InferCtxt::can_eq` and `InferCtxt::can_sub` return booleans

### PR DESCRIPTION
**Pull request by compiler-errors**
Nobody matches on the result, nor does the result return anything useful...

### CODE REVIEW

**Comment by compiler-errors** [comment]
After #107940 lands, this these functions should additionally use `TyCtxt::check_tys_might_be_eq` when the new solver is enabled, to check for *deep* type equality

**Comment by BoxyUwU** [comment]
I feel like `if !self.infcx.can_eq(a, b) {` is less clear than `if self.infcx.can_eq(a, b).is_err()`. Could we just make the return type `Result<(), ()>`. if we start handling nested obligations we wont be able to always return a `TypeError` anyway so getting rid of it would have to happen

**Comment by compiler-errors** [comment]
The answer to a "can" question being a boolean makes pretty good sense to me, and `!self.can_do_thing()` is pretty clearly "can't do thing". 

We also have `FnCtxt::can_coerce` which has a handful of `!self.can_coerce` calls around the codebase already.

**Comment by lcnr** [comment]
Ignoring for a moment that `can_eq` is kinda bad as a whole because it ignores nested obligations causing stuff lazy norm to end up changing behavior I am in favor of this change.

Definitely in favor of yeeting `TypeError` from `can_eq` because I can't think of a case where you should use that `TypeError` to actually do anything :sweat_smile:

wrt `TyCtxt::check_tys_might_be_eq` and lazy norm I don't yet have an opinion. I slightly prefer returning `bool` over result here.

**Pull request merged**
