### PR TITLE
collections: use Unique in btree::Node

### PR DESCRIPTION
**Pull request by seanmonstar**
Adds back Send and Sync to BTreeMap and Set.

### CODE REVIEW

**Comment by pnkfelix** [comment]
@Gankro I've been experimenting with having `NonZero::new` actually `debug_assert` that the input it is given is not-zero.

This PR may be one cause of that assert breaking -- in particular, it is passing in `ptr::null_mut::<u8>` as the input for the `Unique` in `edges`

Any suggestions of whether and how we should address this violation of the requirements of `NonZero<T>` (and thus, transitively, `Unique<T>`)?

**Comment by pnkfelix** [comment]
(one obvious option is to use a non-null sentinel pointer instead of null...)

**Comment by Gankro** [comment]
@pnkfelix that's what heap::EMPTY is for, no?

**Comment by pnkfelix** [comment]
@Gankro that's one example of a non-null sentinel pointer.  (Not sure how wise it would be to use it for this particular purpose, but I don't see anything immediately wrong with it.)

But I more meant: Should we consider using an `Option<Unique<K>>` for the `keys` and use `None` instead of `null`.  (I misspoke up above when I said it was `edges` that was being initialized with `null`.)  If I understand correctly, based on the use of `NonZero` within `Unique`, the `Option<Unique<K>>` will still be one word in size, right?

**Comment by pnkfelix** [comment]
Hmm, I suppose a problem with using `Option` in the natural way is that it will insert a bunch of calls to `unwrap()` that will then insert overhead in the form of null checks and associated never-invoked unwinding panic code...

Well I'll try to compare and contrast.  I'd rather do either of these two options than stick with the status quo.

**Comment by Gankro** [comment]
@pnkfelix keep in mind that it's being rewritten: https://github.com/gereeter/btree-rewrite

**Pull request merged**
