### PR TITLE
Use CLOCK_MONOTONIC_RAW for Instant when available

### LINKED ISSUE #37902: time.rs should consider using CLOCK_MONOTONIC_RAW instead of CLOCK_MONOTONIC on Linux
I have reproducible compiler crashes on arm64:
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'other was less than the current instant', /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/sys/unix/time.rs:276
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm not really sure where that behavior originates but I suspect the rather old Kernel in combination with the (obscure) hardware I'm running. https://github.com/longsleep/linux-pine64/issues/44 has some more details, basically I see CLOCK_MONOTONIC jumping backwards from time to time. Looking somehow further I see other people used to have the same issue (http://stackoverflow.com/questions/3657289/linux-clock-gettimeclock-monotonic-strange-non-monotonic-behavior) 

My Linux Kernel docs say:
```
       CLOCK_MONOTONIC
              Clock that cannot be set and represents monotonic time since some unspecified starting point.  This clock is not affected by
              discontinuous jumps in the system time (e.g., if the system administrator manually changes the clock), but  is  affected  by
              the incremental adjustments performed by adjtime(3) and NTP.

       CLOCK_MONOTONIC_RAW (since Linux 2.6.28; Linux-specific)
              Similar  to  CLOCK_MONOTONIC, but provides access to a raw hardware-based time that is not subject to NTP adjustments or the
              incremental adjustments performed by adjtime(3).
``` 

I see this behavior even without OpenNTPd running (so I still suspect that there is a Kernel/HW-Issue), but it might be better to use the Linux specific RAW version of the monotonic clock in order to get strict monotonic increasing values. 

I just saw #37137 but as this is on real hardware that might be more relevant. Even when I'm not running anything that obviously does clock adjustments I see this behavior, RAW seems to be very consistently monotonically increasing. As rust is the only thing that I saw complaining so far you maybe want to consider changing this call.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #37902

r? @alexcrichton

### CODE REVIEW

**Comment by nagisa** [comment]
I find it dubious to work around a bug in an ancient version of the kernel by using MONOTONIC_RAW.

**Comment by sfackler** [comment]
CLOCK_MONOTONIC_RAW is a more appropriate clock for `Instant` regardless since it isn't affected by NTP adjustments.

**Comment by Amanieu** [comment]
@sfackler See my [comment](https://github.com/rust-lang/rust/issues/37902#issuecomment-261859649) in #37902. We actually *do* want to take NTP adjustments into account since we want our clock to stay in sync with real time (1 second on clock = 1 real second).

**Comment by alexcrichton** [comment]
Some thoughts of mine:

* We've seen https://github.com/rust-lang/rust/issues/37902 at least two times now (https://github.com/rust-lang/rust/issues/37137 as well). It's unfortunate that these programs panic-by-default.
* To be clear, it seems like this is a kernel bug and not a bug in the standard library. That is, it looks like `CLOCK_MONOTONIC` is violating what it's documented as doing.

So in light of that I like this approach as it works around buggy kernels in what appear to be somewhat common circumstances. In that sense I think the only question is for systems which have non-buggy versions of both clocks whether we use the raw versions or not (basically @Amanieu's question). I would tend to agree that `CLOCK_MONOTONIC` seems like the most accurate here in terms of what we'd like to have, although I believe the documentation for `Instant` would allow both. 

Is it possible for us to isolate these buggy kernels? Can they somehow be detected? Do we know for sure that it was a buggy kernel and can track down versions? If we can do that then we could perhaps use the raw clock only on these buggy kernels.

**Comment by Amanieu** [comment]
We could detect buggy kernels by caching the last value returned by `clock_gettime(CLOCK_MONOTONIC)` and checking if a newly return value is earlier than the cached value. However this has performance implications since you would need a mutex to serialize calls to `clock_gettime`, which may not be desirable since this functionality is often used for fine-grained timing (e.g. benchmarking).

**Comment by sfackler** [comment]
It does depend on your use case - at low durations you'd preseumably prefer the slight inaccuracy of the raw clock over the possibility of measuring inside of an NTP-induced skew.

Seems reasonable that CLOCK_MONOTONIC is a better default choice though.

**Pull request closed without merging**
