### PR TITLE
Book on slices: Mention internal representation

### PR DESCRIPTION
**Pull request by kolloch**
When I read the book, the following sentence of the reference documentation helped me greatly to understand slices:

"Slices are a view into a block of memory represented as a pointer and a length."

In this commit, I tried to integrate the gist of that into the slice section inside of "primitive-types.md". I am not a native speaker, so feel very free to improve the wording.

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hi @kolloch ! I'm sorry this PR slipped through the cracks somehow.

@bors: r+ p=1

**Comment by steveklabnik** [comment]
Whew, sorry, I have been doing too many rollups lately, I didn't meen to set a high priority!

**Comment by kolloch** [comment]
@steveklabnik No worries. Just a very minor suggestion anyways. But since I was rereading the book from start to end, I thought that I'd mention it. Very nice work, BTW, thank you!

**Comment by steveklabnik** [comment]
Thank you! :)

**Pull request merged**
