### PR TITLE
rustc_llvm: re-run build script if config.toml changes

### LINKED ISSUE #35199: rustbuild ignores the llvm-config setting
I got in my `src/bootstrap/config.toml`:

```
[target.x86_64-unknown-linux-gnu]
…
llvm-config = "/home/nagisa/local/bin/llvm-config"
```

but rustc_llvm/build.rs still seems to attempt using /usr/bin/llvm-config

```
$ cat build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-9ee423514f5f4196/output 
cargo:rustc-cfg=cargobuild
cargo:rerun-if-changed=/usr/bin/llvm-config
```

cc @alexcrichton

### PR DESCRIPTION
**Pull request by venkatagiri**
closes #35199

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks good to me, but r? @alexcrichton

**Comment by venkatagiri** [comment]
FYI, after this change, the `config.toml` file is present in the build.rs config and touching/modifying `config.toml` is re-compiling `librustc_llvm`.
```
$ cat build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-ebd551ef66e29972/output | grep rerun
cargo:rerun-if-changed=/home/vagrant/repos/rust/build/x86_64-unknown-linux-gnu/llvm/bin/llvm-config
cargo:rerun-if-changed=/home/vagrant/repos/rust/config.toml
cargo:rerun-if-changed=../rustllvm/ArchiveWrapper.cpp
cargo:rerun-if-changed=../rustllvm/llvm-rebuild-trigger
cargo:rerun-if-changed=../rustllvm/RustWrapper.cpp
cargo:rerun-if-changed=../rustllvm/rustllvm.h
cargo:rerun-if-changed=../rustllvm/README
cargo:rerun-if-changed=../rustllvm/PassWrapper.cpp
```

**Comment by Mark-Simulacrum** [comment]
Hm, that's somewhat unfortunate -- but presumably it compiles fairly quickly? If not, we may want to reconsider this change, though I guess modifying config.toml is a somewhat rare occurence.

**Comment by alexcrichton** [comment]
Thanks for the PR @venkatagiri! 

@Mark-Simulacrum it's true yeah that this is a bit too coarse wrt when to rebuild things, but I think this is a good "next step" to fixing bugs in rustbuild. Want to file a follow-up issue about reducing the rebuilding granularity here?

In the meantime though this looks great for solving the issue at hand, so I'll....


@bors: r+

**Comment by Mark-Simulacrum** [comment]
Filed #42444.

@bors rollup

**Comment by venkatagiri** [comment]
@alexcrichton any ideas/suggestions on how to restrict the re-run to just `llvm-config` changes in `config.toml`. I can give it a try in fixing #42444.

**Comment by alexcrichton** [comment]
@venkatagiri ideally this'll be fixed through a mechanism such as https://github.com/rust-lang/cargo/pull/4125, so we may want to just wait for that PR to land and then update the build script here.

**Pull request merged**
