### PR TITLE
[WIP] implement explicit deref patterns through `k#deref`

### PR DESCRIPTION
**Pull request by fee1-dead**
Some technical considerations: (feel free to add to the list)

1. The first commits in this PR are based on #119351, adding support for the `k#ident` syntax.
2. Variants added: `ast::PatKind::Deref`, `hir::PatKind::Deref`, `thir::PatKind::DerefPattern`, `mir::TestKind::Deref`.
3. We use `Deref` for now, but we might want a different trait (`DerefPure`) later.
4. In typeck, we deref the `expected` (input type of the expression) type exactly once for simplicity, and then type check the inner pattern with `<expected as Deref>::Target`. Doing multiple derefs with a single `k#deref` isn't supported for now, and we might want to explore how to do implicit/multiple derefs later.
5. The actual codegen first takes the place being matched (let us call that `place`), creates a temporary references `&place`, then calls `deref`. (`place2 = Deref::deref(&place)`). The inner patterns then use `(*place2)` for continued matching. This means: (TODO: add test for types that cannot be moved out)

```rust
match vec![1] {
    k#deref [x] => {} // `x` here has type `i32`, not `&i32`
}
```

6. We skip generating false edges from or to arms with deref patterns. This behavior should be fixed before this PR actually get merged, since it means that any unreachable arm under deref patterns would not be borrowcked. (see the `vec-2.rs` test for this) **Clarification:** skipping false edges are done because deref patterns generate temporaries that are used to create bindings. When false edges are generated for deref patterns the temporaries don't get assigned to since they are assigned to during the tests and not before an arm block starts, which lead to borrowck errors.
7. The key to the matching algorithm is in `sort_candidate`, where we replace the original match pair of `PatKind::DerefPattern` with the inner pattern on the new temporary created by the deref. Note that since `sort_candidate` can be called on multiple candidates after a test is performed, we need to ensure that the peeling of deref pattern on a match pair only happens once (through `is_first`), so that the subsequent match arms all do their derefs individually and get tested individually.
8. The current impl only does `Deref` as being deliberately minimal. We would want to figure out the binding mode and try doing the appropriate deref in the future.
9. There is no guarantee that only a single deref occurs. In fact, point 7, through `is_first` is opposed to this idea. We'd probably want to explore whether `is_first` is really necessary with more testing. 

cc @compiler-errors @BoxyUwU @Nadrieril @matthewjasper @tgross35 @CAD97 (would like to hear from you about the implementation)

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? compiler
I'm overloaded with reviews.

**Comment by petrochenkov** [comment]
Also, `k#ident` is an even worse hack than `r#ident`.
If context-sensitive keywords don't work in this position, use something like `do yeet`.

**Comment by fee1-dead** [comment]
re `k#ident`: I will change this soon.

For point number 6, Nadrieril suggested that we do the `Deref` more than once: one when we do the test, to allow subsequent tests to match on the deref temporary, and do it again when pre-binding, for the false edges to work correctly. This would be unsound if we used `Deref`, which is a safe trait, but would not be an issue once we switch to using `DerefPure`.

**Comment by WaffleLapkin** [comment]
@petrochenkov I don't think I agree. `k#` and `r#` are basically identical. Moreover `k#something` is oftentimes used as a placeholder by T-lang when designing stuff, so it's not taken from nowhere (I think they even wanted to use it for actual feature prototypes, although we never went along with it so far...).

I think it should be totally fine as a placeholder here and can't really see any issues...

**Comment by fee1-dead** [comment]
closing in favor of #122222.

**Pull request closed without merging**
