### PR TITLE
Update cargo to stabilize Rust 2021.

### PR DESCRIPTION
**Pull request by m-ou-se**
This upgrades the `cargo` submodule, to include https://github.com/rust-lang/cargo/pull/9800.

### CODE REVIEW

**Comment by m-ou-se** [comment]
@bors try

(To be able to use it with `rustup-toolchain-install-master fe8f73c8fba2eb4eead6ca5178075e10ae780cb8 --component cargo`.)

**Comment by m-ou-se** [comment]
Already done in https://github.com/rust-lang/rust/pull/88563. Closing.

**Comment by ehuss** [comment]
Ah, yea, thanks!  It's a bit easier for me to use the automated scripts to run tests and make sure there are back links to all the PRs.  I also wanted to include the book updates for 2021 (and I had delayed this week to batch things up).

**Comment by m-ou-se** [comment]
I didn't know you had automated it. That's awesome. ^^

**Pull request closed without merging**
