### PR TITLE
Build compiler-builtins with 1 CGU

### PR DESCRIPTION
**Pull request by saethlin**
I'm testing whether this CGUs setting is required anymore.

### CODE REVIEW

**Comment by bjorn3** [comment]
CI may still pass even if compiler-builtins still needs 1 CGU. I believe linker issues only occur when compiler-builtins and libgcc/compiler-rt are both linked into the same binary and an intrinsic only provided by libgcc/compiler-rt is used that happens to be defined in the same object file as one that is provided by compiler-builtins. Aside from that weak linkage only has an effect when linking an executable or dylib. At runtime the dynamic linker may still incorrectly prefer the less optimized version from compiler-builtins over one provided by libgcc/compiler-rt if neither is statically linked into the same executable or dylib (eg because a dynamically linked libgcc_s.so is used instead).

**Comment by saethlin** [comment]
> CI may still pass even if compiler-builtins still needs 1 CGU.

You mean more than one right?

> I believe linker issues only occur when compiler-builtins and libgcc/compiler-rt are both linked into the same binary and an intrinsic only provided by libgcc/compiler-rt is used that happens to be defined in the same object file as one that is provided by compiler-builtins.

I have no idea what you are trying to describe. How would libgcc/compiler-rt be in the same object file as compiler-builtins?

The comment in `library/Cargo.toml` just vaguely mentions "symbol clashes", but you seem to be talking about ensuring that the right implementation is preferred. Are you talking about the same problem as the comment?

**Comment by lqd** [comment]
here's a recent issue cg_gcc had by not having this CGU setting https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.E2.9C.94.20Multiple.20definition.20of.20__multf3.20in.20rustc_codegen_gcc

**Comment by saethlin** [comment]
In addition, I'm a bit confused because the comment in library/Cargo.toml says:

> The goal here is to place every single intrinsic into its own object file

And bjorn3 said on that Zulip thread:

> to ensure every intrinsic ends up in a separate object file

But just using a lot of codegen-units doesn't make that happen. Every _module_ ends up in a separate object file. The compiler's CGU partitioning code does not permit splitting modules across CGUs.

So I don't know if I'm just missing an implied understanding that everyone has, or if the current source-level organization of compiler_builtins has managed to avoid linker issues by dumb luck, because the modules are generally organized so that if you want one intrinsic in a module, you want all of that module.

**Comment by bjorn3** [comment]
> And bjorn3 said on that Zulip thread:
> 
> > to ensure every intrinsic ends up in a separate object file
> 
> But just using a lot of codegen-units doesn't make that happen. Every _module_ ends up in a separate object file. The compiler's CGU partitioning code does not permit splitting modules across CGUs (there is a mildly good reason for this).

We already put every intrinsic in a separate module. Setting `codegen-units` is done to prevent rustc from merging multiple modules into a single codegen units for compiler-builtins.

**Comment by saethlin** [comment]
> We already put every intrinsic in a separate module.

So I suppose maybe I'm unclear on what the definition of an intrinsic is.

```
╭ ➜ ben@archlinux:~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib
╰ ➤ ar x libcompiler_builtins-75d2cc7090a2edf1.rlib 
╭ ➜ ben@archlinux:~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib
╰ ➤ nm compiler_builtins-75d2cc7090a2edf1.compiler_builtins.4cf492fc7b165bad-cgu.004.rcgu.o | rustfilt 
0000000000000000 T compiler_builtins::mem::__llvm_memcpy_element_unordered_atomic_1
0000000000000000 T compiler_builtins::mem::__llvm_memcpy_element_unordered_atomic_2
0000000000000000 T compiler_builtins::mem::__llvm_memcpy_element_unordered_atomic_4
0000000000000000 T compiler_builtins::mem::__llvm_memcpy_element_unordered_atomic_8
0000000000000000 T compiler_builtins::mem::__llvm_memset_element_unordered_atomic_1
0000000000000000 T compiler_builtins::mem::__llvm_memset_element_unordered_atomic_2
0000000000000000 T compiler_builtins::mem::__llvm_memset_element_unordered_atomic_4
0000000000000000 T compiler_builtins::mem::__llvm_memset_element_unordered_atomic_8
0000000000000000 T compiler_builtins::mem::__llvm_memmove_element_unordered_atomic_1
0000000000000000 T compiler_builtins::mem::__llvm_memmove_element_unordered_atomic_2
0000000000000000 T compiler_builtins::mem::__llvm_memmove_element_unordered_atomic_4
0000000000000000 T compiler_builtins::mem::__llvm_memmove_element_unordered_atomic_8
0000000000000000 T compiler_builtins::mem::bcmp
0000000000000000 t compiler_builtins::mem::impls::compare_bytes::{{closure}}
0000000000000000 T compiler_builtins::mem::memcmp
0000000000000000 T compiler_builtins::mem::memcpy
0000000000000000 T compiler_builtins::mem::memset
0000000000000000 T compiler_builtins::mem::strlen
0000000000000000 T compiler_builtins::mem::memmove
```
That looks like a lot of intrinsics in the same object file.

**Comment by bjorn3** [comment]
That is not an object file containing actual intrinsics. You should ignore all symbols starting with `_ZN`. Those are never intrinsics. Something like `__llvm_memset_element_unordered_atomic_2` would be, but `_ZN17compiler_builtins3mem40__llvm_memset_element_unordered_atomic_217he01f139febb7ffd0E` would not be. The former calls the latter, but only the former can conflict with libgcc/compiler-rt and thus needs to be in a separate object (as it currently is), while the latter can co-exist with other functions in the same object file.

**Pull request closed without merging**
