### PR TITLE
Added useful links section

### PR DESCRIPTION
**Pull request by alexispurslane**
This is something that I wish I had when I started contributing to Rust (not that long ago :). I plan on writing a manual for bors and the rust testing setup too, if there isn't one already.

### CODE REVIEW

**Comment by steveklabnik** [comment]
llvm change needs reverted :)

**Comment by christopherdumas** [comment]
OK.

**Comment by christopherdumas** [comment]
(I squashed the commits too)

**Comment by steveklabnik** [comment]
Thank you!

**Pull request merged**
