### PR TITLE
doc: Added commas where needed

### PR DESCRIPTION
**Pull request by x4exr**

### CODE REVIEW

**Comment by x4exr** [comment]
Oops, sorry. My IDE made those on its own for some reason. I'll go ahead and fix that

**Comment by Nilstrieb** [comment]
can you squash the two commits? looks good to merge after that.

**Comment by x4exr** [comment]
I tried squashing but It didnt work, im not sure how to
```
git reset --soft master~2
fatal: ambiguous argument 'master~2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by dtolnay** [comment]
> ```
> fatal: Not a valid object name master
> ```

This probably means there isn't a [remote-tracking branch](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches) called `master`. It might have worked if you use `origin/master` instead of `master` in those commands.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
