### PR TITLE
test: Add testcase for #16745

### LINKED ISSUE #16745: Can't mix generic and specific literals in match arms
For example
```rust
n is_whitespace(b: u8) -> bool {
    match b {
        b' '  => true,
        b'\t' => true,
        b'\n' => true,
        0x0B  => true,
        0x0C  => true,
        b'\r' => true,
        _     => false,
    }
}
```
```
mod.rs:166:9: 166:13 error: mismatched types between arms
mod.rs:166         b' '  => true,
                   ^~~~
mod.rs:167:9: 167:14 error: mismatched types between arms
mod.rs:167         b'\t' => true,
                   ^~~~~
mod.rs:168:9: 168:14 error: mismatched types between arms
mod.rs:168         b'\n' => true,
                   ^~~~~
mod.rs:166:9: 166:13 error: mismatched types between arms
mod.rs:166         b' '  => true,
                   ^~~~
mod.rs:167:9: 167:14 error: mismatched types between arms
mod.rs:167         b'\t' => true,
                   ^~~~~
mod.rs:168:9: 168:14 error: mismatched types between arms
mod.rs:168         b'\n' => true,
                   ^~~~~
mod.rs:169:9: 169:13 error: mismatched types between arms
mod.rs:169         0x0B  => true,
                   ^~~~
mod.rs:170:9: 170:13 error: mismatched types between arms
mod.rs:170         0x0C  => true,
```

### PR DESCRIPTION
**Pull request by richo**
closes #16745

### CODE REVIEW

**Comment by jakub-** [comment]
@richo Hey, great, could we perhaps tweak the test case so that it has an assertion? Maybe assert on the value of the whole match expression?

Just trying to make sure it is a bit more comprehensive (I admit, however, I myself have not been very diligent about this in the past.)

r+ with that

**Comment by richo** [comment]
Added an assertion. Should be good to go.

**Pull request merged**
