### PR TITLE
[perftest] Use LTO for compiling `rustdoc`

### PR DESCRIPTION
**Pull request by Kobzol**
r? @ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
Hmm, looks like we're missing bitcode for `jemalloc`:
```
Couldn't add bitcode from jemalloc_sys-f8a71c72a88bc04e.jemalloc_sys.3fd4af2a-cgu.0.rcgu.o
```
I wonder why this wasn't a problem for `librustc_driver`, which AFAIK sets up `jemalloc` in the same way.
It's possibly by the fact that `librustdoc` uses `extern crate jemalloc;` (?).

I noticed that `librustc_driver` also uses `extern crate tracing;`, which caused a problem here, but it wasn't a problem for the driver. @bjorn3 did you encounter any issues with using LTO for crates included from the sysroot (`extern crate X;`) when you were working on the `librustc_driver` LTO PR?

**Comment by bjorn3** [comment]
>  @bjorn3 did you encounter any issues with using LTO for crates included from the sysroot (extern crate X;) when you were working on the librustc_driver LTO PR?

I don't think I tested that.

**Comment by Kobzol** [comment]
I asked because `librustc_driver` also uses `extern crate tracing;`, but I haven't seen it causing any problems.

**Comment by Kobzol** [comment]
This probably hit the modifications of the perf. CI machine, rerunning perf.

@rust-timer build 13e91afe8ca2f1641d8d6cbcffe6e2860b18cc33

**Comment by Kobzol** [comment]
After discussing this with @lqd and @nnethercote, I think that this is actually not needed. `librustc_driver` is now LTO optimized, and the rest of the `doc` code is in `librustdoc`, which is a single crate, so thin LTO probably won't have a big effect on it. So I'm inclined to close this.

@bjorn3 Do you agree with my assessment of the `rustdoc` LTO "situation"?

**Comment by bjorn3** [comment]
Rustdoc uses several external crates like a markdown parser. Those could benefit from LTO. I don't know how big the effect would be though.

**Pull request closed without merging**
