### PR TITLE
Work around invalid spans in imported FileMaps

### PR DESCRIPTION
**Pull request by michaelwoerister**
This should solve issues #23115, #23469, and #23407.

As the title says, this is just a workaround. The underlying problem is that macro expansion can produce invalid spans. I've opened issue #23480 so we don't forget about that.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice!

**Comment by michaelwoerister** [comment]
:broken_heart: indeed. I'll fix this when I come home after work today.

On March 19, 2015 1:17:12 AM CET, bors <notifications@github.com> wrote:
>:broken_heart: Test failed -
>[auto-mac-64-opt](http://buildbot.rust-lang.org/builders/auto-mac-64-opt/builds/4120)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/pull/23489#issuecomment-83232028

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
