### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #92385 (Add Result::{ok, err, and, or, unwrap_or} as const)
 - #94559 (Remove argument from closure in thread::Scope::spawn.)
 - #94712 (promot debug_assert to assert)
 - #94716 (update Miri)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=92385,94559,94712,94716)

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r- retry

Miri is broken by some very recently landing changes. Sorry for that.

**Comment by RalfJung** [comment]
Lol we clicked that button the same time.^^

**Comment by Dylan-DPC** [comment]
creating a new rollup already :P don't race me there xD

**Pull request closed without merging**
