### PR TITLE
re-enable 'html literals' macro test

### LINKED ISSUE #20673: src/test/run-pass/html-literals.rs is ignored
With the new macro rules (https://github.com/rust-lang/rust/pull/20563) this test had to be ignored.

### PR DESCRIPTION
**Pull request by steveklabnik**
This test now works again

Fixes #20673

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oddly enough, this test actually compiles today? Perhaps it could just be un-ignored?

**Comment by steveklabnik** [comment]
Oh strange. Sure, if you think there's value in keeping it, I'm okay with un-ignoring.

**Comment by alexcrichton** [comment]
Can't hurt! (r=me with un-ignore-test)

**Pull request merged**
