### PR TITLE
rustdoc: Record crate name instead of using `None`

### LINKED ISSUE #83365: rustdoc prints `<unknown>` as name of crate root
```rust
//! [my_module]

mod my_module {}
```

```
warning: public documentation for `<unknown>` links to private item `my_module`
 --> foo.rs:1:6
  |
1 | //! [my_module]
  |      ^^^^^^^^^ this item is private
  |
  = note: `#[warn(private_intra_doc_links)]` on by default
  = note: this link will resolve properly if you pass `--document-private-items`

warning: 1 warning emitted
```

It should say `foo` instead.

### PR DESCRIPTION
**Pull request by camelid**
Fixes #83365.

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
Looks great :) r=me with CI passing.

**Comment by camelid** [comment]
Uh... why are 38 tests failing? That's weird...

**Comment by camelid** [comment]
Maybe the change in how crate names are used is messing up URLs or something?

**Comment by jyn514** [comment]
I ran into something like this in https://github.com/rust-lang/rust/pull/78082 - see if this is adding an extra directory named after the top-level crate. There was somewhere in html/render that overrode this later.

**Comment by camelid** [comment]
> I ran into something like this in #78082 - see if this is adding an extra directory named after the top-level crate.

Yep, it is doing that. Do you remember where the place in `html/render` was?

**Comment by jyn514** [comment]
Not off the top of my head, sorry.

**Comment by camelid** [comment]
I do see [this change](https://github.com/rust-lang/rust/pull/78082/files#diff-46f011cf734f3de35eddca150990366cc41bd8eaf3945a241b2a2f79c5bb77eaL85-R85), but haven't found the change that I need yet...

**Comment by camelid** [comment]
Okay, it looks like the bug is in whatever's populating `cache.paths`. (No need to respond, just recording this so I don't forget.)

**Comment by camelid** [comment]
Fixed the bug. Will push up commit tomorrow.

**Pull request merged**
