### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #22954, #23119, #23509, #23561, #23590, #23607, #23608, #23618, #23622, #23639, #23641
- Failed merges: #23401

### CODE REVIEW

**Comment by alexcrichton** [comment]
Picked up the rest of the queue in https://github.com/rust-lang/rust/pull/23654 as well, so closing in favor of that. Shoulda at least started from this though, sorry about that :(

**Comment by alexcrichton** [comment]
Or actually it looks like I rolled up the rollup.

**Comment by steveklabnik** [comment]
@alexcrichton no worries, I just said I'd kick one off after the other was done

**Pull request closed without merging**
