### PR TITLE
Move items related to computing diffs to a separate file

### PR DESCRIPTION
**Pull request by Nicholas-Baron**
Work towards #89475.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
There's some diff-related code here as well - https://github.com/rust-lang/rust/blob/cb501a6fe6cdb1928611b7193dec96f3d7bd2293/src/tools/compiletest/src/runtest.rs#L2404

I'm not sure how much that is "the same" or can be unified, haven't looked too closely. What do you think?

**Comment by Nicholas-Baron** [comment]
@Mark-Simulacrum While this does seem diff-related, its structure is very different from `write_diff` and `make_diff`, suggesting some semantic differences. This makes unification a task I think beyond this PR.

It may be possible to extract some parts as separate functions, as `self` is not reference heavily in them. However, this may be beyond the scope of this PR as well. The following code block is an example. https://github.com/rust-lang/rust/blob/cb501a6fe6cdb1928611b7193dec96f3d7bd2293/src/tools/compiletest/src/runtest.rs#L2406-L2431

**Comment by Mark-Simulacrum** [comment]
Hm. Ok. Well, I guess we can add a "why do we have two different diff implementations" (unified-diff and diff crates) to the list of open questions...

But regardless I think much of the code *can* be moved into this module, if not unified just yet -- it looks pretty separate from being *rustdoc* specific to me, beyond the minor filter on extensions (which seems easy to pass in).

**Pull request merged**
