### PR TITLE
[experiment] Allocate DepGraph::read_index de-duplication hashset more lazily.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Possibly an optimization for `DepGraph::read_index()`. Might need some tweaking. I also want to try a SIMD-based version.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@rust-timer build c81a607ee5eebb66b37b0f11ab038cf48ab60aa2

**Comment by michaelwoerister** [comment]
Looks like the current version has no visible effect. I'll do a SIMD enabled version when I find the time.

**Comment by Zoxc** [comment]
@rust-timer build b350a5644a4b98b0c16953bc075e40ec5cb2cbd0

**Comment by Zoxc** [comment]
Do you have any stats on how many reads a dep node typically gets and how many of these are duplicates?

**Comment by michaelwoerister** [comment]
Yes, @wesleywiser collected some data a while ago and even implemented delayed deduplication but it didn't improve performance and increased memory usage. Here's the relevant issue and PR:

- Explore delayed read-edge deduplication or getting rid of it entirely - https://github.com/rust-lang/rust/issues/45873
- [incremental] Collect stats about duplicated edge reads from queries - #46068

I also did some experiments similar to this one but it didn't improve performance either:
- incr.comp.: Use a set implementation optimized for small item counts for deduplicating read-edges - https://github.com/rust-lang/rust/pull/45577

I don't expect this to be much of a win, if at all. It's a spare-time project for me, more or less `:)` @nnethercote's optimization to use a `SmallVec` (https://github.com/rust-lang/rust/pull/50565) was more important.

`-Z incremental-info` should tell you how many reads are duplicated, IIRC.

**Comment by michaelwoerister** [comment]
Yeah, that doesn't seem to make a measurable difference. Bummer.

**Pull request closed without merging**
