### PR TITLE
remove `allow_fail` test flag

### LINKED ISSUE #93345: remove `allow_fail` test flag
As noted in https://github.com/rust-lang/rust/issues/46488#issuecomment-1022585129 we've discussed stabilizing this feature and came to the conclusion that we likely need better support for tests that are allowed to fail in certain situations such as when not run in CI, but that we're not confident that this feature is the best way to solve the specific problems people have. For now we would like to remove this feature and follow up later with a more thorough RFC discussion using concrete examples.

### PR DESCRIPTION
**Pull request by name1e5s**
close #93345

### CODE REVIEW

**Comment by name1e5s** [comment]
Hmm, it seems that we should preserve `allow_fail` field in `TestDesc` to pass the check with stage 0 compiler.

**Comment by m-ou-se** [comment]
We should wait until the FCP in #46488 finishes, so marking this as blocked for now.

**Comment by m-ou-se** [comment]
> Hmm, it seems that we should preserve `allow_fail` field in `TestDesc` to pass the check with stage 0 compiler.

You can use `#[cfg(bootstrap)]` for code that should only used with the stage 0 compiler.

**Comment by m-ou-se** [comment]
Thanks!

@bors r+

**Pull request merged**
