### PR TITLE
Optimize assert equal

### PR DESCRIPTION
**Pull request by 0xPoe**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

### CODE REVIEW

**Comment by petrochenkov** [comment]
It's ok to do this in tests (or doc tests), but not always in regular code or benchmarks.

`assert_ne` generates some amount of formatting code that may slow down performance critical code and affect benchmark results.

**Comment by Rustin-Liu** [comment]
@petrochenkov  Could we do a performance test to see the results?

**Comment by matthiaskrgr** [comment]
Looking at godbolt, it seems that `assert_ne(x,y)` generates more instructions than `assert!(x != y)` and `assert_eq!(x,y)` generates more instructions than `assert!(x == y)`:
https://rust.godbolt.org/z/xEC-tw

**Comment by Rustin-Liu** [comment]
> Looking at godbolt, it seems that `assert_ne(x,y)` generates more instructions than `assert!(x != y)` and `assert_eq!(x,y)` generates more instructions than `assert!(x == y)`:
> https://rust.godbolt.org/z/xEC-tw

Got it. Thanks!

**Pull request closed without merging**
