### PR TITLE
impl AsFd and AsRawFd for io::{Stdin, Stdout, Stderr}, not the sys versions

### PR DESCRIPTION
**Pull request by joshtriplett**
https://github.com/rust-lang/rust/pull/100892 implemented AsFd for the
sys versions, rather than for the public types. Change the
implementations to apply to the public types.

### CODE REVIEW

**Comment by joshtriplett** [comment]
Noticed when trying to merge https://github.com/rust-lang/rust/pull/98033

**Comment by the8472** [comment]
This seems like the wrong place. For other public, os-specific types the `impl AsFd` lives somewhere in `os::<platform>` modules, not in `sys`. There impls in the sys modules are for the internal types.

**Comment by joshtriplett** [comment]
> This seems like the wrong place. For other public, os-specific types the `impl AsFd` lives somewhere in `os::<platform>` modules, not in `sys`. There impls in the sys modules are for the internal types.

`impl AsFd` for stdio types lives in `library/std/src/sys/unix/stdio.rs` on UNIX, as well.

**Comment by the8472** [comment]
This is a bit inconsistent, e.g. `AsRawFd` comes from from `os::fd::raw` https://doc.rust-lang.org/src/std/os/fd/raw.rs.html#183-188
And the `impl AsFd for File` comes from `os` too. https://doc.rust-lang.org/src/std/os/fd/owned.rs.html#258-263

**Comment by joshtriplett** [comment]
@the8472 That would be a substantially larger reorganization, affecting multiple targets. No objections to such a reorganization, but that seems orthogonal to this bugfix.

That said, it does look like `impl AsRawFd for io::Stdin` would be redundant, so I'll remove that.

**Comment by the8472** [comment]
Not suggesting to fix everything. Just put the Stdio ones in the right place.

**Comment by joshtriplett** [comment]
Alright, let's hope this actually builds everywhere.

**Pull request merged**
