### PR TITLE
[DO NOT MERGE] perf run for rustc-hash candidate

### PR DESCRIPTION
**Pull request by orlp**
See https://github.com/rust-lang/rustc-hash/pull/37.

### CODE REVIEW

**Comment by thomcc** [comment]
Looks green on cycles, walltime, task clock, cpu clock, ... Instructions are somewhat surprisingly a mixed bag (surprising as it does strictly less work, IIUC).

**Comment by orlp** [comment]
@thomcc It is not strictly less work, it adds an extra bit rotation for the pure integer hash case where there wasn't anything before.

These results are a bit more of a mixed bag than the results in my previous experiments, I believe because I gated some string optimizations behind a `nightly` feature and enabled them in the `[patch]` section which does not work. Can you re-run the benchmark now that I've specified the feature in the respective `Cargo.toml`s?

**Comment by Nilstrieb** [comment]
it's mostly neutral, but there is a bit of green, that's awesome, congrats! makes sense then to move ahead and replace it in rustc_hash

**Comment by nnethercote** [comment]
I see a small but clear instructions win for `unused-warnings` and a clear cycles win for `tuple-stress`, both secondary benchmarks. Very small improvements, really, and it's not obvious to me that this change should be merged. `FxHash` is used so heavily that I would prefer a stronger signal before replacing it with something entirely different.

**Comment by WaffleLapkin** [comment]
It's intresting that cache-misses and branch-misses are so green.

**Comment by orlp** [comment]
@nnethercote If you'd like I could do a run where I remove the final `rotate_left` which I think would *in general* lead to green across the board for instruction count, but would also make the hash significantly more vulnerable to misuse like the current one is.

This PR isn't strictly a performance PR - it's also one that makes rustc-hash more robust against accidental heavy multicollisions if your only differences happen to be in the high bits of the last hashed word.

**Comment by nnethercote** [comment]
> This PR isn't strictly a performance PR - it's also one that makes rustc-hash more robust against accidental heavy multicollisions if your only differences happens to be in the high bits of the last hashed word.

So it seems the argument is that the new hash gives slightly better performance and has better protection against bad cases. On the latter item, from the design I can believe that the new algorithm is less collision-prone, but it would be good to have some empirical evidence. 

A couple of ideas:
- Compare the old and new versions through a hash function evaluation suite. (I know these exist, I can't remember the names of any now, I figure you probably know a suitable one.)
- #91660 is one example I know of where the existing `FxHasher` behaved really badly. The commits in that PR include comments that explain things well. There are two 32-bit fields in a struct that get combined into a 64-bit integer and then hashed, and if you do it one order with the existing `FxHasher` you get good results and if you do it in the other order you get terrible results. So you could repeat that "change the order" experiment with the current `FxHasher` to reconfirm the big slowdown, and then retry that experiment with the new hasher and see if it avoids the slowdown. The slowdowns are big enough that you might not even need to run rustc-perf. Just doing `cargo check` on `stm32f` might be sufficient.

Good results on one or both of those would be enough to convince me to switch algorithms. What do you think? I don't want to be a roadblock, but I also want to be cautious when changing such a critical piece of code.

**Comment by orlp** [comment]
@nnethercote Thanks for bringing https://github.com/rust-lang/rust/pull/91660 to my attention, because this is *precisely* what this hash mitigates. I quote from the linked PR:

```rust
// The order here has direct impact on `FxHash` quality because we have far more `DefIndex` per
// crate than we have `Crate`s within one compilation. Or in other words, this arrangement puts
// more entropy in the low bits than the high bits. The reason this matters is that `FxHash`, which
// is used throughout rustc, has problems distributing the entropy from the high bits, so reversing
// the order would lead to a large number of collisions and thus far worse performance.
//
// On 64-bit big-endian systems, this compiles to a 64-bit rotation by 32 bits, which is still
// faster than another `FxHash` round.
#[cfg(target_pointer_width = "64")]
impl Hash for DefId {
    fn hash<H: Hasher>(&self, h: &mut H) {
        (((self.krate.as_u32() as u64) << 32) | (self.index.as_u32() as u64)).hash(h)
    }
}
```

If you don't mind, I'd like to do a simulated benchmark to demonstrate the effectiveness of the new hash in this scenario. Suppose we have 64 crates and 1024 `def_index`'s per crate (which adds up to a total of 2^16 elements), so a hash table of 2^17 elements should fit all the data with a load factor of 0.5. Let's see how many collisions for hash table buckets we get in that scenario:

```rust
use core::hash::{BuildHasher, BuildHasherDefault};

fn compute_max_collisions(name: &str, hasher: impl BuildHasher) {
    let table_mask = (1 << 17) - 1;
    let mut table_orig_order = vec![0u64; 1 << 17];
    let mut table_swap_order = vec![0u64; 1 << 17];
    for krate in 0..64_u32 {
        for def_index in 0..1024_u32 {
            let h_orig = hasher.hash_one(((def_index as u64) << 32) | krate as u64);
            let h_swap = hasher.hash_one(((krate as u64) << 32) | def_index as u64);
            table_orig_order[(h_orig & table_mask) as usize] += 1;
            table_swap_order[(h_swap & table_mask) as usize] += 1;
        }
    }
    
    let max_orig = table_orig_order.into_iter().max().unwrap();
    let max_swap = table_swap_order.into_iter().max().unwrap();
    println!("{name} max orig collisions: {max_orig}");
    println!("{name} max swap collisions: {max_swap}");
}

fn main() {
    compute_max_collisions("current", BuildHasherDefault::<current::FxHasher>::default());
    compute_max_collisions("orlp", BuildHasherDefault::<orlp::FxHasher>::default());
}
```

You can run it yourself here, I just copy/pasted the current and my implementation: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7ca94ca09b9ab282874e6ae4c08d7c88>.

So what are the results?

```
current max orig collisions: 1024
current max swap collisions: 64
orlp max orig collisions: 2
orlp max swap collisions: 2
```

Now, hashbrown is a combination of larger hash table buckets + a tag instead of only a bucket index which mitigates this, but the principle stays the same.

**Comment by nnethercote** [comment]
Ok, that satisfies me, thanks!

Perhaps the PR for this repo that incorporates the new FxHash should simplify the `DefId` hasher, then -- sounds like we won't need the big/little endian split and the long comment any more.

**Pull request closed without merging**
