### PR TITLE
Enforce formatting for rustc_codegen_cranelift

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by camelid** [comment]
No longer blocked, just needs rebase now. @rustbot author

**Comment by bjorn3** [comment]
Rebased

**Comment by Mark-Simulacrum** [comment]
@bors r+

Seems OK to me, though note that the rustfmt used in rust-lang/rust CI is from a pinned nightly, bumped alongside the bootstrap compiler.

**Comment by joshtriplett** [comment]
Is there an issue filed for the breakage rustfmt causes with `y.rs`?

**Comment by bjorn3** [comment]
The breakage to y.rs isn't rustfmt's fault. It starts with:

```rust
#!/usr/bin/env bash
#![allow()] /*This line is ignored by bash
# This block is ignored by rustc
```

Rustfmt puts the comment on a newline, but this causes it to be interpreted as command by bash rather than as comment.

**Pull request merged**
