### PR TITLE
Cache the specialization_graph query

### LINKED ISSUE #48987: incr.comp.: Cache the specialization_graph query.
Computing the specialization graph for a trait involves looking at lots of things. The result of the query should be easily cacheable:

https://github.com/rust-lang/rust/blob/e65547d4fad0425d1db4f33a4d8134bf2cad939e/src/librustc/traits/specialize/specialization_graph.rs#L39-L66

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #48987

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Perfect! `:)`

@bors try

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, could you do a perf-run please? Just to make sure this doesn't regress anything.

**Comment by Mark-Simulacrum** [comment]
Perf started.

**Comment by michaelwoerister** [comment]
Link: http://perf.rust-lang.org/compare.html?start=fab632f9759af4f3d96c6ec69e24e5428060dba4&end=e744f7efcbdd9caf5dafe6bfaa813fa6aaec2aba&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, I think something has gone wrong with the perf-run.

**Comment by Mark-Simulacrum** [comment]
I've added even more debugging and restarted it.. not sure what went wrong.

**Comment by michaelwoerister** [comment]
Still doesn't `:(`

**Comment by Mark-Simulacrum** [comment]
Restarted *again* this time the logging is confirmed to work. Turns out env_logger doesn't send output to stdout...

**Comment by Mark-Simulacrum** [comment]
It worked: http://perf.rust-lang.org/compare.html?start=fab632f9759af4f3d96c6ec69e24e5428060dba4&end=e744f7efcbdd9caf5dafe6bfaa813fa6aaec2aba&stat=instructions%3Au.

No ideas on what went wrong before, but I guess we at least have logging now.

**Pull request merged**
