### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/42785
- https://github.com/rust-lang/rust/pull/42740
- https://github.com/rust-lang/rust/pull/42735
- https://github.com/rust-lang/rust/pull/42728
- https://github.com/rust-lang/rust/pull/42695
- https://github.com/rust-lang/rust/pull/42659
- https://github.com/rust-lang/rust/pull/42634
- https://github.com/rust-lang/rust/pull/42566

I just unilaterally accepted all the non-accepted nominations. Everything picked cleanly.

Still testing locally.

cc @rust-lang/compiler 

r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
....This appears to have passed CI, but bors didn't actually merge as far as I can tell. I guess

@bors r=alexcrichton

**Comment by Mark-Simulacrum** [comment]
Ah, I guess:

@bors retry

**Comment by alexcrichton** [comment]
@bors: retry

* osx timeout

**Comment by Mark-Simulacrum** [comment]
@bors retry

Failure seems spurious:

```
[01:01:22] failures:
[01:01:22]
[01:01:22] ---- [run-make] run-make/sanitizer-leak stdout ----
[01:01:22]
[01:01:22] error: make failed
[01:01:22] status: exit code: 2
[01:01:22] command: "make"
[01:01:22] stdout:
[01:01:22] ------------------------------------------
[01:01:22] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-leak.stage2-x86_64-unknown-linux-gnu:/checkout/obj/build/x86_64-unknown-linux-gnu
[01:01:22] /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-leak.stage2-x86_64-unknown-linux-gnu/leak 2>&1 | grep -q 'detected memory leaks'
[01:01:22] Makefile:6: recipe for target 'all' failed
[01:01:22]
[01:01:22] ------------------------------------------
[01:01:22] stderr:
[01:01:22] ------------------------------------------
[01:01:22] make: *** [all] Error 1
[01:01:22]
[01:01:22] ------------------------------------------
[01:01:22]
[01:01:22] thread '[run-make] run-make/sanitizer-leak' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2480
[01:01:22] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:01:22]
[01:01:22]
[01:01:22] failures:
[01:01:22]     [run-make] run-make/sanitizer-leak
[01:01:22]
[01:01:22] test result: FAILED. 148 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Mark-Simulacrum** [comment]
@bors retry

os x timeout

**Comment by alexcrichton** [comment]
@bors: p=1

(beta backports)

**Comment by Mark-Simulacrum** [comment]
Presuming spurious failure, @bors retry

```
[00:57:26] ---- [run-make] run-make/sanitizer-leak stdout ----
[00:57:26] 	
[00:57:26] error: make failed
[00:57:26] status: exit code: 2
[00:57:26] command: "make"
[00:57:26] stdout:
[00:57:26] ------------------------------------------
[00:57:26] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-leak.stage2-x86_64-unknown-linux-gnu:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-leak.stage2-x86_64-unknown-linux-gnu -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-leak.stage2-x86_64-unknown-linux-gnu  -C opt-level=1 -g -Z sanitizer=leak -Z print-link-args leak.rs | grep -q librustc_lsan
[00:57:26] /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-leak.stage2-x86_64-unknown-linux-gnu/leak 2>&1 | grep -q 'detected memory leaks'
[00:57:26] Makefile:6: recipe for target 'all' failed
[00:57:26] 
[00:57:26] ------------------------------------------
[00:57:26] stderr:
[00:57:26] ------------------------------------------
[00:57:26] make: *** [all] Error 1
[00:57:26] 
[00:57:26] ------------------------------------------
[00:57:26] 
[00:57:26] thread '[run-make] run-make/sanitizer-leak' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2480
[00:57:26] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:57:26] 
[00:57:26] 
[00:57:26] failures:
[00:57:26]     [run-make] run-make/sanitizer-leak
[00:57:26] 
[00:57:26] test result: [31mFAILED(B[m. 148 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by kennytm** [comment]
Something's wrong with @bors, 10 minutes and the beta branch is still not updated.

**Comment by Mark-Simulacrum** [comment]
I think @bors doesn't like this pull request. I'm going to try and reopen as a new PR I guess..

**Comment by Mark-Simulacrum** [comment]
I've reopened this as https://github.com/rust-lang/rust/pull/42927 in the hopes that @bors like it more.

**Pull request closed without merging**
