### PR TITLE
mark std::string::String::new() and std::vec::Vec::new() as #[must_use].

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by rkruppe** [comment]
Could you say a bit about the motivation? With many other methods where must_use is being proposed, I can see an argument about not using the result hiding a specific, subtle bug (e.g., calling `String::trim` and expecting it to work in-place) or seriously wasting resources (e.g., anything that allocates). But neither of those reasons applies to `{Vec,String}::new()`.

**Comment by leodasvacas** [comment]
I suppose that the motivation is that if the return value is dead code then the constructing call is always dead code.

**Comment by scottmcm** [comment]
In https://github.com/rust-lang/rust/issues/48926#issuecomment-389152854, @est31 proposed a new lint that would obviate the need for changes like this (since both methods are const) which I think is a better approach than manually annotating all these.

**Comment by TimNN** [comment]
I think we'll need some more consensus on general guidelines which `std` function should be marked `#[must_use]`, so I'm marking this PR as blocked on #48926 for the time being.

**Comment by TimNN** [comment]
Thank you for your PR! It doesn't look like there will be a decision about how to handle `#[must_use]` functions in the standard library any time soon, so I'm going to close this PR for now.

**Pull request closed without merging**
