### PR TITLE
Update libbacktrace

### PR DESCRIPTION
**Pull request by steveklabnik**
We haven't updated libbacktrace in two years. This is just blindly updating to the latest HEAD; I'd like to see what travis says. It at least builds on my machine, running some tests...

This perpetuates the patches from https://github.com/rust-lang/rust/pull/30908

### CODE REVIEW

**Comment by retep998** [comment]
Can I question why this includes `THE ADVENTURES OF TOM SAWYER`!?

**Comment by petrochenkov** [comment]
A number of other patches was applied to our version of libbacktrace after https://github.com/rust-lang/rust/pull/30908 if you look at git history, Mach-O support in particular.

**Comment by steveklabnik** [comment]
@petrochenkov thanks, good call. I figured there may be more; I hadn't fully checked into it yet. I'll go take a look now that it did build successfully.

**Comment by steveklabnik** [comment]
I've reapplied some patches, and disregarded some others. A double check here would be great.

Spelling fixes, that I've disregarded so that we closer track upstream:

* https://github.com/rust-lang/rust/commit/02aa0aff2f0b42368dd871186510493fa60d785a
* https://github.com/rust-lang/rust/commit/7ee3e39f640a9532842e1441bf6bc98893b6a3ba
* https://github.com/rust-lang/rust/commit/02aa0aff2f0b42368dd871186510493fa60d785a

Backports that should be included with the update:

* https://github.com/rust-lang/rust/commit/a42115375b1d7ae2a6c3f8c85819ef8182abaf52


https://github.com/rust-lang/rust/commit/e8121b3d163f90a8f1cefca07352d3780eed933d added support for apple platforms, but then https://github.com/rust-lang/rust/commit/8581b59fb39b0072665de59b1a70e708b251d4b0 disabled it, so I've just not bothered. The original patch was sent upstream, but was ignored and eventually closed.

For https://github.com/rust-lang/rust/commit/aa6bd117bbe05930476b4aec1001fff77ce66348, the file was completely deleted upstream, and so I don't think applies anymore.

**Comment by kennytm** [comment]
(I'd prefer us to transition to a gimli-based library eventually so I'm :-1: to merging this huge PR.)

8581b59fb39b0072665de59b1a70e708b251d4b0 (#45866) only disabled mmap support for macOS, not the entire functionality.

The upstream patch ianlancetaylor/libbacktrace#2 was closed because the maintainer simply ignored the PR without any further communication. It doesn't mean the patch is not working.

BTW is it possible we just turn libbacktrace into a submodule? +18846/-8114 isn't a fun thing to deal with.

**Comment by sfackler** [comment]
A submodule seems like a good idea.

**Comment by alexcrichton** [comment]
I believe at the time that this was originally added the repo didn't exist or I couldn't find it, but I definitely agree that we should use a submodule now. If anything it'll help us track how we diverge! To that end I've now created https://github.com/rust-lang-nursery/libbacktrace

Ok and to make sure we don't lose anything, let's take a look at the [current history](https://github.com/rust-lang/rust/commits/e0635188ed30e083245482218a0de9237f14ce90/src/libbacktrace) of the "submodule". The commits we're dealing with are:

* 7ee3e39f640a9532842e1441bf6bc98893b6a3ba - typos
* ece9a57d1b6e10ef2ad1dffd19fd6033cdc760ee - typos
* 8581b59fb39b0072665de59b1a70e708b251d4b0 - disable mmap on OSX
* 2f3c412c84712f2159ccf5c174ac716d19925d68 - disable mmap for all of libbacktrace
* aa6bd117bbe05930476b4aec1001fff77ce66348 - fix line numbers on i686
* e3de40e72f0f6b2dba54388d05e94e2c145cec6d - osx related
* e8121b3d163f90a8f1cefca07352d3780eed933d - osx related
* 0fad1b1cd8e6577590108c653e4818685e0f7b03 - update config.sub
* d14b268b9d0f37811c47cc6b1ebf2433fbb0ad0e - fix uninitialized variable
* a42115375b1d7ae2a6c3f8c85819ef8182abaf52 - backport soundness fix
* 02aa0aff2f0b42368dd871186510493fa60d785a - typos
* 55e2b7e1b4606ae0bc684293f011b7006d1f1258 - reapply rust-specific-changes

And I believe that's it. 5f57121fb328c0e62b49a405f9a5339098ec0a8e, the next element in the history, is where we reset to a revision of upstream gcc, so it's sync'd with the original source. I agree with @steveklabnik to leave out typos, which leaves us with:

* 8581b59fb39b0072665de59b1a70e708b251d4b0 - https://github.com/rust-lang-nursery/libbacktrace/commit/7845b4ecc7e8a6856ea42bb0f1f6bfcdbb8926ca
* 2f3c412c84712f2159ccf5c174ac716d19925d68 - now https://github.com/rust-lang-nursery/libbacktrace/commit/bddb51c706113aa04fbf3e05630231ac56772300
* aa6bd117bbe05930476b4aec1001fff77ce66348 - now https://github.com/rust-lang-nursery/libbacktrace/commit/e06f27504ac3e44f2d2d8a55446653edd3e594de
* e3de40e72f0f6b2dba54388d05e94e2c145cec6d - now https://github.com/rust-lang-nursery/libbacktrace/commit/07b6b415fabd150419ced7bf92662113856433d8
* e8121b3d163f90a8f1cefca07352d3780eed933d - now https://github.com/rust-lang-nursery/libbacktrace/commit/b47a92c573f730c5331d5d35f687102fa47f4aa5
* 0fad1b1cd8e6577590108c653e4818685e0f7b03 - now https://github.com/rust-lang-nursery/libbacktrace/commit/2e94976e6203f92313fedc205c5daafbface06af
* d14b268b9d0f37811c47cc6b1ebf2433fbb0ad0e - now https://github.com/rust-lang-nursery/libbacktrace/commit/6ccb80058808e10b05c3560e756858e28a428458
* ~~a42115375b1d7ae2a6c3f8c85819ef8182abaf52~~ - not necessary
* 55e2b7e1b4606ae0bc684293f011b7006d1f1258 - now https://github.com/rust-lang-nursery/libbacktrace/commit/e0abfecd2afb44c99bafec0434cb3d6d6322c25b

and I believe that's everything? The [stack of commits](https://github.com/rust-lang-nursery/libbacktrace/commits/rust-snapshot-2018-05-22) is the tip of the `rust-snapshot-2018-05-22` branch of that repo.

@kennytm I agree that eventually we want to move away from libbacktrace, but unfortunately that's a much larger change so for the time being I think an incremental update moving us towards the submodule should probably be sufficient

@steveklabnik do you want to update this PR to add a submodule to the repo I've created?

**Comment by alexcrichton** [comment]
@steveklabnik also while you're at it, can you update the backtrace and backtrace-sys crates?

**Comment by steveklabnik** [comment]
@alexcrichton I can do it tomorrow; if you want to just get it done, feel free to close this and do it yourself :)

**Comment by alexcrichton** [comment]
@bors: r+

No worries! I've pushed the changes here and let's see what bors thinks of this.

**Comment by steveklabnik** [comment]
Ugh, pinged @alexcrichton on chat about this; I didn't see that he updated the PR, so just did it and force pushed my version. Oops. Hopefully he can restore soon.

**Comment by alexcrichton** [comment]
🏒

**Comment by kennytm** [comment]
@bors retry 

All macOS jobs did not start (errored immediately).

**Comment by alexcrichton** [comment]
@bors: r+

Lots of build failures locally on cross platforms (and on crates.io), bespoke build system it is!

**Comment by nikic** [comment]
Since this commit I'm getting 150 ui test failures (also compile-fail, anything involving failures really). Some of them are segfaults (sample backtrace: https://gist.github.com/nikic/0b752e8aecf12930e488bbfc9bfbd7f1). Most are "panicked while panicking", with the partial trace looking something like

```
stack backtrace:
   0:     0x7f8e3cd9bc2e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::ha82b397ea71be585
   1:     0x7f8e3cd71796 - std::sys_common::backtrace::print::h0f02aefa57d1295d
   2:     0x7f8e3cd782bd - std::panicking::default_hook::{{closure}}::hb248860985868cdd
   3:     0x7f8e3cd78030 - std::panicking::default_hook::h0dd63170d2171fd8
   4:     0x7f8e393070d5 - rustc::util::common::panic_hook::h5a856d10e946cf82
   5:     0x7f8e3cd78943 - std::panicking::rust_panic_with_hook::h470a7ba29e7f6e22
   6:     0x7f8e3cd7853c - std::panicking::begin_panic_fmt::hdda42c41c88b4167
   7:     0x7f8e3cd78501 - rust_begin_unwind
   8:     0x7f8e3cdcf722 - core::panicking::panic_fmt::hd47ce5be3b71cd97
   9:     0x7f8e3d15c4a5 - core::result::unwrap_failed::h38f2e7889fea9e60
  10:     0x7f8e3d182df4 - <arena::TypedArena<T> as core::ops::drop::Drop>::drop::h694e59aa0a4a1d47
  11:     0x7f8e3d0da9cc - core::ptr::drop_in_place::h0d7fde6281af2c84
  12:     0x7f8e3d0eeaf9 - rustc_driver::driver::compile_input::he84fc71bb26c3ae0
  13:                0x3 - <unknown>
thread panicked while panicking. aborting.
```

In both cases the trace contains a weird low-address function (0x1 for the segfault, 0x3 for the panic).

I checked that this happens with 74d09399c1289a20b1c258153f005f2604f9ec46 but not 4f99f37b7e213d69a489884f651adfc6d217cef5.

**Comment by kennytm** [comment]
@nikic Could you file a new issue about this?

**Comment by nikic** [comment]
@kennytm Done in #51295 :)

**Pull request merged**
