### PR TITLE
move skolemized regions into global tcx

### PR DESCRIPTION
**Pull request by nikomatsakis**
Experimental branch to move skolemized regions into global tcx. This is probably not what we want long term but may be convenient to unblock @sgrif in the short term.

I'd like to do a perf run, though the main concern I guess would be memory usage.

r? @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
(I think that when all is said and done we can again confine skolemized things to the local tcx)

**Comment by nagbot-rs** [comment]
@bors: retry

* crates.io was down

**Comment by kennytm** [comment]
@bors r-

CI error is legit.

**Pull request merged**
