### PR TITLE
Remove std::io::lazy::Lazy in favour of SyncOnceCell

### PR DESCRIPTION
**Pull request by m-ou-se**
The (internal) std::io::lazy::Lazy was used to lazily initialize the stdout and stdin buffers (and mutexes). It uses atexit() to register a destructor to flush the streams on exit, and mark the streams as 'closed'. Using the stream afterwards would result in a panic.

Stdout uses a LineWriter which contains a BufWriter that will flush the buffer on drop. This one is important to be executed during shutdown, to make sure no buffered output is lost. It also forbids access to stdout afterwards, since the buffer is already flushed and gone.

Stdin uses a BufReader, which does not implement Drop. It simply forgets any previously read data that was not read from the buffer yet. This means that in the case of stdin, the atexit() function's only effect is making stdin inaccessible to the program, such that later accesses result in a panic. This is uncessary, as it'd have been safe to access stdin during shutdown of the program.

---

This change removes the entire io::lazy module in favour of SyncOnceCell. SyncOnceCell's fast path is much faster (a single atomic operation) than locking a sys_common::Mutex on every access like Lazy did.

However, SyncOnceCell does not use atexit() to drop the contained object during shutdown.

As noted above, this is not a problem for stdin. It simply means stdin is now usable during shutdown.

The atexit() call for stdout is moved to the stdio module. Unlike the now-removed Lazy struct, SyncOnceCell does not have a 'gone and unusable' state that panics. Instead of adding this again, this simply replaces the buffer with one with zero capacity. This effectively flushes the old buffer *and* makes any writes afterwards pass through directly without touching a buffer, making print!() available during shutdown without panicking.

---

In addition, because the contents of the SyncOnceCell are no longer dropped, we can now use `&'static` instead of `Arc` in `Stdout` and `Stdin`. This also saves two levels of indirection in `stdin()` and `stdout()`, since Lazy effectively stored a `Box<Arc<T>>`, and SyncOnceCell stores the `T` directly.

### CODE REVIEW

**Comment by m-ou-se** [comment]
Two interesting minor differences before/after:

---

1:

```rust
use std::{thread, io, mem, time::Duration};

fn main() {
    print!("hello");
    thread::spawn(|| mem::forget(io::stdout()));
    thread::sleep(Duration::from_secs(1));
}
```
Before this change, this outputs nothing: The Arc count does not drop back to 0, the stdout buffer is not dropped/flushed.
After this change, this propefly flushes the stream, and outputs `hello`. Improvement!

---

2:

```rust
use std::{thread, io, mem, time::Duration};

fn main() {
    print!("hello");
    thread::spawn(|| mem::forget(io::stdout().lock()));
    thread::sleep(Duration::from_secs(1));
}
```
Before this change, this outputs `hello`, while after this change, this no longer flushes the stream and outputs nothing. This seems like a regression. However: This only worked because the whole `ReentrantMutex` in the `Arc` was dropped (thus flushing the buffer), even though the `ReentrantMutex` inside there was still locked (since a guard was leaked). This might have been unsound: destroying a locked mutex can be [undefined behaviour with posix pthreads](https://pubs.opengroup.org/onlinepubs/007904975/functions/pthread_mutex_destroy.html).

**Review by dtolnay — APPROVED** [review]
This looks amazing to me. Thank you @m-ou-se!

**Comment by dtolnay** [comment]
To get some eyes on the externally observable behavior changes in https://github.com/rust-lang/rust/pull/77154#issuecomment-698495414:
@rfcbot fcp merge

**Comment by withoutboats** [comment]
IMO all the externally visible differences are bug fixes. This is great!

**Comment by m-ou-se** [comment]
#77212 failed on this PR for `auto (wasm32, ubuntu-latest-xl)`:

```
failures:

---- [ui] ui/stdout-during-shutdown.rs stdout ----
diff of run.stdout:

-	hello, world!


The actual run.stdout differed from the expected run.stdout.
Actual run.stdout saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/stdout-during-shutdown/stdout-during-shutdown.run.stdout
normalized run.stderr:
stdio streams had content in them that was not flushed. you should set EXIT_RUNTIME to 1 (see the FAQ), or make sure to emit a newline when you printf etc.
```

Apparently that target has trouble with atexit and output without a newline, which is exactly the point of the test. See [this](https://emscripten.org/docs/getting_started/FAQ.html#what-does-exiting-the-runtime-mean-why-don-t-atexit-s-run):

>By default Emscripten sets EXIT_RUNTIME=0, which means that we don’t include code to shut down the runtime. That means that when main() exits, we don’t flush the stdio streams, or call the destructors of global C++ objects, or call atexit callbacks.

I'll disable the test for this platform.

**Comment by RalfJung** [comment]
Maybe add comments explaining why this is ignored?

**Comment by m-ou-se** [comment]
> Maybe add comments explaining why this is ignored?

Done.

It might be the case that adding this in the test would also solve it:

```rust
#[cfg(target_os = "emscripten")]
#[link_args = "-s EXIT_RUNTIME=1"]
extern "C" {}
```

But I'm unable to test this locally. And I don't think this test really matters on emscripten.

**Pull request merged**
