### PR TITLE
misc doc improvements for std::env

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by aidanhs** [comment]
Hi @tshepang, it looks like your PR has failed CI with
```
[00:44:07] Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
[00:44:07]    Compiling linkchecker v0.1.0 (file:///checkout/src/tools/linkchecker)
[00:44:10]     Finished release [optimized] target(s) in 2.77 secs
[00:44:10] Documenting standalone (x86_64-unknown-linux-gnu)
[00:44:10] Linkcheck (x86_64-unknown-linux-gnu)
[00:44:11] std/env/fn.join_paths.html:57: broken link - std/env/containing%20an%20error%20message
[00:44:16] thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49
[00:44:16] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:44:16] 
[00:44:16] 
[00:44:16] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[00:44:16] expected success, got: exit code: 101
```

Could you take a look? Looking at your diff, I guess markdown isn't able to figure that the subsequent brackets aren't the link.

**Comment by tshepang** [comment]
@aidanhs thanks for that bit of guidance

**Comment by BurntSushi** [comment]
LGTM. Thanks! @bors r+

**Comment by Mark-Simulacrum** [comment]
```
[01:05:59]      Running build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/concurrent-4e888deb515d5802
[01:05:59] 
[01:05:59] running 10 tests
[01:06:00] test concurrent_installs ... FAILED
[01:06:00] test git_same_repo_different_tags ... ok
[01:06:01] test debug_release_ok ... ok
[01:06:02] test multiple_installs ... ok
[01:06:03] test git_same_branch_different_revs ... ok
[01:06:04] test killing_cargo_releases_the_lock ... ok
[01:06:04] test no_deadlock_with_git_dependencies ... ok
[01:06:04] test one_install_should_be_bad ... ok
[01:06:05] test multiple_registry_fetches ... ok
[01:06:05] test same_project ... ok
[01:06:05] 
[01:06:05] failures:
[01:06:05] 
[01:06:05] ---- concurrent_installs stdout ----
[01:06:05] 	thread 'concurrent_installs' panicked at '
[01:06:05] Expected: execs
[01:06:05]     but: exited with exit code: 101
[01:06:05] --- stdout
[01:06:05] 
[01:06:05] --- stderr
[01:06:05]     Updating registry `file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t0/registry`
[01:06:05]     Blocking waiting for file lock on the registry index
[01:06:05] error: could not find `foo` in `registry https://github.com/rust-lang/crates.io-index`
[01:06:05] ', /cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31
[01:06:05] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:05] 
[01:06:05] 
[01:06:05] failures:
[01:06:05]     concurrent_installs
[01:06:05] 
[01:06:05] test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured
[01:06:05] 
[01:06:05] error: test failed, to rerun pass '--test concurrent'
```

I've seen this before, I think, but not sure.

@bors retry

**Comment by alexcrichton** [comment]
@Mark-Simulacrum that was fixed in https://github.com/rust-lang/cargo/pull/4051 , updated in rust-lang/rust in https://github.com/rust-lang/rust/pull/42039 and accidentally reverted in https://github.com/rust-lang/rust/pull/42073

I'll send another PR to update

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/40474 network weirdness

**Pull request merged**
