### PR TITLE
Don't lint numeric overflows in promoteds in release mode

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb 

mitigates #50814

### CODE REVIEW

**Comment by eddyb** [comment]
cc @nikomatsakis I don't think this is a complete solution, but is it even on the right path?

**Comment by oli-obk** [comment]
Repeating my statement from IRC:

This might leak memory/not run destructors.

I don't see the issue with that, because to reach this code, you have to ignore a lint (soon to be deny-by-default) in order to get here.

Yes this might be happening in a dependency, but right now you can only reach this by either doing UB (or at least very shady unsafe stuff) inside a constant or comparing addresses of constant values inside a constant.

**Comment by oli-obk** [comment]
Ok... so the errors that are happening here make it seem to me like this is not the way to go. This would become a very messy codegen_llvm solution.

I just left in the regression part

**Comment by oli-obk** [comment]
@bors r=eddyb

just a test that needed adjusting

**Pull request merged**
