### PR TITLE
Remove weird Cell example from InvariantType docs

### LINKED ISSUE #20147: Documentation example for InvariantType is strange
http://doc.rust-lang.org/std/kinds/marker/struct.InvariantType.html

It starts talking about cell for some reason. I think this was copy + pasted from InvariantLifetime and never updated.

### PR DESCRIPTION
**Pull request by leejunseok**
Should fix #20147

P.S. This is my first PR in the history of ever. Please let me know if I'm doing anything wrong.

### CODE REVIEW

**Comment by huonw** [comment]
Hi there! Thanks for the PR. Everything looks in order, but I'm not sure this example deserves to be removed.

cc @steveklabnik

**Comment by leejunseok** [comment]
Woops, I'm sorry, I probably should've asked around a little before making the changes.

**Comment by steveklabnik** [comment]
I don't know much about `InvariantType`, but I think this looks good to me :+1:

**Comment by steveklabnik** [comment]
@leejunseok some odd commits have crept in here, can you rebase and sqaush? r=me after

**Comment by leejunseok** [comment]
hrm, sorry git still isn't quite natural to me, I'm trying to get my history sorted out.

**Comment by leejunseok** [comment]
I didn't know how to sync rust-lang/rust and my own rust (along with my local repo) and I ended up doing something very strange to my repo. I've figured it out now, but my history was too mangled for me to save. I'll open another PR!

Sorry about the inconvenience!

**Pull request closed without merging**
