### PR TITLE
wasi: round up the size for `aligned_alloc`

### PR DESCRIPTION
**Pull request by cuviper**
C11 `aligned_alloc` requires that the size be a multiple of the
alignment. This is enforced in the wasi-libc emmalloc implementation,
which always returns NULL if the size is not a multiple.
(The default `MALLOC_IMPL=dlmalloc` does not currently check this.)

### CODE REVIEW

**Comment by thomcc** [comment]
Note that this behavior has been proposed to change, so we should consider reverting this in the future if https://open-std.org/JTC1/SC22/WG14/www/docs/n2072.htm is standardized.

**Comment by cuviper** [comment]
> we should consider reverting this in the future if n2072 is standardized.

We could... but I wouldn't bother unless there's some evidence that it's *useful*, and not just the allocator rounding up on your behalf or otherwise wasting that padding.

**Comment by thomcc** [comment]
It's definitely useful, to the point where it's surprising this restriction exists.

Consider allocating 1 byte at alignment 1024 from a bump nursery (this is true for other types of allocators as well but less easy to show). You'd `(curptr + 1023) & !1023`, which will waste between 0 and 1023 bytes. If you round the size up to 1024 even though you only need 1 byte, you waste between 1024 and 2047 bytes.

**Comment by RalfJung** [comment]
> C11 aligned_alloc requires that the size be a multiple of the
alignment. 

FWIW, I can't find this requirement in C18 or C23 any more, so wasi may have to be updated here.

**Pull request merged**
