### PR TITLE
Default Type Parameter Fallback: Revival

### PR DESCRIPTION
**Pull request by leoyvens**
See #27336 for background. This is about using type parameter defaults to inform inference. This was once implemented in #26870. It turns out there were issues with the design, the implementation was finally removed in #40570. But this feature is awesome and we should not let it die.

As discussed in the tracking issue, we want adding defaults to type parameters to be backwards compatible, but the original design did not take this into account. @eddyb suggests that we future-proof this by not applying a fallback where a conflict could possibly occur. That would make defaults on fns and impls pretty much useless. So [I suggested](https://github.com/rust-lang/rust/issues/27336#issuecomment-344069120) that we invert the situation and give priority to the defaults on fns and impls, taking care to be future-proof. For details of how this is done see the comments and implementation in `fn apply_user_type_parameter_fallback`. The tests show what works and what doesn't under this design. Numeric and diverging fallbacks take precedence over user supplied fallbacks.

Does this need an RFC? Does the RFC block accepting the PR? Should it be an ammendment to RFC 213?

A gotcha:
As commented in the test `trait_impl.rs`, if a type var is partially inferred then it's default will not be considered. For example if we know that `T == Vec<U>` then the default for `T` will be ignored while the default of `U` may apply. This avoids conflicting defaults and is consistent with not applying user fallbacks for numerics, a numeric var can be seen as having been partially inferred.

Error messages:
If fallback fails, we preserve the error message that would occur if no fallback was present, so "type annotations needed" or "the type of this value must be known in this context". A custom error message would be complicated to craft and would not be useful as most of the time the only thing the user can do is annotate a type.
To preserve error messages I need to rollback any constraints made when trying to solve defaults. Currently everything is rolled back on any failure, throwing away any successes along with it. This is bad but we can easily implement a heuristic that solves the easy cases and bundles only the hard cases together, making pathological cases rare. So I'm satisfied with this strategy.

Todo:
1. Implement the heuristic for avoiding rolling back successes.
3. Not working for defaults in type aliases.
4. Fix interaction with specialization described below.
5. Decide if the behaviour in `trait_def_rules_over_impl.rs` is expected. If so, forbid writing defaults in implementations of trait methods.

The first commits are a rebase an old branch by @jroesch and @nikomatsakis. I ended up not salvaging much, but some refactorings were useful.

Disclaimer: I'm learning as I go, I'm not really familiar with any of this stuff.

### CODE REVIEW

**Comment by leodasvacas** [comment]
@kennytm tidy thinks some `.rs` test files are binary files, what do?

**Comment by kennytm** [comment]
@leodasvacas Run `chmod a-x path/of/those/files.rs` and then commit them again.

**Comment by leodasvacas** [comment]
@kennytm Those UI tests pass locally but fail on travis, I generated all the outputs with the command suggested when the test fails. Do you know what I can do here?

**Comment by leodasvacas** [comment]
I've tested the interaction with specialization, and the following interaction is concerning:
```rust
#![feature(default_type_parameter_fallback)]
#![feature(specialization)]

use std::fmt::Debug;

trait B { fn b(&self) -> Self; }

default impl<T=String> B for Option<T> where T: Default
{
    fn b(&self) -> Option<T> {
        Some(T::default())
    }
}
// When there specialized but generic impls, their defaults
// are ignored no matter what they are.
// This code does not compile because `x` in main fails to infer.
// However if we commented out this impl, `x` would be inferred to `String`.
// This is bad because specialization may break inference fallback,
// and I think we guarantee specialization won't break any code.
impl<T=String> B for Option<T> where T: Default + Debug
{
    fn b(&self) -> Option<T> { Some(T::default()) }
}

fn main() {
    let x = None;
    let y = x.b();
}
```
Options:
1. Pick an impl and apply its default. The most specialized impl? The most specialized impl that has a default? Is there even a concept of "most specialized" with lattice specialization? I'm not familiar with trait selection so I don't know if this sort of fix is feasible.
2. Forbid defaulting of type params that appear in the target of a trait impl. This is not so bad as they would be treated as ordinary inference variables, unable to interfere with fallback selection but still able to benefit from it.

**Comment by nikomatsakis** [comment]
Sorry for not commenting. It was thanksgiving, and now I've been traveling. I haven't had a chance to look or think deeply about this proposal, but I feel some level of skepticism. In part this is because I've become very skeptical on the idea of defaulted type parameters in general, and also because I feel like we've been approaching their design in a bit of a ... haphazard way. I'd like to see an RFC (or at least "proto RFC") that clearly lays out the **motivation** for such changes, enumerating the use cases we are trying to fix and those we are not, and also lays out the possible dangers for "incoherence" and describes how they are addressed. That said, I don't want to have pure stop energy here, I also like the idea (in general) of iterating in tree, so I'll try to give this PR the time it deserves in a day or two!

**Comment by leodasvacas** [comment]
@nikomatsakis Thanks for the comment! I'll write that pre-RFC, but it may take some time. Also it's easier to discuss an RFC with an implementation available on nightly.
 
I'm realizing that the big issue with the original implementation was not so much future-proofing against conflicts but more the fact that we tried defaults every time we ran inference, leading to unpredictable results. That's fixed now that defaults are applied as a last resort.

It's seems better to focus on having a good story for adding a new type parameter with a default rather than on adding defaults to existing parameters. This makes the feature simpler and more powerful, and we don't really lose any use cases. I'll flesh out the full design in an RFC. This PR remains entirely relevant anyways, it's a small adjustment to the algorithm.

**Comment by shepmaster** [comment]
Ping from triage! It's been over 7 days since we heard from reviewer @nikomatsakis. Please assign a new reviewer @rust-lang/compiler.

**Comment by kennytm** [comment]
Ping from triage @nikomatsakis! I see that you commented in https://github.com/rust-lang/rust/pull/46714#issuecomment-351711936. Is there any update from that?

**Comment by leodasvacas** [comment]
It's not clear whether this needs an RFC, but some structured rationale would help this PR. Niko and me will schedule a chat to see how to move this forward. Thanks triage guys for the pings!

**Comment by alexcrichton** [comment]
@leodasvacas looks like there may be some merge conflicts now?

**Comment by leodasvacas** [comment]
@alexcrichton Thanks for the triage! This is S-blocked at the moment as Niko and me still need to schedule a chat.

**Comment by leodasvacas** [comment]
After meeting with Niko we've decided it's best not to land anything until we get a new design through as an RFC. So closing until that happens.

**Pull request closed without merging**
