### PR TITLE
Make the return type of `Fn` trait an associated type

### LINKED ISSUE #20871: Make return type of the `Fn` traits an associated type
I think that the argument types cannot be an associated type, but the return type of the `Fn` traits can and ought to be.

### Why make the return type associated?

It seems right: I don't think I want the ability to have functions overloaded purely on return type. A similar argument was [gracefully made by @aturon regarding binary operators recently](http://discuss.rust-lang.org/t/implicit-widening-polymorphic-indexing-and-similar-ideas/1141/15?u=nikomatsakis).

But also, it would make an impl like example (from @alexcrichton) legal:

```rust
impl<R,F> Foo for F : FnMut() -> R { ... }
```

Right now this is illegal because the type `R` is unconstrained. This is kind of counter-intuitive.

### Why not make the argument types associated?

The reason that the argument types cannot be associated is because of HRTB. Imagine we have a constraint like `F : Fn(&i32) -> &i32`. Now, if both `A` and `R` were associated types, we'd have to be able to evaluate independent projections like `F::A` and `F::R` but ensure that we got consistent lifetimes in both cases -- unfortunately, we can't do that, because there is nothing linking the lifetimes together. Put another way, if `A` and `R` were associated types, then `F : Fn(&i32) -> &i32` would be sugared into three predicates internally:

- `F : Fn`
- `for<'a> <F as Fn>::A == &'a i32`
- `for<'b> <F as Fn>::R == &'b i32`

Note that the connection between A and R has been lost. (While implementing associated types, I spent a while trying to make this work out, and it really...just doesn't.)

On the other hand, if we convert *just* the return type to be an associated type, the example works just fine. We desugar the `F : Fn(&i32) -> &i32` example into:

- `for<'a> F : Fn<(&'a i32,)>`
- `for<'a> <F as Fn<(&'a i32,)>>::R == &'a i32`

Another reason not to make the argument types associated is that it permits more overloading. For example, the "identity" function works (hat tip: @eddyb):

```rust
struct Identity;
impl<A> Fn(A) for Identity {
    type R = A;
    fn call(&self, (arg,): (A,)) -> A {
        arg
    }
}
```

cc @aturon @huonw

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes https://github.com/rust-lang/rust/issues/20871

r? @aturon (at least until we decide definitively if this is a good idea)

### CODE REVIEW

**Comment by alexcrichton** [comment]
In terms of the sugar, does this limit us to the possibilities of the `Trait(A, B) -> C` desugaring later? It kinda semantically makes sense to me that the inputs are type parameters and the output is an associated type, but it seems like our desugaring would look like:

```
where F: A(B) -> C
// equivalent to
where F: A<B, FirstAssociatedType=C>
```

which is a little odd, but perhaps not the end of the world!

**Comment by sfackler** [comment]
Tidy failure https://travis-ci.org/rust-lang/rust/builds/46746709

**Comment by nikomatsakis** [comment]
@alexcrichton that is precisely what the desugaring amounts to in this version. The fact that `Fn(A) -> B` desugars to `Fn<(A,), Output=B>` doesn't seem particularly odd to me by itself (but read on). @eddyb even had the interesting idea that we could extend the `->T` sugar to always mean `Output=T` so that one could write `Add<R> -> S` instead of `Add<R, Output=S>`.

There is however one thing I wasn't crazy about: sometimes you won't want to constrain the output of the function. In that case, the existing desugaring doesn't give you that option, so you have to opt out of the sugar altogether.

For example, the `Map` adapter is written today:

```rust
struct Map<A,B,I,F>
    where I : Iterator<Item=A>, F : FnMut(A) -> B
{
    iter: I,
    fn: F
}

impl<A,B,I,F> Iterator<B> for Map<I,F>
    where I : Iterator<Item=A>, F : FnMut(A) -> B
{ ... }
```

Under this scheme it could be simplified to:

```rust
struct Map<I,F>
    where I : Iterator, F : FnMut<(I::Item,)>
{
    iter: I,
    fn: F
}

impl<I,F> Iterator<F::Output> for Map<I,F>
    where I : Iterator, F : FnMut<(I::Item,)>
{
}
```

I definitely like having fewer type parameters, but the difference between `FnMut(I::Item)` and `FnMut<(I::Item),>` feels...subtle. But at the same time having `FnMut(I::Item)` not bind the result type seems like a non-starter, too inconsistent with other things (and in particular it'd bite us in object type syntax: `Box<FnMut()>` would be an error, since the `Output` type is not bound).

On the other hand, if one preferred, one could never use the non-sugared form, at the cost of more type parameters:

```rust
struct Map<B,I,F>
    where I : Iterator, F : FnMut(I::Item) -> B
...
```

so in some sense it's no worse than today, just gives you the option to do better.

**Comment by alexcrichton** [comment]
Whoa! That is very interesting about the difference between `Fn<(Foo,)>` and `Fn(Foo)`, I had to read this a few times before it clicked.

For now we don't even necessarily have to have all the parameters on `Map`, we could just remove the where clause and then add the type parameters to the `impl` blocks I think?

**Comment by nikomatsakis** [comment]
@alexcrichton yes, we could.

**Comment by nikomatsakis** [comment]
I've decided to open an RFC for this. Better to err on the side of more RFCs, I figure.

**Comment by nikomatsakis** [comment]
@alexcrichton in fact we cannot remove the parameters on map today, due to the fact that `B` parameter in the impl would be unconstrained, precisely because the return type of the `Fn` trait is not an associated type.

**Comment by nikomatsakis** [comment]
RFC has landed now. Rebased, testing the build now. I had to add a fix for #21664 (which is now at the front of the PR series) because recent changes exposed that problem when combined with this change.

**Comment by brson** [comment]
breaking change

**Pull request merged**
