### PR TITLE
Check implementing type for `#[doc(hidden)]`

### LINKED ISSUE #85526: `missing_docs` lint does not take into account the implementing type being `#[doc(hidden)]`
I tried [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fbce6f3fc24a28d741173d074e9d5e3b):

```rust
#![warn(missing_docs)]

//! Crate docs

#[doc(hidden)]
pub struct Foo;

impl Foo {
    pub fn bar() {}
}
```

I expected to see this happen: no warnings, `Foo` and its method are not publicly documented.

Instead, this happened:

```
warning: missing documentation for an associated function
 --> src/lib.rs:9:5
  |
9 |     pub fn bar() {}
  |     ^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:1:9
  |
1 | #![warn(missing_docs)]
  |         ^^^^^^^^^^^^

warning: 1 warning emitted
```

### PR DESCRIPTION
**Pull request by pierwill**
Closes #85526.

### CODE REVIEW

**Comment by camelid** [comment]
r? rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Apart from the nit, looks good to me, thanks for the improvement/fix! Feel free to r+ if you think the suggestion I made isn't worth it.

**Comment by pierwill** [comment]
@GuillaumeGomez Is it alright if I like the original code a little better? 😇 (Also, I don't have `r+` privileges 😇 😇 .)

**Comment by pierwill** [comment]
Done.

**Comment by GuillaumeGomez** [comment]
I'm the one who implemented it, so I guess it's the reason? ;)

**Pull request merged**
