### PR TITLE
Update comment regarding SO_REUSEADDR on Windows

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by reitermarkus** [comment]
Seems like `SO_REUSEADDR` actually exists on Windows.

**Comment by Mark-Simulacrum** [comment]
Hm, so some rough searching online suggests that Windows may not actually want this set (e.g. [this random github thread](https://github.com/warmcat/libwebsockets/issues/65)). 

I myself don't have much windows experience so I'm not willing to approve this just yet. I'll leave myself assigned as I don't know if we have anyone better at this time.

cc @retep998

**Comment by reitermarkus** [comment]
I also don't really have any Windows experience, just stumbled upon this while implementing `libstd` for another target.

So either this should be used or the constant removed.

**Comment by retep998** [comment]
From the very MSDN article that you linked:

> The SO_REUSEADDR option has very few uses in normal applications aside from multicast sockets where data is delivered to all of the sockets bound on the same port. Otherwise, any application that sets this socket option should be redesigned to remove the dependency since it is eminently vulnerable to "socket hijacking". As long as SO_REUSEADDR socket option can be used to potentially hijack a port in a server application, the application must be considered to be not secure.

While on non-windows platforms `SO_REUSEADDR` allows you to bind to sockets that are still in `TIME_WAIT`, on Windows `SO_REUSEADDR` allows you to bind to sockets that are *actively being used* resulting in undefined behavior.

So no, we do not want this change. A change which we should consider though is setting `SO_EXCLUSIVEADDRUSE` for all our sockets.

**Comment by Mark-Simulacrum** [comment]
Okay, yeah, that's what I suspected based on the GitHub thread. My skimming must have missed that on the MSDN page.

I would appreciate an update to this PR which includes a note that links to the MSDN page and summarizes why we don't want it.

**Comment by lzutao** [comment]
This PR could change to document that for Windows.

**Comment by reitermarkus** [comment]
Ok, I reverted the change and added an explanation as to why we don't set it on Windows.

**Pull request merged**
