### PR TITLE
Update release notes for 1.19.0

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This is just #42503 there is some problems with submodules I can't seem to fix so I just created a new PR.

### CODE REVIEW

**Comment by kennytm** [comment]
This one needs a p=1 or something. It is currently at the last place of the queue.

**Comment by Mark-Simulacrum** [comment]
It's just going into master though? Presumably not all that important, but seeing as the other PR was p=100...

@bors p=100

**Comment by Aaronepower** [comment]
@Mark-Simulacrum Does it not need to go on `origin/beta`?

**Comment by Mark-Simulacrum** [comment]
Not sure. @alexcrichton or @brson should know.

**Pull request merged**
