### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by 0xPoe**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

### CODE REVIEW

**Comment by eddyb** [comment]
This is not an (accidental) typo, i.e. I wasn't aware of "evaluable" (which my spellchecker doesn't think is a real word, coincidentally) and [I'm not the first person](https://english.stackexchange.com/questions/304948/evaluable-vs-evaluatable) to fall prey to this conundrum.

In fact, the oldest of these occurrences, AFAICT, comes from https://github.com/rust-lang/rust/commit/35c261aea0d891d31b3fda83da653cb1e385681f#diff-268f3645af45ee52080a7d24acb217ddR52 by @nikomatsakis.

cc @rust-lang/compiler (I'm fine with this changing, as long as we can agree "evaluatable" is wrong)

**Comment by eddyb** [comment]
Ah, I am being informed that `evaluatable` is a word: https://en.wiktionary.org/wiki/evaluatable (at least in a *mathematical* sense, which feels appropriate here).

So we can probably close the PR, unless we want to have more discussion on the topic.

**Comment by nikomatsakis** [comment]
I....am surprised to learn that 'evaluable' is a word. =) I prefer evaluatable somehow, it seems more obvious. The spell checker doesn't seem to know either of them

**Comment by varkor** [comment]
I was previously under the impression that "evaluable" was a word and "evaluatable" was not; the Oxford English Dictionary [has "evaluable"](https://www.oed.com/view/Entry/65180) but not "evaluatable". But perhaps this is the British English spelling 😁

**Comment by Rustin-Liu** [comment]
Beacuse my IDE(Clion) spell checker doesn't know "evaluatable", so I rename it. It seems many dictionaries and search engines don't know this word. But please feel free to close this PR if you think this change is unnecessary.

**Comment by crlf0710** [comment]
Triaging here. According to opinions from t-compiler, this is not considered a typo, so i'll go ahead and  close this. If you want to raise more discussions, feel free to open a topic on Zulip!

**Pull request closed without merging**
