### PR TITLE
[BETA] revert leak check changes

### LINKED ISSUE #125194: regression: trait bound not satisfied
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/blades-0.5.0/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/kino-mc.rsmt2/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/rsmt2-0.16.2/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/kprav33n.aoc22.rs/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/rene-0.1.0/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/CallumJHays.quickdiff/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Heiss.blades-heading/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Punie.legend/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/cost-management.cost-management-api/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/grego.blades-katex-rs/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/o-santi.nixchess/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/robertohuertasm.yt-api-rest-actix-web/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/vorrarit.test-rust/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/blades-katex-0.1.2/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/etwin_forum_store-0.12.3/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/serde_flat_path-0.1.2/log.txt

```
[INFO] [stdout] error[E0277]: the trait bound `for<'a> beef::generic::Cow<'a, str, beef::wide::internal::Wide>: Borrow<beef::generic::Cow<'_, str, lean::internal::Lean>>` is not satisfied
[INFO] [stdout]    --> src/page.rs:433:18
[INFO] [stdout]     |
[INFO] [stdout] 433 |             .get(template)
[INFO] [stdout]     |              --- ^^^^^^^^ the trait `for<'a> Borrow<beef::generic::Cow<'_, str, lean::internal::Lean>>` is not implemented for `beef::generic::Cow<'a, str, beef::wide::internal::Wide>`
[INFO] [stdout]     |              |
[INFO] [stdout]     |              required by a bound introduced by this call
[INFO] [stdout]     |
```

likely #119820 cc @lcnr, this was intended breakage afaik

### PR DESCRIPTION
**Pull request by lcnr**
reverts the behavior changes from https://github.com/rust-lang/rust/pull/119820 to give `sqlx` and other affected projects another 6 weeks.

Fixes #125194 #126006

### CODE REVIEW

**Comment by compiler-errors** [comment]
r=me, unless you think my approval is fine on its own.

**Comment by lcnr** [comment]
cc @davidtwco @wesleywiser not sure how to handle types team backports? should we just land them without any additional input or should we also let them go through the compiler team meeting?

**Comment by jackh726** [comment]
(FWIW, I think the last thing we decided was that T-types can make their own backport decisions, but usually just delegate it back to T-compiler)

That being said, I don't care either way about waiting a couple days for this, or just landed this now. This is a pretty cut and dry decision imo.

**Comment by lcnr** [comment]
backport approved https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-05-30/near/441466538

can I jsut use `r=compiler-errors` on beta PRs :sweat_smile: haven't filed one in a while

**Comment by cuviper** [comment]
> can I just use `r=compiler-errors` on beta PRs 😅 haven't filed one in a while

Usually beta PRs are backports from master, and someone on the release team will do a pseudo-rollup of several backports at once. But if you're targeting beta only then I think it's fine for you to go ahead with a direct reviewer.

(cc @rust-lang/release in case others feel differently)

**Pull request merged**
