### PR TITLE
fix u32 steps_between for 16-bit systems

### LINKED ISSUE #48006: Memory Unsafety on 16bit Platforms for Range.collect()
`TrustedLen` is implemented for Range<T> [for every integer primitve T](https://doc.rust-lang.org/nightly/src/core/iter/range.rs.html#282). TrustedLen [requires](https://doc.rust-lang.org/nightly/std/iter/trait.TrustedLen.html) that the upper bound of `.size_hint` is None if the iterator produces more than `usize::MAX` elements. `<Range as Iterator>.size_hint` [uses `steps_between`](https://doc.rust-lang.org/nightly/src/core/iter/range.rs.html#235) to produce its result. The [implementation](https://doc.rust-lang.org/nightly/src/core/iter/range.rs.html#117) of `steps_between` subtracts the lower from the upper value and casts it to usize. This is [implemented undconditionally](https://doc.rust-lang.org/nightly/src/core/iter/range.rs.html#168) for u32. On 16bit platforms, the result of the subtraction of two u32 values may not fit inside `usize`, producing an invalid `size_hint`.
This means, that e.g. collecting into a Vec using its [`SpecExtend::spec_extend` specialization for TrustedLen](https://doc.rust-lang.org/nightly/src/alloc/vec.rs.html#1839) allows writing beyond its reserved buffer. One such example input would be `(0..(usize::MAX as u32 + 1)).collect::<Vec<_>>()`.

Reference: https://github.com/rust-lang/rust/pull/47944#discussion_r165844199
/cc @bluss

### PR DESCRIPTION
**Pull request by llogiq**
This fixes #48006.

### CODE REVIEW

**Comment by nagisa** [comment]
@bors r-

Seems like tests have failed.

r=me once fixed.

**Comment by llogiq** [comment]
Oops, it's `std::iter::Step`, not `std::ops::Step`. Let's see if this works...

**Comment by llogiq** [comment]
@nagisa this should now work, and hopefully we have at least one 16bit system to test this...

**Comment by nagisa** [comment]
Sadly, there are no CI runners that have `pointer_width = 16`, no.

@bors r+

**Pull request merged**
