### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #114111 (Improve test case for experimental API remove_matches)
 - #114169 (refactor builtin unsize handling, extend comments)
 - #114182 (clean up after 113312)
 - #114193 (Update lexer emoji diagnostics to Unicode 15.0)
 - #114200 (Detect trait upcasting through struct tail unsizing in new solver select)
 - #114228 (Check lazy type aliases for well-formedness)
 - #114267 (Map RPITIT's opaque type bounds back from projections to opaques)
 - #114269 (Migrate GUI colors test to original CSS color format)
 - #114286 (Add missing feature gate in multiple_supertrait_upcastable doc)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=114111,114169,114182,114193,114200,114228,114267,114269,114286)

### CODE REVIEW

**Comment by compiler-errors** [comment]
Why did like half of those PRs not get included in the rollup 💀

**Comment by matthiaskrgr** [comment]
Yeah something is weird, just noticed it now :|

**Comment by compiler-errors** [comment]
I guess it's fine, as long as those other PRs weren't closed by bors, they're just sitting waiting for the next rollup I guess. Maybe bors just didn't detect an unsuccessful merge, or something.

**Pull request merged**
