### PR TITLE
[beta] Prepare the 1.26.0 beta release

### PR DESCRIPTION
**Pull request by alexcrichton**
* Bump the bootstrap compiler to the stable release
* Update the channel to beta

### CODE REVIEW

**Comment by kennytm** [comment]
@bors retry 

```
sh src/ci/init_repo.sh . /c/cache/rustsrc
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Command exited with code 128
```

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/361362781). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
$ cat obj/tmp/sccache.log
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:158f2496:start=1522708520163151910,finish=1522708520170017480,duration=6865570
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0c52c69c
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:0c52c69c:start=1522708520176119604,finish=1522708520182731592,duration=6611988
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:000c8ce4
$ dmesg | grep -i kill
[   11.082471] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by alexcrichton** [comment]
@bors: r+

cc @kennytm, it looks like miri's failing build may be blocking this from landing originally?

**Pull request merged**
