### PR TITLE
Windows: Allow running processes whose path exceeds the legacy `MAX_PATH`

### PR DESCRIPTION
**Pull request by ChrisDenton**
On Windows `Command` currently fails when run using paths longer than the legacy `MAX_PATH`. This PR allows running such executables while leaving the behaviour of shorter paths unchanged.

This does not risk changing the behaviour of currently working code. It only allows something to work that would previously fail.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
It was pointed out to me that my previous implementation meant path would have slightly different behaviours, depending only on the length, because of the way `.exe` is, or isn't, appended after being passed to `CreateProcessW`. For the sake of consistency I've reunified long and short path handling.

Note that `CreateProcessW` has slightly weird rules here and Rust could certainly use a simpler strategy. However I'd rather not do that as a side effect of this change. So I've opted to maintain the existing behaviour for now.

**Comment by jyn514** [comment]
Cc @retep998

**Comment by ChrisDenton** [comment]
I now minded to close this PR in favour of doing a bigger overhaul of how `Command` looks for executables on Windows. On the [internals forum](https://internals.rust-lang.org/t/15015) there seems (so far) to be consensus that it should only look in PATH. Doing that manually would make this unnecessary.

**Pull request closed without merging**
