### PR TITLE
Make Solaris builder compatible with Solaris 10

### PR DESCRIPTION
**Pull request by bgermann**
Would it be possible to get this in the next 1.22.0 beta?

### CODE REVIEW

**Comment by kennytm** [comment]
1.22 beta has just been branched off, so we need to explicit nominate this to beta in order to get this in.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

This seems fine to backport if you'd like, want to send a PR to the beta branch once this lands?

**Comment by bgermann** [comment]
Yes.

**Pull request merged**
