### PR TITLE
Prevent Windows from displaying UI on errors.

### PR DESCRIPTION
**Pull request by vadimcn**
Otherwise tests like run-pass/out-of-stack get wedged on Windows error reporting dialog (unless error reporting has been disabled, of course).

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Could this be added to a different location though? It seems like we should always do this but there's a few early-return locations in the method where it was added.

**Comment by vadimcn** [comment]
Ok, I moved it to the top.

**Comment by vadimcn** [comment]
Per https://blogs.msdn.microsoft.com/oldnewthing/20040727-00/?p=38323, it's best to preserve inherited flags.
@bors: r=alexcrichton

**Pull request merged**
