### PR TITLE
Fix variable debuginfo being optimized away at `mir-opt-level=2 `

### LINKED ISSUE #103655: MIR optimizations at `mir-opt-level=2` remove some debuginfo
It looks like variables are being optimized away at `mir-opt-level=2` when they should be retained for debugging purposes. For example, in the following program, `a` and `b` are not known to the debugger (on any platform):

```rust
pub fn example() {
    let a = 1;
    let b = 16;
    
    foo(a + b); // break here
}

#[inline(never)]
fn foo(x: i32) {
    std::process::exit(x);
}
```

This appears to be the result of MIR optimizations as going from `-Zmir-opt-level=1` to `-Zmir-opt-level=2` causes the calls to `@llvm.dbg.value` to disappear:

```diff
define void @_ZN7example7example17h6142df5531d284b7E() unnamed_addr #0 !dbg !6 {
start:
-  call void @llvm.dbg.value(metadata i32 1, metadata !12, metadata !DIExpression()), !dbg !18
-  call void @llvm.dbg.value(metadata i32 16, metadata !15, metadata !DIExpression()), !dbg !19
  tail call fastcc void @_ZN7example3foo17he136a32a31d586dbE(), !dbg !20
  unreachable, !dbg !21
}
```

[godbolt](https://rust.godbolt.org/z/bKobYvcb5)

LLVM is able to perform this optimization while retaining debuginfo so we shouldn't interfere with that unless the user has opted into a higher level of MIR optimization where degrading debuggability is acceptable.

### PR DESCRIPTION
**Pull request by wesleywiser**
The `DeadStoreElmination` pass was removing the uses of these locals
because the are never used in the MIR body except for debuginfo. I've
updated the pass to consider locals referenced by debuginfo as always
alive unless a higher MIR opt level is requested by the user.

Fixes #103655 

r? @ghost

### CODE REVIEW

**Comment by JakobDegen** [comment]
According to rust-lang/compiler-team#319 , mir opt level 2 is not required to maintain debuggability. Has this changed?

**Comment by wesleywiser** [comment]
> According to [rust-lang/compiler-team#319](https://github.com/rust-lang/compiler-team/issues/319) , mir opt level 2 is not required to maintain debuggability. Has this changed?

It changed in https://github.com/rust-lang/rust/pull/82736 which was merged after that policy. I looked briefly but don't see our policy actually documented anywhere other than that closed MCP. I might take a stab at introducing an enum for `mir-opt-level` that maps the `0-4` levels to what they actually mean but first I want to see what kind of impact this has on compile times.

**Comment by JakobDegen** [comment]
I'm incredibly confused. When I [asked](https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/Meaning.20of.20MIR.20Opt.20Levels) about the policy on Zulip no one could seem to agree what it was, and now this PR is proposing another option. Certainly if this is right then lots of my commits to the repo have been wrong (although I'm not the only one). I also have some thoughts about a mir opt level policy that doesn't allow us to regress debuginfo on any opt level that users will realistically be turning on.

It seems like we need a new MCP on this topic, given that the previous one does not seem to have resolved this topic

**Comment by wesleywiser** [comment]
That's a fair concern! I agree, the current situation is very confusing, probably because we never really documented it anywhere and then was later modified without a clear explanation of the new level being introduced. Sorting this out via an MCP and then actually documenting it somewhere seems like a reasonable next step. 

At the same time, it seems like a bug to me that disabling MIR optimizations for code like that of the test gives you both better debuginfo and doesn't hurt code quality either (LLVM is able to perform this optimization just as well as we can but they do it while preserving debuginfo). If there isn't much of a compile time impact from this change, I think we should merge it.

**Comment by JakobDegen** [comment]
Sure, I don't feel particularly strongly about this PR specifically (although that may change in the future). That being said, do we know what is needed in order for us to fix debuginfo in the same way LLVM does?

**Comment by wesleywiser** [comment]
> I also have some thoughts about a mir opt level policy that doesn't allow us to regress debuginfo on any opt level that users will realistically be turning on.

Yet another option (sorry), would be to tie the presence of debuginfo in MIR to `-Cdebuginfo=2`. If the user isn't actually requesting debuginfo, I don't see a strong reason we should retain it in MIR. At the same time, if the user is specifically asking for debuginfo, then we should put some effort into not breaking it.

**Comment by wesleywiser** [comment]
> Sure, I don't feel particularly strongly about this PR specifically (although that may change in the future). That being said, do we know what is needed in order for us to fix debuginfo in the same way LLVM does?

I think I put a most of the infrastructure in place to support this in #73210 but it wasn't enabled because it wasn't working correctly on Windows. At the time, I knew nothing about Windows debuginfo so perhaps now I can resolve whatever that issue was. 😄

**Comment by JakobDegen** [comment]
I've been thinking for a while that optimization "levels" might be a pretty bad solution to the problem they're trying to solve. Maybe this is a good opportunity to revisit this problem from the beginning, start by figuring out what the use cases are that we're trying to support, and design from there

**Comment by wesleywiser** [comment]
Just trying to see what we need to do to recover the throughput (if possible).

@bors try @rust-timer queue

**Comment by JohnCSimon** [comment]
@wesleywiser Can you please post your status on this PR? It has sat idle for months.

**Comment by JohnCSimon** [comment]
@wesleywiser 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
