### PR TITLE
Unconditionally capture tokens for attributes.

### PR DESCRIPTION
**Pull request by Aaron1011**
This allows us to avoid synthesizing tokens in `prepend_attr`, since we
have the original tokens available.

We still need to synthesize tokens when expanding `cfg_attr`,
but this is an unavoidable consequence of the syntax of `cfg_attr` -
the user does not supply the `#` and `[]` tokens that a `cfg_attr`
expands to.

This is based on PR https://github.com/rust-lang/rust/pull/77250 - this PR exposes a bug in the current `collect_tokens` implementation, which is fixed by the rewrite.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/77250.

**Comment by Aaron1011** [comment]
A lot of the slowdown is probably due to https://github.com/rust-lang/rust/pull/77250

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/77250 has landed.

**Comment by Aaron1011** [comment]
@rust-timer build 67a0ba996f5e1d8ba58854397300e83feaf43de2

**Comment by Aaron1011** [comment]
cc @rust-lang/infra The try build completed, but Bors never left a comment.

**Comment by Aaron1011** [comment]
The performance impact is now less than 0.5%

@petrochenkov: This is now ready for review

**Pull request merged**
