### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #73210 ([mir-opt] Allow debuginfo to be generated for a constant or a Place)
 - #77268 (Link to "Contributing to Rust" rather than "Getting Started".)
 - #77488 (Mark `repr128` as `incomplete_features`)
 - #77918 (Cleanup network tests)
 - #77920 (Avoid extraneous space between visibility kw and ident for statics)
 - #77969 (Doc formating consistency between slice sort and sort_unstable, and big O notation consistency)
 - #78069 (Fix const core::panic!(non_literal_str).)
 - #78072 (Cleanup constant matching in exhaustiveness checking)
 - #78116 (Make inline const work in range patterns)
 - #78119 (Throw core::panic!("message") as &str instead of String.)
 - #78122 (Avoid panic_bounds_check in fmt::write.)
 - #78153 (Sync LLVM submodule if it has been initialized)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
retrying this so it runs automatically when the tree is reopened

@bors retry

**Comment by JohnTitor** [comment]
@bors retry
Re-created another rollup.

**Comment by JohnTitor** [comment]
So, the current queue is quite long and I created another rollup.
@bors r-

**Pull request closed without merging**
