### PR TITLE
Rolling up PRs in the queue

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @michaelwoerister, wasn't sure what to do with [this failure](http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/1743/steps/test/logs/stdio) so I just ignored the test on windows for now (it's passing locally on linux and OSX)

**Comment by alexcrichton** [comment]
cc @cgaebel, @pczarn, @Gankro, [this failure](http://buildbot.rust-lang.org/builders/auto-linux-32-nopt-t/builds/3247/steps/test/logs/stdio) seems pretty disturbing (internal hashmap error)

**Comment by cgaebel** [comment]
@alexcrichton Just ran that test case in a loop with rustc master and can't reproduce. Maybe it was a codegen bug in one of the intermediate patches...?

**Comment by alexcrichton** [comment]
I've seen it from time to time before (not sure if it's precisely the same assertion). I suspect that it will be pretty hard to reproduce due to the semi-random nature of `HashMap`. And perhaps it was an intermediate bug! Hard to know anything for sure :(

**Pull request merged**
