### PR TITLE
Add asm!() support for PowerPC64

### PR DESCRIPTION
**Pull request by DrChat**
I was anticipating this to be difficult so I didn't do it as part of #84732... but this was pretty easy to do 👀

### CODE REVIEW

**Comment by programmerjake** [comment]
@DrChat Libre-SOC has a 400 Euro bounty through nlnet.nl on adding `asm!` support for powerpc64le, do you want it?

https://bugs.libre-soc.org/show_bug.cgi?id=451

**Comment by DrChat** [comment]
Heh, oh really? Sure I'll claim it :) - I don't think it will be too difficult to do.

**Comment by programmerjake** [comment]
Ok, can I contact you through email?

**Comment by DrChat** [comment]
Sure, me@justinm.one (assuming the bouncer still works, anyways)

**Comment by programmerjake** [comment]
Sent! Luke should get back to you in a day or so (he's in the UK so is probably sleeping right now)

**Comment by DrChat** [comment]
Nice! Appreciate you letting me know this bounty existed!

**Pull request merged**
