### PR TITLE
Update dist-(arm|armv7|armhf)-linux to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by nikic**
I believe this should be safe, as actual artifacts will be produced by a cross toolchain. The build ran through cleanly locally.

This came up in https://github.com/rust-lang/rust/pull/93577, where the host GCC ICEd during the LLD build. (Though I wonder why we build LLD for the host at all...)

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We currently [document](https://doc.rust-lang.org/nightly/rustc/platform-support.html) ARMv6 Linux (kernel 3.2, glibc 2.17) as the support for arm-unknown-linux-gnueabi, which this builder produces.

I suspect that glibc 2.17 is older than even Ubuntu 18.04, but we probably should at least bump those docs alongside this PR. Since this target doesn't have a current maintainer, there's probably no one in particular to ping, though we could reach out to the Arm folks I suppose.

**Comment by nikic** [comment]
@Mark-Simulacrum Isn't the used kernel and glibc version controlled by the crosstool-ng config, rather than the host operating system? I thought the host OS is only relevant for cases where we don't use a cross toolchain (like the primary x86 dist builders).

**Comment by Mark-Simulacrum** [comment]
Ah, right. Yeah, that makes sense I think.

@bors r+ rollup

**Comment by nikic** [comment]
In the interest of more efficient docker cache repopulation I've updated dist-armv7-linux as well. Based on a local run, that one works fine with ubuntu 20.04 as well.

**Pull request merged**
