### PR TITLE
Move __thread_local_inner to sys

### PR DESCRIPTION
**Pull request by Ayush1325**
Move `__thread_local_inner` macro in `crate::thread::local` to `crate::sys`. Initially, I was thinking about removing this macro completely, but I could not find a way to create the generic statics without macros, so in the end, I just moved to code around.

This probably will need a rebase once https://github.com/rust-lang/rust/pull/108917 is merged

r? @workingjubilee

### CODE REVIEW

**Comment by joboet** [comment]
Perhaps it would make sense to split the macro up and use `#[cfg]` to choose the macro? That would reduce the code the compiler has to look at.

I'm not sure if `sys` is the right place, but the alternative (`sys_common`) does not seem to fit either... see also #84187.

**Comment by Ayush1325** [comment]
> Perhaps it would make sense to split the macro up and use `#[cfg]` to choose the macro? That would reduce the code the compiler has to look at.
> 
> I'm not sure if `sys` is the right place, but the alternative (`sys_common`) does not seem to fit either... see also #84187.

Well, the problem with splitting the macro is that currently, the macro has to be public. As far as I understand, any macro called by the public macro should also be public, which means exporting many macros that are internal implementation details. That's why I initially thought about using functions, but well, it is not possible to have generic statics, so I ended up just moving the whole thing to sys.

Also, I think sys_common is supposed not to have any platform-dependent code, so it probably isn't the correct place. Maybe @devsnek can provide better ideas?

**Comment by joboet** [comment]
> Well, the problem with splitting the macro is that currently, the macro has to be public. As far as I understand, any macro called by the public macro should also be public, which means exporting many macros that are internal implementation details. That's why I initially thought about using functions, but well, it is not possible to have generic statics, so I ended up just moving the whole thing to sys.

I meant something like [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c6c8859c1f2ba66cfc5611e10a8bb456), where the right `__thread_local_inner` macro is chosen with `#[cfg]`s.

**Comment by Ayush1325** [comment]
> > Well, the problem with splitting the macro is that currently, the macro has to be public. As far as I understand, any macro called by the public macro should also be public, which means exporting many macros that are internal implementation details. That's why I initially thought about using functions, but well, it is not possible to have generic statics, so I ended up just moving the whole thing to sys.
> 
> I meant something like [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c6c8859c1f2ba66cfc5611e10a8bb456), where the right `__thread_local_inner` macro is chosen with `#[cfg]`s.

I see, I will try to do it this way.

**Comment by workingjubilee** [comment]
Can we push this into `sys/common/thread_local.rs` or something like that? I want to keep this as a "directory" file. It's fine if this file grows a couple of additional `use` declarations.

**Comment by workingjubilee** [comment]
Excellent, thank you!

Let's see what the full CI run says about it.
@bors r+

**Comment by workingjubilee** [comment]
Sorry, another review inspired me to take a closer look at some things and I just verified they are actually correct. More confident this will pass in a rollup now.

@bors r+ rollup

**Pull request merged**
