### PR TITLE
Make UnsafeCell::into_inner safe

### LINKED ISSUE #35067: UnsafeCell::into_inner should not be unsafe
It's been unsafe since 2014 when it was called `unwrap`. Nobody thought about it, I guess, but it shouldn't be unsafe.

### PR DESCRIPTION
**Pull request by varkor**
This fixes #35067. It will require a Crater run as discussed in that
issue.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @BurntSushi 

@bors try 

cc @aidanhs for crater

**Comment by cramertj** [comment]
This shouldn't need a crater anymore since this works now:

```rust
let x: unsafe fn(_) -> _ = UnsafeCell::<u32>::into_inner;
```

I added that conversion way back in https://github.com/rust-lang/rust/pull/37389.

**Comment by nikomatsakis** [comment]
It still technically needs a crater run. There are other ways to expose the type. e.g. you might have a trait implemented only for `unsafe fn()` and so forth.

**Comment by cramertj** [comment]
@nikomatsakis Even then you'd still have to trigger the coercion to `unsafe fn()` first, wouldn't you? For example:

```rust
trait Foo {
    fn bar(&self) {}
}

impl Foo for unsafe fn() {}

unsafe fn baz() {}

fn main() {
    // These do not work:
    baz.bar();
    Foo::bar(&baz);

    // These do:
    let x: unsafe fn() = baz;
    x.bar();
    Foo::bar(&x);
}
```

**Comment by nikomatsakis** [comment]
@cramertj ah, hmm, good point. You may be right. =)

**Comment by carols10cents** [comment]
errrrr try failed because of... cargo? I'm going to see if retrying works...

@bors try

**Comment by kennytm** [comment]
Nope doesn't work. Cargo needs to add `#[allow(unused_unsafe)]` for their LazyCell.

**Comment by Mark-Simulacrum** [comment]
This is a breaking change because of the deny(warnings) resulting the compilation failure, though it is minor. We have done this in the past, though (most recently with the ASCII extension traits). @rust-lang/libs: Do we want to do this considering the breaking change aspect?

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Curious to see what the libs team thinks!

**Comment by sfackler** [comment]
@Mark-Simulacrum We don't consider new lint events as breaking changes. Cargo hard-caps lints at warn for dependencies, so it'll only break code that specifically asked to be broken.

**Comment by carols10cents** [comment]
Ping for ticky box [here](https://github.com/rust-lang/rust/pull/47204#issuecomment-356643568) @Kimundi !

**Comment by kennytm** [comment]
Same error as https://github.com/rust-lang/rust/pull/47204#issuecomment-356607275, please fix cargo first.

**Comment by kennytm** [comment]
@bors retry

The cargo on master contained rust-lang/cargo#4972 already.

**Comment by alexcrichton** [comment]
Er this passed, just a 3 hour timeout, merged manually

**Pull request merged**
