### PR TITLE
make `erase_regions_ty` query anonymous

### PR DESCRIPTION
**Pull request by nikomatsakis**
r? @michaelwoerister

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Presuming you wanted a perf build: http://perf.rust-lang.org/compare.html?start=7a4f39453cfbeab1c2220331f2eae8938165c964&end=afa558bf87d8910d28d3d52a4aa1232bd7fae2bc&stat=instructions%3Au.

**Comment by nikomatsakis** [comment]
Doesn't look especially significant, though it does help a few tests.

**Comment by michaelwoerister** [comment]
Thanks, @Mark-Simulacrum! That's indeed what I wanted. 

@nikomatsakis I think those are pretty good improvements for a one line change `:)`

Could we even go further and not even allocate a node if it is anonymous and has no inputs?

**Comment by michaelwoerister** [comment]
There might be room for further improvement here by not even allocating a `DepNode` in cases like this but that would need a slightly bigger change. Let's not wait for that.

@bors r+

**Comment by michaelwoerister** [comment]
I opened #45408 regarding further optimization.

**Pull request merged**
