### PR TITLE
Remove manual implementations of HashStable for hir::Expr and hir::Ty.

### PR DESCRIPTION
**Pull request by cjgillot**
We do not need to force hashing HIR bodies inside those nodes. The contents of bodies are not accessible from the `hir_owner` query which used `hash_without_bodies`. When the content of a body is required, the access is still done using `hir_owner_nodes`, which continues hashing HIR bodies.

### CODE REVIEW

**Comment by nagisa** [comment]
Looks like this PR still needs some work.

@rustbot author

**Comment by ehuss** [comment]
@bors retry

There is some kind of problem with GitHub Actions workflows being cancelled.

**Pull request merged**
