### PR TITLE
Revert "Stabilize RangeArgument"

### PR DESCRIPTION
**Pull request by sfackler**
This reverts commit 143206d54d7558c2326212df99efc98110904fdb.

From the discussion in #30877 it seems like this is premature.

### CODE REVIEW

**Comment by clarcharr** [comment]
Could you leave `Bound` in `core::ops` for this? That move is definitely agreed upon, but `RangeArgument` is what has the discrepancy.

**Comment by sfackler** [comment]
@clarcharr yep, I'll move things to libcore in a separate PR - I think it'll be a bit less confusing to do it separately :)

**Pull request merged**
