### PR TITLE
[Experiment] for #117191

### PR DESCRIPTION
**Pull request by Skgland**
Based on the request in https://github.com/rust-lang/rust/pull/117191#issuecomment-1783975003

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Right, I forgot that this doesn't quite work out of the box today:

```
tar: /codebuild/output/src47799677/src/release/dl/rust-docs-beta-x86_64-unknown-linux-gnu.tar.gz: Cannot open: No such file or directory
```

I'll try to push some commits here in the next week or so fixing this and re-running try.

**Comment by Mark-Simulacrum** [comment]
Kicked off dev-static beta.

**Comment by Skgland** [comment]
<https://dev-static.rust-lang.org/dist/2023-11-05>
has 
`channel-rust-1.74-beta.toml`
`channel-rust-1.74.0-beta.toml`
and
`channel-rust-1.74.0-beta.5.toml`
so I think its working?

**Pull request closed without merging**
