### PR TITLE
constify `slice_as_chunks` (unstable)

### PR DESCRIPTION
**Pull request by scottmcm**
Tracking issue: #74985

Nothing complicated required; just adding `const` to the declarations.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'll go ahead and just approve since this is unstable and I think fairly obvious yes surface area.

@bors r+

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/111719#issuecomment-1552945088)

@bors r-

**Comment by scottmcm** [comment]
Ah, of course, #108273 won the race.

**Comment by scottmcm** [comment]
Yay, no lib.rs update needed now.

@bors r=Mark-Simulacrum

**Pull request merged**
