### PR TITLE
 [MSP430] Build std components for msp430.

### PR DESCRIPTION
**Pull request by pftbest**
cc @japaric 
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@pftbest to confirm, do you have a good sense for how often this target breaks? If it's pretty rarely this seems fine by me to land, but if it's pretty common I think we may want to perhaps hold off on it for now

**Comment by pftbest** [comment]
The last major break was in November 2017 when codegen units where enabled by default (#45836). It was fixed in January (#47453).

Since then there where two minor breaks, one in April (#49618) where #[cfg(target_pointer_width)] was missing, and one in May (#50369) where cast from char to usize was giving a warning.

In both cases the problem was the fact that msp430 is a 16bit bit target, and it is easy to forget that usize can be 16bit wide. For example in this pull request i have yet another [fix for a similar problem](https://github.com/rust-lang/rust/pull/51250/commits/675e2660d72a7f9f40131a2d3baa58ba1eea268a). As you can see the fix was trivial in all this cases.

There is also one more thing you should know about, due to [LLVM bug](https://bugs.llvm.org/show_bug.cgi?id=37618) the build will fail when `DEPLOY=1` flag is missing. [It is set in CI](https://github.com/rust-lang/rust/blob/2ccf71c3b24e9a3ba5062c8230aa66079b748edb/.travis.yml#L115) so it will not fail the travis build, but it may be surprising if somebody tries to build `dist-various-1` image locally. If you are not comfortable with this, I can try to fix LLVM assertion but I'm not sure how long it will take.

**Comment by Mark-Simulacrum** [comment]
We discussed this today in the infra meeting, and decided that we'd like to hold off for now on landing this until the LLVM assertion is fixed. `DEPLOY` doesn't actually fix the assertion, rather it just disables LLVM assertions, so we'd prefer to not land a target that is potentially/likely generating incorrect code. Does that sound reasonable to you?

**Comment by pftbest** [comment]
> DEPLOY doesn't actually fix the assertion, rather it just disables LLVM assertions

In this particular case the problem is caused by integer overflow checks that gets enabled when `DEPLOY=0`. Without this range checks libcore compiles fine even with LLVM assertions enabled.

But I understand your concern, so I'll see what I can do about it.

**Comment by pietroalbini** [comment]
Ping from triage @pftbest! It's been a while since we heard from you, will you have time to work on this again?

**Comment by pftbest** [comment]
Hello, I have no progress on this yet, sorry.

**Comment by TimNN** [comment]
Ping form triage! I'm marking this as blocked (on the LLVM bug).

**Comment by TimNN** [comment]
Ping from triage! Thanks for your PR, @pftbest. It looks like the blocking bug is not going to be resolved anytime soon, so we're closing this PR for now. Feel free to reopen in the future!

**Comment by cr1901** [comment]
@pftbest I think this might be worth trying to get merged again now:

1. The LLVM bug you linked seems to be [fixed](https://bugs.llvm.org/show_bug.cgi?id=37618#c2).
2. The last time _I_ can recall the msp430 backend not emitting code period was [10 months ago](https://github.com/rust-lang/rust/pull/60985).
3. I'm unaware of any outstanding LLVM bugs (including ones that don't outright break code generation) since [2 months ago](https://github.com/rust-lang/rust/pull/68570).
4. If @pftbest, @awygle, or someone on @asl (msp430 LLVM backend maintainer) can get bug fixes and features upstream in LLVM, I'm on standby to quickly merge them into Rust's LLVM fork.

**Pull request closed without merging**
