### PR TITLE
Revert "Rollup merge of #80538 - JulianKnodt:err_usize, r=lcnr"

### PR DESCRIPTION
**Pull request by JohnTitor**
This reverts commit be2a3f86420f1efa95ee68b6a9f89b5a1e6f810b, reversing
changes made to 4c4e8e70bb5f28c9ed7b0b30d70c80261871c8ec.

It's second attempt to find the cause of [the perf regression](https://perf.rust-lang.org/compare.html?start=9919ad6e9ed113557c68c430de2e0f434e4f5b6e&end=f412fb56b8d11c168e7ee49ee74e79c4ab2e5637&stat=instructions:u) in rollup (#80708).

r? @ghost

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hey @rylev sorry for the trouble caused by my rollup! Could you run a perf check for this?

**Comment by JohnTitor** [comment]
The result is:

image

So we could say this is the cause.

**Comment by rylev** [comment]
The performance regressions aren't serious enough to actually warrant reverting. I think they should be investigated, but I'm closing this PR so no one actually merges it.

**Pull request closed without merging**
