### PR TITLE
Add more diagnostic items

### PR DESCRIPTION
**Pull request by Serial-ATA**
This just adds a handful diagnostic items I noticed were missing.

Would it be worth doing this for all of the remaining types? I'm willing to do it if it'd be helpful.

### CODE REVIEW

**Comment by Serial-ATA** [comment]
I think it's hitting this:
https://github.com/rust-lang/rust/blob/0b3404b01b251401e6b45cb1c4df8f883dfab2d7/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L1834-L1840

Should a special case be added for `Error`?

**Comment by Manishearth** [comment]
@bors r+

seems fine, unsure if we need to add more

cc @estebank

**Comment by GuillaumeGomez** [comment]
Ci isn't happy.

@bors: r-

**Comment by Serial-ATA** [comment]
Here's why CI is failing: https://github.com/rust-lang/rust/pull/96302#issuecomment-1105953459. It shouldn't be interfering with tests, so I'm not sure what's going on here.

**Comment by Manishearth** [comment]
Not sure either, @estebank?

**Comment by estebank** [comment]
Oh! So that's a very crude filter to avoid verbose output, relying on the assumption that if something is a diagnostic item there are better things than list them in those errors. Can you do `./x.py test src/test/ui --bless` and add the changes to `.stderr` files to a new commit so we can see if the changes are acceptable?

In the past I've added diagnostic items on an as-needed basis, though.

**Comment by Serial-ATA** [comment]
I'm confused. Over 700 files were modified, and most of these changes don't even look remotely related to what's been added. The only diagnostic item I needed is causing so many problems :smile:

**Comment by estebank** [comment]
Try pulling a more recent master and rebasing your changes on top of it, I'm noticing some output changes caused by a relatively recently landed PR.

**Comment by Serial-ATA** [comment]
Oops, I blindly added `COMPILETEST_FORCE_STAGE0=1` since it wouldn't let me do `./x.py test src/test/ui --bless`. Turns out the only difference is that one file from before.

**Comment by Serial-ATA** [comment]
Now a Cargo test is failing? I'm not able to reproduce it locally. 🤔

**Comment by estebank** [comment]
I'm as baffled as you are 😮 

@bors retry lets check it's not spurious

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/96511#issuecomment-1112159825)

**Comment by Serial-ATA** [comment]
Looks like the failing test just had a windows only version added. Hopefully that's the last issue with this :smile:

**Comment by xFrednet** [comment]
I'm guessing bors is stuck

@bors ping

**Pull request merged**
