### PR TITLE
rustdoc: display field types together with names in detailed docs

### PR DESCRIPTION
**Pull request by birkenfeld**
Is this desirable? The problem I can see is that the type names might get quite long.

Fixes: #32024

### CODE REVIEW

**Comment by cmr** [comment]
I think I'm in favor.

**Comment by steveklabnik** [comment]
Can you show a screenshot of what this looks like?

**Comment by birkenfeld** [comment]
Sure:
shot1
shot2

**Comment by GuillaumeGomez** [comment]
Nice but I'm afraid it's a bit too loaded. Hard choice...

**Comment by cmr** [comment]
To render this nicely, I think the field name and type should be on its own line, with the documentation for it following indented a bit.

**Comment by cmr** [comment]
(And I think the `Fields` header and section shouldn't be intended so much)

**Comment by birkenfeld** [comment]
If no one beats me to it, I'll change this to implement @cmr's suggestions.

**Comment by birkenfeld** [comment]
New try! Shots:

shot1
shot2

**Comment by GuillaumeGomez** [comment]
I really don't like this design. :-/

Maybe with the "[-]" thing, it would work better at first. But I don't know how we could display the field's information nicely...

**Comment by TyOverby** [comment]
Big :+1: for me!  I always felt dumb having to scroll up to check field types.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Pull request closed without merging**
