### PR TITLE
Use Rc instead of Box for interned strings.

### PR DESCRIPTION
**Pull request by nnethercote**
We currently heap-allocate each one twice, once for Interner::names and
once for Interner::strings. Using Rc instead means each one is allocated
once and then shared.

This speeds up numerous rustc-perf runs, the best by 4%.

Here are details for the ones with an improvement of 1% or more:
```
coercions-check
        avg: -2.3%      min: -4.1%      max: -0.8%
coercions
        avg: -1.3%      min: -2.8%      max: -0.8%
coercions-opt
        avg: -1.5%      min: -2.7%      max: -0.6%
tuple-stress
        avg: -0.5%      min: -1.3%      max: 0.1%
tuple-stress-check
        avg: -0.6%      min: -1.3%      max: -0.3%
tuple-stress-opt
        avg: -0.7%      min: -1.3%      max: -0.4%
```

### CODE REVIEW

**Comment by michaelwoerister** [comment]
> We currently heap-allocate each one twice

`:D` 

@Zoxc, do you see a problem with using `Rc` here? The ref-count should never be changed from different threads, as far as I can tell.

**Comment by Zoxc** [comment]
This use of `Rc` is fine. It will need an `unsafe impl Send for Interner {}` though. Add a note that the impl is safe because the ref count is only modified at one thread at a time. It is modified during insertion and during destruction. These may happen on different threads, but are mutually excluded.

**Comment by michaelwoerister** [comment]
OTOH, there wouldn't be a real downside to using `Lrc`, right?

**Comment by Zoxc** [comment]
It would be slower.

**Comment by michaelwoerister** [comment]
Yes, but I wouldn't expect the difference to be noticeable.

**Comment by nnethercote** [comment]
Updated with the `unsafe impl Send`. 

r? @Zoxc

**Comment by nnethercote** [comment]
#50607 is a much better way of doing things.

**Pull request closed without merging**
