### PR TITLE
Remove dead code from sys::windows::c

### PR DESCRIPTION
**Pull request by pitdicker**
I am not entirely sure I have got everything right, but if it compiles it is ok probably...
I tested it with msvc x86_64 and gnu.

Somehow a lot of `EXCEPTION-*` constants are dead code when running test, no idea why.
I have put `#![cfg_attr(test, allow(dead_code))]` at the top for this.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 0a6f35b31725ea7d7ec88030dd38600a9412c3cf

Quite the cleanup!

**Comment by pitdicker** [comment]
I can't really get cross-compiling set up, but I think this fixes it for 32-bit.
Should I somehow first test myself, or is it ok to try?

**Comment by alexcrichton** [comment]
@bors: r+ 94db864965e9e4e80d9a4a3d6878d30ab4efd2c9

If this bounces I've got a [simple script](https://gist.github.com/alexcrichton/78c5ef69baf8e1a458e0) to just mock compile the repo, which may be useful for ensuring that other platforms just compile

**Comment by pitdicker** [comment]
Thanks!

I have no idea what that script does...

**Comment by alexcrichton** [comment]
Ah if you tweak the first two lines to uncomment the right stage/triple and just run it inside of a checkout of the compiler it will "bootstrap" that target into a directory called `out`

**Comment by pitdicker** [comment]
mingw really does not like me... I have reinstalled msys and 64- and 32-bit mingw and made a fresh checkout and rebuild of rust. But cross-compiling seems out of reach for me. And I tried your script.
Is there any guide for setting this it up?

This pr should work now, but untested for 32-bit.

**Comment by alexcrichton** [comment]
I tested this out locally and got (for the MSVC targets)

```
src/libstd/sys/windows/c.rs:1090:5: 1093:58 warning: foreign function is never used: `RaiseException`, #[warn(dead_code)] on by default
src/libstd/sys/windows/c.rs:1090     pub fn RaiseException(dwExceptionCode: DWORD,
src/libstd/sys/windows/c.rs:1091                           dwExceptionFlags: DWORD,
src/libstd/sys/windows/c.rs:1092                           nNumberOfArguments: DWORD,
src/libstd/sys/windows/c.rs:1093                           lpArguments: *const ULONG_PTR);
```

Both the MinGW targets compiled with no warnings, however.

**Comment by pitdicker** [comment]
Thanks so much for testing this! A little cleanup is not worth all the effort this takes...

I don't understand why `RaiseException` is not used on msvc. Both msvc targets use seh.rs.
And seh.rs uses it, except for stage0.
But I thought dead code in stage0 only gives warnings, not errors?

**Comment by retep998** [comment]
@pitdicker Which is why the message says `warning: foreign function is never used: `RaiseException`, #[warn(dead_code)] on by default`, which is a warning and not an error.

**Comment by pitdicker** [comment]
@retep998 The problem is the later stages deny warnings. So I am not sure if compiling fails with this warning, and if so, why?

**Comment by alexcrichton** [comment]
@pitdicker oh good point! If that ends up being the only error then this is indeed probably good to go, I only compiled in stage0

@bors: r+ 98fa5ac342208e78622babffeba412a0b2ca1966

**Comment by pitdicker** [comment]
They say in Dutch when you don't succeed the first two times: third time is shipping rights :). Let's hope

**Comment by alexcrichton** [comment]
@bors: retry force

Unfortunately this won't land until #31855 lands

**Pull request merged**
