### PR TITLE
Make more use of autoderef throughout the compiler

### PR DESCRIPTION
**Pull request by jonas-schievink**

### CODE REVIEW

**Comment by steveklabnik** [comment]
👍

**Comment by jroesch** [comment]
LGTM r+

**Comment by jonas-schievink** [comment]
Rebased

**Comment by jonas-schievink** [comment]
Rebased

**Comment by jonas-schievink** [comment]
Rebased

**Comment by jonas-schievink** [comment]
Help I'm trapped in a merge conflict factory!

**Comment by steveklabnik** [comment]
Gah. 

If you fix it again, i'll r+ with a high priority

**Comment by jonas-schievink** [comment]
Fixed

**Pull request merged**
