### PR TITLE
[CI] Use a lockfile for installing the `datadog` package

### PR DESCRIPTION
**Pull request by Kobzol**
Without a lockfile, it could fail to compile when the dependencies have changed. Reported [here](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/CI.20failure.20in.20DataDog.20upload).

r? @jdno

try-job: x86_64-msvc-ext2

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
Once this lands, we should probably do something similar for `browser-ui-test`, which is currently also installed from NPM without a lockfile.

https://github.com/rust-lang/rust/blob/a224f3807e58afc9353510f1d556c607d367545d/src/ci/docker/host-x86_64/x86_64-gnu-tools/Dockerfile#L105-L106

**Comment by jieyouxu** [comment]
```
2024-12-12T06:58:13.4430797Z found 0 vulnerabilities
2024-12-12T06:58:13.8673233Z Metric avg-cpu-usage: 79.5104
2024-12-12T06:58:13.8843957Z Traceback (most recent call last):
2024-12-12T06:58:13.8844644Z   File "D:\a\rust\rust\src\ci\scripts\upload-build-metrics.py", line 68, in <module>
2024-12-12T06:58:13.9588925Z     upload_datadog_measure("avg-cpu-usage", avg_cpu_usage)
2024-12-12T06:58:13.9590675Z   File "D:\a\rust\rust\src\ci\scripts\upload-build-metrics.py", line 51, in upload_datadog_measure
2024-12-12T06:58:13.9591291Z     subprocess.run(
2024-12-12T06:58:13.9591780Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 505, in run
2024-12-12T06:58:14.0113610Z     with Popen(*popenargs, **kwargs) as process:
2024-12-12T06:58:14.0115247Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 951, in __init__
2024-12-12T06:58:14.0122696Z     self._execute_child(args, executable, preexec_fn, close_fds,
2024-12-12T06:58:14.0123364Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 1420, in _execute_child
2024-12-12T06:58:14.0337177Z     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
2024-12-12T06:58:14.0341267Z FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Kobzol** [comment]
More fun with MSYS2.. anyway, should be fixed now. I'll readd it to the queue if/when PR CI passes.

**Pull request merged**
