### PR TITLE
inform user where to give a type annotation

### LINKED ISSUE #47777: inform user where to give a type annotation after a call to collect
UPDATE: [Mentoring instructions below.](https://github.com/rust-lang/rust/issues/47777#issuecomment-361312349)

---

We are not giving a very good error message in this example:

```rust
fn main() {
    let mut dirty_list = (0..5).collect();
    dirty_list.pop();
}
```

[We say:](https://play.rust-lang.org/?gist=974c68bc5ca266189c7ae56e2f21c6a1&version=stable)

```
error[E0619]: the type of this value must be known in this context
 --> src/main.rs:3:5
  |
3 |     dirty_list.pop();
  |     ^^^^^^^^^^^^^^^^
```

It'd be nice if we at least informed the user that they ought to annotate the type of `dirty_list`. (Indeed, I know we used to have a bug on this, and I *thought* we were doing so...?)

It'd be nicer still if we recognized that there is a call to `collect` and were able to say something like "you need to specify the kind of collection".

cc @estebank

### PR DESCRIPTION
**Pull request by csmoe**
should resolve #47777 
previous pull request https://github.com/rust-lang/rust/pull/47982 was closed because of a mistaken rebase.
r? @estebank

### CODE REVIEW

**Comment by estebank** [comment]
@csmoe could you show the `rustc` output both before and after for any of the `compile-fail` errors? Also, I think you might have to rebase against latest master (`git checkout master && git pull && git checkout inform_type_annotations && git rebase master`) to get the correct behavior for [two `ui` tests](https://travis-ci.org/rust-lang/rust/builds/341271827#L2363) (otherwise the PR won't get merged by bors).

**Comment by csmoe** [comment]
@estebank It’s really difficult for me to test the `rustc` on my laptop, I had tried about 8 hours yesterday but still failed to compile either -llvm parts-. So I just pulled this request to test my commits by bors(really sorry for the annoying failure message). Is there any way to compile with local llvm installed from linux packages repo?
I’ll update more changes about 2 days later(Chinese New Year). sorry for the delay.

**Comment by estebank** [comment]
> after this commit:

Love it!

> It’s really difficult for me to test the rustc on my laptop, I had tried about 9 hours to compile but never succeeded to build it when testing. 

That is highly unusual. It takes me about 20 minutes to compile LLVM on first pull, and after that it doesn't need to be recompiled (until pulling changes to LLVM version from the repo).

> So I just pulled this request to test my commits by bors(really sorry for the annoying failure message).

I do the same sometimes when working on multiple branches (wait for travis CI to fail or pass while I keep working).

> Is there any way to compile with local llvm installed from linux packages repo?

I don't know, sorry :-/

> I’ll update more changes about 2 days later to deal with the failure(Chinese New Year). sorry for the delay.

Don't worry! Take your time and enjoy the holiday. I like the change, I'm looking forward to having it merged. Just ping me once you've cleared the error.

**Comment by csmoe** [comment]
error cleared.
cc @estebank

**Comment by nikomatsakis** [comment]
So excited for this PR! 💯

**Comment by nikomatsakis** [comment]
@csmoe I don't know your twitter handle, so I'll just drop this here:

https://twitter.com/nikomatsakis/status/966737996434366464

**Pull request merged**
