### PR TITLE
rustdoc: unstable should show feature name and issue

### PR DESCRIPTION
**Pull request by m4rw3r**
Implemented #27759 

Example:

screen shot 2015-08-16 at 21 45 17

### CODE REVIEW

**Comment by killercup** [comment]
Very cool!

If the screenshot is accurate, I'd suggest making the font size of the name of the feature a bit smaller and changing it's background to transparent.

**Comment by m4rw3r** [comment]
I pretty much just imitated the style used by github in that example in the linked issue since it seemed like it made the feature name clear, but here is an alternative without the background and with a slightly smaller font-size:
screen shot 2015-08-17 at 14 33 22

Is this better?

**Comment by killercup** [comment]
@m4rw3r I like this second version better. I'm no authority on the visual design of rustdoc, though :)

**Comment by alexcrichton** [comment]
Awesome, thanks @m4rw3r! A few thoughts:

* Could this avoid adding a CLI option to rustdoc for now? The flag interface is already a bit too ambitious I think and it'd be nice to keep it under control!
* The new `issue_tracker_base_url` probably only needs to be added to the standard library and facade crates, it should be ok to omit for all the rustc_private and above crates
* Could you host these docs so we could poke around a bit?
* Could you add a test for this as well? (see `src/test/rustdoc`)

**Comment by m4rw3r** [comment]
@alexcrichton I put a copy of the docs rendered with my branch on github pages: http://m4rw3r.github.io/rust/std/result/enum.Result.html#method.expect

**Comment by alexcrichton** [comment]
Awesome, thanks @m4rw3r!

**Comment by steveklabnik** [comment]
looks really nice

**Comment by tshepang** [comment]
so kool

**Comment by alexcrichton** [comment]
@bors: r+ 6532a08525137a5f839c4ed555ad95360621f5db

Thanks @m4rw3r! Also feel free to ping a PR whenever you force push it, unfortunately github doesn't send out notifications on those events :(

**Comment by m4rw3r** [comment]
@alexcrichton iirc I did not force-push this one, but I will keep that in mind if I do force push something. Github had some problems with git-pull about 2 days ago, that caused the travis build to be delayed. 

Now on to find some other thing to implement for rustdoc :)

**Pull request merged**
