### PR TITLE
rustdoc: speed up processing of cross-crate fns to fix a perf regression

### PR DESCRIPTION
**Pull request by fmease**
* The first commit doesn't affect perf but get's rid of a `.clone()` and a bunch of lines of code. I can drop it if you'd like me to
* The second commit, *“reduce the amount of `asyncness` query executions”*, addresses the perf regression introduced in #116084

r? @ghost

### CODE REVIEW

**Comment by fmease** [comment]
Okay, for the last time hopefully ^^:
@bors try @rust-timer queue

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Nice work, thanks!

@bors r+

**Pull request merged**
