### PR TITLE
Fix processing mod with multi-level path on Windows

### PR DESCRIPTION
**Pull request by EPashkin**
Fix error in [rustfmt](https://github.com/rust-lang-nursery/rustfmt/issues/1754) because libsyntax can not handle `mod` with multilevel path on Windows.

Alternative is do almost same in https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/fs.rs#L717 to allow work on paths with different separators, Ex. "\\\\?\\c:\\windows/temp"

### CODE REVIEW

**Comment by EPashkin** [comment]
@nikomatsakis You right. Rust works with it fine but `libsyntax` is not: because it used canonicalized base path (like "\\\\?\c:\work\lib") and it only path form on Windows that not accept mixed separator (see https://github.com/rust-lang-nursery/rustfmt/issues/1754#issuecomment-389953313)

**Comment by retep998** [comment]
If you have a relative path, it is completely valid to do replacements such as changing `/` to `\`, although to be completely correct we'd also need to strip `.` components and handle `..` as well, because they're perfectly valid in a relative path but lose their special meaning if naively joined onto a `\\?\` path. Really this is how path joining should always be done, but it's probably too late to change `libstd` in that manner.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@EPashkin can we add some form of test for this? It looks like there are some examples of tests that use `#[path]` in `src/test/run-pass/mod_dir_path2.rs`, maybe we can construct a test there? (It'd be good to build the test first to ensure it fails on windows; this strikes me as the sort of thing where it is easy to have a test that isn't actually testing what you think it is)

**Comment by EPashkin** [comment]
@nikomatsakis I almost sure that test don't use `libsyntax` or canonicalized base paths
as it modified version of it passed on not fixed version.
Also I don't see any test that uses `libsyntax` directly.
```
#[path = "mod_dir_simple"]
mod pancakes {
    #[path = "test.rs"]
    pub mod syrup;
}

#[path = "mod_dir_simple/test.rs"]
mod gravy;

pub fn main() {
    assert_eq!(pancakes::syrup::foo(), 10);
    assert_eq!(gravy::foo(), 10);
}
```

**Comment by nikomatsakis** [comment]
@EPashkin nice job going above and beyond with the test :) I think it's really good to test these sorts of properties, as they are easily overlooked during refactorings and things. (I presume that test fails without your PR?)

**Comment by EPashkin** [comment]
@nikomatsakis Thanks.
Yes, test will fails on windows with removed fix ;)

**Comment by EPashkin** [comment]
@nikomatsakis This is final test version.
Want me to squash commits?

**Comment by EPashkin** [comment]
@nikomatsakis Friendly reminder of this PR

**Comment by pietroalbini** [comment]
Ping from triage @nikomatsakis! This PR needs your review.

**Pull request merged**
