### PR TITLE
remove `NoSendItem` and `NoSyncItem` lang items

### PR DESCRIPTION
**Pull request by japaric**
r? @FlaPer87

### CODE REVIEW

**Comment by FlaPer87** [comment]
We should probably remove this along with https://github.com/rust-lang/rust/blob/master/src/libcore/marker.rs#L379-L387 but the later may require a new snapshot. I just pushed to snap3.

**Comment by japaric** [comment]
@FlaPer87 that's not necessary (because neither the marker nor the lang items exist in stage1 and forwards), but if you want to kill two birds with one stone, then you can cherry pick (or roll up) this PR with the "register snapshot" one.

**Comment by FlaPer87** [comment]
@japaric yes, I didn't mean to imply it was necessary. It's more like, lets remove them altogether. I'll cherry-pick. Thanks a lot for tackling this.

**Comment by frewsxcv** [comment]
Needs a rebase

**Pull request merged**
