### PR TITLE
[LSDA] Take ttype_index into account when taking unwind action

### PR DESCRIPTION
**Pull request by bzEq**
If `cs_action != 0`, we should check the `ttype_index` field in action record. If `ttype_index == 0`, a clean up action is taken; otherwise catch action is taken.

This can fix unwind failure on AIX which uses LLVM's libunwind by default. IIUC, rust's LSDA is borrowed from c++ and I'm assuming itanium-cxx-abi https://itanium-cxx-abi.github.io/cxx-abi/exceptions.pdf should be followed, so the fix follows what libcxxabi does. See https://github.com/llvm/llvm-project/blob/ec48682ce9f61d056361c5095f21e930b8365661/libcxxabi/src/cxa_personality.cpp#L152 for use of `ttype_index`.

### CODE REVIEW

**Comment by cuviper** [comment]
I don't know these details about unwinding -- maybe r? @Amanieu

**Comment by Amanieu** [comment]
I think this looks correct, based on the implementation in libcxxabi. However I think this change also needs to be applied to the SJLJ code path.

**Comment by Amanieu** [comment]
I'm surprised this is needed though, I didn't think LLVM emitted code like this. Could you expand on the cases where this causes problems on AIX?

**Comment by Amanieu** [comment]
LGTM. Could you also update the SJLJ code path?

**Comment by Amanieu** [comment]
That's quite a lot of duplicated code, this could be moved into `interpret_cs_action`.

**Comment by Amanieu** [comment]
I don't think it is necessary.

@bors r+

**Pull request merged**
