### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by arlosi**
8 commits in 1b15556767f4b78a64e868eedf4073c423f02b93..7ac9416d82cd4fc5e707c9ec3574d22dff6466e5
2023-07-18 14:44:47 +0000 to 2023-07-24 14:29:38 +0000
- fix(cargo-credential): should enable feature `serde/derive` (rust-lang/cargo#12396)
- fix: encode URL params correctly for SourceId in Cargo.lock (rust-lang/cargo#12280)
- docs: format config override caveat as a note (rust-lang/cargo#12392)
- credential provider implementation (rust-lang/cargo#12334)
- feat(crates-io): expose HTTP headers and Error type (rust-lang/cargo#12310)
- chore: Don't update test data (rust-lang/cargo#12380)
- fix: only skip mtime check on `~/.cargo/{git,registry}` (rust-lang/cargo#12369)
- Update docs for artifact JSON debuginfo levels. (rust-lang/cargo#12376)

Since rust-lang/cargo#12334 makes built-in credential providers part of the cargo binary, it's no longer needed to build them in bootstrap.

### CODE REVIEW

**Review by albertlarsan68 — APPROVED** [review]
r=me on the bootstrap changes

**Comment by ehuss** [comment]
Thanks!

I think the lines at https://github.com/rust-lang/rust/blob/fc8a3e357a0a5e317132e5ff8858ec70970fb07a/src/bootstrap/dist.rs#L1088-L1093 also need to be removed. It's not critical since it would not generate an error or cause problems since it just skips over the entries, but it would become dead code after this change.

**Comment by ehuss** [comment]
Thanks!

@bors r+ p=1

**Comment by ehuss** [comment]
cc @weihanglo Just verifying you saw this.

**Pull request merged**
