### PR TITLE
Add new rpitit compare mode

### PR DESCRIPTION
**Pull request by spastorino**
r? @compiler-errors 

This depends on #108700, after that one is merged I can rebase it on top of master but for now is good for a review. The last commit https://github.com/rust-lang/rust/pull/108710/commits/7dfcdcaea26fbba86f79db17f872cb3af5d69f5b is the only meaningful one, the rest are about #108700

### CODE REVIEW

**Comment by jackh726** [comment]
I don't see the benefit of a separate compare mode, vs being explicit. Compare modes are more useful for things that will every *every* program. RPITIT lowering does not.

**Comment by compiler-errors** [comment]
Yeah, @jackh726 is right. We can probably just use revisions for all the tests in `impl-trait/in-trait` and `async-await/in-trait`. It would be cool if we could have opt-in migrate mode instead of opt-out, but I digress.

**Comment by spastorino** [comment]
@jackh726 I'm not sure what did you mean exactly, but we are aiming to replace existing code with what we have under -Zlower-impl-trait-in-trait-to-assoc-ty. I think this is useful in order to:

1. Disallow people to push code that breaks under lower-impl-trait-in-trait-to-assoc-ty
2. As a way to track failing tests (which can be done also just using revisions)

**Comment by jackh726** [comment]
Yes, but this compiler flag should only affect RPITIT lowering, and thus only the tests in the directories listed by @compiler-errors.

To argue some more against this: RPITITs are unstable now *anyways*. I doubt we want different behavior for long. Revisions are *enough* if needed. I might even argue that it's not even worth adding the compile flag and just making the change (you want this to get tested, and having a flag for an unstable feature seems counter to that goal).

**Comment by spastorino** [comment]
It's true that most tests live where @compiler-errors mentioned (note that there are a ton of other places where we use RPITITs and AFITs trying to test other stuff). Anyway, I can add revisions to those and be sure that I keep track of the ones that are working and the ones that are not working.
The reason for me for opening this PR was to be sure that we are not pushing code that break things related to this change. Anyway, the compare-mode and the unstable flag are temporary things until we are sure so IMO this shouldn't hurt.
I'm also fine with closing this and I can add revisions if you both prefer.

**Comment by spastorino** [comment]
Closing in favor of using revisions.

**Pull request closed without merging**
