### PR TITLE
Impl Error for Box<T: Error>

### LINKED ISSUE #30349: Box<T: Error> should implement Error (std::error::Error)
I'm not too sure what versioning-annotations to use, otherwise I'd do a PR myself.

```rust
impl<T: Error + ?Sized> Error for Box<T> {
    fn description(&self) -> &str {
        Error::description(&**self) 
    }
    fn cause(&self) -> Option<&Error> {
        Error::cause(&**self) 
    }
}
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #30349

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'd like to run crater over this to make sure it doesn't have too much intended breakage first.

**Comment by GuillaumeGomez** [comment]
Please do! :)

**Comment by alexcrichton** [comment]
Crater reports [one regressions](https://gist.github.com/alexcrichton/655991c192902246945f) which is spurious, so I think this is good to go.

@bors: r+ 31f7f3a835141605c579d00471ce1bb331f2f192

**Comment by alexcrichton** [comment]
@bors: r-

er actually, can you define this for `T: ?Sized` instead of just `T`?

**Comment by GuillaumeGomez** [comment]
I didn't because of a problem. Hold on, I try again to see why.

**Comment by GuillaumeGomez** [comment]
That's the [error]https://gist.github.com/GuillaumeGomez/ca1e875066fb9ea545d9() I get.

**Comment by alexcrichton** [comment]
Hm right, that's what I remember getting in the past. I'm gonna hold off on r+'ing for now and tag this with T-libs to get some more discussion.

I'm a little worried that `Box<Error>` won't implement `Error` (which one might reasonably expect), but it does seem valuable that `Box<MyCustomError>` can be used with `try!` to return a `Box<Error>` (due to the `From` impl).

Curious on others' thoughts as well though (cc @rust-langlibs)

**Comment by alexcrichton** [comment]
cc @rust-lang/libs

**Comment by GuillaumeGomez** [comment]
Any news on this?

**Comment by alexcrichton** [comment]
Unfortunately we haven't had time yet in libs triage to come back around to this, but it's still on the agenda.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the conclusion was to merge. We may want to ensure that `Box<Error>` implements `Error` somehow in the future, but in the meantime it seems like that shouldn't necessarily prevent this sort of impl from existing anyway. Thanks again for the PR @GuillaumeGomez!

@bors: r+ f9f29814e3451757b254121115c9bb9f4a3fc253

**Pull request merged**
