### PR TITLE
Add E0619 error explanation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
r? @nikomatsakis
(for the record, I regret not letting this ICE)

**Comment by durka** [comment]
This is a duplicate error code.

```
Compiling rustc_typeck v0.0.0 (file:///home/aburka/rust/src/librustc_typeck)
warning: diagnostic code E0619 already used
    --> src/librustc_typeck/check/mod.rs:4719:21
     |
4719 | /                     type_error_struct!(self.tcx.sess, sp, ty, E0619,
4720 | |                                        "the type of this value must be known in this context")
     | |______________________________________________________________________________________________^
     |
note: previous invocation
    --> src/librustc_typeck/check/intrinsic.rs:40:13
     |
40   | /             struct_span_err!(tcx.sess, it.span, E0619,
41   | |                              "intrinsic must be a function")
     | |____________________________________________________________^
     = note: this error originates in a macro outside of the current crate
```

**Comment by nikomatsakis** [comment]
It does seem unclear why this requires a nice error... but ok. :)

**Comment by GuillaumeGomez** [comment]
Sorry, to avoid another conflict I moved this error code.

@bors: r=nikomatsakis rollup

**Pull request merged**
