### PR TITLE
Support embedding LLVM bitcode on AIX

### PR DESCRIPTION
**Pull request by bzEq**

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
r? compiler

**Comment by nagisa** [comment]
Could you please reference some documentation on the section names AIX expects? `IPA` in `.ipa` appears to stand for inter-procedural-analysis. Is whatever stored there otherwise some sort of bytecode?

I’m particularly curious what happens if you try to link together some system library with an `.ipa` section with a rust library containing an `.ipa` section. Does that work correctly?

**Comment by bzEq** [comment]
> Could you please reference some documentation on the section names AIX expects?

No, there isn't currently. We haven't support `-fembed-bitcode` in clang for XCOFF yet. See https://github.com/llvm/llvm-project/blob/267708f9d5150c5153e92e913c021918b790ac4f/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp#L5102.

The purpose of this PR currently is to workaround linking issue we have encountered during bootstrap, since the linker doesn't recognize the inline assembly generated by https://github.com/rust-lang/rust/blob/696aaad58c57a589f6fb2ecff5bae2eec581cb71/compiler/rustc_codegen_llvm/src/back/write.rs#L903.

> IPA in .ipa appears to stand for inter-procedural-analysis. Is whatever stored there otherwise some sort of bytecode?

We are planning to support LTO on AIX, and this might be the name of the section to store LLVM bitcode.

> I’m particularly curious what happens if you try to link together some system library with an .ipa section with a rust library containing an .ipa section.

AIX linker will ignore `.ipa` sections and they won't appear in the final object file.

**Comment by nagisa** [comment]
Ah, sorry for missing this!

> AIX linker will ignore .ipa sections and they won't appear in the final object file if no symbol references this section.

Awesome, this is the behaviour that resolves any worries I might have had about keeping this section.

@bors r+

**Pull request merged**
