### PR TITLE
stabilize mem::discriminant (closes #24263)

### LINKED ISSUE #24263: discriminant_value intrinsic -- tracking issue for 639
Tracking issue for rust-lang/rfcs#639.

Some things to nail down before stabilization:
- [x] prototype implementation
- [ ] signature needs to have a `<T:Reflect>` bound
- [x] documentation should reflect the inherent instability in this value and describe valid uses
- [ ] perhaps signature should require input `T` to actually be an `enum` instance?
- [ ] do we want to adjust the return type in any way to enforce the above rules?

### PR DESCRIPTION
**Pull request by durka**

### CODE REVIEW

**Comment by est31** [comment]
@dtolnay if this is to be merged on beta, #44262 has to be as well.

**Comment by durka** [comment]
If it's going to beta, the "since" field should be changed as well.

**Comment by durka** [comment]
I don't think this depends on #44262. That splits out `#[repr(i128)]` from the `i128_type` feature gate but doesn't stabilize either one.

**Comment by est31** [comment]
ahh right its still unstable.

**Comment by alexcrichton** [comment]
Accepting for backport according to the last libs triage

**Comment by durka** [comment]
@alexcrichton should I do that, or will you? including fixing up the `since` fields?

**Comment by alexcrichton** [comment]
Ah it's ok, I'll do it at some point with other backports. Want to send a PR to master to update the fields?

**Comment by durka** [comment]
#44552

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
