### PR TITLE
Remove unneeded Send/Sync bounds on Arc, Mutex, RwLock and sync::mpsc

### PR DESCRIPTION
**Pull request by huonw**
These types had many instances of `T: Send + Sync` in places they were not necessary.

In fact, the only place they are required is when considering under what circumstances can `Arc<T>` (etc.) be sent/shared across thread boundaries, i.e. the only place it matters is the `unsafe impl`s of `Send` and `Sync`. It is perfectly safe for an `Arc<T>` to stay on and be used on a single thread if `T` doesn't satisfy the necessary bounds. It just acts like a (expensive) `Rc<T>`. The added flexibility may be convenient in generic code. (Similar reasoning applies to `Mutex`, `RwLock` and `sync::mpsc`. See commit messages for some more details.)

This also fixes a hole, where `Arc::new` has no bounds on `T`, but `Drop for Arc<T>` requires `T: Send + Sync` (meaning one could theoretically create an `Arc` type which has no destructor, although the compiler mishandles this case anyway).

### CODE REVIEW

**Comment by huonw** [comment]
Alternatively, we could tighten up these types and make them require the relevant bounds everywhere (closing the `Arc` hole), "just in case". Taking that approach should be able to be related to the approach in this PR backwards compatibly (unless we get some sort of implied bounds and use them for `Arc`). cc https://github.com/rust-lang/rfcs/pull/590

**Comment by alexcrichton** [comment]
I've seen this definitely assist in `#[derive]` implementations in the past (as you don't have to insert the extra bounds manually). My only (very minor) concern would be about error messages. Previously `channel::<Rc<T>>` would provide a nice error message on construction, but I presume it yields basically the same error message when it crosses threads? It's a little unfortunate to get the error much later, but I also prefer this as it's strictly more flexibly (especially with generics as you say).

r+ from me, but would like a second opinion from @brson or @aturon as well.

**Comment by brson** [comment]
It seems like there's a policy that is unclear here, and these bounds may be tighter than necessary on purpose. I do have a vague recollection that we wanted bounds on types at some point for reasons similar to what @alexcrichton was saying.

**Comment by aturon** [comment]
I am inclined not to take this step, and instead to further tighten up the use of `Send` per rust-lang/rfcs#590

Like @alexcrichton, I'm worried about error messages and clarity here. 

Further, I'm not convinced about the generic programming angle. In a case where you're generic enough to not be able to send an `Arc` value, you are therefore unable to make use of `Arc` beyond what `Rc` offers. In other words, the only reason to choose `Arc` is if you do want to communicate between threads, and you can only do that if you have sufficient type constraints anyway.

Finally, as you point out, keeping the bounds tighter is the more conservative option.

**Comment by huonw** [comment]
Tighter bounds implemented in #23954.

**Comment by huonw** [comment]
@aturon relaxed his objection after discussion on IRC ([start](https://botbot.me/mozilla/rust-internals/2015-04-01/?msg=35618693&page=10), [end](https://botbot.me/mozilla/rust-internals/2015-04-01/?msg=35620186&page=10).

**Pull request merged**
