### PR TITLE
Fix escape key handling

### LINKED ISSUE #72647: When pressing ESC on search, it sometimes bring back the results
Peek 2020-05-27 10-54

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #72647.

The problem was that you could have a timeout just after the moment you press "escape", putting back the results.

r? @kinnison

### CODE REVIEW

**Review by kinnison — COMMENTED** [review]
I'm tempted to ask for a factoring of the clearing of the timeout into a function,but if you don't think it's worthwhile then this is clean afaict, but I'm unable to build compilers/rustdoc right now due to my desktop being fluffed and being out of disk space on my laptop.  r=me with or without factoring the function out, thought I'd prefer it if you did.

**Comment by GuillaumeGomez** [comment]
I'll do it then. :)

**Comment by GuillaumeGomez** [comment]
Updated!

**Review by kinnison — APPROVED** [review]

**Pull request merged**
