### PR TITLE
rustdoc: Resolve some more doc links early

### PR DESCRIPTION
**Pull request by petrochenkov**
Trying another subset of https://github.com/rust-lang/rust/pull/94857 that is not too expensive.

### CODE REVIEW

**Comment by Kobzol** [comment]
`syn` is quite noisy lately, so the regression might be a fluke.

**Comment by GuillaumeGomez** [comment]
Does it fix the missing call to `unindent_comment` from your topic in zulip?

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
>Does it fix the missing call to `unindent_comment` from your topic in zulip?

No, I'll submit that change later.

Let's actually land this, it's a pure performance win, and a relatively large one, and I won't be able to work on other parts of https://github.com/rust-lang/rust/pull/94857 until the next week.
This can be rolled up with https://github.com/rust-lang/rust/pull/96260 to save CI time.
@rustbot ready

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup=never

**Pull request merged**
