### PR TITLE
Correct type inference failure uncovered by japaric

### PR DESCRIPTION
**Pull request by nikomatsakis**
This also includes some miscellaneous cleanup. This is kind of a band-aid but it fixes the problems @japaric was encountering.

r? @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
The first commit was already reviewed by @brson in https://github.com/rust-lang/rust/pull/21485

**Comment by FlaPer87** [comment]
This looks good to me :cake:

**Comment by eddyb** [comment]
The compile-fail failures seem to be caused by inference getting further than before.

**Pull request merged**
