### PR TITLE
Make ErrorGuaranteed discoverable outside types, consts, and lifetimes

### PR DESCRIPTION
**Pull request by oli-obk**
types like `PatKind` could contain `ErrorGuaranteed`, but not return them via `tainted_by_errors` or `error_reported` (see https://github.com/rust-lang/rust/pull/127687#discussion_r1679027883). Now this happens, but it's a bit fragile as you can see with the `TypeSuperVisitable for Ty` impl.

We will catch any problems around Ty, Region or Const at runtime with an assert, and everything using derives will not have such issues, as it will just invoke the `TypeVisitable for ErrorGuaranteed` impl

### CODE REVIEW

**Comment by oli-obk** [comment]
We could use derives for `TyKind`, `ConstKind` and `RegionKind` to avoid the hand written impls, but not sure that has a perf impact and it's also annoying to do: https://github.com/oli-obk/rust/pull/new/tainting_visitors

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
r=me if perf is ok.

**Review by lcnr — COMMENTED** [review]
you also have to update the `HasTypeFlags` visitor, don't you?

**Pull request merged**
