### PR TITLE
make MCP510 behavior opt-in to avoid conflicts between the CLI and target flavors

### LINKED ISSUE #113597: Regression when using `linker=arm-none-eabi-gcc`
The [cortex-m](https://github.com/rust-embedded/cortex-m) CI tests building with all our supported linkers: Rust's provided `lld`, ARM GCC's `arm-none-eabi-ld`, and ARM GCC's `arm-none-eabi-gcc`. It recently encountered an error when using `arm-none-eabi-gcc` in nightly builds since #112910.

The most likely culprit is that the failing version has started added `"-fuse-ld=lld"` to the linker arguments, which was not present in previous working versions. @lqd, I wonder if we're meant to be adding some other argument to disable adding `-fuse-ld=lld`?

### Code

The error occurs with the cortex-m-rt CI and can be reproduced like so:

```
git clone https://github.com/rust-embedded/cortex-m
cd cortex-m/cortex-m-rt
rustup toolchain install nightly-2023-07-03
rustup target add thumbv6m-none-eabi --toolchain nightly-2023-07-03
cargo +nightly-2023-07-03 rustc --target thumbv6m-none-eabi --example alignment --features cortex-m/critical-section-single-core -- -C linker=arm-none-eabi-gcc -C link-arg=-nostartfiles
```

Or viewed in CI [here](https://github.com/rust-embedded/cortex-m/actions/runs/5525648825/jobs/10079495043?pr=483).

The error is:

```
error: linking with `arm-none-eabi-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="<snip>" VSLANG="1033" "arm-none-eabi-gcc" "/tmp/rustcFHUl0t/symbols.o" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/examples/alignment-c363c9558a2fe06e.15yn3mrxz53m7uw7.rcgu.o" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/examples/alignment-c363c9558a2fe06e.6wqau5vl49hu4fi.rcgu.o" "-Wl,--as-needed" "-L" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/deps" "-L" "/home/adam/Projects/re/cortex-m/target/debug/deps" "-L" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/build/cortex-m-rt-69b7ab10efe30aa1/out" "-L" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "-Wl,-Bstatic" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/deps/libpanic_halt-f60a67ec71296eeb.rlib" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/deps/libcortex_m_rt-9a1a89eba3425cf7.rlib" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/librustc_std_workspace_core-cc16e9be0f247487.rlib" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/libcore-b9a65150d0351313.rlib" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/libcompiler_builtins-2769d4646d3d396e.rlib" "-Wl,-Bdynamic" "-fuse-ld=lld" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "-o" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/examples/alignment-c363c9558a2fe06e" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "-nostartfiles" "-Tlink.x"
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
```

### Version it worked on

nightly-2023-07-02

### Version with regression

nightly-2023-07-03

bisected to https://github.com/rust-lang/rust/commit/8e2d5e3a584b15ffee14984cb0b0986f00754b3d

from PR https://github.com/rust-lang/rust/pull/112910

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by lqd**
Fixes #113597, which contains more details on how this happens through the code, and showcases an unexpected `Gnu(Cc::Yes, Lld::Yes)` flavor.

#112910 added support to use `lld` when the flavor requests it, but didn't explicitly do so only when using `-Clink-self-contained=+linker` or one of the unstable `-Clinker-flavor`s. 

The problem: some targets have a `lld` linker and flavor, e.g. `thumbv6m-none-eabi` from that issue. Users can override the linker but there are no linker flavors precise enough to describe the linker opting out of lld: when using `-Clinker=arm-none-eabi-gcc`, we infer this is a `Cc::Yes` linker flavor, but the `lld` component is unknown and therefore defaulted to the target's linker flavor, `Lld::Yes`. 

<details>
<summary>Walkthrough of how this happens</summary>

The linker flavor used is a mix between what can be inferred from the CLI (`-C linker`) and the target's default linker flavor:

- there is no linker flavor on the CLI (and that also offers another workaround on nightly: `-C linker-flavor=gnu-cc -Zunstable-options`), so it will have to be inferred [from here](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_codegen_ssa/src/back/link.rs#L1334-L1336) to [here](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_codegen_ssa/src/back/link.rs#L1321-L1327).
- in [`infer_linker_hints`](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_target/src/spec/mod.rs#L320-L352) `-C linker=arm-none-eabi-gcc` infers a `Some(Cc::Yes)` cc hint, and no hint about lld. 
- the target's `linker_flavor` is combined in `with_cli_hints` with these hints. We have our `Cc::Yes`, but there is no hint about lld, [so the target's flavor `lld` component is used](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_target/src/spec/mod.rs#L356-L358). It's [`Gnu(Cc::No, Lld::Yes)`](https://github.com/rust-lang/rust/blob/993deaa0bf8bab9dd3eadfd1fbeb093328e95afe/compiler/rustc_target/src/spec/thumb_base.rs#L35).
- so we now have our `Gnu(Cc::Yes, Lld::Yes)` flavor

</details>

This results in a `Gnu(Cc::Yes, Lld::Yes)` flavor on a non-lld linker, causing an additional unexpected `-fuse-ld=lld` argument to be passed.

I don't know if this target defaulting to `rust-lld` is expected, but until MCP510's new linker flavor are stable, when people will be able to describe their linker/flavor accurately, this PR keeps the stable behavior of not doing anything when the linker/flavor on the CLI unexpectedly conflict with the target's.

I've tested this on a `no_std` `-C linker=arm-none-eabi-gcc -C link-arg=-nostartfiles --target thumbv6m-none-eabi` example, trying to simulate one of `cortex-m`'s test mentioned in issue #113597 (I don't know how to build a local complete  `thumbv6m-none-eabi` toolchain to run the exact test), and checked that `-fuse-lld` was indeed gone and the error disappeared.

r? @petrochenkov

### CODE REVIEW

**Comment by lqd** [comment]
If vadim agrees this is a good direction, compared to e.g. changing flavor inference and hints, then we could nominate it for a backport since #112910 is already in beta.

**Comment by petrochenkov** [comment]
Why doesn't `-fuse-ld=lld` work with `arm-none-eabi-gcc`?
Does that version of gcc simply not support `-fuse-ld=lld`, or it works but it's not able to find lld shipped with rustc?

**Comment by petrochenkov** [comment]
Ok, I did some more testing and figured what happens too.

- The directory containing shipped `rust-lld` (`<toolchain>/lib/rustlib/x86_64-unknown-linux-gnu/bin`) is added to search paths  is added to search directories (despite `+linker` not being specified), that's why the target finds its `rust-lld` linker and works by default.
- The directory containing shipped `ld.lld` (`<toolchain>/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld`) is not added to search paths, that's why the `-fuse-ld=lld` doesn't find its `ld.lld` linker (unless `+linker` is specified).

>in the `cortex-m` test, they're not using self-contained linking

They do use self-contained linking because they find and use lld shipped with rustc.
`+linker` is just not fully implemented yet, otherwise it would control whether rust-lld shipped with rustc would be found or not, and the `thumbv6m-none-eabi` target's spec would enable `+linker` by default.
(The two directories mentioned above should also be merged into one.)

**Comment by lqd** [comment]
> (For now I'm ignoring that the underlying linker change from ld to lld can also be surprising even if both work successfully.)

I was myself mostly concerned about that: adding `-fuse-ld=lld` where lld wasn't used before. Hence this PR bailing out so that `-Clinker=arm-none-eabi-gcc`  keeps using `arm-none-eabi-ld.bfd`.

> My point is that the case in https://github.com/rust-lang/rust/issues/113597 should actually work.

There were two ways to think about this: we could do nothing when none of the unstable flags are used, or change the target specs defaulting to `rust-lld` to enable `+linker`.  Otherwise we get the discrepancy you're mentioning of having 2 ways to use the exact same linker, with one of them failing due to the missing search path.

Would you prefer I close this PR and update the target specs like `thumbv6m-none-eabi`'s instead ?

**Comment by lqd** [comment]
Though as I said, the description in https://github.com/rust-lang/rust/issues/113597#issuecomment-1633328663 makes me think that the future end goal for these use-cases is to be able to opt out of lld when needed, via `-Clinker=arm-none-eabi-gcc -Clinker-flavor=gnu-cc`.

**Comment by petrochenkov** [comment]
>Would you prefer I close this PR and update the target specs like `thumbv6m-none-eabi`'s instead ?

No, just thinking aloud about a possible long term solution.

**Comment by petrochenkov** [comment]
I wonder what a good non-temporary solution for the inference would look like.

- If the default is `(Cc::No, Lld::Yes)` (e.g. `rust-lld`)
  - and we switch to some specific platform compiler (e.g. `-C linker=arm-none-eabi-gcc`), should we change to `Lld::No`? Maybe yes?
  - and we switch to some non-default but generic compiler `-C linker=clang`? Then maybe not?
- If the default is `(Cc::Yes, Lld::Yes)` (e.g. future x86_64 linux with default LLD)
  - and we switch to some specific platform compiler (e.g. `-C linker=arm-none-eabi-gcc`), should we change to `Lld::No`? Maybe yes?
  - and we switch to some non-default but generic compiler `-C linker=clang`? Then maybe not?

Maybe the value should depend on the value of `-Cself-contained:+linker`?

Or maybe we should just keep the current scheme because it's simple, and it's all guessing anyway, and if the new linker flavors are stabilized then we can guess wrong.

**Comment by lqd** [comment]
#113597 is now on beta, nominating this PR for backport.

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-07-20/near/376994753)

@rustbot label +beta-accepted

**Pull request merged**
