### PR TITLE
Upload builds from GHA instead of Azure Pipelines

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR does two things:

* Enables RLA comments on PRs (needed after the switch to GHA in RLA).
* Switches GitHub Actions as the CI authorized to upload non-macOS builds.

Note that Docker/LLVM caches will likely be busted.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Will the dummy-credentials just be no-op uploads? I imagine we'll want to make sure that docker caches for example still work on Azure so we're not busting them continuously (or stop running jobs entirely instead of dummy-var'ing them).

**Comment by pietroalbini** [comment]
The dummy credentials are the existing gha buckets.

**Comment by Mark-Simulacrum** [comment]
Ah okay, that makes more sense. Unfortunate naming :/

r=me when ready

**Comment by pietroalbini** [comment]
@bors r=Mark-Simulacrum

This will likely fail one time.

**Comment by Mark-Simulacrum** [comment]
```
2020-07-20T17:46:47.9653699Z + /scripts/validate-toolstate.sh
2020-07-20T17:46:47.9705032Z Cloning into 'rust-toolstate'...
2020-07-20T17:46:48.5729316Z <Nothing changed>
2020-07-20T17:46:48.7351930Z Traceback (most recent call last):
2020-07-20T17:46:48.7352697Z   File "../../src/tools/publish_toolstate.py", line 286, in <module>
2020-07-20T17:46:48.7353324Z     validate_maintainers(repo, github_token)
2020-07-20T17:46:48.7353970Z   File "../../src/tools/publish_toolstate.py", line 87, in validate_maintainers
2020-07-20T17:46:48.7355615Z     'Accept': 'application/vnd.github.hellcat-preview+json',
2020-07-20T17:46:48.7356332Z   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
2020-07-20T17:46:48.7356917Z     return opener.open(url, data, timeout)
2020-07-20T17:46:48.7357511Z   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
2020-07-20T17:46:48.7358065Z     response = meth(req, response)
2020-07-20T17:46:48.7358662Z   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
2020-07-20T17:46:48.7359637Z     'http', request, response, code, msg, hdrs)
2020-07-20T17:46:48.7360565Z   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
2020-07-20T17:46:48.7361135Z     return self._call_chain(*args)
2020-07-20T17:46:48.7361767Z   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
2020-07-20T17:46:48.7362328Z     result = func(*args)
2020-07-20T17:46:48.7362895Z   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
2020-07-20T17:46:48.7363576Z     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2020-07-20T17:46:48.7364203Z urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

Doesn't seem spurious.

**Comment by pietroalbini** [comment]
Woops, configured the wrong token in Azure.

@bors retry

**Comment by Mark-Simulacrum** [comment]
Hm well now you're forbidden not unauthorized...

```
2020-07-20T21:36:43.3315998Z   File "../../src/tools/publish_toolstate.py", line 286, in <module>
2020-07-20T21:36:43.3316489Z     validate_maintainers(repo, github_token)
2020-07-20T21:36:43.3316982Z   File "../../src/tools/publish_toolstate.py", line 87, in validate_maintainers
2020-07-20T21:36:43.3318330Z     'Accept': 'application/vnd.github.hellcat-preview+json',
2020-07-20T21:36:43.3318845Z   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
2020-07-20T21:36:43.3319312Z     return opener.open(url, data, timeout)
2020-07-20T21:36:43.3319759Z   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
2020-07-20T21:36:43.3320200Z     response = meth(req, response)
2020-07-20T21:36:43.3320894Z   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
2020-07-20T21:36:43.3321668Z     'http', request, response, code, msg, hdrs)
2020-07-20T21:36:43.3322148Z   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
2020-07-20T21:36:43.3322573Z     return self._call_chain(*args)
2020-07-20T21:36:43.3323031Z   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
2020-07-20T21:36:43.3323468Z     result = func(*args)
2020-07-20T21:36:43.3323901Z   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
2020-07-20T21:36:43.3324433Z     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2020-07-20T21:36:43.3324907Z urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pietroalbini** [comment]
Gah.

@bors retry

**Comment by Manishearth** [comment]
@bors retry

```
Attempting with retry: aws s3 cp --no-progress --recursive --acl public-read /tmp/tmp.DLyVh63HIg s3://rust-lang-ci2/rustc-builds/99fd67637a71263d6dbec7f16550ee68eb91bb54
upload failed: ../../../../../tmp/tmp.DLyVh63HIg/cpu-mingw-check.csv to s3://rust-lang-ci2/rustc-builds/99fd67637a71263d6dbec7f16550ee68eb91bb54/cpu-mingw-check.csv An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Command failed. Attempt 2/5:
upload failed: ../../../../../tmp/tmp.DLyVh63HIg/cpu-mingw-check.csv to s3://rust-lang-ci2/rustc-builds/99fd67637a71263d6dbec7f16550ee68eb91bb54/cpu-mingw-check.csv An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Command failed. Attempt 3/5:
upload failed: ../../../../../tmp/tmp.DLyVh63HIg/cpu-mingw-check.csv to s3://rust-lang-ci2/rustc-builds/99fd67637a71263d6dbec7f16550ee68eb91bb54/cpu-mingw-check.csv An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Command failed. Attempt 4/5:
upload failed: ../../../../../tmp/tmp.DLyVh63HIg/cpu-mingw-check.csv to s3://rust-lang-ci2/rustc-builds/99fd67637a71263d6dbec7f16550ee68eb91bb54/cpu-mingw-check.csv An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Command failed. Attempt 5/5:
upload failed: ../../../../../tmp/tmp.DLyVh63HIg/cpu-mingw-check.csv to s3://rust-lang-ci2/rustc-builds/99fd67637a71263d6dbec7f16550ee68eb91bb54/cpu-mingw-check.csv An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
The command has failed after 5 attempts.
```

**Comment by Manishearth** [comment]
I suspect that's not actually an intermittent, but could probably be fixed by fixing credentials cc @pietroalbini

**Comment by Manishearth** [comment]
@bors treeclosed-

unless someone is fixing this

**Comment by pietroalbini** [comment]
Wrong bucket name :/

@bors retry

**Comment by pietroalbini** [comment]
Ok this was "fun" to debug. We were previously using the API token as the git username and an arbitrary string as the password, but while that still works for the old token it doesn't work anymore for newly generated ones. To be honest I'm not sure why that's even allowed at all.

I tested it locally, and using the arbitrary string as the username and the API token as the password works, so the last commit I pushed switches toolstate to that approach.

r? @Mark-Simulacrum again?

**Comment by Manishearth** [comment]
```
Logon failed, use ctrl+c to cancel basic credential prompt.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Sleeping for 3 seconds before retrying push
From https://github.com/pietroalbini/rust-toolstate
 * branch            master     -> FETCH_HEAD
HEAD is now at b08d1af (windows CI update)
[master d1e8608] (windows CI update)
 1 file changed, 1 insertion(+)
Logon failed, use ctrl+c to cancel basic credential prompt.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Sleeping for 3 seconds before retrying push
From https://github.com/pietroalbini/rust-toolstate
 * branch            master     -> FETCH_HEAD
HEAD is now at b08d1af (windows CI update)
[master 893428f] (windows CI update)
 1 file changed, 1 insertion(+)
Logon failed, use ctrl+c to cancel basic credential prompt.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Sleeping for 3 seconds before retrying push
From https://github.com/pietroalbini/rust-toolstate
 * branch            master     -> FETCH_HEAD
HEAD is now at b08d1af (windows CI update)
thread 'main' panicked at 'Failed to update toolstate repository with new data', src\bootstrap\toolstate.rs:447:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to run: D:\a\1\s\build\bootstrap\debug\bootstrap test check-tools
Build completed unsuccessfully in 0:00:22
== clock drift check ==
  local time: Tue Jul 21 18:57:12 CUT 2020
  network time: Tue, 21 Jul 2020 18:57:12 GMT
== end clock drift check ==
```

**Comment by pietroalbini** [comment]
I swear I'm good at this. Let's try with the production token and with the username/password switch reverted.

@bors r=Mark-Simulacrum

**Pull request merged**
