### PR TITLE
Revive suggestions for boxed trait objects instead of impl Trait

### PR DESCRIPTION
**Pull request by TaKO8Ki**
The suggestion implemented in #75608 was not working properly, so I fixed it.

### CODE REVIEW

**Comment by compiler-errors** [comment]
@TaKO8Ki it has only been 6 days since you've submitted this PR, so please wait a bit longer before requesting a new reviewer 😅

**Comment by TaKO8Ki** [comment]
@compiler-errors I had a conflict and requested a review, but as you said, I'll wait a little longer.

**Comment by compiler-errors** [comment]
r? is to get a new reviewer, not to signal that the PR is ready for a review. But since I already am notified for this, I can take a look later today after a flight.

r? @compiler-errors

**Comment by compiler-errors** [comment]
Looks good!

@bors r+

**Pull request merged**
