### PR TITLE
ci: use free runner in dist-i686-msvc

### PR DESCRIPTION
**Pull request by marcoieni**
I already tried this in https://github.com/rust-lang/rust/pull/132316#issuecomment-2444763685 and I thought this would take too long. However, the slowness was due to llvm cache not being hit.
Instead, we need to compare timings with an llvm cache hit.
So now I'm trying again.

try-job: dist-i686-msvc

### CODE REVIEW

**Comment by MarcoIeni** [comment]
What a committed team 😂

**Comment by Kobzol** [comment]
Yeah, looks good! Let's do this.

@bors r+

**Comment by klensy** [comment]
There is no mention of actual time change after this pr.

I found few build time from before: 1.14, 1.26, so this degrades build times 1.5x?

**Comment by MarcoIeni** [comment]
Hey, you are right, sorry!

This moves the build time from ~80 minutes to (apparently) 1h 53 minutes.

However, on average auto builds take more than 2h 30 minutes.

An auto build is done when the the slowest job finishes (which for now are often the macos ones).

So making this job slower has no impact on the auto builds velocity. 👍

**Pull request merged**
