### PR TITLE
Arenas cleanup

### PR DESCRIPTION
**Pull request by nnethercote**
I was looking closely at the arenas code and here are some small improvement to readability.

### CODE REVIEW

**Comment by nnethercote** [comment]
@bors rollup=always

Because this is a combination of comment changes and trivial code changes.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/91016#issuecomment-973082529
@bors r-

```
 error: this URL is not a hyperlink
   --> compiler/rustc_arena/src/lib.rs:338:13
    |
338 |     /// see fitzgeraldnick.com/2019/11/01/always-bump-downwards.html.)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<fitzgeraldnick.com/2019/11/01/always-bump-downwards.html.>`
    |
    = note: `-D rustdoc::bare-urls` implied by `-D warnings`
    = note: bare URLs are not automatically turned into clickable links
```

**Comment by nnethercote** [comment]
> ```
>  error: this URL is not a hyperlink
>    --> compiler/rustc_arena/src/lib.rs:338:13
>     |
> 338 |     /// see fitzgeraldnick.com/2019/11/01/always-bump-downwards.html.)
>     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<fitzgeraldnick.com/2019/11/01/always-bump-downwards.html.>`
> ```
Huh, I didn't see this with `./x.py test`. Is there a command I could have run locally to catch this?

Also, curious that the leading `https://` has been stripped in that error message.

Anyway, I've updated: @bors r=oli-obk

**Comment by JohnTitor** [comment]
> Huh, I didn't see this with `./x.py test`. Is there a command I could have run locally to catch this?

The warning is generated by rustdoc so you could see it via `./x.py doc`, I guess (yeah, it's kinda annoying to use that command just for a compiler/library change..., I don't know how we trigger it via other commands.)

> Also, curious that the leading `https://` has been stripped in that error message.

The scheme somehow has been stripped when copy/pasting 🤔, it's not a fault of the warning.

**Pull request merged**
