### PR TITLE
[experiment] rustc_mir: remove `#![type_length_limit]` checks.

### PR DESCRIPTION
**Pull request by eddyb**
The first time we started doubting the usefulness of this check was in #54540, but it's been showing up more.

I've since learned that the PR which added this (#37789) did fix a real issue (#37311) but IMO it's not the most efficient solution (we could instead e.g. periodically warn that monomorphization collection is still ongoing, and that it could indicate an accidental generic blowup), though we may not have anything better in general.

Nevertheless, I think it's a good idea to try this out, even if it may be too late for certain regressions.

This PR was specifically prompted by @hawkw running into a slowdown which may be caused by the `#![type_length_limit]` check, but we don't really know much for certain yet (and a try build is the easiest comparison that has some guarantees of fairness, plus we can get the perf run results).

cc @nikomatsakis @pnkfelix @arielb1 @lcnr

### CODE REVIEW

**Comment by eddyb** [comment]
So 1% at best, and only on `incr-unchanged` runs. Also, from what I'm hearing, it doesn't help much (even if it does lower compile times a bit) for the usecase that motivated this PR.

Perhaps we could test further on some of the reported regressions?

**Comment by camelid** [comment]
@eddyb It appears there are merge conflicts.

**Comment by nikomatsakis** [comment]
So chalk uses a type-length limit test but in a different way. Instead of forbidding types completely, it "just" causes trait solving to yield ambiguous results when types are getting too big.

**Comment by nikomatsakis** [comment]
Closing this as it's a super old experiment

**Pull request closed without merging**
