### PR TITLE
lint: convert incoherent_fundamental_impls into hard error

### PR DESCRIPTION
**Pull request by hdhoang**
*Summary for affected authors:* If your crate depends on one of the following crates, please upgrade to a newer version:
- gtk-rs: upgrade to at least 0.4
- rusqlite: upgrade to at least 0.14
- nalgebra: upgrade to at least 0.15, or the last patch version of 0.14
- spade: upgrade or refresh the Cargo.lock file to use version 1.7
- imageproc: upgrade to at least 0.16 (newer versions no longer use nalgebra)

implement #46205

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
This looks great, thanks!

**Comment by nikomatsakis** [comment]
@bors try

cc @rust-lang/infra -- gonna want a crater run of this

**Comment by kennytm** [comment]
@bors clean

The try build is successful.

**Comment by Mark-Simulacrum** [comment]
Crater has been started in check-only mode, though we're testing a beta improved version of Crater so this could turn out to take up to 5-6 days with restarts.

**Comment by Mark-Simulacrum** [comment]
Crater results are at: http://cargobomb-reports.s3.amazonaws.com/pr-49799/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/config.toml). If you see any spurious failures not on the list, please make a PR against that file.

(interested observers: Crater is a tool for testing the impact of changes on the crates.io ecosystem. You can find out more at the [repo](https://github.com/rust-lang-nursery/crater/) if you're curious)

**Comment by hdhoang** [comment]
I'm collecting the primary failures. Meanwhile `lru-disk-cache` is already fixed, and that fix links to this comment with several of the primaries mentioned: https://github.com/rust-lang/rust/pull/46192#issuecomment-349056049

**Comment by nikomatsakis** [comment]
@hdhoang The 'known issues' were reported in the original issue or something like that? 

As for nalgebra and pin-api, cc @sebcrozet and @withoutboats, seems like these crates are relying on a bug (`INCOHERENT_FUNDAMENTAL_IMPLS`) that we would like to remove support for. Have you any idea how to fix those errors? (I've not looked closely)

**Comment by nikomatsakis** [comment]
OK, so, I would like to **close** this forwards compatibility lint, converting it into a hard error. However, I'm not psyched about breaking 131 crates. @hdhoang or @rust-lang/release, is there an easy way to understand which root crates are responsible for each failure? I'd like to see if there are a few places where we can push hard on getting a fix published in order to mitigate the impact.

**Comment by hdhoang** [comment]
the known issues were discovered in #46192 by its crater run, with elaboration by @arielb1 here https://github.com/rust-lang/rust/pull/46192#issuecomment-349056049

all but bow already have fixes, either in later versions or an unmerged branch. A large swath is from glib or rusqlite, so we need the graph and then pinging the maintainers whose dependencies pull in those.

nalgebra is the root for a bunch of regressions though, and has no fix yet.

**Comment by sebcrozet** [comment]
@hdhoang A [fix](https://github.com/sebcrozet/nalgebra/pull/333) is now ready for `nalgebra`. Though this required a breaking change (renaming some methods).

**Comment by pietroalbini** [comment]
@nikomatsakis while it might not be needed anymore, I already wrote the code of [crater-tree](https://github.com/pietroalbini/crater-tree), so here is the dependency graph:

<details>
<pre>
elastic
rspotify
swc-hosts
annatar
geocoding
constellation-server
hecate
nickel_sqlite
tv-renamer
flow_between
iron_rusqlite_middleware
sc2
trust-dns-server
planetkit
screenruster-saver-laughing_man
gaia
txtr
artano
voc-perturb
kiss3d
  ncollide_testbed3d
  lafont
way-cooler-background
processing
rshare
softrender
plexus
nalgebra
  spade
    geo
      elastic_types
      geohash
      geojson
      scarlet
      wkb
      gdal
      polylabel
      tilecover
      proj
      geos
      mapbox_vector_tile
      osm_boundaries_utils
  simple-fcl
  silkbag
  bbox
  ncollide_pipeline
    ncollide_testbed2d
    nphysics3d
    nphysics2d
      nitro
  ncollide_procedural
  ncollide_math
    ncollide_geometry
  timecode
  map18xx
  bvh
  nyx-space
  coord_transforms
  trk-io
  riscan-pro
  steering
  mel
  spherical-cow
  na
  kalman_filter
  ahrs
  k
  iwls
  graph-neighbor-matching
dbmigrate-lib
  dbmigrate
clfft
ocl-extras
poisson
generate-nix-pkg
carnix
respk
schemer-rusqlite
flo_anim_sqlite
raudient
juju
rusqlite
  serde_rusqlite
  citadel-crud
  r2d2_sqlite
  database_exporter
  adbackup
avr-vm
vorbis-shortener
rrt
glib
  cairo-rs
    gdk
      gtk
        relm-test
        cedar
        relm-core
        obozrenie-gtk
        msgbox
  gdk-pixbuf
  glib-itc
lru-disk-cache
bow
  multistr
    parse-hosts
pin-api
</pre>
</details>

**Comment by nikomatsakis** [comment]
@hdhoang 

> so we need the graph and then pinging the maintainers whose dependencies pull in those.

Hmm, so I had imagined we might be able to make new "patch releases" to the key crates. But I guess that -- in general -- it may not be possible in this case, since it likely requires removing an impl. Hmm.

**Comment by nikomatsakis** [comment]
@hdhoang while we ponder how best to proceed, it occurs to me that maybe we should *at least* go to deny-by-default to start. I am shocked to see e.g. `pin-api` in that list (cc @withoutboats), and I imagine a deny-by-default lint would help stop the problem from getting worse.

**Comment by nikomatsakis** [comment]
@hdhoang think you'd be up for opening that as a quick PR?

**Comment by hdhoang** [comment]
I'm afk until the 2nd though, you can make another call for first-contribution (that's how I got hooked).

**Comment by nikomatsakis** [comment]
@hdhoang ok -- though if you think you can do it on the 2nd or so, that seems 'soon enough'. But maybe you'll be busy =)

**Comment by shepmaster** [comment]
Ping from triage @nikomatsakis ! Will you have time to continue the review of this soon?

**Comment by nikomatsakis** [comment]
@hdhoang can you rebase (so as not to have a "merge commit")?

**Comment by nikomatsakis** [comment]
@shepmaster there really isn't any "review" needed, it's more of a policy question at this point. How much breakage will we cause and are we willing to do that...(and/or can we think of ways to circumvent it)

**Comment by nikomatsakis** [comment]
So the current status as I understand it is roughly this:

- This bugfix is needed to preserve soundness of coherence; we have been warning for a fairly long time
  - Since [Nov 2017, specifically](https://github.com/rust-lang/rust/issues/46205). 
- However, there are a large number of extant crates (131) that would be affected by making this a hard error:
  - almost all of these are due to dependencies on older versions of libs; the newer versions are fixed, but the fixes are not backwards compatible.
  - you can see the [dependency tree here](https://github.com/rust-lang/rust/pull/49799#issuecomment-384953032)
- We recently landed a PR that moves the lint to deny-by-default, but it still remains a lint
  - since most of these errors are in outdated dependencies, which have capped lints, I am not optimistic that this will cause much migration, but it may.

Options I see:

- Wait and re-run crater in a few months. I'm not too keen on maintaining the existing code, but we can probably do it.
- Land this change, breaking those crates until they migrate.
- Land semver-violating fixes to those crates. This may or may not affect the *consumers*, since they may or may not use the APIs that had to break. I don't know if we can test that.
  - I'm not sure if this is a "real option".

cc @rust-lang/compiler @rust-lang/lang @rust-lang/core -- thoughts?

**Comment by oli-obk** [comment]
How hard would it be to update the consumers to use the new fixed versions?

**Comment by wycats** [comment]
It feels like we're missing a capability in our lint capping system: the ability to have a "deny by default but warn transitively" for situations where we are about to break the supporting code.

I'd worry it could be overused (all of the reasons that we have lint capping in the first place make getting more aggressive on transitive lints unlikely to have the desired effect in most cases), but if we're literally about to break the supporting code, giving people a heads up that this is going to happen seems useful.

I've always believed that any warnings that we allow through from transitive deps should be summarized at the end of the run, not included inline.

**Comment by shepmaster** [comment]
> we have been warning for a fairly long time
> Since Nov 2017, specifically.

If I'm reading it correctly, [that commit](https://github.com/rust-lang/rust/commit/2614cc51dde5e57983dd9809372845073ac30aac) has only been present in stable Rust since 1.24, which isn't really that long of a time:

image

It might have been backported to a beta, which I didn't check.

**Comment by nikomatsakis** [comment]
Bah. I was writing up a comment here but it seems to have gotten lost. Some notes:

First, yeah, I guess the warnings haven't been in effect that long in terms of *stable releases*. Maybe it behooves us to wait a little longer, particularly since @hdhoang recently landed the "deny by default", which *may* help?

We could also make some active effort to upgrade people to the newer packages -- at the very least pinging the maintainers would be polite.

Finally, @alexcrichton asks how urgent it is -- I think we can probably keep the lint in for a while longer. At some point it will become untenable and I was "looking forward", trying to clear obstacles, but I think we're not at that point yet. 

So probably the next step is to start alerting the maintainers of packages that they ought to update (and/or do some of those updates ourselves). I wonder if it'd be worth automating some tooling here.. like something that will craft a nice comment which pings maintainers and includes a checklist. 

@pietroalbini -- what do you think about that =) it'd be great to have something that emitted a markdown template that one could then copy-and-paste and add various details. Would that be hard to do?

**Comment by joshtriplett** [comment]
We discussed this in the lang team meeting; we share the concern about the number of crates this would break. Let's revisit this when the deny-by-default lint gets into stable, and we get some movement/communication from the crates it breaks.

**Comment by pietroalbini** [comment]
> @pietroalbini -- what do you think about that =) it'd be great to have something that emitted a markdown template that one could then copy-and-paste and add various details. Would that be hard to do?

I wrote a script for that during the last beta triage, and while it's not pretty it can be easily adapted. [gist](https://gist.github.com/pietroalbini/57155492c8fcb07972ca485a7b22a6e2)

**Comment by hdhoang** [comment]
I have made a graph of the transitive dependencies https://gist.github.com/hdhoang/b8638df95322b2650c311d088972ea61

The nalgebra clusters have spade and several geo-related crates as focal points.

Of the glib-related, way-cooler-background looks small & active. I will try to cargo upgrade it first.

**Comment by nikomatsakis** [comment]
@hdhoang that graph is awesome =) I didn't get a chance to run @pietroalbini's script yet, but I will do so today

**Comment by nikomatsakis** [comment]
@sebcrozet based on [this README], it seems like the latest version of nalgebra is not yet released? I don't think I can recommend everybody migrate to git master -- do you think you can cut the `0.15.0` release? Or can they migrate to something else for now?

[this README]: https://github.com/sebcrozet/nalgebra/blob/master/CHANGELOG.md#modified

**Comment by nikomatsakis** [comment]
@hdhoang 

> all but bow already have fixes, either in later versions or an unmerged branch. A large swath is from glib or rusqlite, so we need the graph and then pinging the maintainers whose dependencies pull in those.

When you wrote this, what is the "all" you are referring to? All the "top-level failures" identified by @pietroalbini [here](https://github.com/rust-lang/rust/pull/49799#issuecomment-384953032)? (Can't be, I suppose, since otherwise why would crater be testing them?)

I'm trying to figure out which crates precisely to notify and what to tell them. =) Is there a new version of glib available that fixes the problem?

**Comment by pietroalbini** [comment]
By the way, looking at my top levels, some of them have rusqlite as a dependency, I guess I did something wrong while building the dependency graph `:/`

**Comment by hdhoang** [comment]
At that time, by "all" I meant the "known issues" list (namely `lru-disk-cache 0.1`, `glib 0.1`, `bow 1.0.3`, `rusqlite`, `ocl`), first [collected for the original fix's crater run](https://github.com/rust-lang/rust/pull/46192#issuecomment-349056049).

Here's a new progress report:
- lru-disk-cache 0.1 has been [fixed and released as 0.2](https://github.com/mozilla/sccache/commit/d14852991d39edccf4bc91f04577fcdf393de430#diff-cdbc3f31c4dbee3e4c63deab36e8f78c)
- ocl 0.13, 0.15 has been [fixed and released in 0.17 and later](https://github.com/cogciprocate/ocl/commit/d4768a7e258438301f040a0058ec0929b96846ea)
- glib 0.1 has been fixed in [this commit, released in version 0.4 and later](https://github.com/gtk-rs/glib/commit/b36de4e9c38fb7be534fb7f17ec9eae3b2d3cd26#diff-dd26c2766e65aca43e4228e64ebd0cf8)
- nalgebra has [fixed in 0.14.2 and later](https://github.com/sebcrozet/nalgebra/pull/333)
- rusqlite has [merged a fix](https://github.com/jgallagher/rusqlite/commit/89f38b40984424c9a18c6ceeed15d47e8f3d82bb)


I think the path forward differs for each root-cause:
- lru-disk-cache: run crater on v0.2
- ocl: ocl-extras is in the same repo, so we only need to port [clfft 0.3.1](https://crates.io/crates/clfft/0.3.1) forward
- glib 0.1 and related ecosystem (mainly GUI apps based on gtk-rs 0.1): porting them to gtk-rs 0.5
- nalgebra: very many crates need to be updated
- rusqlite: I guess the merged fix can be a semver-preserving patch to earlier versions? cc @gwenn

However, there are other crates not tested by crater yet. For example, in [ocl's reverse dependencies](https://crates.io/crates/ocl/reverse_dependencies), geogrid, geoshaper and ocl-algebra should be ported forward too.

Not fixed yet:
- bow cc @clarcharr : @arielb1 said "I think the only fix is to not use `Into` but instead use an `into_box` function." in the linked comment above
- pin-api cc @withoutboats : I guess this is only a preview for `std`-included functionality, so coherence issue is okay for now?

crater-related: @pietroalbini Should I add `rspotify` to the blacklist for [this timeout](https://cargobomb-reports.s3.amazonaws.com/pr-49799/ecb60b3c2f42741c46899792e9c932714c8a3147/reg/rspotify-0.1.2/log.txt)?

**Comment by hdhoang** [comment]
@clarcharr thanks for your input! Since the downstream crates (multistr 0.5.2, parse-hosts 0.5.0, and swc-hosts 0.2.1) are also yours, could you port them away from bow?

@pietroalbini bow can be added to the blacklist too.

**Comment by pietroalbini** [comment]
> crater-related: @pietroalbini Should I add rspotify to the blacklist for this timeout?

Yeah, but it should be marked with `slow = true`, not with `skip = true`.

> @pietroalbini bow can be added to the blacklist too.

Nah, if it's a real failure and not spurious there is no need to add a crate to the blacklist, it will just be marked as `build-fail` in the next runs.

**Comment by clarcharr** [comment]
@hdhoang That's been the plan for a while; I just haven't gotten around to it. I'll update the maintenance badges for these crates within the next few days.

**Comment by hdhoang** [comment]
ah, crater doesn't enable optional features, thus it will miss some broken downstream cases (eg `basic_dsp` optionally uses `clfft` which is broken by old `ocl`). I will try to build a more comprehensive graph with crates.io API.

@pietroalbini How can we crater optional dependencies? `--all-features` could enable mutually-exclusive features I imagine.

**Comment by pietroalbini** [comment]
Ugh, good question. Can you open an issue in [rust-lang-nursery/crater](https://github.com/rust-lang-nursery/crater)?

**Comment by clarcharr** [comment]
Just wanted to update and say that I finally marked the `bow` crate as deprecated on crates.io. I also published a new major version which exports no code, so, it shouldn't cause crater any problems.

I'm not sure if crater reads the maintenance badges on crates.io and outright ignores deprecated crates, but I figure that that would be desired.

**Comment by pietroalbini** [comment]
Ping from triage! What's the status on this?

**Comment by kennytm** [comment]
It is [blocked](https://github.com/rust-lang/rust/pull/49799#issuecomment-390618050) by rust-lang-nursery/crater#235.

**Comment by pietroalbini** [comment]
> I'm not sure if crater reads the maintenance badges on crates.io and outright ignores deprecated crates, but I figure that that would be desired.

Nope.

> It is blocked by rust-lang-nursery/crater#235.

I don't think that will be implemented soon. If we really want to do that I can patch crater on the fly to add `--all-features` though.

**Comment by Mark-Simulacrum** [comment]
I'm marking this as waiting for crater since I think it would be good to do another run (see if we can move forward with this).

**Comment by pietroalbini** [comment]
Hmm, what should the second crater run look like? If I understood the thread correctly we want a crater run testing all the features of a crate?

**Comment by hdhoang** [comment]
We also need a new rusqlite release to start porting its dependents too, so that there would be less to go through in the second run.

**Comment by stokhos** [comment]
Ping from triage @hdhoang is this PR ready for crater yet?

**Comment by hdhoang** [comment]
The PR's content is ready for another crater run, but the rusqlite-dependent crates haven't been fixed yet. If crater has gained optional-dependency tracking, I would love to see the updated result too.

**Comment by pietroalbini** [comment]
That's probably not going to happen in a while... `:(`

**Comment by TimNN** [comment]
Ping from triage @hdhoang, @pietroalbini, @nikomatsakis: What is the status of this PR? If I understand correctly it is blocked on a crater run, which is blocked on a crater feature request, which won't be happening soon. Is that correct?

**Comment by hdhoang** [comment]
We are only hard-blocked on rusqlite's next release, as breaking the SQLite-using ecosystem is too painful.

As mentioned by @gwenn in the issue linked above, we would like to upgrade the ecosystem out of the affected version ranges for the crates mentioned in https://github.com/rust-lang/rust/pull/49799#issuecomment-389079493
We can comb through crates.io reverse-dep pages for them to find the relevant broken crates manually. Discovery could be more automated I'm sure, but I haven't investigated that route.

The crater feature request is nice to have to automatically discover and verify that we have ported all affected crates (I imagine rusqlite is popular as optional-dep).

**Comment by nikomatsakis** [comment]
I wonder if we should take another stab here. I see a lot of merged PRs in the list. =)

**Comment by hdhoang** [comment]
We could always allow the maintainers more time to publish new version on crates.io, since much of the failure list comes from the registry. I would like to propose valeriansaliou/constellation#5 as the milestone to trigger the next run. The fix chain is rusqlite -> trust-dns-server (just released) -> constellation.

nalgebra@0.14 compatibility shim was a nice swoop to fix a lot of crates, but I'm not sure crater will override an old/unshimmed version specified in Cargo.lock. cc @pietroalbini 

AIUI, #50390 (deny-by-default) has been released to the stable channel in 1.28 (3 months ago), but it doesn't trigger in dependencies' code (as with all lints), so the crates haven't upgraded aggressively out of this incompatibility.

**Comment by nikomatsakis** [comment]
@hdhoang sounds good

**Comment by pietroalbini** [comment]
> nalgebra@0.14 compatibility shim was a nice swoop to fix a lot of crates, but I'm not sure crater will override an old/unshimmed version specified in Cargo.lock. cc @pietroalbini 

Nope.

**Comment by nikomatsakis** [comment]
What we could do is to issue a "patch release" for older versions of nalgebra, if there aren't too many.

**Comment by hdhoang** [comment]
I'll need some time to rework this around #56481. Strangely bors doesn't update the conflict status here.

**Comment by hdhoang** [comment]
Hmm I wrongfully emitted a lint-denial for the other issue. Probably I chose the wrong `traits::IntercrateMod` in `Children::insert`.

**Comment by Centril** [comment]
@hdhoang @nikomatsakis what's the status of this PR now?

**Comment by hdhoang** [comment]
hi! thanks for checking back with us. constellation hasn't been updated, and I should go around and ping the other inactive crates again too.

On the other hand, since the tracking issue has been expanded with detailed explanation and fix, and another PR has ran afoul of this lint, I lean towards another crater run when the crater queue is short. As always, I'm on standby to fix conflict as needed.

**Comment by Centril** [comment]
@craterbot run mode=check-only

**Comment by hdhoang** [comment]
I will table up the report and contact the authors.

**Comment by Dylan-DPC** [comment]
ping from triage @nikomatsakis awaiting your review on this 
@hdhoang you can resolve the conflict

**Comment by hdhoang** [comment]
thanks for the ping, I have sorted the conflict out.

**Comment by hdhoang** [comment]
I will force-push after #59945 is resolved.

**Comment by nikomatsakis** [comment]
@hdhoang so I'm not sure on the exact status here -- is this PR blocked on https://github.com/rust-lang/rust/issues/59945? I was going to schedule it for review on thu (I'm trying to schedule my queue now), but in that case I was also hoping you could do a summary of the current status.

**Comment by hdhoang** [comment]
@nikomatsakis I have resolved the conflict (it was a simple removed-lint appending conflict), but while building locally I encountered the bootstrap failure described there. I thought that pushing the resolution right then would leave this PR in a failed state, so I proposed waiting on fixing the bootstrap failure. Just now, I have rebased again and the build seems to progress normally.

On to this PR's status after the 2nd crater run, I have been contacting the affected authors with an issue template. I hope to get to them all by the end of the month. The progress I have so far is in https://gist.githubusercontent.com/hdhoang/b8638df95322b2650c311d088972ea61/raw/c938120ca0555fa533dd2c0a5831c7d2f1f56593/2nd-run.org

Since the eventual compiler error will point to the tracking issue, could you or someone add a section "What should I do to fix this error?" to the issue description? I suggest some text along the line of: 

```
If you are depending of the crates, please upgrade to a newer version:
- gtk-rs: upgrade to at least 0.4
- rusqlite: upgrade to at least 0.14
- nalgebra: upgrade to at least 0.15
- spade: upgrade or refresh the Cargo.lock file to use version 1.7
- imageproc: upgrade to at least 0.16
```

So that the authors have a clear action to take

**Comment by nikomatsakis** [comment]
Done

**Comment by nikomatsakis** [comment]
Er, wait, @hdhoang, was I supposed to ignore that suggestion? If so, I can revert the changes I made to https://github.com/rust-lang/rust/issues/46205...

**Comment by hdhoang** [comment]
@nikomatsakis hi! I have contacted the crates that exploded in the 2nd crater run. This PR only awaits your approval now.

Your addition to the tracking PR should stay, and I have added a "TLDR" to this PR as well. (I was having some incoherent thoughts back in that comment/update about the error message, but clarifying authors' course of action is helpful).

**Comment by hdhoang** [comment]
ping @nikomatsakis, could you review this PR?

**Comment by pnkfelix** [comment]
It seems like the issues here relate to how we end up resolving issue #34596 and PR #59658, right?

In particular, many people on this PR (#49799) have pointed out that a deny-by-default lint has landed, but such a lint will be silenced in dependent crates by `--cap-lints`, and thus there is insufficient incentive for crate clients to report bugs upstream to trhe maintainers of their dependent crates. That is exactly the problem described by issue #34596 (and with an attempted, though stalled, patch in PR #59658).

Should we postpone moving on this PR until issue #34596 is resolved? Or have I overlooked a detail here that motivates landing this change even with the overall future-incompat strategy still "up in the air"?

**Comment by pnkfelix** [comment]
nominating for discussion of previous comment at lang team meeting.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/lang meeting. Everyone who was there felt it was time to move forward, but that we ought to have an FCP. Therefore:

@rfcbot fcp merge

I propose to **merge** this PR, which will convert https://github.com/rust-lang/rust/issues/46205 into a hard error. This is a longstanding soundness hole in our coherence guarantees, and it became a warning in Nov of 2017. 

@hdhoang has heroically opened a lot of PRs (see attached comments on this PR). The number of known regressions **on crates.io** appears fairly minimal. I didn't count, but I would eyeball it at around 20-30 crates, none of which appeared to be major (but I might have missed some). I believe the errors can largely be corrected by upgrading dependencies (or merging pending PRs). There are also a fair number of regressions in random git repositories.

**Comment by nikomatsakis** [comment]
I'm leaving this nominated to remind people to check their boxes.

**Comment by nikomatsakis** [comment]
(NB, I checked @aturon's box as they are absent)

**Comment by Centril** [comment]
@rfcbot reviewed

Please wake up bot... :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
I'm going to approve since I think that FCP is very likely to complete without incident and we could always roll back if needed.

**Comment by nikomatsakis** [comment]
A 💯 ❤️ to @hdhoang for seeing this through!

**Comment by nnethercote** [comment]
This ended up being a big [perf win](https://perf.rust-lang.org/compare.html?start=73a3a90d25ddb3be3d0ad2238dbb55ae79e459dc&end=a614cee22e8d79766c6a6d0f63c28f12eaec63f4&stat=instructions:u) for `packed-simd`.

**Pull request merged**
