### PR TITLE
Put inline functions in only one CGU

### PR DESCRIPTION
**Pull request by Zoxc**
Revival of https://github.com/rust-lang/rust/pull/70459 for the purpose of up-to-date performance tests.

cc @nnethercote

### CODE REVIEW

**Comment by Zoxc** [comment]
I pushed another variation which keeps `inline(always` in multiple CGUs. That could use a perf run too.

**Comment by nnethercote** [comment]
Bootstrap and artifact size results are also bad, in addition to the compile-time results :(

**Pull request closed without merging**
