### PR TITLE
Fix the ICE described in #83693

### LINKED ISSUE #83693: ICE: panicked at 'assertion failed: !substs.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:1475:9
### Code

```Rust
impl F {
    fn call() {
        <Self as Fn(&TestResult)>::call
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (48691ea6e 2021-03-29)
binary: rustc
commit-hash: 48691ea6e639640f110b43e33d4aba1f07e7415c
commit-date: 2021-03-29
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
error[E0412]: cannot find type `F` in this scope
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:6
   |
1  |   impl F {
   |        ^ help: a trait with a similar name exists: `Fn`

error[E0412]: cannot find type `TestResult` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:22
  |
3 |         <Self as Fn(&TestResult)>::call
  |                      ^^^^^^^^^^ not found in this scope

error[E0601]: `main` function not found in crate `perses_node_priority_with_dfs_delta_reduced_mutant`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | / impl F {
2 | |     fn call() {
3 | |         <Self as Fn(&TestResult)>::call
4 | |     }
5 | | }
  | |_^ consider adding a `main` function to `perses_node_priority_with_dfs_delta_reduced_mutant.rs`

error[E0658]: use of unstable library feature 'fn_traits'
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:9
  |
3 |         <Self as Fn(&TestResult)>::call
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #29625 <https://github.com/rust-lang/rust/issues/29625> for more information
  = help: add `#![feature(fn_traits)]` to the crate attributes to enable

error[E0229]: associated type bindings are not allowed here
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:18
  |
3 |         <Self as Fn(&TestResult)>::call
  |                  ^^^^^^^^^^^^^^^ associated type not allowed here

thread 'rustc' panicked at 'assertion failed: !substs.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:1475:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (48691ea6e 2021-03-29) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1: 5:2>::call`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0229, E0412, E0601, E0658.
For more information about an error, try `rustc --explain E0229`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0412]: cannot find type `F` in this scope
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:6
   |
1  |   impl F {
   |        ^ help: a trait with a similar name exists: `Fn`

error[E0412]: cannot find type `TestResult` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:22
  |
3 |         <Self as Fn(&TestResult)>::call
  |                      ^^^^^^^^^^ not found in this scope

error[E0601]: `main` function not found in crate `perses_node_priority_with_dfs_delta_reduced_mutant`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | / impl F {
2 | |     fn call() {
3 | |         <Self as Fn(&TestResult)>::call
4 | |     }
5 | | }
  | |_^ consider adding a `main` function to `perses_node_priority_with_dfs_delta_reduced_mutant.rs`

error[E0658]: use of unstable library feature 'fn_traits'
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:9
  |
3 |         <Self as Fn(&TestResult)>::call
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #29625 <https://github.com/rust-lang/rust/issues/29625> for more information
  = help: add `#![feature(fn_traits)]` to the crate attributes to enable

error[E0229]: associated type bindings are not allowed here
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:18
  |
3 |         <Self as Fn(&TestResult)>::call
  |                  ^^^^^^^^^^^^^^^ associated type not allowed here

thread 'rustc' panicked at 'assertion failed: !substs.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:1475:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/48691ea6e639640f110b43e33d4aba1f07e7415c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/48691ea6e639640f110b43e33d4aba1f07e7415c/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/48691ea6e639640f110b43e33d4aba1f07e7415c/library/core/src/panicking.rs:50:5
   3: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::instantiate_value_path
   4: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
   5: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
   6: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
   7: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
   8: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
   9: rustc_typeck::check::check::check_fn
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_typeck::check::typeck
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: rustc_query_system::query::plumbing::force_query_with_job
  15: rustc_query_system::query::plumbing::get_query_impl
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  17: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  18: rustc_typeck::check::typeck_item_bodies
  19: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  20: rustc_data_structures::stack::ensure_sufficient_stack
  21: rustc_query_system::query::plumbing::force_query_with_job
  22: rustc_query_system::query::plumbing::get_query_impl
  23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  24: rustc_session::utils::<impl rustc_session::session::Session>::time
  25: rustc_typeck::check_crate
  26: rustc_interface::passes::analysis
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  28: rustc_data_structures::stack::ensure_sufficient_stack
  29: rustc_query_system::query::plumbing::force_query_with_job
  30: rustc_query_system::query::plumbing::get_query_impl
  31: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  32: rustc_interface::passes::QueryContext::enter
  33: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  34: rustc_span::with_source_map
  35: rustc_interface::interface::create_compiler_and_run
  36: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (48691ea6e 2021-03-29) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1: 5:2>::call`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0229, E0412, E0601, E0658.
For more information about an error, try `rustc --explain E0229`.
```

</p>
</details>

### LINKED ISSUE #84768: ICE: 'assertion failed: !substs.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:1477:9
```rust
#![feature(fn_traits)]

fn transform_mut<F>(f: F) where F: for<'b> FnOnce(&'b mut u8) {
    <F as FnOnce(&mut u8)>::call_once(f, 1)
}
```

([playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bbd5944104a01aaa5a6552bc9d396720))

Yes, this code is broken, but I'm surprised to get an ICE :smile: 

```
error[E0229]: associated type bindings are not allowed here
 --> src/lib.rs:4:11
  |
4 |     <F as FnOnce(&mut u8)>::call_once(f, 1)
  |           ^^^^^^^^^^^^^^^ associated type not allowed here

thread 'rustc' panicked at 'assertion failed: !substs.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:1477:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (478a07df0 2021-04-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `transform_mut`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
```

### PR DESCRIPTION
**Pull request by FabianWolff**
This pull request fixes #83693 and fixes #84768.

### CODE REVIEW

**Comment by petrochenkov** [comment]
I'm sufficiently sure that this patch treats symptoms rather than the root cause.

The minimized self-contained reproduction for this case is
```rust
#![feature(associated_type_defaults)]
#![feature(unboxed_closures)]

#[rustc_paren_sugar]
trait Tr<T> {
    type Output = u8;
    fn method() {}
}

impl<T> Tr<T> for u8 {}

fn main() {
    <u8 as Tr(&u8)>::method; // Sugared, ICE
    <u8 as Tr<(), Output = &u8>>::method; // Desugared, no ICE
}
```
What is the difference between the sugared and desugared cases?
Can we reproduce the ICE in desugared form?
Can we produce a desugaring not causing the ICE?

**Comment by FabianWolff** [comment]
> I'm sufficiently sure that this patch treats symptoms rather than the root cause.

It seems that you are right; the issue is more complex than I thought at first.

Thanks for the example that you've provided; however, I think your desugaring is wrong and should look like this:
```rust
    <u8 as Tr(&u8)>::method; // ICE
    <u8 as Tr(&u8) -> ()>::method; // equivalent, ICE
    <u8 as Tr<(&u8,), Output = ()>>::method; // desugared, no ICE
```
Neither of the following cause an ICE:
```rust
    <u8 as Tr<(), Output = &u8>>::method;
    <u8 as Tr() -> &u8>::method;
```
The ICE thus probably has to do with the special treatment of lifetime elision for parenthesized generic trait arguments:
https://github.com/rust-lang/rust/blob/9d93819fa7ae40376ac1f563a858d2ba5f3b0277/compiler/rustc_resolve/src/late/lifetimes.rs#L2411-L2417
So probably `visit_fn_like_elision()` should create a binder somewhere but doesn't. However, I know too little about this function to figure out where or how to fix this; do you happen to have an idea?

**Comment by petrochenkov** [comment]
>do you happen to have an idea?

No (perhaps @jackh726 may know something right away).
I can investigate, but I won't get to it soon, so I suggest to dig into the code yourself, there's no rocket science in those parts of the compiler.

**Comment by jackh726** [comment]
I do know, not quite off of my head. On mobile so will followup next time I get on my computer. 

If I remember correctly, visit_fn_like_elision doesn't create the binders, but instead uses the closest binders in scope.

**Comment by petrochenkov** [comment]
r? @jackh726
(I'd taken two PRs from your queue instead.)

**Comment by jackh726** [comment]
So, we probably should be bailing out of `visit_fn_like_elision` sooner, but we aren't.

https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/late/lifetimes.rs#L2686-L2707

We actually should probably be bailing on `Scope::Body` too. I'm not sure if we also need to manually set any lifetimes to `'static`. I think that should be the default. And that'll prevent an escaping bound var. (This is another place where a `ReError` would be nice)

**Comment by FabianWolff** [comment]
> We actually should probably be bailing on `Scope::Body` too.

Sorry for not getting around to implementing this sooner @jackh726. But yes, this seems to fix the problem; thanks for your help! I've also added a test case for #84768, which was caused by the same problem.

**Comment by JohnCSimon** [comment]
Ping from triage:
@FabianWolff is this ready for review? 
If so - remove the `S-waiting-on-author` label and add `S-waiting-on-review`

**Comment by FabianWolff** [comment]
> @FabianWolff is this ready for review?

Yes, it is.

@rustbot label: +S-waiting-on-review -S-waiting-on-author

**Comment by jackh726** [comment]
Sorry it's taken a bit to get back to this. 

@bors r+ rollup

**Comment by FabianWolff** [comment]
> Sorry it's taken a bit to get back to this.

No problem, thanks for the review!

**Pull request merged**
