### PR TITLE
Update Clippy

### LINKED ISSUE #60154: `rls` no longer builds after rust-lang/rust#60124
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#60124, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @petrochenkov, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @eddyb, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes fallout from https://github.com/rust-lang/rust/pull/60124.
Closes #60154.

r? @oli-obk 
cc @matthiaskrgr

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I would personally like to have https://github.com/rust-lang/rust-clippy/pull/4013 included (it's waiting for CI right now) to prevent false positives.

with that included r=me if that is possible :p

**Comment by Xanewok** [comment]
Will do, please ping me when/if that lands

**Comment by matthiaskrgr** [comment]
@Xanewok ping, https://github.com/rust-lang/rust-clippy/pull/4013 was merged.

**Comment by Xanewok** [comment]
That was fast, thanks!

@bors r=matthiaskrgr p=1

**Pull request merged**
