### PR TITLE
Rename all mentions of `nil` to `unit`

### LINKED ISSUE #53719: Rename all mentions of `nil` to `unit` or `()`
Ancient Rust used the term `nil` to describe the empty tuple. The compiler still uses this in a few places (e.g. the `mk_nil` method). All of these mentions should be changed to the current terminology or just outright `()` in comments.

### PR DESCRIPTION
**Pull request by kenta7777**
Fixes #53719. 

Renamed keywords nil to unit.

### CODE REVIEW

**Comment by kenta7777** [comment]
#53719

**Comment by scottmcm** [comment]
This seems to have a bunch of surprising submodule changes?

**Review by davidtwco — CHANGES_REQUESTED** [review]
Thanks for the PR @kenta7777!

The change from `nil` to `unit` seems fine to me (cc @nikomatsakis) but like @scottmcm said, I'm not sure why there are submodule changes? - these seem unrelated to #53719.

**Comment by kenta7777** [comment]
@davidtwco @scottmcm Thank you for your review and comment. I had changed the submodule code by mistake. I will fix and send pull request again.

**Comment by kenta7777** [comment]
I reverted my commits about changing submodule codes and committed mk_nil to mk_unit change only.

**Comment by davidtwco** [comment]
@kenta7777 This is looking really great. I've spotted a handful of other places in the compiler (such as those below) where there are still references to `nil`:

https://github.com/rust-lang/rust/blob/7f8160409f5bb4490720df21e2c4fbf1a647bae2/src/librustc/ty/sty.rs#L1461-L1466

https://github.com/rust-lang/rust/blob/7f8160409f5bb4490720df21e2c4fbf1a647bae2/src/libserialize/opaque.rs#L57-L60

If you could tackle these (and any remaining references to `nil` that I missed - perhaps run a grep) and maybe squash some of your commits down to one or two then that'd be great!

**Comment by kenta7777** [comment]
@davidtwco Thank you for your prompt response. I'll tackle with at least is_nil and emit_nil.

**Comment by nikomatsakis** [comment]
I think this seems fine — I agree that "nil" isn't really standard Rust terminology these days.

Nice job @davidtwco catching the missing cases.

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
Great work @kenta7777!

@bors r+

**Comment by davidtwco** [comment]
@kenta7777 Looks like you need to rebase this. Consider squashing to fewer commits when doing so. Once you do I'll take another look and re-approve.

**Comment by kenta7777** [comment]
@davidtwco I rebased this and resolved the merge conflicts.

**Comment by kenta7777** [comment]
Thanks!

**Pull request merged**
