### PR TITLE
rustdoc: insert newlines between attributes

### LINKED ISSUE #73205: Multiple attributes are shown on the same line in type declarations in rustdoc
When looking at rustdoc for items with multiple attributes, atributes are shown on the same line, rather than multiple. I don't have a code fragment, as I've only seen this appear in std documentation.

For example, see the MaybeUninit docs: https://doc.rust-lang.org/1.44.0/std/mem/union.MaybeUninit.html and expand the declaration.

I expected to see something like

```rust
#[lang = "maybe_uninit"]
#[repr(transparent)]
pub union MaybeUninit<T> {
    // some fields omitted
}
```

Instead, I see:

```rust
#[lang = "maybe_uninit"]#[repr(transparent)]
pub union MaybeUninit<T> {
    // some fields omitted
}
```

image

This occurs for both rust 1.44.0 and current nightly (unsure of exact nightly version, as looking at std nightly docs, not local docs).

### PR DESCRIPTION
**Pull request by euclio**
Fixes #73205.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]
Looks good to me! Once rebased, and CI passed, r=me.

**Comment by euclio** [comment]
Rebased and green.

**Pull request merged**
