### PR TITLE
HirId-ification, continued

### PR DESCRIPTION
**Pull request by zackmdavis**
Another incremental step towards the vision of #50928 (previously: #50929).

r? @michaelwoerister

### CODE REVIEW

**Comment by eddyb** [comment]
@michaelwoerister What do you mean? All I'm seeing is changes in scopes, not `DefId`s.

**Comment by michaelwoerister** [comment]
Sorry, @eddyb, yeah, might be a bug then? I didn't look too hard since I'm on parental leave `:)`

**Comment by eddyb** [comment]
Maybe one of the calls to `next_id()` in HIR lowering is now scoped differently and/or one of the variables its result is bound to shadows other variables with the same name.

**Comment by pietroalbini** [comment]
(note for future triage: the author has not so much time for rust at the moment, let's keep this open though https://github.com/rust-lang/rust/pull/51149#issuecomment-396127722)

**Comment by pietroalbini** [comment]
(note for future triage: the author has not so much time for rust at the moment, let's keep this open though https://github.com/rust-lang/rust/pull/51149#issuecomment-396127722)

**Comment by zackmdavis** [comment]
(most recent rebase just fixes conflicts, tests not expected to pass yet)

**Comment by zackmdavis** [comment]
@michaelwoerister Congratulations on the baby!!

@eddyb So, the original version of this PR (which tried to add `hir_id` fields to all remaining HIR nodes that didn't have them) was trying to do too many things at once, such that I wasn't able to debug it. (I tried redoing the lowering changes from scratch while paying attention to scoping, and I still ended up hitting a broken-MIR assertion.) But it turns out that the later part of the PR making `mem_categorization::cmt` use a HirId is independently viable, so I've rebased just that, which I think is ready for your review.

**Comment by michaelwoerister** [comment]
Thanks, @zackmdavis! I'm back from leave now.

**Pull request merged**
