### PR TITLE
What if we just add `<[MaybeUninit<T>; N]>::assume_init` directly?

### PR DESCRIPTION
**Pull request by scottmcm**
I recall (though can't find where) libs-api being unsatisfied with the `transpose` approach for this, so I figured I'd toss out this as another alternative.

Now that we don't need lang item hacks to add inherent impl blocks for built-in types, we can just add
```rust
impl<T, const N: usize> [MaybeUninit<T>; N] {
    pub const unsafe fn assume_init(self) -> [T; N];
}
```

That seems pretty reasonable -- the odds of another meaning for `assume_init` on generic overlays that might overlap feel low to me, and another *specific* meaning of it for arrays of a different type would still be possible.

If this is worth doing, I can add analogous things to `&[MaybeUninit<T>]` and `&mut [MaybeUninit<T>]` too.

cc #96097
r? @m-ou-se

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Can you post the rationale on https://github.com/rust-lang/libs-team/issues/122? The original reason for transpose was to also let you index into the array which this PR doesn't solve in the general case. I wonder if we should commit to having slice methods and offer an array to slice conversion and then let you do index operations with the slice instead of the array.

**Comment by scottmcm** [comment]
I'm hoping that we can just stabilize `inline_const` (I've [proposed it](https://github.com/rust-lang/rust/pull/104087#issuecomment-1315946122)).  At that point, `[const { MaybeUninit::uninit() }; N]` works, which makes the `MaybeUninit::uninit().transpose()` much less needed, and thus I started thinking whether we could get away without the other `transpose` either.

**Comment by anden3** [comment]
Hello @scottmcm! Just wanna let you know that this PR has a merge conflict :)

**Comment by JohnCSimon** [comment]
@scottmcm 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
