### PR TITLE
Use PackedFingerprint in DepNode to reduce memory consumption

### PR DESCRIPTION
**Pull request by tgnottingham**

### CODE REVIEW

**Comment by tgnottingham** [comment]
This is a second attempt. The first was #78516, and was abandoned due to the performance implications of using a `[u8; 16]` representation, which leads to aliasing pessimizations, at least.

This uses `#[repr(packed)]` instead, which I assumed would be fraught with UB and performance perils versus using `[u8; 16]`, but turns out to be much simpler and much more performant, based on local tests.

**Comment by jyn514** [comment]
Wow, that's a big difference! Up to 10% memory gains, almost no increased instruction count :D

**Comment by tgnottingham** [comment]
> Wow, that's a big difference! Up to 10% memory gains, almost no increased instruction count :D

Yeah! :) And I just added a relatively simple change to the dep graph code that should net a couple more percent.

**Comment by Xanewok** [comment]
> Wow, that's a big difference! Up to 10% memory gains, almost no increased instruction count :D

If I understand correctly, changing this to packed will result in "unaligned" loads (it's just a byte stream but the load is not on a word boundary aiui), which themselves won't bump the instruction count but rather incur latency penalty. If we look at cycles we can see a 1-3% regression across the board.

**Comment by jyn514** [comment]
> This new change splits up dep node data to pack it more tightly (which is made easier by the fingerprint having lower alignment,
which is why I thought the change seemed related enough to justify including in this PR). 

@bors try @rust-timer queue

**Comment by tgnottingham** [comment]
> If I understand correctly, changing this to packed will result in "unaligned" loads (it's just a byte stream but the load is not on a word boundary aiui), which themselves won't bump the instruction count but rather incur latency penalty. If we look at cycles we can see a 1-3% regression across the board.

And x86 is probably the best case scenario. Still, if we can mitigate the cycle increase, or if the pros outweigh the cons, it may be worth packing `Fingerprint`s on x86 specifically.

**Comment by tgnottingham** [comment]
The additional memory savings from the second change get lost in the variance in the benchmarks. Profiling locally verifies the modified structures to be smaller. I don't think the second change is worth the added complexity, at least while there are bigger improvements to be had elsewhere.

The max-rss measurement for keccak has very high variance in my experience, so you might take it with a grain of salt.

The cycles look a bit better, but I'm guessing that's also attributable to variance. May have gotten unlucky the first time, or lucky the second time. Nevertheless, I'll experiment with some other approaches that may perform better.

**Comment by tgnottingham** [comment]
Trying a little more targeted approach this time, using a `PackedFingerprint` type only where it has the greatest impact.

**Comment by tgnottingham** [comment]
Cycles look much better, possibly a decrease on average, while memory reduction is just as good as in the previous approach.

**Comment by nnethercote** [comment]
Sorry for the slow response, I am on leave and didn't see this until just now.

The perf results look good, but I am worried about the UB mentioned [here](https://doc.rust-lang.org/nomicon/other-reprs.html#reprpacked). Any thoughts on that?

**Comment by tgnottingham** [comment]
Yes, that warning concerned me as well. I know that the `unaligned_references` and `safe_packed_borrows` lints detect when you take references to packed fields (including inside `#[derive]'d trait implementations), and I believe that is the only UB concern. Those lints aren't firing, and they were before I made the required changes, so that's some assurance. That said, perhaps they're not complete. I'll ask around for some additional assurance.

**Comment by nnethercote** [comment]
Ok, r=me once you've finished asking around.

**Comment by tgnottingham** [comment]
I've made the `Fingerprint` field of the `PackedFingerprint` private to further assuage fears that a client could take a reference to the packed field without the lints catching it. The `PackedFingerprint` implementation itself should be safe, as care is taken to avoid taking such references, and as I understand it, the `#[derive]`'d trait implementations do the same when the type is `Copy`.

Outside of this PR, I'm working on some changes that could make this one more or less impactful, so I'll revisit whether packing continues to be worthwhile if those changes get integrated. I know packing isn't a thing to be taken lightly, but for now, it looks like a pretty clear win.

**Comment by nnethercote** [comment]
> Outside of this PR, I'm working on some changes that could make this one more or less impactful, so I'll revisit whether packing continues to be worthwhile if those changes get integrated.

Do you still want to land this now?

**Comment by tgnottingham** [comment]
Yes--it may be a while before I can finish those other changes.

@RalfJung, I know you've been involved with work and discussions around references to packed fields and UB. Do you have any concerns about landing this PR?

**Comment by RalfJung** [comment]
I recommend if you use packed fields you should set the lint added by https://github.com/rust-lang/rust/pull/72270 to `deny` in the relevant crates:
```rust
#![deny(unaligned_references)]
```

**Comment by RalfJung** [comment]
Ah, looks like you already knew that.^^ But the lint does not seem to be enabled in rustc.

To my knowledge, if the packed fields are private and the crate defining the struct has that lint enabled, that should guarantee soundness.

**Comment by tgnottingham** [comment]
Thanks! Added the `#[deny]`.

**Comment by tgnottingham** [comment]
> Outside of this PR, I'm working on some changes that could make this one more or less impactful, so I'll revisit whether packing continues to be worthwhile if those changes get integrated.

Those changes have landed in #79589 and #80957, and I've revisted the perf effect of reverting this change in #81230. I think it continues to carry it's weight.

**Pull request merged**
