### PR TITLE
move file-extension based .gitignore down to src/

### PR DESCRIPTION
**Pull request by RalfJung**
Currently, it for example ignores `*.rlib` files in the repository root -- which I think is wrong; I sometimes get these files when I call rustc directly and I do want them cleaned up, not ignored. No such files are created during the normal build process.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors r+ rollup

no strong opinion here

**Comment by nikomatsakis** [comment]
> I find this confusing -- doesn't it effectively say that you want git to track changes in the repo root for files with these extensions? Meaning, with this change running git add -A would (incorrectly) stage .rlib files in the repo root into the git index.

That is correct; on the other hand, `git clean` will delete those files. 

Maybe I was hasty in r+'ing, though, and should have done a broader survey. My bad.

cc @rust-lang/compiler @rust-lang/libs and other people who hack on this repo. Do you have opinions? :)

**Comment by nagisa** [comment]
I don’t mind this change. I doubt people with a habit of littering around their repository will be using `git add -A` anyway and having `git clean` work for people who do have random files lying around in repository root is a huge boon.

**Comment by RalfJung** [comment]
The way I use git (and, from my experience, the way it is frequently used), `.gitignore` is for files that are *expected* to be there but should not be committed -- generally, files created by compilation.  This is so that if there is any *unexpected* data in the repository, git will be able to know and tell me, and `git clean` will be able to clean it up.  I noticed that git failed to inform me about some unexpected files in the repository root, hence this PR.

I wasn't aware people would do `git add -A` without even checking `git status` what it is they are adding; that must be a workflow rather different from mine. If that's common enough I suppose we should do this change. Notice, however, that it is easy for such people to locally *extend* the files ignored by git by editing `.git/info/exclude`. I know of no way to locally "unignore" a file.

**Comment by nikomatsakis** [comment]
I tend to agree with @nagisa and @RalfJung — knowing which "stray files" are hanging around is fairly useful for me so I can keep my directories tidy. (And, as @RalfJung pointed out, one can locally extend the set of files to ignore with relative ease (which I also do))

**Comment by uberjay** [comment]
Yeah, I actually would be pretty surprised if anyone used `git add -A`, too, I was using it a a shorthand for "files I wouldn't want to add should be ignored". However, after reading your explanation, I get it!

It makes sense to only ignore files which are *expected* to be created! Thanks for humoring me.

**Comment by petrochenkov** [comment]
Oh no.

> I sometimes get these files when I call rustc directly and I do want them cleaned up

I often call rustc directly too, like this or similar
```
build/x86_64-pc-windows-gnu/stage1/bin/rustc ../mytest.rs
```
and I want the produced files to be ignored, so they do not litter git-gui or git status.

>This is so that if there is any unexpected data in the repository, git will be able to know and tell me

In my case this *is* expected temporary data in the repository, exactly something that needs to be ignored.
So, this [breaks my workflow](https://xkcd.com/1172/).

**Comment by crlf0710** [comment]
@petrochenkov maybe you can edit your `.git/info/exclude` and add them back... which only affects your local copy. It's not a big deal.

**Pull request merged**
