### PR TITLE
gcc: build with --disable-multilib, as it used only to bootstrap llvm

### PR DESCRIPTION
**Pull request by klensy**
Should probably reduce CI time a little

### CODE REVIEW

**Comment by Kobzol** [comment]
Note that the GCC build is pretty much perfectly cached in Docker and almost never rebuilt. Therefore speeding up the GCC build won't actually reduce CI time.

**Comment by klensy** [comment]
Please kick a try build, thanks.

**Comment by klensy** [comment]
> Note that the GCC build is pretty much perfectly cached in Docker and almost never rebuilt. Therefore speeding up the GCC build won't actually reduce CI time.

Oh, maybe.

**Comment by Kobzol** [comment]
To provide a little more context: anything that is built inside the Dockerfile is cached via an external Docker image cache. The Docker cache sometimes gets busted, but for 99% runs it works. So there't not much point in optimizing the duration of building stuff inside the Docker. The important stuff to optimize is in the opt-dist tool, or in bootstrap itself.

**Comment by klensy** [comment]
Smaller size?

Kindly ask for retry, wrongly mixed comments and code in previous attempt.

**Comment by Kobzol** [comment]
@bors try

Smaller size of the Docker image? Possibly, but that hasn't been a bottleneck in any sort of way so far, I don't think that we need to care about that much.

**Comment by klensy** [comment]
Predicting fail here https://github.com/rust-lang/rust/blob/e59540968e0c6fc3c37d92a639b83fc8fcee5e81/src/ci/docker/host-x86_64/dist-x86_64-linux/build-gcc.sh#L45

**Comment by klensy** [comment]
Maybe move copy of build-gcc.sh for i686 into it's own folder, so
https://github.com/rust-lang/rust/blob/475be26d99b8e3898c482e0ac42ab7bce3d511bf/src/ci/docker/host-x86_64/dist-x86_64-linux/build-gcc.sh#L42-L45
can be removed?

**Comment by cuviper** [comment]
If we split them, I think we could skip the gcc build entirely on `dist-x86_64-linux` and use `devtoolset-11-gcc-c++`, after installing `centos-release-scl` for the extra yum repos. IIRC, the only reason I didn't use that before, when updating to `centos:7`, was because it lacked 32-bit libraries.

**Comment by Dylan-DPC** [comment]
@klensy any updates on this? thanks

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
