### PR TITLE
Stabilize `is_symlink()` for `Metadata` and `Path`

### PR DESCRIPTION
**Pull request by maxwase**
I'm not fully sure about `since` version, correct me if I'm wrong 

Needs update after stabilization: [cargo-test-support](https://github.com/rust-lang/cargo/blob/8063672238a5b6c3a901c0fc17f3164692d0be85/crates/cargo-test-support/src/paths.rs#L202)

Linked issue: #85748

### CODE REVIEW

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by Kixunil** [comment]
Shouldn't this return `Result` in the spirit of `try_exists`? Or is it considered too inconsistent given existing methods return `bool`?

**Comment by joshtriplett** [comment]
@Kixunil Good catch!

@rfcbot concern should-return-result

**Comment by maxwase** [comment]
> Shouldn't this return `Result` in the spirit of `try_exists`? Or is it considered too inconsistent given existing methods return `bool`?

I don't think it should. There are `is_dir` and `if_file` methods with this signature (stable since 1.5.0). This question is also discussed in #76487 and #83186.

Personally, I think it would be inconvenient to return `Result` in this method, but it might be useful to have `try_exists_symlink` to some extend, but to what extent?

For now it is working well [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e4de590d40de85b5c1ee608a4d92d855) 

@Kixunil @joshtriplett

**Comment by joshtriplett** [comment]
I agree that on Metadata we can just return bool. On Path, I think we should return a result.

**Comment by maxwase** [comment]
@joshtriplett, Wouldn't that be illogical to have `is_dir() -> bool` and `is_file() -> bool`, but `is_symlink() -> Result<bool, Error>`?

I see 3 ways to solve this:
1. Deprecate `is_dir` and `is_file` -> bool signatures and replace these with `try_is_...`. This will brake A LOT of code and make these methods so inconviniet to use due to error handling. These methods alwo used in functions that retuns a lot of types of errors, so you can't just use `?`, also you can't use `.unwrap()` because it will be strange to see in production code, so you will use  `.unwrap_or(false)`, as currently implemented. A programmer who wants to handle methadata error can do it by himself.
2. Accept this PR to comlete method hole and continue thinking about it.
3. Accept this PR and open new, not deprecating old methods. New PR will add `try_is...`, so it will be convinient to use foe everyone.

**Review by yaahc — CHANGES_REQUESTED** [review]

**Review by yaahc — APPROVED** [review]

**Comment by WhyNotHugo** [comment]
I don't fully grasp the state of this feature; isn't it available as of 1.57?

I'm getting an error indicating that it's unstable:

```
error[E0658]: use of unstable library feature 'is_symlink'
  --> src/main.rs:82:22
   |
82 |         if home_path.is_symlink() {
   |                      ^^^^^^^^^^
   |
   = note: see issue #85748 <https://github.com/rust-lang/rust/issues/85748> for more information

error[E0658]: use of unstable library feature 'is_symlink'
  --> src/main.rs:87:26
   |
87 |     } else if !home_path.is_symlink() {
   |                          ^^^^^^^^^^
   |
   = note: see issue #85748 <https://github.com/rust-lang/rust/issues/85748> for more information
```

**Comment by ChrisDenton** [comment]
If you look at the sidebar you should see a "milestone" tag. This says it'll be stable in 1.58.

**Comment by WhyNotHugo** [comment]
Ah, that completely slipped past me, thanks!

**Comment by ChrisDenton** [comment]
No worries. It's easy to miss if you don't know to look for it.

**Comment by maxwase** [comment]
> I don't fully grasp the state of this feature; isn't it available as of 1.57?
> 
> I'm getting an error indicating that it's unstable:
> 
> ```
> error[E0658]: use of unstable library feature 'is_symlink'
>   --> src/main.rs:82:22
>    |
> 82 |         if home_path.is_symlink() {
>    |                      ^^^^^^^^^^
>    |
>    = note: see issue #85748 <https://github.com/rust-lang/rust/issues/85748> for more information
> 
> error[E0658]: use of unstable library feature 'is_symlink'
>   --> src/main.rs:87:26
>    |
> 87 |     } else if !home_path.is_symlink() {
>    |                          ^^^^^^^^^^
>    |
>    = note: see issue #85748 <https://github.com/rust-lang/rust/issues/85748> for more information
> ```

I don't understand this too. Stable attribute is 1.57 in master, but milestone is 1.58 here. Also this PR was not mentioned in release list
@joshtriplett, can you please explain?

**Comment by kennytm** [comment]
it means the `#[stable]` version property is wrongly tagged 🤷

**Comment by maxwase** [comment]
> it means the `#[stable]` version property is wrongly tagged 🤷 

Should I replace it in new PR?

**Comment by kennytm** [comment]
yes

**Pull request merged**
