### PR TITLE
std: Add debugging for a failing test on appveyor

### PR DESCRIPTION
**Pull request by alexcrichton**
I'm not sure why this is failing, so let's hopefully get some more
information to help investigation!

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @kennytm

**Comment by RalfJung** [comment]
My theory is that the test runner is so slow that it just takes more than 100 [whatever the unit] between the two measurements of the current system time.

**Comment by alexcrichton** [comment]
@bors: r+

@RalfJung that doesn't match up with the test, which doesn't rely on how long it takes between measurements. It calculates the difference between two measurements and ensure that the difference can be added/subtracted to the measurement to get the other.

**Comment by RalfJung** [comment]
@alexcrichton Ah, I misread the code.

**Comment by alexcrichton** [comment]
@bors: retry

* #56040

**Pull request merged**
