### PR TITLE
Add unstable copy_from_slice

### PR DESCRIPTION
**Pull request by strega-nil**
implements rust-lang/rfcs#1419

r? alexcrichton

### CODE REVIEW

**Comment by ubsan** [comment]
I wrote that comment wrong :P 

Hi @aturon :)

**Comment by bluss** [comment]
This method should be available in libcore too right, so needs to be added to SliceExt too?

**Comment by bluss** [comment]
Note, this does not fix the tracking issue -- the issue is open until the feature is stable.

**Comment by ubsan** [comment]
@bluss alright, I'll take out that thing about "fixes".

Also, yes I do think it should go in SliceExt. I'll implement that tonight.

**Comment by alexcrichton** [comment]
Thanks @ubsan! In addition to what @bluss mentioned, could you also add a positive test which asserts that the behavior is as expected?

**Comment by ubsan** [comment]
@alexcrichton will do :)

**Comment by bluss** [comment]
Great! Let's go..

@bors r+ 849c4ce

**Comment by bluss** [comment]
@bors r-

travis found this one

```
src/libcollections/lib.rs:35:12: 35:27 error: unused or unknown feature, #[deny(unused_features)] on by default

src/libcollections/lib.rs:35 #![feature(copy_from_slice)]
```

**Comment by bluss** [comment]
Ok that's really weird, probably bug #30209

**Comment by ubsan** [comment]
@bluss that's weird, it worked on my end... I specifically added an unstable attribute, and then added a feature, and compiled and it worked.

**Comment by bluss** [comment]
But then the libcollections code changed to just and UFCS trait method call, which is what the bug indicates

**Comment by bluss** [comment]
stage1 seems to have no such unused feature warning, but stage2 does when compiling libcollections.

**Comment by bluss** [comment]
When compiling libcollectionstest actually.

**Comment by alexcrichton** [comment]
I think you'll just need to add this to the top of libcollections:

```
#![cfg_attr(not(test), feature(...))]`
```

**Comment by bluss** [comment]
Yeah that seems to be right. That was a bit confusing.

**Comment by bluss** [comment]
Did you mean to have the libcollectionstest tests replace the run-pass/run-fail tests? I.e. remove the other ones?

**Comment by ubsan** [comment]
@bluss yes. Is that not what our tests should be? I am super confused about our tests :P

**Comment by bluss** [comment]
having them in just libcollectionstests seems good.

**Comment by ubsan** [comment]
cool :)

**Comment by bluss** [comment]
Feel free to squash the commits together if you want (to create a cleaner history).

**Comment by ubsan** [comment]
@bluss will do

**Comment by bluss** [comment]
Can we delete the two files in src/tests/ ? They are redundant now.

**Comment by bluss** [comment]
r=me without the redundant tests. I'm happy this is finally landing!

**Comment by ubsan** [comment]
@bluss I thought I had deleted those :/

**Comment by ubsan** [comment]
@bluss I feel like kind of a dumb right now :P

**Comment by alexcrichton** [comment]
@bors: r+ e12b1f9424512e39c3d64f955a3bb913707b41d8

Thanks @ubsan!

**Pull request merged**
