### PR TITLE
Optimise Chars::last()

### PR DESCRIPTION
**Pull request by ollie27**
The default implementation of last() goes through the entire iterator
but that's not needed here.

### CODE REVIEW

**Comment by bluss** [comment]
@bors r+ rollup

Thank you!

**Comment by bluss** [comment]
By the way, this applies to char_indices as well. Another commit or another PR is welcome.

**Comment by ollie27** [comment]
Good point. I've applied the same to `CharIndices`.

**Comment by durka** [comment]
Shouldn't this apply to any `DoubleEndedIterator`?

**Comment by ollie27** [comment]
Yeah, but I think it might be breaking change to do this for iterators that might have side effects.

**Comment by bluss** [comment]
Yes. Iterator::last's doc is specific about how it goes about finding the last value (traversing it all).

**Pull request merged**
