### PR TITLE
Typo fix in Unstable book: `cargo cov` -> `cargo profdata`

### PR DESCRIPTION
**Pull request by amaurremi**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Isn't [cargo cov](https://crates.io/crates/cargo-cov) working too?

**Comment by amaurremi** [comment]
If I run `cargo cov -- merge ...` results in the error
```
Unrecognized command: merge.
```
And it works with `cargo profdata -- merge ...`.

**Comment by GuillaumeGomez** [comment]
Weird... Well, I'll let someone else with more knowledge about this review it.

r? @ehuss

**Comment by ehuss** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
