### PR TITLE
Move `SharedContext` to `context.rs`

### PR DESCRIPTION
**Pull request by camelid**
It is tightly connected to `Context` and is primarily used as a field in
`Context`. Thus, it should be next to `Context`.

### CODE REVIEW

**Comment by camelid** [comment]
Probably worth using `git diff --color-moved=dimmed-zebra` to review.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors; r+ rollup

**Comment by GuillaumeGomez** [comment]
Oh so ";" is stopping bors from doing anything. Interesting.

@bors; r+ rollup

**Comment by GuillaumeGomez** [comment]
Oh come on...

@bors: r+ rollup

**Comment by JohnTitor** [comment]
@bors r-
This needs a rebase to fix some compile errors: https://github.com/rust-lang/rust/pull/83777#issuecomment-812435587

**Comment by camelid** [comment]
> Oh so ";" is stopping bors from doing anything. Interesting.

You can also leave off the `:`, so `bors r+ rollup` (with an `@` in front, but I left it off because bors does not ignore commands in inline code) will work.

**Comment by GuillaumeGomez** [comment]
I know, but I like the ":". :)

**Comment by GuillaumeGomez** [comment]
Let's start again then!

@bors: r+ rollup

**Pull request merged**
