### PR TITLE
Compress `Liveness` data some more.

### PR DESCRIPTION
**Pull request by nnethercote**
Profiling shows that the `(reader, writer, used)` triples used by
liveness analysis almost always have invalid `reader` and `writer`
fields. We can take advantage of this knowledge to use a compressed
representation for them, falling back to a secondary table for the
uncommon cases.

This change reduces instruction counts on numerous benchmarks, the best
by 16%. It also reduces max-rss on numerous benchmarks, the best by 38%.

The patch also renames these triples from `Users` to `RWU`, because it's
confusing having a type whose name is plural and then used within
vectors whose names are also plural.

r? @nikomatsakis

### CODE REVIEW

**Comment by nnethercote** [comment]
I know I just changed this code in #54211, but I came up with this better way of handling things and couldn't resist trying. It worked better than I expected. Instruction counts:
```
keccak-check
        avg: -5.0%      min: -16.2%     max: -1.2%
keccak-debug
        avg: -6.1%      min: -14.0%     max: -1.5%
keccak-opt
        avg: -5.5%      min: -14.0%     max: -1.2%
inflate-check
        avg: -2.4%      min: -8.3%      max: -0.9%
inflate-opt
        avg: -2.0%?     min: -6.8%?     max: -0.3%?
inflate-debug
        avg: -2.6%      min: -6.4%      max: -1.3%
clap-rs-check
        avg: -2.4%      min: -4.7%      max: -0.8%
clap-rs-debug
        avg: -2.6%      min: -3.7%      max: -2.0%
clap-rs-opt
        avg: -1.5%      min: -2.5%      max: -1.0%
```
max-rss:
```
keccak-check
        avg: -27.4%     min: -38.7%     max: -0.1%
keccak-debug
        avg: -12.7%     min: -38.0%     max: 0.0%
keccak-opt
        avg: -12.7%     min: -38.0%     max: 0.0%
inflate-check
        avg: -6.2%      min: -18.4%     max: 0.2%
inflate-opt
        avg: -2.1%?     min: -9.3%?     max: 0.6%?
inflate-debug
        avg: -1.6%      min: -8.8%      max: 1.6%
clap-rs-debug
        avg: 1.6%       min: -0.6%      max: 7.2%
clap-rs-opt
        avg: -1.4%      min: -6.6%      max: 0.8%
clap-rs-check
        avg: -0.6%      min: -0.9%      max: -0.1%
```
I also tried a different representation, where each packed RWU was a single byte and the secondary table was an `FxHashMap`. It saved some more memory, but the instruction counts and wall-times were a bit higher, so I finalized on this vector approach.

**Comment by nnethercote** [comment]
BTW, although the benefits (esp. max-rss) mostly accrue to non-NLL builds, the NLL builds do get some improvement.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

@nnethercote what do you think about trying to rewrite this pass altogether to operate on MIR? By this point you've about rewritten it already a few times. =)

**Comment by wesleywiser** [comment]
@nnethercote Please, feel free to take that :) I've got a couple other things on my plate at the moment

**Comment by nnethercote** [comment]
[Perf results](https://perf.rust-lang.org/compare.html?start=e7b5ba8661aa844a06c37f22d7af0afb1807d347&end=af50e3822c4ceda60445c4a2adbb3bfa480ebd39&stat=instructions:u) look good, as expected.

**Pull request merged**
