### PR TITLE
ci: Add Dockerfile for dist-sparc64-linux

### PR DESCRIPTION
**Pull request by glaubitz**
This addresses https://github.com/rust-lang/rust/issues/47903.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @rust-lang/infra -- I don't know anything about docker =) somebody care to review?

**Comment by alexcrichton** [comment]
Thanks @glaubitz! Since this isn't enabled for now, mind moving it to the `disabled` folder?

**Comment by glaubitz** [comment]
Isn’t it possible to enable it? I would like to have upstream builds for sparc64-linux to simplify building Rust on this target, avoiding the need for cross-compile.

The sparc64 toolchain is available on Ubuntu, so cross-building Rust there should just work.

Is there anything else I forgot to add?

**Comment by alexcrichton** [comment]
Ah sorry unfortunately we don't have enough capacity right now for a new builder, so a new host toolchain can't be built by us just yet

**Comment by glaubitz** [comment]
Ok, then feel free to move it to the disabled section for the time being.

**Comment by glaubitz** [comment]
I was wondering, has the build capacity increased in the mean time such that we could enable builds for sparc64-unknown-linux-gnu these days? After fixing all the latest bugs, Rust is pretty stable on this target nowadays so it would be cool if it was possible to build and install Rust on sparc64-unknown-linux-gnu directly from upstream.

**Comment by alexcrichton** [comment]
Unfortunately no extra capacity yet :(

**Comment by glaubitz** [comment]
I recently read that AWS is now providing extra instances for the Rust project (https://aws.amazon.com/blogs/opensource/aws-sponsorship-of-the-rust-project/), so I was wondering whether the conditions regarding additional capacity have changed in the meantime so that sparc64-unknown-linux-gnu could be enabled?

**Pull request merged**
