### PR TITLE
Revert "Work around invalid DWARF bugs for fat LTO"

### LINKED ISSUE #90357: DWARF info for `static` vars in lib crates has stopped being produced reliably in LTO builds
As of the 2021-09-23 nightly, rustc has stopped producing debug output for variables in a specific combination of circumstances:

- The variable is `static`
- It is defined in a lib crate.
- The lib crate is included in a bin crate.
- The bin crate is built with `lto = true`.

We noticed this after bumping past 09-23 to the 2021-10-27 nightly, when our debugger broke. The static is still being included in the ELF output (both allocated space, and represented correctly in the symtab), but is missing from DWARF. Bisecting indicates 2021-09-23 as the culprit (09-22 works).

Here is a repro case that I've reduced that works on linux x86-64, at least, and probably other DWARF platforms.

https://github.com/cbiffle/rustc-dwarf-regression-repro

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by cbiffle**
Since September, the toolchain has not been generating reliable DWARF
information for static variables when LTO is on. This has affected
projects in the embedded space where the use of LTO is typical. In our
case, it has kept us from bumping past the 2021-09-22 nightly toolchain
lest our debugger break. This has been a pretty dramatic regression for
people using debuggers and static variables. See #90357 for more info
and a repro case.

This commit is a mechanical revert of
d5de680e20def848751cb3c11e1182408112b1d3 from PR #89041, which caused
the issue. (Note on that PR that the commit's author has requested it be
reverted.)

I have locally verified that this fixes #90357 by restoring the
functionality of both the repro case I posted on that bug, and debugger
behavior on real programs. There do not appear to be test cases for this
in the toolchain; if I've missed them, point me at 'em and I'll update
them.

### CODE REVIEW

**Comment by jyn514** [comment]
@cbiffle do you think you could add tests for this in src/test/debuginfo so it doesn't regress again?

**Comment by cbiffle** [comment]
So, there were some tests that would have caught this, except that (1) they were "temporarily" disabled in 2018 and (2) they were using the wrong build configuration. Altering `basic-types-globals.rs` by turning it back on and enabling LTO produces a test that fails on current master, for two reasons:

- Because its assertions about GDB's output appear to have rotted in the four years it's been disabled, and
- Because of the bug described in #90357

I've added a commit to this PR that re-enables the test and adds a duplicate of it using LTO. Both tests pass with this PR.
I admit I don't understand the circumstances that led to these tests being disabled in #47155, so I don't know for sure that simply turning them back on and fixing the decay is the right answer.

Also, if there is a way to matrix a single test case in multiple build configurations rather than copy-pasta, please let me know.

**Comment by jyn514** [comment]
> If there's interest in this change I can create a followup PR.

That sounds amazing!

**Comment by compiler-errors** [comment]
> Also, if there is a way to matrix a single test case in multiple build configurations rather than copy-pasta, please let me know.

@cbiffle: Look at [revisions](https://rustc-dev-guide.rust-lang.org/tests/compiletest.html#revisions), though you might need to check out other tests for best examples for how to use it.

**Comment by cbiffle** [comment]
> @cbiffle: Look at [revisions](https://rustc-dev-guide.rust-lang.org/tests/compiletest.html#revisions), though you might need to check out other tests for best examples for how to use it.

Slick. That's almost exactly what I wanted. Unfortunately, any attempt to use `revisions` in a gdbtest hits a panic: https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/runtest.rs#L758

**Comment by cbiffle** [comment]
> > If there's interest in this change I can create a followup PR.
> 
> That sounds amazing!

Posted as a draft in https://github.com/rust-lang/rust/pull/95696 . It's based on top of this PR for my convenience. If it seems like this PR is going to be controversial I can rebase and separate them.

**Comment by cbiffle** [comment]
Hi! Is anybody looking at this? Can I do anything to facilitate? Thanks!

**Comment by pnkfelix** [comment]
> This commit is a mechanical revert ofhttps://github.com/rust-lang/rust/commit/d5de680e20def848751cb3c11e1182408112b1d3 from PR https://github.com/rust-lang/rust/pull/89041, which caused
the issue. (Note on that PR that the commit's author has requested it be
reverted.)

This is pretty easy justification for a revert here. :)

Thanks @cbiffle !

@bors r+ rollup

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/96096#issuecomment-1100505108) 

@bors r- 
@bors rollup=never

**Comment by GrantM11235** [comment]
What is the status of this PR? Does bors need to try again?

**Comment by jyn514** [comment]
@GrantM11235 it failed the multiplatform tests - someone (presumably @cbiffle, although other people can take it over if they don't have time) needs to figure out why and fix the tests.

**Comment by cbiffle** [comment]
@jyn514 I'd like to help however I can, but I don't understand the failure these hit.

**Comment by cbiffle** [comment]
@pnkfelix or anyone else, do you understand the build failure here? We're getting increasingly far behind the rust-embedded ecosystem because they're using features that became available after DWARF generation broke, whereas we require DWARF generation. I'd like to do what I can to move this along but my fix works on the platforms I have access to.

**Comment by nikic** [comment]
The build failure is because the newly reenabled tests fail. It looks like https://github.com/rust-lang/rust/pull/95138 also tried to reenable gdb tests, but also ran into failures. Most likely, these don't work under gdb 7, but work under some newer version. You could try adding a min-gdb-version annotation.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@cbiffle - can you post your status on this PR?

**Comment by jyn514** [comment]
@bors r=pnkfelix rollup=never

Thanks!

**Pull request merged**
