### PR TITLE
Show the sign for signed ops on `exact_div`

### PR DESCRIPTION
**Pull request by oli-obk**
r? @RalfJung Cc https://github.com/rust-lang/miri/pull/961/files#r341842128

I'm fairly unhappy with the duplication and the general effort required for this.

Maybe it would be better to add a `display` impl for `ImmTy`?

### CODE REVIEW

**Comment by Centril** [comment]
> Maybe it would be better to add a `display` impl for `ImmTy`?

No please. :) I think `Display` impls in the compiler contribute towards implicit dependencies and are harmful wrt. https://github.com/rust-lang/rust/issues/65031#issue-501780794 due to the orphan rules.

Surely we can de-dup some other way without adding those impls... ^^

**Comment by RalfJung** [comment]
> I think Display impls in the compiler contribute towards implicit dependencies and are harmful wrt. #65031 (comment) due to the orphan rules

I have no idea what this means... `Display` is defined in libstd so it's a different crate anyway. Also `Immediate` is not in librustc so it should have a hard time contributing to its compile times.

**Comment by Centril** [comment]
> I have no idea what this means... `Display` is defined in libstd so it's a different crate anyway.

When I was refactoring libsyntax, there were a bunch of implicit dependencies on e.g. `impl Display for syntax::ast::Path` which in turn used `syntax::print::pprust`. The problems is if you move pprust out of libsyntax.

> Also `Immediate` is not in librustc so it should have a hard time contributing to its compile times.

Ah OK, great.

**Comment by RalfJung** [comment]
@oli-obk `Scalar` has both a `Display` and a `Debug` impl already. I think the `Display` impl is used when printing the invalid value that we encountered during validity checking; the `Debug` impl is extremely helpful when debugging CTFE stuff as it makes the Miri trace just so much more readable.^^

For `Debug` I chose to display hex to work around the sign issue, and anyway we don't have enough type information to determine if we should print this as signed or unsigned. So likely the `Scalar::Display` impl is just a bad idea and should be removed, and indeed I think having a `Display` impl for `ImmTy` instead and using that both in `exact_div` and for validity would be a good idea. Or, if it has to be, a `to_string` method returning `String`; I don't think we mind some extra allocations when generating the error message (but it seem silly to me to kill not use omnipresent abstractions like `Display`).

Also see https://github.com/rust-lang/rust/pull/65859, that code *also* pretty-prints MIR values, so probably all of these cases should share code.

**Comment by JohnCSimon** [comment]
Ping from triage - this PR has sat idle for a while and is now unmergable.  
@oli-obk @Centril @RalfJung

**Review by RalfJung — APPROVED** [review]
LGTM! r=me, but it'd be even better if you could add a test (at least for the sign part) in-tree.

**Comment by oli-obk** [comment]
Oh... XD I was working locally on deduplicating the rendering logic from this with the one from constants. I'll open a separate PR and that will also have tests for rustc then

**Pull request merged**
