### PR TITLE
Do not emit "class method" debuginfo for types that are not DICompositeType.

### LINKED ISSUE #35991: LLVM assertion failure when compiling winapi with the latest nightly
When compiling a project that depends on `winapi` on the latest nightly, the compilation halts due to an llvm assertion failure while `winapi` is being built.

Error message:
```
Assertion failed: !isa<DIType>(Scope) && "shouldn't make a namespace scope for a type", file C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\llvm\lib\CodeGen\AsmPrinter\CodeViewDebug.cpp, line 202
```

Toolchain/platform info
```
rustc --version
rustc 1.13.0-nightly (e9bc1bac8 2016-08-24)

toolchain: nightly-x86_64-pc-windows-msvc

winapi version: v0.2.8
winapi-build version: v0.1.1
```

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #35991 by restricting the "class method" debuginfo sugar from #33358 to structs and enums only.

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc @tromey: It seems like LLVM doesn't allow us to put methods on non-class types. Does the current version GDB rely on that in any way yet?

**Comment by michaelwoerister** [comment]
@bors r+

Since LLVM does not allow this anymore, there's little we can do in the short term. In the long term, we'll need a different strategy for associating methods with their self types anyway, since this one doesn't scale to trait methods.

**Comment by alexcrichton** [comment]
@bors: p=10

(fixing nightlies)

**Comment by tromey** [comment]
> It seems like LLVM doesn't allow us to put methods on non-class types. Does the current version GDB rely on that in any way yet?

No.  IIRC this was just in our draft proposal for how interface impls ought to be represented, not anything that was actually implemented (or even actually proposed)?

**Comment by michaelwoerister** [comment]
@tromey Good, so this doesn't make things worse at least.

**Pull request merged**
