### PR TITLE
Make create_dll_import_lib easier to implement

### PR DESCRIPTION
**Pull request by bjorn3**
This will make it easier to implement raw-dylib support in cg_clif and cg_gcc. This PR doesn't yet include an create_dll_import_lib implementation for cg_clif as I need to correctly implement dllimport in cg_clif first before raw-dylib can work at all with cg_clif.

Required for https://github.com/rust-lang/rustc_codegen_cranelift/issues/1345

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? compiler

**Review by jieyouxu — APPROVED** [review]
Thanks for the cleanup, the changes look reasonable to me.

**Comment by tgross35** [comment]
Seems like the `ar_archive_writer` bump caused problems on ppc https://github.com/rust-lang/rust/pull/128773#issuecomment-2273095604

@bors r-

**Comment by bjorn3** [comment]
Building on big-endian got broken. Fixed in https://github.com/rust-lang/ar_archive_writer/pull/18 and added a CI check for big-endian systems. I've released it as v0.3.3 and updated this PR to make use of it.

**Comment by jieyouxu** [comment]
Thanks, r=me after PR CI is green

**Pull request merged**
