### PR TITLE
Streamline MIR dataflow cursors

### PR DESCRIPTION
**Pull request by nnethercote**
`rustc_mir_dataflow` has two kinds of results (`Results` and `ResultsCloned`) and three kinds of results cursor (`ResultsCursor`, `ResultsClonedCursor`, `ResultsRefCursor`). I found this quite confusing.

This PR removes `ResultsCloned`, `ResultsClonedCursor`, and `ResultsRefCursor`, leaving just `Results` and `ResultsCursor`. This makes the relevant code shorter and easier to read, and there is no performance penalty.

r? @cjgillot

### CODE REVIEW

**Comment by nnethercote** [comment]
No change on perf, as expected. That's good news, it means the very small increase in cloning has no meaningful perf effect.

**Comment by nnethercote** [comment]
cc @Jarcho

**Comment by Jarcho** [comment]
Looked back at what this was before I changed last touched it. The current mess of different cursor types was just a way to avoid cloning in all the cases it did before.

It might be possible to simplify things by only borrowing the entry sets and cloning only the analysis.

**Comment by nnethercote** [comment]
> It might be possible to simplify things by only borrowing the entry sets and cloning the analysis.

That's exactly what `ResultsClonedCursor` did, which required the assistance of `CloneAnalysis` and `AnalysisResults`. But the cost of cloning the entry sets is negligible, so it's not worth all the extra complexity to avoid cloning.

**Comment by nnethercote** [comment]
> `CloneAnalysis` could just be `Clone`. There would have been (very small) perf hits on some of the stuff I was working on at time, but it's really not needed. If I were to do things now I wouldn't have added it at all.

The PR removes `CloneAnalysis`, exactly by just using `Clone` in a very small number of places.
 
> `AnalysisResults` wouldn't be needed if the entry sets and analysis were stored directly as separate fields. I think that caused some other problems somewhere else, but I don't remember everything I tried at the time.

The PR removes `AnalysisResults` as well.

**Comment by cjgillot** [comment]
LGTM. Why is this still marked as draft?

**Comment by nnethercote** [comment]
Sorry, I forgot to remove the draft marker :)

**Comment by nnethercote** [comment]
@cjgillot: is your "LGTM" equivalent to an r+ ?

**Pull request merged**
