### PR TITLE
Short circuit Send and Sync impls for TokenTree

### PR DESCRIPTION
**Pull request by Zoxc**
Workaround to make the parallel compiler build after https://github.com/rust-lang/rust/pull/60444.

r? @nikomatsakis

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Do we know the actual cause of the problem? Is the compiler running into some kind of livelock?

**Comment by michaelwoerister** [comment]
This is what `perf` tells me after running `./x.py build` for an hour or so:
```
Samples: 22M of event 'cycles:uppp', Event count (approx.): 22349476896140
Overhead  Command          Shared Object                                 Symbol
  21.14%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::evaluate_stack
   6.54%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
   4.53%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::evaluate_predicate_recursively
   3.03%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::ty::context::TyCtxt::_intern_substs
   2.51%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::infer::InferCtxt::start_snapshot
   2.48%  rustc            libc-2.28.so                                  [.] __memmove_avx_unaligned_erms
   2.31%  rustc            libc-2.28.so                                  [.] _int_malloc
   1.63%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::evaluate_predicates_recursively
   1.59%  rustc            libc-2.28.so                                  [.] _int_free
   1.34%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::infer::InferCtxt::in_snapshot
   1.25%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
   1.22%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::confirm_candidate
   1.10%  rustc            libc-2.28.so                                  [.] malloc
   1.00%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
   0.97%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::infer::InferCtxt::commit_from
   0.92%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::candidate_from_obligation
   0.88%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   0.86%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::ty::context::CtxtInterners::intern_ty
   0.82%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   0.81%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
   0.70%  rustc            libc-2.28.so                                  [.] realloc
   0.67%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::ty::fold::<impl rustc::ty::context::TyCtxt>::replace_bound_vars
   0.65%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::project::normalize_with_depth
   0.62%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
   0.62%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <rustc::traits::ObligationCause as core::clone::Clone>::clone
   0.60%  rustc            libLLVM-8-rust-1.35.0-beta.so                 [.] llvm::GlobalsAAResult::DeletionCallbackHandle::deleted
   0.58%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <T as rustc::ty::context::InternIteratorElement<T,R>>::intern_with
   0.58%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::infer::InferCtxt::probe
   0.57%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::impl_or_trait_obligations
   0.49%  rustc            rustc                                         [.] free
   0.48%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::infer::InferCtxt::in_snapshot
   0.45%  rustc            librustc-e9b5ca1e357beddc.so                  [.] rustc::traits::select::SelectionContext::collect_predicates_for_types
   0.45%  rustc            librustc-e9b5ca1e357beddc.so                  [.] <rustc::traits::ObligationCause as core::clone::Clone>::clone
   0.40%  rustc            libLLVM-8-rust-1.35.0-beta.so                 [.] combineInstructionsOverFunction
   0.38%  rustc            libLLVM-8-rust-1.35.0-beta.so                 [.] llvm::ValueHandleBase::AddToUseList
   0.37%  rustc            rustc                                         [.] malloc
```

**Comment by pietroalbini** [comment]
Beta nominating this. It's blocking the bootstrap update and the version number bump for nightly 1.37.0.

**Comment by Zoxc** [comment]
We just need this on master to bump the bootstrap compiler.

**Comment by michaelwoerister** [comment]
Let's land this for now. @Zoxc, r=me if you add an explanation why the explicit impls for `TokenTree` are needed (with a link to the GH issue).

**Comment by howaboutsynergy** [comment]
worked for me with commit 315ab95a9c13cbb69ae8538fcd69b9f7b0c30f89 (HEAD -> master, origin/master, origin/HEAD)

but without this patch I get infinite loop(?) for 4 hours https://github.com/rust-lang/rust/issues/61162

Could the root cause of the infinite loop be fixed instead? 
Because this seems like a workaround. ie. it should maybe detect and fail without this patch.

**Comment by pietroalbini** [comment]
This is blocking making nightly 1.37.0 so I'd prefer for the workaround to land first.

**Comment by pietroalbini** [comment]
@bors p=1

Blocking the nightly version bump.

**Comment by pietroalbini** [comment]
Removing the beta nomination.

**Comment by Keruspe** [comment]
@pietroalbini why removing the beta nomination? I guess this could be the cause of #61262 ?

**Comment by pnkfelix** [comment]
I think @pietroalbini removed the beta nomination because we typically reserve beta backports for things that will help resolve "customer" issues, and entities bootstrapping the compiler (be they`rustc` developers or package distribution systems) are, for better or for worse, not always considered first-class customers?

(I am not trying to disparage anyone in my comment above; I made the above statement as someone who both is a `rustc` developer bootstrapping the compiler all the time, and also as someone who triages bugs on a weekly basis and struggles with the question of which bugs are worth the risk of backporting to beta.)

Anyway, what would be the expected utility of a beta-backport here? As far as I can tell by reading the discussion on #61262, the problem only arises when one uses `parallel-compiler=true` for a bootstrap, right? Are you bootstrapping using a checkout of the source code of the beta-branch itself?

**Comment by Keruspe** [comment]
@pnkfelix I am the rust packager for Exherbo and the package builds the beta branch directly from a checkout.
I closed the bug though as the issue can indeed be worked around

**Pull request merged**
