### PR TITLE
Stablise io_error_downcast

### LINKED ISSUE #99262: Tracking Issue for `io_error_downcast`
Feature gate: `#![feature(io_error_downcast)]`

This is a tracking issue for new API `std::io::Error::downcast`.

Existing APIs requires two separate calls to obtain the raw os error or the inner error and they both return `Option`.

Thus, users would have to first call `Error::get_ref` to check that we indeed has an inner error and checked that it [`is`](https://doc.rust-lang.org/std/error/trait.Error.html#method.is-2) the type we expected.

Users cannot use `std::io::Error::into_inner` becuase takes the error by value and returns `Option<Box<dyn Error + Send + Sync>>` instead of `Result<Box<dyn Error + Send + Sync>, Self>`.

They also cannot workaround this issue by calling `Error::raw_os_error`, since the `io::Error` can also be constructed using [`impl From<ErrorKind> for Error`](https://doc.rust-lang.org/std/io/struct.Error.html#impl-From%3CErrorKind%3E) or using other internal methods only accessible by the std library.

This new feature `io_error_downcast` solved this issue by providing new API `std::io::Error::downcast` to downcast the inner error easily without `unwrap` or `expect`.

### Public API

```rust
// std::io::Error

impl Error {
    fn downcast<E: std::error::Error + Send + Sync + 'static>(self) -> Result<E, Self>;
}
```

### Steps / History

- [x] API Change Proposal: https://github.com/rust-lang/libs-team/issues/57
- [x] Implementation: #98387 
- [x] Update `std::io::Error::downcast` return type and doc: #120117
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR #124076

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by NobodyXu**
Tracking issue #99262
Closes #99262

FCP completed in https://github.com/rust-lang/rust/issues/99262#issuecomment-2077374397

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Looks good to me, but there are at least 8 more days left in the final comment period before this can be stabilized.

**Comment by NobodyXu** [comment]
Thanks, I didn't know that because this is my first time doing stabilisation and also didn't find it in doc or bors output.

I would wait for 8 days and then ping you, once FCP is considered complete.

**Comment by NobodyXu** [comment]
@dtolnay FCP has completed now https://github.com/rust-lang/rust/issues/99262#issuecomment-2077374397

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
