### PR TITLE
Use more symbols in rustdoc

### PR DESCRIPTION
**Pull request by jyn514**
Builds on https://github.com/rust-lang/rust/pull/80044 and should not be merged before.

I want to test if this is actually faster before merging it, there was a lot of `to_string()` calls so I'm not sure it will actually help. That means I have to wait for 80044 to get merged before running perf.

r? @ghost

### CODE REVIEW

**Comment by jyn514** [comment]
Both instruction counts and max-rss look like noise. @GuillaumeGomez said he was working on converting even more strings to symbols, maybe that will combine well? I don't feel super strongly about whether this lands.

**Comment by GuillaumeGomez** [comment]
Let's get this in as well! Thanks!

@bors: r+ rollup

**Comment by jyn514** [comment]
@GuillaumeGomez anything that affects perf should not be rolled up, it means you can't find which PRs had an impact and it mask regressions.

**Comment by GuillaumeGomez** [comment]
Arf indeed... The `rollup=never` got overwritten I guess. Not great and bad PR handling on my side... :-/

**Comment by jyn514** [comment]
It's ok, fortunately this one didn't have much of an impact.

**Pull request merged**
