### PR TITLE
Warn unused trait imports, rebased

### LINKED ISSUE #25730: Unused import of trait is not warned about if similar trait is defined and used inside the crate
If I import a trait from an external crate into my crate and not use it, the compiler warns me about the unused import. But if I have a trait inside my crate with the same method and implement it, the compiler does not emit a warning about the unused trait from outside.

Let's say I have this trait in its own library crate:
```rust
// library crate 'testtrait'
pub trait OutsideTrait {
    fn method(&self) -> String;
}
```
In my executable crate I have the following code:
```rust
// executable crate
extern crate testtrait;

use testtrait::OutsideTrait;

trait InsideTrait {
    fn function(&self) -> String;
}

#[derive(Debug)]
struct Foo;

impl InsideTrait for Foo {
    fn function(&self) -> String {
        format!("{:?}", *self)
    }
}

fn main() {
    let b = Foo;
    println!("{}", b.function());
}
```
Now the compiler warns me about the unused import `testtrait::OutsideTrait`
However, if I change the name of `method` to `function` in order to make `OutsideTrait` match `InsideTrait`, the compiler will **not** warn me about the unused import of `testtrait::OutsideTrait`.
```rust
pub trait OutsideTrait {
    fn function(&self) -> String;
}
```
This happens regardless of whether I add an additional parameter to the function in `OutsideTrait` or `InsideTrait`.
Note, that if I implement neither trait, the compiler will again warn me about the unused import of `OutsideTrait`, which is totally fine.

The warning is not emitted by the compiler but the issue is still valid. `OutsideTrait` is an unused import and should be reported as such.

### PR DESCRIPTION
**Pull request by sanxiyn**
Rebase of #30021.

Fix #25730.

### CODE REVIEW

**Comment by nrc** [comment]
r+ with a rebase

**Comment by sanxiyn** [comment]
Travis failure is legit.

f64::sqrt is defined in std. Since librand is no_std, librand defines its own version in FloatMath trait and imports it. But randtest is not no_std, so FloatMath import is necessary for librand and unused for randtest.

**Comment by sanxiyn** [comment]
Rebased and fixed tests.

**Comment by mitaa** [comment]
cc #33154 

I assume this has something to do with this PR?

```
C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\libstd\sys/windows\fs.rs:12:5: 12:20 error: unused import
C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\libstd\sys/windows\fs.rs:12 use io::prelude::*;
                                                                                     ^~~~~~~~~~~~~~~
C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\libstd\lib.rs:283:31: 283:39 note: lint level defined here
C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\libstd\lib.rs:283 #![cfg_attr(not(stage0), deny(warnings))]
                                                                                                     ^~~~~~~~
```

**Comment by sanxiyn** [comment]
Yes, it does. Thanks for noticing.

**Comment by bluss** [comment]
Cargo should not be using deny since that makes it explicitly not forward compatible with lint changes.

@brson can we change cargotest to cap the lint level?

**Comment by sanxiyn** [comment]
We could use RUSTFLAGS. Two problems: first, cargo used by rustbuild at the moment is too old and does not support RUSTFLAGS. Second, setting RUSTFLAGS interferes with running cargo test suite.

**Comment by sanxiyn** [comment]
Cargo should reset RUSTFLAGS when running tests. Sent as rust-lang/cargo#2617.

**Comment by alexcrichton** [comment]
> cargo used by rustbuild at the moment is too old and does not support RUSTFLAGS

Hm, is it? The date is 2016-04-10 and [`RUSTFLAGS` support](https://github.com/rust-lang/cargo/pull/2241) was merged back in March.

**Comment by sanxiyn** [comment]
Oops, I was working on this PR's branch, which predates #32942. Before that, Cargo was from 2016-03-11.

**Comment by brson** [comment]
Well, to offer a differing opinion [I suggested elsewhere] that this is why cargo exists. We added this test because too many PR's broke cargo. It should be fixed in cargo before merging.

**Comment by bluss** [comment]
That's reasonable but then I have to stress that cargo should not be using `deny`. They are opting in to extra breaking changes.

**Comment by sanxiyn** [comment]
Rebased (twice) and removed unused trait imports introduced in the meantime. Waiting rust-lang/cargo#2636 to be merged so that commit hash in cargotest can be updated.

**Comment by sanxiyn** [comment]
Updated cargotest.

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/33435

**Comment by alexcrichton** [comment]
@bors: retry

* #33435

**Comment by alexcrichton** [comment]
@bors: retry

* #33435

**Pull request merged**
