### PR TITLE
Add doc aliases to fs.rs

### PR DESCRIPTION
**Pull request by D1mon**
Add aliases for create_dir, create_dir_all, remove_dir, remove_dir_all

### CODE REVIEW

**Comment by the8472** [comment]
The libs team is currently working on a policy when doc aliases are appropriate. https://github.com/rust-lang/std-dev-guide/pull/25
Some of the proposals here would not be in line with that policy.

**Comment by joshtriplett** [comment]
Based on the new doc alias policy, could you please drop the aliases for the `_all` variants, and drop the `delete` and `rm` aliases? Just keep the `mkdir` and `rmdir` aliases, and only for the function they directly map to (the non-`_all`) variant.

**Comment by jyn514** [comment]
@D1mon can you squash the commits? We don't allow merge commits, there's instructions in the dev guide: https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy

**Comment by D1mon** [comment]
I can't commit (merging is blocked). Maybe because i edit in github (without git clone)!?

**Review by JohnTitor — APPROVED** [review]
Let's go ahead with bors-squashed, that feature has some bugs but it should just work at least.
The change itself follows https://std-dev-guide.rust-lang.org/documentation/doc-alias-policy.html so LGTM.

**Comment by JohnTitor** [comment]
@bors rollup-
A rollup doesn't handle the squash status, it seems: #87539

**Comment by JohnTitor** [comment]
Okay, I've squashed them on my local, everything should be fine now.
@bors r+ rollup squash-

**Pull request merged**
