### PR TITLE
Clarify that send_to might fail in certain cases

### LINKED ISSUE #34202: OS Error 10014 (Bad address) when using "localhost" in UDP source address on Win7
Consider this code:

```
use std::net::UdpSocket;

fn main() {
    let local_addr = "localhost:8900";
    let target_addr = "example.com:8900";

    let socket = UdpSocket::bind(local_addr).unwrap();
    let buf : [u8; 9] = [176,18,0,9,161,0,0,1,1];
    socket.send_to(&buf[..],target_addr).unwrap();
}
```

which fails like this:

`thread '<main>' panicked at 'called`Result::unwrap()`on an`Err`value: Error { repr: Os { code: 10014, message: "Bei dem Versuch das Zeigerargument eines Aufrufs zu\r\nverwenden, wurde eine ung\u{fc}ltige Zeigeradresse gefunden." } }', ../src/libcore\result.rs:746`

The error occurs on the last line by the way.

If you write `let local_addr="127.0.0.1:8900";`, it works just fine (no panic).

If i remember correctly, this worked on Linux, so it should be an os specific issue. Of course you can just use an ip for the source address, but this kind of error shouldn't occur nevertheless right?
## Meta

OS: Windows 7 Professional 64bit

`rustc --version --verbose`:
rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: x86_64-pc-windows-msvc
release: 1.9.0

Backtrace:

```
stack backtrace:
   0:        0x13f82138b - std::rt::lang_start::h5b0863080165c75e
   1:        0x13f82078b - std::rt::lang_start::h5b0863080165c75e
   2:        0x13f81449f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   3:        0x13f814f8d - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   4:        0x13f81c4ab - rust_begin_unwind
   5:        0x13f824365 - core::panicking::panic_fmt::h73bf9d7e8e891a73
   6:        0x13f8115e3 - unwrap_failed<std::io::error::Error>
                        at [redacted]\src\libcore\macros.rs:29
   7:        0x13f812c34 - unwrap
                        at [redacted]\src\libcore\result.rs:687
   8:        0x13f811197 - main
                        at [redacted]\src\bin\test_udp_problem.rs:12
   9:        0x13f820158 - std::rt::lang_start::h5b0863080165c75e
  10:        0x13f81c418 - std::sys_common::thread_local::StaticKey::lazy_init::h0dbf04c687960888
  11:        0x13f81ff07 - std::rt::lang_start::h5b0863080165c75e
  12:        0x13f813179 - main
  13:        0x13f827c7a - __tmainCRTStartup
                        at f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:626
  14:         0x76cb59bc - BaseThreadInitThunk
```

### PR DESCRIPTION
**Pull request by achanda**
Closes #34202

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm this doesn't panic, right? It'd return an error?

**Comment by CensoredUsername** [comment]
This doesn't panic, it returns an error. In the linked issue `unwrap()` is just called on the error so it panics.

**Comment by achanda** [comment]
My bad, updated now.

**Comment by brson** [comment]
Waiting for updates to @alexcrichton's feedback.

**Comment by achanda** [comment]
Sorry, this fell off my radar. Updated now.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
