### PR TITLE
enable PGO on x86_64-apple-darwin

### PR DESCRIPTION
**Pull request by csmoe**
r? @lqd 

previous take https://github.com/rust-lang/rust/pull/108837

### CODE REVIEW

**Comment by lqd** [comment]
The linking issue from the previous PR was not problematic, and easy to workaround locally. The resulting profiling data however caused errors depending on the binary tools used via cmake (between the llvm distributed tools and the osx devtools).
And then PGO wasn't able to find the data it needed when instrumenting, whereas on linux they're found immediately.

Compared to not using PGO on the same master commit, what are the benchmark results you're seeing locally with this PR ?

**Comment by csmoe** [comment]
Your previous PR wasn't problematic indeed, tried to rebase it with master, but a bit annoying to resolve conflicts in yaml file, so I created this one.

I work on an Apple M1 machine, still testing.

**Comment by jyn514** [comment]
Please run `x test --stage 2` locally on this before enabling it by default. We don't test PGO in CI: https://github.com/rust-lang/rust/issues/109535

**Comment by jyn514** [comment]
Actually that might not do the right thing; you need to get a PGO compiler to run the tests somehow, I don't know if x is able to do that. If not you may need to use `build.rustc` and `x test --stage 0` in a second checkout.

**Comment by lqd** [comment]
> Please run `x test --stage 2` locally on this before enabling it by default

Tests, and benchmarks, yes. As I said before, I'm still working on this myself for rustc rather than LLVM, and I'm not sure similar changes would be enough: I have done this before and it wasn't enough just yet, but maybe I did it wrong; we'll see once we have some feedback about the results.

**Comment by lqd** [comment]
https://github.com/rust-lang/rust/pull/110792 may add hurdles to this and https://github.com/rust-lang/rust/pull/108837. 

Our experimenting is fine, and good results could help in this discussion, but it seems unlikely that PGO would fit in the current runners time budget, under the exact same CI structure.

**Comment by csmoe** [comment]
The initial motivation of this PR pair with https://github.com/rust-lang/rust/pull/110605 is trying to dist PGO'ed rust toolchain for a huge monorepo, if rust-ci resources is restricted, a dry-run mighted be enough to make sure the PGO flow work on macos.

**Comment by jyn514** [comment]
I wouldn't trust --dry-run to tell you whether it will actually work or not. I don't like the idea of having code here that's only intended for external projects and we never use in CI.

**Comment by lqd** [comment]
> to make sure the PGO flow work on macos

What results did you have locally:
- do tests still pass with your PGOed compiler ?
- what is the difference in performance (on rustc-perf benchmarks or your external huge monorepo, whichever is easier to gather) with your PGOed compiler, compared to the same rustc commit but built without PGO ?

**Comment by Dylan-DPC** [comment]
@csmoe any updates on this?

**Comment by csmoe** [comment]
@Dylan-DPC sorry, I'll retry this week.

**Comment by Dylan-DPC** [comment]
cool no worries :)

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
