### PR TITLE
Make {Rc,Arc}::allocator associated functions

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Review by tgross35 — APPROVED** [review]
Context: https://github.com/rust-lang/rust/pull/89132#discussion_r1266044996, that PR just landed a few hours ago.

I'm marking this prioritize since it fixes a (just recently introduced) namespace regression on types like `Rc<Vec<T>>` - but chance of that conflict is pretty small, so feel free to adjust if this isn't suitable.

@rustbot label +I-prioritize -T-libs +T-libs-api +A-allocators

**Comment by tgross35** [comment]
r? libs-api

**Comment by tgross35** [comment]
Pretty easy to id but here's a repro

```rust
#![feature(allocator_api)]

use std::rc::Rc;

struct Foo;

impl Foo {
    fn allocator(&self) -> u32 { 100 }
}

fn main() {
    let rc = Rc::new(Foo);
    dbg!(rc.allocator());
}
```

Output on nightly:

```
warning: method `allocator` is never used
...
[foo.rs:15] rc.allocator() = Global
```

Output on older nightly:

```
[foo.rs:15] rc.allocator() = 100
```

**Comment by apiraino** [comment]
@tgross35 we use the `I-prioritize` label for issues that need to be assigned a priority, not for patches (but thanks for raising the flag). If you are asking for an expedit review you might prefer talking with someone involved with #89132 (maybe open a topic on Zulip?) and assign to them.

@rustbot label -I-prioritize

**Comment by tgross35** [comment]
Whoops, "Indicates that prioritization has been requested for this issue" I can see why that can be read two different ways. In that case, @Amanieu reviewed the other PR so may want to do this one.

r? amanieu

**Pull request merged**
