### PR TITLE
Use queue-based `RwLock` on more platforms

### PR DESCRIPTION
**Pull request by joboet**
This switches over Windows 7, SGX and Xous to the queue-based `RwLock` implementation added in #110211, thereby fixing #121949 for Windows 7 and partially resolving #114581 on SGX. TEEOS can't currently be switched because it doesn't have a good thread parking implementation.

CC @roblabla @raoulstrackx @xobs Could you help me test this, please?
r? @ChrisDenton the Windows stuff should be familiar to you

### CODE REVIEW

**Comment by ChrisDenton** [comment]
The Windows stuff is fine. I can't easily test on Windows 7 atm (so help is welcome) but testing the Win7 binary on Windows 10 worked..

I'll wait for the SGX experts to weigh in on their target. And if someone can test on Windows 7 proper that would be great. I don't foresee any issues though so I wouldn't block on it.

**Comment by xobs** [comment]
Looks good to me:

```
...
test sync::reentrant_lock::tests::smoke ... ok
test sync::reentrant_lock::tests::trylock_works ... ok
test sync::rwlock::tests::frob ... ok
test sync::rwlock::tests::panic_while_mapping_read_unlocked_no_poison ... ok
test sync::rwlock::tests::panic_while_mapping_write_unlocked_poison ... ok
test sync::rwlock::tests::smoke ... ok
test sync::rwlock::tests::test_get_mut ... ok
test sync::rwlock::tests::test_get_mut_poison ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:307:9:
test panic in inner thread to poison RwLock
ok
test sync::rwlock::tests::test_into_inner ... ok
test sync::rwlock::tests::test_into_inner_drop ... ok
test sync::rwlock::tests::test_into_inner_poison ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:283:9:
test panic in inner thread to poison RwLock
ok
test sync::rwlock::tests::test_mapped_read_guard_covariance ... ok
test sync::rwlock::tests::test_mapping_mapped_guard ... ok
test sync::rwlock::tests::test_read_guard_covariance ... ok
test sync::rwlock::tests::test_rw_arc ... ok
test sync::rwlock::tests::test_rw_arc_access_in_unwind ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:209:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_no_poison_mapped_r_r ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:122:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_no_poison_mapped_r_w ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:149:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_no_poison_rr ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:108:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_no_poison_rw ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:135:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_poison_mapped_w_r ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:68:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_poison_mapped_w_w ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:95:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_poison_wr ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:55:9:
explicit panic
ok
test sync::rwlock::tests::test_rw_arc_poison_ww ... PANIC in PID 6:
thread '<unnamed>' panicked at library/std/src/sync/rwlock/tests.rs:81:9:
explicit panic
ok
test sync::rwlock::tests::test_rwlock_try_write ... ok
test sync::rwlock::tests::test_rwlock_unsized ... ok
test sys::os_str::bytes::tests::display ... ok
test sys::os_str::bytes::tests::slice_debug_output ... ok
test sys::pal::common::tests::bench_heap_path_alloc ... ok
...
```

**Comment by roblabla** [comment]
Oh, awesome! I had resigned myself to thinking the win7 target would be stuck with a broken implementation of RwLocks, so this is great news!

I ran the full core/alloc/std test suite on Windows 7 32-bit and 64-bit, both are passing. LGTM!

**Comment by ChrisDenton** [comment]
Thank you everyone for testing this!

@bors r+

**Pull request merged**
