### PR TITLE
Move help popup generation code

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The first commit is just a small cleanup.

The idea behind this PR is to reduce a bit more the generated HTML files by moving the duplicated code into one place instead.

r? @kinnison

### CODE REVIEW

**Review by kinnison — APPROVED** [review]
My JavaScript-fu isn't massively strong, but afaict that looks okay.  Assuming you've confirmed that it works as expected, :+1: from me.

**Comment by GuillaumeGomez** [comment]
Let's ask someone else to review it as well then!

r? @QuietMisdreavus

**Comment by JohnCSimon** [comment]
Ping from triage
@QuietMisdreavus  can you please review this PR?
cc: @GuillaumeGomez 
Thanks

**Comment by Mark-Simulacrum** [comment]
I guess keyboard shortcuts don't work without JS anyway, right? So this isn't losing functionality (or documentation of that functionality)?

**Comment by GuillaumeGomez** [comment]
Nope, just reducing generated HTML size and making page load faster for JS-disabled people (which is a complete side-effect, but a nice one I think? haha).

**Pull request merged**
