### PR TITLE
Add more links and put the link character to the left

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus 

And of course, a few screenshots:

screen shot 2017-09-17 at 22 08 46
screen shot 2017-09-17 at 22 09 47
screen shot 2017-09-17 at 22 10 56

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
So how does this look with the existing `class="anchor"` links? I see the new ones here put the anchor before the text in the header, but the previous ones had it after. Does the `position: absolute` in the CSS make it not matter?

**Comment by GuillaumeGomez** [comment]
`position: absolute;` and `left: ...px;`.

**Comment by GuillaumeGomez** [comment]
New screenshot as requested on IRC:

screen shot 2017-09-17 at 22 25 09

**Comment by QuietMisdreavus** [comment]
r=me pending travis

**Pull request merged**
