### PR TITLE
Make `u8::is_ascii` a stable `const fn`

### PR DESCRIPTION
**Pull request by ecstatic-morse**
`char::is_ascii` was already stabilized as `const fn` in #55278, so there is no reason for `u8::is_ascii` to go through an unstable period.

cc @rust-lang/libs

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
:+1:  on the code changes and the stabilization. But as I can't start FCP merges, reassigning:

r? @sfackler

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Review by Centril — APPROVED** [review]

**Pull request merged**
