### PR TITLE
Revert `cargo update` changes and bump `download-artifact` to v4

### PR DESCRIPTION
**Pull request by clubby789**
Revert #122489 and #122698

https://github.com/rust-lang/rust/pull/122951#issuecomment-2017430266
The failures + https://github.com/rust-lang/rust-log-analyzer/issues/81 are causing some annoying spam. I don't think this is _that_ important for now and I don't know enough GHA to fix it 😓

### CODE REVIEW

**Comment by Nilstrieb** [comment]
could you also take a look at https://github.com/rust-lang/rust/pull/122951, which may or may not have caused more failures?

**Comment by Kobzol** [comment]
From the error:
```
    GITHUB_TOKEN: ***
failed to determine base repo: failed to run git: fatal: not a git repository (or any of the parent directories): .git

Error: Process completed with exit code 1.
```
It looks like the `skip if S-waiting-on-bors` should have a checkout of the repository before it (not sure why it has worked before though).

**Comment by clubby789** [comment]
That error is because I replaced 'exit' with 'gh run cancel' to prevent an failed run status. But that command only works inside a checkout which we're not in at this point. This revert fixes that

**Comment by Kobzol** [comment]
https://github.com/rust-lang/rust/actions/runs/8435672859/job/23101668190

It seems like there is another error that perhaps *is* related to the bump of the `upload-artifact` action though.

**Comment by clubby789** [comment]
Added a bump to make `download-artifact` match, which should fix this?

**Comment by Kobzol** [comment]
Ok, let's try reverting for now, and updating the download action, to see if we can get back to a working state.

r? @Kobzol

**Pull request merged**
