### PR TITLE
Enable frame pointers by default

### PR DESCRIPTION
**Pull request by saethlin**
r? @ghost

### CODE REVIEW

**Comment by Nilstrieb** [comment]
note #107689 which tries to enable them on just rustc builds and already has perf results

**Comment by Nilstrieb** [comment]
instructions are pretty bad but cycles look pretty good.

**Comment by bjorn3** [comment]
Maybe try with only omitting in leaf functions?

**Comment by saethlin** [comment]
Haha I don't have a lot of time to work on this either but possibly just enough.

**Pull request closed without merging**
