### PR TITLE
Remove spawning from task::Context

### PR DESCRIPTION
**Pull request by cramertj**
r? @aturon 

cc https://github.com/rust-lang-nursery/wg-net/issues/56

### CODE REVIEW

**Comment by Nemo157** [comment]
Is the plan to provide a `Spawn` trait and `FutureObj` etc. in `futures`, or just drop them from the "core" abstractions?

**Comment by cramertj** [comment]
@seanmonstar 
> With the remove of FutureObj and co, unless arbitrary_self_types has made Future object-safe, there's no longer a way to have Future trait objects, right?

We'll continue to provide these types inside the futures crate, but they no longer need to be part of the standard library.

> Is the plan to provide a Spawn trait and FutureObj etc. in futures, or just drop them from the "core" abstractions?

Yup-- everything that is being removed from here will reappear in the futures crate.

**Comment by aturon** [comment]
This looks great, nice simplification.

@bors r+

**Comment by Thomasdezeeuw** [comment]
Isn't this a bit took quick since the discussion is still going in https://github.com/rust-lang-nursery/wg-net/issues/56? I'm for this change, but not everbody is.

**Comment by cramertj** [comment]
@Thomasdezeeuw The point of having the current std API is to experiment with the intended design-- any design (even the current one) needs to go through a real RFC before stabilization. I think the conversation in https://github.com/rust-lang-nursery/wg-net/issues/56 has turned up enough motivating factors that we should give this approach a shot. If it doesn't work out or the RFC process resolves to a different design, then we can change it. If you think there's a solid reason we shouldn't do this (to the point that it's not worth trying) please leave a comment on https://github.com/rust-lang-nursery/wg-net/issues/56 so we can take that into account!

**Comment by Ekleog** [comment]
@cramertj I think I put forward some arguments against rushing this in https://github.com/rust-lang-nursery/wg-net/issues/56 , that were only answered by “don't do this, change your API” (which I don't really consider a valid resolution). Basically, this without any solution to https://github.com/rust-lang-nursery/wg-net/issues/7 is breaking the (my? maybe I'm the only one here who actually has a use case for access to the default spawner from library code…) world without any other way to do the same thing.

On the other hand, this change can happen at any time until the RFC. Is there really a need to rush this forward before solving https://github.com/rust-lang-nursery/wg-net/issues/7?

**Comment by cramertj** [comment]
> Is there really a need to rush this forward before solving rust-lang-nursery/wg-net#7?

@Ekleog IMO one of the best steps we can take towards solving rust-lang-nursery/wg-net#7 is to actually get experience using both APIs, which this change allows us to do. Additionally, I'd like to open an RFC for futures-in-std soon, and it'd be best if we could say we'd successfully tested and been using the same API as the one being RFC'd.

**Comment by Ekleog** [comment]
@cramertj I'm not really sure I understand whether you already meant it, but… it sounds to me like the potential hooks mentioned by https://github.com/rust-lang-nursery/wg-net/issues/7 would likely need to be implemented in the `Executor` trait? Which would mean a futures-in-std RFC would still be blocked on experimenting with the outcome of https://github.com/rust-lang-nursery/wg-net/issues/7 anyway.

**Pull request merged**
