### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
11 commits in ac6bbb33293d8d424c17ecdb42af3aac25fb7295..add15366eaf3f3eb84717d3b8b71902ca36a7c84
2023-12-26 23:22:08 +0000 to 2024-01-02 03:24:42 +0000
- chore(deps): update gix (rust-lang/cargo#13230)
- chore(deps): update alpine docker tag to v3.19 (rust-lang/cargo#13228)
- rustfix: Support inserting new lines. (rust-lang/cargo#13226)
- Fix fix::fix_in_dependency to not rely on rustc (rust-lang/cargo#13220)
- cleanup: Remove error-format special-case in `cargo fix` (rust-lang/cargo#13224)
- `cargo fix`: always inherit the jobserver (rust-lang/cargo#13225)
- Bump cargo-credential to 0.4.3 (rust-lang/cargo#13221)
- `cargo add` - fix for adding features from repository with multiple packages. (rust-lang/cargo#13213)
- Remove repetitive words (rust-lang/cargo#13216)
- Add cargo:rustc-cdylib-link-arg into RESERVED_PREFIXES list (rust-lang/cargo#13212)
- chore(doc): doc for custom subcommands look up. (rust-lang/cargo#13203)

### CODE REVIEW

**Comment by ehuss** [comment]
@bors retry

Apple runner billing issue.

**Comment by fmease** [comment]
Adjusting the priority to jump ahead of the rollup #119516 in light of the dire closed tree situation.
Let me know if that's desired.

@bors p=20

**Comment by petrochenkov** [comment]
@weihanglo 
Could you include https://github.com/rust-lang/cargo/pull/13220 as well?
This will unblock https://github.com/rust-lang/rust/pull/119204.

**Comment by weihanglo** [comment]
Done.

@bors r+

**Pull request merged**
