### PR TITLE
Bump bootstrap compiler to 1.66

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This PR:

- Bumps version placeholders to release
- Bumps to latest beta
- cfg-steps code

r? @pietroalbini

### CODE REVIEW

**Comment by ehuss** [comment]
I think the PR title was intended to be 1.66, not 1.56?

**Comment by Mark-Simulacrum** [comment]
Alright, CI is passing here, so I think this is ready for review now.

**Comment by klensy** [comment]
https://github.com/rust-lang/rust/blob/9fdc5f228e9c6b8bd1937fe51a95391e7c11b1c8/src/bootstrap/compile.rs#L699-L700

This should be removed too?

**Comment by pietroalbini** [comment]
```
pietro@backdoor: ~/r/github/rust-lang/rust ((9fdc5f228e9...))$ rg '#!?\[.*\(bootstrap' -t rust
library/core/src/prelude/v1.rs
78:#[cfg(not(bootstrap))]

library/core/tests/mem.rs
80:#[cfg(not(bootstrap))] // stage 0 doesn't have the fix yet, so the test fails

library/core/src/macros/mod.rs
1517:    #[cfg(not(bootstrap))]

[ignoring stdarch]

library/alloc/src/alloc.rs
408:    #[cfg(bootstrap)]

library/std/src/prelude/v1.rs
62:#[cfg(not(bootstrap))]
pietro@backdoor: ~/r/github/rust-lang/rust ((9fdc5f228e9...))$ 
```

Are those `cfg`s intentionally skipped?

@rustbot author

**Comment by Mark-Simulacrum** [comment]
I believe all four were added after we bumped src/version, or at least removing them led to errors.

**Pull request merged**
