### PR TITLE
Update error message E0120

### LINKED ISSUE #35253: E0120 needs to be updated to new format
From: src/test/compile-fail/E0120.rs

Error E0120 needs a span_label, updating it from:

```
error[E0120]: the Drop trait may only be implemented on structures
  --> src/test/compile-fail/E0120.rs:13:1
   |
13 | impl Drop for MyTrait { //~ ERROR E0120
   | ^
```

To:

```
error[E0120]: the Drop trait may only be implemented on structures
  --> src/test/compile-fail/E0120.rs:13:1
   |
13 | impl Drop for MyTrait { //~ ERROR E0120
   | ^ implementing Drop requires a struct
```

Bonus: update the span to highlight the type.

```
error[E0120]: the Drop trait may only be implemented on structures
  --> src/test/compile-fail/E0120.rs:13:1
   |
13 | impl Drop for MyTrait { //~ ERROR E0120
   |               ^^^^^^^ implementing Drop requires a struct
```

### PR DESCRIPTION
**Pull request by Keats**
Fixes #35253 as part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by Keats** [comment]
Is there a better way to get the type name? Also I guess I should put something other than `unreachable!`?

**Comment by jonathandturner** [comment]
There may be a better way to get the type name span, but if that works, it's fine with me.

For `unreachable!`, it looks like people are using `panic!` instead and passing in a short message.

Actually, in your case, can we do something more like:

```rust
let mut err = struct_span_err!(tcx.sess, item.span, E0120,
                                                  "the Drop trait may only be implemented on structures");
match item.node {
    ItemImpl(_, _, _, _, ref ty, _) => {
        err.span = ty.span;
        err.span_label(ty.span, &format!("implementing Drop requires a struct"));
    },
    _ => ()
};
err.emit();
```

That way we can fall-back to the larger span if we have a node type we don't expect.

**Comment by Keats** [comment]
Updated

**Comment by jonathandturner** [comment]
Even better :)  Thanks!

@bors r+ rollup

**Comment by jonathandturner** [comment]
Can you run `python src/bootstrap/bootstrap.py --stage 1 --step check-tidy` and update this PR after fixing the tidy errors?

**Comment by Keats** [comment]
Sorry, updated

**Comment by jonathandturner** [comment]
No worries, thanks for updating.

@bors r+ rollup

**Pull request merged**
