### PR TITLE
Impl AsRef, Borrow for Ref, RefMut

### PR DESCRIPTION
**Pull request by dhardy**
**Summary:** Implement `AsRef`, `Borrow` for `std::cell::Ref`, `RefMut`.

Sorry if I didn't exactly follow a guide. This is too small to need an RFC?

I'm not certain about the `#[stable]` attrs, but it seems there's little choice in the matter (given that one can't have unstable impls of existing traits).

# Motivation

Why? Because we can. This is what `AsRef` and `Borrow` are for? (More generally: *any* impl of `Deref` should impl `AsRef` too?)

Further motivation:
```rust
trait Foo<T: ?Sized> {
    type Ref<'b>: std::borrow::Borrow<T>;
    fn borrow(&self) -> Self::Ref<'_>;
}

struct MyCell(std::cell::RefCell<String>);
impl Foo<str> for MyCell {
    type Ref<'b> = std::cell::Ref<'b>; // avoids the need to construct a new type here
    fn borrow(&self) -> Self::Ref<'_> {
        std::cell::Ref::map(self.0.borrow(), String::as_str)
    }
}
```

ACP: https://github.com/rust-lang/libs-team/issues/215

### CODE REVIEW

**Comment by dhardy** [comment]
Hmm, the `Borrow` impls may violate the "soft requirements" on the `Borrow` type:

> x.borrow() == y.borrow() should give the same result as x == y

But `Ref` does not impl `PartialEq`.

---

Unfortunately neither `AsRef` nor `Borrow` are exactly the ideal trait for the above example: `AsRef` does not have a blanket `impl<T> AsRef<T> for T` while `Borrow` has the above "soft requirement on behaviour" in its documentation.

**Comment by anden3** [comment]
Hello @dhardy! I noticed that there's a merge conflict for this PR, what's the status of it? :)

**Comment by dhardy** [comment]
Status: no feedback. I'm not going to waste time resolving CI/merge issues on a PR that no one wants to comment on.

**Comment by Nilstrieb** [comment]
Hi, thank you for your PR! The process for adding new library APIs was changed and if you want to push your PR forward, you should open an [ACP](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29) instead to get additional visibility. The libs API team does not have enough time to go though everything, but your change seems simple enough that it could get approved.

**Pull request closed without merging**
