### PR TITLE
allocators: don’t assume MIN_ALIGN for small sizes

### PR DESCRIPTION
**Pull request by SimonSapin**
See individual commit messages.

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’d appreciate review of not only the diff, but also the assumptions. In particular, should `alloc_system` be even more conservative than this to support arbitrary `malloc` implementations? (This is all based on research I did in only the past few days, there may be things that are “common knowledge” but that I missed.)

We might also want to reconsider how useful this `MIN_ALIGN` optimization is in the first place. In `alloc_system` it seems important: `calloc` can probably do much better than `posix_memalign` + `memset`, and `realloc` than `posix_memalign` + `memcpy` (especially of platforms with virtual memory, for allocation at least as large as the page size).

In `alloc_jemalloc` however we only use it to avoid setting some flags. jemalloc does have some fast paths for `flags == 0`, but I don’t know how much benefit they provide if we need an extra branch on the Rust side. (That branch is likely not optimized away when using `std::heap::Heap`, because of the `#[global_allocator]` indirection: #45831.)

**Comment by RalfJung** [comment]
So this does *not* fix `System.alloc` to call jemalloc, right? It just fixes `System.alloc` to at least satisfy the API when it is actually jemalloc.

**Comment by SimonSapin** [comment]
@RalfJung Correct. `System` by definition calls `malloc` and friends on Unix platforms. That the standard library overrides `malloc` in some cases is a separate issue: https://github.com/rust-lang/rust/issues/45966

**Comment by SimonSapin** [comment]
CC @alexcrichton

**Comment by alexcrichton** [comment]
Awesome, thanks! I'd personally think that the `alloc_system` implementation probably doesn't want to change too much (for the reasons you mentioned), but if we benchmark the jemalloc implementation and there's not much difference using flags vs not then seems fine to me to always specify the alignment!

Unfortunately I think it's basically just impossible to fix `System.alloc` calling jemalloc because of linker trickery. Our only recourse is to remove jemalloc.

**Comment by SimonSapin** [comment]
@alexcrichton Let’s move the relevant discussion to #45966.

**Pull request merged**
