### PR TITLE
Fix pointer value in the 'complex example' on stack/heap

### PR DESCRIPTION
**Pull request by klao**
The `f` argument will reference the actual value in the `d` box, not the box in the `bar`'s stack frame.

I am just learning Rust, so I don't know how to explain this well, but just from `f`'s type it is clear that it will be a pointer to an `i32`, not a pointer to a pointer. Some `println!("{:p}", ...)`'s can easily confirm this.

I would actually suggest to remove/simplify this part of the example. This is a subtle issue that can easily confuse people at the early stages of familiarizing with the language. (As I got confused by it. :))

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you! I agree that this could use some simplification.

**Comment by steveklabnik** [comment]
Oh, and for why: https://users.rust-lang.org/t/im-having-trouble-following-an-example-in-the-stack-and-the-heap/3666/6 <- we found this bug recently, but I hadn't had the time to update the example.

**Comment by klao** [comment]
Great explanation in the linked thread, thanks!

**Pull request merged**
