### PR TITLE
libsyntax: cleanup and refactor `pat.rs`

### PR DESCRIPTION
**Pull request by Centril**
A smaller refactoring & cleanup of `pat.rs` (best read commit by commit).

r? @petrochenkov

### CODE REVIEW

**Comment by Centril** [comment]
(I started writing up this PR before the note in https://github.com/rust-lang/rust/pull/63469#issuecomment-520362718 but I'm happy to wait for moving things around.)

**Comment by petrochenkov** [comment]
I personally don't extract code into functions unless they are called at least twice or take a whole page of text, so I'd rather back out a half of the "extract" commits.
In general, I find it harder to read code if it's broken into small fragments in different places.

**Comment by Centril** [comment]
> so I'd rather back out a half of the "extract" commits.

Which ones would you like to keep?

>  In general, I find it harder to read code if it's broken into small fragments in different places.

Heh; I personally think (and imo this is conventional SE thinking) that large methods forces you to hold more state in your head, that they obscure the overall structure re. the "overall picture" (`parse_pat_with_range_pat`) and "details" (the definitions of the alternatives in the production), and that they violate the single responsibility principle. I think it's a good idea to refactor eagerly (both into more functions and files) and plan for growth; otherwise you tend you grow huge messes like `parser.rs` was before.

**Comment by petrochenkov** [comment]
I don't want to argue about this too much, it still looks ok, in particular because *every* match arm in parse_pat is moved into a separate function (something I didn't notice in commit by commit reading), even if the resulting functions sometimes look like `do_this_thing_specifically_while_also_doing_that_thing`.

@bors r+

**Comment by dlrobertson** [comment]
:tada:

**Pull request merged**
