### PR TITLE
Use correct tracking issue for c_variadic

### LINKED ISSUE #57306: Linked tracking issue for VaList is wrong
If you click on the linked issue for [VaList](https://doc.rust-lang.org/nightly/std/ffi/struct.VaList.html) it will take you to #27745 when it seems like it should be #44930.

### PR DESCRIPTION
**Pull request by eqrion**
Fixes #57306

### CODE REVIEW

**Comment by stokhos** [comment]
Ping from triage @eqrion Have you been able to make any progress on this PR?

**Comment by eqrion** [comment]
Apologies, I forgot about this.

@stokhos Merging was blocked on conflicts, I rebased past them so it should be good to merge again. Not sure if there's something I need to do to trigger this.

**Pull request merged**
