### PR TITLE
compiler: update solaris/illumos to enable tsan support.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by jackh726** [comment]
Is there any documentation for this one way or another?

**Comment by devnexen** [comment]
https://github.com/llvm/llvm-project/blob/8a4e3675d88ecd0413d89dea1e3578a4696b05da/compiler-rt/cmake/config-ix.cmake#L801

**Comment by jackh726** [comment]
Sorry, I'm definitely not familiar here. What would the `OS_NAME` for these targets be there? `SunOS`?

**Comment by devnexen** [comment]
indeed ... sunos covers both illumos and solaris.

**Comment by jackh726** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
