### PR TITLE
Document the broken C ABI of `wasm32-unknown-unknown`

### PR DESCRIPTION
**Pull request by alexcrichton**
Inspired by discussion on
https://github.com/rust-lang/rust/issues/129486 this is intended to at least document the current state of the world in a more public location than throughout a series of issues.

### CODE REVIEW

**Comment by tgross35** [comment]
This doesn't apply to the emscripten targets too, does it? (We could probably use a doc page for that at some point)

**Comment by alexcrichton** [comment]
The check happens [here](https://github.com/rust-lang/rust/blob/ae9f5019f9ce6eb3ecd96206ade4a612efe20fd5/compiler/rustc_target/src/abi/call/mod.rs#L933-L937) so I believe it's correct that this doesn't affect the emscripten target. I'll note though that I'm not familiar enough with the emscripten target to provide much support there, e.g. I wouldn't be confident enough to write a doc page for the emscripten target.

**Comment by workingjubilee** [comment]
Thanks! This looks good to me!

@bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/129810#issuecomment-2322886566

**Comment by workingjubilee** [comment]
whoa, those are compiled as doctests?

**Pull request merged**
