### PR TITLE
Make RFC 1214 warnings into errors

### PR DESCRIPTION
**Pull request by nikomatsakis**
Make RFC 1214 warnings into errors, and rip out the "warn or err"
associated machinery. Future such attempts should go through lints
anyhow.

There is a fair amount of fallout in the compile-fail tests, as WF
checking now occurs earlier in the process.

r? @arielb1

### CODE REVIEW

**Comment by jroesch** [comment]
LGTM, seems to me a nice clean up pass.

**Comment by arielb1** [comment]
At last!

@bors r+

**Comment by nikomatsakis** [comment]
@Manishearth to be clear, this did NOT land as part of some rollup, right?

**Comment by Manishearth** [comment]
Yeah, this didn't get rolled up. I tried to, but there were merge conflicts (which is why it got mentioned by the rollups)

(Probably should have prioritized this one and fixed the smaller merge conflicts instead of breaking this PR, but I didn't notice that this PR touched so much. Sorry.)

**Comment by nikomatsakis** [comment]
Giving p=1 because this is conflict prone and better to land sooner rather than later so people have more time to adapt.

**Pull request merged**
