### PR TITLE
Disambiguate between SourceFiles from different crates even if they have the same path

### LINKED ISSUE #85955: ICE: "cannot lex `source_file` without source" with integration test
If you attempt to `include!` a file in both the library and an external integration test that links to the library (this is important because if there is no `extern crate` or `use` statements, the ICE does not happen), it causes an ICE in the latest nightly. This ICE is not present in stable or beta.

<details>
<summary>build.rs</summary>

```rust
fn main() {
    std::fs::write(
        &std::path::Path::new(&std::env::var_os("OUT_DIR").unwrap()).join("crash.rs"),
        "pub struct A;",
    )
    .unwrap();
}
```
</details>

<details>
<summary>src/lib.rs</summary>

```rust
include!(concat!(env!("OUT_DIR"), "/", "crash.rs"));
```
</details>

<details>
<summary>tests/crash.rs</summary>

```rust
extern crate abc; // abc must be replaced by the name of the crate to test (e.g. the name in the Cargo.toml file)

include!(concat!(env!("OUT_DIR"), "/", "crash.rs"));
```
</details>

### Command

```
cargo test
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (625d5a693 2021-06-01)
binary: rustc
commit-hash: 625d5a693e4697bcafdd34fd1a38c281acabb8e9
commit-date: 2021-06-01
host: x86_64-apple-darwin
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
error: internal compiler error: cannot lex `source_file` without source: /Users/src/ice-test/target/debug/build/ice-test-dcdce532143b8bc1/out/xds.core.v3.rs

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1005:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (625d5a693 2021-06-01) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x1170d13b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc0a32d3c3444fdc6
   1:        0x117135b5c - core::fmt::write::h120e3853e954a389
   2:        0x1170c33ea - std::io::Write::write_fmt::hfa38fa23f7fce513
   3:        0x1170d506f - std::panicking::default_hook::{{closure}}::h5d5d1571ac2df726
   4:        0x1170d4b6d - std::panicking::default_hook::h4f38c2182113a3d6
   5:        0x10f8b72b8 - rustc_driver::report_ice::h315ec60d4f33b035
   6:        0x1170d58a6 - std::panicking::rust_panic_with_hook::h111fa41f5cc5bae1
   7:        0x1139d22b1 - std::panicking::begin_panic::{{closure}}::hb5d77af7cdcca810
   8:        0x1139d2229 - std::sys_common::backtrace::__rust_end_short_backtrace::h4cf6426c0e11596d
   9:        0x113c91811 - std::panicking::begin_panic::hf129750fee14a661
  10:        0x1139f1080 - std::panic::panic_any::h35ee1f3d736053e5
  11:        0x1139f76ac - rustc_errors::HandlerInner::bug::hffe2549ce25674c9
  12:        0x1139f5457 - rustc_errors::Handler::bug::h5d19ee9d6012acf4
  13:        0x11335dc2a - rustc_parse::maybe_file_to_stream::{{closure}}::h2b76850df2689f69
  14:        0x11335db4f - rustc_parse::maybe_file_to_stream::h6a5b54720a5326c4
  15:        0x11335d5e3 - rustc_parse::maybe_source_file_to_parser::hb2889c8806f22353
  16:        0x11335d244 - rustc_parse::new_parser_from_file::h880749fe6c165a55
  17:        0x111edea8e - rustc_builtin_macros::source_util::expand_include::hec829b007a51890d
  18:        0x1131665fa - rustc_expand::expand::MacroExpander::fully_expand_fragment::hc9471323bbd298aa
  19:        0x113165489 - rustc_expand::expand::MacroExpander::expand_crate::ha260ef6cedc5f864
  20:        0x10f9c91c0 - rustc_interface::passes::configure_and_expand_inner::h995c2829b63caf5c
  21:        0x10f9bf430 - rustc_interface::passes::configure_and_expand::{{closure}}::hc06a0520c8089ddc
  22:        0x10f9b2fdb - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::h7057a1aefc5c0c79
  23:        0x10f9c7ef5 - rustc_interface::passes::configure_and_expand::h5530d33ac5f81757
  24:        0x10f9e680d - rustc_interface::queries::Queries::expansion::hde0b694af7141ffa
  25:        0x10f8d5e89 - rustc_span::with_session_globals::h8ceb270caa69a3cc
  26:        0x10f913b3f - std::sys_common::backtrace::__rust_begin_short_backtrace::h044fc2ce181347b9
  27:        0x10f8c6ebd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h95785b84dcf6930e
  28:        0x1170e0b6b - std::sys::unix::thread::Thread::new::thread_start::hd7d90a4d6d405897
  29:     0x7fff2073f954 - __pthread_start
```

</p>
</details>

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR fixes an ICE that can occur when the compiler encounters a source file that is part of both the local crate and an upstream crate:

1. While importing source files from an upstream crate the compiler creates a `SourceFile` entry for `foo.rs` in the `SourceMap`. Since this is an imported source file its `src` field is `None`.
2. At a later point the parser encounters `foo.rs` again. It tells the `SourceMap` to load the file but because we already have an entry for `foo.rs` the `SourceMap` will return the existing version with `src == None`.
3. The parser proceeds under the assumption that `src.is_some()` and panics when actually trying to use the file's contents.

This PR fixes the issue by adding the source file's associated `CrateNum` to the `SourceMap`'s interning key. As a consequence the two instances of the file will each have a separate entry in the `SourceMap`. They just happen to share the same file path. This approach seemed less problematic to me than trying to mutate the `SourceFile` after it had already been created.

Another, more involved, approach might be to merge the `src` and the `external_src` field.

Fixes #85955

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Looks good to me!

**Comment by michaelwoerister** [comment]
Thanks for the review, @davidtwco!

**Comment by wesleywiser** [comment]
Since this issue was introduced in #83813 which landed in 1.54, I'm nominating for backport to beta (1.54).

**Comment by gilescope** [comment]
I've built this branch and confirm this solves the ICE for me. Thank you so much @michaelwoerister !

**Comment by davidtwco** [comment]
Looks like a legitimate failure.

**Comment by michaelwoerister** [comment]
I'll look into it. 
@bors rollup=never

**Comment by michaelwoerister** [comment]
It looks like https://github.com/rust-lang/rust/pull/85834 might be culprit: `CrateNum` now gets encoded as a `StableCrateId` but the decoder in question still decodes it as a `u32`.

**Comment by michaelwoerister** [comment]
I fixed the issue by encoding the `CrateNum` part as a `StableCrateId` and then mapping that back to `CrateNum` on-demand. I also tried to remove the default encoding and decoding impls for CrateNum in order to make it more difficult to run into an encoder/decoder mismatch like this in the future but it turns out the default impls are still used somewhere. I opened https://github.com/rust-lang/rust/issues/86540 regarding that.

Do you want to take another look, @davidtwco?

**Review by davidtwco — APPROVED** [review]

**Comment by gilescope** [comment]
Thanks again @michaelwoerister for fixing this - much obliged!

**Comment by michaelwoerister** [comment]
You're welcome, @gilescope!

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/39906weekly2021062454818.html#243791684)

@rustbot label +beta-accepted

**Comment by pnkfelix** [comment]
This seems to have caused a mild (approx. -1%) [regression on ctfe-stress-4](https://perf.rust-lang.org/compare.html?start=3487be11d5f3c9afc4d8e44438cdd2af1e98c859&end=80926fc409d671e7da13f08c90642b1e71f800d9&stat=instructions:u) for the incr-unchanged case.

My intuition is that it may just be an unavoidable cost of the change in representation that was introduced here.

(Should a perf run have been done on this PR before it landed? Not an easy call to make; only one benchmark significantly regressed, but from the code itself here, this was a key data structure being modified, so maybe a perf run is always warranted in such cases.)

**Comment by cuviper** [comment]
@michaelwoerister I found this non-trivial to backport to beta, particularly with errors in `on_disk_cache.rs`. Would you be able to prepare that backport yourself?

**Comment by michaelwoerister** [comment]
Sorry, @cuviper, I totally overlooked your message. A backport PR is up at https://github.com/rust-lang/rust/pull/87393.

**Pull request merged**
