### PR TITLE
Add tests for Atomic*::fetch_{min,max}

### PR DESCRIPTION
**Pull request by bjorn3**
This ensures that all atomic operations except for fences are tested. This has been useful to test my work on using atomic instructions for atomic operations in cg_clif instead of a global lock.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Maybe this causes a failure on rollup (https://github.com/rust-lang/rust/pull/82142#issuecomment-779181680). But I'm leaving this since I'm not sure if this really causes it and another rollup is in the queue. If you're sure, please r- this and the rollup.

**Comment by bjorn3** [comment]
This is very likely the cause. I think it requires a compiler-rt intrinsic on ARM that compiler-builtins doesn't implement.

@bors r-

**Comment by bjorn3** [comment]
I disabled the tests on ARM.

**Comment by kennytm** [comment]
I think this is only undefined on `arm-android` since `__sync_fetch_and_u?(min|max)_4` do get defined on arm_linux. https://github.com/rust-lang/compiler-builtins/blob/e6fd1b272ff4cc34810e20126ffe17888a708f39/src/arm_linux.rs#L146-L150.

**Comment by bjorn3** [comment]
I have also enabled them for arm-linux now.

**Pull request merged**
