### PR TITLE
Make `assert` a built-in procedural macro

### PR DESCRIPTION
**Pull request by sinkuu**
Makes `assert` macro a built-in one without touching its functionality. This is a prerequisite for RFC 2011 (#44838).

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ping from triage @aturon! This PR needs your review.

**Comment by aturon** [comment]
cc @rust-lang/libs, I'm not a good reviewer for this.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @sinkuu!

**Comment by sinkuu** [comment]
Legit failure.

**Comment by sinkuu** [comment]
`./x.py test src/tools/cargo --stage 2` (where bors failed) passed locally, so it should be ok.

**Comment by durka** [comment]
Before this PR you could invoke `assert` as `std::assert!(...)` given `#![feature(use_extern_macros)]`, but not anymore. Intended?

**Comment by sinkuu** [comment]
I overlooked that. Is it possible to export built-in macros via std?

**Pull request merged**
