### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #72810 (validate basic sanity for TerminatorKind)
 - #72989 (Revert pr 71840)
 - #72993 (Count the beta prerelease number just from master)
 - #73057 (Clean up E0644 explanation)
 - #73059 (remove outdated comment)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
This was a [small perf loss](https://perf.rust-lang.org/compare.html?start=9c1857fad849ad56d38327b9bc11377a0bdbb4cf&end=450abe80f193ccefbfcd48214d70520f2d507f0e&stat=instructions:u). Ignore the `script-servo-opt` change, that one bounces around like crazy. There were some small improvements, but more losses.

@pnkfelix, @RalfJung: your PRs seem the mostly likely causes. Any ideas?

**Comment by Dylan-DPC** [comment]
would recommend branching off to a new issue - makes it easier to track than on a merged pr

**Comment by RalfJung** [comment]
@nnethercote I measured perf impact of MIR validation in https://github.com/rust-lang/rust/pull/73087, and it came out with "basically no impact". That measurement includes this PR. So I think it's not my PR -- but I might misinterpret.

**Comment by pnkfelix** [comment]
I can believe that my revert (PR #72989) of the drop tree reworking (PR #71840) caused regressions.

But that injected bugs, so we have to live with the revert for the short term at least.

**Pull request merged**
