### PR TITLE
Add an alias from cargo x to cargo run --

### LINKED ISSUE #95858: Add an alias from `cargo x` to `cargo run --` in `.cargo/config.toml`.
This helps with https://github.com/rust-lang/rust/issues/94829 by  making more visually similar to the existing `src/tools/x` command.

_Originally posted by @bjorn3 in https://github.com/rust-lang/rust/issues/95854#issuecomment-1094082063_

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/95858

### CODE REVIEW

**Comment by jyn514** [comment]
I think this will interact poorly with vendoring: https://github.com/rust-lang/rust/blob/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/src/bootstrap/bootstrap.py#L1187-L1206
maybe we can change that check to see if `.cargo/config` differs from the default? and remove the `rmtree(.cargo)` call?

**Comment by Mark-Simulacrum** [comment]
I am not sure this is really worth it -- do we think that the long-term expectation for user interface is cargo x build?

I think it might be worth holding off on a change like this PR until we have a clearer story around `cargo run --` working *and* an expectation that users should migrate to it. I'm not sure we're there yet, though there's definitely a relatively happy path to getting there I expect.

For example, for cargo test, I think there may be a pretty clear path to that running the bootstrap process and passing off any arguments as today's arguments to x.py test. cargo fmt seems like it should be largely in a similar place of 'works out of the box' with some work (perhaps upstream to it as a tool).

For doc, build, and check, the story is more complicated -- honestly, mostly because all three lack a clear integration point for non-Cargo tools to step in. It's not clear to me yet what our goal here should be (e.g., we could push for rustbuild-specific features in Cargo, but I think no one is a fan of that trajectory). Maybe there's a general integration point -- similar to https://github.com/matklad/cargo-xtask/, but without .cargo/config.toml modifications which feel to me like somewhat of an anti-pattern (it's sort of a user, not upstream file, it seems to me).

It might be that we push for ability to declare aliased commands from Cargo.toml, pointing to subcrates in the workspace explicitly, as an unstable feature. That could mean a natural path for xbuild/xdoc/xcheck and so on to work out of the box, for example, if you already have a local rustc sysroot. Features like that have stalled out historically, but I think given a strong use case and interested hands, it's not impossible we could add something quite limited and unstable, though likely hard.

**Comment by Mark-Simulacrum** [comment]
To elaborate a little on the .cargo/config.toml concern -- I think I recall hearing that some consumers of rustc tarballs and git trees generating or using that file to add their own settings (alongside the config.toml file from x.py), so I am hesitant to start expanding the amount of things we ourselves put in it as default. It's not insurmountable as a concern, but I think we're not at the point of knowing it's the right trajectory from my perspective.

**Comment by hi-rustin** [comment]
> I think it might be worth holding off on a change like this PR until we have a clearer story around `cargo run --` working _and_ an expectation that users should migrate to it.

Close it for now.

**Comment by jyn514** [comment]
Replied here: https://github.com/rust-lang/rust/issues/95858#issuecomment-1133807250

(but I do agree it makes sense to hold off until it's more clear where we want to end up with the entrypoint)

**Pull request closed without merging**
