### PR TITLE
appveyor: Wrap handle.exe download in a retry

### PR DESCRIPTION
**Pull request by alexcrichton**
Should help deal with spurious download failures.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors p=20 

We keep hitting this...

**Comment by Mark-Simulacrum** [comment]
I guess we failed to retry? *After 3 hours of retrying*? This seems suspicious..

https://ci.appveyor.com/project/rust-lang/rust/build/1.0.3252/job/s26dwj5huwd7x8fs

@bors retry
 - #40474

```
00:00:39] Added C:\ProgramData\chocolatey\bin\ISCC.exe shim pointed to 'c:\program files (x86)\inno setup 5\iscc.exe'.
[00:00:39]  The install of innosetup was successful.
[00:00:39]   Software installed as 'exe', install location is likely default.
[00:00:39]
[00:00:39] Chocolatey installed 2/2 packages. 0 packages failed.
[00:00:39]  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[00:00:39] set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
[00:00:39] appveyor-retry appveyor DownloadFile https://download.sysinternals.com/files/Handle.zip
```

**Comment by ishitatsuyuki** [comment]
Time to mirror it. It may just being the network hanging.

**Comment by Mark-Simulacrum** [comment]
`Downloading Handle.zip (316,667 bytes)...6%` Progress!

@bors retry
 - #40474

**Comment by ishitatsuyuki** [comment]
@Mark-Simulacrum I'd rather recommend calm down and fix this to use a mirror. I have no idea who has access to S3, but I guess it's not only granted to Alex. You should also be able modify the commit in that case.

**Comment by kennytm** [comment]
Travis:

```
[01:29:00] error: unable to get packages from source
[01:29:00] 
[01:29:00] Caused by:
[01:29:00]   failed to get 200 response from `https://crates.io/api/v1/crates/utf8-ranges/0.1.3/download`, got 500
```

I thought it was fixed in #41978? And `utf8-ranges` again?

**Comment by alexcrichton** [comment]
@kennytm no the bootstrap won't use that Cargo until the next beta happens.

**Comment by frewsxcv** [comment]
Even with this change, AppVeyor still ran into an issue downloading handle.exe:

https://ci.appveyor.com/project/rust-lang/rust/build/1.0.3261/job/hgnbayocfa0rvkis

**Comment by alexcrichton** [comment]
@bors: r=Mark-Simulacrum 

I've updated to a mirror

**Comment by frewsxcv** [comment]
that's gotta be unrelated, but what exactly is the error there?

@bors retry

**Comment by Mark-Simulacrum** [comment]
Yeah, I guess... rustc hung? It's odd.

**Comment by alexcrichton** [comment]
From the [previous successful build](https://travis-ci.org/rust-lang/rust/jobs/232418631):

```
[00:09:29]    Compiling rustc v0.0.0 (file:///checkout/src/librustc)
[00:13:25]    Compiling rustc_incremental v0.0.0 (file:///checkout/src/librustc_incremental)
```

Not sure how this jumped from 4 minutes to >30 in one run...

**Comment by alexcrichton** [comment]
@bors: retry

* travis deployment problem?

**Pull request merged**
