### PR TITLE
Library stabilizations/deprecations for 1.15 release

### LINKED ISSUE #23755: std::io::Take should have into_inner() method
It seems like a reasonably obvious thing to do and would be trivial to implement. The only alternative right now is to always use `.by_ref()` before calling `.take()`, and that's not always viable (e.g. because the `io::Take` needs to be kept around without borrowing the owner of the underlying reader).

An example usage would be implementing a message-based protocol on top of a stream protocol, where the messages either have fixed-length frames or have length indicators, I might want to call `.take()` to be able to work with a single message and then `.into_inner()` when I'm done to recover the underlying reader.

### LINKED ISSUE #27733: Tracking issue for `borrow_state` stabilization
The `RefCell` API offers a way to determine the state of the borrow, to avoid panics on additional borrowing. It's not clear how useful this API is in practice, but it's otherwise ready for stabilization.

-----

**EDIT:** @KodrAus

Before stabilization:
- [ ] Add a concrete, motivating example to the documentation https://github.com/rust-lang/rust/pull/59211#issuecomment-474611456

### LINKED ISSUE #27746: Tracking issue for `cell_extras` stabilization
The `Ref` type connected to `RefCell` supports some methods for changing the type of the reference, such as `map` and `filter_map`. While `map` is clearly fully general, `filter_map` is somewhat of a special case hooked into `Option`. To make it fully general would likely require HKT. We need an overall plan before stabilization.

### LINKED ISSUE #27784: Tracking issue for char encoding methods
This is a tracking issue for the unstable `unicode` feature and the `char::encode_utf{8,16}` methods.

The interfaces here are a little wonky but are done for performance. It's not clear whether these need to be exported or not or if there's a better method to do so through iterators.

### LINKED ISSUE #28356: Tracking issue for Arc/Rc extras
This is a tracking issue for the `arc_counts`, `rc_counts`, and `rc_would_unwrap` features. The counting functions have been around for awhile but `would_unwrap` was added recently.

cc #27718, more discussion there.

### LINKED ISSUE #31398: Tracking issue for CommandExt::before_exec
Open questions:
- The requirements for `Send` + `Sync` on the closure need to be documented and are "somewhat odd"
- It's somewhat surprising to have to deal with a list of callbacks to invoke, especially when order might matter quite a bit.
- There are weird semantics with using `Stdio::piped()` for any of the stdio handles because they'll immediately close the other half of the pipe (via CLOEXEC). 

This is a tracking issue for https://github.com/rust-lang/rfcs/pull/1359.

### LINKED ISSUE #34931: Tracking issue for `mpsc::Receiver::try_iter`
Tracking issue for the new non-blocking `mpsc::Receiver` iterator API introduced in #34724.

The API is currently gated behind the unstable `receiver_try_iter` feature.

The API includes:
- `std::sync::mpsc::Receiver::try_iter`
- `std::sync::mpsc::TryIter`

cc @alexcrichton

### LINKED ISSUE #35428: Add `is_empty` function to `ExactSizeIterator`
Tracking issue for functionality introduced in https://github.com/rust-lang/rust/pull/34357

### LINKED ISSUE #35601: Introduce `as_slice`/`as_mut_slice` methods on `std::vec::IntoIter` struct.
Tracking issue for: https://github.com/rust-lang/rust/pull/35447

### LINKED ISSUE #35603: Tracking issue for Atomic*::{get_mut, into_inner}
Tracking issue for https://github.com/rust-lang/rfcs/pull/1649

### LINKED ISSUE #35918: Tracking issue for `File::read_at`, `File::write_at` (`file_offset`)

### LINKED ISSUE #36105: Tracking issue for Iterator min/max_by
https://github.com/rust-lang/rust/pull/35856

### PR DESCRIPTION
**Pull request by aturon**
Stabilized:

- `std::iter::Iterator::{min_by, max_by}`
- `std::os::*::fs::FileExt`
- `std::sync::atomic::Atomic*::{get_mut, into_inner}`
- `std::vec::IntoIter::{as_slice, as_mut_slice}`
- `std::sync::mpsc::Receiver::try_iter`
- `std::os::unix::process::CommandExt::before_exec`
- `std::rc::Rc::{strong_count, weak_count}`
- `std::sync::Arc::{strong_count, weak_count}`
- `std::char::{encode_utf8, encode_utf16}`
- `std::cell::Ref::clone`
- `std::io::Take::into_inner`

Deprecated:

- `std::rc::Rc::{would_unwrap, is_unique}`
- `std::cell::RefCell::borrow_state`

Closes #23755
Closes #27733
Closes #27746
Closes #27784
Closes #28356
Closes #31398
Closes #34931
Closes #35601
Closes #35603
Closes #35918
Closes #36105

### CODE REVIEW

**Comment by aturon** [comment]
r? @alexcrichton 

I'll push up a final commit to take care of any remaining build failures before sending to bors, but you can go ahead and review.

**Comment by aturon** [comment]
cc @rust-lang/libs

**Comment by alexcrichton** [comment]
r+ from me, feel free to r=me and follow bors failures

Looks like `make tidy` may be failing though?

**Comment by achanda** [comment]
Can we add https://github.com/rust-lang/rust/issues/36949 here?

**Comment by aturon** [comment]
@achanda No, that issue has not entered its "final comment period" for stabilization yet -- we like to make sure that people are aware that the feature is headed for stabilization and have a chance to make final comments before we land it. I expect we'll pick it up for the 1.16 release.

**Comment by achanda** [comment]
Got it, thanks @aturon!

**Comment by frewsxcv** [comment]
It looks like there are Travis errors?

**Comment by frewsxcv** [comment]
Looks like there are a couple more errors.

**Comment by frewsxcv** [comment]
More errors again. I'll stop responding if you've got it under control :)

**Comment by bluss** [comment]
I'm unsure about ExactSizeIterator::is_empty #35428

**Comment by aturon** [comment]
I'm removing the `is_empty` stabilization, to allow more time for discussion.

**Pull request merged**
