### PR TITLE
submodules: update clippy from c0dbd34b to bd33a97c

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
Fix implicit_return docs
rustup https://github.com/rust-lang/rust/pull/61758/files
Remove wrong lifetime from LintContext
Workaround for rust-lang/rustfmt#3615
Fixing eta with respect to lazy evaluation.
````
r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors p=1

waiting for https://github.com/rust-lang/rust/pull/61597 to get merged first

**Comment by Centril** [comment]
@bors p=0

No need to p=1 clippyups; I will roll them up.

**Comment by matthiaskrgr** [comment]
rebased

**Comment by matthiaskrgr** [comment]
>No need to p=1 clippyups; I will roll them up.

It still makes sense to increase priority because then, in case the rollup fails, the submodule update will be checked next.

**Pull request merged**
