### PR TITLE
Move static assertions into test modules

### PR DESCRIPTION
**Pull request by camsteffen**

### CODE REVIEW

**Comment by camsteffen** [comment]
Just to separate tests from implementation. I saw these functions and wondered how are they used in the impl. And they aren't.

**Comment by camsteffen** [comment]
Also for consistency with other code. I could alternatively just add cfg test.

**Comment by camelid** [comment]
> Just to separate tests from implementation. I saw these functions and wondered how are they used in the impl. And they aren't.

IIUC, they are all prefixed with `_assert`, which usually implies a static assertion. Static assertions are usually kept inline with the code that they are asserting against (e.g., `static_assert_size` is usually next to the data structure that it is asserting the size of).

**Comment by JohnTitor** [comment]
Hmm, I agree the static assertion items in `/library` are losing consistency. For instance:

- `fn _assert_*`: 6 functions in the normal mod, 3 functions in the test mod
- `fn assert_covariance`: 3 functions in the normal mod, 3 functions in the test mod

So, we could say it would be up to the contributors and it seems fine to me. I don't mind accepting this but I also don't feel like it's a cleanup. If we prefer that they're in test modules, then we should clarify that rule and ensure it with tidy or something else IMHO. Otherwise, such a PR comes again and again.

**Comment by crlf0710** [comment]
@camsteffen Ping from triage, could you address the comments above? Thanks!

**Comment by camsteffen** [comment]
> So, we could say it would be up to the contributors and it seems fine to me.

I'll just go with that since there doesn't seem to be much desire for this.

**Pull request closed without merging**
