### PR TITLE
Remove const trait bound modifier hack

### PR DESCRIPTION
**Pull request by compiler-errors**
It's no longer necessary, according to the test suite :D

r? @fee1-dead or anyone really

### CODE REVIEW

**Comment by fee1-dead** [comment]
Although it still seems weird that we're pushing constness for traits in `lower_path_segment` somehow. Might need more investigation, though I'm a bit busy these few weeks.

@bors r+ rollup

**Comment by fmease** [comment]
> according to the test suite

Well the test that used to exercise this hack I added was effectively 'disabled' by removing the `effects`  feature flag: [tests/ui/rfcs/rfc-2632-const-trait-impl/const-trait-bounds-trait-objects.rs](https://github.com/rust-lang/rust/blob/master/tests%2Fui%2Frfcs%2Frfc-2632-const-trait-impl%2Fconst-trait-bounds-trait-objects.rs). I haven't checked if that hack is still needed.

**Comment by compiler-errors** [comment]
Ideally the hack would be implemented some other way since I'm cleaning up how we pass through trait bound modifiers in #131652.

**Comment by fmease** [comment]
No longer seems to be necessary: `rustc +9322d183f45e0fd5a509820874cc5ff27744a479 tests/ui/rfcs/rfc-2632-const-trait-impl/const-trait-bounds-trait-objects.rs --edition=2021 -Zcrate-attr='feature(effects)' -Znext-solver` doesn't ICE.

**Pull request merged**
