### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
10 commits in bc89bffa5987d4af8f71011c7557119b39e44a65..4ed7bee47f7dd4416b36fada1909e9a62c546246
2024-06-22 00:36:36 +0000 to 2024-06-25 16:28:22 +0000
- test: omit target-dir name (rust-lang/cargo#14142)
- test: migrate offline, open_namespaces and owner to snapbox (rust-lang/cargo#14138)
- docs: remove stray comment (rust-lang/cargo#14133)
- Change tests to support `rustc` wording changes (rust-lang/cargo#14135)
- deps: dont use tracing-attributes for workspace, use for cargo only (rust-lang/cargo#14122)
- Include vcs_info even if workspace is dirty (rust-lang/cargo#13960)
- test: migrate profile* to snapbox (rust-lang/cargo#14128)
- test: migrate path and paths to snapbox (rust-lang/cargo#14109)
- test: migrate rustflags, rustup and script to snapbox (rust-lang/cargo#14126)
- test: migrate rename_deps, replace, required_features and run to snapbox (rust-lang/cargo#14127)

### CODE REVIEW

**Comment by ehuss** [comment]
@bors retry

`Could not resolve host: github.com`

**Comment by workingjubilee** [comment]
was:
>  Docker version 24.0.9, build 2936816
>  Error response from daemon: Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
>  Error: Process completed with exit code 1.

**Comment by estebank** [comment]
Same error @workingjubilee saw in the previous run. Trying once more just in case.

@bors retry

**Comment by compiler-errors** [comment]
@bors treeclosed-

A rollup (https://github.com/rust-lang/rust/pull/126965#issuecomment-2189980900) has been testing for an hour -- seems like this is mitigated.

**Pull request merged**
