### PR TITLE
core: add functions to flip boolean

### PR DESCRIPTION
**Pull request by jewlexx**
This PR adds two functions which invert a boolean value.

`.toggle` takes a mutable reference to a boolean value, and inverts it, then replaces the existing value with the inverted boolean.

`.flip` takes a reference to a boolean value, and inverts it, then returns that inverted value.

Implementation details are in `library/core/src/bool.rs` and tests are in `library/core/tests/bool.rs`.

The tests cover constant boolean flips, and both functions, and their applications.

### CODE REVIEW

**Comment by joshtriplett** [comment]
For `flip`, we already have a function for this: [`not`](https://doc.rust-lang.org/std/ops/trait.Not.html#tymethod.not).

If we get inherent traits in the future, I'd love to make `Not` an inherent trait of `bool`.

But in the interim, I don't think we should add these.

**Comment by jewlexx** [comment]
What about `toggle`? As far as I know that doesn't already exist, and it's more ergonomic in a lot of cases.

E.G. 
```rust
use parking_lot::{Mutex, const_mutex};

static BOOLEAN: Mutex<bool> = const_mutex(false);

fn main() {
  BOOLEAN.lock().toggle();
  // The above is far more ergonomic than
  *BOOLEAN.lock() = BOOLEAN.lock().not();
  // or another implementation which reaches the same goal
}
```

**Comment by joshtriplett** [comment]
@jewlexx If you have a `bool` protected by a `Mutex`, you may be able to replace it with an `AtomicBool`. `AtomicBool` has `fetch_nand` which would work for this (`fetch_nand` with `true` is effectively `fetch_not`). We could potentially also add a `fetch_not`, which I do think would help.

**Comment by jewlexx** [comment]
Okay thank you for your help

**Pull request closed without merging**
