### PR TITLE
Migrate `error-found-staticlib-instead-crate`, `output-filename-conflicts-with-directory`, `output-filename-overwrites-input`, `native-link-modifier-verbatim-rustc` and `native-link-verbatim-linker` `run-make` tests to `rmake.rs` format

### PR DESCRIPTION
**Pull request by Oneirical**
Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks! LGTM but needs a `./x fmt`, r=me after that.

ferrisOwOYeah_286x100

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/126602#issuecomment-2174022340

**Comment by Oneirical** [comment]
So, there was an `//@ ignore-apple` in the original test, which I removed because I wanted to run bors try to learn the reason, and then I forgot it was gone.
At least, we know the reason now, but from now on, when I test why these ignores exist, it should be included in the PR description or a comment.

**Comment by jieyouxu** [comment]
Thanks, r=me after CI is green.

**Pull request merged**
