### PR TITLE
really_init cmdline args on Miri

### LINKED ISSUE #66862: `miri` no longer builds after rust-lang/rust#66547
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#66547, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @leo60228, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @dtolnay, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
r? @joshtriplett 

Closes #66862.

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]

**Comment by joshtriplett** [comment]
Failure looks entirely spurious, retrying.

@bors retry

**Comment by dtolnay** [comment]
I think Chocolatey is down.

```console
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
  Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
```

**Pull request merged**
