### PR TITLE
rustdoc-json: Better Header Type

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
- Make ABI an enum, instead of being stringly typed
- Replace Qualifier HashSet with 3 bools
- Merge ABI field into header, as they always occor together

r? @CraftSpider 

@rustbot modify labels: +A-rustdoc-json +T-rustdoc

### CODE REVIEW

**Comment by CraftSpider** [comment]
I'm definitely a fan of this change
@bors r+

**Comment by CraftSpider** [comment]
Maybe should have waited for tests to finish, but ah well, bors will fail if it does :P

**Comment by aDotInTheVoid** [comment]
This needs to be reapproved on the latest version

**Pull request merged**
