### PR TITLE
[DO NOT MERGE] Test the hashbrown `add-is_empty-checks` branch.

### PR DESCRIPTION
**Pull request by nnethercote**
This gave lots of small instruction count wins (up to 1.3%) during local measurements. This PR is to measure the change on CI. It refers to a branch on my fork of `hashbrown` and so isn't suitable for landing.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
> The job **`dist-x86_64-linux`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/4623197588?check_suite_focus=true) [(plain)](https://github.com/rust-lang-ci/rust/commit/a73ccfae448712957ea5d06f7fdc808c2c0d8f87/checks/4623197588/logs)
> Click to see the possible cause of the failure (guessed by this bot)

The bot guessed wrongly. Here is the real error:
```
2021-12-24T02:12:07.7357772Z error: failed to sync
2021-12-24T02:12:07.7358416Z 
2021-12-24T02:12:07.7358773Z Caused by:
2021-12-24T02:12:07.7359650Z   found duplicate version of package `hashbrown v0.11.2` vendored from two sources:
2021-12-24T02:12:07.7372682Z 
2021-12-24T02:12:07.7374834Z   	source 1: registry `crates-io`
2021-12-24T02:12:07.7376518Z   	source 2: https://github.com/nnethercote/hashbrown?branch=add-is_empty-checks#dec8e8cc
2021-12-24T02:12:07.7378823Z 
2021-12-24T02:12:07.7379152Z 
2021-12-24T02:12:07.7380930Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "vendor" "--sync" "/checkout/./src/tools/rust-analyzer/Cargo.toml" "/checkout/./compiler/rustc_codegen_cranelift/Cargo.toml"
2021-12-24T02:12:07.7382936Z expected success, got: exit status: 101
```
I don't understand what's going wrong. `cargo vendor`? `rust-analyzer`? :shrug:

**Comment by joshtriplett** [comment]
I think you might have more luck adding your version of hashbrown to the `[patch.crates-io]` section of the top-level `Cargo.toml`.

**Comment by the8472** [comment]
> I don't understand what's going wrong. cargo vendor? rust-analyzer? shrug

Yeah, dist is building rust-src package which vendors all the dependencies and if you have inconsistent ones across several crates it fails.

> I think you might have more luck adding your version of hashbrown to the [patch.crates-io] section of the top-level Cargo.toml.

That may not be sufficient if rust-analyzer pulls in its own hashbrown and causes a vendoring conflict. I ran into the same problem in #90673 so `src/tools/tidy/src/extdeps.rs` will likely need some patching.
[This commit](https://github.com/rust-lang/rust/pull/90673/commits/f91df9b84a962b171bbb2944d7dc81c40d70a221) adds an option to disable tool building which should disable rust-analyzer, but I haven't managed to test it yet.
On top of those issues `tidy` will fail too due to lack of whitelisting for allowed sources.

You can check locally with tidy and `x.py dist --stage 1`

**Comment by nnethercote** [comment]
With only mingw-check failing, it should be possible get a CI perf run happening, as in #92548...

@bors try @rust-timer queue

**Comment by lqd** [comment]
I'm not sure which use-cases of try artifacts would be broken by this but here goes: you could remove the cargo vendor step making `dist` fail [here](https://github.com/rust-lang/rust/blob/b03c504742d086df063bfa105a1186bbc01a4b0e/src/bootstrap/dist.rs#L918-L928). The rust-src component will be incomplete but that should hopefully be enough to get a try build to be profiled. 

(In fact I can probably test that theory for you before your TZ's rolls over a new day)

**Comment by nnethercote** [comment]
https://github.com/rust-lang/hashbrown/pull/305 now has a pull request, so this PR isn't needed any more.

**Comment by nnethercote** [comment]
Thanks, @lqd!

The results ended up [here](https://perf.rust-lang.org/compare.html?start=b03c504742d086df063bfa105a1186bbc01a4b0e&end=7f2f2f7e1a8b9a1c3e3329facd5fc84e11f5da4d
). They are curious. On local measurements I got uniform instruction count wins, with no regressions.

On CI there were a lot of instruction count wins, but also some regressions. But the cycle time results -- which are a more realistic metric than instruction counts, but normally are noisy -- are great! Almost universal improvements, up to 4.65%, plus one 11% which I don't trust.

The wall-time results also look decent. They're so noisy that you have to show the non-significant results to see many results, but there are clearly more wins than losses, which suggests a real improvement overall. Based on this, I will submit a PR to hashbrown.

**Pull request closed without merging**
