### PR TITLE
ancilliary data tests only for relevant oses

### PR DESCRIPTION
**Pull request by devnexen**
As it stops tests otherwise, triggering only for linux/android.

### CODE REVIEW

**Comment by the8472** [comment]
> As it stops tests otherwise, triggering only for linux/android.

I have difficulty understanding the PR description. Do you mean the tests aren't working on other platforms? I think they *should* work, e.g. freebsd does have a notion of SCM_RIGHTS. https://www.freebsd.org/cgi/man.cgi?query=unix&sektion=4

**Comment by devnexen** [comment]
it does not work as it is not implemented here (yet).

**Comment by the8472** [comment]
Which platform is "here"?

**Comment by devnexen** [comment]
I was referring to rust, not implemented for BSD in general, for instance.

**Comment by the8472** [comment]
That doesn't seem right? The ancilliary module itself is exported on various BSDs.

https://github.com/rust-lang/rust/blob/5de331ba40ac722dd5513c79194c6c411766a23f/library/std/src/os/unix/net/mod.rs#L15-L25

And inside the module `ScmRights` is exported unconditionally.

https://github.com/rust-lang/rust/blob/5de331ba40ac722dd5513c79194c6c411766a23f/library/std/src/os/unix/net/ancillary.rs#L236-L237

Since that is public *should* work on all the listed platforms, at least on nightly since it's still unstable. If it doesn't then that's a bug that needs to be fixed one way or another, rather than disabling tests.

**Comment by devnexen** [comment]
it is mainly for this reason 
https://github.com/rust-lang/rust/blob/5de331ba40ac722dd5513c79194c6c411766a23f/library/std/src/os/unix/net/ancillary.rs#L181

**Comment by the8472** [comment]
But that's for `SocketCred` while the test is about `ScmRights`

**Comment by devnexen** [comment]
true sorry. In reality, the issue seems to be the if let pattern, making the unreachable code path useless.

**Pull request closed without merging**
