### PR TITLE
overlook overflows in rustdoc trait solving

### LINKED ISSUE #52873: ICE when running `cargo doc` on `typenum` at `librustc/traits/structural_impls.rs:178`
```
 Documenting typenum v1.10.0 (file:///home/hdevalence/code/typenum)
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached

thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (866a71325 2018-07-29) running on x86_64-unknown-linux-gnu

error: Could not document `typenum`.
```

Steps to reproduce:
```
git clone https://github.com/paholg/typenum.git
cd typenum
echo 'nightly-2018-07-24' > rust-toolchain
cargo doc # works
echo 'nightly-2018-07-30' > rust-toolchain
cargo doc # ICE
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Context:

The new rustdoc "auto trait" feature walks across impls and tries to run trait solving on them with a lot of unconstrained variables. This is prone to overflows. These overflows used to cause an ICE because of a caching bug (fixed in this PR). But even once that is fixed, it means that rustdoc causes an overflow rather than generating docs.

This PR therefore adds a new helper that propagates the overflow error out. This requires rustdoc to then decide what to do when it encounters such an overflow: technically, an overflow represents neither "yes" nor "no", but rather a failure to make a decision. I've decided to opt on the side of treating this as "yes, implemented", since rustdoc already takes an optimistic view. This may prove to include too many items, but I *suspect* not. 

We could probably reduce the rate of overflows by unifying more of the parameters from the impl -- right now we only seem to consider the self type. Moreover, in the future, as we transition to Chalk, overflow errors are expected to just "go away" (in some cases, though, queries might return an ambiguous result). 

Fixes #52873

cc @QuietMisdreavus -- this is the stuff we were talking about earlier
cc @GuillaumeGomez -- this supersedes #53687

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Er, dang it, I should try to make a test for this. Now that I know what's going wrong I may be able to do it.

**Comment by GuillaumeGomez** [comment]
Oh this is **perfect**! Thanks a lot!

On rustdoc side, it'll be "easy". I already have something in mind: if we get an overflow, we just continue to check if there is an other matching trait, if not, then we consider this one was a matching one. How does that sound for you?

**Comment by nikomatsakis** [comment]
> On rustdoc side, it'll be "easy". I already have something in mind: if we get an overflow, we just continue to check if there is an other matching trait, if not, then we consider this one was a matching one. How does that sound for you?

I'm not sure I understand exactly what you are proposing. Do you mean "continue to look for any other matching impl"?

**Comment by eddyb** [comment]
r=me with tests added

**Comment by GuillaumeGomez** [comment]
@nikomatsakis Yes I do! (sorry for the answer delay...)

**Comment by nikomatsakis** [comment]
Argh. So I spent a while trying to reproduce this error with a self-contained test case but I've failed thus far.

**Comment by nikomatsakis** [comment]
I guess I will start by paring down the existing failure.

**Comment by nikomatsakis** [comment]
Finally reduced to a test https://gist.github.com/nikomatsakis/f3279ba3aad294559b566786c7884d91

**Comment by GuillaumeGomez** [comment]
Like I said: seems to appear starting a certain number of possibilities. Thanks a lot in any case!

**Comment by QuietMisdreavus** [comment]
The linked issue is still occurring on beta; should we backport this PR?

**Comment by GuillaumeGomez** [comment]
Didn't you disable blanket impls doc generation on beta? If so, it shouldn't be happening... Otherwise, it means the bug was not from there and that we should backport this pr and re-enable blanket impl doc generation.

**Comment by GuillaumeGomez** [comment]
Weird...

**Comment by QuietMisdreavus** [comment]
@rust-lang/rustdoc Since this never got a beta backport, now that ICE is on stable. I've gotten a couple confirmations that 1.30.0 fails to build docs for `typenum`. If the release team decides to publish a point release, should we backport this?

@rfcbot poll T-rustdoc Stable backport?

**Comment by QuietMisdreavus** [comment]
If it helps the decision, someone was able to get this branch cleanly rebased onto the stable branch, so it should work out. https://github.com/rust-lang/rust/compare/stable...joelgallant:predicate_may_hold-failure

**Comment by QuietMisdreavus** [comment]
Urf, trying to get the rfcbot poll to work. One last try, then i'm switching to manual ticky-boxes...

@rfcbot poll Stable backport?

**Comment by pietroalbini** [comment]
There seems to be consensus from the rustdoc team, marking this as stable-accepted.

**Pull request merged**
