### PR TITLE
Improve associated constant rendering in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Before:

screen shot 2017-02-19 at 00 30 51

After:

screen shot 2017-02-19 at 00 30 39

cc @SergioBenitez

r? @rust-lang/docs

### CODE REVIEW

**Comment by frewsxcv** [comment]
LGTM. Gonna hold off on doing an r+ to see if others have feedback.

**Comment by SergioBenitez** [comment]
Definitely nicer! My only remaining concern is that long definitions still look quite bad. As an example, see [ContentType::JSON](https://api.rocket.rs/rocket/http/struct.ContentType.html#associatedconstant.JSON). If the definition remains on the same line as the name of the constant, the rendering won't look great.

To ameliorate this, I propose that we adopt one of the following:

  1. Hide the definition entirely on the main page. Clicking on the constant's name leads to a page that shows the full definition as well as the documentation.
  2. Hide the definition by default but allow users to click an "expand" button to see the definition.
  3. Perhaps in conjunction with 2, move the definition to the body of the documentation, where the docstring is shown. Place the definition inside of a shaded `pre` section.

**Comment by GuillaumeGomez** [comment]
I feel a bit off for hiding type and value information by default. In your case, the indent will allow to make the reading easier (which is helped by the new style).

**Comment by steveklabnik** [comment]
Seems good to me too.

**Comment by QuietMisdreavus** [comment]
Not quite a fan, but probably better than nothing. I like @SergioBenitez's suggestion 3, though I'm not sure how rustdoc receives the values of associated consts. It might take some finesse (read: duplicate code) to get it to render through the same pretty-print as a struct's definition.

**Comment by GuillaumeGomez** [comment]
I just thought that moving associated consts in a "category" of their own might be problematic in case this value is only for certain implementation (I think about type parameters specialization).

**Comment by SergioBenitez** [comment]
That's not what I'm proposing, @GuillaumeGomez. Keep the `const` documentation where it is, relatively, but make it look like:

> const **Other**: usize
> 
> ```
> const Other: usize = 12
> ```
> 
> This is the documentation for this item.

A larger example:

> const **Any**: ContentType
> ```
> const Any: ContentType = ContentType{ttype: UncasedAscii{string: Cow::Borrowed("*"),},
>            subtype: UncasedAscii{string: Cow::Borrowed("*"),},
>            params: None,}
> ```
> ContentType representing _any_ Content-Type (`*/*`).

You can play with the formatting and optionally hide the definition by default.

**Comment by GuillaumeGomez** [comment]
Ok, sorry the misunderstanding! This way seems to be quite good indeed. I'll give it a try.

**Comment by GuillaumeGomez** [comment]
Ok, I updated as suggested:

Hidden:

screen shot 2017-02-26 at 18 33 12

Not hidden:

screen shot 2017-02-26 at 18 33 14

By default they're visible.

**Comment by SergioBenitez** [comment]
@GuillaumeGomez I think we still want to know the type in the non-hidden version, right?

**Comment by frewsxcv** [comment]
Looking great @GuillaumeGomez, nice job :)

**Comment by SergioBenitez** [comment]
Actually, if the definition is visible by default, maybe it's okay to not include the type in the hidden version?

**Comment by GuillaumeGomez** [comment]
I'll need to add tests as well.

**Comment by GuillaumeGomez** [comment]
So, I added all missing types in the "correct" output and added tests (and filed an [ICE](https://github.com/rust-lang/rust/issues/40136), so nice of me).

**Comment by steveklabnik** [comment]
@SergioBenitez what do you think?

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rust/pull/40144#issuecomment-283182216

**Comment by alexcrichton** [comment]
@bors: retry

Looks like travis missed this PR...

**Pull request merged**
