### PR TITLE
Use `?` Kleene operator again

### PR DESCRIPTION
**Pull request by mark-i-m**
In https://github.com/rust-lang/rust/pull/51587 I removed a bunch of uses of the `?` Kleene operator. Now `?` is stable, so I am adding them back :tada: 

Unfortunately, the macros had all changed slightly since that PR. In particular, a few of them have extra arms, which I also tried to apply `?` to. I think I got it right, but I would appreciate an extra careful review...

### CODE REVIEW

**Comment by davidtwco** [comment]
> 
> 
> I am getting some test failures locally... are we not using rust 2018 _within the compiler_?

I'm not sure about this, not something I've ever run into. Could you fix the tidy issue so that we can see if the error you're seeing shows up on Travis?

**Comment by petrochenkov** [comment]
The compiler is certainly not using 2018 edition.

**Comment by petrochenkov** [comment]
I still think `?` should be supported on both edition.

**Comment by mark-i-m** [comment]
> I still think ? should be supported on both edition.

That ship has sailed already...

> The compiler is certainly not using 2018 edition.

Interesting... Is that just a matter of running rustfmt and updating x.py? Are there plans to ever do that?

> Could you fix the tidy issue so that we can see if the error you're seeing shows up on Travis?

Sure, when I get to a computer

**Comment by mark-i-m** [comment]
@davidtwco I pushed a tidy fix, but if the compiler is not using rust 2018, then this PR cannot be merged... `?` requires 2018.

**Comment by davidtwco** [comment]
@mark-i-m I'm not too sure. I don't know if this has come up before. One way I could think of doing it, though it is admittedly quick hacky, would be to modify the below code so that the 2018 branch is used if `cfg!(stage0) || cfg!(stage1) || cfg!(stage2)`:

https://github.com/rust-lang/rust/blob/d48ab693d1ce99f30c0cf9abdf45c209824fe825/src/libsyntax/ext/tt/quoted.rs#L437-L448

I feel like that's really awful though. Hopefully someone else knows of a better way than modifying the check to identify the compiler in some way.

**Comment by mark-i-m** [comment]
@davidtwco I could do that, but what I would really like to do is just use rust 2018. Do you know if there is any blocker to just passing --edition 2018 through x.py and running rustfmt?

**Comment by davidtwco** [comment]
@mark-i-m I have no idea. There may be good reasons why that hasn't happened, but maybe not. 🤷‍♂️

**Comment by mark-i-m** [comment]
@davidtwco I played around with this a bit, and it looks like the may challenge is just that rustfix needs to be run on the compiler, which is not something `x.py` can do at the moment. Another problem is that rustfix PRs are likely to be large and messy and might require some tree-locking...

**Pull request closed without merging**
