### PR TITLE
Fix type hint bug in eval_const_expr_partial() (issue #39548)

### PR DESCRIPTION
**Pull request by larsluthman**
When evaluating const expressions for things like array lengths, rustc assumes that the operands in comparison expressions (a < b, a == b, a >= b etc) are booleans and sets their type hints accordingly, causing an incorrect compilation error in the case "(FOO < 4)" with "const FOO: i32 = 3" and a compiler panic in the case "(3 < 4)".

This fix makes sure that rustc does not assume anything about the types of those operands.

### CODE REVIEW

**Review by oli-obk — CHANGES_REQUESTED** [review]
lgtm, but needs a regression test (the snippet from the issue is fine)

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by steveklabnik** [comment]
@bors: retry 

This seems... stuck?

**Comment by alexcrichton** [comment]
@bors: retry

That failure seems... worrisome, but I don't know how it'd be caused by this PR so let's see what happens.

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged #39003

**Comment by alexcrichton** [comment]
@bors: retry

* osx timeout https://github.com/rust-lang/rust/issues/40061

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by alexcrichton** [comment]
@bors: retry 

* network error

**Comment by eddyb** [comment]
@larsluthman That old const-eval is on its last legs, and #40008 makes it eagerly type-checked, *always*, so it fixes the issue "automatically". I've incorporated your testcase, and I'm sorry your fix won't make it.

**Pull request closed without merging**
