### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by matklad**
This updates rust-analyzer submodule to the latest release. 

I plan to do that every Monday after rust-analyzer release (about 16:00 CET).

This is semi-automated by https://github.com/rust-analyzer/rust-analyzer/pull/5253/files#diff-c06f6a9cbd0ad2421bcc2ddc28805457R77-R100. 

Who would be the appropriate person to r? on Mondays?

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
If you have permissions, our current policy is that pure submodule bumps can be self-approved. If you don't have permissions you should post a PR to rust-lang/team granting yourself r+ on this repository (I guess for now on an individual basis, we may want a 'submodule-pushers' marker team or something).

@bors r+

**Comment by matklad** [comment]
I already have r+ perm, yeah!

**Comment by matklad** [comment]
Seems like an unrelated miri failure

**Pull request merged**
