### PR TITLE
Hidden suggestion support

### PR DESCRIPTION
**Pull request by estebank**
Add way to hide suggestion snippet window from cli output to avoid cluttered spans that don't enhance understanding.

r? @pietroalbini CC @zackmdavis

### CODE REVIEW

**Comment by estebank** [comment]
_This hasn't been tested yet_

**Comment by estebank** [comment]
@zackmdavis This PR is to allow @pietroalbini to add a suggestion to remove a few items out of an `use` statement without cluttering the output with secondary spans that don't add much:

```
LL | use foo::{bar, qux};
   |              --^^^ unused import
   |              |
   |              help: remove the import
```

becomes

```
LL | use foo::{bar, qux};
   |                ^^^ unused import
   = help: remove the import
```

**Comment by zackmdavis** [comment]
Looks promising!

**Comment by pietroalbini** [comment]
Assign this to another person, I'm not expert enough of this part of the codebase to review this PR.

**Comment by oli-obk** [comment]
The impl Lgtm but I'm not too happy about merging it without using it

**Comment by estebank** [comment]
@oli-obk It makes sense to wait for #56645 to be merged and then I can rebase and add uses.

**Comment by pietroalbini** [comment]
https://github.com/rust-lang/rust/pull/56645 has been merged.

**Comment by estebank** [comment]
We'll need to update these tests to run rustfix once the rustfix in master can handle these cases, but checking the json output shows that these are correctly exposed. We don't expose the type of suggestion, so tools will _not_ be able to differentiate between the different styles, but I think that is something we can defer on.

**Comment by estebank** [comment]
@oli-obk added one use of these methods, leaving the other methods in because otherwise it feels incomplete.

@pietroalbini please verify that the new output is what you had in mind. VSCode will still provide the same messages as before.

**Comment by pietroalbini** [comment]
> @pietroalbini please verify that the new output is what you had in mind. VSCode will still provide the same messages as before.

Yep, thanks!

**Pull request merged**
