### PR TITLE
add #[track_caller] to slice split_at_mut fn

### LINKED ISSUE #83378: `split_at_mut` should `#[track_caller]`
When `split_at_mut` is called with `mid > len`, an internal assertion fails. However, it doesn't track its caller, so `RUST_BACKTRACE=1` is required to determine the call site.

I tried this code:

```rust
fn main() {
    let mut x = [1];
    
    x.split_at_mut(2);
}
```

#### I expected to see this happen:

An error of the form `thread 'main' panicked at 'split index (is 2) should be <= len (is 1)'`.

#### Instead, this happened:

`thread 'main' panicked at 'assertion failed: mid <= self.len()', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/mod.rs:1279:9`

### Meta
This occurs on stable (1.50.0), beta (1.51.0-beta.8) and nightly (1.53.0-nightly 2021-03-21).

Tested on playground.

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/83378

### CODE REVIEW

**Comment by hi-rustin** [comment]
It looks like many of other methods may also have this issue, do we need to create a new Issue to track and resolve these issues?

**Comment by Dylan-DPC** [comment]
@hi-rustin once https://github.com/rust-lang/rust/pull/83359 is merged i'm planning on targeting the others as well

**Comment by nagisa** [comment]
I don't think rust-timer is a good way to evaluate the performance impact of this. This should be ideally accompanied by some microbenchmark results, I feel.

**Comment by joshtriplett** [comment]
@nagisa It's not perfect, but it helps give an idea of the impact. A similar proposal to add `#[track_caller]` to various `Vec` methods caused a serious performance hit; by contrast, this seems roughly performance-neutral.

**Comment by joshtriplett** [comment]
Hmmm. This seems to have a surprisingly high impact on max-rss in some cases.

**Comment by Mark-Simulacrum** [comment]
max-rss regularly varies up to 15-20% on benchmarks, though we've not pinpointed why, so I think the variation here is just noise.

**Comment by joshtriplett** [comment]
Ah, that's unfortunate; I've seen many people evaluating max-rss figures from rust-timer without knowing about that level of variability.

**Comment by hi-rustin** [comment]
@joshtriplett Can we merge this PR?

https://github.com/rust-lang/rust/pull/83359#issuecomment-812739031 It seems that this max-rss change is acceptable?

**Pull request closed without merging**
