### PR TITLE
Rollup of 3 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #41227, #41240, #41250
- Failed merges:

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors retry

https://github.com/rust-lang/rust/issues/40417

**Comment by arielb1** [comment]
openssl build failed on x86_64-linux:
```
[00:51:17] error: failed to run custom build command for `openssl-sys v0.9.10`

[00:51:17] process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/build/openssl-sys-af1f288687ffbc04/build-script-build` (exit code: 101)

[00:51:17] --- stderr

[00:51:17] thread 'main' panicked at 'OpenSSL library directory does not exist: /checkout/obj/build/x86_64-unknown-linux-gnu/openssl/install/lib', /cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.10/build.rs:55

[00:51:17] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
That's likely https://github.com/rust-lang/rust/pull/41227 at fault, I'll investigate

**Pull request closed without merging**
