### PR TITLE
Revert "Auto merge of #133654 - weihanglo:update-cargo, r=weihanglo"

### PR DESCRIPTION
**Pull request by nikic**
This reverts commit 76f3ff605962d7046bc1537597ceed5e12325f54, reversing changes made to 1fc691e6ddc24506b5234d586a5c084eb767f1ad.

The new pgo_works test fails when rust is built without profiling support, including in CI on x86_64-gnu-aux. See https://github.com/rust-lang/rust/pull/133499#issuecomment-2508901283 for how this happened.

### CODE REVIEW

**Comment by lqd** [comment]
r=me if you don't need a t-cargo approval

**Comment by nikic** [comment]
Don't think we need t-cargo approval as this is just a revert.

@bors r=lqd p=1000

**Comment by RalfJung** [comment]
Assuming this will land, let's make sure the queue can proceed immediately.

@bors treeclosed-

**Pull request merged**
