### PR TITLE
Fix nested eager expansions in arguments of `format_args`

### LINKED ISSUE #63460: Recursive macro call inside concat macro fails to find macros referred to by $crate
```rust
#[macro_export]
macro_rules! separator {
    () => { "/" };
}

#[macro_export]
macro_rules! concat_separator {
    ( $e:literal, $($other:literal),+ ) => {
        concat!($e, $crate::separator!(), $crate::concat_separator!($($other),+))
    };
    ( $e:literal ) => {
        $e
    }
}

fn main() {
    println!("{}", concat_separator!(2, 3, 4))
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5e5eeda6572b99d39911309e18d8f2f8))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0433]: failed to resolve: could not find `separator` in `$crate`
  --> src/main.rs:9:29
   |
9  |         concat!($e, $crate::separator!(), $crate::concat_separator!($($other),+))
   |                             ^^^^^^^^^ could not find `separator` in `$crate`
...
17 |     println!("{}", concat_separator!(2, 3, 4))
   |                    -------------------------- in this macro invocation

error[E0433]: failed to resolve: could not find `concat_separator` in `$crate`
  --> src/main.rs:9:51
   |
9  |         concat!($e, $crate::separator!(), $crate::concat_separator!($($other),+))
   |                                                   ^^^^^^^^^^^^^^^^ could not find `concat_separator` in `$crate`
...
17 |     println!("{}", concat_separator!(2, 3, 4))
   |                    -------------------------- in this macro invocation
```

If either the recursion ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e7e443dabc9692464ecbb07830286ea0)) or the `concat!` is removed ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=305b013ef718cdb15ba3f1a2cad7ea8d)), this compiles exactly as expected. Additionally, if I explicitly name my crate, it works as expected, but would be vulnerable to crate renames in user code (can't reproduce in playground because it doesn't build a library).

### LINKED ISSUE #63685: hygiene: cannot find macro `foo!` in this scope
This code ([playpen]) compiles on stable but not on nightly and beta:
```rust
macro_rules! foo {
    () => {
        "foo"
    };
}

macro_rules! bar {
    () => {
        foo!()
    };
}

fn main() {
    println!(bar!());
}
```

[playpen]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8b3bc98ae358e6ff16fb7dc4003c6233

Standard Error

```rust
   Compiling playground v0.0.1 (/playground)
error: cannot find macro `foo!` in this scope
 --> src/main.rs:9:9
  |
9 |         foo!()
  |         ^^^

warning: unused macro definition
 --> src/main.rs:1:1
  |
1 | / macro_rules! foo {
2 | |     () => {
3 | |         "foo"
4 | |     };
5 | | }
  | |_^
  |
  = note: `#[warn(unused_macros)]` on by default

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Edit**: Removed `concat!` macro

_Originally posted by @lzutao in https://github.com/rust-lang/rust/issues/63460#issuecomment-522294181_

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/63460
Fixes https://github.com/rust-lang/rust/issues/63685 (regression from making `format_args` opaque - https://github.com/rust-lang/rust/pull/63114)

r? @matthewjasper

### CODE REVIEW

**Comment by matthewjasper** [comment]
Can you check if this also fixes #63460, and of so as a test?
r=me with that done

**Comment by lzutao** [comment]
Ping @petrochenkov 
@rustbot modify labels: -S-waiting-on-review S-waiting-on-author

**Comment by petrochenkov** [comment]
Yes, https://github.com/rust-lang/rust/issues/63460 is fixed as well, I've added a test.
@bors r=matthewjasper

**Comment by petrochenkov** [comment]
To the release team:
I'm not entirely sure this can be backported to beta without https://github.com/rust-lang/rust/pull/63535.
I'll try and report.

**Comment by petrochenkov** [comment]
>I'm not entirely sure this can be backported to beta without #63535.

Ok, it seems to work, [here](https://github.com/petrochenkov/rust/commits/betaeger)'s a beta backport (without the renaming commit).

**Comment by nikomatsakis** [comment]
Reviewed by the compiler team:

Accepted for beta backport

**Pull request merged**
