### PR TITLE
FR: impl core::ops::* for F where F: Fn {}

### PR DESCRIPTION
**Pull request by ZaneHannanAU**
Was looking into making closures like

```rust
|x| !x.some_boolean_function()
```

or

```rust
|x| -x.some_numeric_function()
```

into more simple manners by way of some closing structure; namely

```rust
!Structure::some_boolean_function
```

or

```rust
-Structure::some_numeric_function
```

for something like

```rust
let s: String = vec!["hi ", "there ", "friend", "", "."].into_iter().filter(!String::is_empty).collect();
```

or

```rust
let neg = ::std::iter::successors(Some(1_i128), -|x| x.checked_mul(2));
```

or similar.

Was hoping to figure it out with a simple one but... as it can be seen it takes some work and is not very nice to read through.

`Neg` may be something to reconsider in this case...

### CODE REVIEW

**Comment by the8472** [comment]
If it works do you intend to extend it to other ops? That would get us closer to predicates looking similar to if expressions (examples in https://github.com/rust-lang/rust/issues/65669#issuecomment-545102403)

**Comment by ZaneHannanAU** [comment]
Yes

**Comment by ZaneHannanAU** [comment]
Will aim to implement all bitwise boolean (not, or, and, xor) operators, but currently need to get compiler to listen... which may be more difficult than I expect.

**Comment by the8472** [comment]
If you want to iterate faster than CI does but can't compile the whole of rustc on your machine you can start a normal rust project, copy-paste some Op trait and then implement that an Fn trait (you'll have to call it as normal function instead using operator syntax). Once that works you can wrap it into a macro.

**Comment by alexcrichton** [comment]
Thanks for the PR!

I think this is a relatively major feature though and probably want some discussion before proposing it with a PR. Has there perhaps been an internals thread, an issue, or an RFC discussing this?

**Comment by ZaneHannanAU** [comment]
@alexcrichton not quite an issue, on it specifically, but #65669 has some discussion and eventually talks about it.

**Comment by alexcrichton** [comment]
Ok I think it would be best for a feature like this to have its own dedicated thread somewhere rather than being buried in an existing issue.

**Comment by Dylan-DPC** [comment]
@ZaneHannanAU any updates?

**Comment by ZaneHannanAU** [comment]
Sadly no. I don't think I have the knowledge to implement it at this stage.

**Pull request closed without merging**
