### PR TITLE
[Experiment] Remove format_args_nl!()

### PR DESCRIPTION
**Pull request by m-ou-se**
This experiment removes `format_args_nl!(…)`, replacing it with `format_args!("{}\n", format_args!(…))`. ~~This will result in a performance regression, but I'm curious how significant it is.~~ _Edit: No performance impact, actually!_

(This does break a bunch of diagnostics and (clippy) lints, so this is not mergable.)

### CODE REVIEW

**Comment by m-ou-se** [comment]
Huh. Okay, that's cool.

**Comment by Dylan-DPC** [comment]
Closing this as it was an experiment.

**Comment by cramertj** [comment]
@m-ou-se Is there a reason why this wasn't merged? It looks like `format_args_nl` died out in https://github.com/rust-lang/rust/pull/97658.

**Comment by m-ou-se** [comment]
@cramertj If I remember correctly, changing `format_args_nl!(…)` to `format_args!("{}\n", format_args!(…))` made some diagnostics / (clippy) lints harder to implement. It's been a while though, so I don't remember the details.

**Pull request closed without merging**
