### PR TITLE
Add macro lifetime specifier

### LINKED ISSUE #23956: Can't use externally defined lifetimes in macros due to hygiene
I've tried using `ty`, `expr`, `tt` and `ident` fragments but nothing works.

Macros should have a lifetime fragment type (`$foo:lifetime`). It's currently a rather annoying hole in `macro_rules!` usability.

### PR DESCRIPTION
**Pull request by Diggsey**
Allows accepting a lifetime as a parameter to a macro.

Fixes #23956

### CODE REVIEW

**Comment by alexcrichton** [comment]
One point of possible worry is that `lifetime` is perhaps slated to become a keyword one day in accordance with the associated types RFC, it just has yet to be implemented.

**Comment by Diggsey** [comment]
I renamed it to use "life" instead of "lifetime" to avoid the conflict.

**Comment by Stebalien** [comment]
Bump?

**Comment by huonw** [comment]
Hm, I think this needs a few more pairs of eyes.

**Comment by nikomatsakis** [comment]
Seems like an RFC would make sense to work out naming etc. But also, this should be feature-gated.

**Comment by nikomatsakis** [comment]
During lang subteam mtg, we decided this should have an RFC, since it is a language extension, albeit a minor one. Removing nomination since we've taken a look (no priority needed).

**Comment by steveklabnik** [comment]
@Diggsey any interest in pursuing an RFC for this, like @nikomatsakis suggested?

**Comment by durka** [comment]
I'd be interested in helping with an RFC for this.

**Comment by durka** [comment]
It occurs to me that adding a fragment specifier for lifetimes doesn't actually fix significant situations where you might want to parse a lifetime specifier, for example in a list of generic parameters. In such a situation you would have to differentiate a lifetime specifier from an identifier, and in general [a macro can't alternate on one fragment specifier vs another](http://is.gd/enusNf), unless this is actually a bug (cf #27832).

A design which could allow such alternation is not a new fragment specifier, but a (hopefully minor) modification to the lexer to allow `'$` to parse. Then you could have a macro [like this](http://is.gd/4yA3nu), using the apostrophe to differentiate. On the other hand this might be a terrible idea. Thoughts?

**Comment by alexcrichton** [comment]
Closing due to inactivity (and sounds like an RFC is desired)

**Pull request closed without merging**
