### PR TITLE
Rev::rposition counts from the wrong end

### PR DESCRIPTION
**Pull request by sfanxiang**
Introduced in #43074.

cc @SimonSapin

### CODE REVIEW

**Comment by timvermeulen** [comment]
>`self.iter.position(predicate).map(|i| self.len() - i - 1)`

I think this won't work because `self.len()` is called after `self.iter.position` is called, so it's no longer the original length – you would have to call `self.len()` first. Alternatively, I think you could also return just `self.len()` from the closure as `self.iter.position` will have shortened the iterator by exactly `i + 1` elements already.

I have no idea why the build is failing though 😕

**Comment by timvermeulen** [comment]
It seems like adding the `Self: ExactSizeIterator` bound makes the compiler no longer realize that `Self::Item` and `I::Item` are the same, for whatever reason 🤔

**Comment by sfanxiang** [comment]
I wonder why this is happening too, if the original code builds fine.

**Comment by timvermeulen** [comment]
The original code doesn't have the `Self: ExactSizeIterator` bound (the default implementation does, but not the incorrect implementation of `Rev` itself) so that has to be the cause.

**Comment by sfanxiang** [comment]
I'm totally confused. Where does `i32` come from? :thinking:

**Comment by Alexendoo** [comment]
Ping from triage, @scottmcm any ideas what's causing that type inference issue?

**Comment by sfanxiang** [comment]
@scottmcm Removed `Rev::rposition` for now due to compile error. Could you please review?

And what's the performance gain of specializing `rposition` anyway? It will always have to iterate over the values passed to `predicate`, starting from `next_back()`.

**Comment by timvermeulen** [comment]
>And what's the performance gain of specializing `rposition` anyway?

I think that was only useful before the `try_fold` days (since repeated `next` calls don't use internal iteration and `fold` doesn't short-circuit).

**Comment by scottmcm** [comment]
It could theoretically matter if the underlying iterator had some special implementation (like if there was a `memchr-iterator` or something), but it's definitely far less useful in the current `try_rfold` world.  So just removing it and fixing the bug with usually no cost sounds like a good approach to me.

@bors r+ rollup

**Pull request merged**
