### PR TITLE
Impl From<Ipv4Addr, Ipv6Addr> for IpAddr.

### PR DESCRIPTION
**Pull request by Yamakaky**
Fixes https://github.com/rust-lang/rfcs/issues/1816.

### CODE REVIEW

**Comment by clarcharr** [comment]
Hey @Yamakaky, could you add a #[stable(…)] attribute to these and rebase? I think that this would make the PR mergeable.

**Comment by Yamakaky** [comment]
Should I put `feature = "rust1"`?

**Comment by clarcharr** [comment]
I'd do `#[stable(feature = "ip_from_ip", since = "1.15.0")]`.

**Comment by Yamakaky** [comment]
Done. I also added the same implementation for SocketAddr.

**Comment by alexcrichton** [comment]
Sorry for the delay @Yamakaky! At this point this'll actually land in 1.16.0 I believe, so could this be updated to that release instead? Otherwise this looks great to me, so I'll...

@rfcbot fcp merge

**Comment by Yamakaky** [comment]
Done

**Pull request merged**
