### PR TITLE
Overhaul `ThinVec` usage

### PR DESCRIPTION
**Pull request by nnethercote**
r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
> rustc exited with signal: 4 (SIGILL) (core dumped)

SIGILL?!

This PR introduces the use of the external `thin_vec` crate, and I had a different crash (seg fault) in it earlier today. That was caused by calling `ThinVec::set_len` on an empty `ThinVec`. I worked around that, and things were running fine on my machine. But now we have this crash on CI, which occurs as soon as the newly built compiler starts being used to compile `std`. Which suggests something being fairly badly broken.

Uncontrolled crashes are incredibly rare in rustc in my experience, and `ThinVec` has lots of unsafe code, so I'm going to assume this crash is also due to `ThinVec` somehow. Though how a SIGILL might be triggered, I don't know.

**Comment by nnethercote** [comment]
Hmm. Because I was suspicious about `ThinVec` I pushed #100668, which has the parts of the PR prior to the introduction of the external `thin_vec` crate. And it's crashing with SIGILL on CI as well. So it must be something else.

**Comment by 5225225** [comment]
Yep, it looks to be a debug assertion being tripped.

```rust
stack backtrace:
   0: rust_begin_unwind
             at ./library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./library/core/src/panicking.rs:142:14
   2: <alloc::vec::Vec<rustc_ast::ptr::P<rustc_ast::ast::Expr>> as rustc_data_structures::map_in_place::MapInPlace<rustc_ast::ptr::P<rustc_ast::ast::Expr>>>::flat_map_in_place::<rustc_ast::mut_visit::visit_exprs<rustc_expand::expand::InvocationCollector>::{closure#0}, core::option::Option<rustc_ast::ptr::P<rustc_ast::ast::Expr>>>
   3: <rustc_ast::ast::Crate as rustc_expand::expand::InvocationCollectorNode>::noop_visit::<rustc_expand::expand::InvocationCollector>
             at ./compiler/rustc_expand/src/expand.rs:1371:9
   4: <rustc_expand::expand::InvocationCollector>::visit_node::<rustc_ast::ast::Crate>::{closure#2}
             at ./compiler/rustc_expand/src/expand.rs:1737:61
   5: <rustc_expand::expand::InvocationCollector>::visit_node::<rustc_ast::ast::Crate>
             at ./compiler/rustc_expand/src/expand.rs:1737:21
   6: <rustc_expand::expand::MacroExpander>::collect_invocations
             at ./compiler/rustc_expand/src/expand.rs:557:13
   7: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             at ./compiler/rustc_expand/src/expand.rs:392:13
   8: <rustc_expand::expand::MacroExpander>::expand_crate
             at ./compiler/rustc_expand/src/expand.rs:379:21
   9: rustc_interface::passes::configure_and_expand::{closure#1}::{closure#1}
             at ./compiler/rustc_interface/src/passes.rs:336:50
  10: <rustc_data_structures::profiling::VerboseTimingGuard>::run::<rustc_ast::ast::Crate, rustc_interface::passes::configure_and_expand::{closure#1}::{closure#1}>
             at ./compiler/rustc_data_structures/src/profiling.rs:739:9
  11: <rustc_session::session::Session>::time::<rustc_ast::ast::Crate, rustc_interface::passes::configure_and_expand::{closure#1}::{closure#1}>
             at ./compiler/rustc_session/src/utils.rs:10:9
  12: rustc_interface::passes::configure_and_expand::{closure#1}
             at ./compiler/rustc_interface/src/passes.rs:336:21
  13: <rustc_data_structures::profiling::VerboseTimingGuard>::run::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>, rustc_interface::passes::configure_and_expand::{closure#1}>
             at ./compiler/rustc_data_structures/src/profiling.rs:739:9
  14: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>, rustc_interface::passes::configure_and_expand::{closure#1}>
             at ./compiler/rustc_session/src/utils.rs:10:9
  15: rustc_interface::passes::configure_and_expand
             at ./compiler/rustc_interface/src/passes.rs:288:13
  16: <rustc_interface::queries::Queries>::expansion::{closure#0}::{closure#0}
             at ./compiler/rustc_interface/src/queries.rs:181:17
  17: <rustc_interface::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface::queries::Queries>::expansion::{closure#0}::{closure#0}, core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>>
             at ./compiler/rustc_interface/src/passes.rs:132:13
  18: <rustc_interface::queries::Queries>::expansion::{closure#0}
             at ./compiler/rustc_interface/src/queries.rs:180:25
  19: <rustc_interface::queries::Query<(alloc::rc::Rc<rustc_ast::ast::Crate>, alloc::rc::Rc<core::cell::RefCell<rustc_interface::passes::boxed_resolver::BoxedResolver>>, alloc::rc::Rc<rustc_lint::context::LintStore>)>>::compute::<<rustc_interface::queries::Queries>::expansion::{closure#0}>
             at ./compiler/rustc_interface/src/queries.rs:37:28
  20: <rustc_interface::queries::Queries>::expansion
             at ./compiler/rustc_interface/src/queries.rs:169:9
  21: rustc_driver::run_compiler::{closure#1}::{closure#2}
             at ./compiler/rustc_driver/src/lib.rs:358:13
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
             at ./compiler/rustc_interface/src/queries.rs:381:19
  23: rustc_driver::run_compiler::{closure#1}
             at ./compiler/rustc_driver/src/lib.rs:309:22
  24: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}
             at ./compiler/rustc_interface/src/interface.rs:323:13
  25: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
             at ./compiler/rustc_span/src/lib.rs:986:5
  26: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
             at ./compiler/rustc_interface/src/interface.rs:317:5
  27: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}
             at ./compiler/rustc_interface/src/interface.rs:339:12
  28: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  29: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}>
             at ./compiler/rustc_span/src/lib.rs:112:5
  30: rustc_interface::util::run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}
             at ./compiler/rustc_interface/src/util.rs:159:32
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is on 26873fedff6b77b9233a5437b67da4bfd0756e26

**Comment by nnethercote** [comment]
@5225225: thanks for the info! So I would need to enable debug assertions locally to see the SIGILL? You got a backtrace when you ran it locally. Is there a reason why the crash on CI has so little information?

**Comment by 5225225** [comment]
I edited the debug assertions to be a panic instead of an abort, and then used `RUST_BACKTRACE=1`.

See: https://github.com/rust-lang/rust/blob/86c6ebee8fa0a5ad1e18e375113b06bd2849b634/library/core/src/intrinsics.rs#L2120-L2136

You want to make that `::core::intrinsics::abort` into `panic!("oh no");` or something. That'll at least give you a backtrace.

**Comment by 5225225** [comment]
I've done some more debugging work, and it's a slice get_unchecked (using usize as an index) where the index is 0, and the slice length is 0.

I *highly* suspect the changes to `compiler/rustc_data_structures/src/map_in_place.rs`. Notably, we changed pointer arithmetic to a `get_unchecked`.

**Comment by 5225225** [comment]
Right. I think I know why now.

It's the get_unchecked. We're setting the length to 0, but that means you *can't use .get_unchecked* or it's UB.

the set_len is correct, but you have to *keep* the pointer arithmetic. (To be polite, you could debug_assert that your pointer arithmetic offset is `<` `old_len`)

**Comment by nnethercote** [comment]
> It's the get_unchecked. We're setting the length to 0, but that means you _can't use .get_unchecked_ or it's UB.

Oh, I understand what happened. Earlier in the year I wrote some code that moved `flat_map_in_place` into a macro, but I never merged it. Some time later, these `get_unchecked` checks were added, and `flat_map_in_place` was updated to avoid using `get_unchecked`. Then yesterday I resurrected my old code, not noticing that `flat_map_in_place` had changed, thus reinserting the `get_unchecked` calls. My fault for not comparing more closely my old code vs. the current code.

Thanks again for the assistance, @5225225!

**Comment by apiraino** [comment]
@nnethercote you have this under control, correct? (just checking PRs without review activity for a while)
thanks!

**Comment by nnethercote** [comment]
I have several overlapping PRs that are all trying to reduce AST node sizes, coming from different angles, e.g. #101562, #101885, #102000. Those other ones are more fundamental, so I'll close this one.

**Pull request closed without merging**
