### PR TITLE
Enable MIR inlining for generators too

### PR DESCRIPTION
**Pull request by cjgillot**
This is a tentative to enable MIR inlining on generators too.

This PR proceeds in 2 steps:
1. the generator information is separated from the MIR body itself, to be computed using two separate queries: `mir_generator_lowered` and `mir_generator_info`;
2. we perform inlining on the generator body (`generator_resume` function).

This PR took the opportunity to simplify the generated `generator_drop` code, since it won't be optimized on its own.

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? compiler

**Comment by fee1-dead** [comment]
r? rust-lang/compiler

**Comment by cjgillot** [comment]
The issue with `deeply-nested-multi` benchmark is only a recursion limit issue.

**Comment by cjgillot** [comment]
From perf results, this does not seem to be worth it.

**Comment by JakobDegen** [comment]
I agree that we should maybe not be turning this on right now, but I'd also caution against just using perf results here.  Compile time perf is not the same as runtime perf, and also in general this will enable other optimizations that we may take advantage of in the future. I expect that we will want to revive this PR at some point.

**Comment by wesleywiser** [comment]
Agreed, I think there might be code quality reasons to enable this in the future. I do wonder though if inlining into generators is what we want. It seems plausible to me that keeping the generator code as small as possible might enable better inlining of the generator into its callsite which could also be beneficial to runtime performance.

**Comment by JakobDegen** [comment]
Hmm, what makes you think that generators are more affected by this than any other function?

**Pull request closed without merging**
