### PR TITLE
Support endianness mark in test case check files

### PR DESCRIPTION
**Pull request by ecnelises**
Add new endianness mark ('big' or 'little') into stderr file suffixes, which helps when memory layout dumps in error messages are different.

### CODE REVIEW

**Comment by jyn514** [comment]
Do we *have* any supported big-endian platforms? This seems like an expansion of scope for compiletest, and I don't think it makes sense to maintain all this new code if we're never testing it.

**Comment by ecnelises** [comment]
> Do we _have_ any supported big-endian platforms? This seems like an expansion of scope for compiletest, and I don't think it makes sense to maintain all this new code if we're never testing it.

Per [platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html), Tier-2 targets with following arch name should be big-endian, some of them have host tools:

- powerpc
- powerpc64
- mips
- mips64
- s390x
- armebv7r
- sparc64
- sparcv9

But I guess they're not tested very often. Because what #103231 fixes is also a bug only at big-endian and after months no one raised. I found this issue when testing local build on `powerpc64-ibm-aix` (the work #102293 is in progress).

**Comment by jyn514** [comment]
Ok. Given that I am not comfortable unilaterally approving this change. You can suggest it in t-infra: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra
which has meetings every week on Monday at 15:00 UTC.

**Comment by michaelwoerister** [comment]
I think it would be clearer if it was `be`/`le` instead of `big`/`little`. Or even `big_endian`/`little_endian`.

**Comment by Mark-Simulacrum** [comment]
This was discussed in the T-compiler meeting -- opinions varied pretty widely, but it seems like there was general agreement with a plan to try to add some testing in CI for a big-endian platform prior to landing tests that would otherwise error. I'll take a look at how to best do that but for now assigning to myself as reviewer.

**Comment by Mark-Simulacrum** [comment]
Hi @ecnelises, apologies for the slow response time here. I've pushed up a couple of commits which add a new CI builder running the UI test suite in check-only mode targeting powerpc64-unknown-linux-gnu. This should validate that the 64-bit big endian tests are up to date, which should largely address the problem here.

It doesn't cover 16 or 32-bit big-endian -- if you wanted to add powerpc-unknown-linux-gnu to the builder that would probably be relatively easy, but I think in practice we may want to not generate the full cross-product of (16,32,64)-bit x (little, big) endian -- just covering one big endian target is probably enough.

r? @jyn514 on the CI builder aspect

**Review by jyn514 — APPROVED** [review]
not super familiar with this part of the dockerfiles, but everything here looks reasonable. r=me when you get CI passing

**Comment by RalfJung** [comment]
I think this PR is problematic, since it means next time someone does something that changes the expected output for the affected files, they won't be able to `--bless` the reference files. Basically nobody has a big-endian machine so one can't just use `x.py test --bless --target something-big-endian`. And even if one does have access to a big-endian machine, now we have up to 4 different targets that need to be covered before the reference files are all up-to-date again. This is a lot worse than the 32bit/64bit situation, which is already annoying enough.

I think we should only land this once we have a bot that can auto-bless these files for all targets.

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval (since I though the people in this WG are among the most affected by this change)

**Comment by RalfJung** [comment]
I think some of the strategies proposed in https://github.com/rust-lang/rust/pull/106047 are preferable, since they avoid creating a lot of work for other people:
- add heavily normalization to the const-eval tests so that the raw byte dumps are basically removed, and no longer cause endianess differences
- add a new test that only runs on little-endian targets that does *not* have the normalization and tests the raw byte dumps (using tests from the existing files, the examples will currently be spread across multiple files and should be collected by hand)

**Comment by jyn514** [comment]
@RalfJung is it possible to change the tests so that they dump the values of the constants instead of the raw memory? That should avoid differences between little- and big-endian platforms, right?

**Comment by RalfJung** [comment]
I just answered that same question in https://github.com/rust-lang/rust/pull/102379#issuecomment-1363344771. We have at least 3 big-endian-related PRs open currently and that's terrible because I have to keep answering the same questions in each of them.^^

**Comment by Mark-Simulacrum** [comment]
> I think we should only land this once we have a bot that can auto-bless these files for all targets. This affects quite a few of the const-eval files that I have to bless fairly regularly, and from what I can tell, this PR as-is would make my life super difficult.

Seems like a reasonable objection and minimum goal. It should be relatively achievable, but may not happen particularly quickly.

Do you think it's necessary for this to be faster than a full bors run (i.e., part of PR CI?)

**Comment by RalfJung** [comment]
For the sake of keeping the queue moving, it sounds pretty bad if blessing needs a full bors cycle?

**Comment by jyn514** [comment]
@RalfJung that's already the case today for 32-bit targets, no?

**Comment by RalfJung** [comment]
It is much easier to run a 32bit target on a 64bit host than it is to run a big endian target on a little endian host. So with the 32bit files I would say things are annoying but acceptable.

**Comment by uweigand** [comment]
FYI, the alternate solution https://github.com/rust-lang/rust/pull/106047 and https://github.com/rust-lang/rust/pull/106046 has now been merged, so the Rust test suite is currently clean on big-endian targets (at least on s390x).

**Comment by apiraino** [comment]
I think I can safely remove `T-compiler` from the review queue here. pls let me know if instead they need to check stuff here, thanks!

@rustbot label -T-compiler

**Comment by RalfJung** [comment]
> FYI, the alternate solution #106047 and #106046 has now been merged, so the Rust test suite is currently clean on big-endian targets (at least on s390x).

IMO we should close this PR, for the [reasons stated above](https://github.com/rust-lang/rust/pull/104135#issuecomment-1363353764).

**Comment by Mark-Simulacrum** [comment]
Closing for now per https://github.com/rust-lang/rust/pull/104135#issuecomment-1363353764.

**Pull request closed without merging**
