### PR TITLE
Implement unstable ffi_return_twice attribute

### PR DESCRIPTION
**Pull request by gnzlbg**
This PR implements [RFC2633](https://github.com/rust-lang/rfcs/pull/2633)

r? @eddyb

### CODE REVIEW

**Comment by gnzlbg** [comment]
I'd prefer to enable this only for `extern` functions. Is there an easy way to error if this attribute is applied to something else?

**Comment by rkruppe** [comment]
Code LGTM. Does anyone have a strong opinion on whether to merge this now or wait how the RFC plays out?

**Comment by eddyb** [comment]
cc @RalfJung

**Comment by alexcrichton** [comment]
r=me on the technical side of things, so for language/rfc/whatnot

r? @RalfJung

**Comment by RalfJung** [comment]
Uh, sorry, I don't have any skin in this. It's all FFI stuff, which I know little about, and from my understanding it's mostly about taming LLVM's optimizer, which I know even less about.

**Comment by RalfJung** [comment]
Oh, and don't we usually wait until the RFC gets accepted before implementing it? Like, what if we land this and then the RFC gets rejected?

**Comment by gnzlbg** [comment]
> Like, what if we land this and then the RFC gets rejected?

We remove the feature and call it a day. AFAICT many unstable features are implemented all the time without nobody ever talking about actually RFCing the stuff. I want to use this in stable Rust at some point, so for that it definitely needs to go properly through the process.

**Comment by RalfJung** [comment]
*shrug*

@bors r=alexcrichton

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/58664#issuecomment-466598762, @bors r-

**Comment by gnzlbg** [comment]
I guess another PR in the rollup also added the same error code? Or how did tidy fail there but not here?

**Comment by gnzlbg** [comment]
@Centril all checks passed, can we give this another try?

**Comment by Hezuikn** [comment]
> I'd prefer to enable this only for extern functions. Is there an easy way to error if this attribute is applied to something else?

why?

**Pull request merged**
