### PR TITLE
Add extended information for E0594

### PR DESCRIPTION
**Pull request by twe4ked**
Thanks!

r? @steveklabnik

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
You need to update tests as well.

**Comment by twe4ked** [comment]
Is there a good way to run just the failing doc specs (or at least a smaller number of them)?

**Comment by tanriol** [comment]
E0594 is not specific to statics ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bc82e810474d4bb409d0f078e12521ef) producing it without any statics).

**Comment by twe4ked** [comment]
Yeah you're right Denis. This definitely needs work, I might have a bit more of a play and see if I can work out a better way to write this–it may be out of my level of knowledge though. If I don't get to it soon I'll close the PR.

**Comment by Dylan-DPC** [comment]
ping from triage @twe4ked any updates on this?

**Comment by twe4ked** [comment]
Thanks for the ping. I'm not really sure where to take it from here and I know now that there is potentially bunch of information looking. Sorry!

**Pull request closed without merging**
