### PR TITLE
Derive Copy for std::ops::Range and RangeFrom

### PR DESCRIPTION
**Pull request by SimonSapin**
`RangeTo` and `RangeFull` already have it.

### CODE REVIEW

**Comment by eddyb** [comment]
These don't have it because they're iterators.
The choice of removing `Copy` impls instead of adjusted `for` loop desugaring or linting was made, to prevent this problematic case:
```rust
let mut iter = 0..n;
for i in iter { if i > 2 { break; } }
iter.collect()
```
Here `iter` is actually not mutated, but copied. `for i in &mut iter` is required to mutate the iterator.
We could switch to linting against using an iterator variable after it was copied by a `for` loop, but no decision has been made yet.

**Comment by SimonSapin** [comment]
Ok, so there was a reason.

“The choice […] was made” seems to contradict “no decision has been made yet.” If the decision against implementing `Copy` is made/confirmed, feel free to close this.

**Comment by alexcrichton** [comment]
Yeah we've [decided in the past](https://github.com/rust-lang/rust/pull/21846#issuecomment-110526401) to not take this, so I'm going to close this for now.

**Comment by eddyb** [comment]
@SimonSapin original phrasing was a bit off. What I meant to say was that no decision has been made for switching to linting (which my personal preference).

**Comment by sanmai-NL** [comment]
I favor a lint, since this code pattern is now not possible: 
```rust
let three_times = 0_u32..3_u32;
for _ in three_times {
    ...
}
for _ in three_times {
    ...
}
```

**Pull request closed without merging**
