### PR TITLE
Add const examples

### PR DESCRIPTION
**Pull request by steveklabnik**
I only added them to `std::f32` to get feedback on this approach before adding the other constants.

When looking at https://github.com/rust-lang/rust/pull/68952, I found the docs a little confusing. Unless you're intimately aware of what's going on here, I don't think it's super clear what is deprecated and what you're supposed to do instead. I think short examples really clarify what's meant here, so that's what I did.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Thanks, I agree it wasn't clear before.

I might suggest "intended way" instead of "correct way" because the difference isn't in correctness, just in what we'd like for people to write.

**Comment by steveklabnik** [comment]
> I might suggest "intended way" instead of "correct way" because the difference isn't in correctness, just in what we'd like for people to write.

I love it; I felt weird writing it out but couldn't come up with something better.

I will make that change and add the other examples either tonight or tomorrow.

**Comment by steveklabnik** [comment]
This should be ready for review; I'm building a copy of the docs locally to make sure that those int macros expand the way I think they should, and I believe I've fixed tidy.

**Review by dtolnay — APPROVED** [review]
Thank you Steve.

**Comment by steveklabnik** [comment]
image

**Pull request merged**
