### PR TITLE
rustdoc: add missing URL redirect

### PR DESCRIPTION
**Pull request by weihanglo**
https://github.com/rust-lang/rust/pull/94753 missed some redirect settings, and one of the missing URL shows up in an error message. This PR adds those redirects.

### CODE REVIEW

**Comment by jyn514** [comment]
The error message is versioned, no? So this will only fix beta/nightly, not any earlier version. I think we should change the link rustdoc emits to point to the new URL, rather than adding a redirect.

**Comment by weihanglo** [comment]
>  I think we should change the link rustdoc emits to point to the new URL

It is done with https://github.com/rust-lang/rust/pull/103588/commits/06692ea4441b168b279ec6fbdd8311d0444cbc4c, no? 
(Sorry I am entirely not familiar with rustdoc internals)

> rather than adding a redirect

Hmm… Maybe outside rustdoc, someone wrote a blogpost linking to an old URL with no version specified. These redirects helps I believe.

**Comment by jyn514** [comment]
> It is done with [06692ea](https://github.com/rust-lang/rust/commit/06692ea4441b168b279ec6fbdd8311d0444cbc4c), no?

I missed that, thanks. Yes, that's the solution I would expect.

> Hmm… Maybe outside rustdoc, someone wrote a blogpost linking to an old URL with no version specified. These redirects helps I believe.

:+1: seems reasonable, but personally I don't think it's important enough to backport @notriddle. It's low risk though so no strong objection from me.

**Comment by apiraino** [comment]
backport approved!

@rustbot label +beta-accepted

**Pull request merged**
