### PR TITLE
Update E0520 to new error format

### LINKED ISSUE #36112: E0520 needs to be updated to new format
From: src/test/compile-fail/E0520.rs

E0520 needs a span_label, a span_note converted to a span_label, a note, and a new title, updating it from:

```
error[E0520]: item `fly` is provided by an `impl` that specializes another, but the item in the parent `impl` is not marked `default` and so it cannot be specialized.
  --> src/test/compile-fail/E0520.rs:26:5
   |
26 |     default fn fly(&self) {} //~ ERROR E0520
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: parent implementation is here:
  --> src/test/compile-fail/E0520.rs:21:1
   |
21 | impl<T: Clone> SpaceLlama for T {
   | ^
```

To:

```
error[E0520]:  `fly` specializes an item from a parent impl, but neither that item nor the impl are marked default 
  --> src/test/compile-fail/E0520.rs:26:5
   |
21 | impl<T: Clone> SpaceLlama for T {
   | - parent `impl` is here
...
26 |     default fn fly(&self) {} //~ ERROR E0520
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ cannot specialize default item `fly`
   |
   = note: to specialize, either the parent `impl` or `fly` in the parent `impl` must be marked `default`
```

### PR DESCRIPTION
**Pull request by 0xmohit**
Fixes #36112.
Part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by TimNN** [comment]
It looks like you have a tidy failure:

```
/build/src/test/compile-fail/E0520.rs:30: line longer than 100 chars
```

**Comment by 0xmohit** [comment]
Thanks, @TimNN.  Should be fixed now.

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by 0xmohit** [comment]
The [following](https://travis-ci.org/rust-lang/rust/builds/156246093#L6931) appears unrelated:

```
test [run-pass] run-pass/issue-36023.rs ... FAILED
```

**Comment by TimNN** [comment]
Yes, thats a known travis failure.

**Pull request merged**
