### PR TITLE
Tweak may_dangle syntax for MCP 563

### PR DESCRIPTION
**Pull request by SoniEx2**
(don't mind us just using CI for development)

### CODE REVIEW

**Comment by SoniEx2** [comment]
oh. does CI run on drafts...? we thought it didn't?

but yes, noted about the `r?`, sorry >.<

**Comment by SoniEx2** [comment]
hmm, actually unsure how to proceed. gonna wait for a fix for #107231 and see what we can do from there.

**Comment by clubby789** [comment]
This could be fixed without changing attribute validation globally, the `used` attribute denies other words like this:
https://github.com/rust-lang/rust/blob/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/compiler/rustc_codegen_ssa/src/codegen_attrs.rs#L153-L182

**Comment by JohnCSimon** [comment]
@SoniEx2 
ping from triage - what is the status of this PR?

FYI: when a PR is ready for review, please send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by SoniEx2** [comment]
we aren't entirely sure how to do this. also waiting for feedback on rust-lang/rfcs#3390 because that happened.

**Pull request closed without merging**
