### PR TITLE
Don't call `Symbol::as_str` twice in `integer_lit`

### PR DESCRIPTION
**Pull request by DaniPopes**
When parsing integer literals, `Symbol::as_str` gets called twice because the first `as_str` result in `strip_underscore` gets discarded.

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I don't really see why this is a material improvement to the code. Is there data that shows that `Symbol::as_str` is expensive enough to warrant this?

**Comment by DaniPopes** [comment]
I measured it locally with a different compiler I am developing which uses similar logic as rustc, and it's about 0.5-1% improvement on instruction count and L1/L2 accesses during parsing, depending of course on number of literals.

The [`as_str` docs](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/symbol/struct.Symbol.html#method.as_str) do mention:
> This is a slowish operation because it requires locking the symbol interner.

And as far as I can tell it's a thread local, mutex lock, and hashmap lookup that we can avoid for free on a decently hot function.

Might be worth requesting a perf run.

**Comment by compiler-errors** [comment]
Thanks much for the contribution, but given that this doesn't seem to improve the performance of the compiler and makes the code harder to reason about, I don't think that this PR is worth merging.

**Pull request closed without merging**
