### PR TITLE
Miri: make size/align_of_val work for dangling raw ptrs

### PR DESCRIPTION
**Pull request by RalfJung**
This is needed for https://github.com/rust-lang/rust/issues/80365#issuecomment-752128105.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Is this testable within this repo or do we need miri for it?

r=me with a test if possible

**Comment by RalfJung** [comment]
Good point, I added a test.

@bors r=oli-obk

**Comment by matthieu-m** [comment]
Is that a guarantee that we will want to make going forward?

I tried to create a `*const dyn Debug` from a `*const DynamicallySized<[usize]>` and failed (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=427a8368a8f15cc3e6907420ca260084)) as apparently it's not possible to create a pointer to trait from a pointer to DST right now.

It's unclear whether this is a restriction that will stay, or not. If it doesn't, however, then `size_of_val_raw` may, on certain types, require accessing the _data-pointer_ of the trait.

As such, it seems that if we wish to keep our options open regarding the conversion from DST to trait, then we should enforce that `size_of_val_raw` require a valid data-pointer.

**Comment by RalfJung** [comment]
> Is that a guarantee that we will want to make going forward?

The guarantee is what is [documented](https://doc.rust-lang.org/nightly/std/mem/fn.size_of_val_raw.html) for `align_of_val_raw_`/`size_of_val_raw`. In particular, for *sized* types, the pointers may dangle. So what Miri did previously was definitely wrong.

I think Miri also implements the rest of those docs correctly, but if there's a bug, please let me know. Note the last clause in the documentation:

> otherwise, it is conservatively not allowed to call this function.

Currently, this is impossible to reach (there are no other kinds of DST), but that is not a stable assumptions -- so if one has *no clue* what the unsized tail is, one has to use `size_of_val` still.

**Pull request merged**
