### PR TITLE
Remove unnecessary `main` functions in doc examples.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Having the `main` function allows sometimes to avoid some bad automatic test wrapping. If travis says ok, then it's all good but just in case I prefer wait and see.

**Comment by frewsxcv** [comment]
Travis already finished for this.

**Comment by frewsxcv** [comment]
For the record, `use` and `extern` can be used inside functions, so they aren't going to be extracted out of the generated `main`.

**Comment by GuillaumeGomez** [comment]
Normally yes but sometimes we have weird behaviors. Anyway, travis is happy so I am!

@bors: r+ rollup

**Pull request merged**
