### PR TITLE
Dogfood more or_patterns in the compiler

### PR DESCRIPTION
**Pull request by cuviper**
Another step toward the stabilization of `or_patterns`...

cc #54883 @Centril
r? @Mark-Simulacrum

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Dylan-DPC** [comment]
failed in rollup 

@bors r-

**Comment by cuviper** [comment]
@Dylan-DPC was that failed as in broke some functionality? Or simply failed to merge -- since this touches a lot of code, conflicts are somewhat likely.

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never

It looks like it just didn't merge (which is expected), this touches a lot of code. Marking as not rolling up.

@bors r+

**Comment by Dylan-DPC** [comment]
No sorry, by failed I meant due to conflicts not due to the CI

**Comment by Mark-Simulacrum** [comment]
(Well, actually, that approval is useless as this has conflicts, but that's fine. @cuviper feel free to approve as needed).

**Comment by Dylan-DPC** [comment]
@Mark-Simulacrum there's a conflict in `src/librustc_mir/interpret/intern.rs`. Do you still want to r+? :P

**Comment by cuviper** [comment]
macOS failed to download clang...

@bors retry

**Comment by cuviper** [comment]
Timeout installing msys...

@bors retry

**Pull request merged**
