### PR TITLE
Less `maybe_whole_expr`, take 2

### PR DESCRIPTION
**Pull request by nnethercote**
I first tried this in #107550. I now think it's worth doing again, as a precursor to #124141.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
This needs a crater run because the error is now reported even under `#[cfg(FALSE)]`.
@bors try

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by nnethercote** [comment]
Lots of crater failures. A quick scan indicates that the `unic-ucd-segment` crate is responsible for most of the failures. I checked and found that it builds ok with the first commit applied, but fails with the second commit. It has some complicated multi-level declarative macros. If I cahnge `parse_literal_maybe_minus` to also handle `ExprKind::MacCall` (in the same way it handles `ExprKind::Lit`) then `unic-ucd-segment` compiles again.

**Comment by nnethercote** [comment]
`rustsec` also fails, and it needs `ExprKind::Path` to be handled in `parse_literal_maybe_minus`.

It's interesting that `can_begin_literal_maybe_minus` does *not* include `ExprKind::{MacCall,Path}`.

**Comment by petrochenkov** [comment]
In the token based model neither `mac!()` nor `path::to::somewhere` are any close to literals, so I don't expect this to work even if the none-delimited groups become "untyped" some time after the removal of nonterminals.
So these cases should probably report a deprecation lint.

**Comment by nnethercote** [comment]
Hmm, looking at the `ExprKind::Path` case some more, I think the real problem is in rustc. Consider this code:
```rust
macro_rules! range {
    ($min:expr, $max:expr) => {
        $min ..= $max
    }
}

const MAX: u32 = 10;

fn main() {
    match 3 {
        range!(0, MAX) => {}
        _ => {}
    }
}
```
It compiles fine with stable rustc. With the original version of this PR applied (i.e. without `ExprKind::Path` handling added to `parse_maybe_literal_minus`) it fails like this:
```
error: unexpected token: expression `MAX`
  --> p.rs:3:18
   |
3  |         $min ..= $max
   |                  ^^^^
...
11 |         range!(0, MAX) => {}
   |         --------------
   |         |
   |         this macro call doesn't expand to a pattern
   |         in this macro invocation
   |
   = note: this error originates in the macro `range` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Adding `ExprKind::Path` handling to `parse_maybe_literal_minus` makes it compile again, but that's not the right solution. The real problem is in `parse_pat_range_end`:

https://github.com/rust-lang/rust/blob/433355166d769afc9c19f761cc7efc4d152e9a2c/compiler/rustc_parse/src/parser/pat.rs#L960-L976

What happens in `check_path`? It fails! Because it relies on `Token::is_path_start`, which relies on `Token::is_whole_path`, which succeeds for `NtPath` but not for `NtExpr(... ExprKind::Path ...)`.

So then we fall through to `parse_maybe_literal_minus`, which succeeds on stable because it accepts any `NtExpr`, but fails with this PR because it doesn't accept `NtExpr(... ExprKind::Path ...)`.

The real solution is that `parse_pat_range_end` should handle `NtExpr(... ExprKind::Path ...)` before calling `parse_maybe_literal_minus`. There's almost certainly a similar problem for the start of pattern ranges.

I don't know yet if the `MacCall` case is like this or not.

**Comment by nnethercote** [comment]
While looking at the `ExprKind::Path` stuff more closely, I found this in `parse_path_inner`:

https://github.com/rust-lang/rust/blob/684b3553f70148ded97a80371c2405984d4f6aa7/compiler/rustc_parse/src/parser/path.rs#L196-L206

It accepts `NtPath` and `NtTy(... TyKind::Path ...)`. @dtolnay added the latter part in #91150.  I think it will need to allow `NtExpr(... ExprKind::Path ...)` to address the problem I described in the previous comment. And then I wonder if `NtPat(... PatKind::Path ...)` should also be allowed.

**Comment by nnethercote** [comment]
Getting the path stuff right is a bit tricky, so I think it's worth merging just the first commit here. Let's re-do the failures from the last crater run:

@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-126571/retry-regressed-list.txt

**Comment by nnethercote** [comment]
No failures when re-running the crater failures with just the first commit applied. I think it's worth merging now and thinking about the additional restrictions on `ExprKind` in a follow-up. @petrochenkov, what do you think?

**Pull request merged**
