### PR TITLE
Better handling of lib defaults

### PR DESCRIPTION
**Pull request by wagenet**
r? @alexcrichton

### CODE REVIEW

**Comment by wagenet** [comment]
So it looks like running `rustc --version` from this build gives me an infinite recursion error...

**Comment by wagenet** [comment]
As possibly this is a rustup issue. I'll investigate more tomorrow.

**Comment by alexcrichton** [comment]
Looks great to me, thanks @wagenet! Could you also add a test for this functionality?

**Comment by wagenet** [comment]
@alexcrichton how do you recommend testing this. I couldn't find any existing tests for the command line flags, though I might just be missing them.

**Comment by alexcrichton** [comment]
@wagenet oh I'm just thinking like a run-pass test which passes `-l` where `#[link]` is already in the source. There's a few `#[link]` directives in the run-pass tests I believe which you can just copy and use to pass as `-l` via `// compile-flags: ...` at the top as well.

**Comment by wagenet** [comment]
So I've verified that this all works in my local app and fixes the bug I was encountering. However, I haven't yet been able to figure out good tests. The ones here don't really test properly.

**Comment by alexcrichton** [comment]
@wagenet ah that's ok, let's leave this to bors

**Pull request merged**
