### PR TITLE
Const pin get ref

### PR DESCRIPTION
**Pull request by DutchGhost**
Implements https://github.com/rust-lang/rust/issues/69001.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Is there any const way to construct a Pin to call get_ref on? If not, is this still useful? Could you show an example of the use case?

**Comment by DutchGhost** [comment]
There isn't any way _at the moment_ to const construct a Pin. However, both constructors can be constified as well.

I didn't do this, since that relies on the fact you can't require any trait bounds in const fn's on stable rustc, and both constructors require `P: Deref`. To be able to constify them, one relies on the nightly const_fn feature, but it could be done.

**Comment by dtolnay** [comment]
Makes sense. In that case I would prefer not to accept this until the method is actually usable in const context and there is a use case.

**Pull request closed without merging**
