### PR TITLE
rename other than copy/remove

### PR DESCRIPTION
**Pull request by king6cong**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Sometimes the `rename` operation can fail when a `copy` would otherwise succeed (such as crossing filesystems), perhaps that could be used first with a `copy` fallback?

**Comment by eddyb** [comment]
@alexcrichton Is there no such "best effort" operation implemented anywhere, for moving files?

**Comment by alexcrichton** [comment]
Oh there probably issue e.g. in the incremental support, I'm not familiar with the precise location, though (@michaelwoerister may know)

**Comment by michaelwoerister** [comment]
Here is something:
https://github.com/rust-lang/rust/blob/24055d0f2aa8dce5caed7544e6006aa48dceaea5/src/librustc/util/fs.rs#L67
It's not for renaming though but for copy vs hard-link.

**Comment by king6cong** [comment]
Thanks for your advice,  everyone 😺 
Here's another commit. @alexcrichton

**Comment by alexcrichton** [comment]
Looks good to me, thanks! I think the tidy check is failing on travis though?

**Comment by king6cong** [comment]
File formatted @alexcrichton

**Pull request merged**
