### PR TITLE
Strengthen validation of FFI attributes

### PR DESCRIPTION
**Pull request by inquisitivecrystal**
Previously, `codegen_attrs` validated the attributes `#[ffi_pure]`, `#[ffi_const]`, and `#[ffi_returns_twice]` to make sure that they were only used on foreign functions. However, this validation was insufficient in two ways:

1. `codegen_attrs` only sees items for which code must be generated, so it was unable to raise errors when the attribute was incorrectly applied to macros and the like.
2. the validation code only checked that the item with the attr was foreign, but not that it was a foreign function, allowing these attributes to be applied to foreign statics as well.

This PR moves the validation to `check_attr`, which sees all items. It additionally changes the validation to ensure that the attribute's target is `Target::ForeignFunction`, only allowing the attributes on foreign functions and not foreign statics. Because these attributes are unstable, there is no risk for backwards compatibility. The changes also ending up making the code much easier to read.

This PR is best reviewed commit by commit. Additionally, I was considering moving the tests to the `attribute` subdirectory, to get them out of the general UI directory. I could do that as part of this PR or a follow-up, as the reviewer prefers.

CC: #58328, #58329

### CODE REVIEW

**Comment by bryangarza** [comment]
Not an official reviewer, but I looked through the commits and it looks good to me.

> Additionally, I was considering moving the tests to the `attribute` subdirectory, to get them out of the general UI directory. I could do that as part of this PR or a follow-up, as the reviewer prefers.

I think it'd be better if you move them into the `attribute` dir as part of this PR so if someone is looking at the commit for the tests, they can `git diff` that commit hash and get the rest of the code changes too

**Review by davidtwco — APPROVED** [review]
LGTM, but this is technically a breaking change, so I think we'll want to do a crater run to see how safe this is to land.

**Comment by inquisitivecrystal** [comment]
> LGTM, but this is technically a breaking change, so I think we'll want to do a crater run to see how safe this is to land.

All these attributes are still unstable, so it shouldn't be a problem? Unless we're worried about breaking nightly code.

**Comment by davidtwco** [comment]
> > LGTM, but this is technically a breaking change, so I think we'll want to do a crater run to see how safe this is to land.
> 
> All these attributes are still unstable, so it shouldn't be a problem? Unless we're worried about breaking nightly code.

Oh, I should have checked that, great - that's much simpler.

**Comment by inquisitivecrystal** [comment]
> Oh, I should have checked that, great - that's much simpler.

I did mention it in the OP, but I don't blame you for missing it - I'm not the most concise. :)

**Comment by compiler-errors** [comment]
For future reference, do not approve a PR when a try-build is running, or else it will try to be merged into master 😬

**Comment by davidtwco** [comment]
> For future reference, do not approve a PR when a try-build is running, or else it will try to be merged into master 😬

Oh, oops, hadn't done that before. My bad.

**Comment by inquisitivecrystal** [comment]
I'm going to force push and then close and reopen to reset things (at least, those are the steps I've seen before; not sure which of the two is required, but doing both can't hurt).

**Comment by inquisitivecrystal** [comment]
I think if someone approves again we should be set? The change to the last commit only affected the commit message.

**Comment by inquisitivecrystal** [comment]
@davidtwco: could you `r+` this again?

**Pull request merged**
