### PR TITLE
`collect_tokens_trailing_token` cleanups

### PR DESCRIPTION
**Pull request by nnethercote**
More cleanups I made while understanding the code for processing `cfg_attr`, to fix test failures in #124141.

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
I fixed the doc failure and rebased.

@bors r=petrochenkov

**Comment by tgross35** [comment]
@nnethercote I guess you have to rebase again and update the ```` ```ignore ```` test in `attr_wrapper`, tidy is complaining about it here https://github.com/rust-lang/rust/actions/runs/10002645597/job/27648285238?pr=127952#step:25:1689.

No clue why that didn't show up in PR CI, https://github.com/rust-lang/rust/pull/127936 is the only thing that merged since you rebased.

@bors r-

**Comment by nnethercote** [comment]
I added a reason to the `ignore` comment, hopefully that should fix the problem.

@bors r=petrochenkov

**Pull request merged**
