### PR TITLE
Remove many instances of 'just'

### LINKED ISSUE #28810: Audit iterator specializations for side effects
After some discussion about https://github.com/rust-lang/rust/pull/28125 the libs subteam decided that iterator adaptors should always preserve the same semantics in terms of the convenience methods and such. This was not audited for when all the initial specializations landed, so we should take a look and make sure that everything adheres to this policy.

Additionally, documentation should be added to the `Iterator` trait methods indicating what form of guarantees you are given (e.g. calling `last` is equivalent to exhausting the iterator).

triage: I-nominated

### PR DESCRIPTION
**Pull request by steveklabnik**
Doing so is considered weaker writing. Thanks @Charlotteis!

Fixes #28810

### CODE REVIEW

**Comment by Charlotteis** [comment]
@steveklabnik :sparkling_heart:

**Comment by steveklabnik** [comment]
Wow, I typo'd https://github.com/rust-lang/rust/issues/28835 in the description :(

**Pull request merged**
