### PR TITLE
Update cargo, rls, miri

### PR DESCRIPTION
**Pull request by ehuss**
Update cargo, rls, miri

Added `rustc-workspace-hack` to miri so that it shares the same features for serde as other tools.

cc @alexcrichton 

## cargo

25 commits in 2cf1f5dda2f7ed84e94c4d32f643e0f1f15352f0..0d1f1bbeabd5b43a7f3ecfa16540af8e76d5efb4
2018-12-11 03:44:04 +0000 to 2018-12-19 14:45:14 +0000
- Remove Stale bot's configuration (rust-lang/cargo#6463)
- Add labels to issue templates (rust-lang/cargo#6464)
- Fix new man page links. (rust-lang/cargo#6459)
- Fix metabuild compile errors with --message-format=json. (rust-lang/cargo#6432)
- Support alt-registry names in [patch] table. (rust-lang/cargo#6456)
- Update the rustup URL (rust-lang/cargo#6455)
- New man pages. (rust-lang/cargo#6405)
- Reify the DepFingerprint type (rust-lang/cargo#6451)
- Extract Fingerprint::new (rust-lang/cargo#6449)
- Upgrade the metabuild to Rust 2018 (rust-lang/cargo#6448)
- Make edition comparing code consistent (rust-lang/cargo#6450)
- Document `name` and `authors` in [package] (rust-lang/cargo#6447)
- Travis: only use mdbook 0.1.7. (rust-lang/cargo#6443)
- Update git2-curl requirement from 0.8.1 to 0.9.0 (rust-lang/cargo#6439)
- Update git2 requirement from 0.7.5 to 0.8.0 (rust-lang/cargo#6438)
- Display errors when `cargo fix` fails. (rust-lang/cargo#6419)
- cargo fix: fix targets with shared sources. (rust-lang/cargo#6434)
- Fix panic-in-panic in tests. (rust-lang/cargo#6431)
- More Rust 2018 edition cleanups (rust-lang/cargo#6422)
- Cleanup some trait impls for SourceId (rust-lang/cargo#6429)
- Remove a nightly check from doc tests (rust-lang/cargo#6427)
- Replace CargoError with failure::Error (rust-lang/cargo#6425)
- Allow testsuite warnings in dev (rust-lang/cargo#6426)
- add `--dry-run` option to cargo update (rust-lang/cargo#6371)
- Migrate to some Rust 2018 idioms (rust-lang/cargo#6416)

## rls

16 commits in bd5b899afb05e14d33e210ede3da241ca1ca088f..6f5e4bba7b1586fca6e0ea7724cadb5683b2f308
2018-12-10 08:53:00 +0100 to 2018-12-21 17:11:08 +0100
- Update jsonrpc-core (rust-lang-nursery/rls#1206)
- Use `home_dir` from `home` crate (rust-lang-nursery/rls#1207)
- Update cargo. (rust-lang-nursery/rls#1204)
- Fix deprecated `trim_{left,right}` warnings (rust-lang-nursery/rls#1203)
- Respect ${CARGO,RUSTUP}_HOME for tooltip relative dirs (rust-lang-nursery/rls#1201)
- Separate tooltip tests that require Racer fallback (rust-lang-nursery/rls#1200)
- tests: Don't generate tooltip results in tests/fixtures (rust-lang-nursery/rls#1199)
- Overhaul fixture handling in tests (rust-lang-nursery/rls#1190)
- Don't return symbols with empty names (rust-lang-nursery/rls#1193)
- Don't check AppVeyor CI status for bors
- Properly infer full_docs (rust-lang-nursery/rls#1192)
- Update cargo (rust-lang-nursery/rls#1191)
- Improve hover test_tooltip tests (rust-lang-nursery/rls#1175)
- Fix unused warnings (rust-lang-nursery/rls#1185)
- Workaround rust-lang-nursery/rls#703 to prevent obscure failures due to sccache. (rust-lang-nursery/rls#1177)
- Disable travis cache (rust-lang-nursery/rls#1182)

## miri

14 commits in bccadeb4f7cbeeb14097a365653148afe8bbd159..6c2fc6daf1ac6849d1243b213f5a3fb07feeef29
2018-12-08 11:07:22 +0100 to 2018-12-26 14:28:25 +0100
- use memory::check_bounds_ptr for offset check (solson/miri#589)
- Fix comparing function pointers (solson/miri#587)
- fix for infallible allocation (solson/miri#586)
- fix test for latest nightly (solson/miri#585)
- Treat ref-to-raw cast like a reborrow: do a special kind of retag (solson/miri#572)
- Test cargo-miri on Windows (solson/miri#578)
- Cargo miri tweaks and test that we can exclude tests (solson/miri#580)
- Fix cargo miri test (solson/miri#550)
- fix for latest nightly (solson/miri#574)
- Add rustc-workspace-hack. (solson/miri#575)
- use RUSTC_WRAPPER for the cargo hook (solson/miri#573)
- do not auto-detect the targets in the sysroot, instead specify target manually through env var (solson/miri#570)
- Cleanup: Avoid repeating signatures, get rid of to_bytes hack (solson/miri#568)
- Support building and running with full MIR on foreign architectures, drop support for missing MIR (solson/miri#566)

### CODE REVIEW

**Comment by ehuss** [comment]
Aye yai yai, I'll try to fix rls.

**Comment by Xanewok** [comment]
`"/checkout/src/tools/rls/target/tests/hover/save_data"`

This might be due to https://github.com/rust-lang/rls/blob/6844569133e4a5fea2a7887911d9091ef1301648/src/actions/hover.rs#L2172. There's now ongoing effort to clean RLS testing suite, https://github.com/rust-lang/rls/pull/1190 cleaning what test data we write and to generate temp dirs for writing purposes during testing.

@ehuss @alexcrichton Is the change very urgent? If so, we could land this PR now directly and fix `save_dir` handling afterwards; otherwise I'll do that first thing in the morning (being in ~12 hours).

Assuming temp directory is writable in CI, after the PR merge (which pulls in `tempfile` crate) we could create analogous `save_dir` with `tempfile::tempdir()?.into_path()` instead of https://github.com/rust-lang/rls/blob/6844569133e4a5fea2a7887911d9091ef1301648/src/actions/hover.rs#L1244.

**Comment by ehuss** [comment]
Oh good, temp directories sound better.  It looks like there are three places where they need to be used:

https://github.com/rust-lang/rls/blob/6844569133e4a5fea2a7887911d9091ef1301648/src/actions/hover.rs#L1194-L1198

https://github.com/rust-lang/rls/blob/6844569133e4a5fea2a7887911d9091ef1301648/src/actions/hover.rs#L2117-L2121

https://github.com/rust-lang/rls/blob/6844569133e4a5fea2a7887911d9091ef1301648/src/actions/hover.rs#L2172-L2176

The way these tests are determining the target directory are incorrect.  Will your PR switch all of them to use a temp directory?  Otherwise, I was thinking of switching it to something like this:

```rust
    fn target_dir() -> PathBuf {
        // Test output is stored in the target dir, for lack of a better
        // location (a temp dir might also be reasonable, but more
        // cumbersome). Unfortunately Cargo does not make it easy to detect.
        if let Ok(dir) = env::var("CARGO_TARGET_DIR") {
            return PathBuf::from(dir);
        }
        let mut path = env::current_exe().expect("Can't determine exe");
        path.pop(); // chop off exe name
        path.pop(); // chop off 'debug'

        // When run with `--target`, also pop the target name.
        if path.file_name().and_then(|s| s.to_str()) != Some("target") {
            path.pop();
        }
        path
    }
```

I'm not in a big rush.  If RLS can be fixed within a few days, I'd be fine with that.

**Comment by Xanewok** [comment]
Yeah, these should be switched over. I missed those in the original PR, will send a follow-up upstream tomorrow.

**Comment by Xanewok** [comment]
https://travis-ci.org/rust-lang/rust/jobs/469617899#L7794

```
expected value: "fnv-1.0.6/lib.rs"
actual   value: "/cargo/registry/src/github.com-1ecc6299db9ec823/fnv-1.0.6/lib.rs"
```

I think CI fails because `.cargo` and tmp dir are starting from different root and if that's the case we supply the full path instead of relative... I'll look into that. I guess the quickest fix would be to use the `target_dir()` logic.

Re local failure, unfortunately it seems that only macOS experiences spurious failures and we can't quite dig as to what's causing this (and I don't have any access to macOS machine :cry:). Might be best to disable it altogether on macOS for now.

**Comment by Xanewok** [comment]
The abs/relative is actually caused by https://github.com/rust-lang/rls/blob/8753cb5fcfdc4079035de30f919d05d464c3285c/src/actions/hover.rs#L665-L666. In Rust CI we [map](https://github.com/rust-lang/rust/blob/d99a320cba42f661aebfa1293b7b2ec3603dda75/src/ci/docker/run.sh#L137) `.cargo` to `/cargo`, confusing the logic at the highlighted lines above. This actually uncovered a bug, working on a fix!

**Comment by Xanewok** [comment]
@ehuss hopefully everything works as expected now, latest https://github.com/rust-lang/rls/commit/173be7729ae9ea41303fbd84f339f76554c9d9af should work.

**Comment by ehuss** [comment]
Aww, I thought that the toolstate wouldn't complain if the state didn't *change*.  Anyone have ideas what to do about that?  I'm not sure how hard it would be to get miri tests passing.

**Comment by RalfJung** [comment]
These look like failures that have already been fixed in miri. Did you try updating to latest master?

**Comment by ehuss** [comment]
@RalfJung Oh, sorry, I didn't see you've been busy!  However, I updated and every test is failing with this message:
```
error[E0080]: constant evaluation error: no mir for `std::rt::lang_start_internal`
  --> /Users/eric/Proj/rust/rust/src/libstd/rt.rs:74:5
   |
74 |     lang_start_internal(&move || main().report(), argc, argv)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no mir for `std::rt::lang_start_internal`
   |
   = note: inside call to `std::rt::lang_start::<()>`
```

I'm trying to figure out if it is unique to my system or not.  I pushed an update and will see what CI says.   Does that error make any sense to you?

**Comment by ehuss** [comment]
Oh, derp, I swear I had set it earlier, but I guess not.

It looks like `gnu-tools` is passing. :tada:  Thanks @Xanewok and @RalfJung for the fast fixes!

**Comment by ehuss** [comment]
@Xanewok looks like `test_tooltip_racer` failed on Windows, with some absolute paths where relative ones were expected.

**Comment by Xanewok** [comment]
That's... unfortunate. I can't repro locally on Windows and AppVeyor normally should set `%USERPROFILE`. On my Windows box I also have `CARGO_HOME` and `RUSTUP_HOME` set correctly when `cargo test`ing. 
The only way that'd fail was if those (or `%HOME%`) were somehow set to bad/empty string, which I don't expect them to be (otherwise `%USERPROFILE%` joined with `.cargo` fallback should work).

@alexcrichton do we do something non-standard with our env vars on AppVeyor?

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/56741 landed, miri in here will now fail. There's a fix at https://github.com/solson/miri/pull/572, so if you update this PR to use the latest `rustup` branch, everything should work again.

**Comment by ehuss** [comment]
@Xanewok If I had to guess, I'd say it is running in an msys environment where $HOME is `/c/Users/appveyor`.  That style of path won't match with `C:/Users/appveyor/...` style paths.  Maybe don't check HOME on Windows?

**Comment by RalfJung** [comment]
The miri PR has landed, so in fact just pulling miri master again should fix it-

**Comment by Xanewok** [comment]
> If I had to guess, I'd say it is running in an msys environment where $HOME is /c/Users/appveyor

@ehuss You're right, we execute our CI script under `sh` and we set `$HOME` there to UNIX-style path. 🙁  PR https://github.com/rust-lang/rls/pull/1207 should fix it - sorry for the churn!

**Comment by ehuss** [comment]
@RalfJung I think #54125 has caused one of the miri tests to fail:

```
failures:

---- [compile-fail] compile-fail/never_transmute_void.rs stdout ----

error: tests/compile-fail/never_transmute_void.rs:13: unexpected error: '13:9: 13:10: unused variable: `v` [unused_variables]'

error: tests/compile-fail/never_transmute_void.rs:9: expected error not found: entered unreachable code

error: tests/compile-fail/never_transmute_void.rs:16: expected message not found: inside call to `f`

error: 1 unexpected errors found, 2 expected errors not found
status: exit code: 1
command: "/Users/eric/Proj/rust/rust/build/x86_64-apple-darwin/stage2-tools-bin/miri" "tests/compile-fail/never_transmute_void.rs" "-L" "/var/folders/rw/vx9xfxys6kjd5x1jw70pqg2c0000gn/T/compiletest4q0fQt" "--target=x86_64-apple-darwin" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/var/folders/rw/vx9xfxys6kjd5x1jw70pqg2c0000gn/T/compiletest4q0fQt/never_transmute_void.stage-id" "-Dwarnings" "-Dunused" "--edition" "2018" "-Zmiri-disable-validation" "-L" "/var/folders/rw/vx9xfxys6kjd5x1jw70pqg2c0000gn/T/compiletest4q0fQt/never_transmute_void.stage-id.aux" "-A" "unused"
unexpected errors (from JSON output): [
    Error {
        line_num: 13,
        kind: Some(
            Error
        ),
        msg: "13:9: 13:10: unused variable: `v` [unused_variables]"
    }
]

not found errors (from test file): [
    Error {
        line_num: 9,
        kind: Some(
            Error
        ),
        msg: "entered unreachable code"
    },
    Error {
        line_num: 16,
        kind: None,
        msg: "inside call to `f`"
    }
]

thread '[compile-fail] compile-fail/never_transmute_void.rs' panicked at 'explicit panic', /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.17/src/runtest.rs:1098:13
```

**Comment by RalfJung** [comment]
@ehuss sounds right. I can write a fix later today, but not right now.

But if someone submits a PR against miri, I could quickly merge it.

**Comment by ehuss** [comment]
@RalfJung It looks like miri is now broken by #56981?

Also, this is now blocked on clippy being broken. 😢

**Comment by RalfJung** [comment]
Yeah, Miri needs another update. I can look into it later.

These coordinated tool updates are quite painful...

**Comment by RalfJung** [comment]
There's a fix for Miri at https://github.com/solson/miri/pull/586 (pull the "rustup" branch).

**Comment by ehuss** [comment]
@RalfJung looks like miri is broken again by #56985.

**Comment by RalfJung** [comment]
@ehuss there's a fix at https://github.com/solson/miri/pull/587 (pull the `rustup` branch)

**Comment by RalfJung** [comment]
It got merged into miri master.

**Comment by ehuss** [comment]
@RalfJung thanks!

 @alexcrichton looks like the tools job is green again.

**Comment by RalfJung** [comment]
@ehuss you should pull latest Miri master, that one works with https://github.com/rust-lang/rust/pull/57129

**Comment by Xanewok** [comment]
Clippy fails to build now (RLS depends on it), needs https://github.com/rust-lang/rust/pull/57138 to be fixed.

**Comment by ehuss** [comment]
Yay, it's green again! 🎉

**Comment by RalfJung** [comment]
Hooray!

@bors r=alexcrichton

**Comment by RalfJung** [comment]
@bors p=9

High potential of conflicts

**Pull request merged**
