### PR TITLE
Add const evaluation error UI test.

### LINKED ISSUE #78834: Wrong error about the size of a parameter not being known at compiletime
I tried this code:

```rust
struct B<A: Sized = [(); {
    let x = [0u8; !0usize];
    1
}]> {
    a: A
}

fn main() {

}
```

I expected to see this happen: This code should compile, as `A` is a generic type with the default type being `[(); 1]`. When I remove the `let x = [0u8; !0usize]` line, everything compiles fine.

Instead, this happened: I got an error message, `error[E0277]`

### Meta

`rustc --version --verbose`:
```
Stable version: 1.47.0
Beta version: 1.48.0-beta.5
1.49.0-nightly (2020-11-05 9d78d1d02761b906038b)
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `A` cannot be known at compilation time
  --> src/main.rs:32:19
   |
31 | struct B<A: Sized = [(); {
   |          -
   |          |
   |          this type parameter needs to be `Sized`
   |          required by this bound in `B`
32 |     let x = [0u8; !0usize];
   |                   ^^^^^^^ doesn't have a size known at compile-time

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by LFS6502**
This closes #78834

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
formatting in this test goes kinda crazy but according to rustfmt it's valid so whatever

**Comment by compiler-errors** [comment]
Test name could be improved to talk about how it's in a const generic default but w/e

r? compiler-errors @bors r+ rollup

**Comment by Zalathar** [comment]
> formatting in this test goes kinda crazy but according to rustfmt it's valid so whatever

I'm pretty sure `x fmt` doesn't touch ui tests, because it would break error comments.

(The formatting is atypical, but in the context of a tiny UI test I don't think it's a big deal.)

**Comment by HypheX** [comment]
> formatting in this test goes kinda crazy but according to rustfmt it's valid so whatever

:laughing: Yeah, it's wild. I actually ran it through rustfmt and it actually made it even worse on my end.

**Comment by compiler-errors** [comment]
@Zalathar: I am aware. I mean I ran it through rustfmt locally.

**Pull request merged**
