### PR TITLE
Change arm-linux-androideabi to correspond to the armeabi official ABI

### LINKED ISSUE #40941: Change arm-linux-androideabi to correspond to the armeabi official ABI
This step is missing from https://github.com/rust-lang/rust/issues/33278#issuecomment-216938045

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes #40941.

### CODE REVIEW

**Comment by malbarbo** [comment]
It this enough to fix the issue?

**Comment by arielb1** [comment]
Thanks for the PR @malbarbo. @japaric or someone else should be reviewing your PR shortly.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @malbarbo!

FWIW the reason we didn't do this originally was to prevent regressing Servo, but I just chatted with @fabricedesre on IRC and it sounds like they're good to go (can change to armv7 target if necessary).

Also cc @larsbergstrom to make sure you're in the loop on this as well.

**Comment by malbarbo** [comment]
Thanks Alex! Should this be tagged relnotes?

**Comment by alexcrichton** [comment]
Indeed yeah

**Comment by larsbergstrom** [comment]
@alexcrichton Thanks for the heads-up!

**Pull request merged**
