### PR TITLE
Update RLS

### LINKED ISSUE #85225: `rls` no longer builds after rust-lang/rust#83813
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#83813, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @cbeuw, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by Xanewok**
Contains https://github.com/rust-lang/rls/pull/1736. With #82208 merged, this should now close https://github.com/rust-lang/rust/issues/85225. Tested locally with `./x.py test src/tools/rls` and seems to be working as expected.

I noticed the rustfmt merge didn't trigger toolstate upgrade (because we pruned most but not all of the related machinery?), so I'd rather get this rubber-stamped by someone more knowledgeable with infra/the merged changes in case I missed something and need to include something else here to unbreak the RLS toolstate.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by calebcartwright** [comment]
I had some similar questions about rustfmt after I checked the toolstate page earlier (admittedly a bit prematurely) and noticed that it hadn't been updated in a while either. Not sure if that's expected or related, but sharing in case it is

**Comment by jyn514** [comment]
> I noticed the rustfmt merge didn't trigger toolstate upgrade

What is toolstate upgrade?

**Comment by Xanewok** [comment]
I meant "Toolstate changed!" notifications such as https://github.com/rust-lang/rust/pull/84886#issuecomment-832690412

**Comment by Xanewok** [comment]
I guess there's no harm in pushing this further and I believe chances of this needing a follow-up are slim

@bors r+ p=1

**Pull request merged**
