### PR TITLE
Try to improve rustdoc performance by reducing the number of allocations of pulldown-cmark

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
By default, `pulldown-cmark` allocates a possibly too big amount of memory for each doc-comment we parse: https://github.com/raphlinus/pulldown-cmark/blob/c6b8fa6b43d6c6100a16b04d19445979a8ce0d66/src/firstpass.rs#L23-L39. From this, I realized that we are actually doing a great number of allocations and that we could very likely reduce this number. To do so, I added some methods in `pulldown_cmark` which allow to pass a buffer as argument (you can see the diff [here](https://github.com/raphlinus/pulldown-cmark/compare/branch_0.9.3...GuillaumeGomez:pulldown-cmark:parser-buffer?expand=1) and I updated the code on the rustdoc side as well. So first let's see if the performance is impacted positively.

### CODE REVIEW

**Comment by lqd** [comment]
(cc @klensy who I've discussed this with)

**Comment by GuillaumeGomez** [comment]
Going to disable the tidy check for crates source.

**Comment by klensy** [comment]
Looks like missed perf queue.

**Comment by GuillaumeGomez** [comment]
Oh indeed. I don't know why I input the wrong command... Friday evening effect.

@bors try @rust-timer queue

**Comment by klensy** [comment]
I'll try to check whats changed.

**Comment by GuillaumeGomez** [comment]
I definitely didn't expect such results. Most of them don't seem related to rustdoc too.

For doc checks, the biggest regression is of 0.67% on diesel. Memory usage seemed to have gown on ripgrep by 1.54% too. Again, I'm very surprised.

**Comment by GuillaumeGomez** [comment]
Did you have time to take a look @klensy ?

**Comment by klensy** [comment]
Not yet, sadly.

**Comment by GuillaumeGomez** [comment]
No change so it seems it's not worth continuing this.

**Pull request closed without merging**
