### PR TITLE
Don't allow `-Zunstable-options` to take a value 

### PR DESCRIPTION
**Pull request by Zalathar**
Passing an explicit boolean value (`-Zunstable-options=on`, `off` etc.) sometimes appears to work, but actually puts the compiler into an unintended state where unstable _options_ are still forbidden, but unstable values of _some_ stable options are allowed.

This is a result of `-Zunstable-options` being checked in multiple different places, in slightly different ways. Fixing the checks in `config::nightly_options` to understand boolean values would be non-trivial, so for now it's easier to make things consistent by forbidding values in the `-Z` parser.

---

There were a few uses of this in tests, which happened to work because they were tests of unstable values.

### CODE REVIEW

**Comment by jieyouxu** [comment]
> Passing an explicit boolean value (`-Zunstable-options=on`, `off` etc.) sometimes appears to work, but actually puts the compiler into an unintended state where unstable options are still forbidden, but unstable values of some stable options are allowed.

I feel like that sounds *intentional* but is an abuse of the same value, maybe worth introducing `-Zunstable-option-values` I wonder...

**Comment by Kobzol** [comment]
We already have `-Zallow-features` (https://github.com/rust-lang/rust/blob/7244af6ca346db8e5b1bee2d68775cfabc6e1706/tests/run-make/rustc-crates-on-stable/rmake.rs#L13) for enumerating specific features, isn't that enough?

**Comment by jieyouxu** [comment]
> We already have `-Zallow-features`:
> 
> https://github.com/rust-lang/rust/blob/7244af6ca346db8e5b1bee2d68775cfabc6e1706/tests/run-make/rustc-crates-on-stable/rmake.rs#L13
> 
> for enumerating specific features, isn't that enough?

See https://github.com/rust-lang/rust/issues/123404#issuecomment-2473589626, `-Zallow-features` affect all the `#[feature(..)]`s, but it doesn't affect rustc cli flags AFAIK.

**Comment by Zalathar** [comment]
> but unstable values of _some_ stable options are allowed

Also note that when I say “some” here, I really do mean _some_. All unstable values are checked by ad-hoc code, so whether a particular option's unstable values are enabled by `yes` depends on which of the two APIs that ad-hoc code calls. And we already have a mixture of both styles in the compiler.

**Review by jieyouxu — APPROVED** [review]
I think this is strictly better than having an inconsistent weird remix of *some* unstable values being gated while others are not. So, cool.

**Comment by jieyouxu** [comment]
Thanks!
@bors r+ rollup

**Pull request merged**
