### PR TITLE
CONTRIBUTING.md redux

### PR DESCRIPTION
**Pull request by steveklabnik**
This redux of CONTRIBUTING.md adds in more information, including
subsuming both compliment-bugreport.md and Note-development-policy
in the wiki.

I only glanced at the broad TOC of Note-development-policy, and did
not use the text as the basis for the re-write. This will then address
the last outstanding part of #5831.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Needs a rebase

**Comment by brson** [comment]
r=me Awesome polish for the newbie experience.

**Comment by brson** [comment]
You might link to this file from the README.

**Pull request merged**
