### PR TITLE
Fix JSON reexport ICE

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/97432.

The problem was that the ID was conflicting because the reexports have the same one. To fix it, I "extended" it by adding the `Symbol` into it as well.

r? @notriddle

### CODE REVIEW

**Comment by Urgau** [comment]
This is more like a bandage than a real solution.

You should look at https://github.com/rust-lang/rust/pull/93518 which is completely different approach than this PR is taking, basically the idea is for the JSON output to not inline anything meaning that re-export will not ICE anymore rustdoc because they still will be different.

**Comment by CraftSpider** [comment]
That PR needs updated and is not yet perfect, it still has some known failures. On the other hand as far as I can tell it does fix re-export issues generally. I've been slacking on doing the work to carry it over the finish-line, I'd be willing to help mentor someone else if they are willing to do some of the work to push it over the finish-line, alternatively I'll try to set aside some time this weekend to finish it up.

**Comment by GuillaumeGomez** [comment]
I also took another approach at the start where I stopped inlining reexports but I found the result sub-optimal. However it'd be a better approach overall than my current PR.

What is missing in https://github.com/rust-lang/rust/pull/93518?

**Comment by GuillaumeGomez** [comment]
I see. Considering none of these PRs are anywhere close to being merged, should we move forward with this one then? I can add a `FIXME: remove this function once no more inlining for JSON format` above the `from_item_id_with_name` function to make sure it won't remain.

My problem here is that we have an ICE, which should be avoided at all cost.

**Comment by CraftSpider** [comment]
I'd support moving forward with this as a future FIXME

**Comment by GuillaumeGomez** [comment]
Ok, updating the PR then. :)

**Comment by GuillaumeGomez** [comment]
And done!

**Review by CraftSpider — APPROVED** [review]

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/97637#issuecomment-1144556662)

**Comment by GuillaumeGomez** [comment]
Fixed the doc comment.

@bors: r=CraftSpider rollup

**Pull request merged**
