### PR TITLE
Fix the span for try shorthand expressions

### PR DESCRIPTION
**Pull request by marcusklaas**
My five character contribution to the rust parser! Fixes https://github.com/rust-lang/rust/issues/32709.

### CODE REVIEW

**Comment by jseyfried** [comment]
Thanks!

@bors r+ rollup

**Comment by nagisa** [comment]
Needs a test.

@bors r-

**Comment by marcusklaas** [comment]
@nagisa AFAIK, there is no way to test against regressions of overly long spans. If you know of a way, I'd be happy to write one!

**Comment by jseyfried** [comment]
@marcusklaas I believe you can do something like this:
```rust
fn main() {
    a?; //~ ERROR 2:5: 2:7
}
```

**Comment by nikomatsakis** [comment]
as @marcusklaas notes, we don't usually test these, though indeed we probably should... would be nice to add a more targeted way of testing them. I guess that what @jseyfried suggests may actually work.

**Comment by nagisa** [comment]
It does indeed work. We also have a bunch of regression tests all around already testing that the span (where it was misaligned before) is correct by using some smart whitespacing in test (though I’m not sure whether the tests actually properly test the span). 

I don’t see how this case is any different.

**Comment by marcusklaas** [comment]
@nagisa these whitespace tests can only verify that some part of the code is part of the span. Here we want to ensure that the span does *not* contain something. I'll give @jseyfried's approach a try; looks promising!

**Comment by marcusklaas** [comment]
Added a test! r? @nagisa

**Comment by mitaa** [comment]
```
/home/travis/build/rust-lang/rust/src/test/compile-fail/symbol-names/issue-32709.rs:11: trailing whitespace
```

**Comment by steveklabnik** [comment]
@bors: r-

this has a tidy error

**Comment by marcusklaas** [comment]
Fixed. Apologies for the mess.

**Comment by Manishearth** [comment]
http://buildbot.rust-lang.org/builders/auto-linux-musl-64-opt/builds/3787/steps/test/logs/stdio

```


---- [compile-fail] compile-fail/symbol-names/issue-32709.rs stdout ----
	
error: unexpected compiler message: '/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16:5: 16:6 error: unresolved name `a` [E0425]'

error: unexpected compiler message: '/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16:5: 16:7 error: mismatched types:'

error: expected error on line 16 not found: 2:5: 2:7

error: 2 unexpected errors found, 1 expected errors not found
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs -L x86_64-unknown-linux-gnu/test/compile-fail/ --target=x86_64-unknown-linux-musl -L x86_64-unknown-linux-gnu/test/compile-fail/symbol-names/issue-32709.stage2-x86_64-unknown-linux-musl.compile-fail.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/symbol-names/issue-32709.stage2-x86_64-unknown-linux-musl -C linker=/musl-x86_64/bin/musl-gcc -C ar=ar --cfg rtopt -C rpath -O -L x86_64-unknown-linux-musl/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16:5: 16:6 error: unresolved name `a` [E0425]
/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16     a?; //~ ERROR 2:5: 2:7
                                                                                                                      ^
/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16:5: 16:6 help: run `rustc --explain E0425` to see a detailed explanation
/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16:5: 16:7 error: mismatched types:
 expected `()`,
    found `std::result::Result<_, _>`
(expected (),
    found enum `std::result::Result`) [E0308]
/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16     a?; //~ ERROR 2:5: 2:7
                                                                                                                      ^~
/buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/test/compile-fail/symbol-names/issue-32709.rs:16:5: 16:7 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error

------------------------------------------

thread '[compile-fail] compile-fail/symbol-names/issue-32709.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-musl-64-opt/build/src/compiletest/runtest.rs:1677


failures:
    [compile-fail] compile-fail/symbol-names/issue-32709.rs
```

**Comment by nagisa** [comment]
Oh, it still has the rollup flag on! My bad @Manishearth!

@bors rollup- r-

@marcusklaas need to adjust line numbers from 2 to 16 in the test.

**Comment by marcusklaas** [comment]
Ugh - I force pushed an experimental test the last time around :/ My bad. All should be well now.

**Pull request merged**
