### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by compiler-errors**
Successful merges:

 - #100724 (Migrate ast lowering to session diagnostic)
 - #100735 (Migrate `rustc_ty_utils` to `SessionDiagnostic`)
 - #100738 (Diagnostics migr const eval)
 - #100744 (Migrate rustc_mir_dataflow to diagnostic structs)
 - #100776 (Migrate `rustc_lint` errors to `SessionDiagnostic`)
 - #100817 (sugg: suggest the usage of boolean value when there is a typo in the keyword)
 - #100836 (Migrate `rustc_attr` crate diagnostics)
 - #100890 (Migrate rustc_driver to SessionDiagnostic)
 - #100900 (on `region_errors.rs`)

Failed merges:

 - #100831 (Migrate `symbol_mangling` module to new diagnostics structs)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=100724,100735,100738,100744,100776,100817,100836,100890,100900)

### CODE REVIEW

**Comment by compiler-errors** [comment]
Tried to roll up all of the translation PRs into one cc @davidtwco

**Comment by compiler-errors** [comment]
Well I also included one that wasn't a translation PR but oh well.

**Comment by nnethercote** [comment]
`html5ever-0.26.0` has become very noisy lately, so I think this is a phantom regression.

@rustbot label: -perf-regression

**Pull request merged**
