### PR TITLE
Change match desugaring in MIR to be O(n) instead of O(n^2)

### LINKED ISSUE #29227: Perf regression in nightly when compiling massive matches
The file located here: https://gist.github.com/swgillespie/37b32f7b09ae536df8dc when compiled using `rustc rustc_abuse.rs -o rustc_abuse -Z time-passes` takes approximately 9 seconds and 40MB of memory to compile on stable and beta, while taking almost a minute and 4GB of memory on nightly. 

The Bad Thing being done here is that there are several massive matches. As expected, match checking takes a few seconds, but the real culprit here seems to be "MIR dump", which is where the memory usage peaks. The memory usage is high enough to get my Travis CI build killed that has some code similar to this, but not as extreme.

These numbers were gathered with:
* `rustc 1.5.0-nightly (4826f9625 2015-10-21)` 
* `rustc 1.4.0-beta.3 (20eba406f 2015-10-16)` 
* `rustc 1.3.0 (9a92aaf19 2015-09-15)`. 
* Mac OS X 10.10.5

### PR DESCRIPTION
**Pull request by nikomatsakis**
The older algorithm was pretty inefficient for big matches. Fixes #29227. (On my computer, MIR construction on this test case goes from 9.9s to 0.025s.) Whereas before we had a loop like:
- for all outcomes of the test we are performing
  - for all candidates
    - check whether candidate is relevant to outcome

We now do:
- for all candidates
  - determine which outcomes the candidate is relevant to

Since the number of outcomes in this case is proportional to the number of candidates, the original algorithm turned out to be O(n^2), and the newer one is just O(n).

This PR also does some minor speedups by eagerly mirroring all patterns, so that we can just pass around `&Pattern<'tcx>`, which makes cloning cheaper. We could probably go a bit further in this direction.

r? @Aatch

### CODE REVIEW

**Comment by Aatch** [comment]
Looks good to me. r=me with that one change.

**Comment by nikomatsakis** [comment]
@bors r=aatch

(queue is basically empty, so I'll keep abusing bors, since my local build is being slow)

**Pull request merged**
