### PR TITLE
macOS: avoid calling pthread_self() twice

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage: @kubo39 - the build has failed. 
Your code is for MacOS only but it's failing under Linux x86_64-gnu-llvm-7 ....

**Comment by shepmaster** [comment]
This seems reasonable, but can you share a little about why this change is important or why you noticed it?

**Comment by shepmaster** [comment]
You can go ahead and squash your two commits together now as well.

**Comment by kubo39** [comment]
I noticed this while reading the code. To be honest, this is not so important change(maybe slightly faster).

**Comment by shepmaster** [comment]
Thanks!

**Pull request merged**
