### PR TITLE
Remove ArenaCacheSelector for visible_parent_map query

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by In-line** [comment]
Please, kindly schedule a perf run, in accordinness with https://github.com/rust-lang/rust/pull/87349#discussion_r773143736

**Comment by In-line** [comment]
Surprising results, that DefIdMap cloning has lower performance cost, than Lrc wrapper. What do you think @Mark-Simulacrum ?

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

I think this might've been some amount of noise when it was run, so let's re-check just in case.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/92169.

**Pull request closed without merging**
