### PR TITLE
Pull in a wasm fix from LLVM upstream

### PR DESCRIPTION
**Pull request by alexcrichton**
This pulls in a fix for https://bugs.llvm.org/show_bug.cgi?id=36564 which has
already landed in upstream LLVM and should...

Closes rust-lang-nursery/rust-wasm#168

### CODE REVIEW

**Comment by nagisa** [comment]
Probably a good point in time to also pull in fixes for https://github.com/rust-lang/rust/issues/50499.

Can we just bump our release_6_0 branch to what’s upstream? That will potentially also get us the other fixes backported to 6.0.

**Comment by alexcrichton** [comment]
Sure, just needs a PR to rust-lang/llvm!

**Comment by kennytm** [comment]
r=me unless we want to wait for the fix mentioned in https://github.com/rust-lang/rust/pull/50514#issuecomment-387178494.

**Comment by nagisa** [comment]
cc @cuviper, you said you wanted to do that.

**Comment by cuviper** [comment]
Do you want just those cherry-picked fixes, or a full `release_60` bump?  If the latter, do you want it as a merge or a rebase?

**Comment by alexcrichton** [comment]
I think picking up the `release_60` branch wholesale is fine, and let's merge it into `rust-llvm-release-6-0-0`

**Comment by alexcrichton** [comment]
@bors: r=kennytm

pulled in @cuviper's [update](https://github.com/rust-lang/llvm/pull/113) as well, thanks @cuviper!

**Pull request merged**
