### PR TITLE
proc_macro/bridge: remove `#[repr(C)]` from non-ABI-relevant types.

### PR DESCRIPTION
**Pull request by eddyb**
Not sure how this happened, maybe some of these were passed through the bridge a long time ago?

r? @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
The handle store seems to be used by the server at https://github.com/rust-lang/rust/blob/116201eefebcf45074ae232377e7145f5fbb704b/library/proc_macro/src/bridge/server.rs#L69

**Comment by eddyb** [comment]
@bjorn3 Yeah but that's all server-side, it doesn't cross the client<->server ABI boundary.

**Comment by bjorn3** [comment]
I see. In that case r=me if there is no perf regression.

**Comment by mystor** [comment]
> Not sure how this happened, maybe some of these were passed through the bridge a long time ago?

It wouldn't surprise me too much if at one point in the design process, the ident for `TokenStream` was directly passed as a function argument rather than being serialized/deserialized through a buffer.

**Comment by eddyb** [comment]
Wait, the try build never triggered?

@bors try @rust-timer queue

**Comment by eddyb** [comment]
(spurious network failures)

@bors try @rust-timer queue

**Pull request merged**
