### PR TITLE
Update to rustfmt v1.4.1 / 9e960e7d6a0c6b7c46c195acbd6f92ade6eec3ba

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by lzutao** [comment]
It looks like racer and rls need to be updated too.
cc @Xanewok

**Comment by mati865** [comment]
It's waiting on https://github.com/racer-rust/racer/pull/1061, aslo see https://github.com/racer-rust/racer/pull/1060

**Comment by Xanewok** [comment]
Pulled Rustfmt update in https://github.com/rust-lang/rust/pull/62805

**Comment by SimonSapin** [comment]
Thanks! Closing in favor of #62805.

**Pull request closed without merging**
