### PR TITLE
Clarify Iterator::position doc

### PR DESCRIPTION
**Pull request by shahn**
Extend the example a little bit to show behaviour better.

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Could you remove the cargo submodule changes? Other than that, looks great, thanks!

**Comment by shahn** [comment]
Wow how embarrassing, I don't know how that happened :( Fixed hopefully

**Comment by steveklabnik** [comment]
It's no biggie! It happens all the time.

**Pull request merged**
