### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by JohnTitor**
cc https://github.com/rust-lang/rust-clippy/pull/4493

r? @oli-obk

### CODE REVIEW

**Comment by flip1995** [comment]
Would you mind bumping Clippy one more time? An ICE fix landed, just now: rust-lang/rust-clippy#4486

**Comment by JohnTitor** [comment]
@flip1995 Sure! updated

**Comment by JohnTitor** [comment]
@oli-obk could you run `bors retry`?

**Comment by phansch** [comment]
Maybe I can? (not sure if I understand the team/submodule permissions correctly)

@bors retry

**Comment by flip1995** [comment]
Every bors project has its own list for reviewers/tryers. Here's the one for rust: https://team-api.infra.rust-lang.org/v1/permissions/bors.rust.try.json

You can see those of other projects by changing the name at the end of the URL. (Not sure if there's a easier way to access this list though)

**Pull request merged**
