### PR TITLE
Fixed some occurrences of 'if' being spelled 'iff'

### PR DESCRIPTION
**Pull request by Esption**
I noticed in docs, specifically http://doc.rust-lang.org/std/primitive.u8.html#method.is_power_of_two, that it was like this, and it was apparently in multiple places too.

Didn't change any occurrences through the cross-depo things. There's a lot in /src/llvm/ for instance, but I'm not confident on how to go about sending fixes for those, so this is just what's in the base rust depo.

r? @steveklabnik

### CODE REVIEW

**Comment by killercup** [comment]
I've been told that "iff" is short for "if and only if" ([Wikipedia](https://en.wikipedia.org/wiki/If_and_only_if) confirms this).

**Comment by Esption** [comment]
Ahh, well I feel dumb then. Well TIL I guess.

**Comment by tomjakubowski** [comment]
I think use of "iff" in API docs should probably be replaced with "if, and only if,", unless it's in a highly technical section that already discusses things in mathematical terms (like a proof of some algorithm's correctness).

**Comment by steveklabnik** [comment]
@tomjakubowski agreed. Almost all of these are not in documentation, but I would accept a patch that changed it to be more explicit in user-facing stuff

**Comment by Esption** [comment]
@steveklabnik Okay, then I'll undo the "iff" -> 'if" from the last commit and the rustdoc comments that had "iff" will rename to "if and only if"

**Comment by pnkfelix** [comment]
r=pnkfelix

**Comment by tshepang** [comment]
`is_power_of_two` is one weird method; never seen anything like it before

**Pull request merged**
