### PR TITLE
libstd: deny(elided_lifetimes_in_paths)

### PR DESCRIPTION
**Pull request by Centril**
r? @oli-obk

### CODE REVIEW

**Comment by Centril** [comment]
@oli-obk Should hopefully be good to go now. :)

**Comment by Centril** [comment]
I'm going to take the liberty to @bors r=oli-obk since only minor things changed :)

**Comment by kennytm** [comment]
@bors r-

The SGX target contained hidden lifetime parameters.

**Comment by Centril** [comment]
Fixed those... 😓 

@bors r=oli-obk

**Pull request merged**
