### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by cuviper**
- Only add an automatic SONAME for Rust dylibs #130960
- Reject leading unsafe in `cfg!(...)` and `--check-cfg` #131057, resolving https://github.com/rust-lang/rust/issues/131055
- Disable jump threading `UnOp::Not` for non-bool #131201 
- Update LLVM submodule #131448 
- Split x86_64-msvc-ext into two jobs #130072
- Use a small runner for msvc-ext2 job #130151 

r? ghost

### CODE REVIEW

**Comment by cuviper** [comment]
There are a couple more nominated backports as well, so I'll hold off a few days in case they're accepted...
https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Aclosed+label%3Abeta-nominated

**Comment by jieyouxu** [comment]
@cuviper the passing current cargo to run-make one is kind of funny, because that alone might've unblock the beta backport but...

- That *alone* requires building an off-by-one stage cargo: fixed in https://github.com/rust-lang/rust/pull/130739
- But https://github.com/rust-lang/rust/pull/130739 alone will lead to unnecessary stage 1 cargo rebuilds: fixed in https://github.com/rust-lang/rust/pull/131155

You previously said

> I already worked around the problem on beta by marking those tests `only-nightly`, but we can revert that if we backport this as a better fix.

So if https://github.com/rust-lang/rust/pull/130642 isn't *necessary*, I would recommend not backporting it.

**Comment by cuviper** [comment]
Yeah, I agree we probably don't need #130642, and I forgot that I nominated it myself :grimacing: -- I'll drop that.

**Comment by tgross35** [comment]
Oh - do we not have the mitigations for the MSVC failure on the beta branch?

@bors retry

**Comment by cuviper** [comment]
What's the mitigation? I should probably backport it too.

**Comment by tgross35** [comment]
I think currently we have https://github.com/rust-lang/rust/pull/130151 and https://github.com/rust-lang/rust/pull/130072 (cc @chrisdenton)

**Comment by cuviper** [comment]
Thanks! I went ahead and backported them.

**Pull request merged**
