### PR TITLE
Update stdarch submodule to latest head

### PR DESCRIPTION
**Pull request by vertexclique**
Includes avx512 work & aarch64 tme.

### CODE REVIEW

**Comment by vertexclique** [comment]
@Amanieu failed on Linux, might be hwcap issue?

**Comment by Mark-Simulacrum** [comment]
(Continuing from the other thread)

We generally want `x.py doc src/libstd --stage 0` to "just work" because it's significantly better for docs contributors as opposed to forcing them to build a full std/compiler toolchain just to document std. However, that said, I am surprised to see this working with the rustc bootstrap compiler which ran x.py check on that crate already? Is there some bug in bootstrap perhaps that is only sometimes passing --cfg bootstrap?

**Comment by Amanieu** [comment]
It seems that CI is running a stage0 rustdoc which doesn't understand the "tme" feature as part of the mingw-check builder.

I'm not exactly sure what the right course of action is here. cc @pietroalbini

**Comment by Amanieu** [comment]
So it seems that this is caused by https://github.com/rust-lang/rust/pull/56627:

> So far this starts to enable the `std::arch` in stage0 builds of rustc.
This means that we may need stage0/not(stage0) in stdsimd itself, but
more and more code is starting to use `std::arch` so I think it's time
to start shifting the balance of work here.

I guess we'll just need to add `cfg(bootstrap)` to stdarch.

**Comment by Mark-Simulacrum** [comment]
In the cases where we do need it I'm hoping we can make sure that the current nightly compiler will still work -- i.e., that you just get a less featureful stdsimd but not actually breakage when we upgrade the bootstrap compiler. If that's not possible then please ping me when landing such a change, as it means we need to bump stdsimd when bumping the bootstrap compiler in rust-lang/rust (and in the long run probably means we should subtree/merge in stdsimd to this repo).

**Comment by Amanieu** [comment]
The TME instructions are not available on any physical CPU yet (and I don't think even QEMU supports them), so I doubt this will cause any breakage in practice.

**Comment by vertexclique** [comment]
> The TME instructions are not available on any physical CPU yet (and I don't think even QEMU supports them), so I doubt this will cause any breakage in practice.

Yes, yes, and yes. So far only llvm and gcc incorporated this support.

**Comment by vertexclique** [comment]
Can someone add this to rollup if it is ok?

**Pull request merged**
