### PR TITLE
Do not consider `#` an emoji in the lexer

### LINKED ISSUE #109746: regression: no emojis in lifetime names (despite no emojis being present?)
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/solores-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/tuix_derive-0.2.0/log.txt

Not clear what the cause here is, but worth figuring out.

### PR DESCRIPTION
**Pull request by estebank**
Fix #109746. [Some unexpected ASCII chars are considered emoji by `rust-unic`](https://github.com/open-i18n/rust-unic/issues/280), so we exclude them ourselves.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Can you link to https://github.com/open-i18n/rust-unic/issues/280 ? I think that may be the root cause of the issue.

r=me afterwards
@bors rollup

**Comment by compiler-errors** [comment]
Actually, rust-unic doesn't seem to have been updated since 2020. I'm actually feeling like we may want to unland the original fix and fix the issue with `'emoji` in a better way :cold_sweat: ....

**Comment by compiler-errors** [comment]
Well, this is beta nominated anyways, so perhaps let's use that as an opportunity to discuss this in the compiler meeting tomorrow morning. r=me if we decide to go forward with this fix during that time.

**Comment by estebank** [comment]
We've been using rust-unic in the lexer for a while now to recover identifiers with emojis in general, the PR with the regression only added a path to recover lifetimes in particular. Other codepaths were already excluding ASCII codepoints from consideration. It is disappointing to see such a useful project fall into disrepair, but maybe we can (as a separate effort) try to contact the maintainers (I see @CAD97 was involved a few years back and might be amenable to doing code reviews for fixes?). Otherwise, we could move to another crate like [emojis](https://crates.io/crates/emojis) for the checks.

**Comment by CAD97** [comment]
I can do code review, but I don't think I have publish rights (would need to double check), so it'd have to be published as a fork.

Nowadays I'd recommend building on icu4x if possible since that has a real backing rather than relying on the bandwidth of just one person for management.

A big advantage of icu4x is that the data provider can be separated from the algorithm/API provider, so the former doesn't have to wait on the latter for updates, and you get to choose exactly what data you pack. [Here's the relevant loader.](https://docs.rs/icu_properties/latest/icu_properties/sets/fn.load_emoji.html)

(I also fell out of favor with unic's project structure around the time of my most recent commit landing there, and again nowadays tend to prefer icu4x. I can try to email @behnam over the weekend to see if I can get publishing permissions to keep what unic does have updated.)

**Comment by apiraino** [comment]
Beta backport declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-03-30/near/345695160). Seems a safer choice to revert #108031

@rustbot label -beta-nominated

**Comment by Manishearth** [comment]
So an annoying thing is that what is and isn't an emoji is kinda font-dependent too.

There are a couple properties that may be useful here:

 - [`Emoji_Presentation`](https://www.unicode.org/reports/tr51/#def_emoji_presentation) ([list](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AEmoji_Presentation%3A%5D&g=&i=)): This should render as an emoji by default 
 - [`Extended_Pictographic`](https://www.unicode.org/reports/tr51/#def_level1_emoji)  ([list](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AExtended_Pictographic%3A%5D&g=&i=)): This character is pictographic and not from a writing system. Contains a lot of symbols too.
 - [`Emoji`](https://www.unicode.org/reports/tr51/#def_emoji_character) ([list](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AEmoji%3A%5D&g=&i=)): Unicode considers it acceptable to render this character as an emoji, even if it does not recommend it by default. This contains a lot of stuff applications like Discord choose to render as emoji (e.g. ™, though I think Discord no longer does that particular one)

I _suspect_ what you want is the first one. It's not perfect, but it's probably better. [Here's what it excludes from `Emoji`](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3Aemoji_presentation%3DNo%3A%5D%26%5B%3Aemoji%3A%5D&g=&i=XID_Continue). Note that only those with `XIDC=N` are relevant for this diagnostic since it's triggered by lex errors.


Yes, ICU4X has APIs for all of these properties, e.g. [`icu::properties::sets::load_emoji_presentation()`](https://icu4x.unicode.org/doc/icu/properties/sets/fn.load_emoji_presentation.html).

**Comment by CAD97** [comment]
To the specific case of this diagnostic, the "best" solution would probably be to somehow gate the "likely bad identifier" codepath to only characters which would otherwise get the "unknown start of token" error. `` `©` is not allowed in identifiers`` is probably essentially as useful as ``identifiers cannot contain emoji: `©` ``, anyway.

**Comment by Manishearth** [comment]
Yeah though I think switching to Emoji_Presentation will also be a win.

**Comment by Manishearth** [comment]
Also, the latest UAX 31 draft does have [an extension for emoji in identifiers](https://www.unicode.org/reports/tr31/tr31-38.html#Emoji_Profile) which we could include if someone is up to writing an RFC (I'm happy to let them know what would be required and help them along).

**Comment by CAD97** [comment]
Ooh, that's cool! Even if Rust doesn't use it for allowed identifiers (without a technical limitation, I don't see a reason not to, given we already support all sorts of "bad" identifiers via the normal XID sets), using that specification for the recognizing of bad identifiers for nicer errors makes a lot of sense.

The only thing that worries me a little is that part of it is

> The removal of the code point U+FE0E VARIATION SELECTOR-15 (the Text Presentation Selector) from the set *Continue*.

which unless that codepoint is in the RGI emoji set added to both *Start* and *Continue*, makes the change make some strings which are currently identifiers not. (I understand the purpose: to prevent the use of an allowed identifier emoji in text presentation. And there's no simple way to say "allowed, but only after a codepoint which isn't part of an emoji sequence.") Though the use of this codepoint in a valid identifier should be rare enough that this should be fine? I guess that's for the eventual RFC to hash out.

**Comment by Manishearth** [comment]
>  there's no simple way to say "allowed, but only after a codepoint which isn't part of an emoji sequence."

It's the opposite: the spec allows it after certain emoji-capable codepoints. But yes, this complicates things. For backcompat it probably makes sense to not touch VS and maybe just exclude emoji that contain characters that are current Rust syntax tokens (it's a very small handful)

**Comment by CAD97** [comment]
Well, I've confused myself sufficiently for today. VS15 = text presentation, VS16 = emoji presentation. The emoji profile removes VS15 from the identifier *Continue*, uses VS15 for marking the set of characters which are both pattern syntax and emoji presentation as syntax instead of identifiers, removes VS16 from the operator *Continue*, and has an example of using VS16(?) to mark ☕ as not an identifier, but syntax instead.

I *think* that because Rust doesn't use Pattern_Syntax for defining the set of syntactically meaningful characters, instead using a small list of ASCII (though IIRC all are in Pattern_Syntax), none of the characters in `[[:Pattern_Syntax:]&[:Emoji_Presentation:]]`[^e] should present an ambiguity for Rust, and we should just be able to continue to allow VS15 in identifiers without problems.

[^e]: From iterating over the set with the regex crate: ⌚⌛⏩⏪⏫⏬⏰⏳◽◾☔☕♈♉♊♋♌♍♎♏♐♑♒♓♿⚓⚡⚪⚫⚽⚾⛄⛅⛎⛔⛪⛲⛳⛵⛺⛽✅✊✋✨❌❎❓❔❕❗➕➖➗➰➿⬛⬜⭐⭕

Or perhaps you're saying to exclude those characters from identifiers, since following them with VS15 should by the standard emoji profile make them behave as syntax instead of identifier.

Or perhaps you're just referring to cases like *️⃣, which is `*` followed by VS16 and a combining enclosing keycap. I don't _think_ allowing these would cause any issues for actual emoji-in-identifiers support (though obviously it would for use just for improved diagnostics). What might result in interesting behavior is whether peoples' editors type ☺️ as `☺` (single codepoint, disallowed) or `☺️` (with VS16, allowed). (Chance the distinction survives getting posted as a GitHub comment: low. My Android inserts the VS16.)

It'd be nice if the UAX could make the handling of VS15 a bit clearer without having to read UTS51. I thought I understood[^0] without knowing the intricacies of emoji sequences, just the basics, but now I'm not sure I do anymore. The maybe-typo of using U+FE0F VS16 in the operator example instead of U+FE0E VS15 like discussed in the following prose certainly doesn't help.

[^0]: What I initially read as the section resulting in: VS15 (text presentation) is no longer allowed in identifiers. VS16 (emoji presentation) is no longer allowed in syntax/operators. VS15 can be used to mark characters that changed from syntax to identifiers as syntax again.

Rephrasing, if I understood the spec correctly, the handling of VS15 is just to handle the emoji which are considered syntax. An alternative handling would be to instead just forbid the use of those characters as syntax (this is already the case in Rust), not adding them-plus-VS15 to the set of characters with syntactic use. Thus we can leave VS15 in identifiers without any issue.

I'm obviously interested in being clued in if/when an RFC is posted to adopt the emoji profile for Rust identifiers. But until then this doesn't matter too much.

**Comment by Manishearth** [comment]
Yeah, and also I certainly am not planning on proposing this

I _may_ propose an RFC for ZWNJ in the identifier profile, and I _may_ propose some lint improvements as PRs. I would help someone doing a mathematical symbols thing and would sketch out what needs to be done for someone wanting to do emoji, but I don't think we have anyone who wants to do that.

**Pull request closed without merging**
