### PR TITLE
Bump rust-installer

### PR DESCRIPTION
**Pull request by jonhoo**
Makes generation of `manifest.in` deterministic:
https://github.com/rust-lang/rust-installer/pull/120

### CODE REVIEW

**Comment by jonhoo** [comment]
r? @Mark-Simulacrum 

probably given he approved the initial rust-installer PR

**Comment by Mark-Simulacrum** [comment]
@bors try

Want to produce a dev-static nightly just in case, but not expecting any problems.

**Comment by Mark-Simulacrum** [comment]
Kicked off dev-static nightly...

**Comment by Mark-Simulacrum** [comment]
dev-static nightly [published](https://forge.rust-lang.org/release/process.html#publishing-a-nightly-based-off-a-try-build), seems to install OK for me so going to go ahead and approve. @bors r+

**Pull request merged**
