### PR TITLE
diagnostics: remove trailing spaces

### PR DESCRIPTION
**Pull request by klensy**
Remove few occurrences of trailing spaces and drive by fix of needless alloc of const string.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
lol 

@bors rollup=iffy

**Comment by Dylan-DPC** [comment]
bors r=oli-obk

**Comment by Dylan-DPC** [comment]
@bors r=oli-obk 

(sorry for the noise :P)

**Comment by klensy** [comment]
Rebased. Tests rot quite fast, sadly.

**Comment by klensy** [comment]
job `auto (i686-gnu-nopt, ubuntu-20.04-xl)`: looks like it hangs.

**Pull request merged**
