### PR TITLE
add Rust By Example to the bookshelf

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
cc #46194

With #46196 freshly merged, we should add a link to the main docs distribution so people can find it! We discussed this at the docs team meeting today and decided to go ahead with adding it to the bookshelf.

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]
yayyy looks good!

**Comment by frewsxcv** [comment]
Is this waiting on anything ? If not r=me

**Comment by QuietMisdreavus** [comment]
I don't think this is waiting on anything administrative. RBE is already being rendered and included with the official docs - <https://doc.rust-lang.org/nightly/rust-by-example/> exists right now. Travis had an issue where they had issues with builds getting backed up yesterday, so it never ran on this PR. I just restarted it, so it looks like we can wait for linkchecker if you want.

**Review by steveklabnik — APPROVED** [review]

**Pull request merged**
