### PR TITLE
Improve the message for parser_incorrect_semicolon

### LINKED ISSUE #100607: Slightly improve no return for returning function error
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=5eb617461b6c4128c6201c83b00f0d47)

```rust
fn func() -> i32 {
    123;
}

fn main() {
    
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:1:14
  |
1 | fn func() -> i32 {
  |    ----      ^^^ expected `i32`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
2 |     123;
  |        - help: remove this semicolon

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like have a small note directly behind "- help: remove this semicolon" that says " for implicit return". As I have witness a beginner getting confused as to why certain lines of code in a function require semicolon but not others. (The added note wording might need further amendments).

### PR DESCRIPTION
**Pull request by reez12g**
fixes https://github.com/rust-lang/rust/issues/100607

### CODE REVIEW

**Comment by compiler-errors** [comment]
I don't think the message you edited is actually the change you want to make. See the CI failure:

```diff
9	   |
10	LL | struct S {};
-	   |            ^ help: remove this semicolon
+	   |            ^ help: remove this semicolon for implicit return
12	   |
```

**Comment by Rageking8** [comment]
@reez12g Are you still working on this?

**Comment by Rageking8** [comment]
Due to @reez12g inactivity for this PR, I went ahead and proceeded to create another PR to resolve the issue(#100607): #102650. Hence, I believe this PR can be closed. Thanks.

**Comment by Rageking8** [comment]
@compiler-errors  sorry for the ping, but can you close this PR as complete since it's just an inactive duplicate of #102650 which has already been merged. Thanks.

**Pull request closed without merging**
