### PR TITLE
[MIR] Rvalue::ty infallible + remove TypedConstVal

### PR DESCRIPTION
**Pull request by nagisa**
Feel free to r+ whenever there aren't any big bit-rot sensitive PRs in the queue.

r? @eddyb

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by arielb1** [comment]
```

Cloning into 'cargo'...
fatal: unable to access 'https://github.com/rust-lang/cargo/': gnutls_handshake() failed: Error in the pull function.


command did not execute successfully: "git" "clone" "--depth" "1" "--branch" "master" "https://github.com/rust-lang/cargo"
```

@bors retry

**Pull request merged**
