### PR TITLE
add test where we ignore hr implied bounds

### PR DESCRIPTION
**Pull request by lcnr**
r? types

### CODE REVIEW

**Comment by oli-obk** [comment]
Can you add a variant of the test that should keep failing if that one starts passing?

**Comment by lcnr** [comment]
hmm, not sure what such a test would look like :thinking: the note "We have to be careful as implied bounds are only sound if they're also correctly checked" was more about implied bounds in general and includes stuff like #25860, #84591, and #100051.

**Comment by the8472** [comment]
> Can you add a variant of the test that should keep failing if that one starts passing?

There is the `should-fail` directive for that. And if you don't want to check the error output then there's a `known-bug` directive

**Pull request merged**
