### PR TITLE
fixing configure so that it works on bitrig/openbsd

### PR DESCRIPTION
**Pull request by dhuseby**
this fixes the issue the bitrig autobuilder is running into.

### CODE REVIEW

**Comment by Manishearth** [comment]
http://buildbot.rust-lang.org/builders/auto-bitrig-64-opt/builds/101/steps/clean/logs/stdio

still fails :/

**Comment by semarie** [comment]
hum...`make` (BSD version from base) instead of `gmake` (GNU version from ports) ?

**Comment by dhuseby** [comment]
yup.  it needs to run gmake.  when I build on bitrig, it properly detects the presence of gmake and uses that instead of make.  so maybe this is a problem with the build scripts?

**Comment by semarie** [comment]
@dhuseby a patch is coming in rust-buildbot

**Comment by dhuseby** [comment]
@semarie thanks.  which PR?

**Comment by semarie** [comment]
https://github.com/rust-lang/rust-buildbot/pull/10

**Comment by dhuseby** [comment]
@semarie why doesn't this affect openbsd as well?

**Comment by dhuseby** [comment]
oh, nvrmnd.  it does, but you don't have a build bot.

**Pull request merged**
