### PR TITLE
Added version 7.3* for Apple's clang compiler

### LINKED ISSUE #32442: Can't configure on OSX (nightly)
After updating Xcode, running `./configure` results in:

    configure: error: bad APPLE CLANG version: 7.3.0, need >=7.0

     % clang --version
    Apple LLVM version 7.3.0 (clang-703.0.29)
    Target: x86_64-apple-darwin15.4.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### PR DESCRIPTION
**Pull request by agbaroni**
The recent 7.3 clang version was missing.

Closes #32442

### CODE REVIEW

**Comment by tamird** [comment]
Perhaps it's time to allow any `7.x`?

**Comment by nagisa** [comment]
The original change seems to have landed through the rollup, but the PR itself seems to have changed in weird ways since rollup was started, thus didn’t get closed automatically.

**Pull request closed without merging**
