### PR TITLE
Make inline assembly volatile if it has no outputs. Fixes #46026

### LINKED ISSUE #46026: Add an error for inline assembly which are non-volatile without any outputs
https://github.com/rust-lang/rust/pull/45920 turned up some usages of inline assembly which have no outputs. LLVM will just remove such inline assembly as they can never be used. We should make this an error.

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by kennytm** [comment]
🤔 Is it possible to write a test for this?

**Comment by Zoxc** [comment]
Added a test.

r? @eddyb

**Comment by alexcrichton** [comment]
If LLVM has this option then presumably it's useful for someone at some point? In the sense of "you probably want this" but perhaps not always? For those users that may wish to turn this off, would they have any recourse?

**Comment by Zoxc** [comment]
You always want this behavior.

**Comment by alexcrichton** [comment]
@Zoxc as the reviewer of a PR it's sort of my job to understand why we would want such a change, what the change itself is doing, and if possible there's an alternative route to achieving the final goal. To understand this change there is no description on this PR, no comments indicating what the change is doing on the PR itself, an issue [opened by yourself](https://github.com/rust-lang/rust/issues/46026) which advocates a different solution, a [reference](https://github.com/rust-lang/rust/pull/45920) to [another PR](https://github.com/rust-lang-nursery/compiler-builtins/pull/207) fixing a similar bug, and only internal comments which say what's happening rather than why.

I am not personally intimately familiar with either inline assembly or volatile inline assembly. When I ask a question like "For those users that may wish to turn this off, would they have any recourse?" I'm actually genuinely curious as to what's going on here and why this is being proposed. An answer like "You always want this behavior." basically doesn't help me at all and is very curt and seems to assume that I should obviously understand that this is the only possible change we could do.

I'd ask again, then, why doesn't LLVM do this already? Is there a use case for nonvolatile assembly with no outputs? I sort of realize that you don't seem to believe so, but have you investigated LLVM's source code for this? Test cases? Other users? Are there others we could ask?

I've found that 99% of the time if there's an option or a flag in LLVM it's there for good reason. We have been bitten many times in the past for not exposing or otherwise defaulting various options. I'd like to be sure that we should do this before approving so, and at this point I without doing what seems to be all of the investigation myself I don't have a lot to go on to make a decision on this PR.

**Comment by Zoxc** [comment]
Inline assembly expressions are pure by default, which means they can be removed if they are unused. You can tell LLVM that it has side effects by marking it "volatile"; for example disabling interrupts or changing some FPU flag. You can also say that the assembly changes memory by using the "memory" clobber. If either "volatile" or "memory" are present, LLVM can never remove the inline assembly expression.

If an inline assembly expression has no outputs and is pure, it can never be used and LLVM is free to remove it entirely. This is what happened in [compiler-builtins](https://github.com/rust-lang-nursery/compiler-builtins/pull/207). Such inline assembly expressions are useless and are pretty much guaranteed to be user errors, hence I created https://github.com/rust-lang/rust/issues/46026.

Just adding "volatile" in these cases as suggested by @parched seemed like the better option. It avoids breaking crates and we want "volatile" (and "memory") to eventually be default anyway. We should probably add both "volatile" and "memory" if neither "volatile" or "memory" are present and the inline assembly has no output. Adding both is more conservative, although I suspect "memory" is a stronger constraint than "volatile".

If we do this we can write `asm!("cli"::::"volatile")` to get LLVM "volatile" inline assembly, `asm!("cli":::"memory")` to get LLVM "memory" inline assembly. `asm!("cli")` will get us LLVM "volatile" and "memory" inline assembly. If we want the current behavior for `asm!("cli")` we can just remove the inline assembly expression.

**Comment by petrochenkov** [comment]
>Such inline assembly expressions are useless and are pretty much guaranteed to be user errors

Unless they are produced by some kind of macro or code generator, then LLVM removing them is exactly the desired outcome.
(I can't give a concrete example though.)

**Comment by rkruppe** [comment]
What counts as "output" for the purposes of this code? Is it the `=` constraint (e.g., `=r`, `=*m`)? If so,  I *believe* I agree with @Zoxc's reasoning that inline asm without outputs and "volatile" is likely a user error, pointing to this part of the language reference:

> Inline asms with side effects not visible in the constraint list must be marked as having side effects. This is done through the use of the ‘sideeffect‘ keyword, like so:

However, it is far from obvious to me that silently adding the side-effects flag is the right option. I'd favor giving the user an error, for several reasons:

- as @sunfishcode said in #46026, "inline asm is uncommon and extraordinarily unsafe, conditions which generally favor explicitness over implicitness"
- re: breaking crates, it could be a deny-by-default lint
- *Silently* fixing the user's mistake passes up an opportunity to teach them about the need for "volatile" and/or "memory", which will come back to bite them if they later write some inline asm that does have outputs but *also* has side effects beyond what's declared in the output constraints.
- I am not sure I understand this statement by @Zoxc correctly:
  > we want "volatile" (and "memory") to eventually be default anyway.

  ... but if it is taken to refer to all inline asm everywhere, then I disagree and don't see why we would want that.

**Comment by arielb1** [comment]
@Zoxc

It feels more natural to have a lint against this rather than to implicitly "DWIM":
1. it would not give problems with macros
2. DWIM can be surprising: if someone adds an output that is ignored in some configurations, their code will randomly be optimized out.

**Comment by kennytm** [comment]
All @Zoxc, it seems the majority here prefer to emit a deny-by-fault lint instead of silently make the asm `"volatile"`. Would you mind to change the PR to emit a lint, or is DWIM still a better choice?

**Comment by Amanieu** [comment]
See this line from the [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Volatile):

> `asm` statements that have no output operands, including `asm goto` statements, are implicitly volatile.

Matching the GCC/Clang behavior here is probably a good idea.

**Comment by rkruppe** [comment]
I was working under the assumption that Clang differs from GCC here, but [apparently it doesn't](https://godbolt.org/g/EXGbnH).

Not matching C compiler is unfortunate, but the arguments in favor of an error still stand. Since it's not a *silent* mismatch, I don't see it causing a lot of trouble (i.e., if someone ports inline asm without outputs from C, they'll get a deny-by-default lint rather than miscompilation).

**Comment by Zoxc** [comment]
> I am not sure I understand this statement by @Zoxc correctly:
> 
> we want "volatile" (and "memory") to eventually be default anyway.
> ... but if it is taken to refer to all inline asm everywhere, then I disagree and don't see why we would want that.

What I want is for all inline assembly to be volatile by default. If you want purity you have to explicitly opt-in by marking the assembly `pure`. This is consistent with Rust approach of safety by default. It is also an ergonomic default since most inline assembly needs to be volatile.

**Comment by rkruppe** [comment]
I can see the appeal of defaulting to volatile. Is that plan written down anywhere else? Does it have buy-in from others?

**Comment by Zoxc** [comment]
@rkruppe There is this thing: https://internals.rust-lang.org/t/inline-assembly-syntax/239

**Comment by rkruppe** [comment]
Okay, interesting. However, that's a far bigger and more radical proposal than just making volatile the default. It's also quite old, and has received relatively little discussion compared to its size and radicalness (surely explained by the smaller size of the Rust community in 2014).

In any case, it doesn't seem like any bigger changes to inline asm are sure to happen soon, so this doesn't really change my position re: this narrower patch. Specifically,

- if "volatile by default" does happen (which I'd welcome!), this patch is obsolete
- if it doesn't happen, I stand by my reasoning that DWIM treatment of inline asm without outputs is strictly worse than a deny-by-default-lint

**Comment by Amanieu** [comment]
I am opposed to changing the current `asm!` macro and enabling volatile by default since this would be a silent change to the semantics of all the inline asm currently in use. However I wouldn't mind having that as part of a larger rework of inline assembly.

Regardless, I feel that such a change is outside the scope of this issue. I see only two options here:

- Follow GCC/Clang's inline asm semantics and automatically mark inline asm statements with no outputs as volatile.
- Emit a deny-by-default lint whenever an inline asm statement has no outputs and isn't marked as volatile.

I don't have any particular preference for either of these options.

**Comment by kennytm** [comment]
Triage —

Evidently this feature generated many possible directions but we have no clear decision which way to take. Perhaps this needs some sort of Pre-RFC. Anyway I'm nominating this to @rust-lang/lang for discussion whether to keep this PR open or switch to another approach. 

Current possible solutions on table are:

### `volatile` if no output, non-`volatile` otherwise (this PR as-is)

* Pro: [`volatile` when no output is the only correct behavior](https://github.com/rust-lang/rust/pull/46030#issuecomment-345266867)
* Pro: [matches the GCC/clang's behavior](https://github.com/rust-lang/rust/pull/46030#issuecomment-346327806)
* Cons: [not friendly for code generator / macros](https://github.com/rust-lang/rust/pull/46030#issuecomment-345427422)

### Lint (deny by default) if no output and not volatile

* Pro: [LLVM allows it, so probably useful for some reason](https://github.com/rust-lang/rust/pull/46030#issuecomment-345262529)
* Pro: [favor explicitness over implicitness](https://github.com/rust-lang/rust/pull/46030#issuecomment-345431910)

### `volatile` is default, require `pure` mark to negate

* Pro: [consistent with Rust's approach i.e. safety by default](https://github.com/rust-lang/rust/pull/46030#issuecomment-346334561)
* Pro: [more ergonomic as most inline ASM needs to be volatile](https://github.com/rust-lang/rust/pull/46030#issuecomment-346334561)
* Cons: [silent change to semantics of all inline ASM currently in use](https://github.com/rust-lang/rust/pull/46030#issuecomment-346974068)

**Comment by joshtriplett** [comment]
Personally, I greatly prefer the approach of just automatically implying `volatile` if an `asm!` has no output. I have a hard time thinking of any possible `asm!` block that has no outputs yet does *not* need to be treated as `volatile`.

I would propose the following invitation: if *anyone* can suggest a *single* `asm!` block that has no outputs yet should *not* be marked as `volatile`, then we should either go with the lint approach, or at the very least add some attribute that turns *off* `volatile` so that such blocks can use it; either way, that probably needs an RFC. (Or we could look at the nature of the `asm!` block proposed to figure out if we can do that automatically somehow.) If *nobody* can suggest even one such `asm!` block by, say, two weeks from now (2017-12-20), then I'd propose we accept this as written.

In the spirit of inviting widespread consideration of that, I'd also propose that we feature this PR in This Week in Rust and post it on the rustlang Twitter.

Does that sound reasonable?

(In the interim, however, I don't think we should accept this without a corresponding patch to the documentation of `asm!`. @Zoxc, can you please propose one?)

**Comment by whitequark** [comment]
```rust
fn is_the_optimizer_on() -> bool {
  unsafe {
    asm!("mov r0, 1":::"volatile")
    asm!("mov r0, 0":::)
    let x: usize;
    asm!("mov %0, 0"::"=r"(x):);
    x == 1
  }
}
```

**Comment by joshtriplett** [comment]
@whitequark OK, that was hilarious.

That said, given that that code is effectively *broken* by the optimizer to not work the way it's written, and that there's no particular guarantee the optimization that eliminates the second `asm!` wouldn't be done in `-O0` (LLVM does do *some* "free" optimizations even in `-O0`), I don't think a block that specifically *relies* on the elimination of not-actually-dead code should count. There's also no guarantee that `r0` won't be used for something else by compiler-generated code, since it isn't marked as used or clobbered by those blocks, and since the blocks aren't connected in any way (so nothing stops the compiler from putting things *between* them). Say, for instance, the compiler emitted stack-related code associated with declaring `x` and that code happened to use `r0`.

Rather, I think I would argue that it's a bug in Rust (albeit not a trivial one to fix) that it doesn't lint all three of those `asm!` blocks due to using a register they didn't talk about using, and in the first two cases, marking that register as an output. And it's also a bug in the code that it touches `r0` in multiple separate blocks and expects the value to have any correlation between those blocks.

**Comment by whitequark** [comment]
> And it's also a bug in the code that it touches r0 in multiple separate blocks and expects the value to have any correlation between those blocks.

More specifically, since the 2nd `asm!` statement is pure, it is legal to put it at any point in the function, so yeah, this function cannot possibly do what it advertises to.

**Comment by joshtriplett** [comment]
@whitequark Even if all the `asm!` statements in that function were `volatile`, it's *still* not reasonable to assume that `r0` retains its value between separate `asm!` blocks, especially not between the second and third that have Rust code between them (even a declaration). It might happen to work, but it doesn't seem reasonable to rely on.

**Comment by whitequark** [comment]
Good point, I agree.

**Comment by withoutboats** [comment]
It seems plausible that, as @petrochenkov said, asm could be codegen'd and is expected to be stripped out in this case.

**Comment by kennytm** [comment]
Triage ping @rust-lang/lang! This PR is still awaiting decision.

**Comment by rkruppe** [comment]
For cross-reference, there's a new and independent [pre-RFC for inline assembly](https://internals.rust-lang.org/t/pre-rfc-inline-assembly/6443). The discussion there has also touched upon volatile flags and inline asm with no outputs.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/lang meeting and came to the conclusion that we should do as follows:

- For now, we should match gcc/clang behavior. This is basically the one thing our current inline assembly system has going for it (it's compatible), and we should keep that.
    - this means "volatile" by default, not sure about "memory"
- It is also ok to have a warn-by-default lint that suggests making "volatile" explicit.

**Comment by shepmaster** [comment]
Ping from triage, @Zoxc ! It's been over a week since we've heard from you; will you be able to apply the feedback from the team sometime soon?

**Comment by Zoxc** [comment]
The feedback was to merge this, so someone just needs to approve it.

**Comment by nikomatsakis** [comment]
@Zoxc just to confirm, earlier you said:

> We should probably add both "volatile" and "memory" if neither "volatile" or "memory" are present and the inline assembly has no output.

Is this what gcc (and/or llvm) do by default? I think we should match them, in any case.

r=me if we are matching behavior.

**Comment by Zoxc** [comment]
The PR adds only `volatile` if there are no outputs, which matches what the GCC docs say.

**Comment by rkruppe** [comment]
Clang has less docs than GCC but empirically it also seems to do this (https://godbolt.org/g/pN2yV7 and https://godbolt.org/g/cfFr8W)

**Comment by nikomatsakis** [comment]
@rkruppe 

From godbolt:

>   call void asm sideeffect "nop", "~{dirflag},~{fpsr},~{flags}"() #2, !srcloc !2

I guess `sideeffect` is the equivalent of volatile?

**Comment by rkruppe** [comment]
> I guess sideeffect is the equivalent of volatile?

Yes, that's what it's called in LLVM IR.

**Comment by kennytm** [comment]
The test needs to be ignored on asm.js.

**Comment by pietroalbini** [comment]
Hi @Zoxc, seems like you need to update a test as per https://github.com/rust-lang/rust/pull/46030#issuecomment-361838644. Could you do that so the PR can be merged?

**Pull request merged**
