### PR TITLE
add test for wasm linker override=clang

### PR DESCRIPTION
**Pull request by reez12g**
addressing https://github.com/rust-lang/rust/issues/109728

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Test itself seems fine to me, is there a reason this is in draft mode?

**Comment by reez12g** [comment]
Thanks!
CI passed, so I remove the draft status.

**Comment by reez12g** [comment]
In that case, should we include a command in the Makefile to install clang? Perhaps something like this:
`sudo apt-get install clang && $(RUSTC) foo.rs --crate-type cdylib --target $(TARGET) -C linker=clang`

**Comment by Mark-Simulacrum** [comment]
tests/run-make/issue-84395-lto-embed-bitcode/Makefile also requires CLANG -- I think you can set this test up the same way, which should hopefully work and still run in CI.

The test-various builder already includes clang: https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/test-various/Dockerfile#L5, so I suspect this *could* have worked, just a matter of not finding it. It's possible that we could add a needs-clang attribute similar to the one in the lto-embed-bitcode test but more generic, if we have to run on test-various.

The tests themselves shouldn't install via apt or similar though.

**Comment by reez12g** [comment]
Thanks!
I modified the linker argument.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy

I'm not sure if that's enough without needs-matching-clang in terms of filtering for platforms with clang, but let's see what CI says.

**Comment by reez12g** [comment]
I added `# needs-matching-clang`

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy

Alright, let's try that.

**Pull request merged**
