### PR TITLE
Update compiler error 0030 to use new error format.

### PR DESCRIPTION
**Pull request by silenuss**
Part of #35233,
Addresses #35204

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by silenuss** [comment]
Sorry, I've been on vacation all week so I couldn't get to this. I've fixed the conflicts so things should be all good again!

**Comment by jonathandturner** [comment]
Thanks for updating!

@bors r+ rollup

**Pull request merged**
