### PR TITLE
Add O(1) `Vec -> VecDeque` conversion guarantee

### PR DESCRIPTION
**Pull request by Sp00ph**
(See #105072)

### CODE REVIEW

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

Can we guarantee that converting `Vec` to `VecDeque` (using `From`) is able to keep the original allocation, not dropping unused capacity or needing to snap to a particular element count, such as power-of-2?

https://github.com/rust-lang/libs-team/issues/138 has the justifications. Here is what I found compelling:

> By guaranteeing that this conversion be O(1), it allows users to freely convert between `Vec<T>` and `VecDeque<T>` without ever reallocating and makes it trivial to e.g. turn an existing `Vec<T>` into a FIFO queue.

> As a bonus if the O(1) conversion happens, we could delegate `VecDeque: FromIterator` to `Vec: FromIterator`, getting a bunch of optimization for free (by not needing to reimplement them on `VecDeque`) and potentially saving a bunch of monomorphization work too (since collecting an iterator into either container type can reuse the same code).

> (Could even spell it `impl<I, T> FromIterator<I> for VecDeque<T> where Vec<T>: FromIterator<I>` and never again worry about keeping them in sync.)

> I'd love to have this.  It'd be amazing to change the answer for "how do I remove a bunch of things from the front of a `Vec`?" to change from "well, let me tell you about a bunch options with `into_iter` and `drain` and ..." to "It's O(1) to convert it to a `VecDeque`, so just do that -- you can always convert it back again for just the unavoidable data movement cost anyway if you still need a `Vec`".

Be aware of the tradeoff that this complicates ever adopting a more sophisticated platform-specific deque internals, such as seen in https://crates.io/crates/slice-deque.

**Comment by CryZe** [comment]
Am I missing something or does this mean that the elements are not going to be in the order that they were in the VecDeque? It seems like guaranteeing O(1) is rather meaning that it's guaranteeing that you can't rely on the order, which may or may not be fine, though I would possibly want to see a conversion that does guarantee it.

**Comment by Sp00ph** [comment]
It's only about guaranteeing O(1) `Vec -> VecDeque` conversions, not the other way around. Converting `VecDeque -> Vec` may indeed have to rotate around memory and is therefore O(n), though it is already documented to not reallocate the buffer

**Comment by CryZe** [comment]
Yeah sorry I somehow got the direction of the impl wrong.

**Comment by workingjubilee** [comment]
If Rust had named it `Deque`, it may have made sense for it to not have an `O(1)` guaranteed conversion, but I think naming it `VecDeque` strongly recommends in favor of making this change.

**Comment by scottmcm** [comment]
More fun stuff that such an implementation enables: O(1) `vec::IntoIter` → `VecDeque` conversions.

(Done as a non-guaranteed specialization in #105453.)

**Comment by dtolnay** [comment]
I'm marking @yaahc's box because she has stepped down from T-libs-api after the point that this feature got proposed for FCP.

**Comment by BurntSushi** [comment]
> Be aware of the tradeoff that this complicates ever adopting a more sophisticated platform-specific deque internals, such as seen in https://crates.io/crates/slice-deque.

I will say that it is somewhat unfortunate that this API guarantee will prevent such a really cool trick like that, but I think the API guarantee here is probably worth it.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
