### PR TITLE
Simplify implementation for par_for_each_module

### PR DESCRIPTION
**Pull request by cjgillot**

### CODE REVIEW

**Comment by cjgillot** [comment]
Re-rolling the dice.
r? compiler

**Comment by compiler-errors** [comment]
I wonder what the perf implication of those `#[inline]` is.

@bors try @rust-timer queue

**Comment by compiler-errors** [comment]
r=me when perf comes back regardless

**Comment by compiler-errors** [comment]
That is noise. I've seen webrender getting +/- 1% perf changes on so many PRs. Posted about it [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/webrender-2022.20is.20flaky/near/294609359). r=me regardless unless you think the regressions is actually real.

**Pull request merged**
