### PR TITLE
update Miri

### PR DESCRIPTION
**Pull request by RalfJung**
Noteworthy PRs:
- https://github.com/rust-lang/miri/pull/2357
- https://github.com/rust-lang/miri/pull/2646
- https://github.com/rust-lang/miri/pull/2718
- https://github.com/rust-lang/miri/pull/2721
- https://github.com/rust-lang/miri/pull/2725

### CODE REVIEW

**Comment by RalfJung** [comment]
Strange, we have -D warnings in the Miri build but that lint did not fire...
```
 error: lifetime parameter `'tcx` never used
  --> src/tools/miri/src/shims/unix/linux/fd/socketpair.rs:18:12
   |
18 |     fn dup<'tcx>(&mut self) -> io::Result<Box<dyn FileDescriptor>> {
   |           -^^^^- help: elide the unused lifetime
```

**Comment by gimbles** [comment]
image
Is it just mine or does the Rustbot message not seem to *actually* ping rust-lang/miri? usually it's in bold

**Comment by Mark-Simulacrum** [comment]
> Strange, we have -D warnings in the Miri build but that lint did not fire...
> 
> ```
>  error: lifetime parameter `'tcx` never used
>   --> src/tools/miri/src/shims/unix/linux/fd/socketpair.rs:18:12
>    |
> 18 |     fn dup<'tcx>(&mut self) -> io::Result<Box<dyn FileDescriptor>> {
>    |           -^^^^- help: elide the unused lifetime
> ```

I don't think the lint is on by default, perhaps? rustbuild turns it on for in-tree things here: https://github.com/rust-lang/rust/blob/master/src/bootstrap/builder.rs#L1666

**Comment by RalfJung** [comment]
Ah... So we have to keep those flags in sync with our own CI then to avoid such issues.

**Comment by RalfJung** [comment]
> Is it just mine or does the Rustbot message not seem to actually ping rust-lang/miri? usually it's in bold

It is bold here. :shrug:

**Pull request merged**
