### PR TITLE
Use consistent wording in docs, use is zero instead of is 0

### PR DESCRIPTION
**Pull request by timvisee**
In documentation, wording of _"`rhs` is zero"_ and _"`rhs` is 0"_ is intermixed. This is especially visible [here](https://doc.rust-lang.org/std/primitive.usize.html#method.div_ceil).

This changes all occurrences to _"`rhs` is zero"_ for better readability.

### CODE REVIEW

**Comment by jhpratt** [comment]
> This variant has more occurrences in the code base.

A quick `rg` shows that this is _just barely_ true, 55/45 at best.

> On top of that, `rhs` refers to a numeric value.

"zero" is still a numeric value, though?

---

Personally I find "zero" easier to read, so if anything I'd prefer to standardize on that. Forcing a standardization when there are two alternatives nearly evenly split, though, is almost certainly a never-ending effort.

**Comment by timvisee** [comment]
I have no strong feeling about either variant, and am also happy to close this PR.

I just noticed this inconsistency while scrolling through the documentation and figured, lets suggest a simple change. I understand it'll be a never-ending effort to keep it like this and am not suggesting to enforce it.

> Personally I find "zero" easier to read, so if anything I'd prefer to standardize on that.

I have to agree, "zero" is easier to read.

@jhpratt Shall I switch gears and change these to "zero", or do you prefer me to close the PR and leave it as is?

> A quick rg shows that this is just barely true, 55/45 at best.

I did an exact match in which case I saw 40 matches for 0, and 14 for zero.

**Comment by jhpratt** [comment]
> I have to agree, "zero" is easier to read.

Let's shift towards that, then. Readability is the point of docs, after all :slightly_smiling_face: 

> I understand it'll be a never-ending effort to keep it like this and am not suggesting to enforce it.

For sure. I wasn't implying that you wanted to do such a thing, just making sure that you're aware it's infeasible in case you did.

**Comment by jhpratt** [comment]
Awesome, thanks!

@bors r+ rollup

**Comment by timvisee** [comment]
😄

Thanks for your time!

**Pull request merged**
