### PR TITLE
BTreeMap: move generic support functions out of navigate.rs

### PR DESCRIPTION
**Pull request by ssomers**
A preparatory step chipped off #78104, useful in general (if at all).

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by ssomers** [comment]
Note this would be another benign conflict postponing #78015 (because of the alphabetically close new module names), but to me it seems sensible to do it first.

**Comment by Mark-Simulacrum** [comment]
Oh, hm, I did not see this before that other PR. If you want to ping me on Zulip to just say "please review in this order" or whatever, that's fine by me -- otherwise I usually go in oldest first order in my waiting-on-review queue.

**Comment by Mark-Simulacrum** [comment]
r=me though on the change itself (I think I approved a similar commit elsewhere, IIRC a bit smaller but I might be misremembering)

**Comment by ssomers** [comment]
@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

Still feeding this commit separately, because it's simple and separate, even though you approved the #78104 (without the no-rollup constraint, to my surprise, but I'm just beginning to understand that process).

**Pull request merged**
