### PR TITLE
Revert "Merge CrateDisambiguator into StableCrateId"

### PR DESCRIPTION
**Pull request by bjorn3**
This reverts https://github.com/rust-lang/rust/pull/85804

### CODE REVIEW

**Comment by varkor** [comment]
Seems like a perf improvement. Going to leave to r? @Mark-Simulacrum for the decision.

**Comment by Mark-Simulacrum** [comment]
r=me, unfortunately looks like this has a bunch of merge conflicts now

**Comment by bjorn3** [comment]
Rebased

**Comment by Mark-Simulacrum** [comment]
It doesn't seem like reverting this actually recovered performance -- this PR is a [regression](https://perf.rust-lang.org/compare.html?start=022720bfccd46400e69def42f4647fe4059ad951&end=2312ff1a850db449b79fd3c4b215395cd2598c25&stat=instructions:u) just like the [merge run](https://perf.rust-lang.org/compare.html?start=2023cc3aa1ea98530f3124ed07713e6f95fd26ab&end=59579907ab52ad2369735622185a26f158bf0f0f&stat=instructions%3Au) on the original was.

@bjorn3 my guess is that *maybe* reverting the revert is a good idea but I noted you suggested some possible performance improvements on the original diff (https://github.com/rust-lang/rust/pull/85804#pullrequestreview-673167112) which might be worth considering. Ultimately seems like other PRs landing in between are likely causing problems with measuring and comparing this PR.

**Comment by bjorn3** [comment]
Revert in https://github.com/rust-lang/rust/pull/86143. I will wait with perf improvements until #85834 is merged as it introduces a method that is needed for some of the possible perf improvements.

**Pull request merged**
