### PR TITLE
Remove `compile-fail` test suite

### PR DESCRIPTION
**Pull request by petrochenkov**
By moving all of its tests to `ui` test suite.
Now we have directives like `// dont-check-compiler-stderr` that allow to disable `.stderr` comparison for platform-dependent tests without introducing a whole new test suite.

### CODE REVIEW

**Comment by lcnr** [comment]
not familiar with the affected areas, maybe

r? @Mark-Simulacrum

**Comment by petrochenkov** [comment]
PR CI (Linux) is green and I tested this locally on Windows, so this should be ready for the big CI.
It is still probably going to fail a couple of times on more exotic targets though.
@bors rollup=never

**Pull request merged**
