### PR TITLE
Subtree sync for rustc_codegen_cranelift

### PR DESCRIPTION
**Pull request by bjorn3**
The main highlight this time is a fix for a miscompilation of RwLock on macOS. Also a Cranelift update and a couple of extra vendor intrinsics on arm64.

r? @ghost

@rustbot label +A-codegen +A-cranelift +T-compiler

### CODE REVIEW

**Comment by bjorn3** [comment]
@bors retry spurious codegen test failure?

This PR doesn't change anything outside of cg_clif.

**Comment by workingjubilee** [comment]
Yes, we've been getting frequent spurious failures.

**Pull request merged**
