### PR TITLE
revert for benchmark

### PR DESCRIPTION
**Pull request by bvanjoi**
This PR reverts #118311 and #118188, with the intent to assess the performance impact brought about by #118311

### CODE REVIEW

**Comment by pnkfelix** [comment]
(As I mentioned on https://github.com/rust-lang/rust/pull/118311#issuecomment-1831918109, I don't think that measuring the effect of reverting *both* PR #118311 and PR #118188 will not tell us much about the performance impact of reverting PR #118311, because PR #118188 itself introduced a number of performance *improvements*, and so reverting that will presumably induce regressions that could well mask the effect we are trying to determine.)

**Comment by bvanjoi** [comment]
We can draw two conclusions from this PR and #118411:

- As indicated in the above comments, the combination of #118311 and #118188 resulted in an optimization
- The comment found at https://github.com/rust-lang/rust/pull/118411#issuecomment-1841531683 underlines that there's no equivalence between ﻿`ExprKind::Closure(Closure { movability: Some(_), .. }) => DefKind::Coroutine` and ﻿`tcx.coroutine_kind(def_id).is_some()`. Therefore, we can obtain some performance optimization through certain modification as demonstrated in #118411.

**Comment by bvanjoi** [comment]
So, should we consider merging #118411?

cc @petrochenkov @pnkfelix

**Comment by petrochenkov** [comment]
I wasn't assigned to this PR, so I forgot about it entirely.
This revert served its purpose, so it can be closed now.
https://github.com/rust-lang/rust/pull/118411 should be reviewed and merged in some form.

**Pull request closed without merging**
