### PR TITLE
Partial implementation of uniform paths 2.0 to land before beta

### PR DESCRIPTION
**Pull request by petrochenkov**
Reimplementation of uniform paths using in-scope resolution rather than canaries is a minor breaking change due to stricter future-proofing, so it needs to be landed before beta or backported later.

I hope to implement at least something until beta so we have less to backport.
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Beta/nightly promotion is what I think matters here and that'll happen early next week so I don't think there's a super big rush here?

**Comment by Mark-Simulacrum** [comment]
Changes look good modulo some tests though I'm not super familiar with this area if code - r=me if you don't think we need them

**Comment by petrochenkov** [comment]
>Beta/nightly promotion is what I think matters here and that'll happen early next week

Oh, that's great, I thought it's supposed to be Oct 26 (same day as stable release).
Then I'll perhaps manage to do everything during the weekend.

**Comment by Mark-Simulacrum** [comment]
We're delaying beta/nightly promotion due to RC2.

**Comment by Mark-Simulacrum** [comment]
We're delaying beta/nightly promotion due to RC2.

**Comment by pnkfelix** [comment]
@petrochenkov are you planning on doing further revision to this PR, e.g. adding tests? Or do you just want to copy over the r+ marker from @Mark-Simulacrum ?

**Comment by petrochenkov** [comment]
@pnkfelix 
Yes, during remainder of the week.
(Right now this is only refactoring, not even tests needed.)

**Comment by petrochenkov** [comment]
@Mark-Simulacrum 
Ok, no more delays. This is ready for landing and the rest I'll implement later.

All the commits are refactorings except for https://github.com/rust-lang/rust/pull/55297/commits/b45b4daba75eb6d48ebd86ac56c5ff29c3637a12 (bug-fix), https://github.com/rust-lang/rust/pull/55297/commits/acdbd0643cc3d7bd74826c0f13746c81c08d6cc1 (drive-by diagnostics improvement) and https://github.com/rust-lang/rust/pull/55297/commits/c57f0a7201860eb87ad8df1f3e63ea1ed03dcb40 (which is somewhat essential and fixes imports with empty groups (`a::b::{}`) on 2018 edition).

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=5

Beta promotion has already happened so I'll prepare a beta backport as well.

**Pull request merged**
