### PR TITLE
Fix ICE with `main`'s return type containing lifetimes

### LINKED ISSUE #48890: rustc panicked at 'assertion failed: !substs.has_erasable_regions()'
```thread 'rustc' panicked at 'assertion failed: !substs.has_erasable_regions()', librustc_trans_utils/symbol_names.rs:192:9```

I tried this code:

```rust
#![feature(termination_trait)]

extern crate metaflac     as m_flac;
extern crate mp3_metadata as m_mp3;

use std::env;
use std::error::Error;

fn main() -> Result<(), Box<Error>> {
    let path = env::args().skip(1).next().unwrap();
    let meta = m_mp3::read_from_file(path)?;
    println!("{:?}", meta);

    Ok(())
}
```

## Meta

`rustc --version --verbose`:
```
rustc 1.26.0-nightly (2789b067d 2018-03-06)
binary: rustc
commit-hash: 2789b067da2ac921b86199bde21dd231ace1da39
commit-date: 2018-03-06
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

Backtrace:
```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:403
   6: std::panicking::begin_panic
   7: rustc_trans_utils::symbol_names::symbol_name
   8: rustc::dep_graph::graph::DepGraph::with_task_impl
   9: rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::force
  10: rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::try_get
  11: rustc::ty::maps::TyCtxtAt::symbol_name
  12: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::symbol_name
  13: rustc_mir::monomorphize::item::MonoItemExt::symbol_name
  14: rustc_mir::monomorphize::assert_symbols_are_distinct
  15: rustc_trans::base::collect_and_partition_translation_items
  16: rustc::dep_graph::graph::DepGraph::with_task_impl
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'
tcx>>::force
  18: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'
tcx>>::try_get
  19: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
  20: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_
translation_items
  21: rustc_trans::base::trans_crate
  22: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  23: rustc_driver::driver::phase_4_translate_to_llvm
  24: rustc_driver::driver::compile_input::{{closure}}
  25: rustc::ty::context::TyCtxt::create_and_enter
  26: rustc_driver::driver::compile_input
  27: rustc_driver::run_compiler
```

### PR DESCRIPTION
**Pull request by sinkuu**
Fixes #48890

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362691246). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (611607/611607), completed with 4865 local objects.
---
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
The command "curl -fo /home/travis/stamp https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-03-17-stamp-x86_64-unknown-linux-musl" failed. Retrying, 2 of 3.
---
[00:01:57] configure: rust.quiet-tests     := True
---
[00:44:34] ..........................................................................i.........................
[00:44:40] .................i..................................................................................
---
[00:45:17] ..............................................................................................i.....
[00:45:24] ...................................................................i................................
---
[00:46:20] .............................................i......................................................
---
[00:50:24] .............................i......................................................................
[00:50:40] ..............................................................i.....................................
[00:50:56] ...............................................i....................................................
[00:51:17] ....................................................................................................
[00:51:40] ....................................................................................................
[00:52:03] ....................................................................................................
[00:52:28] .i...............................................................................................i..
[00:52:54] ...........................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:53:07] .........................
[00:53:39] ....................................................................................................
[00:54:16] ...............................................................ii...................................
[00:55:01] ..........................i....................................................itest [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:55:10] .ii.................
[00:55:53] .......................................................................................iiiiiii......
---
[00:58:13] ..................i............................................................ii.iii...............
[00:58:21] ....................................................................................................
[00:58:29] ........i..............................i............................................................
[00:58:37] ....................................................................................................
[00:58:44] ....................i...............................................................................
[00:58:52] ....................................................................................................
[00:59:02] ....................................................................................................
[00:59:13] ....................................................................................................
[00:59:24] ....................................................................................................
[00:59:39] ....................................................................................................
[00:59:47] .............i......................................................................................
[00:59:57] ................i..ii...............................................................................
[01:00:07] ....................................................................................................
[01:00:18] ....................................................................................................
[01:00:28] ..................................................................................i.................
[01:00:39] ............................i.......................................................................
---
[01:01:17] ...........................i........................................................................
[01:01:18] ....................................................................i...............................
[01:01:19] ................i.......................................................
---
[01:01:35] .............iF.......................
[01:01:35] failures:
[01:01:35] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:478:22
[01:01:35]
[01:01:35] ---- [run-fail] run-fail/rfc-1937-termination-trait/termination-trait-for-str.rs stdout ----
[01:01:35]
[01:01:35] error: Error: expected failure status (Some(101)) but received status Some(1).
---
[01:01:35] Error: "An error message for you"
[01:01:35]
[01:01:35] ------------------------------------------
[01:01:35]
[01:01:35] thread '[run-fail] run-fail/rfc-1937-termination-trait/termination-trait-for-str.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2901:9
---
[01:01:35] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/run-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:01:35] expected success, got: exit code: 101
[01:01:35]
[01:01:35]
[01:01:35] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:01:35] Build completed unsuccessfully in 0:18:19
[01:01:35] Makefile:58: recipe for target 'check' failed
[01:01:35] make: *** [check] Error 1
---
$ dmesg | grep -i kill
[   11.393158] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by nikomatsakis** [comment]
@sinkuu nice! Looks like you need a `// failure-status: 1` comment in the tests.

**Comment by arielb1** [comment]
Nice set of tests!

**Comment by arielb1** [comment]
@bors p=1

This is a beta-nominated PR

**Comment by scottmcm** [comment]
This was beta-nominated; what needs to happen for a beta merge?

**Comment by alexcrichton** [comment]
@scottmcm this was waiting for beta-accepted which I've now applied, so should be good to go!

(gonna review a few more and then do a lot of backports at once)

**Pull request merged**
