### PR TITLE
Introducting f32:: and f64:: ZERO and NEG_ZERO

### PR DESCRIPTION
**Pull request by milescaprio**
Change to the std library API which adds f32::ZERO, f64::ZERO, f32::NEG_ZERO, and f64::ZERO to improve consistency interfacing with IEEE-754.
Still a bit new to the system rust uses with the standard library. If there's more review to be done on this, then feel free to do so, edit my commits, or let me know if I should change anything with the code or workflow.
@rustbot label +T-libs-api -T-libs

### CODE REVIEW

**Comment by joshtriplett** [comment]
What is the advantage of using these over `0f32`/`0f64`/`-0f32`/`-0f64`?

**Comment by scottmcm** [comment]
This PR looks like it'll be mostly about policy, not about the correctness of the diff, so assigning to the libs-api member who commented here
r? @joshtriplett

**Comment by PunkyMunky64** [comment]
> What is the advantage of using these over `0f32`/`0f64`/`-0f32`/`-0f64`?

What is the advantage of using f32::INFINITY over 1f32/0f32? Clarity mostly? I thought it would just make it more consistent. Plus to some people it's unclear whether -0 will be stored differently, so NEG_ZERO could help I guess? If you don't think it's necessary that's fine

**Comment by joshtriplett** [comment]
> What is the advantage of using f32::INFINITY over 1f32/0f32?

I think that one is a clarity win, for multiple reasons. First, because we don't have a simple token that's floating-point infinity, and I think a constant adds clarity in place of an expression. And second, because while in general most environments *should* just produce infinity there, it's *possible* to configure some environments to produce an exception instead.

I don't think the same thing applies to `0f32` and `-0f32` (or just `0.0` and `-0.0`, if you don't want to write the type), which seem simpler. Also, https://doc.rust-lang.org/std/primitive.f32.html explicitly talks about `-0.0`.

**Pull request closed without merging**
