### PR TITLE
Stabilize `#![feature(mixed_integer_ops)]`

### PR DESCRIPTION
**Pull request by jhpratt**
Tracked and FCP completed in #87840.

@rustbot label +T-libs-api +S-waiting-on-review +relnotes

r? rust-lang/t-libs-api

### CODE REVIEW

**Comment by jhpratt** [comment]
Ah, I didn't realize that. Either way works for me: in theory the PRs should be identical.

**Comment by joshtriplett** [comment]
@Dylan-DPC That PR is delegated to you, and it looks ready to be merged. Any blockers for doing so?

**Comment by Dylan-DPC** [comment]
No blockers just dint have the time to update the `since` field to the new placholder

**Pull request merged**
