### PR TITLE
Fix a bug in the inliner

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb

### CODE REVIEW

**Comment by RalfJung** [comment]
You can trigger this bug without miri being involved by running the following in the miri directory:
```
xargo/build.sh # do get a libstd with all the MIR, which means the MIR inliner has more options
rustc -Zmir-opt-level=3 --sysroot=$HOME/.xargo/HOST tests/run-pass-fullmir/unsized-tuple-impls.rs
```

**Comment by eddyb** [comment]
This isn't a complete fix... I screwed up. I had `return` on both `*local = l` places,  but then didn't need to return the value so I removed `return` but now it's wrong (both args and ret ptr).

**Pull request merged**
