### PR TITLE
Rename must-compile-successfully into compile-pass

### LINKED ISSUE #49568: Rename must-compile-successfully into compile-pass
cc @Mark-Simulacrum

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #49568.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/361143733). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613552/613552), completed with 4905 local objects.
---
[00:00:45] configure: rust.quiet-tests     := True
---
[00:42:41] .........................................................................i..........................
[00:42:47] ................i...................................................................................
---
[00:43:23] ................................F...........................................................i.......
[00:43:30] ................................................................i...................................
---
[00:43:52] 8   "spans": [
[00:43:52] 9     {
[00:43:52] 10       "file_name": "$DIR/unused_parens_json_suggestion.rs",
[00:43:52] -       "byte_start": 1056,
[00:43:52] -       "byte_end": 1069,
[00:43:52] +       "byte_start": 1043,
[00:43:52] +       "byte_end": 1056,
[00:43:52] 13       "line_start": 25,
[00:43:52] 14       "line_end": 25,
[00:43:52] 15       "column_start": 14,
[00:43:52]
[00:43:52] 35       "spans": [
[00:43:52] 36         {
[00:43:52] 37           "file_name": "$DIR/unused_parens_json_suggestion.rs",
[00:43:52] -           "byte_start": 902,
[00:43:52] -           "byte_end": 915,
[00:43:52] +           "byte_start": 889,
[00:43:52] +           "byte_end": 902,
[00:43:52] 40           "line_start": 20,
[00:43:52] 41           "line_end": 20,
[00:43:52] 42           "column_start": 9,
[00:43:52]
[00:43:52] 64       "spans": [
[00:43:52] 65         {
[00:43:52] 66           "file_name": "$DIR/unused_parens_json_suggestion.rs",
[00:43:52] -           "byte_start": 1056,
[00:43:52] -           "byte_end": 1069,
[00:43:52] +           "byte_start": 1043,
[00:43:52] +           "byte_end": 1056,
[00:43:52] 69           "line_start": 25,
[00:43:52] 70           "line_end": 25,
[00:43:52] 71           "column_start": 14,
[00:43:52]
[00:43:52]
[00:43:52] The actual stderr differed from the expected stderr.
[00:43:52] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused_parens_json_suggestion.stderr
[00:43:52] To update references, run this command from build directory:
[00:43:52] /checkout/src/test/ui/update-references.sh '/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui' 'lint/unused_parens_json_suggestion.rs'
[00:43:52]
[00:43:52] error: 1 errors occurred comparing output.
[00:43:52] status: exit code: 0
[00:43:52] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/lint/unused_parens_json_suggestion.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused_parens_json_suggestion.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--error-format" "pretty-json" "-Zunstable-options" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused_parens_json_suggestion.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:43:52]   "message": "unnecessary parentheses around assigned value",
[00:43:52]   "code": {
[00:43:52]     "code": "unused_parens",
[00:43:52]     "explanation": null
[00:43:52]   },
[00:43:52]   "level": "warning",
[00:43:52]   "spans": [
[00:43:52]     {
[00:43:52]       "file_name": "/checkout/src/test/ui/lint/unused_parens_json_suggestion.rs",
[00:43:52]       "byte_start": 1043,
[00:43:52]       "byte_end": 1056,
[00:43:52]       "line_start": 25,
[00:43:52]       "line_end": 25,
[00:43:52]       "column_start": 14,
[00:43:52]       "column_end": 27,
[00:43:52]       "is_primary": true,
[00:43:52]       "text": [
[00:43:52]         {
[00:43:52]           "text": "    let _a = (1 / (2 + 3));",
[00:43:52]           "highlight_start": 14,
[00:43:52]           "highlight_end": 27
[00:43:52]         }
[00:43:52]       ],
[00:43:52]       "label": null,
[00:43:52]       "suggested_replacement": null,
[00:43:52]       "expansion": null
[00:43:52]     }
[00:43:52]   ],
[00:43:52]   "children": [
[00:43:52]     {
[00:43:52]       "message": "lint level defined here",
[00:43:52]       "code": null,
[00:43:52]       "level": "note",
[00:43:52]       "spans": [
[00:43:52]         {
[00:43:52]           "file_name": "/checkout/src/test/ui/lint/unused_parens_json_suggestion.rs",
[00:43:52]           "byte_start": 889,
[00:43:52]           "byte_end": 902,
[00:43:52]           "line_start": 20,
[00:43:52]           "line_end": 20,
[00:43:52]           "column_start": 9,
[00:43:52]           "column_end": 22,
[00:43:52]           "is_primary": true,
[00:43:52]           "text": [
[00:43:52]             {
[00:43:52]               "text": "#![warn(unused_parens)]",
[00:43:52]               "highlight_start": 9,
[00:43:52]               "highlight_end": 22
[00:43:52]             }
[00:43:52]           ],
[00:43:52]           "label": null,
[00:43:52]           "suggested_replacement": null,
[00:43:52]           "expansion": null
[00:43:52]         }
[00:43:52]       ],
[00:43:52]       "children": [],
[00:43:52]       "rendered": null
[00:43:52]     },
[00:43:52]     {
[00:43:52]       "message": "remove these parentheses",
[00:43:52]       "code": null,
[00:43:52]       "level": "help",
[00:43:52]       "spans": [
[00:43:52]         {
[00:43:52]           "file_name": "/checkout/src/test/ui/lint/unused_parens_json_suggestion.rs",
[00:43:52]           "byte_start": 1043,
[00:43:52]           "byte_end": 1056,
[00:43:52]           "line_start": 25,
[00:43:52]           "line_end": 25,
[00:43:52]           "column_start": 14,
[00:43:52]           "column_end": 27,
[00:43:52]           "is_primary": true,
[00:43:52]           "text": [
[00:43:52]             {
[00:43:52]               "text": "    let _a = (1 / (2 + 3));",
[00:43:52]               "highlight_start": 14,
[00:43:52]               "highlight_end": 27
[00:43:52]             }
[00:43:52]           ],
[00:43:52]           "label": null,
[00:43:52]           "suggested_replacement": "1 / (2 + 3)",
[00:43:52]           "expansion": null
[00:43:52]         }
[00:43:52]       ],
[00:43:52]       "children": [],
[00:43:52]       "rendered": null
[00:43:52]     }
[00:43:52]   ],
[00:43:52]   "rendered": "warning: unnecessary parentheses around assigned value\n  --> /checkout/src/test/ui/lint/unused_parens_json_suggestion.rs:25:14\n   |\nLL |     let _a = (1 / (2 + 3));\n   |              ^^^^^^^^^^^^^ help: remove these parentheses\n   |\nnote: lint level defined here\n  --> /checkout/src/test/ui/lint/unused_parens_json_suggestion.rs:20:9\n   |\nLL | #![warn(unused_parens)]\n   |         ^^^^^^^^^^^^^\n\n"
[00:43:52] }
---
[00:43:52] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_6
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by GuillaumeGomez** [comment]
Ping @Mark-Simulacrum

**Comment by alexcrichton** [comment]
@bors: retry

pushed to master, kicking bors

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362866638). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:44:26] error: ui test compiled successfully!
[00:44:26] status: exit code: 0
[00:44:26] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/generic-param-attrs.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-param-attrs.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-param-attrs.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:44:26] error: ui test compiled successfully!
[00:44:26] status: exit code: 0
[00:44:26] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/nll/issue-43058.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/issue-43058.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/issue-43058.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:44:26] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:44:26] expected success, got: exit code: 101
[00:44:26]
[00:44:26]
[00:44:26] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:44:26] Build completed unsuccessfully in 0:02:27
[00:44:26] make: *** [check] Error 1
[00:44:26] Makefile:58: recipe for target 'check' failed
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:06974448:start=1522970065855404671,finish=1522970065862485419,duration=7080748
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:0c4040dc
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:0c4040dc:start=1522970065869124309,finish=1522970065885291982,duration=16167673
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:11ec5804
$ dmesg | grep -i kill
[   10.400512] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362866638). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:44:26] error: ui test compiled successfully!
[00:44:26] status: exit code: 0
[00:44:26] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/generic-param-attrs.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-param-attrs.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-param-attrs.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:44:26] error: ui test compiled successfully!
[00:44:26] status: exit code: 0
[00:44:26] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/nll/issue-43058.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/issue-43058.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/issue-43058.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:44:26] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:44:26] expected success, got: exit code: 101
[00:44:26]
[00:44:26]
[00:44:26] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:44:26] Build completed unsuccessfully in 0:02:27
[00:44:26] make: *** [check] Error 1
[00:44:26] Makefile:58: recipe for target 'check' failed
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:06974448:start=1522970065855404671,finish=1522970065862485419,duration=7080748
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:0c4040dc
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:0c4040dc:start=1522970065869124309,finish=1522970065885291982,duration=16167673
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:11ec5804
$ dmesg | grep -i kill
[   10.400512] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by GuillaumeGomez** [comment]
Ok, updated and replaced the new `must-compile-successfully`. A high priority would come very handy in here.

cc @Mark-Simulacrum @alexcrichton

**Pull request merged**
