### PR TITLE
resolve instance: missing value to `delay_span_bug`

### PR DESCRIPTION
**Pull request by lcnr**

### CODE REVIEW

**Comment by fee1-dead** [comment]
I think it is okay to turn this into a logical error, but we might need a comment distinguishing when this returns `Ok(None)` and when this returns `Err(ErrorGuaranteed)`. Perhaps a comment to document this?

After that r=me.

**Comment by compiler-errors** [comment]
@lcnr does this fix a bug, or just being defensive against future bugs?

**Comment by lcnr** [comment]
> @lcnr does this fix a bug, or just being defensive against future bugs?

purely being defensive, though I vaguely remember that changing this in a wip PR removed some incorrect error messages :shrug:

**Pull request merged**
