### PR TITLE
Remove some unnecessary feature gates

### LINKED ISSUE #56585: Remove unnecessary stability attributes for const fn
In 8d6edc9f8f71075c55fad3c5ca5a7e28b5e01400 various stability attributes were added to functions that are not public. This was required to satisfy the min_const_fn checker. The lines in question all contain `FIXME: min_const_fn`. @oli-obk [volunteered](https://github.com/rust-lang/rust/pull/56066#discussion_r235491541) to take a look.

You should be able to test this build with a somewhat-recent nightly and
```
cargo +nightly check --target x86_64-fortanix-unknown-sgx --manifest-path src/libstd/Cargo.toml
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #56585 

cc @jethrogb

### CODE REVIEW

**Comment by jethrogb** [comment]
Mostly LGTM

For the 2 functions you removed, can you put `#[allow(unused)]` or `#[cfg(false)]` instead?

**Comment by oli-obk** [comment]
> For the 2 functions you removed, can you put #[allow(unused)] or #[cfg(false)] instead?

Any particular reason? Can't you just `git revert 1346619` when you need them?

**Comment by jethrogb** [comment]
Oh I didn't see it was a separate commit. Sure, that works.

**Pull request merged**
