### PR TITLE
Always print `aborting due to n previous error(s)`

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@estebank, could you take a look at the last commit (b1d872b)? This PR changes diagnostics output and I'd like to make sure that that's OK.

**Comment by estebank** [comment]
@michaelwoerister LGTM++

**Comment by michaelwoerister** [comment]
Looks good to me too! There seems to be some overlap with https://github.com/rust-lang/rust/pull/49030 though. I'll just approve for now. A merge conflict should be the worst that can happen.

@bors r+

**Pull request merged**
