### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
- Successful merges: #45635, #45987, #46031, #46050, #46052, #46103, #46134, #46141, #46155, #46120, #46148
- Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r-

Needs to take out #45635 again, the macro `-Z` flag thing broke the UI test.

**Comment by MaloJaffre** [comment]
The Travis error seems legit:
```
Check compiletest suite=ui-fulldeps mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

[00:53:08] 

[00:53:08] running 9 tests

[00:53:13] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:331:21

[00:53:13] F........

[00:53:13] failures:

[00:53:13] 

[00:53:13] ---- [ui] ui-fulldeps/issue-44953/issue-44953.rs stdout ----

[00:53:13] 	normalized stderr:

[00:53:13] error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)

[00:53:13]   --> $DIR/issue-44953.rs:16:14

[00:53:13]    |

[00:53:13] 16 | #[macro_use] extern crate log;

[00:53:13]    |              ^^^^^^^^^^^^^^^^^

[00:53:13]    |

[00:53:13]    = help: add #![feature(rustc_private)] to the crate attributes to enable

[00:53:13] 

[00:53:13] error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)

[00:53:13]   --> $DIR/issue-44953.rs:19:5

[00:53:13]    |

[00:53:13] 19 |     info!("This is a log message.");

[00:53:13]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[00:53:13]    |

[00:53:13]    = help: add #![feature(rustc_private)] to the crate attributes to enable

[00:53:13]    = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)

[00:53:13] 

[00:53:13] error: aborting due to 2 previous errors

[00:53:13] 

[00:53:13] 

[00:53:13] 

[00:53:13] expected stderr:

[00:53:13] error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)

[00:53:13]   --> $DIR/issue-44953.rs:16:14

[00:53:13]    |

[00:53:13] 16 | #[macro_use] extern crate log;

[00:53:13]    |              ^^^^^^^^^^^^^^^^^

[00:53:13]    |

[00:53:13]    = help: add #![feature(rustc_private)] to the crate attributes to enable

[00:53:13] 

[00:53:13] error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)

[00:53:13]   --> $DIR/issue-44953.rs:19:5

[00:53:13]    |

[00:53:13] 19 |     info!("This is a log message.");

[00:53:13]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[00:53:13]    |

[00:53:13]    = help: add #![feature(rustc_private)] to the crate attributes to enable

[00:53:13]    = note: this error originates in a macro outside of the current crate

[00:53:13] 

[00:53:13] error: aborting due to 2 previous errors

[00:53:13] 

[00:53:13] 

[00:53:13] 

[00:53:13] diff of stderr:

[00:53:13] 

[00:53:13]  error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)

[00:53:13]    --> $DIR/issue-44953.rs:16:14

[00:53:13]     |

[00:53:13]  16 | #[macro_use] extern crate log;

[00:53:13]     |              ^^^^^^^^^^^^^^^^^

[00:53:13]     |

[00:53:13]     = help: add #![feature(rustc_private)] to the crate attributes to enable

[00:53:13]  

[00:53:13]  error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)

[00:53:13]    --> $DIR/issue-44953.rs:19:5

[00:53:13]     |

[00:53:13]  19 |     info!("This is a log message.");

[00:53:13]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[00:53:13]     |

[00:53:13]     = help: add #![feature(rustc_private)] to the crate attributes to enable

[00:53:13] -   = note: this error originates in a macro outside of the current crate

[00:53:13] +   = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)

[00:53:13]  

[00:53:13]  error: aborting due to 2 previous errors
```

**Pull request closed without merging**
