### PR TITLE
dse: Eliminate dead assignment statements when `debuginfo` is not set to `full`

### PR DESCRIPTION
**Pull request by dianqk**
This will help: https://github.com/rust-lang/rust/pull/128299#issuecomment-2310279340

r? cjgillot or mir-opt

### CODE REVIEW

**Comment by DianQK** [comment]
@rust-timer build 2124150

**Comment by cjgillot** [comment]
The first commit looks a lot like the first commit in https://github.com/rust-lang/rust/pull/106852. You will have to fight CI like that PR has to.
For the second commit, should this cleanup be done in SimplifyLocals? Or are you specifically targeting StorageLive/StoragegDead pairs in the same bb?

**Comment by Kobzol** [comment]
Great binary size results! But why is diesel/opt 10% larger now :thinking:

**Comment by DianQK** [comment]
> Great binary size results! But why is diesel/opt 10% larger now 🤔

I think this is related to inlining, but I haven't checked it yet.

**Comment by DianQK** [comment]
> The first commit looks a lot like the first commit in #106852. You will have to fight CI like that PR has to. 

Ahh, looks like it, I think we need to add `FileCheck` to these test cases first. I don't like a PR to have such a long dependency, I'll try to accomplish something similar in match_br.

@rustbot author

> For the second commit, should this cleanup be done in SimplifyLocals? Or are you specifically targeting StorageLive/StoragegDead pairs in the same bb?

Yes, they are `StorageLive/StoragegDead` pairs in the same BB that can be definitely be eliminated.

**Comment by Dylan-DPC** [comment]
@DianQK any updates on this?

**Comment by DianQK** [comment]
> @DianQK any updates on this?

This PR needs more work to complete and I maybe consider resubmitting it.

**Pull request closed without merging**
