### PR TITLE
Fully optimize by default

### LINKED ISSUE #17081: debug_assert and debug logging shouldn't be enabled by default in optimized builds
At the moment, using debug assertions is discouraged because it will hurt performance. In practice, no one disables assertions so they are not used: `debug_assert!` only has 11 uses in the Rust repository. It would have many more if I didn't feel I had to delete all of the assertions I used during development to avoid a 5-20% performance hit by default.

It would make a lot more sense to enable them by default only in non-optimized builds where the performance hit will be dwarfed by other issues. It would be overridden by passing an explicit `--cfg` switch, and Rust's build system could just use the default. Rust developers could easily override this, but users and packagers wouldn't be given a slow / bloated build by default.

This would make it acceptable to use `debug_assert!` for bounds checks in the unchecked indexing methods on slices and the very valuable jemalloc debugging assertions could also be enabled by default in an unoptimized build. Using the debug variant of mutexes rather than faster deadlocking ones is another example. There are bots building and testing with no optimizations, so there would be better testing coverage.

### LINKED ISSUE #22390: Turn on CFG_DISABLE_DEBUG by default
There's no reason to have `debug_assert!` enabled for most of our binaries. This is probably a lot of the reason behind our benchmark problems!

I nominate for P-high.

### PR DESCRIPTION
**Pull request by brson**
This makes the default configuration fully optimized, with no debugging options, no llvm asserts, renames --enable-debug to --enable-debug-assertions, and adds --enable-debug as a blanket option that toggles various things, per #17665. It does not add a `--enable-release` flag since that would be a no-op.

cc @nrc

Fixes https://github.com/rust-lang/rust/issues/22390
Fixes https://github.com/rust-lang/rust/issues/17081
Partially addresses https://github.com/rust-lang/rust/issues/17665

### CODE REVIEW

**Comment by nrc** [comment]
Could we build jemalloc with `--enable-debug` and `--enable-fill` in the debug configuration? Otherwise, looks good!

**Comment by brson** [comment]
@nrc done

**Comment by brson** [comment]
For some reason when I build with --enable-debug, llvm-mc doesn't get built.

**Comment by brson** [comment]
I pushed a follow up that changes --enable-debug to not set --disable-optimize-llvm since I cannot get LLVM to build (libLTO linking fails) in that config.

**Comment by nagisa** [comment]
I still disagree with disabling LLVM asserts in nightlies.

**Comment by brson** [comment]
@nagisa Oh, I did mean to leave llvm asserts on for nightlies. I'll update it.

**Comment by nagisa** [comment]
@brson yay!

**Comment by alexcrichton** [comment]
This... was merged? Not sure what github is doing... Closing!

**Comment by pnkfelix** [comment]
Ah ha!  I bet this is why my `make rustc-stage1` lately have been taking 40 minutes or more!

Filed #24405

**Pull request closed without merging**
