### PR TITLE
Implement an internal lint encouraging use of `Span::eq_ctxt`

### PR DESCRIPTION
**Pull request by a-lafrance**
Adds a new Rustc internal lint that forbids use of `.ctxt() == .ctxt()` for spans, encouraging use of `.eq_ctxt()` instead (see https://github.com/rust-lang/rust/issues/49509).

Also fixed a few violations of the lint in the Rustc codebase (a fun additional way I could test my code). Edit: MIR opt folks I believe that's why you're CC'ed, just a heads up.

Two things I'm not sure about:
1. The way I chose to detect calls to `Span::ctxt`. I know adding diagnostic items to methods is generally discouraged, but after some searching and experimenting I couldn't find anything else that worked, so I went with it. That said, I'm happy to implement something different if there's a better way out there. (For what it's worth, if there is a better way, it might be worth documenting in the rustc-dev-guide, which I'm happy to take care of)
2. The error message for the lint. Ideally it would probably be good to give some context as to why the suggestion is made (e.g. `rustc::default_hash_types` tells the user that it's because of performance), but I don't have that context so I couldn't put it in the error message. Happy to iterate on the error message based on feedback during review.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
impl lgtm (just needs to fix the `==` usage in clippy, too), though we should probably include a note somewhere that explains why, ideally as a doc comment on the method, too.

r? @compiler-errors do you remember details?

**Comment by a-lafrance** [comment]
PR to fix the lint violation in Clippy is up: https://github.com/rust-lang/rust-clippy/pull/11679

**Comment by compiler-errors** [comment]
There's nothing technically wrong with using `==` on ctxt, I just added it as a convenience method -- but I guess now that there's a convenience method, we should prefer it. So I don't think there's much documentation needed here.

**Comment by oli-obk** [comment]
> PR to fix the lint violation in Clippy is up: [rust-lang/rust-clippy#11679](https://github.com/rust-lang/rust-clippy/pull/11679)

Oh 😅 you could've just done it in this PR. `x test clippy` or even just `x check clippy` will work locally to test it and you can commit clippy changes here

**Comment by a-lafrance** [comment]
Yeah 😅 I found that out [in the Clippy PR](https://github.com/rust-lang/rust-clippy/pull/11679#issuecomment-1765119556). Good to know though, I'll update this PR with those changes.

**Pull request merged**
