### PR TITLE
Create `implicit_transmute_types` lint

### PR DESCRIPTION
**Pull request by Flying-Toast**
Type inference is useful in most cases, but it can cause issues around usage of transmute.
Even though a specific usage of transmute may have been confirmed to be sound, someone might
unintentionally change a piece of surrounding code that causes the transmuted types to
change and possibly become unsound. Despite that, `transmute()` will happily continue to infer these
changed types.

This commit adds a lint `implicit_transmute_types` that catches calls to transmute without
an explicit turbofish. The idea is that the initial author of code that uses a transmute will
verify the soundness of converting between the two types, and specify those types on the transmute
call. If the types end up changing later, typecheck will fail and force the transmute call to be
updated and remind the user to reassess the soundness of transmuting between the new types.

The lint is "allow" by default because it would trigger in lots of existing rust code, including
many cases in the core libraries. It may be beneficial to make it warn-by-default in the future
though.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
maybe it would make more sense to put this into clippy first?

**Comment by Flying-Toast** [comment]
Yeah I was thinking Clippy would probably be a better fit for a lint like this, just figured I'd check what others thought :-)
What do you think about keeping the note in the `mem::transmute` docs? Should we skip that too and just see how the lint pans out in clippy?

**Comment by compiler-errors** [comment]
I think that this probably should live in clippy as well, at least at first. As for the `mem::transmute` docs, that'll need to be approved by the libs team, so it's probably best to open a PR with that change separate from this one.

**Comment by compiler-errors** [comment]
I'm gonna close this, and a separate PR should be opened and assigned to T-libs for the documentation changes.

Then I encourage you to open a clippy lint. Then down the road we can uplift this into a rustc lint if it ends up being something we want to warn always!

**Pull request closed without merging**
