### PR TITLE
use sort_unstable to sort primitive types

### PR DESCRIPTION
**Pull request by matthiaskrgr**
It's not important to retain original order if we have &[1, 1, 2, 3] for example.

clippy::stable_sort_primitive

### CODE REVIEW

**Comment by leonardo-m** [comment]
Can't sort perform by itself this optimization inside?

**Comment by matthiaskrgr** [comment]
Hmm, it may be possible to have a custom `sort()` impl for slices of primitives and use `sort::quicksort()` (unstable sort) instead of `merge_sort()` under the hood, but I don't know what kind of dangers this implies. I'm wondering what the libs team thinks.

[sort](https://doc.rust-lang.org/src/alloc/slice.rs.html#194-199)
[sort_unstable](https://doc.rust-lang.org/src/core/slice/mod.rs.html#1696-1701)

**Review by davidtwco — APPROVED** [review]
LGTM, can make an issue if you want to look into performing this optimisation within `sort`.

**Comment by matthiaskrgr** [comment]
Zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/default.20to.20unstable.20sort.20when.20sorting.20primitive.20type.20slices

May make an issue if this remains unanswered so the idea does not get lost :)

**Comment by matthiaskrgr** [comment]
````

failures:

---- [run-make] run-make-fulldeps/long-linker-command-lines stdout ----

error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
DYLD_LIBRARY_PATH="/Users/runner/work/1/s/build/x86_64-apple-darwin/test/run-make-fulldeps/long-linker-command-lines/long-linker-command-lines:/Users/runner/work/1/s/build/x86_64-apple-darwin/stage2/lib:" '/Users/runner/work/1/s/build/x86_64-apple-darwin/stage2/bin/rustc' --out-dir /Users/runner/work/1/s/build/x86_64-apple-darwin/test/run-make-fulldeps/long-linker-command-lines/long-linker-command-lines -L /Users/runner/work/1/s/build/x86_64-apple-darwin/test/run-make-fulldeps/long-linker-command-lines/long-linker-command-lines  foo.rs -g -O
RUSTC="/Users/runner/work/1/s/build/x86_64-apple-darwin/stage2/bin/rustc" DYLD_LIBRARY_PATH="/Users/runner/work/1/s/build/x86_64-apple-darwin/test/run-make-fulldeps/long-linker-command-lines/long-linker-command-lines:/Users/runner/work/1/s/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib:" /Users/runner/work/1/s/build/x86_64-apple-darwin/test/run-make-fulldeps/long-linker-command-lines/long-linker-command-lines/foo
attempt: 100
attempt: 200
attempt: 300

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'status: exit code: 1
stdout:

stderr:
error: couldn't read /Users/runner/work/1/s/build/x86_64-apple-darwin/test/run-make-fulldeps/long-linker-command-lines/long-linker-command-lines/bar.rs: stream did not contain valid UTF-8

error: aborting due to previous error

', foo.rs:76:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [all] Error 101

````

Hm, since this test did not fail previously (when the build timed out) I assume this is spurious?

**Comment by Mark-Simulacrum** [comment]
Seems quite likely, though I am a bit surprised by spurious failures in that test.

@bors retry run-make-fulldeps/long-linker-command-lines

**Comment by davidtwco** [comment]
This is one unlucky PR..
@bors retry

**Comment by davidtwco** [comment]
```quote
---- workspaces::relative_rustc stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build`
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build`
thread 'workspaces::relative_rustc' panicked at '
Expected: execs
    but: exited with exit code: 101
--- stdout

--- stderr
error: could not execute process `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t1927/lib/./foo -vV` (never executed)

Caused by:
  Text file busy (os error 26)
', src/tools/cargo/crates/cargo-test-support/src/lib.rs:832:13
```

**Comment by matthiaskrgr** [comment]
Hmm, I rebased and retried again locally and didn't see any of the these test failures.

**Comment by Mark-Simulacrum** [comment]
Okay, let's try again. @bors retry

**Pull request merged**
