### PR TITLE
Omit integer suffix when unnecessary

### PR DESCRIPTION
**Pull request by alfiedotwtf**
See PR # 21378 for context

### CODE REVIEW

**Comment by frewsxcv** [comment]
Needs a rebase

**Comment by alfie** [comment]
Ping @frewsxcv

**Comment by frewsxcv** [comment]
@alfie I unfortunately do not have reviewing rights :P  You might need @nick29581 for that

**Comment by alfie** [comment]
Sorry @frewsxcv :)

**Comment by alfie** [comment]
Sorry, I didn't realise force push didn't notify.

**Comment by alfie** [comment]
@alexcrichton any idea why homu stopped?

**Comment by alexcrichton** [comment]
Ah I canceled it manually because this is included in the rollup (#21872) and wanted to put the rollup back on bors.

**Comment by alfie** [comment]
Ahh cool, np :)

**Pull request merged**
