### PR TITLE
nll: use an FxHashSet to keep track of visited locations

### PR DESCRIPTION
**Pull request by ljedrz**
It should be faster; can we do a perf run to make sure?

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try

Cc @nnethercote @nikomatsakis - wondering if you've seen this in any profiles?

**Comment by nnethercote** [comment]
I don't recall seeing this in profiles.

I've said this before, but I'll say it again: I *strongly* recommend using profile information to drive optimizations. Optimizations typically make code more complex, and if they don't speed the compiler up, that's a net loss. If you want to improve compile speed -- something I greatly appreciate! -- grab a profiler and [start measuring](https://github.com/rust-lang-nursery/rustc-perf/blob/master/collector/README.md) :)

**Comment by nnethercote** [comment]
It's also worth noting that looking up a hashset can be slower than looking up a vector if the number of elements is small, because hashing is moderately expensive.

**Comment by Mark-Simulacrum** [comment]
@rust-timer build ebea71b8535b8687c54367fa79fa8b25e3c23d53

**Comment by Mark-Simulacrum** [comment]
Looks like probably just noise on instructions and possibly some losses in terms of memory use so we probably don't want to land this

**Pull request closed without merging**
