### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by compiler-errors**
Successful merges:

 - #113010 (rust-installer & rls: remove exclusion from rustfmt & tidy )
 - #113317 ( -Ztrait-solver=next: stop depending on old solver)
 - #113319 (`TypeParameterDefinition` always require a `DefId`)
 - #113320 (Add some extra information to opaque type cycle errors)
 - #113321 (Move `ty::ConstKind` to `rustc_type_ir`)
 - #113337 (Winnow specialized impls during selection in new solver)
 - #113355 (Move most coverage code out of `rustc_codegen_ssa`)
 - #113356 (Add support for NetBSD/riscv64 aka. riscv64gc-unknown-netbsd.)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=113010,113317,113319,113320,113321,113337,113355,113356)

### CODE REVIEW

**Comment by compiler-errors** [comment]
Strange. Hopefully noise? But I started a rust-timer on https://github.com/rust-lang/rust/pull/113320#issuecomment-1622404778 and https://github.com/rust-lang/rust/pull/113317#issuecomment-1622408136.

Other PRs don't look like they affected anything? But maybe I overlooked something.

**Comment by lqd** [comment]
Noise spikes on `bitmaps` are usually smaller IIRC, at least recently they were. These 2 runs, or the next couple PRs to be merged, should hopefully be enough to see if that's just noise.

(In case you don't know: you don't have to launch the perf runs on the rolled up PR's individual page, you can also launch them here in this rollup, e.g. so that all your investigation is in the same place)

**Comment by compiler-errors** [comment]
Huh, well looks like https://github.com/rust-lang/rust/pull/113320#issuecomment-1622519126 may be the culprit? cc @oli-obk

Or else someone should look at those results and conclude they're noise.

**Comment by rylev** [comment]
Looks like @oli-obk investigated more [here](https://github.com/rust-lang/rust/pull/113320#issuecomment-1623476780).

@oli-obk any further thoughts on this or shall we officially give up on what might be the cause?

**Comment by lqd** [comment]
> Looks like @oli-obk investigated more [here](https://github.com/rust-lang/rust/pull/113320#issuecomment-1623476780).

As well as [here](https://github.com/rust-lang/rust/pull/113400) where the revert results are also confusing.

**Comment by oli-obk** [comment]
I should try reverting the entire PR, will do that tomorrow.

**Comment by lqd** [comment]
I got you, hopefully you'll have #113587's results ready for breakfast.

**Comment by lqd** [comment]
Very confusing indeed, the `bitmaps` regression detected in this rollup has not reverted since then. 

image


Maybe some noise when testing individual PRs has prevented us from seeing the correct PR introducing it, or it's a combination of multiple PRs in this rollup that is causing the issue.

**Pull request merged**
