### PR TITLE
revise RwLock for HermitCore

### PR DESCRIPTION
**Pull request by stlankes**
- current version is derived from the wasm implementation
- increasing the readability of `Condvar`
- simplify the interface to the libos

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@stlankes if you can rebase this, i can get it reviewed soon.

**Comment by Dylan-DPC** [comment]
err sorry just saw the commit

Also we do not encourage merge commits, so do you mind un-merging it and doing a rebase instead? thanks

**Comment by stlankes** [comment]
I will do it

**Comment by stlankes** [comment]
I rebased the patch...

**Comment by jyn514** [comment]
I'm not sure who should review this ... Maybe @Amanieu?

**Review by dtolnay — APPROVED** [review]
Not reviewed beyond confirming that it only affects `target_os = "hermit"`.

**Pull request merged**
