### PR TITLE
[stable] Backport Clippy ICE fix to stable

### PR DESCRIPTION
**Pull request by flip1995**
This ICE slipped through. There were multiple issues opened after the 1.47 release about this ICE:

https://github.com/rust-lang/rust-clippy/issues/6140
https://github.com/rust-lang/rust-clippy/issues/6143
https://github.com/rust-lang/rust-clippy/issues/6147

This PR backports the fix for this ICE: https://github.com/rust-lang/rust-clippy/pull/5948

This probably does not warrant a point release, but it would be great to include this, if there is one.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We discussed this in the release team meeting last week, and roughly decided that we'd be on board with a backport here presuming we end up doing a point release. There are no current plans for a point release, though.

**Comment by Mark-Simulacrum** [comment]
@flip1995 Can you confirm that 1.48 does not contain this regression? Do we have a separate PR with a backport there?

**Comment by flip1995** [comment]
> @flip1995 Can you confirm that 1.48 does not contain this regression? Do we have a separate PR with a backport there?

The original commit fixing this (8776db9) was merged with this Clippy sync: https://github.com/rust-lang/rust/pull/76034 

This was 2 days after the 1.46 release. So shortly after 1.47 beta was branched. So it would only be available in 1.48 (current beta).

```rust
$ git branch master beta stable --contains=8776db9
  beta
* master
```

**Comment by Mark-Simulacrum** [comment]
Ok, great, thanks.

**Comment by flip1995** [comment]
This fix will hit stable 1.48 on Thursday, therefore, I will close this.

**Pull request closed without merging**
