### PR TITLE
Rollup of 26 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #40317, #40387, #40433, #40452, #40456, #40457, #40463, #40466, #40467, #40482, #40495, #40496, #40497, #40499, #40500, #40503, #40505, #40507, #40512, #40520, #40526, #40536, #40538, #40539, #40545, #40586
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r-

Oh that looks like a legitimate error:

```
error[E0308]: mismatched types

   --> /checkout/src/libstd/sys_common/net.rs:342:55

    |

342 |         cvt(unsafe { c::bind(*sock.as_inner(), addrp, len) })?;

    |                                                       ^^^ expected i32, found u32

error[E0308]: mismatched types

   --> /checkout/src/libstd/sys_common/net.rs:433:55

    |

433 |         cvt(unsafe { c::bind(*sock.as_inner(), addrp, len) })?;

    |                                                       ^^^ expected i32, found u32

error[E0308]: mismatched types

   --> /checkout/src/libstd/sys/unix/ext/net.rs:644:82

    |

644 |                 cvt(libc::bind(*inner.as_inner(), &addr as *const _ as *const _, len))?;

    |                                                                                  ^^^ expected i32, found u32

error[E0308]: mismatched types

   --> /checkout/src/libstd/sys/unix/ext/net.rs:923:85

    |

923 |                 cvt(libc::bind(*socket.0.as_inner(), &addr as *const _ as *const _, len))?;

    |                                                                                     ^^^ expected i32, found u32

error: aborting due to 4 previous errors

error: Could not compile `std`.

To learn more, run the command again with --verbose.
```

**Comment by alexcrichton** [comment]
(er didn't mean to close)

**Comment by frewsxcv** [comment]
Oh I missed that. Maybe I was looking at the wrong machine. Probably that libc bump again.

**Comment by alexcrichton** [comment]
(agreed to the cause)

**Comment by frewsxcv** [comment]
I'll open another rollup

**Pull request closed without merging**
