### PR TITLE
unignore lexer tests

### PR DESCRIPTION
**Pull request by richo**
Motivated by the test output not lining up when it could, I normalized all of the issue-\* tests.

While doing it, I found some lexer tests that could be unignored and fixed an int -> isize.

### CODE REVIEW

**Comment by pnkfelix** [comment]
I'm not sure if this is a good time to be making sweeping changes like this...

**Comment by richo** [comment]
Sure. I'm fairly indifferent about the last commit (it bothered me enough to change it, but not enough that I'm never going to run the tests again if it doesn't land).

The first two commits should go in regardless though.

**Comment by alexcrichton** [comment]
I would also prefer to avoid changes like this for now, the first two commits are fine by me though!

**Pull request merged**
