### PR TITLE
Coerce fields to the expected field type

### LINKED ISSUE #31260: Coercion sites are not consistent between struct tuples and structs
``` rust
pub struct Struct<K: 'static> {
    pub field: K,
}

static STRUCT: Struct<&'static [u8]> = Struct {
    field: &[1]
};

pub struct Tuple<K: 'static>(K);

static TUPLE: Tuple<&'static [u8]> = Tuple(&[1]);
```

`STRUCT` fails to type check, while `TUPLE` succeeds.

```
<anon>:7:40: 9:2 error: mismatched types:
 expected `Struct<&'static [u8]>`,
    found `Struct<&[_; 1]>`
(expected slice,
    found array of 1 elements) [E0308]
<anon>:7 static STRUCT: Struct<&'static [u8]> = Struct {
<anon>:8     field: &[1]
<anon>:9 };
<anon>:7:40: 9:2 help: see the detailed explanation for E0308
```

### PR DESCRIPTION
**Pull request by arielb1**
Fully fixes #31260.

This needs a crater run. I was supposed to do this last month but it slipped. Let's get this done.

### CODE REVIEW

**Comment by eddyb** [comment]
Started crater run.

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/a2d2d3bb2d27037859452fd8238f608f) shows **0 regressions** (ignoring network errors).

**Comment by eddyb** [comment]
cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/compiler meeting briefly. If no regressions, seems like we should do this.

**Comment by Mark-Simulacrum** [comment]
I suspect this is a spurious failure; it looks like the test will exit after 30 seconds via `process::exit(1)` -- which should probably be 0, really, I think.

```
[01:03:36] failures:
[01:03:36]
[01:03:36] ---- [run-pass] run-pass/tcp-stress.rs stdout ----
[01:03:36]
[01:03:36] error: test run failed!
[01:03:36] status: exit code: 1
[01:03:36] command: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/tcp-stress.stage2-x86_64-unknown-linux-gnu
[01:03:36] stdout:
[01:03:36] ------------------------------------------
[01:03:36]
[01:03:36] ------------------------------------------
[01:03:36] stderr:
[01:03:36] ------------------------------------------
[01:03:36]
[01:03:36] ------------------------------------------
[01:03:36]
[01:03:36] thread '[run-pass] run-pass/tcp-stress.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2479
[01:03:36] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Mark-Simulacrum** [comment]
@bors retry

https://github.com/rust-lang/rust/issues/41006

```
[01:46:36] error: failed to remove: C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\rustc_driver.dll
[01:46:36]
[01:46:36] Caused by:
[01:46:36]   Access is denied. (os error 5)
[01:46:36] Build failed, waiting for other jobs to finish...
[01:46:40] error: build failed
```

**Pull request merged**
