### PR TITLE
Suggest `const_mut_refs`, not `const_fn` for mutable references in `const fn`

### LINKED ISSUE #77134: `#![feature(const_fn)]` doesn't work
I tried this code:

```rust
#![feature(const_fn)]
struct Foo(Option<&'static mut i32>);
impl Foo {
    const fn new() -> Self {
        Self(None)
    }
}

fn main() {}
```

I expected to see this happen: Compilable

Instead, this happened:
```
   Compiling foo v0.1.0 (/home/hiroki/foo)
error[E0723]: mutable references in const fn are unstable
 --> src/main.rs:5:14
  |
5 |         Self(None)
  |              ^^^^
  |
  = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
  = help: add `#![feature(const_fn)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0723`.
error: could not compile `foo`

To learn more, run the command again with --verbose.
```
### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (8b4085359 2020-09-23)
binary: rustc
commit-hash: 8b4085359ae798dedb05c95ad42520557bd25320
commit-date: 2020-09-23
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

I found this bug when I was trying to build [linked-list-allocator](https://github.com/phil-opp/linked-list-allocator) crate.

`cargo-bisect-rustc `: https://gist.github.com/toku-sa-n/0b8e18d78c625ee1dd6b9fe630bed7ce

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #77134.

Prior to #76850, most uses of `&mut` in `const fn` ~~required~~ involved two feature gates, `const_mut_refs` and `const_fn`. The first allowed all mutable borrows of locals. The second allowed only locals, arguments and return values whose types contained `&mut`. I switched the second check to the `const_mut_refs` gate. However, I forgot update the error message with the new suggestion.

Alternatively, we could revert to having two different feature gates for this. OP's code never borrows anything mutably, so it didn't need `const_mut_refs` in the past, only `const_fn`. I'd prefer to keep everything under a single gate, however.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
I would have thought we could remove `feature(const_fn)` from some tests now, can you check?

**Comment by ecstatic-morse** [comment]
I browsed the `const_mut_refs` tests. It looks like the feature gate test was vn OR, not an AND: `const_mut_refs` turned off everything and `const_fn` turned off only the type checks, so I don't think there's anything to remove.

In other news, we need more `const_mut_refs` tests, since I don't know if we have anything testing const-qualification of mutably borrowed values.

**Pull request merged**
