### PR TITLE
Fix rustdoc pathes search

### LINKED ISSUE #50086: Vec::new doesn't give expected results on rustdoc search
I suppose it doesn't parse the query correctly and therefore doesn't look for the parent, which is bad.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #50086.

Depends on #50302.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
I'm confused why you added the `exact-check` flag but didn't actually use it.

Also, now that https://github.com/rust-lang/rust/pull/50302 is merged, can you rebase to filter that commit out of this PR?

**Comment by GuillaumeGomez** [comment]
> I'm confused why you added the `exact-check` flag but didn't actually use it.

Good catch! I now use it in the pinbox test. :)

**Comment by QuietMisdreavus** [comment]
Note to self when the new `exact-check` flag is added to rustc-guide: The difference between setting `exact-check` and *not* setting `ignore-order` is that "no flags" only means that the actual results include the expected results in the right order, but `exact-check` ensures that no *additional* items are in the actual result. In other words, the actual result is exactly the same as the input.

**Comment by QuietMisdreavus** [comment]
Okay, after a bit of a chat to piece together what's going on, i'm okay with this. The key takeaway is that the conditional being changed was being used to short-circuit any query which matched the input, regardless of whether it was part of a longer path. The added conditional makes it so that this branch only gets hit on queries that don't have a `::` in it. That makes it so that other sorters come in to order the results, thus putting `std::vec::Vec::new` back on top when you're searching for `vec::new`.

@bors r+ rollup

**Comment by kennytm** [comment]
@bors r-

```
Checking "pinbox-new.js" ... FAILED
==> Exact check failed at position 1: expected '{"path":"std::boxed::PinBox","name":"new"}' but found '{"crate":"std","ty":11,"name":"new","path":"std::boxed","desc":"Allocate memory on the heap, move the data into it and pin it.","parent":{"ty":3,"name":"PinBox"},"type":{"inputs":[{"name":"t"}],"output":{"name":"pinbox"}},"lev":1}'
```

**Comment by GuillaumeGomez** [comment]
Fixed.

**Comment by QuietMisdreavus** [comment]
Since the travis builder doesn't have node, we won't know whether this works until bors gets its hands on it.

@bors r+ rollup-

**Pull request merged**
