### PR TITLE
Format libcore with rustfmt (including tests and benches)

### PR DESCRIPTION
**Pull request by dtolnay**
Important: two small non-rustfmt changes that will need close review:

- I added `#[rustfmt::skip]` to two manually arranged tables in src/libcore/benches/ascii.rs; see first commit in the PR.
- I added `// ignore-tidy-filelength` to src/libcore/ptr/mod.rs because rustfmt puts it over tidy's 3000 line limit; see second commit in the PR. I filed #66891 to follow up on breaking up that file. For now though having it be formatted is more important than having it below the line limit.

---

As with my previous formatting PRs, I am avoiding causing merge conflicts in other PRs by only touches those files that are not involved in any currently open PR. Files that appear in new PRs between when this PR is opened and when it makes it to the top of the bors queue will be reverted from this PR.

The list of files involved in open PRs is determined by querying GitHub's GraphQL API [with this script](https://gist.github.com/dtolnay/aa9c34993dc051a4f344d1b10e4487e8).

With the list of files from the script in outstanding_files, the relevant commands were:

```
$ find src/libcore -name '*.rs' \
    | xargs rustfmt --edition=2018 --unstable-features --skip-children
$ rg libcore outstanding_files | xargs git checkout --
```

To confirm no funny business:

```
$ git checkout $THIS_COMMIT^
$ git show --pretty= --name-only $THIS_COMMIT \
    | xargs rustfmt --edition=2018 --unstable-features --skip-children
$ git diff $THIS_COMMIT  # there should be no difference
```

r? @Dylan-DPC

### CODE REVIEW

**Comment by dtolnay** [comment]
Failure in libcore/tests/num/flt2dec/strategy/dragon.rs is from ordering of wildcard imports, I opened #66894 to delete them.

**Comment by dtolnay** [comment]
- Remove src/libcore/tests/num/flt2dec/strategy/dragon.rs from this PR to avoid conflict with #66894.

**Comment by JohnCSimon** [comment]
Ping from triage:
@Dylan-DPC - can you please review this PR?

**Comment by dtolnay** [comment]
- Rebased

**Pull request merged**
