### PR TITLE
Add `read_exact_at` and `write_all_at` to WASI's `FileExt`

### PR DESCRIPTION
**Pull request by sunfishcode**
This adds `read_exact_at` and `write_all_at` to WASI's `FileExt`,
similar to the Unix versions of the same names.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Looks good to me, but would someone from @rust-lang/libs mind confiming that the insta-stabilization here is ok? These are copied from `std::os::unix` (which are stable) and so this looks to be inheriting the stability from there too.

**Comment by sfackler** [comment]
LGTM

**Comment by alexcrichton** [comment]
Ok, thanks!

@bors: r+

**Comment by Manishearth** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/74110#issuecomment-654513453

**Comment by sunfishcode** [comment]
Updated to rename WASI's `read_at`/`write_at` to `read_vectored_at`/`write_vectored_at` and to provide regular `read_at`/`write_at` for better consistency with other platforms.

r? @alexcrichton

**Pull request merged**
