### PR TITLE
[rustdoc] Allows links in headings

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Reopening of https://github.com/rust-lang/rust/pull/94360.

# Explanations

Rustdoc currently doesn't follow the markdown spec on headings: we don't allow links in them. So instead of having headings linking to themselves, this PR generates an anchor on the left side like this:

image

<details>
<summary>previous version</summary>

image

</details>

Having the anchor always displayed allows for mobile devices users to be able to have a link to the anchor. The different color used for the anchor itself is the same as links so people notice when looking at it that they can click on it.

You can test it [here](https://rustdoc.crud.net/imperio/links-in-headings/std/index.html).

cc @camelid 
r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
> This doesn’t seem like a great solution. The section button adds visual clutter after so much other work has been done to reduce it.

Agreed, hence why we now have hosted documentation so we can suggest alternatives. :)

> Other than [conflicting with the `[-]` button in the top-doc](https://github.com/rust-lang/rust/issues/100254#issuecomment-1208115764), are there any other problems with having it in the gutter and showing it on mouse-over?

Because it brings two issues:
 1. It doesn't work on mobile (that's minor)
 2. It either creates a void (where the symbol is supposed to be) or moves the content when mouse overs the title or needs to be placed at the end of the heading (which brings new issues like "what happens if the symbol can't stand on the same line and then appears on the next one?".

So displaying the symbol all the time seems like the best solution. Other possibilities I see are (they are not mutually exclusive):
 * Change the icon for the anchor
 * Change the color
   * Same color all the time?
   * Dimmed out until heading is hovered?
   * Something else?

> The top-doc problem seems like it could be acceptably solved by hiding the button entirely:
> 
> ```
> #top-doc > *:first-child > .anchor { display: none }
> ```
>
> It is inconsistent, but since the header is at the top of the page, not being able to link to it directly doesn’t seem like that big of a missing feature.

As you said, it is inconsistent and I'd prefer to avoid that if possible.

**Comment by GuillaumeGomez** [comment]
Yes but it's okay because in this context, there is no `[-]` element so there can not be any conflict. In the case of headings, we'd need to have an incoherence in case we remove the anchor if the first element of the top doc block is a heading, which is my main issue.

But if it's only a concern for me, I can make it appear on hover except on the first heading if the first element of the top doc block and end the debate. :)

I suppose the color should be the one from the text as well?

(Confirming before making changes :wink: )

**Comment by GuillaumeGomez** [comment]
Ok! I'm a bit sad for the mobile devices but I suppose it's a minor concern. Thanks for the feedback, doing the update as soon as possible!

**Comment by fmease** [comment]
Could we address the issue with mobile devices (which inherently don't support hovers), by utilizing `@media (pointer:none), (pointer:coarse) { /* … */ }` to always show `§` on mobile devices? I haven't checked browser support on https://caniuse.com yet. Rn, there's no way to “obtain” a section's link anchor on mobile, did I read that right?

**Comment by GuillaumeGomez** [comment]
So you suggest to display the anchor all the time on mobile devices? No need to use such CSS features, we could simply use a media query to make the anchors displayed all the time in this case. However, it would mean more content displayed on devices that don't have that much screen space

I'm personally fine with that (ie, displaying anchors all the time on mobile devices) but we currently don't display existing anchors already, so I think the best would be to remain coherent with that (at least for the moment, we can discuss about that in a separate issue).

**Comment by GuillaumeGomez** [comment]
From last [rustdoc meeting](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.2004-12-2023/near/405905524):

> seems like we have a consensus to make all headings except code headers to make the anchor appear on hover and not be a link anymore

I'll update the PR in the next days following this input.

**Comment by GuillaumeGomez** [comment]
I unified the headings and the anchors and used this opportunity to move the creation of such headings into one place. With this, I think the concern was resolved?

**Comment by mgeisler** [comment]
Hey folks, I realize this was just merged... but I don't see this mentioned above. A _major_ use of self-links here and elsewhere (for me) is to copy-paste them into other places.

What I'm talking about is a workflow where I highlight a self-link like this:

image

Does Ctrl-c and then Ctrl-v somewhere else. The somewhere else could be here: [Monotone Matrices](https://docs.rs/smawk/latest/smawk/#monotone-matrices).

The GitHub comment editor is clever enough to turn this into 

```markdown
[Monotone Matrices](https://docs.rs/smawk/latest/smawk/#monotone-matrices)
```

which I find super useful! I couldn't have written the link better myself :smile: 

For that to work, it's necessary that the link has useful text. Is that ability going away?

**Comment by GuillaumeGomez** [comment]
I didn't even know it was possibility. I suppose it could be possible to replicate this behaviour on the anchor directly.

**Comment by mgeisler** [comment]
Perhaps it can be replicated, I don't really know how it works behind the scenes.

I just wanted to mention it since regressing on this (unknown) feature is a step back for those that use it. That might of course just be me, in which case you can take this as me spreading awareness of it :smile:

**Comment by GuillaumeGomez** [comment]
Well, we were not markdown-compliant: headings are not supposed to be links. ^^'

**Comment by mgeisler** [comment]
> Well, we were not markdown-compliant:

Yeah, I see what you mean.

It can be argued in several ways. One way to see it would be to say that `rustdoc` simply transformed the input a bit before sending it to the Markdown (Commonmark) parser: `# Foo` becomes `# [Foo](#foo)`. This is similar to how `rustdoc` already happily

- transforms code blocks by [Hiding portions of the example](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example),
- injects extra link targets (I assume) to make [Linking to items by name](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html#linking-to-items-by-name) work so smoothly.

So I would not call this case super clear :smile: 

> headings are not supposed to be links. ^^'

Yeah, I agree! I find it a typographic no-no when users add links in headings... meaning I much prefer when headings link back to themselves :wink:

If the headings themselves don't do that, I of course look for a TOC somewhere on the page. If that doesn't work, then I can of course do the classic thing and right-click to copy the link address and then write the link out normally.

**Pull request merged**
