### PR TITLE
`-Z location-detail`: provide option to disable all location details

### PR DESCRIPTION
**Pull request by hudson-ayers**
As reported [here](https://github.com/rust-lang/rust/pull/89920#issuecomment-1190598924), when I first implemented the `-Z location-detail` flag there was a bug, where passing an empty list was not correctly supported, and instead rejected by the compiler. This PR fixes that such that passing an empty list results in no location details being tracked, as originally specified in https://github.com/rust-lang/rfcs/pull/2091 .

This PR also adds a test case to verify that this option continues to work as intended.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm not the right reviewer for this change.

r? @davidtwco

**Comment by Aaron1011** [comment]
Personally, I think it might be more intuitive to have an explicit `none` or `no` option (which would be incompatible with all other options).

**Review by davidtwco — CHANGES_REQUESTED** [review]
I agree with @Aaron1011, I'd prefer to see this with a `none` or `no` option than accepting an empty list. As far as I can gather from skimming the parse functions, we don't have any other options that accept an empty list, but we do have some that accept `none`/`no`.

**Comment by hudson-ayers** [comment]
Updated to support `none` instead of an empty list

**Comment by klensy** [comment]
Should be fixed also there (but i don't see where it used) https://github.com/rust-lang/rust/blob/c9b31839b624345d59fda6e595b9abae71fcea13/compiler/rustc_session/src/options.rs#L397-L398
and there
https://github.com/rust-lang/rust/blob/c9b31839b624345d59fda6e595b9abae71fcea13/compiler/rustc_session/src/options.rs#L1349-L1351

Should `all` option be reworded? As if `all` passed as argument, it isn't accepted.

**Comment by hudson-ayers** [comment]
> Should be fixed also there (but i don't see where it used)
> 
> https://github.com/rust-lang/rust/blob/c9b31839b624345d59fda6e595b9abae71fcea13/compiler/rustc_session/src/options.rs#L397-L398

Fixed. And I agree it is confusing to see where this constant is used -- the key is that the `options!()` macro has an implicit requirement that you pass as `$parse` a name which is both the name of the function that parses the option in the `parse` module and also the name of the options descriptor string in the `desc` module. So this is used here: https://github.com/rust-lang/rust/blob/6e89c4cfb1c76a56ee70d19af6ce1070d4bd7cec/compiler/rustc_session/src/options.rs#L1364

> and there
> https://github.com/rust-lang/rust/blob/c9b31839b624345d59fda6e595b9abae71fcea13/compiler/rustc_session/src/options.rs#L1349-L1351
> 
> Should `all` (or added as valid one) option be reworded? As if `all` passed as argument, it isn't accepted.

I removed any mention of `all` and specified that the default is `file,line,column`.

**Review by davidtwco — APPROVED** [review]

**Pull request merged**
