### PR TITLE
Stabilize default_alloc_error_handler

### LINKED ISSUE #66741: Tracking issue for `handle_alloc_error` defaulting to panic (for no_std + liballoc)
The proposal below was implemented in https://github.com/rust-lang/rust/pull/76448, feature-gated under `#![feature(default_alloc_error_handler)]`.

Issues to resolve before stabilization:

* [ ] Document the new behavior
* [ ] Get some usage experience beyond a synthetic test case https://github.com/rust-lang/rust/issues/66741#issuecomment-706069713
* [ ] The current implementation might have UB https://github.com/rust-lang/rust/pull/76448#discussion_r502293959 https://github.com/rust-lang/rust/issues/66741#issuecomment-706079813
  > Removing that unwind attribute needs to be benchmarked as it could lead to many extra unwind edges

Initial proposal:

----

## Summary

This issue is for getting consensus on a change initially proposed in the tracking issue for `#[alloc_error_handler]`: https://github.com/rust-lang/rust/issues/51540#issuecomment-553114657

When no `#[alloc_error_handler]` is defined (which implies that `std` is not linked, since it [literally](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/libstd/alloc.rs#L204-L218) has such a handler), `alloc::alloc::handle_alloc_error` should default to calling `core::panic!` with a message identical to the one that `std` prints to stderr before aborting in that case.

Although https://github.com/rust-lang/rust/issues/51540#issuecomment-556079840 suggested that a full RFC would not be necessary, this is loosely structured after the RFC template.

## Background

See the Background section of [the sibling issue proposing stabilization of the attribute](https://github.com/rust-lang/rust/issues/66740).

## Motivation

As of Rust 1.36, specifying an allocation error handler is the only requirement for using the `alloc` crate in `no_std` environments (i.e. without the `std` crate being also linked in the program) that cannot be fulfilled by users on the Stable release channel.

Removing this requirement by having a default behavior would allow:

* `no_std` + `liballoc` applications to start running on the Stable channel
* `no_std` applications that run on Stable to start using `liballoc`

## Guide-level explanation

When `std` *is* linked in an application, `alloc::alloc::handle_alloc_error` defaults to printing an error message to stderr and aborting the process.

When `std` is *not* linked and no other [`#[alloc_error_handler]`](https://github.com/rust-lang/rust/issues/51540) is defined, `handle_alloc_error` defaults to panicking as if the following handler were defined:

```rust
#[alloc_error_handler]
fn default_handler(layout: core::alloc::Layout) -> ! {
    panic!("memory allocation of {} bytes failed", layout.size())
}
```

## Reference-level explanation

The implementation for this would be very similar to that of `#[global_allocator]`. (Links in the next two paragraphs go to that implementation.)

`alloc::alloc::handle_alloc_error` is modified to [call](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/liballoc/alloc.rs#L84) an [`extern "Rust" { fn … }` declaration](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/liballoc/alloc.rs#L16-L23).

The definition of this function does not exist in Rust source code. Instead, it is [synthesized](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/librustc_codegen_llvm/allocator.rs) by the compiler [for “top-level” compilations (executables, `cdylib`s, etc.) when `alloc` is in the crate dependency graph](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/librustc_codegen_ssa/base.rs#L553-L571). If an `#[alloc_error_handler]` is defined, the synthesized function calls it. If not, the synthesized function calls `alloc::alloc::default_error_handler` which is a new lang item. (Or [is it?](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/libstd/alloc.rs#L236-L240))

In order to allow experimentation for this new default behavior, it should initially be gated behind the `#![feature(default_alloc_error_handler)]` feature flag. When no handler is defined, a call to the default is (at first) only synthesized if *any* of the crates in the dependency graph has that feature gate. If none of them do, [the current compilation error](https://github.com/rust-lang/rust/blob/582a4eaee6b3674a34aeefaa5ecad0207bac9b4b/src/librustc/middle/weak_lang_items.rs#L110-L111) continues to be emitted.

## Alternatives

The status quo is that `no_std` + `alloc` requires Nightly.

[Stabilizing `#[alloc_error_handler]`](https://github.com/rust-lang/rust/issues/66740) or some other mechanism for specifying this handler is another way to unlock the `no_std` + `liballoc` on Stable use case. This removes the initial motivation for coming up with this default behavior. However perhaps this default is still desirable? In a `no_std` environment where there is no process to abort, the allocation error handler will likely be very similar to the panic handler (which is already mandatory).

### PR DESCRIPTION
**Pull request by Amanieu**
Tracking issue: #66741

This turns `feature(default_alloc_error_handler)` on by default, which causes the compiler to automatically generate a default OOM handler which panics if `#[alloc_error_handler]` is not provided.

The FCP completed over 2 years ago but the stabilization was blocked due to an issue with unwinding. This was fixed by #88098 so stabilization can be unblocked.

Closes #66741

### CODE REVIEW

**Comment by lcnr** [comment]
considering that the FCP was 2 years ago, i would expect us to go through another FCP which explains the reason why stabilization was blocked. Won't block this without an FCP, but i definitely want someone to look at this who's a bit more knowledgeable about this than me

r? compiler

**Comment by bjorn3** [comment]
When using this with cg_clif I get:

```
           /home/gh-bjorn3/cg_clif/build_sysroot/sysroot_src/library/alloc/src/alloc.rs:419: undefined reference to `rust_oom'
```

It seems that the current implementation depends on `-Zfunction-sections=yes`, while cg_clif sets it to `no` for linker performance reasons. To elaborate on why it depends on this. The code in question is

```rust
pub mod __alloc_error_handler {
    use crate::alloc::Layout;

    // called via generated `__rust_alloc_error_handler`

    // if there is no `#[alloc_error_handler]`
    #[rustc_std_internal_symbol]
    pub unsafe fn __rdl_oom(size: usize, _align: usize) -> ! {
        panic!("memory allocation of {size} bytes failed")
    }

    // if there is an `#[alloc_error_handler]`
    #[rustc_std_internal_symbol]
    pub unsafe fn __rg_oom(size: usize, align: usize) -> ! {
        let layout = unsafe { Layout::from_size_align_unchecked(size, align) };
        extern "Rust" {
            #[lang = "oom"]
            fn oom_impl(layout: Layout) -> !;
        }
        unsafe { oom_impl(layout) }
    }
}
```

`__rust_alloc_error_handler` will be generated as a call to either of these functions. `__rdl_oom` when `#![feature(default_alloc_error_handler)]` is used, no problem here and `__rg_oom` when it isn't used. The problem is that in this case `rust_oom` (which is the actual symbol name of `oom_impl`) is not defined. In other words it only just so happens to work because `__rg_oom` is garbage collected by the linker by default. Both compiling liballoc with `-Zfunction-sections=no` and using `-Clink-dead-code` when compiling the executable or dylib will cause `__rg_oom` to not be garbage collected and thus give a linker error.

**Comment by Ericson2314** [comment]
I guess this is fine, but for people using alloc without global error handling at all (the current unstable `cfg` stuff, a feature hopefully someday) I hope one doesn't get needlessly synthesized.

**Comment by oli-obk** [comment]
We should probably have a test that uses this in a way we expect it to be used without requiring other feature gates. The tests touched by this PR all use other feature gates.

**Comment by petrochenkov** [comment]
@Amanieu 
Could you respond to the previous comments - https://github.com/rust-lang/rust/pull/102318#issuecomment-1258240102 (whether a new FCP is required), https://github.com/rust-lang/rust/pull/102318#issuecomment-1258297702 (function sections) and https://github.com/rust-lang/rust/pull/102318#issuecomment-1259469989 (tests)?
@rustbot author

**Comment by bjorn3** [comment]
The comment about function sections has been resolved by https://github.com/rust-lang/rust/pull/103061. src/test/ui/allocator/no_std-alloc-error-handler-default.rs now passes with cg_clif where it previously failed due to `-Zfunction-sections=no` being the default in cg_clif.

**Comment by Amanieu** [comment]
> We should probably have a test that uses this in a way we expect it to be used without requiring other feature gates. The tests touched by this PR all use other feature gates.

`src/test/ui/allocator/no_std-alloc-error-handler-default.rs` specifically tests for this feature. Some feature gates are required anyways, such as `lang_items` for `eh_personality` and `rustc_private` to use the libc crate. We might be able to get rid of the others but I feel this test is fine as it is.

> considering that the FCP was 2 years ago, i would expect us to go through another FCP which explains the reason why stabilization was blocked. Won't block this without an FCP, but i definitely want someone to look at this who's a bit more knowledgeable about this than me
> 
> r? compiler

I personally don't feel a new FCP is required, but I'll leave the decision to @rust-lang/lang.

**Comment by oli-obk** [comment]
> We should probably have a test that uses this in a way we expect it to be used without requiring other feature gates. The tests touched by this PR all use other feature gates.

This is still unaddressed

**Comment by oli-obk** [comment]
> Some feature gates are required anyways, such as `lang_items` for `eh_personality` and `rustc_private` to use the libc crate. We might be able to get rid of the others but I feel this test is fine as it is.

That sounds to me like we are not stabilizing anything. If this feature can only be used in conjunction with other features, stabilizing it doesn't do anything for stable Rust users.

But I believe you could just not remove src/test/ui/missing/missing-alloc_error_handler.rs, since after your changes it should work without any features or unstable flags.

**Comment by dvdhrm** [comment]
> > Some feature gates are required anyways, such as `lang_items` for `eh_personality` and `rustc_private` to use the libc crate. We might be able to get rid of the others but I feel this test is fine as it is.
> 
> That sounds to me like we are not stabilizing anything. If this feature can only be used in conjunction with other features, stabilizing it doesn't do anything for stable Rust users.

We successfully deploy stable rust on production UEFI platforms with `no_std`. We would like to also deploy `alloc`, but this feature is the only thing requiring a nightly compiler.

Yes, there are other nightly features that would be great to have and simplify a lot of things, but this is the only blocking issue to allow stable compilers to work with `alloc` and `no_std`. The lang-items, the exception-handler, the libc crate, they are all optional.

The public parts of our infrastructure are the `r-efi` crate for base UEFI integration with `no_std` environments, and the `r-efi-alloc` crate for allocator integration. The latter compiles fine on stable, but requires a nightly compiler to be actually used with `[global_allocator]` due to the alloc-handler being required but unstable.

I can gladly give more information about our deployments if needed. We recently were able to switch to a stable compiler with the base UEFI integration and it *significantly* simplifies deployments and increases trust in the infrastructure. We would very much like to use `alloc` as well, since it allows deploying the standard rust collections rather than writing our own.

**Comment by CryZe** [comment]
Same thing for WASM where you don't use libc / eh_personality usually.

**Comment by Amanieu** [comment]
I've removed most of the unstable features from the tests. The only remaining features are:
- `rustc_private` which is needed to use rustc's private copy of `libc`. The test harness doesn't have access to cargo to use the normal libc crate.
- `lang_items` is needed because the standard library is built with `-C panic=unwind` so a personality function must be provided. This isn't needed on targets that build the standard library with `-C panic=abort`.

**Comment by oli-obk** [comment]
Stabilization report for @rust-lang/lang

More details (Guide/Reference level explanations) can be found in the main post of the [tracking issue](https://github.com/rust-lang/rust/issues/66741). There are no outstanding issues with this feature. The only alternative was to stabilize the `#[alloc_error_handler]` attribute to allow users to define their own error handler. This alternative was rejected by T-lang in https://github.com/rust-lang/rust/issues/66740#issuecomment-664549885

### Motivation (verbatim from [tracking issue](https://github.com/rust-lang/rust/issues/66741))

As of Rust 1.36, specifying an allocation error handler is the only requirement for using the `alloc` crate in `no_std` environments (i.e. without the `std` crate being also linked in the program) that cannot be fulfilled by users on the Stable release channel.

Removing this requirement by having a default behavior would allow:

* `no_std` + `liballoc` applications to start running on the Stable channel
* `no_std` applications that run on Stable to start using `liballoc`

**Comment by joshtriplett** [comment]
We talked about this in today's @rust-lang/lang meeting. We're going to confirm consensus via a quick FCP, since it's been 2 years.

@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot fcp reviewed

**Pull request merged**
