### PR TITLE
add `#[allow(unused_qualifications)]` to derived impls

### LINKED ISSUE #19102: #[deriving] implementations need #[allow(unused_qualifications)]
Example:
```rust
#![warn(unused_qualifications)]

use self::A::B;

#[deriving(PartialEq)]
pub enum A {
    B,
}

fn main() {
}
```

Output:
```
a.rs:7:5: 7:6 warning: unnecessary qualification
a.rs:7     B,
           ^
note: in expansion of #[deriving]
a.rs:5:1: 5:23 note: expansion site
a.rs:1:9: 1:30 note: lint level defined here
a.rs:1 #![warn(unused_qualifications)]
               ^~~~~~~~~~~~~~~~~~~~~
a.rs:7:5: 7:6 warning: unnecessary qualification
a.rs:7     B,
           ^
note: in expansion of #[deriving]
a.rs:5:1: 5:23 note: expansion site
a.rs:1:9: 1:30 note: lint level defined here
a.rs:1 #![warn(unused_qualifications)]
               ^~~~~~~~~~~~~~~~~~~~~
a.rs:7:5: 7:6 warning: unnecessary qualification
a.rs:7     B,
           ^
note: in expansion of #[deriving]
a.rs:5:1: 5:23 note: expansion site
a.rs:1:9: 1:30 note: lint level defined here
a.rs:1 #![warn(unused_qualifications)]
               ^~~~~~~~~~~~~~~~~~~~~
a.rs:7:5: 7:6 warning: unnecessary qualification
a.rs:7     B,
           ^
note: in expansion of #[deriving]
a.rs:5:1: 5:23 note: expansion site
a.rs:1:9: 1:30 note: lint level defined here
a.rs:1 #![warn(unused_qualifications)]
               ^~~~~~~~~~~~~~~~~~~~~
```

This is something that wasn’t an issue before, but with the scoping of enum variants can *very* easily become a problem now.

### PR DESCRIPTION
**Pull request by apasel422**
closes #19102

### CODE REVIEW

**Comment by apasel422** [comment]
Ping.

**Comment by retep998** [comment]
Ping. I really hope this lands soon.

**Comment by apasel422** [comment]
Should this be reassigned?

**Comment by huonw** [comment]
@bors r+

Sorry for the delay!

**Pull request merged**
