### PR TITLE
std: Stabilize the `io` module

### PR DESCRIPTION
**Pull request by alexcrichton**
The new `std::io` module has had some time to bake now, and this commit
stabilizes its functionality. There are still portions of the module which
remain unstable, and below contains a summart of the actions taken.

This commit also deprecates the entire contents of the `old_io` module in a
blanket fashion. All APIs should now have a reasonable replacement in the
new I/O modules.

Stable APIs:
- `std::io` (the name)
- `std::io::prelude` (the name)
- `Read`
- `Read::read`
- `Read::{read_to_end, read_to_string}` after being modified to return a `usize`
  for the number of bytes read.
- `ReadExt`
- `Write`
- `Write::write`
- `Write::{write_all, write_fmt}`
- `WriteExt`
- `BufRead`
- `BufRead::{fill_buf, consume}`
- `BufRead::{read_line, read_until}` after being modified to return a `usize`
  for the number of bytes read.
- `BufReadExt`
- `BufReader`
- `BufReader::{new, with_capacity}`
- `BufReader::{get_ref, get_mut, into_inner}`
- `{Read,BufRead} for BufReader`
- `BufWriter`
- `BufWriter::{new, with_capacity}`
- `BufWriter::{get_ref, get_mut, into_inner}`
- `Write for BufWriter`
- `IntoInnerError`
- `IntoInnerError::{error, into_inner}`
- `{Error,Display} for IntoInnerError`
- `LineWriter`
- `LineWriter::{new, with_capacity}` - `with_capacity` was added
- `LineWriter::{get_ref, get_mut, into_inner}` - `get_mut` was added)
- `Write for LineWriter`
- `BufStream`
- `BufStream::{new, with_capacities}`
- `BufStream::{get_ref, get_mut, into_inner}`
- `{BufRead,Read,Write} for BufStream`
- `stdin`
- `Stdin`
- `Stdin::lock`
- `Stdin::read_line` - added method
- `StdinLock`
- `Read for Stdin`
- `{Read,BufRead} for StdinLock`
- `stdout`
- `Stdout`
- `Stdout::lock`
- `StdoutLock`
- `Write for Stdout`
- `Write for StdoutLock`
- `stderr`
- `Stderr`
- `Stderr::lock`
- `StderrLock`
- `Write for Stderr`
- `Write for StderrLock`
- `io::Result`
- `io::Error`
- `io::Error::last_os_error`
- `{Display, Error} for Error`

Unstable APIs:

(reasons can be found in the commit itself)
- `Write::flush`
- `Seek`
- `ErrorKind`
- `Error::new`
- `Error::from_os_error`
- `Error::kind`

Deprecated APIs
- `Error::description` - available via the `Error` trait
- `Error::detail` - available via the `Display` implementation
- `thread::Builder::{stdout, stderr}`

Changes in functionality:
- `old_io::stdio::set_stderr` is now a noop as the infrastructure for printing
  backtraces has migrated to `std::io`.

[breaking-change]

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that in the fallout commit I have duplicated "TTY detection" between libtest and libsyntax as well as a structure to replace `Chan{Reader,Writer}` in rustc_driver/libtest. The current `set_stderr` interface is now a noop, but I replaced it with a `set_panic` hidden function (unstable) in `std::io`. I don't want to regress functionality in terms of quality of compiler diagnostics as well as test output for now, so we can reconsider the function later on.

**Comment by alexcrichton** [comment]
I've modified the first commit to remove the `FooExt` traits by folding functionality with `where Self: Sized` into the main `Read`/`Write`/`BufRead` traits.

**Comment by aturon** [comment]
Really, really exciting. What a long haul!

@bors: r+ b1f2158

**Comment by aturon** [comment]
(I left some very minor nits, feel free to fix when it bounces ;-)

**Pull request merged**
