### PR TITLE
Relax orderings in std::sync::once

### PR DESCRIPTION
**Pull request by jeehoonkang**
Currently, in `std::sync::once`, every access to the shared objects are `SeqCst`, while it doesn't need to be.  I relaxed orderings to `Acquire`, `Release`, and `AcqRel`.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This has actually been [proposed before](https://github.com/rust-lang/rust/pull/31650) and my own personal opinions at least [haven't changed much](https://github.com/rust-lang/rust/pull/31650#issuecomment-184532666).

Mind reading over some of the discussion there and posting your thoughts on it?

**Comment by jeehoonkang** [comment]
@alexcrichton Thank you!  I haven't notice that there was a closed PR on this issue.  I will discuss further in that issue.

**Comment by aidanhs** [comment]
Hi @jeehoonkang @alexcrichton, just wondering what the status of this PR is after the (brief) exchange on #31650 - is this waiting on review, or are we looking for a bit more justifying background?

**Comment by alexcrichton** [comment]
@jeehoonkang do you think `SeqCst` as-is today is wrong? (in the LLVM implementation rather than the standard) If not, do you think this has a technical benefit over the current construction?

**Comment by jeehoonkang** [comment]
@aidanhs @alexcrichton The current implementation with `SeqCst` is correct.  What I want to argue is that the reason it is correct is exactly the same as the reason a version with `Release` and `Acquire` is correct, because currently LLVM's `SeqCst` is broken and it doesn't give you a better reasoning principle than `Release` and `Acquire`.

That said, I kinda agree with the conclusion made in #31650 that we keep `SeqCst`.  Without a formal proof, it would be just safer to keep the strongest ordering, which is `SeqCst`.  If performance difference is not that great, I agree that we don't merge it now.

I agree to **close** this PR.  Maybe later we can reopen, once someone clearly explains why `Release` and `Acquire` is safe in `once`.

**Comment by alexcrichton** [comment]
Ok sounds good to me, thanks regardless @jeehoonkang !

**Pull request closed without merging**
