### PR TITLE
[typo] fix typo in panicking.rs

### PR DESCRIPTION
**Pull request by syheliel**

### CODE REVIEW

**Comment by tgross35** [comment]
Lol I think the commit was just made by a pirate. From 2016 @alexcrichton https://github.com/rust-lang/rust/commit/0ec321f7b541fcbfbf20286beb497e6d9d3352b2#diff-a764274bf8d1938779a1fd5ad2ac211f01a4f99362e5aadeccab818f4edd2a91R386

**Comment by joboet** [comment]
To be honest, I quite like this bit of humour actually, it makes the comment less dry. Mind if I close this?

**Comment by syheliel** [comment]
@joboet Hi, the reason I made this PR is that I have a hard time finding how to set a breakpoint on each panic when debugging by lldb.  I think the modified version is easier to find when you use Google to search for catch every `panic!`. 

Also, I think `rust_panic`'s usage in debugging may be worth being mentioned in the doc.

**Comment by alexcrichton** [comment]
Alas while I wish I were this clever I [am not](https://github.com/rust-lang/rust/commit/705f472c5509ec3a8fe3448541282eca1386344a)

**Comment by Nilstrieb** [comment]
This comment will be wrong after  #127173 :). And I don't think we're gonna want to make it `#[no_mangle]`.

**Comment by syheliel** [comment]
@Nilstrieb so sad :( Could you kindly provide some guidane for setting breakpoint on panic after #127173 ?

**Comment by JohnCSimon** [comment]
from triage: 


@syheliel - do u

**Comment by Dylan-DPC** [comment]
Closing this based on the above comments. Thanks for the contribution

**Pull request closed without merging**
