### PR TITLE
Simplify encoder and decoder

### PR DESCRIPTION
**Pull request by cjgillot**
Extracted from https://github.com/rust-lang/rust/pull/83036 and https://github.com/rust-lang/rust/pull/82780.

### CODE REVIEW

**Comment by joshtriplett** [comment]
This provides a decent improvement on max-rss, but regresses on instructions.

**Comment by joshtriplett** [comment]
Still appears to be a substantial regression, unfortunately.

**Comment by michaelwoerister** [comment]
I've done a few similar things in https://github.com/rust-lang/rust/pull/82183/commits/c49297da5c7b0990397cfdc86c61dca27ff92ae0 (part of #82183). I did not see performance regressions there. Maybe that's of interest.

**Comment by Aaron1011** [comment]
cc @rust-lang/infra ^ - it looks like the permissions for `rust-timer` are messed up somehow.

**Comment by bjorn3** [comment]
Improvements up to 1.5%.

**Comment by lcnr** [comment]
can someone else take this over, I don't have a lot of capacity rn

r? @michaelwoerister maybe, feel free to reassign

**Comment by michaelwoerister** [comment]
Looks good to me. I'm still not a fan of all that unsafe code and most of it can be removed as https://github.com/rust-lang/rust/commit/c49297da5c7b0990397cfdc86c61dca27ff92ae0 demonstrates. 

I'd also prefer if `read_raw_bytes` would just borrow the underlying data instead of copying it to `&mut [MaybeUninit<u8>]`. That works with the `opaque` decoder but can't be done if `read_raw_bytes` is moved to the `Decoder` trait, as this PR does. I hope we can make that change once we get rid of JSON encoding as https://github.com/rust-lang/compiler-team/issues/418 proposes.

But for now this PR is still a strict improvement.

@bors r+

**Pull request merged**
