### PR TITLE
Stabilize str_split_once

### LINKED ISSUE #74773: Tracking Issue for str_split_once
Feature gate: `#![feature(str_split_once)]`

### Public API

```rust
impl str {
    pub fn split_once<'a, P: Pattern<'a>>(&'a self, delimiter: P) -> Option<(&'a str, &'a str)>;
    pub fn rsplit_once<'a, P: Pattern<'a>>(&'a self, delimiter: P) -> Option<(&'a str, &'a str)>;
}
```

### Steps / History

- [x] Implementation: #74707
- [x] Final commenting period (FCP): https://github.com/rust-lang/rust/issues/74773#issuecomment-776643142
- [ ] Stabilization PR: #81940

### Unresolved Questions

* [x] Should the method return the separator as well (`(&str, &str, &str)`)? (https://github.com/rust-lang/rust/issues/76512)
  * https://github.com/rust-lang/rust/issues/74773#issuecomment-737216336

### PR DESCRIPTION
**Pull request by jhpratt**
Closes #74773

### CODE REVIEW

**Comment by jhpratt** [comment]
@rustbot modify labels to +T-libs, +A-str

Dang it rustbot let me set labels!

**Comment by jhpratt** [comment]
Not quite sure why this is failing, as the methods are definitely stabilized here.

**Comment by tesuji** [comment]
tidy tool uses beta toolchain to compile ?

**Comment by jhpratt** [comment]
@tesuji If that's the case, why did it build before?

**Comment by tesuji** [comment]
> @tesuji If that's the case, why did it build before?

I'm not certain but one could use RUSTC_BOOTSTRAP flag to enable nightly feature on beta/stable channel.

**Comment by jhpratt** [comment]
Not to be rude, but I'd honestly rather you not guess. There are others that have knowledge as to why this isn't building, and I'm fine waiting for them. Better to have one definitive answer than a few guesses, as I'm sure you can understand.

**Comment by Mark-Simulacrum** [comment]
It does look like we currently globally set RUSTC_BOOTSTRAP for all compilations - I had thought we had stopped doing so for bootstrap compiler only tools, but I guess I just wanted to for long enough that it made it happen.

I believe it should be sufficient to just leave the feature gates in for tidy and linkcheck, with a comment having the text cfg(bootstrap) in it above them - I think cfg_attr would be preferable but I'm not 100% sure it will work for the bootstrap tools (it should, though). If it doesn't then just a comment with cfg(bootstrap) on the feature gates is enough.

Otherwise it looks like this is good but will need a T-libs FCP, so once we get CI fixed I'll reassign.

**Comment by jhpratt** [comment]
CI is green.

**Comment by m-ou-se** [comment]
This is blocked on the FCP on the tracking issue: https://github.com/rust-lang/rust/issues/74773#issuecomment-776643142

**Comment by matklad** [comment]
Based on https://github.com/rust-lang/rust/issues/74773#issuecomment-786186178

bors r+

**Pull request merged**
