### PR TITLE
Add buffering to stdout

### PR DESCRIPTION
**Pull request by n-milo**
This PR includes implementing `IsTerminal` for the raw `sys::stdio` structs, so we can check terminal status without constructing an `Stdout` object.

Then `Stdout` switches from wrapping a `LineWriter` to a `StdoutWriter`, which wraps either a `LineWriter` or `BufWriter` depending on whether or not stdout is pointing to a terminal. This means standard output will no longer be line-buffered when outputting to a non-terminal.

We could also make stdout wrap a `dyn Write` instead of the `StdoutWriter` enum, which would make it simpler but I figured we don't want dynamic dispatch for every write to stdout.

### CODE REVIEW

**Comment by joshtriplett** [comment]
The first three commits LGTM.

The remainder will need an FCP to change behavior.

**Comment by the8472** [comment]
This touches on two topics

A) Is it ok to hand out file borrowed descriptors that violate the locks? #114140
Until that question is resolved we shouldn't expose them. And we can't add those APIs unstably since they're trait implementations.

B) Blockbuffering for stdout. #60673 and https://github.com/rust-lang/rust/pull/78515#issuecomment-1168362639
I think this requires more complex API changes because a user may still want line-buffering even when writing to a pipe for example because the pipe connects to a parent processes that interleaves multiple children to a terminal. Switching to block buffering may then end up tearing line endings or delay the output more than it currently does. So they user would at least need an API to switch back to line-buffering. Implementing such an API is what the linked issues are about.

**Comment by m-ou-se** [comment]
Changing the block buffering behaviour for stdout should be done in two steps:

1. Add an API for switching buffering mode for stdout (line, block, none). That way, Rust programs can opt-in to block buffering.
2. Change the default behaviour to block buffering when the output is not a tty. Then, Rust programs can still opt-out using the API from step 1.

I am *personally* not convinced (yet?) we should actually do step 2, but we all seem to be in favour of at least taking step 1. Step 2 can be a separate discussion.

For step 1, we'd first need to see a proposal for an API for this. Several ideas have come up in the past, including adding a new 'switchable buffer/writer' type to `std::io`, adding a line buffering mode to `BufWriter`, adding a block buffering mode to `LineWriter`, adding a `std::io::set_stdio_mode` function taking an enum, and probably a few more ideas.

See also https://github.com/rust-lang/rust/pull/78515#issuecomment-1168362639

I personally think that adding a block buffering mode to `LineWriter` (and exposing that on `Stdout` too) is the cleanest solution, but am open to other solutions as well.

**Comment by joshtriplett** [comment]
r? libs-api

**Comment by m-ou-se** [comment]
Closing this because of https://github.com/rust-lang/rust/pull/115652#issuecomment-1766439033. Feel free to propose an API for step 1 to get things moving. Thanks!

**Pull request closed without merging**
