### PR TITLE
Move `Layout` and `LayoutErr` to `core::mem`

### LINKED ISSUE #59: Move `Layout` and `LayoutErr` to `core::mem`
`Layout` is basically a wrapper around `mem::size_of` and `mem::align_of` (batteries included) and should live in the same module. For compatibility, `Layout` (and its Error) have to be reexported to `core::alloc`.

NB: As the discussion just came up (#57), it would also be possible to rename `LayoutErr` to `LayoutError` in `core::mem` and reexport it in `core::alloc` as `LayoutErr`.

### PR DESCRIPTION
**Pull request by TimDiekmann**
This moves `core::alloc::{Layout, LayoutErr}` to `core::mem::{Layout, LayoutError}` and reexport them as `core::alloc::{Layout, LayoutErr}`. Currently it is neither possible to deprecate reexports, nor to document them, however I added the comment so it shows up if *rustdoc* supports this one day. Also `#[doc(no_inline)]` was added to express, that this is a reexport, this is probably the best bet. The alternative would be `#[doc(hidden)]`.

It's may be an option to also reexport `mem::LayoutError` as `alloc::LayoutError` but this is not required.

~I have another commit in the queue which changes (I hope) all occurrences to the new path, but I want to wait for the CI first. This shouldn't cause *any* errors or warnings.~ I pushed the commit. All previous test passed.

r? @LukasKalbertodt 

closes rust-lang/wg-allocators#59

### CODE REVIEW

**Comment by Amanieu** [comment]
I'm not a big fan of this change since it feels like a lot of churn for something that is already stable. However I can see that `core::mem` is also a good location for `Layout` since it isn't strictly allocation-related (it could be used for things like `offset_of`, safe transmute, etc).

@rust-lang/libs any thoughts?

**Comment by BurntSushi** [comment]
Also not a huge fan of this. I can see how `mem` could be a good spot for it, but `alloc` actually seems like the best spot since it's part of the core allocator API. At the very least, `alloc` doesn't seem like a bad spot to me.

**Comment by dtolnay** [comment]
How about we revisit this if a method is ever added in core::mem involving Layout in the signature. For now alloc is the only module containing methods that involve Layout, even if the same type is useful for other purposes.

**Pull request closed without merging**
