### PR TITLE
cleanup: remove the *san Cargo features from std

### PR DESCRIPTION
**Pull request by japaric**
these belong to a previous iteration of the sanitizer implementation

r? @alexcrichton
cc @whitequark

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 

Thanks!

**Comment by frewsxcv** [comment]
This PR might have caused this issue: https://travis-ci.org/rust-lang/rust/jobs/202521389

**Comment by japaric** [comment]
> command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "arm-unknown-linux-gnueabihf" "--release" "--locked" "--manifest-path" "/checkout/src/rustc/std_shim/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std_shim:0.0.0" "-p" "core:0.0.0" "-p" "std:0.0.0" "-p" "std_unicode:0.0.0" "-p" "rand:0.0.0" "-p" "collections:0.0.0" "-p" "panic_abort:0.0.0" "-p" "compiler_builtins:0.0.0" "-p" "unwind:0.0.0" "-p" "rustc_asan:0.0.0" "-p" "rustc_msan:0.0.0" "-p" "rustc_tsan:0.0.0" "-p" "alloc:0.0.0" "-p" "rustc_lsan:0.0.0" "-p" "alloc_system:0.0.0" "-p" "libc:0.0.0" "--no-run" "--" "--quiet"

This looks wrong because rustc_asan and friends are only dependencies of std on x86_64 Linux but this is testing for arm-linux. It seems that bootstrap has build the dependency graph of std assuming that the target is x86_64-linux. bootstrap is using `cargo metadata` to build the dependency graph and that contains `target` information so this seems fixable. I'll take a look.

**Comment by japaric** [comment]
If I'm reding this correctly, bootstrap uses `cargo metadata`s `resolve` field which, I think, contains the dependency graph that has been resolved for the host -- we can't use that one because that's e.g. for x86_64-linux but we want the dep graph for arm-linux.

`cargo metadata` also contains a "non resolved" version which seems to be pretty much a verbatim copy of the involved Cargo.tomls. That version distinguishes between `dependencies` and `target.*.dependencies`. We could use that "non resolved" version but the "target" information is represented as, e.g., `null`, `"cfg(os = "windows")"` and `"x86_64-unknown-linux-gnu"`. The second form, with the `cfg`, seem like it's going to be difficult to dealt with. We'll have to replicate some of Cargo's cfg logic :-/.

A much simpler but hacky solution would be to blacklist rustc_asan and company in check.rs; that way we could filter away those crates so they are never passed to the `cargo test` command shown above.

@alexcrichton thoughts? ^

**Comment by alexcrichton** [comment]
@japaric I think the easiest solution would be to add this to all sanitizer `Cargo.toml`, right?

```toml
[lib]
test = false
```

The lib isn't intended to be unit tested, right?

**Comment by japaric** [comment]
Oh, is that enough? OK. r? @alexcrichton

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by alexcrichton** [comment]
ping @japaric (rebase)

**Comment by japaric** [comment]
@alexcrichton rebased

**Pull request merged**
