### PR TITLE
rustdoc: add optional woff2 versions of Source Serif and Source Code

### PR DESCRIPTION
**Pull request by tspiteri**
This provides woff2 versions of Source Serif and Source Code similar to how #82545 provides woff2 versions of Fira Sans. The total byte count for the six files (three for each font family) is reduced by 25% from 476 KiB to 358 KiB.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good to me but considering how complicated font updates were in the past, I'll ask our expert to review. :)

r? @jsha

**Comment by jsha** [comment]
I've confirmed that the SourceCodePro files are identical with the ones from https://github.com/adobe-fonts/source-code-pro/releases/tag/2.038R-ro%2F1.058R-it%2F1.018R-VAR, and that the SourceSerif4 files are identical with the ones from https://github.com/adobe-fonts/source-serif. And all the diffs seem to be correct. 👍🏻 Thanks for making this change, @tspiteri.

@bors r+

**Comment by tspiteri** [comment]
I cannot interpret the logs and have no idea why CI failed.

**Comment by jsha** [comment]
I also don't understand the test logs. Perhaps it is an intermittent failure? Let's retry:

@bors try

Also cc @jyn514 any idea why the tests failed above?

**Comment by jyn514** [comment]
Failed without logs, the apple machine must have been reallocated in the middle of a build.

@bors retry

image

**Comment by jyn514** [comment]
@jsha note that `bors try` is different, it only builds artifacts but does not merge the PR. It's usually used for perf runs, or occasionally if people need to download changes with rustup before they've been merged.

**Comment by jyn514** [comment]
@rust-lang/infra I think we confused bors, do you know how to fix it?

**Pull request merged**
