### PR TITLE
Add vendor to Fuchsia's target triple

### PR DESCRIPTION
**Pull request by djkoloski**
Historically, Rust's Fuchsia targets have been labeled x86_64-fuchsia and aarch64-fuchsia. However, they should technically contain vendor information. This CL changes Fuchsia's target triples to include the "unknown" vendor since Clang now does normalization and handles all triple spellings.

This was previously attempted in #90510, which was closed due to inactivity.

### CODE REVIEW

**Comment by ehuss** [comment]
r? compiler

**Comment by djkoloski** [comment]
cc @tmandry

**Review by tmandry — APPROVED** [review]

**Comment by nagisa** [comment]
Well, if Tyler thinks its fine then it seems good to me too!

@bors r+

**Comment by ehuss** [comment]
@bors retry
#93784

**Pull request merged**
