### PR TITLE
Update rayon and rustc-rayon

### LINKED ISSUE #92677: `tidy` license check error for `crossbeam-queue`
Getting this error in #90842:

```
tidy error: invalid license `MIT/Apache-2.0 AND BSD-2-Clause` in `crossbeam-queue 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)`
```

> I think this is a bug in tidy.
> 
> In `src/tools/tidy/src/deps.rs` `EXCEPTIONS`, there is already an exception for `crossbeam-queue`. However, exceptions are not allowed for the runtime crates that make up the standard library.
> 
> With the `backtrace` feature, `std` depends on `object`. Then `object` has a conditional dependency on `indexmap`, but this is not enabled under `std`. However, if you look at the whole workspace metadata at once (as tidy does), then the compiler enables the `object` features that require `indexmap`, and now also the `indexmap` feature for `rustc-rayon` too.
> 
> So tidy sees `std` -> `object` -> `indexmap` -> `rustc-rayon` -> `rustc-rayon-core` -> `crossbeam-queue` in the metadata, and thus includes *all* of that in "runtime" crates, and then the exception isn't allowed. But if you look at `cargo tree --all-features -p std`, they aren't really included at all.
> 
_Originally posted by @cuviper in https://github.com/rust-lang/rust/issues/90842#issuecomment-1007815922_

### PR DESCRIPTION
**Pull request by cuviper**
This updates rayon for various tools and rustc-rayon for the compiler's parallel mode.

- rayon v1.3.1 -> v1.5.1
- rayon-core v1.7.1 -> v1.9.1
- rustc-rayon v0.3.1 -> v0.3.2
- rustc-rayon-core v0.3.1 -> v0.3.2

... and indirectly, this updates all of crossbeam-* to their latest versions.

Fixes #92677 by removing crossbeam-queue, but there's still a lingering question about how tidy discovers "runtime" dependencies. None of this is truly in the standard library's dependency tree at all.

### CODE REVIEW

**Comment by cuviper** [comment]
Odd, `i686-msvc-1` and `x86_64-msvc-1` stalled in the same place:

```
Testing rustc_macros stage1 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
[RUSTC-TIMING] build_script_build test:false 0.896
[RUSTC-TIMING] unicode_xid test:false 0.181
[RUSTC-TIMING] build_script_build test:false 0.708
[RUSTC-TIMING] proc_macro2 test:false 2.249
[RUSTC-TIMING] quote test:false 1.004
[RUSTC-TIMING] syn test:false 21.663
[RUSTC-TIMING] synstructure test:false 2.537
[RUSTC-TIMING] rustc_macros test:false 5.514
   Compiling rustc_macros v0.1.0 (D:\a\rust\rust\compiler\rustc_macros)
Error: The operation was canceled.
```

CI passed everywhere else, including the equivalent mingw runners.

**Comment by mati865** [comment]
There were several different issues with MSVC CI recently, worth retrying.

**Comment by klensy** [comment]
One more of https://github.com/rust-lang/rust/pull/92883#issuecomment-1013332090

**Pull request merged**
