### PR TITLE
Autogenerate SIMD intrinsics for AArch64, ARM and x86

### PR DESCRIPTION
**Pull request by huonw**
This adds a new Python script (compatible with 2.7 and 3.x) that will consume some JSON files that define a platform's intrinsics. It can output a file that defines the intrinsics in the compiler, or an `extern` block that will import them.

The complexity of the generator is to be DRY: platforms (especially ARM and AArch64) have a lot of repetition with their intrinsics, for different versions with different types, so being able to write it once is nice.

### CODE REVIEW

**Comment by huonw** [comment]
(I should do some more testing to make sure the definitions are correct before this lands, but if there are any mistakes, they'll probably just be local one-line changes to a JSON file.)

**Comment by alexcrichton** [comment]
Looks good to me, r=me once you're satisfied the JSON is right

**Pull request merged**
