### PR TITLE
Update RLS and Cargo

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes the `test-fail` RLS toolstate caused by #59114.

r? @Centril @Manishearth

### CODE REVIEW

**Comment by ehuss** [comment]
This won't work without updating cargo.  I can post a PR, or you can just add the cargo update here.

**Comment by Xanewok** [comment]
Right, makes sense! Included the Cargo update to the version it was bumped to in https://github.com/rust-lang/rls/pull/1448.

@bors r=Manishearth

**Comment by Centril** [comment]
@bors retry

Yielding prio to https://github.com/rust-lang/rust/pull/60519 which includes https://github.com/rust-lang/rust/pull/60496

**Comment by Manishearth** [comment]
That's a doc fix for a pretty obscure platform, I don't think that should have lower priority here. These tools are used by lots of people and it's annoying for them when they're broken on nightly.

**Comment by jethrogb** [comment]
> That's a doc fix for a pretty obscure platform,

It's not a doc fix, it's a security bug fix.

**Comment by Manishearth** [comment]
Not quite, it's fixing the _potential_ of a security bug in an internal API on an obscure platform. The only danger there is someone committing a change to libstd in the next few days that ignores this yet-undocumented invariant, causing an actual security bug to be shipped.

It needs to be landed, but there's no rush.

**Comment by Manishearth** [comment]
Oh, I missed the assertion in the PR. Never mind.

**Comment by kennytm** [comment]
Something's wrong with the incremental test on 32-bit Windows.

**Comment by ehuss** [comment]
Can someone retry this?  It shouldn't be possible for this PR to affect the incremental tests.  I also built i686-pc-windows-gnu locally and the incremental tests seem fine.

**Comment by kennytm** [comment]
@bors retry

Travis connection reset while updating homebrew.

**Pull request merged**
