### PR TITLE
Load all DefPathHash -> DefId mappings before dumping dep graph

### LINKED ISSUE #79723: `-Z dump-graph` now longer prints def paths since PR #74967
The changes in PR #74967 ended up breaking the way that we debug-print `DepNodes` with `-Z dump-graph`.
The simplest way to fix this might be to just fall back to the old approach (build a table of all `DefPathHash`es across all crates) when we need to debug-print for `-Z dump-graph`.

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #79723

### CODE REVIEW

**Comment by tgnottingham** [comment]
The DPH mapping functionality isn't inherently associated with `OnDiskCache`, and using `OnDiskCache` in non-incremental mode is kinda funny. So, you could have `debug_def_path_hash_to_def_id` live in `GlobalCtxt`, and have a method that uses it during non-incremental, and uses `OnDiskCache::def_path_hash_to_def_id` during incremental. That also has the nice property that `OnDiskCache` uses the same code path and structures to map DPHs regardless of whether or not we're dumping the dep graph.

Only issue is that `OnDiskCache::def_path_hash_to_def_id` doesn't currently work for foreign `DefPathHashes` that didn't exist in previous session, but do in this session, so that would need to be changed. But that might be nice anyway, as I can easily see someone not expecting it.

Also, before #74967, the equivalent of `debug_def_path_hash_to_def_id` was populated when `opts.build_dep_graph()` was true, i.e. when either `-Z dump_dep_graph` or `-Z query_dep_graph` was specified, but now it's only built for `dump_dep_graph`.

**Comment by michaelwoerister** [comment]
I hope I'll get to reviewing this next week. Thanks for the PR, @Aaron1011!

**Comment by michaelwoerister** [comment]
Thanks for trying to fix this, @Aaron1011!

I've been taking a look at the implementation and I think I understand how it works -- but I'm a bit hesitant to make things more complex for a feature like `-Zdump-dep-graph` which I suspect is rarely ever used. Like @tgnottingham, I'm also a bit worried about instantiating an `OnDiskCache` in non-incremental mode because it's rather unexpected and might lead to confusion and the need for special casing down the line.

Am I correct in the assumption that the output of `-Zdump-dep-graph` works fine (even without this PR) if compiling in incremental mode? If so I would suggest just emitting a warning if `-Zdump-dep-graph` is passed to the compiler without `-Cincremental` being passed too.

These dependency graph debugging options are all really old. We could probably simplify things if we just assumed that the dep-graph will only ever be built in incremental mode.

**Comment by JohnCSimon** [comment]
Ping from triage
@Aaron1011  - can you please address the build failures, merge conflicts, and comments from the reviewer? Thank you.

@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by Dylan-DPC** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
