### PR TITLE
[LLVM 4.0] Update AlwaysInliner pass header and constructor

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Out of curiosity, do you know if there's an easily available "not legacy" version that we should be migrating towards?

**Comment by shepmaster** [comment]
> an easily available "not legacy" version

A good point, @alexcrichton! Here's what the header has to say:

```c++
/// Inlines functions marked as "always_inline".
///
/// Note that this does not inline call sites marked as always_inline and does
/// not delete the functions even when all users are inlined. The normal
/// inliner should be used to handle call site inlining, this pass's goal is to
/// be the simplest possible pass to remove always_inline function definitions'
/// uses by inlining them. The \c GlobalDCE pass can be used to remove these
/// functions once all users are gone.
```

It looks like it was introduced in llvm-mirror/llvm@b699f7b88fcfbddfb4d7f98a85cbf3373c32049d:

> Notably things this doesn't support:

>    - Array alloca merging
>      - To support the above, bottom-up inlining with careful history
>        tracking and call graph updates
>    - DCE of the functions that become dead after this inlining.
>    - Inlining through call instructions with the always_inline attribute.
>      Instead, it focuses on inlining functions with that attribute.

Do you know if the intended Rust usage of this pass includes any of those?

**Comment by rkruppe** [comment]
The "legacy" part refers to the legacy pass manager (cf. https://github.com/llvm-mirror/llvm/commit/b699f7b88fcfbddfb4d7f98a85cbf3373c32049d) so I don't think we can migrate without switching to the new pass manager wholesale, which seems (1) difficult and (2) premature since the new pass manager doesn't have feature parity yet AFAIK.

**Comment by alexcrichton** [comment]
Oh ok if this is just related to that infrastructure seems fine!

@bors: r+

I fear the day the legacy pass manager goes away, but presumably we'll deal with that then.

**Pull request merged**
