### PR TITLE
cache type sizes in type-size limit visitor

### PR DESCRIPTION
**Pull request by lqd**
This is basically https://github.com/rust-lang/rust/pull/125507#issuecomment-2206813779 as lcnr can't open the PR now.

Locally it reduces the `itertools` regression by quite a bit, to "only +50%" compared to nightly (that includes overhead from the local lack of artifact post-processing, and is just a data point to compare to the 10-20x timings without the cache).

```console
Benchmark 1: cargo +stage1 build --release
  Time (mean ± σ):      2.721 s ±  0.009 s    [User: 2.446 s, System: 0.325 s]
  Range (min … max):    2.710 s …  2.738 s    10 runs

Benchmark 2: cargo +nightly build --release
  Time (mean ± σ):      1.784 s ±  0.005 s    [User: 1.540 s, System: 0.279 s]
  Range (min … max):    1.778 s …  1.792 s    10 runs

Summary
  cargo +nightly build --release ran
    1.52 ± 0.01 times faster than cargo +stage1 build --release
```

On master, it's from 34s to the 2.7s above.

r? compiler-errors

### CODE REVIEW

**Comment by lqd** [comment]
The joys of `--keep-stage 1` and not running tests 👍 .

@bors try

**Comment by lqd** [comment]
This should be ready to review, as at least a first step to reduce the problem.

@rustbot ready

**Comment by compiler-errors** [comment]
comparison url using the start of #125507's perf run and the end is this commit. Looks like we fixed everything unless I just can't read?

https://perf.rust-lang.org/compare.html?start=2db4ff40af2b9f93b6240dbd67ed7f2f34b19776&end=83217ae97e94eb43ce31396b49a938608f7f9c06&stat=instructions:u

**Comment by Kobzol** [comment]
Resolved a perf. regression from https://github.com/rust-lang/rust/pull/125507.

@rustbot label: +perf-regression-triaged

**Pull request merged**
