### PR TITLE
Improve CFG construction for match expressions

### LINKED ISSUE #22073: Moves in guard expressions aren't handled properly
This code causes a segfault (without optimisations on):

```rust
use std::fmt;
fn main() {
    let a = std::rc::Rc::new(1);
    
    let x = (1, 2);
    
    match x {
        (_, y) |
        (y, _) if take(y, a) => (),
        _ => ()
    }

}

fn take<T:fmt::Debug>(x: usize, t: T) -> bool {
    println!("{:?}", t);
    x == 1
}
```

as does this similar code:

```rust
use std::fmt;
fn main() {
    let a = std::rc::Rc::new(1);
    
    let x = (1, 2);
    
    match x {
        (_, y) if take(y, a) => (),
        (y, _) if take(y, a) => (),
        _ => ()
    }

}

fn take<T:fmt::Debug>(x: usize, t: T) -> bool {
    println!("{:?}", t);
    x == 1
}
```

This is because the current control flow graph essentially visits each arm in parallel. With multiple patterns, each pattern within the arm is visited, then the guard is visited after all the patterns have been visited, even though this doesn't reflect the real semantics (we visit the pattern, then the guard, then the next pattern, then the guard again).

### PR DESCRIPTION
**Pull request by Aatch**
Previously, for each arm, each pattern would be visited, then the guard, then the body. All arms would be visited in parallel.

Now, the patterns in each arm are visited in parallel, but after each pattern, the guard is visited. Furthermore, an edge is added from each guard to the next, reflecting the fact that a guard may be evaluated multiple times, and that multiple guards may be evaluated. This required changing dataflow to handle the fact that there is now a 1-many mapping of NodeIds -> CFGIndex.

This also:
- Refactors the CFG a little to use explicit node types for entry, exit, dummy and unreachable nodes.
- Extends the graphviz library to allow for customisation of the graph nodes. This is used for pretty-printing the CFG.
- Shows the matches when requested item is not unique. Methods on generic types don't seem to be able to be matched, so this just prints out the items that match the suffix provided, which includes the node id.

Fixes #22073

### CODE REVIEW

**Comment by pnkfelix** [comment]
> can you make this return an Option<NodeAttributes>

Thinking further on this point, I wonder if instead all of the fields in `NodeAttributes` should be `Options`.  Because under my suggestion above, you get clean output if you attach *no* attributes, but you still will get a fair amount of boilerplate when all you want is to insert a single attribute.

**Comment by Aatch** [comment]
@pnkfelix in light of the work I'm currently doing, I may just revert the graphviz-specific changes. I've written a much more full-featured system that 1) avoids outputting attributes that are the default, 2) allows for node and edge attributes to be set at the graph level and 3) allows both nodes and edges to be set.

**Comment by pnkfelix** [comment]
@Aatch that sounds fine with me.  So I'll just focus on reviewing the changes to the control-flow graph itself.

**Comment by pnkfelix** [comment]
(I'll be posting a PR with a subset of the work here shortly. Thanks a ton @Aatch; I'm making sure to retain your authorship meta-data on the new commits.)

**Comment by pnkfelix** [comment]
closing in favor of #22580 (which is essentially the same as the first commit in this PR, apart from some factoring into separate commits, cutting of some details I decided were not strictly necessary, and slight fixes to the very helpful comment from @Aatch ).

**Pull request closed without merging**
