### PR TITLE
Point at last valid token on failed `expect_one_of`

### LINKED ISSUE #32540: provide better diagnostic for forgotten semicolon token
this code

```
fn main(){
    let value = 20;
    let m = match value {
        20 => true,
        40 => false,
        _ => false
    }

    println!("{}", m);
}
```

give this error message:

```
C:\depot>rustc ex.rs
ex.rs:9:5: 9:12 error: expected one of `.`, `;`, `?`, or an operator, found `println`
ex.rs:9     println!("{}", m);
            ^~~~~~~
error: aborting due to previous error
```

ideally, the error is something like this:

```
C:\depot>rustc ex.rs
ex.rs:7:5: 7:12 error: expected one of `.`, `;`, `?`, or an operator after '}' token
ex.rs:7     }
            ^~
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by estebank**
```rust
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `)`
  --> $DIR/token-error-correct-3.rs:29:9
   |
25 |         foo()
   |              - expected one of `.`, `;`, `?`, `}`, or an operator after this
...
29 |     } else {
   |     ^ unexpected token
```

Fix #32540.

### CODE REVIEW

**Comment by nagisa** [comment]
> error: expected one of `.`, `;`, `?`, `}`, or an operator, found `)`

Sounds wrong. It says it expects those symbols instead of/before the parenthesis, although I think it might just be the example mis-copied and not actual output from the compiler (as the tests look good)?

---

I would also investigate if something like this is possible (note how label is shifted by 1):

```
   |
25 |         foo()
   |              - expected one of `.`, `;`, `?`, `}`, or an operator here
...
29 |     } else {
   |     ^ unexpected token
```

**Comment by estebank** [comment]
> I think it might just be the example mis-copied

Indeed, that was the case, @nagisa. 

> I would also investigate if something like this is possible (note how label is shifted by 1):

I was afraid the output when the unexpected token is right after the last correctly parsed token wouldn't be too great, but now that I mocked it out, it doesn't seem too bad:

```rust
   |
25 |         foo()} else {
   |              ^
   |              |
   |              expected one of `.`, `;`, `?`, `}`, or an operator here
   |              unexpected token
```

**Comment by estebank** [comment]
I've changed it so that when the next parsed token is in the same place as the next expected token, we only show the most detailed label

```rust
25 |         foo()} else {
   |              ^ expected one of `.`, `;`, `?`, `}`, or an operator here
```

vs.

```rust
25 |             fs::create_dir_all(path.as_ref()).map(|()| true)
   |                                                             - expected one of `.`, `;`, `?`, `}`, or an operator here
...
29 |         } else {
   |         ^ unexpected token
```

**Comment by estebank** [comment]
Ping.

**Comment by alexcrichton** [comment]
r? @jonathandturner 

or maybe @nrc

**Comment by jonathandturner** [comment]
I'd probably detect this case:

```
   |
25 |         foo()} else {
   |              ^
   |              |
   |              expected one of `.`, `;`, `?`, `}`, or an operator here
   |              unexpected token
```

And just give a single message instead, like:

```
   |
25 |         foo()} else {
   |              ^
   |              |
   |              unexpected token, expected one of `.`, `;`, `?`, `}` or an operator
```

**Comment by estebank** [comment]
@jonathandturner I added a [check for it](https://github.com/rust-lang/rust/pull/40811/files#diff-da9d34ca1d0f6beee2838cf02e07345cR574) that does that. [From one of the tests](https://github.com/rust-lang/rust/pull/40811/files#diff-beb01736b1c52103f2dcd2eac341b810R17):

```rust

error: expected one of `,`, `.`, `?`, or an operator, found `;`
  --> $DIR/token-error-correct-3.rs:23:35
   |
23 |             callback(path.as_ref();  //~ NOTE: unclosed delimiter
   |                                   ^ expected one of `,`, `.`, `?`, or an operator here

```

**Comment by jonathandturner** [comment]
LGTM

@bors r+

**Comment by estebank** [comment]
@jonathandturner fixed merge conflict.

@bors r=jonathandturner

**Pull request merged**
