### PR TITLE
Migrate `run-make/invalid-library` to `rmake.rs`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #121876.

r? @jieyouxu

try-job: x86_64-msvc

### CODE REVIEW

**Comment by Kobzol** [comment]
r? @Kobzol

Thanks!

@bors r+

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/126886#issuecomment-2185572232

**Comment by jieyouxu** [comment]
Oh yeah this is another case of I can't seem to figure out if/when `AR` is available on Windows platforms

**Comment by Kobzol** [comment]
Maybe a more general solution is to just use e.g. https://docs.rs/ar/latest/ar/ instead of an external binary?

**Comment by GuillaumeGomez** [comment]
Do you want it to be part of this PR (and as part of `run_make_support`) or as a follow-up?

**Comment by Kobzol** [comment]
Doesn't need to be a part of this PR, although if it does indeed work reliably (even on Windows), then maybe we might remove `needs-ar` in the future.

**Comment by GuillaumeGomez** [comment]
Doing it in this PR then.

**Comment by GuillaumeGomez** [comment]
Fixed merge conflicts.

**Pull request merged**
