### PR TITLE
Teach bootstrap install and dist commands about TargetSelection

### PR DESCRIPTION
**Pull request by shepmaster**
With this, we can now use a target JSON file to build a
cross-compiler:

```
x.py install --host ../aarch64-apple-darwin.json --target aarch64-apple-darwin
```

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like you'll need to rustfmt: https://github.com/rust-lang/rust/pull/74495/checks?check_run_id=886036950#step:22:1573

**Comment by Mark-Simulacrum** [comment]
r=me with that fixed though

**Comment by Manishearth** [comment]
@abors retry yield

**Comment by ehuss** [comment]
@bors retry
Azure error:
```
error: failed to get `cc` as a dependency of package `bootstrap v0.0.0 (D:\a\1\s\src\bootstrap)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error inflating zlib stream; class=Zlib (5)
```

**Pull request merged**
