### PR TITLE
long error explanation for E0313

### PR DESCRIPTION
**Pull request by bindsdev**
part of #61137

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Formatting looks good to me, thanks! I'll let someone else confirm the content of the explanation.

**Comment by akabinds** [comment]
> Formatting looks good to me, thanks! I'll let someone else confirm the content of the explanation.

Great, thank you!

**Comment by akabinds** [comment]
> The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3307214833/jobs/5458674990) [(plain)](https://github.com/rust-lang/rust/commit/33c01a9f5d80b94e903bdf1f60d147722d0dbb18/checks/9055050304/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)
> ```
> Testing error-index stage2
> doc tests for: /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md
> 
> 
> command did not execute successfully: "/checkout/obj/build/bootstrap/debug/rustdoc" "-Wrustdoc::invalid_codeblock_attributes" "-Dwarnings" "-Znormalize-docs" "-Z" "unstable-options" "--test" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md" "--test-args" ""
> 
> stdout ----
> 
> running 1047 tests
> ---
> ---- /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0313 (line 5591) stdout ----
> error: lifetime may not live long enough
>  --> /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md:5593:8
>   |
> 4 |     || foo(bar);
>   |     -- ^^^^^^^^ argument requires that `'1` must outlive `'static`
>   |     |
>   |     lifetime `'1` represents this closure's body
>   |
>   = note: closure implements `FnMut`, so references to captured variables can't escape the closure
> 
> error[E0597]: `bar` does not live long enough
>   |
>   |
> 4 |     || foo(bar);
>   |     -- ----^^^-
>   |     |  |   |
>   |     |  |   borrowed value does not live long enough
>   |     |  argument requires that `bar` is borrowed for `'static`
> 5 | }
> 5 | }
>   |  - `bar` dropped here while still borrowed
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0597`.
> For more information about this error, try `rustc --explain E0597`.
> Some expected error codes were not found: ["E0313"]
> ---- /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0313 (line 5622) stdout ----
> error: lifetime may not live long enough
>   |
>   |
> 4 |     move || foo(bar);
>   |     ------- ^^^^^^^^ argument requires that `'1` must outlive `'static`
>   |     |
>   |     lifetime `'1` represents this closure's body
>   |
>   = note: closure implements `FnMut`, so references to captured variables can't escape the closure
> error: aborting due to previous error
> 
> Couldn't compile the test.
> ```

@GuillaumeGomez it seems like, according to the error log, that `E0313` error code wasn't produced and `E0597` instead was produced. Does this mean `E0313` is not produced by the compiler anymore? How could I fix this or is this error out of my control with the code I write?

**Comment by GuillaumeGomez** [comment]
It's still produced by the compiler [here](https://github.com/rust-lang/rust/blob/e64f1110c062f61746f222059439529a43ccf6dc/compiler/rustc_infer/src/infer/error_reporting/note.rs#L167). The difficult part of writing error explanation is to be able to actually trigger the error. In this case, you have the full control of the erroneous code example you write. ;)

**Comment by akabinds** [comment]
> Hello, checking status. If I read it correctly this is waiting on #103742? I'll tentatively switch review status to signal this.
> 
> Feel free to request a review when it's appropriate with `@rustbot ready`, thanks!
> 
> @rustbot author

Correct. I explained my situation here to other contributors and maintainers on the Rust community Discord server and they suggested that deprecation of the error code might be the proper solution. The issue you referenced explains a bit more. If deprecation is decided upon, then this PR will no longer have significance.

**Comment by Ezrashaw** [comment]
@akabinds I believe that this can now be closed, `E0313` has been removed.

**Comment by akabinds** [comment]
> @akabinds I believe that this can now be closed, `E0313` has been removed.

Great. Thank you!

**Pull request closed without merging**
