### PR TITLE
[WIP] Allow functions to be inlined across crates without an inline attribute

### PR DESCRIPTION
**Pull request by Zoxc**
r? @ghost

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Wow those are some nice gains!

**Comment by bjorn3** [comment]
inflate-check clean:


Totals | 0.833 | 99.31%* | -15.7% (-0.155) | 48219 | 0.3% (130.000) | 0.000 | 0.0% (0.000)
-- | -- | -- | -- | -- | -- | -- | --
typeck_tables_of | 0.578 | 69.35% | -20.4% (-0.148) | 43 | 0.0% (0.000) | 0.000 | 0.0% (0.000)

Similar for other crates. Some functions called by `typeck_tables_of` could use a `#[inline]` it seems.

**Comment by nikomatsakis** [comment]
Closing this pull request as Zoxc is stepping back from compiler development; see rust-lang/team#316.

**Comment by jonas-schievink** [comment]
I might pick this one up. Having to put `#[inline]` on tiny functions is fairly unnecessary and I see that all the time.

**Comment by Zoxc** [comment]
@jonas-schievink If you pick this up, there's still some test failures if the threshold is high (related to allocators). MIR inlining is likely to have a large interaction with this, so it might be less beneficial once we get that working. Also using ThinLTO might be better for optimizing the compiler itself, but that is [blocked on LLVM 10 due to ThinLTO bugs](https://github.com/rust-lang/rust/pull/68879),

These benchmarks show that we don't do enough inlining in the compiler currently, and one way or another we should find a way to increase that.

**Pull request closed without merging**
