### PR TITLE
added optional method chain indentations for emacs major mode

### PR DESCRIPTION
**Pull request by KOMON**
I added an option to auto-indent method chains to line up along their '.' operators. Like so: 

```
let input = io::stdin().readline()
                       .ok()
                       .expect("Failed to read line");
```

The old default would indent like so:

```
let input = io::stdin().readme()
    .ok()
    .expect("Failed to read line");
```

The Rust guide explicitly condones the former, so I thought it would be nice for the emacs mode to support it. It's off by default, you have to set `rust-indent-method-chain` to `t` via your .emacs or the customize menu

### CODE REVIEW

**Comment by cmr** [comment]
The tabs should be replaced with spaces.

**Comment by nikomatsakis** [comment]
Holy macarel! I've been idly wishing someone would do this. :v:

**Comment by FlaPer87** [comment]
@KOMON thanks... a lot! :dancer:

**Comment by huonw** [comment]
r? @pnkfelix 

(I don't know of any other reviewer as experienced with emacs as you, @pnkfelix.)

**Comment by pnkfelix** [comment]
@bors: r-

@KOMON can you replace the tabs with spaces as requested by @cmr ?

**Comment by KOMON** [comment]
@pnkfelix Done

**Pull request merged**
