### PR TITLE
Ensure stability directives are checked in all cases

### PR DESCRIPTION
**Pull request by cjgillot**
Split off  #93017

Stability and deprecation were not checked in all cases, for instance if a type error happened.
This PR moves the check earlier in the pipeline to ensure the errors are emitted in all cases.

r? @lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
are these just the first 7 commits from https://github.com/rust-lang/rust/pull/93017? and if so, did you change anything meaningful about them after my first review? If not, r=me

**Comment by cjgillot** [comment]
Just in case.
@bors r-
@bors try @rust-timer queue

**Comment by Manishearth** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/94200#issuecomment-1046375988

**Comment by lcnr** [comment]
@cjgillot is there something i should look at again here?

**Comment by cjgillot** [comment]
The last commit is new, and attempts to avoid an non-deterministic use of `FxHashMap`.

**Comment by matthiaskrgr** [comment]
Looks like tests needs to be reblessed
https://github.com/rust-lang/rust/pull/94532#issuecomment-1057274643
I'm gonna rollup=never since this seems kinda fragile
@bors r- rollup=never

**Pull request merged**
