### PR TITLE
Correct the Android stat struct definitions

### PR DESCRIPTION
**Pull request by chriswailes**
See https://cs.android.com/android/platform/superproject/+/master:bionic/libc/include/sys/stat.h for reference.

Originally part of https://github.com/rust-lang/rust/pull/112858

### CODE REVIEW

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by Amanieu** [comment]
Re-running FCP with the correct team.

@rfcbot fcp cancel
@rfcbot fcp merge

**Comment by BurntSushi** [comment]
@rfcbot concern breaking-change

Is there some kind of context for why this is okay? I see that, for example, `pub type dev_t = u64;` is getting changed to `pub type dev_t = u32;`.

**Comment by Amanieu** [comment]
This was discussed in the libs-api meeting yesterday. We're OK with making a breaking change here because the previous definitions was simply incorrect, and anyways these types have been deprecated since Rust 1.8.

**Comment by BurntSushi** [comment]
Can we say a bit more? If they're deprecated and it's okay to break them because nobody is using them, then why can't we leave them as-is and add a note that they're currently wrong?

Can a crate run be done here? (Although I'm not sure if crater supports Android targets..?)

This just looks pretty suspicious to me overall and I feel like we should have a compelling reason to do this.

**Comment by dtolnay** [comment]
Our best guess was these Rust data structures were copied from a different platform, not realizing that they'd have different layout on different platforms. The fields simply do not line up with the platform's C data structures.

**Comment by thomcc** [comment]
We use them in the internal implementation of several functions inside std, so they need to be fixed for that reason as well. (Alternatively, we could also leave them as is, and carry a fixed version for internal use instead)

**Comment by BurntSushi** [comment]
Fair enough. I suppose if somebody is using the current signatures and they get "broken" by this, then whatever they were doing before is likely silently broken.

Sorry for the noise.

**Comment by BurntSushi** [comment]
@rfcbot resolve breaking-change

**Comment by thomcc** [comment]
I think this has gotten enough enough eyes on it, but it's assigned to me as a reviewer, so I've checked the actual definition matches. So once FCP is done, you can r=me.

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/pull/113505#issuecomment-1627718506

**Pull request merged**
