### PR TITLE
[beta] Remove statement that was forgotten when backporting #94596

### PR DESCRIPTION
**Pull request by compiler-errors**
This `if` statement was introduced in #94438, then removed in #94596. Both of these PRs were beta-backported in #94933, but I think there was a mistake in the order they were applied or this removal was overlooked. I think this fixes the remaining issues referenced in https://github.com/rust-lang/rust/issues/94511#issuecomment-1072851886.

Not sure this is the correct way to put something up for beta-backport, but the PR is at least open so it can be referenced and the commit can be cherry-picked. Feel free to close this PR.

r? @Mark-Simulacrum 
cc: #94511

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Thanks! It does indeed seem plausible order was wrong - I don't think I saw rebase errors around this but could just be git producing wrong results in wrong order.

It might be nice to see if we can add tests (to master).

@bors r+ rollup=never since these changes were already backport approved.

**Comment by compiler-errors** [comment]
Hmm... strange. Wtf is going on here. Will look into it.

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
  left: `LLVMing`,
 right: `Codegenning`', /checkout/compiler/rustc_codegen_ssa/src/back/write.rs:1470:21
```

**Comment by compiler-errors** [comment]
Hm, seems like a spurious failure. Can someone bors-retry?

**Pull request merged**
