### PR TITLE
Revert #49719

### LINKED ISSUE #51416: semantics of `$($x:tt)?*` were changed in Rust 2015, should revert
There has been a lot of discussion about the proper semantics of `$($x:tt)?*`. Ideally, `?` would serve as the "optional" operator there, but that is not the semantics in stable Rust, where it serves as a separator. https://github.com/rust-lang/rust/pull/49719 did a crater run which found no crates relying on the current behavior; however, that PR was merged without an official decision from the lang team on whether to change the behavior. We should revert that PR and then make an official decision (for example, one proposal implemented in https://github.com/rust-lang/rust/pull/51336 is to change the behavior in the edition, though in that case we probably want a migration lint etc).

@pietroalbini is going to prepare the revert PR and backport

( cc @mark-i-m, @sgrif, @petrochenkov @alexreg @durka )

### PR DESCRIPTION
**Pull request by emilyalbini**
This also needs to be backported into beta.

Fixes #51416.
r? @nikomatsakis

### CODE REVIEW

**Comment by pietroalbini** [comment]
Marking this as beta-accepted since the compiler team decided at the last meeting to rollback the change, which is already in beta.

**Comment by petrochenkov** [comment]
Argh, I'm late and this is merged already.
Given zero regressions we should not <sub>(in the past tense)</sub> revert https://github.com/rust-lang/rust/pull/49719, but should rather pass it through a formal FCP.

**Pull request merged**
