### PR TITLE
Moved issue tests to subdirs and normalised names

### PR DESCRIPTION
**Pull request by alexreg**
Consistency, decluttering, ease of navigation :-)

r? @Centril

### CODE REVIEW

**Comment by Centril** [comment]
The reorganization here makes sense so I'd r+ myself but I'll let someone from T-compiler OK this...

r? @varkor

**Comment by estebank** [comment]
r=me after rebasing

**Comment by petrochenkov** [comment]
The `issues` directories in `run-pass` and `ui` test suites were created to reduce number of tests in a single directory and avoid e.g. issues with GitHub displaying the file list.
So they are rather necessary evil than something that other tests suits have to be consistent with.

The end goal for the `issues` directories is to not exist at all, with individual tests moved to their language-feature-specific subdirectories.

**Comment by estebank** [comment]
The only thing I'd add to what @petrochenkov said is that having `issue-*` files should be reserved for actual bugs, be only regression tests for a specific case, while more general things/regression tests for features should have an actual name in the file that is descriptive.

**Comment by alexreg** [comment]
Sounds fair enough. Since that may not happen for a while though, and will take a fair bit of effort, I think this is a good stop-gap solution.

**Comment by petrochenkov** [comment]
A stop-gap solution shouldn't go into the opposite direction from the end goal, IMO.

**Comment by varkor** [comment]
I also don't think this is going in the right direction. There's nothing per se that relates any of the `issue-####` tests: they have similar names simply because it's a canonical naming scheme for tests without better names. I'm all for tests being given more descriptive names, but only tests that are related should be grouped by directory like this.

**Comment by Centril** [comment]
I do think this is an improvement and I do think it advances @petrochenkov's goal (which I agree with) of:
> The end goal for the issues directories is to not exist at all, with individual tests moved to their language-feature-specific subdirectories.

Specifically, what I like about this PR is not consistency but that it reduces the amount of files that are in `compile-XX`. Having fewer files there is better organization and makes it easier to navigate.

**Comment by alexreg** [comment]
@Centril Yeah, consistency was only one goal: decluttering the directories like `compile-X` and `run-Z` and `ui` is another big one. I'll update the description accordingly, since that was very much part of my motivation too. :-)

**Comment by petrochenkov** [comment]
`foo_bar.rs` -> `foo-bar.rs` is ok.

`ui/issue-N.rs` -> `ui/issues/issue-N.rs` and `run-pass/issue-N.rs` -> `run-pass/issues/issue-N.rs`, is ok since the `issues` directories already exist in `ui`/`run-pass`, but it would be much more useful to classify them into the feature directories instead.

cc @QuietMisdreavus for the `rustdoc` changes, not sure about them.

Other changes are unnecessary churn, IMO. Other test suites are already small, and tests from `compile-fail` in particular should be moved to UI (after fixing the blocking issues), rather than moved around.

**Comment by petrochenkov** [comment]
@bors r-

@alexreg, please do not abuse r+ rights

**Comment by alexreg** [comment]
Huh? I'd been giving the go ahead to r=estebank. I admittedly should have waited until CI passed, but I had to leave, and tests were passing locally, so...

**Comment by varkor** [comment]
> Huh? I'd been given the go-ahead to do r=estebank.

The point was that *since* the review approval was given, additional points of discussion have been raised and there's not a clear consensus yet and triggering bors is effectively choosing to ignore that.

**Comment by petrochenkov** [comment]
@alexreg 
LGTM now.
Could you squash the commits to avoid affecting the history?

**Comment by alexreg** [comment]
@varkor r+?

**Comment by estebank** [comment]
```
error[E0583]: file not found for module `issue_12590_b`
 --> C:\projects\rust\src/test\pretty\issue-12590-c.rs:7:5
  |
7 | mod issue_12590_b;
  |     ^^^^^^^^^^^^^
  |
  = help: name the file either issue_12590_b.rs or issue_12590_b\mod.rs inside the directory "C:\projects\rust\src/test\pretty"
error: aborting due to previous error
For more information about this error, try `rustc --explain E0583`.
```

**Comment by alexreg** [comment]
@estebank Thanks. I wonder how that got through my local tests and CI...

@bors r=varkor

**Pull request merged**
