### PR TITLE
Remove various double spaces in compiler source comments.

### PR DESCRIPTION
**Pull request by anden3**
Was asked to do it by @Nilstrieb

### CODE REVIEW

**Comment by anden3** [comment]
r? Nilstrieb

**Comment by Nilstrieb** [comment]
@bors r+ rollup
CI really shouldn't fail so I won't wait

**Comment by Nilstrieb** [comment]
r? Nilstrieb

**Comment by anden3** [comment]
I found some more, pushing another commit soon.

**Pull request merged**
