### PR TITLE
Inject the `compiler_builtins` crate whenever the `core` crate is injected

### PR DESCRIPTION
**Pull request by oli-obk**
It depends on libcore for providing all lang items that are necessary for doing anything useful, so core can't depend on it.

r? @japaric 

cc @aturon

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360229975). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613112/613112), completed with 4857 local objects.
---
[00:00:41] configure: rust.quiet-tests     := True
---
[00:18:45] make: *** [all] Error 1
[00:18:45] Makefile:28: recipe for target 'all' failed
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:3901454a:start=1522409549192346845,finish=1522409549199528480,duration=7181635
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:105d11c0
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:105d11c0:start=1522409549206175186,finish=1522409549213163157,duration=6987971
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0511bc9a
$ dmesg | grep -i kill
[   10.870252] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

If this was not helpful or you have suggestes for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360288158). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613128/613128), completed with 4853 local objects.
---
[00:00:43] configure: rust.quiet-tests     := True
---
[00:20:08] error[E0463]: can't find crate for `compiler_builtins`
[00:20:08]
[00:20:08] error: aborting due to previous error
[00:20:08]
[00:20:08] For more information about this error, try `rustc --explain E0463`.
[00:20:08] error: Could not compile `panic_abort`.
[00:20:08]
[00:20:08] Caused by:
[00:20:08]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name panic_abort libpanic_abort/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=14193139c52711af -C extra-filename=-14193139c52711af --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/release/deps --extern libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/liblibc-4b35f2d05e20a0a4.rlib --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/libcore-a8294e31ba20c477.rlib -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-3fdfe34106cc8b15/out` (exit code: 101)
[00:20:08] warning: build failed, waiting for other jobs to finish...
[00:20:09] error: build failed
[00:20:09] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:20:09] expected success, got: exit code: 101
[00:20:09] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1064:9
[00:20:09] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:20:09] travis_fold:end:stage1-std
[00:20:09] travis_time:end:stage1-std:start=1522420949020891945,finish=1522421002426650809,duration=53405758864
[00:20:09] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:20:09] Build completed unsuccessfully in 0:15:04
[00:20:09] Makefile:28: recipe for target 'all' failed
[00:20:09] make: *** [all] Error 1
---
$ cat obj/tmp/sccache.log
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:048fa278:start=1522421003045336271,finish=1522421003052734791,duration=7398520
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:148da1bc
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:148da1bc:start=1522421003058907052,finish=1522421003065611621,duration=6704569
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0052db94
$ dmesg | grep -i kill
[   10.710744] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360287629). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613124/613124), completed with 4853 local objects.
---
[00:00:45] configure: rust.quiet-tests     := True
---
[00:23:53] error[E0463]: can't find crate for `compiler_builtins`
[00:23:53]
[00:23:53] error: aborting due to previous error
[00:23:53]
[00:23:53] For more information about this error, try `rustc --explain E0463`.
[00:23:53] error: Could not compile `unwind`.
[00:23:53]
[00:23:53] Caused by:
[00:23:53]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name unwind libunwind/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=09bb8c86b54eb662 -C extra-filename=-09bb8c86b54eb662 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/release/deps --extern libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/liblibc-4b35f2d05e20a0a4.rlib --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/libcore-a8294e31ba20c477.rlib -l gcc_s -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-3fdfe34106cc8b15/out` (exit code: 101)
[00:23"always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:23:54] expected success, got: exit code: 101
[00:23:54] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1064:9
[00:23:54] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:23:54] travis_fold:end:stage1-std
[00:23:54] travis_time:end:stage1-std:start=1522421066798884900,finish=1522421136842379243,duration=70043494343
[00:23:54] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:23:54] Build completed unsuccessfully in 0:18:40
[00:23:54] Makefile:28: recipe for target 'all' failed
[00:23:54] make: *** [all] Error 1
---
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:17bed2ce:start=1522421137766754712,finish=1522421137778643452,duration=11888740
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0da2802c
$ dmesg | grep -i kill
[   11.516288] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by japaric** [comment]
I want to point out that this PR will break *some* nightly users of Xargo. If they were developing a no-std *library* and didn't have a Xargo.toml that specified the compiler-builtins crate as part of the sysroot that Xargo will build then `xargo build` will break for them. The fix is to add or edit a Xargo.toml to look like this:

``` toml
[dependencies.core] # add this section if you didn't have it already
stage = 0

[dependencies.compiler_builtins] # add this section
features = ["mem"] # not really required
stage = 1
```

@alexcrichton how do you feel about this nightly-only breaking change and the Cargo.toml modifications in the diff?

This PR looks good to me but I'll leave @alexcrichton do the sign off. 

r? @alexcrichton

**Comment by oli-obk** [comment]
@TimNN I love the bot. The only slightly confusing situation is that it will post even after a commit that fails has been force pushed over with a commit that succeeds

**Comment by alexcrichton** [comment]
r=me on the rustc changes!

**Comment by oli-obk** [comment]
rebased

@bors r=alexcrichton

**Comment by kennytm** [comment]
@bors r-

Cannot build `profiler_builtins` at stage1-std on `dist-x86_64-linux`. Log: https://travis-ci.org/rust-lang/rust/jobs/362546762

```
[00:26:50] error[E0463]: can't find crate for `compiler_builtins`
[00:26:50] 
[00:26:50] error: aborting due to previous error
[00:26:50] 
[00:26:50] For more information about this error, try `rustc --explain E0463`.
```

**Comment by japaric** [comment]
Fixed the merge conflict and two more Cargo.tomls; still testing locally. The Cargo.lock will need to be updated as well but that's hard to do from GH :-).

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363183149). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (611672/611672), completed with 4861 local objects.
---
[00:00:46] configure: rust.quiet-tests     := True
---
[00:01:18] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:18] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:18] Build completed unsuccessfully in 0:00:31
[00:01:18] make: *** [prepare] Error 1
[00:01:18] Makefile:81: recipe for target 'prepare' failed
[00:01:18] Command failed. Attempt 2/5:
[00:01:18] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:18] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:18] Build completed unsuccessfully in 0:00:00
[00:01:18] make: *** [prepare] Error 1
[00:01:18] Makefile:81: recipe for target 'prepare' failed
[00:01:18] Command failed. Attempt 3/5:
[00:01:18] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:18] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:18] Build completed unsuccessfully in 0:00:00
[00:01:18] make: *** [prepare] Error 1
[00:01:18] Makefile:81: recipe for target 'prepare' failed
[00:01:18] Command failed. Attempt 4/5:
[00:01:18] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:18] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:18] Build completed unsuccessfully in 0:00:00
[00:01:18] make: *** [prepare] Error 1
[00:01:18] Makefile:81: recipe for target 'prepare' failed
[00:01:18] Command failed. Attempt 5/5:
[00:01:18] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:18] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:18] Build completed unsuccessfully in 0:00:00
[00:01:18] make: *** [prepare] Error 1
[00:01:18] Makefile:81: recipe for target 'prepare' failed
[00:01:18] The command has failed after 5 attempts.
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:0e9514fc:start=1523031062354581336,finish=1523031062362205548,duration=7624212
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:0866ba90
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:0866ba90:start=1523031062368936878,finish=1523031062375297956,duration=6361078
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:02177eb8
$ dmesg | grep -i kill
[   10.613799] init: failsafe main process (1094) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by japaric** [comment]
> still testing locally

I ran x.py dist for x86_64-linux and wasm32 with profilers and sanitizers enabled and it finished successfully.

@oli-obk could you update the lockfile?

**Pull request merged**
