### PR TITLE
Don't ignore errors of syscalls in std::sys::unix::fd

### PR DESCRIPTION
**Pull request by tbu-**
If any of these syscalls fail, it indicates a programmer error that
should not be silently ignored.

### CODE REVIEW

**Comment by tbu-** [comment]
These syscalls can essentially only fail if an invalid file descriptor is passed to them.

**Comment by brson** [comment]
It's not obvious to me that it's possible for these to return errors. Do you have scenarios in mind where these won't return 0?

(I'm not clear on how exposed to user code these are. Are these just internal implementation details or can people use them to call cloexec on arbitrary file descriptors?)

Even if it's not supposed to be possible for these to return errors it may be prudent to convert these to `assert!` anyway - I'd sure like to know if somebody does hit an error here, and this isn't a fast path since we've just made a syscall.

**Comment by brson** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
If we actually check for errors here then seems like we should actually punt up the error, that's what we have `Result` for. These were added in a time where we didn't support construction from arbitrary file descriptors, so it didn't make sense to even check for an error here. It's pretty rare to even find C code that checks for errors against functions like this.

**Comment by retep998** [comment]
>It's pretty rare to even find C code that checks for errors against functions like this.

I don't think we should base Rust's error handling on the dangerous footgun that is C.

There are a few cases where system function errors are being ignored on Windows too. If any way is thought up to allow `Result` to be punted up, then it should probably apply to Windows as well.

**Comment by tbu-** [comment]
Now the errors a bubbled up instead of being checked locally.

**Pull request merged**
