### PR TITLE
Accept subcomands as last element in x.py argv

### LINKED ISSUE #38373: Should accept positional arguments after flags
Consider a command line invocation like this:

```
python x.py test --stage 1 --target=x86_64-unknown-linux-gnu 
```

It has the most commonly edited arguments somewhere middle in the command line, and the least edited – on the sides. Instead I would, so editing the command would be very quick:

```
python x.py --target=x86_64-unknown-linux-gnu --stage 1 test
```

but it fails with an error:

```
unknown command: --stage
Usage: x.py --stage [options] [<args>...]
```

(unrelatedly, it seems like its usage is also kinda wrong)

### PR DESCRIPTION
**Pull request by estebank**
Fix #38373.

### CODE REVIEW

**Comment by nagisa** [comment]
I think we should still just use a proper argument parser. The thing is that while

```
python x.py --stage 1 test
```

is a valid command

```
python x.py --stage 1 test src/libstd
```

is also valid, and will not work with this patch.

**Comment by estebank** [comment]
You're right, but then there would be parsing code in two different places, in two different languages. This seemed like a quick workaround for the time being. I was already uneasy about having the list of subcommands there.

I could also look for the presence of a subcommand and move everything that comes after to the front of the argv list. This is still not ideal and could break, but seems to me like a close enough heuristic that would not be broken *now* and that would relief this annoyance in the meantime without having to duplicate argv parsing code in Python and Rust.

**Comment by nagisa** [comment]
Is it even necessary for python part to parse any arguments? Why can’t it just pass them through (and rustbuild (the rust part) properly handle everything)?

**Comment by alexcrichton** [comment]
Thanks for the PR! I think that the bug though lies not in the python script but rather [here](https://github.com/rust-lang/rust/blob/e60aa62ffe7462d48cb44ab33f2551b466745e83/src/bootstrap/flags.rs#L215) in the Rust code. Python's correctly forwarding all arguments and not interpreting them, but the problem is that we have a different set of flags for each subcommand, so we don't know how to parse the arguments until we figure out the subcommand. We can likely be more clever on that line, though!

We could perhaps use the `StopAtFirstFree` mode of getopts to use the "base" set of flags and assume that no subcommand-specific flags like `--test-args` come before the subcommand. That way we could parse the arguments, learn the subcommand, then reparse the arguments with the known set of flags afterwards.

**Comment by nagisa** [comment]
Or migrate to clap :)

**Pull request closed without merging**
