### PR TITLE
Add Atomic*::from_mut_slice

### PR DESCRIPTION
**Pull request by cuviper**
Tracking issue #76314 for `from_mut` has a question about the possibility of `from_mut_slice`, and I found a real case for it. A user in the forum had a parallelism problem that could be solved by open-indexing updates to a vector of atomics, but they didn't want to affect the other code using that vector. Using `from_mut_slice`, they could borrow that data as atomics just long enough for their parallel loop.

ref: https://users.rust-lang.org/t/sharing-vector-with-rayon-par-iter-correctly/72022

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Generally makes sense to me, though feels a bit unfortunate that we need a separate function - it seems like if you have stateless &mut T -> &mut U, you can do &mut [T] -> &mut [U], right?

Probably not worth not doing this, but it feels like maybe there's a missing abstraction of some kind here - feels similar to  https://doc.rust-lang.org/nightly/std/cell/struct.Cell.html#method.as_slice_of_cells in some ways.

r? @dtolnay for libs-api sign off

**Comment by cuviper** [comment]
> it seems like if you have stateless &mut T -> &mut U, you can do &mut [T] -> &mut [U], right?

Yes, the constraint is almost like `T: AsMut<U>`, but they have to be the same size and return the same address, no dereferencing. It's similar to coercion too. Maybe something like `unsafe trait CoerceMut<T>` with a blanket impl for slices?

**Review by dtolnay — APPROVED** [review]
Nice!

**Comment by m-ou-se** [comment]
:D Coincidentally I just got to my to do list item that says "Add atomic from_mut_slice" and noticed you just added it a few days ago. Nice!

**Comment by WaffleLapkin** [comment]
Should we also introduce the inverse operation? i.e. `&mut [Atomic*] -> &mut [*]`?

just like `Atomic*::from_mut` has an inverse `Atomic*::get_mut`.

**Comment by cuviper** [comment]
@WaffleLapkin that's a bit awkward because I don't think we can have a `&mut [self]` method. So it would either have to be a method on actual slice impls, or else an explicit associated method like `Atomic*::get_mut_slice(this: &mut [Self])`.

**Comment by WaffleLapkin** [comment]
For me an explicit associated method seems fine. Can make a PR 👀

**Pull request merged**
