### PR TITLE
run-pass/simd-intrinsic-float-minmax: Force use of qNaN on Mips

### PR DESCRIPTION
**Pull request by draganmladjenovic**
Workaround for #52746. 
r? @gnzlbg

### CODE REVIEW

**Comment by gnzlbg** [comment]
LGTM. I've opened https://github.com/rust-lang/rust/issues/52897 to track one of the issues raised in https://github.com/rust-lang/rust/issues/52746 .

**Comment by draganmladjenovic** [comment]
r? @gnzlbg 
Sorry my first assignment change didn't get picked up.  I don't think I have sufficient rights to merge this anyway, so assigning this to you.

**Comment by gnzlbg** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
@bors: r+

This is fine for now yeah, but definitely seems like something to sort before stabilization!

**Pull request merged**
