### PR TITLE
rustdoc: Handle concurrent mkdir requests

### PR DESCRIPTION
**Pull request by alexcrichton**
It's likely that `rustdoc` as a tool is run concurrently in the same output
(e.g. documenting multiple crates as Cargo does), in which case it needs to
handle concurrent calls to `fs::create_dir`.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

r=me @steveklabnik

**Comment by steveklabnik** [comment]
@bors: r-

@guillaumegomez let's talk on IRC today, I'll be around in an hour at most.

**Comment by GuillaumeGomez** [comment]
A double-check by @rust-lang/tools team is required here. :)

**Comment by steveklabnik** [comment]
@bors: r+ retry

(While I did ask @GuillaumeGomez to ping @rust-lang/tools generally on rustdoc PRs, this one is straightforward enough that I feel good about merging, and the CI failures were spurious. Re-assigning to me, though, since I was the original reviewer)

**Pull request merged**
