### PR TITLE
macros: fix regression involving identifiers in `macro_rules!` patterns.

### LINKED ISSUE #42019: macro fragment names are no longer idents
This is a stable-to-beta regression, but it's such a weird thing to do that I don't know if it counts.

Consider the following code ([playpen](https://is.gd/RmWrlU)):

```rust
macro_rules! gen {
    ($name:ident ($($dol:tt $var:ident)*) $($body:tt)*) => {
        macro_rules! $name {
            ($($dol $var:ident)*) => {
                $($body)*
            }
        }
    }
}
```

The `gen` macro parses a macro argument spec by matching a dollar sign with `$dol` and the fragment name with `$var`. Then (in this toy example) it just regurgitates that adding `:ident` as the type of each fragment.

This works in 1.17, but fails when invoked in 1.18 and nightly with the message "expected identifier, found [the ident passed in for `$var`]", pointing at `$var` on line 4. All three channels work if `$var:ident` is changed to `$var:tt` on line 2.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #42019.
r? @nrc

### CODE REVIEW

**Comment by shepmaster** [comment]
FYI: typo in the commit message: *fregression*.

**Comment by kennytm** [comment]
`i586-pc-windows-msvc` failed, `run-make\issue-26092` again, very likely the same as https://github.com/rust-lang/rust/pull/43179#issuecomment-315515838. Spurious.

**Pull request merged**
