### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #26778, #27127, #27131, #27140, #27146, #27147, #27151, #27154, #27156, #27157, #27158, #27164, #27167
- Failed merges:

### CODE REVIEW

**Comment by apasel422** [comment]
@steveklabnik Can you replace 5a2bcd3 with e6d8434?

**Comment by alexcrichton** [comment]
@bors: r-

Unfortunately I think the test failure was legitimate.

**Comment by steveklabnik** [comment]
closing, and I will fix up and make a new rollup soon

**Pull request closed without merging**
