### PR TITLE
Fix sidebar bug

### PR DESCRIPTION
**Pull request by carloslfu**
Validate if the description is available in the rawSearchIndex

### CODE REVIEW

**Comment by steveklabnik** [comment]
What specifically does this fix?

**Comment by carloslfu** [comment]
When a crate don't have items, an error stops the rendering of sidebar. I found this in the [servo generated docs][docs-servo]
[docs-servo]:http://doc.servo.org/servo/index.html

**Comment by steveklabnik** [comment]
Ahhh gotcha, thanks!

**Pull request merged**
