### PR TITLE
bootstrap: actually allow set debuginfo-level to "line-tables-only"

### PR DESCRIPTION
**Pull request by klensy**
I've tried to set in config.toml `rust.debuginfo-level = "line-tables-only"`, but ended with:
``` failed to parse TOML configuration 'config.toml': 
data did not match any variant of untagged enum StringOrInt for key `rust.debuginfo-level`
```
Also this PR allows to set `line-directives-only` for debuginfo in config.toml too.
1. Fixes this. Alternative is remove that Deserialize and use default one:
https://github.com/rust-lang/rust/blob/0e682e9875458ebf811206a48b688e07d762d9bb/src/bootstrap/src/core/config/config.rs#L725-L728

2. Should `line-directives-only` be added too?

3. I've tried to add test to rust/src/bootstrap/src/core/config/tests.rs:
```rust
#[test]
fn rust_debuginfo() {
    assert!(matches!(
        parse("rust.debuginfo-level-rustc = 1").rust_debuginfo_level_rustc,
        DebuginfoLevel::Limited
    ));
    assert!(matches!(
        parse("rust.debuginfo-level-rustc = \"line-tables-only\"").rust_debuginfo_level_rustc,
        DebuginfoLevel::LineTablesOnly
    ));
}
```

But test passes before that PR too; looks like config parse tests checks something wrong? I mean, that tests check something which isn't actual bootstrap behavior.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Can we make that the default in the compiler profile?

**Comment by klensy** [comment]
> Can we make that the default in the compiler profile?

Maybe? I didn't use profiles.
Currently it's 0 for compiler profile, so changing it will make it slower but will give more debug info, for perf tools too.

**Comment by workingjubilee** [comment]
I do not think changing it will make the actual compiler that much slower for regular execution, as generally debuginfo is not even mapped in at the same time as most code, nevermind actually contending for cache.

**Comment by workingjubilee** [comment]
I think we can figure out the default in #123337 as what the compiler contributors think would be best as default is up to them but this part of the change is a matter of the bootstrap code per se.

**Review by albertlarsan68 — CHANGES_REQUESTED** [review]
LGTM, but I think that we should support all levels that are supported by the compilers that are used

**Review by albertlarsan68 — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
