### PR TITLE
Mark hotplug_codegen_backend as ignore-stage1

### PR DESCRIPTION
**Pull request by bjorn3**
Suggested by @eddyb in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/do.20we.20really.20need.20stage2.2E.2E.3F/near/191659846.

### CODE REVIEW

**Comment by eddyb** [comment]
Have you confirmed that works, btw? I wasn't aware of `compiletest` parsing `#` comments in `Makefile`s.

**Comment by bjorn3** [comment]
I haven't, but several other `Makefile`'s have the same annotation: https://github.com/rust-lang/rust/search?q=%23+ignore-stage1&unscoped_q=%23+ignore-stage1

**Comment by jonas-schievink** [comment]
I can confirm that this works

**Comment by jonas-schievink** [comment]
Also works fine in stage2, so:

@bors r+ rollup

**Pull request merged**
