### PR TITLE
Include both benchmarks and tests in the numbers given to `TeFiltered{,Out}`

### LINKED ISSUE #103794: assertion failed: `st.current_test_count() == st.total` when running benchmarks
I tried running benchmarks with current nightly rust:

```
cargo +nightly bench bench_evaluating_debug_info_expressions
    Finished bench [optimized + debuginfo] target(s) in 0.01s
     Running benches/bench.rs (target/release/deps/bench-ca766c0cc6658384)

running 0 tests
test bench_evaluating_debug_info_expressions                   ... bench:     393,281 ns/iter (+/- 10,673)
thread 'main' panicked at 'assertion failed: st.current_test_count() == st.total', library/test/src/console.rs:296:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: bench failed, to rerun pass `--bench bench`

```

Running with the previous nightly works:
```
cargo +nightly-2022-10-30 bench bench_evaluating_debug_info_expressions
    Finished bench [optimized + debuginfo] target(s) in 0.01s
     Running benches/bench.rs (target/release/deps/bench-ca766c0cc6658384)

running 1 test
test bench_evaluating_debug_info_expressions                   ... bench:     391,268 ns/iter (+/- 6,342)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured; 22 filtered out; finished in 0.71s
```

Also, note the difference in the line `running 0 tests`.

This happens for the benchmarks in both the `gimli` and `addr2line` crates.

#103689 looks to be related (@saethlin)

### Meta

```
rustc +nightly --version --verbose
rustc 1.67.0-nightly (77e57db38 2022-10-30)
binary: rustc
commit-hash: 77e57db384aca99444c3b5f6a9c86bc58a804d89
commit-date: 2022-10-30
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/core/src/panicking.rs:115:5
   3: test::console::run_tests_console
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/test/src/console.rs:296:5
   4: test::test_main
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/test/src/lib.rs:140:15
   5: test::test_main_static
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/test/src/lib.rs:159:5
   6: call_once<fn(), ()>
             at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by thomcc**
Fixes #103794 

`#[bench]` is broken on nightly without this, sadly. It apparently has no test coverage. In addition to manually testing, I've added a run-make smokecheck for this (which would have caught the issue), but it would be nice to have a better way to test, err, libtest. For now we should get this in ASAP IMO

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Closing tree till this is merged
@bors tree-closed=1000
@bors p=1000

**Comment by thomcc** [comment]
Unsure why this failed -- seems to pass locally. Guessing this either needs to be `run-make-fulldeps` (I usually avoid the compiler tests suites)? Pushed up that change.

**Comment by thomcc** [comment]
LMK if you want me to split the test into a different PR so that you can land it without waiting for me to figure out how to where to put the test for this.

**Comment by Mark-Simulacrum** [comment]
It failed for a cross-compile case, I think if you add `# ignore-cross-compile` to the test it will work. I'm not sure fulldeps will have the same effect.

r=me with that done

**Comment by ehuss** [comment]
For the test, if you want to keep it in run-make, then it needs something like `ignore-cross-compile` so you don't have to deal with all the various targets that need extra setup, or "none" targets which can't generate executables.

**Comment by thomcc** [comment]
Oh, yeah, thanks; this tries to run the output, so indeed cross compile doesn't make sense. I had tried fulldeps since most of the other Makefiles that have `$(RUSTC) --test` were in there, and github wouldn't let me download the failure log for some reason (and I wanted to do *something* rather than block all merges into rust-lang/rust... 😅)

I've moved it back and added `# ignore-cross-compile` (I also waited for the tests to pass locally).

> r=me with that done

@bors r=Mark-Simulacrum

**Comment by thomcc** [comment]
Seems pretty likely to be noise.

**Comment by lqd** [comment]
Indeed, these 2 benchmarks are currently noisy.

@rustbot label: +perf-regression-triaged

**Pull request merged**
