### PR TITLE
Improve docs in `AllocRef`

### PR DESCRIPTION
**Pull request by TimDiekmann**
r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
LGTM but keep in mind that I have no involvement with the allocator WG and didn't know about the new API until 5h ago.
If you still want my review, r=me.

**Comment by TimDiekmann** [comment]
The changes do not affect the allocator-wg directly, only the trait. You are the expert on undefined behavior and `AllocInit::Uninitialized` is basically a noop and `Zeroed` is basically calling `ptr::write_bytes(0)`. The other changes were simply overlooked last time.

As I'm not a team member I can't r=you.

**Comment by RalfJung** [comment]
Okay. @bors r+

**Comment by TimDiekmann** [comment]
Thanks. You may want to add a rollup=always :slightly_smiling_face:

**Pull request merged**
