### PR TITLE
Use hir::Path instead of ast::Path in HIR Attribute's.

### PR DESCRIPTION
**Pull request by eddyb**
The goal here was to avoid using `ast::Path` in the HIR and having serialization logic for `ast::{Ty,Expr,...}` (inside generic arguments), despite them not existing for attribute paths.
We can't remove `Nonterminal`s "as easily", but we `bug!` for those already in some places.

This seemed a trivial change at first, but now I'm not so sure, I've had to make a lot of code work on either AST or HIR `Attribute`s, using generics (over the `Path` parameter).

Maybe we should just have `path: Vec<Ident>` in `Attribute`, instead of `{ast,hir}::Path`?
**EDIT**: opened #56492 for that variant.

r? @petrochenkov cc @nikomatsakis

### CODE REVIEW

**Comment by petrochenkov** [comment]
>We can't remove Nonterminals "as easily", but we bug! for those already in some places.

That's what I immediately thought - even if AST paths are removed, there still can be pieces of AST in tokens.

Is it possible to `bug!()` on generic arguments in AST paths as well?
I think that would be the best solution for the short term problem of unblocking https://github.com/rust-lang/rust/pull/56511.
(If some generic arguments still reach HIR as a consequences of error recovery, they can be filtered away during lowering.)

**Comment by petrochenkov** [comment]
Actually, looking at https://github.com/rust-lang/rust/pull/56511 I no longer understand why pieces of AST in HIR is an issue.
https://github.com/rust-lang/rust/pull/56511 removes encodable/decodable imple from HIR, but AST is still serializable, so what's the problem?

**Comment by petrochenkov** [comment]
Regarding attributes in HIR, I the long term goal is to have some semantic representation for attributes in HIR (`hir::Attribute`) based on name resolution results, and not just tokens.
This means no `hir::MetaItem`, `hir::MetaItemKind` etc, because no token parsing happens on HIR attributes, all the parsing and validation is done during AST -> HIR lowering.
`hir::Attributes` would probably still contain paths (`hir::Path`), but mostly for diagnostics.

In that sense this PR is closer to the long term goal than https://github.com/rust-lang/rust/pull/56492.

**Comment by Aaronepower** [comment]
Triage; @eddyb Hello, have you been able to get back to this PR?

**Comment by TimNN** [comment]
Ping from triage @eddyb: What is the status of this PR?

**Comment by Dylan-DPC** [comment]
ping from triage @eddyb Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Pull request closed without merging**
