### PR TITLE
Move ascii::escape_default to libcore

### PR DESCRIPTION
**Pull request by 1011X**
As requested in #46409, the `ascii::escape_default` method has been added to the core library. All I did was copy over the `std::ascii` module file, remove the (redundant) `AsciiExt` trait, and change some of the documentation to match. None of the tests were changed.

I wasn't sure how to handle the annotations. For `EscapeDefault` and `escape_default()`, I changed them to `#[unstable(feature = "core_ascii", issue = "46409")]`. Is that alright? Or should I leave them as they were?

### CODE REVIEW

**Comment by 1011X** [comment]
I changed the annotations to stable with the version as `1.26.0`, which is the current nightly version.

**Comment by BurntSushi** [comment]
I don't know what our decision procedure is for moving things into `core`. @alexcrichton?

**Comment by alexcrichton** [comment]
Ah I think we'd go through the normal FCP process for this as it would be an insta-stable definition in libcore. @1011X I'd sort of expect though for the original definition to be deleted from somewhere, does that still need to happen?

Also currently libcore for various technical reasons the tests go in `src/libcore/tests` unlike other libraries where it's indeed inline with the source itself.

**Comment by 1011X** [comment]
Oh right, I'll delete them from std and re-export the ones in core, and move the tests as well. My bad, I'm still figuring out how std and core are organized.

**Comment by alexcrichton** [comment]
Yeah no need to duplicate the tests as well, thanks!

**Comment by alexcrichton** [comment]
@1011X oh I think there's also a modification necessary in `src/libcore/tests/mod.rs` to actually bring the tests in as well?

Otherwise this looks good to me, thanks!

@rfcbot fcp merge

**Comment by 1011X** [comment]
@alexcrichton Got it! Thanks for the help :)

**Comment by alexcrichton** [comment]
Looks like CI may have some errors?

**Comment by 1011X** [comment]
Uh... I don't know what the error is because CI apparently can't fetch the log?

**Pull request merged**
