### PR TITLE
Only store a LocalDefId in some HIR nodes

### PR DESCRIPTION
**Pull request by cjgillot**
Some HIR nodes are guaranteed to be HIR owners: Item, TraitItem, ImplItem, ForeignItem and MacroDef.
As a consequence, we do not need to store the `HirId`'s `local_id`, and we can directly store a `LocalDefId`.

This allows to avoid a bit of the dance with `tcx.hir().local_def_id` and `tcx.hir().local_def_id_to_hir_id` mappings.

### CODE REVIEW

**Comment by bjorn3** [comment]
Many big improvements up to 9.7% and a few small regressions up to 0.6%.

**Comment by cjgillot** [comment]
Rebased with 2 extra drive-by commits.

**Comment by estebank** [comment]
Sorry I didn't get to this before it grew stale again. I'll try to be faster next time you resolve the merge conflicts.

**Comment by cjgillot** [comment]
Conflict countdown starts now :)

**Pull request merged**
