### PR TITLE
Add an option to run rustbuild on low priority on Windows

### PR DESCRIPTION
**Pull request by Zoxc**
Just so I can watch YouTube videos while compiling

### CODE REVIEW

**Comment by nagisa** [comment]
Similar effect can be achieved on unix by setting the nice level. See setrlimit(2) RLIMIT_NICE.

**Comment by alexcrichton** [comment]
I personally feel like this is slightly weird to implement in a build system, but with a relatively clear implementation path on Unix then if we are to have it at all I feel like we should put in the extra effort to implement this on Unix as well.

**Comment by carols10cents** [comment]
Hi @Zoxc! This looks awesome! 😆  Are you up for making the changes for Unix as well, or could you use some help with that?

**Comment by carols10cents** [comment]
Hi @Zoxc, since we haven't heard back from you about whether you're willing and able to make the changes requested to support Unix as well, we’re going to close this for now. When you get a chance to update this or let us know that you need help, please reopen!

**Pull request closed without merging**
