### PR TITLE
Don't spill operands onto the stack in naked functions

### LINKED ISSUE #42779: Naked functions with arguments generate a prologue
When compiling

```rust
#[naked]
pub extern fn naked_test(_fubar: u64) {
    unsafe { asm!("int3") }
}
```
(https://is.gd/Q03g7b)

The generated assembly includes a prologue with unexpected `mov`'s (as well as a trailing `ret`, already reported in https://github.com/rust-lang/rust/issues/32487)

Expected behaviour would be to have no prologue (and prevent compilation of a `#[naked]` function that is not `extern` as this would require implementing an undefined ABI, contrarily to what seems to happen https://is.gd/sQFBIy).

This is treacherous, as it dereferences some memory locations that may not be accessible, as happened to me and led to hours of debugging to finally figure out the compiled function was not the one defined.

cc https://github.com/rust-lang/rust/issues/32408

### PR DESCRIPTION
**Pull request by npmccallum**
Currently, the code spills operands onto the stack for the purpose of
debuginfo. However, naked functions can only contain an asm block. Therefore,
attempting to spill the operands on the stack is undefined behavior.
    
Fixes https://github.com/rust-lang/rust/issues/42779
cc https://github.com/rust-lang/rust/issues/32408

Note that this PR reverts https://github.com/rust-lang/rust/pull/74105 which ultimately didn't fix the problem.

cc @haraldh @Amanieu @matthewjasper

### CODE REVIEW

**Comment by Amanieu** [comment]
Actually we need something even stronger here: we must never emit an `alloca` in LLVM IR for naked functions since those are directly converted to stack allocations in debug builds. The LLVM IR must contain only a single `inlineasm` instruction followed by an `unreachable`.

**Comment by npmccallum** [comment]
> Actually we need something even stronger here: we must never emit an `alloca` in LLVM IR for naked functions since those are directly converted to stack allocations in debug builds. The LLVM IR must contain only a single `inlineasm` instruction followed by an `unreachable`.

I agree. However, that should not block this fix, which is needed either way (and currently blocks my day job).

**Pull request merged**
