### PR TITLE
Stabilize option_ref_mut_cloned

### LINKED ISSUE #43738: Tracking issue for `Option<&mut T>::cloned()`
Implemented in #43705

### PR DESCRIPTION
**Pull request by mbrubeck**
Closes #43738.

### CODE REVIEW

**Review by joshtriplett — APPROVED** [review]

**Comment by Aaron1011** [comment]
The doc comment for that function still contains the `#[feature]` attribute, under the `Examples` heading:

```
     /// #![feature(option_ref_mut_cloned)]
     /// let mut x = 12;
```

Since the feature is being stabilized, I believe that should be removed.

**Comment by mbrubeck** [comment]
> The doc comment for that function still contains the `#[feature]` attribute

Fixed, thanks.  r? @joshtriplett

**Comment by joshtriplett** [comment]
Good catch, thank you!

**Pull request merged**
