### PR TITLE
CI: rename Rust for Linux CI job

### PR DESCRIPTION
**Pull request by Kobzol**
The `rfl` name was not very [descriptive](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Testing.20Rust.20for.20Linux.20in.20our.20CI/near/447408854).

try-job: x86_64-rust-for-linux

### CODE REVIEW

**Comment by lqd** [comment]
While we're doing this, here's a random drive-by comment :3 

`x86_64-gnu-integration` is not very descriptive of `fuchsia` either.

**Comment by Kobzol** [comment]
Good point, also changed it here.

**Comment by Kobzol** [comment]
@bors try

Rebased on https://github.com/rust-lang/rust/pull/127102.

**Pull request merged**
