### PR TITLE
Sync rustfmt

### PR DESCRIPTION
**Pull request by calebcartwright**
We had a bug in the update we made ~1 week ago, so running a somewhat early sync to pull the fix in

### CODE REVIEW

**Comment by calebcartwright** [comment]
CI failure was unrelated and transient, closing and reopening to restart the initial CI checks

**Comment by calebcartwright** [comment]
@bors r+ p=1

subtree sync, and I want to make sure this gets landed before the next nightly build to minimize the number of nightlies containing this bug, as the rustfmt output is supposed to be stable on nightly too

**Comment by calebcartwright** [comment]
I find several of these comments quite confusing.

This obviously has no impact on builds/tests for miri, so unclear why the bots believe that updating the rustfmt subtree would.

I'm also unsure what the proper etiquette is relative to supposed perf regressions. Similar to the miri comment, rustfmt has absolutely nothing to do with those benchmarks and to the best of my knowledge no aspect of rustfmt is included in those runs. As such I naturally disagree with the assessment, but I'm disinclined to file an issue as that seems like obvious noise.

I believe both of these can and should be chalked up to bots running amok, but let me know if anyone feels otherwise

**Comment by RalfJung** [comment]
Miri has a spuriously failing test that happened to fail after the previous PR, and happened to work again after this one. The test is fixed in Miri proper but the Miri submodule here still needs updating to prevent such flip-floping of test results.

I don't know about the perf changes, but I would ignore them -- I have had perf change reports for Miri updates, which also clearly just demonstrate noise in the perf measurement.

**Comment by calebcartwright** [comment]
Also @Mark-Simulacrum this might need to be nominated for a backport. This needs to be included in the same release as #98040, so if #98040 is indeed slated for 1.63 as the milestone suggests then I want to nominate this for what I guess is a beta backport

**Comment by Mark-Simulacrum** [comment]
beta-accepting for 1.63 backport (mostly as coincidence that these straddled the release cut date)

**Comment by rylev** [comment]
Looks like there is some new noise in the `keccak` benchmark. Marking this as triaged. 

@rustbot label: +perf-regression-triaged

**Comment by ehuss** [comment]
Untagging, re-milestoning, this was included in https://github.com/rust-lang/rust/pull/98572.

**Pull request merged**
