### PR TITLE
Make rustc_mir::dataflow module pub (for clippy)

### PR DESCRIPTION
**Pull request by sinkuu**
I'm working on fixing false-positives of a MIR-based clippy lint (https://github.com/rust-lang/rust-clippy/pull/4509), and in need of the dataflow infrastructure.

### CODE REVIEW

**Comment by tmandry** [comment]
I think this is fine, but I'd like to double check with either @eddyb, @pnkfelix, or @matthewjasper.

What are you using to consume the results? Right now I think `DataflowResultsCursor` is the preferred way (see #62315).

**Comment by sinkuu** [comment]
I'm using `state_for_location` and `DataflowResultsCursor`. I'll try to switch to the latter.

**Comment by JohnCSimon** [comment]
Ping from triage:

@sinkuu @tmandry This PR has not been updated in a week. What is the status of the PR?

Thanks.

**Comment by sinkuu** [comment]
@JohnCSimon Waiting for an approval from

> either @eddyb, @pnkfelix, or @matthewjasper.

**Comment by tmandry** [comment]
No objections have been voiced so I'm approving this.
@bors r+

**Pull request merged**
