### PR TITLE
Port `tests/run-make/sysroot-crates-are-unstable` from Python to rmake

### PR DESCRIPTION
**Pull request by Zalathar**
EDIT: See #129071 for a much simpler migration that doesn't try to get rid of the Python script.

(I would still like to finish porting the Python script at some point, but that doesn't have to be tied to the Makefile migration.)

---

Part of the run-make Makefile purge (#121876), and also the Python purge (#110479).

This is a relatively complex script by run-make standards, and it's not a direct 1:1 port, though I did try to retain all the functionality of the old script (such as reporting all errors instead of just the first one).

It's a bit annoying that reporting all errors requires so much extra plumbing.

---

While reviewing this just before posting, I realised that I neglected to port the `set_ld_lib_path` stuff (#89033), so marking this as draft until I've had a chance to look into that.

### CODE REVIEW

**Comment by Zalathar** [comment]
Oh, it looks like `rustc()` already takes care of that automatically, so maybe this is fine.

**Comment by Zalathar** [comment]
Like a lot of run-make tests, this one is frustratingly close to just being a UI test.

The trick is that it would need to run arbitrary code ahead of time, to generate a dynamic list of revisions (based on the sysroot contents), which is probably non-trivial to support in compiletest.

Alternatively, we could hardcode the list of sysroot crates, and have some kind of separate check to ensure that the hardcoded list matches the actual sysroot.

**Comment by jieyouxu** [comment]
I'm fine with it being a run-make test tbh, run-make tests are exactly for the situation where it's impossible or otherwise very awkward to try to shoehorn into other test suites.

**Comment by Zalathar** [comment]
Closing this, partly to prevent confusion with #129071, and partly because I want to have another go at it without the complexity of trying to report all failures.

**Pull request closed without merging**
