### PR TITLE
report `const_err` on all expressions that can fail

### PR DESCRIPTION
**Pull request by oli-obk**
also a drive-by fix for reporting an "overflow in shift _left_" when shifting an `i64` _right_

This increases the warning noise for shifting by more than the bitwidth and for `-T::MIN`. I can silence the bitwidth warnings explicitly and fix the const evaluator to make sure `--$expr` is treated exactly like `$expr` (which is kinda wrong, but mathematically right).

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
Disqualifying expressions leads to ICEs like the one Travis found in `run-pass/associated-const-type-parameters.rs`.

**Comment by oli-obk** [comment]
yea... that's because associated constants aren't implemented in const eval, only in trans/consts. I decided to err on the safe side and ignored all errors due to non-const-path. This kind of distinction will become irrelevant with miri anyway. So for now we report fewer errors than we could.

**Comment by eddyb** [comment]
@oli-obk Forgot to update `Cargo.toml`?

**Comment by oli-obk** [comment]
yep. done.

**Comment by oli-obk** [comment]
> failed to decode compiler output as json: `ParseError(SyntaxError(InvalidSyntax, 1, 116))`

Huh? The error occurred on `compile-fail\dep-graph-trait-impl-two-traits.rs`

**Pull request merged**
