### PR TITLE
Remove redundant test typeid equality by subtyping

### PR DESCRIPTION
**Pull request by spastorino**
This known-bug label was a left over on #118247
 
r? @jackh726 

This doesn't address #110395, I didn't investigate about it yet.

### CODE REVIEW

**Comment by jackh726** [comment]
@bors r-

This test should just be removed - a better MCVE was added in #118247 and it serves no purpose for #110395.

**Comment by spastorino** [comment]
> @bors r-
> 
> This test should just be removed - a better MCVE was added in #118247 and it serves no purpose for #110395.

Makes sense, removed the file.

**Pull request merged**
