### PR TITLE
stabilize std::error::<dyn Error>::chain() and std::error::Chain

### PR DESCRIPTION
**Pull request by haraldh**
remove Copy from Iterator as per comment
https://github.com/rust-lang/rust/issues/58520#issuecomment-553682166

and change #[unstable] to #[stable]

Tracker: #58520

### CODE REVIEW

**Comment by withoutboats** [comment]
It seems a bit far-fetched to make a breaking change to an unstable API and then stabilize it as soon as that's merged, especially since it was merged by @sfackler on the grounds that its just a change to an unstable API.

In terms of semantics, this is the API surface I want and I think the libs team has consensus on that. But I still am not a fan of the choice of name you've given to this API, and I think the libs team as a whole needs to reach a consensus here.

I would r+ the copy change immediately, however.

**Comment by withoutboats** [comment]
The other issue I see blocking stability (aside from the name) is the `T: Error` vs `dyn Error` issue. For reasons that are beyond annoying, `Box<dyn Error>` does not implement `Error`. This makes whether methods are implemented for `dyn Error` or `T: Error` matter in really annoying ways.

Can this method be implemented on both `dyn Error` and `T: Error`? If so, is it? If it can't be, why not? Have we chosen the right choice? I had to make these choices for failure once, and I'm not sure I made them right then (not that I even remember clearly what I did without checking). I would like to see some write up explaining our policy around where we add these convenience methods to convince me we've done it in the right way and not just introduced yet another papercut to the error API.

**Comment by haraldh** [comment]
> I would r+ the copy change immediately, however.

PR #66511

**Comment by haraldh** [comment]
> The other issue I see blocking stability (aside from the name) is the `T: Error` vs `dyn Error` issue. For reasons that are beyond annoying, `Box<dyn Error>` does not implement `Error`. This makes whether methods are implemented for `dyn Error` or `T: Error` matter in really annoying ways.
> 
> Can this method be implemented on both `dyn Error` and `T: Error`? If so, is it? If it can't be, why not? Have we chosen the right choice? I had to make these choices for failure once, and I'm not sure I made them right then (not that I even remember clearly what I did without checking). I would like to see some write up explaining our policy around where we add these convenience methods to convince me we've done it in the right way and not just introduced yet another papercut to the error API.

Please add your comment to the tracker #58520 so we can discuss this

**Pull request closed without merging**
