### PR TITLE
Update Cargo

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit brings in a few Cargo updates

* Updates Cargo with experimental HTTP/2 support - a post on the forums
  will be made about testing this when available.
* Bumps Cargo's own version number
* Lots of other various fixes!

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @ehuss

**Comment by ehuss** [comment]
Does this supersede #54334?

**Comment by alexcrichton** [comment]
Ah yes it does, and we probably want to prioritize this too...

**Comment by alexcrichton** [comment]
Ok I'm gonna fold this into https://github.com/rust-lang/rust/pull/54334

**Pull request closed without merging**
