### PR TITLE
do not rerun trait solver cycles on ambiguity

### PR DESCRIPTION
**Pull request by lcnr**
See the comment in `fn reached_fixpoint`.

Fixes a minimization of the hang in fuchsia (even if it doesn't fix fuchsia itself) and may impact other hangs as well :shrug: doesn't fix the regression in diesel by itself

r? @compiler-errors

### CODE REVIEW

**Comment by lqd** [comment]
> may impact other hangs as well 🤷

As an example of other cases where this PR helps: it improves the new solver's current simili-hang on #125994 a lot.

**Comment by lcnr** [comment]
@rustbot ready

looked at https://github.com/rust-lang/chalk/pull/48/ and to my understanding their reasoning was about an implementation detail of chalk. I still don't fully get why they got hangs when rerunning goals, but it seems unrelated as we do "apply the constraints" from ambiguous results and the added test works with the new solver (after changing it to `(): Sized<ty>` to avoid the "self ty is infer" check).

**Comment by jimblandy** [comment]
@lcnr @fmease Hi! Is there anything else blocking this? We're still effectively unable to build docs for wgpu-core.

**Comment by lqd** [comment]
@jimblandy are you sure you're commenting on the correct PR? This PR is for the new solver, and shouldn't help building docs for wgpu-core.

**Comment by jimblandy** [comment]
> @jimblandy are you sure you're commenting on the correct PR? This PR is for the new solver, and shouldn't help building docs for wgpu-core.

Yes, I think I am commenting on the right issue:
- The original rustdoc issue is here: https://github.com/rust-lang/rust/issues/114891
- @fmease refers to it in the initial comment for this: https://github.com/rust-lang/rust/issues/126196.
- In this comment, @lncr says that should be fixed by this issue: https://github.com/rust-lang/rust/issues/126196#issuecomment-2160175950

**Comment by fmease** [comment]
To clear things up, #114891 is due to something going wrong in the old solver (it can't be the next solver because it's not enabled by default yet). I was then able to slightly minimize the issue here: https://github.com/rust-lang/rust/issues/114891#issuecomment-2132072219. However, I'm not particularly well-versed in either trait solver much less in the gnarly details around cycles & caching which seems to be the root cause.

So instead I decided to experimentally migrate the problematic rustdoc 'routine' (blanket impl synthesis) from the old to the next solver in #126196 and check if that might solve the problem.
However, it turned out that the "rustc equivalent" of #114891 currently ~hangs in the next solver, too: #126196. Finally, this brings us to this PR.

Getting slightly off-topic but unfortunately I don't know when and why #114891 regressed (since it's hard to bisect a compiletime or hang issue).

**Comment by lcnr** [comment]
merged as part of #128828

**Pull request closed without merging**
