### PR TITLE
rustc: rename ty::maps to ty::query.

### PR DESCRIPTION
**Pull request by eddyb**
Should've never been `maps` but "query system/engine" didn't fully settle from the start.

r? @michaelwoerister or @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
We should update rustc-guide:

https://rust-lang-nursery.github.io/rustc-guide/query.html

**Comment by Zoxc** [comment]
If we are changing this, why not put it in `rustc::queries`? I don't see why it should be in the `ty` module.

**Comment by eddyb** [comment]
@Zoxc I plan to, but I'd rather shift around the contexts a bit first. Currently it's all internal to the tcx, and that needs to change, making the typesystem secondary to queries.

**Comment by eddyb** [comment]
What's happening here?

@bors retry

**Pull request merged**
