### PR TITLE
Center content of the generated docs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik 
cc @frewsxcv

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Screenshot is [here](https://github.com/rust-lang/rust/pull/35679#issuecomment-239800403).

**Comment by steveklabnik** [comment]
What's the motivation for this change?

**Comment by GuillaumeGomez** [comment]
Another little improvement to documentation. Too much unused spaces.

**Comment by nagisa** [comment]
> Too much unused spaces.

Amount of whitespace does not change, and with this change the mouse travel distance from sidebar/logo to the content and back increases significantly.

**Comment by GuillaumeGomez** [comment]
@nagisa: It doesn't but it's better used. Also, I don't see the problem with the mouse travel distance.

**Comment by ubsan** [comment]
I like the original better. :-1: from me

**Comment by steveklabnik** [comment]
Putting this on the meeting agenda.

**Comment by GuillaumeGomez** [comment]
Thanks @steveklabnik!

**Comment by nagisa** [comment]
> Also, I don't see the problem with the mouse travel distance.

Have you used anything other than a mouse to control the pointer? A [pointing stick](https://en.wikipedia.org/wiki/Pointing_stick) or a [trackball](https://en.wikipedia.org/wiki/Trackball)? With these (and really, with any device), the less pointer has to move, the better.

**Comment by GuillaumeGomez** [comment]
I use almost only my keyboard.

**Comment by killercup** [comment]
I like the original better as well.

If you wanted to improve readability, you could try setting `max-width: 42em` for prose text (but don't change anything else like code blocks or tables).

**Comment by peschkaj** [comment]
I prefer the original. The motivation doesn't line up with the implementation. If we're going to make a change, we should align it with a clear goal (e.g. "change markup to improve SEO" or "Add additional accessibility markup" or "Improve readability by setting width to 42em")

**Comment by steveklabnik** [comment]
Seems like most people are :-1: , so closing. Thanks anyway @GuillaumeGomez :heart:

**Pull request closed without merging**
