### PR TITLE
[stable] 1.72.1 release

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This backports:

*  Remove assert that checks type equality #115215 
*  implied bounds: do not ICE on unconstrained region vars #115559 
*  rustdoc: correctly deal with self ty params when eliding default object lifetimes #115276 
*  Stop emitting non-power-of-two vectors in (non-portable-SIMD) codegen #115236 
*  Normalize before checking if local is freeze in deduced_param_attrs #114948 

Some cherry-picks required merge conflict resolution, we'll see if I got it right based on CI (rustdoc fix and LLVM codegen test).

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=50

Bumped the arm-android builder to use Ubuntu 23.04 instead of 22.10, which went out of support in July (per https://en.wikipedia.org/wiki/Ubuntu_version_history). Not sure why we're rebuilding that image as part of CI here...

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=50

Added dist-android and x86_64-gnu-llvm-15 builders; these are the last two using 22.10 Ubuntu AFAICT. I'll look into whether the android bump is a problem tomorrow (@rustbot ping android -- do you know if we depend on any host toolchain/glibc/etc versions on the android builder?)

**Comment by Mark-Simulacrum** [comment]
@rustbot ping android

Do you know if we depend on any host toolchain/glibc/etc versions on the android builder?

This stable-targeted PR is looking to bump the dist-android and arm-android Docker containers from 22.10 to  23.04 Ubuntu -- my hope is that we don't care about that, but want to ping. AFAICT 22.10 isn't supported anymore and we're getting 404s from some Ubuntu repositories there.

**Comment by Mark-Simulacrum** [comment]
cc @chriswailes, @maurer, @mgeisler, @stephenhines (not sure why android ping isn't working)

Repeating my question from previous ping attempt:

> Do you know if we depend on any host toolchain/glibc/etc versions on the android builder?
>
> This stable-targeted PR is looking to bump the dist-android and arm-android Docker containers from 22.10 to 23.04 Ubuntu -- my hope is that we don't care about that, but want to ping. AFAICT 22.10 isn't supported anymore and we're getting 404s from some Ubuntu repositories there.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=50

Fixed the codegen test...

**Comment by Mark-Simulacrum** [comment]
Pinned redox install on dist-various-1 to an older tarball pulled from archive.org. @bors r+ rollup=never p=50

**Comment by cuviper** [comment]
> Retrieving 'linux-4.1.49'
> Error:     linux: download failed

We try-looped that 5 times before failing, so I'm not sure a retry will help, but maybe it will work from a different CI host?

@bors retry

**Comment by chriswailes** [comment]
There shouldn't be any dependencies on host objects.  If there are they are erroneous and we'd like to fix them.

**Pull request merged**
