### PR TITLE
Improve display of crate name when hovered

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Currently when we hover the crate name, the background is stuck to the version and to the logo (when there is one):

Screenshot from 2023-11-14 11-42-39
Screenshot from 2023-11-14 11-43-19

I find it very unpleasant so I reduced the padding size and increased the margin (left and top) to keep the same positioning but not making it stuck anymore:

Screenshot from 2024-01-29 20-40-11
Screenshot from 2024-01-29 20-48-01

[online docs](https://rustdoc.crud.net/imperio/improve-crate-name-hover/std/index.html)

r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Including the search bar:

Screenshot from 2023-11-14 14-20-34
Screenshot from 2023-11-14 14-20-45

Although I'm curious about why we want it to be aligned (should be GUI tested too ;) ).

**Comment by GuillaumeGomez** [comment]
Also if using more screen space is okay, I can simply increase `margin-top` on the version (but still keep the left padding/margin update on the crate name).

**Comment by GuillaumeGomez** [comment]
So what do you want to do here @notriddle ?

**Comment by GuillaumeGomez** [comment]
Updated screenshots, code and added link to online docs so you can test it yourself. :)

**Review by fmease — APPROVED** [review]

**Review by notriddle — APPROVED** [review]

**Comment by fmease** [comment]
CC #120471, could be addressed in this PR, too, or in a follow-up.

In the latter case, r=notriddle,fmease on this PR I suppose.

**Comment by GuillaumeGomez** [comment]
Different case. I'll take a look later on. Thank you both for the reviews!

@bors r=fmease,notriddle

**Pull request merged**
