### PR TITLE
Custom backtrace output for Fuchsia

### PR DESCRIPTION
**Pull request by cramertj**
This is... not my favorite code that I've ever written. This lovely platform-agnostic module is no longer platform-agnostic. I considered breaking it up more, but the public API for other crates has to remain roughly the same in order to fulfill their needs on other platforms, and the actual quantity of cfg'd code here is fairly small-- it seems wrong to introduce a non-sys-common `sys/fuchsia/backtrace.rs` and `sys/everything_but_fuchsia/backtrace.rs`. Let me know if you have better suggestions for organizing this.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
For some context this is coupled with https://github.com/rust-lang/backtrace-rs/pull/245 being published, and I think the last few commits I've just pushed there may help simplify the integration here (and even delete a bunch of code!)

**Comment by alexcrichton** [comment]
Ok I've merged that PR and published a new version on crates.io, @cramertj want to update the support here to use it?

**Comment by cramertj** [comment]
@alexcrichton great, thanks! will do.

**Comment by cramertj** [comment]
Closing this, as I think a fresh PR would be a better start.

**Pull request closed without merging**
