### PR TITLE
Store VariantIdx to distinguish enum variants

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This saves ~24% of the instructions on the match-stress-enum benchmark, but I'm not 100% sure that this is OK - if we ever compare two constructors across enums (e.g., a Result and an Option), then this is obviously insufficient; I can experiment with continuing to store the DefId for comparison purposes in that case.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

The only PartialEq user is here, but it's not quite clear if that compares across enums ever.

```
error[E0369]: binary operation `==` cannot be applied to type `&Constructor<'_>`
   --> compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:821:55
    |
821 |             Variant(_) => used_ctors.iter().any(|c| c == self),
    |                                                     - ^^ ---- &Constructor<'_>
    |                                                     |
    |                                                     &Constructor<'_>
    |
    = note: an implementation of `std::cmp::PartialEq` might be missing for `&Constructor<'_>`
```

**Comment by Mark-Simulacrum** [comment]
Cc @Nadrieril

**Comment by Nadrieril** [comment]
That's fine, typechecking ensures we only ever compare `Constructor`s for the same type. The rest of the code relies on this in various places already.
LGTM

**Pull request merged**
