### PR TITLE
Update to LLVM 18.1.3

### LINKED ISSUE #122805: Codegen regression in `Ipv6Addr` `[u16; 8]` to `[u8; 16]` conversion
### Code

I tried this code:

```rust
// Taken from `Ipv6Addr::new`

pub fn convert1(value: [u16; 8]) -> [u8; 16] {
    let addr16 = [
        value[0].to_be(),
        value[1].to_be(),
        value[2].to_be(),
        value[3].to_be(),
        value[4].to_be(),
        value[5].to_be(),
        value[6].to_be(),
        value[7].to_be(),
    ];
    unsafe { std::mem::transmute::<_, [u8; 16]>(addr16) }
}

pub fn convert2(value: [u16; 8]) -> [u8; 16] {
    let addr16 = value.map(|val| val.to_be());
    unsafe { std::mem::transmute::<_, [u8; 16]>(addr16) }
}
```

I expected to see this happen: *these two pieces of code produced the same assembly*

Instead, this happened: *the first version generates worse code https://rust.godbolt.org/z/qrz7Pn1a7*

### Version it worked on

It most recently worked on: 1.76

### Version with regression

`rustc --version --verbose`:
```
rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18)
binary: rustc
commit-hash: efd9d2df12b5e17fac0b4d0fb89f612ecd79f259
commit-date: 2024-03-18
host: x86_64-unknown-linux-gnu
release: 1.78.0-beta.1
LLVM version: 18.1.2
```

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #122805.

This should work on all targets: https://rust.godbolt.org/z/svW8ha31z.

r? @cuviper

### CODE REVIEW

**Comment by cuviper** [comment]
Looks good!

@bors r+ rollup=never

**Comment by cuviper** [comment]
Ah, probably should mark that test for min 18.0.3.

**Comment by DianQK** [comment]
> Ah, probably should mark that test for min 18.1.3.

Ah, Yeah. I have added.

**Comment by apiraino** [comment]
backport voting postponed to next week waiting to see how the MIPS regression evolves. Even if it's a tier 3 regression introduced _by this patchset_, we're not too eager mergin this yet

**Comment by DianQK** [comment]
Replaced by #124044.

@rustbot label -beta-nominated

**Pull request merged**
