### PR TITLE
stabilize `#[must_use]` for functions and must-use comparison operators (RFC 1940)

### PR DESCRIPTION
**Pull request by zackmdavis**
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
[Blocked on stabilization decision](https://github.com/rust-lang/rust/issues/43302#issuecomment-372364549)

**Comment by nikomatsakis** [comment]
No longer blocked. Needs rebase though, ping @zackmdavis =)

**Comment by zackmdavis** [comment]
Wednesday

**Comment by zackmdavis** [comment]
(rebased on unmerged PR #50149, which this would collide with conditional on #50149 being approved)

**Comment by zackmdavis** [comment]
(also left [a comment](https://github.com/rust-lang/rust/issues/43302#issuecomment-384516946) on the tracking issue re whether to error on incorrect attribute placement)

**Comment by estebank** [comment]
> (rebased on unmerged PR #50149, which this would collide with conditional on #50149 being approved)

Just approved that PR so soon you should be able to rebase against `master` again.

**Comment by zackmdavis** [comment]
@nikomatsakis ready

**Comment by GuillaumeGomez** [comment]
@nikomatsakis: Why not adding it in this PR directly?

**Pull request merged**
