### PR TITLE
On short error format, append primary span label to message

### PR DESCRIPTION
**Pull request by estebank**
The `error-format=short` output only displays the path, error code and main error message all in the same line. We now add the primary span label as well after the error message, to provide more context.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by compiler-errors** [comment]
I believe this failed in a rollup: https://github.com/rust-lang/rust/pull/126912#issuecomment-2187247076

@bors r- rollup=iffy

**Comment by estebank** [comment]
Blocked on https://github.com/rust-lang/cargo/pull/14135.

**Pull request merged**
