### PR TITLE
[CI] Update binutils for powerpc64 and powerpc64le

### LINKED ISSUE #1620: the pre-built cargo is broken on powerpc64le
It seems that the host building it has a faulty openssl.

here the backtrace from simply running `cargo`
``` gdb
#0  0x0000000100000004 in ?? ()
#1  0x00000001008a8e90 in rand_pool_acquire_entropy ()
#2  0x00000001008a8688 in rand_drbg_get_entropy ()
#3  0x00000001008a5e58 in RAND_DRBG_instantiate ()
#4  0x00000001008a70a8 in drbg_setup ()
#5  0x00000001008a71c8 in do_rand_drbg_init_ossl_ ()
#6  0x00007ffff7f16184 in __pthread_once_slow () from /lib64/libpthread.so.0
#7  0x00000001008cc558 in CRYPTO_THREAD_run_once ()
#8  0x00000001008a7670 in RAND_DRBG_get0_public ()
#9  0x00000001008a7758 in drbg_bytes ()
#10 0x00000001008a8a70 in RAND_bytes ()
#11 0x00000001007ef630 in SSL_CTX_new ()
#12 0x000000010070f738 in git_openssl_stream_global_init ()
#13 0x00000001006e8f44 in init_once ()
#14 0x00007ffff7f16184 in __pthread_once_slow () from /lib64/libpthread.so.0
#15 0x00000001006e90b4 in git_libgit2_init ()
#16 0x0000000100695390 in std::sync::once::Once::call_once::{{closure}} ()
#17 0x00000001009efcb4 in std::sync::once::Once::call_inner () at src/libstd/sync/once.rs:387
#18 0x0000000100695338 in libgit2_sys::init ()
#19 0x0000000100685b30 in git2::config::Config::open_default ()
#20 0x00000001003f5c60 in cargo::ops::registry::http_proxy ()
#21 0x00000001003f42dc in cargo::ops::registry::needs_custom_http_transport ()
#22 0x00000001000c86c8 in cargo::main ()
#23 0x00000001000b5864 in std::rt::lang_start::{{closure}} ()
#24 0x00000001009f1934 in std::rt::lang_start_internal::{{closure}}::{{closure}} () at src/libstd/rt.rs:49
--Type <RET> for more, q to quit, c to continue without paging--
#25 std::sys_common::backtrace::__rust_begin_short_backtrace () at src/libstd/sys_common/backtrace.rs:135
#26 0x00000001009f3f1c in std::rt::lang_start_internal::{{closure}} () at src/libstd/rt.rs:49
#27 std::panicking::try::do_call () at src/libstd/panicking.rs:297
#28 0x0000000100a02a94 in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:92
#29 0x00000001009f4da8 in std::panicking::try () at src/libstd/panicking.rs:276
#30 std::panic::catch_unwind () at src/libstd/panic.rs:388
#31 std::rt::lang_start_internal () at src/libstd/rt.rs:48
#32 0x00000001000cad58 in main ()
```
And here is a strace:
``` strace
syscall_0x1047a8e7c(0x11c576690, 0x20, 0x2f90, 0x1, 0x19, 0x190) = -1 ENOSYS (Function not implemented)
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x103f00004} ---
+++ killed by SIGILL +++
```

uname
```
Linux sol 4.18.10-gentoo #1 SMP Thu Sep 27 00:19:49 -00 2018 ppc64le POWER9, altivec supported PowerNV T2P9S01 REV 1.01 GNU/Linux
```

(copied from https://github.com/rust-lang/cargo/issues/6568)

### LINKED ISSUE #6320: cargo crashes with illegal instruction under .OPENSSL_cpuid_setup on big-endian ppc64
**Problem**

Running cargo on Linux on big-endian ppc64 does not work at all, because cargo immediately crashes with illegal instruction. The crashing stack frame does not show a readable name but the next one says `.OPENSSL_cpuid_setup ()`.

**Steps**

1. Install cargo on Linux on big-endian ppc64 (I used Fedora 25 in qemu)
2. Run e.g. `cargo --version`

**Possible Solution(s)**

Is there a way to get cargo to use rustls instead of OpenSSL?

**Notes**

Output of `cargo version`:

Can't run it, but `rustc --version` says:
rustc 1.32.0-nightly (6f93e93af 2018-11-14)

### LINKED ISSUE #57345: cargo >nightly-2018-09-30 crashes on IBM POWER9 ppc64le with Fedora 29
hello, cargo >nightly-2018-09-30 shipped through rustup crashes on startup on ppc64le.

cargo binary compiled on my machine from sources on master or branch rust-1.32.0 runs fine

crash log
```
Program received signal SIGILL, Illegal instruction.
0x0000000100000004 in ?? ()
(gdb) bt
#0  0x0000000100000004 in ?? ()
#1  0x00000001008a9650 in rand_pool_acquire_entropy ()
#2  0x00000001008a8e48 in rand_drbg_get_entropy ()
#3  0x00000001008a6618 in RAND_DRBG_instantiate ()
#4  0x00000001008a7868 in drbg_setup ()
#5  0x00000001008a7988 in do_rand_drbg_init_ossl_ ()
#6  0x00007ffff7ef4e08 in __pthread_once_slow (once_control=0x100cfa6f8 <rand_drbg_init>, init_routine=0x1008a78e0 <do_rand_drbg_init_ossl_>)
    at pthread_once.c:116
#7  0x00000001008cc2d8 in CRYPTO_THREAD_run_once ()
#8  0x00000001008a7e30 in RAND_DRBG_get0_public ()
#9  0x00000001008a7f18 in drbg_bytes ()
#10 0x00000001008a9230 in RAND_bytes ()
#11 0x00000001007f0330 in SSL_CTX_new ()
#12 0x0000000100708ec8 in git_openssl_stream_global_init ()
#13 0x00000001006bc1d4 in init_once ()
#14 0x00007ffff7ef4e08 in __pthread_once_slow (once_control=0x100cf830c <_once_init>, init_routine=0x1006bc100 <init_once>) at pthread_once.c:116
#15 0x00000001006bc344 in git_libgit2_init ()
#16 0x0000000100695fd0 in std::sync::once::Once::call_once::{{closure}} ()
#17 0x00000001009f0df4 in std::sync::once::Once::call_inner () at src/libstd/sync/once.rs:387
#18 0x0000000100695f78 in libgit2_sys::init ()
#19 0x0000000100686c90 in git2::config::Config::open_default ()
#20 0x0000000100452de0 in cargo::ops::registry::http_proxy ()
#21 0x000000010045145c in cargo::ops::registry::needs_custom_http_transport ()
#22 0x00000001000c9e78 in cargo::main ()
#23 0x00000001000bf084 in std::rt::lang_start::{{closure}} ()
#24 0x00000001009f2a34 in std::rt::lang_start_internal::{{closure}}::{{closure}} () at src/libstd/rt.rs:49
#25 std::sys_common::backtrace::__rust_begin_short_backtrace () at src/libstd/sys_common/backtrace.rs:135
#26 0x00000001009f501c in std::rt::lang_start_internal::{{closure}} () at src/libstd/rt.rs:49
#27 std::panicking::try::do_call () at src/libstd/panicking.rs:297
#28 0x0000000100a03b94 in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:92
#29 0x00000001009f5ea8 in std::panicking::try () at src/libstd/panicking.rs:276
#30 std::panic::catch_unwind () at src/libstd/panic.rs:388
#31 std::rt::lang_start_internal () at src/libstd/rt.rs:48
#32 0x00000001000cc4d8 in main ()
```
My machine is a RaptorCS Talos II, it has an IBM POWER9 processor, my system is Fedora 29 with latest updates.
I would guess this is a build environment issue on your end; please indicate how I can help, thanks a lot for your time!

### PR DESCRIPTION
**Pull request by cuviper**
Cargo powerpc64 and powerpc64le are seeing `SIGILL` crashes in openssl,
which was found to be a linking problem, fixed by newer binutils. See
<https://github.com/rust-lang/rust/issues/57345#issuecomment-462094555>

For powerpc64 we're using crosstool-ng, which doesn't offer a newer
binutils version, but we can just compile it separately. On powerpc64le
we're already building binutils. Both are now updated to binutils 2.32.

Closes rust-lang/cargo#6320
Closes rust-lang/rust#57345
Closes rust-lang/rustup.rs#1620

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Nice finds!

**Comment by cuviper** [comment]
I've nominated this for beta and stable to get the fixed builds out sooner, though I'm aware that we'll only get stable if there's a point release. cc @rust-lang/release

**Comment by cuviper** [comment]
@rust-lang/infra -- please consider this for beta.

**Comment by pietroalbini** [comment]
We discussed this at the infra meeting, and decided not to backport this.

**Comment by leo-lb** [comment]
@pietroalbini What is the cost of making a working build for ppc64le? Really don't understand the behavior here.

**Comment by pietroalbini** [comment]
Backporting CI changes is always risky for us, so we tend to reject most of the backports that are not essential for a Tier 1 platform, as it happened with this PR.

Most of our CI is built around custom Docker images which are rebuilt every time the CI configuration is changed. In a perfect world rebuilding a Docker image twice with the same Dockerfile would result in the same image being produced, but making Docker builds deterministic and reproducible is hard.

It's not rare that a change on an image breaks an unrelated platform (for example it happened a few days ago with Android and its SDK that doesn't support pinning at all), and we can't afford these kinds of breakages on beta. I hope you understand.

**Comment by leo-lb** [comment]
> Backporting CI changes is always risky for us, so we tend to reject most of the backports that are not essential for a Tier 1 platform, as it happened with this PR.
> 
> Most of our CI is built around custom Docker images which are rebuilt every time the CI configuration is changed. In a perfect world rebuilding a Docker image twice with the same Dockerfile would result in the same image being produced, but making Docker builds deterministic and reproducible is hard.
> 
> It's not rare that a change on an image breaks an unrelated platform (for example it happened a few days ago with Android and its SDK that doesn't support pinning at all), and we can't afford these kinds of breakages on beta. I hope you understand.

You don't have a way to make changes specific to each platform?

**Comment by pietroalbini** [comment]
> You don't have a way to make changes specific to each platform?

Sort of.

The main issue is we have to cache the Docker images, since we don't have the CI capacity to rebuild them every time (our time cap is 3 hours, and for example rebuilding the linux x86 ones take 2.5 hours), so we need to decide at the start of the build whether to use the cached one or rebuild the image.

In our cache the images are identified by the hash of all the related `src/ci/docker` files, but when building the hashing code we opted to include more (potentially unneeded) files in the hash rather than leaving some of them out, since a collision could make huge damages to our ability to land PRs.

Also we share lots of scripts between Docker images, so rebuilding one could trigger the rebuild of another one even if all the previous issues didn't exist.

Rest assured we don't want to ship broken lower-tier platforms, but backporting those kinds of changes is too risky, and there is a reason why we have an (informal) policy against it.

**Comment by leo-lb** [comment]
I feel like something could be done to make this situation easier, it sounds like a mess.

@madscientist159 (https://github.com/madscientist159) can and will donate ppc64 hardware from IntegriCloud, that way you can build things with more capacity.

**Comment by cuviper** [comment]
Even with native hardware (which would be nice!), we still need to take care with toolchain compatibility, so that wouldn't remove problems like this.

**Comment by pietroalbini** [comment]
> I feel like something could be done to make this situation easier, it sounds like a mess.

Yeah, as you saw our CI is quirky and messy, but it gets its job done and it has some really nice features (like the ability to run the same exact build locally with `src/ci/docker/run.sh image-name`) :)

> **`@madscientist159`** can and will donate ppc64 hardware from IntegriCloud, that way you can build things with more capacity.

We still need to figure out a way to properly make use of hardware donations, but thanks for the offer! When all the stuff on our end is sorted out we'll try to remember to ping y'all again!

To be clear though, the problem is not the lack of hardware to test things on, but the time it takes to run a full test: x86 tests at the moment take around 2 to 3 hours to execute, and the Docker image takes 2.5 hours to build. Since we test only one PR at the time (not for capacity issues, but to ensure all the commits on master are always working -- [more details if you're curious](https://github.com/rust-lang/homu#why-is-it-needed)) being able to land a PR every 4/5 hours instead of one every 2/3 hours would be *really* bad for our queue.

**Comment by leo-lb** [comment]
@pietroalbini It is lack of hardware to test things on, if the hardware is faster, then that takes less time and your problem is solved.
Or I am misunderstanding the issue?

**Comment by leo-lb** [comment]
> Even with native hardware (which would be nice!), we still need to take care with toolchain compatibility, so that wouldn't remove problems like this.

Yes, I think there should be a way to edit the build process, per platform and per release quality (stable, beta, nightly). AIUI it's not the case and they're scared to make changes because a fix for powerpc64/le can break the others.

**Comment by pietroalbini** [comment]
> It is lack of hardware to test things on, if the hardware is faster or you have more, then that takes less time and your problem is solved.
Or I am misunderstanding the issue?

Well, sort of. To be fair the main problem if we skipped caching altogether is not PowerPC but x86, and even throwing a lot of money at the problem won't help *too* much since it's not possible to distribute building the docker container.

> Yes, I think there should be a way to edit the build process, per platform and per release quality (stable, beta, nightly).

The build process is already clearly split between stable, beta and nightly. The line between the platforms' build processes is a bit fuzzy though, and I agree with you we should strive to improve that.

Kenny already improved in #59253 the cache hashing code so it's more precise, and that's included in the 1.35 CI configuration. If you have any ideas on how to improve the caching invalidation (without rebuilding the image every time) I'd love to hear them!

> it's not the case and they're scared to make changes because a fix for powerpc64/le can break the others.

By the way, we're wary of making changes to the CI only for beta and stable, we have no problems tweaking things on nightly and let the changes ride the trains as it's happening with this PR ;)

**Comment by leo-lb** [comment]
We (ppc64 users) will wait, we wish it was in our hands to have a working build through rustup and it would already have been fixed, thankfully there's workarounds available.

**Comment by madscientist159** [comment]
I second this; the fact that Rust is having issues on POWER is making it very hard to recommend Rust for secure applications.  While I understand the x86 focus, x86 is a very poor platform to be tied exclusively to for a language that is focusing on security aspects -- a safe language will not paper over the serious issues that the x86 platform presents at a firmware and hardware level.

We can get you direct dedicated access to a fairly large POWER9 box if build / test time is the main problem.  In terms of benchmarks, the POWER9 systems compete directly with expensive x86 machines for build time; it's not like you're going to be waiting for the POWER9 box to finish when the x86 machine is done. :wink:

**Pull request merged**
