### PR TITLE
RequiredConstsVisitor is not needed when error happens in mir_promoted

### PR DESCRIPTION
**Pull request by chenyukang**

### CODE REVIEW

**Comment by compiler-errors** [comment]
Although not noted in the PR, this is a different strategy to solve #104209, which is also addressed in #104233. Not sure whcih is better strategy, but regardless this PR needs a "fixes ##" note and a UI test.

**Comment by chenyukang** [comment]
> Although not noted in the PR, this is a different strategy to solve #104209, which is also addressed in #104233. Not sure which is better strategy (I don't particularly care), but regardless this PR needs a "fixes ##" note and a UI test.

Yes, I was investigating #104209, but this change can not fix that issue.
My next fix is same as you, but since you submitted a PR for that, I removed it to avoid conflict 😁

**Comment by compiler-errors** [comment]
Hm -- If this PR does not fix anything or change observable behavior, I think it should be closed then, since it's not useful on its own.

**Comment by chenyukang** [comment]
Ok, closing it.

**Pull request closed without merging**
