### PR TITLE
rustdoc-json-types: Improve ItemSummary::path docs

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Somewhat inspired by the doc changes from #103085 (cc @Urgau)

r? @GuillaumeGomez

### CODE REVIEW

**Review by Urgau — APPROVED** [review]
LGTM, maybe just add that it is currently implementation defined (so as not to give too many guarantees) ?

**Comment by GuillaumeGomez** [comment]
I agree with @Urgau's suggestion: let's not give too many guarantees so please update your comment to reflect it. But otherwise looks all good, thanks!

**Comment by aDotInTheVoid** [comment]
Good suggestion, updated

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r=Urgau,GuillaumeGomez rollup

**Pull request merged**
