### PR TITLE
Rollup of 17 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #53299 (Updated core/macros.rs to note it works in a no_std environment.)
 - #53376 (Cross reference io::copy and fs::copy in docs.)
 - #53455 (Individual docs for {from,to}_*_bytes)
 - #53550 (librustc_lint: In recursion warning, change 'recurring' to 'recursing')
 - #53860 (Migrate (some) of run-pass/ to ui)
 - #53874 (Implement Unpin for Box, Rc, and Arc)
 - #53895 (tidy: Cleanups and clippy warning fixes)
 - #53946 (Clarify `ManuallyDrop` docs)
 - #53948 (Minimized clippy test from when NLL disabled two-phase borrows)
 - #53959 (Add .git extension to submodule paths missing it)
 - #53966 (A few cleanups and minor improvements to mir/dataflow)
 - #53967 (propagate build.python into cmake)
 - #53979 (Remove `#[repr(transparent)]` from atomics)
 - #53991 (Add unchecked_shl/shr check for intrinsics to fix miri's test suit)
 - #53992 (migrate run-pass/borrowck to ui/run-pass)
 - #53994 (migrate run-pass/*/ to ui/run-pass)
 - #54023 (update clippy submodule)

### CODE REVIEW

**Comment by ljedrz** [comment]
dat diff

**Comment by kennytm** [comment]
@bors r- retry 

```
[01:16:20] failures:
[01:16:20]     [rustdoc] rustdoc/intra-link-extern-crate.rs
[01:16:20]     [rustdoc] rustdoc/intra-link-private.rs
```

**Comment by kennytm** [comment]
@bors r+

Removed #53522 (causing  the intralink error above)
Removed #53162 (already testing)
Added #53830.

**Comment by kennytm** [comment]
@bors r+

Removed #53935 (broken RLS)
Removed #53830 (already testing)
Added #54023.

**Pull request merged**
