### PR TITLE
Avoid StringReader when checking code blocks for syntax errors

### PR DESCRIPTION
**Pull request by matklad**
`parse_stream_from_source_str` is a more stable API to convert a
string into a bunch of tokens, and it also catches errors about
mismatched parenthesis.

r? @ghost

### CODE REVIEW

**Comment by matklad** [comment]
This fails the `bad-code-block.rs` test, but I am not sure what the error is. 

r? @GuillaumeGomez  (but this a WIP due to the test failure)

cc @petrochenkov

**Comment by pickfire** [comment]
@matklad Are you sure you assigned the correct reviewer? Did you mean @ghost?

**Comment by matklad** [comment]
Yes: specifying r? @username directly in the PR description leads to ping amplification (as PR description is included in the commit message generated by gost). So I write ghost and then assign the actual reviewer in the second comment.

**Comment by pickfire** [comment]
Ah, I got confused for a moment. I forgot this is rustdoc and @GuillaumeGomez is a reviewer, I thought you made a typo on the reviewer.

**Comment by matklad** [comment]
Fixed the test failure, should be ready to review now!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me. Since you ping @petrochenkov, I'll let them take a look first as well. cc @jyn514

**Review by jyn514 — APPROVED** [review]
LGTM, I don't know this part of the code very well but if @matklad says `parse_stream_from_source_str` is more stable I trust his judgement.

**Pull request merged**
