### PR TITLE
Optimize symbol interning for parallel rustc

### PR DESCRIPTION
**Pull request by bjorn3**
Avoid an exclusive lock when getting the symbol string

### CODE REVIEW

**Comment by bjorn3** [comment]
Up to 0.4% regression on non-parallel rustc. Likely due to the extra lock. Let's see if parallel rustc performance improves over not making this change.

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
If anything this seems to be a perf regression compared to the previous parallel rustc benchmark.

this bench: https://perf.rust-lang.org/compare.html?start=26366828a40403c83d6cc29bf5614a6e0388354c&end=8e819e901bee81666d28b5275ec8594bdc75619b&stat=cpu-clock
previous bench: https://perf.rust-lang.org/compare.html?start=2218520b8adf8b8e64b817537d9eb0a84840e2f1&end=7cd4a2ec5195e5df4cb2f7292aa53fa3d870cd9f&stat=cpu-clock

(see https://github.com/rust-lang/rustc-perf/issues/915 for a workaround for a bug preventing old benchmark to be shown)

**Comment by rylev** [comment]
The issue with rustc perf should be resolved

**Pull request closed without merging**
