### PR TITLE
Add a regression test for argument copies with DestinationPropagation

### PR DESCRIPTION
**Pull request by saethlin**
This example, as a codegen test: https://github.com/rust-lang/rust/pull/105813#issuecomment-1367947793

r? @tmiasko

### CODE REVIEW

**Comment by saethlin** [comment]
The alignment of u64 is 8 on 64-bit systems but 4 on 32-bit, so the codegen test failed on a 32-bit target. I switched `T` to `[u8; 256]`.

**Comment by JohnTitor** [comment]
A test file now has to be added to the `tests` dir on the root, see https://github.com/rust-lang/rust/pull/106458
@bors r-

**Pull request merged**
