### PR TITLE
Keep stdout open in limit_vector_count test

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by tmiasko** [comment]
Unintentional close of stdout caused issues on CI in #75121, #75206, #75215, and #74888, so this should be prioritized.

**Comment by ecstatic-morse** [comment]
cc @adamreichold

**Comment by adamreichold** [comment]
> cc @adamreichold #75005
> 
> Good find by the way.

I am sorry for the issues and annoyance this has caused. With hindsight, a temporary file would probably have been better choice. :-(

**Pull request merged**
