### PR TITLE
[Perf Experiment] Introduce `NeverShortCircuit` to see if it helps fold-via-try_fold

### PR DESCRIPTION
**Pull request by scottmcm**
This was removed a while ago for compilation time reasons, but the user experience would be better if implementing just `try_fold` was enough to also get optimized `fold` -- and at the LLVM level that completely works.

Since the removal we've moved to a different `Try` implementation, so this PR tries adding an as-simple-as-possible `repr(transparent)` newtype `NeverShortCircuit` in hopes that will minimize any perf regressions (as it won't need to test `From` impls and such, like it used to back in the try_trait_v1 days).

r? @ghost

### CODE REVIEW

**Comment by me22** [comment]
@rust-timer queue 6f42da510ae8aeb7f33b36463a98f35e72a14d91

**Comment by scottmcm** [comment]
@rust-timer queue 6f42da510ae8aeb7f33b36463a98f35e72a14d91

**Comment by scottmcm** [comment]
@rust-timer build 6f42da510ae8aeb7f33b36463a98f35e72a14d91

**Comment by scottmcm** [comment]
Hmm, mostly 0.1% regressions but a couple over 1%.  Promising, but not clean enough to be obviously-fine.

Seeing 1% regressions on check builds makes me think there's an opportunity to improve that, since the implementation of a function in `core` really shouldn't matter for that...

**Pull request closed without merging**
