### PR TITLE
Changed usages of `mir` in librustc::mir and librustc_mir to `body`

### PR DESCRIPTION
**Pull request by imbrem**
Work on part 2 of #60229

### CODE REVIEW

**Comment by imbrem** [comment]
r? eddyb

**Comment by eddyb** [comment]
r=me after a rebase

**Comment by imbrem** [comment]
@eddyb finished the rebase! Hope I did it right...

**Comment by imbrem** [comment]
@eddyb rebased again!

**Comment by imbrem** [comment]
@eddyb rebased yet again haha

**Comment by eddyb** [comment]
@Centril @oli-obk Sorry for not seeing this, but someone should've r=me'd the PR.
@bors r+

**Pull request merged**
