### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #73989 (adjust ub-enum test to be endianess-independent)
 - #74045 (Explain effects of debugging options from config.toml)
 - #74076 (Add `read_exact_at` and `write_all_at` to WASI's `FileExt`)
 - #74105 (Suppress debuginfo on naked function arguments)
 - #74109 (Only allow `repr(i128/u128)` on enum)
 - #74116 (Fix cross compilation of LLVM to aarch64 Windows targets)
 - #74125 (Correctly mark the ending span of a match arm)
 - #74129 (:arrow_up: rust-analyzer)
 - #74135 (Update books)
 - #74145 (Update rust-installer to latest version)
 - #74161 (Fix  disabled dockerfiles)
 - #74167 (linker: illumos ld does not support --eh-frame-hdr)
 - #74168 (Add a help to use `in_band_lifetimes` in nightly)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@pietroalbini looks like it's hanging on checking out the code at https://github.com/rust-lang-ci/rust/runs/856552047

**Comment by Manishearth** [comment]
@bors retry yield

:/

**Comment by Manishearth** [comment]
> looks like it's hanging on checking out the code at https://github.com/rust-lang-ci/rust/runs/856552047

And now  that page shows that the build was interrupted. It was definitely stuck on "checking out the source code" when I cancelled it, and the expand button on "checking out the source code" wasn't working

**Comment by Manishearth** [comment]
Actually, this might be an Actions bug:


image

The build is running, but there's still a spinny on "checkout the source code", and the expand button isn't working.

**Comment by eddyb** [comment]
Looks like this is in the same situation now: https://github.com/rust-lang-ci/rust/runs/857062392

I've tried adding this to the `<details>` for "checkout the source code":
```
data-log-url="/rust-lang-ci/rust/commit/1751bcef6a24df68772e7545aa858f0201f3c2b3/checks/857062392/logs/3"
```

Which matches the pattern on the other steps (or in other builds), but it 404s grabbing that from the server.

So I'm guessing this is a server-side bug and the UI reflects that.

**Pull request closed without merging**
