### PR TITLE
move some tests into subfolders

### PR DESCRIPTION
**Pull request by lcnr**
This reduces the size of the test folders without making the moved tests harder to find.

Is this kind of change desired/worth the effort?

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
In general, I think folders are good, but we've been a bit blocked on somebody trying to come up with a good organizational scheme. Overall, I think that we probably need some good way to index tests in more than one way -- e.g., sometimes it's useful to view them by rfc, other times by the area of the code. I had imagined picking one method as the *primary* way, and then using tags (e.g., `// tag #foo`) for other schemes.

**Comment by nikomatsakis** [comment]
I'll r+ this as a one-off though

**Comment by Centril** [comment]
> I'll r+ this as a one-off though

@nikomatsakis I hope this is not a one-off; I think this PR moves us in the direction we want (tagging, good by-area/feature organization), and as long as PRs do that, let's keep r+ing them. :)

**Pull request merged**
