### PR TITLE
Added test for inclusive_range_syntax in compile-fail test suite

### LINKED ISSUE #39059: Removal of the lang feature gate tests whitelist
PR #38914 has added a tidy check for gate tests in compile-fail for all unstable lang features, helping ensure that they are actually unstable. See also issue #22820.

To be recognized as gate test for a specific feature, tests either need to follow a naming scheme `feature-gate-NAME-OF-THE-FEAT.rs` or include a `// gate-test-NAME-OF-THE-FEAT` comment. For most of the currently present features, I could easily find matching tests in the test suite. Sadly, [there is still a whitelist](https://github.com/rust-lang/rust/blob/6fe23719feb20c25a8b2693d1f196e72d8da9af5/src/tools/tidy/src/features.rs#L168-L175) of currently 20 features for which it tolerates that it can't detect any gate tests.

The goal is to eliminate that whitelist, which this issue is tracking.

The features on the whitelist fall into the following categories:

**Has already tests, they just need to be marked (found this out only on a second look):**

* [x] `more_struct_aliases` → marked by PR #39243
* [x] `custom_attribute` → marked by PR #39243
* [x] `default_type_parameter_fallback` → marked by PR #39243
* [x] `use_extern_macros` → marked by PR #39243
* [x] `quote` → marked by PR #39250
* [x] `macro_reexport` → marked by PR #39250
* [x] `inclusive_range_syntax` → marked by PR #40031

**Used nowhere in the codebase. Remove?**

*got all removed by PR #39071*

* [x] `safe_suggestion`
* [x] `pushpop_unsafe`

**Needs a test (or I just haven't found a suiting test to mark, even on second look):**

* [x] `cfg_target_has_atomic` → got a test by #40150
* [x] `simd` → got a test by #40101
* [x] `abi_ptx`→ got a test by #40168
* [x] `const_indexing` → got a test by PR #39700
* [x] `stmt_expr_attributes` → got a test by PR #40252
* [ ] `unwind_attributes` → will get a test by PR #40279
* [x] `static_recursion` → got a test by PR #39834
* [ ] `cfg_target_thread_local` → will get a test by PR #40279
* [x] `unboxed_closures` → got a test by PR #40047
* [x] `staged_api` → got a test by PR #39772

**Don't know what to do with this one. Any ideas?**

* [x] `reflect` → removed by PR #39075

The "Needs a test" section is a good place for beginners to help out!

You basically need to:

0. if you haven't already, read `CONTRIBUTING.md` and `COMPILER_TESTS.md`
1. search in the `src/test/run-pass` suite for tests of that feature
2. copy one of those tests over to the compile-fail suite
3. rename it appropriately (`feature-gate-FEAT-NAME.rs`) and remove the `#![feature(...)]` line
4. remove the feature from the whitelist
5. test locally (`./x.py test src/tools/tidy` and `./x.py test src/test/compile-fail --test-args feature-gate-FEAT-NAME`)
5. submit a PR!

It would also be very good if you searched the `compile-fail` testsuite for already existing gate tests and mark those instead. A good place to look is the PR that introduced that feature, they usually also add gate tests.

You can help out in the "Has already tests" section as well. Here, contributing is even easier!

You'll need to:

0. read `CONTRIBUTING.md` and `COMPILER_TESTS.md` (second one is not strictly required, but it never harms :D)
1. add a line with `// gate-test-FEATURE_NAME` to the files that were mentioned above
2. remove the feature from the whitelist
3. test locally (`./x.py test src/tools/tidy`, since you only added comments)
4. submit a PR!

If you need help, ask in this thread. Also, its best to prevent duplicate work, so it would be nice if you could announce that you work on some of the items. Thanks in advance!

### PR DESCRIPTION
**Pull request by nikhilshagri**
Fixes #39059
r? @est31 

Forgot to leave a comment on the issue, hopefully nobody else is working on this one!

### CODE REVIEW

**Comment by durka** [comment]
This is already tested at src/test/parse-fail/range_inclusive_gate.rs.

**Comment by est31** [comment]
@durka thanks for pointing this out! Seems I've missed that test when generating the list for #39059.

@cynicaldevil you should instead of adding the test add the `// gate-test-...` comment and add the `test/parse-fail` directory to the [list of directories with feature gate tests inside](https://github.com/rust-lang/rust/blob/cf20d8e23cb590ab405476ce0ad184d9856be9cd/src/tools/tidy/src/features.rs#L118-L119) so that its recognized.

**Comment by cynicaldevil** [comment]
@est31 Updated PR.

**Review by durka — APPROVED** [review]

**Comment by est31** [comment]
Merged. Thanks!

**Pull request merged**
