### PR TITLE
Implement `?const` opt-out for trait bounds

### PR DESCRIPTION
**Pull request by ecstatic-morse**
For now, such bounds are treated exactly the same as unprefixed ones in all contexts. [RFC 2632](https://github.com/rust-lang/rfcs/pull/2632) does not specify whether such bounds are forbidden outside of `const` contexts, so they are allowed at the moment.

Prior to this PR, the constness of a trait bound/impl was stored in `TraitRef`. Now, the constness of an `impl` is stored in `ast::ItemKind::Impl` and the constness of a bound in `ast::TraitBoundModifer`. Additionally, constness of trait bounds is now stored in an additional field of `ty::Predicate::Trait`, and the combination of the constness of the item along with any `TraitBoundModifier` determines the constness of the bound in accordance with the RFC. Encoding the constness of impls at the `ty` level is left for a later PR.

After a discussion in \#wg-grammar on Discord, it was decided that the grammar should not encode the mutual exclusivity of trait bound modifiers. The grammar for trait bound modifiers remains `[?const] [?]`. To encode this, I add a dummy variant to `ast::TraitBoundModifier` that is used when the syntax `?const ?` appears. This variant causes an error in AST validation and disappears during HIR lowering.

cc #67794

r? @oli-obk

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Unfortunately, the straightforward implementation adds a field to `ty::TraitRef`, which is widely used during trait solving. This is undesirable since trait solving doesn't need to know about the constness of trait bounds.

I have a few other strategies in mind if the increase in memory usage is too large.

@bors try @rust-timer queue

**Comment by oli-obk** [comment]
We need to think about the future checks for `?const`. Those won't be implementable on the HIR datastructures since we may be calling generic functions from other crates. All the bounds will need to know about `?const` in order for a call to know whether the argument must implement a trait or not. Instead of encoding it in traitref you may be able to encode it as a predicate variant

**Comment by ecstatic-morse** [comment]
> Instead of encoding it in traitref you may be able to encode it as a predicate variant.

That's a good idea. I would need to make changes in the trait solver to ensure that `Predicate::Trait` and `Predicate::TraitConst` are treated equivalently for now, but this may the Right Way™ to do this.

**Comment by oli-obk** [comment]
Maybe it suffices to make it a field of Predicate::Trait? It could fit into the padding after the tag and before the value. Then you don't have to worry about the treating the same

**Comment by oli-obk** [comment]
Also doesn't really look like a max rss regression, but a perf regression

**Comment by ecstatic-morse** [comment]
After the most recent push, this is closer to the final version, but still not ready for review. The changes to `ItemKind::Impl` could be split into their own PR. The `ConstnessAnd` wrapper makes it easier to audit that constness of trait bounds is correctly propagated into `ty::Predicate`.

**Comment by oli-obk** [comment]
I thunk it would be best if you'd move the first two commits into their own PR as you'll be rebasing all the time otherwise.

**Comment by ecstatic-morse** [comment]
@oli-obk Okay I think this is ready for an initial review. I updated the PR description with a summary of the changes. The diff is pretty noisy, so you might be better off looking at the commits that mention `ty::Predicate` and `ToPredicate` separately.

**Review by oli-obk — APPROVED** [review]
r=me with the comment added

I added the "no ?const bounds in non-const scopes"-situation to the tracking issue

**Comment by ecstatic-morse** [comment]
Comments added.

@bors r=oli-obk

**Comment by oli-obk** [comment]
(a windows builder froze in https://dev.azure.com/rust-lang/rust/_build/results?buildId=18973&view=logs&j=9c50ef33-0f08-5524-430c-de3652601ceb&t=ebc29b8c-b8ce-5d09-e743-211cd7eea1d8&l=5627)

**Pull request merged**
