### PR TITLE
Don't expand vector if there is nothing left to write into it.

### PR DESCRIPTION
**Pull request by ghost**
A common C++ pattern is as follows:

vector v;
v.reserve(size);
// add size elements to v in some way, without v being required to expand

In Rust, users will equivalently do the following:
let mut v = Vec::with_capacity(size);
// add size elements to v in some way, without v being required to expand

The method read_to_end violates this expectation, by increasing the amount of space the vector is taking if the buffer being currently read in is exactly the right size required.

This results in a large performance drop in these cases- I attach benchmarking code and results.  This PR fixes this, so that if read_to_end is called with exactly the correct number of bytes allocated, the vector will not expand in size.

```
#![feature(test)]
extern crate test;
use std::io::Read;

#[bench]
fn read_to_end_1024(b: &mut test::Bencher) {
    let buf = [1u8; 1024];
    let mut src = &buf[..];
    let mut dst = Vec::with_capacity(1024);
    b.iter(|| {
        test::black_box(src.read_to_end(&mut dst))
    });
}

#[bench]
fn read_to_end_64k(b: &mut test::Bencher) {
    let buf = [1u8; 1024 * 64];
    let mut src = &buf[..];
    let mut dst = Vec::with_capacity(64);
    b.iter(|| {
        test::black_box(src.read_to_end(&mut dst))
    });
}

#[bench]
fn read_to_end_normal_test(b: &mut test::Bencher) {
    let buf = [1u8; 100000];
    let mut src = &buf[..];
    let mut dst = Vec::new();
    b.iter(|| {
        test::black_box(src.read_to_end(&mut dst))
    });
}

#[bench]
fn read_to_end_small_test(b: &mut test::Bencher) {
    let buf = [1u8; 1000];
    let mut src = &buf[..];
    let mut dst = Vec::new();
    b.iter(|| {
        test::black_box(src.read_to_end(&mut dst))
    });
}

#[test]
fn read_to_end_doesnt_expand_capacity_unless_necessary() {
    const BUF_SIZE: usize = 1024;
    let buf = [1u8; BUF_SIZE];
    let mut src = &buf[..];
    let mut dst = Vec::with_capacity(BUF_SIZE);
    let init_capacity = dst.capacity();
    assert_eq!(src.read_to_end(&mut dst).unwrap(), BUF_SIZE);
    assert_eq!(init_capacity, dst.capacity());
}

/*
Results on my machine:

Without Modification:

test read_to_end_1024        ... bench:      9972 ns/iter (+/- 2666)
test read_to_end_64k         ... bench:   2568395 ns/iter (+/- 793768)
test read_to_end_normal_test ... bench:   2133921 ns/iter (+/- 554167)
test read_to_end_small_test  ... bench:     10703 ns/iter (+/- 2967)


With Modification:

test read_to_end_1024            ... bench:       750 ns/iter (+/- 30)
test read_to_end_64k              ... bench:     74184 ns/iter (+/- 14296)
test read_to_end_normal_test  ... bench:   1525546 ns/iter (+/- 200031)
test read_to_end_small_test   ... bench:      5651 ns/iter (+/- 1128)
*/
```

### CODE REVIEW

**Comment by alexcrichton** [comment]
In the benchmarks the same vector is being pushed onto on each iteration of the loop, and the 64k benchmark doesn't reserve 64k of space (it just reserves 64 bytes), were these both intentional? I tried tweaking both of these and got these [before and after numbers](https://gist.github.com/alexcrichton/31122565e893d6599453).

I'm somewhat wary of optimizing for microbenchmarks like this, I feel like the implementation of these common functions should be expressible in concise terms, but this `read_to_end` function continues to become more sprawling over time. This also issues 2x more syscalls when the reader is backed by something like a `File` or `TcpStream`, which may or may not be desirable. 

So I suppose I have a few questions:

* Can you measure how this compares when backed by a syscall-oriented reader?
* Would it be possible to make this more concise? The two `match` statements are very similar and are a little unsightly to have duplicated.

Thanks for continuing to press on this function!

**Comment by bcoopers** [comment]
>In the benchmarks the same vector is being pushed onto on each iteration of the loop, and the 64k benchmark doesn't reserve 64k of space (it just reserves 64 bytes), were these both intentional?

The first of these was not intentional, the second of these was (I wanted to do one where it continued to expand, the other where it did not. The 64 reserved at the end will continue being multiplied by 2, which means it will eventually meet the 64k requirement exactly, and thus be expanded to 128k by the original but kept at 64k by the modified version.)

> I tried tweaking both of these and got these before and after numbers.

On my computer your test gives:

Before:
test read_to_end_1024        ... bench:      7812 ns/iter (+/- 1498)
test read_to_end_64k         ... bench:   2185142 ns/iter (+/- 260208)
test read_to_end_normal_test ... bench:   2180402 ns/iter (+/- 498111)
test read_to_end_small_test  ... bench:      7876 ns/iter (+/- 1808)

After:
test read_to_end_1024        ... bench:      7936 ns/iter (+/- 3158)
test read_to_end_64k         ... bench:    147839 ns/iter (+/- 95546)
test read_to_end_normal_test ... bench:   1981639 ns/iter (+/- 343215)
test read_to_end_small_test  ... bench:       802 ns/iter (+/- 342)

I ran these a few times, they seemed pretty consistent.  You can see it's considerably faster for the largest case where the old would need to reallocate, and the new would not.  It's obvious your computer is much beefier than mine- maybe running with a larger buffer on your machine would bring out the performance difference?

> I'm somewhat wary of optimizing for microbenchmarks like this, I feel like the implementation of these common functions should be expressible in concise terms, but this read_to_end function continues to become more sprawling over time.

I would generally agree, but in this case I think it's an important benchmark, since it is a fairly common use case to treat a vector as a dynamic array rather than a variable length array, assigning it a capacity exactly what you know it will reach and then never growing it past that capacity (eg, I know the file is exactly this long, let me reserve that much up front so it never has to grow).  In this function, using a vector in this way will result in using up twice as much memory as necessary, as well as reallocating the entire vector for no reason.

Right now the only way to get optimal performance in this case is to reserve exactly one more byte than you need.  It seems better to make this function more complex rather than requiring every Rust programmer to remember to reserve the extra byte when using this function.

Given that though...

> Can you measure how this compares when backed by a syscall-oriented reader?

This is a good point.  I'll look into this, and try testing on a file.  It could be that the syscall will wipe out any performance increases.

> Would it be possible to make this more concise? The two match statements are very similar and are a little unsightly to have duplicated.

Yeah this would be nice.  I'll look into this as well.

**Comment by bcoopers** [comment]
I tested it on files of different sizes, and in every case got either a large performance increase (sometimes twice as fast) or, if it was slower, was on the order of 1% or so (within the errors of the bench).  https://gist.github.com/bcoopers/c5b363a4effc4f78509b

**Comment by bcoopers** [comment]
Looking at it, I don't see a way to reduce the complexity of the code.  Though the results of the match are similar, what they are actually doing is entirely different.  You could combine them by having one match statement, with an if statement saying whether to write it to a temporary buffer or the end of the vector, and another one inside the results saying whether to copy the byte from the buffer over or not- but I think this would make the function look more cluttered, not less.

I'll keep thinking about it, but the solution isn't apparent to me right now.

**Comment by alexcrichton** [comment]
> On my computer your test gives:

Whoa, I have a feeling my box isn't 150x faster than yours! How are you compiling/running the benchmarks? I was compiling as `rustc foo.rs --test -Clto -Copt-level=3` and then running via `./foo --bench`. Did you perhaps forget to optimize?

> I would generally agree, but in this case I think it's an important benchmark ...  In this function, using a vector in this way will result in using up twice as much memory as necessary, as well as reallocating the entire vector for no reason.

Yeah I do agree with this, it does seem bad! I just want to get a handle on what sort of overhead we're talking about :)

> in every case got either a large performance increase (sometimes twice as fast)

Hm, I'm getting [quite different numbers](https://gist.github.com/7c660b0bee6dd7c82de0) myself. For me it looks like this PR is a little faster, but only slightly so. This may be related to the answer to my first question though!

**Comment by bcoopers** [comment]
You're absolutely right, I did not turn the optimizer on for my tests.  Sorry about that.

With the optimizer on, I get pretty different results from yours still... https://gist.github.com/bcoopers/cd2465904a3c7760c577

On my machine the change seems to hurt more at smaller read sizes (which makes sense, since the syscall stays the same price while the copy/reallocate gets more expensive as the vector gets larger) and results in maybe a 15% improvement for a large (10 megabyte) file.

I'll leave it up to you at this point, whether to merge or close it. It's not particularly clear whether this change is beneficial or not, as my results suggest it strongly depends on how much data is being read in.  It certainly wasn't as beneficial as I had hoped, or as my initial (mistaken) benchmark suggested.

**Comment by bcoopers** [comment]
Hmm it says I closed it, which I am pretty sure I did not... maybe I accidentally clicked something... in any case I suspect you were going to close it anyway.  Let me know if you decide differently and I can recreate the

**Comment by alexcrichton** [comment]
> You're absolutely right, I did not turn the optimizer on for my tests.

No worries! Just trying to make sense of the huge gap in numbers we were seeing :)

> With the optimizer on, I get pretty different results from yours still

Oh dear, it looks like I made an error and was reusing the same binary! [My corrected numbers](https://gist.github.com/alexcrichton/6a45f407d83cbb60de3c) align much more closely with yours.

> I'll leave it up to you at this point, whether to merge or close it.

Hm ok, so the numbers seem to yield these conclusions:

* For cases with a pre-allocated vector, this change results in a speedup across the board of ~15%
* For cases under 1MB without a pre-allocated capacity, this change results in a slowdown of almost 2x
* For cases over 1MB without a pre-allocated capacity, this change results in a speedup of ~10%

These conclusions make me think that this change may not be worth it for now. I believe that you can regain this change's performance win by preallocating one extra byte (so the final read of length 1 can hit EOF), so it's pretty easy to recover.

Does that sound ok to you?

**Comment by bcoopers** [comment]
Yes I think that's reasonable, and our results seem more or less in agreement now. You can go ahead and close this.

> I believe that you can regain this change's performance win by preallocating one extra byte

Looking at the code, you might have to actually preallocate as much as an extra 64k as written.  I might experiment with this a little further, trying with only the change:

    let remaining_capacity = buf.capacity() - buf.len();
    buf.extend(iter::repeat(0).take(cmp::min(new_write_size, remaining_capacity)));

which would allow you to preallocate only one extra byte, and also has the advantage of not reallocing in certain cases.  If this results in a reasonable performance increase (now that I know how to bench properly haha) I'll probably make a new pull request, otherwise I'll just drop it.

**Comment by alexcrichton** [comment]
>  I might experiment with this a little further, trying with only the change:

Ok cool, thanks for investigating!

**Pull request closed without merging**
