### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #109981 (Set commit information environment variables when building tools)
 - #110348 (Add list of supported disambiguators and suffixes for intra-doc links in the rustdoc book)
 - #110409 (Don't use `serde_json` to serialize a simple JSON object)
 - #110442 (Avoid including dry run steps in the build metrics)
 - #110450 (rustdoc: Fix invalid handling of nested items with `--document-private-items`)
 - #110461 (Use `Item::expect_*` and `ImplItem::expect_*` more)
 - #110465 (Assure everyone that `has_type_flags` is fast)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=109981,110348,110409,110442,110450,110461,110465)

### CODE REVIEW

**Comment by lqd** [comment]
Interesting rustdoc win! The small `wg-grammar` regression looks like inlining perturbations in the incremental cache encoder, probably fine.

**Comment by lqd** [comment]
Yup `wg-grammar` is noisy as well. 

image

**Comment by rylev** [comment]
Marking as triaged since the regression is noise

@rustbot label +perf-regression-triaged

**Pull request merged**
