### PR TITLE
Move `CrateConfig` from `Crate` to `ParseSess`

### PR DESCRIPTION
**Pull request by jseyfried**
This is a syntax-[breaking-change]. Most breakage can be fixed by removing a `CrateConfig` argument.
r? @eddyb

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @nnethercote

**Comment by arielb1** [comment]
```
failures:
    [run-pass] run-pass/ast_stmt_expr_attr.rs
    [run-pass] run-pass/compiler-calls.rs
    [run-pass] run-pass/macro-crate-does-hygiene-work.rs
    [run-pass] run-pass/macro-crate-multi-decorator-literals.rs
    [run-pass] run-pass/macro-crate-multi-decorator.rs
    [run-pass] run-pass/macro-crate.rs
    [run-pass] run-pass/plugin-lib-ok-in-plugin.rs
    [run-pass] run-pass/plugin-plus-extern-crate.rs
    [run-pass] run-pass/qquote.rs

test result: FAILED. 63 passed; 9 failed; 0 ignored; 0 measured
```

@bors r-

**Pull request merged**
