### PR TITLE
Only enable ConstProp at mir-opt-level >= 2.

### PR DESCRIPTION
**Pull request by cjgillot**
That pass is not responsible for lints any more, so we can restrict it to optimized builds.

This reduces the amount of duplicated const-eval messages.

### CODE REVIEW

**Comment by saethlin** [comment]
I'm pretty sure this won't but is supposed to break this mir-opt test: https://github.com/rust-lang/rust/blob/cf7ada217c8ac63367b184afd9fffaff30f6ed44/tests/mir-opt/div_overflow.rs#L1

I think it won't break it because the mir-opt tests all override `-Zmir-opt-level=4`, instead of basing the MIR opt level on `-Copt-level`, which is what this test is supposed to look for.

**Comment by oli-obk** [comment]
So we lose some perf for `hyper` and `keccak`, but gain some across the board. The losses are entirely due to

* more LLVM codegen, as we generate more LLVM-IR
* more metadata encoding as we encode more MIR

This makes me wonder if the const prop PR is useful at all (so also in release mode) except to provide simpler MIR for other MIR opts?

**Comment by oli-obk** [comment]
> I'm pretty sure this won't break this mir-opt test, but it should:

hmm... do you think this is an issue? I think the rest of the tests (ui tests) should suffice for testing the check/build defaults.

**Comment by saethlin** [comment]
Yes, that is an issue. That mir-opt test is supposed to check that we don't emit a specific unreachable panic branch in debug mode, and after this PR we will again emit the undesirable panic. That test never tested what it was supposed to. It should have been a codegen test.

If you are deciding in this PR to regress our codegen in debug builds, we should reopen that issue. Maybe someone can find another way to get the desired codegen.

**Comment by oli-obk** [comment]
> If you are deciding in this PR to regress our codegen in debug builds, we should reopen that issue. Maybe someone can find another way to get the desired codegen.

the relevant issue is https://github.com/rust-lang/rust/issues/72751

While this PR regresses that issue, the issue had no motivation explicitly mentioned. As long as we were able to trivially support it, that seems like a no-brainer, but I don't see a strong reason for actually avoiding emitting the panic path in debug builds. If there is such a reason, we should of course do something about it, but I found none in the PRs or issues linked to or from #72751

**Comment by cjgillot** [comment]
That failure is an existing bug in codegen which was hidden by const-prop :sob:. Filed https://github.com/rust-lang/rust/issues/110128 while I investigate a fix.

**Pull request merged**
