### PR TITLE
add tests for #26873

### LINKED ISSUE #26873: unresolved import using separate files, but not mod statements
This code compiles:

```rust
//! lib.rs

mod A {
    pub mod B {
        use super::*;
        
        pub struct S;
    }
    
    pub mod C {
        use super::*;
        use super::B::S;
    
        pub struct T;
    }
    
    pub use self::C::T;
}

use A::*;
```

```
$ rustc --crate-type lib lib.rs -Awarnings
$
````

However, splitting the code into files causes compilation to fail:

```rust
//! lib.rs

mod A;

use A::*;
```

```rust
//! A/mod.rs

pub mod B;
pub mod C;

pub use self::C::T;
```

```rust
//! A/B.rs

use super::*;
pub struct S;
```

```rust
//! A/C.rs

use super::*;

use super::B::S;

pub struct T { i: i32 }
```

```rust
$ rustc --crate-type lib lib.rs -Awarnings
lib.rs:3:5: 3:10 error: unresolved import
lib.rs:3 use A::*;
             ^~~~~
A/mod.rs:4:9: 4:26 error: unresolved import
A/mod.rs:4 pub use self::C::T;
                   ^~~~~~~~~~~~~~~~~
A/C.rs:1:5: 1:14 error: unresolved import
A/C.rs:1 use super::*;
             ^~~~~~~~~
A/B.rs:1:5: 1:14 error: unresolved import
A/B.rs:1 use super::*;
             ^~~~~~~~~
error: aborting due to 4 previous errors
$
```

I am not sure whether `use C::T` or use `self::C::T` is correct; regardless, replacing the latter with the former in `A/mod.rs` produces a similar error:

```rust
$ rustc --crate-type lib lib.rs -Awarnings
A/mod.rs:4:9: 4:10 error: unresolved import `C::T`. Maybe a missing `extern crate C`?
A/mod.rs:4 pub use C::T;
                   ^
error: aborting due to previous error
$
```

### PR DESCRIPTION
**Pull request by durka**
I think we can close #26873 with these tests.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like there are some tidy errors (license related), but other than that lgtm

**Comment by durka** [comment]
Bah, 2/2 so far on forgetting to copy the license into tests.

**Comment by durka** [comment]
Fixed, I think.

**Comment by durka** [comment]
That test failure makes no sense.

**Comment by durka** [comment]
@alexcrichton could you restart the test? I think it started in the middle of a force-push or something.

**Comment by alexcrichton** [comment]
This is [in the queue](http://buildbot.rust-lang.org/homu/queue/rust), it just hasn't hit bors yet

**Comment by durka** [comment]
Oh, got it.

**Comment by Manishearth** [comment]
http://buildbot.rust-lang.org/builders/auto-linux-musl-64-opt/builds/2590/steps/test/logs/stdio

**Comment by mitaa** [comment]
I did some printf debugging:
Rust is for some reason looking for the module in the directory `/home/mitaa/dev/rust` instead of `/home/mitaa/dev/rust/src/test/run-pass` when running the pretty test

I guess `// ignore-pretty` should be acceptable for now (like the few other tests with mod directives)

**Comment by durka** [comment]
Seems like a bug in the prettifier. Anyway, workaround added.

**Pull request merged**
