### PR TITLE
Add `const` to `Vec::len()` and `Vec::is_empty()`

### PR DESCRIPTION
**Pull request by Yaulendil**
Came across this while converting the const methods of a slice-based type into an owned version. Should be no change in behavior to any existing code, but allows vector length to be used in a const fn.

This has some amount of precedent, as `<[T]>::len()` and `<[T]>::is_empty()` are both also const; In addition, `Vec` already has a const fn in `Vec::new()`.

There are a few other `Vec` methods that look `const`able to me on the surface, but I figured it would be best to start with just these two, as they rely only on a single field.

### CODE REVIEW

**Comment by Yaulendil** [comment]
Would this be immediately stable, like a trait impl? I did not consider that it would need an attribute.

**Comment by thomcc** [comment]
r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

**Comment by cuviper** [comment]
> Would this be immediately stable, like a trait impl?

No, the process is to have `rustc_const_unstable` at first, with a tracking issue to stabilize later.
(Although these two methods are rather obvious for `Vec`, just keeping up with slices.)

**Review by dtolnay — CHANGES_REQUESTED** [review]
I don't understand the use case for this. Could you please elaborate with some realistic example code where this change is needed?

As far as I know it's not possible to obtain a nonempty const vec. (Could be wrong though.)

**Comment by cuviper** [comment]
Note that a `const fn` could also be called at runtime with an allocated `Vec`.

**Comment by Yaulendil** [comment]
> Could you please elaborate with some realistic example code where this change is needed?

I suppose I dont have an example where it is strictly ***needed***, but I have a type (which wraps a slice and makes guarantees about the elements) that I am converting to instead own its data. This is a minimal example:

```rust
pub struct ProtectedSlice<'s, T> {
    data: &'s [T], // Note that the data itself is kept private.
}

impl<'s, T> ProtectedSlice<'s, T> {
    pub const fn new(data: &'s [T]) -> Self {
        Self { data }
    }

    pub const fn len(&self) -> usize {
        self.data.len()
    }
}


pub struct ProtectedVec<T> {
    data: Vec<T>,
}

impl<T> ProtectedVec<T> {
    pub const fn new(data: Vec<T>) -> Self {
        Self { data }
    }

    pub /*const*/ fn len(&self) -> usize {
        self.data.len()
    }
}
```

It stopped compiling, but the `const`ness of `len()` was the only problem, and looking at the declaration of `Vec::len()`, it seemed like an oversight. It is not actually being called from any const fn, but wouldnt it be best to have a similar outlook to implementing `Copy` (if it can safely be const, it should)?

(Apologies if there is something I misunderstand.)

**Comment by dtolnay** [comment]
> if it can safely be const, it should

This has not been our approach so far. The standard library has an enormous API surface and it's not worthwhile to go through the whole thing adjudicating to what extent it's safe to commit to each thing being const. We focus on the changes that are motivated by a compelling use case.

To be clear, I can come up with contrived use cases that need Vec::len to be const, but since it sounds like that isn't what motivated this PR, I'll go ahead and close.

**Pull request closed without merging**
