### PR TITLE
Slice partition_dedup_by avoid inner branch

### PR DESCRIPTION
**Pull request by pickfire**
Prevent checking next_read != next_write since it will always be
true after it hits a different bucket once, inline the whole loop but
remove the branch itself. Slight increase in instruction count as
the loop is inlined.

https://godbolt.org/z/q13c6P slight increase in instruction count but I don't know if will should be less cache misses now. Not sure how to write a benchmark for this.

Maybe try running bors timer to confirm? Not sure if it will be affected since I am not sure if this code is called a lot.

Partially discussed in https://github.com/rust-lang/rust/issues/77772

CC @Plecra @the8472 @lzutao who may be interested

### CODE REVIEW

**Comment by the8472** [comment]
Any benchmarks verifying the improvement?

**Comment by Plecra** [comment]
I see! This is the same optimisation I added [here](https://github.com/Plecra/alt-dedup-rs/blob/main/src/lib.rs#L80), but applied to the `partition_dedup_by` implementation.

This is definitely worth benchmarking - I suspect branch prediction might offset the cost of these extra instructions. [I've written a set of benchmarks using a seeded `Rng` to generate the data](https://github.com/Plecra/alt-dedup-rs/blob/main/benches/vs_std.rs), and it'd probably be worth also using a more realistic dataset.

**Comment by pickfire** [comment]
@the8472 I don't quite know how to benchmark this.

@Plecra Not the same, yours is the same as the previous one in standard library. I discussed this with you but you say you are not sure about it in the issue I linked above.

**Comment by the8472** [comment]
@pickfire just some `partition_dedup_by` benchmarks with data that should benefit from this optimization and run the benchmark before and after the change.

**Comment by dtolnay** [comment]
@rustbot modify labels to +S-waiting-on-author
This is going to require a benchmark.

**Comment by pickfire** [comment]
Oh, I just realized it is not faster, probably because the assembly increased.
```
> cargo benchcmp bench.old bench.new
 name                  bench.old ns/iter  bench.new ns/iter  diff ns/iter   diff %  speedup 
 part_dedup_first_l1   382                1,634                     1,252  327.75%   x 0.23 
 part_dedup_first_l2   3,777              16,612                   12,835  339.82%   x 0.23 
 part_dedup_first_l3   521,583            1,773,709             1,252,126  240.06%   x 0.29 
 part_dedup_last_l1    759                518                        -241  -31.75%   x 1.47 
 part_dedup_last_l2    7,546              5,353                    -2,193  -29.06%   x 1.41 
 part_dedup_last_l3    500,212            1,007,431               507,219  101.40%   x 0.50 
 part_dedup_same_l1    261                258                          -3   -1.15%   x 1.01 
 part_dedup_same_l2    2,564              2,524                       -40   -1.56%   x 1.02 
 part_dedup_same_l3    564,641            467,216                 -97,425  -17.25%   x 1.21 
 part_dedup_unique_l1  382                512                         130   34.03%   x 0.75 
 part_dedup_unique_l2  3,778              5,346                     1,568   41.50%   x 0.71 
 part_dedup_unique_l3  524,809            1,002,029               477,220   90.93%   x 0.52 
```

[bench.rs](https://github.com/rust-lang/rust/files/5506217/bench.txt)

I will just close this. But I wonder if simd can help in situation like these? CC @Licenser

**Pull request closed without merging**
