### PR TITLE
Test `x.ps1` in `msvc` CI job

### PR DESCRIPTION
**Pull request by Kobzol**
Small adjustment to https://github.com/rust-lang/rust/pull/112633, to resolve [this comment](https://github.com/rust-lang/rust/pull/112633#issuecomment-1592973577).

r? @pietroalbini

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/112754#issuecomment-1595970913

**Comment by Kobzol** [comment]
Maybe `&&` doesn't work in the makefile? :thinking: Trying again with Makefile rule dependencies instead, let's see what CI says.

@rustbot author

**Comment by Kobzol** [comment]
Ok that should do it, now the tests pass.

@rustbot ready

**Pull request merged**
