### PR TITLE
perf: Buffer stderr when writing json errors/warnings

### PR DESCRIPTION
**Pull request by Marwes**
Since `stderr` is unbuffered, writing out json messages actually take up
about ~10%/0.1s of the runtime of the `inflate` benchmark as it generates a fair number of warnings.

cc #64413

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Is this ready for a perf run @Marwes?

**Comment by Marwes** [comment]
Yep

**Comment by ecstatic-morse** [comment]
Awesome! cc #69227

**Comment by Marwes** [comment]
No improvement in benchmarks, yet it was a clear when I ran `inflate` manually (`cargo check`). Maybe warnings are ignored when benchmarks are ran so nothing is emitted? Couldn't find anything about it though.

**Comment by ecstatic-morse** [comment]
@marwes. `syscall` only counts as one instruction. Have a look at the `task-clock` benchmarks.

**Comment by Marwes** [comment]
Perf looks good (looking at `task-clock`). Should be good to merge?

**Comment by ecstatic-morse** [comment]
I don't think we should merge this as-is. I believe this would decouple error messages from other output such as `RUSTC_LOG`, making debugging harder. Instead, we should wrap `io::Stderr` in a global `BufWriter` when writing to a file.

**Comment by Marwes** [comment]
Isn't it already decoupled and susceptible to races though? This change does mean that there is a race between `writeln!` and the `flush`. But since `stderr` isn't locked before passing it to `writeln!` then each segment written to `stderr` is already susceptible races with `RUSTC_LOG`.

**Comment by ecstatic-morse** [comment]
@Marwes In a single-threaded context, what happens if I `emit` then call `warn!` then call `emit` again? I want to see the following:
```
ERROR 1
warning
ERROR 2
```

Are we flushing the emitter buffer so that the relative order is preserved?

**Comment by Marwes** [comment]
The buffer is flushed immediately after each `emit`, so effectively it only buffers each warning written. Without that tests indeed showed interleaved messages like you pointed out.

**Comment by ecstatic-morse** [comment]
Ah, my bad. I withdraw my objection.

**Comment by tamird** [comment]
Doesn't it negate the effect of buffering, if you're immediately flushing after every write?

**Comment by Marwes** [comment]
Each `write!` involves multiple syscalls since writing out JSON performs no buffering (each `{`, `[` is a separate syscall).

So there is a still a good amount of benefit.

**Pull request merged**
