### PR TITLE
rustdoc: Make two small cleanups

### PR DESCRIPTION
**Pull request by camelid**

### CODE REVIEW

**Comment by jyn514** [comment]
r=me with ci passing

**Comment by camelid** [comment]
Regression is spurious.

cc @rylev
@rustbot label: -perf-regression

**Comment by rylev** [comment]
I'm going to add back the perf-regression label since this is currently the only way to track these types of spurious regressions. This one is particularly concerning since it's so large. This is only a note for the perf team to look deeper into what happened. No action needs to be taken by the author or reviewer of this PR. 

@rustbot label: +perf-regression

**Pull request merged**
