### PR TITLE
Cargo lock tidy check

### PR DESCRIPTION
**Pull request by gsquire**
A rebased PR for #32901

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ b3de04214646a33fa5a14fbb2e8ba55e7ee5a707 

Thanks!

**Comment by tamird** [comment]
as mentioned in the original PR, it may be worth printing the diff in addition to emitting an opaque failure

**Comment by petrochenkov** [comment]
This doesn't work on Windows/MSYS2 for some reason, for example in https://github.com/rust-lang/rust/pull/33794 `make tidy` run successfully locally, but reported an error on buildbots.

**Pull request merged**
