### PR TITLE
std: Stabilize feature try_reserve_2 

### LINKED ISSUE #91789: Tracking Issue for try_reserve method on more containers
This is another tracking issue for the try_reserve part of the RFC "fallible collection allocation" (rust-lang/rfcs#2116).
The feature gate for the issue is `#![feature(try_reserve_2)]`.

The feature is a follow-up to #48043. Since `try_reserve` was stabilized in 1.57.0, we may need a new feature gate for further `try_reserve` implementation on more containers.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement `try_reserve` and `try_reserve_exact` on `BinaryHeap` #91529 
- [x] Implement `try_reserve` and `try_reserve_exact` on `PathBuf` #92513
- [x] Implement `try_reserve` and `try_reserve_exact` on `OsString` #92338 
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

If any containers were missing, please comment in the issue, and I will add it to the list.

### Implementation history

#91529 
#92338 
#92513

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR intends to stabilize feature `try_reserve_2`, closes https://github.com/rust-lang/rust/issues/91789

This PR will also replace the previous PR: https://github.com/rust-lang/rust/pull/95139

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
Please do the stabilization of new APIs in a different PR than the new capacity-related guarantees. They will need two different libs-api FCP.

**Comment by Xuanwo** [comment]
> Please do the stabilization of new APIs in a different PR than the new capacity-related guarantees. They will need two different libs-api FCP.

Updated.

**Comment by dtolnay** [comment]
This is blocked on the FCP in https://github.com/rust-lang/rust/issues/91789#issuecomment-1026130086.

@rustbot label -S-waiting-on-author +S-blocked

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
