### PR TITLE
Printable book

### PR DESCRIPTION
**Pull request by vrinek**
Tested on:
- Safari on OSX
- Firefox on OSX

### CODE REVIEW

**Comment by steveklabnik** [comment]
Is there any chance you could post a version online so I could check it out on Linux?

**Comment by vrinek** [comment]
I did a `make docs` and pushed a `gh-pages` on my repo. It's viewable at http://blog.vrinek.io/rust/doc/book/index.html.

**Comment by steveklabnik** [comment]
Thank you! Looks great here too.

**Comment by thiagooak** [comment]
Adding

```
@media only print {
  #page-wrapper {
     margin-left: 30px;
  }
}
```

would fix #17426 also

not sure what would be the ideal size, 30px looks reasanable

**Pull request merged**
