### PR TITLE
Fix link in std::collections::btree_set documentation

### PR DESCRIPTION
**Pull request by pravic**
r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Thank you!

**Comment by ollie27** [comment]
This will actually break the link on the [`std::collections::BTreeSet`](https://doc.rust-lang.org/nightly/std/collections/struct.BTreeSet.html) page. See #32130.

**Comment by pravic** [comment]
Oops. So I'm getting out with this fix.

**Comment by steveklabnik** [comment]
I'm going to give this one a close, since we can't take this patch literally. Sorry about that!

**Pull request closed without merging**
