### PR TITLE
Docs for std::ptr::slice_from_raw_parts

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by mgeier** [comment]
Thanks @kornelski for this PR!

For reference, here's some discussion: https://users.rust-lang.org/t/missing-guidance-on-converting-ffi-ptr-length-to-slice/106048

Wouldn't it also be helpful to mention (or even recommend using) `.as_ref().unwrap_or(&[])`?

To me this was initially not obvious.

**Comment by kornelski** [comment]
The examples use `.as_ref().expect()`

**Comment by mgeier** [comment]
> The examples use `.as_ref().expect()` to highlight the non-null requirement.

Yes, and I think that's helpful!

But it only illustrates the problem, not the solution.

**Comment by cuviper** [comment]
> But it only illustrates the problem, not the solution.

The solution is going to be domain-specific. In general, there is a distinction between non-existence and emptiness, so treating null as an empty slice is not necessarily the right thing to do. But maybe we can suggest it with that qualification, like "If you are converting from a context where null pointers are used for emptiness, then you may want `.as_ref().unwrap_or(&[])`."

**Pull request merged**
