### PR TITLE
Update iterator.rs

### PR DESCRIPTION
**Pull request by kineticz**
seems more concise this way.

### CODE REVIEW

**Comment by apasel422** [comment]
This could use a more detailed commit message.

**Comment by brson** [comment]
r=me with more descriptive commit message per @apasel422

**Comment by rphmeier** [comment]
Are the implementations for `gt` and `ge` correct? It seems to me that the new implementations here will return true whenever the partial_cmp in `le` or `le` returns `None`, which is the opposite of previous behavior. The `ne` implementation seems correct to me.

**Comment by kindlychung** [comment]
Agree with @rphmeier . This can be closed.

**Pull request closed without merging**
