### PR TITLE
 Use a single hash map to store query state

### PR DESCRIPTION
**Pull request by Zoxc**
Is it too late to wish for better layout optimizations for Christmas?

r? @michaelwoerister

### CODE REVIEW

**Comment by killercup** [comment]
You better `fetch --all`
We gotta `bors try`
Better not wait
I'm telling you why
Santa Zoxc is opt'mizing layout

**Comment by Zoxc** [comment]
@rust-timer build b4c6ee6bc9c5960b10c8d5024aa632626af2ab37

**Pull request closed without merging**
