### PR TITLE
A few tweaks to iterations/collecting

### PR DESCRIPTION
**Pull request by ljedrz**
- simplify and speed up `dot::GraphWalk::nodes` for `cfg::CFG`
- `reserve` the capacity for `edges` in `DepGraph::query`
- collect directly to a `HirVec` in `LoweringContext::lower_attrs`
- fix overallocation in `OnDiskCache::serialize`
- preallocate the `new_partitioning` vector in `merge_codegen_units`
- simplify `impl FromHex for str`
- improve the creation of `self_arg_names` in `impl MethodDef`

### CODE REVIEW

**Comment by alexcrichton** [comment]
@rust-timer build f632eed65b97ffe2650dfcad1930f5004752fbee

**Comment by alexcrichton** [comment]
Hm the performance here seems negligible, so perhaps the ergonomic improvments could stay but the reservation/etc could be removed?

**Comment by ljedrz** [comment]
Sounds good; I only left the overallocation fix, since it corrects a mistake.

**Pull request merged**
