### PR TITLE
Add Capacity/length methods for OsString.

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/rust-lang/rust/issues/29453

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Looks pretty good to me, but it'd be good to add some tests I think (particular of `clear`, which has an obvious visible effect, but ideally you'd test the other methods too using `unsafe` code).

**Comment by alexcrichton** [comment]
Looks good to me as well! r=me with some tests like @nikomatsakis mentioned

**Comment by frewsxcv** [comment]
> but ideally you'd test the other methods too using `unsafe` code

I know what `unsafe` means in the context of Rust, but I'm not sure why testing these methods would necessitate the usage of `unsafe` code? Do you have an example to get a better understanding of what you mean?

**Comment by alexcrichton** [comment]
I believe @nikomatsakis means testing the methods which themselves internally use `unsafe` (generally a good idea)

**Comment by frewsxcv** [comment]
Let me know how those tests look

**Comment by alexcrichton** [comment]
@bors: r+ 85aaa7b6df386d26509e6d4bebe9dd3246352510

Thanks!

**Comment by frewsxcv** [comment]
Forgot to add a few intermediate methods (via `Buf`) for Windows. Just forced pushed the changes.

**Comment by frewsxcv** [comment]
Test fail looks unrelated

**Comment by frewsxcv** [comment]
Forgot to implement `Buf::into_inner` on the windows side. Latest force push fixes that.

**Comment by frewsxcv** [comment]
Forgot the import. Added it in.

**Pull request merged**
