### PR TITLE
coverage: Include the highest counter ID seen in `.cov-map` dumps

### PR DESCRIPTION
**Pull request by Zalathar**
When making changes that have a large impact on coverage counter creation, this makes it easier to see whether the number of physical counters has changed.

(The highest counter ID seen in coverage maps is not necessarily the same as the number of physical counters actually used by the instrumented code, but it's the best approximation we can get from looking only at the coverage maps, and it should be reasonably accurate in most cases.)

Extracted from #131398, since I'm still considering whether to make those changes as-is, whereas this PR is useful and good on its own.

### CODE REVIEW

**Comment by Zalathar** [comment]
One of the motivations behind this is that it's really easy to make changes that make the coverage mappings “simpler” (by using fewer expressions), at the expense of making them use more physical counters. That's not necessarily a good tradeoff, and without this extra summary it's hard to notice the downside.

**Review by jieyouxu — APPROVED** [review]
AFAICT this seems reasonable. Thanks!

**Comment by Zalathar** [comment]
Rebased/blessed to resolve trivial conflict with #131524.

@bors r=jieyouxu

**Pull request merged**
