### PR TITLE
Add full Rust language grammar definition to docs

### PR DESCRIPTION
**Pull request by icorderi**
Original [issue](https://github.com/rust-lang/rust/issues/19278) that inspired this patch.

The [reference.md](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md) has evolved past simple grammatical constructs, and it serves a different purpose. 
The intent for the proposed _grammar.md_ is to hold **only** the official reference for the language grammar. This document would keep track of grammatical changes to the language over time, facilitate discussions over proposed changes to the existing grammar, and serve as basis for building parsers by third-parties (IDE's, GitHub linguist, CodeMirror, etc.). 

The current state of the PR contains all the grammars that were available in [reference.md](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md) and nothing else. 
There are still a lot of missing pieces that weren't available. The following are just a few of the definitions missing:
- [Functions](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#functions)
- [Structures](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#structures)
- [Traits](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#traits)
- [Implementations](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#implementations)
- [Operators](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#unary-operator-expressions)
- [Statements](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#statements)
- [Expressions](https://github.com/icorderi/rust/blob/docs/grammar/src/doc/grammar.md#expressions)

We need help from people familiar with those grammatical constructs to fill in the missing pieces.

### CODE REVIEW

**Comment by Gankro** [comment]
Triage bump

**Comment by cmr** [comment]
See also https://github.com/bleibig/rust-grammar/ and https://github.com/rust-lang/rust/tree/master/src/grammar

**Comment by cmr** [comment]
My basic feeling is that none of the old grammar is worth keeping and we should instead, if we want, distribute a grammar as a separate appendix.

**Comment by steveklabnik** [comment]
I'm going to merge this as-is, and we can keep improving it, including the part about adding links from the reference. Thank you!

**Comment by nikomatsakis** [comment]
I think if we're going to distribute an official grammar, we really ought to have an automated testing mechanism. Not to say r- on this patch, just that this should be a priority. I think it'd be very helpful, personally, even if it's not what the actual rustc uses (and even if we don't check for correspondence between rustc and the official grammar, which of course would also be good).

**Comment by steveklabnik** [comment]
@nikomatsakis we had some of this in src/grammar, but yes, such a thing would be nice.

**Comment by steveklabnik** [comment]
Oh also, this isn't currently linked from anywhere yet, so while it's kind of official, people may not actually know about it :wink: maybe that's a good critiera for when to add the link.

**Comment by cmr** [comment]
I also really think that this particular partial grammar is worthless, but we can replace it later with https://github.com/bleibig/rust-grammar or https://github.com/ptgreen/rfront as the need arises.

**Comment by brson** [comment]
Epic PR. Thanks for sticking with it.

**Comment by SimonSapin** [comment]
Does this new document shows up somewhere on http://doc.rust-lang.org? I couldn’t find it.

**Comment by steveklabnik** [comment]
@SimonSapin it does not yet, as it's not finished.

**Pull request merged**
