### PR TITLE
book: make the test succeed by avoiding using non-existent function

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by bluss** [comment]
I think it should be identical to the preceding `it_works`, it's an example in the same context, so this change is unnecessary.

**Comment by tshepang** [comment]
But the test fails at the moment

**Comment by Manishearth** [comment]
Plop in a definition of `it_works` commented out with `#`es, then. Testing is supposed to test something, in this case you're testing `add_two`.

**Comment by tshepang** [comment]
I will add the `add_two` function

**Comment by tshepang** [comment]
fixed

**Comment by Manishearth** [comment]
```
---- The__code_ignore__code__attribute_0 stdout ----
	<anon>:2:5: 4:6 error: visibility has no effect inside functions [E0447]
<anon>:2     pub fn add_two(a: i32) -> i32 {
<anon>:3         a + 2
<anon>:4     }
error: aborting due to previous error

```

**Comment by tshepang** [comment]
test ignored, as is the case with one before it

**Comment by Manishearth** [comment]
We don't want to ignore the test.

We want to not mark the function as pub.


Actually, I thought this PR was to solve a doctest failure/ignore, which is why I suggested using a `#`'d out function. But the doctest passes, since doctests don't even compile `#[test]` bits.

It's a pretty common pattern in rust docs to use snippets that need parts from previous snippets. Because of this, I'm not sure if this PR is really necessary.

**Comment by tshepang** [comment]
I think it's marked `pub` in order to demo that the function is to be `use`d externally... it's a library. Note that `pub` is used earlier in the file for the same function, and that case has been `ignore`d as well.

I will close this regardless, given your last point.

**Pull request closed without merging**
