### PR TITLE
Change language in Travis configuration to shell

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
In theory, this will give us more disk space to work with and unblock the queue.

See https://github.com/travis-ci/packer-templates/pull/454 and https://github.com/travis-ci/docs-travis-ci-com/issues/1267#issuecomment-313675483.

cc @kennytm 
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

Looks like travis is stuck.

**Comment by kennytm** [comment]
Thanks @Mark-Simulacrum. 

The beta branch will also need this too, and should be merged before/together with #43199 and #43114.

**Comment by Mark-Simulacrum** [comment]
cc @brson @alexcrichton 

Nominating and accepting for backport to beta -- without this, beta won't build.

**Pull request merged**
