### PR TITLE
Make the getter for NonZero types into a const fn

### PR DESCRIPTION
**Pull request by Lokathor**
I opened an issue for this [here](https://github.com/rust-lang/rust/issues/56721) earlier today and no one immediately called it foolish, so here's the PR for it.

### CODE REVIEW

**Comment by Lokathor** [comment]
Near as I can tell, several of the changes involved adding a special feature

* `#![feature(const_nonzero_methods)]`

which we don't need to bother with now that the minimal `const fn` is stable for everybody. Does that sound right @oli-obk ? I can get to doing this later today after work.

**Comment by oli-obk** [comment]
> which we don't need to bother with now that the minimal const fn is stable for everybody. Does that sound right @oli-obk ?

We still need to do that. Just like any other feature, we first implement it behind a feature gate, and then, once it has been tested on nightly, we stabilize the feature.

**Comment by Lokathor** [comment]
I added the test and gate and such for NonZero types, but I didn't touch DebruijnIndex or any other thing at all. I don't have any understanding of those other parts and I don't want to get lots in the weeds. I'm focusing on a small PR that's a clear improvement, and other things can come later.

**Comment by Centril** [comment]
> 
> 
> > which we don't need to bother with now that the minimal const fn is stable for everybody. Does that sound right @oli-obk ?
> 
> We still need to do that. Just like any other feature, we first implement it behind a feature gate, and then, once it has been tested on nightly, we stabilize the feature.

I think we can dispense with that since we have min_const_fn on stable now; imo someone from T-libs can just FCP instead.

cc @SimonSapin

**Comment by SimonSapin** [comment]
I’m in favor of making this constness stable immediately.

@rfcbot fcp merge

**Comment by Lokathor** [comment]
Should I do one more commit to _remove_ the `#[rustc_const_unstable(feature = "const_nonzero_methods")]` then?

**Comment by SimonSapin** [comment]
@Lokathor Either that, or force-push your branch to remove the commit that adds it. But maybe only after we get team consensus, in case someone thinks differently.

With the team label:

@rfcbot fcp merge

**Comment by dtolnay** [comment]
As implemented in the PR, if the constness is unstable why did `feature(const_nonzero_methods)` need to get added in librustc / librustc_data_structures / librustc_mir? Would those crates not have compiled without `feature(const_nonzero_methods)` i.e. is this a breaking change? Those crates can't already have been using NonZeroT::get in const context since it wasn't const fn. If they were using NonZeroT::get but not in const context then why does that require enabling `feature(const_nonzero_methods)`?

**Comment by oli-obk** [comment]
> Would those crates not have compiled without feature(const_nonzero_methods) i.e. is this a breaking change? 

This is just a leftover from minimizing #54799, which actually used the function in a const way. I did not comment on that, because it was going to go away anyway if we choose to directly stabilize.

**Comment by SimonSapin** [comment]
In https://github.com/rust-lang/rust/pull/56739#issuecomment-446860384 I proposed FCP to stabilize as `const`, without a feature gate. If we have team consensus, the PR would need to change before merging.

**Comment by Lokathor** [comment]
The merge conflict is simple to fix but we're waiting on 1 more vote before deciding on instant stable or nightly with feature. I don't want to clutter up the commit list, so I'll wait for that vote and decision.

But thanks bors-bot.

**Comment by ZirconiumX** [comment]
Ping from not-triage: can @kimundi, @sfackler or @withoutboats review this? We just need one more tick for a majority.

**Comment by Lokathor** [comment]
@simonsapian so it seems like we're going for the instant-stable option, correct?

**Comment by oli-obk** [comment]
yes, feel free to proactively update the PR if you want

**Comment by Lokathor** [comment]
@oli-obk all set.

**Review by oli-obk — APPROVED** [review]

**Comment by Lokathor** [comment]
It said there was nothing to rebase? Maybe I typed in the git command wrong. The "resolve conflicts" tool seems to have sorted it out though.

**Comment by Centril** [comment]
@Lokathor  You have a merge-commit tho and we prefer not to have those... ;)

**Comment by SimonSapin** [comment]
Ehh sorry? I can take care of rebasing for you if you’d like. Let me know, and make sure you check the checkbox https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by Dylan-DPC** [comment]
Reworked this in #57167

**Pull request closed without merging**
