### PR TITLE
Make `x doc --open` work on every book

### PR DESCRIPTION
**Pull request by emilyalbini**
Before this PR, the `--open` flag had to be configured explicitly for every book, and most of them didn't configure it, resulting in the flag silently failing in all but two books.

In this PR, the code to check for the `--open` flag is in the underlying `RustbookSrc` step rather than all the individual steps. This is done by passing the parent step as a field of `RustbookSrc`, so that we can check for the correct step in `maybe_open_in_browser`.

This was part of a larger change that in the end wasn't worth it. Still, I think it could be useful as-is.

### CODE REVIEW

**Comment by ozkanonur** [comment]
Seems we have an error in CI pipeline

@rustbot author

**Comment by pietroalbini** [comment]
That is the current behavior for the books that already support `--open`.

**Review by onur-ozkan — APPROVED** [review]
> That is the current behavior for the books that already support --open.

LGTM then, sorry for the noise.

I think it would be nicer to open the `doc` once for all after the compilation. I will check what I can do for this.

**Pull request merged**
