### PR TITLE
Rollup of 14 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
- Successful merges: #47423, #47425, #47440, #47541, #47549, #47554, #47558, #47610, #47635, #47655, #47661, #47662, #47667, #47672
- Failed merges:

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
That's strange, logs seem incomplete...

**Comment by kennytm** [comment]
It's just the usual #46903 I believe.

**Comment by kennytm** [comment]
@bors r+

Removed #47620, already testing.

**Pull request merged**
