### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #75881 (Expand rustdoc theme chooser x padding)
 - #75885 (Fix another clashing_extern_declarations false positive.)
 - #75892 (Fix typo in TLS Model in Unstable Book)
 - #75901 (Improve theme button hover background color)
 - #75910 (Add test for issue #27130)
 - #75917 (Move to intra doc links for core::ptr::non_null)
 - #75919 (Fix typo (`thumbv8m.main-none-eabihf` is Mainline))
 - #75926 (Fix typo in release notes)
 - #75976 (Improve help popup)
 - #75985 (Should not apply field accessing on enum)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by camelid** [comment]
How do you access the logs for the failed build?

**Comment by bugadani** [comment]
https://github.com/rust-lang-ci/rust/runs/1038546677 Looks like it's caused by #75910 :/

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang-ci/rust/runs/1038546677)

**Comment by bugadani** [comment]
@Dylan-DPC I *think* I fixed the issue, how should I proceed?

**Comment by Dylan-DPC** [comment]
i'll make a new rollup in a while

**Pull request closed without merging**
