### PR TITLE
ci: use a custom android sdk manager with pinning and mirroring

### LINKED ISSUE #59778: Investigate pinning Android SDK components inside CI
We already had at least two different CI issues caused by the Android SDK's sdkmanager:

* https://github.com/rust-lang/rust/pull/57857: a new license was added and sdkmanager failed to accept it with the old command
* https://github.com/rust-lang/rust/issues/59757: the emulator was updated to a broken (at least for us) version, causing all builds to fail

The root cause of those issues is that sdkmanager doesn't support any kind of pinning (as far as I can tell), and any change Google makes can break our CI.

Should we develop a pinning mechanism and use it for all the Android SDK components?

cc @rust-lang/infra

### PR DESCRIPTION
**Pull request by emilyalbini**
Google's own sdkmanager has two issues that make it unsuitable for us:

* Mirroring has to be done manually, which is annoying because we need to figure out on our own all the URLs to copy (I couldn't find any documentation when building this PR, had to use mitmproxy).
* There is no support for pinning, which means an update on Google's side can break our CI, as it happened multiple times.

This PR replaces all our usage of sdkmanager with a custom Python script which mimics its behavior, but with the two issues fixes.

sdkmanager's logic for installing packages is thankfully very simple: the package name (like `system-images;android-18;default;armeabi-v7a`) is the directory where the package should live (with `;` replaced with `/`), so to install a package we only need to extract its contents in the right directory.

r? @alexcrichton 
cc @kennytm 
fixes https://github.com/rust-lang/rust/issues/59778

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you describe a bit what the process would look like to upgrade these images? (ideally in comments in the code as well!)

I'd just want to make sure that's documented somewhere and otherwise lgtm

**Comment by pietroalbini** [comment]
[There is already a bit of docs in the comments.](https://github.com/rust-lang/rust/pull/59926/files#diff-97224f6175da473f77248cd34ad18b0cR7) Should I expand it or move it somewhere else?

The gist of it (for example to update the emulator) is:

```
src/ci/docker/scripts/android-sdk-manager.py add-to-lockfile src/ci/docker/arm-android/android-sdk.lock emulator
src/ci/docker/scripts/android-sdk-manager.py update-mirror src/ci/docker/arm-android/android-sdk.lock
```

**Comment by alexcrichton** [comment]
Yeah I was wondering how we'd update all the hashes, but I see the words now and that seems reasonable to me, sorry for the oversight!

@bors: r+

**Comment by pietroalbini** [comment]
Do not rollup this.

**Comment by Centril** [comment]
@bors p=2

Putting behind a r0llup and its constituent PRs.

**Pull request merged**
