### PR TITLE
Revert most of MaybeUninit, except for the new API itself

### PR DESCRIPTION
**Pull request by RalfJung**
This reverts most of https://github.com/rust-lang/rust/pull/53508/ for perf reasons (first commit reverts that entire PR), except for the new API itself (added back in 2nd commit).

### CODE REVIEW

**Comment by RalfJung** [comment]
@rust-lang/wg-compiler-performance  I'd prefer to also include https://github.com/rust-lang/rust/pull/53508/commits/96572cb5f8e9aab3e39162ff10fc6b8a41dde4ed but wasn't sure if you'd be happy with that.

**Comment by nagisa** [comment]
Do we know *why* the regression occurred?

**Comment by withoutboats** [comment]
@r? @eddyb

**Comment by nagisa** [comment]
@RalfJung this wants a rebase.

**Comment by RalfJung** [comment]
I am on a conference, not sure if I can get to this before the weekend. Anyone, feel free to take over.

**Comment by RalfJung** [comment]
Rebase done.

@bors r=nagisa

**Comment by kennytm** [comment]
@bors p=15

rollup fairness

**Comment by nnethercote** [comment]
The final perf improvements from this landing are [here](https://perf.rust-lang.org/compare.html?start=d95fd2585d8d7327a83beee10d9e32129b26cd68&end=7e7bc060c1564b19742fd241f40a02c9210e445c&stat=instructions:u).

**Pull request merged**
