### PR TITLE
[DO NOT MERGE] Upgrade libcompiler-builtins

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
r? @alexcrichton 

The plan is perform a try, get the artifacts and check if the sanitizers work.

### CODE REVIEW

**Comment by kennytm** [comment]
The CI is green? You need to modify `.travis.yml` to enable the ARM jobs if you want to try those.

**Comment by ishitatsuyuki** [comment]
No, no. Sanitizers are never tested in CI, so we need an artifact to do so. ARM is unrelated to sanitizers.

**Comment by kennytm** [comment]
I see.

**Comment by ishitatsuyuki** [comment]
Can anyone with privilege run a try?

**Comment by kennytm** [comment]
@ishitatsuyuki The `try` build won't run any tests. Or do you just want to get a compiler artifact?

**Comment by ishitatsuyuki** [comment]
Yes, I want an artifact.

**Comment by alexcrichton** [comment]
For others watching, this is related to https://github.com/rust-lang-nursery/compiler-builtins/pull/202. I'm still not super comfortable merging an update to compiler-rt without also updating LLVM, AFAIK they're meant to be kept in tandem and it seems like ripe opportunity for subtle bugs if they get out of sync.

**Comment by ishitatsuyuki** [comment]
@alexcrichton, test results:

ASan in release mode seems partially broken. Invalid memory accesses doesn't trigger an error, but LeakSanitizer does kick in.

ASan in debug mode doesn't compile at all due to #45220. `-Ccodegen-units=1` doesn't have an effect.

Maybe LLVM upgrade is needed then. Feel free to close.

**Pull request closed without merging**
