### PR TITLE
Change how the `0` flag works in format!

### LINKED ISSUE #39997: Text formatting: a leading zero on the minimum width should really mean leading zero
In a string format, the leading zero on a minimum width is treated as a padding character. It would make more sense for it to be treated strictly as a leading zero. The status quo permits strange things like this:
```
assert_eq!(format!("{:<04}", 1), "1000");
```
Either `"   1"` or `"0001"` would be better answers than one that changes the numeric value.

Just to be clear, I agree that this behavior is correct:
```
assert_eq!(format!("{:0<4}", 1), "1000");
```
This case uses `0` as its padding character, so you deserve whatever you get.

### PR DESCRIPTION
**Pull request by Sawyer47**
Now it always implies right-alignment, so that padding zeroes are placed after the sign (if any) and before the digits. In other words, it always takes precedence over explicitly specified `[[fill]align]`. This also affects the '#' flag: zeroes are placed after the prefix (0b, 0o, 0x) and before the digits.

Here's a short summary of how similar format strings work in Python and Rust:

```
              :05     :<05    :>05    :^05 
Python 3.6  |-0001| |-1000| |000-1| |0-100|
Rust before |-0001| |-1000| |-0001| |-0100|
Rust after  |-0001| |-0001| |-0001| |-0001| 

             :#05x   :<#05x  :>#05x  :^#05x 
Python 3.6  |0x001| |0x100| |000x1| |00x10|
Rust before |0x001| |0x100| |000x1| |0x010|
Rust after  |0x001| |0x001| |0x001| |0x001| 
```

Fixes #39997 [breaking-change]

### CODE REVIEW

**Comment by Sawyer47** [comment]
Please don't merge it yet as I completely forgot about floats. I was slightly misled by the current documentation of `0` flag, because it only says about integer formats.

**Comment by Sawyer47** [comment]
I updated the logic for floats as well.

**Comment by alexcrichton** [comment]
Thanks for the PR @Sawyer47! I've tagged this with `T-libs` to ensure that it comes up during triage which is where we'll discuss the breakage aspect

**Comment by alexcrichton** [comment]
@rust-lang/libs if you've got opinions ahead of time, feel free to comment here!

I'm fine landing this PR personally.

**Comment by alexcrichton** [comment]
Discussed during libs triage today the conclusion was that athis is good to go. Thanks for the PR @Sawyer47!

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry

* weird hang in android -- https://github.com/rust-lang/rust/issues/38851

**Pull request merged**
