### PR TITLE
Don't generate empty json variables

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @rust-lang/rustdoc

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Won't this generate a bunch of errors when `source-script.js` attempts to access these missing fields?

**Comment by GuillaumeGomez** [comment]
It's supposed to be checked in the JS. (I'll rerun it locally to be sure though)

**Comment by GuillaumeGomez** [comment]
You were absolutely right, I wasn't checking those variables. Shame on me!

**Review by QuietMisdreavus — APPROVED** [review]
This looks good now, thanks! r=me when travis is green.

**Pull request merged**
