### PR TITLE
Implement `AsFd` and `AsRawFd` for `Rc`

### LINKED ISSUE #105931: `AsFd` and `AsRawFd` are implemented for `Arc<T>`, but not `Rc<T>`
I was looking through the list of things that implement `AsFd`, and noticed there's an implementation for `Arc<T>` where `T: AsFd`, but not for `Rc`. I don't think there's any subtle any subtle reason this couldn't/shouldn't be implemented for `Rc` too?

### PR DESCRIPTION
**Pull request by ids1024**
Fixes https://github.com/rust-lang/rust/issues/105931.

### CODE REVIEW

**Review by eggyal — CHANGES_REQUESTED** [review]
Seems reasonable to me.

You may want to have a quick read over the [Stabilizing features](https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html) chapter of the Standard library developers Guide.  At a minimum the stabilisation attributes should be `since = "CURRENT_RUSTC_VERSION"`.

Obviously will require ACP.

@rustbot modify labels: +T-libs-api

**Comment by ids1024** [comment]
Ah, looks like `CURRENT_RUSTC_VERSION` is new since the last time I submitted a PR like this. Seems like a better way of doing things.

**Comment by joshtriplett** [comment]
This seems exactly analogous to the change for `Arc`.

@rfcbot merge

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
