### PR TITLE
rustc: Rewrite platform intrinsics crate

### LINKED ISSUE #41885: Rewrite platform intrinsic generation as a build script
Right now the compiler has a [`rustc_platform_intrinsics` crate](https://github.com/rust-lang/rust/tree/master/src/librustc_platform_intrinsics) which is basically a database of all platform intrinsics with their inputs/outputs and LLVM names, etc. This is the information the compiler uses to typecheck all intrinsics and also generate code for them with LLVM. An example generated file looks like [`aarch64.rs`](https://github.com/rust-lang/rust/blob/25a161765fb90f2bfc78bda8fef944048e72bd26/src/librustc_platform_intrinsics/aarch64.rs).

These files are all generated by a [`generator.py`](https://github.com/rust-lang/rust/blob/25a161765fb90f2bfc78bda8fef944048e72bd26/src/etc/platform-intrinsics/generator.py) script in the `src/etc` dir. This generator slurps up a ton of JSON definitions, for example all the files in [`src/etc/platform-intrinsics/x86`](https://github.com/rust-lang/rust/tree/25a161765fb90f2bfc78bda8fef944048e72bd26/src/etc/platform-intrinsics/x86) and then generates these Rust files.

Now that we're using Cargo as a build system we can avoid checking in these generated source files. Instead we can translate `generator.py` into Rust as a build script and use build-time code generation to generate all of these files.

This isn't necessarily an easy task because `generator.py` is not exactly a trivial script, but I'm more than willing to help out if anyone's got any questions!

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit rewrites (updates) the `rustc_platform_intrinsics` crate
in this repository. This crate was previously procedurally generated
from a number of JSON files and was intended to be the basis for how we
bind SIMD in Rust. This crate is quite old at this point and is actually
only used very little. The `stdsimd` crate and `std::arch` modules are
the "new" way for stabilizing SIMD intrinsics.

Despite this, however, the crate isn't useless! Most LLVM intrinsics are
called directly in the `stdsimd` crate using the `link_llvm_intrinsics`
feature, but not all intrinsics can be expressed directly in Rust.
Instead some intrinsics, notably those that return LLVM aggregates, need
to be compiler-defined to ensure they're declared with the correct
signature.

A good example of this is the x86 rdrand/rdseed family of LLVM
intrinsics, all of which return an aggregate of some form. The stdsimd
functions which provide these x86 intrinsics link to functions defined
by this crate, so we need to keep those!

Adding all that together, this commit performs the following tasks:

* Deletes the now-outdated `src/etc/platform-intrinsics` infrastructure
* Deletes all `src/librustc_platform_intrinsics/*` intrinsics that are
  otherwise compatible to be defined in Rust itself. This includes
  everything that doesn't deal with aggregates basically. Empty
  architecture files are removed.
* The style of `src/librustc_platform_intrinsics/` was updated slightly
  to make it a bit easier to handwrite. The `x86` rdrand/rdseed
  intrinsics and some `aarch64` intrinsics which return aggregates have
  all survived to continue to be defined by this crate.

Closes #41885

### CODE REVIEW

**Comment by nagisa** [comment]
> A good example of this is the x86 rdrand/rdseed family of LLVM
intrinsics, all of which return an aggregate of some form. The stdsimd
functions which provide these x86 intrinsics link to functions defined
by this crate, so we need to keep those!

We can definitely make something work out here with a special ABI like the `unadjusted` that we introduced as an implementation detail for compiler-rt...

**Comment by alexcrichton** [comment]
@nagisa indeed! And whomever implements that will have the please of deleting this whole crate!

**Comment by alexcrichton** [comment]
In general all `std::arch` intrinsics target the LLVM used by rustc itself, and we haven't seen any requests to get compatibility with older ones. If that comes up though auto-upgrading is good to know!

**Comment by nagisa** [comment]
@bors r+

Some back-story. This crate, I believe, was intended to become some sort of a public stable API for SIMD and other instructions. Since we now have decided on stdsimd approach, it seems fine to me to remove most of this crate. In fact, stdsimd could also replace uses of e.g. rdrand intrinsic with "unadjusted" (yes, it works, cc @gnzlbg) as well. Unless that happens, however, this crate cannot be removed entirely quite yet.

**Comment by alexcrichton** [comment]
Oh nice! If unadjusted works I'll update stdsimd to stop using platform-intrinsics and then I'll send a PR to completely delete this crate. Thanks for checking!

**Comment by bjorn3** [comment]
bjorn3/rustc_codegen_cranelift#171 is the conversation you mean @gnzlbg I think.

**Pull request closed without merging**
