### PR TITLE
Update mdbook.

### PR DESCRIPTION
**Pull request by ehuss**
This brings in some important updates to fix some rendering issues in the books. In particular fixing hidden lines in code blocks, and some escaping issues.  More details at https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md

This also requires updating mdbook-linkcheck.

### CODE REVIEW

**Comment by ehuss** [comment]
cc @mark-i-m @Michael-F-Bryan
I had to remove the timeout filter for mdbook-linkcheck, as the API doesn't seem to provide a way to do it anymore. Would it be possible to extend mdbook-linkcheck to make that a built-in feature?

Also, the API is a little awkward, needing to import a separate crate for the `ColorChoice`.

**Comment by Michael-F-Bryan** [comment]
> Would it be possible to extend mdbook-linkcheck to make that a built-in feature?

You can actually remove the hack checking if "timed out" is in the error message because all necessary information is exposed in the invalid link error. 

I'm not sure of the exact code you'd write (on phone), but the chain of items you're looking for are:

1. [`ValidationOutcome::invalid_links`](https://docs.rs/mdbook-linkcheck/0.5.0/mdbook_linkcheck/struct.ValidationOutcome.html#structfield.invalid_links)
2. [`InvalidLink::reason`](https://docs.rs/mdbook-linkcheck/0.5.0/mdbook_linkcheck/struct.InvalidLink.html#structfield.reason)
3. [`Reason::Client(reqwest::Error)`](https://docs.rs/mdbook-linkcheck/0.5.0/mdbook_linkcheck/enum.Reason.html)
4. [`reqwest::Error::is_timeout()`](https://docs.rs/reqwest/0.9.22/reqwest/struct.Error.html#method.is_timeout)

> Also, the API is a little awkward, needing to import a separate crate for the ColorChoice.

Sorry about the awkward API! I'll see if I can make a new patch release which re-exports the enum so you can avoid adding the dependency to `Cargo.toml` and keep it in sync.

**Comment by ehuss** [comment]
Sorry Alex, you're too fast. I forgot to check licenses, and needed to push an update.

@Michael-F-Bryan None of those are `pub` exposed APIs.  Primarily [`check_links`](https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/ceae3b56afc0822a2c9d321c76a297366855930d/src/lib.rs#L152-L156) is not pub.  It's also a bit unfortunate needing to duplicate all the logic in the `run` function.

**Comment by mark-i-m** [comment]
@ehuss Do you know if it is possible to take advantage of mdbook-linkcheck caching now? That is we would store the link cache. If we do that, then I think we don't need to worry about timeouts as much because we will be making fewer requests to start with... Does Azure pipelines have a way to cache artifacts and restore them?

**Comment by ehuss** [comment]
>  if it is possible to take advantage of mdbook-linkcheck caching now?

Azure has a beta preview of caching, but the rust repo does not use it.  Typically s3 buckets are used, but I do not know anything about them or whether it would be appropriate to use.

**Comment by Michael-F-Bryan** [comment]
> @Michael-F-Bryan None of those are pub exposed APIs. Primarily `check_links` is not pub.

Ah, I was looking at [`mdbook_linkcheck::validate()`](https://docs.rs/mdbook-linkcheck/0.5.0/mdbook_linkcheck/fn.validate.html). I'm guessing it should be fine to make that `pub` seeing as it's the main way you'd want to programmatically use `mdbook-linkcheck` once a book has been loaded into memory.

**Pull request merged**
