### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #44320, #44554, #44648, #44658, #44712, #44717, #44726
- Failed merges:

### CODE REVIEW

**Comment by Havvy** [comment]
https://travis-ci.org/rust-lang/rust/jobs/278400957

```
[00:54:44] failed to execute command: "shasum" "-a" "256" "/checkout/obj/build/x86_64-unknown-linux-gnu/openssl/openssl-1.0.2k.tar.tmp"

[00:54:44] error: No such file or directory (os error 2)
```

**Comment by GuillaumeGomez** [comment]
I suppose it's a travis issue? Let's retry...

@bors: retry

**Comment by aidanhs** [comment]
It failed with the same error, and there is a PR in the rollup that talks about sha1sum...

**Pull request closed without merging**
