### PR TITLE
Sync rustfmt subtree

### PR DESCRIPTION
**Pull request by calebcartwright**

### CODE REVIEW

**Comment by calebcartwright** [comment]
At first blush I'm a bit surprised this only occurred on some platforms and not others, but regardless I don't think it's transient. Will take a closer look later today

@bors r-

**Comment by ytmimi** [comment]
@calebcartwright for what it's worth I also ran into a clap issue a little while ago when opening up a PR. I think I have a fix in https://github.com/rust-lang/rustfmt/pull/5385, but not totally sure if that will be an acceptable solution for what's going on here

**Comment by calebcartwright** [comment]
Thanks @ytmimi though I think this is probably just a case of needing the features specified as part of the workspace hack in this repo

**Comment by calebcartwright** [comment]
@bors r+ p=1

Subtree sync and would like to reduce risk of merge conflicts and having to restart the process

**Pull request merged**
