### PR TITLE
fs::copy() unix: set file mode early

### PR DESCRIPTION
**Pull request by haraldh**
same fix as commit fb98ca716fca8d9342f4cf308622a8e78c072fb7
PR: https://github.com/rust-lang/rust/pull/58803

A convenience method like fs::copy() should try to prevent pitfalls a
normal user doesn't think about.

In case of an empty umask, setting the file mode early prevents
temporarily world readable or even writeable files,
because the default mode is 0o666.

In case the target is a named pipe or special device node, setting the
file mode can lead to unwanted side effects, like setting permissons on
/dev/stdout or for root setting permissions on /dev/null.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder, could the logic here be shared between the two functions?

**Comment by haraldh** [comment]
sure, we can extract the permission part in a helper function

**Comment by haraldh** [comment]
waiting on https://github.com/rust-lang/rust/pull/58803 to be merged for a refactored version

**Comment by haraldh** [comment]
or should I force update #58803 with a new version?

**Comment by alexcrichton** [comment]
Our queue is moving a bit slowly recently (sorry about that!) so want to go ahead and merge this with that PR?

**Comment by haraldh** [comment]
done

**Pull request closed without merging**
