### PR TITLE
Make the unused_mut lint smarter

### PR DESCRIPTION
**Pull request by arielb1**
This makes it somewhat more aggressive, so this is kind-of a [breaking-change] for these compiling with `#[deny(unused_mut)]`.

r? @pnkfelix

### CODE REVIEW

**Comment by arielb1** [comment]
any chance?

**Comment by pnkfelix** [comment]
(I don't know if I agree that #26332 is actually a bug ... that is, I don't know if I like the idea of flagging that sort of code with a warning... but I'm willing to assume that it is for the purposes of completing this review)

**Comment by pnkfelix** [comment]
cc @rust-lang/lang

**Comment by pnkfelix** [comment]
(The cleanup commit looks fine to me; I am just hesistant to r-plus this PR without double-checking that others agree that this change to the lint in question is desirable.)

**Comment by nrc** [comment]
f+ on the principle here - it sounds like it is making the lint better, and I don't think lints count as a breaking change

**Comment by pnkfelix** [comment]
@nrc okay, my main concern was that someone who writes:
```rust
let mut x;
...
x = 3;
```

may intend, in the long term, to add additional statements that assign to `x`, and this lint will be annoying for that case.

But I am willing to believe that the change here will help more than it hurts.  Especially if it helps new-comers understand the idea that the "delayed single-assignment style" like above is not considered mutation by `rustc`.

**Pull request merged**
