### PR TITLE
More thorough status-quo tests for `#[coverage(..)]`

### PR DESCRIPTION
**Pull request by Zalathar**
In light of the stabilization push at https://github.com/rust-lang/rust/issues/84605#issuecomment-2166514660, I have written some tests to more thoroughly capture the current behaviour of the `#[coverage(..)]` attribute.

These tests aim to capture the *current* behaviour, which is not necessarily the desired behaviour. For example, some of the error message are not great, some things that perhaps ought to cause an error do not, and recursive coverage attributes have not been implemented yet.

@rustbot label +A-code-coverage

### CODE REVIEW

**Comment by petrochenkov** [comment]
Could you mark the places in tests that show undesirable or at least questionable behavior with FIXME comments?
@rustbot author

**Comment by Zalathar** [comment]
Added FIXME comments [(diff)](https://github.com/rust-lang/rust/compare/062312d6714dacab753ea3ce6f6d16bb0b29cad4..50936586323eefb6504945f444fe9e4928f2bb86).

@rustbot ready

**Comment by Zalathar** [comment]
Newly-filed issues:
- #126625
- #126626

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Pull request merged**
