### PR TITLE
Disable jump threading `UnOp::Not` for non-bool

### LINKED ISSUE #131195: `-Zmir-opt-level` miscompiles code with panic
I tried this code:

```rust
pub fn myfunc() -> i32 {
    let mut c :i32 = 1;
    c = 1 ;
    if !c != 0 {
        return 1;
    }
    panic!("Reached end of non-void function");
}

pub fn main() {
    let e = myfunc();
    println!("e={}", e);
}
```

I expected to see this happen: **always panic**

Instead, this happened: **only -Zmir-opt-level=2 panic**

For mir-opt-level 0, 1 and 3, they all normally return
```shell
% rustc -Awarnings -Zmir-opt-level=2 test.rs && ./test
thread 'main' panicked at test.rs:7:5:
Reached end of non-void function
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
%
% rustc -Awarnings -Zmir-opt-level=0 test.rs && ./test
e=1
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (18b1161ec 2024-10-02)
binary: rustc
commit-hash: 18b1161ec9eeab8927f91405bca0ddf59a4a26c9
commit-date: 2024-10-02
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fix #131195, where jumpthreading was optimizing `!a == b` into `a != b` for non-bool, where this is definitely not true.

### CODE REVIEW

**Comment by compiler-errors** [comment]
I would not be surprised if jumpthreading has more type-based bugs, since we've already found two at this point.

**Comment by compiler-errors** [comment]
#131203

**Comment by compiler-errors** [comment]
This is a more conservative fix than #131201, which seems like it still has problems.

**Comment by lqd** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-10-10/near/476139779). A backport PR will be authored by the release team at the end of the current development cycle.

Stable nomination is also [accepted in principle](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-10-10/near/476140262) but it's not really needed: the new stable should have this beta backport when the stable artifacts are built in 3 days. Therefore, I'll remove the stable nomination, as it's a no-op this late in the cycle.

@rustbot label +beta-accepted -stable-nominated

**Pull request merged**
