### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #88906 (Implement write() method for Box<MaybeUninit<T>>)
 - #90269 (Make `Option::expect` unstably const)
 - #90854 (Type can be unsized and uninhabited)
 - #91170 (rustdoc: preload fonts)
 - #91273 (Fix ICE #91268 by checking that the snippet ends with a `)`)
 - #91381 (Android: -ldl must appear after -lgcc when linking)
 - #91453 (Document Windows TLS drop behaviour)
 - #91462 (Use try_normalize_erasing_regions in needs_drop)
 - #91474 (suppress warning about set_errno being unused on DragonFly)
 - #91483 (Sync rustfmt subtree)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=88906,90269,90854,91170,91273,91381,91453,91462,91474,91483)

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Did bors hiccup here? I think it's complaining that merged PRs are now conflicting with themselves?

**Comment by pietroalbini** [comment]
This has been merged into master, but GitHub didn't detect it for whatever reason. Closing.

**Comment by rylev** [comment]
@matthiaskrgr this seems to hurt match expression compilation performance, but none of the individual PRs strike me as being a culprit. We'll likely want to run cachegrind to see what we find, but I unfortunately don't have time for that right now.

**Pull request closed without merging**
