### PR TITLE
Add `-Z instrument-mcount`

### PR DESCRIPTION
**Pull request by quark-zju**
This flag inserts `mcount` function call to the beginning of every function
after inline processing. So tracing tools like uftrace [1] (or ftrace for
Linux kernel modules) have a chance to examine function calls.

It is similar to the `-pg` flag provided by gcc or clang, but without
generating a `__gmon_start__` function for executables. If a program
runs without being traced, no `gmon.out` will be written to disk.

Under the hood, it simply adds `"instrument-function-entry-inlined"="mcount"`
attribute to every function. The `post-inline-ee-instrument` LLVM pass does
the actual job.

[1]: https://github.com/namhyung/uftrace

### CODE REVIEW

**Comment by estebank** [comment]
@bors r+

CC @rust-lang/compiler

**Comment by nagisa** [comment]
Is it known that all the tools use specifically the `mcount` function name? A codegen test would’ve been nice as well.

**Comment by quark-zju** [comment]
Good question. uftrace seems to assume the `mcount` name for now. `clang -pg` defaults to [`mcount`](https://github.com/llvm-mirror/clang/blob/d1840a054d43341f98b8a37f490248818c11fee4/lib/Basic/TargetInfo.cpp#L108) but platforms can override it. The rule seems rather [complicated](https://github.com/llvm-mirror/clang/blob/d569b56d4d26d45cee1d65b868318cba15358fc6/lib/Basic/Targets/OSTargets.h#L230). I guess that's for gprof compatibility. Since uftrace is the main intended use-case here, it seems cleaner to not introduce such complexity. I'll add a comment, and try to add a test.

**Comment by eddie9712** [comment]
Hi all, I have tried the "-Z instrument-mcount" with rustc compiler (`rustc 1.60.0-nightly (bd3cb5256 2022-01-16)`). However, I didn't get any `mcount` function insert in my executable file. Is the "-Z instrument-mcount" still supported ?

**Comment by dwlsalmeida** [comment]
@eddie9712 same here!

**Comment by honggyukim** [comment]
Hi, @quark-zju already analyzed this problem before at https://github.com/namhyung/uftrace/issues/1392#issuecomment-986403291. There must be some changes in LLVM 13. @tlambertz found a workaround at https://github.com/namhyung/uftrace/issues/1392#issuecomment-1047195716 as follows.
```
rustc +nightly -Zinstrument-mcount -C passes="ee-instrument post-inline-ee-instrument" main.rs
```
For now, we have to add `-C passes="ee-instrument post-inline-ee-instrument"` along with `-Zinstrument-mcount` until LLVM fixes this issue.

**Pull request merged**
