### PR TITLE
Hash full Ident (including Span) in AssocItem

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by cjgillot** [comment]
Would the trick from https://github.com/rust-lang/rust/pull/92533 work here, or is it too heavy a change?

**Comment by Aaron1011** [comment]
> Would the trick from #92533 work here, or is it too heavy a change?

I started working on that when I was writing this PR, but it was turning into a fair amount of work. I'll see if I can get it compiling

**Comment by Aaron1011** [comment]
We went with https://github.com/rust-lang/rust/pull/93095 instead

**Pull request closed without merging**
