### PR TITLE
fix CI skipping weekly `cargo update`

### PR DESCRIPTION
**Pull request by pitaj**
This resolves the issue where CI will not run on PRs opened by the existing workflow, due to Github automatically preventing tasks performed by `GITHUB_TOKEN` from initiating more workflow runs.

r? infra

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm going to try and bring this up during today's infra meeting - I'd like to see if folks have opinion on this vs. using a deploy key while keeping the token for accessing content...

**Comment by pitaj** [comment]
I did look into that, but the problem is then that the token needs push access to rust-lang-ci/rust and PR access to rust-lang/rust.

**Comment by pitaj** [comment]
Trying some things but I'm pretty sure this isn't possible without multiple tokens/keys.

**Comment by pitaj** [comment]
Okay, so I was able to get this to work using a classic personal access token with just the `public_repo` and `read:org` permissions. Of course my bot `pitaj-highfive` had to have write access to `pitaj-rust-lang-ci/rust` but this could also be made to work on the bot's own `rust` fork instead of the `-ci` fork.

**Pull request closed without merging**
