### PR TITLE
rustdoc: Clean up handling of lifetime bounds

### PR DESCRIPTION
**Pull request by camelid**
Previously, rustdoc recorded lifetime bounds by rendering them into the
name of the lifetime parameter. Now, it leaves the name as the actual
name and instead records lifetime bounds in an `outlives` list, similar
to how type parameter bounds are recorded.

Also, higher-ranked lifetimes cannot currently have bounds, so I simplified
the code to reflect that.

r? @GuillaumeGomez

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
You did it faster than I expected. Looks great, thanks a lot!

@bors: r+

**Comment by jyn514** [comment]
@bors r-

This doesn't update format-version in rustdoc-json-types. Please read the messages from highfive, I set them up for a reason.

**Comment by jyn514** [comment]
Oh sorry, I missed https://github.com/rust-lang/rust/pull/88604/files#diff-1a2ef1ea43fd65123fdf8a158a34408aa7c31c4bdb34ce1458b7f6c22b3ab459R237. Seems weird that the format-version is in rustdoc and not in rustdoc-json-types - maybe we should change that at some point?

@bors r=GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
> Oh sorry, I missed https://github.com/rust-lang/rust/pull/88604/files#diff-1a2ef1ea43fd65123fdf8a158a34408aa7c31c4bdb34ce1458b7f6c22b3ab459R237. Seems weird that the format-version is in rustdoc and not in rustdoc-json-types - maybe we should change that at some point?
> 
> @bors r=GuillaumeGomez

Please open an issue so we don't forget. ;)

**Pull request merged**
