### PR TITLE
Fix MinGW `run-make-fulldeps` tests

### PR DESCRIPTION
**Pull request by mati865**
`compiler-rt-works-on-mingw` and `libs-search-path` were not ran because `only-mingw` doesn't match any target.
Enabled and verified few ignored tests with `windows-gnu` toolchain. They are still ignored on MSVC since I'm not experienced with this target.

### CODE REVIEW

**Comment by jyn514** [comment]
This failed on x86_64-pc-windows-gnu: https://github.com/rust-lang/rust/pull/74415#issuecomment-659744772

**Comment by mati865** [comment]
I apologize for that.
Made last second tweak to the test and typed `_imp__` instead of `__imp_` 🤦‍♂️

Tests pass again:
```
Check compiletest suite=run-make-fulldeps mode=run-make (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)

running 212 tests
...i........ii..i.i...i....................ii...i.............i.i..............ii.....i............. 100/212
.......i..................iiiiii......ii..i.i....i.i..iii.....................iii.i................. 200/212
............
test result: ok. 178 passed; 0 failed; 34 ignored; 0 measured; 0 filtered out

        finished in 60.116
```

**Pull request merged**
