### PR TITLE
remove `Tt` prefix from TokenType variants

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by sfackler** [comment]
Can you add `[breaking change]` to the commit message? LGTM otherwise.

**Comment by oli-obk** [comment]
done

**Comment by sfackler** [comment]
Looks like there are some tests that need to be modified as well.

**Comment by oli-obk** [comment]
sorry about that... grep now returns no results for `TtToken`, `TtDelim` or `TtSeqence`

**Pull request merged**
