### PR TITLE
[beta] Uniform path backports

### PR DESCRIPTION
**Pull request by petrochenkov**
What's included:
- https://github.com/rust-lang/rust/pull/56392/commits/c658d7340149274bb30a56fb3e7de799c266f4bc ("resolve: Avoid "self-confirming" resolutions in import validation", prerequisite for the following items)
- https://github.com/rust-lang/rust/pull/57160 ("resolve: Fix an ICE in import validation")
- https://github.com/rust-lang/rust/pull/56759 ("Stabilize `uniform_paths`")

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @Aaronepower (for https://github.com/rust-lang/rust/pull/57471) -- I think it's likely this will land and if necessary I can take on backing it out of stable last minute

**Comment by petrochenkov** [comment]
@ :guardsman: craterbot run start=master#2bde39b8edce6463e1c37f8a8082a875e7b536b1 end=try#0d8b5d1f16bab9e975695518ff8705bdab9fe94c mode=check-only

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/compiler meeting. We decided we're definitely ok with backporting the first two PRs. As for the third PR, we don't typically backport stabilizations, but in this case this would help close a source of active problems around migration ([see this list of related bugs](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.2354818.20weekly.20meeting.202019-01-10/near/154846582)). Therefore, 👍 to backport if the crater run results look good.

**Comment by pietroalbini** [comment]
I included c658d73 and #57160 in the rollup (https://github.com/rust-lang/rust/pull/57516), so we'll only need to backport the stabilization if crater is ok.

**Comment by pietroalbini** [comment]
Crater results looks good!

@bors r+

**Comment by pietroalbini** [comment]
Rolled up inside #57516.

**Pull request merged**
