### PR TITLE
Allow transmutes between the same types after erasing lifetimes

### LINKED ISSUE #101081: Regression transmuting `RwLockReadGuard<T: ?Sized>`.
`RwLockReadGuard<T>` is now not transmutable when `T` is (dependent on) a generic parameter and `?Sized`, when it was previously 

(I don't necessarily think this is a significant enough problem to be worth "fixing", but I guess it is technically a regression).

### Code

I tried this code:

```rust
use std::sync::RwLockReadGuard;
// the lifetimes aren't important
fn test1<'to, 'from: 'to, T: ?Sized>(guard: RwLockReadGuard<'from, T>) -> RwLockReadGuard<'to, T> {
    unsafe { std::mem::transmute(guard) }
}
```

I expected to see this happen: compilation success

Instead, this happened: compilation error
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/main.rs:7:14
  |
7 |     unsafe { std::mem::transmute(guard) }
  |              ^^^^^^^^^^^^^^^^^^^
  |
  = note: `RwLockReadGuard<T>` does not have a fixed size
```

### Version it worked on

It most recently worked on: Rust 1.63.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.64.0-beta.3 (82bf34178 2022-08-18)
binary: rustc
commit-hash: 82bf34178fb14562d158c4611bdab35d4d39b31c
commit-date: 2022-08-18
host: x86_64-unknown-linux-gnu
release: 1.64.0-beta.3
LLVM version: 14.0.6
```

### Backtrace
(no backtrace, compiler didn't crash)

### Why
[This commit](https://github.com/rust-lang/rust/commit/7cefa8f9959565acc6e3606cfa6aa1376c9f862f) changed the definition of `RwLockReadGuard` from
```rs
pub struct RwLockReadGuard<'a, T: ?Sized + 'a> {
    lock: &'a RwLock<T>,
}
```
to
```rs
pub struct RwLockReadGuard<'a, T: ?Sized + 'a> {
    inner_lock: &'a sys::MovableRwLock,
    data: &'a T,
}
```

(The following is (AFAICT) why this change caused this regression; It is not itself a regression, and it applies to all (recent) versions of rustc (i.e. since at least 1.41.0))

AFICT, rustc currently only supports transmuting a subset of `Sized` types that it conservatively can guarantee are the same size. For generic struct types with `?Sized` parameters, i think rustc can only guarantee the size if the whole struct's size does not depend on the parameters, or if the struct's only non-zst field is a (transitive transparent wrapper of a) pointer type depending on a generic parameter (`rustc_middle::ty::layout::SizeSkeleton` only has `Known(usize)` and `Pointer { .. }` variants, so can only express completely known and only-a-pointer sizes), e.g.
```rs
pub struct Works<T: ?Sized> { // SizeSkeleton::compute returns Ok(Pointer { .. }) for this when T: ?Sized
    inner: *mut T,
}
pub unsafe fn works<T: ?Sized>(from: Works<T>) -> Works<T> {
    std::mem::transmute(from) // works
}

#[repr(align(32))]
struct OverAlignZST;

pub struct AlsoWorks<T: ?Sized> { // SizeSkeleton::compute returns Ok(Pointer { .. }) for this when T: ?Sized
    inner: *mut T,
    other: OverAlignZST,
}
pub unsafe fn also_works<T: ?Sized>(from: AlsoWorks<T>) -> AlsoWorks<T> {
    std::mem::transmute(from) // works
}

pub struct DoesntWork<T: ?Sized> { // SizeSkeleton::compute returns Err(Unknown(T)) for this when T: ?Sized
    inner: *mut T,
    other: u8,
}
pub unsafe fn doesnt_work<T: ?Sized>(from: DoesntWork<T>) -> DoesntWork<T> {
    std::mem::transmute(from) // DoesntWork<T> does not have a fixed size
}
```

(See also: #101084 )
<details><summary>Moved to #101084</summary>
<p>
(See also: #101084)
Unrelated note: I think this size-calculation ignoring all ZSTs (not just 1-ZSTs) when there is a pointer field can cause `transmute` to (incorrectly?) allow transmuting between differently-sized types, e.g. this compiles and runs normally, but ICEs under miri:

```rs
#[repr(align(32))]
struct OverAlignZST;

pub struct AlsoWorks<T: ?Sized> { // SizeSkeleton::compute returns Ok(Pointer { .. }) for this when T: ?Sized
    inner: *mut T,
    other: OverAlignZST,
}
// This does not compile if you remove ?Sized
pub unsafe fn also_works<T: ?Sized>(from: *mut T) -> AlsoWorks<T> {
    std::mem::transmute(from) // works
}
fn main() {
    let mut x = vec![0; 16];
    let x = &mut x[..];
    unsafe {
        let x = also_works(x);
      }
 }
```

```
$ cargo miri run
...
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Size(16 bytes)`,
 right: `Size(32 bytes)`
...
query stack during panic:
end of query stack

Miri caused an ICE during evaluation. Here's the interpreter backtrace at the time of the panic:
note: the place in the program where the ICE was triggered
  --> src/main.rs:57:5
   |
57 |     std::mem::transmute(from) // works
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: inside `also_works3::<[i32]>` 
...
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by oli-obk**
r? @compiler-errors  on the impl

fixes #101081 

See discussion in the issue and at https://rust-lang.zulipchat.com/#narrow/stream/326866-t-types.2Fnominated/topic/.23101081.3A.20Regression.20transmuting.20.60RwLockReadGuard.3CT.3A.20.3FSized.3E.E2.80.A6

I think this may need lang team signoff as its implications may go beyond the jurisdiction of T-types

I'll write up a proper summary later

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
r=me on the implementation, waiting for FCP

**Comment by apiraino** [comment]
Signaling the [above comment](https://github.com/rust-lang/rust/pull/101520#pullrequestreview-1103159911) with a `S-blocked` label

@rustbot label s-blocked

**Comment by oli-obk** [comment]
transmuting between (generic) types is only allowed for specific subsets of types. Usually this means that you can transmute between types where the sizes are known (e.g. pointers) or structs of a single field of such a type.

The problem with those rules is that you can easily end up in a situation where `transmute<Foo<'a, T>, Foo<'b, T>>(x)` is rejected, because there are some non-zst fields:

```rust
struct Foo<'a, T: ?Sized>(&'a T, i32);

fn foo<'a, 'b, T: ?Sized>(x: Foo<'a, T>) -> Foo<'b, T> {
    unsafe { std::mem::transmute(x) }
    // ^ only an error if the `i32` field is there, otherwise compiles fine
}
```

I propose to relax the rules on transmutes and allow transmutes between types that are equal (ignoring regions). This means we lock ourselves into a world where we can never use specialization on lifetimes to change types. As far as I can tell this would be unsound for other reasons anyway, so it's not a loss.

@rfcbot merge

**Comment by joshtriplett** [comment]
The only lifetime I can imagine specializing on would be `'static`. Would that still be an option, potentially?

**Comment by lcnr** [comment]
Specialization (affecting associated types) being possible based on `'static` is in conflict with this PR. However, specialization based on `'static` is already impossible (or nearly so) due to other reasons however:

Const evaluation has to happen during typeck for const generics. During typeck we do not know whether some arbitrary region variable will end up as `'static`. If a constant therefore references some region variable, we can only evaluate that one once borrowck is complete. We need to evaluate constants before borrowck however.

We also ignore regions in other areas of the compiler which might be slightly easier to change (if still difficult).

But even ignoring the difficulty of actually implementing specialization based on `'static`, I don't think we should add that for 2 reasons. `borrowck` is currently only a safety check, it does not impact codegen in any way. This is a nice property we lose this way. It is also quite difficult to understand where lifetimes are actually `'static`. Promotion makes things `'static` which shouldn't be while subtyping "un-`'static`s" things which should be `'static`. E.g. consider `fn two_inputs<'a>(a: &'a (), b: &' ())`. If you call two inputs with `'static` and some shorter local lifetime, subtyping changes `'static` to a shorter lifetime, which would change the used impl by specialization which is really bad.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by scottmcm** [comment]
Pondering: Does adding this make it any harder in (the far) future to change the check from being compiler-magic to some kind of `where const { size_of::<T>() == size_of::<U>() }`?  Or are there already existing cases that make the complicated (other than the questions about how to add such constraints at all).

**Comment by lcnr** [comment]
> Pondering: Does adding this make it any harder in (the far) future to change the check from being compiler-magic to some kind of `where const { size_of::<T>() == size_of::<U>() }`? Or are there already existing cases that make the complicated (other than the questions about how to add such constraints at all).

wouldn't expect so, ctfe also erases regions, so this shouldn't add any additional complications.

**Comment by compiler-errors** [comment]
r=me when rebased

**Comment by jackh726** [comment]
I think labels here a bit a wonky.

This should probably have just gotten a "S-waiting-on"fcp" label, if anything, and not S-blocked or S-waiting-on-team.

**Pull request merged**
