### PR TITLE
Remove needless indirection through Rc

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
NamedMatch is already cheap to clone due to Lrc's inside.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Since this may have performance implications, let's gather performance data:

@bors try

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 126d5c72bb5ed8113cc4d92fef9161f3f4b7863e

**Comment by petrochenkov** [comment]
r=me when perf is ready

**Comment by Mark-Simulacrum** [comment]
Perf looks like just noise as I expected, since this isn't really removing an allocation from the hot path and Rc is very cheap.

@bors r=petrochenkov rollup

**Pull request merged**
