### PR TITLE
introduce "type must be valid for" into lexical region solver

### LINKED ISSUE #55756: Lifetimes bug on beta 1.31: the associated type may not live long enough
A reduced test case ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=95c6cf5b6f9d53cfb7136cfa1bbd0b7e)):

```rust
#![crate_type="lib"]

pub trait Database<'a> {
    type Guard: 'a;
}

pub struct Stateful<'a, D: 'a>(&'a D);

impl<'b, D: for <'a> Database<'a>> Stateful<'b, D> {
    pub fn callee<'a>(&'a self) -> <D as Database<'a>>::Guard {
        unimplemented!()
    }
    pub fn caller<'a>(&'a self) -> <D as Database<'a>>::Guard {
        let state = self.callee();
        unimplemented!()
    }
}
```

Error diagnostic output in details block below

<details>

```
error[E0311]: the associated type `<D as Database<'_>>::Guard` may not live long enough
  --> src/lib.rs:14:13
   |
14 |         let state = self.callee();
   |             ^^^^^
   |
   = help: consider adding an explicit lifetime bound for `<D as Database<'_>>::Guard`
note: the associated type `<D as Database<'_>>::Guard` must be valid for the block suffix following statement 0 at 14:9...
  --> src/lib.rs:14:9
   |
14 | /         let state = self.callee();
15 | |         unimplemented!()
16 | |     }
   | |_____^
note: ...so that variable is valid at time of its declaration
  --> src/lib.rs:14:13
   |
14 |         let state = self.callee();
   |             ^^^^^

error[E0311]: the associated type `<D as Database<'_>>::Guard` may not live long enough
  --> src/lib.rs:14:13
   |
14 |         let state = self.callee();
   |             ^^^^^
   |
   = help: consider adding an explicit lifetime bound for `<D as Database<'_>>::Guard`
note: the associated type `<D as Database<'_>>::Guard` must be valid for the block at 13:63...
  --> src/lib.rs:13:63
   |
13 |       pub fn caller<'a>(&'a self) -> <D as Database<'a>>::Guard {
   |  _______________________________________________________________^
14 | |         let state = self.callee();
15 | |         unimplemented!()
16 | |     }
   | |_____^
note: ...so that references are valid when the destructor runs
  --> src/lib.rs:14:13
   |
14 |         let state = self.callee();
   |             ^^^^^

error[E0311]: the associated type `<D as Database<'_>>::Guard` may not live long enough
  --> src/lib.rs:14:21
   |
14 |         let state = self.callee();
   |                     ^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound for `<D as Database<'_>>::Guard`
note: the associated type `<D as Database<'_>>::Guard` must be valid for the method call at 14:21...
  --> src/lib.rs:14:21
   |
14 |         let state = self.callee();
   |                     ^^^^^^^^^^^^^
note: ...so type `<D as Database<'_>>::Guard` of expression is valid during the expression
  --> src/lib.rs:14:21
   |
14 |         let state = self.callee();
   |                     ^^^^^^^^^^^^^

error[E0311]: the associated type `<D as Database<'_>>::Guard` may not live long enough
  --> src/lib.rs:14:21
   |
14 |         let state = self.callee();
   |                     ^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound for `<D as Database<'_>>::Guard`
note: the associated type `<D as Database<'_>>::Guard` must be valid for the destruction scope surrounding statement at 14:9...
  --> src/lib.rs:14:9
   |
14 |         let state = self.callee();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...so that references are valid when the destructor runs
  --> src/lib.rs:14:21
   |
14 |         let state = self.callee();
   |                     ^^^^^^^^^^^^^

error: aborting due to 4 previous errors
```

</details>

## Original bug report

#### Versions
rustc 1.31.0-beta.4 (04da282bb 2018-11-01)
cargo 1.31.0-beta (efb7972a0 2018-10-24)

#### Expected behavior
Everything compiling correctly like it does on stable 1.30

#### Actual behavior
A lot of lifetime-related errors:
```
error[E0311]: the associated type `<D as trie::Database<'_>>::Guard` may not live long enough                                                                                                                                    
   --> /home/mike/dev/etcdev/sputnikvm/stateful/src/lib.rs:536:23                                                                                                                                                                
    |                                                                                                                                                                                                                            
536 |         let account = state.get(&address);                                                                                                                                                                                 
    |                       ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                  
    |                                                                                                                                                                                                                            
    = help: consider adding an explicit lifetime bound for `<D as trie::Database<'_>>::Guard`                                                                                                                                    
note: the associated type `<D as trie::Database<'_>>::Guard` must be valid for the method call at 536:23...                                                                                                                      
   --> /home/mike/dev/etcdev/sputnikvm/stateful/src/lib.rs:536:23                                                                                                                                                                
    |                                                                                                                                                                                                                            
536 |         let account = state.get(&address);                                                                                                                                                                                 
    |                       ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                  
note: ...so that a type/lifetime parameter is in scope here                                                                                                                                                                      
   --> /home/mike/dev/etcdev/sputnikvm/stateful/src/lib.rs:536:23                                                                                                                                                                
    |                                                                                                                                                                                                                            
536 |         let account = state.get(&address);                                                                                                                                                                                 
    |                       ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                  
                                                 
```

It has been an issue in nightly 1.31 for a long time now, but I haven't reported the issue while it was just nightly. Now the regression is in beta channel and may land in stable, breaking existing code.

My own findings on the subject: regression is related to an old lifetime system, it's not reproducible with `nll` feature on, so on `nightly` the code can be compiled with `nll`, but not without it. Same holds for beta now except `nll` isn't quite there yet.

The subjected codebase: https://github.com/ETCDEVTeam/sputnikvm/tree/master/stateful

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is a fix for #55756 -- it makes the lexical region solver impose constraints more like the ones that NLL does, which overcomes a shortcoming in the logic for handling `<T as Foo<'a>>::Bar: 'b` outlives bounds. As part of the NLL check, that logic itself was fixed to avoid "overconstraining" -- i.e., adding stricter region checks than were necessary. Unfortunately, the logic now has the potential to *underconstrain* (it always did, but it's worse). This is caused #55756. This change matches NLL's behavior, which winds up requiring that if a value of type `T` is live during some scope S, then every region in `T` must outlive `S` (which is stricter than outlives when normalization is involved). 

As part of the Chalk and Polonius work, I plan to revisit this whole system, and hopefully move to a more precise solver that can accommodate the kinds of outlives constraints we encounter in progress. However, this patch seems like a reasonably conservative step that also solves the regressions at hand.

[More discussion in this comment.](https://github.com/rust-lang/rust/issues/55756#issuecomment-439151486)

Fixes #55756 

r? @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @rust-lang/compiler -- I'm nominating this for beta backport, since it fixes a regression.

**Comment by pietroalbini** [comment]
@bors r-
Tidy failed:

```
[00:04:02] tidy error: /checkout/src/librustc_typeck/check/regionck.rs:378: line longer than 100 chars
[00:04:02] tidy error: /checkout/src/librustc_typeck/check/regionck.rs:832: line longer than 100 chars
[00:04:02] tidy error: /checkout/src/librustc_typeck/check/regionck.rs:1049: line longer than 100 chars
```

**Comment by nikomatsakis** [comment]
Giving p=1 because this is a Rust 2018 blocker.

**Comment by nikomatsakis** [comment]
@bors r-

Huh. Apparently this broke some tests.

**Comment by nikomatsakis** [comment]
OK, so, the errors are sort of interesting. These are test cases that also break with NLL (I guess that makes sense). They have to do with closures whose signatures contain invalid types -- currently, regionck doesn't give an error for this, but it seems wrong. An example is:

```rust
    || {
        &mut x //~ ERROR cannot infer
    };
```

Why, you ask, is this wrong? Well, the answer is that this is an `FnMut` closure, so it has access to only an `&'a mut self`, but it is returning out access to (effectively) `&mut self.x`. The return type of this closure would therefore have to be something like `&'a mut T` where `T` is the type of `x`. But given the structure of the `FnMut` trait, the associated type `Output` cannot name this `'a`, it is not in scope. And indeed if you try to *use* this closure in any way, the error would be detected. (Here is an [analogous situation written more explicitly](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=8365c5f2d723a542c97df86cba199594).)

I *suspect* we can get away with breaking these tests -- NLL will break them away, and they are seim-broken -- but it makes me a *bit* nervous. We could also try one of the alternative fixes I had in mind. (Hmm, I *thought* that the NLL breakage was noticed in the wild (https://github.com/rust-lang/rust/issues/49824) but it turns out that this breakage was noticed by *me* from one of our *other* tests which was purposefully probing at extreme scenarios. That makes me feel better.)

One test that used to give errors also now started to work, interestingly -- that test seems clearly "ok" to me (it's an `impl Trait` regression test added because it used to ICE, owing to inferring a `'empty` region, one that is presumably now constrained by the more coarse rule).

**Comment by nikomatsakis** [comment]
On balance, given that the broken tests are basically invalid and the fixed test seems valid, I'm inclined to run with it.

**Comment by nikomatsakis** [comment]
@bors r- 

I am feeling mildly nervous about backporting this and want to attempt a more conservative fix first.

**Comment by nikomatsakis** [comment]
I think I would still like to make this change, but I am not as keen to beta nominate it. Created #56043 which also fixes same bug.

**Comment by alexcrichton** [comment]
@nikomatsakis with https://github.com/rust-lang/rust/pull/56043 landed and backported is still still 2018 edition critical? (aka on the milestone)

**Comment by nikomatsakis** [comment]
@alexcrichton it is not

**Comment by nikomatsakis** [comment]
@bors r- 

Actually, second guessing. I want to think about whether to land this now or let NLL fix these test cases.

**Comment by pnkfelix** [comment]
@nikomatsakis I'd like us to consider landing this now.

Minimizing the number of *subtle* discrepancies between AST-borrowck and NLL eases our internal processes for evaluating the correctness of NLL itself.

**Comment by eddyb** [comment]
@pnkfelix I would prefer landing this if it gets us closer to removing the AST borrowck (is there a full post-2018 transition plan spelled out anywhere?).

**Comment by Dylan-DPC** [comment]
ping from triage @nikomatsakis @pnkfelix @eddyb any updates on this?

**Comment by nikomatsakis** [comment]
Sorry, I've been busy. I'm going to try and rebase this and/or close it this week though =)

**Comment by stokhos** [comment]
Ping from triage @nikomatsakis  Have you been able to make any progress on this PR?

**Comment by nikomatsakis** [comment]
Not yet but still hope to =)

**Comment by Centril** [comment]
Ping from triage, @nikomatsakis -- have you been able to make progress?

r? @pnkfelix

**Comment by Dylan-DPC** [comment]
ping from triage @nikomatsakis closing this due to inactivity. Thanks

**Pull request closed without merging**
