### PR TITLE
[BETA] Update cargo

### PR DESCRIPTION
**Pull request by ehuss**
3 commits in d0f828419d6ce6be21a90866964f58eb2c07cd56..9edd089168f8795b3890bc3daf5b99f03e9f8765
2019-07-23 21:58:59 +0000 to 2019-08-02 09:26:36 -0700
- [beta] Revert "Release a jobserver token while locking a file" (rust-lang/cargo#7204)
- [BETA] Don't fail if we can't acquire readonly lock (rust-lang/cargo#7165)
- [BETA] Fix `cargo new` in root directory. (rust-lang/cargo#7128)

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

Looks like LLVM fell out of cache

**Comment by ehuss** [comment]
@pietroalbini Are you planning a beta rollup?  Just FYI, I just added a new commit here.

@bors r=alexcrichton

**Comment by pietroalbini** [comment]
> Are you planning a beta rollup?

Yeah in the next few days, which is the reason for the p=-1.

**Comment by pietroalbini** [comment]
@bors r-

This should still be considered approved, but I'll include it in the rollup tomorrow.

**Pull request merged**
