### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #121248 (Move some tests)
 - #121528 (Consider middle segments of paths in `unused_qualifications`)
 - #121749 (Don't lint on executable crates with `non_snake_case` names)
 - #121935 (library/ptr: mention that ptr::without_provenance is equivalent to deriving from the null ptr)
 - #121945 (Run some ui-fulldeps tests on stage 1 again)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=121248,121528,121749,121935,121945)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors retry
  warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)

**Comment by Kobzol** [comment]
@rust-timer build f6ee0c0d7e340bf27eed847964571921caafed7c

**Comment by Kobzol** [comment]
Looks like the regressions come from https://github.com/rust-lang/rust/pull/121528. It seems to be a correctness fix, so I think it's fine, but just CCing @petrochenkov to check if this is expected.

**Pull request merged**
