### PR TITLE
Split starting a listener out from accepting the first connection.

### PR DESCRIPTION
**Pull request by anasazi**
The Listener trait takes two type parameters, the type of connection and the type of Acceptor,
and specifies only one method, listen, which consumes the listener and produces an Acceptor.

The Acceptor trait takes one type parameter, the type of connection, and defines two methods.
The accept() method waits for an incoming connection attempt and returns the result.
The incoming() method creates an iterator over incoming connections and is a default method.

Example:

``` rust
let listener = TcpListener.bind(addr); // Bind to a socket
let acceptor = listener.listen(); // Start the listener
for stream in acceptor.incoming() {
    // Process incoming connections forever (a failure will kill the task).
}
```

Closes #8689

### CODE REVIEW

**Comment by Fensteer** [comment]
In the current version of TCP implementation, these changes have been overwritten, is it a regression ? The overwrite occurred when net2 has been merge to net.

**Comment by eddyb** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
@Fensteer this is, uh, a five-year-old PR. Nearly everything about libstd and rustc has changed since this time. I'd recommend opening a fresh issue.

**Comment by anasazi** [comment]
Yeah I imagine most of my stuff disappeared with the death of the greenthread runtime.

**Pull request closed without merging**
