### PR TITLE
TEST: Check the overhead of adding another field to TyCtxt

### PR DESCRIPTION
**Pull request by Zoxc**
@bors try

### CODE REVIEW

**Comment by Zoxc** [comment]
@Mark-Simulacrum A perf run is required :)

**Comment by Mark-Simulacrum** [comment]
Perf run queued.

**Comment by Zoxc** [comment]
Result: http://perf.rust-lang.org/compare.html?start=02b4d3ddfb7cd9f1caf8ed90f18f8e798a1f4b05&end=4a413faffd06a4ebff0b2281e7f2f8138eab22a1&stat=instructions%3Au

**Pull request closed without merging**
