### PR TITLE
Use `DisplayBuffer` for socket addresses.

### PR DESCRIPTION
**Pull request by reitermarkus**
Continuation of https://github.com/rust-lang/rust/pull/100625 for socket addresses.

Renames `net::addr` to `net::addr::socket`, `net::ip` to `net::addr::ip` and `net::ip::display_buffer::IpDisplayBuffer` to `net::addr::display_buffer::DisplayBuffer`.

### CODE REVIEW

**Comment by thomcc** [comment]
Can you add tests covering long addresses? E.g. ones that would catch an issue if the length used by the `DisplayBuffer`s were wrong? It doesn't seem like we have these.

---

Also, to be clear (since it's not clear from the PR description), none of the renamed things are public API, this modifies internal stuff only.

That said, the renames are probably not that well motivated (since `DisplayBuffer` is plausibly more broadly useful than just here, and if we moved it elsewhere the module structure here would be slightly goofy), but I don't think it matters that much.

**Comment by reitermarkus** [comment]
I added some tests for short and long addresses.

> the renames are probably not that well motivated

> the module structure here would be slightly goofy

I think `addr::socket::SocketAddr` and `addr::ip::IpAddr` makes more sense than `addr::SocketAddr` and `ip::IpAddr`.

I guess it would also make sense for `parser` to be in `addr::parser` instead.

**Comment by thomcc** [comment]
I'm not sure this level of nesting helps?

**Comment by reitermarkus** [comment]
> I'm not sure this level of nesting helps?

How do you suggest to structure this?

**Comment by thomcc** [comment]
> How do you suggest to structure this?

I think what you had initially was probably better, but honestly I think just the changes so that DisplayBuffer is used for the parsing would be fine.

**Comment by reitermarkus** [comment]
I flattened the module structure again, but did rename `addr` to `socket_addr` and `ip` to `ip_addr` so the names are more symmetric.

**Comment by thomcc** [comment]
Thank you. This looks great. Will approve after CI goes green.

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/101148) 

@bors r-

**Comment by reitermarkus** [comment]
Rebased this, @thomcc and @Dylan-DPC.

**Comment by reitermarkus** [comment]
Seems like the rollup is failing again with the same error. I have no idea how the changes here relate to the failing test.

**Comment by Dylan-DPC** [comment]
failed in CI of https://github.com/rust-lang/rust/pull/101262

**Comment by reitermarkus** [comment]
@thomcc, can you have another look here? 

I fixed the clippy problem due to the changed path. Should I submit this to the clippy repo instead?

**Comment by thomcc** [comment]
No, but I need someone from the clippy team to say if those changes are fine.

**Comment by Jarcho** [comment]
Is there a reason for not just changing the paths in clippy? It's not likely to happen with this, but when large changes occur both here and in clippy it can make syncs a pain.

**Comment by reitermarkus** [comment]
> Is there a reason for not just changing the paths in clippy?

Well, I read

https://github.com/rust-lang/rust/blob/9a677674b3364cab71fd49793aa5cc90b9dc5322/src/tools/clippy/clippy_utils/src/paths.rs#L4-L5

Currently this is implemented so it supports both paths and diagnostic items since I didn't know if this needs to be merged into `clippy` in a backwards-compatible way. Seems like it doesn't, so this can be simplified a bit now.

**Comment by Jarcho** [comment]
As far as large changes I'm specifically referring to the new `is_pat_variant` function. It's generally better to make the smallest change on this side to keep the merging easy. Switching `match_def_path` to `is_diagnostic_item` is one thing. Adding a new helper function to merge different code paths is a whole lot more.

Anyways the clippy changes are fine once the fallback to path checking is removed. The chances of a large merge conflict here are near zero.

**Comment by thomcc** [comment]
@rustbot author

(Please use "at-rustbot ready" to reassign to me when you've made those changes, thanks)

**Comment by thomcc** [comment]
@Jarcho is this what you were looking for?

**Comment by thomcc** [comment]
I'm fine with the library portion, so I'm going to reassign to @Jarcho for the review of the clippy changes, since I have no idea what I'm looking at there.

r? @Jarcho

**Comment by Jarcho** [comment]
Clippy changes look good.

**Pull request merged**
