### PR TITLE
Add more coherence tests

### PR DESCRIPTION
**Pull request by weiznich**
I've wrote the missing test cases listed in [this google doc](https://docs.google.com/spreadsheets/d/1WlroTEXE6qxxGvEOhICkUpqguYZP9YOZEvnmEtSNtM0/edit#gid=0)

> The other thing that might be useful is to rename the existing tests so they all fit the new naming scheme we were using.

I'm not entirely sure how to do this. If everything from the google sheet is covered could I just remove the remaining tests in `src/test/ui/coherence` or is there something in there that should remain?

cc #63599 

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@weiznich thanks! you rock.

In terms of the existing tests, hmm, I feel like some of them may have covered worthy scenarios outside of the doc. I wouldn't want to remove them without review.

**Comment by Centril** [comment]
The failure in https://github.com/rust-lang/rust/pull/65550#issuecomment-543653477 may have been spurious and maybe not. Please have a look. :)

**Comment by tmandry** [comment]
Failed in https://github.com/rust-lang/rust/pull/65565#issuecomment-543930701, @bors r-

**Comment by weiznich** [comment]
Seems like the file name of the test is causing that (again :pensive:). I will fix it as soon as I'm back on my PC.

**Comment by weiznich** [comment]
@tmandry Pushed the (hopefully) the fixes

**Comment by nikomatsakis** [comment]
@bors r+ rollup

@weiznich yeah the file name convention is maybe annoying-- otoh it's so cool to be able to read the test purpose out of the directory listing...

**Pull request merged**
