### PR TITLE
tools: Update rustfmt and re-enable testing

### PR DESCRIPTION
**Pull request by DSpeckhals**
This allows rustfmt and the RLS to test and compile again.

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+ p=1

Thanks!

**Comment by kennytm** [comment]
Legit error. rustfmt needs to be updated again.

```
error[E0004]: non-exhaustive patterns: `Ty` not covered
    --> src\tools\rustfmt\src\items.rs:2714:30
     |
2714 |         let item_str = match self.node {
     |                              ^^^^^^^^^ pattern `Ty` not covered
error: aborting due to previous error
error: Could not compile `rustfmt-nightly`.

```

**Comment by DSpeckhals** [comment]
I will see if I can get rustfmt and then the submodule fixed within the next several hours.

**Comment by DSpeckhals** [comment]
This should be ready again. @nrc just merged https://github.com/rust-lang-nursery/rustfmt/commit/96566276e3ed0bfcdc4816ec6c90307a4569cfb7, which covers the non-exhaustive pattern.

**Pull request merged**
