### PR TITLE
Cleanup: move format! ui tests to where they belong

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
for the curious: apparently, `ifmt` was the code name for the "new" formatting infra many years ago.

**Review by jyn514 — APPROVED** [review]

**Comment by jonas-schievink** [comment]
r=me with rebase

**Comment by camelid** [comment]
@matklad All this needs is a rebase and then it can be merged!

**Comment by matklad** [comment]
oh wow, completely slipped my mind, thanks for the poke. I've re-applied this on top of new tree, now this just moves the files to a more logical directory

@bors r+ rollup

**Comment by camelid** [comment]
What happens if the tree is closed while a PR is being tested (like this one)? Will bors still merge it, or will it just wait for tests to finish and then stop?

**Comment by camelid** [comment]
I guess bors answered my question 😄

**Comment by RalfJung** [comment]
The tree is still closed, somehow that command did not work?
@bors treeclosed-

**Comment by mati865** [comment]
FYI bors doesn't listen on closed PRs/issues.

**Pull request merged**
