### PR TITLE
CI: fix CMake installation for 32/64 bit `dist` Linux

### PR DESCRIPTION
**Pull request by Kobzol**
Should hopefully fix LLVM 17 build (https://github.com/rust-lang/rust/pull/114048#issuecomment-1649586577).

### CODE REVIEW

**Comment by klensy** [comment]
Feels like this should fail, as cmake required cmake to build itself, bootstraping required some additional steps (https://github.com/Kitware/CMake#building-cmake), but we'll see.

**Comment by Kobzol** [comment]
The previous version of the Dockerfile didn't seem to install CMake before running the CMake script, and the installation script itself doesn't seem to use `cmake`. We'll see.

**Comment by Kobzol** [comment]
Ah, that's a good point. Still, I suppose that if `cmake` gets installed into the global directories (i.e. not into `/rustroot`, but into `usr/bin`), it should still be available. I don't think that we use an absolute path (like `/rustroot/bin/cmake`) anywhere.

**Comment by klensy** [comment]
Insert `which cmake` and `cmake --version` all around to assert which version actually used?

**Comment by klensy** [comment]
Success? https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/dist-i686-linux/Dockerfile too

**Pull request merged**
