### PR TITLE
Deprioritize fulfillment errors that come from expansions.

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes (part of?) #69455

### CODE REVIEW

**Comment by m-ou-se** [comment]
That error is the async.stderr thing.

@estebank [said](https://github.com/rust-lang/rust/issues/69455#issuecomment-1382182677):

> don't include the async.stderr file, that's an ongoing issue I've noticed, faulty test someone else is fixing

I suppose this PR is blocked until that is fixed.

**Comment by estebank** [comment]
Yeah, it doesn't seem like it would be your PR causing the error in `tests/ui/chalkify/bugs/async.rs`. I'm seeing *different* issues with that test (the output is non-deterministic across machines) though.

**Comment by compiler-errors** [comment]
Well #106793 is landed, so I think this PR is ready for a bless and r+

**Pull request merged**
