### PR TITLE
Mark "unused binding" suggestion as maybe incorrect

### LINKED ISSUE #54196: cargo fix renames unused local variables from foo to _foo
For example:

```
let device = &self.ctx.device;
let _device = &self.ctx.device;
```

I don't like that refactor because I might end up with local variables that do nothing. I think `cargo fix` should just ignore unused local variables all together.  If `cargo fix` just renames local variables to hide the warnings from the compiler, then the compiler lint is a bit pointless.

Renaming unused function parameters seems fine.

### PR DESCRIPTION
**Pull request by estebank**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/120470)*

Ignoring unused bindings should be a determination made by a human, `rustfix` shouldn't auto-apply the suggested change.

Fix rust-lang/rust#54196.

### CODE REVIEW

**Comment by cjgillot** [comment]
Should we do this with TryPrefixSugg too?

**Comment by compiler-errors** [comment]
yeah would prefer that one too

@bors r-

**Comment by estebank** [comment]
Done.

@bors r=compiler-errors

**Comment by Nadrieril** [comment]
I believe this is the cause of [this rollup failure](https://github.com/rust-lang/rust/pull/120522#issuecomment-1918839983)

**Comment by matthiaskrgr** [comment]
failed in https://github.com/rust-lang-ci/rust/actions/runs/7718718807/job/21040575445#step:26:10331 
https://github.com/rust-lang/rust/pull/120512
@bors r-

**Comment by Nadrieril** [comment]
This is failing some cargo tests. Run `./x.py test tools/cargo` to reproduce:
```
failures:

---- fix::fix_shared_cross_workspace stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo fix --allow-no-vcs`
thread 'fix::fix_shared_cross_workspace' panicked at tests/testsuite/fix.rs:1513:10:

test failed running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo fix --allow-no-vcs`
error: Expected lines did not match (ignoring order):
0   23        Checking foo v0.1.0 (/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/tmp/cit/t1329/foo/foo)
1   22        Checking bar v0.1.0 (/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/tmp/cit/t1329/foo/bar)
2        -       Fixed [..]foo/src/shared.rs (2 fixes)
3   19        Finished dev [unoptimized + debuginfo] target(s) in 0.32s
    3    +
    4    +
    5    +  |
    6    +  |
    7    +  |
    8    +  |
    9    + --> foo/src/shared.rs:1:14
    10   +warning: unused variable: `x`
    11   +warning: unused variable: `x`
    12   + --> bar/src/../../foo/src/shared.rs:1:14
    13   +1 | pub fn fixme(x: Box<&dyn Fn() -> ()>) {}
    14   +1 | pub fn fixme(x: Box<&dyn Fn() -> ()>) {}
    15   +warning: `bar` (lib test) generated 1 warning
    16   +warning: `foo` (lib test) generated 1 warning
    17   +  = note: `#[warn(unused_variables)]` on by default
    18   +  = note: `#[warn(unused_variables)]` on by default
    19   +       Fixed bar/src/../../foo/src/shared.rs (1 fix)
    20   +warning: `foo` (lib) generated 1 warning (1 duplicate)
    21   +warning: `bar` (lib) generated 1 warning (1 duplicate)
    22   +  |              ^ help: if this is intentional, prefix it with an underscore: `_x`
    23   +  |              ^ help: if this is intentional, prefix it with an underscore: `_x`



---- messages::deduplicate_messages_basic stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo test --no-run -j1`
thread 'messages::deduplicate_messages_basic' panicked at tests/testsuite/messages.rs:72:10:

test failed running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo test --no-run -j1`
error: stderr did not match:
1   1        Compiling foo [..]
2   2     warning: unused variable: `x`
3   3      --> src/lib.rs:3:25
4   4       |
5   5     3 |                     let x = 1;
6   6       |                         ^ help: if this is intentional, prefix it with an underscore: `_x`
7   7       |
8   8       = note: `#[warn(unused_variables)]` on by default
9   9     
10       -warning: `foo` (lib) generated 1 warning (run `cargo fix --lib -p foo` to apply 1 suggestion)
    10   +warning: `foo` (lib) generated 1 warning
11  11    warning: `foo` (lib test) generated 1 warning (1 duplicate)
12  12        Finished [..]
13  13      Executable unittests src/lib.rs (target/debug/deps/foo-[..])


other output:



---- messages::deduplicate_messages_mismatched_warnings stdout ----
[1m[31merror[0m[1m:[0m test failed, to rerun pass `--test testsuite`
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo test --no-run -j1`
thread 'messages::deduplicate_messages_mismatched_warnings' panicked at tests/testsuite/messages.rs:116:10:

test failed running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo test --no-run -j1`
error: stderr did not match:
1   1        Compiling foo v0.0.1 [..]
2   2     warning: unused variable: `x`
3   3      --> src/lib.rs:3:25
4   4       |
5   5     3 |                     let x = 1;
6   6       |                         ^ help: if this is intentional, prefix it with an underscore: `_x`
7   7       |
8   8       = note: `#[warn(unused_variables)]` on by default
9   9     
10       -warning: `foo` (lib) generated 1 warning (run `cargo fix --lib -p foo` to apply 1 suggestion)
    10   +warning: `foo` (lib) generated 1 warning
11  11    warning: variable `MY_VALUE` should have a snake case name
12  12     --> src/lib.rs:8:25
13  13      |
14  14    8 |                     let MY_VALUE = 1;
15  15      |                         ^^^^^^^^ help: convert the identifier to snake case: `my_value`
16  16      |
17  17      = note: `#[warn(non_snake_case)]` on by default
18  18    
19  19    warning: `foo` (lib test) generated 2 warnings (1 duplicate)
20  20        Finished [..]
21  21      Executable unittests src/lib.rs (target/debug/deps/foo-[..])


other output:




failures:
    fix::fix_shared_cross_workspace
    messages::deduplicate_messages_basic
    messages::deduplicate_messages_mismatched_warnings

test result: FAILED. 3020 passed; 3 failed; 178 ignored; 0 measured; 0 filtered out; finished in 286.95s
```

@bors r-
@rustbot author

**Comment by estebank** [comment]
Just looked into this. This is inconvenient. I found the test changes that I need to make, but I would have to land a disabling of the tests in the cargo repo, then update the cargo remote, merge this, and then reenable the tests, right?

**Comment by Nadrieril** [comment]
Can't you commit the cargo changes in this PR directly? That's how we do it with clippy and rust-analyzer.

**Comment by estebank** [comment]
@Nadrieril clippy and rust-analyzer both live in repo and get merged, while cargo is a sub-repo, so commits to it need to be upstreamed first. Thankfully, @weihanglo is on the case and already merged [my test changes to the cargo repo](https://github.com/rust-lang/cargo/pull/13382) and has a [PR up to update the subrepo](https://github.com/rust-lang/rust/pull/120508), so this PR shouldn't linger for too long.

**Comment by estebank** [comment]
I think `__CARGO_FIX_YOLO="yolo" cargo fix` would do what you want, @connortsui20. The proper place to discuss this is https://github.com/rust-lang/cargo/issues/13028.

**Pull request merged**
