### PR TITLE
Delete unstable deprecated APIs

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Removes std_unicode, char::decode_utf8, ptr::offset_to, io::Read::chars.

These were all deprecated at least 6 weeks ago I believe so seems like it's time to delete them.

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r- 

[distcheck failed](https://github.com/rust-lang/rust/pull/52844#issuecomment-408736832).

```
[00:11:11] Dist src
[00:11:11] thread 'main' panicked at 'could not read dir "/checkout/src/libstd_unicode": Os { code: 2, kind: NotFound, message: "No such file or directory" }', bootstrap/lib.rs:1248:25
```

**Comment by SimonSapin** [comment]
This might be identical to https://github.com/rust-lang/rust/pull/52732.

**Comment by SimonSapin** [comment]
Ah no, #52732 also removes deprecated `AsciiExt` methods.

**Comment by Mark-Simulacrum** [comment]
Oh, sorry, missed that -- want to rebase and approve that PR?

**Comment by SimonSapin** [comment]
Done. Bors acknowledged https://github.com/rust-lang/rust/pull/52732#issuecomment-408923429 but it seems the homu queue didn’t get the memo…

**Pull request closed without merging**
