### PR TITLE
Document that `OsString` and `OsStr` are bytes; provide conversions to bytes

### PR DESCRIPTION
**Pull request by joshtriplett**
The `OsString` and `OsStr` types are wrappers around bytes, and are *required* by existing stable APIs to be byte-based encodings that are supersets of UTF-8 (since a `&str` can become an `&OsStr` without allocation). However, both types are opaque, and do not provide access to raw bytes, primarily because on Windows they use the WTF-8 encoding, the standard for which recommends against exposing it.

Nonetheless, many crates *do* rely on `OsStr` and `OsString` being bytes. We already provide the `OsStrExt` and `OsStringExt` extension traits, [which get used reasonably widely](https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Arust+%2Fuse+std%3A%3Aos%3A%3Aunix.*OsStrExt%2F) despite being non-portable. And the [`os_str_bytes`](https://crates.io/crates/os_str_bytes) crate has millions of downloads, and tens of thousands of new downloads everyday.

This PR is an effort to seek consensus for making the contents of an `OsStr` or `OsString` available as bytes, inspired by recent discussions within the libs-api team.

This is a *minimal* PR to acheive that goal. This PR consists almost entirely of documentation, updating the module documentation in `std::ffi` and the type documentation on `OsString`. This PR only adds two methods: `OsStr::as_bytes` and `OsString::into_vec`, and plumbs those methods down to the existing implementations for both UNIX and Windows. Both methods are unstable (and I'll file a tracking issue for them as soon as I take this PR out of draft status).

In particular, this PR does *not* add any new `From` or `TryFrom` or `Into` or `TryInto` impls, nor does it add methods to construct `OsStr` or `OsString` from bytes (which would require error handling), nor does it attempt to do any further unification of implementations between Windows and UNIX, nor does it extend these types to have more of the functionality of [bstr](https://docs.rs/bstr/latest/bstr/). All of those things could happen in potential future changes, and I'd be happy to make some of those changes myself, but I'd like to focus on the initial consensus for making the change before further work that depends on the change.

As one further note of the implications of this change: there has been a proposal to change OsStr/OsString on Windows from WTF-8 to a more complex encoding that can potentially speed up matching for use with the Pattern API. Since that proposal, we've decided to seal the Pattern API and avoid stabilizing it. I would propose that we not switch the encoding of OsStr/OsString, and proceed with exposing bytes using the current encoding. Another option would be to expose bytes but not specify the exact encoding beyond "superset of UTF-8".

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
> are required by existing stable APIs to be byte-based encodings that are supersets of UTF-8 (since a &str can become an &OsStr without allocation).

It seems like this only requires that there is some variant of OsStr that is byte-based encoded as a superset of UTF-8, right? It would be possible for OsStr to wrap something like `enum OsStrInternal { Utf8(&str), Other(???) }`, presuming we used some kind of pointer tricks or whatever that are compatible with &str's representation. (For example, Other might be encoded by moving the length of the str +isize::MAX, since such lengths aren't valid &str).

I mostly ask/note this because I want to make sure that this kind of option is explicitly mentioned in the writeup (and potentially rejected, either for complexity or infeasibility if (for example) we can't think of an encoding that will work), so that we can point back to it when thinking about this in the future.

**Comment by joshtriplett** [comment]
> > are required by existing stable APIs to be byte-based encodings that are supersets of UTF-8 (since a &str can become an &OsStr without allocation).
> 
> It seems like this only requires that there is some variant of OsStr that is byte-based encoded as a superset of UTF-8, right? It would be possible for OsStr to wrap something like `enum OsStrInternal { Utf8(&str), Other(???) }`, presuming we used some kind of pointer tricks or whatever that are compatible with &str's representation to encode the state -- i.e., not actually an enum. (For example, Other might be encoded by moving the length of the str +isize::MAX, since such lengths aren't valid &str).
> 
> I mostly ask/note this because I want to make sure that this kind of option is explicitly mentioned in the writeup (and potentially rejected, either for complexity or infeasibility if (for example) we can't think of an encoding that will work), so that we can point back to it when thinking about this in the future.

Fair enough; strictly speaking, the requirement would be that `OsStr` must be a superset of a UTF-8 `str`, which is not quite the same as saying that the bytes must be a superset of UTF-8. I think in practice the documentation should not actually make that distinction as it would be confusing to the reader, but libs-api should absolutely allow for that possibility when considering options.

We could, for example, use some encoding that has a second variant for a native `[u16]` on Windows. I don't think we *should* do that here, even though we might be able to.

**Comment by dylni** [comment]
> And the [`os_str_bytes`](https://crates.io/crates/os_str_bytes) crate has millions of downloads, and tens of thousands of new downloads everyday.

Note that this crate doesn't rely on the internal representation at all. It [decodes the encoded `u16` bytes](
https://github.com/dylni/os_str_bytes/blob/e61fb11c7fb89d71efe0744f3c9d49523c277806/src/windows/mod.rs#L71-L77) from [`OsStrExt::encode_wide`](https://doc.rust-lang.org/std/os/windows/ffi/trait.OsStrExt.html#tymethod.encode_wide). So, this crate would not make sense to be a reason that the internal encoding could not change. However, the current libstd API does only allow limited changes.

Also, the preferred way to use the crate is to use [`RawOsStr`](https://docs.rs/os_str_bytes/6.0.0/os_str_bytes/struct.RawOsStr.html) and [`RawOsString`](https://docs.rs/os_str_bytes/6.0.0/os_str_bytes/struct.RawOsString.html), which make it rare to need the raw bytes. For example, [clap](https://crates.io/crates/clap) only uses those structs.

I think this PR would still be a good idea, since many people rely on the representation anyway. However, I wanted to clarify those points.

> on Windows they use the WTF-8 encoding, the standard for which recommends against exposing it.

One option would be to do the same as os\_str\_bytes and [document limited invariants](https://docs.rs/os_str_bytes/6.0.0/os_str_bytes/#encoding) about the encoding. This would allow many of the same changes that could be made now to the internal representation.

**Comment by dylni** [comment]
There is one problem if this PR gets merged and starts getting used. Without a wrapper, it becomes very easy to mix WTF-8 and UTF-8 bytes. For searching and concatenation, that would be a problem, since both need special handling of WTF-8 bytes.

**Comment by joshtriplett** [comment]
> One option would be to do the same as os_str_bytes and [document limited invariants](https://docs.rs/os_str_bytes/6.0.0/os_str_bytes/#encoding) about the encoding.

I have no objections to documenting a lesser guarantee and making the encoding less specified.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/95706 has landed, so https://github.com/rust-lang/rust/pull/95290/commits/af7b7da80e7a7d691f7376662b34ac4d5e9420d0 should no longer be necessary.

**Comment by epage** [comment]
> In particular, this PR does not add any new From or TryFrom or Into or TryInto impls, nor does it add methods to construct OsStr or OsString from bytes (which would require error handling), nor does it attempt to do any further unification of implementations between Windows and UNIX, nor does it extend these types to have more of the functionality of [bstr](https://docs.rs/bstr/latest/bstr/). All of those things could happen in potential future changes, and I'd be happy to make some of those changes myself, but I'd like to focus on the initial consensus for making the change before further work that depends on the change.

I appreciate the progress on this and recognize that other crates can benefit from this but I figure it'd be worth documenting where this is deficient for at least one use case, clap.  At a high level, clap needs
- `starts_with` which we emulate with this PR at the byte-slice level
- `strip_prefix` which can't be emulated
- `split_once` which can't be emulated

There are a couple of ways to unblock clap:
- Pattern API, see #49802 (for which this PR wouldn't be needed) 
- Construct `OsStr` from bytes
  - Emulate Pattern API by dropping to bytes, do processing, and convert back
- Slicing support (a subset of #49802)
  - Emulate Pattern API by dropping to bytes, get needed indices, and then slice the original `OsStr`

If there is anything I can do to help move along any of the parts to unblock clap, let me know!

**Comment by BurntSushi** [comment]
cc @SimonSapin whom I know I've spoken to about this very topic a few times over the years.

**Comment by BurntSushi** [comment]
So speaking for me personally, I've desperately wanted the ability to get the raw bytes of a `OsStr` for a long time now. My main use case is executing regexes/globs on file paths. For such things, creating a new copy of the path or even just doing a simple UTF-8 check can end up being a perf pessimization. So what I ended up doing was creating a suite of routines in the `bstr` crate that almost get me home: https://docs.rs/bstr/latest/bstr/#file-paths-and-os-strings. Namely, on Unix, they are free. But on Windows, they only give me bytes if it's valid UTF-8 underneath. In practice, this does result in a perf hit on Windows _and_ a correctness problem. But on Windows, invalid UTF-16 file paths appear to be incredibly rare.

Now speaking as a libs-api member, I am a bit more cautious about this. I think overall, there are generally two reasons for caution here:

Firstly, WTF-8 is not intended to actually be stored anywhere. The [WTF-8 spec calls this out in its introductory text in no uncertain terms](https://simonsapin.github.io/wtf-8/):

> [WTF-8](https://simonsapin.github.io/wtf-8/#wtf-8) is a hack intended to be used internally in self-contained systems with components that need to support [potentially ill-formed UTF-16](https://simonsapin.github.io/wtf-8/#potentially-ill-formed-utf-16) for legacy reasons.
>
> Any [WTF-8](https://simonsapin.github.io/wtf-8/#wtf-8) data must be converted to a [Unicode](https://simonsapin.github.io/wtf-8/#unicode-text) encoding at the system’s boundary before being emitted. [UTF-8](https://simonsapin.github.io/wtf-8/#utf-8) is recommended. [WTF-8](https://simonsapin.github.io/wtf-8/#wtf-8) must not be used to represent text in a file format or for transmission over the Internet.
>
> In particular, the [Encoding Standard](https://encoding.spec.whatwg.org/) [[ENCODING]](https://simonsapin.github.io/wtf-8/#biblio-encoding) defines [UTF-8](https://simonsapin.github.io/wtf-8/#utf-8) and other encodings for the Web. There is no and will not be any[ encoding label](https://encoding.spec.whatwg.org/#names-and-labels) [[ENCODING]](https://simonsapin.github.io/wtf-8/#biblio-encoding) or[ IANA charset alias](http://www.iana.org/assignments/character-sets/character-sets.xhtml) [[CHARSETS]](https://simonsapin.github.io/wtf-8/#biblio-charsets) for [WTF-8](https://simonsapin.github.io/wtf-8/#wtf-8).

My suspicion is that if we add a `as_bytes()` routine that is easy to call and works on all platforms, then it won't be long before people start using that routine for serialization purposes via something like Serde. At that point, we'll start seeing WTF-8 encoded data on disk. Today, the APIs make this quite unlikely and difficult to do. You'd have to actually implement your own WTF-8 encoder to do it.

Now is this a show stopping problem? I don't know. But I think if we do expose `as_bytes()` like this PR proposes, then we should be clear eyed about this. IMO, this will start us down the path of creating the problem that is "serialized WTF-8." Now, how much of a problem is that in practice? I'm not quite sure. But it's definitely a problem that I don't think folks have today.

The second reason to be cautious here has been more explicitly addressed. Namely, by exposing the internal representation, we limit our ability to maneuver in the future. @joshtriplett mentions that we've sealed the `Pattern` trait, but I think this just means that we won't try to expose that trait such that others can implement it. I don't think it means that we won't implement it for other types. `OsStr{ing}` is quite annoying to work with, so I could imagine doing this some day. And if we do, are we going to want to change the representation?

We could mitigate the second reason by declaring that the encoding is "unspecified." But again, there is the practical reality that if we leave the encoding as WTF-8 for long enough, code will grow to depend on it and it will, _in practice_, be difficult or impossible for us to change.

Like I said, personally, I am quite excited about this change. But with my libs-api hat on, I do have some concerns. I think part of the issue here is just making sure we are clear eyed about the cons that go into exposing an `as_bytes()` routine and committing that we are indeed okay with them given the benefits of exposing the internal representation.

**Comment by JanBeh** [comment]
Note that `str` implements `AsRef<OsStr>`, thus an `OsStr` must not just be a superset of `str` but valid `str`s must also be *encoded* in the same way when cheaply transformed to an `OsStr` via [`AsRef::as_ref`](https://doc.rust-lang.org/std/convert/trait.AsRef.html#tymethod.as_ref). This is contradictory to the current documentation of [`OsStr`](https://doc.rust-lang.org/std/ffi/struct.OsStr.html):

> This type represents a borrowed reference to a string in the operating system’s preferred representation.

So in either case, `OsStr`'s documentation should be fixed, because `OsStr` cannot represent a string in the operating system's preferred representation (unless it's a superset of `str` and encoded in the same way for all valid `str`s).

**Comment by SimonSapin** [comment]
Yes, the encoding / memory representation must be a super-set of UTF-8, not just the set of possible values.

And yes, that bit of doc should probably be changed to refer to the set of value instead of the OS’s preferred (memory) representation, which on Windows is WTF-16.

**Comment by SimonSapin** [comment]
> I would propose that we not switch the encoding of OsStr/OsString, and proceed with exposing bytes using the current encoding.

This is contrary to [RFC 2295](https://rust-lang.github.io/rfcs/2295-os-str-pattern.html). Is there a process to retract a previously-accepted RFC?

> Another option would be to expose bytes but not specify the exact encoding beyond "superset of UTF-8".

If (type) conversion to bytes is added, I’d expect conversion from bytes to come soon after. At that point the encoding is de-facto stable as people will start doing things that will break if we ever change the encoding. Documentation saying not to rely on details of the encoding is only a very weak protection against people doing it, knowingly or not.

----

I wrote up the WTF-8 specification with mixed feelings. It’s a neat trick to work around some specific problems (and if using it having a proper definition is good). But I wish these problems did not exist in the first place. They only do because of compatibility constraints with existing systems that adopted a 16-bit design made at a time when, arguably, we didn’t know better.

My fear is that WTF-8 itself could become such a problem, and make the world of programming a little worse for many people. If WTF-8 strings end up stored or transmitted, whether knowingly or not, then some day some other program might need to add hacks for compatibility with whatever emitted them.

It’s in an attempt to avoid this that I unilaterally added this “must not be used to represent text in a file format or for transmission over the Internet” bit to the WTF-8 spec, as quoted by @BurntSushi above. I suspect this will happen sooner or later if `OsStr` exposes conversion with WTF-8 bytes. That said, I acknowledge the tension with the real constraints on some valid use cases imposed by `OsStr` being opaque. And if it only leads to widespread use of the `os_str_bytes` crate, the end result is not so different since as far as I can tell it also exposes WTF-8 bytes on Windows (though with worse performance since it goes through WTF-16 with `OsStrExt::encode_wide`).

Ultimately though I only have so much power over other people’s decisions. Going against a “must” in the IETF RFC 2119 sense only means not conforming to a specification. At times, there may be reasons for a [willful violation](https://infra.spec.whatwg.org/#willful-violation) of a specification. I’ll leave to the team to decide if this is the case here.

**Comment by sunfishcode** [comment]
> And the [os_str_bytes](https://crates.io/crates/os_str_bytes) crate has millions of downloads, and tens of thousands of new downloads everyday.

Looking at the numbers, a big part of this popularity is that os_str_bytes is used in clap, which is popular. And from the discussion above:

> At a high level, clap needs
>     * `starts_with` which we emulate with this PR at the byte-slice level
>     * `strip_prefix` which can't be emulated
>     * `split_once` which can't be emulated

And in addition to clap:
 - argfile is os_str_bytes' next most popular user, and at a quick scan it also appears to just need `strip_prefix`.
 - At least some users of `OsStrExt`/`OsStringExt` also effectively just need `starts`/`ends_with` and `strip_prefix`/`suffix`. This is the case for cap-std, for example.

So, a first, step here could be to add `starts_with`, `ends_with`, `strip_prefix`, and `strip_suffix` methods to `OsStr`. This would seem to address many of the use cases here, without exposing `OsStr`'s internal encoding, at least any more than that it's a superset of UTF-8, which is already exposed.

It wouldn't address everything, such as @BurntSushi's use case above, but it wouldn't preclude other approaches either. `starts`/`ends_with` and `strip_prefix`/`suffix` will likely always be the most ergonomic for the use cases that need them.

**Comment by joshtriplett** [comment]
@sunfishcode One of many reasons I'd like to add this PR is to allow clap and other tools like it to reliably use bytes for argument handling and conversion to whatever type they want (whether path or integer or anything else).

**Comment by epage** [comment]
Benefits for clap dropping `os_str_bytes`
- Reduced third-party dependencies for faster builds
- Reduction in unsafe in third-party code

This would also make it easier for alternatives to clap to crop up.
- Missing OsStr support is a common mistake when writing an argument parser.
- When it is supported, its usually in limited ways (e.g. not allowing `--arg=osstr`).
- In lexopt's case, its because they re-implemented what they needed from `os_str_bytes`, I'm assuming to meet a goal of zero dependencies" 
- When writing `clap_lex`, I also found dealing the hybrid lifetimes of `Cow<RawOsStr>` a pain to deal with, creating a worse API, and possibly impacting performance (can't remember all the details of the problems I ran into)

**Comment by BurntSushi** [comment]
> * In lexopt's case, its because they re-implemented what they needed from `os_str_bytes`, I'm assuming to meet a goal of zero dependencies"

I think you're referring to this bit, right? https://github.com/blyxxyz/lexopt/blob/0bfd88145236308e76157fa782cef8dd5429e41c/src/lib.rs#L307-L330

It looks like it doesn't need to re-roll WTF-8 and it isn't _too_ bad overall. It does seem to handle the case of `--flag={not-unicode}` correctly anyway.

**Comment by BurntSushi** [comment]
@sunfishcode As I mentioned above, it's common to want to run a regex or a glob on a file path. You can't do that today in a cross platform way without taking either a performance hit or a correctness hit (usually on Windows).

**Comment by sunfishcode** [comment]
@BurntSushi Ineded; when I [mentioned](https://github.com/rust-lang/rust/pull/95290#issuecomment-1115032120) that above, @joshtriplett [replied](https://github.com/rust-lang/rust/pull/95290#issuecomment-1115039188) that there are additional use cases beyond that, and I'm interested in learning more about them.

**Comment by BurntSushi** [comment]
@sunfishcode Oh sorry, my bad! Misunderstood.

**Comment by joshtriplett** [comment]
Following up on this, with some more concrete examples:

@sunfishcode wrote:
> @joshtriplett Could you say more about those other use cases?

Sure. Concretely, as one of many use cases, I'm doing argument parsing (in one case with clap, in another case by hand), of arguments that may be several different things, that may or may not be UTF-8, and that may or may not contain filenames, and then in some of those cases I need to send the bytes over a stream of bytes as part of a larger structure.

Also, more generally, I don't think it's sufficient to just provide specialized APIs on a case-by-case basis. I think we need to support people doing *arbitrary* things we didn't anticipate, using command-line arguments, environment variables, and similar. I'm not asking for specific APIs; I'm asking for bytes, that I can feed into tools and libraries that expect bytes.

I would *also*, separately, love to have the functionality of bstr in the standard library. But that's for another day.

> Specifically, are there situations where users are passing command-line arguments or setting environment variables with strings that:
> 
>     * aren't UTF-8 or UTF-16,

:heavy_check_mark: I need to parse and handle things that may or may not be Unicode.

>     * aren't text in an encoding not related to Unicode (since `OsStr` holds a superset of UTF-8),

:heavy_check_mark: They may be ASCII-superset, or they may be arbitrary-filename-encoding, and I don't know in advance which one.

>     * are relevant in cross-platform codebases (since Unix-specific codebases can just do `OsStrExt` and get the bytes),

:heavy_check_mark: Yes, I'm doing this in a portable command-line tool that also needs to run on Windows. A big reason I'm asking for this is to *stop* using `OsStrExt` and making code less portable. `OsStrExt`/`OsStringExt` are currently the *only* non-portable APIs I can't currently avoid using.

>     * aren't filesystem paths, or strings containing filesystem paths (eg. "--input=/some/path") (since these can usually be handled with specialized APIs),

:heavy_check_mark: They're not guaranteed to be filesystem paths, and if they *are* filesystem paths they might not be filesystem paths for the same OS the application is running on.

(I *also* plan to provide ways for the tool I'm building to support escape sequences, to allow Windows users to handle UNIX paths. But I'd like all platforms to be able to handle their own native paths as well as Unicode paths, and UNIX able to handle all paths, without having non-portable code.)

In particular, I would like to object to the notion that it's enough to just provide APIs and keep the type opaque, rather than providing bytes so that people can build arbitrary things atop that.

>     * aren't arbitrary byte sequences (since not all byte values can be passed through), and

:heavy_check_mark: On UNIX I care that they can be arbitrary byte sequences. On Windows, it's fine that they can only be Unicode-superset. But either way I need to work with them as bytes, and I don't want to have to write separate UNIX and Windows codepaths for a fundamentally portable operation.

>     * are common enough or performance-critical enough to be worth putting in the standard library?
> 
> Or, am I thinking about this too narrowly?

We currently only provide two ways to get command-line arguments and environment variables: you can get UTF-8 and panic if it isn't Unicode, or you can get an opaque OsStr. You can't just get bytes. I don't think this is *just* a performance issue, this is a correctness issue. People can't, today, build portable APIs that process arguments (environment variables, etc) as bytes.

**Comment by epage** [comment]
I wanted to clarify my earlier comments about the needs from clap.

While this RFC is making progress towards helping clap, it is not yet sufficient to help clap as we need to support converting back into `OsStr` / `OsString`.  `clap` currently uses a subset of the recreation of the Pattern API.  I gave calls from the implementation at that time to discuss what functionality is needed to unblock clap (e.g. converting back to `OsStr` or full pattern API or slicing `OsStr`s) but what exact Pattern API functions depend on the implementation which is always in flux.

For now, access to functionality as flexible as the full Pattern API is sufficient for `clap`, (whether we have the API directly or are working with lower level primitives) **but** it gets awkward when extending to other use cases, like `clap_complete` or `argfile`.  Being able to write algorithms independent of `str`, `[u8]`, or `OsStr` would be a big help for reducing duplicated efforts and bugs.  `clap_complete` provides shell completions and we are exploring doing the processing in Rust, instead of duplicating it within each shell and dealing with opaque APIs and arbitrary escaping (implementation on this started after my last comment).  The way we interact with the shell is still in flux and one of the options is for us to get a shell-quoted string that we have to manually split.  This would require a crate like `shlex`.  We could go through and re-implement all of `shlex`s parsing logic based on only what the Pattern API provides but more ideally we would have access to just a byte stream which gives us more implementation flexibility (hand parser, nom, etc) while sharing the implementation between different input types.  `argfile` allows loading arguments from a file with `@path` syntax and we want to parse files in the Response file format which means Windows quoting rules.  I want to be able to use `wildcard` with any encoding on but it is coupled to UTF-16 atm.  If they instead converted from UTF-16 to bytes and then did the processing, the algorithm could be shared across all of the potential input sources like with `shlex`.

Frankly, there have been several times in the last month where I've been tempted to transmute `&OsStr` to `&[u8]`, knowing the types are compatible and that I would not be storing it at-rest so the likelihood that I'd be broken is negligible.  The only thing that held me back is concern over people being overly dogmatic over the use of `unsafe`.

**Comment by QuineDot** [comment]
If we're going to get `split_once` (and `rsplit_once`), even without exposing WTF-8 bytes, I think there needs to be a decision on what you can split on.  Presumably you can at least split on a `str` or `char`.  If you can also split on an `OsStr`, then you'll have to deal with potentially splitting a surrogate-pair-sized value in half (e.g. as discussed in [the RFC.](https://github.com/rust-lang/rfcs/pull/2295)).

Once you have `split_once` (and `rsplit_once`) for `char`, you can (painfully) build up arbitrary range splicing (ala `str::get`) at Unicode boundaries using safe code.  I.e., no additional guarantees or information is exposed.  This is a subset of what is in the RFC that would also be nice to have built-in instead.  And/or similarly,
* Iterators over something like `Either<&str, NonUnicodeValue>` or `Either<&str, &OsStr>`
* Something like `CharIndices` but also with a non-unicode variant
* etc

**Comment by camelid** [comment]
ping from triage: what's the status of this PR?

**Comment by mortie** [comment]
I'm very interested in the status of this. I currently use unsafe mem::transmute calls (inspired by Clap) in my command line parsing function, and I frankly don't think it's acceptable that correct argument handling (whether it's options parsing or the only uses people have mentioned here) is impossible in portable and safe rust. Has there been any progress?

**Comment by epage** [comment]
@mortie #109698 is under discussion, focusing on codifying that its proper to use `transmute`

**Review by dtolnay — COMMENTED** [review]
I believe this has been superseded by https://github.com/rust-lang/rust/pull/109698.

**Pull request closed without merging**
