### PR TITLE
Update cargo

### LINKED ISSUE #44237: Rustdoc unit tests not being run by Rustbuild
As far as we could tell.

Currently, running `cargo test` in src/librustdoc seems to work, but there are some failures:

```
   Doc-tests rustdoc

running 3 tests
test clean/simplify.rs - clean::simplify (line 24) ... FAILED
test clean/simplify.rs - clean::simplify (line 20) ... FAILED
test html/markdown.rs - html::markdown (line 18) ... FAILED

failures:

---- clean/simplify.rs - clean::simplify (line 24) stdout ----
	error: expected expression, found keyword `where`
 --> clean/simplify.rs:2:1
  |
2 | where T: Trait, <T as Trait>::Foo = Bar
  | ^^^^^

thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12

---- clean/simplify.rs - clean::simplify (line 20) stdout ----
	error: expected expression, found keyword `where`
 --> clean/simplify.rs:2:1
  |
2 | where T: Trait<Foo=Bar>
  | ^^^^^

thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- html/markdown.rs - html::markdown (line 18) stdout ----
	error[E0061]: this function takes 2 parameters but 1 parameter was supplied
 --> html/markdown.rs:6:35
  |
6 | let html = format!("{}", Markdown(s));
  |                                   ^ expected 2 parameters

thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12


failures:
    clean/simplify.rs - clean::simplify (line 20)
    clean/simplify.rs - clean::simplify (line 24)
    html/markdown.rs - html::markdown (line 18)

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out
```

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This includes https://github.com/rust-lang/cargo/pull/4447 which fixes a bug in Cargo that is needed to fix https://github.com/rust-lang/rust/issues/44237.

r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@alexcrichton Beta-nominating: As far as I can tell, this fixes the problem I encountered when attempting to re-enable testing for librustdoc. We need to update cargo on beta for those tests to be run.

**Comment by alexcrichton** [comment]
I'm going to de-nominate from beta as this wasn't required to get rustdoc tests running

**Pull request merged**
