### PR TITLE
Use `mimalloc` as `global_allocator` for `rustc_driver`

### PR DESCRIPTION
**Pull request by Zoxc**
This changes the Rust global allocator for `rustc_driver` to `mimalloc`, leaving LLVM unaffected.

Based on https://github.com/rust-lang/rust/pull/122362.

### CODE REVIEW

**Comment by lqd** [comment]
Has anything changed since we last evaluated `mimalloc` and decided we wouldn't use it over `jemalloc` on linux?

**Comment by Zoxc** [comment]
I'd like to see the memory use of a mimalloc + jemalloc mix.

**Comment by lqd** [comment]
Ok then we can wait another hour for #122362's results in case there's an issue there, and then trigger a run for this PR.

In the meantime, @bors try.

**Comment by lqd** [comment]
Ok then we can wait another hour for #122362's results in case there's an issue there, and then trigger a run for this PR. I'm not sure what code will get mimalloc vs get jemalloc's symbol overrides (if any) but we'll see.

In the meantime: 

@bors try

**Comment by lqd** [comment]
@rust-timer build 7c1e66778214e445126667614fe1d6a72eb7d2ea

**Pull request closed without merging**
