### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #72714 (Fix debug assertion in typeck)
 - #73197 (Impl Default for ranges)
 - #73323 (wf: check foreign fn decls for well-formedness)
 - #74051 (disallow non-static lifetimes in const generics)
 - #74376 (test caching opt_const_param_of on disc)
 - #74501 (Ayu theme: Use different background color for Run button)
 - #74505 (Fix search input focus in ayu theme)
 - #74522 (Update sanitizer docs)
 - #74546 (Fix duplicate maybe_uninit_extra attribute)
 - #74552 (Stabilize TAU constant.)
 - #74555 (Improve "important traits" popup display on mobile)
 - #74557 (Fix an ICE on an invalid `binding @ ...` in a tuple struct pattern)
 - #74561 (update backtrace-rs)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors retry

toolstate permission denied cc @Mark-Simulacrum 

```
2020-07-20T20:11:28.5526361Z [master 4353d43] (linux CI update)
2020-07-20T20:11:28.5526853Z  1 file changed, 1 insertion(+)
2020-07-20T20:11:32.0799579Z To https://github.com/pietroalbini/rust-toolstate
2020-07-20T20:11:32.0800179Z  ! [remote rejected] master -> master (permission denied)
2020-07-20T20:11:32.0800694Z error: failed to push some refs to 'https://github.com/pietroalbini/rust-toolstate'
```

**Comment by Mark-Simulacrum** [comment]
@bors retry

I suspect we need https://github.com/rust-lang/rust/pull/74565 to land first before this, right? @pietroalbini -- do you know? My assumption is that if we've switched tokens in the UI and that's leading to problems here or so.

**Comment by pietroalbini** [comment]
@Mark-Simulacrum I should have hopefully granted the right permissions.

**Pull request merged**
