### PR TITLE
Tweak confusable idents checking

### PR DESCRIPTION
**Pull request by nnethercote**
The confusable idents checking does some sub-optimal things with symbols.

r? @petrochenkov 
cc @crlf0710

### CODE REVIEW

**Comment by nnethercote** [comment]
These two commits are the first two commits from #74554.

**Comment by petrochenkov** [comment]
Actually, @bors r-.
The non-ASCII ident lints (which are now enabled by default) caused perf regressions, and a lot of this `CowBoxSymStr` stuff was done with intention to make them faster.
I'm not sure how much those intentions corresponded to reality, but it still would be prudent to run this through perf.

**Comment by Mark-Simulacrum** [comment]
NonAsciiIdents is still allow by default I think, but some of the other lints like confusable idents are not. Regardless this seems perf-neutral or a slight improvement, even, so @bors r=petrochenkov

**Pull request merged**
