### PR TITLE
Fix docblock code display on mobile

### LINKED ISSUE #89618: `<code>` in docblocks should use "work-wrap" CSS rule
Otherwise, if too long we can't read them:

Screenshot from 2021-10-07 12-01-37

With `word-wrap` rule:

Screenshot from 2021-10-07 12-03-21

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/89618.

Before:

Screenshot from 2021-10-07 12-01-37

After:

Screenshot from 2021-10-07 20-17-21

r? @jsha

### CODE REVIEW

**Review by jsha — APPROVED** [review]

**Comment by dns2utf8** [comment]
An alternative would be to insert a very, very long text in the `<code>`
image

**Comment by GuillaumeGomez** [comment]
I prefer to not change the layout too much considering that it's not what's being tested here. ;)

**Pull request merged**
