### PR TITLE
Don't unwind when hitting the macro expansion recursion limit

### PR DESCRIPTION
**Pull request by Zoxc**
This removes one use of `FatalError.raise()`.

r? @petrochenkov

### CODE REVIEW

**Comment by Zoxc** [comment]
Hm.. it seems like `ui\issues\issue-16098.rs` relies on the early exit here to avoid long compile times.

```rust
macro_rules! prob1 {
    (0) => {
        0
    };
    ($n:expr) => {
        if ($n % 3 == 0) || ($n % 5 == 0) {
            $n + prob1!($n - 1); //~ ERROR recursion limit reached while expanding `prob1!`
        } else {
            prob1!($n - 1);
        }
    };
}

fn main() {
    println!("Problem 1: {}", prob1!(1000));
}
```

**Comment by petrochenkov** [comment]
>it seems like ui\issues\issue-16098.rs relies on the early exit here to avoid long compile times.

Interesting, I wanted to remove this fatal error too, and expected producing a dummy fragment to work.

**Comment by petrochenkov** [comment]
Each call to `error_recursion_limit_reached` could halve the recursion limit and silence all the following recursion limit messages for the current `ExtCtxt`.

**Comment by Zoxc** [comment]
@petrochenkov I tried using an early exit from `expand_invoc` once the recursion limit was hit. That wasn't sufficient to make `issue-16098.rs` complete in a timely manner.

**Comment by petrochenkov** [comment]
The problem here is not entirely in expansion.
With https://github.com/rust-lang/rust/pull/69497#issuecomment-591895447 `rustc --pretty=expanded issue-16098.rs` completes in less than a second.

The generated AST is enormous though, so later compilation phases take a lot of time.

**Comment by Zoxc** [comment]
I made the compiler exit early after macro expansion if a recursion limit was hit.

**Comment by Centril** [comment]
Nice! The rest of the fatal errors are removed in https://github.com/rust-lang/rust/pull/70074, making expansion entirely fatal-error free.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/70110#issuecomment-600749136, @bors r-

**Comment by Zoxc** [comment]
Still don't know why it failed in the rollup.

@bors r-

**Comment by Zoxc** [comment]
Looks like the PR build also failed in https://github.com/rust-lang/rust/pull/70110, which doesn't happen here. I'm going to assume some other PR was the cause of the failure.

@bors r=petrochenkov

**Pull request merged**
