### PR TITLE
Stop a private method on `SipHasher` from shadowing `Hasher::write`

### LINKED ISSUE #28374: SipHasher::write, when used externally, should refer to trait method, not inherent (and private) method.
This code snippet works: http://is.gd/cAKwYz

However, substituting `::Hasher` for `::SipHasher` gives the following error:

```
src/chunks.rs:35:5: 35:34 error: method `write` is private
src/chunks.rs:35     ::std::hash::SipHasher::write(&mut hasher, &x);
```

Discussion from IRC:

```
savv  hello. I am trying to figure out why SipHasher::write appears to be private, whereas ::finish is not: http://is.gd/cjwAvO
savv  Even though they both seem to be the same in terms of public-ness: https://doc.rust-lang.org/src/core/hash/sip.rs.html#174-200
eibwen  savv: it's because it has an inherent method of the same name
eibwen  savv: you need to call it via Hasher::write(&mut hasher, &x)
eibwen  you're welcome. you could open an issue about that
```

### PR DESCRIPTION
**Pull request by tbu-**
Closes #28374

### CODE REVIEW

**Comment by tbu-** [comment]
You couldn't call `sip.write` before, because the inherent method shadowed the method of `Hasher`.

**Comment by sfackler** [comment]
Is there an issue filed for the larger issue in method resolution that caused this?

**Comment by arielb1** [comment]
@sfackler 

#12808 (kind-of)

**Pull request merged**
