### PR TITLE
Add nightly style guide section for `precise_capturing` `use<>` syntax

### PR DESCRIPTION
**Pull request by compiler-errors**
r? style

Tracking:

- https://github.com/rust-lang/rust/issues/123432

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'm going to go ahead and FCP merge this as-is, since I don't believe there is any additional consideration we need to have towards this syntax. Please register a concern if we should have more discussion.

@rfcbot fcp merge

**Comment by compiler-errors** [comment]
Tho let's get three checkboxes

@rfcbot concern checkboxes

**Review by traviscross — APPROVED** [review]

**Comment by calebcartwright** [comment]
I can't resolve the concern but have checked my box

**Comment by compiler-errors** [comment]
@rfcbot resolve checkboxes

**Pull request merged**
