### PR TITLE
impl AsRef<[T]> for vec::IntoIter<T>

### PR DESCRIPTION
**Pull request by CAD97**
Adds `impl<T> AsRef<[T]> for vec::IntoIter<T>`. This mirrors the same trait impl for [`slice::Iter`](https://doc.rust-lang.org/nightly/std/slice/struct.Iter.html). Both types already offer `fn as_slice(&self) -> &[T]`, this just adds the trait impl for `vec::IntoIter`.

If/when `fn as_slice(&self) -> &[T]` stabilizes for `vec::Drain` and `slice::IterMut`, they should get `AsRef<[T]>` impls as well. As thus, tangentially related to #58957.

My ultimate goal here: being able to use `for<T, I: Iterator<Item=T> + AsRef<[T]>> I` to refer to `vec::IntoIter`, `vec::Drain`, and eventually `array::IntoIter`, as an approximation of the set of by-value iterators that can be "previewed" as by-ref iterators. (Actually expressing that as a trait requires GAT.)

### CODE REVIEW

**Comment by CAD97** [comment]
Marked as stable in 1.46 as trait impls are insta-stable and with FCP this will definitely miss the 1.45 beta cutoff.

**Comment by dtolnay** [comment]
@rust-lang/libs: this adds `impl<T> AsRef<[T]> for std::vec::IntoIter<T>` exposing the same behavior as the long-stable https://doc.rust-lang.org/std/vec/struct.IntoIter.html#method.as_slice.

@rfcbot fcp merge

**Comment by CAD97** [comment]
`RefMut<[T]>` could also be provided for `as_mut_slice`, but there's not precedent for providing that trait on slice iterators. (`slice::IterMut` also doesn't provide `as_slice`/`AsRef<[T]>` on stable yet.) I've kept this PR to just be `AsRef<[T]>` to keep it to aligning with existing precedent (on `slice::Iter`).

**Review by dtolnay — APPROVED** [review]

**Comment by jplatte** [comment]
Milestone is incorrect, should be 1.46.

**Pull request merged**
