### PR TITLE
do not normalize all non-scalar constants to a ConstValue::ScalarPair

### PR DESCRIPTION
**Pull request by RalfJung**
We still need `ConstValue::ScalarPair` for match handling (matching slices and strings), but that will never see anything `Undef`. For non-fat-ptr `ScalarPair`, just point to the allocation like larger data structures do.

Fixes https://github.com/rust-lang/rust/issues/54387

r? @eddyb

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @oli-obk

**Comment by RalfJung** [comment]
A less risky variant for beta might be to just backport the changes in `const_eval` to normalize fewer things, but not get rid of the `ScalarMaybeUndef` in `ConstValue` entirely.

**Comment by eddyb** [comment]
So the argument here is that anything that doesn't need an allocation should be fully initialized?
(I expected `ScalarMaybeUndef` to be used more, but I see why you'd want the opposite)

**Comment by RalfJung** [comment]
> So the argument here is that anything that doesn't need an allocation should be fully initialized?

Yes. We have those variants only because pattern matching and some code around array lengths need them. No reason they should have to handle `Undef`.

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang/rust/issues/54738

**Comment by RalfJung** [comment]
I made a beta backport at https://github.com/rust-lang/rust/pull/54759

**Comment by pnkfelix** [comment]
T-compiler accepted #54759 for the backport.

**Pull request merged**
