### PR TITLE
update Miri

### LINKED ISSUE #65684: `miri` no longer builds after rust-lang/rust#65671
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#65671, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/65684

### CODE REVIEW

**Comment by RalfJung** [comment]
Self-r+ because this just updates a submodule; p=1 because it fixes toolstate.

@bors r+ p=1

**Comment by RalfJung** [comment]
@oli-obk due to https://github.com/rust-lang/miri/pull/1010, bootstrap now has to install xargo itself. I think that's good; it disentangles the two a bit -- bootstrap makes fewer assumptions about what `cargo miri setup` does.

Could you review the changes needed for that?

**Comment by oli-obk** [comment]
Heh, neat setup. I'm not sure about the `install` directory, but we can change it later

@bors r+

**Comment by RalfJung** [comment]
The install directory is also left unchanged by this PR.

**Comment by RalfJung** [comment]
Hm, looks like we can't call `cargo install` this way:
```
2019-10-24T16:05:49.9785583Z error: Found argument '--manifest-path' which wasn't expected, or isn't valid in this context 
```
@bors r-

**Comment by RalfJung** [comment]
This time I build-tested it... took an hour but now it's looking good. :)

@bors r=oli-obk

**Comment by RalfJung** [comment]
Some other PR landed in the mean time that broke Miri:
```
2019-10-25T20:33:57.8333743Z error[E0308]: mismatched types
2019-10-25T20:33:57.8335013Z --> src\tools\miri\src\helpers.rs:78:82
2019-10-25T20:33:57.8335166Z |
2019-10-25T20:33:57.8336103Z 78 | let place = mir::Place { base: mir::PlaceBase::Local(local), projection: Box::new([]) };
2019-10-25T20:33:57.8336416Z | ^^^^^^^^^^^^ expected reference, found struct `std::boxed::Box`
2019-10-25T20:33:57.8336985Z |
2019-10-25T20:33:57.8337152Z = note: expected type `&rustc::ty::List<rustc::mir::ProjectionElem<rustc::mir::Local, &rustc::ty::TyS<'_>>>`
2019-10-25T20:33:57.8337702Z found type `std::boxed::Box<[_; 0]>`
```

**Comment by RalfJung** [comment]
Rebased and fixed Miri.

@bors r=oli-obk

**Pull request merged**
