### PR TITLE
First round of LLVM 6.0.0 compatibility

### PR DESCRIPTION
**Pull request by alexcrichton**
This includes a number of commits for the first round of upgrading to LLVM 6. There are still [lingering bugs](https://github.com/rust-lang/rust/issues/47683) but I believe all of this will nonetheless be necessary!

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors r+

cc @nagisa who may have opinions

**Comment by kennytm** [comment]
Is the `llvm-emscripten` submodule expected to be included? The comment in cd4b23e suggests not.

**Comment by alexcrichton** [comment]
@bors: r-

nah that was accidentally. When including this in https://github.com/rust-lang/rust/pull/47748 I've [removed the submodule](https://github.com/rust-lang/rust/pull/47748/commits/cd4b23e6740b628e4b96e81993b445b2b2cd7ed7) and if that doesn't land I'll update this PR

**Pull request merged**
