### PR TITLE
Less verbose output for unused arguments 

### LINKED ISSUE #37718: Multiple unused formatting argument notes should use multispan
After https://github.com/rust-lang/rust/pull/37613, the output for `format!` errors looks like:

```
error: multiple unused formatting arguments
  --> $DIR/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: argument never used
  --> $DIR/format-foreign.rs:12:30
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^
note: argument never used
  --> $DIR/format-foreign.rs:12:40
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                                        ^^^^^^^
note: argument never used
  --> $DIR/format-foreign.rs:12:49
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                                                 ^
   = help: `%.*3$s` should be written as `{:.2$}`
   = help: `%s` should be written as `{}`
   = note: printf formatting not supported; see the documentation for `std::fmt`
= note: this error originates in a macro outside of the current crate
```

that's a lot of lines dedicated to underlining macro acruments. They should all be output in one multispan.

cc @DanielKeep @estebank @jonathandturner @GuillaumeGomez

### PR DESCRIPTION
**Pull request by perryprog**
Closes #37718 

This is my first contribution to rust, so sorry if I'm missing anything!

The output now looks like this:
screen shot 2017-07-18 at 5 01 32 pm

It's not the prettiest, but whenever #41850 gets resolved, this should be able to be improved.

**EDIT:** This also does not seem
r? @Mark-Simulacrum

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
This looks good to me, but I'm going to r? @GuillaumeGomez for final review. It looks like we already have the follow up issue which will make this even better: https://github.com/rust-lang/rust/issues/41850.

**Comment by perryprog** [comment]
Woot! Thanks!

**Comment by perryprog** [comment]
Hmm... I'm wondering if it would be better to use something other than `span_label`, as combining the red error line, with the blue "secondary" errors looks bad, and sends a mixed message.

How would you have just the red "primary" error under the unused arguments, or _just_ the blue "secondary" error lines under the unused arguments?

**Comment by estebank** [comment]
> How would you have just the red "primary" error under the unused arguments, or just the blue "secondary" error lines under the unused arguments?

`struct_span_err` takes a `MultiSpan`, which means you can do

```rust
cx.ecx.struct_span_err(errs.iter().map(|(sp, _)| *sp).collect::<Vec<Span>>(),
                       "multiple unused formatting arguments")
```
which would give you the following output instead:

```
error: multiple unused formatting arguments
  --> $DIR/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^  ^^^^^^^  ^
```

If you keep the `for (sp, _) in errs {...}` it'd look like this:

```
error: multiple unused formatting arguments
  --> $DIR/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^  ^^^^^^^  ^ unused
   |                              |          |
   |                              |          unused
   |                              unused
```

I personally think it looks slightly better without the labels in that case, but I'm not too fussed either way.

**Comment by perryprog** [comment]
I’ll wait to find out what @Mark-Simulacrum and @GuillaumeGomez prefer.

@estebank where’s the best place to find documentation about this sort of thing? Also, thanks a lot for helping me! I really appreciate it!

**Comment by estebank** [comment]
@perryprog my best advice would be to read the code. @Manishearth compiles the [rustdoc for the compiler](https://manishearth.github.io/rust-internals-docs/rustc_errors/diagnostic_builder/struct.DiagnosticBuilder.html) if you need a link for somebody else, but I always end up going back to the code itself as there're sometimes comments explaining what's going on. It's a great help to just see how other errors do their thing.

I sometimes add a dependency on [backtrace-rs](https://github.com/alexcrichton/backtrace-rs) to add a `debug!` with a specific location's backtrace when I can't find out where it is actually being called from. If you are using `debug!` statements, you'll probably want to do `./configure --enable-debug` (it will slow down builds after stage 0, though). You should probably know about `rustc -Z treat-err-as-bug`, which will make the compiler panic on the first diagnostic error that is emitted. This coupled with `RUST_BACKTRACE=short` is sometimes useful to get the callstack, but not always (as sometimes a diagnostic is saved and emitted much later in the run).

**Comment by GuillaumeGomez** [comment]
The code looks good and the current output seems fine to me (the "unused" is important).

**Comment by perryprog** [comment]
@GuillaumeGomez just want to make sure I'm clear here: Are you good with this output:
```
error: multiple unused formatting arguments
  --> $DIR/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^  ^^^^^^^  ^ unused
   |                              |          |
   |                              |          unused
   |                              unused
```
or are you good with what I have in the PR currently:
screen shot 2017-07-18 at 5 01 32 pm

**Comment by GuillaumeGomez** [comment]
I'm good with what you have currently. :)

**Comment by perryprog** [comment]
@GuillaumeGomez oh, ok 😛

I think I’ll write some more tests, and then this’ll be ready for a merge.

**Comment by estebank** [comment]
>However, it seems like the struct_span_err method doesn't accept a Vec:

@perryprog I thought that `MultiSpan from Vec<Span>` was implemented, my bad. `struct_span_err()`(https://manishearth.github.io/rust-internals-docs/syntax/ext/base/struct.ExtCtxt.html#method.struct_span_err) should be changed to accepting `Into<MultiSpan>` (as `DiagnosticBuilder` already accepts that), so that you can provide [`MultiSpan::from_spans()`](https://manishearth.github.io/rust-internals-docs/syntax_pos/struct.MultiSpan.html#method.from_spans) to it instead of the `Vec<Span>`.

Having said that, given @GuillaumeGomez comment, you don't need to do that for this PR.

**Comment by perryprog** [comment]
I'll add the tests in a separate PR, is that fine?

**Comment by estebank** [comment]
@bors r-

@perryprog missed the bit about adding more tests, let's add them to this PR so they're self contained (easier to track down the work done after the fact that way). Ping me when you've added them and I'll r+ again.

**Comment by perryprog** [comment]
I'm just adding some UI tests — should I just add them all inside [this file](https://github.com/rust-lang/rust/blob/master/src/test/ui/macros/format-foreign.rs)?

**Comment by estebank** [comment]
Only if they're tightly related to that test, otherwise just create a new file with a descriptive title.

**Comment by perryprog** [comment]
@estebank **ping** pong 🏓

**Pull request merged**
