### PR TITLE
rustdoc: fix summary lines

### LINKED ISSUE #31899: rustdoc summaries include parts of doc examples
A documentation comment like the one cited verbatim below, produces a main page summary that includes the first line of the code in the example. This is very surprising since there's an empty line in between, and the code example inserts a large colored box in the overview page (the parent module).

cc @mitaa since it's probably related to PR #31602

```
/// A tuple or fixed size array that can be used to index an array.
///
/// ```
/// use ndarray::arr2;
///
/// let mut a = arr2(&[[0, 1], [0, 0]]);
/// a[[1, 1]] = 1;
/// assert_eq!(a[[0, 1]], 1);
/// assert_eq!(a[[1, 1]], 1);
/// ```
///
/// **Note** the blanket implementation that's not visible in rustdoc:
/// `impl<D> NdIndex for D where D: Dimension { ... }`
```

screenshot

### PR DESCRIPTION
**Pull request by mitaa**
fixes #31899

r? @alexcrichton

### CODE REVIEW

**Comment by mitaa** [comment]
cc @bluss

**Comment by bluss** [comment]
Response time is A+++ :smile:

**Comment by mitaa** [comment]
I just remembered that this function is also used for the search-index descriptions.. So that still needs the old behaviour.

I'm going to push an update as soon as I have time.

**Comment by alexcrichton** [comment]
The idea here was to render headers like:

```rust
/// really long intro
/// comment
///
/// more explanation
```

as "really long intro comment", but doesn't this break that as only the first line is taken?

**Comment by mitaa** [comment]
You're right, I guess I got a bit confused by looking at the HTML source through inspector, which doesn't show the newlines in the `<p>` element (I thought hoedown/markdown removes these).
The rendererd markdown for
```rust
/// A tuple or fixed size array that can be used to index an array.
/// Make this line a bit longer.
///
/// ```
/// use ndarray::arr2;
/// ```
pub fn bar() {}
```
actually is
```
<p>A tuple or fixed size array that can be used to index an array.
Make this line a bit longer.</p>
<pre class='rust rust-example-rendered'>
<span class='kw'>use</span> <span class='ident'>ndarray</span>::<span class='ident'>arr2</span>;</pre>
```

Because of this I'm now extracting the first occuring html element in the string which seems to me the correct way to go.
I don't think that there is something in-tree with which I could replace the parsing code I've written?

**Comment by alexcrichton** [comment]
Er hang on, can we drill into what the bug is in the first place? I'd really like to avoid having any sort of HTML parser in rustdoc just to extract the first `<p>` span or something like that, it sounds quite brittle!

It looks like the bug may be that we're extracting text *after* rendering, when we should be extracting *before* rendering?

**Comment by mitaa** [comment]
I'm a bit uneasy about the parsing, but extracting before rendering means reintroducing #30366 and#25787.

**Comment by mitaa** [comment]
The problem doesnt appear with two paragraps, but with one paragraph and a codeblock. Specifically hoedown doesnt leave a blank line in this case.

..perhaps we could insert a dummy item between the first paragraph and following item, which we know leaves a blank line, before we markdown render it? (and then shorten it after rendering)

```
/// A tuple or fixed size array that can be used to index an array.
/// Make this line a bit longer.
///
/// # dummy
/// ```
/// use ndarray::arr2;
/// ``````

**Comment by alexcrichton** [comment]
Can we perhaps alter the hoedown rendering of code blocks to insert the blank line for us? That may be a good fix in the case that code blocks are the only cause of this.

**Comment by mitaa** [comment]
Oh right, we can do that  :smile:

(updated)

**Comment by alexcrichton** [comment]
@bors: r+ 0b3bc9b5e29ba867172120361fb32716fdb99e30

Thanks!

**Comment by bluss** [comment]
Thank you @mitaa !

**Pull request merged**
