### PR TITLE
Issue 52057 — inference variable

### PR DESCRIPTION
**Pull request by nikomatsakis**
Break out the computation of universal region relations and do it during the typeck, where we can handle the resulting constraints that arise. 

r? @pnkfelix

### CODE REVIEW

**Comment by nikomatsakis** [comment]
A note on naming: I want to rename `universal_region` to `free_region` (which was actually the name I used originally...) both because it's less awkward and because we have two kinds of universally quantified regions: free regions (lifetime parameters) and bound regions like the one in `for<'a> fn(&'a u32)`. In particular, free regions appear free in the fn body, but bound regions do not. 

I wound up not doing the rename in this PR though because it would conflict so badly with https://github.com/rust-lang/rust/pull/52488

**Comment by pietroalbini** [comment]
Ping from triage @pnkfelix! This PR needs your review.

**Comment by pnkfelix** [comment]
conflicts! That's what you get for trying to opt into new features!

**Pull request merged**
