### PR TITLE
Drop support for all cloudabi targets

### PR DESCRIPTION
**Pull request by tesuji**
`cloudabi` is a tier-3 target, and [it is no longer being maintained upstream][no].

This PR drops supports for cloudabi targets. Those targets are:
* aarch64-unknown-cloudabi
* armv7-unknown-cloudabi
* i686-unknown-cloudabi
* x86_64-unknown-cloudabi

Since this drops supports for a target, I'd like somebody to tag `relnotes` label to this PR.

Some other issues:
* The tidy exception for `cloudabi` crate is still remained because 
  * `parking_lot v0.9.0` and `parking_lot v0.10.2` depends on `cloudabi v0.0.3`.
  * `parking_lot v0.11.0` depends on `cloudabi v0.1.0`.

[no]: https://github.com/NuxiNL/cloudabi#note-this-project-is-unmaintained

### CODE REVIEW

**Comment by lzutao** [comment]
Also cc @joshtriplett for their request in <https://github.com/rust-lang/rust/pull/75568#issuecomment-716871404>.

**Review by m-ou-se — COMMENTED** [review]
Rip CloudABI :(

Considering the state of the cloudabi project and the effort in maintaining sys/cloudabi, I support this change.

**Comment by m-ou-se** [comment]
cc @EdSchouten

**Comment by Mark-Simulacrum** [comment]
Please squash commits; I think since this is moving from tier 3 to, uh, tier "nothing" I personally do not feel inclined to make an announcement at this time (but inclusion in relnotes will likely happen).

**Comment by EdSchouten** [comment]
Hey! Sorry for letting you folks wait. Feel free to remove support for CloudABI. Thanks!

**Comment by m-ou-se** [comment]
@EdSchouten  Thanks again for all the time and energy you've put in CloudABI and making it work with Rust! It's a shame to see it come to an end, but it was wonderful while it lasted. The project has been a great inspiration. <3

**Comment by Mark-Simulacrum** [comment]
Rebased this and will r+ once CI passes.

**Pull request merged**
