### PR TITLE
rustdoc: escape the deprecated and unstable reason text

### LINKED ISSUE #38220: Unescaped HTML in unstable reason
The docs for `FnBox` (https://doc.rust-lang.org/std/boxed/trait.FnBox.html) contain this line in the rendered output:

> will be deprecated if and when Box becomes usable

In the HTML source, this is the unescaped `Box<FnOnce>` instead of the escaped `Box&lt;FnOnce&gt;`.

### PR DESCRIPTION
**Pull request by estebank**
Fix #38220.
Instead of the [current output](https://doc.rust-lang.org/std/boxed/trait.FnBox.html):

incorrect unescaped unstable reason in docs

display:

escaped unstable reason in docs

### CODE REVIEW

**Review by ollie27 — CHANGES_REQUESTED** [review]
These strings are run through a Markdown renderer after this and it doesn't make any sense to HTML escape something and then treat it as Markdown. I think the right thing to do here is replace the Markdown rendering with just escaping.

Also there is one other instance of this below these two that should probably be changed as well.

**Comment by estebank** [comment]
@petrochenkov [travis error seems unrelated](https://travis-ci.org/rust-lang/rust/jobs/182360075#L3357)

**Comment by ollie27** [comment]
Actually we could leave it using Markdown and just add ``` ` ```s around `Box<FnOnce>` in the stability message like is done [elsewhere](https://github.com/rust-lang/rust/blob/7537f953e2d28dc0f34ab39737b058e7b79a7fb7/src/libcollections/binary_heap.rs#L553).

**Comment by estebank** [comment]
@ollie27 I'm thinking that even if using Markdown syntax to mark code would be preferable here it should still look reasonable (as in escaped) even if the code author forgets to do so.

**Comment by ollie27** [comment]
Adding the quotes and escaping results in it being rendered as "will be deprecated if and when `Box&lt;FnOnce&gt;` becomes usable", so yes escaping first does break Markdown.

**Comment by estebank** [comment]
@ollie27 you're absolutely right.

**Comment by alexcrichton** [comment]
Sounds like @ollie27's [suggestion](https://github.com/rust-lang/rust/pull/38244#issuecomment-265854442) may be the least invasive?

**Comment by estebank** [comment]
After reading through Hoedown's documentation, I have added a new `MarkdownHtml` struct that escapes HTML tags from the output, presenting the following output:



for `reason` ```"will be deprecated if and when `Box<FnOnce>` Box<FnOnce> becomes usable"```.

**Comment by estebank** [comment]
@ollie27 I feel that the patch is ready for merging. It changes this specific instance of the issue to use the code formatting, and avoids the issue going forward whenever somebody actually forgets to do so by escaping correctly. Only drawback is that you can't use HTML tags in these messages, but I feel that no one would be missing that feature for this field.

**Comment by ollie27** [comment]
I'm not sure about having the Markdown rendering act differently here to other places but as you've said it probably won't cause any problems in reality. We'll have to see what other people think.

Either way, if this change is accepted it will need tests.

**Comment by steveklabnik** [comment]
ping @ollie27 are you happy with this now?

**Comment by ollie27** [comment]
Yeah this is fine with me. Are people okay with no longer allowing raw HTML in depreciation and stability messages?

**Comment by nrc** [comment]
@ollie27 sgtm

**Comment by estebank** [comment]
@ollie27 if you're happy with the PR, can you post "@bors r+" for @bors to automerge this change? :)

**Comment by ollie27** [comment]
Sure.

@bors r+

**Pull request merged**
