### PR TITLE
Allow to pass a full path for `run-make` tests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
It's common (at least for me) to pass a full path to a `run-make` test (including the `rmake.rs` file) and to see that it isn't found, which is a bit frustrating.

With these changes, we can now optionally pass the `rmake.rs` (or even `Makefile`) at the end of the path.

cc @jieyouxu 
r? @Kobzol

### CODE REVIEW

**Comment by jieyouxu** [comment]
Oh yeah I've been annoyed by this as well, nice!

**Comment by Kobzol** [comment]
I like the idea, but I'm a bit scared of making compiletest changes unnecessarily. Could this be implemented via the inverse logic, i.e. if we get a `rmake.rs`/`Makefile` file path, then take its directory, and then just use the original Makefile logic going further?

**Comment by GuillaumeGomez** [comment]
I went for that originally. That means updating the filters, iterate over them and for each of them, check if the path starts with `run-make` then `tests` and ends with `rmake.rs` or `Makefile`. I'm fine with this approach too so gonna implement it.

**Comment by Kobzol** [comment]
Oh, if you specify a filepath, it won't automatically go [here](https://github.com/rust-lang/rust/pull/128100/files#diff-a3a0087e83f61b1a1ac97320e7b785506a5ba7d94237a93494ab310a7baff885R669)? In that case it's not as simple as I thought :laughing: But still I probably prefer the directory handling, in my view the test is the directory, and `rmake.rs`/`Makefile` is an implementation detail.

**Comment by GuillaumeGomez** [comment]
It doesn't do what you think it does. :laughing:

**Comment by GuillaumeGomez** [comment]
I went for the filter update instead. Much simpler, should have gone for this one instead... What do you think of this approach?

**Comment by Kobzol** [comment]
I don't know a lot about compiletest, but this looks better than before, and it works for me.

I wonder how UI tests do this though. If I do `x test tests/ui/associated-item`, it runs all tests within that directory, if I do `x test tests/ui/associated-item/associated-item-enum.rs`, it runs just that one test. I suppose that this happens on a different place than here (?).

Anyway, feel free to r=me, unless @jieyouxu has any objections.

**Comment by GuillaumeGomez** [comment]
It's actually `run-make` that is different here. We check if the folder has a `Makefile` or a `rmake.rs` then add it to the path.

**Comment by jieyouxu** [comment]
Yeah, rmake.rs not accepting the *exact* path was just a quirk in my original implementation of it, this part of the test filtering has not been changed since I added it initially. It was more of a "initial workint version".

**Comment by GuillaumeGomez** [comment]
Prototype -> prod, oh well, we all know the drill. :laughing: 

Then let's go!

@bors r=Kobzol,jieyouxu rollup

**Comment by GuillaumeGomez** [comment]
You should give a talk or write a blog post about "Migrating run-make, the ugly and terrible" haha

**Pull request merged**
