### PR TITLE
Handle more span edge cases in generics diagnostics

### PR DESCRIPTION
**Pull request by SkiFire13**
This should fix invalid suggestions that didn't account for empty bracket pairs (`<>`) or type bindings.

### CODE REVIEW

**Comment by the8472** [comment]
@Dylan-DPC this is missing an assignee

**Comment by estebank** [comment]
@SkiFire13 apologies for the delay and the significant divergence introduced by https://github.com/rust-lang/rust/pull/82272. That PR touches a lot of code that affects the same output you were trying to improve. Would you be interested in trying to port your changes to the new approach?

**Comment by SkiFire13** [comment]
Don't worry, I feel like if my PR would have been merged before it would have been harder to rebase #82272. I'm currently working on rebasing it.

**Pull request merged**
