### PR TITLE
Stabilize or_insert_with_key

### PR DESCRIPTION
**Pull request by ChaiTRex**
Stabilizes the `or_insert_with_key` feature from https://github.com/rust-lang/rust/issues/71024. This allows inserting key-derived values when a `HashMap`/`BTreeMap` entry is vacant.

The difference between this and  `.or_insert_with(|| ... )` is that this provides a reference to the key to the closure after it is moved with `.entry(key_being_moved)`, avoiding the need to copy or clone the key.

### CODE REVIEW

**Comment by varkor** [comment]
This will needs a libs team sign-off.

r? @SimonSapin

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by m-ou-se** [comment]
Sorry for the delay! Unfortunately this missed 1.49. Can you update the stable versions to 1.50?

**Comment by ChaiTRex** [comment]
@m-ou-se It is updated in the latest commit.

**Comment by BurntSushi** [comment]
> The difference between this and `.or_insert_with(|| ... )` is that this provides a reference to the key to the closure after it is moved with `.entry(key_being_moved)`, avoiding the need to copy or clone the key.

This seems like a useful bit of information that would be good to add to the docs.

**Comment by ChaiTRex** [comment]
@BurntSushi How about this?

> Ensures a value is in the entry by inserting, if empty, the result of the default function. This method allows for generating key-derived values for insertion by providing the default function a reference to the key that was moved during the `.entry(key)` method call.<br />
> The reference to the moved key is provided so that cloning or copying the key is unnecessary, unlike with `.or_insert_with(|| ... )`.

**Comment by BurntSushi** [comment]
@ChaiTRex Thank you, that looks great to me!

**Pull request merged**
