### PR TITLE
Store def_id_to_hir_id as variant in hir_owner.

### PR DESCRIPTION
**Pull request by spastorino**
If hir_owner is Owner(_), the LocalDefId is pointing to an owner, so the ItemLocalId is 0.
If the HIR node does not exist, we store Phantom.
Otherwise, we store the HirId associated to the LocalDefId.

Related to #89278

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
@cjgillot we've been able to reduce the perf regression in non-clean builds significantly. I believe the problem was that the `hir_owner` query returned a HirId for non-owners, but that id was always thrown away (except in `local_def_id_to_hir_id`). So if the ignored value changed any callers of `hir_owner` were recomputed, even though they just threw the changed value away.

This has been fixed by changing `hir_owner` back to its previous signature and instead adding a second query specifically for `local_def_id_to_hir_id`.

There are still regressions (mostly in incremental clean builds), but I don't know how to avoid them... it seems the `hir_crate` query changes its output even in clean runs?

**Comment by oli-obk** [comment]
@cjgillot we've been able to reduce the perf regression in non-clean builds significantly. I believe the problem was that the `hir_owner` query returned a HirId for non-owners, but that id was always thrown away (except in `local_def_id_to_hir_id`). So if the ignored value changed any callers of `hir_owner` were recomputed, even though they just threw the changed value away.

This has been fixed by changing `hir_owner` back to its previous signature and instead adding a second query specifically for `local_def_id_to_hir_id`.

There are still regressions (mostly in incremental clean builds), but I don't know how to avoid them... it seems the `hir_crate` query changes its output even in clean runs?

**Comment by cjgillot** [comment]
> @cjgillot we've been able to reduce the perf regression in non-clean builds significantly.

This is great! The perf is still bad, but I don't think there is anything more than query system overhead, is there?

> I believe the problem was that the `hir_owner` query returned a HirId for non-owners, but that id was always thrown away (except in `local_def_id_to_hir_id`). So if the ignored value changed any callers of `hir_owner` were recomputed, even though they just threw the changed value away.
> 

I did not expect that. Does it come from queries call `local_def_id_to_hir_id` without fetching the HIR behind those ids.

> This has been fixed by changing `hir_owner` back to its previous signature and instead adding a second query specifically for `local_def_id_to_hir_id`.
> 

I had excluded this possibility because of some old PR's perf result, but I guess I did not think it through.

> There are still regressions (mostly in incremental clean builds), but I don't know how to avoid them... it seems the `hir_crate` query changes its output even in clean runs?
>

`hir_crate` lowers HIR for the whole crate. As the AST is not hashed, it's always recomputed. `hir_crate` output is still hashed (it's hash is the HIR contribution to `crate_hash`), but contains way too much information for it's own good. One of the aims of #88186 is to change this.

**Comment by oli-obk** [comment]
> Does it come from queries call `local_def_id_to_hir_id` without fetching the HIR behind those ids.

I did not dig in the details further. But I do know of queries that do that, since they need the HirId for obligation causes



> The perf is still bad, but I don't think there is anything more than query system overhead, is there?

Yea, it looks exactly like that is the cause.



> but contains way too much information for it's own good

Yea that's what I was guessing, thanks for confirming.

@bors r+ rollup=never

**Comment by spastorino** [comment]
CI is segfaulting, unrelated to this PR.

**Comment by rylev** [comment]
Talked with @oli-obk and @spastorino about this [here](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Perf.20of.20.2389278). The change in this PR (along with https://github.com/rust-lang/rust/issues/93301) is needed to be able to make AST -> HIR lowering incremental (as a part of the general move towards more incremental compilation). This is achieved by removing a global untracked-by-incremental map that exists in `TyCtxt`. While this doesn't get us much immediately, there is a strong belief that this will lead to dividends through more incremental compilation, potentially less ICEs, and potentially easier implementations for things like async functions in traits. 

@rustbot label: +perf-regression-triaged

**Pull request merged**
