### PR TITLE
Update E0185 and E0186 to new format

### LINKED ISSUE #35276: E0185 needs to be updated to new format
From: src/test/compile-fail/E0185.rs

E0185 needs a span_label, updating it from:

```
error[E0185]: method `foo` has a `&self` declaration in the impl, but not in the trait
  --> src/test/compile-fail/E0185.rs:18:5
   |
18 |     fn foo(&self) {} //~ ERROR E0185
   |     ^^^^^^^^^^^^^^^^
```

To:

```
error[E0185]: method `foo` has a `&self` declaration in the impl, but not in the trait
  --> src/test/compile-fail/E0185.rs:18:5
   |
18 |     fn foo(&self) {} //~ ERROR E0185
   |     ^^^^^^^^^^^^^^^^ `&self` not used in the trait
```

Bonus: show the trait that it's referencing.

```
error[E0185]: method `foo` has a `&self` declaration in the impl, but not in the trait
  --> src/test/compile-fail/E0185.rs:18:5
   |
12 |     fn foo();
   |     --------- trait declared without `&self`
...
18 |     fn foo(&self) {} //~ ERROR E0185
   |     ^^^^^^^^^^^^^^^^ `&self` used in impl
```

### LINKED ISSUE #35277: E0186 needs to be updated to new format
From: src/test/compile-fail/E0186.rs

Error E0186 needs a span_label, updating it from:

```
error[E0186]: method `foo` has a `&self` declaration in the trait, but not in the impl
  --> src/test/compile-fail/E0186.rs:18:5
   |
18 |     fn foo() {} //~ ERROR E0186
   |     ^^^^^^^^^^^
```

To:

```
error[E0186]: method `foo` has a `&self` declaration in the trait, but not in the impl
  --> src/test/compile-fail/E0186.rs:18:5
   |
18 |     fn foo() {} //~ ERROR E0186
   |     ^^^^^^^^^^^ expected `&self` in impl
```

Bonus: show the trait line as well

```
error[E0186]: method `foo` has a `&self` declaration in the trait, but not in the impl
  --> src/test/compile-fail/E0186.rs:18:5
   |
12 |     fn foo(&self);
   |     -------------- `&self` used in trait
...
18 |     fn foo() {} //~ ERROR E0186
   |     ^^^^^^^^^^^ expected `&self` in impl
```

### PR DESCRIPTION
**Pull request by yossi-k**
Part of #35233.
Fixes #35277.
Fixes #35276.
r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks pretty good.  Question: why switch from ' to ` ?

**Comment by yossi-k** [comment]
Wow haven't even notice... That was IntelliJ. 
Should I switch back?

**Comment by jonathandturner** [comment]
Yes, please.  It helps the errors be more consistent.

**Comment by yossi-k** [comment]
@jonathandturner Fixed, also added the bonus part.

**Comment by jonathandturner** [comment]
Nice!

Can you [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits from 7 down to 1?  With that I think this will be ready.

**Comment by yossi-k** [comment]
Done

**Comment by jonathandturner** [comment]
Thanks 👍 

@bors r+ rollup

**Pull request merged**
