### PR TITLE
Update E0035, E0036 and E0370 to new error format

### LINKED ISSUE #35206: E0035 needs to be updated to new format
From: src/test/compile-fail/E0035.rs

**Edit (9/24/2016)**: updated wording

Error E0035 needs a span_label and an updated title, updating it from:

```
error[E0035]: does not take type parameters
  --> src/test/compile-fail/E0035.rs:19:7
   |
19 |     x.method::<i32>(); //~ ERROR E0035
   |       ^^^^^^
```

To:

```
error[E0035]: function called with unnecessary type parameters
  --> src/test/compile-fail/E0035.rs:19:7
   |
19 |     x.method::<i32>(); //~ ERROR E0035
   |       ^^^^^^ does not take type parameters
```

### LINKED ISSUE #35207: E0036 needs to be updated to new format
From: src/test/compile-fail/E0036.rs

The E0036 error needs a span_label, updating it from:

```
error[E0036]: incorrect number of type parameters given for this method: expected 1, found 2
  --> src/test/compile-fail/E0036.rs:22:7
   |
22 |     x.method::<i32, i32>(v); //~ ERROR E0036
   |       ^^^^^^
```

To:

```
error[E0036]: incorrect number of type parameters given for this method: expected 1, found 2
  --> src/test/compile-fail/E0036.rs:22:7
   |
22 |     x.method::<i32, i32>(v); //~ ERROR E0036
   |       ^^^^^^ Passed 2 type arguments, expected 1
```

### LINKED ISSUE #35634: E0370 needs to be updated to new format
From: src/test/compile-fail/E0370.rs

E0370 needs a span_label, an updated title, and a new note, changing it from:

```
error[E0370]: enum discriminant overflowed on value after 9223372036854775807i64; set explicitly via Y = -9223372036854775808i64 if that is desired outcome
  --> src/test/compile-fail/E0370.rs:17:5
   |
17 |     Y, //~ ERROR E0370
   |     ^ 
```

To:

```
error[E0370]: enum overflowed
  --> src/test/compile-fail/E0370.rs:17:5
   |
17 |     Y, //~ ERROR E0370
   |     ^ overflowed after 9223372036854775807i64
   |
   = note: explicitly set `Y = -9223372036854775808i64` if that is desired outcome
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #35634.
Fixes #35206.
Fixes #35207.

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks like you have a stray commit in this PR

**Comment by jonathandturner** [comment]
Other than that, looks okay

**Comment by GuillaumeGomez** [comment]
Updated.

**Pull request merged**
