### PR TITLE
Adds a `--failed` flag to `x test`

### PR DESCRIPTION
**Pull request by darklyspaced**
This flag runs solely tests that failed on the previous iteration.

related to: #114609

### CODE REVIEW

**Comment by darklyspaced** [comment]
okay. the CI _really_ seems to hate creating files. both solutions worked fine on my system 😅, so it just seems like its a weird quirk with the CI. i don't really know what to do at this point. could i have some guidance on this please? @ozkanonur

**Comment by ozkanonur** [comment]
> okay. the CI really seems to hate creating files. both solutions worked fine on my system sweat_smile, so it just seems like its a weird quirk with the CI. i don't really know what to do at this point. could i have some guidance on this please? @ozkanonur

Before doing the PR review on feature implementations, it is necessary to discuss within the bootstrap team whether this feature is truly needed and worth to implement and maintain. In the past, we haven't been very open to similar feature requests/ideas, mainly because we can already achieve such things using subcommands (like grep, awk, etc.). If you want, You can initiate the discussion in the [bootstrap channel on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap), or I can bring it up for discussion in the upcoming bootstrap meeting.

**Comment by ozkanonur** [comment]
PR is marked as `blocked` until a conclusion is reached through discussion by the bootstrap team.

**Comment by darklyspaced** [comment]
> If you want, You can initiate the discussion in the [bootstrap channel on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap)

Started a discussion around the feature [here](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Usefulness.20of.20a.20.60--failed.60.20flag.20on.20.60x.20test.60/near/384631095). Thanks for letting me know.

**Comment by ozkanonur** [comment]
> During the Bootstrap team meeting, we decided that this feature is not necessary. The reason is that the Bootstrap layer is already complex and large, and we believe that the maintenance effort required for this feature wouldn't justify the benefit it would bring.

> Thank you for your proposal!

From https://github.com/rust-lang/rust/issues/114609#issuecomment-1687533131

**Pull request closed without merging**
