### PR TITLE
Migrate `src/test/ui/run-pass/*` back to `src/test/run-pass/`.

### LINKED ISSUE #54047: Implement some way to run UI tests ignoring run-pass tests
`run-pass` test were recently merged into UI tests (https://github.com/rust-lang/rust/pull/53860, https://github.com/rust-lang/rust/pull/53992, https://github.com/rust-lang/rust/pull/53994), which is unfortunate in several aspects.

If you are working with diagnostics (changing spans, labels, error messages, etc) or in "compile-fail" area in general, and want to check the result on UI tests, then there's absolutely no need to run thousands of run-pass tests (+ their NLL variations) as well, which are also quite slow because you have to launch both the compiler and the produced executable.

### PR DESCRIPTION
**Pull request by pnkfelix**
Moves all the tests from `src/test/ui/run-pass/**` back to `src/test/run-pass/`.

This should have no impact on our overall testing completeness due to PR #54223 

Fix #54047

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me with green tests

**Comment by pnkfelix** [comment]
ha ha ha that was not expected

**Comment by pnkfelix** [comment]
Ah, I see, my issue is this: 

https://github.com/rust-lang/rust/blob/ae366637fedf6f34185e54fc7b2d725b1a458ff6/src/tools/compiletest/src/runtest.rs#L1342-L1352

In other words, we have a blanket `-Aunused` for *just* the `compile-fail` and `ui` test suites, but *not* for the `run-pass` test suite.

In other words, what happened was:
 1. I moved a bunch of files from `src/test/run-pass/` to `src/test/ui/.` In that process, I allowed a minimal number of lints in each test file.
 2. Then I changed strategy and made `src/test/run-pass/` a ui-like test suite. But I didn't include the above blanket `-Aunused` (and I argue it would have been a bad idea to do so). So some tests had to get some lints allowed. *But* the tests that were ported in step 1 above got away with not having the lint enabled.
 3. Now I'm trying to port the tests back, but they are now hitting the newly injected lint against unused code in the newly ui-ified `src/test/run-pass/`.

Okay. That's the explanation.

Now my fix is just to add the necessary lint allows, I think.

**Comment by pnkfelix** [comment]
The reason I’m missing cases like this is that i hit linker errors on four tests during the non-compare-mode phase, so once I get things down to those tests I have to choose between adding temp `// ignore-test` to them, or just crossing my fingers...

I will at least try to make sure I have a ticket filed for these specific linker errors, which seem to come from some combination of codegen-units, linktime optimization, and/or incremental compilation...

**Comment by kennytm** [comment]
Two failures on Windows due to unexpected warnings.

```
failures:
    [run-pass] run-pass\process\process-sigpipe.rs
    [run-pass] run-pass\structs-enums\struct-return.rs
```

**Comment by pnkfelix** [comment]
(marking as `[WIP]` temporarily while commit  7e54bcc03fe65a3d9ca3e6708125870caaac3be1 is on the branch for testing.)

**Pull request merged**
