### PR TITLE
Add compiletest `--compare-mode nll` option

### LINKED ISSUE #48879: Add "modes" to compiletest, for running all tests with NLL enabled and comparing with master
The NLL team has been trying to find a good workflow for evaluating the discrepancies between AST borrowck and NLL-based borrowck.

 * Past workflows have developed and used things like `-Z borrowck=compare` and the https://github.com/pnkfelix/nll-probe tool, but here I'm going to try to avoid a deep dive into how those have failed to satisfy our needs.

Our goal here: We want a way to track the current state of NLL, including the cases where there are known deviations, in a manner that allows immediate analysis of that state to determine things like:
 * "how many test cases does NLL deviate from AST borrowck",
 * "what do the deviations look like", or
 * "does this deviation represent a bug that needs to be fix? Or is it an improvement on the AST borrowck?"

Here's a new proposal for a (hopefully) relatively small change to `compiletest` that should yield an easier workflow to answer questions like those above, at least for the `ui/` subset of our tests.

 1. Context: The `ui/` tests are set up so that each test consists of an input `$file.rs`, and a set of expected outputs in `$file.stderr` (compilation error messages) and `$file.stdout` (non erroneous compiler output; rarely used). (For more info, see [this chapter in the rustc-guide](https://rust-lang-nursery.github.io/rustc-guide/tests/adding.html#guide-to-the-ui-tests).)
 1. Add a "mode" argument to `compiletest`, encoded either as a command line parameter or as an environment variable, or both. (The first mode we'll support will be "nll", which tells `compiletest` to pass `-Z nll` in addition to any other flags when invoking `rustc`, at least for the `ui/` tests).
 2. When running under a particular mode, if there is `$file.$mode.stderr` file, then this file will be used as the source of "acceptable output". If there is no such file, then `compiletest` will fallback to the regular filename `$file.stderr`.
 3. One complication: UI tests also include "inline" comments of the form `//~ ERROR` that indicate what error is expected on which line (these are mildly redundant with the stderr files above). Because messages may differ in the mode M, but we don't want to edit the sources too much, compiletest should just ignore the `//~ ERROR` annotations when running in a particular mode. We will still see the errors that occur from the stderr output, it's just less convenient.
 4. To ensure that we are tracking discrepancies somewhere, whenever there is a `$file.$mode.stderr`, then some tool (probably `compiletest`, but maybe `tidy`?) will be responsible to checking that `$file.rs` somewhere contains a comment that explains the source of the discrepancy. This could be a specially formatted FIXME, if the new behavior seems worse than before:
```rust
// $mode FIXME(#123) -- summary of discrepancy caused by NLL bug with corresponding issue num
```
or a "YAYME" comment for when the new behavior is an improvement:
```rust
// $mode YAYME(#123) -- summary of a beneficial discrepancy
```
(presumably the ticket linked by YAYME would just be the tracking issue for NLL or whatever other mode is being tested).

Benefits of the proposed system:

 * To find the cases that have discrepancies for nll, one can use `ls *.nll.stderr`
 * To find what a given discrepancy looks like, one can use `diff onetest.stderr onetest.nll.stderr`
 * To see if a discrepancy is a bug or not, grep for FIXME or YAYME in the .rs files.
   * This workflow is perhaps not ideal; @nikomatsakis has pointed out that it might be nicer if these comments somehow lived in the `*.$mode.stderr` files.

# Open Questions (to be resolved by implementor)

 * [ ] What should `compiletest` do about occurrences of `//~ ERROR` in the source text? In particular, should it check that the error output still has those cases, even when running under a given mode?
   * The current inclination of @pnkfelix and @nikomatsakis is that it is actually *okay* for `compiletest` to *ignore* the `//~ ERROR` annotations when running under a given mode. The reasoning here is this: the `//~ ERROR` annotations will already get checked by compiletest runs that *don't* have a mode. We probably *don't* want to force an error when there's a discrepancy when running under a given mode; any discrepancies, including any of those errors disappearing, should be accounted for in the linked `// $mode FIXME/YAYME`  issue, and we want to allow them to disappear or differ.

### PR DESCRIPTION
**Pull request by memoryleak47**
Before implementing the tidy stuff, I'd appreciate if someone reviews the changes so far.
This is my first non-trivial pull request, so I could really use some feedback. :)
closes #48879.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@memoryleak47 

>  This is my first non-trivial pull request, so I could really use some feedback. :)

Welcome =)

**Review by nikomatsakis — APPROVED** [review]
This looks really good! It's hard to test compiletest, so I guess I'll try to do a local build.

**Comment by memoryleak47** [comment]
I'm currently working on the tidy change. Should I open another pull request for that?

**Comment by pnkfelix** [comment]
One problem from my initial attempt to try out the PR: it seems like it will reuse previous cached results that were not run with `--compare-mode nll`.

More specifically, if I run `compiletest` on `src/test/run-pass`, and then immedately run it a second time, the second will finish much faster and every test will just say " ... ignored" after it, because it is reusing the cached success result.

But the problem is that if I run `compiletest` on `src/test/run-pass`, and then immedately run it a second time but this time pass `--compare-mode nll`, then we should not reuse the cached results (because the input arguments to `compiletest` differed.

As I write this, I am wondering whether this is just considered part of the `compiletest` design, in the sense that its users need to know well enough to clear the cache when making changes to the `compiletest` invocation. So maybe the problem here is "works as designed."

But its possible that we might be better off including the mode somewhere in the path we generate for the files we generate.
 * Or again, maybe the user should just know enough to pass a `--stage-id` parameter to `compiletest` that includes an encoding of the mode...

**Comment by pnkfelix** [comment]
After discussion with @nikomatsakis, I think I like another option that he suggested, which I will outline here:

 1. For right now, in this PR: make `compiletest` *ignore* the stamp files when you run it with `--compare-mode`
 2. Longer term (not in this PR), assuming that we add support for this to `x.py`, then as part of adding support for this to `x.py`, we should make `compiletest` resume respecting the stamp files, and at the same time `x.py --compare-mode nll` would be responsible for passing an appropriate `--stage-id` parameter so that the stamp files have the compare mode encoded in their filenames.

**Comment by memoryleak47** [comment]
Is there a good reason, to not just change the stamp-function to include the compare-mode in the output path? (eg. `<path>-<stage-id>-<compare-mode>.stamp`)
Also, I'm having trouble running compiletest with `--compare-mode nll` for debugging, as this doesn't seem to be possible using `x.py`, and I'm not familiar with using compiletest directly.

**Comment by nikomatsakis** [comment]
@memoryleak47 sorry for not getting back to you! Last week was Rust All Hands and it was a pretty overwhelming week.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/361821464). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (607705/607705), completed with 4799 local objects.
---
[00:00:44] configure: rust.quiet-tests     := True
---
[00:04:09] tidy error: /checkout/src/tools/compiletest/src/main.rs:626: line longer than 100 chars
[00:04:10] some tidy checks failed
[00:04:10]
[00:04:10]
[00:04:10] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:10] expected success, got: exit code: 1
[00:04:10]
[00:04:10]
[00:04:10] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:10] Build completed unsuccessfully in 0:01:43
[00:04:10] Makefile:79: recipe for target 'tidy' failed
[00:04:10] make: *** [tidy] Error 1
---
$ cat obj/tmp/sccache.log
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:00c3a60e:start=1522787404361827543,finish=1522787404369620476,duration=7792933
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:257549e8
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:257549e8:start=1522787404376848300,finish=1522787404383568298,duration=6719998
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:04641c62
$ dmesg | grep -i kill
[   11.067144] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by memoryleak47** [comment]
Alright, running compiletest with `--compare-mode` should now ignore timestamps.
Already tested that locally using @pnkfelix's trick. Thanks. :)
Testing the ui suite with `--compare-mode nll` causes a lot of errors, but I guess this is expected behaviour, caused by differences between nll and ast borrowck.

**Review by nikomatsakis — COMMENTED** [review]
As a meta comment, this is the kind of thing where I wish we had a testing framework for compiletest (https://github.com/rust-lang/rust/issues/47606). It always makes me nervous, since a wrong move could mean we are not testing what we think we are testing =)

That said, these changes seem good to me.

So r=me but I'd like @pnkfelix to "sign off" as well, for added security.

**Comment by pnkfelix** [comment]
also, I don't know if this is exactly relevant to this particular PR, but during my experimentation: When I  created an *empty* `augmented-assignments.nll.stderr` file, I expected to see a diff that just showed all plusses. (I.e., a diff against an empty file)

But instead it seems like if the revision file is empty, then it falls back on the base file `augmented-assignments.stderr`, in this particular case...

(I don't know whether other people think that fall back behavior for empty files is more intutive... it wasn't intuitive for me, since I'm the kind of person who will just do `touch augmented-assignments.nll.stderr` and then run the tool to see what the content is that I need to add.)

**Comment by pnkfelix** [comment]
Note: the prior two comments are more nits about things that we can do in follow-up PR's; they need not block landing this as-is.

**Pull request merged**
