### PR TITLE
continue to prefer hyphens in test files named after issue numbers

### PR DESCRIPTION
**Pull request by zackmdavis**
a [followup](https://github.com/rust-lang/rust/pull/38473#issuecomment-270068136) to #38473

(The files in `auxillary/` directories have an excuse, as they get used as crates/modules, for which snake_case names make more sense.)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors r-

https://travis-ci.org/rust-lang/rust/jobs/198507424

**Comment by alexcrichton** [comment]
@zackmdavis gah sorry for the delay here! Looks like there's some failures on CI though? Mind fixing and I'll r+?

**Comment by carols10cents** [comment]
Hi @zackmdavis! Just a friendly ping-- are you still up for making the changes to get the tests to pass? Let us know if you need any help or have any questions!

**Comment by zackmdavis** [comment]
@carols10cents hi, Carole! Thanks for asking! I'm kind of recovering from a personal crisis that I'm tempted to explain in this comment because humans are social animals, but which it turns out that I shouldn't actually explain, because you have no particular reason to care about that because the thing that you asked about was the status of this pull request! I think we should close the pull request, because while it would be desirable to tidy up the hyphens in the test file names, it's more important to keep the queue of open pull requests tidy; I can reopen or file another pull request later if I get around to it.

**Comment by carols10cents** [comment]
@zackmdavis no worries! As a social animal, I hope that you're doing better and I'm sending good thoughts your way ❤️

**Pull request closed without merging**
