### PR TITLE
Android abstract unix domain sockets AddressKind correction

### PR DESCRIPTION
**Pull request by NickAtAccuPS**
The prior check causes abstract unix domain sockets to return AddressKind::Unnamed instead of AddressKind::Abstract on Android.

Other than the immediately proceeding comment "macOS seems to return a len of 16 and a zeroed sun_path for unnamed addresses" the check as-implemented does not seem to have alternative explanation. I couldn't find an alternative explanation while stepping though git blame. I suspect the AddressKind::Unnamed nonzero check should instead be if macos, length 16, and zeroed array. @sfackler could you comment on this, the code as-is is the same from your initial addition of abstract uds support.

### CODE REVIEW

**Comment by sfackler** [comment]
Why are you looking for an alternative explanation? The check is for not Linux because BSDs share OSX's behavior.

**Comment by sfackler** [comment]
We have checks that addresses are unnamed as appropriate, and those should be running on Android as well: https://github.com/NickAtAccuPS/rust/blob/da6142c81057342d8d6686ae4078995aab73b5bc/src/libstd/sys/unix/ext/net.rs#L1747

Did you see this not working in practice? Maybe this behavior changed at some point in Android releases?

**Comment by pietroalbini** [comment]
Thanks for this PR! Changed the title to WIP so bors actually prevents merging until the prefix is removed from the title `:)` (also, highfive is down, assigned label+reviewer)

**Comment by NickAtAccuPS** [comment]
> The check is for not Linux because BSDs share OSX's behavior.
That's the context I was missing.

The problem I'm seeing in the wild is that while libstd doesn't handle creating/pairing an abstract UDS, it does handle them correctly if `UnixStream` et al. are manually constructed with `from_raw_fd()` with an abstract namespaced socket fd on Linux. This is how `mio_uds` is [currently implemented](https://github.com/alexcrichton/mio-uds/blob/e9967bcbe2eb9c9aa540d14934b6ff90a139c0c0/src/stream.rs#L61).

`self.address()` is used for the `fmt::Debug` and checks for abstract sockets correctly on Linux but incorrectly returns that the socket is unnamed socket on Android. This PR fixes that issue specifically.

Sorry that this wasn't clear from the first comment; I had forgotten that libstd doesn't support [abstract socket creation](https://github.com/NickAtAccuPS/rust/blob/da6142c81057342d8d6686ae4078995aab73b5bc/src/libstd/sys/unix/ext/net.rs#L1816).

I don't think the `test_connect_unix_datagram()` test is relevant to this PR; @sfackler did you mean to link to the `abstract_namespace_not_allowed()` test? Still that's just checking for creating an abstract UDS, not manually populating a `UnixStream` with an abstract socket fd. Since this case is correctly handled for Linux including debug statements, I think it makes sense to correctly handle it on Android too which is what this PR accomplishes.

**Comment by sfackler** [comment]
Ah, I was thinking that the issue was failing to detect unnamed addresses, not abstract addresses.

**Comment by pietroalbini** [comment]
@sfackler you need to r+ this again.

**Pull request merged**
