### PR TITLE
Add inlining annotations in `dec2flt`.

### PR DESCRIPTION
**Pull request by TDecking**
Currently, the combination of `dec2flt` being generic and the `FromStr` implementaions
containing inline anttributes causes massive amounts of assembly to be generated whenever
these implementation are used. In addition, the assembly has calls to function which ought to
be inlined, but they are not (even when using lto).

This Pr fixes this.

### CODE REVIEW

**Comment by TDecki** [comment]
All regressions are inside `diesel-1.4.8`. The only instance I see is in `sqlite/types/date_and_time/chrono.rs` inside the
`impl FromSql<Timestamp, Sqlite> for NaiveDateTime` definition. Oddly enough, there is a regression inside the `check` profile,
and I don't see how my changes could possibly affect this.

**Comment by Nilstrieb** [comment]
Running the cachegrind command locally shows that most changes in diesel happened in type folding - looks like noise.
@rustbot label +perf-regression-triaged

**Comment by TDecki** [comment]
@Nilstrieb Thanks for the help.

**Pull request merged**
