### PR TITLE
Use getentropy(2) on macos

### LINKED ISSUE #70179: On macOS, try `getentropy()` before opening `/dev/urandom`?
# Background

Hi, I'm developing a HTTP load generator called [oha](https://github.com/hatoo/oha). The application often exceeds the number of open file limit and then, tokio runtime crashes because it tries to open `/dev/urandom` to generate random on macOS.

https://github.com/hatoo/oha/issues/23

# issue

On macOS, according to https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/rand.rs, `fill_bytes` always read `/dev/urandom` but opening `/dev/urandom` may fail because of the limit of the number of open files.
So it would be better to try `getentropy` like [getrandom](https://docs.rs/getrandom/0.1.14/getrandom/) before reading `/dev/urandom`.

Thanks.

### PR DESCRIPTION
**Pull request by hatoo**
resolves #70179

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This seems to be what the getrandom crate does as of https://github.com/rust-random/getrandom/pull/46, and since we're using it just for seeding hashmap randomness (i.e., not for generating entropy in an ongoing fashion) it seems to fit the use case described in the API.

However, I'm relatively unfamiliar with this side of libstd, so another reviewer would be good. Perhaps @LukasKalbertodt? Not sure who we have who is familiar with this...

**Comment by LukasKalbertodt** [comment]
I'm really sorry, but I don't think I can reasonably review this PR either (I've never worked with MacOS, for one). To avoid reassigning a bunch of times still:

@rust-lang/libs @RalfJung Can anyone of you review this PR? Thanks :)

**Comment by RalfJung** [comment]
I have never used a macOS system, so... I don't think I can give good feedback here.^^ I agree with what @Mark-Simulacrum said.

**Review by dtolnay — APPROVED** [review]
The implementation looks good to me and matches what the popular getrandom crate has been using for the past 9 months.

**Pull request merged**
