### PR TITLE
[WIP] Implement RFC 1560.

### PR DESCRIPTION
**Pull request by jseyfried**
This prototypes https://github.com/rust-lang/rfcs/pull/1560 (cc #35120).

More specifically,
- Items and named imports shadow glob imports.
- Multiple globs can import the same name if the name is unused or the imports are shadowed.
- Multiple globs can import the same name if the imports are of the same item (following re-exports).
  - The visibility of such a name is the maximum visibility of the imports.
  - Equivalently, adding a glob import will never reduce the visibility of a name, nor will removing one increase it.
- Non-prelude private imports can be used wherever we currently allow private items to be used.
  - Prelude-imported names are unaffected, i.e. they continue to be usable only in lexical scopes.
- Globs import all visible names, not just public names.
  - Equivalently, glob importing from an ancestor module imports all of the ancestor's names, and glob importing from other modules is unchanged.
  - The visibility of a glob-imported name is the minimum visibility of the glob itself and the name in the imported module. In particular, `pub use super::*` is equivalent to `use`ing the private names and `pub use`ing the public names from `super` (modulo shadowing). See [this comment](https://github.com/rust-lang/rust/issues/31783#issuecomment-186938547) from #31783.

This implementation still needs documentation, tests, and more precise diagnostics (most importantly, an error for when an ambiguous name is used), but other than that it is complete.

### CODE REVIEW

**Comment by jseyfried** [comment]
@nikomatsakis Could we do a crater run to see how much breakage these changes cause?

**Comment by retep998** [comment]
Also if you could test it on Windows with `winapi` since that makes use of recursive globs.

**Comment by jseyfried** [comment]
cc @petrochenkov

**Comment by alexcrichton** [comment]
Unfortunately I broke `make dist` in https://github.com/rust-lang/rust/pull/32133, so crater isn't working as it can't build a compiler from this commit. Can you rebase on https://github.com/rust-lang/rust/pull/32217 once it lands? That should enable a crater run!

**Comment by nrc** [comment]
Just a note that the proposed changes are a draft RFC that hasn't been PR'ed yet, we should wait for the RFC to be approved (and of course to be a PR first) before landing this.

I would be curious to see a crater run in the meantime though.

**Comment by jseyfried** [comment]
> we should wait for the RFC to be approved before landing this

I know; this is a ways off from being ready to land regardless.

**Comment by jseyfried** [comment]
@alexcrichton I had to rebase anyway -- this should be ready for a crater run now!

**Comment by alexcrichton** [comment]
(also started a crater run)

**Comment by jseyfried** [comment]
> (also started a crater run)

Thanks!

**Comment by alexcrichton** [comment]
Oh dear, looks like [quite a few regressions](https://gist.github.com/alexcrichton/277f2844dc5b4f1b01ee) :(

**Comment by jonas-schievink** [comment]
Most of them seem to be caused by the use of `bitflags`

**Comment by jseyfried** [comment]
All of the root regressions appear to be due to a bug that I fixed in the above commit.

I had generalized the last bullet point ("The visibility of a glob-imported name is the minimum visibility of the glob itself and the name in the imported module") to apply to single imports as well. This won't a difference after the made a difference after the warning cycle from #31362

**Comment by alexcrichton** [comment]
Scheduled another crater run

**Comment by alexcrichton** [comment]
Hurray, [zero regressions](https://gist.github.com/alexcrichton/cba27f80a5659b182c45)!

**Comment by jseyfried** [comment]
Excellent. It also looks like these changes fix two crates that were broken by new names in upstream crates.

**Comment by alexcrichton** [comment]
@jseyfried this has been inactive for awhile now, should we close or try to rebase + land?

**Comment by jseyfried** [comment]
@alexcrichton I'm planning on rebasing, finishing this up, and maybe feature gating once RFC 1560 goes into FCP,  which should be any day now.

**Comment by alexcrichton** [comment]
Ok, awesome!

**Comment by nikomatsakis** [comment]
@jseyfried going to close this PR due to inactivity. Feel free to re-open though. :)

**Comment by jseyfried** [comment]
I finished this in #35894.

**Pull request closed without merging**
