### PR TITLE
Fix tidy unittest.

### PR DESCRIPTION
**Pull request by ehuss**
The tidy unittests weren't compiling due to a change made a long while ago to the `Version` type.

### CODE REVIEW

**Comment by ehuss** [comment]
I was thinking of adding tidy's unittests to `bootstrap/test.rs`, but I'm unsure if it is worth running. Any thoughts on that? I think if we do add it, it might want to be separate from *running* tidy, if anything to reduce the noise, but also avoid slowing tidy down.

**Comment by Mark-Simulacrum** [comment]
Yes, we definitely shouldn't run them as part of tidy -- I think we have a similar-ish split for Cargo (with cargotest vs. cargo itself).

I think we should run them in CI though.

**Comment by jyn514** [comment]
r=me unless you wanted to add the unittests to CI as part of this PR

**Comment by ehuss** [comment]
Ok, I added it so that it gets checked in CI.

@rustbot ready

**Comment by jyn514** [comment]
Looks great, thanks!

@bors r+ rollup

**Pull request merged**
