### PR TITLE
Download pre-compiled bootstrap from CI 

### PR DESCRIPTION
**Pull request by dvtkrlbs**
because of a silly rebase mistake i accidently nuked my branch which in turn closed the pr #112598. I recovered the branch using the github repo events and creating a new branch using their API.

r? @ozkanonur 

Currently with no changes on the bootstrap directory while doing a pre-push hook. I am getting
```
extracting /Users/dvtkrlbs/DEV/rust/build/cache/bootstrap-nightly-aarch64-apple-darwin.tar.xz
[Errno 2] No such file or directory: '/Users/dvtkrlbs/DEV/rust/build/aarch64-apple-darwin/stage0/bootstrap-nightly-aarch64-apple-darwin.'
```

Other than this issue (it triggers a download from ci even if it is not available or trying to extract the wrong file)

### CODE REVIEW

**Comment by dvtkrlbs** [comment]
Sorry for the wrong cc. I accidentally forgot to reset the stdarch submodule. Fixed now

**Comment by dvtkrlbs** [comment]
For the last issue for modification change detection I am open to suggestion. I don't really comprehend my current take on the issue and it is really hard to test since there is no easy way to mock git rev-parse.

**Comment by dvtkrlbs** [comment]
There also seems to be changes on the component download url format. I am not sure how the bootstrap artifacts fit into those

**Comment by onur-ozkan** [comment]
I am quite busy and don't have time for mentoring tasks these days. Overally, the flow should include the steps I mentioned on the previous PR https://github.com/rust-lang/rust/pull/112598#issuecomment-1596536781

As for the catching the modification changes, you can find several references in the codebase(I see I even left a suggestion related to that on https://github.com/rust-lang/rust/pull/112598#discussion_r1233539793).

@rustbot author

**Comment by dvtkrlbs** [comment]
Sorry for the lack of progress on this. I've been quite busy for a while and couldn't find any time to work on this I am closing this PR in case someone wants to continue feel free to base from my changes.

**Pull request closed without merging**
