### PR TITLE
update backtrace formating text tips

### PR DESCRIPTION
**Pull request by F001**
Follow up with #38165, improve consistency.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like a test needs to be updated.

```
[00:50:03] failures:
[00:50:03] 
[00:50:03] ---- [run-pass] run-pass/multi-panic.rs stdout ----
[00:50:03] 	
[00:50:03] error: test run failed!
[00:50:03] status: exit code: 101
[00:50:03] command: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/multi-panic.stage2-x86_64-unknown-linux-gnu 
[00:50:03] stdout:
[00:50:03] ------------------------------------------
[00:50:03] 
[00:50:03] ------------------------------------------
[00:50:03] stderr:
[00:50:03] ------------------------------------------
[00:50:03] thread 'main' panicked at 'assertion failed: `(left == right)` (left: `Some("note: Run with `RUST_BACKTRACE=full` for a backtrace.")`, right: `Some("note: Run with `RUST_BACKTRACE=1` for a backtrace.")`)', /checkout/src/test/run-pass/multi-panic.rs:19
[00:50:03] note: Run with `RUST_BACKTRACE=full` for a backtrace.
[00:50:03] 
[00:50:03] ------------------------------------------
[00:50:03] 
[00:50:03] thread '[run-pass] run-pass/multi-panic.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2472
[00:50:03] note: Run with `RUST_BACKTRACE=full` for a backtrace.
[00:50:03] 
[00:50:03] 
[00:50:03] failures:
[00:50:03]     [run-pass] run-pass/multi-panic.rs
[00:50:03] 
[00:50:03] test result: FAILED. 2682 passed; 1 failed; 5 ignored; 0 measured
```

**Comment by F001** [comment]
@Mark-Simulacrum Fixed. Do you have other concerns?

**Comment by Mark-Simulacrum** [comment]
Out of interest, why did you add `RUST_BACKTRACE=no` as an option? Otherwise, I'm going to leave for @arielb1 to review the heart of the changes, I don't really know this area of the compiler.

**Comment by F001** [comment]
Well, this option is not added by this PR. It has been added by the PR  #38165, but I think not all the occurrences are updated accordingly.

**Comment by alexcrichton** [comment]
Thanks for the PR! Could you expand a bit on the rationle though? I'm not sure why we'd suggest `RUST_BACKTRACE=full` to *start* with, it seems like you'd only want to reach for that if you saw a backtrace and already determined that it may not be good enough.

**Comment by F001** [comment]
The rationale is that, according to #38165, the options are defined as:

* RUST_BACKTRACE=full prints all the informations (current behaviour)
* RUST_BACKTRACE=(short|yes) is the default 
* RUST_BACKTRACE=(0|no) disables the backtrace.
* RUST_BACKTRACE=<everything else> is equivalent to short for backward compatibility.

So I think the suggestion should be updated to `RUST_BACKTRACE=(full|short|yes)`, and the old style `RUST_BACKTRACE=(1|0)` should not be the official suggestion.

I'm not sure which one is the best either, (full|short|yes) all seems reasonable to me. They are all better than (1|0).

**Comment by F001** [comment]
@alexcrichton If you think `full` is not appropriate in the suggestion, I'll update it to `yes`.

**Comment by F001** [comment]
Another alternative, use longer sentence for the suggestion: 

note: Run with `RUST_BACKTRACE=yes` for a backtrace, and run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by alexcrichton** [comment]
Ah yes sorry, so I'm not personally a fan of the simultaneous change in interface here either, I'd prefer to not change how we parse values just yet. What I'm worried about though is that this is recommending `RUST_BACKTRACE=full` *before* `RUST_BACKTRACE=1`, which seems backwards?

**Comment by F001** [comment]
Yeah, I understand your concern. Now I have changed the recommending to `RUST_BACKTRACE=yes` which has the same behavior as `RUST_BACKTRACE=1`. 

The motivation is that right now option `1` is supported only for backward compatibility, the option `short|yes` is more official with the same behavior.

I would like to hear suggestion from @Yamakaky too, do you think we should update the recommending words?

**Comment by Yamakaky** [comment]
My rational for only suggesting the short back trace was that new users will not want the full one in almost any case, and advanced users will know about the full version.

**Comment by F001** [comment]
Yeah~ I agree to suggesting the short style too. I just think `yes` is better than `1`.

**Comment by Yamakaky** [comment]
I do too! I think yes/short, full and no should be good, with the old values as compat.

**Comment by F001** [comment]
@alexcrichton PR is updated.

**Comment by alexcrichton** [comment]
Ok not recommending "full" sounds good to me, but otherwise I'm still not sure I understand the rationale for this PR? Why change from "1" to "yes"? Why add "no" as a way to turn it off?

**Comment by F001** [comment]
I thought that the options of RUST_BACKTRACE had been changed to (full|short|yes|no) as described in #38165 , and it has been an agreement in core team. But It turns out to be not true. 

I'm sorry for the confusion I caused. Therefore, I'm going to close this PR.

**Pull request closed without merging**
