### PR TITLE
[stable] 1.52.0 release

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This includes the release notes (#84183) as well as cherry-picked commits from:

* [beta] revert PR #77885 #84710
* [beta] remove assert_matches #84759 
* Revert PR 81473 to resolve (on beta) issues 81626 and 81658. #83171 
* [beta] rustdoc revert deref recur #84868 
*  Fix ICE of for-loop mut borrowck where no suggestions are available #83401 

Additionally in "fresh work" we're also:

* reverting: directly expose copy and copy_nonoverlapping intrinsics #81238 to avoid https://github.com/rust-lang/rust/issues/84297 on 1.52

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors retry

```
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 54
clang+llvm-10.0.0-x86_64-apple-darwin/include/clang/Basic/ObjCRuntime.h: Lzma library error:  No progress is possible
```

**Comment by Mark-Simulacrum** [comment]
Added revert of #81473 via backporting https://github.com/rust-lang/rust/pull/83171; some resolveable conflicts

**Comment by Mark-Simulacrum** [comment]
Alright, bundled in  [beta] rustdoc revert deref recur #84868, let's give this another go - @bors r+ rollup=never p=100

**Comment by pietroalbini** [comment]
@bors retry

Spurious

**Pull request merged**
