### PR TITLE
Cap lints for cargotest

### PR DESCRIPTION
**Pull request by sanxiyn**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you add a comment explaining why?

**Comment by alexcrichton** [comment]
otherwise r=me though

**Comment by alexcrichton** [comment]
Hm, actually, cc @brson. What're your thoughts here? Do you think we should require Cargo to be fixed upstream before landing changes to lints?

**Comment by sanxiyn** [comment]
This seems unwanted. Closing.

**Pull request closed without merging**
