### PR TITLE
Fix buffer overrun in bootstrap and (test-only) symlink_junction

### PR DESCRIPTION
**Pull request by thomcc**
I don't think these can be hit in practice, due to their inputs being valid paths. It's also not security-sensitive code, but just... bad vibes.

I think this is still not really the right way to do this (in terms of path correctness), but is no worse than it was.

r? @ChrisDenton

### CODE REVIEW

**Comment by jyn514** [comment]
Can we switch to using docs.rs/junction instead? it makes me nervous to have all this unsafe code without tests ...

**Comment by thomcc** [comment]
> Can we switch to using docs.rs/junction instead

For bootstrap that seems reasonable, done.

For std I'm less sure. Deps in std (even dev-deps) have a way of causing headaches -- I'll leave it up to the reviewer.

**Comment by albertlarsan68** [comment]
r=me on the bootstrap changes

**Comment by ChrisDenton** [comment]
I'll look at these changes in a bit but I'm definitely in favour of avoiding headaches 🙂. I think the ultimate solution is for me to finally write an ACP (which I'll do now before I forget), fix up the std function with tests and finally get it stabilized.

**Comment by ChrisDenton** [comment]
Ok this looks like an improvement, even if it's only avoiding an unlikely edge case. The new dependency looks fine for bootstrap though hopefully we can unify this code in a future libstd.

@bors r+

**Pull request merged**
