### PR TITLE
Guarantee that `char` has the same size and alignment as `u32`

### PR DESCRIPTION
**Pull request by joshlf**

### CODE REVIEW

**Comment by joshlf** [comment]
A change to add the same text to the Reference is here: https://github.com/rust-lang/reference/pull/1401

**Comment by joshtriplett** [comment]
@rfcbot merge

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by RalfJung** [comment]
Note that this does *not* imply that char and u32 are ABI compatible (i.e., they are passed between functions the same way).

That would probably make sense to guarantee by extending the list in the "fn" ptr type docs. (Needs a new PR since FCP already started here.)

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

This was discussed and is now in FCP.

**Comment by RalfJung** [comment]
> Note that this does *not* imply that char and u32 are ABI compatible (i.e., they are passed between functions the same way). That would probably make sense to guarantee by extending the list in the "fn" ptr type docs. (Needs a new PR since FCP already started here.)

I opened a PR for that: https://github.com/rust-lang/rust/pull/118032.

**Pull request merged**
