### PR TITLE
Improve `make_hash` function

### PR DESCRIPTION
**Pull request by ranma42**
The `make_hash` function is used to prevent hashes of non-empty
buckets to collide with `EMPTY_HASH = 0u64`. Ideally this function
also preserve the uniform distribution of hashes and is cheap to
compute.

The new implementation reduces the input hash size by one bit, simply
by setting the most significant bit. This obviously prevent output
hashes to collide with `EMPTY_HASH` and guarantees that the uniform
distribution is preserved. Moreover, the new function is simpler (no
comparisons, just an OR) and (under the same assumptions as the old
function, i.e. only the least significant bit will contribute to the
bucket index) no additional collisions are caused.

### CODE REVIEW

**Comment by ranma42** [comment]
I did some benchmarking on x86-64 (by stripping the call to the hasher and comparing minimal `make_hash` functions that simply use the old vs new policy). Iterating over `0..2047u64` gives:
```
running 2 tests
test b_make_hash_2048     ... bench:      1129 ns/iter (+/- 45)
test b_make_hash_new_2048 ... bench:       900 ns/iter (+/- 58)
```
On 32-bits platforms I would expect a possibly bigger improvement, because LLVM should be able to notice that the OR operation on the low word is a no-op (while to compare with `EMPTY_BUCKET` both words had to be examined).

**Comment by alexcrichton** [comment]
cc @Gankro, @pczarn, curious about your opinions on this.

**Comment by Gankro** [comment]
Do these performance changes actually make it into the actual HashMap benches?

**Comment by Gankro** [comment]
Functionality-wise this seems like a reasonable change. It should have no practical effect on truncated hash-collisions, but will double the likelihood of a "true" hash collision from "very unlikely" to "still very unlikely".

**Comment by pczarn** [comment]
The old implementation was basically a single cmov.

Pros of the new approach:
* Definitely better on 32-bit platforms.
* A little simpler.

I agree with @Gankro, there are no other pros or cons in practice.

**Comment by ranma42** [comment]
@Gankro I do not expect these performance changes (0.1 ns every time a hash is computed?) to be measurable in practical applications. The main reason I proposed this change is to simplify the function and to make it more obvious that the distribution remains uniform after making the hash "safe".

**Pull request merged**
