### PR TITLE
[WIP] Bring rust-semverver in-tree and test that it builds.

### PR DESCRIPTION
**Pull request by eddyb**
<hr/>

This PR initializes `src/tools/rust-semverver` to https://github.com/rust-dev-tools/rust-semverver/commit/0bbdabfc883a4e5c4d6dce21800b01649f0a70fa using `git subtree add`, akin to what @oli-obk did to bring `clippy` in-tree. Only the last 3 commits are mine.

I was also able to make `./x.py check src/tools/semverver` and `./x.py build src/tools/semverver` work, but for now I've kept `./x.py test src/tools/semverver` equivalent to `build` (i.e. not actually running any tests), pending actual test integration.

To get tests working I suspect we'll have to rewrite some of the test driving logic in  `src/tools/semverver/tests` to rely more on environment variables than relative paths (akin to what `clippy` does).

In order to get `rust-semverver` to build successfully in-tree, I had to work around the fact that it depends on some Cargo crates which do not build with `SourceType::InTree` (i.e. Cargo doesn't build with `-Drust_2018_idioms`), so for now it's using `SourceType::Submodule` despite that being incorrect for `src/tools/semverver` itself.

I also updated it to the latest rustc and Cargo, but I haven't tested that it still works afterwards.

r? @Mark-Simulacrum cc @ibabushkin @rust-lang/compiler @rust-lang/dev-tools @Manishearth @JohnTitor

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I guess the intent here is to ship it with rustup eventually? We'll probably want a MCP at least for this sort of change. I guess in principle this is also blocked on finishing the move to subtrees (currently I believe we're primarily waiting on some upstreaming of git patches).

**Comment by Manishearth** [comment]
The intent is to start with not having to rustup it so much but yeah, maybe ship eventually

**Comment by eddyb** [comment]
Seems to be failing on Windows now with:
```
warning: libssh2/src/wincng.c:63:28: fatal error: versionhelpers.h: No such file or directory
warning: compilation terminated.

error: failed to run custom build command for `libssh2-sys v0.2.14`
```

AFAICT this is just a dependency of Cargo, not sure how Cargo itself builds.
(I guess `x.py check` doesn't include `src/tools/cargo`? so that might also fail on the `mingw-check` builder)

**Comment by mati865** [comment]
`versionhelpers.h` is available in mingw-w64 starting from version 5.0.0, Ubuntu 16.04 ships version 4.0.4.
I think it worked previously because `mingw-check` was not building `libssh2-sys` crate.
From MinGW PoV the easiest way forward would be upgrading the builder to use newer image. Alternatively you can try bumping `libssh2-sys` and **hoping** it no longer uses that header.

**Comment by eddyb** [comment]
@mati865 I'm guessing we must have a builder that builds mingw Cargo, right? So that one was updated but the PR CI one wasn't?

**Comment by ehuss** [comment]
For Windows, Cargo is only built on native windows hosts, it is not cross-compiled on linux to windows in CI.

**Comment by mati865** [comment]
@eddyb MinGW dist builder is Windows based and CI installs mingw-w64 5.0.x (the one with `versionhelpers.h` present) on it.

**Comment by eddyb** [comment]
`mingw-check` passes now, after I changed it from Ubuntu 16.04 to 18.04, thanks @mati865 and @ehuss!

**Comment by nikomatsakis** [comment]
I am a strong supporter of us shipping this tool, but I'd like to understand the maintenance plan -- can we create a team for it under the dev-tools team, for example?

**Comment by Mark-Simulacrum** [comment]
Yes, that's one of the questions I was hoping an MCP (or similar, perhaps RFC or so) would answer.

To be clear, I've not been planning on reviewing this until someone with "T-compiler" hat on says that we're going to merge this in and we have some sort of plan for maintenance etc.

**Comment by Manishearth** [comment]
The dev tools team has been "maintenance mode" maintaining it, doing rustups. We can continue keeping an eye on it, in part one of the things we do is keep an eye out for these smaller tools. We'd need maintainers to do more

**Comment by mati865** [comment]
@eddyb I think you should split CI image bump to another PR since it's strictly infra change.

**Pull request closed without merging**
