### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #73618 (Documentation for the false keyword)
 - #74486 (Improve Read::read_exact documentation)
 - #74514 (Do not clobber RUSTDOCFLAGS)
 - #74516 (do not try fetching the ancestors of errored trait impls)
 - #74520 (include backtrace folder in rust-src component)
 - #74523 (Improve documentation for `core::fmt` internals)
 - #74527 (Add myself to toolstate change notifications for rustfmt)
 - #74534 (Only skip impls of foreign unstable traits)
 - #74536 (fix documentation surrounding the `in` and `for` keywords)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors treeclosed=6 p=6

will try and watch this

**Comment by nnethercote** [comment]
This was a big [perf loss](https://perf.rust-lang.org/compare.html?start=2c21a6f3a8b1c75c444b87fde5116853383b3fbd&end=891e6fee572009ff2be4d4057fb33483610c36a7&stat=instructions:u) on rustdoc up to 12% on many benchmarks.

@jyn514 Any idea which PRs could be responsible? I can't tell, because most or all of them involve docs.

**Comment by jyn514** [comment]
@nnethercote I expect https://github.com/rust-lang/rust/pull/74514 because it documents private items. So not actually a perf loss, just doing more work. It could also be https://github.com/rust-lang/rust/pull/74534 though.

**Comment by jyn514** [comment]
Note that these both fixed bugs introduced in https://github.com/rust-lang/rust/pull/74422 and https://github.com/rust-lang/rust/pull/74408. So it will be unfortunately very hard to figure out whether they were a net loss or not :/

**Pull request merged**
