### PR TITLE
added doc for function pointers as arguments

### PR DESCRIPTION
**Pull request by KalitaAlexey**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks!

The problem here is that at this point in the book, we have not covered structs and methods. So a lot of this can't be here...

**Comment by KalitaAlexey** [comment]
What if I add references to structs and methods sections?

**Comment by steveklabnik** [comment]
Forward references are a measure of last resort. I would prefer some other kind of solution.

This is why the section is so bare right now :smile:

**Comment by steveklabnik** [comment]
After thinking about this for a while, @KalitaAlexey , I do appreciate the PR, but don't want to add more forward references. If you can think of some other way to make this more clear, please let me know!

**Pull request closed without merging**
