### PR TITLE
The Magenta kernel is now called Zircon.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by pylaligand** [comment]
Hi there! I hope I caught all the instances, but haven't been able to run tests yet. Any guidance on how to produce appropriate test coverage would be much appreciated.

**Comment by mattico** [comment]
You can set `ALLOW_PR=1` in https://github.com/rust-lang/rust/blob/fd4bef54abafe6d93ec3c87498de696da6ef5819/.travis.yml#L98

To let you test this on travis before r+

**Comment by dtolnay** [comment]
Tier 2 platform + senior Google employee working on platform + everything in this PR only affects that platform = do what you want, I guess. 😜 r=me after removing ALLOW_PR=1.

**Comment by pylaligand** [comment]
Rebased, but it looks like I picked up some submodules changes. Not sure what to make of these.

**Comment by pylaligand** [comment]
I think I fixed the submodules issue.

**Comment by pylaligand** [comment]
@dtolnay could you approve this change? I removed the Travis testing bit and rebased.

**Comment by pylaligand** [comment]
Thanks for the approval @dtolnay. What's the next step, will the bot check the change in?

**Comment by dtolnay** [comment]
Yep, the bot will merge as soon as the build passes against the merge commit. That ensures the master branch is always a commit that has passed all CI (the ["not rocket science"](https://graydon2.dreamwidth.org/1597.html) approach to CI). I'm not really familiar with this UI but here is the current queue: https://buildbot2.rust-lang.org/homu/queue/rust

**Comment by kennytm** [comment]
The `download-toolchain` script failed on Fuchsia. There is no `unzip` command?

```
[00:05:25] + ./zircon/scripts/download-toolchain
[00:05:25] Downloading https://fuchsia-build.storage.googleapis.com/magenta/toolchain/x86_64-elf/Linux-x86_64/509cd48809f5252ffc8ef0c72dbf208151750f66
######################################################################## 100.0%
[00:05:25] Unpacking /tmp/zircon/prebuilt/downloads/x86_64-elf-Linux-x86_64.tar.bz2
[00:05:32] Downloading https://fuchsia-build.storage.googleapis.com/magenta/toolchain/aarch64-elf/Linux-x86_64/509cd48809f5252ffc8ef0c72dbf208151750f66
######################################################################## 100.0%
[00:05:32] Unpacking /tmp/zircon/prebuilt/downloads/aarch64-elf-Linux-x86_64.tar.bz2
[00:05:39] Downloading https://storage.googleapis.com/fuchsia/clang/linux-amd64/86d57720455e2d6aff2b48f9cea3ef77ab2af06a
######################################################################## 100.0%
[00:05:40] Unpacking /tmp/zircon/prebuilt/downloads/clang+llvm-x86_64-linux.zip
[00:05:40] ./zircon/scripts/download-toolchain: line 121: unzip: command not found
[00:05:40] The command '/bin/sh -c /tmp/build-toolchain.sh' returned a non-zero code: 127
```

**Comment by pylaligand** [comment]
@petrhosek see error above.

**Comment by pylaligand** [comment]
Does this need another approval or will the bot pick it up again?

**Comment by raggi** [comment]
@dtolnay thanks for plugging away with us. I just pushed a rebase and and update of liblibc, which should fix the linker failure. When I tested this locally, it looks like liblibc 0.2.31 has dependencies on other submodules that would need to be updated, but I'm not sure which ones. Would appreciate seeing if it builds in the bots, as my local build may be different.

**Comment by dtolnay** [comment]
Let's find out!

@bors r+

I checked with Alex the implications of bumping the liblibc submodule:

> should be fine to do at any time

**Comment by raggi** [comment]
The bump of the libc module had an issue that was to be fixed by PR 44515, but that PR is blocked. I chatted with Alex about it and picked in the relevant part to fix the build. My local build is still running, but I saw std build, so bots stand a chance now.

**Comment by kennytm** [comment]
So, it has spent 2 hours trying to build the docker's LLVM (*not* Rust's copy of LLVM), is this normal? Note that our CI jobs can't run more than 3 hours.

```
[00:08:10] + cd llvm
[00:08:10] + mkdir build
[00:08:10] + cd build
[00:08:10] + hide_output cmake -GNinja -DFUCHSIA_x86_64_SYSROOT=/usr/local/x86_64-unknown-fuchsia -DFUCHSIA_aarch64_SYSROOT=/usr/local/aarch64-unknown-fuchsia -DLLVM_ENABLE_LTO=OFF -DCLANG_BOOTSTRAP_PASSTHROUGH=LLVM_ENABLE_LTO -C ../tools/clang/cmake/caches/Fuchsia.cmake ..
[00:08:10] + set +x
[00:08:20] + hide_output ninja stage2-distribution
[00:08:20] + set +x
[00:08:50] Thu Sep 21 03:07:20 UTC 2017 - building ...
[00:09:20] Thu Sep 21 03:07:50 UTC 2017 - building ...
[00:09:50] Thu Sep 21 03:08:20 UTC 2017 - building ...
...
[02:14:29] Thu Sep 21 05:12:59 UTC 2017 - building ...
[02:14:59] Thu Sep 21 05:13:29 UTC 2017 - building ...
[02:15:29] Thu Sep 21 05:13:59 UTC 2017 - building ...
[02:15:59] Thu Sep 21 05:14:29 UTC 2017 - building ...
[02:16:22] shared.sh: line 11:  9356 Terminated              bash -c "while true; do sleep 30; echo \$(date) - building ...; done"
[02:16:22] + hide_output ninja stage2-install-distribution
[02:16:22] + set +x
[02:16:28] shared.sh: line 11: 10698 Terminated              bash -c "while true; do sleep 30; echo \$(date) - building ...; done"
[02:16:28] + cd ../..
```

**Comment by alexcrichton** [comment]
@bors: retry

I think that this may have enough caches populated now to go through

**Comment by kennytm** [comment]
Check: The Docker-LLVM is currently in the "building ..." stage for >1 hour. I don't think anything is cached.

https://travis-ci.org/rust-lang/rust/jobs/278254065

**Comment by raggi** [comment]
FYI - @petrhosek is going to drop another commit in here that will switch the dist-fuchsia build over to using our llvm prebuilds that we use in our platform buildtools. That should completely nullify the llvm build time, as well as bringing back some things we'd previously disabled due to build time issues, such as LTO. Should land in less than an hour. Thanks again for your patience and persistence :)

**Comment by alexcrichton** [comment]
The test failure here is a spurious test failure, but yeah if y'all want to improve the build time of the docker container that'd be great!

**Comment by kennytm** [comment]
Failed to build stage2-std on Fuchsia with error `/usr/local/bin/x86_64-unknown-fuchsia-clang: 2: /usr/local/bin/x86_64-unknown-fuchsia-clang: clang: Permission denied`. Some missing `chmod +x`?

<details>

```
[00:52:29] error: failed to run custom build command for `compiler_builtins v0.0.0 (file:///checkout/src/rustc/compiler_builtins_shim)`
[00:52:29] process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/release/build/compiler_builtins-f21bb826468eb8d0/build-script-build` (exit code: 101)
[00:52:29] --- stdout
[00:52:29] cargo:rerun-if-changed=build.rs
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/absvdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/absvsi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/absvti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/addvdi3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/addvsi3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/addvti3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/apple_versioning.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/clzdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/clzsi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/clzti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/cmpdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/cmpti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/comparedf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/comparesf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ctzdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ctzsi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ctzti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/divdc3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/divdf3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/divsc3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/divsf3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/divxc3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/extendhfsf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/extendsfdf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ffsdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ffsti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatdisf.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatdixf.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatundidf.S
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatundisf.S
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatundixf.S
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/int_util.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/muldc3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/muldf3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/mulsc3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/mulsf3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/mulvdi3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/mulvsi3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/mulvti3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/mulxc3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negdf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negsf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negvdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negvsi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/negvti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/paritydi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/paritysi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/parityti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/popcountdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/popcountsi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/popcountti2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/powixf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/subvdi3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/subvsi3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/subvti3.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/truncdfhf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/truncdfsf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/truncsfhf2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ucmpdi2.c
[00:52:29] cargo:rerun-if-changed=../../libcompiler_builtins/compiler-rt/lib/builtins/ucmpti2.c
[00:52:29] TARGET = Some("x86_64-unknown-fuchsia")
[00:52:29] OPT_LEVEL = Some("2")
[00:52:29] TARGET = Some("x86_64-unknown-fuchsia")
[00:52:29] HOST = Some("x86_64-unknown-linux-gnu")
[00:52:29] TARGET = Some("x86_64-unknown-fuchsia")
[00:52:29] TARGET = Some("x86_64-unknown-fuchsia")
[00:52:29] HOST = Some("x86_64-unknown-linux-gnu")
[00:52:29] CC_x86_64-unknown-fuchsia = Some("x86_64-unknown-fuchsia-clang")
[00:52:29] TARGET = Some("x86_64-unknown-fuchsia")
[00:52:29] HOST = Some("x86_64-unknown-linux-gnu")
[00:52:29] CFLAGS_x86_64-unknown-fuchsia = Some("-ffunction-sections -fdata-sections -fPIC --target=x86_64-unknown-fuchsia")
[00:52:29] DEBUG = Some("false")
[00:52:29] running: "x86_64-unknown-fuchsia-clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-unknown-fuchsia" "--target=x86_64-unknown-fuchsia" "-fno-builtin" "-fvisibility=hidden" "-fomit-frame-pointer" "-ffreestanding" "-DVISIBILITY_HIDDEN" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/build/compiler_builtins-312803e36a222f71/out/../../libcompiler_builtins/compiler-rt/lib/builtins/absvdi2.o" "-c" "../../libcompiler_builtins/compiler-rt/lib/builtins/absvdi2.c"
[00:52:29] cargo:warning=/usr/local/bin/x86_64-unknown-fuchsia-clang: 2: /usr/local/bin/x86_64-unknown-fuchsia-clang: clang: Permission denied
[00:52:29] exit code: 126
[00:52:29] 
[00:52:29] --- stderr
[00:52:29] thread 'main' panicked at '
[00:52:29] 
[00:52:29] Internal error occurred: Command "x86_64-unknown-fuchsia-clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-unknown-fuchsia" "--target=x86_64-unknown-fuchsia" "-fno-builtin" "-fvisibility=hidden" "-fomit-frame-pointer" "-ffreestanding" "-DVISIBILITY_HIDDEN" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/build/compiler_builtins-312803e36a222f71/out/../../libcompiler_builtins/compiler-rt/lib/builtins/absvdi2.o" "-c" "../../libcompiler_builtins/compiler-rt/lib/builtins/absvdi2.c" with args "x86_64-unknown-fuchsia-clang" did not execute successfully (status code exit code: 126).
[00:52:29] 
[00:52:29] ', /cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:4
[00:52:29] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:52:29] 
[00:52:29] warning: build failed, waiting for other jobs to finish...
[00:52:42] error: build failed
[00:52:42] thread 'main' panicked at 'command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-fuchsia" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:52:42] expected success, got: exit code: 101', /checkout/src/bootstrap/compile.rs:883:8
[00:52:42] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

</details>

**Comment by raggi** [comment]
Rebased and fixed up, I think those changes might even fix our build issue. Ever hopeful.

**Comment by dtolnay** [comment]
If you need to push any more changes and the new changes only affect the fuchsia target, leave a comment `@bors r=dtolnay` and the bot will build it without waiting for me to review.

**Comment by dtolnay** [comment]
Oh I didn't know about that. I will try to find out whether there is a way to delegate review permission.

@bors r+

**Comment by raggi** [comment]
Thanks again folks for all your patience and assistance.

**Pull request merged**
