### PR TITLE
Remove `IdFunctor` trait.

### PR DESCRIPTION
**Pull request by nnethercote**
It's defined in `rustc_data_structures` but is only used in
`rustc_type_ir`. The code is shorter and easier to read if we remove
this layer of abstraction and just do the things directly where they are
needed.

r? @BoxyUwU

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time.

Shouldn't affect speed, but let's check because the type folding code is hot:

@bors try @rust-timer queue

**Comment by compiler-errors** [comment]
pls fix CI by adding `allocator_api` back, then r=me

**Comment by nnethercote** [comment]
> pls fix CI by adding `allocator_api` back, then r=me

Done.

@bors r=compiler-errors

**Comment by compiler-errors** [comment]
spurious?

@bors retry

**Pull request merged**
