### PR TITLE
Wrap cast expressions inside of ValueTypeAscription

### LINKED ISSUE #54332: NLL should respect lifetimes in `as` expressions
Spawned off from https://github.com/rust-lang/rust/issues/47184. The following test case compiles, but it should not:

```rust
#![allow(warnings)]
#![feature(nll)]

fn main() {
    let x = 22_u32;
    let y: &u32 = (&x) as &'static u32;
}
```

The problem is that the "cast" expression is not preserving the full type that the user gave (`&'static u32`). 

This is very similar to https://github.com/rust-lang/rust/issues/54331

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #54332.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
i'm curious to see whether travis is happier now

**Comment by nikomatsakis** [comment]
Welp, we have our answer. =)

**Comment by matthewjasper** [comment]
Isn't there an issue open for deduplicating these messages? cc @oli-obk

**Comment by oli-obk** [comment]
Are you looking for https://github.com/rust-lang/rust/pull/53821 ? that PR deduplicates all const eval error reporting

**Comment by nikomatsakis** [comment]
Could that be the problem here?

**Comment by oli-obk** [comment]
I don't think so. This change changes the way the HAIR is structured for casts, thus having an effect on the generated MIR. I don't know what effect, but it looks to me like it causes the MIR to mention a constant twice, thus it being evaluated twice via https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/const_prop.rs#L256

This can easily be verified by generating the MIR of one of the failing tests before and after this PR.

**Comment by nikomatsakis** [comment]
Subsumed into https://github.com/rust-lang/rust/pull/55152

@oli-obk 

> but it looks to me like it causes the MIR to mention a constant twice

oh I can definitely imagine how this would happen — we are now adding a MIR annotation that "asserts" that the constant has a given, user-provided type. Is this then "ok"? Maybe answer in #55152 though :P

**Pull request closed without merging**
