### PR TITLE
libsyntax: fix for `has_test_signature`

### PR DESCRIPTION
**Pull request by blackbeam**
Fix for `error: functions used as tests must have signature fn() -> ()` and `error: functions used as benches must have signature fn(&mut Bencher) -> ()` in case of explicit return type declaration.

Currently

``` rust
#[test]
fn some_test() -> () {}
```

will produce:

```
error: functions used as tests must have signature fn() -> ()
```

which is definitely wrong.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r-

er actually, could you add a test for this case as well?

**Comment by blackbeam** [comment]
@alexcrichton Not sure that github notifies about added commits. re-r?

**Comment by alexcrichton** [comment]
@bors: r+ fd02920 rollup

Thanks!

**Comment by blackbeam** [comment]
@alexcrichton I have just fixed the test. Another WCPGW problem, sorry..

**Comment by frewsxcv** [comment]
Needs a rebase

**Comment by blackbeam** [comment]
All except e5b991a (because of 577c464) was merged by #21582.
I think i should close this.

**Pull request closed without merging**
