### PR TITLE
Choose an appropriate python version for x.py at runtime

### LINKED ISSUE #71818: Rust doesn't build without "python" name being available
Since Ubuntu 20.04, the name `python` [no longer available by default](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default) without `python-is-python2` package being installed. The build scripts should point to `python2` instead.

### PR DESCRIPTION
**Pull request by jyn514**
*Or, how I learned to stop worrying and love the shell.*

image

- Start `x.py` as a shell script and re-execute the program with the right python interpreter
- Default to python3 -> python -> python2

Closes https://github.com/rust-lang/rust/issues/71818.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by jyn514** [comment]
I found that this breaks on CentOS because it doesn't have `which` available. I'll use `command -v` instead.

**Comment by jyn514** [comment]
This breaks in Powershell (probably cmd.exe too, but I don't know how to install that on linux):

```
ResourceUnavailable: Program 'x.py' failed to run: Exec format errorAt line:1 char:1
+ ./x.py check
+ ~~~~~~~~~~~~.
```

**Comment by jyn514** [comment]
It looks like servo handles this by having a separate `mach.bat` bootstrap script, which seems unfortunate :/

**Comment by nagisa** [comment]
Are you sure this isn't missing a shebang for shell of some sort?

Running `./x.py` on a NixOS system with this PR does not work:

```
$ git checkout origin/master
$ ./x.py
info: Downloading and building bootstrap before processing --help
      command. See src/bootstrap/README.md for help with common
      commands.
Updating only changed submodules
Updating submodule src/llvm-project
<snip>
$ git checkout origin/pr/80585
$ ./x.py
Failed to execute process './x.py'. Reason:
exec: unknown error (errno was 8)
The file './x.py' is marked as an executable but could not be run by the operating system.
```

**Comment by jyn514** [comment]
@nagisa most shells will execute files as scripts if they don't have a shebang, what shell are you using?

That said, if this doesn't work even on linux, it's probably not worth pursuing.

**Comment by nagisa** [comment]
I use `fish` and various non-shell uses would probably break as well.

**Pull request closed without merging**
