### PR TITLE
Revert #83357 and achieve the same impact on serde-json by adding a check in Vec::spec_extend

### PR DESCRIPTION
**Pull request by saethlin**

### CODE REVIEW

**Comment by saethlin** [comment]
r? @dtolnay 
@rylev @klensy per https://github.com/rust-lang/rust/pull/83357#issuecomment-811770400

**Comment by saethlin** [comment]
I do not know why this is slower. I'm going to stand up the rustc-perf benchmarking locally and try to figure this out.

**Comment by the8472** [comment]
Note that there have been some changes to the spec_extend code path since #83357 so stuff may optimize differently now compared to when the last perf run was made. Maybe measure the revert and the new check separately.

**Comment by saethlin** [comment]
I'm just more confused now. There's evidence posted in https://github.com/rust-lang/rust/pull/83357 that it was a regression, but now undoing it is also a regression??

**Comment by the8472** [comment]
Oh, the link in https://github.com/rust-lang/rust/pull/83357#issuecomment-810104757 points to the max-rss report, not instructions (the default).

max-rss tends to be noisy, but the reverts seem to be biased towards an improvement, i.e. it recovers the max-rss regression but also undoes the compile time improvements.

**Comment by saethlin** [comment]
Wow I was really looking in the wrong direction.

I have no idea why max-rss would be impacted by these changes. My instinct is that blaming a max-rss regression on #83357 is a mistake; it doesn't change when and with what arguments any allocator is invoked. If it changes the size of anything, it should reduce code size.

**Comment by the8472** [comment]
> Wow I was really looking in the wrong direction.
> 
> I have no idea why max-rss would be impacted by these changes. My instinct is that blaming a max-rss regression on #83357 is a mistake; it doesn't change when and with what arguments any allocator is invoked. If it changes the size of anything, it should reduce code size.

The PR was not part of a rollup, so the perf runs are a direct comparison with its parent commit. And we have three comparisons now and all point in the same direction so that makes it less likely to be noise.

`Vec` code is a significant fraction of all code, vec iterator code doubly so, due to monomorization. So things are really sensitive to changes there.

So, reverting fixes the memory footprint issue. But it also undoes the instruction count improvements on some of the parts that involve little to no heavy lifting on the LLVM side (e.g. `-check` runs), so they're probably not due to more IR being generated but due to something else in the compiler returning to less efficient code.

So perhaps run one of the non-opt benchmarks under `perf` and see what code in the compiler is affected and whether we could improve the performance without the max-rss increase.

One possibility might be that you focused only on `extend` while the `reserve` changes had a broader impact.

**Comment by the8472** [comment]
@saethlin do the serde speedups mostly come from `Extend` or `FromIterator` improvements? If it's about the latter then I think we can get `reserve` out of some `FromIterator` code paths.

**Comment by saethlin** [comment]
@the8472 The `serde` improvement(s) come from making `std::io::Write::write_all` into a `Vec<u8>` cheaper. I believe that forwards down to the `SpecExtend` code path I was poking at in this PR, or at least that's what benchmarking indicates.

**Comment by the8472** [comment]
https://github.com/rust-lang/rust/blob/c051c5ddda79f45fad196ca3a4690251e377d043/library/std/src/io/impls.rs#L384-L387

calls

https://github.com/rust-lang/rust/blob/c051c5ddda79f45fad196ca3a4690251e377d043/library/alloc/src/vec/mod.rs#L2118-L2120

which should specialize to

https://github.com/rust-lang/rust/blob/c051c5ddda79f45fad196ca3a4690251e377d043/library/alloc/src/vec/spec_extend.rs#L83-L86

calls

https://github.com/rust-lang/rust/blob/c051c5ddda79f45fad196ca3a4690251e377d043/library/alloc/src/vec/mod.rs#L1693-L1700


So there's a reserve, but it's not the one in spec_extend that's relevant if you want to optimize serde.
And we should collapse some of that call-chain.

I think that warrents a few separate PRs. One for serde improvements. One purely for the revert, assuming the libs team prefers to keep `max-rss` low at the expense of the `instructions:u` losses (that pretty much seems to be the trade-off here).
And then I have an idea how to avoid one or two `reserve` calls which might claw back some of the instruction count losses.

**Comment by nnethercote** [comment]
FWIW, I made a bunch of improvements to these code paths last year to reduce code size. At first the changes gave obvious improvements, but by the end things were getting unpredictable and it was hard to improve some things without regressing other things.

**Comment by saethlin** [comment]
I was never sure what the next steps were on here, and the codebase seems to have moved on a bit. I'm still here, but this PR isn't really.

**Pull request closed without merging**
