### PR TITLE
Implement Try, Neg, and FromIterator<Ordering> for Ordering

### PR DESCRIPTION
**Pull request by balt-dev**
This adds implementations of `Try`, `Neg`, and `FromIterator<Ordering>` to `Ordering`.
Note that since trait implementations cannot be marked as unstable, upon merging, this would instantly be stabilized.

### CODE REVIEW

**Comment by balt-dev** [comment]
Interesting, I never got the error about `CURRENT_RUSTC_VERSION` on my machine. One second.

**Comment by balt-dev** [comment]
The `Try` and `Neg` implementations can be removed if deemed too frivolous, but the `FromIterator` implementation seems quite useful.

**Comment by tgross35** [comment]
This should get an ACP first to discuss what exact new API make sense without worrying about the implementation. That is in issue template at https://github.com/rust-lang/libs-team/issues.

@rustbot label -T-libs +T-libs-api

**Comment by balt-dev** [comment]
Thank you!

**Comment by balt-dev** [comment]
I'll go ahead and close this for now until that gets sorted out.

**Pull request closed without merging**
