### PR TITLE
Revert #107834

### PR DESCRIPTION
**Pull request by Kobzol**
This reverts commit [41c6c5d4996728b5a635319ef9b077a3d0ccc480](https://github.com/rust-lang/rust/pull/107834) and https://github.com/rust-lang/rust/pull/107956. Trying to check if this fixes building `rustc` for perf bot.

### CODE REVIEW

**Comment by lqd** [comment]
This should "fix it" in the sense that `rustfmt` will no longer be copied into perf.rlo `target/` folder. The different reverts have probably caused it to stay copied in the server, so we may want to clean that up. I believe that's why the error changed from being about the other PR to this one.

I also think the reverted PR is buggy anyways so I'll try to fix it.

**Comment by Kobzol** [comment]
Good point, the fact that the error has changed is probably because of the file that is now there. In any case, we should find the smallest revert that will get us to a working bootstrap, and then later fix the rustfmt copy issue.

**Comment by lqd** [comment]
Yeah, but the reverts are unfortunately mixed in with unknown persistent changes to the server and the reverted PR didn't break things by itself it seems, so reverting it would only fix the current state of things as a side-effect of not relying on the dirty folderon the server ? Maybe reverting both is safer. We should probably check the reverts locally to get that info though.

**Comment by Kobzol** [comment]
@bors try @rust-timer queue

Indeed it looks like both PRs cause problems, at least with the current contents of the `target` directory on `rustc-perf`. Let's see if reverting both at once helps.

**Comment by lqd** [comment]
I believe it should help indeed: the presence of the `rustfmt`  in `./target` would now be irrelevant to bootstrap, and avoid the current error. 

(I also have a local bootstrap fix for that error)

**Comment by Kobzol** [comment]
It works now. The bootstrap timings are missing, but that's only because the base commit didn't have them. Comparing thr last run vs an older nightly (e.g. 2022-02-10) shows bootstrap diff. And the error has also disappeared from the status page.

I propose to merge this and then apply @lqd's fix and then re-apply the stage0 PR, after it's also fixed.

**Comment by lqd** [comment]
In theory, reverting #107956 and landing #108316 should also fix it (🤞) -- it does work locally, the symlink won't be recreated if it already exists. If we revert both #107956 and #107834 here, then that fix can be integrated into a future PR without any time pressure, to re-land #107834 in some form.

**Comment by Kobzol** [comment]
We know that this works, so I'd merge it ASAP and then land your fix to reapply the rustfmt PR. But both works, I'll let you decide :)

**Comment by albertlarsan68** [comment]
I think making sure perf works is the most important.
Cc @jyn514 
@bors r+ p=1 rollup=never

**Pull request merged**
