### PR TITLE
Remove negate_unsigned feature gate

### LINKED ISSUE #29645: Tracking issue for `negate_unsigned` feature
Allows negation of unsigned integers. Tracking for stabilization/deprecation.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes  #29645

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you also squash the commits down into one?

**Comment by rkruppe** [comment]
This will break nightly programs that use the `negate_unsigned` feature, right? If so, please throw a `[breaking-change]` in the PR description or in one of the commit messages.

**Comment by oli-obk** [comment]
squashed, added `[breaking-change]` and rewrote the help message

**Comment by ollie27** [comment]
I think the help message should mention `.wrapping_neg()` because it matches the behaviour of the current unsigned negation and can't overflow.

**Comment by pnkfelix** [comment]
@ollie27 I am not sure if `wrapping_neg` is a `const fn`, so such a message could be misleading in a const expression context. .. still there might be a way to phrase the suggestion (or only emit it in non const contexts? )

**Comment by pnkfelix** [comment]
The Travis failures look legitimate

**Comment by oli-obk** [comment]
fixed tidy errors and adjusted the second test's help messages

**Comment by cmr** [comment]
I really don't want this to be removed. Unsigned negation can be quite useful when bit twiddling (I just used it in a PCI driver), and the equivalent "!val + 1" is really strange compared to most other systems code.

**Comment by steveklabnik** [comment]
@bors: r-

this failed the rollup

**Comment by pnkfelix** [comment]
@oli-obk looks like it needs to be updated to use the new structured error API for the `span_note` call?

**Comment by oli-obk** [comment]
rebased and fixed

**Pull request merged**
