### PR TITLE
Add connect_from methods to TcpStream

### PR DESCRIPTION
**Pull request by valaphee**
When having multiple ip addresses assigned, it is not possible to use a specific one when establishing a TCP connection. `connect_from` solves this allowing to use a specific ip to bind first.

Solves https://github.com/rust-lang/rust/issues/68053

### CODE REVIEW

**Comment by valaphee** [comment]
?r

**Comment by the8472** [comment]
As mentioned in https://github.com/rust-lang/rust/issues/68053#issuecomment-572558291 I think this API is too inflexible for the many ways that sockets can be built up and adding use cases one method at a time will likely lead to bad API design.
Compare to the [Socket2](https://docs.rs/socket2/0.5.5/socket2/struct.Socket.html) API surface for example.

Imo this requires discussion about the overall design we're aiming for and whether there could be intermediate steps. [Filing an ACP](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html) could be a start.

**Comment by valaphee** [comment]
I agree that its to inflexible, and could ultimately be replaced by a more flexible socket api in general.

Isn't there already an ACP for a socket api overhaul?

**Comment by the8472** [comment]
Oh right, there was a somewhat related request in https://github.com/rust-lang/libs-team/issues/66 which was about unbound UDP sockets.

**Comment by JohnCSimon** [comment]
@valaphee 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
