### PR TITLE
Fixes #30873

### LINKED ISSUE #30873: Bitrig tests are failing.
There's some test failures related to linking command problems.

### PR DESCRIPTION
**Pull request by dhuseby**
fixes the failing bitrig unit tests.

### CODE REVIEW

**Comment by dhuseby** [comment]
@brson the change in file  src/libstd/lib.rs fixes deprecation warnings on all of the bsd platforms.  I'm pretty sure that the dynamic_lib module is only used on Linux and Windows, but please double check me on that.  Thanks!

**Comment by alexcrichton** [comment]
`dynamic_lib` is actually required on all platforms for the compiler as it's how we load plugins currently, so perhaps that could stick around?

**Comment by dhuseby** [comment]
@alexcrichton ah, i see this:
```
librustc_plugin/lib.rs:61:#![feature(dynamic_lib)]
librustc_plugin/load.rs:111:        use std::dynamic_lib::DynamicLibrary;
librustdoc/lib.rs:22:#![feature(dynamic_lib)]
librustdoc/plugins.rs:15:use std::dynamic_lib as dl;
librustdoc/test.rs:15:use std::dynamic_lib::DynamicLibrary;
```

is this what you're talking about?

**Comment by dhuseby** [comment]
let me remove that part from the patch.

**Comment by dhuseby** [comment]
@alexcrichton alright, i removed the conditional compile.

**Pull request merged**
