### PR TITLE
Remove `AccumulateVec` and its uses.

### PR DESCRIPTION
**Pull request by nnethercote**
It's basically just a less capable version of `SmallVec`.

FWIW, the only use of `ArrayVec` is now within `HybridIdxSet`.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Did this forget the removal of the accumulate_vec file itself?

**Comment by nnethercote** [comment]
> Did this forget the removal of the accumulate_vec file itself?

Yes! I will fix that on Monday.

**Comment by eddyb** [comment]
Also, could it be possible to be cc'd on PRs that involve performance-related code? I only saw this PR randomly. Maybe the whole of @rust-lang/wg-compiler-performance? (but others might not like it)

**Comment by Zoxc** [comment]
@nnethercote Rebase and run `x.py build` locally to update `Cargo.lock`

**Comment by nnethercote** [comment]
I'm confused... I definitely already did `./x.py build` locally, and the `Cargo.lock` file is updated appropriately within the commit, AFAICT. And the try push succeeded...

**Comment by nnethercote** [comment]
@rust-timer build b076004c94cf91fbebec0c238ca3618c6b4b7d8e

**Comment by nnethercote** [comment]
The perf results all look like noise. Unsurprising, because rustc now uses the `SmallVec` from crates.io, which has the same optimization when creating from an iterator that `AccumulateVec` has.

r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Agreed that perf is probably noise. @bors r+

**Comment by Mark-Simulacrum** [comment]
Agreed that perf is probably noise. @bors r+

**Comment by Mark-Simulacrum** [comment]
Agreed that perf is probably noise. @bors r+

**Comment by Mark-Simulacrum** [comment]
Agreed that perf is probably noise. @bors r+

**Comment by eddyb** [comment]
> Unsurprising, because rustc now uses the SmallVec from crates.io, which has the same optimization when creating from an iterator that AccumulateVec has.

Oh, that makes sense. I didn't realize that happened!

**Pull request merged**
