### PR TITLE
library: core::str::lines: Fix handling of trailing bare CR

### PR DESCRIPTION
**Pull request by ijackson**
E.g., split `"bare\r"` into the single line `"bare\r"`, not `"bare"`.

The documentation for this function says that only LF or CR-LF count as newlines.  So a bare CR is not a line ending, and must not be stripped.

This fix is a behavioural change, even though it brings the behaviour into line with the documentation, and into line with that of `std::io::BufRead:;lines()`.

It seems unlikely that anyone is relying on this bug, but I'm not sure how to rule it out. Perhaps this should have an FCP or a crater run or something.  It should definitely be in the release notes.

This is an alternative to #91051, which proposes to document rather than fix the behaviour.

Also add some tests of edge cases.  I felt they were useful for the docs so I made them doctests.

As for the implementation: the current version doesn't give the map closure the right information, so we need to use` split_inclusive`.  After that, we can reuse the logic in the new `str::trim_newline`.

Currently that is not merged yet, so this branch is on top of #91047.

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
I'd be happy to propose FCP to T-libs-api, but I would prefer not to bundle a new public `trim_newline` method into this fix. Could that please be removed from this PR?

**Comment by ijackson** [comment]
> I'd be happy to propose FCP to T-libs-api, but I would prefer not to bundle a new public `trim_newline` method into this fix. Could that please be removed from this PR?

I had expected #91047 (`trim_newline`) to be uncontroversial, and therefore to be merged fairly quickly (ie, before this MR).  That's why this branch is on top of that one: if #91047 had been merged then this MR would no longer contain the addition of `trim_newline`.

 I'm not sure precisely why #91047 is stalled but if you prefer I can remove the `pub` from `trim_newline` here, and then if this MR goes in first, #91047's branch can be turned into "make this internal function pub".  Doing it this way would mean #91047 ought to wait further, on the FCP here, to because otherwise  merging #91047 would generate a merge conflict here.

**Comment by Dylan-DPC** [comment]
@ijackson whats the update on this?

**Review by dtolnay — COMMENTED** [review]
I'll close this so that anyone else interested in resolving #94435 isn't deterred by there already being an old existing PR.

We'll need a PR that fixes the issue while exposing no novel standard library APIs.

**Pull request closed without merging**
