### PR TITLE
Correct a typo in fs::File::create documentation

### PR DESCRIPTION
**Pull request by cryptoquick**
Hi, I think this is a typo, but feel free to close if it isn't.

### CODE REVIEW

**Comment by clubby789** [comment]
The existing link seems correct, as [`OpenOptions::open`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.open) details error behaviour, whereas `[OpenOptions::create`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.create) does not.

**Comment by cryptoquick** [comment]
@clubby789 It's not clear if the sentence I've changed refers to error behavior; I understood it to mean that this method is similar to the corresponding OpenOptions builder method.

**Comment by ChrisDenton** [comment]
Hm, I don't think the [`OpenOptions::create`](https://doc.rust-lang.org/nightly/std/fs/struct.OpenOptions.html#method.open) documentation is particularly useful to understanding the `File::create` method. Here's the current documentation for `OpenOptions::create`:

> Sets the option to create a new file, or open it if it already exists.
>
> In order for the file to be created, [OpenOptions::write](https://doc.rust-lang.org/nightly/std/fs/struct.OpenOptions.html#method.write) or [OpenOptions::append](https://doc.rust-lang.org/nightly/std/fs/struct.OpenOptions.html#method.append) access must be used.

The documentation for [`OpenOptions::open`](https://doc.rust-lang.org/nightly/std/fs/struct.OpenOptions.html#method.open) does provide more relevant information that isn't available in `File::create`  whereas `OpenOptions::create` does not.

So I don't think this is a typo. However, maybe it could be mentioned that `File::create` is a shorthand for `OpenOptions::new().write(true).create(true).truncate(true).open(path)`.

**Comment by Dylan-DPC** [comment]
Closing this pr based on the [comment](https://github.com/rust-lang/rust/pull/106339#issuecomment-1372172764)

**Pull request closed without merging**
