### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/42006
- https://github.com/rust-lang/rust/pull/41904

Bumps the version so we get a new beta.

@sfackler libs backports here

@nikomatsakis there are several other nominated PRs that don't cherry-pick cleanly: https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3Abeta-nominated+is%3Aclosed. Can you take a look or recruit someone else to?

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* crates.io failure https://github.com/rust-lang/rust/issues/42118

**Comment by Mark-Simulacrum** [comment]
No, bors, I really did mean p=20, not rollup...

@bors p=20

**Comment by Mark-Simulacrum** [comment]
@bors -rollup

I think this is the syntax I might've seen @steveklabnik use.

**Pull request merged**
