### PR TITLE
Miscellaneous inlining improvements

### PR DESCRIPTION
**Pull request by nnethercote**
These commits inline some hot functions that aren't currently inlined, for some speed wins.

r? @Centril

### CODE REVIEW

**Comment by nnethercote** [comment]
The try push failed due to a disk being full. Let's try again.

@bors try

**Comment by nnethercote** [comment]
Local `check` results are good, mostly benefiting short-running benchmarks.
```
helloworld-check
        avg: -4.4%      min: -5.0%      max: -4.0%
deeply-nested-check
        avg: -2.8%      min: -4.3%      max: -1.9%
issue-46449-check
        avg: -3.4%      min: -4.2%      max: -2.8%
unify-linearly-check
        avg: -3.4%      min: -4.2%      max: -2.4%
trait-stress-check
        avg: -1.5%      min: -4.1%      max: -0.1%
await-call-tree-check
        avg: -3.0%      min: -4.0%      max: -2.2%
wf-projection-stress-65510-che...
        avg: -1.1%      min: -2.9%      max: -0.1%
regression-31157-check
        avg: -1.6%      min: -2.5%      max: -0.8%
tokio-webpush-simple-check
        avg: -1.3%      min: -1.8%      max: -0.8%
token-stream-stress-check
        avg: -1.3%      min: -1.3%      max: -1.2%
webrender-wrench-check
        avg: -0.9%      min: -1.2%      max: -0.5%
clap-rs-check
        avg: -0.6%      min: -1.2%      max: 0.2%
wg-grammar-check
        avg: -0.6%      min: -1.2%      max: -0.3%
ripgrep-check
        avg: -0.8%      min: -1.1%      max: -0.4%
inflate-check
        avg: -0.4%      min: -1.1%      max: -0.1%
futures-check
        avg: -0.7%      min: -1.0%      max: -0.3%
encoding-check
        avg: -0.7%      min: -0.9%      max: -0.4%
coercions-check
        avg: -0.6%?     min: -0.9%?     max: -0.3%?
tuple-stress-check
        avg: -0.2%      min: -0.8%      max: 0.0%
regex-check
        avg: -0.7%      min: -0.8%      max: -0.3%
syn-check
        avg: -0.5%      min: -0.7%      max: -0.3%
unicode_normalization-check
        avg: -0.3%      min: -0.7%      max: -0.1%
piston-image-check
        avg: -0.5%      min: -0.7%      max: -0.2%
hyper-2-check
        avg: -0.4%      min: -0.6%      max: -0.2%
keccak-check
        avg: -0.2%      min: -0.5%      max: -0.1%
webrender-check
        avg: -0.4%      min: -0.5%      max: -0.2%
html5ever-check
        avg: -0.3%      min: -0.5%      max: -0.1%
unused-warnings-check
        avg: -0.3%      min: -0.4%      max: -0.2%
deep-vector-check
        avg: -0.2%      min: -0.4%      max: -0.2%
serde-check
        avg: -0.2%      min: -0.3%      max: -0.1%
cranelift-codegen-check
        avg: -0.2%      min: -0.3%      max: -0.1%
ucd-check
        avg: -0.1%      min: -0.3%      max: 0.1%
cargo-check
        avg: -0.2%      min: -0.3%      max: -0.1%
script-servo-check
        avg: -0.2%      min: -0.3%      max: -0.1%
serde-serde_derive-check
        avg: -0.2%      min: -0.2%      max: -0.1%
style-servo-check
        avg: -0.2%      min: -0.2%      max: -0.1%
ctfe-stress-4-check
        avg: -0.1%?     min: -0.2%?     max: -0.1%?
packed-simd-check
        avg: -0.1%      min: -0.1%      max: -0.0%
```

**Comment by Centril** [comment]
r=me with positive perf numbers, etc. etc.

**Comment by bjorn3** [comment]
There are many improvements, but syn-opt regressed.

**Comment by mati865** [comment]
@bjorn3 could be noise: https://github.com/rust-lang/rust/issues/69060

**Comment by nnethercote** [comment]
Yes, `syn` is known to be noisy, that's why it has a `?` next to the numbers in the table. (See the warning at the top of the page for more explanation.)

Furthermore, this change affects compiler front-end code so if there was a genuine regression for `syn` it should show up for `syn-debug` and `syn-check` benchmarks too.

@bors r=Centril

**Pull request merged**
