### PR TITLE
Update the stdarch submodule

### PR DESCRIPTION
**Pull request by sayantn**
cc @tgross35 @Amanieu 
r? @tgross35 

try-job: dist-various-2

### CODE REVIEW

**Comment by tgross35** [comment]
Let’s see if the full job hits any errors.

@bors try

**Comment by tgross35** [comment]
This PR only updates to https://github.com/rust-lang/stdarch/commit/443063a317a010d9362390ce86c6320c61244d8b, which is probably alright as long as there is nothing added more recently.

The x86 dist job [passed](https://github.com/rust-lang-ci/rust/actions/runs/10188611515/job/28185085916) before the test was removed. Let's try just this with rfl.

@bors try

**Comment by tgross35** [comment]
Some additional context - this was split off of https://github.com/rust-lang/rust/pull/117468 which seems to have failed the RFL job in CI.

**Comment by tgross35** [comment]
The latest push just split commits (as requested), this still updates to stdarch 443063a317a010d9362390ce86c6320c61244d8b.

Tests seem to pass for this submodule update, and this was already approved in https://github.com/rust-lang/rust/pull/117468.

@bors r+

**Comment by tgross35** [comment]
@bors r-

Uncertain but it seems like this failed https://github.com/rust-lang/rust/pull/128518

**Comment by workingjubilee** [comment]
Oh amazing.

**Comment by sayantn** [comment]
There are also some uses of it in rustfmt (in `tests/{source, target}/cfg-if`)

**Comment by tgross35** [comment]
Once https://github.com/rust-lang/rust/pull/128528 merges you can rebase and we can retry.

**Comment by tgross35** [comment]
I guess this doesn't need a rebase just to test.

@bors try

**Comment by tgross35** [comment]
@bors r-

Another failure unfortunately https://github.com/rust-lang/rust/pull/128608#issuecomment-2267099257

**Comment by tgross35** [comment]
Typo in the job name

@bors try

**Comment by Kobzol** [comment]
Any idea why this would regress perf.?

**Comment by sayantn** [comment]
Can be a fluke, there was no changes to the compiler (quite a few intrinsics, about 1500, were implemented in this period, that may affect it)

**Comment by Kobzol** [comment]
It doesn't *seem* like noise, but it's also quite small and limited to a single primary benchmark + doc builds. Probably not much that we can do about this. Marking as triaged.

@rustbot label: +perf-regression-triaged

**Comment by lqd** [comment]
It's likely the usual "libstd changes and slows things down" because of more metadata for the new intrinsics, documentation _in_ the metadata, etc. Remember that just the documentation of the thousands of stdarch intrinsics are taking a big chunk of libcore/libstd metadata.

**Pull request merged**
