### PR TITLE
Add readln macro

### PR DESCRIPTION
**Pull request by sa-**
This gets the ball rolling faster for experienced programmers who are new to rust.

Usage:
```
let input = readln!();
println!("You entered {}", input);
```

### CODE REVIEW

**Comment by sfackler** [comment]
I'm not sure I understand why this needs to be a macro as opposed to a normal function?

**Comment by sa-** [comment]
It's consistent with the decision for println! to be a macro instead of a function

**Comment by sfackler** [comment]
Println is a macro because it needs to be to be able to validate the syntax at compile time.

**Comment by sa-** [comment]
Consistent in terms of the interface. Seems fitting to use `readln!()` the same way you would use `println!()`

However I'm new to the rust world and I'm open to suggestions

**Comment by steveklabnik** [comment]
> However I'm new to the rust world and I'm open to suggestions

Hey @sa- ! Thanks for this! Unfortunately, adding a macro like this is considered a major change, as macros are *global* and *instantly stable*, so there's a high bar. For changes like this, stuff has to go through our RFC process instead of just a PR. You can find that here: https://github.com/rust-lang/rfcs

As such, I'm going to give this one a close. Please pursue this over there, thank you!

**Pull request closed without merging**
