### PR TITLE
Enabled the `vec![]` macro to use the `[a; b]` repeat syntax.

### LINKED ISSUE #15587: `vec![]` should support the `[value, ..repeat]` syntax
Rust now supports `[]` in macro invocations, with a driving use case being able to write `vec![0, 0, 0]` as analogy to the fixed sized vector syntax `[0, 0, 0]`. 

However, there is no analogy to the `[0, ..n]` repeat syntax for it: `vec![0, ..n]` does not work.

~~For it to be added, `vec!` would either need to become a procedural macro, or something like https://github.com/rust-lang/rfcs/pull/88 needs to be implemented.~~

### PR DESCRIPTION
**Pull request by Kimundi**
Closes #15587

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'm ok with this, but @aturon had worries about `vec!` on #20657, so I'd like to run this by him.

**Comment by aturon** [comment]
My worries were just about stabilizing it at all (given that we might want something more general). But that seems unlikely to land soon enough, and we should probably avoid breaking code using `vec`. I'm fine with this change.

**Comment by aturon** [comment]
Note that this is a nice replacement for `from_elem`.

**Comment by Kimundi** [comment]
Yeah, the `from_elem` use case is what reminded me about this. Though `vec![a; b]` is more restrictive since it demands `a: Copy` and `constexpr` `b`, but that should still cover a lot.

**Comment by nikomatsakis** [comment]
Nifty.

**Pull request merged**
