### PR TITLE
ascii doc generation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This is part of #25033. The goal is here to generate full ascii (with console colors).

It's just a start so source code is very ugly (a lot of commented code and stuff...). I'll try to make a better looking code (colors have been radomly set for now) and add the usage of the `libterm` instead of static strings.

I'll comment when this PR will be ready.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Wow, this is quite the PR! I feel like this isn't quite the route we want to take, however, as there is a **huge** amount of duplication between the HTML generation and the ascii generation. If we want to go this route I think we'll want some layer of abstraction to have the same core layer generating documentation and then the backend can be HTML or ascii.

That being said, could you elaborate on the rationale for this change? I'm not sure what the use case is here and I was unaware that we wanted to add additional backends to rustdoc at this time.

**Comment by GuillaumeGomez** [comment]
My goal for now is to provide a terminal highlighter which can be used in rusct --explain (I opened a PR for it which will be updated when this one will be merged). But why not also highlighting source code displayed by the compiler when it hits an error. I think that might be a very big improvement (I really like highlighting).

This PR is very incomplete for the moment. I wanna provide a common trait for both Html and Ascii to avoid code duplication when possible. I also need to make highlighting consistent and homogenous (and use libterm for it).

**Comment by alexcrichton** [comment]
Hm ok, it looks like there's some significant work to do here, so in the interest of keeping the queue clean would you be ok closing this until it's more fleshed out? I'm not 100% sure that we want a terminal backend to rustdoc right now (there's a lot of UI questions I might have), but I think it'd be worth fleshing it out a bit more before going to a PR.

**Comment by GuillaumeGomez** [comment]
I opened it to have opinions and allow people to keep an eye on it. So if you prefer to close it, please do !

**Comment by alexcrichton** [comment]
Ok, in that case I'll close this for now.

**Pull request closed without merging**
