### PR TITLE
Rewrite, improve documentation for `core::hash::BuildHasherDefault`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/31242.

### CODE REVIEW

**Comment by frewsxcv** [comment]
r? @rust-lang/docs 

cc @rust-lang/libs to make sure I'm using `BuildHasherDefault` correctly here.

**Comment by sfackler** [comment]
LGTM

**Comment by GuillaumeGomez** [comment]
You even added all urls. T_T What a great day!

@bors: r+ rollup

**Comment by oyvindln** [comment]
There is a [failing doctest](https://buildbot.rust-lang.org/builders/auto-win-msvc-32-opt/builds/5593/steps/test/logs/stdio) from this PR in the rollup #38407. Looks like there are some spelling issues.

**Comment by frewsxcv** [comment]
@oyvindln Woops, thanks for letting me know! Spelling fixed in the latest force push.

@bors r=GuillaumeGomez rollup

**Comment by frewsxcv** [comment]
Travis found another typo.

@bors r=GuillaumeGomez

**Pull request merged**
