### PR TITLE
[libstd] fix typo in docs

### PR DESCRIPTION
**Pull request by niklasad1**
Hi,
This fixes a typo in the docs

### CODE REVIEW

**Comment by kennytm** [comment]
Are you sure it is a typo? The folder is indeed called "[liblibc](https://github.com/rust-lang/rust/tree/master/src)" here.

**Comment by niklasad1** [comment]
No, I will close if that's the case. Missed that submodule

**Comment by steveklabnik** [comment]
I'm torn. It is called `liblibc` but the crate is literally `libc`.

Why is it `liblibc` anyway?

**Comment by kennytm** [comment]
@steveklabnik #12526 (rebased as #13315). It seems once upon a time all crates must be named `libsomething`, and we want to write `extern crate libc;` instead of `extern crate c;`, and thus it was named `liblibc` 🙃

**Pull request closed without merging**
