### PR TITLE
Use --cfg when running doctests

### LINKED ISSUE #30252: rustdoc seems to ignore `--cfg feature=foo`
[Here is a minimal crate](https://gist.github.com/durka/dc2deda494e86617a82f) with a no-op feature. It seems the feature is accessible in regular tests but not in doc-tests.

Originally I figured this was a Cargo bug, but that one is [closed](https://github.com/rust-lang/cargo/issues/1277) and as seen in the output above, Cargo is passing the flag to rustdoc, so I figure the regression is here in rustc.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #30252.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could the test actually be added to `src/test/rustdoc`? I think modifying `// compile-flags` should allow it to do the right thing, other than that r=me

**Comment by sanxiyn** [comment]
Test moved. Thanks for reviewing!

**Comment by briansmith** [comment]
Could this change be backported to 1.7 and 1.6?

This seems like a small change that would be low risk for backporting. I am working on adding `#![no_std]` support to some crates, targetting the Rust 1.6 release where `#![no_std]` becomes stable. They would benefit from having this change, and I bet others' crates would benefit too, for similar reasons.

Thanks.

**Comment by steveklabnik** [comment]
I'm not sure we should be back porting things this close to the release. I'm on the super conservative side on this though.

**Comment by alexcrichton** [comment]
Adding `beta-nominated` to have some discussion (doesn't hurt much)

**Comment by alexcrichton** [comment]
Accepted for a backport

**Pull request merged**
