### PR TITLE
Fix #[track_caller] shims for trait objects.

### LINKED ISSUE #74764: Trait objects missing `#[track_caller]` shims
After reducing a [repro of a potential track_caller bug](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ab89f4bc0d72027f70546594c7e0747b) from @yaahc, I get a segfault from [this code](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=5d89066b6706b1a5b3a07aa40212d6c1):

```rust
trait Handler {
    fn handle(&self);
}

impl<T> Handler for T {
    #[track_caller]
    fn handle(&self) {
        assert_eq!(std::panic::Location::caller().file(), file!());
    }
}

fn main() {
    let handler: &(dyn Handler) = &5u8;
    handler.handle();
}
```

This repros for me on my up-to-date checkout as well as for the current beta compiler. I'm not sure whether that makes this a regression from stable to beta, since it's an apparent bug in an API which is first stabilizing in this release.

cc @eddyb

### PR DESCRIPTION
**Pull request by anp**
We were missing an Instance::resolve_for_fn_ptr in resolve_for_vtable.

Closes #74764.

### CODE REVIEW

**Comment by anp** [comment]
cc @oli-obk bc @eddyb says we should make sure that codegen & miri agree on how to make vtables like this.

**Comment by anp** [comment]
If this works I think we should consider backporting since the regression is currently [visible with a segfault on stable](https://github.com/rust-lang/rust/issues/74764#issuecomment-663958950).

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/48776weeklymeeting2020073054818.html#205483550) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/48776weeklymeeting2020073054818.html#205484926) stable nomination in T-compiler meeting.

@rustbot modify labels: stable-accepted

**Pull request merged**
