### PR TITLE
Remove some eval_always

### PR DESCRIPTION
**Pull request by cjgillot**
Some `eval_always` marker may not be useful and trigger unnecessary query recomputations. This PR attempts to measure the amount of such recomputations.

Blocked on #90581

### CODE REVIEW

**Comment by jyn514** [comment]
@cjgillot the biggest slowdown I saw was from `privacy_access_levels` - I wonder if that map is being hashed now when it wasn't before? If you add `no_hash`, does it speed things up?

**Comment by jyn514** [comment]
Also, I'd be curious to see the perf impact of just the first commit, using that for https://github.com/rust-lang/compiler-team/issues/437 would make things a lot easier I think.

**Comment by cjgillot** [comment]
The first commit is https://github.com/rust-lang/rust/pull/85941

**Comment by cjgillot** [comment]
r? @Aaron1011
But without any hurry: we maybe should wait for the unstable fingerprint situation to be settled before exposing those queries to it.

**Comment by Aaron1011** [comment]
To avoid the possibility of exposing more fingerprint ICEs, I think we might want to wait until https://github.com/rust-lang/rust/issues/85360 is resolved to merge this.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/issues/85360 has been fixed :)

**Comment by Aaron1011** [comment]
I'm not quite sure what we should do here. @cjgillot Do you think this worth merging as-is, or would it be better to try to investigate the reasons for the slowdown?

**Comment by cjgillot** [comment]
@Aaron1011, I split this PR into several others, to measure the perf impact of individual commits.
* https://github.com/rust-lang/rust/pull/90579
* https://github.com/rust-lang/rust/pull/90580
* https://github.com/rust-lang/rust/pull/90581

If their impact is reasonable, I suggest you review them independently.
(Having the commits separated would also help in case of a bug.)

**Comment by apiraino** [comment]
@cjgillot are also these related/split from this PR?
- https://github.com/rust-lang/rust/pull/91331
- https://github.com/rust-lang/rust/pull/91295
- https://github.com/rust-lang/rust/pull/91296

**Comment by Zoxc** [comment]
`eval_always` is quite useful as a performance optimization on queries with a lot of dependencies (basically the entire crate) since we don't have to load, check, record and save those dependencies to disk. Pretty much any change to the crate would cause these to be executed again anyway, so there's not much to gain by removing it.

Also take care to not remove `eval_always` from queries which read untracked state or have side effects.

**Pull request closed without merging**
