### PR TITLE
Add config option and cli arg for skip-llvm-rebuild

### LINKED ISSUE #65612: Add `x.py` option to skip rebuilding LLVM
The compiler LLVM is rebuilt whenever the built version of LLVM doesn't have the right hash. (Previously it was rebuilt based on a special marker file, which was easier to work around.)
https://github.com/rust-lang/rust/blob/f042687959ef15f9c45d7093cd6b01f137da743f/src/bootstrap/native.rs#L88-L108
However, most of the time, having the latest LLVM version is not necessary, but makes rebuilding rustc after rebasing take significantly longer, which is a pain. It would be good to be able to disable this as an option in `x.py` for convenience.

This issue has been assigned to @matthew-healy via [this comment](https://github.com/rust-lang/rust/issues/65612#issuecomment-567610570).

### PR DESCRIPTION
**Pull request by Walther**
Fixes https://github.com/rust-lang/rust/issues/65612.

First time contributing, please let me know if there's anything I need to tweak  🙂 ❤️

### CODE REVIEW

**Comment by Walther** [comment]
I'm not sure if adding the `pub skip_llvm_rebuild: bool` into the config is a great thing, as the Rust side of the build will not use that config option anywhere. On the other hand, tidy check will fail without it, as it will fail to parse the unknown property in the `config.toml` file.

**Comment by alexcrichton** [comment]
Thanks for the PR! I think I may be missing something though? It looks like this adds configuration for skipping an LLVM rebuild but doesn't actually end up reading it when building LLVM?

Also cc @varkor who requested these changes

**Comment by Walther** [comment]
Ah, it's not enough to skip the submodule in bootstrap.py https://github.com/rust-lang/rust/pull/65848/files#diff-3e203f016947a52e3f1fad3967027e7eR734-R740 - sorry, I'll take a new look at where else it needs to be skipped 👍

**Comment by JohnCSimon** [comment]
Ping from triage:
@Walther can you please post your status on this pr?
cc: @alexcrichton @varkor 

Thank you!

**Comment by Walther** [comment]
I have a simple question - at `src/bootstrap/config.rs` line 388 ish, i'd love to add `config.skip_llvm_rebuild` to be set from the `bootstrap.py` too like some other settings are, as i did the handling of CLI args & TOML setting already there. Should I set a new capitalized env var for it, or should i plop it within `RUSTFLAGS` or some such in `build_bootstrap()`, or something completely different? I just need the already-resolved `self.skip_llvm_rebuild` in `RustBuild()` in Python/bootstrap side to be visible in Rust side too.

In addition to what's visible in the PR, I already locally added the lines necessary to actually skip the LLVM build in `native.rs`

```rust
if builder.config.skip_llvm_rebuild {
            builder.info("Skipping LLVM rebuild");
            return build_llvm_config
        }
```

**Comment by alexcrichton** [comment]
I think in general it's fine to only update `config.rs`, I suspect that `bootstrap.py` doesn't really need any changes for this. Inside of `native.rs` yeah I think you'd basically have that block which would skip any amount of LLVM rebuilding.

**Comment by JohnCSimon** [comment]
Ping from triage:
@Walther - can you address the comments from @alexcrichton  so this can be moved forward?

Thank you!

**Comment by Walther** [comment]
Sorry, I've been fairly busy! I hope I can get back at this next weekend or so. If not, and if someone wants  to quickly fix  this instead, that's okay too. There's always more issues to help with :)

**Comment by joelpalmer** [comment]
Ping from Triage: Any update @Walther?

**Comment by JohnCSimon** [comment]
Ping from triage: 
@Walther - can you please post your status for this PR?

Thank you.

**Comment by JohnCSimon** [comment]
Ping from triage:
@Walther  - Unfortunately this PR has sat idle for far too long, and I am going to close it as inactive. Please reopen it when you have the time to make the necessary changes or find help to move this forward.
Please do not push to the PR while it is closed as that prevents it from being reopened.
Thank you for your efforts!

**Pull request closed without merging**
