### PR TITLE
crashes: add test for #131451

### PR DESCRIPTION
**Pull request by matthiaskrgr**
r? @saethlin 
How do I find out which mir opts are involved here? :sweat_smile:

### CODE REVIEW

**Comment by saethlin** [comment]
This should be scriptable:

First off, try with a lower `mir-opt-level`. This is just a fast way to trim down the pass list.

Build with `-Zdump-mir=all`. This will produce a `mir_dump` directory that has the before and after MIR for every pass that was run on any MIR. This produces a directory called `mir_dump/` which contains a bunch of files named like `<crate>.<function>.<phase_number>-<pass_number>.<pass_name>.{before,after}.mir`.

You should be able to manually enable only the passes that produce a diff in the MIR. The before and after files always differ on the first line because that's a comment that repeats the file's name.

Then trim down that list of passes further, if possible.

**Comment by matthiaskrgr** [comment]
ok ty, I think I got it :D
to get the flags, in the mir-dump dir:
```bash
ls -c1 | sort -n | grep after  | grep -o "...-...\..*.after" | cut -c9- | sed 's/\.after$//g'   | sed s/^/\"-Zmir-enable-passes=+/  | sed -e s/$/\",/
```

Then I throw this into icemaker and let it reduce the flags automatically: `-Zvalidate-mir -Zmir-enable-passes=+DataflowConstProp -Zmir-enable-passes=+Inline`

**Comment by saethlin** [comment]
Can you drop -Clink-dead-code=true if the fn is pub?

**Comment by saethlin** [comment]
Nice!
@bors r+ rollup

**Pull request merged**
