### PR TITLE
updating llvm and jemalloc submodules to include bitrig support

### PR DESCRIPTION
**Pull request by dhuseby**
as the subject says.

### CODE REVIEW

**Comment by dhuseby** [comment]
@alexcrichton @brson I'm pretty sure I did this correctly.

**Comment by alexcrichton** [comment]
@bors: r+ 1329dc6e8f328d91a4c6499483a0f00f8302d2d5 

Thanks!

**Comment by dhuseby** [comment]
@alexcrichton I added the bump in the jemalloc revision too.  almost there!

**Comment by alexcrichton** [comment]
I had to check in an extra commit to jemalloc to propagate your changes to the generated `configure` script, so you may want to pin the submodule to rust-lang/jemalloc@e24a1a025a1f214e40eedafe3b9c7b1d69937922 instead

**Comment by dhuseby** [comment]
ah, k.  let me do that.

**Comment by dhuseby** [comment]
@alexcrichton done.

**Comment by dhuseby** [comment]
@alexcrichton alright, now the only thing left is to get my latest bitrig rust snapshots into static.rust-lang.org/dl/  How do I do that?

**Comment by dhuseby** [comment]
and then I can add it to the src/snapshots.txt file

**Comment by dhuseby** [comment]
My snapshots are here: https://github.com/dhuseby/rust-cross-bitrig/tree/master/snapshots

**Comment by alexcrichton** [comment]
I've uploaded your snapshots

**Comment by dhuseby** [comment]
I just rebased to current rust master.

**Comment by dotdash** [comment]
@bors r-

Sorry to r-, but you must also update `src/rustllvm/llvm-auto-clean-trigger`. This is required for the buildbots to actually build the new llvm version.

**Comment by dhuseby** [comment]
@dotdash @alexcrichton updated llvm-auto-clean-trigger per review feedback.

**Comment by dotdash** [comment]
@bors r=alexcrichton e0a0b46

Thanks!

**Pull request merged**
