### PR TITLE
[beta] Make Solaris builder compatible with Solaris 10 retry

### PR DESCRIPTION
**Pull request by bgermann**
Backport of #45343.

### CODE REVIEW

**Comment by kennytm** [comment]
This is a backport of #45343, currently [beta-nominated].

**Comment by bgermann** [comment]
Looks like a network issue.

**Comment by kennytm** [comment]
@bors retry

1. The macOS `check x86_64-apple-darwin` job started 3 hours
2. On its third try, it failed to download `rustc-1.21.0-x86_64-apple-darwin.tar.gz` (hitting a "504 Gateway Time-out")

**Pull request merged**
