### PR TITLE
Mark Arc function get_mut and method make_unique unsafe

### PR DESCRIPTION
**Pull request by bluss**
Mark Arc function get_mut and method make_unique unsafe

This is a temporary mitigation for issue #24880 which points out that
these functions are racy in a particular situation where weak pointers
exist.

To mitigate this, mark the functions unsafe until this can be fixed or
another decision is made.

### CODE REVIEW

**Comment by bluss** [comment]
I don't want us to sit around with thread unsafe API. I'm sorry I don't know how to fix this, but I can mark it unsafe.

Other options:

- Outright removal until resolved
- If we remove Weak support, weakless Arc can offer it.

**Comment by sfackler** [comment]
I don't think stabilizing these as unsafe functions is acceptable, but this seems like a reasonable path forward in the short term since users will at least be aware of what to be careful of.

**Comment by Gankro** [comment]
Yeah, this is an "honest" adjustment for now.

@bors r+

**Comment by alexcrichton** [comment]
I would also be fine just removing these functions, it's not clear that an implementation is acceptable in terms of performance costs and it's not very useful to have a racy version today.

**Comment by bluss** [comment]
@alexcrichton I'm fine either way. It *is* possible to use these safely for a user who knows they don't use Weak pointers though.

**Comment by alexcrichton** [comment]
Oh sorry, to clarify I didn't mean to stop this or anything, just saying if you want to amend to remove the functions outright I would also r+ :)

**Comment by bluss** [comment]
I just want to go for it. With this change we are back to “honest” so then we're fine to fix it later.

**Pull request merged**
