### PR TITLE
rustdoc: Remove the json-{input, output} format

### LINKED ISSUE #25108: rustdoc --output-format json command seems broken
I tried this command:

```Shell
> rustdoc --output-format json src/sysinfo.rs
```

On this [repo](https://github.com/GuillaumeGomez/sysinfo).

Result:

```Shell
src/sysinfo.rs:13:1: 13:19 error: use of unstable library feature 'libc'
src/sysinfo.rs:13 extern crate libc;
                  ^~~~~~~~~~~~~~~~~~
src/sysinfo.rs:13:1: 13:19 help: add #![feature(libc)] to the crate attributes to enable
src/processus.rs:43:42: 43:47 error: use of unstable library feature 'libc'
src/processus.rs:43         unsafe { ::ffi::kill(self.pid as c_int, signal as c_int) == 0 }
                                                             ^~~~~
src/processus.rs:43:42: 43:47 help: add #![feature(libc)] to the crate attributes to enable
src/processus.rs:43:59: 43:64 error: use of unstable library feature 'libc'
src/processus.rs:43         unsafe { ::ffi::kill(self.pid as c_int, signal as c_int) == 0 }
                                                                              ^~~~~
src/processus.rs:43:59: 43:64 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:15:5: 15:41 error: use of unstable library feature 'libc'
src/system.rs:15 use libc::types::os::arch::posix01::stat;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/system.rs:15:5: 15:41 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:16:5: 16:17 error: use of unstable library feature 'libc'
src/system.rs:16 use libc::c_char;
                     ^~~~~~~~~~~~
src/system.rs:16:5: 16:17 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:17:5: 17:39 error: use of unstable library feature 'libc'
src/system.rs:17 use libc::funcs::posix01::stat_::lstat;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/system.rs:17:5: 17:39 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:279:35: 279:39 error: use of unstable library feature 'libc'
src/system.rs:279                     let mut buf : stat = unsafe { ::std::mem::uninitialized() };
                                                    ^~~~
src/system.rs:279:35: 279:39 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:280:90: 280:96 error: use of unstable library feature 'libc'
src/system.rs:280                     let res = unsafe { lstat(result.to_str().unwrap().as_ptr() as *const c_char, &mut buf as *mut stat) };
                                                                                                           ^~~~~~
src/system.rs:280:90: 280:96 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:280:115: 280:119 error: use of unstable library feature 'libc'
src/system.rs:280                     let res = unsafe { lstat(result.to_str().unwrap().as_ptr() as *const c_char, &mut buf as *mut stat) };
                                                                                                                                    ^~~~
src/system.rs:280:115: 280:119 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:280:40: 280:45 error: use of unstable library feature 'libc'
src/system.rs:280                     let res = unsafe { lstat(result.to_str().unwrap().as_ptr() as *const c_char, &mut buf as *mut stat) };
                                                         ^~~~~
src/system.rs:280:40: 280:45 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:282:40: 282:47 error: use of unstable library feature 'libc'
src/system.rs:282                     if res < 0 || (buf.st_mode  & S_IFMT) != S_IFLNK {
                                                         ^~~~~~~
src/system.rs:282:40: 282:47 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:282:51: 282:57 error: use of unstable library feature 'libc'
src/system.rs:282                     if res < 0 || (buf.st_mode  & S_IFMT) != S_IFLNK {
                                                                    ^~~~~~
src/system.rs:282:51: 282:57 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:282:62: 282:69 error: use of unstable library feature 'libc'
src/system.rs:282                     if res < 0 || (buf.st_mode  & S_IFMT) != S_IFLNK {
                                                                               ^~~~~~~
src/system.rs:282:62: 282:69 help: add #![feature(libc)] to the crate attributes to enable
src/ffi.rs:10:19: 10:24 error: use of unstable library feature 'libc'
src/ffi.rs:10 	pub fn kill(pid: c_int, signal: c_int) -> c_int;
              	                 ^~~~~
src/ffi.rs:10:19: 10:24 help: add #![feature(libc)] to the crate attributes to enable
src/ffi.rs:10:34: 10:39 error: use of unstable library feature 'libc'
src/ffi.rs:10 	pub fn kill(pid: c_int, signal: c_int) -> c_int;
              	                                ^~~~~
src/ffi.rs:10:34: 10:39 help: add #![feature(libc)] to the crate attributes to enable
src/ffi.rs:10:44: 10:49 error: use of unstable library feature 'libc'
src/ffi.rs:10 	pub fn kill(pid: c_int, signal: c_int) -> c_int;
              	                                          ^~~~~
src/ffi.rs:10:44: 10:49 help: add #![feature(libc)] to the crate attributes to enable
error: aborting due to 16 previous errors
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:192
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "rustc failed"', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
```

So then I added the "missing" feature (that's weird by the way) and then I got:

```Shell
> rustdoc --output-format json src/sysinfo.rs 
thread '<unnamed>' panicked at 'Rust generated JSON is invalid: SyntaxError(EOFWhileParsingObject, 1, 99690)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustdoc/lib.rs:525
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
```

I guess rustdoc is broken somehow ? Here's my current rustdoc version:

```Shell
> rustdoc --version
rustdoc 1.1.0-nightly (ce1150b9f 2015-05-04) (built 2015-05-04)
```

### PR DESCRIPTION
**Pull request by mitaa**
(for reference #32698)

fixes #25108

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 3b5d308bfedff4aaa03b2edf07e9b298e1731968

Thanks!

While you're at it, if you want to remove the plugin support as well I think that basically hasn't ever worked, so feel free to trim it :)

**Comment by mitaa** [comment]
I've just tested it and it worked without a problem so I'd rather not remove it right now :-)

.. but I've deleted the `run-make/rustdoc-json` test I've missed before (thanks travis)

**Comment by mitaa** [comment]
rebased (-> #32230)

**Comment by getreu** [comment]
Please remove it also from the rustdoc man-page.

**Pull request merged**
