### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #111081 (impl SliceIndex<str> for (Bound<usize>, Bound<usize>))
 - #113394 (style-guide: Document style editions, start 2024 style edition)
 - #113588 (bootstrap: use git merge-base for LLVM CI download logic)
 - #113743 (Directly link more target docs)
 - #114262 (Improve the rust style guide doc)
 - #114309 (Update books)
 - #114313 ([rustc_data_structures] Simplify SortedMap::insert.)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=111081,113394,113588,113743,114262,114309,114313)

### CODE REVIEW

**Comment by Kobzol** [comment]
This PR was somehow merged twice (and thus perf. tested twice). I'm not sure if the rustc build regression is caused by that or if it's something else (maybe https://github.com/rust-lang/rust/pull/113588 or https://github.com/rust-lang/rust/pull/114309, since these dealt with git somehow?)

**Comment by lqd** [comment]
91a41abd6ac0a95b49cd69d488feed224279d5c2 doesn't look to be on master compared to c435af0d5c47a333c7cb7f359f3586d5c9dab3ab, probably thanks to the [failed fast forward](https://github.com/rust-lang/rust/pull/114318#issuecomment-1659714001), however webhooks may probably sent to the perf server anyways ?

The rustc error is weird, it mentions e62323df22ecf9c163023132d17b7114f68b72e8 but it's an old commit. Maybe because it was testing a "regular merge commit" that was not actually on master, the usual git commands didn't work 🤔

**Pull request merged**
