### PR TITLE
Add missing Wrapping methods, use doc_comment!

### PR DESCRIPTION
**Pull request by clarfonthey**
Re-opened version of #49393 . Finishing touches for #32463.

Note that this adds `Shl` and `Shr` implementations for `Wrapping<i128>` and `Wrapping<u128>`, which were previously missed. This is technically insta-stable, but I don't know why this would be a problem.

### CODE REVIEW

**Comment by nagisa** [comment]
The implementation of `wrapping_next_power_of_two` is questionable.

Tne name and expectation from the other wrapping methods would make one to expect that when `next_power_of_two` would overflow, you’d get the smallest power of two again (i.e. `1`), but this is not what happens with the current implementation.

**Comment by clarcharr** [comment]
@nagisa see the discussion in #49393 for more on that.

**Comment by nagisa** [comment]
There doesn’t seem to be any conclusion in that thread.

**Comment by nagisa** [comment]
To give an actual counter-argument to current behaviour of it wrapping to `0`. There’s this intrinsic `cttz_nonzero` that is fairly useful when in combination of `next_power_of_two`. Now if we take the currently implemented wrapping behaviour, the code which assumes that "next power of two" follows the strict mathematical definition modulo 2⁶⁴/2³²/2¹⁶/... will sometimes result in undefined behaviour here.

**Comment by clarcharr** [comment]
I'm a bit confused; wouldn't `cttz_nonzero(x.next_power_of_two()) == BITS - ctlz_nonzero(x)` when `x` is zero and `1` when `x` is nonzero?

Not 100% sure what you're trying to do here.

**Comment by nagisa** [comment]
@clarcharr rewriting such code in terms of ctlz is definitely possible, however it is harder to do if you want the "wrapping" power of two behaviour and the resulting code will be less obvious than the obvious solution that uses the wrapping power-of-two.

---

One definition that would support the current implementation would be 

> returns the next power of two greater than or equal to self *modulo X*.

Then doing a `(2⁶³ + 1).next_power_of_two() = 2⁶⁴ mod 2⁶⁴ = 0`.

But in that case we *must*, in very clear manner warn users that this doesn’t always result in an actual power-of-two being returned.

**Comment by clarcharr** [comment]
That is fair, and I'll update the documentation for it. Also as a precaution, I'll give it a different feature flag to make it clear that it should be discussed more in depth during stabilisation.

**Comment by pietroalbini** [comment]
Ping from triage! What's the status of this PR?

**Comment by clarcharr** [comment]
@petroalbini I still need to separate out the `wrapping_next_power_of_two` methods into a separate feature, but otherwise, this is ready for review.

IMHO merging the next power of two functions now is okay because they're unstable, but a separate feature flag should mention that the behaviour might change for reasons @nagisa mentioned.

**Comment by clarcharr** [comment]
Updated those methods with a separate feature flag, also added a `reason` field explaining that the wrapping behaviour may change.

**Comment by pietroalbini** [comment]
Ping from triage @KodrAus! This PR needs your review.

**Comment by KodrAus** [comment]
Thanks @clarcharr!

So looking back through the history it looks like we haven't quite got a concrete use-case to base the wrapping power of two methods on but have at least reached a point where their behaviour is well communicated so we could add a note to the tracking issue to look at them again before stabilization. So that seems good to me.

@clarcharr Sorry, where are we implementing `Shl` and `Shr` for `Wrapping` now?

**Comment by clarcharr** [comment]
@KodrAus Right now the `Shl` and `Shr` impls only allow `usize` on the right-hand-side. This simply adds impls of that for `Wrapping<i128>` and `Wrapping<u128>` which were missed by accident, and necessary to make all of the doc tests pass here.

**Comment by KodrAus** [comment]
Ah gotcha :+1: That shouldn't be a problem for anyone. This looks good to me, I'll add a note to the tracking issue. Thanks @clarcharr!

@bors r+

**Pull request merged**
