### PR TITLE
Split rustc_typeck::check into separate files

### PR DESCRIPTION
**Pull request by Nicholas-Baron**
Contributing to #60302.

### CODE REVIEW

**Comment by oli-obk** [comment]
I'm not a big fan of `util` modules. Can you try to find things that can be placed in new modules for any additional changes you do?

**Comment by Nicholas-Baron** [comment]
Sure. Could it be a one struct to one `mod` generally, with some exceptions?

**Comment by oli-obk** [comment]
Well, if anything is reasonably groupable, then that is definitely preferrable. Ideally instead of a `util` module, the things that are in the `util` module live in the main `check` module, and we'd move out large chunks of things instead.

**Comment by Nicholas-Baron** [comment]
@oli-obk Is something like what I did for `GatherLocalsVisitor` acceptable?

**Comment by oli-obk** [comment]
perfect!

**Comment by Nicholas-Baron** [comment]
It seems that half of the `mod.rs` file was dedicated to the `FnCtxt` struct. I have moved the `FnCtxt` struct and its related `impl`s to a separate file that is now over 3000 lines.

`mod.rs` is fine, for now (~2800 lines).

**Comment by Nicholas-Baron** [comment]
I have gotten `mod.rs` down to ~1150 lines. @oli-obk, should I continue to put more parts in their own files or it just over a thousand lines good enough?

Additionally, `fn_ctxt.rs` is now throwing file length errors. It is about 200 lines over the limit, but I do not know what to move to other files.

**Comment by oli-obk** [comment]
> Additionally, fn_ctxt.rs is now throwing file length errors. It is about 200 lines over the limit, but I do not know what to move to other files.

I guess let's mark that file as oversized for now and see how to split it later?

**Comment by Nicholas-Baron** [comment]
@oli-obk so the issue is no longer that `mod.rs` is too long, but that the `FnCtxt` struct has too much functionality attached to it.

How should I format the `//TODO` that is going to be under the `// ignore-tidy-filelength` for `fn_ctxt.rs`?

**Comment by oli-obk** [comment]
> How should I format the `//TODO` that is going to be under the `// ignore-tidy-filelength` for `fn_ctxt.rs`?

I'm not sure I understand? Just a message about "try to figure out how to split this file into parts" should be sufficient

Also, don't use `TODO`, CI will complain about that, use `FIXME`

**Comment by Nicholas-Baron** [comment]
I am asking about the format, as I have seen `FIXME`s with some attribution to an author. However, some seem to not have an attribution, so I stand corrected.

**Comment by oli-obk** [comment]
Oh heh, that's just convention if you want others to bug you about that FIXME

**Comment by oli-obk** [comment]
Ok, so let's move this out of draft and then I'll do a review and give the PR priority to avoid breakage

**Comment by Nicholas-Baron** [comment]
@oli-obk ready for review

**Pull request merged**
