### PR TITLE
Increase spacing in error format for readability. 

### LINKED ISSUE #33763: Test fails when using RUST_NEW_ERROR_FORMAT
If you set RUST_NEW_ERROR_FORMAT, running the full 'make check' will fail.  @alexcrichton did some investigation and noticed this was one failure: https://github.com/rust-lang/rust/blob/master/src/test/run-make/unicode-input/span_length.rs#L94-L98

We may want to update the test or possibly move it to a UI test.

### LINKED ISSUE #33819: Invalid suggestion for mutability correction in error message
The compiler makes an invalid suggestion for how to correct the immutability of a reference in a `match` block. To reproduce, try to compile the following code:

    use std::fs::File;
    use std::io::Write;

    fn main() {
        let mut op = Some(File::open("").unwrap());
        match op {
            Some(ref mut f) => { write!(f, "!").unwrap();  },
            None => {},
        }
    }

On stable and beta, the compiler will print:

    <anon>:7:33: 7:34 error: cannot borrow immutable local variable `f` as mutable
    <anon>:7         Some(ref f) => { write!(f, "!").unwrap();  },
                                         ^
    <anon>:7:26: 7:40 note: in this expansion of write! (defined in <std macros>)
    <anon>:7:14: 7:19 help: to make the local variable mutable, use `mut` as shown:
    <anon>:          Some(mut ref f) => { write!(f, "!").unwrap();  },

On nightly, it will print:

    error: cannot borrow immutable local variable `f` as mutable
     --> <anon>:7:33
    7 |>         Some(ref f) => { write!(f, "!").unwrap();  },
      |>              -----              ^ cannot borrow mutably
      |>              |
      |>              use `mut ref f` here to make mutable

Both of these suggestions are erroneous, as `mut ref f` is invalid syntax, and should be `ref mut f`.

### PR DESCRIPTION
**Pull request by sophiajt**
Two small tweaks that seem to help readability quite a bit:
- Add spacing header<->snippet, but use the |> on the side for visual consistency
- Fix #33819 
- Fix #33763
- Move format-sensitive test (issue-26480 in cfail) to ui test

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Maybe this is a good chance for a UI test!

**Comment by sanxiyn** [comment]
Failed in Travis due to a UI test.

**Comment by jonathandturner** [comment]
@nikomatsakis - updated and fixed troublesome errors using UI test or check_old_skool if they couldn't easily be a UI test.  Fixed a couple other small issues in the process.

Also, went from two spaces between errors back to one space.

**Pull request merged**
