### PR TITLE
Simplify Span by explicitly not supporting ctxt

### PR DESCRIPTION
**Pull request by nzig**
Reading through the code, I was confused for a while because the code in `libsyntax_pos/span_encoding.rs` appears to support storing the `SyntaxContext ` inside a compressed `Span`. However, no bits are actually allocated for `SyntaxContext`.

Since this is unlikely to ever be used, I think the code would be clearer for the next newcomer if this was simply removed.

See #44646
 r? @michaelwoerister

### CODE REVIEW

**Comment by kennytm** [comment]
cc @petrochenkov

**Comment by petrochenkov** [comment]
Let's keep it as is.
Today it's `0`, tomorrow it can be some other value. There are some plans about changing span's [size](https://github.com/rust-lang/rust/issues/36799#issuecomment-332630030) or the [meaning of base](https://internals.rust-lang.org/t/rfc-compiler-refactoring-spans/1357/29).

**Comment by nzig** [comment]
If we don't change it then I'll add a comment explaining this. It's particularly confusing to me because  `INLINE_OFFSETS` has an entry for `CTXT_INDEX` that is essentially an arbitrary value, because it has 0 size.

**Comment by petrochenkov** [comment]
Sure, feel free to add a comment.
Or maybe it would be better to add the ctxt field to the "picture"
```
// -------------------------------------------------------------
// | base 31:8  | len 7:1  | ctxt (currently 0 bits) | tag 0:0 |
// -------------------------------------------------------------
```

**Comment by nzig** [comment]
Should that be a separate pull request or should I modify this one?

**Comment by petrochenkov** [comment]
@nzig 
There's not much difference, whatever is more convenient for you.

**Comment by nzig** [comment]
OK. I'll make a separate one.

**Pull request closed without merging**
