### PR TITLE
Support building with "cargo" directly instead of "x.py" for development purposes

### PR DESCRIPTION
**Pull request by luca-barbieri**
This pull request allows to just use `cargo` in addition to `x.py` for rustc and libstd development.

This makes it much simpler for new contributors to contribute to rust since there is no need to learn how `x.py` and bootstrapping works, and makes incremental development faster because this new infrastructure does no bootstrapping at all.

To make it work, the user is supposed to install the latest nightly with rustup, and then make changes based on a checkout of the same git commit hash of that nightly: this allows to build a new rustc that works with the standard library from the nightly, and to build a new non-cfg(bootstrap) standard library with the compiler from the nightly.

To support this workflow, we check and warn in build.rs if the compiler and repository versions don't match, and we set the compiler release to the same one of the compiler used to build so that artifacts can be shared between them.

Summary of changes:
- Several changes to make things build without the setup done by `x.py`
- Centralization of code that reads CFG_ environment variables to rustc_session, so they can be set in the build.rs for rustc_session
- build.rs code to detect the rustc version and warn if it is not the correct one, including suggestions on how to fix the issues

With these changes, this is currently working:
- Running `cargo check` for single crates
- Running `cargo run` in src/rustc and having a working compiler without any bootstrapping
- Running `cargo build` in src/libstd, src/libcore or src/libtest
- Testing by running `__CARGO_TESTS_ONLY_SRC_ROOT=$(realpath $PWD/../..) cargo test -Z build-std --target x86_64-unknown-linux-gnu` in src/libcore

What is not working and missing:
- Testing libstd
- Checking or building the whole workspace, even with the build-std incantation
- No way to install the built artifacts, even though they work in place
- No easy way to do a full bootstrap other than using `x.py`

Future work would be to document this, and modify cargo's std-aware code so that libstd can be tested and the special incantation is no longer needed to run libstd tests, and so that you can just build the whole workspace with "cargo build" and have it work as if the pieces were built independently.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This is amazing! Thank you so much for getting this off the ground :)

I've pulled some of the commits here into a separate PR (https://github.com/rust-lang/rust/pull/71029) and approved that, just to reduce the amount of commits in this PR. Those I'm prepared to see land immediately, I think they're required for progress here anyway.

I'm going to need to think a bit about the overall design, though. I'm not quite sure yet whether I want to split and somewhat duplicate code that's currently in bootstrap (or just doesn't really exist). One thought I had is that we should probable come up with some basic "workflows" -- e.g., I'm not quite sure what users would expect with a cargo-native build system.

I also think that to start we should just focus on supporting building and testing std, not rustc; rustc is more complicated (needs a bunch of environment variables set, has sysroot management to deal with, can't easily run without a std built by it)...

With that in mind, I think most of this PR I'm not prepared to land immediately, given that it introduces a lot of code that is either duplicating other code or adding code to manage some process, and I suspect that may be avoidable, so would like to try to avoid it first. I'm primarily concerned that we don't end up with divergent code between the environment variables that bootstrap sets and what the "cargo build" workflow wants, in an effort to avoid situations where we end up with that leading to e.g. CI failing but locally thing seeming to work.

I think the first thing we should get working is the following, in order:

 * `cargo +$master_sha build --manifest-path src/libtest/Cargo.toml`
 * `cargo +$master_sha test --manifest-path src/libtest/Cargo.toml`
 * "I want to use the std I edited somewhere else," which should not require rebuilding the compiler.

I believe that the first already mostly works on master and with the panic-unwind feature entirely works; certainly after https://github.com/rust-lang/rust/pull/71029 it works fine. We should probably document that as soon as that lands in rustc-dev-guide, as it seems a major improvement for folks hacking on std with just the need for check/build builds, even if tests don't work quite yet.

The second will be more difficult. tests for core/alloc/std I believe all depend on rand, which has not been prepared for a in-tree world with rustc-dep-of-std. That means that they cannot build successfully unless you do what you did with -Zbuild-std.

That's a wall of text for sure, but hopefully I'm not too unclear. Feel free to ask if I should clarify my thoughts or if you disagree.

**Comment by Mark-Simulacrum** [comment]
In terms of altering rustc -- I think one thought I've had is that we can likely move things from bootstrap's build parts into build.rs in many cases, especially with a helper crate that things can depend on which will parse config.toml to the extent needed (basically build_helper I think).

Another thought I had is that we might be able to build sysroots via a build.rs in a crate that has a build-dependency on src/rustc/Cargo.toml, which can the install the rustc and relevant libraries into the sysroot.

**Comment by Dylan-DPC** [comment]
@luca-barbieri if you can rebase this, we can get it merged

**Comment by joelpalmer** [comment]
Ping from Triage: Closing due to inactivity. @luca-barbieri please reopen with conflicts resolved. Thanks for the PR.

**Pull request closed without merging**
