### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #34461, #34609, #34732, #34850, #34894, #34935, #34974, #34990, #34995, #35001, #35009, #35010, #35028
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ok *that* seems legitimate.

cc @vadimcn though, the failure to do a backtrace seems worrisome.

**Comment by vadimcn** [comment]
#35014 should fix that

**Pull request closed without merging**
