### PR TITLE
use problem matchers for tidy CI

### PR DESCRIPTION
**Pull request by fee1-dead**

### CODE REVIEW

**Comment by fee1-dead** [comment]
See [this](https://github.com/rust-lang/rust/commit/88889c15888129fa7a0f10886ba924137987190b#annotation_7422933573) to confirm that it is working correctly.

**Comment by pietroalbini** [comment]
The duplication is unfortunate... tidy should (?) be the same across jobs, can we collect annotations only from one of them?

**Comment by fee1-dead** [comment]
> The duplication is unfortunate... tidy should (?) be the same across jobs, can we collect annotations only from one of them?

It might be best to only run tidy on `mingw-check`. A lot of other platforms run by bors run full tests which include tidy already so that should not be a concern for bors. For PR CI the mingw-check-tidy job was designed to not cancel other (perhaps with more interesting errors) jobs if tidy fails.

**Comment by Mark-Simulacrum** [comment]
I believe some parts of tidy are platform specific (e.g., checking binaries/executable files checked into tree). I'm not sure if there's anything else like that.

**Comment by fee1-dead** [comment]
> I believe some parts of tidy are platform specific (e.g., checking binaries/executable files checked into tree). I'm not sure if there's anything else like that.

I checked that part of tidy and it looks like it only runs on unix systems and it just checks if there are files marked as executable.

**Comment by pietroalbini** [comment]
Yeah let's only run tidy in its dedicated job to remove the duplicate annotations.

**Comment by fee1-dead** [comment]
I've pushed a commit to not run tidy on x86_64-gnu-llvm-13, which should resolve this.

**Comment by fee1-dead** [comment]
@pietroalbini @Mark-Simulacrum any updates?

**Comment by fee1-dead** [comment]
Rebased.

@bors r=pietroalbini

**Pull request merged**
