### PR TITLE
Fix import resolution bug

### LINKED ISSUE #32222: Very minor changes causing unrelated module to fail to compile in a nonsense fashion
Unfortunately, I can't reproduce this at a smaller scale. This issue occurs with https://github.com/sgrif/diesel as of commit 9084bb62d74f50e5686a85d6145cfe655ee2a3ba. Rust version is `rustc 1.9.0-nightly (c9629d61c 2016-03-10)`

Currently the tests (run from the `diesel_tests` directory with `cargo test --no-default-features --features "unstable postgres"`) pass. However, applying the following patch:

```patch
diff --git a/diesel_tests/tests/boxed_queries.rs b/diesel_tests/tests/boxed_queries.rs
new file mode 100644
index 0000000..5cb4cbb
--- /dev/null
+++ b/diesel_tests/tests/boxed_queries.rs
@@ -0,0 +1,2 @@
+use super::schema::*;
+use diesel::*;
diff --git a/diesel_tests/tests/lib.rs b/diesel_tests/tests/lib.rs
index aef11d1..901a091 100644
--- a/diesel_tests/tests/lib.rs
+++ b/diesel_tests/tests/lib.rs
@@ -11,6 +11,7 @@ include!("lib.in.rs");
 include!(concat!(env!("OUT_DIR"), "/lib.rs"));
 
 mod associations;
+mod boxed_queries;
 mod expressions;
 mod connection;
 mod filter;
```

causes the following compiler error:

```
tests/types_roundtrip.rs:87:9: 87:18 error: a module named `connection` has already been imported in this module [E0252]
tests/types_roundtrip.rs:87     use super::*;
                                    ^~~~~~~~~
tests/types_roundtrip.rs:87:9: 87:18 help: run `rustc --explain E0252` to see a detailed explanation
tests/types_roundtrip.rs:87:9: 87:18 note: previous import of `connection` here
tests/types_roundtrip.rs:87     use super::*;
```

which is claiming that an import conflicts with itself. I have pushed up the branch `compiler-error-demo` with that change applied for easy reproduction. Again, I'm sorry that I cannot provide a report on a smaller scale, but this appears to be some edge case blowing up. I have no clue why adding a module with a few imports and nothing else would be causing this issue.

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes #32222, which was introduced in #31726.

### CODE REVIEW

**Comment by jseyfried** [comment]
Whenever [`decrement_outstanding_references_for`](https://github.com/jseyfried/rust/blob/3e05371c13f851a5af57a96a5e13c99537787314/src/librustc_resolve/resolve_imports.rs#L264) causes an indeterminate `NameResolution` to become determined (i.e. a success), the binding is defined in all known glob importers of the its containing module.

[This use](https://github.com/jseyfried/rust/blob/3e05371c13f851a5af57a96a5e13c99537787314/src/librustc_resolve/resolve_imports.rs#L481) of `decrement_outstanding_references_for` was incorrect since it only makes the resolution determined temporarily (after which the resolution is reverted to its previous state). This means that the same binding would be defined in all known glob importers each time it became temporarily determined, leading to incorrent duplicate errors (and other privacy-related bugs).

**Comment by alexcrichton** [comment]
@bors: r+ d1020143b67a55d3c5733f735f82bd683b0e35be

Thanks for the quick fix @jseyfried! Does this affect beta as well do you know? If so this would probably be a good candidate for a backprot.

**Comment by jseyfried** [comment]
@alexcrichton this doesn't affect beta.

**Pull request merged**
