### PR TITLE
add println!() macro with out any arguments

### PR DESCRIPTION
**Pull request by sbwtw**
lets add println!() to write "\n".
like java https://docs.oracle.com/javase/7/docs/api/java/io/PrintStream.html#println()

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This seems like a reasonable feature to me, especially given that we've got `panic!()`. Looks like the failures on travis though are legitimate.

**Comment by bluss** [comment]
@sbwtw It looks like these two tests failed due to the changes:

```
failures:
    [compile-fail] compile-fail/empty-comment.rs
    [compile-fail] compile-fail/issue-7970a.rs
```

You can find them inside `src/test` in the rust source tree. Both are using `println!()` and expecting it to fail. I suggest you in both test cases simply define a new macro that uses at least one argument, and use that macro instead of println.

**Comment by sbwtw** [comment]
@bluss @alexcrichton hi, I have modified the test code.

**Comment by sinkuu** [comment]
What about letting `writeln!(dst)` to also write `\n`?

**Comment by sbwtw** [comment]
@sinkuu seems good, but I think its better to modify it in another commit.

**Comment by alexcrichton** [comment]
Thanks @sbwtw! This is tagged with `T-libs` so we'll get around to discussing this in triage next week hopefully.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Seems like a neat feature to me!

**Pull request merged**
