### PR TITLE
Remove more `PtrToPtr` casts in GVN

### PR DESCRIPTION
**Pull request by scottmcm**
This addresses two things I noticed in MIR:

1. `NonNull::<T>::eq` does `(a as *mut T) == (b as *mut T)`, but it could just compare the `*const T`s, so this removes `PtrToPtr` casts that are on both sides of a pointer comparison, so long as they're not fat-to-thin casts.

2. `NonNull::<T>::addr` does `transmute::<_, usize>(p as *const ())`, but so long as `T: Thin` that cast doesn't do anything, and thus we can directly transmute the `*const T` instead.

r? mir-opt

### CODE REVIEW

**Comment by saethlin** [comment]
Thanks! This is as usual more code than I wish it took to implement MIR transforms. But also I never thought of adding more casting cleanups to GVN. I'll re-assess some of the MIR in `Vec` after this PR lands to see if we're still missing more cleanup opportunities.

I'm going to send this to the benchmark queue on the off-chance that this produces a huge amount of more work for GVN or some other mir-opt pass to do. But if I see anything other than "whoa that's a lot of time in inside MIR transforms" I'll approve this when the perf run comes back.

@bors try @rust-timer queue

**Comment by tgross35** [comment]
> This is as usual more code than I wish it took to implement MIR transforms.

In theory, could MIR adopt something like Cranelift's [isle](https://github.com/bytecodealliance/wasmtime/blob/f4b49b8c8942523b5bc44d09aa455fadaf848e41/cranelift/isle/docs/language-reference.md) to describe transformations?

**Comment by saethlin** [comment]
I don't think a project of that scale is worth it for MIR. I'd much rather see someone design an IR that's suited to implementing optimizations first, and co-design it with a DSL for writing optimizations.

Not that I have the kind of time/patience/expertise to do any of those things.

**Comment by cjgillot** [comment]
I wonder if we should also simplify `PtrToPtr` casts in deref projections too.

**Comment by pnkfelix** [comment]
Visiting for weekly rustc-perf triage

* Main primary regressions to opt-full benchmarks ripgrep (2.89%), webrender (1.11%), html5ever (0.70%).
* Some interesting discussion on the PR about the cause; e.g. are PR's like this causing individual MIR reduction that leads to more inlining and then more bloat overall?
* but I do not think any of that would cause us to undo this particular change; there are higher level inlining and code-generation policies that need to be revisited.
* marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
