### PR TITLE
fs: Don't dereference a pointer to a too-small allocation

### PR DESCRIPTION
**Pull request by tavianator**
ptr::addr_of!((*ptr).field) still requires ptr to point to an
appropriate allocation for its type.  Since the pointer returned by
readdir() can be smaller than sizeof(struct dirent), we need to entirely
avoid dereferencing it as that type.

Link: https://github.com/rust-lang/miri/pull/1981#issuecomment-1048278492
Link: https://github.com/rust-lang/rust/pull/93459#discussion_r795089971

### CODE REVIEW

**Comment by RalfJung** [comment]
> Since the pointer returned by
readdir() can be smaller than sizeof(struct dirent), we need to entirely
avoid dereferencing it as that type.

Alternatively, we could deref it at a different, sufficiently small type -- not sure if that is feasible here.

**Comment by tavianator** [comment]
> Alternatively, we could deref it at a different, sufficiently small type -- not sure if that is feasible here.

We could make a type that matches the layout of `struct dirent` except for the trailing array.  But the field vary between platforms, and it would be difficult to keep in sync.  I'd rather just do this and rely on `libc` as the source of truth for the layout.

**Comment by RalfJung** [comment]
@cuviper friendly reminder that this is blocking getting readdir to work again in Miri. :)

**Comment by cuviper** [comment]
Sorry, yeah, looks good.

@bors r+

**Comment by tavianator** [comment]
I don't think the MSVC failure is related to this PR

**Pull request merged**
