### PR TITLE
Update rls and rustfmt and set them testing

### PR DESCRIPTION
**Pull request by nrc**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
This currently pulls in two versions of Cargo I think? If the Cargo submodule is updated as well though I think that should pull in 0.25.0, right?

**Comment by nrc** [comment]
OK, added a Cargo update which means only one version of Cargo again.

**Comment by alexcrichton** [comment]
@bors: r+

What could possibly go wrong if we update everything all at once?

**Comment by oli-obk** [comment]
> What could possibly go wrong if we update everything all at once?

Nothing apparently ;)

**Pull request merged**
