### PR TITLE
Accept less invalid Rust in rustdoc

### PR DESCRIPTION
**Pull request by oli-obk**
pulled out of https://github.com/rust-lang/rust/pull/117213 where this change was already approved

This only affects rustdoc, and has up to [20% perf regressions in rustdoc](https://github.com/rust-lang/rust/pull/117213#issuecomment-1785776288). These are unavoidable, as we are simply doing more checks now, but it's part of the longer term plan of making rustdoc more resistant to ICEs by only accepting valid Rust code.

### CODE REVIEW

**Comment by lqd** [comment]
Looks like unavoidable regressions for a correctness fix, and can be marked triaged.

**Comment by pnkfelix** [comment]
> Looks like unavoidable regressions for a correctness fix, and can be marked triaged.

agreed

@rustbot label: +perf-regression-triaged

**Comment by GuillaumeGomez** [comment]
For the relnotes: the effort to prevent broken code to be accepted by rustdoc will continue, closing the gap between rustc and rustdoc.

**Comment by jyn514** [comment]
these changes should have future incompat lints instead of going directly to breaking code

**Comment by saethlin** [comment]
The crater queue is long, so someone else here can kill the run if they think this is excessive.

@craterbot run mode=rustdoc start=d7d9f15be205b45d44700e7ac33b4f79b91f9680 end=50be22964035027398754e54cd3a497efb00f83e

**Comment by Mark-Simulacrum** [comment]
@craterbot abort

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=rustdoc start=master#d7d9f15be205b45d44700e7ac33b4f79b91f9680 end=master#50be22964035027398754e54cd3a497efb00f83e

**Pull request merged**
