### PR TITLE
Warn unused type aliases

### LINKED ISSUE #37455: Unused type alias does not produce warning
I created the following `main.rs`:

``` rust
type Unused = String;

fn main() {
    println!("Hello, world!");
}
```

Note that `Unused` is not `pub` and not used. Nevertheless no "unused" warning is given.

Here is the full (empty) output of `cargo build`:

``` shell
Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
```

### PR DESCRIPTION
**Pull request by sanxiyn**
The interesting part (type aliases used by UFCS) is already tested by `issue-23808.rs`. But it only tests used type aliases are not warned, so I added a simple test to test unused type aliases are warned.

Fix #37455.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? @eddyb 
(Overlap with `lazy-start`)

**Comment by eddyb** [comment]
What's the motivation between the changes to how path resolutions are stored?
I have a somewhat more complex design I've been working on, which satisfies the needs of incremental and on-demand type-checking.
It'd be already up but I'm still trying to untangle the privacy pass from syntactical types.

**Comment by sanxiyn** [comment]
The motivation is to read partial resolution after it is overwritten by full resolution in `def_map`, so that UFCS path can keep type alias alive.

It can be achieved by simply keeping a copy of `def_map` as returned by resolve, but this (`def_map` only stores full resolution) seemed cleaner to me.

**Comment by eddyb** [comment]
@sanxiyn Ah this is completely unnecessary on my branch, which has a separate HIR node for the original resolution (i.e. the `T` in `T::A`). Do you mind waiting for that?

**Comment by sanxiyn** [comment]
Sure. It would be much better if I can get the original resolution directly from HIR node without maintaining the side table. Thanks.

**Comment by eddyb** [comment]
@sanxiyn #37676 is up, you can probably rebase on top of it if you want (although I should fix Travis first).

**Comment by brson** [comment]
Nice fix.

**Comment by eddyb** [comment]
Sorry for the delay but this should be straight-forward now.

**Comment by petrochenkov** [comment]
Should this be closed?

**Comment by sanxiyn** [comment]
I will close this when the reimplementation lands.

**Pull request closed without merging**
