### PR TITLE
Stabilize `Option::unwrap_none` and `Option::expect_none`

### PR DESCRIPTION
**Pull request by Aaron1011**
cc #62633

These methods have been on nightly for over a year without any issues.

### CODE REVIEW

**Comment by cuviper** [comment]
I'm in favor, but there was some debate in #73077.

**Comment by Aaron1011** [comment]
I somehow missed that other PR when I read through the tracking issue.

**Comment by poliorcetics** [comment]
I really don’t like those methods over `assert(_...)!` macros. Maybe I just never encountered the cases when this becomes heavy to write but those methods just look like bloat to me.

**Comment by m-ou-se** [comment]
Closing this because of https://github.com/rust-lang/rust/issues/62633#issuecomment-777009499.

(Not closing the tracking issue yet. More discussion is still welcome there.

**Pull request closed without merging**
