### PR TITLE
Mention that enum constructors are functions

### LINKED ISSUE #25850: mention the possibility of using enum constructors as functions in expressions
Neither the nightly Rust reference nor the book seem to mention the fact that one can use enum constructors in a function like way inside expressions, eg. `my_iterator.map(Option::Some)`.

(unless I'm mistaken and it's there somewhere, but I didn't find it)

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #25850

### CODE REVIEW

**Comment by Gankro** [comment]
Strings seem distracting in this example. &'static str or i32 might keep this simpler unless there's a reason to avoid them?

**Comment by steveklabnik** [comment]
I kept `String`s because they're used in the enum above, specifically to avoid dealing with lifetime and copy issues.

**Pull request merged**
