### PR TITLE
Use Vec::drain in BufWriter

### PR DESCRIPTION
**Pull request by bluss**
Use Vec::drain in BufWriter

I happened past a comment that asked for functionality that we now have.

### CODE REVIEW

**Comment by sfackler** [comment]
Does calling `drain` actually remove the items or is it lazy?

**Comment by bluss** [comment]
It removes all the items regardless if you iterate it or not. I checked the compilation of this use case back when I added drain, it should compile to the same code.

**Comment by bluss** [comment]
Regarding laziness, during iteration it only reads out values (`ptr::read`), the actual removal doesn't happen until the `Drain` value is dropped (`ptr::copy` and `Vec::set_len`).

**Comment by alexcrichton** [comment]
@bors: r+ b9543ae360e27804747759cd4cc085ca4aaee80d

Yay!

**Comment by bluss** [comment]
Sigh, forgot to remove an import and didn't see that warning

**Comment by bluss** [comment]
Bors come back, stop being weird :sob:

**Comment by alexcrichton** [comment]
This passed all tests except for the android builder which apparently disappeared, so I'm going to merge this manually.

**Pull request merged**
