### PR TITLE
Remove `multiple-definitions` test

### PR DESCRIPTION
**Pull request by fee1-dead**
r? @joshtriplett

Temporary solution to #87084.

### CODE REVIEW

**Comment by ricobbe** [comment]
I should have a fix for the original test in a couple of hours.  Do we want to hold off on this, or what?

**Comment by petrochenkov** [comment]
For the future, adding `// ignore-test` with a FIXME would be more appropriate than outright removing the test.
(I'm not r-'ing this since the test is already going through pre-merge CI.)

**Comment by joshtriplett** [comment]
@ricobbe We can always re-add this the moment you have a fix.

@petrochenkov Good to know, thank you; I'll try to remember that for the future.

**Comment by ricobbe** [comment]
I should have a PR posted with a fix for this within the hour; that PR will re-add the test.

**Pull request merged**
