### PR TITLE
Move to intra doc links for core::ptr::non_null

### PR DESCRIPTION
**Pull request by poliorcetics**
Helps with #75080.

@rustbot modify labels: T-doc, A-intra-doc-links, T-rustdoc

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
r=me once CI is passing

**Comment by jyn514** [comment]
On reflection I realized that adding `T-rustdoc` to all of these makes the actual rustdoc changes really hard to find, so it would be great to only add T-doc in the future. A-intra-doc-links is still helpful though :)

**Comment by poliorcetics** [comment]
Oh sorry 😅

**Pull request merged**
