### PR TITLE
Check `RUSTC_CTFE_BACKTRACE` much less by generating fewer errors

### PR DESCRIPTION
**Pull request by wesleywiser**
Before this change, `get_size_and_align()`  calls `get_fn_alloc()` *a
lot* in CTFE heavy code. This previously returned an `Error` which would
check if `RUSTC_CTFE_BACKTRACE` was set on construction. Doing this
turned out to be a performance hotspot as @nnethercote discovered in
#68792.

This is an alternate take on that PR which resolves the performance
issue by generating *many* fewer errors. Previously, `ctfe-stress-4`
would generate over 5,000,000 errors each of which would check for the
presence of the environment variable. With these changes, that number is
reduced to 30.

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Looks good, r=me when perf agrees

**Comment by RalfJung** [comment]
(But I think there's a typo in the PR description where it fails to link to where @nnethercote discovered the problem.)

**Comment by wesleywiser** [comment]
Heh. Vim word-wrapped the line as I was typing the issue number and since git-commit ignores lines that start with `#`, it removed the line.

**Comment by RalfJung** [comment]
Also, adding the flag to the session as you proposed would still probably be better than the current env var scheme. Even if this solves the main perf problem, there is no good reason to make error creation *that* expensive.

**Comment by RalfJung** [comment]
8% speedup, nice :)

@bors r+ rollup=never
(@nnethercote I assume as this has perf impact it should not be rolled up?)

**Comment by wesleywiser** [comment]
@RalfJung Yeah, that's correct. PRs that impact performance shouldn't be rolled up.

**Comment by nnethercote** [comment]
Nice perf results! I didn't realize this would help benchmarks other than `ctfe-stress-4`, that's good to see.

**Comment by nnethercote** [comment]
BTW, before this lands can you reword the commit message so that the `#` doesn't appear at the start of a line?

**Comment by RalfJung** [comment]
@bors r-
for commit msg ediitng

**Pull request merged**
