### PR TITLE
Generate urls for default trait items as well

### LINKED ISSUE #62741: rustdoc doesn't render links in Trait Implementations sections
https://doc.rust-lang.org/nightly/std/iter/struct.Flatten.html#method.scan
image
https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.scan
image

As we can see, `fold` is not linked in the first image.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #62741

cc @rust-lang/rustdoc 

I expect this PR to fail since a lot(?) of new URLs will be generated. I used the same model as for short doc on items in module view.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Just like expected. :3

**Comment by gagan0723** [comment]
Ping from triage, @QuietMisdreavus can you please review this?

@GuillaumeGomez thanks for the PR 🙏. Some checks are failing, please fix them.

Thanks.

**Comment by GuillaumeGomez** [comment]
For the record: I tried a few things and it seems that the only one which may work would be to keep the `LinkCollector` object to rerun it and changing the item's parent to make it generate urls in the new context. To do so, we'll have to rework a bit the context handling to be able to either get rid of it or create a sub-struct that expect it as a parent when iterating over items.

**Comment by JohnCSimon** [comment]
Ping from triage.

@GuillaumeGomez can you please resolve the merge conflicts? I'm not sure what else needs to happen for this PR.

Thanks

**Comment by GuillaumeGomez** [comment]
To actually make it work? I wrote a small resume of what remained to be done in my previous comment.

**Comment by JohnCSimon** [comment]
Ping from triage.

@GuillaumeGomez @QuietMisdreavus  Just letting you know, this has sat idle for 12 days
Thanks

**Comment by joelpalmer** [comment]
Ping from Triage: Closing due to inactivity. Please re-open when/if there are updates. Thanks @GuillaumeGomez

**Pull request closed without merging**
