### PR TITLE
rustc: implement -C link-arg

### PR DESCRIPTION
**Pull request by japaric**
this flag lets you pass a _single_ argument to the linker but can be
used _repeatedly_. For example, instead of using:

```
rustc -C link-args='-l bar' (..)
```

you could write

```
rustc -C link-arg='-l' -C link-arg='bar' (..)
```

This new flag can be used with RUSTFLAGS where `-C link-args` has
problems with "nested" spaces:

```
RUSTFLAGS='-C link-args="-Tlayout.ld -nostartfiles"'
```

This passes three arguments to rustc: `-C` `link-args="-Tlayout.ld` and
`-nostartfiles"` to `rustc`. That's not what we meant. But this does
what we want:

```
RUSTFLAGS='-C link-arg=-Tlayout.ld -C link-arg=-nostartfiles`
```

cc rust-lang/rfcs#1509

r? @alexcrichton 
cc @Zoxc

This needs a test. Any suggestion?

### CODE REVIEW

**Comment by japaric** [comment]
> This needs a test. Any suggestion?

Added a simple test of using `-C link-arg` twice.

**Comment by retep998** [comment]
Can `-Clink-arg` be combined with `-Clink-args`? And will `-Clink-args` continue to support only being passed once?

**Comment by japaric** [comment]
> Can -Clink-arg be combined with -Clink-args? 

Yes, both sources get merged. 

> And will -Clink-args continue to support only being passed once?

This PR doesn't touch -Clink-args.

**Comment by jethrogb** [comment]
Could you add the attribute counterpart `#[link_arg]` as well?

**Comment by japaric** [comment]
@jethrogb That I'm not sure about. The docs [discourage](https://doc.rust-lang.org/book/advanced-linking.html#link-args) using `#[link_args]` and @alexcrichton [said](https://github.com/rust-lang/rust/issues/36176#issuecomment-243954914):

> This is an intentional design decision of #![link_args], and is one of the reasons it's not generally suitable for passing linker arguments. This "feature" has basically always been slated for deprecation/removal.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @japaric!

**Pull request merged**
