### PR TITLE
Bump compiler_builtins

### PR DESCRIPTION
**Pull request by mati865**
r? @ghost

cc https://github.com/rust-lang/compiler-builtins/issues/585

### CODE REVIEW

**Comment by kleisauke** [comment]
Thanks for doing this! Could you try removing this line?:
https://github.com/rust-lang/rust/blob/773fb88e13b06174d0ba48191731ea43ab6ac668/compiler/rustc_target/src/spec/base/windows_gnu.rs#L34

I'm not sure if that would work, this heavily assumes that the symbols Rust uses from `libgcc` is also provided by the `compiler-builtins` crate. 

FWIW, here's a list of symbols provided by `libgcc.a` for the `i686-w64-mingw32` target:
https://gist.github.com/kleisauke/ae9ea3100118bf704e19e41ae75d595f

**Comment by mati865** [comment]
> Thanks for doing this! Could you try removing this line?:
> 
> https://github.com/rust-lang/rust/blob/773fb88e13b06174d0ba48191731ea43ab6ac668/compiler/rustc_target/src/spec/base/windows_gnu.rs#L34

That is not easily doable. The build fails during stage0 -> stage1 compiler build which means it's still using prebuilt toolchain.
Changes to `compiler/` will be applied only after this step, so when using stage1 compiler.

**Comment by kleisauke** [comment]
> The build fails during stage0 -> stage1 compiler build which means it's still using prebuilt toolchain.

Ah, OK. I'm not sure if we could use `cfg(not(bootstrap))` in `compiler-builtins`, but if this is possible we might be able to do this:
```diff
--- a/src/x86.rs
+++ b/src/x86.rs
@@ -12,6 +12,7 @@ intrinsics! {
     #[cfg(all(
         windows,
         target_env = "gnu",
+        any(not(bootstrap), target_abi = "llvm"),
         not(feature = "no-asm")
     ))]
     pub unsafe extern "C" fn _alloca() {
```
i.e. make `_alloca` only available for `i686-pc-windows-gnu` if not bootstrapping and always available for the `i686-pc-windows-gnullvm` target.

**Comment by mati865** [comment]
No idea if that would work.

**Pull request closed without merging**
