### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by tmandry**
Successful merges:

 - #64925 (Document JSON message output.)
 - #65201 (Disable Go and OCaml bindings when building LLVM)
 - #65334 (Add long error explanation for E0575)
 - #65417 (Add more coherence tests)
 - #65455 (Avoid unnecessary `TokenTree` to `TokenStream` conversions)
 - #65472 (Use a sharded dep node to dep node index map)
 - #65480 (Speed up `LexicalResolve::expansion()`)
 - #65493 (Add long error explanation for E0584)
 - #65496 (properly document panics in div_euclid and rem_euclid)
 - #65498 (Plugins deprecation: don’t suggest simply removing the attribute)
 - #65508 (add option to ping llvm ice-breakers to triagebot)
 - #65513 (reorder fmt docs for more clarity)
 - #65531 (Update backtrace to 0.3.40)

Failed merges:

 - #65390 (Add long error explanation for E0576)
 - #65434 (Add long error explanation for E0577)
 - #65471 (Add long error explanation for E0578)
 - #65501 (Remove `src/llvm-emscripten` submodule)

r? @ghost

### CODE REVIEW

**Comment by tmandry** [comment]
https://github.com/rust-lang/rust/pull/65531#issuecomment-543535615 points out that that PR is likely to fail, so closing this in favor of a rollup without that PR.
@bors retry r-

**Comment by dtolnay** [comment]
For some reason this is still in the bors queue...?

@bors p- rollup-

**Pull request closed without merging**
