### PR TITLE
powerpc64-ibm-aix: update maintainters

### PR DESCRIPTION
**Pull request by daltenty**
Chaofan (@ecnelises) and Kai (@bzEq) will be passing over maintainership for the target over to David Tenty (@daltenty) and Chris Cambly (@gilamn5tr)

### CODE REVIEW

**Comment by daltenty** [comment]
FYI @ecnelises @bzEq @gilamn5tr

**Comment by bzEq** [comment]
LGTM from my side. Thanks David and Chris for taking over this role!

**Comment by ecnelises** [comment]
Thanks!

**Pull request merged**
