### PR TITLE
Hash the remapped sysroot instead of the original.

### PR DESCRIPTION
**Pull request by jgalenson**
One of the reasons that rustc builds are not reproducible is because the --sysroot path is dependent on the current directory.  We can fix this by hashing the remapped sysroot instead of the original when applicable.

Note that with this patch, the hash will stay the same if both the sysroot and the remapped path change.  However, given that if the contents of the sysroot change the hash will also stay the same, this might be acceptable.  I would appreciate feedback on the best way to do this.

This helps #34902, although it does not fix it by itself.

### CODE REVIEW

**Comment by cramertj** [comment]
This LGTM, but just to be sure, r? @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the PR! Since the sysroot argument is only used to load other libraries, which are themselves all tracked, I think we may be able to get by from just skipping the sysroot hashing entirely?

**Comment by jgalenson** [comment]
I didn't know the other libraries were themselves tracked; that does make this cleaner.  All the tests seemed to pass locally, so here it is.

**Comment by jgalenson** [comment]
There's a problem with the test runner: the Azure dashboard shows the test as having passed about 20 hours ago, but the Github dashboard doesn't see it.  Can the test be restarted or something?

**Comment by alexcrichton** [comment]
That's ok those are just PR tests, this is [in the queue](https://buildbot2.rust-lang.org/homu/queue/rust) to be tested and merged in full.

**Comment by jgalenson** [comment]
Ah, okay.  Thanks!

**Comment by RalfJung** [comment]
Looks like the PR title / description no longer reflects the PR content?

**Pull request merged**
