### PR TITLE
Implement `core::future::join!`

### PR DESCRIPTION
**Pull request by ibraheemdev**
`join!` polls multiple futures concurrently and returns their outputs.

```rust
async fn run() {
    let (a, b) = join!(async { 0 }, async { 1 }).await;
}
```

cc @rust-lang/wg-async-foundations

### CODE REVIEW

**Comment by joshtriplett** [comment]
I've seen multiple people observe, in various different contexts, that `join!(a, b, c)` should not implicitly include an `.await`; instead, it should return a future, such that `join!(a, b, c).await` is a concurrent equivalent of `(a.await, b.await, c.await)`.

That would also make it equivalent to the `join` async function, which returns a future that requires awaiting. It seems confusing to have `join(a, b).await` but just `join!(a, b, c)` with no `.await`.

**Comment by joshtriplett** [comment]
Since this is unstable and feature-gated, I'm going to go ahead and r+ it.

@bors r+

**Comment by yoshuawuyts** [comment]
Note: the @rust-lang/wg-async-foundations working group was not notified of this change prior to merging.

I would've liked to have a chance to comment on this design, as I think it is part of a larger topic of async concurrency which warrants an RFC, and should not be merged into the stdlib in a piece-meal fashion.

**Comment by yaahc** [comment]
> I would've liked to have a chance to comment on this design, as I think it is part of a larger topic of async concurrency which warrants an RFC, and should not be merged into the stdlib in a piece-meal fashion.

I do want to note that the reason this didn't get an RFC is because the libs team changed the requirements for adding new features and when they need RFCs in an attempt to ease the contribution experience and make it easier to experiment with new APIs. Us approving a nightly only API is in no way an endorsement that we believe a change should be stabilized, and there is still plenty of time to comment on the design. While I agree that this change and the associated story likely warrant an RFC I want to be careful that we don't overcorrect and institute process changes as a result.

**Comment by yoshuawuyts** [comment]
> I do want to note that the reason this didn't get an RFC is because the libs team changed the requirements for adding new features and when they need RFCs in an attempt to ease the contribution experience and make it easier to experiment with new APIs.

Ah, thanks for clarifying. I was not aware the policy had changed.

**Pull request merged**
