### PR TITLE
Allow lifetimes in macros

### PR DESCRIPTION
**Pull request by mikeyhew**
This is a resurrection of PR #33135.

@sgrif can you take a look at the following diffs from #33135, and see if those changes are still necessary?

- [src/libsyntax/ext/tt/transcribe.rs](https://github.com/rust-lang/rust/pull/33135/files#diff-accdc3605fc908f27c2bbb1c929842c1) This was refactored by @jseyfried, so he may be able to weigh in.
- [src/libsyntax/parse/parser.rs](https://github.com/rust-lang/rust/pull/33135/files#diff-da9d34ca1d0f6beee2838cf02e07345c)

Still to do:

- [ ] Make sure CI passes
- [ ] Get approval from @sgrif, since he wrote the code
- [ ] Feature gate

### CODE REVIEW

**Comment by shepmaster** [comment]
Thanks @mikeyhew! We'll get @pnkfelix to take a look at this PR shortly!

**Comment by kennytm** [comment]
All three tests failed, "expected one of `>`, identifier, or lifetime, found `'a`". 

---

BTW, could you add some tests to show that the patch handles labels?

```rust
#![allow(unreachable_code)]

macro_rules! x {
    ($a:lifetime) => {
        $a: loop {
            break $a;
            panic!("failed");
        }
    }
}
macro_rules! br {
    ($a:lifetime) => {
        break $a;
    }
}
macro_rules! br2 {
    ($b:lifetime) => {
        'b: loop {
            break $b; // this $b should refer to the outer loop.
        }
    }
}
fn main() {
    x!('a);
    'c: loop {
        br!('c);
        panic!("failed");
    }
    'b: loop {
        br2!('b);
        panic!("failed");
    }
}
```

**Comment by mikeyhew** [comment]
Thanks @kennytm, and sure, I'll add those tests. What is the quickest way to run tests for libsyntax? Anything with `--stage 1` seems to take *forever* to build.

**Comment by petrochenkov** [comment]
@mikeyhew 
>Anything with --stage 1 seems to take forever to build.

Do you include LLVM build and similar in "forever"? It only needs to be done once.
"Development cycle" includes only build from modifying libsyntax to running stage 1 tests.
The only way to speed it up that I know is to set `codegen-units = 0` in `config.toml`, with it `time ../x.py test --stage 1 src/test/run-pass --test-args macroxxx` gives `real    4m14.233s`. Slow, but not forever (I'm on a relatively fast desktop machine though).
You can also try to add `--incremental` to the `x.py` command line (I haven't measured time for it because it breaks the build on my machine.).

**Comment by mikeyhew** [comment]
I'm too busy with school right now, and I still don't really understand the code in this PR so I'm going to give up. Someone else will have to take over for this to get implemented.

**Pull request closed without merging**
