### PR TITLE
Remove 'yet to be added' from API docs

### LINKED ISSUE #25728: io::Error docs mention that error::Error downcasting is yet to be added.
http://doc.rust-lang.org/stable/std/io/struct.Error.html#method.new

The methods it talks about now exist, but are currently unstable: http://doc.rust-lang.org/stable/std/error/trait.Error.html#method.is. Not sure if the docs should be updated now or after stabilization

cc @steveklabnik

### PR DESCRIPTION
**Pull request by steveklabnik**
In general, this kind of text gets outdated, as it already sorta kinda is.

Fixes #25728

### CODE REVIEW

**Comment by sfackler** [comment]
I actually have a PR that both adds those methods and removes that part of the docs :) https://github.com/rust-lang/rust/pull/25816

**Comment by Gankro** [comment]
Closing in favour of #25816

**Comment by steveklabnik** [comment]
oh well awesome :)

**Pull request closed without merging**
