### PR TITLE
Fix a typo in the Rust Book ownership page.

### PR DESCRIPTION
**Pull request by liammonahan**
Found a small typo on the Rust book "ownership" page.

Best,
Liam

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hey Liam!

So, I can see how this sentence can be a tad confusing, but your edit doesn't exactly work either.

> Here are some examples of functions with elided lifetimes, along with versions
> of what the elided lifetimes expand to:

To me, this says that each example has multiple versions. What do you think about a re-word like this?

> Here are some examples of functions with elided lifetimes. For each example, we show both the elided and expanded version.

**Comment by liammonahan** [comment]
Hi Steve,

Thanks for your feedback.  I think we're having a disagreement about number.  In your suggested sentence, if I took out "the elided and expanded", I would get:

> For each example, we show both version.

Adding that enumeration shouldn't change the number of the word "versions."  This is also the reason why my originally-proposed sentence was actually correct, but I'm fine to agree on the following before I commit:

> Here are some examples of functions with elided lifetimes. For each example, we show both the elided and expanded versions.

**Comment by steveklabnik** [comment]
You took out words that matter though. 'both' refers to 'the elided version' and 'the expanded version,' but it's not considered good style to repeat yourself so often. If you take out one of the two things, of course it will sound strange!

I wonder if this is some sort of dialect issue. I'm fine with using `versions`, as your last comment suggests, though :)

**Comment by liammonahan** [comment]
Hi Steve,

Usually I would have rolled over by this point, but in the spirit of the quote by Emma Goldman on your blog, I will persist. :)  Taking out or adding "the elided and expanded" does not change the structure of the rest of the sentence.  It merely specifies which versions are meant by "both."  This is the only relevant stackexachange I could find on the topic: http://english.stackexchange.com/questions/101332/both-the-first-and-the-last-plural-vs-both-the-first-and-the-last-singula

I'd like to come up with something that we can both agree on unequivocally, so how about this?

> Here are some examples of functions with elided lifetimes.  We've paired each example of an elided lifetime with its expanded form.

I'm sorry if this whole thread has come off as a little too pugnacious on my part.  I really do admire the herculean documentation task that you've taken on as far as the Rust project is concerned.  I think it's some of the best documentation out there.

Thanks,
Liam

**Comment by steveklabnik** [comment]
Ha! :heart: 

I'm fine with that last sentence.

**Comment by liammonahan** [comment]
Good deal.  It's all committed and ready for bors when you are.

**Pull request merged**
