### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #67806 (Extract `rustc_ast_passes`, move gating, & refactor linting)
 - #68037 (Distribution CI for riscv64gc-unknown-linux-gnu)
 - #68043 (Add some missing timers)
 - #68074 (Add `llvm-skip-rebuild` flag to `x.py`)
 - #68079 (Clarify suggestion for E0013)
 - #68084 (Do not ICE on unicode next point)
 - #68102 (Inline some conversion methods around OsStr)
 - #68106 (Fix issue with using `self` module via indirection)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by alex** [comment]
@Centril This is not a flake, it's a bug in #68037

**Comment by Centril** [comment]
Argh; it wasn't intentional to include that PR :(

**Comment by Centril** [comment]
Recreating...

**Pull request closed without merging**
