### PR TITLE
impl Error for !

### PR DESCRIPTION
**Pull request by canndrew**
`impl Error for ! { ... }`

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 7df8271703557857a004d43ce2902ec7b3279afe

Thanks!

**Comment by eddyb** [comment]
@bors r-

Travis results in "Aborted (core dumped)" while running std tests.

**Comment by canndrew** [comment]
Not sure what's causing this. The test which is aborting is [here](https://github.com/rust-lang/rust/blob/9376da6f77e8b7ed204ee704b29e96213b69d0f1/src/libstd/io/stdio.rs#L672). It aborts at the very start of the spawned thread. Specifically, I can see execution get to [`thread_start`](https://github.com/rust-lang/rust/blob/9376da6f77e8b7ed204ee704b29e96213b69d0f1/src/libstd/sys/unix/thread.rs#L72), then [`start_thread`](https://github.com/rust-lang/rust/blob/9376da6f77e8b7ed204ee704b29e96213b69d0f1/src/libstd/sys/common/thread.rs#L17), then `call_box` starts unwinding (but without executing the closure that was passed to `spawn`). After that, `_Unwind_Resume` gets called from `thread_start` and aborts.

I'm guessing the problem has something to do with the closure returning `!` with `feature(never_type)` enabled by this PR. I haven't been able to reproduce the bug in isolation though.

Can anyone suggest a good next step for debugging this? I'd like to know why it starts unwinding to begin with.

**Comment by alexcrichton** [comment]
I suspect that's bad but not *this PR* bad, let's see what bors has to say:

@bors: r+

**Comment by canndrew** [comment]
Damn. I dunno what to make of that log though, both the panics that it mentions at the bottom are panics that were supposed to occur.

**Comment by alexcrichton** [comment]
Hm that failed at about the same location as travis, so maybe not spurious?

**Comment by canndrew** [comment]
Yeah I'd say it's getting to [this test](https://github.com/rust-lang/rust/blob/9376da6f77e8b7ed204ee704b29e96213b69d0f1/src/libstd/io/stdio.rs#L672) again and aborting. Any idea why? Is there any reason why a closure would start panicking as soon as it's called?

**Comment by alexcrichton** [comment]
Maybe? Not sure. Best next option is likely to reproduce locally so we're not just poking in the dark.

**Comment by canndrew** [comment]
Is there an easy way to get the make system to spit out MIR and LLVM code for the libstd tests? I don't know how to reproduce this locally.

By the way, it is caused by `#![feature(never_type)]` being enabled on the crate, not by the impl.

**Comment by alexcrichton** [comment]
LLVM IR can be emitted with `--emit llvm-ir`, as for MIR though I'm not entirely sure (cc @eddyb)

**Comment by eddyb** [comment]
MIR is `--unpretty=mir -Zunstable-options` or `-Zdump-mir=PreTrans`.
The latter dumps it all in the current dir, one file per function. You can change `PreTrans` to any pass name you want to get before and after MIR.

**Comment by canndrew** [comment]
I just had another look at this. It looks like it crashes [here](https://github.com/rust-lang/rust/blob/46957f05771a427545c792f69b37f8e05dcbb15d/src/libstd/panicking.rs#L329) when it tries to use `mem::uninitialized` to create an uninitialised `!`.

**Comment by canndrew** [comment]
Here's how I fixed this: In the old code, `panicking::try` took a type argument `R` and created an `R` using `mem::uninitialized()`:

```rust
let r: R = mem::uninitialized();
```

Later, it either reads the value out of `r` or calls `mem::forget` on it depending on whether a value was written there.

When `R` is `!` though, this could cause the code to crash. This is fair enough since having an invalid value around is undefined behavior and `R` doesn't have any valid values. So instead I wrapped it in a union:

```rust
union MaybeUninitialized<R> {
    data: R,
    _uninitialized: (),
}

let r: MaybeUninitialized<R> = mem::uninitialized();
```

This is fine since a `MaybeUnitialized<R>` is always valid since it's `_uninitialized` field always contains a valid value.

However this does raise a problem: until now we've always just assumed that `mem::uninitialized` is okay to use so long as the uninitialized data is never read and is always overwritten or forgotten. But in the presence of `!` this doesn't seem to be true, at least not with the current implementation.

**Comment by alexcrichton** [comment]
Hm in theory we shouldn't have to change the code for something like this, doesn't that mean a bug in the compiler?

**Comment by eddyb** [comment]
@alexcrichton Sadly, no. Unsafe code everywhere using closures can have subtle dependencies on the closures returning an inhabited type, before the closure has a chance to stop the control-flow.
This is one of those things that is hard to track down and we need to build tools to analyze the ecosystem.

cc @rust-lang/compiler

**Comment by canndrew** [comment]
I didn't even have to use `uninitialized` in the final code, I could have initialized the union as `MaybeUninitialized { _uninitialized: () }`. This seems like a better way of writing this sort of code since `uninitialized::<!>` is a diverging function (has type `fn() -> !`).

**Comment by canndrew** [comment]
An alternative would be to change the way divergence works for `unsafe` functions and say that just because it returns an uninhabited type doesn't mean it never returns because `unsafe` functions can return invalid instances of a type. That seems like a much messier solution though.

**Comment by alexcrichton** [comment]
@eddyb it seems... bad though if we add `!` and suddenly all unsafe code ever written now needs to be re-audited to be correct? Surely there's somewhere else in the standard library this applies to as well at least?

**Comment by eddyb** [comment]
@alexcrichton Yeah it's not ideal, we'll have to discuss it. @rust-lang/lang is probably more appropriate.

**Comment by canndrew** [comment]
One way to avoid an audit would be to put a `T: Inhabited` bound on `uninitialized`.

It's a pretty fundamental problem though. Functions that return an uninhabited type don't return at all. Except `uninitialized` does return because it doesn't necessarily return a sane value. It's kind of a weird, type-system-defying intrinsic.

This doesn't just effect `!` either. The only difference between `!` and any other uninhabited type *should* be the invisible coercions except right now there are some places in the compiler that check for `!` specifically when they could check for uninhabited types generally. If those places ever get fixed this bug will probably spread to `Void` as well (if it doesn't effect it all ready).

**Comment by aturon** [comment]
cc https://internals.rust-lang.org/t/mem-uninitialized-and-trap-representations/4167/1

**Comment by alexcrichton** [comment]
Ok, I'm going to close this for now in favor of that internals thread (in the interest of clearing out the queue), but we can certainly reopen/resubmit once that's handled!

**Pull request closed without merging**
