### PR TITLE
Revert Allow destructuring opaque types in their defining scopes

### PR DESCRIPTION
**Pull request by matthiaskrgr**
reverts PR #98582

This reverts commit 6f8fb911ad504b77549cf3256a09465621beab9d, reversing
changes made to 7210e46dc69a4b197a313d093fe145722c248b7d.

r? @ghost

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Ouff sorry for all the pings, is there a way to make rustbot not do that? :/

**Comment by oli-obk** [comment]
@bors r+

I'll undo the revert in a new PR and figure out the perf regression there

**Comment by oli-obk** [comment]
Looks like the regression is entirely due to `is_useful` taking more CPU time

**Pull request closed without merging**
