### PR TITLE
Rollup of 15 pull requests

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
- Successful merges: #44124, #44287, #44320, #44694, #44708, #44794, #44797, #44824, #44836, #44840, #44845, #44854, #44889, #44900, #44903
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/43402

**Comment by frewsxcv** [comment]
Was this already pushed to master?

**Comment by Mark-Simulacrum** [comment]
Yes, actually. Closing.

**Pull request closed without merging**
