### PR TITLE
save-analysis: remove a lot of stuff

### PR DESCRIPTION
**Pull request by nrc**
This commits us to the JSON format and the more general def/ref style of output, rather than also supporting different data formats for different data structures. This does not affect the RLS at all, but will break any clients of the CSV form - AFAIK there are none (beyond a few of my own toy projects) - DXR stopped working long ago.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
r=me with Travis paaaing

**Comment by aidanhs** [comment]
Travis failure:
```
[00:43:13] error: internal compiler error: /checkout/src/librustc/hir/map/mod.rs:386: local_def_id: no entry for `259`, which has a map of `Some(EntryTraitRef(NodeId(257), TraitRef { path: path(SomeTrait), ref_id: NodeId(259) }))`
```

**Comment by ishitatsuyuki** [comment]
Travis failing. Please r-.

**Pull request merged**
