### PR TITLE
Prepare everything for distributing miri via rustup

### PR DESCRIPTION
**Pull request by oli-obk**
The next step is to tell rustup about `cargo-miri` in https://github.com/rust-lang/rustup.rs/blob/31935e5f633a5acd3a203d23b61d1556c64a821c/src/rustup/lib.rs#L28 and https://github.com/rust-lang/rustup.rs/blob/1ccd706d1d572c777c5134bd7db7aa1a8df7f278/src/rustup-win-installer/src/lib.rs#L29

### CODE REVIEW

**Comment by kennytm** [comment]
@oli-obk The dist doesn't seem successful.

```
[01:50:36] Building stage2 tool miri (x86_64-unknown-linux-gnu)

[01:50:37] error: Package `miri v0.1.0 (/checkout/src/tools/miri)` does not have these features: `rustc-workspace-hack`

[01:50:37] 

[01:50:37] 

[01:50:37] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/miri/Cargo.toml" "--features" "rustc-workspace-hack/all-static" "--message-format" "json"

[01:50:37] expected success, got: exit code: 101

[01:50:37] Unable to build miri, skipping dist

[01:57:40] Build completed successfully in 1:53:28
```

**Comment by RalfJung** [comment]
This might be caused by https://github.com/rust-lang/rust/pull/56924 not having landed yet.

**Comment by kennytm** [comment]
Marking this as "blocked" then.

**Comment by RalfJung** [comment]
Miri has been updated, so this can proceed now.

**Comment by kennytm** [comment]
<details><summary>winapi feature mismatch</summary>

```
duplicate artifacts found when compiling a tool, this typically means that something was recompiled because a transitive dependency has different features activated than in a previous build:
the following dependencies are duplicated although they have the same features enabled:
  winapi-util 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi_util-99433a355166b63c.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi_util-45568a2709ed2c5a.rlib")
  backtrace 0.3.11 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libbacktrace-3a1ef57ff65fc384.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libbacktrace-55c2819bab96ebb6.rlib")
  curl-sys 0.4.15 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libcurl_sys-caecc71021b45f02.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libcurl_sys-be31cbf23def53b1.rlib")
  atty 0.2.11 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libatty-6f98353814470659.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libatty-6841a51755c86259.rlib")
  rand 0.5.5 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\librand-f5eabde797527f2f.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\librand-bafb7955617bdefe.rlib")
  wincolor 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwincolor-ae3f1502c9f40bba.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwincolor-25738d5f35fd22b0.rlib")
  error-chain 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\liberror_chain-ee74d0268356f343.rlib")
    `clippy-driver` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\liberror_chain-0e9c5430369aea41.rlib")
  parking_lot_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libparking_lot_core-eb027f15f6f5f04d.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libparking_lot_core-d8be4152740a36f2.rlib")
  termcolor 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libtermcolor-b2c3256f48cfd1bf.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libtermcolor-9c3466320343e801.rlib")
  parking_lot 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libparking_lot-3993c4a08024a6df.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libparking_lot-347975fe1e7bbb4a.rlib")
  rustc-workspace-hack 1.0.0 (path+file:///C:/projects/rust/src/tools/rustc-workspace-hack)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\librustc_workspace_hack-3d92713b67de638b.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\librustc_workspace_hack-336224035bee3bac.rlib")
  env_logger 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libenv_logger-997f4995297e4e7e.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libenv_logger-71b31beb29050769.rlib")
  cargo_metadata 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libcargo_metadata-b9264916ec663b77.rlib")
    `clippy-driver` ("C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libcargo_metadata-b9fff641a4e8ef5c.rlib")
the following dependencies have different features:
  winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)
    `miri` additionally enabled features {"knownfolders", "objbase", "shlobj"} at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi-9b8933e1b03fce54.rlib"
    `cargo` additionally enabled features {} at "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi-b21f9c741ca40796.rlib"
to fix this you will probably want to edit the local src/tools/rustc-workspace-hack/Cargo.toml crate, as that will update the dependency graph to ensure that these crates all share the same feature set
```

</details>

**Comment by mati865** [comment]
@oli-obk you should add `["knownfolders", "objbase", "shlobj"]` to https://github.com/rust-lang/rust/blob/master/src/tools/rustc-workspace-hack/Cargo.toml#L24-L50

**Comment by kennytm** [comment]
Please rebase :(

**Pull request merged**
