### PR TITLE
don't reexport atomic::ordering via rustc_data_structures, use std import

### PR DESCRIPTION
**Pull request by klensy**
This looks simpler.

### CODE REVIEW

**Comment by compiler-errors** [comment]
These exports seemed to be introduced in #56614, but I don't see why that's advantageous over just using std here.

@bors r+

**Comment by compiler-errors** [comment]
@bors r-

Failed this rollup: https://github.com/rust-lang/rust/pull/119557#issuecomment-1876172158

**Comment by klensy** [comment]
rebased and fixed non-parallel import usage.

@rustbot ready

**Pull request merged**
