### PR TITLE
Revert "DO NOT MERGE: enable windows try builder"

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This reverts commit 90a37bce44d145715eeac9f1f2f34433fc813ef0.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @Mark-Simulacrum 

Straight up approving since try is currently broken (and this commit is explicitly marked as DO NOT MERGE).

@bors r+ p=1000

**Comment by pietroalbini** [comment]
r=me as well.

**Comment by hellow554** [comment]
Can you explain why it happened? Was it an accident? Some oversight?

**Comment by pietroalbini** [comment]
Forgot to remove that commit before the r=alex.

**Pull request merged**
