### PR TITLE
Rustdoc accessibility: make the sidebar headers actual headers

### PR DESCRIPTION
**Pull request by notriddle**
Part of #87059

Preview it at: https://notriddle.com/notriddle-rustdoc-test/rustdoc-sidebar-header/std/index.html

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good to me overall! Please fix the rustdoc tests and it should be good to go. :)

**Comment by GuillaumeGomez** [comment]
Just to be sure: did you rebase on the master branch? I don't see any other reason why it would fail otherwise...

**Comment by notriddle** [comment]
@GuillaumeGomez

I figured out the problem. The test case was trying to focus on the `<h3 class=sidebar-title>`, when it really needed to focus on the link inside of it.

**Comment by GuillaumeGomez** [comment]
Oh I see! Great catch. :)

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
