### PR TITLE
Update the shown installed rust version to 1.0

### PR DESCRIPTION
**Pull request by coffeejunk**
Rust is out of beta :tada: 

r? @steveklabnik

### CODE REVIEW

**Comment by Stebalien** [comment]
Could you fix the links as well (see #25489)?

**Comment by coffeejunk** [comment]
Done @Stebalien

**Comment by alexcrichton** [comment]
@bors: r+ e095e3963eb02e979ef16797f605cfc14f396e09 rollup

Thanks!

**Comment by Stebalien** [comment]
Could you backport this to the 1.0 book?

**Comment by steveklabnik** [comment]
We do not do doc backports.

**Comment by Stebalien** [comment]
@steveklabnik Why not? The link in the doc is wrong and this is the second person to download the wrong rust.

**Comment by steveklabnik** [comment]
There will always be things wrong in every release. You could also make the case that a new bug that gets fixed on master should be backported, because `rustc` does something wrong.

So, given that no software is perfect, you have to ask 'what's the criteria for backporting'? And, given that we already release new `y` (as in `x.y.z`) versions of the compiler every six weeks, `z` versions are basically only going to be released for security or soundness reasons. So that's why things won't be backported to 1.0.

You could make an argument about backporting to 1.1, but we've decided generally to be _very_ conservative with the stable branch. That's part of it being stable. I may end up doing a few particularly egregious fixes, like the table formatting in the stack and the heap, if that didn't make it in before beta, but that's only for 1.1: in general, after that, we won't be doing any doc backporting generally.

**Comment by Stebalien** [comment]
Fair enough.

**Pull request merged**
