### PR TITLE
Fix normalization error

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Follows #40163. I don't know whether this is good, but seems logical.

[This block of code](https://github.com/rust-lang/rust/blob/ba07bd5d23aced6d4baa5696213b11ca832c1a5d/src/librustc_typeck/check/mod.rs#L2110-L2138) doesn't contain a call to `normalize_associated_types_in`, while [this](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L2027-L2028) block does, and is nearly identical.

Ideally these two blocks should be unified into one, but since the change doesn't seem trivial and I'm unsure if this patch will be accepted it hasn't been done yet.

r? @arielb1

### CODE REVIEW

**Comment by arielb1** [comment]
Nice catch! This is indeed an oversight I have made.

If you can merge the 2 blocks, that would be excellent (and I'll r+ it).

**Comment by Mark-Simulacrum** [comment]
Pushed a unification and another commit which removes references to `Ty` as suggested by eddyb.

**Comment by arielb1** [comment]
nit: I would rather have a name like `apply_defaults_and_return_conflicts` or something. Having a `find_conflicting_defaults` function called on a non-error path is confusing.

r+ modulo nit.

**Comment by Mark-Simulacrum** [comment]
Changed name to suggested `apply_defaults_and_return_conflicts`.

**Pull request merged**
