### PR TITLE
improve codegen of fmt_num to delete unreachable panic

### PR DESCRIPTION
**Pull request by iximeow**
it seems LLVM doesn't realize that `curr` is always decremented at least once in either loop formatting characters of the input string by their appropriate radix, and so the later `&buf[curr..]` generates a check for out-of-bounds access and panic. this is unreachable in reality as even for `x == T::zero()` we'll produce at least the character `Self::digit(T::zero())`, yielding at least one character output, and `curr` will always be at least one below `buf.len()`.

adjust `fmt_int` to make this fact more obvious to the compiler, which fortunately (or unfortunately) results in a measurable performance improvement for workloads heavy on formatting integers.

in the program i'd noticed this in, you can see the `cmp $0x80,%rdi; ja 7c` here, which branches to a slice index fail helper:
before

where after this change the function is broadly similar, but smaller, with one fewer registers updated in each pass through the loop in addition the never-taken `cmp/ja` being gone:
after

this represents a ~2-3% difference in runtime in my [admittedly comically i32-formatting-bound](https://github.com/athre0z/disas-bench/blob/master/bench/yaxpeax/src/main.rs#L58-L67) use case (printing x86 instructions, including i32 displacements and immediates) as measured on a ryzen 9 3950x.

the impact on `<impl LowerHex for i8>::fmt` is both more dramatic and less impactful: it continues to have a loop that is evaluated at most twice, though the compiler doesn't know that to unroll it. the generated code there is identical to the impl for `i32`. there, the smaller loop body has less effect on runtime, and removing the never-taken slice bounds check is offset by whatever address recalculation is happening with the `lea/add/neg` at the end of the loop. it behaves about the same before and after.

---

i initially measured slightly better outcomes using `unreachable_unchecked()` here instead, but that was hacking on std and rebuilding with `-Z build-std` on an older rustc (nightly 5b377cece, 2023-06-30). it does not yield better outcomes now, so i see no reason to proceed with that approach at all.

<details>
<summary>initial notes about that, seemingly irrelevant on modern rustc</summary>
i went through a few tries at getting llvm to understand the bounds check isn't necessary, but i should mention the _best_ i'd seen here was actually from the existing `fmt_int` with a diff like
```diff
        if x == zero {
            // No more digits left to accumulate.
            break;
        };
    }
}
+
+ if curr >= buf.len() {
+     unsafe { core::hint::unreachable_unchecked(); }
+ }
let buf = &buf[curr..];
```

posting a random PR to `rust-lang/rust` to do that without a really really compelling reason seemed a bit absurd, so i tried to work that into something that seems more palatable at a glance. but if you're interested, that certainly produced better (x86_64) code through LLVM. in that case with `buf.iter_mut().rev()` as the iterator, `<impl LowerHex for i8>::fmt` actually unrolls into something like

```
put_char(x & 0xf);
let mut len = 1;
if x > 0xf {
  put_char((x >> 4) & 0xf);
  len = 2;
}
pad_integral(buf[buf.len() - len..]);
```

it's pretty cool! `<impl LowerHex for i32>::fmt` also was slightly better. that all resulted in closer to an 6% difference in my use case.

</details>

---

i have not looked at formatters other than LowerHex/UpperHex with this change, though i'd be a bit shocked if any were _worse_.

(i have absolutely _no_ idea how you'd regression test this, but that might be just my not knowing what the right tool for that would be in rust-lang/rust. i'm of half a mind that this is small and fiddly enough to not be worth landing lest it quietly regress in the future anyway. but i didn't want to discard the idea without at least offering it upstream here)

### CODE REVIEW

**Comment by workingjubilee** [comment]
> (i have absolutely no idea how you'd regression test this, but that might be just my not knowing what the right tool for that would be in rust-lang/rust. i'm of half a mind that this is small and fiddly enough to not be worth landing lest it quietly regress in the future anyway. but i didn't want to discard the idea without at least offering it upstream here)

@iximeow this can in fact be regression-tested! we'd use a codegen (llvm level) or assembly (x86-64 level) test. they use [FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html) to verify that a certain pattern is fulfilled, and can be parameterized with a bit of fussing with their DSL and regex so that e.g. it doesn't matter exactly which `r[axsbi0-9]{2}` register you're using. a codegen test is _slightly_ preferred for this as it would be "platform-independent" to some degree, but i'd be happy to accept this with an assembly test.

**Comment by iximeow** [comment]
are there codegen tests for how rustc compiles `core`? (or `std`?) those are what i couldn't find under `library/test`. there are benches under `library/core/benches/fmt.rs` that seem relevant but i couldn't follow those to test executions so i'm not sure if they're intended for more one-off spot checking of changes.

**Comment by iximeow** [comment]
> Overall result: ❌ regressions - no action needed

:raised_eyebrow: or given that i expected this at worst to have _no_ effect, maybe i should double-check how `core/benches/fmt.rs` looks before/after too..

**Comment by workingjubilee** [comment]
@iximeow That performance suite, and the remark, is about compiler tests, primarily. There's a runtime perf suite, but it showed no change. It's not surprising to me that rustc isn't affected by this change, and the two tests it is affected on are "noisy" tests that reflect synthetic stress tests.

> are there codegen tests for how rustc compiles core? (or std?) those are what i couldn't find under library/test.

It will be under `tests/codegen` not `library/tests`, sadly. The `library/tests` are only for those that can be run by the "usual" Rust test suite.

An example that is relevant is this, with its `CHECK-NOT: panic`:

https://github.com/rust-lang/rust/blob/e3df96cfda905301fc8514e000f942222c1ab6ad/tests/codegen/vec-shrink-panik.rs

**Comment by workingjubilee** [comment]
@iximeow the perf bot's default remarks are also based on instructions executed. note that the wall time is reduced:

unicode-normalization, clap, and bitmaps all showing a wall time improvement

this, combined with the (slight) binary size reduction, in generated artifacts (admittedly, the only non-synthetic mark here is helloworld):
helloworld size reduction

suggests to me that this may in fact be resulting in smaller code sizes with better cache layout. also, I'd be happy to accept the `unreachable_unchecked` if given an LLVMIR codegen test specifically.

**Comment by iximeow** [comment]
i added `fmt_int_no_panic.rs` in https://github.com/rust-lang/rust/pull/122770/commits/cea973f857b63e7c208e822d95c06c4883062449 and quickly figured out i don't know how to get it to test that the _right_ function does not panic. the fact that the test passes is misleading.

for tests like `vecdeque_no_panic.rs` it seems that the assertions are strongly reliant on the tested functions being inlined, and in cases like those if `front` or `back` were outlined the test might appear to pass because no `panic` would exist in `fn dont_panic`, but a panic _may_ exist in `fn front` when called. so it looks like that test would want to include a `// CHECK-NOT: call` to be certain we're checking all the IR. same goes for `vec-shrink-panik` etc.

this is a problem for the new `fmt_into_no_panic` because `core::fmt::write` is resistant to inlining and the function i want to check is a few calls away from what i can write in the test. `fn format_int_doesnt_panic` produces IR like...

```
; Function Attrs: nonlazybind uwtable
define noundef zeroext i1 @format_int_doesnt_panic(ptr noalias noundef align 8 dereferenceable(24) %s) unnamed_addr #0 {
_ZN4core3fmt9Arguments12as_const_str17hf62647c4668d295dE.exit.i:
  %_14 = alloca [1 x %"core::fmt::rt::Argument<'_>"], align 8
  %args2 = alloca %"core::fmt::Arguments<'_>", align 8
  %_7 = alloca [1 x %"core::fmt::rt::Argument<'_>"], align 8
  %args = alloca %"core::fmt::Arguments<'_>", align 8
  call void @llvm.lifetime.start.p0(i64 48, ptr nonnull %args)
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %_7)
  store ptr @alloc_914b2c69d7eca30497b9feaf15ac92f1, ptr %_7, align 8
  %0 = getelementptr inbounds i8, ptr %_7, i64 8
  store ptr @"_ZN4core3fmt3num52_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u8$GT$3fmt17hac9971cd5590704cE", ptr %0, align 8
  store ptr @alloc_b99730e73100e73a81f4fbfe74b3821d, ptr %args, align 8
  %1 = getelementptr inbounds i8, ptr %args, i64 8
  store i64 1, ptr %1, align 8
  %2 = getelementptr inbounds i8, ptr %args, i64 32
  store ptr null, ptr %2, align 8
  %3 = getelementptr inbounds i8, ptr %args, i64 16
  store ptr %_7, ptr %3, align 8
  %4 = getelementptr inbounds i8, ptr %args, i64 24
  store i64 1, ptr %4, align 8
; call core::fmt::write
 [snip, past here doesn't matter much]
```

where the assertion i want to write is really that `_ZN4core3fmt3num52_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u8$GT$3fmt17hac9971cd5590704cE` doesn't panic. 

but in this .ll all we get is the function declaration,
```
; core::fmt::num::<impl core::fmt::LowerHex for u8>::fmt
; Function Attrs: nonlazybind uwtable
declare noundef zeroext i1 @"_ZN4core3fmt3num52_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u8$GT$3fmt17hac9971cd5590704cE"(ptr noalias noundef readonly align 1 dereferenceable(1), ptr noalias noundef align 8 dereferenceable(64)) unnamed_addr #0
```

i was hoping that maybe by making the crate type sufficiently statically linked that i could get a .ll with this function filled in, but i don't see how. at least then writing a correct test would be reduced to "write a `CHECK-LABEL` for a function that does not appear in the test program"...

i couldn't see similar prior art in other forms of `CHECK{,-NOT}: panic` under `tests/codegen`. it looks like all cases rely on the function to be checked to be inlined into the top-level function being tested. @workingjubilee am i missing another detail of the test suite or is this particularly tricky to test?

(i also added benches for formatting `u8::MAX` and `0u8` similar to the larger types. it seems on a current rustc there's not much benefit to `unreachable_unchecked()` vs changing the loop as i've done in this patch. so i've `<details>`'d that section of the PR description)

**Comment by workingjubilee** [comment]
@iximeow Oh, no, you're right, this _is_ tricky to test. Hrm.

**Comment by workingjubilee** [comment]
@saethlin do we have a sufficient combination of commands such that with enough
- "we have LTO at home"
- the LTO: `-Zcross-crate-inline-threshold=yes`

we can make this codegen-testable anyway?

**Comment by saethlin** [comment]
> it looks like all cases rely on the function to be checked to be inlined into the top-level function being tested

That is true and I really do not like that approach. Playing games with the inliner rules tends to have undesired effects; for example it's possible if `Formatter::pad_integral` got inlined into this function that LLVM might manage to do the analysis you're doing here by hand and eliminate the check without the implementation improvement in this PR.

In addition, codegen tests are built against whatever sysroot happens to be specified by the settings in `config.toml`. It might have debug assertions or it might not. It might even have optimizations disabled.

I recently added a test based on using `-Zbuild-std` then analyzing the build artifacts: https://github.com/rust-lang/rust/blob/020bbe46bdf613c0b8211984eaa8e5fe97d6c92d/tests/run-make/compiler-builtins/rmake.rs. Just like it's important that we not only run the test suite that we run the test suite _on the build artifacts going out the door_ for codegen tests like this that are trying to check on the implementation of the standard library, what I'd prefer to see is a test that analyzes the standard library code under normal user conditions. I'm not sure implementing this is a reasonable ask for this PR.

---

The usual LTO at home flags are:
```
-Copt-level=3 -Zcross-crate-inline-threshold=yes -Zmir-opt-level=3 -Zinline-mir-hint-threshold=10000 -Zinline-mir-threshold=10000
```
Full LLVM optimizations, the LTO at home flag, enable MIR inlining in all possible cases then crank up the thresholds to an absurd level. (be aware that just applying such a high MIR inlining threshold to arbitrary crates will cause absurd memory usage, even my beefy desktop cannot compile `syn` with these flags)

But this doesn't help in part because of what I said above: The sysroot has already been compiled with a different set of flags that make LTO at home fail to apply. (as an optimization to compile time _grumble grumble_) https://github.com/rust-lang/rust/pull/115306 we only encode MIR which is deduced to be useful to other crates when compiling the current crate. The compilation of `core` has decided that `core::fmt::write` will not be useful for other crates, and so it becomes ineligible for inlining. Except by LLVM's LTO, because the standard library build we distribute is special-cased: We prune rustc's IR but always emit LLVM's IR for all functions via `-Cembed-bitcode=yes`.

**Comment by the8472** [comment]
An assembly test with `-Clto` might work.

**Comment by the8472** [comment]
We discussed this in a T-libs meeting. Given the difficulty of writing a codegen test that properly inlines everything is difficult we're ok with merging this without a test.

AIUI the test currently isn't working as intended? If so it should be removed from the PR and someone wants to add a working codegen test can be done in a followup PR.

**Comment by iximeow** [comment]
> AIUI the test currently isn't working as intended?

correct, i'd included it in the hopes it was close to being useful (alas!) - i've removed it but kept the benches for u8 formatting as those are informative.

**Comment by workingjubilee** [comment]
Ah, thank you! Sorry about the everything,

@bors r+ rollup=never

**Pull request merged**
