### PR TITLE
Backport LLVM changes to disable deferred inlining

### LINKED ISSUE #91128: Huge compile-time regression in beta/nightly
We have a serious Rust compile-time regression happening on an internal (unfortunately closed-source) crate, happening on both the beta and nightly channels.

Before, compiling the crate would take around 1 minute 30 seconds in automation. Now if I'm using the nightly channel, it seems to take around an hour or so.

Running with `RUSTFLAGS="-Z new-llvm-pass-manager=no"` makes the regression disappear on the nightly channel, so the new pass manager seems to be at fault here.

I've tried compiling with a rustc build from https://github.com/rust-lang/rust/pull/89830, but it didn't make the regression disappear, so it might not be the same inlining issue.

Thanks a bunch to @lqd who suggested disabling the pass manager, and trying the above patch. Pinging LLVM people: @nikic @Mark-Simulacrum. Of course I'm happy to run any other diagnostic and try any tool that could help figure out what's going on here.

### PR DESCRIPTION
**Pull request by nagisa**
Fixes #91128

I was thinking of how to best add the test case from the issue, and I think rust perf infrastructure would probably be the best place for something like it.

### CODE REVIEW

**Comment by nagisa** [comment]
We want to backport either this or https://github.com/rust-lang/rust/pull/91190 to beta.

**Comment by nagisa** [comment]
cc @nikic

**Comment by pnkfelix** [comment]
Declining to beta-backport in favor of PR #91190.

**Comment by Aaron1011** [comment]
Note that this is an LLVM backport, not a beta backport (the PR wording confused me at first)

**Pull request merged**
