### PR TITLE
Add `#[inline]` to IpAddr methods

### LINKED ISSUE #77583: Poorly optimized assembly generation around Ipv4Addr, Ipv6Addr
I tried this code:

```rust
pub fn ipv4_bitand_mask(ipv4: Ipv4Addr, mask: u32) -> Ipv4Addr {
    let ipv4_u32 = u32::from_ne_bytes(ipv4.octets());
    Ipv4Addr::from((ipv4_u32 & mask).to_ne_bytes())
}
```

I expected to see this happen: assembly generated should be equivalent to:

```rust
pub fn ipv4_bitand_mask_unsafe(ipv4: Ipv4Addr, mask: u32) -> Ipv4Addr {
    let ipv4_u32: u32 = unsafe { std::mem::transmute(ipv4) };
    unsafe { std::mem::transmute(ipv4_u32 & mask) }
}
```

Instead, this happened: the generated assembly retains calls to Ipv4::octets and Ipv4::from, leaving the assembly poorly optimized

I've played with different ways of implementing the safe version, but cannot find anyway get it to optimize further.

Good assembly:

```asm
example::ipv4_bitand_mask_unsafe:
        mov     eax, edi
        and     eax, esi
        ret
```

Bad assembly:

```asm
example::ipv4_bitand_mask:
        push    rbx
        sub     rsp, 16
        mov     ebx, esi
        mov     dword ptr [rsp + 8], edi
        lea     rdi, [rsp + 8]
        call    qword ptr [rip + std::net::ip::Ipv4Addr::octets@GOTPCREL]
        and     eax, ebx
        mov     edi, eax
        call    qword ptr [rip + <std::net::ip::Ipv4Addr as core::convert::From<[u8; 4]>>::from@GOTPCREL]
        add     rsp, 16
        pop     rbx
        ret
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=e9b9780847aec6211faf8695331c41b5) and [GodBolt](https://rust.godbolt.org/z/5aG6bc) (both include an IPv6 example as well)

Adding '-Z mir-opt-level=2' (or higher) does optimize away the call to octets, but not the call to from.

I get the same optimization behavior when building a binary, at least on my own platfom (x86-64 Windows MSVC)

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (beb5ae474 2020-10-04)
binary: rustc
commit-hash: beb5ae474d2835962ebdf7416bd1c9ad864fe101
commit-date: 2020-10-04
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
LLVM version: 11.0
```

### PR DESCRIPTION
**Pull request by AngelicosPhosphoros**
Add some inlines to trivial methods of IpAddr
Closes https://github.com/rust-lang/rust/issues/77583

### CODE REVIEW

**Comment by AngelicosPhosphoros** [comment]
Code from issue:
```rust
use std::net::{Ipv4Addr, Ipv6Addr};

pub fn ipv4_bitand_mask(ipv4: Ipv4Addr, mask: u32) -> Ipv4Addr {
    let ipv4_u32 = u32::from_ne_bytes(ipv4.octets());
    Ipv4Addr::from((ipv4_u32 & mask).to_ne_bytes())
}

pub fn ipv6_bitand_mask(ipv6: Ipv6Addr, mask: u128) -> Ipv6Addr {
    let ipv6_u128 = u128::from_ne_bytes(ipv6.octets());
    Ipv6Addr::from((ipv6_u128 & mask).to_ne_bytes())
}
```

Generated asm:
```asm
_ZN9inline_ip16ipv4_bitand_mask17h21a1d58399eeef05E:
	movl	%ecx, %eax
	andl	%edx, %eax
	retq

_ZN9inline_ip16ipv6_bitand_mask17h84a3a89719ccdfc1E:
	movq	%rcx, %rax
	andq	%r8, %rax
	andq	%r9, %rdx
	retq
```

I think, this change is very trivial.
cc @LeSeulArtichaut @mati865

**Comment by LeSeulArtichaut** [comment]
I'm not a reviewer. Maybe r? @m-ou-se

**Comment by AngelicosPhosphoros** [comment]
> 
> 
> I'm not a reviewer.

Offtop: where can I find list of reviewers?

**Comment by m-ou-se** [comment]
Thanks!

@bors r+ rollup

> Offtop: where can I find list of reviewers?

The list of reviewers that the high five bot will pick from is here:
https://github.com/rust-lang/highfive/blob/master/highfive/configs/rust-lang/rust.json#L14-L20

Everyone with bors review rights specifically for the library is listed here: https://www.rust-lang.org/governance/teams/library
(But some of them might only review changes related to a specific topic.)

(And people of the compiler team sometimes also approve library changes that don't affect the public api.)

**Comment by LeSeulArtichaut** [comment]
> Offtop: where can I find list of reviewers?

Also https://www.rust-lang.org/governance

**Comment by AngelicosPhosphoros** [comment]
Thanks for the reply.

> > Offtop: where can I find list of reviewers?
> 
> The list of reviewers that the high five bot will pick from is here:
> https://github.com/rust-lang/highfive/blob/master/highfive/configs/rust-lang/rust.json#L14-L20
> 
> Everyone with bors review rights specifically for the library is listed here: https://www.rust-lang.org/governance/teams/library
> (But some of them might only review changes related to a specific topic.)
> 
> (And people of the compiler team sometimes also approve library changes that don't affect the public api.)

**Comment by pickfire** [comment]
Should there be a test?

**Comment by AngelicosPhosphoros** [comment]
@pickfire You mean codegen test?

**Comment by pickfire** [comment]
Not sure what is it called but to test the generated assembly.

**Comment by m-ou-se** [comment]
I don't see much use in testing that every single `#[inline]` function in `std` is actually inlined.

**Pull request merged**
