### PR TITLE
Revert SGX inline asm syntax

### PR DESCRIPTION
**Pull request by jethrogb**
This was erroneously changed in #83387

### CODE REVIEW

**Comment by bjorn3** [comment]
AT&T syntax was used to support LLVM 8 and 9. Now that the minimum supported LLVM is 10, intel syntax is being used everywhere.

**Comment by jethrogb** [comment]
> AT&T syntax was used to support LLVM 8 and 9.

No, AT&T syntax was used as this is the standard for inline assembly. That LLVM 10 supports Intel syntax is not a reason to rewrite everything.

**Comment by bjorn3** [comment]
The inline asm rfc chose intel syntax as default. That is why there is an `att_syntax` flag instead of an `intel_syntax` flag.

https://rust-lang.github.io/rfcs/2873-inline-asm.html

> Additionally, this RFC proposes using the Intel asm syntax by default on x86 instead of the AT&T syntax. We believe this syntax will be more familiar to most users, but may be surprising for users used to GCC-style asm.
>
> [...]
>
> ### Use AT&T syntax by default on x86
>
> x86 is particular in that there are two widely used dialects for its assembly code: Intel syntax, which is the official syntax for x86 assembly, and AT&T syntax which is used by GCC (via GAS). There is no functional difference between those two dialects, they both support the same functionality but with a different syntax. This RFC chooses to use Intel syntax by default since it is more widely used and users generally find it easier to read and write.

**Comment by jethrogb** [comment]
The RFC merely describes the default behavior of the `asm!` macro.

**Comment by Amanieu** [comment]
It doesn't really matter either way, the end result is the same. I'll leave the asm style up to the discretion of the SGX target maintainers.

@bors r+ rollup

**Pull request merged**
