### PR TITLE
Update libc to 0.2.62

### PR DESCRIPTION
**Pull request by mati865**
Hopefully this will mitigate https://github.com/rust-lang/libc/issues/1489 and https://github.com/rust-lang/rust/issues/64006

### CODE REVIEW

**Comment by mati865** [comment]
r? @alexcrichton 
cc @gnzlbg

**Comment by gnzlbg** [comment]
r? me

@bors: r+

**Comment by newpavlov** [comment]
This PR will conflict with #63806. Maybe it worth to close this PR in favor of it?

**Comment by mati865** [comment]
Yeah, I decided to keep it until #63806 is re-approved which happened 10 minutes ago.

Superseded by https://github.com/rust-lang/rust/pull/63806

**Pull request closed without merging**
