### PR TITLE
Don't compute padding of braces unless they are unmatched

### PR DESCRIPTION
**Pull request by estebank**
Follow up to #53949. Attempt to fix # #54083.

r? @nikomatsakis

### CODE REVIEW

**Comment by estebank** [comment]
@rust-timer build ff274ae

**Comment by estebank** [comment]
@rust-lang/infra can I get a perf run to verify this is enough to revert the regression I introduced?

**Comment by alexcrichton** [comment]
It looks like the parent commit is missing, but [this comparison](https://perf.rust-lang.org/compare.html?start=0198a1ea45e29af00d92423aa6d2ac876410c3f9&end=ff274ae30df22e175774c95124cdf034cc8b8a0a&stat=instructions%3Au) should should the performance difference from before the original change to after this change. (when it's filled in)

**Comment by nikomatsakis** [comment]
If I understand @alexcrichton correctly, then the perf results here look very good.

**Pull request merged**
