### PR TITLE
Improve the wording

### LINKED ISSUE #55752: Incorrect coherence diagnostic
```rust
struct MyError;

impl From<i32> for Result<(), MyError> {
    fn from(x: i32) -> Self {
        if x == 0 { Ok(()) } else { Err(MyError) }
    }
}

fn main() {}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=646489805ed41f94a56e0a2077e0437d))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> src/main.rs:3:1
  |
3 | impl From<i32> for Result<(), MyError> {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl doesn't use types inside crate
  |
  = note: the impl does not reference any types defined in this crate
  = note: define and implement a trait or new type instead

error: aborting due to previous error

For more information about this error, try `rustc --explain E0117`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

This is incorrect because the error message states:

> the impl does not reference any types defined in this crate

but the `impl` does reference one type defined in this crate: `MyError`.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #55752.

This issue has two solution, to change the wording or to add the spans.
I'm not sure which is the best solution.
If you want to add the spans, I will do(but I don't know how to add the spans, please tell me).

### CODE REVIEW

**Comment by varkor** [comment]
@JohnTitor: if you run all the ui tests with the `--bless` flag (`./x.py test src/test/ui --bless --stage 1`) then it should automatically update all the test output to use the new message, which will fix the broken tests.

**Comment by JohnTitor** [comment]
@varkor Thank you for letting me know. I fixed them.

**Comment by varkor** [comment]
@JohnTitor: that looks great! If you could squash the two commits down to one, I'll approve.

**Comment by JohnTitor** [comment]
I couldn't squash my commits well.
Sorry but I'll re-open the PR, please see it.

**Pull request closed without merging**
