### PR TITLE
Add reference to `Self` in traits chapter (book)

### PR DESCRIPTION
**Pull request by munyari**
Addresses #31891

"r? @steveklabnik

### CODE REVIEW

**Comment by munyari** [comment]
So I just learned that I can't put the backticks in commit messages... weird

**Comment by GuillaumeGomez** [comment]
```bash
failures:

---- _2 stdout ----
	error[E0412]: type name `Circle` is undefined or not in scope
 --> <anon>:8:18
  |
8 | impl HasArea for Circle {
  |                  ^^^^^^ undefined or not in scope
  |
  = help: no candidates by the name of `Circle` found in your project; maybe you misspelled the name or forgot to import an external crate?

error: aborting due to previous error(s)

thread '_2' panicked at 'Box<Any>', src/librustc/session/mod.rs:167
```

**Comment by munyari** [comment]
Hey @GuillaumeGomez, how can I run doc tests for the book only?

**Comment by steveklabnik** [comment]
@munyari when I do it, I just call `rustdoc` on the markdown file directly.

Thanks!

@bors: r+ rollup

**Pull request merged**
