### PR TITLE
Calculate `span` info on-demand

### PR DESCRIPTION
**Pull request by jyn514**
- Add helper `attr_span` for common reused function
- Stop storing `Span`s on `Item` directly; calculate them on demand instead
- Special case modules, which have different spans depending on whether
  you use inner or outer attributes
- Special case impls with fake IDs, which can have either dummy spans (for auto traits) or the DefId of the impl block (for blanket impls)
- Use a fake ID for primitives instead of the ID of the crate; this lets
  `source()` know that it should use a dummy span instead of the span of
  the crate.

This shrinks `Item` from 48 to 40 bytes.

Helps with https://github.com/rust-lang/rust/issues/76382.

### CODE REVIEW

**Comment by jyn514** [comment]
The failure is strange - it looks like the file `src/core/slice/ascii.rs.html` is no longer being generated? Not sure what that has to do with my changes ... let me try reverting the change to primitive IDs.

**Comment by jyn514** [comment]
>  let me try reverting the change to primitive IDs.

that did not help :(

**Comment by jyn514** [comment]
New plan: Modules are the only thing that are failing, so I'm going to see if I can get rid of https://github.com/rust-lang/rust/blob/db492ecd5ba6bd82205612cebb9034710653f0c2/src/librustdoc/clean/mod.rs#L238 directly and save the big refactor for later.

**Comment by jyn514** [comment]
> New plan: Modules are the only thing that are failing, so I'm going to see if I can get rid of
> 
> https://github.com/rust-lang/rust/blob/db492ecd5ba6bd82205612cebb9034710653f0c2/src/librustdoc/clean/mod.rs#L238
> directly and save the big refactor for later.

This worked :tada:

**Comment by jyn514** [comment]
@bors try @rust-timer 

was a little too hasty after the rebase :upside_down_face:

**Comment by jyn514** [comment]
@rust-timer queue

**Comment by jyn514** [comment]
@guillaumegomez This is *finally* ready for review :tada: :tada: :tada:

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
The code looks good to me, just waiting for the timer to give the results.

**Comment by jyn514** [comment]
@rust-timer queue

**Comment by jyn514** [comment]
Up to -1.2% in instruction counts on many of the -doc benchmarks. Max-rss looks like noise.

@bors r=GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Less than what I was hoping for but still great!

**Pull request merged**
