### PR TITLE
Added missing atomic operations to atomic types.

### PR DESCRIPTION
**Pull request by alchemy**
AtomicPtr now has fetch_add and fetch_sub for pointer arithmetic.
AtomicInt and AtomicUint now have fetch_min, fetch_max and
fetch_and, fetch_nand, fetch_or, fetch_xor for bitwise logical
operations.

Closes #7421

### CODE REVIEW

**Comment by jonhoo** [comment]
Should this be re-opened following #12949?
These operations are necessary to support atomic pointers with pointer provenance tracking through miri (which, for example, `crossbeam` needs to be miri compatible).

**Comment by RalfJung** [comment]
In terms of portability, I assume if we have `AtomicUsize::fetch_xor` then we can have it on `AtomicPtr` as well.

However, @jonhoo talking about provenance honestly makes little sense when XOR is involved.

**Comment by jonhoo** [comment]
Yeah, I may have been overly eager when suggesting this would _give_ us provenance. Though it is the case that this is currently something that's forcing libraries to use `AtomicUsize`, which has even _less_ hope of tracking provenance :p

**Comment by jonhoo** [comment]
@RalfJung I posted https://github.com/rust-lang/rust/pull/71004 because I think this'd be a good thing to add independently of provenance :)

**Comment by RalfJung** [comment]
> These operations are necessary to support atomic pointers with pointer provenance tracking through miri (which, for example, crossbeam needs to be miri compatible).

See https://github.com/rust-lang/miri/issues/1318 for the Miri-side issue.

**Pull request closed without merging**
