### PR TITLE
Confusing suggestion on incorrect closing `}`

### PR DESCRIPTION
**Pull request by kper**
Compiler returns 
``` 
error: unexpected closing delimiter: `}`
  --> main.rs:20:1
   |
9  |             ErrorHandled::Reported => {}
   |                                       -- this block is empty, you might have not meant to close it temp
...
20 | }
   | ^ unexpected closing delimiter

error: aborting due to previous error
```

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
@kper while the suggestion has some false positives, I don't think that is a reason to remove it entirely. After #69708, there is no test that emits this suggestion, so r? @estebank to weigh in on removal.

**Comment by estebank** [comment]
Oh, I though we had other tests covering this... that's my bad.

I can be on favor of a better heuristic, for users of some editors this suggestion has been helpful. @kper could you give us an idea of what the code was when you got the bogus suggestion? We could, for example, detect empty blocks that are fully valid match arms and never suggest those.

**Comment by kper** [comment]
@estebank oh sorry, the PR didn't link the issue. (#70583)
The code was:
```
pub enum ErrorHandled {
    Reported,
    TooGeneric,
}

impl ErrorHandled {
    pub fn assert_reported(self) {
        match self {
            ErrorHandled::Reported => {}
            ErrorHandled::TooGeneric => panic!(),
        }
    }
}

fn struct_generic(x: Vec<i32>) {
    for v in x {
        println!("{}", v);
    }
    } // <-- incorrect closing brace
}
```

> We could, for example, detect empty blocks that are fully valid match arms and never suggest those. I think that's the most common source of these misleading suggestions.

Well the reason why I removed it, was the compiler returns this error message `this block is empty...`, although this block is somewhere else. 

> empty blocks that are fully valid match arms

Ok, I will try that, so I'll revert the removal.

Is there anything else, I should put there instead? Because after the fix, the compiler will return a message which doesn't provide a suggestion.
```
error: unexpected closing delimiter: `}`
  --> main.rs:20:1
   |
20 | }
   | ^ unexpected closing delimiter

error: aborting due to previous error
```

**Comment by estebank** [comment]
@kper An option would be to keep track of when the last properly formed `Item` ended and ignore `Span`s in `self.last_delim_empty_block_spans` that appear before then. This would make your case do the right thing.

Also, for this case, ideally we would have output like

```
error: unexpected closing delimiter: `}`
  --> main.rs:20:1
   |
16 | fn struct_generic(x: Vec<i32>) {
   |                                - this opening brace...
...
19 |     } // <-- incorrect closing brace
   |     - ...matches this closing brace, but they don't match indentation
20 | }
   | ^ unexpected closing delimiter
```

**Comment by kper** [comment]
Thanks @estebank for the hint. Basically, that is what I'm doing right now. I keep track of my `delim_tokens` and then I check if the empty bracket's span is in that range.

**Comment by kper** [comment]
But, I have still some troubles with the tidy check. 

This is one of my tests. However, `ERROR this block is empty, you might have not mean to close it` seems too long for the tidy check. Is there a way to force it?
```
pub enum ErrorHandled {
    Reported,
    TooGeneric,
}

impl ErrorHandled {
    pub fn assert_reported(self) {
        match self {
            ErrorHandled::Reported => {}} 
                                     //^~ ERROR this block is empty, you might have not mean to close it
            ErrorHandled::TooGeneric => panic!(),
        }
    }
} //~ ERROR unexpected closing delimiter: `}`
```

**Comment by kper** [comment]
> However, ERROR this block is empty, you might have not mean to close it seems too long for the tidy check. Is there a way to force it?

Nevermind, I dropped a word.

Those are the new error message after the PR. My changes led to changes in different tests too. I hope, that is fine. If not, please let me know. 

I dropped the term "but they don't match indentation" from your proposal because it might cause confusion in some cases (the last example below where the indentation is correct). 

```
LL | fn struct_generic(x: Vec<i32>) {
   |                                - this opening brace...
...
LL |     }
   |     - ...matches this closing brace
LL | }
   | ^ unexpected closing delimiter
```

```
match self {
            ErrorHandled::Reported => {}}
                                     //^~ ERROR block is empty, you might have not meant to close it
            ErrorHandled::TooGeneric => panic!(),
        }
    }
} //~ ERROR unexpected closing delimiter: `}`
```

```
LL | fn main() {
   |           - this opening brace...
...
LL |     }
   |     - ...matches this closing brace
LL | }
   | ^ unexpected closing delimiter
```

```
LL | fn main() {
   |           - this opening brace...
LL | 
LL | }
   | - ...matches this closing brace
LL |     let _ = ();
LL | }
   | ^ unexpected closing delimiter
```

**Pull request merged**
