### PR TITLE
Clean up the std library's #![feature]s

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

This is part of https://github.com/rust-lang/rust/issues/87766.

r? @m-ou-se

### CODE REVIEW

**Review by m-ou-se — APPROVED** [review]
Thanks! Can you squash the commits?

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/94623)

@bors r-

**Comment by JmPotato** [comment]
> failed in [rollup](https://github.com/rust-lang/rust/pull/94623)
> 
> @bors r-

@Dylan-DPC Hello, I just fixed the missing `#![feature]`, and a rollup is needed again I think.

**Comment by Dylan-DPC** [comment]
no worries, i'll r+ it and then it will either get merged individually or included in a rollup later today

**Comment by JmPotato** [comment]
> no worries, i'll r+ it and then it will either get merged individually or included in a rollup later today

Maybe an individual merge is proper since the deleted `#![feature]`s could be fully tested and do not interfere with other PRs to merge?

**Pull request merged**
