### PR TITLE
Turn const_caller_location from a query to a hook

### PR DESCRIPTION
**Pull request by oli-obk**
blocked on https://github.com/rust-lang/rust/pull/117317

cc @RalfJung

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors rollup

the regressed crate doesn't even invoke the query/hook

**Comment by RalfJung** [comment]
No strong opinion on whether this should be a query or a hook. :shrug: 

r=me after https://github.com/rust-lang/rust/pull/117317 landed

**Pull request merged**
