### PR TITLE
Point at type ascription before macro invocation on expansion parse error

### LINKED ISSUE #47666: Unfortunate error when typoing `:` for `::`
```rust
fn main() {
    let _ = Option:Some(vec![0, 1]);
}
```

The compiler output for this is:

```
   Compiling playground v0.0.1 (file:///playground)
error: expected type, found keyword `box`
 --> src/main.rs:2:25
  |
2 |     let _ = Option:Some(vec![0, 1]);
  |                         ^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate
```

Of course this is just me being dumb :) but by the time I noticed that, I had already tried `rustup update nightly` and tried the stable version and tried `-Z external-macro-backtrace` and scratched my head a bit and figured it had to be a compiler bug and minimized a test case. So I might as well file it!

### PR DESCRIPTION
**Pull request by estebank**
Fix https://github.com/rust-lang/rust/issues/47666. Follow up to https://github.com/rust-lang/rust/pull/62791.

r? @petrochenkov

### CODE REVIEW

**Comment by estebank** [comment]
The only relevant change is [the last commit](https://github.com/rust-lang/rust/commit/f840e9bcd29f381040a3f3d453e8dafb627ccc09), which adds diagnostic information to `Mac_` to keep the state of `last_type_ascription` at the invocation place location, to be able to ferry it when expanding the macro through `ExpansionData`.

**Comment by petrochenkov** [comment]
I need to think whether a less hacky solution exists, I wouldn't want to merge this as is.

**Comment by estebank** [comment]
Given the way this works it seems to me like the only available option is to collect the state of the parser at the invocation place. I understand the hesitance of merging the PR as is, but I think it is as good a starting point as we're gonna find without a larger refactor.

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, we would like to know if you @petrochenkov could give us a few minutes to share your thoughts on it.

**Comment by petrochenkov** [comment]
Low priority, deferred until the weekend (unless I deal with other reviews earlier).

(@estebank, could you rebase this perhaps in the meantime? https://github.com/rust-lang/rust/pull/62791 has landed.)

**Comment by petrochenkov** [comment]
So, the general idea is to create a parser snapshot for every macro invocation, so when the macro is expanded we can parse its output using a parser from that snapshot rather than a fresh parser.

Except that the only part of the parser this PR snapshots is the `prior_type_ascription` field.
An the snapshots are kept directly in the AST and not in some side table because we don't have node IDs assigned this early.

Since we create a fresh parser when expanding any macro anyway (which is not an entirely cheap operation), I wonder, how much more expensive it would be to clone the existing one instead.
Let's land this PR in the meantime, the diff is not large, it won't be hard to rework or revert if necessary.

**Pull request merged**
