### PR TITLE
[beta] backport

### PR DESCRIPTION
**Pull request by cuviper**
This PR backports:

- Encode def span for ConstParam #110425
- Update to LLVM 16.0.2 #110535
- Encode lifetime param spans too #110469
- make sysroot finding compatible with multiarch systems #110281 
- Update awscli #110952 
- Temporarily disable the jobserver-error test #110361 

Also bumps us to the latest released stable, 1.69.0.

r? @cuviper

### CODE REVIEW

**Comment by cuviper** [comment]
Stalling to add more approved backports.
@bors r-

**Comment by ehuss** [comment]
@bors treeclosed=100

Something is wrong with python and awscli

**Comment by ehuss** [comment]
@bors retry

python setuptools issue

**Comment by cuviper** [comment]
Oh, whoops, I'll need to backport the CI fix too...

**Comment by ehuss** [comment]
@cuviper I had recommended backporting #110361 to avoid that error.

**Comment by cuviper** [comment]
@ehuss, thanks, I've added it. It may help in the future to make sure there's a team label to review the nomination, but this case is simple enough that I feel comfortable approving it myself.

@bors r+

**Pull request merged**
