### PR TITLE
rustc_span: Remove unused symbols.

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
As noted  here, there is no guarantee that all pre-interned symbols are used. 

https://github.com/rust-lang/rust/blob/b10cfcd65fd7f7b1ab9beb34798b2108de003452/compiler/rustc_span/src/symbol.rs#L124-L125

This was done starting with using ripgrep to search for `sym::whatever`. I removed anything that didn't show up. However this had a huge number of false positives, due to extensive macro use. Then there was a manual phase of adding back all the ones used my macros.

I don't think this was worth my time to do, but it's done now . ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
As for weather this could be checked automatically in tidy, I don't think there's any easy way to do that, as it can't be answered with any text-based search.

**Review by WaffleLapkin — APPROVED** [review]
r=me with green CI

(and I'm sorry for your lost time ;-;)

**Comment by DaniPopes** [comment]
> As for weather this could be checked automatically in tidy, I don't think there's any easy way to do that, as it can't be answered with any text-based search.

FWIW I tried this previously in https://github.com/rust-lang/rust/pull/110437

Realized that I never opened a follow-up to remove just the unused symbols :disappointed:

**Pull request merged**
