### PR TITLE
Run `x test tidy` sooner in mingw-check

### PR DESCRIPTION
**Pull request by jyn514**
It takes less time to run than the other tests and is more likely to fail. `expand-yaml-anchors` is still run first to make sure the CI files are internally consistent.

Note that changing to `--stage 0` doesn't actually do anything since bootstrap tools are always built with the bootstrap compiler, this just makes it less confusing.

cc https://github.com/rust-lang/rust/pull/105058/commits/83bab41b5b2d4752d187dd91b05c88ac74cf3783

### CODE REVIEW

**Comment by Nilstrieb** [comment]
This didn't exactly work as expected.
Tidy only started here, with an entire `x check` still running before.
https://github.com/rust-lang/rust/actions/runs/3697810827/jobs/6263246796#step:26:2872

**Comment by Mark-Simulacrum** [comment]
Note that we run the script here twice, once with parallel and once without. Please check you're not looking at the second run. It should still fail fast.

**Comment by Nilstrieb** [comment]
In #105058 it didn't fast-fail when I applied the same change

**Comment by jyn514** [comment]
> Note that we run the script here twice, once with parallel and once without. Please check you're not looking at the second run. It should still fail fast.

amazing pointer, thank you :heart: turns out we were running the parallel script *first*, which seems like the wrong thing - pushed a commit switching the order.

**Comment by Mark-Simulacrum** [comment]
@bors r+

I'm not convinced this is meaningful (i.e., the order doesn't seem like it would matter to me, especially for tidy). But :shrug:

**Comment by matthiaskrgr** [comment]
got a weird `cp: cannot stat 'obj/build/metrics.json': No such file or directory` in ci for `mingw-check`, no idea if thats spurious or not
@bors rollup=iffy

**Comment by jyn514** [comment]
Oh, that's probably from reordering the parallel compiler build. I'll look into it.

@bors r-

**Pull request merged**
