### PR TITLE
Make encode_info_for_trait_item use queries instead of accessing the HIR

### PR DESCRIPTION
**Pull request by spastorino**
This change avoids accessing the HIR on `encode_info_for_trait_item` and uses queries. We will need to execute this function for elements that have no HIR and by using queries we will be able to feed for definitions that have no HIR.

r? @oli-obk

### CODE REVIEW

**Comment by spastorino** [comment]
There are more places where we need to use queries, I can keep sending them in other PRs.

**Comment by oli-obk** [comment]
r=me with a sentence on the motivation in the main comment

**Pull request merged**
