### PR TITLE
Add ci for DragonFly

### PR DESCRIPTION
**Pull request by mneumann**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Since this won't be currently activated, mind moving this to the `disabled` folder as well? (`src/ci/docker/disabled`)

**Comment by mneumann** [comment]
@alexcrichton: Would be nice to enable this once I fix formatting :). Or, if ci for DragonFly is too time-consuming (whatever other reason), is there a possibility to upload "official" distributions for DragonFly that we build ourselves on our machines? This would make `rustup` find something when being installed.

Currently, when I run this builder and cross-compile Rust for DragonFly, I trigger an internal bug in rustc itself (sorry, no bug report yet).

**Comment by alexcrichton** [comment]
Ah unfortunately we don't quite have the resources to commit to this right now, producing rustc for a platform requires quite a bit of compute power :(

**Comment by mneumann** [comment]
@alexcrichton: ok, no problem. but, is there some way so that we can upload snapshots of rust to an "official" location? atm, we are hosting them ourselves. this especially does not play very well together with rustup. probably, it's easier for us all, to not integrate that well with DragonFly. We have rust in the ports, but being able to install rust nightly via rustup is something that is missing.

**Comment by alexcrichton** [comment]
Unfortunately not easily right now :(

**Comment by Mark-Simulacrum** [comment]
Can we get this merged into the disabled folder? That would set the groundwork for eventually enabling, which we can't do currently unfortunately.

**Comment by mneumann** [comment]
@alexcrichton @Mark-Simulacrum ok, another try! I moved it into disabled and moved the patches (which broke "tidy") out into a separate file.

**Pull request merged**
