### PR TITLE
Updated test for E0221

### PR DESCRIPTION
**Pull request by tvladyslav**
As a part of issue #35233
?r @GuillaumeGomez

### CODE REVIEW

**Comment by jonathandturner** [comment]
Ahh, didn't realize that test hadn't been updated.  Good catch.

@bors r+ rollup

**Comment by jonathandturner** [comment]
@bors r-

Actually, before this gets committed, you'll need to run:

```
python src/bootstrap/bootstrap.py --stage 1 --step check-tidy
```

And fix the errors tidy gives you.  It seems like you might have some extra spaces in there.

**Comment by crypto-universe** [comment]
check-tidy fails to run. I'm running `python src/bootstrap/bootstrap.py --clean` second time. Hopefully it will help.
And yes, there was a space.

**Comment by crypto-universe** [comment]
@jonathandturner Now should be OK.

**Comment by jonathandturner** [comment]
Thanks.

@bors r+ rollup

**Pull request merged**
