### PR TITLE
Replace `option.map(cond) == Some(true)` with `option.is_some_and(cond)`

### PR DESCRIPTION
**Pull request by dtolnay**
Requested by @fmease in https://github.com/rust-lang/rust/pull/118226#pullrequestreview-1747432292.

There is also a much larger number of `option.map_or(false, cond)` that can be changed separately if someone wants.

r? fmease

### CODE REVIEW

**Comment by lnicola** [comment]
If these aren't strictly required to build rustc, we prefer merging any changes upstream (in rust-analyzer) first.

**Comment by dtolnay** [comment]
Sounds good. I have moved the src/tools/rust-analyzer change to https://github.com/rust-lang/rust-analyzer/pull/15960.

I have also created https://github.com/rust-lang/rust/pull/118255 to make rustbot inform PR authors about this preference.

**Comment by fmease** [comment]
My purview is rustdoc only.
r? compiler

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+ rollup

**Review by dtolnay — COMMENTED** [review]
> There is also a much larger number of `option.map_or(false, cond)` that can be changed separately if someone wants.

- #118288
- #118289

**Pull request merged**
