### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #95005 (BTree: evaluate static type-related check at compile time)
 - #99742 (Add comments about stdout locking)
 - #100128 (Document that `RawWakerVTable` functions must be thread-safe.)
 - #100956 (Reduce right-side DOM size)
 - #101006 (Fix doc cfg on reexports)
 - #101012 (rustdoc: remove unused CSS for `.variants_table`)
 - #101023 (rustdoc: remove `type="text/css"` from stylesheet links)
 - #101031 (Remove unused build dependency)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=95005,99742,100128,100956,101006,101012,101023,101031)

### CODE REVIEW

**Comment by lqd** [comment]
Most likely #101006 since the biggest hit is on libc's doc ? But that looks like a correctness fix anyways.

Let's check: @rust-timer build 3765c43334186b1ec37153d443eaa50517ddd4d7 include=-doc

**Comment by rylev** [comment]
@GuillaumeGomez this indeed looks like it's coming from https://github.com/rust-lang/rust/pull/101006. Given that is a correctness fix, shall we mark this as triaged and move on?

**Comment by GuillaumeGomez** [comment]
yes it's fine and expected.

**Pull request merged**
