### PR TITLE
Fix source code page sidebar on mobile

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Current broken behaviour:

https://user-images.githubusercontent.com/3050060/145984316-35c82353-5bab-4dc6-9ac6-63ea7e5c27d8.mp4

Fixed:

https://user-images.githubusercontent.com/3050060/145984329-8be1127b-d707-424d-ac3c-c1fb3c48a093.mp4

r? @jsha

### CODE REVIEW

**Comment by camelid** [comment]
I'm unclear what the issue is. The sidebar works for me in Firefox/macOS. Could you elaborate on what's not working?

**Comment by GuillaumeGomez** [comment]
Reduce the width of the windows under 700px to have the "mobile mode". Then you'll have just like the first video. :)

**Comment by jsha** [comment]
I can reproduce on Chrome / Linux by reducing the width of my window under 700px. Clicking the "expand sidebar" icon causes the icon to disappear without actually expanding the sidebar.

**Pull request merged**
