### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by tgross35**
Successful merges:

 - #109174 (Replace `io::Cursor::{remaining_slice, is_empty}`)
 - #128147 (migrate fmt-write-bloat to rmake)
 - #128182 (handle no_std targets on std builds)
 - #128310 (Add missing periods on `BTreeMap` cursor `peek_next` docs)

Failed merges:

 - #128269 (improve cargo invocations on bootstrap)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=109174,128147,128182,128310)

### CODE REVIEW

**Comment by tgross35** [comment]
@bors retry

link.exe bug

**Comment by tgross35** [comment]
? what was that

**Comment by tgross35** [comment]
:/ treeclosed when this was within a minute of finishing

**Comment by nnethercote** [comment]
> :/ treeclosed when this was within a minute of finishing. #125443 probably should have closed the tree after this and reapplied formatting if needed.
> 
> Admittedly I'm a bit surprised that treeclosed cancels ongoing jobs...

My apologies... this is the first time I have ever closed the tree. I knew this was PR was close to merging, but I also thought that it would let the existing job finish :(

**Comment by tgross35** [comment]
No worries, nothing urgent here. I had no clue it cancels things either and would have done the exact same, so I'm glad that I learned now too 😆

**Pull request closed without merging**
