### PR TITLE
Give RPITITs variances, so they can (not) capture lifetimes

### PR DESCRIPTION
**Pull request by compiler-errors**
This is needed for edition 2021 and the `precise_captures` feature, so we can specify that we *don't* want to capture a lifetime implicitly for an RPITIT. I'll elaborate this further and try to motivate its soundness once perf comes back.

Tracking:

- https://github.com/rust-lang/rust/issues/123432

r? @ghost

### CODE REVIEW

**Comment by wesleywiser** [comment]
Hi @compiler-errors, is this ready to be reviewed? Should we assign a reviewer?

**Comment by apiraino** [comment]
Discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-06-27/near/447497591). Removing waiting on review flag

@rustbot label -S-waiting-on-review

**Comment by lqd** [comment]
Make it draf and/or waiting on author, I dunno 😆

**Comment by compiler-errors** [comment]
Implemented in a feature-gated way in #131033.

**Pull request closed without merging**
