### PR TITLE
Tiny expansion to docs for `core::convert`.

### PR DESCRIPTION
**Pull request by icefoxen**
This is not really significant, accept or reject as you wish.  I just want to make sure I understand how the PR process works and that I'm doing it right before doing a bigger one for #33417.

### CODE REVIEW

**Comment by icefoxen** [comment]
Now that I dig around more I notice that this is already described in the docs for `Into` under the heading "Implementing `Into`".  So this may be technically redundant, or maybe a useful pointer in that direction.

**Review by frewsxcv — APPROVED** [review]

**Pull request merged**
