### PR TITLE
rustbuild: implement precise LLVM stamping

### PR DESCRIPTION
**Pull request by xen0n**
This PR implements precise stamping for LLVM builds. By introducing a mirror struct between the build step and `cmake::Config`, we're able to serialize and compare the build configuration, while retaining the same behavior towards CMake.

## New stamp format

The new LLVM build stamp looks like this:

```
# If this file is modified, then llvm will be forcibly cleaned and then rebuilt.
# The actual contents of this file do not matter, but to trigger a change on the
# build bots then the contents should be changed so git updates the mtime.
2016-12-19

target: mips64el-unknown-linux-gnuabi64
host: mips64el-unknown-linux-gnuabi64
profile: Release
define: "CMAKE_CXX_COMPILER" = "ccache"
define: "CMAKE_CXX_COMPILER_ARG1" = "c++"
define: "CMAKE_CXX_FLAGS" = "-ffunction-sections -fdata-sections -fPIC"
define: "CMAKE_C_COMPILER" = "ccache"
define: "CMAKE_C_COMPILER_ARG1" = "cc"
define: "CMAKE_C_FLAGS" = "-ffunction-sections -fdata-sections -fPIC"
define: "LLVM_DEFAULT_TARGET_TRIPLE" = "mips64el-unknown-linux-gnuabi64"
define: "LLVM_ENABLE_ASSERTIONS" = "OFF"
define: "LLVM_ENABLE_LIBEDIT" = "OFF"
define: "LLVM_ENABLE_TERMINFO" = "OFF"
define: "LLVM_ENABLE_ZLIB" = "OFF"
define: "LLVM_INCLUDE_DOCS" = "OFF"
define: "LLVM_INCLUDE_EXAMPLES" = "OFF"
define: "LLVM_INCLUDE_TESTS" = "OFF"
define: "LLVM_PARALLEL_COMPILE_JOBS" = "4"
define: "LLVM_TARGETS_TO_BUILD" = "Mips"
define: "LLVM_TARGET_ARCH" = "mips64el"
define: "WITH_POLLY" = "OFF"
build_arg: "-j"
build_arg: "4"
```

Apart from the original clean trigger, there's now complete CMake configuration. The build was done on a MIPS64 box, hence the exotic triples. Also notice the fact that only the `Mips` backend is enabled is reflected in the stamp, so do other configuration; if any of these is touched, a rebuild would be correctly triggered.

One may argue that it's some real complexity brought in with little benefit; the fact is people do make silly moves sometimes, like tweaking some LLVM options then forgotting to rebuild, causing headaches. So it's in their best interest to provide a safety net like this.

## Potential improvements

* Remove uninteresting options like the `build_args`; they might contain interesting things sometime in the future, we can add them back at any time.
* Diff the expected and actual stamp content more thoroughly and tell the user exactly why they're getting LLVM rebuilt, i.e. which configuration changed, even possibly asking for confirmation. This could be done in a separate PR if deemed necessary; I myself don't see it very pressing.

r? @alexcrichton

### CODE REVIEW

**Comment by nagisa** [comment]
What prevents every single PR from now on checking in a different `llvm-clean-trigger` – a file whose whole purpose is to cause LLVM rebuild on CI, not dev machine?

**Comment by xen0n** [comment]
@nagisa Sorry for being unclear about this, but I'm referring to the `llvm-finished-building` file instead. The `llvm-clean-trigger` is not touched at all by this PR.

**Comment by alexcrichton** [comment]
Thanks for the PR @xen0n! This seems like a lot of support, though, for something which could otherwise just be a principled "let's be sure to touch the trigger when necessary" concern. 

Historically when the build system has been eager to rebuild when all the correct dependencies changed it's just ended up being annoying, so I'm wary of making this "too correct" when the failure mode, not recompiling LLVM when we should, happens almost never.

**Comment by xen0n** [comment]
Fair point. I'm not intending it to be absolutely necessary anyway, and am only pushing forward this for feature-completeness. I agree that people who touch this part of rustc really should know what they're doing, so the safeguard shouldn't be needed in most cases. I'm closing this PR then.

**Pull request closed without merging**
