### PR TITLE
Update rustfmt

### PR DESCRIPTION
**Pull request by jhpratt**

### CODE REVIEW

**Comment by jhpratt** [comment]
Failure appears spurious.

**Review by calebcartwright — CHANGES_REQUESTED** [review]
Please close this. I do not want to do a subtree sync at this time, and we also have a process in place that's based on doing a push prior to doing a pull here

**Comment by jhpratt** [comment]
Alright. Wasn't sure and we were looking to having a recent change land on nightly.

**Comment by calebcartwright** [comment]
> Alright. Wasn't sure and we were looking to having a recent change land on nightly.

In case you hadn't already seen it: https://rustc-dev-guide.rust-lang.org/contributing.html#external-dependencies-subtree

The timing and schedule of syncs is also best handled by the respective owning teams given the other process related items tied to the syncs. I appreciate users wanting a particular commit or a set of commits from downstream, but it wouldn't be feasible to create a practice where we try to sync on a more ad-hoc basis to satisfy those motivations.

**Pull request closed without merging**
