### PR TITLE
[experiment] Update `cc` CI tests

### PR DESCRIPTION
**Pull request by tgross35**
See https://github.com/rust-lang/rust/pull/130720, https://github.com/rust-lang/rust/pull/130898; try with the minimal version bump.

try-job: x86_64-msvc

### CODE REVIEW

**Comment by tgross35** [comment]
Woah! So it succeeded with 1.0.100, let's try the next one up.

**Comment by tgross35** [comment]
Probably should have done more of a bisect algorithm, since we have (now) a known good at 1.0.100 and a known bad at 1.0.106. Updated to 1.0.103, I think the first job will still continue

@bors try

**Comment by tgross35** [comment]
1.0.105 and 1.0.106 both have windows changes, so those seem like likely candidates https://github.com/rust-lang/cc-rs/releases/tag/cc-v1.0.105 https://github.com/rust-lang/cc-rs/releases/tag/cc-v1.0.106. I guess if try jobs work in parallel, might as well make use of that.

@bors try (for 1.0.104)

**Comment by tgross35** [comment]
So we have:

- Success at 1.0.100, https://github.com/rust-lang-ci/rust/commit/f42fb94e330f6efa99e6f1acc7103fc3b2b8a957
- Failure at 1.0.101, https://github.com/rust-lang-ci/rust/commit/9d55780dc98be980b9f40c8b4ba5318b9d1a76f5
- Failure at 1.0.103, https://github.com/rust-lang-ci/rust/commit/ed664a282e7aafa63ac6a0d31f4d0410accc76f5
- Failure at 1.0.104, https://github.com/rust-lang-ci/rust/commit/f1d03b0d4241541d915a507e01c99aa4364f40cd
- Failure at 1.0.105, https://github.com/rust-lang-ci/rust/commit/3bfb192560445de5ea6d82f8d12fa8ba8b08b4a0

All of the failures were around the 1 hour mark, failure to build `compiler_builtins` or one of its dependencies.

The changes between 1.0.100 and 1.0.101 did adjust the way that some tools are found on Windows, maybe the update causes different versions to be located? https://github.com/rust-lang/cc-rs/compare/cc-v1.0.100...cc-v1.0.101

These results don't feel very concrete so I'll rerun 100/101 to see if they appear consistent.

**Comment by tgross35** [comment]
Trying with 1.1.22, which includes @ChrisDenton's fix https://github.com/rust-lang/cc-rs/pull/1215

@bors try

**Comment by arttet** [comment]
It looks like that fix works.

**Comment by tgross35** [comment]
> It looks like that fix works.

Did it pass somewhere? It looks like the try jobs here and in https://github.com/rust-lang/rust/pull/130926 only got picked up 25 minutes ago

**Comment by arttet** [comment]
The [job](https://github.com/rust-lang-ci/rust/actions/runs/11069187019/job/30756214497) has built `profiler_builtins`. But let's wait for results.

**Comment by tgross35** [comment]
Everything gets built multiple times, the failures here have been around the 1 hour mark. Some of the MSVC issues are closer to the end though.

**Comment by tgross35** [comment]
Cool, Chris has the update covered in https://github.com/rust-lang/rust/pull/130926#issuecomment-2379259865

**Pull request closed without merging**
