### PR TITLE
Use 32-bit integer hashing algorithm to avoid the biased swapping in sort_unstable

### LINKED ISSUE #74928: sort_unstable's random swap is biased
The "modulo a power of two" technique used by `sort::break_patterns` is far more biased than modulo or [integer multiplication](https://arxiv.org/abs/1805.10941). (I think that their sort of bias is acceptable here).
https://github.com/rust-lang/rust/blob/584e83dd5ae7a75b8214560c22eafbcfe153caa6/library/core/src/slice/sort.rs#L582-L585

A graph of the techniques for `len = 50` and 8-bit integers using `Mod[Mod[x, 2^Ceiling[Log[2, len]]], len]` (Mathematica) for the power method ([code](https://gist.github.com/TheIronBorn/e31bb13ff32349595eddde20d1c77c99))
image

The average standard deviation of the counts of possible outputs for all possible `len` are so ([code](https://gist.github.com/TheIronBorn/71b7b160d604ac5d83c4c847a31c0933)):
|            | pow     | mul  | mod  |
| ---        | ---     | ---  | ---  |
| **8-bit**  | 10.85   | 0.16 | 0.16 |
| **16-bit** | 2776.36 | 0.16 | 0.16 |

For a picture of the real-world effect of this bias, here is an image where darker pixels are outputs, the vertical axis is the three outputs of the `sort.rs` code, and the horizontal axis is each new `len` (32-bit, 50_000 `len` values after `MAX_INSERTION`, shrunk in post-processing to fit, code and full image for this and all below [here](https://gist.github.com/TheIronBorn/3138c91f23122ea68239af7646417bc1))
Xorshift scaled
There is a clear bias toward lower values even for our limited use.

And here it is using [`rand::thread_rng`](https://docs.rs/rand/0.7.3/rand/fn.thread_rng.html)
StdRng scaled
Still a clear bias

Using the integer multiplication reduction we get
|`Xorshift`|`thread_rng`|
|---|---|
|Xorshift mul scaled|ThreadRng mul scaled|

Still some clear non-randomness but the bias is more evenly distributed across all values (the picture is uglier in full-size though due to Xorshift's low quality).

To avoid that patterning the main issue is the low entropy of our `len` seed. Iterating the PRNG 2 times before using the output produces:
XorshiftIterated scaled
Decent but a little too even.

A better solution is to use an integer hash as a PRNG instead, they are much better at immediately using low entropy "seeds".
["7 shifts"](https://burtleburtle.net/bob/hash/integer.html) by Bob Jenkins
Jenkins scaled

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

Close https://github.com/rust-lang/rust/issues/74928. This PR updates the RNG used by the `break_patterns` to a [32-bit integer hashing algorithm](http://burtleburtle.net/bob/hash/integer.html).

cc @TheIronBorn

I wrote a [benchmark test](https://github.com/JmPotato/rust_playground/blob/bdba4a1f5a55ea128b2a2fb52dbfbeca3caa8f83/benches/sort_unstable_benchmark.rs) to get different versions of `sort_unstable` to run on the same randomly generated dataset. The following criterion output benchmark results show the difference between the changes in this PR and the `rustc 1.61.0-nightly (10cc7a6d0 2022-02-26)` version.

```shell
sort_unstable/length: 25, modulus: 5
                        time:   [232.12 ns 232.22 ns 232.31 ns]
                        change: [+0.8973% +0.9809% +1.0550%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 95 outliers among 5000 measurements (1.90%)
  68 (1.36%) high mild
  27 (0.54%) high severe

sort_unstable/length: 25, modulus: 10
                        time:   [217.90 ns 217.98 ns 218.07 ns]
                        change: [-0.6770% -0.6201% -0.5633%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 153 outliers among 5000 measurements (3.06%)
  88 (1.76%) high mild
  65 (1.30%) high severe

sort_unstable/length: 25, modulus: 100
                        time:   [236.16 ns 236.23 ns 236.29 ns]
                        change: [-0.6861% -0.6373% -0.5879%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 234 outliers among 5000 measurements (4.68%)
  162 (3.24%) high mild
  72 (1.44%) high severe

sort_unstable/length: 25, modulus: 1000
                        time:   [241.44 ns 241.51 ns 241.58 ns]
                        change: [-0.3108% -0.2499% -0.1931%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 403 outliers among 5000 measurements (8.06%)
  3 (0.06%) low severe
  77 (1.54%) low mild
  193 (3.86%) high mild
  130 (2.60%) high severe

sort_unstable/length: 500, modulus: 5
                        time:   [4.6595 us 4.6606 us 4.6617 us]
                        change: [-0.3552% -0.2725% -0.2065%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 426 outliers among 5000 measurements (8.52%)
  294 (5.88%) high mild
  132 (2.64%) high severe

sort_unstable/length: 500, modulus: 10
                        time:   [6.2531 us 6.2546 us 6.2561 us]
                        change: [-1.3431% -1.1181% -0.9313%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 648 outliers among 5000 measurements (12.96%)
  306 (6.12%) high mild
  342 (6.84%) high severe

sort_unstable/length: 500, modulus: 100
                        time:   [9.9634 us 9.9661 us 9.9690 us]
                        change: [-0.3713% -0.2830% -0.2078%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 625 outliers among 5000 measurements (12.50%)
  299 (5.98%) high mild
  326 (6.52%) high severe

sort_unstable/length: 500, modulus: 1000
                        time:   [9.7691 us 9.7710 us 9.7730 us]
                        change: [-0.1566% -0.1237% -0.0913%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 624 outliers among 5000 measurements (12.48%)
  293 (5.86%) high mild
  331 (6.62%) high severe
```

### CODE REVIEW

**Comment by JmPotato** [comment]
Benchmark results updated in the PR description, PTAL, thx! @Mark-Simulacrum

**Comment by JmPotato** [comment]
Another round of the benchmark:

```shell
sort_unstable/length: 25, modulus: 5
                        time:   [244.74 ns 245.26 ns 245.77 ns]
                        change: [+3.3725% +3.7220% +4.0764%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) low mild
  1 (1.00%) high mild

sort_unstable/length: 25, modulus: 10
                        time:   [164.97 ns 165.27 ns 165.57 ns]
                        change: [-2.1635% -1.8905% -1.6316%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

sort_unstable/length: 25, modulus: 100
                        time:   [185.64 ns 185.97 ns 186.30 ns]
                        change: [-4.3990% -4.0341% -3.6860%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild

sort_unstable/length: 25, modulus: 1000
                        time:   [241.00 ns 242.61 ns 244.56 ns]
                        change: [-4.6262% -4.1790% -3.6419%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

sort_unstable/length: 500, modulus: 5
                        time:   [3.4800 us 3.4832 us 3.4866 us]
                        change: [+0.3840% +0.6176% +0.8530%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe

sort_unstable/length: 500, modulus: 10
                        time:   [5.1528 us 5.1832 us 5.2246 us]
                        change: [+2.7131% +3.3381% +4.1485%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 11 outliers among 100 measurements (11.00%)
  5 (5.00%) high mild
  6 (6.00%) high severe

sort_unstable/length: 500, modulus: 100
                        time:   [8.2492 us 8.2640 us 8.2817 us]
                        change: [-1.3892% -1.0490% -0.7131%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe

sort_unstable/length: 500, modulus: 1000
                        time:   [8.5341 us 8.5413 us 8.5493 us]
                        change: [-0.6444% -0.4038% -0.1390%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe
```

**Comment by nagisa** [comment]
This function is intended to prevent some sort of worst case scenario manifesting in the sorting algorithm, right? While benchmarks of a random list sort of scenario are interesting, I feel benchmarks feeding a specific worst case scenario would be useful as well. Even better if they can demonstrate the current implementation being insufficient to prevent the worst-case scenario from manifesting.

**Comment by JmPotato** [comment]
> This function is intended to prevent some sort of worst case scenario manifesting in the sorting algorithm, right? While benchmarks of a random list sort of scenario are interesting, I feel benchmarks feeding a specific worst case scenario would be useful as well. Even better if they can demonstrate the current implementation being insufficient to prevent the worst-case scenario from manifesting.

Thanks for your suggestion! I tried to bench the situation that a worst case may occur by simply using `input.select_nth_unstable` like the below code shows to make sure an unbalanced pivot will be chosen later in `sort_unstable`.

```rust
// Try to make the position of the pivot after partitioning
// is under 12.5% (1/8th) percentile(or over 87.5% percentile).
let unbalanced_pivot_idx = len / 8 - 5;
input.select_nth_unstable(unbalanced_pivot_idx);
input.swap(unbalanced_pivot_idx, len / 2);
```

Here are the benchmark results (I increased the sample number also):

```shell
sort_unstable/length: 50, modulus: 5
                        time:   [349.94 ns 350.37 ns 350.85 ns]
                        change: [-4.9298% -4.7470% -4.5616%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 213 outliers among 2500 measurements (8.52%)
  3 (0.12%) low mild
  81 (3.24%) high mild
  129 (5.16%) high severe

sort_unstable/length: 50, modulus: 10
                        time:   [467.75 ns 468.41 ns 469.08 ns]
                        change: [-1.8835% -1.6595% -1.4173%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 205 outliers among 2500 measurements (8.20%)
  3 (0.12%) low mild
  124 (4.96%) high mild
  78 (3.12%) high severe

sort_unstable/length: 50, modulus: 100
                        time:   [502.40 ns 503.09 ns 503.81 ns]
                        change: [-4.8092% -4.5498% -4.2819%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 145 outliers among 2500 measurements (5.80%)
  6 (0.24%) low mild
  94 (3.76%) high mild
  45 (1.80%) high severe

sort_unstable/length: 50, modulus: 1000
                        time:   [462.73 ns 463.39 ns 464.13 ns]
                        change: [-8.3472% -8.1404% -7.9456%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 231 outliers among 2500 measurements (9.24%)
  10 (0.40%) low mild
  113 (4.52%) high mild
  108 (4.32%) high severe

sort_unstable/length: 500, modulus: 5
                        time:   [3.5763 us 3.5846 us 3.5937 us]
                        change: [+2.2556% +2.6214% +2.9955%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 313 outliers among 2500 measurements (12.52%)
  38 (1.52%) high mild
  275 (11.00%) high severe

sort_unstable/length: 500, modulus: 10
                        time:   [4.7908 us 4.7969 us 4.8037 us]
                        change: [+1.4440% +1.6555% +1.8675%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 214 outliers among 2500 measurements (8.56%)
  42 (1.68%) high mild
  172 (6.88%) high severe

sort_unstable/length: 500, modulus: 100
                        time:   [7.9406 us 7.9506 us 7.9609 us]
                        change: [-0.4755% -0.1502% +0.1450%] (p = 0.35 > 0.05)
                        No change in performance detected.
Found 315 outliers among 2500 measurements (12.60%)
  53 (2.12%) high mild
  262 (10.48%) high severe

sort_unstable/length: 500, modulus: 1000
                        time:   [8.5354 us 8.5468 us 8.5588 us]
                        change: [+0.4657% +0.7669% +1.0406%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 326 outliers among 2500 measurements (13.04%)
  35 (1.40%) high mild
  291 (11.64%) high severe

sort_unstable/length: 5000, modulus: 5
                        time:   [26.201 us 26.251 us 26.303 us]
                        change: [-0.5172% -0.1827% +0.1366%] (p = 0.28 > 0.05)
                        No change in performance detected.
Found 480 outliers among 2500 measurements (19.20%)
  95 (3.80%) high mild
  385 (15.40%) high severe

sort_unstable/length: 5000, modulus: 10
                        time:   [37.665 us 37.734 us 37.806 us]
                        change: [+1.5778% +1.8012% +2.0369%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 429 outliers among 2500 measurements (17.16%)
  68 (2.72%) high mild
  361 (14.44%) high severe

sort_unstable/length: 5000, modulus: 100
                        time:   [74.066 us 74.172 us 74.284 us]
                        change: [+0.9874% +1.2160% +1.4550%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 315 outliers among 2500 measurements (12.60%)
  47 (1.88%) high mild
  268 (10.72%) high severe

sort_unstable/length: 5000, modulus: 1000
                        time:   [183.78 us 184.07 us 184.38 us]
                        change: [+0.0181% +0.2112% +0.4196%] (p = 0.04 < 0.05)
                        Change within noise threshold.
Found 390 outliers among 2500 measurements (15.60%)
  1 (0.04%) low mild
  55 (2.20%) high mild
  334 (13.36%) high severe
```

Though it seems that the performance changes here are not as unstable as before and even have some improvement on the short len case, I'm still wondering if this is convinced since it's not the worst case actually (in which the number of calling `break_patterns` does not reach the limited times).

**Comment by TheIronBorn** [comment]
I think the larger concern here is the modulo-power-of-two technique `gen_usize() & (len.next_power_of_two() - 1)`
Here's the average of `sample / slice::len`:
```
32-bit
xorshift pow 0.4431471490311492
xorshift mul 0.500000024679453
jenkins pow 0.4431548813075751
jenkins mul 0.4999997022914606
crypto gen_range 0.4999954449392249
64-bit
xorshift pow 0.44314726512840646
xorshift mul 0.5000000163025015
jenkins pow 0.4431697646984857
jenkins mul 0.4999859498242413
crypto gen_range 0.5000050251024328
```
Even with a hash algorithm, the power method choose pivots from the lower half ~5% more often than it should.

produced by 
```rust
fn get_avg<R: TinyRng + Rng, F: Fn(&mut R, u64) -> u64>(func: F) -> f64 {
    let range = MAX_INSERTION + 1..1 << 28;
    let range_len = range.end - range.start;
    let mut sum = 0.0;
    for len in range {
        let mut rng = R::from_seed(len as u32);
        for _ in 0..N_SWAPS {
            let sample = func(&mut rng, len as u64);
            // make sure this is symmetric
            sum += (sample + 1) as f64 / (len + 1) as f64;
        }
    }
    sum / (range_len * N_SWAPS) as f64
}
```
full code here https://gist.github.com/TheIronBorn/82f04d2733105886603cb6bfaf96f5c8

**Comment by TheIronBorn** [comment]
I just realized that thanks to the bitmask (`& next_power_of_two`) in 64-bit mode the higher 32-bits won't be used unless `len > u32::MAX`. I don't know if Rust even supports that, but we could do `gen_usize = || { if usize::BITS <= 32 || len <= u32::MAX ...`

**Comment by TheIronBorn** [comment]
If `len` is small (< ~2^8), xorshift with mul has issues, and up to 2^13 in 32-bit mode:
```
1 << 8
32-bit
xorshift mul 0.3405677608633237
jenkins mul 0.4924986672911761
64-bit
xorshift mul 0.5126090395765013
jenkins mul 0.5007449463878153
1 << 13
32-bit
xorshift mul 0.41680382292314916
jenkins mul 0.49927575734698854
64-bit
xorshift mul 0.5001610837929296
jenkins mul 0.5005647120645135
```
If `break_patterns` isn't common with those lengths, we may be able to get away with Xorshift.

**Comment by Mark-Simulacrum** [comment]
Do you have any references on what other standard library implementations do here?

It looks like the benchmark results are still pretty lacklustre -- does that mean our current approach is sufficient to make it impossible to generate a truly pathological case? I would expect some kind of manual synthesis (knowing the indices that will be picked) would manage to create a much more impressive improvement than just ~5%. At least my loose recollection of algorithms class was that e.g. quicksort can degenerate to n^2 with poor index picks; it looks like std is documented to not do that, but presumably this function does matter at least somewhat. It might be useful to compare against an empty stub of this function, too.

FWIW, it seems like we don't *actually* want indefinite random number generation, instead we want 3 indices in the array. Maybe there's an easier way to generate ~3 indices based on an array length, since that's a much more constrained problem (or at least seems like it)?

**Comment by TheIronBorn** [comment]
> Do you have any references on what other standard library implementations do here?

The original [pdqsort implementation ](https://github.com/orlp/pdqsort/blob/b1ef26a55cdb60d236a5cb199c4234c704f46726/pdqsort.h#L446) uses deterministic swapping.

I have found that slices with a lot of duplicates produce many more `break_pattern` calls. Something like `input.fill_with(|| [0,0,0,0,0,1,2,3].choose(rng))` tends to produce ~2.7 unbalanced pivots on average vs <1 for the `select_nth` method above.

> it seems like we don't actually want indefinite random number generation

I wonder if perhaps we could use quasi-random numbers here, it would guarantee a more uniform distribution and it might be faster and reduce duplicates. I don't know of any applications in this area though.

**Comment by Mark-Simulacrum** [comment]
OK. I am currently inclined to close this unless we can find some stronger motivation for making changes here. The benchmark results look to me like they're largely noise (or *very* slight improvements), so they don't by themselves directly motivate this PR's work. If we had a stronger case study (e.g., a pattern that produces pathological results and so leads to consistent >10% improvement in results, perhaps measured on number of swaps + number of comparisons rather than time), then that would make me more inclined to accept work in this direction.

Looking at #74928 doesn't really seem like it is itself all that strongly motivated: yes, there is bias, but it's not clear that the bias is a problem (to me). It seems like the intent of break_patterns is largely still achieved even with a slight amount of bias in what is shuffled, or at least, I'm not really seeing why that wouldn't be the case.

Pending a stronger motivation for why we should be concerned about this case I will close this and #74928 in a little while.

**Comment by TheIronBorn** [comment]
For posterity I ran some numbers and got average "unbalanced pivots" per method with the worst pattern I've found so far:
```
current     = 1.5796516029330798
hash & mul  = 1.5794873679863857
full random = 1.5792097327193553
```

There doesn't seem to be much real world difference.

the code run:
```rust
for _ in 0..1 << 7 {
    for len in 21..20_000 {
        let lut = [0, 0, 0, 0, 0, 1, 2, 3];
        input[..len].fill_with(|| *lut.choose(rng).unwrap());    
        sum += quicksort_badpivots(&mut input[..len], |a, b| a < b);

**Comment by Mark-Simulacrum** [comment]
Alright. Thanks for trying this out! Going to go ahead and close at this point.

**Pull request closed without merging**
