### PR TITLE
Update E0496 to new format

### LINKED ISSUE #36000: E0496 needs to be updated to new format
From: src/test/compile-fail/E0496.rs

E0496 needs a span_label and a span_note converted to a span_label, updating this:

```
error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
  --> src/test/compile-fail/E0496.rs:16:10
   |
16 |     fn f<'a>(x: &'a i32) { //~ ERROR E0496
   |          ^^
   |
note: shadowed lifetime `'a` declared here
  --> src/test/compile-fail/E0496.rs:15:6
   |
15 | impl<'a> Foo<'a> {
   |      ^^
```

To:

```
error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
  --> src/test/compile-fail/E0496.rs:16:10
   |
15 | impl<'a> Foo<'a> {
   |      -- first declared here
16 |     fn f<'a>(x: &'a i32) { //~ ERROR E0496
   |          ^^ lifetime 'a already in scope
```

### PR DESCRIPTION
**Pull request by acrrd**
Fixes #36000.
Part of #35233.

r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!


I wait for travis' confirmation before r+ it.

Also, can you squash your commits please? If you don't know how to do, take a look [here](https://blog.guillaume-gomez.fr/Git-tips/1/2).

**Comment by CryZe** [comment]
Travis won't confirm, it's broken right now.

**Comment by acrrd** [comment]
squash done

**Comment by GuillaumeGomez** [comment]
@acrrd: Travis and buildbot are broken for the moment. Once they're fixed, I'll r+.

**Comment by acrrd** [comment]
There are some tests that fails, these are tests that check the warning and not the error; with my modifications the label of the warning also changed, is what we want?

(I run make check-stage1, it ends with
test result: ok. 2494 passed; 0 failed; 3 ignored; 0 measured
and only if I scroll a lot up I found
test result: FAILED. 2523 passed; 5 failed; 13 ignored; 0 measured
is there a better way to see the summary of the result of the tests?)

**Comment by GuillaumeGomez** [comment]
Sure:

```bash
make check-stage1-cfail
```

**Comment by acrrd** [comment]
Thanks, that will help in avoiding to send PR with tests that do not pass.

What about the tests? I can modify them to the new format also for the warning or I can modify the code the keep the old behavior for the warning.

**Comment by GuillaumeGomez** [comment]
Just check what the command will return. It'll tell you what you need to update (and how).

**Comment by acrrd** [comment]
I have the fail also on master so I think my commit is ok

**Comment by GuillaumeGomez** [comment]
Seems good. Thanks!

@bors: r+ rollup

**Pull request merged**
