### PR TITLE
Bump libc dependency of std to 0.2.88.

### LINKED ISSUE #82400: Accepting Incoming TCP Connections fails on Android
Starting with Android Oreo (8), Android started using a seccomp based filter approach to syscalls, explicitly allowing syscalls, see https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html.
https://android.googlesource.com/platform/bionic.git/+/master/libc/SYSCALLS.TXT enumerates the allowed syscalls.
This means, that dispatching a generic syscall mechanism as introduced with this PR #78572 will result in a panic.

On top of that, I found that older versions of Android, such as Android 6, will return `Function not implemented (os error 38)` for this syscall.
**My tests showed that this only happens on x86, although I can't explain why.**

As there's no way to detect the target android API level, the safest way would probably be to always use the `accept` syscall, and remove the special handling of the `accept4` syscall. This could also be just guarded for x86 -- but would be happy to get an explanation on why it's only on that architecture (see https://github.com/tokio-rs/mio/pull/1446).

I have tested this with both real devices as well as Android emulators.

### Code

I tried this code:

```rust
use std::net::TcpListener;

let listener = TcpListener::bind("0.0.0.0:8080").unwrap();
match listener.accept() {
    Ok((_socket, addr)) => println!("new client: {:?}", addr),
    Err(e) => println!("couldn't get client: {:?}", e),
}
```

and poked it with `telnet <android_host> 8080`.

I expected to see this happen: `accept` returns `Ok(_)`

Instead, this happened:
* Android >= 8.0: panic because of seccomp
```
02-22 13:14:23.287  6015  6041 F my.app.DEBUG: Build fingerprint: 'Android/sdk_phone_x86/generic_x86:10/QPP6.190730.005.B1/5775370:userdebug/test-keys'
02-22 13:14:23.287  6015  6041 F my.app.DEBUG: Revision: '0'
02-22 13:14:23.287  6015  6041 F my.app.DEBUG: ABI: 'x86'
02-22 13:14:23.288  6015  6041 F my.app.DEBUG: Timestamp: 2021-02-22 13:14:23+0000
02-22 13:14:23.288  6015  6041 F my.app.DEBUG: pid: 6015, tid: 6057, name: tokio-runtime-w  >>> my.app:background_services <<<
02-22 13:14:23.288  6015  6041 F my.app.DEBUG: uid: 10103
02-22 13:14:23.288  6015  6041 F my.app.DEBUG: signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
02-22 13:14:23.288  6015  6041 F my.app.DEBUG: Cause: seccomp prevented call to disallowed x86 system call 364
02-22 13:14:23.289  6015  6041 F my.app.DEBUG: Abort message: 'Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP) in tid 4784 (tokio-runtime-w), pid 4735 (ground_services)'
02-22 13:14:23.289  6015  6041 F my.app.DEBUG: eax 0000016c  ebx 0000003f  ecx bfccfdb0  edx bfccfd6c
02-22 13:14:23.289  6015  6041 F my.app.DEBUG: edi eae65c34  esi 00080000
02-22 13:14:23.289  6015  6041 F my.app.DEBUG: ebp bfccfd88  esp bfccfd18  eip ee70cad9


```
* Android < 8.0: strace output
```
[pid 10918] syscall_364(0x34, 0x9d5c9cf8, 0x9d5c9ca0, 0x80800, 0x9fda9dc8, 0x9fda9dc8 <unfinished ...>
[pid 10918] <... syscall_364 resumed> ) = -1 (errno 38)
```
Which translate to _Function not implemented_.

### Version it worked on

It most recently worked on: Rust 1.48

### Version with regression

`rustc --version --verbose`:
```
 rustc --version --verbose
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0

```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by de-vri-es**
This PR bumps the `libc` dependency of `std` to 0.2.88. This will fix `TcpListener::accept` for Android on x86 platforms (https://github.com/rust-lang/libc/commit/31a2777d8f72db9eb3c3105f13afa94a47ca90d5).

This will really finally fix https://github.com/rust-lang/rust/issues/82400 for the main branch :)

r? @JohnTitor

### CODE REVIEW

**Comment by de-vri-es** [comment]
Hmm, the test failure seems unrelated:
```
 extracting /checkout/obj/build/cache/2021-01-28/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
    Updating crates.io index
error: failed to write /checkout/Cargo.lock
```

**Review by JohnTitor — APPROVED** [review]
You should also update Cargo.lock but otherwise LGTM (example commit: https://github.com/rust-lang/rust/pull/81455/commits/c3dedd0d816ae66be6c9971c9c3e2da122d4d3a4).

**Comment by de-vri-es** [comment]
> You should also update Cargo.lock but otherwise LGTM.

Right, forgot about that. Added it now.

**Comment by JohnTitor** [comment]
libc v0.2.88 is released, @de-vri-es we should use the new version here.

**Comment by de-vri-es** [comment]
Yep, definitely. Updated it now. Thanks for the quick libc release :]

**Pull request merged**
