### PR TITLE
[WIP] Stabilize `-Z pre-link-arg(s)` as `-C pre-link-arg(s)`

### PR DESCRIPTION
**Pull request by petrochenkov**
The option is the same as `-C link-arg(s)`, except that the arguments are inserted at the start of the linker option list, rather than at the end.

The feature was introduced in 2017 (https://github.com/rust-lang/rust/pull/41971) to facilitate discussion about passing linker arguments (https://github.com/rust-embedded/wg/pull/24). The conclusion seems to be "yep, `.cargo/config` with `rustc` flags in it is the way to go".

This PR also accompanies https://github.com/rust-lang/rust/pull/70501.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @japaric

**Comment by ehuss** [comment]
Would you mind also updating the documentation at https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/codegen-options/index.md?  It might be useful to clarify what it means by "prepend".  I presume it means "arguments added *before* the arguments generated by rustc"?  So the result is \[pre-link-args\] …generated args… \[link-args\] ?.

**Comment by nagisa** [comment]
Is there a tracking issue for this feature? I have no concerns re implementation, but I think it should still go through the usual process (such as the FCP?)

**Comment by Centril** [comment]
Are there docs for the flag? Would be good to add some user facing ones if not.

**Comment by petrochenkov** [comment]
There's no tracking issue and I'll add docs.

**Comment by petrochenkov** [comment]
>I'll add docs.

Ha-ha, looks like the option parsing for both stable `link-args` and unstable `pre-link-args` is terribly broken if multiple options are passed. Some of them are lost, some are reordered.
```
rustc -C link-arg="a" -C link-args="b c" -C link-args="d e" -C link-arg="f" mytest.rs
```
```
... "d" "e" "a" "f" ...
```
I'm not even surprised.

I'll fix this stuff before the stabilization.

**Comment by petrochenkov** [comment]
Closing for now.
Upon closer investigation it turned out it's a mess (as usual), and it's risky to stabilize as is.
I'll try to work on some cleanup and documentation and then perhaps resurrect this PR in some form.

**Comment by wmmc88** [comment]
@petrochenkov is there any plan to stabilize these features?

**Comment by petrochenkov** [comment]
@wmmc88 
No immediate plans for `-Z pre-link-arg`.

You may also be interested in https://github.com/rust-lang/rust/issues/99427 (`-l link-arg`) which has better chances at stabilization in the near future.

**Pull request closed without merging**
