### PR TITLE
checktools.sh: add link to issue for more context about disabled Miri tests

### PR DESCRIPTION
**Pull request by RalfJung**
Adds some context for the changes made in https://github.com/rust-lang/rust/pull/130072.

### CODE REVIEW

**Comment by jieyouxu** [comment]
Thanks
@bors r+ rollup

**Comment by RalfJung** [comment]
@bors r-

Turns out there's more to say here, https://github.com/rust-lang/rust/pull/130072 is more confusing than I thought.

**Comment by RalfJung** [comment]
Okay now it should be right.

r? @ChrisDenton

**Comment by ChrisDenton** [comment]
This seems right to me.

@bors r+

**Pull request merged**
