### PR TITLE
Extend rustc::middle::dataflow to allow filtering kills from flow-exits

### LINKED ISSUE #24267: break stmt confuses intialization-knowledge of borrow checker
This code should not compile:

demo code courtesy of niko's comment below.
```rust
struct Foo { n0: i32, n1: i32 }

fn leak_1_brk() -> Foo {
    let ret;
    loop {
        ret = Foo { n0: { break }, n1: 22 };
    }
    // (`ret` is still uninitialized here!)
    ret
}

fn main() { }
```

Original report:

I was making regression tests for #21486 and ran into this, though @nikomatsakis has pointed out that it is not specific to FRU.

Test case 1:
```rust
use std::sync::atomic::{Ordering, AtomicUsize, ATOMIC_USIZE_INIT};

#[derive(Debug)]
struct Noisy(u8);
impl Drop for Noisy {
    fn drop(&mut self) {
        // println!("splat #{}", self.0);
        event(self.0);
    }
}

#[allow(dead_code)]
#[derive(Debug)]
struct Foo { n0: Noisy, n1: Noisy }
impl Foo {
    fn vals(&self) -> (u8, u8) { (self.n0.0, self.n1.0) }
}

fn leak_1_brk() -> Foo {
    let _old_foo = Foo { n0: Noisy(1), n1: Noisy(2) };
    let ret;
    loop {
        ret = Foo { n0: { break }, .._old_foo };
    }
    // ret has not been initialized!!!!!
    ret
}

pub fn main() {
    reset_log();
    // Note: there's not much that's reasonable to expect here...
    let value = leak_1_brk().vals();
    assert_eq!(0x01_02, event_log());
    assert_eq!(value, (1,2));
}

static LOG: AtomicUsize = ATOMIC_USIZE_INIT;

fn reset_log() {
    LOG.store(0, Ordering::SeqCst);
}

fn event_log() -> usize {
    LOG.load(Ordering::SeqCst)
}

fn event(tag: u8) {
    let old_log = LOG.load(Ordering::SeqCst);
    let new_log = (old_log << 8) + tag as usize;
    LOG.store(new_log, Ordering::SeqCst);
}
```

Test case 2:
```rust
use std::sync::atomic::{Ordering, AtomicUsize, ATOMIC_USIZE_INIT};

#[derive(Debug)]
struct Noisy(u8);
impl Drop for Noisy {
    fn drop(&mut self) {
        // println!("splat #{}", self.0);
        event(self.0);
    }
}

#[allow(dead_code)]
#[derive(Debug)]
struct Foo { n0: Noisy, n1: Noisy }
impl Foo {
    fn vals(&self) -> (u8, u8) { (self.n0.0, self.n1.0) }
}

fn leak_1_brk() -> Foo {
    let _old_foo = Foo { n0: Noisy(1), n1: Noisy(2) };
    let ret;
    loop {
        ret = Foo { n0: { break }, n1: { break } };
    }
    // !!!!!
    ret
}


pub fn main() {
    reset_log();
    // Note: there's not much that's reasonable to expect here...
    assert_eq!(leak_1_brk().vals(), (1,2));
    assert_eq!(0x01_02, event_log());
}

static LOG: AtomicUsize = ATOMIC_USIZE_INIT;

fn reset_log() {
    LOG.store(0, Ordering::SeqCst);
}

fn event_log() -> usize {
    LOG.load(Ordering::SeqCst)
}

fn event(tag: u8) {
    let old_log = LOG.load(Ordering::SeqCst);
    let new_log = (old_log << 8) + tag as usize;
    LOG.store(new_log, Ordering::SeqCst);
}
```

### PR DESCRIPTION
**Pull request by pnkfelix**
Extend rustc::middle::dataflow to allow filtering kills from flow-exits.

Fix borrowck analysis so that it will not treat a break that pops through an assignment

``` rust
x = { ... break; ... }
```

as a kill of the "moved-out" bit for `x`.

Fix #24267.

[breaking-change], but really, its only breaking code that was already buggy.

### CODE REVIEW

**Comment by pnkfelix** [comment]
oh I still need to add a regression test; I will do that shortly.

**Comment by pnkfelix** [comment]
@nikomatsakis (also, I *am* a little worried about the inefficiency introduced by this filter.  I briefly searched for a more efficient encoding, but this was the easiest thing to put in quickly.  We can discuss more during the week.)

**Comment by pnkfelix** [comment]
(i have now confirmed that this does pass `make check`)

**Comment by pnkfelix** [comment]
(maybe I do indeed need to mark this as a `[breaking-change]`, with a clear stmt that its fixing a soundness bug?)

**Comment by nikomatsakis** [comment]
per our discussion, it would be nicer to distinguish "lexical" kills from "action" kills, and then only kill "lexical" kills when breaking out

**Comment by pnkfelix** [comment]
(this is ready for a re-review)

**Comment by nikomatsakis** [comment]
r+ modulo nits about dead code from before -- looks great!

**Comment by pnkfelix** [comment]
@alexcrichton any info or idea what was up with that failure?  Residual files on the bot from another PR or something?

**Comment by alexcrichton** [comment]
Perhaps, I'm not quite sure...

**Pull request merged**
