### PR TITLE
Switch bootstrap to 1.41

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This updates the version number for master to 1.42 and switches the bootstrap compiler to yesterday's beta. Fallout of cfg(bootstrap) changes is also dealt with.

### CODE REVIEW

**Comment by mark-i-m** [comment]
If I am not mistaken, it appears the tree was closed here: https://github.com/rust-lang/rust/pull/66932 and has been forgotten that way? Nothing appears to be running CI at the moment.

**Comment by Mark-Simulacrum** [comment]
@bors p=100

I thought we had a rollup going but I might've missed its end

**Pull request merged**
