### PR TITLE
fix: UWP compilation issue with `change_time` refactored type

### PR DESCRIPTION
**Pull request by juliusl**
Fixes a compilation issue related to #121478

### CODE REVIEW

**Comment by tgross35** [comment]
This looks consistent with what was changed at https://github.com/rust-lang/rust/pull/127712/files#diff-152c411d8aeb13ef688971e2d5f9dc38417e7de83a66270c9af4336a49c5acd6L404-R415, as reported at https://github.com/rust-lang/rust/pull/112328#issuecomment-2250373923.

r? @tgross35
@bors r+

**Comment by tgross35** [comment]
@mgroenhoff to be clear, you were only experiencing problems from https://github.com/rust-lang/rust/pull/112328 on UWP, correct?

**Comment by juliusl** [comment]
@tgross35 this doesn't seem related to my change but I'm seeing this when I run ./x check locally, 

```psh
PS D:\rs\rust> ./x check
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 2.52s
Checking stage0 library artifacts {alloc, core, panic_abort, panic_unwind, proc_macro, std, sysroot, test, unwind} (x86_64-pc-windows-msvc)
    Finished `release` profile [optimized] target(s) in 4.23s
Checking stage0 library test/bench/example targets (x86_64-pc-windows-msvc)
    Checking std v0.0.0 (D:\rs\rust\library\std)
error[E0432]: unresolved import `std::pipe`
 --> library\std\tests/pipe_subprocess.rs:6:34
  |
6 |         use std::{env, io::Read, pipe::pipe, process};
  |                                  ^^^^ could not find `pipe` in `std`

error[E0635]: unknown feature `anonymous_pipe`
 --> library\std\tests/pipe_subprocess.rs:1:12
  |
1 | #![feature(anonymous_pipe)]
  |            ^^^^^^^^^^^^^^

error[E0282]: type annotations needed
  --> library\std\tests/pipe_subprocess.rs:28:19
   |
28 |             (&rx).read_to_string(&mut s).unwrap();
   |                   ^^^^^^^^^^^^^^ cannot infer type

error: unused import: `io::Read`
 --> library\std\tests/pipe_subprocess.rs:6:24
  |
6 |         use std::{env, io::Read, pipe::pipe, process};
  |                        ^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unused_imports)]`

Some errors have detailed explanations: E0282, E0432, E0635.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `std` (test "pipe-subprocess") due to 4 previous errors
Build completed unsuccessfully in 0:01:34
PS D:\rs\rust>
```

Is this expected?

**Comment by tgross35** [comment]
Have you pulled and/or cleaned recently? `anonymous_pipe` was added only a few days ago, seems like something is just out of date.

**Comment by juliusl** [comment]
Yep I just pulled today, but it might be my env so I'll do a clean

**Comment by tgross35** [comment]
`std::pipe` should definitely have existed for at least a day since it's on nightly https://doc.rust-lang.org/nightly/std/pipe/index.html. Maybe that was from a rebase onto origin rather than upstream? Relevant commit is c9c8a14884c19e51a0eee54ccd98efa7f0f2bddd, if that shows up on your graph it should be there.

**Comment by ChrisDenton** [comment]
Note that UWP is not checked in CI and may be broken unless/until someone reports an issue.

**Comment by juliusl** [comment]
@tgross35 yeah it was my env. Even though I had the latest src for some reason I needed nuke everything and rebuild. But now `./x check` passes.

@ChrisDenton for future reference, do I need to pass any additional flags to `./x check` for `uwp` to compile? I'm assuming `x86_64-pc-windows-msvc` has the vendor set but wanted a sanity check.

**Comment by tgross35** [comment]
`rm -rf build/ target/ obj` is usually enough to ensure your local cache is completely gone (obj is only relevant if you're testing in the CI docker images locally). You should be able to pass `--target` to the `./x` commands to control the build/test target.

**Comment by juliusl** [comment]
Note for posterity, it would be something like --target x86_64-uwp-windows-msvc

**Comment by mgroenhoff** [comment]
@juliusl thanks for the quick fix!
@tgross35 yes I was indeed targeting uwp.

**Comment by juliusl** [comment]
@mgroenhoff btw, which uwp target were you using to compile?

**Comment by mgroenhoff** [comment]
@juliusl That would be `x86_64-uwp-windows-msvc`

**Pull request merged**
