### PR TITLE
E0248, E0267 & E0268 New Format

### PR DESCRIPTION
**Pull request by shyamsundarb-arch**

### CODE REVIEW

**Comment by shyaamsundhar** [comment]
@jonathandturner Hi. I tried a fresh commit. I am unable to merge to file changes into a single commit. Kindly let me know if this is ok!

**Comment by jonathandturner** [comment]
@shyaamsundhar - that's okay, it can be tricky getting used to the tools.

@bors r+ rollup

**Comment by shyaamsundhar** [comment]
@jonathandturner Hi, I am unable to understand this error. Can you help pls?

**Comment by jonathandturner** [comment]
Looks like the server that tests each build is having problems.  Looking into it...

**Comment by alexcrichton** [comment]
@bors: retry

* not sure why...

**Comment by jonathandturner** [comment]
@bors r-

Pulling it out of bors to give @shyaamsundhar time to do the fixes

**Comment by shyaamsundhar** [comment]
Have squashed into single commit in pull request #35586. So closing this pull request.

**Pull request closed without merging**
