### PR TITLE
Revert "Auto merge of #127537 - veluca93:struct_tf, r=BoxyUwU"

### PR DESCRIPTION
**Pull request by Kobzol**
This reverts https://github.com/rust-lang/rust/pull/127537 (commit acb4e8b6251f1d8da36f08e7a70fa23fc581839e), reversing changes made to 100fde5246bf56f22fb5cc85374dd841296fce0e.

Opening to see if this can help resolve the recent perf. results [instability](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Weird.20perf.20results).

### CODE REVIEW

**Comment by Kobzol** [comment]
We could do a bunch of perf. results, but the desired result (remov of instability) would be a bit hard to detect (we'd need to check if the results don't change much, but even the baseline results after reverting are quite large).

So I'd suggest reverting, then checking if it helped and then try to land again with some improvements.

**Comment by Kobzol** [comment]
r? lqd

@bors rollup=never

**Comment by lqd** [comment]
Ah I had also added this to https://github.com/rust-lang/rust/pull/129851 — but do we want to try just this revert and see what happens for a few merges, before trying with https://github.com/rust-lang/rust/pull/129714 if needed?

**Comment by lqd** [comment]
This one will at least fix a few regressions including bootstrap, while the collector behavior on the other was pretty weird and we may need to try both anyways.

@bors r+

**Comment by Kobzol** [comment]
I checked the collector logs of https://github.com/rust-lang/rust/pull/129714 and everything seemed to have happened correctly. So I think that it might just have been some database fluke. Let's try reverting just #127537 first, and see what happens. The other PR didn't seem *that* suspicious.

**Comment by Kobzol** [comment]
@bors p=10

All current perf. results seem really weird and misleading, which is confusing developers on merged PRs. We hope that by reverting this PR, it should be fixed, so ideally the revert should be merged ASAP.

**Pull request merged**
