### PR TITLE
[beta] branch 1.66

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This PR:

* Bumps version placeholders
* Bumps CI channel to beta
* Backports "rustdoc: add support for incoherent impls on structs and traits #103746"

### CODE REVIEW

**Comment by RalfJung** [comment]
```
thread 'main' panicked at 'could not read dir "D:\\a\\rust\\rust\\build\\tmp\\tarball\\rust\\i686-pc-windows-msvc\\miri-beta-i686-pc-windows-msvc\\miri-preview": Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', lib.rs:1578:25
```
@oli-obk any idea why it is even trying to build and package up Miri here? This is a beta branch build...
I guess on master this step must work since people get a Miri component on i686-msvc. Seems like on beta somehow we do skip the step of building Miri but we don't skip the step of creating a rustup component and of course that fails?

Btw, AFAIK on master we are not ever testing Miri on i686-msvc. Is the same true for Clippy? Is this building and shipping Clippy on a target that we haven't even tested it?

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/103802/commits/c2bb2e1e491e449a4404b3886e0ae7505de2531d is the commit which fixed the miri problems on beta. As the description there says my guess is we'll want to either forward-port (to master) that as-is or an alternative which starts *building* but not distributing miri on beta/stable.

**Pull request merged**
