### PR TITLE
Remove meaningless comments in src/test

### PR DESCRIPTION
**Pull request by sd234678**
Per @Centril's comment on #63347

### CODE REVIEW

**Comment by Centril** [comment]
Btw, did you run `--bless` on these?
It seems likely that some line numbers would have changed in the `.stderr` files now.

r=me rollup when green

**Comment by sd234678** [comment]
Think I might have made a mistake trying to rebase there. Would it be better for me to open a new branch from master and cherry-pick my commits onto that?

**Comment by Centril** [comment]
@sd234678 Yeah that will probably go faster. ^^

**Comment by sd234678** [comment]
Moved to #63487

**Pull request closed without merging**
