### PR TITLE
Prevent copies for unsized fn params

### LINKED ISSUE #111175: unsized_fn_params allows some unsized locals, hitting unsound alloca codegen path
Found in https://github.com/rust-lang/miri/issues/2872: this code
```rust
#![feature(core_intrinsics, unsized_fn_params)]
use std::intrinsics;

pub fn forget_unsized(t: [i32]) {
    intrinsics::forget(t)
}
```
with `-Zmir-opt-level=0` generates this LLVM IR
```
define void @_ZN4test14forget_unsized17h6fbb3409c8556ed4E(ptr %0, i64 %1) unnamed_addr #0 {
start:
  %_2 = alloca { ptr, i64 }, align 8
  %t = alloca { ptr, i64 }, align 8
  %2 = getelementptr inbounds { ptr, i64 }, ptr %t, i32 0, i32 0
  store ptr %0, ptr %2, align 8
  %3 = getelementptr inbounds { ptr, i64 }, ptr %t, i32 0, i32 1
  store i64 %1, ptr %3, align 8
  %4 = getelementptr inbounds { ptr, i64 }, ptr %t, i32 0, i32 0
  %5 = load ptr, ptr %4, align 8, !noundef !2
  %6 = getelementptr inbounds { ptr, i64 }, ptr %t, i32 0, i32 1
  %7 = load i64, ptr %6, align 8, !noundef !2
  %8 = mul nsw i64 %7, 4
  %9 = alloca i8, i64 %8, align 16
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %9, ptr align 1 %5, i64 %8, i1 false)
  %10 = getelementptr inbounds { ptr, i64 }, ptr %_2, i32 0, i32 0
  store ptr %9, ptr %10, align 8
  %11 = getelementptr inbounds { ptr, i64 }, ptr %_2, i32 0, i32 1
  store i64 %7, ptr %11, align 8
  ret void
}
```
Notice the `alloca`. This is bad! Our alloca code path is unsound (it does not properly account for alignment); the point of the `unsized_fn_params` feature gate (separate from `unsized_locals`) was to avoid hitting that code path.

I repeat my stance that we should remove the unsound alloca code path (effectively de-imlementing unsized locals) to ensure this can never happen.

We don't have a MIR ping group AFAIK, so Cc @rust-lang/wg-mir-opt I guess.

### PR DESCRIPTION
**Pull request by JakobDegen**
Fixes #111175 .

Regression test added too.

r? rust-lang/mir-opt or @RalfJung

### CODE REVIEW

**Comment by JakobDegen** [comment]
Hmm, I think the relevant example is this one:

```rust
#![feature(unsized_fn_params)]

fn uns(x: [i32], _: ()) {}

fn foo(mut x: [i32]) {
    uns(x, { x[0] = 1; () });
}
```

As far as I can tell there is no Mir that we can generate for `foo` that both correctly rejects that code in borrowck and doesn't have an unsized local.

I'm tempted that we should still merge this, with an appropriate test and comment added (will do that tomorrow). The feature is already unsound, and removing this bug is a pre-requisite to unimplementing unsized locals (which I do think we should do)

**Comment by RalfJung** [comment]
> The feature is already unsound

You mean `unsized_fn_params`? Having actual semantics-changing MIR transforms strikes me as a separate kind of unsoundness from codegen being wrong.

**Comment by JakobDegen** [comment]
> You mean unsized_fn_params? Having actual semantics-changing MIR transforms strikes me as a separate kind of unsoundness from codegen being wrong.

Yes. This isn't a Mir transform though - the "bug" in this PR is that the above example will incorrectly compile and `uns` will see the result of the mutation in the evaluation of the second param. That's a bug in Mir building though, and as I noted, fixing that bug either implies unsized locals or major refactors to Mir.

**Comment by JakobDegen** [comment]
@tmiasko I'll submit an MCP tomorrow for removing unsized locals from rustc completely (and will explain the motivation for that in there). Under the assumption that that's desirable, I feel quite strongly that we should not block that choice on this bug. The fact that unsized_fn_params cannot be implemented correctly in Mir without reliance on an extremely broken feature is unfortunate. Blocking the removal of the broken feature on that situation is imo not a reasonable response though.

**Comment by RalfJung** [comment]
> For the standard library, unsized locals aren't necessary except for the currently unstable forget_unsized

They aren't necessary at all, std only uses the `unsized_fn_params` feature, not `unsized_locals`.

The end goal is to have `unsized_fn_params` never generate an alloca. That was the goal of that feature gate from the start. It just turns out it failed to achieve that.

> Yes. This isn't a Mir transform though - the "bug" in this PR is that the above example will incorrectly compile and uns will see the result of the mutation in the evaluation of the second param. That's a bug in Mir building though, and as I noted, fixing that bug either implies unsized locals or major refactors to Mir.

That's a bug in MIR building after this PR, but done correctly (well, using unsized locals) before this PR?

**Comment by JakobDegen** [comment]
Yes, although I'd slightly object to the use of "correctly" and "unsized locals" in the same sentence :P

**Comment by RalfJung** [comment]
> As of now, the forget_unsized does actually use unsized locals, but it is the only thing to do so (I checked with borrowck modified to always reject unsized temporaries). With forget_unsized gone, you can remove unsized locals or fix the feature gate without introducing new evaluation order bugs.

So basically you are saying, `unsized_fn_params` should not accept the pattern of forwarding an unsized argument to another function? I guess that would be an option, but we'd have to crater it to evaluate whether other `unsized_fn_params` users need this.

Also removing `forget_unsized` is not an option. But we could replace the wrapper function by a re-export of the intrinsic. That would regress taking a fn ptr to it, but would probably be enough to do a crater run.

**Comment by JakobDegen** [comment]
I've updated the PR - it should now not regress any cases that previously did not require unsized locals to work

**Comment by JakobDegen** [comment]
@tmiasko that seems like a reasonable thing to want - is there a reason it has to happen as a part of this PR? I don't really interpret this PR as making anything worse than the status quo

**Comment by JakobDegen** [comment]
The motivation for this change is to unblock the removal of unsized locals. We could also just not land this and then remove unsized locals anyway, in which case this code will ICE. That's fine by me too, maybe it's preferable.

Mostly what I'm trying to avoid is us getting into a situation where we can't remove unsized locals until someone sits down and does the work of fixing this properly

**Comment by RalfJung** [comment]
> As I indicated earlier this isn't sufficient to avoid unsized locals, see for example https://github.com/rust-lang/rust/issues/111355.

That issue is closed, but https://github.com/rust-lang/rust/issues/111175 is still open. Do we need to revive this PR?

**Pull request closed without merging**
