### PR TITLE
Refactor away the prelude injection fold

### PR DESCRIPTION
**Pull request by jseyfried**
Instead, just inject `#[prelude_import] use [core|std]::prelude::v1::*;` at the crate root while injecting `extern crate [core|std];` and process `#[no_implicit_prelude]` attributes in `resolve`.

r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @petrochenkov @eddyb

**Comment by petrochenkov** [comment]
This prevents using prelude in the same crate it is defined in, right? Something similar to `#![local_prelude]` from https://github.com/rust-lang/rust/pull/32274. I wanted to use libcore's prelude in libcore and libstd's prelude in libstd after a snapshot.
I think, I'd still prefer `#[prelude_import]` to be an attribute on something mentioning the imported prelude module, like now, rather than on a whole crate.
I agree with the rest of the PR (the first commit breaks https://github.com/rust-lang/rust/pull/34095 though).

**Comment by jseyfried** [comment]
@petrochenkov 
> This prevents using prelude in the same crate it is defined in, right?

That isn't possible today (besides by using `#![feature(prelude_import)]` and manually adding `#[prelude_import] use local::prelude::*;` in each module, defeating the purpose of a prelude).

> Something similar to `#![local_prelude]` from #32274. I wanted to use libcore's prelude in libcore and libstd's prelude in libstd after a snapshot.

Agreed, I want this too. I'm envisioning
```rust
#![feature(local_prelude)]
#![local_prelude]

mod prelude {
    mod v1 { /* the libcore or libstd prelude */ }
}
```
or
```rust
#![feature(local_prelude)]

mod prelude {
    #[local_prelude]
    mod v1 { /* the libcore or libstd prelude */ }
}
```
Either would very simple to implement after this PR.

> I think, I'd still prefer `#[prelude_import]` to be an attribute on something mentioning the imported prelude module, like now, rather than on a whole crate.

If `#[prelude_import]` were intended for end users, I would agree. Since it is only for rustc-internal use, I don't think it matters.

> the first commit breaks #34095 though

Yeah, the rebase straightforward though -- I'll PR against your branch if this happens to land first.

**Comment by jseyfried** [comment]
@petrochenkov 
> This prevents using prelude in the same crate it is defined in, right?

That isn't possible today (besides by using `#![feature(prelude_import)]` and manually adding `#[prelude_import] use local::prelude::*;` in each module, defeating the purpose of a prelude).

> Something similar to `#![local_prelude]` from #32274. I wanted to use libcore's prelude in libcore and libstd's prelude in libstd after a snapshot.

Agreed, I want this too. I'm envisioning
```rust
#![feature(local_prelude)]

mod prelude {
    #[local_prelude]
    mod v1 { /* the libcore or libstd prelude */ }
}
```
or
```rust
#![feature(local_prelude)]
#![local_prelude]

mod prelude {
    mod v1 { /* the libcore or libstd prelude */ }
}
```
Either would very simple to implement after this PR.

> I think, I'd still prefer `#[prelude_import]` to be an attribute on something mentioning the imported prelude module, like now, rather than on a whole crate.

If `#[prelude_import]` were intended for end users, I would agree. Since it is only for rustc-internal use, I don't think it matters.

> the first commit breaks #34095 though

Yeah, the rebase straightforward though -- I'll PR against your branch if this happens to land first.

**Comment by jseyfried** [comment]
We could also just use the `prelude_import` feature instead of adding a new `local_prelude` feature if we don't want to expose this to the end user.

**Comment by petrochenkov** [comment]
>Either would very simple to implement after this PR.

Sure, I just expected custom and built-in, local and non-local preludes to work through the same mechanism without additional special attributes:
```
// Builtin non-local prelude from std
extern crate std; // <- injected automatically into the crate root
#[prelude_import] use std::prelude::v1::*; // <- injected automatically into the crate root

// Custom local prelude
#[prelude_import] use ::whatever::module::i::want; // <- written manually at the crate root, overwrites previous #[prelude_import] imports, module name is not hardcoded
```

>Since it is only for rustc-internal use, I don't think it matters.

I'll use this argument the next time I come up with some horrible hack :)

**Comment by petrochenkov** [comment]
Note, that with `#[prelude_import] use path::*;` `GlobImport::is_prelude` still can be refactored away, because prelude import is not really an import, only a marker, it can be ignored for all purposes except for supplying the prelude path.

**Comment by jseyfried** [comment]
@petrochenkov good points, I updated this PR accordingly (see the edited initial comment).

I think it's simpler to keep `GlobImport::is_prelude` -- we'll need access to the prelude when expanding macros during import resolution (c.f. [RFC 1560](https://github.com/rust-lang/rfcs/pull/1560)), and the prelude import might depend on other imports or not-yet-expanded modules, so we'll probably need to treat it like an ordinary import anyway.

**Pull request merged**
